WAVEWATCH III: CMakeLists.txt File Reference
CMakeLists.txt File Reference
Functions
file (STRINGS ${CMAKE_BINARY_DIR}/switch switch_strings) separate_arguments(switches UNIX_COMMAND $
set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib) set(CMAKE_LIBRARY_OUTPUT_DIRECTORY $
lib set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin) include($
cmake src_list cmake include (${CMAKE_CURRENT_SOURCE_DIR}/cmake/check_switches.cmake) check_switches("$
Function Documentation
file()
file (STRINGS ${CMAKE_BINARY_DIR}/switch switch_strings)
Definition at line 3 of file CMakeLists.txt.
               {CMAKE_BINARY_DIR}/switch switch_strings)
 separate_arguments(switches UNIX_COMMAND ${switch_strings})
Referenced by w3strkmd::combinesys(), pdlib_w3profsmd::ergout(), wmesmfmd::fieldindex(), mallocinfo_m::getvmrss(), mallocinfo_m::getvmsize(), gxoutf(), gxoutp(), w3ounfmetamd::init_meta(), w3sbs1md::insbs1(), w3snl4md::insnl4(), w3snl5md::insnl5(), w3tidemd::opnvuf(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3gkemd::prepkernelio(), read_grbtxt(), read_grbtxtws(), w3ounfmetamd::read_meta(), w3smcomd::read_smcint(), w3triamd::readmsh(), w3triamd::readmsh_iobp(), w3triamd::readmshobc(), yowpdlibmain::runparmetis(), scrip_iounitsmod::scrip_iounitsredirect(), wmesmfmd::setexport(), w3src4md::tabu_tauhf2(), w3tidemd::tide_read_anapar(), w3tidemd::tide_read_settings(), w3tidemd::tide_read_timeseries(), w3tidemd::tide_write_results(), w3strkmd::timetrackingv2(), w3uostmd::uost_srctrmcompute(), w3bounc(), w3bound(), w3crnc(), w3exgo(), w3exnc(), w3fldsmd::w3fldo(), w3grib(), w3gridmd::w3grid(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3mlti(), w3nmlbouncmd::w3nmlbounc(), w3nmlboundmd::w3nmlbound(), w3nmlgridmd::w3nmlgrid(), w3nmlmultimd::w3nmlmulticonf(), w3nmlmultimd::w3nmlmultidef(), w3nmlounfmd::w3nmlounf(), w3nmlounpmd::w3nmlounp(), w3nmlprncmd::w3nmlprnc(), w3nmlshelmd::w3nmlshel(), w3nmltrncmd::w3nmltrnc(), w3nmluprstrmd::w3nmluprstr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3sbs1(), w3shel(), w3snl5md::w3snl5(), w3srcemd::w3srce(), w3strt(), w3trck(), w3trnc(), w3uprstr(), w3wavemd::w3wave(), w3strkmd::wavetracking_nws_v2(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), pdlib_w3profsmd::write_var_to_text_file(), writematrix(), ww3_systrk(), and m_fileio::z_fileio().
include()
cmake src_list cmake include (${CMAKE_CURRENT_SOURCE_DIR}/cmake/check_switches.)
Definition at line 15 of file CMakeLists.txt.
          {CMAKE_CURRENT_SOURCE_DIR}/cmake/check_switches.cmake)
 check_switches("${switches}" switch_files)
Referenced by pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), w3oacpmd::cpl_oasis_grid(), pdlib_field_vec::do_output_exchanges(), w3servmd::extcde(), pdlib_w3profsmd::pdlib_init(), yowpdlibmain::real_mpi_barrier_pdlib(), pdlib_w3profsmd::scal_integral_print_general(), w3parall::synchronize_global_array(), w3parall::synchronize_ipgl_etc_array(), pdlib_w3profsmd::test_mpi_status(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3bounc(), w3bound(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3init(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3mlti(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3gsrumd::w3nnsp(), w3ounp(), w3prnc(), w3prtide(), w3sbs1(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3shel(), w3strt(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3strkmd::wavetracking_nws_v2(), wmwavemd::wmbcst(), wmfinlmd::wmfinl(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobf(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioef(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohf(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmwavemd::wmwave(), wmwavemd::wmwout(), pdlib_w3profsmd::write_var_to_text_file(), and ww3_systrk().
set() [1/2]
set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/ lib)
Definition at line 7 of file CMakeLists.txt.
                                     {CMAKE_BINARY_DIR}/lib)
 set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set() [2/2]
lib set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/ bin)
Definition at line 9 of file CMakeLists.txt.
                                     {CMAKE_BINARY_DIR}/bin)
 # Include list of src files to make file more readable
 # defines variables "ftn_src", "pdlib_src", "scrip_src", and "scripnc_src"
 include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/src_list.cmake)