WAVEWATCH III: gx_outp.F90 File Reference
gx_outp.F90 File Reference
Post-processing of point output for GrADS post-processing.
Functions/Subroutines
program gxoutp
Post-processing of point output for GrADS post-processing.
subroutine gxexpo
Perform actual point output.
Detailed Description
Post-processing of point output for GrADS post-processing.
Author
H. L. Tolman
J.H. Alves
F. Ardhuin
Date
27-Aug-2015
Definition in file gx_outp.F90.
Function/Subroutine Documentation
gxexpo()
subroutine gxoutp::gxexpo
Perform actual point output.
Author
H. L. Tolman
Date
16-Jul-2012
Definition at line 583 of file gx_outp.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         16-Jul-2012 |
     !/                  +-----------------------------------+
     !/
     !/    30-Jun-1999 : Final FORTRAN 77                    ( version 1.18 )
     !/    24-Jan-2000 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/                  Massive changes to logistics
     !/    25-Jan-2001 : Cartesian grid version              ( version 2.06 )
     !/    02-Feb-2001 : Xnl version 5                       ( version 2.07 )
     !/    01-Aug-2003 : Fix format for SH output points.    ( version 3.03 )
     !/    24-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/    23-Jun-2006 : Linear input added.                 ( version 3.09 )
     !/    03-Jul-2006 : Separate flux modules.              ( version 3.09 )
     !/    25-Jul-2006 : Grid ID for each point.             ( version 3.10 )
     !/    25-Apr-2007 : EMEAN in W3SPR2 par list.           ( version 3.11 )
     !/    09-Oct-2007 : WAM 4+ Sin and Sds added.           ( version 3.13 )
     !/                  (F. Ardhuin)
     !/    09-Oct-2007 : Experimental Sbs (BS1) added.       ( version 3.13 )
     !/                  (F. Ardhuin)
     !/    16-Jul-2012 : Move GMD (SNL3) and nonlinear filter (SNLS)
     !/                  from 3.15 (HLT).                    ( version 4.08 )
     !/    18-Aug-2018 : S_{ice} IC5 (Q. Liu)                ( version 6.06 )
     !/
     !  1. Purpose :
     !
     !     Perform actual point output.
     !
     !  3. Parameters :
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SPRn    Subr. W3SRCnMD Mean wave parameters for use in
     !                               source terms.
     !      W3FLXn    Subr. W3FLXnMD Flux/stress computation.
     !      W3SLNn    Subr. W3SLNnMD Linear input.
     !      W3SINn    Subr. W3SRCnMD Input source term.
     !      W3SDSn    Subr. W3SRCnMD Whitecapping source term
     !      W3SNLn    Subr. W3SNLnMD Nonlinear interactions.
     !      W3SBTn    Subr. W3SBTnMD Bottom friction source term.
     !      W3SDBn    Subr. W3SBTnMD Depth induced breaking source term.
     !      W3STRn    Subr. W3STRnMD Triad interaction source term.
     !      W3SBSn    Subr. W3SBSnMD Bottom scattering source term.
     !      W3SXXn    Subr. W3SXXnMD Unclassified source term.
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      STME21    Subr. W3TIMEMD Convert time to string.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Program in which it is contained.
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !     - Spectra are relative frequency energy spectra.
     !     - Note that arrays CX and CY of the main program now contain
     !       the absolute current speed and direction respectively.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S      Enable subroutine tracing.
     !       !/T      Enable test output.
     !
     !       !/FLXx   Flux/stress computation.
     !       !/LNx    Linear input package
     !       !/STx    Source term package
     !       !/NLx    Nonlinear interaction package
     !       !/BTx    Bottom friction package
     !       !/ICx    Ice source term package
     !       !/DBx    Depth-induced breaking package
     !       !/TRx    Triad interaction package
     !       !/BSx    Bottom scattering package
     !
     !       !/STAB2  Stability correction for !/ST2
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_FLX1
     USE w3flx1md
 #endif
 #ifdef W3_FLX2
     USE w3flx2md
 #endif
 #ifdef W3_FLX3
     USE w3flx3md
 #endif
 #ifdef W3_FLX4
     USE w3flx4md
 #endif
 #ifdef W3_FLX5
     USE w3flx5md
 #endif
 #ifdef W3_LN1
     USE w3sln1md
 #endif
 #ifdef W3_ST1
     USE w3src1md
 #endif
 #ifdef W3_ST2
     USE w3src2md
 #endif
 #ifdef W3_ST3
     USE w3src3md
 #endif
 #ifdef W3_ST4
     USE w3src4md, ONLY : w3spr4, w3sin4, w3sds4
 #endif
 #ifdef W3_ST6
     USE w3src6md
     USE w3swldmd, ONLY : w3swl6
     USE w3gdatmd, ONLY : swl6s6
 #endif
 #ifdef W3_NL1
     USE w3snl1md
 #endif
 #ifdef W3_NL2
     USE w3snl2md
 #endif
 #ifdef W3_NL3
     USE w3snl3md
 #endif
 #ifdef W3_NL4
     USE w3snl4md
 #endif
 #ifdef W3_NLS
     USE w3snlsmd
 #endif
 #ifdef W3_BT1
     USE w3sbt1md
 #endif
 #ifdef W3_BT4
     USE w3sbt4md
 #endif
 #ifdef W3_BT8
     USE w3sbt8md
 #endif
 #ifdef W3_IC1
     USE w3sic1md
 #endif
 #ifdef W3_IC2
     USE w3sic2md
 #endif
 #ifdef W3_IC3
     USE w3sic3md
 #endif
 #ifdef W3_IC4
     USE w3sic4md
 #endif
 #ifdef W3_IC5
     USE w3sic5md
 #endif
 #ifdef W3_DB1
     USE w3sdb1md
 #endif
 #ifdef W3_BS1
     USE w3sbs1md
 #endif
 #ifdef W3_IS2
     USE w3sis2md
 #endif
     !/
     USE w3dispmd, ONLY: liu_forward_dispersion, nar1d, dfac, n1max, &
          ecg1, ewn1, dsie
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: J, I1, I2, IK, ITH, ISPEC, IKM, IKL, &
          IKH, ITT, IX, IY, ISEA
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
     REAL                    :: XL, XH, XL2, XH2, DEPTH, SQRTH, UDIR,&
          UDIRR, UABS, CDIR, SIX, R1, R2, ET,  &
          EWN, ETR, ETX, ETY, EBND, EBX, EBY,  &
          HSIG, WLEN, TMEAN, THMEAN, THSPRD,   &
          EMAX, EL, EH, DENOM, FP, THP, SPP,   &
          FACTOR, CD, USTAR, FHIGH, ZWND, ICE, &
          USTD, Z0, CHARN, EMEAN, FMEAN, WNMEAN,&
          ICETHICK, ICECON, ICEF
 #ifdef W3_FLX5
     REAL                     ::TAUA, TAUADIR, RHOAIR
 #endif
 #ifdef W3_IS2
     REAL                   :: ICEDMAX
 #endif
 #ifdef W3_ST1
     REAL                    :: AMAX, FH1, FH2
 #endif
 #ifdef W3_ST2
     REAL                    :: AMAX, ALPHA(NK), FPI
 #endif
 #ifdef W3_ST3
     REAL                    :: FMEANS, FMEANWS, TAUWX, TAUWY, AMAX, &
          TAUWNX, TAUWNY
 #endif
 #ifdef W3_ST4
     REAL                    :: FMEANWS, TAUWX, TAUWY, AMAX, &
          TAUWNX, TAUWNY,  FMEAN1, WHITECAP(1:4), DLWMEAN
 #endif
 #ifdef W3_ST6
     REAL                    :: AMAX, TAUWX, TAUWY, TAUWNX, TAUWNY
 #endif
 #ifdef W3_BS1
     REAL                    :: TAUSCX, TAUSCY
 #endif
 #ifdef W3_BT3
     REAL                    :: D50
 #endif
 #ifdef W3_BT4
     REAL                    :: D50, PSIC, BEDFORM(3), TAUBBL(2)
 #endif
 #ifdef W3_STAB2
     REAL                    :: STAB0, STAB, THARG1, THARG2, COR1,   &
          COR2, ASFAC
 #endif
     REAL                    :: HSMIN = 0.05
     REAL                    :: WN(NK), CG(NK), E(NK,NTH), E1(NK),   &
          APM(NK), THBND(NK), SPBND(NK),       &
          A(NTH,NK), WN2(NTH,NK),WN_R(NK),     &
          ALPHA_LIU(NK), CG_ICE(NK), R(NK)
     REAL                    :: DIA(NTH,NK), SWI(NK,NTH), SNL(NK,NTH),&
          SDS(NK,NTH), SBT(NK,NTH), SIS(NK,NTH),&
          STT(NK,NTH), DIA2(NK,NTH)
     REAL                    :: XLN(NTH,NK), XWI(NTH,NK), XNL(NTH,NK),&
          XTR(NTH,NK), XDS(NTH,NK), XDB(NTH,NK),&
          XBT(NTH,NK), XBS(NTH,NK), XXX(NTH,NK),&
          XWL(NTH,NK), XIS(NTH,NK)
     LOGICAL                 :: LBREAK
 #ifdef W3_ST3
     LOGICAL                :: LLWS(NTH,NK)
 #endif
 #ifdef W3_ST4
     LOGICAL                :: LLWS(NTH,NK)
     REAL                   :: LAMBDA(NSPEC)
 #endif
     CHARACTER               :: DTME21*23
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GXEXPO')
 #endif
     !
     xl     = 1./xfr - 1.
     xh     =  xfr - 1.
     xl2    = xl**2
     xh2    = xh**2
     ice = 0.
     !
     xln = 0.
     xwi = 0.
     xnl = 0.
     xtr = 0.
     xds = 0.
     xdb = 0.
     xbt = 0.
     xbs = 0.
     xwl = 0.
     xis = 0.
     xxx = 0.
     !
 #ifdef W3_T
     WRITE (ndst,9000) (flreq(j),j=1,nopts)
     WRITE (ndst,9001) flsrce
 #endif
     !
     !     Output of time
     !
     CALL stme21 ( time , dtme21 )
     WRITE (ndso,905) dtme21
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     !     Loop over output points.
     !
     DO j=1, nopts
       IF ( flreq(j) ) THEN
         !
 #ifdef W3_T
         WRITE (ndst,9002) ptnme(j)
 #endif
         !
         ! 2. Calculate grid parameters using and inlined version of WAVNU1.
         !
         depth  = max( dmin, dpo(j) )
         sqrth  = sqrt( depth )
         udir   = mod( 270. - wdo(j)*rade , 360. )
         udirr  = wdo(j)
         uabs   = max( 0.001 , wao(j) )
 #ifdef W3_FLX5
         taua     = max( 0.001 , tauao(j))
         tauadir  = mod( 270. - taudo(j)*rade , 360. )
         rhoair   = max( 0. , dairo(j))
 #endif
         cdir   = mod( 270. - cdo(j)*rade , 360. )
 #ifdef W3_IS2
         icedmax = max( 0., icefo(j))
 #endif
 #ifdef W3_IC2
         icef     = 0.
 #endif
 #ifdef W3_IS2
         icef     = icedmax
 #endif
         icethick = max(0., iceho(j))
         icecon = max(0., iceo(j))
         !
 #ifdef W3_STAB2
         stab0  = zwind * grav / 273.
         stab   = stab0 * aso(j) / max(5.,wao(j))**2
         stab   = max( -1. , min( 1. , stab ) )
         tharg1 = max( 0. , ffng*(stab-ofstab))
         tharg2 = max( 0. , ffps*(stab-ofstab))
         cor1   = ccng * tanh(tharg1)
         cor2   = ccps * tanh(tharg2)
         asfac  = sqrt( (1.+cor1+cor2)/shstab )
 #endif
         !
 #ifdef W3_T
         WRITE (ndst,9010) depth
 #endif
         DO ik=1, nk
           six    = sig(ik) * sqrth
           i1     = int(six/dsie)
           IF (i1.LE.n1max) THEN
             i2 = i1 + 1
             r1 = six/dsie - real(i1)
             r2 = 1. - r1
             wn(ik) = ( r2*ewn1(i1) + r1*ewn1(i2) ) / depth
             cg(ik) = ( r2*ecg1(i1) + r1*ecg1(i2) ) * sqrth
           ELSE
             wn(ik) = sig(ik)*sig(ik)/grav
             cg(ik) = 0.5 * grav / sig(ik)
           END IF
 #ifdef W3_T
           WRITE (ndst,9011) ik, tpi/sig(ik), wn(ik), cg(ik)
 #endif
           !
         END DO
         IF (iicedisp) THEN
           CALL liu_forward_dispersion  (icethick,0.,depth, &
                sig,wn_r,cg_ice,alpha_liu)
         ELSE
           wn_r=wn
           cg_ice=cg
         END IF
         r(:)=1 ! In case IC2 is defined but not IS2
         !
         ! 3.  Prepare spectra etc.
         ! 3.a Mean wave parameters.
         !
         et     = 0.
         ewn    = 0.
         etr    = 0.
         etx    = 0.
         ety    = 0.
         DO ik=1, nk
           ebnd   = 0.
           ebx    = 0.
           eby    = 0.
           DO ith=1, nth
             ispec  = ith + (ik-1)*nth
             e(ik,ith) = spco(ispec,j)
             ebnd   = ebnd + spco(ispec,j)
             ebx    = ebx  + spco(ispec,j)*ecos(ith)
             eby    = eby  + spco(ispec,j)*esin(ith)
           END DO
           e1(ik) = ebnd * dth
           apm(ik)= e1(ik) / ( tpi * grav**2 / sig(ik)**5  )
           IF ( e1(ik) .GT. 1.e-5) THEN
             thbnd(ik) = mod(630.- rade*atan2(eby,ebx),360.)
             spbnd(ik) = rade * sqrt( max( 0. , 2.*( 1. -      &
                  sqrt( max(0.,(ebx**2+eby**2)/ebnd**2) ) ) ) )
           ELSE
             thbnd(ik) = -999.9
             spbnd(ik) = -999.9
           END IF
           ebnd   = e1(ik) * dsii(ik) * tpiinv
           et     = et  + ebnd
           ewn    = ewn + ebnd / wn(ik)
           etr    = etr + ebnd / sig(ik)
           etx    = etx + ebx * dsii(ik)
           ety    = ety + eby * dsii(ik)
         END DO
         !
         ! tail factors for radian action etc ...!
         !
         ebnd   = e1(nk) * tpiinv / ( sig(nk) * dth )
         et     = et  + fte *ebnd
         ewn    = ewn + ftwl*ebnd
         etr    = etr + fttr*ebnd
         etx    = dth*etx*tpiinv + fte*ebx*tpiinv/sig(nk)
         ety    = dth*ety*tpiinv + fte*eby*tpiinv/sig(nk)
         !
         hsig   = 4. * sqrt( et )
         IF ( hsig .GT. hsmin ) THEN
           wlen   = ewn / et * tpi
           tmean  = etr / et * tpi
           thmean = mod( 630. - rade*atan2(ety,etx) , 360. )
           thsprd = rade * sqrt( max( 0. , 2.*( 1. - sqrt(     &
                max(0.,(etx**2+ety**2)/et**2) ) ) ) )
         ELSE
           wlen   = 0.
           tmean  = 0.
           thmean = 0.
           thsprd = 0.
           DO ik=1, nk
             e1(ik) = 0.
             DO ith=1, nth
               e(ik,ith) = 0.
             END DO
           END DO
         END IF
         !
         ! peak frequency
         !
         emax   = e1(nk)
         ikm    = nk
         !
         DO ik=nk-1, 1, -1
           IF ( e1(ik) .GT. emax ) THEN
             emax   = e1(ik)
             ikm    = ik
           END IF
         END DO
         !
         ikl    = max(  1 , ikm-1 )
         ikh    = min( nk , ikm+1 )
         el     = e1(ikl) - e1(ikm)
         eh     = e1(ikh) - e1(ikm)
         denom  = xl*eh - xh*el
         !
         IF ( hsig .GE. hsmin ) THEN
           fp     = sig(ikm) * ( 1. + 0.5 * ( xl2*eh - xh2*el )  &
                / sign( max(abs(denom),1.e-15) , denom ) )
           thp    = thbnd(ikm)
           spp    = spbnd(ikm)
         ELSE
           fp     = 0.
           thp    = 0.
           spp    = 0.
         END IF
         !
         ! 3.4 source terms
         !
         DO ik=1, nk
           factor = tpiinv * cg(ik) / sig(ik)
           DO ith=1, nth
             ispec  = ith + (ik-1)*nth
             a(ith,ik)   = factor * spco(ispec,j)
             wn2(ith,ik) = wn(ik)
           END DO
         END DO
         !
 #ifdef W3_STAB2
         uabs   = uabs / asfac
 #endif
         !
 #ifdef W3_ST0
         zwnd   = 10.
 #endif
 #ifdef W3_ST1
         zwnd   = 10.
 #endif
 #ifdef W3_ST2
         zwnd   = zwind
 #endif
 #ifdef W3_ST3
         zwnd   = zzwnd
         tauwx  = 0.
         tauwy  = 0.
         llws(:,:)  = .true.
 #endif
         ustar  = 1.
 #ifdef W3_ST4
         zwnd   = zzwnd
         tauwx  = 0.
         tauwy  = 0.
 #endif
 #ifdef W3_ST6
         zwnd   = 10.
 #endif
         !
 #ifdef W3_ST0
         fhigh  = sig(nk)
 #endif
 #ifdef W3_ST1
         CALL w3spr1 (a, cg, wn, emean, fmean, wnmean, amax)
         fp     = 0.85 * fmean
         fh1    = fxfm * fmean
         fh2    = fxpm / ustar
         fhigh  = max( fh1 , fh2 )
 #endif
 #ifdef W3_ST2
         CALL w3spr2 (a, cg, wn, depth, fp , uabs, ustar,     &
              emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
         CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,        &
              wnmean, amax, uabs, udirr, ustar, ustd, &
              tauwx, tauwy, cd, z0, charn, llws, fmeanws)
 #endif
 #ifdef W3_ST4
         CALL w3spr4 (a, cg, wn, emean, fmean,  fmean1,      &
              wnmean, amax, uabs, udirr,             &
 #ifdef W3_FLX5
              taua, tauadir, rhoair,           &
 #endif
              ustar, ustd, tauwx, tauwy, cd, z0,     &
              charn, llws, fmeanws, dlwmean )
 #endif
 #ifdef W3_ST6
         CALL w3spr6 (a, cg, wn, emean, fmean, wnmean, amax, fp)
 #endif
         !
 #ifdef W3_FLX1
         CALL w3flx1 ( zwnd, uabs, udirr,                     &
              ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX2
         CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,          &
              ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
         CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,          &
              ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX4
         CALL w3flx4 ( zwnd, uabs, udirr, ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX5
         CALL w3flx5 ( zwnd, uabs, udirr, taua, tauadir,  &
              rhoair, ustar, ustd, z0, cd, charn )
 #endif
         !
         DO itt=1, 3
 #ifdef W3_ST2
           CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,      &
                fpi, xwi, dia )
           CALL w3spr2 (a, cg, wn, depth, fpi, uabs, ustar,   &
                emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
           CALL w3sin3 (a, cg, wn2, uabs, ustar, dair/dwat,   &
                aso(j), udirr, z0, cd, tauwx, tauwy,  &
                tauwnx, tauwny,                       &
                ice, xwi, dia, llws, ix, iy )
           CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,        &
                wnmean, amax, uabs, udirr, ustar, ustd, &
                tauwx, tauwy, cd, z0, charn, llws, fmeanws)
 #endif
 #ifdef W3_ST4
           CALL w3sin4 (a, cg, wn2, uabs, ustar, dair/dwat,   &
                aso(j), udirr, z0, cd, tauwx, tauwy,  &
                tauwnx, tauwny, xwi, dia, llws, ix, iy, lambda )
           CALL w3spr4 (a, cg, wn, emean, fmean,  fmean1,      &
                wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                taua, tauadir, rhoair,             &
 #endif
                ustar, ustd, tauwx, tauwy, cd, z0,       &
                charn, llws, fmeanws, dlwmean )
 #endif
 #ifdef W3_FLX2
           CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,        &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
           CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,        &
                ustar, ustd, z0, cd )
 #endif
         END DO
         !
 #ifdef W3_ST2
         fhigh  = xfc * fpi
 #endif
         !
         IF ( flsrce(2) ) THEN
 #ifdef W3_LN1
           CALL w3sln1 ( wn, fhigh, ustar, udirr, xln )
 #endif
           !
 #ifdef W3_ST1
           CALL w3sin1 (a, wn2, ustar, udirr,      xwi, dia )
 #endif
 #ifdef W3_ST2
           CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,    &
                fpi, xwi, dia )
 #endif
 #ifdef W3_ST3
           CALL w3sin3 (a, cg, wn2, uabs, ustar, dair/dwat, &
                aso(j), udirr, z0, cd,              &
                tauwx, tauwy, tauwnx, tauwny,       &
                ice, xwi, dia, llws, ix, iy )
 #endif
 #ifdef W3_ST4
           CALL w3sin4 (a, cg, wn2, uabs, ustar, dair/dwat, &
                aso(j), udirr, z0, cd,              &
                tauwx, tauwy, tauwnx, tauwny,       &
                xwi, dia,  llws, ix, iy, lambda )
 #endif
 #ifdef W3_ST6
           CALL w3sin6 (a, cg, wn2, uabs, ustar, udirr, cd, &
                dair, tauwx, tauwy, tauwnx, tauwny, xwi, dia )
 #endif
         END IF
         IF ( flsrce(3) ) THEN
 #ifdef W3_NL1
           CALL w3snl1 ( a, cg, wnmean*depth,      xnl, dia )
 #endif
 #ifdef W3_NL2
           CALL w3snl2 ( a, cg, depth,             xnl, dia )
 #endif
 #ifdef W3_NL3
           CALL w3snl3 ( a, cg, wn, depth,         xnl, dia )
 #endif
 #ifdef W3_NL4
           CALL w3snl4 ( a, cg, wn, depth,         xnl, dia )
 #endif
         END IF
         IF ( flsrce(4) ) THEN
 #ifdef W3_ST1
           CALL w3sds1 ( a, wn2, emean, fmean, wnmean, xds, dia )
 #endif
 #ifdef W3_ST2
           CALL w3sds2 ( a, cg, wn, fpi, ustar, alpha, xds, dia )
 #endif
 #ifdef W3_ST3
           CALL w3sds3 ( a, wn, cg, emean, fmeans, wnmean,         &
                ustar, ustd, depth, xds, dia, ix, iy )
 #endif
 #ifdef W3_ST4
           CALL w3sds4 ( a, wn, cg,          &
                ustar, ustd, depth, dair, xds, dia, ix, iy, lambda, whitecap , dlwmean)
 #endif
 #ifdef W3_ST6
           CALL w3sds6 ( a, cg, wn,            xds, dia )
           IF (swl6s6) CALL w3swl6 ( a, cg, wn,  xwl, dia )
 #endif
           !
 #ifdef W3_DB1
           CALL w3sdb1 ( j, a, depth, emean, fmean, wnmean, cg, &
                lbreak, xdb, dia )
 #endif
           !
         END IF
         IF ( flsrce(5) ) THEN
 #ifdef W3_BT1
           CALL w3sbt1 ( a, cg, wn, depth,   xbt, dia )
 #endif
 #ifdef W3_IC1
           CALL w3sic1 ( a, depth, cg,      ix, iy, xbt, dia )
 #endif
 #ifdef W3_IC2
           CALL w3sic2 ( a, depth, icethick, icef ,cg,  wn, ix, iy, xbt, dia, wn_r, &
                cg_ice, alpha_liu, r )
 #endif
 #ifdef W3_IC3
           CALL w3sic3 ( a, depth, cg,  wn, ix, iy, xbt, dia )
 #endif
 #ifdef W3_IC4
           CALL w3sic4 ( a, depth, cg,      ix, iy, xbt, dia )
 #endif
 #ifdef W3_IC5
           CALL w3sic5 ( a, depth, cg,  wn, ix, iy, xbt, dia )
 #endif
 #ifdef W3_BT4
           ix=1    ! to be fixed later
           iy=1    ! to be fixed later
           isea=1  ! to be fixed later
           d50 = sed_d50(isea)
           psic= sed_psic(isea)
 #endif
 #ifdef W3_BT4
           CALL w3sbt4 ( a, cg, wn, depth, d50, psic, taubbl,   &
                bedform, xbt, dia, ix, iy )
 #endif
           !
 #ifdef W3_BT8
           CALL w3sbt8 ( a, depth, xbt, dia, ix, iy )
 #endif
 #ifdef W3_BS1
           CALL w3sbs1 ( a, cg, wn, depth, cao(j)*cos(cdo(j)), &
                cao(j)*sin(cdo(j)),     &
                tauscx, tauscy, xbs, dia )
 #endif
         END IF
         IF ( flsrce(6) ) THEN
 #ifdef W3_IS2
           CALL w3sis2(a, depth, icecon, icethick, icef, icedmax, ix, iy, &
                xis, dia, dia2, wn, cg, wn_r, cg_ice, r)
 #endif
         END IF
         !
 #ifdef W3_STAB2
         uabs   = uabs * asfac
 #endif
         !
         DO ik=1, nk
           factor = tpi / cg(ik) * sig(ik)
           DO ith=1, nth
             ispec       = ith + (ik-1)*nth
             e(ik,ith) = spco(ispec,j)
             swi(ik,ith) = ( xwi(ith,ik) + xln(ith,ik) ) * factor
             snl(ik,ith) = ( xnl(ith,ik) + xtr(ith,ik) ) * factor
             sds(ik,ith) = ( xds(ith,ik) + xdb(ith,ik) ) * factor
 #ifdef W3_ST6
             sds(ik,ith) =   sds(ik,ith) +(xwl(ith,ik)   * factor)
 #endif
             sbt(ik,ith) = ( xbt(ith,ik) + xbs(ith,ik) ) * factor
             sis(ik,ith) = xis(ith,ik) * factor
             stt(ik,ith) = xxx(ith,ik) * factor
           END DO
         END DO
         stt    = stt + swi + snl + sds + sbt + sis
         !
         ! 4.a Perform output
         !
         IF ( flsrce(1) ) WRITE (ndsgrd)                           &
              ((e(ik,ith),ith=1,nth),ik=nk,1,-1)
         IF ( flsrce(2) ) WRITE (ndsgrd)                           &
              ((swi(ik,ith),ith=1,nth),ik=nk,1,-1)
         IF ( flsrce(3) ) WRITE (ndsgrd)                           &
              ((snl(ik,ith),ith=1,nth),ik=nk,1,-1)
         IF ( flsrce(4) ) WRITE (ndsgrd)                           &
              ((sds(ik,ith),ith=1,nth),ik=nk,1,-1)
         IF ( flsrce(5) ) WRITE (ndsgrd)                           &
              ((sbt(ik,ith),ith=1,nth),ik=nk,1,-1)
         IF ( flsrce(6) ) WRITE (ndsgrd)                           &
              ((sis(ik,ith),ith=1,nth),ik=nk,1,-1)
         IF ( flsrce(7) ) WRITE (ndsgrd)                           &
              ((stt(ik,ith),ith=1,nth),ik=nk,1,-1)
         !
         IF ( flagll ) THEN
           WRITE (ndspnt,940) ptnme(j),                          &
                fact*ptloc(1,j), fact*ptloc(2,j), dpo(j), wao(j),  &
                wao(j)*cos(wdo(j)), wao(j)*sin(wdo(j)), aso(j),    &
                cao(j), cao(j)*cos(cdo(j)), cao(j)*sin(cdo(j)),    &
                hsig, grdid(j)
         ELSE
           WRITE (ndspnt,941) ptnme(j),                          &
                fact*ptloc(1,j), fact*ptloc(2,j), dpo(j), wao(j),  &
                wao(j)*cos(wdo(j)), wao(j)*sin(wdo(j)), aso(j),    &
                cao(j), cao(j)*cos(cdo(j)), cao(j)*sin(cdo(j)),    &
                hsig, grdid(j)
         END IF
         !
         ! ... End of points loop
         !
       END IF
     END DO
     !
     RETURN
     !
     ! Formats
     !
 905 FORMAT (9x,a)
 940 FORMAT (a10,1x,2f6.1,f7.1,3f7.1,f8.2,3f7.2,f6.2,2x,a)
 941 FORMAT (a10,1x,2f8.1,f7.1,3f7.1,f8.2,3f7.2,f6.2,2x,a)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST GXEXPO : FLAGS  :',40l2)
 9001 FORMAT (' TEST GXEXPO : FLSRCE :',6l2)
 9002 FORMAT (' TEST GXEXPO : OUTPUT POINT : ',a)
 9010 FORMAT (' TEST GXEXPO : DEPTH =',f7.1,'  IK, T, K, CG :')
 9011 FORMAT ('               ',i3,f8.2,f8.4,f8.2)
 #endif
     !/
     !/ End of GXEXPO ----------------------------------------------------- /
     !/
References w3dispmd::dfac, w3dispmd::dsie, w3dispmd::ecg1, w3dispmd::ewn1, w3dispmd::liu_forward_dispersion(), w3dispmd::n1max, w3dispmd::nar1d, w3gdatmd::swl6s6, w3flx1md::w3flx1(), w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3flx4md::w3flx4(), w3flx5md::w3flx5(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sbt8md::w3sbt8(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), and w3swldmd::w3swl6().
Referenced by gxoutp().
gxoutp()
program gxoutp
Post-processing of point output for GrADS post-processing.
Author
H. L. Tolman
J.H. Alves
F. Ardhuin
Date
27-Aug-2015
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Definition at line 25 of file gx_outp.F90.
References w3odatmd::aso, w3odatmd::dpo, w3timemd::dsec21(), w3servmd::extcde(), file(), w3odatmd::fnmpre, w3odatmd::grdid, gxexpo(), w3servmd::itrace(), w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3odatmd::nopts, w3odatmd::ptloc, w3odatmd::ptnme, w3timemd::stme21(), w3servmd::strace(), w3timemd::tick21(), w3wdatmd::time, w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3odatmd::wao, and w3odatmd::wdo.