WAVEWATCH III: gx_outf.F90 File Reference
gx_outf.F90 File Reference
Generate GrADS input files from raw WAVEWATCH data file.
Functions/Subroutines
program gxoutf
Generate GrADS input files from raw WAVEWATCH data file.
subroutine gxexgo (NX, NY, NSEA)
Perform actual output for GrADS postprocessing.
Detailed Description
Generate GrADS input files from raw WAVEWATCH data file.
Author
H. L. Tolman
A. Chawla
J.H.G.M. Alves
Date
22-Mar-2021
Definition in file gx_outf.F90.
Function/Subroutine Documentation
gxexgo()
subroutine gxoutf::gxexgo (integer, intent(in) NX, integer, intent(in) NY, integer, intent(in) NSEA)
Perform actual output for GrADS postprocessing.
Parameters
[in] NX Grid dimensions.
[in] NY Grid dimensions.
[in] NSEA Number of sea points.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 786 of file gx_outf.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    30-Jun-1999 : Final FORTRAN 77                    ( version 1.18 )
     !/    24-Jan-2000 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/                  Massive changes to logistics.
     !/    29-Jan-2001 : Add output fields 17-18             ( version 2.20 )
     !/    24-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/    27-Jun-2005 : Adding MAPST2.                      ( version 3.07 )
     !/    21-Jul-2005 : Add output fields 19-21.            ( version 3.07 )
     !/    05-Jul-2006 : Consolidate stress arrays.          ( version 3.09 )
     !/    18-Jan-2007 : Update MSOUT/MBOUT treatment.       ( version 3.10 )
     !/    28-Mar-2007 : Adding partitioned output.          ( version 3.11 )
     !/                  Adding user slots for outputs.
     !/    22-Mar-2021 : Add output fields RHOA and TAUA     ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Perform actual output for GrADS postprocessing.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NX/Y    Int.  I  Grid dimensions.
     !       NSEA    Int.  I  Number of sea points.
     !     ----------------------------------------------------------------
     !
     !     Internal parameters
     !     ----------------------------------------------------------------
     !       X1, X2, XX
     !               R.A.  Output fields
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      EXTCDE    Subr.   Id.    Abort program as graceful as possible.
     !      W3S2XY    Subr.   Id.    Convert from storage to spatial grid.
     !     ---------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Main program in which it is contained.
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !     - Note that arrays CX and CY of the main program now contain
     !       the absolute current speed and direction respectively.
     !     - VALLND added to assure that map with only land plots in
     !       GrADS.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !     !/T  Enable test output.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: w3s2xy
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NX, NY, NSEA
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IX, IY, J, ISEA, IXL, IXR
     INTEGER                 :: MAPXCL(NY,NX), MAPDRY(NY,NX),        &
          MAPICE(NY,NX), MAPLND(NY,NX),        &
          MAPMSK(NY,NX)
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
     REAL                    :: X1(NX,NY), XX(NX,NY), XY(NX,NY),     &
          XA(NX,NY,0:NOSWLL)
     REAL                    :: VALLND = 0.001
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GXEXGO')
 #endif
     !
 #ifdef W3_T
     WRITE (ndst,9000) ((flreq(j,k),j=1,nogrp), k=1,ngrpp)
 #endif
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     ! 1.  Preparations
     ! 1.a Write map to file
     !
     mapxcl = mod(mapst2,2)
     mapice = mod(mapst2,2)
     mapdry = mod(mapst2/2,2)
     maplnd = mod(mapst2/4,2)
     mapmsk = mod(mapst2/8,2)
     !
     DO iy=1, ny
       DO ix=1, nx
         IF ( mapsta(iy,ix).EQ.0 ) THEN
           IF ( mapxcl(iy,ix).EQ.1 ) THEN
             x1(ix,iy) = undef
           ELSE
             x1(ix,iy) = vallnd
           END IF
         ELSE IF ( mapsta(iy,ix).LT.0 ) THEN
           IF ( mapmsk(iy,ix).EQ.1 ) THEN
             x1(ix,iy) = -4.
           ELSE IF ( maplnd(iy,ix).EQ.1 ) THEN
             x1(ix,iy) = vallnd
           ELSE IF ( mapice(iy,ix).EQ.1 .AND.                    &
                mapdry(iy,ix).EQ.1 ) THEN
             x1(ix,iy) = -3.
           ELSE IF ( mapdry(iy,ix).EQ.1 ) THEN
             x1(ix,iy) = -2.
           ELSE IF ( mapice(iy,ix).EQ.1 ) THEN
             x1(ix,iy) = -1.
           ELSE
             x1(ix,iy) = -5.
           END IF
         ELSE
           x1(ix,iy) = real(mapsta(iy,ix))
           IF ( msout ) THEN
             IF ( mapsta(iy,ix) .GT. 0 ) x1(ix,iy) = undef
           ELSE IF ( mbout ) THEN
             IF ( mapsta(iy,ix).EQ.2  .OR.                      &
                  iy.EQ.1 .OR. iy.EQ.ny .OR.                    &
                  ( iclose.NE.iclo_none .AND.                   &
                  (ix.EQ.1 .OR. ix.EQ.nx) ) ) THEN
               x1(ix,iy) = undef
             ELSE
               ixl    = 1 + mod(ix+nx-2,nx)
               ixr    = 1 + mod(ix,nx)
               IF ( mapsta(iy+1,ixl).EQ.0 .AND.               &
                    mapxcl(iy+1,ixl).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta(iy+1,ix ).EQ.0 .AND.               &
                    mapxcl(iy+1,ix ).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta(iy+1,ixr).EQ.0 .AND.               &
                    mapxcl(iy+1,ixr).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta( iy ,ixr).EQ.0 .AND.               &
                    mapxcl( iy ,ixr).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta(iy-1,ixr).EQ.0 .AND.               &
                    mapxcl(iy-1,ixr).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta(iy-1,ix ).EQ.0 .AND.               &
                    mapxcl(iy-1,ix ).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta(iy-1,ixl).EQ.0 .AND.               &
                    mapxcl(iy-1,ixl).EQ.1 ) x1(ix,iy) = undef
               IF ( mapsta( iy ,ixl).EQ.0 .AND.               &
                    mapxcl( iy ,ixl).EQ.1 ) x1(ix,iy) = undef
             END IF
           END IF
           IF ( msout .AND. mapsta(iy,ix).EQ.1 ) x1(ix,iy) = undef
           IF ( mbout .AND. mapsta(iy,ix).EQ.2 ) x1(ix,iy) = undef
         END IF
         vallnd = - vallnd
       END DO
     END DO
     !
     WRITE (ndsdat) ((x1(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
     !
     ! 1.b Initialize arrays
     !
     x1 = undef
     xx = undef
     xy = undef
     xa = undef
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     ! 2.  Loop over output fields.
     !
     DO j=1, nogrp
       DO k=1, ngrpp
         !        WRITE(*,*)J,K,FLREQ(J,K)
         IF ( flreq(j,k) ) THEN
           !
           ! Set array dimension flags
           flone = .false.
           fltwo = .false.
           fldir = .false.
           fltri = .false.
           flprt = .false.
           !
 #ifdef W3_T
           WRITE (ndst,9020) idout(j,k)
 #endif
           !
           ! 2.a Set output arrays and parameters
           !
           !     Water depth
           !
           IF ( j.EQ.1 .AND. k.EQ.1 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, dw(1:nsea)          &
                  , mapsf, x1 )
             !
             !     Current
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.2 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, cx(1:nsea)          &
                  , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, cy(1:nsea)          &
                  , mapsf, xy )
             !
             !     Wind speed
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.3 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, ua(1:nsea)          &
                  , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, ud(1:nsea)          &
                  , mapsf, xy )
             !
             !     Air-sea temp. dif.
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.4 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, as(1:nsea)          &
                  , mapsf, x1 )
             !
             !     Water level
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.5 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, wlv   , mapsf, x1 )
             !
             !     Ice concentration
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.6 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, ice   , mapsf, x1 )
             !
             !     Atmospheric momentum
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.8 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, taua(1:nsea)        &
                  , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, tauadir(1:nsea)     &
                  , mapsf, xy )
             !
             !     Air density
             !
           ELSE IF ( j.EQ.1 .AND. k.EQ.9 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, rhoair, mapsf, x1 )
             !
             !     Ice thickness
             !
 #ifdef W3_IS2
           ELSE IF ( j.EQ.1 .AND. k.EQ.11 ) THEN
             flone = .true.
             CALL w3s2xy (nsea, nsea, nx, ny, iceh  , mapsf, x1 )
 #endif
             !
             !     Average sea ice floe diameter
             !
 #ifdef W3_IS2
           ELSE IF ( j.EQ.1 .AND. k.EQ.12) THEN
             flone = .true.
             CALL w3s2xy (nsea, nsea, nx, ny, icef  , mapsf, x1 )
 #endif
             !
             !
             !     Significant wave height
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.1 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, hs    , mapsf, x1 )
             !
             !     Mean wave length
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.2 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, wlm   , mapsf, x1 )
             !
             !     Mean zero-crossing wave period T02
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.3 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, t02   , mapsf, x1 )
             !
             !     Mean wave period Tm
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.4 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, t0m1   , mapsf, x1 )
             !
             !     Mean energy wave period Te
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.5 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, t01   , mapsf, x1 )
             !
             !     Peak period
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.6 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, fp0   , mapsf, x1 )
             !
             !     Mean wave direction
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.7 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, thm   , mapsf, x1 )
             !
             !     Directional spread
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.8 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, ths   , mapsf, x1 )
             !
             !     Peak direction
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.9 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, thp0  , mapsf, x1 )
             !
             !     Dominant wave breaking probability
             !
           ELSE IF ( j.EQ.2 .AND. k.EQ.17 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, wbt  , mapsf, x1 )
             !
             !     Partitioned wave heights
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.1 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, phs(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned peak period
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.2 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, ptp(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned wave leangths (peak)
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.3 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, plp(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned directions
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.4 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pdir(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned direstional spread
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.5 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, psi(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned wind sea fraction
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.6 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pws(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned peak direction
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.7 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pthp0(:,i),       &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Partitioned peakedness
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.8 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pqp(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned peak enhancement factor
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.9 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, ppe(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned gaussian frequency spread
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.10 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pgw(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned spectral width
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.11 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, psw(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned mean energy period (-1)
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.12 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, ptm1(:,i),        &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned mean wave period (+1)
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.13 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pt1(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned mean wave period (+2)
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.14 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pt2(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !
             !     Partitioned peak density
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.15 ) THEN
             flprt = .true.
             DO i=0, noswll
               CALL w3s2xy ( nsea, nsea, nx, ny, pep(:,i),         &
                    mapsf, xa(:,:,i) )
             END DO
             !
             !     Total wind sea fraction
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.16 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, pwst ,mapsf, x1 )
             !
             !     Number of partitions
             !
           ELSE IF ( j.EQ.4 .AND. k.EQ.17 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, pnr , mapsf, x1 )
             !
             !     Friction velocity
             !
           ELSE IF ( j.EQ.5 .AND. k.EQ.1 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, ust(1:nsea)      &
                  , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, ustdir(1:nsea)      &
                  , mapsf, xy )
             !
             !     Charnock parameter
             !
           ELSE IF ( j.EQ.5 .AND. k.EQ.2 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, charn , mapsf, x1 )
             !
             !     Mean energy flux
             !
           ELSE IF ( j.EQ.5 .AND. k.EQ.3 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, cge   , mapsf, x1 )
             !
             !     Air-sea energy flux
             !
           ELSE IF ( j.EQ.5 .AND. k.EQ.4 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, phiaw , mapsf, x1 )
             !
             !     Net supported wave stress
             !
           ELSE IF ( j.EQ.5 .AND. k.EQ.5 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, tauwix, mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, tauwiy, mapsf, xy )
             !
             !     Net supported wave stress
             !
           ELSE IF ( j.EQ.5 .AND. k.EQ.6 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, tauwnx, mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, tauwny, mapsf, xy )
             !
             !     Peakedness
             !
           ELSE IF ( j.EQ.8 .AND. k.EQ.5 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, qp    , mapsf, x1 )
             !
             !     Average source term time step
             !
           ELSE IF ( j.EQ.9 .AND. k.EQ.1 ) THEN
             flone = .true.
             DO isea=1, nsea
               IF ( dtdyn(isea) .NE. undef )                       &
                    dtdyn(isea) = dtdyn(isea) / 60.
             END DO
             CALL w3s2xy ( nsea, nsea, nx, ny, dtdyn , mapsf, x1 )
             !
             !     Cut-off frequency
             !
           ELSE IF ( j.EQ.9 .AND. k.EQ.2 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, fcut  , mapsf, x1 )
             !
             !     Max CFL step for XY propagation
             !
           ELSE IF ( j.EQ.9 .AND. k.EQ.3 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, cflxymax  , mapsf, x1 )
             !
             !     Max CFL step for directional propagation
             !
           ELSE IF ( j.EQ.9 .AND. k.EQ.4 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, cflthmax , mapsf, x1 )
             !!
             !! Not yet coded onto control file list (section 6 above)
             !
             !    Near-bottom amplitude
             !
           ELSE IF ( j.EQ.7 .AND. k.EQ.1 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, aba   , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, abd   , mapsf, xy )
             !
             !     Near-bottom velocity
             !
           ELSE IF ( j.EQ.7 .AND. k.EQ.2 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, uba   , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, ubd   , mapsf, xy )
             !
             !     Radiation stresses
             !
           ELSE IF ( j.EQ.6 .AND. k.EQ.1 ) THEN
             fltwo = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, sxx   , mapsf, x1 )
             CALL w3s2xy ( nsea, nsea, nx, ny, syy   , mapsf, xx )
             CALL w3s2xy ( nsea, nsea, nx, ny, sxy   , mapsf, xy )
             !
             !     User defined #1
             !
           ELSE IF ( j.EQ.10 .AND. k.EQ.1 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, usero(:,1)          &
                  , mapsf, x1 )
             !
             !     User defined #2
             !
           ELSE IF ( j.EQ.10 .AND. k.EQ.2 ) THEN
             flone = .true.
             CALL w3s2xy ( nsea, nsea, nx, ny, usero(:,2)          &
                  , mapsf, x1 )
             !
           ELSE
             WRITE (ndse,990) j, k
             WRITE (ndse,999)
             CALL extcde ( 1 )
             !
           END IF
           !
           ! 3   Perform output
           !
           !     3D array fields
           !
           IF ( fltri ) THEN
             WRITE (ndsdat)                                        &
                  ((x1(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
             WRITE (ndsdat)                                        &
                  ((xx(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
             WRITE (ndsdat)                                        &
                  ((xy(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
             !
             !     Partitions parameters
             !
           ELSE IF ( flprt ) THEN
             DO i=0, noswll
               WRITE (ndsdat)                                      &
                    ((xa(ix,iy,i),ix=ix0,ixn),iy=iy0,iyn)
             END DO
             !
             !     2D array fields
             !
           ELSE IF ( fltwo ) THEN
             WRITE (ndsdat)                                        &
                  ((xx(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
             WRITE (ndsdat)                                        &
                  ((xy(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
             !
             !     Scalars
             !
           ELSE IF ( flone ) THEN
             WRITE (ndsdat)                                        &
                  ((x1(ix,iy),ix=ix0,ixn),iy=iy0,iyn)
           END IF
           !
           ! ... End of fields loop
           !
         END IF
       END DO
     END DO
     !
     RETURN
     !
     ! Error escape locations
     !
     ! Formats
     !
 940 FORMAT (1x,i8,3i3.2,2x,4e12.4)
 950 FORMAT (1x,a13,i9.8,i7.6,2(2f8.2,i4),                           &
          1x,a4,f8.4,1x,a10,2i2,1x,a11,i4)
 951 FORMAT (1x,2f10.5,2i8)
     !
 990 FORMAT (/' *** WAVEWATCH III ERROR IN W3EXGO :'/           &
          '     GROUP',i2,' PARAMETER',i3,' NOT LISTED '    )
 999 FORMAT (/' *** WAVEWATCH III ERROR IN GXEXGO :'/                &
          '     PLEASE UPDATE FIELDS !!! '/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST GXEXGO : FLAGS  :',40l2)
 9020 FORMAT (' TEST GXEXGO : OUTPUT FIELD : ',a)
 #endif
     !/
     !/ End of GXEXGO ----------------------------------------------------- /
     !/
References w3servmd::w3s2xy().
Referenced by gxoutf().
gxoutf()
program gxoutf
Generate GrADS input files from raw WAVEWATCH data file.
Data is read from the grid output file out_grd.ww3 (raw data) and from the file gx_outf.inp (NDSI, output requests). Model definition and raw data files are read using WAVEWATCH III subroutines.
Output files are ww3.ctl and ww3.grads. The output files contains a land-sea map, followed by requested fields. See the control file for the names of the fields.
Author
H. L. Tolman
A. Chawla
J.H.G.M. Alves
Date
22-Mar-2021
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Definition at line 35 of file gx_outf.F90.
References w3adatmd::aba, w3adatmd::abd, w3adatmd::as, w3adatmd::bedforms, w3wdatmd::berg, w3adatmd::bhd, w3adatmd::cflkmax, w3adatmd::cflthmax, w3adatmd::cflxymax, w3adatmd::cge, w3adatmd::charn, w3adatmd::cx, w3adatmd::cy, w3timemd::dsec21(), w3adatmd::dtdyn, w3adatmd::dw, w3servmd::extcde(), w3adatmd::fcut, file(), w3odatmd::flogrd, w3odatmd::fnmpre, w3adatmd::fp0, gxexgo(), w3adatmd::hcmaxd, w3adatmd::hcmaxe, w3adatmd::hmaxd, w3adatmd::hmaxe, w3adatmd::hs, w3wdatmd::ice, w3wdatmd::icef, w3wdatmd::iceh, w3odatmd::idout, w3servmd::itrace(), w3adatmd::mscx, w3adatmd::mscy, w3adatmd::mssx, w3adatmd::mssy, w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3odatmd::ngrpp, w3odatmd::noge, w3odatmd::nogrp, w3odatmd::noswll, w3adatmd::p2sms, w3adatmd::pdir, w3adatmd::pep, w3adatmd::pgw, w3adatmd::phiaw, w3adatmd::phibbl, w3adatmd::phioc, w3adatmd::phs, w3adatmd::plp, w3adatmd::pnr, w3adatmd::ppe, w3adatmd::pqp, w3adatmd::prms, w3adatmd::psi, w3adatmd::psw, w3adatmd::pt1, w3adatmd::pt2, w3adatmd::pthp0, w3adatmd::ptm1, w3adatmd::ptp, w3adatmd::pws, w3adatmd::pwst, w3adatmd::qp, w3wdatmd::rhoair, w3adatmd::stmaxd, w3adatmd::stmaxe, w3timemd::stme21(), w3servmd::strace(), w3adatmd::sxx, w3adatmd::sxy, w3adatmd::syy, w3adatmd::t01, w3adatmd::t02, w3adatmd::t0m1, w3adatmd::taua, w3adatmd::tauadir, w3adatmd::taubbl, w3adatmd::tauox, w3adatmd::tauoy, w3adatmd::tauwix, w3adatmd::tauwiy, w3adatmd::tauwnx, w3adatmd::tauwny, w3adatmd::thm, w3adatmd::thp0, w3adatmd::ths, w3timemd::tick21(), w3wdatmd::time, w3adatmd::tpms, w3adatmd::tusx, w3adatmd::tusy, w3adatmd::ua, w3adatmd::uba, w3adatmd::ubd, w3adatmd::ud, constants::undef, w3adatmd::us3d, w3adatmd::usero, w3adatmd::ussx, w3adatmd::ussy, w3wdatmd::ust, w3wdatmd::ustdir, w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3iogomd::w3readflgrd(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3adatmd::wbt, w3adatmd::whitecap, w3adatmd::wlm, w3wdatmd::wlv, and w3adatmd::wn.