WAVEWATCH III: w3uostmd Module Reference
w3uostmd Module Reference
Parmeterization of the unresolved obstacles.
Functions/Subroutines
subroutine, public uost_initgrid (IGRID, FILELOCAL, FILESHADOW, LOCALFACTOR, SHADOWFACTOR)
Allocate the UOST variables for a given grid, and load them from file.
subroutine, public uost_setgrid (IGRID)
Sets the current grid in the sourceterm object.
subroutine, public uost_srctrmcompute (IX, IY, SPEC, CG, DT, U10ABS, U10DIR, S, D)
Estimates the UOST source term for a give spectrum.
subroutine uost_sourceterm_compute_ld (THIS, IX, IY, SPEC, CG, DT, U10ABS, U10DIR, S, D)
Method of the class UOST_SOURCETERM.
Detailed Description
Parmeterization of the unresolved obstacles.
Author
Lorenzo Mentaschi
Date
08-Oct-2018
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
uost_initgrid()
subroutine, public w3uostmd::uost_initgrid (integer, intent(in) IGRID, character(len=*), intent(in) FILELOCAL, character(len=*), intent(in) FILESHADOW, real, intent(in) LOCALFACTOR, real, intent(in) SHADOWFACTOR)
Allocate the UOST variables for a given grid, and load them from file.
Parameters
[in] IGRID Id of the grid being initialized.
[in] FILELOCAL File from where the alpha/beta coefficient for the local dissipation are loaded.
[in] FILESHADOW File from where the alpha/beta coefficient for the shadow effect are loaded.
[in] LOCALFACTOR Adjustment parameter for the local dissipation alpha and beta.
[in] SHADOWFACTOR Adjustment parameter for the shadow dissipation alpha and beta.
Author
Lorenzo Mentaschi
Date
01-Oct-2018
Definition at line 123 of file w3uostmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |          Lorenzo Mentaschi        |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Oct-2018 |
     !/                  +-----------------------------------+
     !/
     !/    Aug-2018 : Origination.                        ( version 6.07 )
     !/
     !  1. Purpose : allocate the UOST variables for a given grid, and load
     !               them from file
     !  2. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     IGRID, integer:        id of the grid being initialized
     !     FILELOCAL, string:     file from where the alpha/beta coefficient
     !                            for the local dissipation are loaded
     !     FILESHADOW, string:    file from where the alpha/beta coefficient
     !                            for the shadow effect are loaded
     !     LOCALFACTOR, double:   adjustment parameter for the local
     !                            dissipation alpha and beta
     !     SHADOWFACTOR, double:  adjustment parameter for the shadow
     !                            dissipation alpha and beta
     !     ----------------------------------------------------------------
     !
     !  3. Called by :
     !
     !      Name      Type  Module     Description
     !     ----------------------------------------------------------------
     !      W3IOGR    Subr. W3IOGRMD   Initialization of grid objects
     !     ----------------------------------------------------------------
     !
     !  4. Source code :
     !
     !/ ------------------------------------------------------------------- /
     IMPLICIT NONE
     INTEGER, INTENT(IN) :: IGRID
     CHARACTER(LEN=*), INTENT(IN) :: FILELOCAL, FILESHADOW
     REAL, INTENT(IN) :: LOCALFACTOR, SHADOWFACTOR
     TYPE(GRID), POINTER :: GRD
     TYPE(SGRD), POINTER :: SGD
     REAL :: CGMAX, MINSIZE
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'UOST_INITGRID')
 #endif
     IF ( (igrid .LE. 0) .OR. (.NOT. ALLOCATED(grids)) ) THEN
       RETURN
     ENDIF
     grd => grids(igrid)
     sgd => sgrds(igrid)
     grd%UOSTFILELOCAL = filelocal
     grd%UOSTFILESHADOW = fileshadow
     grd%UOSTLOCALFACTOR = localfactor
     grd%UOSTSHADOWFACTOR = shadowfactor
     ALLOCATE( grd%UOST_LCL_OBSTRUCTED(grd%NX, grd%NY) )
     grd%UOST_LCL_OBSTRUCTED = .false.
     ALLOCATE( grd%UOST_SHD_OBSTRUCTED(grd%NX, grd%NY) )
     grd%UOST_SHD_OBSTRUCTED = .false.
     ALLOCATE( grd%UOSTCELLSIZE(grd%NX, grd%NY, sgd%NTH) )
     grd%UOSTCELLSIZE = 0
     ALLOCATE( grd%UOSTLOCALALPHA(grd%NX, grd%NY, sgd%NK, sgd%NTH) )
     grd%UOSTLOCALALPHA = 100
     ALLOCATE( grd%UOSTLOCALBETA(grd%NX, grd%NY, sgd%NK, sgd%NTH) )
     grd%UOSTLOCALBETA = 100
     ALLOCATE( grd%UOSTSHADOWALPHA(grd%NX, grd%NY, sgd%NK, sgd%NTH) )
     grd%UOSTSHADOWALPHA = 100
     ALLOCATE( grd%UOSTSHADOWBETA(grd%NX, grd%NY, sgd%NK, sgd%NTH) )
     grd%UOSTSHADOWBETA = 100
     IF ( (igrid .GT. 0) .AND. ( ALLOCATED(srctrm)) ) THEN
       !  loading local/shadow alpha/beta
       CALL load_alphabeta(grd, sgd, unit_ab)
       !  warning the user that for cells too small UOST may be inaccurate
       cgmax = 20 ! simply taking a high value for the max group velocity to give an indication of this threshold
       minsize = cgmax*grd%DTMAX/1000
       WRITE(ndso,*)'*** WAVEWATCH-III WARNING IN W3UOST/UOST_INITGRID'
       WRITE(ndso,*)'UOST: grid ',trim(grd%GNAME),':'
       WRITE(ndso,*)'      global time step == ', grd%DTMAX, ' s'
       WRITE(ndso,*)'      FOR CELLS SMALLER THAN ABOUT ', minsize,    &
            ' KM UOST MAY UNDERESTIMATE THE DISSIPATION'
       WRITE(ndso,*)
     ENDIF
References w3gdatmd::grids, w3odatmd::ndso, w3gdatmd::sgrds, and w3servmd::strace().
Referenced by w3iogrmd::w3iogr().
uost_setgrid()
subroutine, public w3uostmd::uost_setgrid (integer, intent(in) IGRID)
Sets the current grid in the sourceterm object.
Parameters
[in] IGRID Id of the actual grid.
Author
Lorenzo Mentaschi
Date
01-Oct-2018
Definition at line 232 of file w3uostmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |         Lorenzo Mentaschi         |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Oct-2018 |
     !/                  +-----------------------------------+
     !/
     !/    Aug-2018 : Origination.                        ( version 6.07 )
     !/
     !  1. Purpose : sets the current grid in the sourceterm object
     !  2. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     IGRID, integer:        id of the actual grid
     !     ----------------------------------------------------------------
     !
     !  3. Called by :
     !
     !      Name      Type  Module     Description
     !     ----------------------------------------------------------------
     !      W3INIT    Subr. W3INITMD   Initialization of grid objects
     !      W3WAVE    Subr. W3WAVEMD   Initialization of grid objects
     !                                 before computation
     !     ----------------------------------------------------------------
     !
     !  4. Source code :
     !
     !/ ------------------------------------------------------------------- /
     IMPLICIT NONE
     INTEGER, INTENT(IN) :: IGRID
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'UOST_SETGRID')
 #endif
     IF ( .NOT. ALLOCATED(srctrm) ) THEN
       ALLOCATE(srctrm)
     ENDIF
     CALL srctrm%SETGRID(grids(igrid), sgrds(igrid))
References w3gdatmd::grids, w3gdatmd::sgrds, and w3servmd::strace().
Referenced by w3initmd::w3init(), and w3wavemd::w3wave().
uost_sourceterm_compute_ld()
subroutine w3uostmd::uost_sourceterm_compute_ld (class(uost_sourceterm), intent(inout) THIS, integer, intent(in) IX, integer, intent(in) IY, real, dimension(this%sgd%nspec), intent(in) SPEC, real, dimension(this%sgd%nk), intent(in) CG, real, intent(in) DT, real, intent(in) U10ABS, real, intent(in) U10DIR, real, dimension(this%sgd%nspec), intent(out) S, real, dimension(this%sgd%nspec), intent(out) D)
Method of the class UOST_SOURCETERM.
Computation of the local dissipation of the spectrum.
Parameters
[in,out] THIS Instance of UOST_SOURCETERM passed to the method.
[in] IX X coordinates of actual call.
[in] IY Y coordinates of actual call.
[in] SPEC Input spectrum.
[in] CG Group velocity.
[in] DT Time step.
[in] U10ABS Absolute value of U10.
[in] U10DIR Direction of U10.
[out] S Source term.
[out] D Differential of the source term over the spectrum.
Author
Lorenzo Mentaschi
Date
01-Oct-2018
Definition at line 794 of file w3uostmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |          Lorenzo Mentaschi        |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Oct-2018 |
     !/                  +-----------------------------------+
     !/
     !/    Aug-2018 : Origination.                        ( version 6.07 )
     !/
     !  1. Purpose : Method of the class UOST_SOURCETERM.
     !               Computation of the local dissipation of the spectrum
     !  2. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     THIS: UOST_SOURCETERM      instance of UOST_SOURCETERM passed to the method
     !                           (compulsory in oo programming)
     !     IX, IY: Integer       coordinates of the actual cell
     !     SPEC: real            input spectrum
     !     CG: real              group velocity
     !     DT: real              time step
     !     U10ABS: real          absolute value of U10
     !     U10DIR: real          direction of U10
     !     S: real               source term
     !     D: real               differential of the source term over the spectrum
     !     ----------------------------------------------------------------
     !
     !  3. Called by :
     !
     !      Name                   Type  Module     Description
     !     ----------------------------------------------------------------
     !      UOST_SOURCETERM_COMPUTE     Subr. W3UOSTMD   Computing the source term
     !     ----------------------------------------------------------------
     !
     !  4. Source code :
     !
     !/ ------------------------------------------------------------------- /
     IMPLICIT NONE
     CLASS(UOST_SOURCETERM), INTENT(INOUT) :: THIS
     INTEGER, INTENT(IN) :: IX, IY
     REAL, INTENT(IN) :: SPEC(THIS%SGD%NSPEC), CG(THIS%SGD%NK)
     REAL, INTENT(OUT) :: S(THIS%SGD%NSPEC), D(THIS%SGD%NSPEC)
     REAL, INTENT(IN) :: U10ABS, U10DIR
     REAL, INTENT(IN) :: DT
     INTEGER :: IK, ITH, ISP, NK, NTH
     REAL :: ALPHA, BETA, CGI, CELLSIZE, SPECI, SFC
     LOGICAL :: CELLOBSTRUCTED
     REAL :: TH, PSI
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'UOST_SOURCETERM_COMPUTE_LD')
 #endif
     s = 0
     d = 0
     cellobstructed =  this%GRD%UOST_LCL_OBSTRUCTED(ix, iy)
     IF (.NOT. cellobstructed) RETURN
     nk = this%SGD%NK
     nth = this%SGD%NTH
     DO ik = 1,nk
       cgi = cg(ik)
       DO ith = 1,nth
         !  Getting alpha and beta for local dissipation
         alpha = this%GRD%UOSTLOCALALPHA(ix, iy, ik, ith)/this%GRD%UOSTABMULTFACTOR
         alpha = max(min(alpha*this%GRD%UOSTLOCALFACTOR, 1.), 0.)
         beta = this%GRD%UOSTLOCALBETA(ix, iy, ik, ith)/this%GRD%UOSTABMULTFACTOR
         beta = max(min(beta*this%GRD%UOSTLOCALFACTOR, 1.), 0.)
         IF (alpha .EQ. 1) cycle
         !  Getting the size of the cell along direction ith
         cellsize = this%GRD%UOSTCELLSIZE(ix, iy, ith)*this%GRD%UOSTCELLSIZEFACTOR
         isp = ith + (ik-1)*nth
         speci = spec(isp)
         th = this%SGD%TH(ith)
         CALL compute_reduction_psi(u10abs, u10dir, cg(ik), th, dt, psi)
         IF (beta > 0.09) THEN
           !  Computing the local dissipation for a partially obstructed cell
           sfc = - cgi/cellsize * (1 - beta)/beta
         ELSE
           !  The cell is almost completely obstructed.
           !  Dissipating the energy almost completely.
           sfc = - cgi/cellsize * this%GAMMAUP
         ENDIF
         s(isp) = sfc * speci * psi
         d(isp) = sfc * psi
       ENDDO
     ENDDO
References w3servmd::strace().
uost_srctrmcompute()
subroutine, public w3uostmd::uost_srctrmcompute (integer, intent(in) IX, integer, intent(in) IY, real, dimension(srctrm%sgd%nspec), intent(in) SPEC, real, dimension(srctrm%sgd%nk), intent(in) CG, real, intent(in) DT, real, intent(in) U10ABS, real, intent(in) U10DIR, real, dimension(srctrm%sgd%nspec), intent(out) S, real, dimension(srctrm%sgd%nspec), intent(out) D)
Estimates the UOST source term for a give spectrum.
Parameters
[in] IX
[in] IY
[in] SPEC
[in] CG
[in] DT
[in] U10ABS
[in] U10DIR
[out] S
[out] D
Author
Lorenzo Mentaschi
Date
01-Oct-2018
Definition at line 299 of file w3uostmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |          Lorenzo Mentaschi        |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Oct-2018 |
     !/                  +-----------------------------------+
     !/
     !/    Aug-2018 : Origination.                        ( version 6.07 )
     !/
     !  1. Purpose : estimates the UOST source term for a give spectrum
     !  2. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     IGRID, integer:        id of the actual grid
     !     ----------------------------------------------------------------
     !
     !  3. Called by :
     !
     !      Name      Type  Module     Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD   Computation of the source terms
     !     ----------------------------------------------------------------
     !
     !  4. Source code :
     !
     !/ ------------------------------------------------------------------- /
     IMPLICIT NONE
     INTEGER, INTENT(IN) :: IX, IY
     REAL, INTENT(IN) :: DT
     REAL, INTENT(IN) :: SPEC(SRCTRM%SGD%NSPEC), CG(SRCTRM%SGD%NK)
     REAL, INTENT(IN) :: U10ABS, U10DIR
     REAL, INTENT(OUT) :: S(SRCTRM%SGD%NSPEC), D(SRCTRM%SGD%NSPEC)
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'UOST_SRCTRMCOMPUTE')
 #endif
     CALL srctrm%COMPUTE(ix, iy, spec, cg, dt, u10abs, u10dir, s, d)
References file(), w3odatmd::ndse, w3odatmd::ndso, constants::pi, and w3servmd::strace().
Referenced by w3srcemd::w3srce().