WAVEWATCH III: scrip_netcdfmod Module Reference
scrip_netcdfmod Module Reference
Functions/Subroutines
logical(scrip_logical) function, public scrip_netcdferrorcheck (netcdfStat, errorCode, rtnName, errorMsg)
Function/Subroutine Documentation
scrip_netcdferrorcheck()
logical (scrip_logical) function, public scrip_netcdfmod::scrip_netcdferrorcheck (integer (scrip_i4), intent(in) netcdfStat, integer (scrip_i4), intent(out) errorCode, character (*), intent(in) rtnName, character (*), intent(in) errorMsg)
Definition at line 45 of file scrip_netcdfmod.f90.
     ! !DESCRIPTION:
     ! This routine checks netCDF status flags from netCDF routines.
     ! On error, it adds an error message to the error log and returns
     ! both a true value to the calling routines as well as setting the
     ! error code to fail. It is used in the same manner is the
     ! SCRIP\_ErrorCheck function.
     !
     ! !REVISION HISTORY:
     ! same as module
     ! !OUTPUT PARAMETERS:
     logical (SCRIP_logical) :: &
          SCRIP_NetcdfErrorCheck
     integer (SCRIP_i4), intent(out) :: &
          errorCode ! returned SCRIP error flag
     ! !INPUT PARAMETERS:
     integer (SCRIP_i4), intent(in) :: &
          netcdfStat ! status flag from netCDF call
     character (*), intent(in) :: &
          rtnName, &! name of calling routine
          errorMsg ! error message for logging
     !EOP
     !BOC
     !-----------------------------------------------------------------------
     !
     ! local variables
     !
     !-----------------------------------------------------------------------
     character (SCRIP_charLength) :: &
          ncErrMsg ! netCDF error message
     !-----------------------------------------------------------------------
     !
     ! if no error, return false and a successful errorCode
     !
     !-----------------------------------------------------------------------
     if (netcdfstat == nf90_noerr) then
       errorcode = scrip_success
       scrip_netcdferrorcheck = .false.
       !-----------------------------------------------------------------------
       !
       ! if an error is detected, return a true value and call the SCRIP
       ! error handlers to log the error. Log both the netCDF error msg
       ! as well as the error passed by the calling routine.
       !
       !-----------------------------------------------------------------------
     else
       scrip_netcdferrorcheck = .true.
       ncerrmsg = nf90_strerror(netcdfstat)
       call scrip_errorset(errorcode, rtnname, ncerrmsg)
       call scrip_errorset(errorcode, rtnname, errormsg)
     endif
     !-----------------------------------------------------------------------
     !EOC
References scrip_errormod::scrip_errorset(), and scrip_errormod::scrip_success.
Referenced by scrip_remap_read::read_remap_scrip_ww3(), scrip_remap_read::read_remap_ww3(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), and scrip_remap_write::write_remap_scrip_ww3().