WAVEWATCH III: w3flx4md Module Reference
w3flx4md Module Reference
Flux/stress computations according to Hwang (2011).
Functions/Subroutines
subroutine w3flx4 (ZWND, U10, U10D, UST, USTD, Z0, CD)
Flux/stress computations according to Hwang (JTECH, 2011).
Detailed Description
Flux/stress computations according to Hwang (2011).
Hwang 2011: J Atmos Ocean Tech 28(3) 436-443.
Author
H. L. Tolman
S. Zieger
Q. Liu
Date
24-Nov-2017
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
w3flx4()
subroutine w3flx4md::w3flx4 (real, intent(in) ZWND, real, intent(in) U10, real, intent(in) U10D, real, intent(out) UST, real, intent(out) USTD, real, intent(out) Z0, real, intent(out) CD)
Flux/stress computations according to Hwang (JTECH, 2011).
     CD    = 1E-4 ( -0.016 U10**2 + 0.967U10 + 8.058)
     USTAR = U10 * SQRT( U10 )
Parameters
[in] ZWND Wind height.
[in] U10 Wind speed.
[in] U10D Wind direction.
[out] UST Friction velocity.
[out] USTD Direction of friction velocity.
[out] Z0 Z0 in profile law.
[out] CD Drag coefficient.
Author
H. L. Tolman
Date
03-Jul-2006
Definition at line 106 of file w3flx4md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         03-Jul-2006 |
     !/                  +-----------------------------------+
     !/
     !/    03-Jul-2006 : Origination.                        ( version 3.09 )
     !/
     !  1. Purpose :
     !
     !     Flux/stress computations according to Hwang (JTECH, 2011)
     !
     !  2. Method :
     !
     !     CD    = 1E-4 ( -0.016 U10**2 + 0.967U10 + 8.058)
     !     USTAR = U10 * SQRT( U10 )
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       ZWND    Real   I   Wind height.
     !       U10     Real   I   Wind speed.
     !       U10D    Real   I   Wind direction.
     !       UST     Real   O   Friction velocity.
     !       USTD    Real   0   Direction of friction velocity.
     !       Z0      Real   O   z0 in profile law.
     !       CD      Real   O   Drag coefficient.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse, iaproc, naperr
     USE w3gdatmd, ONLY: flx4a0
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: ZWND, U10, U10D
     REAL, INTENT(OUT)       :: UST, USTD, Z0, CD
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3FLX4')
 #endif
     !
     ! 1.  Tests ---------------------------------------------------------- *
     !
     IF ( abs(zwnd-10.) .GT. 0.01 ) THEN
       IF ( iaproc .EQ. naperr ) WRITE (ndse,1000) zwnd
       CALL extcde (1)
     END IF
     !
     ! 2.  Computation ---------------------------------------------------- *
     !
     !     To prevent the drag coefficient from dropping to zero at extreme
     !     wind speeds, we use a simple modification UST = 2.026 m/s for
     !     U10 greater than 50.33 m/s.
     !
     IF (u10 .GE. 50.33) THEN
       ust = 2.026 * sqrt(flx4a0)
       cd  = (ust/u10)**2
     ELSE
       cd  = flx4a0 * ( 8.058 + 0.967*u10 - 0.016*u10**2 ) * 1e-4
       ust = u10 * sqrt(cd)
     END IF
     !
     z0     = zwnd * exp( -0.4 / sqrt(cd) )
     ustd   = u10d
     !
     RETURN
     !
     ! Formats
     !
 1000 FORMAT (/' *** WAVEWATCH III ERROR IN W3FLX4 : '/               &
          '     HIGHT OF WIND SHOULD BE 10m IN THIS APPRACH '/   &
          '     ZWND =',f8.2,'m'/)
     !/
     !/ End of W3FLX4 ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3gdatmd::flx4a0, w3odatmd::iaproc, w3odatmd::naperr, w3odatmd::ndse, and w3servmd::strace().
Referenced by gxexpo(), w3exnc(), w3expo(), and w3srcemd::w3srce().