WAVEWATCH III: w3sbt4md Module Reference
w3sbt4md Module Reference
SHOWEX bottom friction source term (Ardhuin et al.
Functions/Subroutines
subroutine insbt4
Initialization for bottom friction source term routine.
subroutine tabu_erf
Tabulation of ERF function, which is used in bottom friction subgrid modeling.
subroutine w3sbt4 (A, CG, WN, DEPTH, D50, PSIC, TAUBBL, BEDFORM, S, D, IX, IY)
Computes the SHOWEX bottom friction with movable bed effects.
Variables
integer, parameter sizeerftable =300
real, dimension(0:sizeerftable) erftable
real delxerf
real, parameter xerfmax = 4.
Detailed Description
SHOWEX bottom friction source term (Ardhuin et al.
2003).
Using a subgrid depth parameterization based on Tolman (CE 1995).
Author
F. Ardhuin
J. Lepesqueur
Date
14-Mar-2012
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
insbt4()
subroutine w3sbt4md::insbt4
Initialization for bottom friction source term routine.
Author
F. Ardhuin
Date
14-Mar-2012
Definition at line 146 of file w3sbt4md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |                         SHOM      |
     !/                  |            F. Ardhuin             |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         14-Mar-2012 |
     !/                  +-----------------------------------+
     !/
     !/    14-Mar-2012 : Origination.                        ( version 4.05 )
     !
     !  1. Purpose :
     !
     !     Initialization for bottom friction source term routine.
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SBT4    Subr. W3SRC3MD Corresponding source term.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !      NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'INSIN3')
 #endif
     !
     ! 1.  .... ----------------------------------------------------------- *
     !
     CALL tabu_erf   !tabulates ERF function
     !/
     !/ End of INSBT4 ----------------------------------------------------- /
     !/
References w3servmd::strace(), and tabu_erf().
Referenced by w3sbt4().
tabu_erf()
subroutine w3sbt4md::tabu_erf
Tabulation of ERF function, which is used in bottom friction subgrid modeling.
Initialization for source term routine.
Author
J. Lepesqueur
Date
14-Mar-2012
Definition at line 243 of file w3sbt4md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |        J. Lepesqueur              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         14-Mar-2012 |
     !/                  +-----------------------------------+
     !/
     !/    14-Mar-2012 : Origination.                        ( version 3.13 )
     !/
     !  1. Purpose :
     !     Tabulation of ERF function, which is used in bottom friction subgrid modelling
     !
     !     Initialization for source term routine.
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SIN3    Subr. W3SRC3MD Corresponding source term.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     IMPLICIT NONE
     INTEGER :: I
     REAL :: x,y
     delxerf   = (2*xerfmax)/real(sizeerftable)
     DO i=0,sizeerftable
       x=-1.*xerfmax+i*delxerf
       if(x.lt.0.)then
         y=2**(1/2)*(1-abs(erf(x)))/2
       else
         y=2**(1/2)*(1+erf(x))/2
       end if
       erftable(i)=y
     END DO
     RETURN
     !/ ------------------------------------------------------------------- /
References delxerf, erftable, sizeerftable, and xerfmax.
Referenced by insbt4().
w3sbt4()
subroutine w3sbt4md::w3sbt4 (real, dimension(nspec), intent(in) A, real, dimension(nk), intent(in) CG, real, dimension(nk), intent(in) WN, real, intent(in) DEPTH, real, intent(in) D50, real, intent(in) PSIC, real, dimension(2), intent(out) TAUBBL, real, dimension(3), intent(inout) BEDFORM, real, dimension(nspec), intent(out) S, real, dimension(nspec), intent(out) D, integer, intent(in) IX, integer, intent(in) IY)
Computes the SHOWEX bottom friction with movable bed effects.
Uses a Gaussian distribution for friction factors, and estimates the contribution of rippled and non-rippled fractions based on the bayesian approach of Tolman (1995).
Parameters
[in] A Action density spectrum.
[in] CG Group velocities.
[in] WN Wavenumbers.
[in] DEPTH Water depth.
[in] D50 Median grain size.
[in] PSIC Critical Shields parameter.
[out] TAUBBL Components of stress leaking to the bottom.
[in,out] BEDFORM Ripple parameters (roughness and wavelength).
[out] S Source term (1-D version).
[out] D Diagonal term of derivative.
[in] IX Spatial grid index.
[in] IY Spatial grid index.
Author
F. Ardhuin
J. Lepesqueur
Date
15-Mar-2012
Definition at line 341 of file w3sbt4md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |            F. Ardhuin             |
     !/                  !            J. Lepesqueur          !
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-Mar-2012 |
     !/                  +-----------------------------------+
     !/
     !/    23-Jun-2011 : Origination.                        ( version 4.04 )
     !/    04-Jul-2011 : Adding momentum flux TAUBBL         ( version 4.05 )
     !/    15-Mar-2012 : Adding subgrid treatment for depth  ( version 4.05 )
     !/
     !  1. Purpose :
     !
     !     Computes the SHOWEX bottom friction with movable bed effects
     !
     !  2. Method :
     !     Uses a Gaussian distribution for friction factors, and estimates
     !     the contribution of rippled and non-rippled fractions based on
     !     the bayesian approach of Tolman (1995).
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       A       R.A.  I   Action density spectrum.
     !       CG      R.A.  I   Group velocities.
     !       WN      R.A.  I   Wavenumbers.
     !       DEPTH   Real  I   Water depth.
     !       D50     Real  I   Median grain size.
     !       PSIC    Real  I   Critical Shields parameter
     !       BEFORMS Real I/O  Ripple parameters (roughness and wavelength).
     !       TAUBBL  Real  O   Components of stress leaking to the bottom.
     !       S       R.A.  O   Source term (1-D version).
     !       D       R.A.  O   Diagonal term of derivative.             *)
     !       IX,IY   Int. I   Spatial grid indices
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !      W3EXPO    Subr.   N/A    Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
     USE w3gdatmd, ONLY: nk, nth, nspec, sig, dden,  &
          sbtcx, ecos, esin, dth
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     LOGICAL, SAVE           :: FIRST = .true.
     REAL, INTENT(IN)        :: CG(NK), WN(NK), DEPTH, A(NSPEC), D50
     REAL, INTENT(IN)        :: PSIC
     INTEGER, INTENT(IN)     :: IX, IY
     REAL, INTENT(OUT)       :: S(NSPEC), D(NSPEC), TAUBBL(2)
     REAL, INTENT(INOUT)     :: BEDFORM(3)
     REAL                    :: CBETA(NK)
     REAL :: UORB2,UORB,AORB, EBX, EBY, AX, AY, LX, LY
     REAL :: CONST2, TEMP2
     REAL :: FW, KSUBN, KSUBS, KSUBR, MINADIM
     REAL :: SHIELDS(3), PSI, DELI1, DELI2, EB, XI, VARU, DD50
     INTEGER :: IK, ITH, IS, IND, INDE, ISUB
     REAL :: KRR, DSUB
     REAL DSUM(NK)
     ! These are the 3-point Gauss-Hermitte quadrature coefficients
     REAL, PARAMETER :: WSUB(3) = (/ 0.1666667,   0.1666666  , 0.6666667/)
     REAL, PARAMETER :: XSUB(3) = (/ -0.001,  0.001 , 0. /)
     REAL :: PROBA1, PROBA2, PSIX, PSIXT, PSIN2, DPSI , FACTOR
     REAL :: BACKGROUND
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SBT4')
 #endif
     !
     ! 0.  Initializations ------------------------------------------------ *
     IF ( first ) THEN
       CALL insbt4
       first  = .false.
     END IF
     !
     ! 1.  Min / Max settings for grain size D50---------------------------- *
     !
     dd50=max(d50,1e-5)
     dd50=min(dd50,1.)
     !
     ! 1.1 Set background roughness when ripples are not active
     !
     background=max(sbtcx(6),sbtcx(7)*dd50)
     !
     ! 2. Subgrid loop
     !
     dsum(:)=0.
     taubbl(:)=0.
     !
     DO isub=1,3
       !
       ! 2.a  Computes bulk parameters : E, Uorb, Aorb------------------------- *
       !
       dsub=depth*(1.+xsub(isub))
       uorb=0.
       aorb=0.
       ax  =0.
       ay  =0.
       DO ik=1, nk
         IF ( wn(ik)*dsub .LT. 6. ) THEN
           eb  = 0.
           ebx = 0.
           eby = 0.
           DO ith=1, nth
             is=ith+(ik-1)*nth
             eb  = eb  + a(is)
             ebx = ebx +a(is)*ecos(ith)
             eby = eby +a(is)*esin(ith)
           END DO
           !
           ! U_bot=sigma * Zeta / sinh(KD)  and CBETA = 0.5*sigma^2 /(g*sinh^(kD))
           ! therefore variance(u_bot)= variance(elevation)*2*CBETA/D
           !
           !            CBETA(IK) = MAX(0., (CG(IK)*WN(IK)/SIG(IK)-0.5) )/DSUB
           cbeta(ik) = 0.5*sig(ik)**2 /(grav*(sinh(wn(ik)*dsub))**2)
           !  N.B.:  could also include shoaling effect on EB ...
           factor= (dden(ik) / cg(ik))*2*cbeta(ik)*grav
           varu= eb * factor
           uorb = uorb + varu
           aorb = aorb + varu/(sig(ik)**2)
           ax   = ax   + (ebx * factor)
           ay   = ay   + (eby * factor)
         ELSE
           cbeta(ik) = 0.
         END IF
       END DO
       !
       ! Computes RMS orbital amplitudes
       !
       uorb2 = 2*uorb
       uorb = sqrt(max(1.0e-7,uorb2))
       aorb = sqrt(max(1.0e-7,2*aorb))
       !
       ! Computes potential ripple wavelength, 1.7 = 2 * sqrt(2) * 0.6
       ! Based on Ardhuin et al. (JGR 2002): lambda = 0.6 * d_1/3
       !
       lx = aorb*1.7*ax/sqrt(ax**2+ay**2+1e-12)
       ly = aorb*1.7*ay/sqrt(ax**2+ay**2+1e-12)
       !
       ! 2.b First use of FWTABLE to get skin roughness and estimate Shields parameter
       !
       xi=max((alog10(max(aorb/dd50,0.3))-abmin)/delab,1.)
       ind  = min(sizefwtable-1, int(xi))
       deli1= min(1. ,xi-float(ind))
       deli2= 1. - deli1
       fw =fwtable(ind)*deli2+fwtable(ind+1)*deli1
       psi=fw*uorb2/(2.*grav*(sed_sg-1)*dd50)
       !
       ! Normalized Shields parameter
       !
       shields(isub)=psi/psic
       !
     END DO ! end of loop on ISUB
     dpsi=(shields(2)-shields(1))/(xsub(2)-xsub(1))*sbtcx(5)
     !
     ! Tests if the variation in psi is large enough to use subgrid
     !
     IF (abs(dpsi).LT.0.0001*shields(3).OR.abs(dpsi).LT.1.e-8) THEN
       !
       ! no subgrid in this case
       !
       IF(shields(3).GT.sbtcx(3)) THEN
         !  ripple roughness, see Ardhuin et al. (2003)
         ksubr=aorb*sbtcx(1)*shields(3)**sbtcx(2)
         !  Sheet flow roughness, see Wilson (1989)
         ksubs=aorb*0.0655*(uorb2/((sed_sg-1)*grav*aorb))**1.4
         ksubn = ksubr + ksubs
         bedform(2)=lx
         bedform(3)=ly
       ELSE
         !  relict roughness, see Ardhuin et al. (2003)
         ksubn=max(background,aorb*sbtcx(4))
         bedform(2)=-lx
         bedform(3)=-ly
       END IF
       bedform(1)=ksubn
     ELSE
       !
       ! subgrid in this case
       !
       psix=(sbtcx(3)-shields(3))/dpsi
       psixt=max((psix + xerfmax)/delxerf,0.)
       inde  = max(min(sizeerftable-1, int(psixt)),0)
       deli1  = min(1. ,psixt-float(inde))
       deli2  = 1. - deli1
       proba2=max(min(erftable(inde)*deli2+erftable(inde+1)*deli1,1.),0.)
       proba1 = 1. - proba2
       ! Mean psi with ripples (Tolman 1995, eq. XX)
       psin2=max(shields(3)+exp(-(0.5*psix**2))/sqrt(tpi)*dpsi/(proba2+0.0001),sbtcx(3))
       ! Sum of relict, ripple and sheet flow roughnesses
       ksubn = proba1*max(background,aorb*sbtcx(4))       &
            +proba2*aorb*(sbtcx(1)*psin2**sbtcx(2)+                   &
            0.0655*(uorb2/((sed_sg-1)*grav*aorb))**1.4)
       !
       IF (proba2.GT.0.5) THEN
         bedform(2)=lx
         bedform(3)=ly
       ELSE
         bedform(2)=-lx
         bedform(3)=-ly
       END IF
       !
     END IF
     bedform(1)=ksubn
     !
     ! 2.c second use of FWTABLE to get FW from the full roughness
     !
     xi=max((alog10(max(aorb/ksubn,0.3))-abmin)/delab,1.)
     ind  = min(sizefwtable-1, int(xi))
     deli1= min(1. ,xi-float(ind))
     deli2= 1. - deli1
     fw =fwtable(ind)*deli2+fwtable(ind+1)*deli1
     !
     ! 5. Fills output arrays and estimates the energy and momentum loss
     !
     DO ik=1, nk
       const2=dden(ik)/cg(ik) &         !Jacobian to get energy in band
            *grav/(sig(ik)/wn(ik))    ! coefficient to get momentum
       dsum(ik)=-fw*uorb*cbeta(ik)      !*WSUB(ISUB)
       DO ith=1,nth
         is=ith+(ik-1)*nth
         d(is)=dsum(ik)
         temp2=const2*d(is)*a(is)
         taubbl(1) = taubbl(1) - temp2*ecos(is)
         taubbl(2) = taubbl(2) - temp2*esin(is)
         s(is)=d(is)*a(is)
       END DO
     END DO
     !
     RETURN
     !/
     !/ End of W3SBT4 ----------------------------------------------------- /
     !/
References constants::abmin, w3gdatmd::dden, constants::delab, delxerf, w3gdatmd::dth, w3gdatmd::ecos, erftable, w3gdatmd::esin, w3servmd::extcde(), constants::fwtable, constants::grav, insbt4(), w3odatmd::ndse, w3gdatmd::nk, w3gdatmd::nspec, w3gdatmd::nth, w3gdatmd::sbtcx, constants::sed_sg, w3gdatmd::sig, sizeerftable, constants::sizefwtable, w3servmd::strace(), constants::tpi, and xerfmax.
Referenced by gxexpo(), w3exnc(), w3expo(), and w3srcemd::w3srce().
Variable Documentation
delxerf
real w3sbt4md::delxerf
Definition at line 132 of file w3sbt4md.F90.
   REAL                    :: DELXERF
Referenced by tabu_erf(), and w3sbt4().
erftable
real, dimension(0:sizeerftable) w3sbt4md::erftable
Definition at line 131 of file w3sbt4md.F90.
   REAL                    :: ERFTABLE(0:SIZEERFTABLE)
Referenced by tabu_erf(), and w3sbt4().
sizeerftable
integer, parameter w3sbt4md::sizeerftable =300
Definition at line 130 of file w3sbt4md.F90.
   INTEGER, PARAMETER      :: SIZEERFTABLE=300
Referenced by tabu_erf(), and w3sbt4().
xerfmax
real, parameter w3sbt4md::xerfmax = 4.
Definition at line 133 of file w3sbt4md.F90.
   REAL,    PARAMETER      :: XERFMAX =  4. ! number of stdev
Referenced by tabu_erf(), and w3sbt4().