WAVEWATCH III: yowerr Module Reference
yowerr Module Reference
Has some subroutine to make a nice error message.
Functions/Subroutines
subroutine parallel_abort (string, error)
subroutine abort (string, line, file, errno)
print various error strings and exit.
subroutine warn (string, line, file)
print warning Call this to print an warning string and optional line number, and file
Detailed Description
Has some subroutine to make a nice error message.
Function/Subroutine Documentation
abort()
subroutine yowerr::abort (character(*), intent(in), optional string, integer, intent(in), optional line, character(*), intent(in), optional file, integer, intent(in), optional errno)
print various error strings and exit.
Call this to print an error string and optional line number, file and MPI error string
Parameters
[in] string Errorstring
[in] line Line number
[in] file Filename
[in] errno The MPI error number which is translated into an error string
Definition at line 93 of file yowerr.F90.
         use yowdatapool, only: comm
         use mpi
         implicit none
         ! Errorstring to print
         character(*), optional, intent(in) :: string
         ! Linenumber to print
         integer,      optional, intent(in) :: line
         ! Filename to print
         character(*), optional, intent(in) :: file
         ! MPI error number to translate
         integer,      optional, intent(in) :: errno
         ! Linenumber as string
         character(50) :: lineNumber
         ! MPI_MAX_ERROR_STRING = 1024
         ! MPI Errorstring
         character(MPI_MAX_ERROR_STRING) :: errorstring
         ! The rank of this thread
         integer :: myrank
         ! real MPI errorsting lengt
         integer :: stringLengh
         !
         integer :: ierr
         ! Get rank
         call mpi_comm_rank(comm, myrank,ierr)
         !     if(ierr/=MPI_SUCCESS) write(*,*) "parallel_abort: ierr=", ierr
         ! Always print rank
         write(*, '(i2,a)', advance='no') myrank, " "
         ! Print a simple "ERROR" when no MPI error number was given because the MPI error string contain an "ERROR" allready
         if(.not. present(errno)) then
           write(*,'(a)', advance='no' ) " ERROR "
         endif
         ! print file and linenumber
         if(present(file)) then
           write(*,'(a)',advance='no' ) file
           if(present(line)) then
             Write(linenumber, '(i10)') line
             write(*, '(2a)', advance='no') ":", trim(adjustl(linenumber))
           endif
           write(*, '(a)', advance='no') " "
         endif
         ! if only linenumber is present, add an "Line:" string
         if(.not. present(file) .and. present(line)) then
           Write(linenumber, '(i10)') line
           write(*, '(2a)', advance='no') "Line:", trim(adjustl(linenumber))
           write(*, '(a)', advance='no') " "
         endif
         ! print the errror string
         if(present(string)) then
           write(*,'(a)', advance='no') string
         endif
         ! translate and print the MPI error string
         if(present(errno) .and. errno /= mpi_success) then
           call mpi_error_string(errno, errorstring, stringlengh, ierr)
           write(*,'(2a)', advance='no') 'MPI ERROR: ', errorstring(1:stringlengh)
         endif
         write(*,*)
         stop
References yowdatapool::comm.
Referenced by yowpdlibmain::exchangeghostids(), yowrankmodule::exchangeiplg(), yowexchangemodule::initnbrdomains(), yowrankmodule::initrankmodule(), yowexchangemodule::pdlib_exchange1dreal(), and yowpdlibmain::real_mpi_barrier_pdlib().
parallel_abort()
subroutine yowerr::parallel_abort (character(*), intent(in), optional string, integer, intent(in), optional error)
Definition at line 43 of file yowerr.F90.
     use yowdatapool, only: comm
     use mpi
     implicit none
     character(*),optional,intent(in) :: string !string to print
     integer,optional,intent(in) :: error       !mpi errorcode
     integer :: ierr,i
     logical :: lopen
     integer :: sl
     ! MPI_MAX_ERROR_STRING = 1024
     character(1024) :: errorstring
     integer :: myrank
     ! Get rank
     call mpi_comm_rank(comm, myrank,ierr)
     if(ierr/=mpi_success) write(*,*) "parallel_abort: ierr=", ierr
     inquire(11,opened=lopen)
     if(present(string)) then
       write(*,'(i4,2a)') myrank,': ABORT: ',string
       if(lopen) write(11,'(i4,2a)') myrank,': ABORT: ',string
     endif
     if(present(error)) then
       if(error /= mpi_success) then
         ! get errorstring associatet fuer errorcode err
         call mpi_error_string(error, errorstring, sl, ierr)
         if(ierr/=mpi_success) write(*,*) "parallel_abort: ierr=", ierr
         write(*,'(i4,2a)') myrank,': MPI ERROR: ', errorstring(1:sl)
         if(lopen) write(11,'(i4,2a)') myrank,': MPI ERROR: ', errorstring
       endif
       do i=1,200; inquire(i,opened=lopen); if(lopen) close(i); enddo;
         call mpi_abort(comm, error,ierr)
         if(ierr/=mpi_success) write(*,*) "parallel_abort: ierr=", ierr
       else
         do i=1,200; inquire(i,opened=lopen); if(lopen) close(i); enddo;
           call mpi_abort(comm, 0,ierr)
           if(ierr/=mpi_success) write(*,*) "parallel_abort: ierr=", ierr
         endif
References yowdatapool::comm.
Referenced by yowpdlibmain::assignmesh(), yowpdlibmain::computetria_ien_si_ccon(), yowexchangemodule::creatempitype(), yowpdlibmain::element_crosses_dateline(), yowpdlibmain::exchangeghostids(), yowrankmodule::exchangeiplg(), yowexchangemodule::finalizeexchangemodule(), yowpdlibmain::findconndomains(), yowpdlibmain::findconnnodes(), yowpdlibmain::findghostnodes(), yowexchangemodule::pdlib_exchange1dreal(), yowexchangemodule::pdlib_exchange2dreal(), yowexchangemodule::pdlib_exchange2dreal_zero(), yowpdlibmain::postpartition(), yowpdlibmain::postpartition2(), yowpdlibmain::prepartition(), yowpdlibmain::real_mpi_barrier_pdlib(), and yowpdlibmain::runparmetis().
warn()
subroutine yowerr::warn (character(*), intent(in), optional string, integer, intent(in), optional line, character(*), intent(in), optional file)
print warning Call this to print an warning string and optional line number, and file
Parameters
[in] string warnstring
[in] line Line number
[in] file Filename
Definition at line 169 of file yowerr.F90.
         use yowdatapool, only: comm
         use mpi
         implicit none
         ! Errorstring to print
         character(*), optional, intent(in) :: string
         ! Linenumber to print
         integer,      optional, intent(in) :: line
         ! Filename to print
         character(*), optional, intent(in) :: file
         ! Linenumber as string
         character(50) :: lineNumber
         ! The rank of this thread
         integer :: myrank
         !
         integer :: ierr
         ! Get rank
         call mpi_comm_rank(comm, myrank,ierr)
         !     if(ierr/=MPI_SUCCESS) write(*,*) "parallel_abort: ierr=", ierr
         ! Always print rank
         write(*, '(i2,a)', advance='no') myrank, " "
         write(*,'(a)', advance='no' ) " WARN "
         ! print file and linenumber
         if(present(file)) then
           write(*,'(a)',advance='no' ) file
           if(present(line)) then
             Write(linenumber, '(i10)') line
             write(*, '(2a)', advance='no') ":", trim(adjustl(linenumber))
           endif
           write(*, '(a)', advance='no') " "
         endif
         ! if only linenumber is present, add an "Line:" string
         if(.not. present(file) .and. present(line)) then
           Write(linenumber, '(i10)') line
           write(*, '(2a)', advance='no') "Line:", trim(adjustl(linenumber))
           write(*, '(a)', advance='no') " "
         endif
         ! print the errror string
         if(present(string)) then
           write(*,'(a)', advance='no') string
         endif
         write(*,*)
References yowdatapool::comm.