WAVEWATCH III: yowfunction Module Reference
yowfunction Module Reference
Functions/Subroutines
subroutine pdlib_abort (istat)
subroutine computelistnp_listnpa_listiplg_kernel
subroutine computelistnp_listnpa_listiplg
subroutine computeboundaryinformation
Function/Subroutine Documentation
computeboundaryinformation()
subroutine yowfunction::computeboundaryinformation
Definition at line 283 of file yowfunction.F90.
     use yownodepool, only: listnp, listnpa, listiplg
     USE w3gdatmd, ONLY: iobp
     USE w3odatmd, only : iaproc, naproc
     IMPLICIT NONE
     integer ListFirst(NAPROC), NbSend(NAPROC)
     integer IPROC, eSend, IP, IP_glob, NPAloc
     listfirst=0
     DO iproc=2,naproc
       listfirst(iproc)=listfirst(iproc-1) + listnpa(iproc-1)
     END DO
     DO iproc=1,naproc
       npaloc=listnpa(iproc)
       esend=0
       DO ip=1,npaloc
         ip_glob=listiplg(ip + listfirst(iproc))
         IF (iobp(ip_glob) .eq. 1) THEN
           esend=esend + 1
         END IF
       END DO
       nbsend(iproc)=esend
     END DO
References w3odatmd::iaproc, w3gdatmd::iobp, yownodepool::listiplg, yownodepool::listnp, yownodepool::listnpa, and w3odatmd::naproc.
computelistnp_listnpa_listiplg()
subroutine yowfunction::computelistnp_listnpa_listiplg
Definition at line 195 of file yowfunction.F90.
     USE w3odatmd, only : iaproc, naproc, ntproc
     USE w3adatmd, ONLY: mpi_comm_wave
     USE yowdatapool, only: rtype, istatus
     USE yownodepool, only: npa, np, iplg
     USE yownodepool, only: listnp, listnpa, listiplg
     IMPLICIT NONE
     include "mpif.h"
     INTEGER sumNP, iProc, ierr, istat
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'Before ComputeListNP_ListNPA_Kernel'
     FLUSH(740+iaproc)
 #endif
     IF (iaproc .le. naproc) THEN
       CALL computelistnp_listnpa_listiplg_kernel
     END IF
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) ' After ComputeListNP_ListNPA_Kernel'
     FLUSH(740+iaproc)
 #endif
     IF (iaproc .eq. 1) THEN
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Doing the send'
       FLUSH(740+iaproc)
 #endif
       sumnp=sum(listnpa)
       DO iproc=naproc+1,ntproc
 #ifdef W3_DEBUGINIT
         WRITE(740+iaproc,*) 'Loop state 1, iProc=', iproc
         FLUSH(740+iaproc)
 #endif
         CALL mpi_send(listnp, naproc,mpi_integer, iproc-1, 20, mpi_comm_wave, ierr)
 #ifdef W3_DEBUGINIT
         WRITE(740+iaproc,*) 'Loop state 2, iProc=', iproc
         FLUSH(740+iaproc)
 #endif
         CALL mpi_send(listnpa,naproc,mpi_integer, iproc-1, 21, mpi_comm_wave, ierr)
 #ifdef W3_DEBUGINIT
         WRITE(740+iaproc,*) 'Loop state 3, iProc=', iproc
         FLUSH(740+iaproc)
 #endif
         CALL mpi_send(listiplg, sumnp,mpi_integer, iproc-1, 271, mpi_comm_wave, ierr)
 #ifdef W3_DEBUGINIT
         WRITE(740+iaproc,*) 'Loop state 4, iProc=', iproc
         FLUSH(740+iaproc)
 #endif
       END DO
     END IF
     IF (iaproc .gt. naproc) THEN
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Before allocation'
       FLUSH(740+iaproc)
 #endif
       allocate(listnp(naproc), listnpa(naproc), stat=istat)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Before receiving of data 1'
       FLUSH(740+iaproc)
 #endif
       CALL mpi_recv(listnp ,naproc,mpi_integer, 0, 20, mpi_comm_wave, istatus, ierr)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Before receiving of data 2'
       FLUSH(740+iaproc)
 #endif
       CALL mpi_recv(listnpa,naproc,mpi_integer, 0, 21, mpi_comm_wave, istatus, ierr)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Before computing sumNP'
       FLUSH(740+iaproc)
 #endif
       sumnp=sum(listnpa)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Before allocating ListIPLG'
       FLUSH(740+iaproc)
 #endif
       allocate(listiplg(sumnp), stat=istat)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Before receiving ListIPLG'
       FLUSH(740+iaproc)
 #endif
       CALL mpi_recv(listiplg,sumnp,mpi_integer, 0, 271, mpi_comm_wave, istatus, ierr)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'After receiving ListIPLG'
       FLUSH(740+iaproc)
 #endif
     END IF
References computelistnp_listnpa_listiplg_kernel(), w3odatmd::iaproc, include(), yownodepool::iplg, yowdatapool::istatus, yownodepool::listiplg, yownodepool::listnp, yownodepool::listnpa, w3adatmd::mpi_comm_wave, w3odatmd::naproc, yownodepool::np, yownodepool::npa, w3odatmd::ntproc, and yowdatapool::rtype.
Referenced by pdlib_w3profsmd::pdlib_init().
computelistnp_listnpa_listiplg_kernel()
subroutine yowfunction::computelistnp_listnpa_listiplg_kernel
Definition at line 57 of file yowfunction.F90.
     USE w3odatmd, only : iaproc, naproc, ntproc
     USE w3adatmd, ONLY: mpi_comm_wcmp
     USE yowdatapool, only: rtype, istatus
     USE yownodepool, only: npa, np, iplg
     USE yownodepool, only: listnp, listnpa, listiplg
     IMPLICIT NONE
     include "mpif.h"
     integer IPROC, idx, IP, len, istat, sumNP, ierr
     integer, allocatable :: iVect(:)
     !
     ! Computing ListNP and ListNPA
     !
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 1'
     FLUSH(740+iaproc)
 #endif
     allocate(listnp(naproc), listnpa(naproc), ivect(2), stat=istat)
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 2'
     FLUSH(740+iaproc)
 #endif
     IF (istat /= 0) CALL pdlib_abort(1)
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 3'
     FLUSH(740+iaproc)
 #endif
     IF (iaproc .eq. 1) THEN
       listnp(1)=np
       listnpa(1)=npa
       DO iproc=2,naproc
         CALL mpi_recv(ivect,2,mpi_integer, iproc-1, 19, mpi_comm_wcmp, istatus, ierr)
         listnp(iproc)=ivect(1)
         listnpa(iproc)=ivect(2)
       END DO
       DO iproc=2,naproc
         CALL mpi_send(listnp, naproc,mpi_integer, iproc-1, 20, mpi_comm_wcmp, ierr)
         CALL mpi_send(listnpa,naproc,mpi_integer, iproc-1, 21, mpi_comm_wcmp, ierr)
       END DO
     ELSE
       ivect(1)=np
       ivect(2)=npa
       CALL mpi_send(ivect,2,mpi_integer, 0, 19, mpi_comm_wcmp, ierr)
       CALL mpi_recv(listnp ,naproc,mpi_integer, 0, 20, mpi_comm_wcmp, istatus, ierr)
       CALL mpi_recv(listnpa,naproc,mpi_integer, 0, 21, mpi_comm_wcmp, istatus, ierr)
     END IF
     deallocate(ivect)
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 4'
     FLUSH(740+iaproc)
 #endif
     !
     ! ListIPLG
     !
     sumnp=sum(listnpa)
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 5, sumNP=', sumnp
     FLUSH(740+iaproc)
 #endif
     allocate(listiplg(sumnp), stat=istat)
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 6'
     FLUSH(740+iaproc)
 #endif
     IF (istat /= 0) CALL pdlib_abort(2)
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 7'
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, NAPROC=', naproc, ' NTPROC=', ntproc
     FLUSH(740+iaproc)
 #endif
     IF (iaproc .eq. 1) THEN
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Main node 1'
       FLUSH(740+iaproc)
 #endif
       idx=0
       DO ip=1,npa
         idx=idx+1
         listiplg(ip)=iplg(ip)
       END DO
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Main node 2'
       FLUSH(740+iaproc)
 #endif
       DO iproc=2,naproc
         len=listnpa(iproc)
         allocate(ivect(len), stat=istat)
         IF (istat /= 0) CALL pdlib_abort(3)
         CALL mpi_recv(ivect,len,mpi_integer, iproc-1, 269, mpi_comm_wcmp, istatus, ierr)
         DO ip=1,len
           idx=idx+1
           listiplg(idx)=ivect(ip)
         END DO
         deallocate(ivect)
       END DO
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Main node 3'
       FLUSH(740+iaproc)
 #endif
       DO iproc=2,naproc
 #ifdef W3_DEBUGINIT
         WRITE(740+iaproc,*) 'Before mpi_send IPROC=', iproc
         FLUSH(740+iaproc)
 #endif
         CALL mpi_send(listiplg, sumnp,mpi_integer, iproc-1, 271, mpi_comm_wcmp, ierr)
 #ifdef W3_DEBUGINIT
         WRITE(740+iaproc,*) 'After mpi_send IPROC=', iproc
         FLUSH(740+iaproc)
 #endif
       END DO
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Main node 4'
       FLUSH(740+iaproc)
 #endif
     ELSE
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Peripheral node 1'
       FLUSH(740+iaproc)
 #endif
       CALL mpi_send(iplg, npa,mpi_integer, 0, 269, mpi_comm_wcmp, ierr)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Peripheral node 2'
       FLUSH(740+iaproc)
 #endif
       CALL mpi_recv(listiplg,sumnp,mpi_integer, 0, 271, mpi_comm_wcmp, istatus, ierr)
 #ifdef W3_DEBUGINIT
       WRITE(740+iaproc,*) 'Peripheral node 3'
       FLUSH(740+iaproc)
 #endif
     END IF
 #ifdef W3_DEBUGINIT
     WRITE(740+iaproc,*) 'ComputeListNP_ListNPA_Kernel, step 8'
     FLUSH(740+iaproc)
 #endif
References w3odatmd::iaproc, include(), yownodepool::iplg, yowdatapool::istatus, yownodepool::listiplg, yownodepool::listnp, yownodepool::listnpa, w3adatmd::mpi_comm_wcmp, w3odatmd::naproc, yownodepool::np, yownodepool::npa, w3odatmd::ntproc, pdlib_abort(), and yowdatapool::rtype.
Referenced by computelistnp_listnpa_listiplg().
pdlib_abort()
subroutine yowfunction::pdlib_abort (integer, intent(in) istat)
Definition at line 48 of file yowfunction.F90.
     IMPLICIT NONE
     integer, intent(in) :: istat
     print *, 'Error with istat=', istat
     CALL abort
Referenced by pdlib_w3profsmd::block_solver_init(), computelistnp_listnpa_listiplg_kernel(), pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and pdlib_w3profsmd::pdlib_mapsta_init().