WAVEWATCH III: scrip_timers Module Reference
scrip_timers Module Reference
Functions/Subroutines
subroutine timer_check (timer)
subroutine timer_clear (timer)
real(scrip_r4) function timer_get (timer)
subroutine timer_print (timer)
subroutine timer_start (timer)
subroutine timer_stop (timer)
subroutine timers_init
Variables
integer(scrip_i4), parameter max_timers = 99
integer(scrip_i4), save cycles_max
integer(scrip_i4), dimension(max_timers), save cycles1
integer(scrip_i4), dimension(max_timers), save cycles2
real(scrip_r4), save clock_rate
real(scrip_r4), dimension(max_timers), save cputime
character(len=8), dimension(max_timers), save status
Function/Subroutine Documentation
timer_check()
subroutine scrip_timers::timer_check (integer (scrip_i4), intent(in) timer)
Definition at line 73 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine checks a given timer.  This is primarily used to
 !     periodically accumulate time in the timer to prevent timer cycles
 !     from wrapping around max_cycles.
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     Input Variables:
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &    timer            ! timer number
 !-----------------------------------------------------------------------
       if (status(timer) .eq. 'running') then
         call timer_stop (timer)
         call timer_start(timer)
       endif
 !-----------------------------------------------------------------------
References status, timer_start(), and timer_stop().
timer_clear()
subroutine scrip_timers::timer_clear (integer (scrip_i4), intent(in) timer)
Definition at line 105 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine resets a given timer.
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     Input Variables:
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &    timer            ! timer number
 !-----------------------------------------------------------------------
       cputime(timer) = 0.0_scrip_r4  ! clear the timer
 !-----------------------------------------------------------------------
References cputime.
Referenced by scrip_interface::scrip().
timer_get()
real (scrip_r4) function scrip_timers::timer_get (integer (scrip_i4), intent(in) timer)
Definition at line 132 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine returns the result of a given timer.  This can be
 !     called instead of timer_print so that the calling routine can
 !     print it in desired format.
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     Input Variables:
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &    timer            ! timer number
 !-----------------------------------------------------------------------
 !
 !     Output Variables:
 !
 !-----------------------------------------------------------------------
       real (SCRIP_r4) ::
      &     timer_get   ! accumulated cputime in given timer
 !-----------------------------------------------------------------------
       if (status(timer) .eq. 'stopped') then
         timer_get = cputime(timer)
       else
         call timer_stop(timer)
         timer_get = cputime(timer)
         call timer_start(timer)
       endif
 !-----------------------------------------------------------------------
References cputime, status, timer_start(), and timer_stop().
timer_print()
subroutine scrip_timers::timer_print (integer (scrip_i4), intent(in) timer)
Definition at line 176 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine prints the accumulated cpu time in given timer.
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     Input Variables:
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &    timer            ! timer number
 !-----------------------------------------------------------------------
       !---
       !--- print the cputime accumulated for timer
       !--- make sure timer is stopped
       !---
       if (status(timer) .eq. 'stopped') then
         write(*,"(' CPU time for timer',i3,':',1p,e16.8)")
      &       timer,cputime(timer)
       else
         call timer_stop(timer)
         write(*,"(' CPU time for timer',i3,':',1p,e16.8)")
      &       timer,cputime(timer)
         call timer_start(timer)
       endif
 !-----------------------------------------------------------------------
References cputime, status, timer_start(), and timer_stop().
Referenced by scrip_remap_conservative::remap_conserv().
timer_start()
subroutine scrip_timers::timer_start (integer (scrip_i4), intent(in) timer)
Definition at line 216 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine starts a given timer.
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     Input Variables:
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &    timer            ! timer number
 !-----------------------------------------------------------------------
       !---
       !--- Start the timer and change timer status.
       !---
       if (status(timer) .eq. 'stopped') then
         call system_clock(count=cycles1(timer))
         status(timer) = 'running'
       endif
 !-----------------------------------------------------------------------
References cycles1, and status.
Referenced by scrip_remap_conservative::remap_conserv(), timer_check(), timer_get(), and timer_print().
timer_stop()
subroutine scrip_timers::timer_stop (integer (scrip_i4), intent(in) timer)
Definition at line 250 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine stops a given timer.
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     Input Variables:
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &    timer            ! timer number
 !-----------------------------------------------------------------------
       if (status(timer) .eq. 'running') then
         !---
         !--- Stop the desired timer.
         !---
         call system_clock(count=cycles2(timer))
         !---
         !--- check and correct for cycle wrapping
         !---
         if (cycles2(timer) .ge. cycles1(timer)) then
           cputime(timer) = cputime(timer) + clock_rate*
      &                     (cycles2(timer) - cycles1(timer))
         else
           cputime(timer) = cputime(timer) + clock_rate*
      &                (cycles2(timer) - cycles1(timer) + cycles_max)
         endif
         !---
         !--- Change timer status.
         !---
         status(timer)='stopped'
       endif
 !-----------------------------------------------------------------------
References clock_rate, cputime, cycles1, cycles2, cycles_max, and status.
Referenced by scrip_remap_conservative::remap_conserv(), timer_check(), timer_get(), and timer_print().
timers_init()
subroutine scrip_timers::timers_init
Definition at line 303 of file scrip_timers.f.
 !-----------------------------------------------------------------------
 !
 !     This routine initializes some machine parameters necessary for
 !     computing cpu time from F90 intrinsics.
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4) :: cycles ! count rate return by sys_clock
 !-----------------------------------------------------------------------
       !---
       !--- Initialize timer arrays and clock_rate.
       !---
       clock_rate = 0.0_scrip_r4
       cycles1    = 0
       cycles2    = 0
       cputime    = 0.0_scrip_r4
       status     = 'stopped'
       !---
       !--- Call F90 intrinsic system_clock to determine clock rate
       !--- and maximum cycles.  If no clock available, print message.
       !---
       call system_clock(count_rate=cycles, count_max=cycles_max)
       if (cycles /= 0) then
         clock_rate = 1.0_scrip_r4/real(cycles)
       else
         clock_rate = 0.0_scrip_r4
         print *, '--- No system clock available ---'
       endif
 !-----------------------------------------------------------------------
References clock_rate, cputime, cycles1, cycles2, cycles_max, and status.
Referenced by scrip_interface::scrip(), and scrip_interface::scrip_clear().
Variable Documentation
clock_rate
real (scrip_r4), save scrip_timers::clock_rate
Definition at line 57 of file scrip_timers.f.
       real (SCRIP_r4), save ::
      &     clock_rate       ! clock_rate in seconds for each cycle
Referenced by timer_stop(), and timers_init().
cputime
real (scrip_r4), dimension(max_timers), save scrip_timers::cputime
Definition at line 60 of file scrip_timers.f.
       real (SCRIP_r4), dimension(max_timers), save ::
      &     cputime          ! accumulated cpu time in each timer
Referenced by timer_clear(), timer_get(), timer_print(), timer_stop(), and timers_init().
cycles1
integer (scrip_i4), dimension(max_timers), save scrip_timers::cycles1
Definition at line 53 of file scrip_timers.f.
       integer (SCRIP_i4), dimension(max_timers), save ::
      &     cycles1,         ! cycle number at start for each timer
      &     cycles2          ! cycle number at stop  for each timer
Referenced by timer_start(), timer_stop(), and timers_init().
cycles2
integer (scrip_i4), dimension(max_timers), save scrip_timers::cycles2
Definition at line 53 of file scrip_timers.f.
Referenced by timer_stop(), and timers_init().
cycles_max
integer (scrip_i4), save scrip_timers::cycles_max
Definition at line 50 of file scrip_timers.f.
       integer (SCRIP_i4), save ::
      &     cycles_max       ! max value of clock allowed by system
Referenced by timer_stop(), and timers_init().
max_timers
integer (scrip_i4), parameter scrip_timers::max_timers = 99
Definition at line 47 of file scrip_timers.f.
       integer (SCRIP_i4), parameter ::
      &     max_timers = 99  ! max number of timers allowed
Referenced by scrip_interface::scrip().
status
character (len=8), dimension(max_timers), save scrip_timers::status
Definition at line 63 of file scrip_timers.f.
       character (len=8), dimension(max_timers), save ::
      &     status           ! timer status string
Referenced by timer_check(), timer_get(), timer_print(), timer_start(), timer_stop(), and timers_init().