WAVEWATCH III: w3gdatmd Module Reference
w3gdatmd Module Reference
Data Types
type fldp
type grid
type mpar
type npar
type prop
type sbsp
type sbtp
type schm
type sdbp
type sflp
type sgrd
type sicp
type slnp
type snlp
type srcp
type strp
type uostp
Functions/Subroutines
subroutine w3nmod (NUMBER, NDSE, NDST, NAUX)
subroutine w3dimx (IMOD, MX, MY, MSEA, NDSE, NDST ifdef W3_SMC
subroutine w3dims (IMOD, MK, MTH, NDSE, NDST)
subroutine w3setg (IMOD, NDSE, NDST)
subroutine w3gntx (IMOD, NDSE, NDST)
subroutine w3dimug (IMOD, MTRI, MX, COUNTOTA, NNZ, NDSE, NDST)
subroutine w3setref
Variables
integer ngrids = -1
integer igrid = -1
integer isgrd = -1
integer ipars = -1
integer nauxgr
integer, parameter nic4 =16
integer, parameter nic42 =5
integer, parameter rlgtype = 1
integer, parameter clgtype = 2
integer, parameter ungtype = 3
integer, parameter smctype = 4
integer, parameter iclose_none = ICLO_NONE
integer, parameter iclose_smpl = ICLO_SMPL
integer, parameter iclose_trpl = ICLO_TRPL
integer, parameter nkhs =2000
integer, parameter nkd =1300
integer, parameter ndtab =2000
type(grid), dimension(:), allocatable, target grids
type(sgrd), dimension(:), allocatable, target sgrds
type(mpar), dimension(:), allocatable, target mpars
integer, pointer gtype
integer, pointer rstype
integer, pointer iclose
integer, pointer nx
integer, pointer ny
integer, pointer nsea
integer, pointer nseal
integer, pointer trflag
integer, dimension(:,:), pointer e3df
integer, dimension(:), pointer p2msf
integer, dimension(:), pointer us3df
integer, dimension(:), pointer usspf
real, dimension(:), pointer ussp_wn
real, dimension(:,:), pointer reflc
integer, dimension(:,:), pointer refld
integer, pointer nbedge
integer, dimension(:,:), pointer edges
integer, dimension(:,:), pointer neigh
integer, pointer ntri
integer, pointer countri
integer, pointer countot
integer, pointer nnz
integer optioncall = 3
integer, dimension(:,:), pointer trigp
integer, pointer nbnd_map
integer, dimension(:), pointer index_map
integer, dimension(:), pointer mapsta_loc
integer *1, dimension(:,:), pointer iobpd_loc
integer *2, dimension(:), pointer iobp_loc
integer *1, dimension(:), pointer iobdp_loc
integer *1, dimension(:), pointer iobpa_loc
real(8), dimension(:,:), pointer ien
real(8), dimension(:,:), pointer len
real(8), dimension(:), pointer si
real, dimension(:,:), pointer angle
real, dimension(:,:), pointer angle0
integer, dimension(:), pointer ccon
integer, dimension(:), pointer countcon
integer, dimension(:), pointer ie_cell
integer, dimension(:), pointer pos_cell
integer, dimension(:), pointer iaa
integer, dimension(:), pointer jaa
integer, dimension(:,:), pointer posi
integer, dimension(:), pointer i_diag
integer, dimension(:,:,:), pointer ja_ie
integer, dimension(:), pointer index_cell
integer *2, dimension(:), pointer iobp
integer *1, dimension(:,:), pointer iobpd
integer *1, dimension(:), pointer iobdp
integer *1, dimension(:), pointer iobpa
real(8), dimension(:), pointer tria
real, dimension(:,:), pointer crossdiff
real, pointer maxx
real, pointer maxy
real, pointer dxymax
logical, pointer guginit
real, pointer ffacberg
logical, dimension(:), pointer rref
real, dimension(:), pointer refpars
real, dimension(:), pointer igpars
real, dimension(:), pointer ic2pars
real, dimension(:), pointer ic3pars
integer, dimension(:), pointer ic4pars
real, dimension(:), pointer ic4_ki
real, dimension(:), pointer ic4_fc
real, dimension(:), pointer ic4_cn
real, pointer ic4_fmin
real, pointer ic4_kibk
real, dimension(:), pointer ic5pars
real, dimension(:), pointer is2pars
integer, dimension(:,:), pointer mapsta
integer, dimension(:,:), pointer mapst2
integer, dimension(:,:), pointer mapfs
integer, dimension(:,:), pointer mapsf
integer, pointer ncel
integer, pointer nufc
integer, pointer nvfc
integer, pointer nrlv
integer, pointer mrfct
integer, pointer nglo
integer, pointer narc
integer, pointer nbgl
integer, pointer nbac
integer, pointer nbsmc
integer, dimension(:), pointer nlvcel
integer, dimension(:), pointer nlvufc
integer, dimension(:), pointer nlvvfc
integer, dimension(:,:), pointer ijkcel
integer, dimension(:,:), pointer ijkufc
integer, dimension(:,:), pointer ijkvfc
integer, dimension(:), pointer ismcbp
integer, dimension(:), pointer iclbac
integer, dimension(:), pointer ijkcel3
integer, dimension(:), pointer ijkcel4
integer, dimension(:), pointer ijkvfc5
integer, dimension(:), pointer ijkvfc6
integer, dimension(:), pointer ijkufc5
integer, dimension(:), pointer ijkufc6
integer, pointer nitersec1
real, pointer sx
real, pointer sy
real, pointer x0
real, pointer y0
real, pointer dtcfl
real, pointer dtcfli
real, pointer dtmax
real, pointer dtmin
real, pointer dmin
real, pointer ctmax
real, pointer fice0
real, pointer ficen
real, pointer ficel
real, pointer pfmove
real, pointer stexu
real, pointer steyu
real, pointer stedu
real, pointer iicehmin
real, pointer iicehinit
real, dimension(:), pointer icescales
real, pointer iicehfac
real, pointer iicehdisp
real, pointer iiceddisp
real, pointer iicefdisp
real, pointer btbeta
real, pointer aaircmin
real, pointer aairgb
real(8), pointer gridshift
real, pointer polat
real, pointer polon
real, dimension(:), pointer angld
logical, pointer flagunr
real, dimension(:), pointer zb
real, dimension(:), pointer clats
real, dimension(:), pointer clatis
real, dimension(:), pointer cthg0s
real, dimension(:,:), pointer trnx
real, dimension(:,:), pointer trny
real, dimension(:), pointer ctrnx
real, dimension(:), pointer ctrny
real, dimension(:), pointer clatf
real, dimension(:,:), pointer spcbac
real, dimension(:), pointer angarc
double precision, dimension(:,:), pointer xgrd
double precision, dimension(:,:), pointer ygrd
real, dimension(:,:), pointer dxdp
real, dimension(:,:), pointer dxdq
real, dimension(:,:), pointer dydp
real, dimension(:,:), pointer dydq
real, dimension(:,:), pointer dpdx
real, dimension(:,:), pointer dpdy
real, dimension(:,:), pointer dqdx
real, dimension(:,:), pointer dqdy
real, dimension(:,:), pointer gsqrt
real, dimension(:,:), pointer hpfac
real, dimension(:,:), pointer hqfac
real, dimension(:), pointer sed_d50
real, dimension(:), pointer sed_psic
logical, pointer ginit
logical, pointer fldry
logical, pointer flcx
logical, pointer flcy
logical, pointer flcth
logical, pointer flck
logical, pointer flsou
logical, pointer iicedisp
logical, pointer iicesmooth
logical, pointer flagll
logical, pointer cmprtrck
logical, dimension(:), pointer flagst
character(len=30), pointer gname
character(len=13), pointer filext
type(t_gsu), pointer gsu
integer, pointer nk
integer, pointer nk2
integer, pointer nth
integer, pointer nspec
integer, dimension(:), pointer mapwn
integer, dimension(:), pointer mapth
real, pointer dth
real, pointer xfr
real, pointer fr1
real, pointer fte
real, pointer ftf
real, pointer ftwn
real, pointer fttr
real, pointer ftwl
real, pointer facti1
real, pointer facti2
real, pointer fachfa
real, pointer fachfe
real, dimension(:), pointer th
real, dimension(:), pointer esin
real, dimension(:), pointer ecos
real, dimension(:), pointer es2
real, dimension(:), pointer esc
real, dimension(:), pointer ec2
real, dimension(:), pointer sig
real, dimension(:), pointer sig2
real, dimension(:), pointer dsip
real, dimension(:), pointer dsii
real, dimension(:), pointer dden
real, dimension(:), pointer dden2
logical, pointer sinit
logical, pointer pinit
real, pointer facp
real, pointer xrel
real, pointer xflt
real, pointer fxfm
real, pointer fxpm
real, pointer xft
real, pointer xfc
real, pointer facsd
real, pointer fhmax
real, pointer rwindc
real, dimension(:), pointer wwcor
real, pointer dtme
real, pointer clatmn
real, pointer wdcg
real, pointer wdth
real, pointer dtms
real, pointer refran
logical, pointer funo3
logical, pointer fverg
logical, pointer fswnd
logical, pointer arctc
integer, pointer tail_id
real, pointer tail_lev
real, pointer tail_tran1
real, pointer tail_tran2
integer, pointer nittin
real, pointer cinxsi
integer, pointer cap_id
real, pointer cd_max
real, pointer flx4a0
real, pointer slnc1
real, pointer fspm
real, pointer fshf
real, pointer sinc1
real, pointer sdsc1
real, pointer zwind
real, pointer fswell
real, pointer shstab
real, pointer ofstab
real, pointer ccng
real, pointer ccps
real, pointer ffng
real, pointer ffps
real, pointer cdsa0
real, pointer cdsa1
real, pointer cdsa2
real, pointer sdsaln
real, pointer cdsb0
real, pointer cdsb1
real, pointer cdsb2
real, pointer cdsb3
real, pointer fpimin
real, pointer xfh
real, pointer xf1
real, pointer xf2
real, pointer zzwnd
real, pointer aalpha
real, pointer bbeta
real, pointer zz0max
real, pointer zz0rat
real, pointer zzalp
real, pointer ffxfm
real, pointer ffxpm
real, pointer ssinthp
real, pointer ttauwshelter
real, dimension(:), pointer sswellf
real, pointer ssdsc1
real, pointer ssdsc2
real, pointer ssdsc3
real, pointer ssdsbr
real, pointer ssdsp
real, pointer wwnmeanp
real, pointer sstxftf
real, pointer sstxftwn
real, pointer ssdsc4
real, pointer ssdsc5
real, pointer ssdsc6
real, pointer ssdsbt
real, pointer ddelta1
real, pointer ddelta2
real, pointer ssdscos
real, pointer ssdsdth
real, dimension(:), pointer ssdsbm
integer, pointer sswellfpar
integer, pointer ssdsiso
integer, pointer ssdsbrfdf
integer, dimension(:,:), pointer iktab
integer, dimension(:,:), pointer satindices
integer, pointer ssdsdik
real, dimension(:,:), pointer dcki
real, dimension(:,:), pointer satweights
real, dimension(:,:), pointer cumulw
real, dimension(:,:), pointer qbi
real, pointer ffxfa
real, pointer ssdsbrf1
real, pointer ssdsbrf2
real, pointer ssdsbint
real, pointer ssdsbck
real, pointer ssdshck
real, pointer ssdsabk
real, pointer ssdspbk
real, pointer ssinbr
real, dimension(:), pointer sintailpar
real, dimension(:), pointer ssdsc
real, dimension(:), pointer capchnk
real, pointer sin6a0
real, pointer sds6a1
real, pointer sds6a2
real, pointer swl6b1
real, pointer sin6ws
real, pointer sin6fc
integer, pointer sds6p1
integer, pointer sds6p2
logical, pointer sds6et
logical, pointer swl6s6
logical, pointer swl6cstb1
real, pointer wwnmeanptail
real, pointer sstxftftail
integer, pointer iqtpe
integer, pointer gqnf1
integer, pointer gqnt1
integer, pointer gqnq_om2
real, pointer nltail
real, pointer gqthrsat
real, pointer gqthrcou
real, dimension(:), pointer gqamp
real, pointer snlc1
real, pointer lam
real, pointer kdcon
real, pointer kdmn
real, pointer snls1
real, pointer snls2
real, pointer snls3
integer, pointer ndpths
real, dimension(:), pointer dpthnl
integer, pointer nfrmin
integer, pointer nfrmax
integer, pointer nfrcut
integer, pointer nthmax
integer, pointer nthexp
integer, pointer nspmin
integer, pointer nspmax
integer, pointer nspmx2
integer, pointer nqa
integer, pointer snlnq
integer, dimension(:,:,:), pointer qst1
integer, dimension(:,:,:), pointer qst4
real, pointer snlmsc
real, pointer snlnsc
real, pointer snlsfd
real, pointer snlsfs
real, dimension(:), pointer frq
real, dimension(:), pointer xsi
real, dimension(:,:,:), pointer qst2
real, dimension(:,:,:), pointer qst3
real, dimension(:,:,:), pointer qst5
real, dimension(:,:,:), pointer qst6
real, dimension(:), pointer snll
real, dimension(:), pointer snlm
real, dimension(:), pointer snlt
real, dimension(:), pointer snlcd
real, dimension(:), pointer snlcs
integer, pointer itsa
integer, pointer ialt
real, pointer qr5dpt
real, pointer qr5oml
integer, pointer qi5dis
integer, pointer qi5kev
integer, pointer qi5ipl
integer, pointer qi5pmx
integer(kind=8), pointer qi5nnz
integer, pointer nthx
integer, pointer nfrx
integer, pointer nspl
integer, pointer nsph
real, pointer cnlsa
real, pointer cnlsc
real, pointer cnlsfm
real, pointer cnlsc1
real, pointer cnlsc2
real, pointer cnlsc3
real, dimension(:,:), pointer snsst
real, pointer sbtc1
real, dimension(:), pointer sbtcx
real, pointer sdbc1
real, pointer sdbc2
logical, pointer fdonly
real, pointer sdbsc
character(len=:), pointer uostfilelocal
character(len=:), pointer uostfileshadow
real, pointer uostfactorlocal
real, pointer uostfactorshadow
logical, pointer fsn
logical, pointer fspsi
logical, pointer fsfct
logical, pointer fsnimp
logical, pointer fstotalimp
logical, pointer fstotalexp
logical, pointer fsrefraction
logical, pointer fsfreqshift
logical, pointer fssource
logical, pointer fsbccfl
logical, pointer do_change_wlv
real(8), pointer solverthr_stp
real(8), pointer crit_dep_stp
logical, pointer b_jgs_terminate_maxiter
logical, pointer b_jgs_terminate_difference
logical, pointer b_jgs_terminate_norm
logical, pointer b_jgs_limiter
logical, pointer b_jgs_use_jacobi
logical, pointer b_jgs_block_gauss_seidel
integer, pointer b_jgs_maxiter
integer, pointer b_jgs_limiter_func
real(8), pointer b_jgs_pmin
real(8), pointer b_jgs_diff_thr
real(8), pointer b_jgs_norm_thr
integer, pointer b_jgs_nlevel
logical, pointer b_jgs_source_nonlinear
real, pointer is1c1
real, pointer is1c2
Function/Subroutine Documentation
w3dims()
subroutine w3gdatmd::w3dims (integer, intent(in) IMOD, integer, intent(in) MK, integer, intent(in) MTH, integer, intent(in) NDSE, integer, intent(in) NDST)
Definition at line 1925 of file w3gdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    19-Feb-2004 : Origination.                        ( version 3.06 )
     !/    18-Jul-2006 : Add input grids.                    ( version 3.10 )
     !/    05-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual spatial grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array GRIDS. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       MK,MTH  Int.   I   Spectral dimensions.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOGR    Subr. W3IOGRMD Model definition file IO program.
     !      WW3_GRID  Prog.   N/A    Model set up program.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - Grid dimensions apre passed through parameter list and then
     !       locally stored to assure consistency between allocation and
     !       data in structure.
     !     - W3SETG needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_ST4
     USE constants, ONLY: rade
 #endif
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, MK, MTH, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER, SAVE           :: MK2, MSPEC
 #ifdef W3_ST4
     INTEGER                  :: SDSNTH
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DIMS')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.ngrids ) THEN
       WRITE (ndse,1002) imod, -nauxgr, ngrids
       CALL extcde (2)
     END IF
     !
     IF ( mk.LT.3 .OR. mth.LT.4 ) THEN
       WRITE (ndse,1003) mk, mth
       CALL extcde (3)
     END IF
     !
     IF ( sgrds(imod)%SINIT ) THEN
       WRITE (ndse,1004)
       CALL extcde (4)
     END IF
     !
     mk2    = mk + 2
     mspec  = mk * mth
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMS)
     WRITE (ndst,9000) imod, mth, mk, mk2, mspec
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     ALLOCATE ( sgrds(imod)%MAPWN(mspec+mth),                        &
          sgrds(imod)%MAPTH(mspec+mth),                        &
          sgrds(imod)%TH(mth),                                 &
          sgrds(imod)%ESIN(mspec+mth),                         &
          sgrds(imod)%ECOS(mspec+mth),                         &
          sgrds(imod)%ES2(mspec+mth),                          &
          sgrds(imod)%ESC(mspec+mth),                          &
          sgrds(imod)%EC2(mspec+mth),                          &
          sgrds(imod)%SIG(0:mk+1),                             &
          sgrds(imod)%SIG2(mspec),                             &
          sgrds(imod)%DSIP(0:mk+1),                            &
          sgrds(imod)%DSII(mk),                                &
          sgrds(imod)%DDEN(mk),                                &
          sgrds(imod)%DDEN2(mspec),                            &
          stat=istat                                           )
     check_alloc_status( istat )
     sgrds(imod)%MAPWN(:)=0.
     sgrds(imod)%MAPTH(:)=0.
     sgrds(imod)%TH(:)=0.
     sgrds(imod)%ESIN(:)=0.
     sgrds(imod)%ECOS(:)=0.
     sgrds(imod)%ES2(:)=0.
     sgrds(imod)%ESC(:)=0.
     sgrds(imod)%EC2(:)=0.
     sgrds(imod)%SIG(:)=0.
     sgrds(imod)%SIG2(:)=0.
     sgrds(imod)%DSIP(:)=0.
     sgrds(imod)%DSII(:)=0.
     sgrds(imod)%DDEN(:)=0.
     sgrds(imod)%DDEN2(:)=0.
 #ifdef W3_ST4
     ALLOCATE ( mpars(imod)%SRCPS%IKTAB(mk,ndtab), &
          mpars(imod)%SRCPS%DCKI(nkhs,nkd),  &
          mpars(imod)%SRCPS%QBI(nkhs,nkd),   &
          stat=istat                         )
     check_alloc_status( istat )
     mpars(imod)%SRCPS%IKTAB(:,:)=0.
     mpars(imod)%SRCPS%DCKI(:,:)=0.
     mpars(imod)%SRCPS%QBI(:,:)=0.
     sdsnth  = mth/2-1 !MIN(NINT(SSDSDTH/(DTH*RADE)),MTH/2-1)
     ALLOCATE( mpars(imod)%SRCPS%SATINDICES(2*sdsnth+1,mth), &
          mpars(imod)%SRCPS%SATWEIGHTS(2*sdsnth+1,mth), &
          mpars(imod)%SRCPS%CUMULW(mspec,mspec),        &
          stat=istat                                   )
     check_alloc_status( istat )
     mpars(imod)%SRCPS%SATINDICES(:,:)=0.
     mpars(imod)%SRCPS%SATWEIGHTS(:,:)=0.
     mpars(imod)%SRCPS%CUMULW(:,:)=0.
 #endif
     !
     sgrds(imod)%SINIT  = .true.
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMS)
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3setg ( imod, ndse, ndst )
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMS)
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !
     nk     = mk
     nk2    = mk + 2
     nth    = mth
     nspec  = mk * mth
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMS)
     WRITE (ndst,9003)
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DIMS : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DIMS : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NAUXGR = ',i10/                   &
          '                    NGRIDS = ',i10/)
 1003 FORMAT (/' *** ERROR W3DIMS : ILLEGAL GRID DIMENSION(S) *** '/  &
          '                    INPUT = ',4i10/)
 1004 FORMAT (/' *** ERROR W3DIMS : ARRAY(S) ALREADY ALLOCATED *** ')
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMS)
 9000 FORMAT (' TEST W3DIMS : MODEL ',i4,' DIM. AT ',3i5,i7)
 9001 FORMAT (' TEST W3DIMS : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DIMS : POINTERS RESET')
 9003 FORMAT (' TEST W3DIMS : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DIMS ----------------------------------------------------- /
     !/
References mpars, nauxgr, ndtab, ngrids, nk, nk2, nkd, nkhs, nspec, nth, constants::rade, sgrds, w3servmd::strace(), and w3setg().
Referenced by wminitmd::wminit(), and wminitmd::wminitnml().
w3dimug()
subroutine w3gdatmd::w3dimug (integer, intent(in) IMOD, integer, intent(in) MTRI, integer, intent(in) MX, integer, intent(in) COUNTOTA, integer, intent(in) NNZ, integer, intent(in) NDSE, integer, intent(in) NDST)
Definition at line 3106 of file w3gdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH-III           NOAA/NCEP |
     !/                  |             F.ardhuin             |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-Mar-2007 !
     !/                  +-----------------------------------+
     !/
     !/    15-Mar-2007 : Origination.                        ( version 3.14 )
     !/    11-May-2015 : Updates to 2-ways nestings for UG   ( version 5.08 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual spatial grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array GRIDS. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       MX, MTRI, MSEA       Like NX, NTRI, NSEA in data structure.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !       See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOGR    Subr. W3IOGRMD Model definition file IO program.
     !      WW3_GRID  Prog.   N/A    Model set up program.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - Grid dimensions apre passed through parameter list and then
     !       locally stored to assure consistency between allocation and
     !       data in structure.
     !     - W3SETG needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, MTRI, MX, COUNTOTA, NNZ, NDSE, NDST
     INTEGER                 :: IAPROC = 1
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DIMUG')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.ngrids ) THEN
       WRITE (ndse,1002) imod, ngrids
       CALL extcde (2)
     END IF
     IF ( grids(imod)%GUGINIT ) THEN
       WRITE (ndse,1004)
       CALL extcde (4)
     END IF
     !
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMUG)
     WRITE (ndst,9000) imod, mx, mtri
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     ALLOCATE ( grids(imod)%TRIGP(3,mtri),                         &
          grids(imod)%SI(mx),                                &
          grids(imod)%XGRD(1,mx),                            &
          grids(imod)%YGRD(1,mx),                            &
          grids(imod)%ZB(mx),                                &
          grids(imod)%TRIA(mtri),                            &
          grids(imod)%CROSSDIFF(6,mtri),                     &
          grids(imod)%IEN(mtri,6),                           &
          grids(imod)%LEN(mtri,3),                           &
          grids(imod)%ANGLE(mtri,3),                         &
          grids(imod)%ANGLE0(mtri,3),                        &
          grids(imod)%CCON(mx),                              &
          grids(imod)%COUNTCON(mx),                          &
          grids(imod)%INDEX_CELL(mx+1),                      &
          grids(imod)%IE_CELL(countota),                     &
          grids(imod)%POS_CELL(countota),                    &
          grids(imod)%IAA(nx+1),                             &
          grids(imod)%JAA(nnz),                              &
          grids(imod)%POSI(3,countota),                      &
          grids(imod)%I_DIAG(nx),                            &
          grids(imod)%JA_IE(3,3,mtri),                       &
          grids(imod)%IOBP(mx),                              &
          grids(imod)%IOBPD(nth,mx),                         &
          grids(imod)%IOBDP(mx),                             &
          grids(imod)%IOBPA(mx),                             &
          stat=istat                                         )
     check_alloc_status( istat )
     !
     grids(imod)%IOBP(:)=1
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMUG)
     WRITE (ndst,9001)
 #endif
     !
     !some segmentation troubles can appear, they are related with the allocation of
     !normal(1st dimension) and the nesting of the triangulated grid.
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3setg ( imod, ndse, ndst )
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMUG)
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !     Note that in the case of lon/lat grids, these quantities do not
     !     include the spherical coordinate metric (SPHERE=.FALSE.).
     !
     ntri   = mtri
     countot=countota
     grids(imod)%GUGINIT  = .true.
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMUG)
     WRITE (ndst,9003)
 #endif
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DIMUG : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DIMUG : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NGRIDS = ',i10/)
 1004 FORMAT (/' *** ERROR W3DIMUG : ARRAY(S) ALREADY ALLOCATED *** ')
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMUG)
 9000 FORMAT (' TEST W3DIMUG: MODEL ',i4,' DIM. AT ',2i5,i7)
 9001 FORMAT (' TEST W3DIMUG : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DIMUG : POINTERS RESET')
 9003 FORMAT (' TEST W3DIMUG : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DIMUG ----------------------------------------------------- /
     !/
References countot, grids, nauxgr, ngrids, nth, ntri, nx, w3servmd::strace(), and w3setg().
Referenced by w3triamd::readmsh().
w3dimx()
subroutine w3gdatmd::w3dimx (integer, intent(in) IMOD, integer, intent(in) MX, integer, intent(in) MY, integer, intent(in) MSEA, integer, intent(in) NDSE, integer, intent(in) NDST, ifdef, W3_SMC)
Definition at line 1582 of file w3gdatmd.F90.
        , mcel, mufc, mvfc, mrlv, mbsmc    &
        , marc, mbac, mspec                &
 #endif
        )
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 |
     !/                  +-----------------------------------+
     !/
     !/    24-Jun-2005 : Origination.                        ( version 3.07 )
     !/    18-Jul-2006 : Add input grids.                    ( version 3.10 )
     !/    05-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    02-Feb-2007 : Add FLAGST.                         ( version 3.10 )
     !/    30-Oct-2009 : Implement run-time grid selection.  ( version 3.14 )
     !/                  (W. E. Rogers & T. J. Campbell, NRL)
     !/    30-Oct-2009 : Implement curvilinear grid type.    ( version 3.14 )
     !/                  (W. E. Rogers & T. J. Campbell, NRL)
     !/    30-Oct-2009 : Implement unstructured grids        ( version 3.14.1)
     !/    03-Sep-2012 : Clean up of UG grids                ( version 4.08 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual spatial grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array GRIDS. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       MX, MY, MSEA       Like NX, NY, NSEA in data structure.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !       See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOGR    Subr. W3IOGRMD Model definition file IO program.
     !      WW3_GRID  Prog.   N/A    Model set up program.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - Grid dimensions apre passed through parameter list and then
     !       locally stored to assure consistency between allocation and
     !       data in structure.
     !     - W3SETG needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, MX, MY, MSEA, NDSE, NDST
 #ifdef W3_SMC
     INTEGER, INTENT(IN)     :: MCel, MUFc, MVFc, MRLv, MBSMC
     INTEGER, INTENT(IN)     :: MARC, MBAC, MSPEC
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_SMC
     INTEGER                 :: IARC, IBAC, IBSMC
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DIMX')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.ngrids ) THEN
       WRITE (ndse,1002) imod, -nauxgr, ngrids
       CALL extcde (2)
     END IF
     !
     IF ( mx.LT.3 .OR. (my.LT.3.AND.gtype.NE.ungtype) .OR. msea.LT.1 ) THEN
       WRITE (ndse,1003) mx, my, msea, gtype
       CALL extcde (3)
     END IF
     !
     IF ( grids(imod)%GINIT ) THEN
       WRITE (ndse,1004)
       CALL extcde (4)
     END IF
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMX)
     WRITE (ndst,9000) imod, mx, my, msea
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     ! NB: Some array start at 0 because MAPFS(IY,IX)=0 for missing points
     !
     IF (gtype .NE. ungtype) THEN
       ALLOCATE ( grids(imod)%ZB(msea),  &
            grids(imod)%XGRD(my,mx),    &
            grids(imod)%YGRD(my,mx),    &
            stat=istat                  )
       check_alloc_status( istat )
     ENDIF
     ALLOCATE ( grids(imod)%MAPSTA(my,mx),  &
          grids(imod)%MAPST2(my,mx),  &
          grids(imod)%MAPFS(my,mx),   &
          grids(imod)%MAPSF(msea,3),  &
          grids(imod)%FLAGST(msea),   &
 #ifdef W3_RTD
          grids(imod)%AnglD(msea),    &
 #endif
          grids(imod)%CLATS(0:msea),  &
          grids(imod)%CLATIS(0:msea), &
          grids(imod)%CTHG0S(0:msea), &
          grids(imod)%TRNX(my,mx),    &
          grids(imod)%TRNY(my,mx),    &
          grids(imod)%DXDP(my,mx),    &
          grids(imod)%DXDQ(my,mx),    &
          grids(imod)%DYDP(my,mx),    &
          grids(imod)%DYDQ(my,mx),    &
          grids(imod)%DPDX(my,mx),    &
          grids(imod)%DPDY(my,mx),    &
          grids(imod)%DQDX(my,mx),    &
          grids(imod)%DQDY(my,mx),    &
          grids(imod)%GSQRT(my,mx),   &
          grids(imod)%HPFAC(my,mx),   &
          grids(imod)%HQFAC(my,mx),   &
          stat=istat                  )
     check_alloc_status( istat )
 #ifdef W3_BT4
     ALLOCATE ( grids(imod)%SED_D50(0:msea), &
          grids(imod)%SED_PSIC(0:msea),&
          stat=istat                 )
     check_alloc_status( istat )
 #endif
     !
 #ifdef W3_SMC
     ALLOCATE ( grids(imod)%NLvCel(0:mrlv),     &
          grids(imod)%NLvUFc(0:mrlv),     &
          grids(imod)%NLvVFc(0:mrlv),     &
          grids(imod)%IJKCel(4, -9:mcel), &
          grids(imod)%IJKUFc(7,mufc),     &
          grids(imod)%IJKVFc(7,mvfc),     &
          grids(imod)%CTRNX(-9:mcel),     &
          grids(imod)%CTRNY(-9:mcel),     &
          grids(imod)%CLATF(mvfc),        &
          stat=istat                      )
     check_alloc_status( istat )
     ALLOCATE ( grids(imod)%IJKCel3(-9:mcel),  &
          grids(imod)%IJKCel4(-9:mcel),  &
          grids(imod)%IJKVFc5(mvfc),     &
          grids(imod)%IJKVFc6(mvfc),     &
          grids(imod)%IJKUFc5(mufc),     &
          grids(imod)%IJKUFc6(mufc),     &
          stat=istat)
     !! Arctic part related variables, declare minimum 1 element.
     iarc = marc
     IF( marc .LE. 1 ) iarc = 1
     ibac = mbac
     IF( mbac .LE. 1 ) ibac = 1
     ibsmc = mbsmc
     IF( mbsmc .LE. 1 ) ibsmc = 1
     ALLOCATE ( grids(imod)%ICLBAC(ibac),       &
          grids(imod)%ANGARC(iarc),       &
          grids(imod)%SPCBAC(mspec,ibac), &
          grids(imod)%ISMCBP(ibsmc),      &
          stat=istat                      )
     check_alloc_status( istat )
     !! All SMC grid related varialbes are initialised in case SMC
     !! switch is selected but SMCTYPE is not used.  JGLi08Mar2021
     grids(imod)%NLvCel(:) = 0
     grids(imod)%NLvUFc(:) = 0
     grids(imod)%NLvVFc(:) = 0
     grids(imod)%ISMCBP(:) = 0
     grids(imod)%ICLBAC(:) = 0
     grids(imod)%IJKCel(:,:) = 0
     grids(imod)%IJKUFc(:,:) = 0
     grids(imod)%IJKVFc(:,:) = 0
     grids(imod)%CTRNX(:)  = 0.0
     grids(imod)%CTRNY(:)  = 0.0
     grids(imod)%CLATF(:)  = 0.0
     grids(imod)%ANGARC(:) = 0.0
 #endif
     !
     grids(imod)%FLAGST = .true.
     grids(imod)%GINIT  = .true.
     grids(imod)%MAPSF(:,3)=0.
     grids(imod)%CLATS(0)=1.
     grids(imod)%CLATIS(0)=1.
     grids(imod)%CTHG0S(0)=1.
     !
 #ifdef W3_REF1
     ALLOCATE ( grids(imod)%RREF(4),     &
          grids(imod)%REFPARS(10), &
          stat=istat               )
     check_alloc_status( istat )
     !
     grids(imod)%RREF(:)=.false.
     grids(imod)%REFPARS(:)=0.
     !
     ! Memory footprint can be reduced by defining REFLC and REFLD only over nodes
     ! where reflection can occur.
     ALLOCATE ( grids(imod)%REFLC(4,0:nsea), &
          grids(imod)%REFLD(6,0:nsea), &
          stat=istat                    )
     check_alloc_status( istat )
 #endif
 #ifdef W3_IG1
     ALLOCATE ( grids(imod)%IGPARS(12), stat=istat )
     check_alloc_status( istat )
 #endif
 #ifdef W3_IC2
     ALLOCATE ( grids(imod)%IC2PARS(9), stat=istat )
     check_alloc_status( istat )
 #endif
 #ifdef W3_IC3
     ALLOCATE ( grids(imod)%IC3PARS(16), stat=istat )
     check_alloc_status( istat )
 #endif
 #ifdef W3_IC4
     ALLOCATE ( grids(imod)%IC4PARS(1), stat=istat )
     check_alloc_status( istat )
     ALLOCATE ( grids(imod)%IC4_KI(nic4), stat=istat )
     check_alloc_status( istat )
     ALLOCATE ( grids(imod)%IC4_FC(nic4), stat=istat )
     check_alloc_status( istat )
     ALLOCATE ( grids(imod)%IC4_CN(nic42), stat=istat )
     check_alloc_status( istat )
 #endif
 #ifdef W3_IC5
     ALLOCATE ( grids(imod)%IC5PARS(9), stat=istat )
     check_alloc_status( istat )
 #endif
 #ifdef W3_IS2
     ALLOCATE ( grids(imod)%IS2PARS(24), stat=istat )
     check_alloc_status( istat )
 #endif
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMX)
     WRITE (ndst,9001)
 #endif
     !
 #ifdef W3_REF1
     grids(imod)%REFLC(1:4,0:nsea)=0.
     grids(imod)%REFLD(:,:)=0
 #endif
 #ifdef W3_IG1
     grids(imod)%IGPARS(:)=0.
 #endif
 #ifdef W3_IC2
     grids(imod)%IC2PARS(:)=0.
 #endif
 #ifdef W3_IS2
     grids(imod)%IS2PARS(:)=0.
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Update counters in grid
     !
     grids(imod)%NX     = mx
     grids(imod)%NY     = my
     grids(imod)%NSEA   = msea
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMX)
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3setg ( imod, ndse, ndst )
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMX)
     WRITE (ndst,9003)
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DIMX : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DIMX : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NAUXGR = ',i10/                   &
          '                    NGRIDS = ',i10/)
 1003 FORMAT (/' *** ERROR W3DIMX : ILLEGAL GRID DIMENSION(S) *** '/  &
          '                    INPUT = ',4i10 /)
 1004 FORMAT (/' *** ERROR W3DIMX : ARRAY(S) ALREADY ALLOCATED *** ')
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3DIMX)
 9000 FORMAT (' TEST W3DIMX : MODEL ',i4,' DIM. AT ',2i5,i7)
 9001 FORMAT (' TEST W3DIMX : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DIMX : DIMENSIONS STORED')
 9003 FORMAT (' TEST W3DIMX : POINTERS RESET')
 #endif
     !/
     !/ End of W3DIMX ----------------------------------------------------- /
     !/
References grids, gtype, nauxgr, ngrids, nic4, nic42, nsea, w3servmd::strace(), ungtype, and w3setg().
Referenced by wminitmd::wminit(), and wminitmd::wminitnml().
w3gntx()
subroutine w3gdatmd::w3gntx (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Definition at line 2881 of file w3gdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH-III           NOAA/NCEP |
     !/                  |           T. J. Campbell          |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         20-Jul-2011 |
     !/                  +-----------------------------------+
     !/
     !/    30-Oct-2009 : Origination.                        ( version 3.13 )
     !/    06-Dec-2010 : Change from GLOBAL (logical) to ICLOSE (integer) to
     !/                  specify index closure for a grid.   ( version 3.14 )
     !/                  (T. J. Campbell, NRL)
     !/    23-Dec-2010 : Fix HPFAC and HQFAC by including the COS(YGRD)
     !/                  factor with DXDP and DXDQ terms.    ( version 3.14 )
     !/                  (T. J. Campbell, NRL)
     !/    20-Jul-2011 : HPFAC and HQFAC are now calculated using W3DIST.
     !/                  Result should be very similar except near pole.
     !/                  Due to precision issues, HPFAC and HQFAC revert
     !/                  to SX and SY in case of regular grids.
     !/                  (W. E. Rogers, NRL)                 ( version 3.14 )
     !/    20-Jan-2017 : Update to new W3GSRUMD APIs         ( version 6.02 )
     !/    20-Jan-2017 : Change calculation of curvilinear grid metric and
     !/                  derivatives calculations to use W3GSRUMD:W3CGDM.
     !/                  (T.J. Campbell, NRL)                ( version 6.02 )
     !/
     !  1. Purpose :
     !
     !     Construct required spatial grid quantities for curvilinear grids.
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Check on previous initialization of grids.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER, PARAMETER :: NFD    = 4
     LOGICAL, PARAMETER :: PTILED = .false.
     LOGICAL, PARAMETER :: QTILED = .false.
     LOGICAL, PARAMETER :: IJG    = .false.
     LOGICAL, PARAMETER :: SPHERE = .false.
     INTEGER :: PRANGE(2), QRANGE(2)
     INTEGER :: LBI(2), UBI(2), LBO(2), UBO(2), ISTAT
     REAL   , ALLOCATABLE :: COSA(:,:)
 #ifdef W3_S
     INTEGER, SAVE      :: IENT = 0
     CALL strace (ient, 'W3GNTX')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.ngrids ) THEN
       WRITE (ndse,1002) imod, -nauxgr, ngrids
       CALL extcde (2)
     END IF
     !
     SELECT CASE ( grids(imod)%GTYPE )
     CASE ( rlgtype )
     CASE ( clgtype )
     CASE ( smctype )
     CASE DEFAULT
       WRITE (ndse,1003) grids(imod)%GTYPE
       CALL extcde (3)
     END SELECT
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Create grid search utility object
     !
     grids(imod)%GSU = w3gsuc( ijg, flagll, grids(imod)%ICLOSE, &
          grids(imod)%XGRD, grids(imod)%YGRD )
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
     CALL w3gsup(grids(imod)%GSU, ndst)
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Reset grid pointers
     !
     CALL w3setg ( imod, ndse, ndst )
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Construct curvilinear grid derivatives and metric
     !     Note that in the case of lon/lat grids, these quantities do not
     !     include the spherical coordinate metric (SPHERE=.FALSE.).
     !
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
     ALLOCATE ( cosa(ny,nx), stat=istat )
     check_alloc_status( istat )
 #endif
     prange = (/ 1,nx/)
     qrange = (/ 1,ny/)
     lbi = (/ 1, 1/)
     ubi = (/ny,nx/)
     lbo = (/ 1, 1/)
     ubo = (/ny,nx/)
     SELECT CASE ( gtype )
       !!Li  SMC grid shares the settings with rectilinear grid. JGLi12Oct2020
     CASE ( rlgtype, smctype )
       CALL w3cgdm( ijg, flagll, iclose, ptiled, qtiled,            &
            prange, qrange, lbi, ubi, lbo, ubo, real(xgrd), real(ygrd), &
            nfd=nfd, sphere=sphere, dx=sx, dy=sy,           &
            dxdp=dxdp, dydp=dydp, dxdq=dxdq, dydq=dydq,     &
            dpdx=dpdx, dpdy=dpdy, dqdx=dqdx, dqdy=dqdy,     &
            hpfc=hpfac, hqfc=hqfac, gsqr=gsqrt,             &
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
            cosa=cosa,                                      &
 #endif
            rc=istat )
       IF ( istat.NE.0 ) THEN
         WRITE (ndse,1004) gtype
         CALL extcde (4)
       END IF
     CASE ( clgtype )
       CALL w3cgdm( ijg, flagll, iclose, ptiled, qtiled,            &
            prange, qrange, lbi, ubi, lbo, ubo, real(xgrd), real(ygrd), &
            nfd=nfd, sphere=sphere,                         &
            dxdp=dxdp, dydp=dydp, dxdq=dxdq, dydq=dydq,     &
            dpdx=dpdx, dpdy=dpdy, dqdx=dqdx, dqdy=dqdy,     &
            hpfc=hpfac, hqfc=hqfac, gsqr=gsqrt,             &
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
            cosa=cosa,                                      &
 #endif
            rc=istat )
       IF ( istat.NE.0 ) THEN
         WRITE (ndse,1004) gtype
         CALL extcde (4)
       END IF
     END SELECT
     !
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
     WRITE(ndst,'(A,2E14.6)')'HPFAC MIN/MAX:',minval(hpfac),maxval(hpfac)
     WRITE(ndst,'(A,2E14.6)')'HQFAC MIN/MAX:',minval(hqfac),maxval(hqfac)
     WRITE(ndst,'(A,2E14.6)')'GSQRT MIN/MAX:',minval(gsqrt),maxval(gsqrt)
     WRITE(ndst,'(A,2E14.6)')'DXDP  MIN/MAX:',minval(dxdp),maxval(dxdp)
     WRITE(ndst,'(A,2E14.6)')'DYDP  MIN/MAX:',minval(dydp),maxval(dydp)
     WRITE(ndst,'(A,2E14.6)')'DXDQ  MIN/MAX:',minval(dxdq),maxval(dxdq)
     WRITE(ndst,'(A,2E14.6)')'DYDQ  MIN/MAX:',minval(dydq),maxval(dydq)
     WRITE(ndst,'(A,2E14.6)')'DPDX  MIN/MAX:',minval(dpdx),maxval(dpdx)
     WRITE(ndst,'(A,2E14.6)')'DPDY  MIN/MAX:',minval(dpdy),maxval(dpdy)
     WRITE(ndst,'(A,2E14.6)')'DQDX  MIN/MAX:',minval(dqdx),maxval(dqdx)
     WRITE(ndst,'(A,2E14.6)')'DQDY  MIN/MAX:',minval(dqdy),maxval(dqdy)
     WRITE(ndst,'(A,2E14.6)')'COSA  MIN/MAX:',minval(cosa),maxval(cosa)
     WRITE (ndst,9003)
     DEALLOCATE ( cosa, stat=istat )
     check_dealloc_status( istat )
 #endif
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3GNTX : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3GNTX : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NAUXGR = ',i10/                   &
          '                    NGRIDS = ',i10/)
 1003 FORMAT (/' *** ERROR W3GNTX : UNSUPPORTED TYPE OF GRID *** '/   &
          '                    GTYPE  = ',i10/)
 1004 FORMAT (/' *** ERROR W3GNTX : ERROR OCCURED IN W3CGDM *** '/    &
          '                    GTYPE  = ',i10/)
     !
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3GNTX)
 9000 FORMAT (' TEST W3GNTX : MODEL ',i4)
 9001 FORMAT (' TEST W3GNTX : SEARCH OBJECT CREATED')
 9002 FORMAT (' TEST W3GNTX : POINTERS RESET')
 9003 FORMAT (' TEST W3GNTX : GRID ARRAYS CONSTRUCTED')
 #endif
     !/
     !/ End of W3GNTX ----------------------------------------------------- /
     !/
References clgtype, dpdx, dpdy, dqdx, dqdy, dxdp, dxdq, dydp, dydq, flagll, grids, gsqrt, gtype, hpfac, hqfac, iclose, nauxgr, ngrids, nx, ny, rlgtype, smctype, w3servmd::strace(), sx, sy, w3gsrumd::w3gsup(), w3setg(), xgrd, and ygrd.
w3nmod()
subroutine w3gdatmd::w3nmod (integer, intent(in) NUMBER, integer, intent(in) NDSE, integer, intent(in) NDST, integer, intent(in), optional NAUX)
Definition at line 1433 of file w3gdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    24-Feb-2004 : Origination.                        ( version 3.06 )
     !/    18-Jul-2006 : Add input grids.                    ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Set up the number of grids to be used.
     !
     !  2. Method :
     !
     !     Store in NGRIDS and allocate GRIDS.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NUMBER  Int.   I   Number of grids to be used.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       NAUX    Int.   I   Number of auxiliary grids to be used.
     !                          Grids -NAUX:NUBMER are defined, optional
     !                          parameters.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Error checks on previous setting of variable.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: NUMBER, NDSE, NDST
     INTEGER, INTENT(IN), OPTIONAL :: NAUX
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: I, NLOW
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3NMOD')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .NE. -1 ) THEN
       WRITE (ndse,1001) ngrids
       CALL extcde (1)
     END IF
     !
     IF ( number .LT. 1 ) THEN
       WRITE (ndse,1002) number
       CALL extcde (2)
     END IF
     !
     IF ( PRESENT(naux) ) THEN
       nlow   = -naux
     ELSE
       nlow   = 1
     END IF
     !
     IF ( nlow .GT. 1 ) THEN
       WRITE (ndse,1003) -nlow
       CALL extcde (3)
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Set variable and allocate arrays
     !
     ngrids = number
     nauxgr = - nlow
     ALLOCATE ( grids(nlow:number), &
          sgrds(nlow:number), &
          mpars(nlow:number), &
          stat=istat )
     check_alloc_status( istat )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Initialize GINIT and SINIT
     !
     DO i=nlow, number
       grids(i)%GINIT  = .false.
       grids(i)%GUGINIT  = .false.
       sgrds(i)%SINIT  = .false.
       mpars(i)%PINIT  = .false.
 #ifdef W3_NL2
       mpars(i)%SNLPS%NDPTHS = 0
 #endif
     END DO
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3NMOD)
     WRITE (ndst,9000) nlow, ngrids
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3NMOD : GRIDS ALREADY INITIALIZED *** '/  &
          '                    NGRIDS = ',i10/)
 1002 FORMAT (/' *** ERROR W3NMOD : ILLEGAL NUMBER OF GRIDS *** '/    &
          '                    NUMBER = ',i10/)
 1003 FORMAT (/' *** ERROR W3NMOD : ILLEGAL NUMBER OF AUX GRIDS *** '/&
          '                    NUMBER = ',i10/)
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3NMOD)
 9000 FORMAT (' TEST W3NMOD : SETTING UP FOR GRIDS ',i3,           &
          ' THROUGH ',i3)
 #endif
     !/
     !/ End of W3NMOD ----------------------------------------------------- /
     !/
References grids, mpars, nauxgr, ngrids, sgrds, and w3servmd::strace().
Referenced by gxoutf(), gxoutp(), w3bounc(), w3bound(), w3grib(), w3gridmd::w3grid(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3strt(), w3trck(), w3trnc(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().
w3setg()
subroutine w3gdatmd::w3setg (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Definition at line 2152 of file w3gdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  !           J. H. Alves             !
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         03-Sep-2012 |
     !/                  +-----------------------------------+
     !/
     !/    24-Jun-2005 : Origination.                        ( version 3.07 )
     !/    09-Nov-2005 : Remove soft boundary options.       ( version 3.08 )
     !/    23-Jun-2006 : Add data for W3SLN1.                ( version 3.09 )
     !/    18-Jul-2006 : Add input grids.                    ( version 3.10 )
     !/    05-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    02-Feb-2007 : Add FLAGST.                         ( version 3.10 )
     !/    14-Apr-2007 : Add Miche style limiter.            ( version 3.11 )
     !/                  ( J. H. Alves )
     !/    25-Apr-2007 : Adding Battjes-Janssen Sdb.         ( version 3.11 )
     !/                  ( J. H. Alves )
     !/    18-Sep-2007 : Adding WAM4 source terms.           ( version 3.13 )
     !/                  ( F. Ardhuin )
     !/    27-Jun-2008 : Expand WAM4 variants namelist       ( version 3.14 )
     !/                  ( F. Ardhuin )
     !/    30-Oct-2009 : Implement run-time grid selection.  ( version 3.14 )
     !/                  (W. E. Rogers & T. J. Campbell, NRL)
     !/    30-Oct-2009 : Implement curvilinear grid type.    ( version 3.14 )
     !/                  (W. E. Rogers & T. J. Campbell, NRL)
     !/    06-Dec-2010 : Change from GLOBAL (logical) to ICLOSE (integer) to
     !/                  specify index closure for a grid.   ( version 3.14 )
     !/                  (T. J. Campbell, NRL)
     !/    13-Jul-2012 : Move data structures GMD (SNL3) and nonlinear
     !/                  filter (SNLS) from 3.15 (HLT).      ( version 4.08 )
     !/    03-Sep-2012 : Clean up of UG grids                ( version 4.08 )
     !/
     !  1. Purpose :
     !
     !     Select one of the WAVEWATCH III grids / models.
     !
     !  2. Method :
     !
     !     Point pointers to the proper variables in the proper element of
     !     the GRIDS array.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Many subroutines in eth WAVEWATCH system.
     !
     !  6. Error messages :
     !
     !     Checks on parameter list IMOD.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/PRn  Select propagation scheme
     !
     !     !/STn  Select source terms
     !     !/NLn
     !     !/BTn
     !
     !     !/S    Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3SETG')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.ngrids ) THEN
       WRITE (ndse,1002) imod, -nauxgr, ngrids
       CALL extcde (2)
     END IF
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3SETG)
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model numbers
     !
     igrid  = imod
     isgrd  = imod
     ipars  = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers in structure GRID
     !
     gtype  => grids(imod)%GTYPE
     rstype => grids(imod)%RSTYPE
     iclose => grids(imod)%ICLOSE
     !
     nx     => grids(imod)%NX
     ny     => grids(imod)%NY
     nsea   => grids(imod)%NSEA
     nseal  => grids(imod)%NSEAL
     trflag => grids(imod)%TRFLAG
     flagll => grids(imod)%FLAGLL
     !
 #ifdef W3_SMC
     ncel   => grids(imod)%NCel
     nufc   => grids(imod)%NUFc
     nvfc   => grids(imod)%NVFc
     nrlv   => grids(imod)%NRLv
     mrfct  => grids(imod)%MRFct
     nglo   => grids(imod)%NGLO
     narc   => grids(imod)%NARC
     nbgl   => grids(imod)%NBGL
     nbac   => grids(imod)%NBAC
     nbsmc  => grids(imod)%NBSMC
 #endif
     !
     e3df   => grids(imod)%E3DF
     p2msf  => grids(imod)%P2MSF
     us3df  => grids(imod)%US3DF
     usspf  => grids(imod)%USSPF
     ussp_wn => grids(imod)%USSP_WN
     ffacberg => grids(imod)%FFACBERG
 #ifdef W3_REF1
     reflc  => grids(imod)%REFLC
     refld  => grids(imod)%REFLD
     rref   => grids(imod)%RREF
     refpars=> grids(imod)%REFPARS
 #endif
 #ifdef W3_IG1
     igpars => grids(imod)%IGPARS
 #endif
 #ifdef W3_IC2
     ic2pars => grids(imod)%IC2PARS
 #endif
 #ifdef W3_IC3
     ic3pars => grids(imod)%IC3PARS
 #endif
 #ifdef W3_IC4
     ic4pars => grids(imod)%IC4PARS
     ic4_ki => grids(imod)%IC4_KI
     ic4_fc => grids(imod)%IC4_FC
     ic4_cn => grids(imod)%IC4_CN
     ic4_fmin => grids(imod)%IC4_FMIN
     ic4_kibk => grids(imod)%IC4_KIBK
 #endif
 #ifdef W3_IC5
     ic5pars => grids(imod)%IC5PARS
 #endif
 #ifdef W3_IS2
     is2pars => grids(imod)%IS2PARS
 #endif
     sx     => grids(imod)%SX
     sy     => grids(imod)%SY
     x0     => grids(imod)%X0
     y0     => grids(imod)%Y0
     !
     dtcfl  => grids(imod)%DTCFL
     dtcfli => grids(imod)%DTCFLI
     dtmax  => grids(imod)%DTMAX
     dtmin  => grids(imod)%DTMIN
     dmin   => grids(imod)%DMIN
 #ifdef W3_SEC1
     nitersec1  => grids(imod)%NITERSEC1
 #endif
     ctmax  => grids(imod)%CTMAX
     fice0  => grids(imod)%FICE0
     gridshift  => grids(imod)%GRIDSHIFT
     cmprtrck => grids(imod)%CMPRTRCK
 #ifdef W3_RTD
     polat  => grids(imod)%PoLat
     polon  => grids(imod)%PoLon
     flagunr  => grids(imod)%FLAGUNR
 #endif
     ficen  => grids(imod)%FICEN
     ficel  => grids(imod)%FICEL
     iicehmin  => grids(imod)%IICEHMIN
     iicehdisp  => grids(imod)%IICEHDISP
     iicefdisp  => grids(imod)%IICEFDISP
     iiceddisp  => grids(imod)%IICEDDISP
     iicehfac  => grids(imod)%IICEHFAC
     iicehinit  => grids(imod)%IICEHINIT
     icescales  => grids(imod)%ICESCALES
     pfmove => grids(imod)%PFMOVE
     stexu  => grids(imod)%STEXU
     steyu  => grids(imod)%STEYU
     stedu  => grids(imod)%STEDU
     btbeta => grids(imod)%BTBETA
     aairgb => grids(imod)%AAIRGB
     aaircmin => grids(imod)%AAIRCMIN
     !
     ginit  => grids(imod)%GINIT
     guginit  => grids(imod)%GUGINIT
     fldry  => grids(imod)%FLDRY
     flcx   => grids(imod)%FLCX
     flcy   => grids(imod)%FLCY
     flcth  => grids(imod)%FLCTH
     flck   => grids(imod)%FLCK
     flsou  => grids(imod)%FLSOU
     iicedisp => grids(imod)%IICEDISP
     iicesmooth => grids(imod)%IICESMOOTH
     !
     gname  => grids(imod)%GNAME
     filext => grids(imod)%FILEXT
     trigp  => grids(imod)%TRIGP
     ntri     => grids(imod)%NTRI
     countri     => grids(imod)%COUNTRI
     si     => grids(imod)%SI
     countot    => grids(imod)%COUNTOT
     ien     => grids(imod)%IEN
     len     => grids(imod)%LEN
     angle     => grids(imod)%ANGLE
     angle0     => grids(imod)%ANGLE0
     ccon     => grids(imod)%CCON
     countcon     => grids(imod)%COUNTCON
     index_cell  => grids(imod)%INDEX_CELL
     ie_cell     => grids(imod)%IE_CELL
     pos_cell     => grids(imod)%POS_CELL
     iobp     => grids(imod)%IOBP
     iaa      => grids(imod)%IAA
     jaa      => grids(imod)%JAA
     posi     => grids(imod)%POSI
     i_diag     => grids(imod)%I_DIAG
     ja_ie     => grids(imod)%JA_IE
     nbedge    => grids(imod)%NBEDGE
     edges     => grids(imod)%EDGES
     neigh     => grids(imod)%NEIGH
     nnz      => grids(imod)%NNZ
     iobpd     => grids(imod)%IOBPD
     iobdp     => grids(imod)%IOBDP
     iobpa     => grids(imod)%IOBPA
     tria     => grids(imod)%TRIA
     crossdiff => grids(imod)%CROSSDIFF
     maxx     => grids(imod)%MAXX
     maxy     => grids(imod)%MAXY
     dxymax   => grids(imod)%DXYMAX
     xgrd   => grids(imod)%XGRD
     ygrd   => grids(imod)%YGRD
     zb     => grids(imod)%ZB
     !
     IF ( ginit ) THEN
       !
       mapsta => grids(imod)%MAPSTA
       mapst2 => grids(imod)%MAPST2
       mapfs  => grids(imod)%MAPFS
       mapsf  => grids(imod)%MAPSF
       flagst => grids(imod)%FLAGST
       !
 #ifdef W3_RTD
       angld  => grids(imod)%AnglD
 #endif
       clats  => grids(imod)%CLATS
       clatis => grids(imod)%CLATIS
       cthg0s => grids(imod)%CTHG0S
       trnx   => grids(imod)%TRNX
       trny   => grids(imod)%TRNY
       !
       dxdp   => grids(imod)%DXDP
       dxdq   => grids(imod)%DXDQ
       dydp   => grids(imod)%DYDP
       dydq   => grids(imod)%DYDQ
       dpdx   => grids(imod)%DPDX
       dpdy   => grids(imod)%DPDY
       dqdx   => grids(imod)%DQDX
       dqdy   => grids(imod)%DQDY
       gsqrt  => grids(imod)%GSQRT
       hpfac  => grids(imod)%HPFAC
       hqfac  => grids(imod)%HQFAC
       !
 #ifdef W3_BT4
       sed_d50  => grids(imod)%SED_D50
       sed_psic => grids(imod)%SED_PSIC
 #endif
       !
 #ifdef W3_SMC
       nlvcel => grids(imod)%NLvCel
       nlvufc => grids(imod)%NLvUFc
       nlvvfc => grids(imod)%NLvVFc
       ijkcel => grids(imod)%IJKCel
       ijkufc => grids(imod)%IJKUFc
       ijkvfc => grids(imod)%IJKVFc
       ismcbp => grids(imod)%ISMCBP
       ctrnx  => grids(imod)%CTRNX
       ctrny  => grids(imod)%CTRNY
       clatf  => grids(imod)%CLATF
       ijkcel3 => grids(imod)%IJKCel3
       ijkcel4 => grids(imod)%IJKCel4
       ijkvfc5 => grids(imod)%IJKVFc5
       ijkvfc6 => grids(imod)%IJKVFc6
       ijkufc5 => grids(imod)%IJKUFc5
       ijkufc6 => grids(imod)%IJKUFc6
       iclbac => grids(imod)%ICLBAC
       angarc => grids(imod)%ANGARC
       spcbac => grids(imod)%SPCBAC
 #endif
       !
       gsu  => grids(imod)%GSU
       !
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Set pointers in structure SGRD
     !
     nk     => sgrds(imod)%NK
     nk2    => sgrds(imod)%NK2
     nth    => sgrds(imod)%NTH
     nspec  => sgrds(imod)%NSPEC
     !
     dth    => sgrds(imod)%DTH
     xfr    => sgrds(imod)%XFR
     fr1    => sgrds(imod)%FR1
     fte    => sgrds(imod)%FTE
     ftf    => sgrds(imod)%FTF
     ftwn   => sgrds(imod)%FTWN
     fttr   => sgrds(imod)%FTTR
     ftwl   => sgrds(imod)%FTWL
     facti1 => sgrds(imod)%FACTI1
     facti2 => sgrds(imod)%FACTI2
     fachfa => sgrds(imod)%FACHFA
     fachfe => sgrds(imod)%FACHFE
     !
     sinit  => sgrds(imod)%SINIT
     !
     IF ( sinit ) THEN
       !
       mapwn  => sgrds(imod)%MAPWN
       mapth  => sgrds(imod)%MAPTH
       !
       th     => sgrds(imod)%TH
       esin   => sgrds(imod)%ESIN
       ecos   => sgrds(imod)%ECOS
       es2    => sgrds(imod)%ES2
       esc    => sgrds(imod)%ESC
       ec2    => sgrds(imod)%EC2
       sig    => sgrds(imod)%SIG
       sig2   => sgrds(imod)%SIG2
       dsip   => sgrds(imod)%DSIP
       dsii   => sgrds(imod)%DSII
       dden   => sgrds(imod)%DDEN
       dden2  => sgrds(imod)%DDEN2
       !
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Set pointers in structure MPAR
     !
     pinit  => mpars(imod)%PINIT
     !
     !     Structure NPARS
     !
     facp   => mpars(imod)%NPARS%FACP
     xrel   => mpars(imod)%NPARS%XREL
     xflt   => mpars(imod)%NPARS%XFLT
     fxfm   => mpars(imod)%NPARS%FXFM
     fxpm   => mpars(imod)%NPARS%FXPM
     xft    => mpars(imod)%NPARS%XFT
     xfc    => mpars(imod)%NPARS%XFC
     facsd  => mpars(imod)%NPARS%FACSD
     fhmax  => mpars(imod)%NPARS%FHMAX
 #ifdef W3_RWND
     rwindc => mpars(imod)%NPARS%RWINDC
 #endif
 #ifdef W3_WCOR
     wwcor  => mpars(imod)%NPARS%WWCOR
 #endif
     !
     !     Structure PROPS
     !
 #ifdef W3_PR2
     dtme   => mpars(imod)%PROPS%DTME
     clatmn => mpars(imod)%PROPS%CLATMN
 #endif
 #ifdef W3_PR3
     wdcg   => mpars(imod)%PROPS%WDCG
     wdth   => mpars(imod)%PROPS%WDTH
 #endif
 #ifdef W3_SMC
     dtms   => mpars(imod)%PROPS%DTMS
     refran => mpars(imod)%PROPS%Refran
     funo3  => mpars(imod)%PROPS%FUNO3
     fverg  => mpars(imod)%PROPS%FVERG
     fswnd  => mpars(imod)%PROPS%FSWND
     arctc  => mpars(imod)%PROPS%ARCTC
 #endif
     !
     !     Structure FLDP
     !
 #ifdef W3_FLD1
     tail_id  => mpars(imod)%FLDPS%TAIL_ID
     tail_lev => mpars(imod)%FLDPS%TAIL_LEV
     tail_tran1 => mpars(imod)%FLDPS%TAIL_TRAN1
     tail_tran2 => mpars(imod)%FLDPS%TAIL_TRAN2
 #endif
 #ifdef W3_FLD2
     tail_id  => mpars(imod)%FLDPS%TAIL_ID
     tail_lev => mpars(imod)%FLDPS%TAIL_LEV
     tail_tran1 => mpars(imod)%FLDPS%TAIL_TRAN1
     tail_tran2 => mpars(imod)%FLDPS%TAIL_TRAN2
 #endif
     !
     !     Structure SFLPS
     !
 #ifdef W3_FLX2
     nittin => mpars(imod)%SFLPS%NITTIN
     cinxsi => mpars(imod)%SFLPS%CINXSI
 #endif
 #ifdef W3_FLX3
     nittin => mpars(imod)%SFLPS%NITTIN
     cap_id => mpars(imod)%SFLPS%CAP_ID
     cinxsi => mpars(imod)%SFLPS%CINXSI
     cd_max => mpars(imod)%SFLPS%CD_MAX
 #endif
 #ifdef W3_FLX4
     flx4a0 => mpars(imod)%SFLPS%FLX4A0
 #endif
     !
     !     Structure SLNPS
     !
 #ifdef W3_LN1
     slnc1  => mpars(imod)%SLNPS%SLNC1
     fspm   => mpars(imod)%SLNPS%FSPM
     fshf   => mpars(imod)%SLNPS%FSHF
 #endif
     !
     !     Structure SRCPS
     !
     wwnmeanptail=> mpars(imod)%SRCPS%WWNMEANPTAIL
     sstxftftail => mpars(imod)%SRCPS%SSTXFTFTAIL
 #ifdef W3_ST1
     sinc1  => mpars(imod)%SRCPS%SINC1
     sdsc1  => mpars(imod)%SRCPS%SDSC1
 #endif
 #ifdef W3_ST2
     zwind  => mpars(imod)%SRCPS%ZWIND
     fswell => mpars(imod)%SRCPS%FSWELL
     shstab => mpars(imod)%SRCPS%SHSTAB
     ofstab => mpars(imod)%SRCPS%OFSTAB
     ccng   => mpars(imod)%SRCPS%CCNG
     ccps   => mpars(imod)%SRCPS%CCPS
     ffng   => mpars(imod)%SRCPS%FFNG
     ffps   => mpars(imod)%SRCPS%FFPS
     cdsa0  => mpars(imod)%SRCPS%CDSA0
     cdsa1  => mpars(imod)%SRCPS%CDSA1
     cdsa2  => mpars(imod)%SRCPS%CDSA2
     sdsaln => mpars(imod)%SRCPS%SDSALN
     cdsb0  => mpars(imod)%SRCPS%CDSB0
     cdsb1  => mpars(imod)%SRCPS%CDSB1
     cdsb2  => mpars(imod)%SRCPS%CDSB2
     cdsb3  => mpars(imod)%SRCPS%CDSB3
     fpimin => mpars(imod)%SRCPS%FPIMIN
     xfh    => mpars(imod)%SRCPS%XFH
     xf1    => mpars(imod)%SRCPS%XF1
     xf2    => mpars(imod)%SRCPS%XF2
 #endif
     !
 #ifdef W3_ST3
     zzwnd  => mpars(imod)%SRCPS%ZZWND
     aalpha => mpars(imod)%SRCPS%AALPHA
     bbeta  => mpars(imod)%SRCPS%BBETA
     ssinthp  => mpars(imod)%SRCPS%SSINTHP
     zz0max  => mpars(imod)%SRCPS%ZZ0MAX
     zz0rat  => mpars(imod)%SRCPS%ZZ0RAT
     zzalp  => mpars(imod)%SRCPS%ZZALP
     ttauwshelter  => mpars(imod)%SRCPS%TTAUWSHELTER
     sswellf  => mpars(imod)%SRCPS%SSWELLF
     ssdsc1 => mpars(imod)%SRCPS%SSDSC1
     wwnmeanp => mpars(imod)%SRCPS%WWNMEANP
     ffxfm => mpars(imod)%SRCPS%FFXFM
     ffxpm => mpars(imod)%SRCPS%FFXPM
     ddelta1 => mpars(imod)%SRCPS%DDELTA1
     ddelta2 => mpars(imod)%SRCPS%DDELTA2
     sstxftf => mpars(imod)%SRCPS%SSTXFTF
     sstxftwn => mpars(imod)%SRCPS%SSTXFTWN
 #endif
     !
 #ifdef W3_ST4
     zzwnd    => mpars(imod)%SRCPS%ZZWND
     aalpha   => mpars(imod)%SRCPS%AALPHA
     bbeta    => mpars(imod)%SRCPS%BBETA
     ssinthp  => mpars(imod)%SRCPS%SSINTHP
     zz0max   => mpars(imod)%SRCPS%ZZ0MAX
     zz0rat   => mpars(imod)%SRCPS%ZZ0RAT
     zzalp    => mpars(imod)%SRCPS%ZZALP
     ttauwshelter  => mpars(imod)%SRCPS%TTAUWSHELTER
     sintailpar  => mpars(imod)%SRCPS%SINTAILPAR
     capchnk  => mpars(imod)%SRCPS%CAPCHNK
     sswellfpar  => mpars(imod)%SRCPS%SSWELLFPAR
     sswellf  => mpars(imod)%SRCPS%SSWELLF
     ssdsc    => mpars(imod)%SRCPS%SSDSC
     ssdsbr   => mpars(imod)%SRCPS%SSDSBR
     ssdsbt   => mpars(imod)%SRCPS%SSDSBT
     ssdsbrf1 => mpars(imod)%SRCPS%SSDSBRF1
     ssdsbrf2 => mpars(imod)%SRCPS%SSDSBRF2
     ssdsbrfdf  => mpars(imod)%SRCPS%SSDSBRFDF
     ssdsbm   => mpars(imod)%SRCPS%SSDSBM
     ssdsbck  => mpars(imod)%SRCPS%SSDSBCK
     ssdsabk  => mpars(imod)%SRCPS%SSDSABK
     ssdspbk  => mpars(imod)%SRCPS%SSDSPBK
     ssdshck  => mpars(imod)%SRCPS%SSDSHCK
     ssdsbint => mpars(imod)%SRCPS%SSDSBINT
     ssdsp    => mpars(imod)%SRCPS%SSDSP
     wwnmeanp => mpars(imod)%SRCPS%WWNMEANP
     ffxfm    => mpars(imod)%SRCPS%FFXFM
     ffxfa    => mpars(imod)%SRCPS%FFXFA
     ffxpm    => mpars(imod)%SRCPS%FFXPM
     ssdsdth  => mpars(imod)%SRCPS%SSDSDTH
     sstxftf  => mpars(imod)%SRCPS%SSTXFTF
     sstxftwn => mpars(imod)%SRCPS%SSTXFTWN
     ssdscos  => mpars(imod)%SRCPS%SSDSCOS
     ssdsiso  => mpars(imod)%SRCPS%SSDSISO
     iktab    => mpars(imod)%SRCPS%IKTAB
     dcki     => mpars(imod)%SRCPS%DCKI
     qbi      => mpars(imod)%SRCPS%QBI
     cumulw   => mpars(imod)%SRCPS%CUMULW
     satindices    => mpars(imod)%SRCPS%SATINDICES
     satweights   => mpars(imod)%SRCPS%SATWEIGHTS
     ssinbr   => mpars(imod)%SRCPS%SSINBR
 #endif
     !
 #ifdef W3_ST6
     sin6a0 => mpars(imod)%SRCPS%SIN6A0
     sin6ws => mpars(imod)%SRCPS%SIN6WS
     sin6fc => mpars(imod)%SRCPS%SIN6FC
     sds6et => mpars(imod)%SRCPS%SDS6ET
     sds6a1 => mpars(imod)%SRCPS%SDS6A1
     sds6p1 => mpars(imod)%SRCPS%SDS6P1
     sds6a2 => mpars(imod)%SRCPS%SDS6A2
     sds6p2 => mpars(imod)%SRCPS%SDS6P2
     swl6s6 => mpars(imod)%SRCPS%SWL6S6
     swl6b1 => mpars(imod)%SRCPS%SWL6B1
     swl6cstb1 => mpars(imod)%SRCPS%SWL6CSTB1
 #endif
     !
     !     Structure SRNLS
     !
 #ifdef W3_NL1
     snlc1  => mpars(imod)%SNLPS%SNLC1
     lam    => mpars(imod)%SNLPS%LAM
     kdcon  => mpars(imod)%SNLPS%KDCON
     kdmn   => mpars(imod)%SNLPS%KDMN
     snls1  => mpars(imod)%SNLPS%SNLS1
     snls2  => mpars(imod)%SNLPS%SNLS2
     snls3  => mpars(imod)%SNLPS%SNLS3
     iqtpe  => mpars(imod)%SNLPS%IQTPE
     gqnf1  => mpars(imod)%SNLPS%GQNF1
     gqnt1  => mpars(imod)%SNLPS%GQNT1
     gqnq_om2  => mpars(imod)%SNLPS%GQNQ_OM2
     nltail => mpars(imod)%SNLPS%NLTAIL
     gqthrsat => mpars(imod)%SNLPS%GQTHRSAT
     gqthrcou=> mpars(imod)%SNLPS%GQTHRCOU
     gqamp=> mpars(imod)%SNLPS%GQAMP
 #endif
 #ifdef W3_NL2
     iqtpe  => mpars(imod)%SNLPS%IQTPE
     ndpths => mpars(imod)%SNLPS%NDPTHS
     nltail => mpars(imod)%SNLPS%NLTAIL
     IF ( ndpths .NE. 0 ) dpthnl => mpars(imod)%SNLPS%DPTHNL
 #endif
 #ifdef W3_NL3
     nfrmin => mpars(imod)%SNLPS%NFRMIN
     nfrmax => mpars(imod)%SNLPS%NFRMAX
     nfrcut => mpars(imod)%SNLPS%NFRCUT
     nthmax => mpars(imod)%SNLPS%NTHMAX
     nthexp => mpars(imod)%SNLPS%NTHEXP
     nspmin => mpars(imod)%SNLPS%NSPMIN
     nspmax => mpars(imod)%SNLPS%NSPMAX
     nspmx2 => mpars(imod)%SNLPS%NSPMX2
     frq    => mpars(imod)%SNLPS%FRQ
     xsi    => mpars(imod)%SNLPS%XSI
     nqa    => mpars(imod)%SNLPS%NQA
     qst1   => mpars(imod)%SNLPS%QST1
     qst2   => mpars(imod)%SNLPS%QST2
     qst3   => mpars(imod)%SNLPS%QST3
     qst4   => mpars(imod)%SNLPS%QST4
     qst5   => mpars(imod)%SNLPS%QST5
     qst6   => mpars(imod)%SNLPS%QST6
     snlnq  => mpars(imod)%SNLPS%SNLNQ
     snlmsc => mpars(imod)%SNLPS%SNLMSC
     snlnsc => mpars(imod)%SNLPS%SNLNSC
     snlsfd => mpars(imod)%SNLPS%SNLSFD
     snlsfs => mpars(imod)%SNLPS%SNLSFS
     snll   => mpars(imod)%SNLPS%SNLL
     snlm   => mpars(imod)%SNLPS%SNLM
     snlt   => mpars(imod)%SNLPS%SNLT
     snlcd  => mpars(imod)%SNLPS%SNLCD
     snlcs  => mpars(imod)%SNLPS%SNLCS
 #endif
 #ifdef W3_NL4
     itsa   => mpars(imod)%SNLPS%ITSA
     ialt   => mpars(imod)%SNLPS%IALT
 #endif
 #ifdef W3_NL5
     qr5dpt => mpars(imod)%SNLPS%QR5DPT
     qr5oml => mpars(imod)%SNLPS%QR5OML
     qi5dis => mpars(imod)%SNLPS%QI5DIS
     qi5kev => mpars(imod)%SNLPS%QI5KEV
     qi5nnz => mpars(imod)%SNLPS%QI5NNZ
     qi5ipl => mpars(imod)%SNLPS%QI5IPL
     qi5pmx => mpars(imod)%SNLPS%QI5PMX
 #endif
 #ifdef W3_NLS
     nthx   => mpars(imod)%SNLPS%NTHX
     nfrx   => mpars(imod)%SNLPS%NFRX
     nspl   => mpars(imod)%SNLPS%NSPL
     nsph   => mpars(imod)%SNLPS%NSPH
     snsst  => mpars(imod)%SNLPS%SNSST
     cnlsa  => mpars(imod)%SNLPS%CNLSA
     cnlsc  => mpars(imod)%SNLPS%CNLSC
     cnlsfm => mpars(imod)%SNLPS%CNLSFM
     cnlsc1 => mpars(imod)%SNLPS%CNLSC1
     cnlsc2 => mpars(imod)%SNLPS%CNLSC2
     cnlsc3 => mpars(imod)%SNLPS%CNLSC3
 #endif
     !
     !     Structure SBTPS
     !
 #ifdef W3_BT1
     sbtc1  => mpars(imod)%SBTPS%SBTC1
 #endif
 #ifdef W3_BT4
     sbtcx  => mpars(imod)%SBTPS%SBTCX
 #endif
     !
     !     Structure SDBPS
     !
 #ifdef W3_DB1
     sdbc1  => mpars(imod)%SDBPS%SDBC1
     sdbc2  => mpars(imod)%SDBPS%SDBC2
     fdonly => mpars(imod)%SDBPS%FDONLY
     sdbsc  => mpars(imod)%SDBPS%SDBSC
 #endif
     !
     !
 #ifdef W3_UOST
     uostfilelocal => mpars(imod)%UOSTPS%UOSTFILELOCAL
     uostfileshadow => mpars(imod)%UOSTPS%UOSTFILESHADOW
     uostfactorlocal => mpars(imod)%UOSTPS%UOSTFACTORLOCAL
     uostfactorshadow => mpars(imod)%UOSTPS%UOSTFACTORSHADOW
 #endif
     !
     !     Structure SICPS
     !
 #ifdef W3_IS1
     is1c1  => mpars(imod)%SICPS%IS1C1
     is1c2  => mpars(imod)%SICPS%IS1C2
 #endif
     !
     !    Structure SCHM
     fsbccfl => mpars(imod)%SCHMS%FSBCCFL
     fsn => mpars(imod)%SCHMS%FSN
     fspsi => mpars(imod)%SCHMS%FSPSI
     fsfct => mpars(imod)%SCHMS%FSFCT
     fsnimp => mpars(imod)%SCHMS%FSNIMP
     fstotalimp => mpars(imod)%SCHMS%FSTOTALIMP
     fstotalexp => mpars(imod)%SCHMS%FSTOTALEXP
     fsrefraction => mpars(imod)%SCHMS%FSREFRACTION
     fsfreqshift => mpars(imod)%SCHMS%FSFREQSHIFT
     fssource => mpars(imod)%SCHMS%FSSOURCE
     do_change_wlv => mpars(imod)%SCHMS%DO_CHANGE_WLV
     solverthr_stp => mpars(imod)%SCHMS%SOLVERTHR_STP
     crit_dep_stp => mpars(imod)%SCHMS%CRIT_DEP_STP
     b_jgs_terminate_maxiter => mpars(imod)%SCHMS%B_JGS_TERMINATE_MAXITER
     b_jgs_terminate_difference => mpars(imod)%SCHMS%B_JGS_TERMINATE_DIFFERENCE
     b_jgs_terminate_norm => mpars(imod)%SCHMS%B_JGS_TERMINATE_NORM
     b_jgs_limiter => mpars(imod)%SCHMS%B_JGS_LIMITER
     b_jgs_use_jacobi => mpars(imod)%SCHMS%B_JGS_USE_JACOBI
     b_jgs_block_gauss_seidel => mpars(imod)%SCHMS%B_JGS_BLOCK_GAUSS_SEIDEL
     b_jgs_maxiter => mpars(imod)%SCHMS%B_JGS_MAXITER
     b_jgs_limiter_func => mpars(imod)%SCHMS%B_JGS_LIMITER_FUNC
     b_jgs_pmin => mpars(imod)%SCHMS%B_JGS_PMIN
     b_jgs_diff_thr => mpars(imod)%SCHMS%B_JGS_DIFF_THR
     b_jgs_norm_thr => mpars(imod)%SCHMS%B_JGS_NORM_THR
     b_jgs_nlevel => mpars(imod)%SCHMS%B_JGS_NLEVEL
     b_jgs_source_nonlinear => mpars(imod)%SCHMS%B_JGS_SOURCE_NONLINEAR
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3SETG : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3SETG : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NAUXGR = ',i10/                   &
          '                    NGRIDS = ',i10/)
 #if defined(TEST_W3GDATMD) || defined(TEST_W3GDATMD_W3SETG)
 9000 FORMAT (' TEST W3SETG : GRID/MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of W3SETG ----------------------------------------------------- /
     !/
References aaircmin, aairgb, aalpha, angarc, angld, angle, angle0, arctc, b_jgs_block_gauss_seidel, b_jgs_diff_thr, b_jgs_limiter, b_jgs_limiter_func, b_jgs_maxiter, b_jgs_nlevel, b_jgs_norm_thr, b_jgs_pmin, b_jgs_source_nonlinear, b_jgs_terminate_difference, b_jgs_terminate_maxiter, b_jgs_terminate_norm, b_jgs_use_jacobi, bbeta, btbeta, cap_id, capchnk, ccng, ccon, ccps, cd_max, cdsa0, cdsa1, cdsa2, cdsb0, cdsb1, cdsb2, cdsb3, cinxsi, clatf, clatis, clatmn, clats, cmprtrck, cnlsa, cnlsc, cnlsc1, cnlsc2, cnlsc3, cnlsfm, countcon, countot, countri, crit_dep_stp, crossdiff, cthg0s, ctmax, ctrnx, ctrny, cumulw, dcki, ddelta1, ddelta2, dden, dden2, dmin, do_change_wlv, dpdx, dpdy, dpthnl, dqdx, dqdy, dsii, dsip, dtcfl, dtcfli, dth, dtmax, dtme, dtmin, dtms, dxdp, dxdq, dxymax, dydp, dydq, e3df, ec2, ecos, edges, es2, esc, esin, fachfa, fachfe, facp, facsd, facti1, facti2, fdonly, ffacberg, ffng, ffps, ffxfa, ffxfm, ffxpm, fhmax, fice0, ficel, ficen, filext, flagll, flagst, flagunr, flck, flcth, flcx, flcy, fldry, flsou, flx4a0, fpimin, fr1, frq, fsbccfl, fsfct, fsfreqshift, fshf, fsn, fsnimp, fspm, fspsi, fsrefraction, fssource, fstotalexp, fstotalimp, fswell, fswnd, fte, ftf, fttr, ftwl, ftwn, funo3, fverg, fxfm, fxpm, ginit, gname, gqamp, gqnf1, gqnq_om2, gqnt1, gqthrcou, gqthrsat, grids, gridshift, gsqrt, gsu, gtype, guginit, hpfac, hqfac, i_diag, iaa, ialt, ic2pars, ic3pars, ic4_cn, ic4_fc, ic4_fmin, ic4_ki, ic4_kibk, ic4pars, ic5pars, icescales, iclbac, iclose, ie_cell, ien, igpars, igrid, iiceddisp, iicedisp, iicefdisp, iicehdisp, iicehfac, iicehinit, iicehmin, iicesmooth, ijkcel, ijkcel3, ijkcel4, ijkufc, ijkufc5, ijkufc6, ijkvfc, ijkvfc5, ijkvfc6, iktab, index_cell, iobdp, iobp, iobpa, iobpd, ipars, iqtpe, is1c1, is1c2, is2pars, isgrd, ismcbp, itsa, ja_ie, jaa, kdcon, kdmn, lam, len, mapfs, mapsf, mapst2, mapsta, mapth, mapwn, maxx, maxy, mpars, mrfct, narc, nauxgr, nbac, nbedge, nbgl, nbsmc, ncel, ndpths, neigh, nfrcut, nfrmax, nfrmin, nfrx, nglo, ngrids, nitersec1, nittin, nk, nk2, nltail, nlvcel, nlvufc, nlvvfc, nnz, nqa, nrlv, nsea, nseal, nspec, nsph, nspl, nspmax, nspmin, nspmx2, nth, nthexp, nthmax, nthx, ntri, nufc, nvfc, nx, ny, ofstab, p2msf, pfmove, pinit, polat, polon, pos_cell, posi, qbi, qi5dis, qi5ipl, qi5kev, qi5nnz, qi5pmx, qr5dpt, qr5oml, qst1, qst2, qst3, qst4, qst5, qst6, reflc, refld, refpars, refran, rref, rstype, rwindc, satindices, satweights, sbtc1, sbtcx, sdbc1, sdbc2, sdbsc, sds6a1, sds6a2, sds6et, sds6p1, sds6p2, sdsaln, sdsc1, sed_d50, sed_psic, sgrds, shstab, si, sig, sig2, sin6a0, sin6fc, sin6ws, sinc1, sinit, sintailpar, slnc1, snlc1, snlcd, snlcs, snll, snlm, snlmsc, snlnq, snlnsc, snls1, snls2, snls3, snlsfd, snlsfs, snlt, snsst, solverthr_stp, spcbac, ssdsabk, ssdsbck, ssdsbint, ssdsbm, ssdsbr, ssdsbrf1, ssdsbrf2, ssdsbrfdf, ssdsbt, ssdsc, ssdsc1, ssdscos, ssdsdth, ssdshck, ssdsiso, ssdsp, ssdspbk, ssinbr, ssinthp, sstxftf, sstxftftail, sstxftwn, sswellf, sswellfpar, stedu, stexu, steyu, w3servmd::strace(), swl6b1, swl6cstb1, swl6s6, sx, sy, tail_id, tail_lev, tail_tran1, tail_tran2, th, trflag, tria, trigp, trnx, trny, ttauwshelter, uostfactorlocal, uostfactorshadow, uostfilelocal, uostfileshadow, us3df, ussp_wn, usspf, wdcg, wdth, wwcor, wwnmeanp, wwnmeanptail, x0, xf1, xf2, xfc, xfh, xflt, xfr, xft, xgrd, xrel, xsi, y0, ygrd, zb, zwind, zz0max, zz0rat, zzalp, and zzwnd.
Referenced by wmesmfmd::createexpmesh(), gxoutf(), gxoutp(), w3bounc(), w3bound(), w3adatmd::w3dima(), w3idatmd::w3dimi(), w3dims(), w3dimug(), w3wdatmd::w3dimw(), w3dimx(), w3odatmd::w3dmo2(), w3odatmd::w3dmo3(), w3odatmd::w3dmo5(), w3gntx(), w3grib(), w3gridmd::w3grid(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3sbs1(), w3shel(), w3strt(), w3trck(), w3trnc(), w3uprstr(), w3wavemd::w3wave(), w3adatmd::w3xdma(), wmmdatmd::wmdimd(), wmmdatmd::wmdimm(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
w3setref()
subroutine w3gdatmd::w3setref
Definition at line 3294 of file w3gdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           F. Ardhuin              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         13-Nov-2013 |
     !/                  +-----------------------------------+
     !/
     !/    13-Nov-2013 : Origination.                        ( version 4.13 )
     !/
     !  1. Purpose :
     !
     !     Update reflection directions at shoreline.
     !
     !  2. Method :
     !
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       None
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      WW3_GRID  Prog. WW3_GRID Grid preprocessor
     !      W3ULEV    Subr. W3UPDTMD Water level update
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S      Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants
 #ifdef W3_S
     USE w3servmd, ONLY : strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/
     INTEGER                 :: ISEA, IX, IY, IXY, IXN, IXP, IYN, IYP
     INTEGER                 :: J, K, NEIGH1(0:7)
     INTEGER                 :: ILEV, NLEV
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     REAL                    :: TRIX(NY*NX), TRIY(NY*NX), DX, DY,    &
          COSAVG, SINAVG, THAVG, ANGLES(0:7), CLAT
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SETREF')
 #endif
     !
     ! 1.  Preparations --------------------------------------------------- *
     !
 #ifdef W3_REF1
     IF (refpars(2).GT.0) rref(2)=.true.
     IF (refpars(3).GT.0) rref(3)=.true.
     IF (refpars(4).GT.0) rref(4)=.true.
     !
     DO iy=2, ny-1
       DO ix=2, nx-1
         IF (refpars(1).GT.0) rref(1)=.true.
         !No reflection from artificial island on pole.
         IF (flagll.AND.(ygrd(iy,ix).GT.85)) rref(1)=.false.
         IF (mapsta(iy,ix).GT.0) THEN
           !
           ! Prepares for reflection from subgrid islands
           !
           IF (rref(2)) &
                reflc(2,mapfs(iy,ix))= max((1. - trnx(iy,ix)),(1.-trny(iy,ix)))
           !
           ! Prepares for iceberg reflections
           !
           IF (rref(4)) &
                reflc(4,mapfs(iy,ix))= 1.
           !
           ! resolved shoreline reflection
           !
           IF (rref(1)) THEN
             reflc(1,  mapfs(iy,ix)) = 0.
             refld(1:6,mapfs(iy,ix)) = 0
             !
             ! Search for neighboring coastline.        3 2 1
             ! around X. These are the neighbors of X:  4 X 0
             !                                          5 6 7
             !
             !
             neigh1(0)=8*mapst2(iy,ix+1)+mapsta(iy,ix+1)
             neigh1(1:3)=8*mapst2(iy+1,ix+1:ix-1:-1)+mapsta(iy+1,ix+1:ix-1:-1)
             neigh1(4)=8*mapst2(iy,ix-1)+mapsta(iy,ix-1)
             neigh1(5:7)=8*mapst2(iy-1,ix-1:ix+1)+mapsta(iy-1,ix-1:ix+1)
             !
             ! if one of the surrounding points is land: determines directions ...
             !
             IF (minval(abs(neigh1)).EQ.0) THEN
               IF ( flagll ) THEN
                 clat   = cos(ygrd(iy,ix)*dera)
               ELSE
                 clat = 1.
               END IF
               angles(0)= atan2(dydp(iy,ix),dxdp(iy,ix)*clat)
               angles(1)= atan2(dydp(iy,ix)+dydq(iy,ix),(dxdp(iy,ix)+dxdq(iy,ix))*clat)
               angles(2)= atan2(dydq(iy,ix),dxdq(iy,ix)*clat)
               angles(3)= atan2(dydq(iy,ix)-dydp(iy,ix),(dxdq(iy,ix)-dxdp(iy,ix))*clat)
               angles(4:7)= angles(0:3)+pi
               IF ((neigh1(0).GE.1).AND.(neigh1(4).GE.1)) THEN
                 refld(3,mapfs(iy,ix))=0
               ELSE
                 IF ((neigh1(0).GE.1).OR.(neigh1(4).GE.1)) refld(3,mapfs(iy,ix))=1
               END IF
               IF ((neigh1(2).EQ.1).AND.(neigh1(6).GE.1)) THEN
                 refld(4,mapfs(iy,ix))=0
               ELSE
                 IF ((neigh1(2).GE.1).OR.(neigh1(6).GE.1)) refld(4,mapfs(iy,ix))=1
               END IF
               !
               ! Looks for a locally straight coast in all 8 orientations
               !
               j=0
               refld(1,mapfs(iy,ix))=0
               cosavg=0
               sinavg=0
               ! Shore angle is corrected for grid rotation in w3ref1md.ftn with  REFLD(5:6,MAPFS(IY,IX))
               refld(5,mapfs(iy,ix))= mod(nth+nint(angles(0)/tpi*nth),nth)
               refld(6,mapfs(iy,ix))= mod(nth+nint((angles(2)/tpi-0.25)*nth),nth)
 #endif
 #ifdef W3_REFT
               IF (iy.EQ.4) THEN
                 WRITE(6,*) 'POINT (IX,IY):',ix,iy
                 WRITE(6,*) 'REFT:',neigh1(3),neigh1(2), neigh1(1)
                 WRITE(6,*) 'REFT:',neigh1(4),1, neigh1(0)
                 WRITE(6,*) 'REFT:',neigh1(5:7)
                 WRITE(6,*) 'ANG:',angles(3)*rade,angles(2)*rade, angles(1)*rade
                 WRITE(6,*) 'ANG:',angles(4)*rade,1, angles(0) *rade
                 WRITE(6,*) 'ANG:',angles(5:7)*rade
                 WRITE(6,*) 'REFT:',xgrd(iy+1,ix-1:ix+1), ygrd(iy+1,ix-1:ix+1)
                 WRITE(6,*) 'REFT:',xgrd(iy,ix-1:ix+1) , ygrd(iy,ix-1:ix+1)
                 WRITE(6,*) 'REFT:',xgrd(iy-1,ix-1:ix+1), ygrd(iy-1,ix-1:ix+1)
                 WRITE(6,*) 'REFLD:',refld(3:6,mapfs(iy,ix))
               ENDIF
 #endif
 #ifdef W3_REF1
               DO k=0,7
                 IF (neigh1(k).EQ.0.AND.neigh1(mod(k+7,8)).EQ.0 &
                      .AND.neigh1(mod(k+1,8)).EQ.0 &
                      .AND.neigh1(mod(k+4,8)).NE.0) THEN
                   reflc(1,mapfs(iy,ix))= refpars(1)
                   !
                   ! Defines direction index for specular reflection (normal to coast)
                   !
                   !  for example, if we have this layout   1 1 0
                   !  (NB: 1 is sea, 0 is land)             1 X 0
                   !                                        1 1 0
                   !
                   !  then there is only a coastline detection for K=0, giving J=1
                   !  and the final result will be REFLD(1,MAPFS(IY,IX))=1
                   !  Namely, the direction TH(REFLD) is the direction pointing INTO the coast
                   !
                   refld(2,mapfs(iy,ix))= 2
                   cosavg=cosavg+cos(angles(k))  !ECOS(1+(K*NTH)/8)
                   sinavg=sinavg+sin(angles(k))  !ESIN(1+(K*NTH)/8)
                   j=j+1
                 ENDIF
               END DO
               IF (j.GT.0) THEN
                 IF (j.GT.1) refld(2,mapfs(iy,ix))= 1
                 thavg=atan2(sinavg,cosavg)
                 refld(1,mapfs(iy,ix))=1+mod(nth+nint(thavg/tpi*nth),nth)
               ELSE
                 !                             1 1 1
                 ! Looks for mild corners like 1 1 1
                 !                             1 0 0
                 DO k=0,7
                   IF (neigh1(k).EQ.0.AND.neigh1(mod(k+1,8)).EQ.0 &
                        .AND.neigh1(mod(k+4,8)).NE.0) THEN
                     reflc(1,mapfs(iy,ix))= refpars(1)
                     refld(1,mapfs(iy,ix))= 1+mod((k*nth+(k+1)*nth)/16,nth)
                     refld(2,mapfs(iy,ix))= 1
                   ENDIF
                 END DO
                 !                              1 1 1                        1 1 1
                 ! Looks for sharp corners like 1 1 1 but not diagonals like 1 1 1
                 !                              1 0 1                        1 1 0
                 IF (reflc(1,mapfs(iy,ix)).LE.0) THEN
                   DO k=0,7,2
                     IF ( neigh1(k).EQ.0.AND.neigh1(mod(k+4,8)).NE.0) THEN
                       reflc(1,mapfs(iy,ix))= refpars(1)
                       refld(1,mapfs(iy,ix))= 1+(k*nth)/8
                       refld(2,mapfs(iy,ix))= 0
                       !WRITE(6,*) 'NEIGH3:',IX,IY,K,NEIGH1,K*(NTH/8)
                     END IF
                   END DO
                 END IF
               END IF
               ! End of test if surrounding point is land
             END IF
 #endif
 #ifdef W3_REFT
             IF (reflc(1,mapfs(iy,ix)).GT.0)  THEN
               WRITE (6,*) 'COAST DIRECTION AT POINT:',ix,iy,' IS ', &
                    refld(:,mapfs(iy,ix)),th(refld(1,mapfs(iy,ix)))*360/tpi
             ENDIF
 #endif
 #ifdef W3_REF1
             ! End of test if local point is sea
           END IF
         END IF
       END DO
     END DO
 #endif
     !
     RETURN
     !
     ! Formats
     !
     !/
     !/ End of W3SETREF ----------------------------------------------------- /
     !/
References constants::dera, dxdp, dxdq, dydp, dydq, flagll, mapfs, mapst2, mapsta, nth, constants::pi, constants::rade, reflc, refld, refpars, rref, w3servmd::strace(), th, constants::tpi, trnx, trny, xgrd, and ygrd.
Referenced by w3iorsmd::w3iors(), and w3updtmd::w3ulev().
Variable Documentation
aaircmin
real, pointer w3gdatmd::aaircmin
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), w3setg(), and w3src4md::w3spr4().
aairgb
real, pointer w3gdatmd::aairgb
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), w3setg(), and w3src4md::w3spr4().
aalpha
real pointer w3gdatmd::aalpha
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src3md::calc_ustar(), w3src4md::calc_ustar(), w3src3md::tabu_stress(), w3src4md::tabu_stress(), w3src3md::tabu_tauhf(), w3src4md::tabu_tauhf(), w3src4md::tabu_tauhf2(), w3setg(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src4md::w3spr4(), w3srcemd::w3srce(), and w3updtmd::w3uice().
angarc
real, dimension(:), pointer w3gdatmd::angarc
Definition at line 1204 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::w3psmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3utau(), w3updtmd::w3uwnd(), and w3wavemd::w3wave().
angld
real, dimension(:), pointer w3gdatmd::angld
Definition at line 1192 of file w3gdatmd.F90.
   REAL, POINTER         :: AnglD(:)
Referenced by w3exnc(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3setg(), and w3updtmd::w3ubpt().
angle
real, dimension(:,:), pointer w3gdatmd::angle
Definition at line 1123 of file w3gdatmd.F90.
   REAL, POINTER           :: ANGLE(:,:),ANGLE0(:,:)
Referenced by w3triamd::ug_gradients(), and w3setg().
angle0
real, dimension(:,:), pointer w3gdatmd::angle0
Definition at line 1123 of file w3gdatmd.F90.
Referenced by w3setg().
arctc
logical, pointer w3gdatmd::arctc
Definition at line 1264 of file w3gdatmd.F90.
Referenced by w3smcomd::smc_interp(), w3psmcmd::smcaverg(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::w3psmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3utau(), w3updtmd::w3uwnd(), and w3wavemd::w3wave().
b_jgs_block_gauss_seidel
logical, pointer w3gdatmd::b_jgs_block_gauss_seidel
Definition at line 1415 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_BLOCK_GAUSS_SEIDEL
Referenced by pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_w3profsmd::jacobi_finalize(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3initmd::w3init(), and w3setg().
b_jgs_diff_thr
real(8), pointer w3gdatmd::b_jgs_diff_thr
Definition at line 1419 of file w3gdatmd.F90.
   REAL(8), POINTER :: B_JGS_DIFF_THR
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_limiter
logical, pointer w3gdatmd::b_jgs_limiter
Definition at line 1413 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_LIMITER
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setg(), and w3srcemd::w3srce().
b_jgs_limiter_func
integer, pointer w3gdatmd::b_jgs_limiter_func
Definition at line 1417 of file w3gdatmd.F90.
   INTEGER, POINTER :: B_JGS_LIMITER_FUNC
Referenced by w3setg(), and w3srcemd::w3srce().
b_jgs_maxiter
integer, pointer w3gdatmd::b_jgs_maxiter
Definition at line 1416 of file w3gdatmd.F90.
   INTEGER, POINTER :: B_JGS_MAXITER
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_nlevel
integer, pointer w3gdatmd::b_jgs_nlevel
Definition at line 1421 of file w3gdatmd.F90.
   INTEGER, POINTER :: B_JGS_NLEVEL
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_norm_thr
real(8), pointer w3gdatmd::b_jgs_norm_thr
Definition at line 1420 of file w3gdatmd.F90.
   REAL(8), POINTER :: B_JGS_NORM_THR
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_pmin
real(8), pointer w3gdatmd::b_jgs_pmin
Definition at line 1418 of file w3gdatmd.F90.
   REAL(8), POINTER :: B_JGS_PMIN
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_source_nonlinear
logical, pointer w3gdatmd::b_jgs_source_nonlinear
Definition at line 1422 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_SOURCE_NONLINEAR
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_terminate_difference
logical, pointer w3gdatmd::b_jgs_terminate_difference
Definition at line 1411 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_TERMINATE_DIFFERENCE
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_terminate_maxiter
logical, pointer w3gdatmd::b_jgs_terminate_maxiter
Definition at line 1410 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_TERMINATE_MAXITER
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_terminate_norm
logical, pointer w3gdatmd::b_jgs_terminate_norm
Definition at line 1412 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_TERMINATE_NORM
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3setg().
b_jgs_use_jacobi
logical, pointer w3gdatmd::b_jgs_use_jacobi
Definition at line 1414 of file w3gdatmd.F90.
   LOGICAL, POINTER :: B_JGS_USE_JACOBI
Referenced by pdlib_w3profsmd::block_solver_finalize(), pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::pdlib_w3xypug_block_explicit(), pdlib_w3profsmd::pdlib_w3xypug_block_implicit(), w3initmd::w3init(), and w3setg().
bbeta
real pointer w3gdatmd::bbeta
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src3md::tabu_tauhf(), w3src4md::tabu_tauhf(), w3src4md::tabu_tauhf2(), w3setg(), w3src3md::w3sin3(), and w3src4md::w3sin4().
btbeta
real, pointer w3gdatmd::btbeta
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3iogomd::calc_wbt(), and w3setg().
cap_id
integer, pointer w3gdatmd::cap_id
Definition at line 1285 of file w3gdatmd.F90.
Referenced by w3flx3md::w3flx3(), and w3setg().
capchnk
real, dimension(:), pointer w3gdatmd::capchnk
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::calc_ustar(), and w3setg().
ccng
real, pointer w3gdatmd::ccng
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uwnd().
ccon
integer, dimension(:), pointer w3gdatmd::ccon
Definition at line 1124 of file w3gdatmd.F90.
   INTEGER,  POINTER       :: CCON(:),  COUNTCON(:), IE_CELL(:),           &
        POS_CELL(:),  &
        IAA(:), JAA(:), POSI(:,:),                   &
        I_DIAG(:), JA_IE(:,:,:),                     &
        INDEX_CELL(:)
Referenced by w3triamd::area_si(), pdlib_w3profsmd::pdlib_init(), w3triamd::readmshobc(), w3triamd::ug_getopenboundary(), w3profsmd::w3cflug(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
ccps
real, pointer w3gdatmd::ccps
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uwnd().
cd_max
real, pointer w3gdatmd::cd_max
Definition at line 1286 of file w3gdatmd.F90.
Referenced by w3flx3md::w3flx3(), and w3setg().
cdsa0
real, pointer w3gdatmd::cdsa0
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cdsa1
real, pointer w3gdatmd::cdsa1
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cdsa2
real, pointer w3gdatmd::cdsa2
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cdsb0
real, pointer w3gdatmd::cdsb0
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cdsb1
real, pointer w3gdatmd::cdsb1
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cdsb2
real, pointer w3gdatmd::cdsb2
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cdsb3
real, pointer w3gdatmd::cdsb3
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
cinxsi
real pointer w3gdatmd::cinxsi
Definition at line 1282 of file w3gdatmd.F90.
   REAL, POINTER           :: CINXSI
Referenced by w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3setg(), and w3src2md::w3spr2().
clatf
real, dimension(:), pointer w3gdatmd::clatf
Definition at line 1202 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), and w3setg().
clatis
real, dimension(:), pointer w3gdatmd::clatis
Definition at line 1197 of file w3gdatmd.F90.
   REAL   , POINTER :: CLATIS(:) ! INVERSE OF COS(LAT) DEFINED ON ISEA
Referenced by w3triamd::ug_gradients(), and w3setg().
clatmn
real, pointer w3gdatmd::clatmn
Definition at line 1257 of file w3gdatmd.F90.
Referenced by w3setg(), and w3pro2md::w3xyp2().
clats
real, dimension(:), pointer w3gdatmd::clats
Definition at line 1196 of file w3gdatmd.F90.
   REAL   , POINTER :: CLATS(:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), w3smcomd::calc_interp(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3psmcmd::w3psmc(), w3setg(), w3ref1md::w3sref(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
clgtype
integer, parameter w3gdatmd::clgtype = 2
Definition at line 625 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: CLGTYPE = 2
Referenced by w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::fieldindex(), wmesmfmd::setupimpbmsk(), w3bounc(), w3bound(), w3crnc(), w3exnc(), w3gntx(), w3iopomd::w3iopp(), w3snl5md::w3snl5(), w3ref1md::w3sref(), w3updtmd::w3uini(), w3updtmd::w3utrn(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
cmprtrck
logical, pointer w3gdatmd::cmprtrck
Definition at line 1220 of file w3gdatmd.F90.
   LOGICAL, POINTER :: CMPRTRCK
Referenced by w3iotrmd::w3iotr(), and w3setg().
cnlsa
real, pointer w3gdatmd::cnlsa
Definition at line 1377 of file w3gdatmd.F90.
   REAL, POINTER           :: CNLSA, CNLSC, CNLSFM,                &
        CNLSC1, CNLSC2, CNLSC3, SNSST(:,:)
Referenced by w3snlsmd::insnls(), and w3setg().
cnlsc
real, pointer w3gdatmd::cnlsc
Definition at line 1377 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snlsmd::w3snls().
cnlsc1
real, pointer w3gdatmd::cnlsc1
Definition at line 1377 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snlsmd::w3snls().
cnlsc2
real, pointer w3gdatmd::cnlsc2
Definition at line 1377 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snlsmd::w3snls().
cnlsc3
real, pointer w3gdatmd::cnlsc3
Definition at line 1377 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snlsmd::w3snls().
cnlsfm
real, pointer w3gdatmd::cnlsfm
Definition at line 1377 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snlsmd::w3snls().
countcon
integer, dimension(:), pointer w3gdatmd::countcon
Definition at line 1124 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), w3triamd::readmshobc(), w3triamd::ug_getopenboundary(), and w3setg().
countot
integer, pointer w3gdatmd::countot
Definition at line 1109 of file w3gdatmd.F90.
Referenced by w3triamd::count(), w3triamd::readmsh(), w3dimug(), and w3setg().
countri
integer, pointer w3gdatmd::countri
Definition at line 1109 of file w3gdatmd.F90.
Referenced by w3triamd::count(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), and w3setg().
crit_dep_stp
real(8), pointer w3gdatmd::crit_dep_stp
Definition at line 1409 of file w3gdatmd.F90.
   REAL(8), POINTER  :: CRIT_DEP_STP
Referenced by w3wavset::compute_active_node(), and w3setg().
crossdiff
real, dimension(:,:), pointer w3gdatmd::crossdiff
Definition at line 1132 of file w3gdatmd.F90.
   REAL, POINTER           :: CROSSDIFF(:,:)
Referenced by w3setg().
cthg0s
real, dimension(:), pointer w3gdatmd::cthg0s
Definition at line 1198 of file w3gdatmd.F90.
   REAL   , POINTER :: CTHG0S(:) ! TAN(Y)/R, DEFINED ON ISEA
Referenced by w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3setg(), and w3wavemd::w3wave().
ctmax
real, pointer w3gdatmd::ctmax
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcgtcrfr(), w3psmcmd::smckuno2(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), and w3setg().
ctrnx
real, dimension(:), pointer w3gdatmd::ctrnx
Definition at line 1202 of file w3gdatmd.F90.
   REAL, POINTER :: CTRNX(:), CTRNY(:), CLATF(:)
Referenced by w3psmcmd::w3psmc(), and w3setg().
ctrny
real, dimension(:), pointer w3gdatmd::ctrny
Definition at line 1202 of file w3gdatmd.F90.
Referenced by w3psmcmd::w3psmc(), and w3setg().
cumulw
real, dimension(:,:), pointer w3gdatmd::cumulw
Definition at line 1323 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
dcki
real, dimension(:,:), pointer w3gdatmd::dcki
Definition at line 1323 of file w3gdatmd.F90.
   REAL, POINTER           :: DCKI(:,:), SATWEIGHTS(:,:),CUMULW(:,:),QBI(:,:)
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
ddelta1
real, pointer w3gdatmd::ddelta1
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src3md::w3sds3(), and w3setg().
ddelta2
real, pointer w3gdatmd::ddelta2
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src3md::w3sds3(), and w3setg().
dden
real, dimension(:), pointer w3gdatmd::dden
Definition at line 1234 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), w3srcemd::calc_fpi(), w3iogomd::calc_u3stokes(), wmesmfmd::calcstokes3d(), pdlib_w3profsmd::compute_mean_param(), wmesmfmd::fieldindex(), w3sbs1md::insbs1(), w3gig1md::w3addig(), w3iogomd::w3outg(), w3sbs1md::w3sbs1(), w3sbt4md::w3sbt4(), w3sdb1md::w3sdb1(), w3src2md::w3sds2(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3sis2md::w3sis2(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3str1md::w3str1(), w3swldmd::w3swl4(), w3swldmd::w3swl6(), and w3updtmd::w3ubpt().
dden2
real, dimension(:), pointer w3gdatmd::dden2
Definition at line 1234 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), and w3sis1md::w3sis1().
dmin
real, pointer w3gdatmd::dmin
Definition at line 1183 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::block_solver_init(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), wmesmfmd::fieldindex(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), w3profsmd::setdepth(), w3psmcmd::smcdhxy(), w3wavemd::w3gath(), w3initmd::w3init(), w3pro3md::w3ktp3(), w3setg(), w3srcemd::w3srce(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), and w3dispmd::wavnu_local().
do_change_wlv
logical, pointer w3gdatmd::do_change_wlv
Definition at line 1407 of file w3gdatmd.F90.
   LOGICAL, POINTER  :: DO_CHANGE_WLV
Referenced by w3initmd::w3init(), w3setg(), and w3updtmd::w3ulev().
dpdx
real, dimension(:,:), pointer w3gdatmd::dpdx
Definition at line 1208 of file w3gdatmd.F90.
   REAL   , POINTER :: DPDX(:,:), DPDY(:,:) ! DP/DX & DP/DY DEFINED ON IX,IY
Referenced by w3pro3md::w3cflxy(), w3updtmd::w3dzxy(), w3gntx(), w3iotrmd::w3iotr(), w3setg(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
dpdy
real, dimension(:,:), pointer w3gdatmd::dpdy
Definition at line 1208 of file w3gdatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3updtmd::w3dzxy(), w3gntx(), w3iotrmd::w3iotr(), w3setg(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
dpthnl
real, dimension(:), pointer w3gdatmd::dpthnl
Definition at line 1353 of file w3gdatmd.F90.
   REAL, POINTER           :: DPTHNL(:)
Referenced by w3snl2md::insnl2(), and w3setg().
dqdx
real, dimension(:,:), pointer w3gdatmd::dqdx
Definition at line 1209 of file w3gdatmd.F90.
   REAL   , POINTER :: DQDX(:,:), DQDY(:,:) ! DQ/DX & DQ/DY DEFINED ON IX,IY
Referenced by w3pro3md::w3cflxy(), w3updtmd::w3dzxy(), w3gntx(), w3iotrmd::w3iotr(), w3setg(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
dqdy
real, dimension(:,:), pointer w3gdatmd::dqdy
Definition at line 1209 of file w3gdatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3updtmd::w3dzxy(), w3gntx(), w3iotrmd::w3iotr(), w3setg(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
dsii
real, dimension(:), pointer w3gdatmd::dsii
Definition at line 1234 of file w3gdatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), wmesmfmd::calcstokes3d(), w3snl5md::insnl5(), w3partmd::ptmean(), w3iogomd::w3outg(), w3sbs1md::w3sbs1(), w3src6md::w3sds6(), w3setg(), w3src6md::w3spr6(), and w3ref1md::w3sref().
dsip
real, dimension(:), pointer w3gdatmd::dsip
Definition at line 1234 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), w3src4md::insin4(), w3sis2md::insis2(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3gig1md::w3addig(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3src4md::w3sds4(), w3setg(), w3updtmd::w3uini(), w3updtmd::w3ulev(), and w3uprstr().
dtcfl
real, pointer w3gdatmd::dtcfl
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3initmd::w3init(), w3psmcmd::w3psmc(), w3setg(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypug(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), and wminitmd::wminitnml().
dtcfli
real, pointer w3gdatmd::dtcfli
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), and w3wavemd::w3wave().
dth
real, pointer w3gdatmd::dth
Definition at line 1232 of file w3gdatmd.F90.
   REAL, POINTER           :: DTH, XFR, FR1, FTE, FTF, FTWN, FTTR, &
        FTWL, FACTI1, FACTI2, FACHFA, FACHFE
Referenced by w3fld1md::appendtail(), w3iogomd::calc_wbt(), w3sbs1md::insbs1(), w3src4md::insin4(), w3snl1md::insnl1(), w3snl3md::insnl3(), w3snl5md::insnl5(), w3snlsmd::insnls(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3iogomd::secondhh(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3iogomd::skewness(), w3psmcmd::smcdhxy(), w3psmcmd::smcgtcrfr(), w3psmcmd::smckuno2(), w3src6md::tau_wave_atmos(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3bounc(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3iobcmd::w3iobc(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3sbs1md::w3sbs1(), w3sbt4md::w3sbt4(), w3src2md::w3sds2(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3snl4md::w3snl4(), w3snl1md::w3snlgqm(), w3snlsmd::w3snls(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3ref1md::w3sref(), w3str1md::w3str1(), w3swldmd::w3swl6(), w3updtmd::w3uini(), w3uprstr(), w3wavemd::w3wave(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
dtmax
real, pointer w3gdatmd::dtmax
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3initmd::w3init(), w3setg(), w3shel(), w3srcemd::w3srce(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
dtme
real, pointer w3gdatmd::dtme
Definition at line 1257 of file w3gdatmd.F90.
   REAL, POINTER           :: DTME, CLATMN
Referenced by w3setg(), and w3pro2md::w3xyp2().
dtmin
real, pointer w3gdatmd::dtmin
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), w3sis1md::w3sis1(), and w3srcemd::w3srce().
dtms
real, pointer w3gdatmd::dtms
Definition at line 1263 of file w3gdatmd.F90.
   REAL, POINTER           :: DTMS, Refran
Referenced by w3psmcmd::w3psmc(), and w3setg().
dxdp
real, dimension(:,:), pointer w3gdatmd::dxdp
Definition at line 1206 of file w3gdatmd.F90.
   REAL   , POINTER :: DXDP(:,:), DXDQ(:,:) ! DX/DP & DX/DQ DEFINED ON IX,IY
Referenced by w3gntx(), w3setg(), w3setref(), wminitmd::wminit(), and wminitmd::wminitnml().
dxdq
real, dimension(:,:), pointer w3gdatmd::dxdq
Definition at line 1206 of file w3gdatmd.F90.
Referenced by w3gntx(), w3setg(), w3setref(), wminitmd::wminit(), and wminitmd::wminitnml().
dxymax
real, pointer w3gdatmd::dxymax
Definition at line 1133 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3setg(), and wmiopomd::wmiopp().
dydp
real, dimension(:,:), pointer w3gdatmd::dydp
Definition at line 1207 of file w3gdatmd.F90.
   REAL   , POINTER :: DYDP(:,:), DYDQ(:,:) ! DY/DP & DY/DQ DEFINED ON IX,IY
Referenced by w3gntx(), w3setg(), w3setref(), wminitmd::wminit(), and wminitmd::wminitnml().
dydq
real, dimension(:,:), pointer w3gdatmd::dydq
Definition at line 1207 of file w3gdatmd.F90.
Referenced by w3gntx(), w3setg(), w3setref(), wminitmd::wminit(), and wminitmd::wminitnml().
e3df
integer, dimension(:,:), pointer w3gdatmd::e3df
Definition at line 1098 of file w3gdatmd.F90.
   INTEGER, POINTER        :: E3DF(:,:), P2MSF(:), US3DF(:), USSPF(:)
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), w3adatmd::w3dima(), w3exgi(), w3iogomd::w3flgrdupdt(), w3initmd::w3mpio(), w3iogomd::w3outg(), w3adatmd::w3seta(), w3setg(), w3adatmd::w3xdma(), and w3adatmd::w3xeta().
ec2
real, dimension(:), pointer w3gdatmd::ec2
Definition at line 1234 of file w3gdatmd.F90.
Referenced by wmesmfmd::fieldindex(), w3sis2md::insis2(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3gig1md::w3addig(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3iogomd::w3outg(), w3sbs1md::w3sbs1(), w3src4md::w3sds4(), w3setg(), w3src3md::w3sin3(), w3src4md::w3sin4(), and w3ref1md::w3sref().
ecos
real, dimension(:), pointer w3gdatmd::ecos
Definition at line 1234 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition_va(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), wmesmfmd::fieldindex(), w3sbs1md::insbs1(), w3src4md::insin4(), w3sis2md::insis2(), w3snl5md::insnl5(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3iogomd::secondhh(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3iogomd::skewness(), w3psmcmd::smcdhxy(), w3src6md::tau_wave_atmos(), w3gig1md::w3addig(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3sbs1md::w3sbs1(), w3sbt4md::w3sbt4(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3sln1md::w3sln1(), w3snl4md::w3snl4(), w3src4md::w3spr4(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
edges
integer, dimension(:,:), pointer w3gdatmd::edges
Definition at line 1105 of file w3gdatmd.F90.
   INTEGER, POINTER        :: EDGES(:,:), NEIGH(:,:)
Referenced by w3wavset::fd_compute_diff(), w3wavset::fd_wave_setup_compute_system(), and w3setg().
es2
real, dimension(:), pointer w3gdatmd::es2
Definition at line 1234 of file w3gdatmd.F90.
Referenced by wmesmfmd::fieldindex(), w3sis2md::insis2(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3iogomd::w3outg(), w3src4md::w3sds4(), and w3setg().
esc
real, dimension(:), pointer w3gdatmd::esc
Definition at line 1234 of file w3gdatmd.F90.
Referenced by wmesmfmd::fieldindex(), w3sis2md::insis2(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3iogomd::w3outg(), w3src4md::w3sds4(), and w3setg().
esin
real, dimension(:), pointer w3gdatmd::esin
Definition at line 1234 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition_va(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), wmesmfmd::fieldindex(), w3sbs1md::insbs1(), w3src4md::insin4(), w3sis2md::insis2(), w3snl5md::insnl5(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3iogomd::secondhh(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3iogomd::skewness(), w3psmcmd::smcdhxy(), w3src6md::tau_wave_atmos(), w3gig1md::w3addig(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3sbs1md::w3sbs1(), w3sbt4md::w3sbt4(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sln1md::w3sln1(), w3snl4md::w3snl4(), w3src4md::w3spr4(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
fachfa
real, pointer w3gdatmd::fachfa
Definition at line 1232 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), expand(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3setg(), w3snlsmd::w3snls(), w3srcemd::w3srce(), and w3updtmd::w3ulev().
fachfe
real, pointer w3gdatmd::fachfe
Definition at line 1232 of file w3gdatmd.F90.
Referenced by expand(), w3partmd::ptmean(), w3src3md::tabu_tauhf(), w3src4md::tabu_tauhf(), w3src4md::tabu_tauhf2(), w3bounc(), w3iobcmd::w3iobc(), w3setg(), w3snl1md::w3snl1(), w3snl3md::w3snl3(), wminiomd::wmioeg(), and wminiomd::wmiohg().
facp
real, pointer w3gdatmd::facp
Definition at line 1245 of file w3gdatmd.F90.
   REAL, POINTER           :: FACP, XREL, XFLT, FXFM, FXPM,        &
        XFT, XFC, FACSD, FHMAX
Referenced by pdlib_w3profsmd::action_limiter_local(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setg(), and w3srcemd::w3srce().
facsd
real, pointer w3gdatmd::facsd
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
facti1
real, pointer w3gdatmd::facti1
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3iogomd::w3outg(), w3src2md::w3sds2(), w3setg(), w3src2md::w3sin2(), w3snl3md::w3snl3(), and w3srcemd::w3srce().
facti2
real, pointer w3gdatmd::facti2
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3iogomd::w3outg(), w3src2md::w3sds2(), w3setg(), w3src2md::w3sin2(), w3snl3md::w3snl3(), and w3srcemd::w3srce().
fdonly
logical, pointer w3gdatmd::fdonly
Definition at line 1394 of file w3gdatmd.F90.
   LOGICAL, POINTER        :: FDONLY
Referenced by w3sdb1md::w3sdb1(), and w3setg().
ffacberg
real, pointer w3gdatmd::ffacberg
Definition at line 1136 of file w3gdatmd.F90.
   REAL,    POINTER        :: FFACBERG
Referenced by w3setg(), and w3updtmd::w3utrn().
ffng
real, pointer w3gdatmd::ffng
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uwnd().
ffps
real, pointer w3gdatmd::ffps
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uwnd().
ffxfa
real, pointer w3gdatmd::ffxfa
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
ffxfm
real pointer w3gdatmd::ffxfm
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
ffxpm
real pointer w3gdatmd::ffxpm
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
fhmax
real, pointer w3gdatmd::fhmax
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
fice0
real, pointer w3gdatmd::fice0
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3utrn().
ficel
real, pointer w3gdatmd::ficel
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3utrn().
ficen
real, pointer w3gdatmd::ficen
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), w3updtmd::w3uice(), and w3updtmd::w3utrn().
filext
character(len=13), pointer w3gdatmd::filext
Definition at line 1224 of file w3gdatmd.F90.
   CHARACTER(LEN=13), POINTER :: FILEXT
Referenced by w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3sbs1(), w3setg(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupdt().
flagll
logical, pointer w3gdatmd::flagll
Definition at line 1219 of file w3gdatmd.F90.
   LOGICAL, POINTER :: FLAGLL
Referenced by w3oacpmd::cpl_oasis_grid(), w3snl5md::insnl5(), w3triamd::ug_gradients(), w3bounc(), w3bullmd::w3bull(), w3pro3md::w3cflxy(), w3crnc(), w3updtmd::w3dzxy(), w3exnc(), w3gntx(), w3initmd::w3init(), w3iopomd::w3iopp(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3ounp(), w3setg(), w3setref(), w3shel(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3ref1md::w3sref(), w3trck(), w3trnc(), w3updtmd::w3uini(), w3updtmd::w3utrn(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
flagst
logical, dimension(:), pointer w3gdatmd::flagst
Definition at line 1221 of file w3gdatmd.F90.
   LOGICAL, POINTER :: FLAGST(:)
Referenced by w3setg(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), and wminitmd::wminitnml().
flagunr
logical, pointer w3gdatmd::flagunr
Definition at line 1193 of file w3gdatmd.F90.
   LOGICAL, POINTER      :: FLAGUNR
Referenced by w3ounfmetamd::init_meta(), w3crnc(), w3exnc(), w3iopomd::w3iope(), w3iopomd::w3iopp(), and w3setg().
flck
logical, pointer w3gdatmd::flck
Definition at line 1217 of file w3gdatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3initmd::w3init(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3setg(), and w3wavemd::w3wave().
flcth
logical, pointer w3gdatmd::flcth
Definition at line 1217 of file w3gdatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3initmd::w3init(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3setg(), and w3wavemd::w3wave().
flcx
logical, pointer w3gdatmd::flcx
Definition at line 1217 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3setg(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
flcy
logical, pointer w3gdatmd::flcy
Definition at line 1217 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3setg(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
fldry
logical, pointer w3gdatmd::fldry
Definition at line 1217 of file w3gdatmd.F90.
Referenced by w3setg(), and w3wavemd::w3wave().
flsou
logical, pointer w3gdatmd::flsou
Definition at line 1217 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setg(), and w3wavemd::w3wave().
flx4a0
real, pointer w3gdatmd::flx4a0
Definition at line 1289 of file w3gdatmd.F90.
   REAL, POINTER           :: FLX4A0
Referenced by w3flx4md::w3flx4(), and w3setg().
fpimin
real, pointer w3gdatmd::fpimin
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), w3setg(), and w3src2md::w3sin2().
fr1
real, pointer w3gdatmd::fr1
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3snl1md::insnlgqm(), w3bounc(), w3bound(), w3iobcmd::w3iobc(), w3setg(), w3snl1md::w3snlgqm(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmiohg(), and wmiopomd::wmiopo().
frq
real, dimension(:), pointer w3gdatmd::frq
Definition at line 1361 of file w3gdatmd.F90.
   REAL, POINTER           :: FRQ(:), XSI(:),                      &
        QST2(:,:,:), QST3(:,:,:),            &
        QST5(:,:,:), QST6(:,:,:),            &
        SNLL(:), SNLM(:), SNLT(:),           &
        SNLCD(:), SNLCS(:)
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
fsbccfl
logical, pointer w3gdatmd::fsbccfl
Definition at line 1406 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3setg(), and w3profsmd::w3xypfsn2().
fsfct
logical, pointer w3gdatmd::fsfct
Definition at line 1405 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3initmd::w3init(), w3setg(), and w3profsmd::w3xypug().
fsfreqshift
logical, pointer w3gdatmd::fsfreqshift
Definition at line 1406 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3initmd::w3init(), w3setg(), and w3wavemd::w3wave().
fshf
real, pointer w3gdatmd::fshf
Definition at line 1295 of file w3gdatmd.F90.
Referenced by w3setg(), and w3sln1md::w3sln1().
fsn
logical, pointer w3gdatmd::fsn
Definition at line 1405 of file w3gdatmd.F90.
   LOGICAL, POINTER  :: FSN,FSPSI,FSFCT,FSNIMP,FSTOTALIMP,FSTOTALEXP
Referenced by pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3initmd::w3init(), w3setg(), and w3profsmd::w3xypug().
fsnimp
logical, pointer w3gdatmd::fsnimp
Definition at line 1405 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3initmd::w3init(), w3setg(), and w3profsmd::w3xypug().
fspm
real, pointer w3gdatmd::fspm
Definition at line 1295 of file w3gdatmd.F90.
Referenced by w3setg(), and w3sln1md::w3sln1().
fspsi
logical, pointer w3gdatmd::fspsi
Definition at line 1405 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3initmd::w3init(), w3setg(), and w3profsmd::w3xypug().
fsrefraction
logical, pointer w3gdatmd::fsrefraction
Definition at line 1406 of file w3gdatmd.F90.
   LOGICAL, POINTER  :: FSREFRACTION, FSFREQSHIFT, FSSOURCE, FSBCCFL
Referenced by pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3initmd::w3init(), w3setg(), and w3wavemd::w3wave().
fssource
logical, pointer w3gdatmd::fssource
Definition at line 1406 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3sdb1md::w3sdb1(), w3setg(), w3srcemd::w3srce(), and w3wavemd::w3wave().
fstotalexp
logical, pointer w3gdatmd::fstotalexp
Definition at line 1405 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_init(), w3initmd::w3init(), w3setg(), and w3wavemd::w3wave().
fstotalimp
logical, pointer w3gdatmd::fstotalimp
Definition at line 1405 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::pdlib_init(), w3initmd::w3init(), w3setg(), and w3wavemd::w3wave().
fswell
real, pointer w3gdatmd::fswell
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3src2md::w3sin2().
fswnd
logical, pointer w3gdatmd::fswnd
Definition at line 1264 of file w3gdatmd.F90.
Referenced by w3idatmd::w3dimi(), w3setg(), w3updtmd::w3ucur(), w3uprstr(), w3updtmd::w3urho(), w3updtmd::w3utau(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().
fte
real, pointer w3gdatmd::fte
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3srcemd::calc_fpi(), w3iogomd::calc_wbt(), pdlib_w3profsmd::compute_mean_param(), wmesmfmd::fieldindex(), w3partmd::ptmean(), pdlib_w3profsmd::scal_integral_print_general(), w3iogomd::w3outg(), w3src2md::w3sds2(), w3setg(), w3src2md::w3sin2(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3str1md::w3str1(), w3swldmd::w3swl4(), and w3swldmd::w3swl6().
ftf
real, pointer w3gdatmd::ftf
Definition at line 1232 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::compute_mean_param(), w3setg(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), and w3str1md::w3str1().
fttr
real, pointer w3gdatmd::fttr
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3srcemd::calc_fpi(), w3iogomd::w3outg(), w3setg(), and w3src2md::w3sin2().
ftwl
real, pointer w3gdatmd::ftwl
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3iogomd::w3outg(), and w3setg().
ftwn
real, pointer w3gdatmd::ftwn
Definition at line 1232 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::compute_mean_param(), w3setg(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src6md::w3spr6(), and w3swldmd::w3swl6().
funo3
logical, pointer w3gdatmd::funo3
Definition at line 1264 of file w3gdatmd.F90.
   LOGICAL, POINTER        :: FUNO3, FVERG, FSWND, ARCTC
Referenced by w3psmcmd::w3psmc(), and w3setg().
fverg
logical, pointer w3gdatmd::fverg
Definition at line 1264 of file w3gdatmd.F90.
Referenced by w3psmcmd::w3psmc(), and w3setg().
fxfm
real, pointer w3gdatmd::fxfm
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
fxpm
real, pointer w3gdatmd::fxpm
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
ginit
logical, pointer w3gdatmd::ginit
Definition at line 1217 of file w3gdatmd.F90.
   LOGICAL, POINTER :: GINIT, FLDRY, FLCX, FLCY, FLCTH, FLCK, FLSOU, IICEDISP,&
        IICESMOOTH
Referenced by w3setg().
gname
character(len=30), pointer w3gdatmd::gname
Definition at line 1223 of file w3gdatmd.F90.
   CHARACTER(LEN=30), POINTER :: GNAME
Referenced by w3bounc(), w3bound(), w3gridmd::w3grid(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iorsmd::w3iors(), w3ounf(), w3ounp(), w3prnc(), w3sbs1(), w3setg(), w3trnc(), and w3uprstr().
gqamp
real, dimension(:), pointer w3gdatmd::gqamp
Definition at line 1346 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snlgqm().
gqnf1
integer, pointer w3gdatmd::gqnf1
Definition at line 1345 of file w3gdatmd.F90.
Referenced by w3snl1md::insnlgqm(), and w3setg().
gqnq_om2
integer, pointer w3gdatmd::gqnq_om2
Definition at line 1345 of file w3gdatmd.F90.
Referenced by w3snl1md::insnlgqm(), and w3setg().
gqnt1
integer, pointer w3gdatmd::gqnt1
Definition at line 1345 of file w3gdatmd.F90.
Referenced by w3snl1md::insnlgqm(), and w3setg().
gqthrcou
real, pointer w3gdatmd::gqthrcou
Definition at line 1346 of file w3gdatmd.F90.
Referenced by w3snl1md::insnlgqm(), and w3setg().
gqthrsat
real, pointer w3gdatmd::gqthrsat
Definition at line 1346 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snlgqm().
grids
type(grid), dimension(:), allocatable, target w3gdatmd::grids
Definition at line 1088 of file w3gdatmd.F90.
   TYPE(GRID), TARGET, ALLOCATABLE :: GRIDS(:)
Referenced by pdlib_w3profsmd::all_va_integral_print(), w3triamd::area_si(), pdlib_w3profsmd::deallocate_pdlib_global(), wmscrpmd::get_scrip_info(), wmscrpmd::get_scrip_info_structured(), wmscrpmd::get_scrip_info_unstructured(), wmmdatmd::init_get_jsea_isproc_glob(), w3triamd::is_in_ungrid(), w3triamd::is_in_ungrid2(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_mapsta_init(), w3wavset::preparation_fd_scheme(), wmesmfmd::setservices(), w3uostmd::uost_initgrid(), w3uostmd::uost_setgrid(), w3dimug(), w3wdatmd::w3dimw(), w3dimx(), w3gntx(), w3nmod(), w3setg(), w3psmcmd::w3smcell(), w3psmcmd::w3smcgmp(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
gridshift
real(8), pointer w3gdatmd::gridshift
Definition at line 1189 of file w3gdatmd.F90.
   REAL(8),POINTER         :: GRIDSHIFT ! see notes in WMGHGH
Referenced by w3setg(), wminitmd::wminit(), and wminitmd::wminitnml().
gsqrt
real, dimension(:,:), pointer w3gdatmd::gsqrt
Definition at line 1210 of file w3gdatmd.F90.
   REAL   , POINTER :: GSQRT(:,:) ! SQRT(G) DEFINED ON IX,IY
Referenced by w3pro3md::w3cflxy(), w3gntx(), w3setg(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
gsu
type(t_gsu), pointer w3gdatmd::gsu
Definition at line 1226 of file w3gdatmd.F90.
   TYPE(T_GSU), POINTER :: GSU ! Grid search utility object
Referenced by w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3iotrmd::w3iotr(), w3setg(), wminitmd::wminit(), wminitmd::wminitnml(), and wmiopomd::wmiopp().
gtype
integer, pointer w3gdatmd::gtype
Definition at line 1094 of file w3gdatmd.F90.
   INTEGER, POINTER :: GTYPE
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::fieldindex(), w3parall::get_jsea_ibelong(), w3parall::init_get_isea(), w3parall::init_get_jsea_isproc(), wmmdatmd::init_get_jsea_isproc_glob(), pdlib_w3profsmd::pdlib_w3xypug(), wmesmfmd::readfromfile(), pdlib_w3profsmd::scal_integral_print_general(), w3parall::set_up_nseal_nsealm(), wmesmfmd::setupimpbmsk(), pdlib_w3profsmd::test_mpi_status(), w3gig1md::w3addig(), w3bounc(), w3bound(), w3crnc(), w3adatmd::w3dima(), w3wdatmd::w3dimw(), w3dimx(), w3adatmd::w3dmnl(), w3exnc(), w3gntx(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3pro3md::w3map3(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3ounf(), w3adatmd::w3seta(), w3setg(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3snl5md::w3snl5(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3utrn(), w3wavemd::w3wave(), w3adatmd::w3xdma(), w3adatmd::w3xeta(), w3profsmd::w3xypug(), w3wavset::wave_setup_computation(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmioeg(), wminiomd::wmioes(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), wmupdtmd::wmupdv(), and pdlib_w3profsmd::write_var_to_text_file().
guginit
logical, pointer w3gdatmd::guginit
Definition at line 1134 of file w3gdatmd.F90.
   LOGICAL, POINTER        :: GUGINIT
Referenced by w3setg().
hpfac
real, dimension(:,:), pointer w3gdatmd::hpfac
Definition at line 1211 of file w3gdatmd.F90.
   REAL   , POINTER :: HPFAC(:,:) ! H_P = SQRT(G_PP) DEFINED ON IX,IY
Referenced by w3oacpmd::cpl_oasis_grid(), w3gntx(), w3setg(), w3ref1md::w3sref(), w3updtmd::w3uini(), w3updtmd::w3utrn(), w3wavemd::w3wave(), w3pro2md::w3xyp2(), wmgridmd::wmgeql(), wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
hqfac
real, dimension(:,:), pointer w3gdatmd::hqfac
Definition at line 1212 of file w3gdatmd.F90.
   REAL   , POINTER :: HQFAC(:,:) ! H_Q = SQRT(G_QQ) DEFINED ON IX,IY
Referenced by w3oacpmd::cpl_oasis_grid(), w3gntx(), w3setg(), w3ref1md::w3sref(), w3updtmd::w3uini(), w3updtmd::w3utrn(), w3wavemd::w3wave(), w3pro2md::w3xyp2(), wmgridmd::wmgeql(), wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
i_diag
integer, dimension(:), pointer w3gdatmd::i_diag
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3setg().
iaa
integer, dimension(:), pointer w3gdatmd::iaa
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), w3wavset::fd_wave_setup_apply_fct(), w3setg(), and w3profsmd::w3xypfsnimp().
ialt
integer, pointer w3gdatmd::ialt
Definition at line 1368 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl4md::w3snl4().
ic2pars
real, dimension(:), pointer w3gdatmd::ic2pars
Definition at line 1145 of file w3gdatmd.F90.
   REAL,    POINTER        :: IC2PARS(:)
Referenced by w3setg(), and w3sic2md::w3sic2().
ic3pars
real, dimension(:), pointer w3gdatmd::ic3pars
Definition at line 1148 of file w3gdatmd.F90.
   REAL,    POINTER        :: IC3PARS(:)
Referenced by w3sic3md::w3ic3wncg_cheng(), w3sic3md::w3ic3wncg_v1(), w3setg(), w3sic3md::w3sic3(), and w3wavemd::w3wave().
ic4_cn
real, dimension(:), pointer w3gdatmd::ic4_cn
Definition at line 1154 of file w3gdatmd.F90.
   REAL, POINTER           :: IC4_CN(:)
Referenced by w3setg(), and w3sic4md::w3sic4().
ic4_fc
real, dimension(:), pointer w3gdatmd::ic4_fc
Definition at line 1153 of file w3gdatmd.F90.
   REAL, POINTER           :: IC4_FC(:)
Referenced by w3setg(), and w3sic4md::w3sic4().
ic4_fmin
real, pointer w3gdatmd::ic4_fmin
Definition at line 1155 of file w3gdatmd.F90.
   REAL, POINTER           :: IC4_FMIN, IC4_KIBK
Referenced by w3setg(), and w3sic4md::w3sic4().
ic4_ki
real, dimension(:), pointer w3gdatmd::ic4_ki
Definition at line 1152 of file w3gdatmd.F90.
   REAL, POINTER           :: IC4_KI(:)
Referenced by w3setg(), and w3sic4md::w3sic4().
ic4_kibk
real, pointer w3gdatmd::ic4_kibk
Definition at line 1155 of file w3gdatmd.F90.
Referenced by w3setg(), and w3sic4md::w3sic4().
ic4pars
integer, dimension(:), pointer w3gdatmd::ic4pars
Definition at line 1151 of file w3gdatmd.F90.
   INTEGER, POINTER        :: IC4PARS(:)
Referenced by w3setg(), and w3sic4md::w3sic4().
ic5pars
real, dimension(:), pointer w3gdatmd::ic5pars
Definition at line 1158 of file w3gdatmd.F90.
   REAL,    POINTER        :: IC5PARS(:)
Referenced by w3sic5md::fsdisp(), w3setg(), and w3sic5md::w3sic5().
icescales
real, dimension(:), pointer w3gdatmd::icescales
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
iclbac
integer, dimension(:), pointer w3gdatmd::iclbac
Definition at line 1171 of file w3gdatmd.F90.
Referenced by w3setg(), and w3wavemd::w3wave().
iclose
integer, pointer w3gdatmd::iclose
Definition at line 1096 of file w3gdatmd.F90.
   INTEGER, POINTER :: ICLOSE
Referenced by w3updtmd::w3dzxy(), w3gntx(), w3initmd::w3init(), w3iopomd::w3iopp(), w3iotrmd::w3iotr(), w3pro1md::w3map1(), w3setg(), w3wdasmd::w3wdas(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), and wmiopomd::wmiopp().
iclose_none
integer, parameter w3gdatmd::iclose_none = ICLO_NONE
Definition at line 629 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: ICLOSE_NONE = iclo_none
Referenced by w3updtmd::w3dzxy(), w3iopomd::w3iopp(), w3pro1md::w3map1(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
iclose_smpl
integer, parameter w3gdatmd::iclose_smpl = ICLO_SMPL
Definition at line 630 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: ICLOSE_SMPL = iclo_smpl
Referenced by w3updtmd::w3dzxy(), w3iopomd::w3iopp(), w3pro1md::w3map1(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
iclose_trpl
integer, parameter w3gdatmd::iclose_trpl = ICLO_TRPL
Definition at line 631 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: ICLOSE_TRPL = iclo_trpl
Referenced by w3updtmd::w3dzxy(), w3iopomd::w3iopp(), w3pro1md::w3map1(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
ie_cell
integer, dimension(:), pointer w3gdatmd::ie_cell
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), pdlib_w3profsmd::pdlib_init(), w3profsmd::w3cflug(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
ien
real(8), dimension(:,:), pointer w3gdatmd::ien
Definition at line 1122 of file w3gdatmd.F90.
   REAL(8), POINTER        :: IEN(:,:), LEN(:,:), SI(:)
Referenced by w3triamd::nvectri(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3triamd::ug_gradients(), w3profsmd::w3cflug(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
igpars
real, dimension(:), pointer w3gdatmd::igpars
Definition at line 1142 of file w3gdatmd.F90.
   REAL,    POINTER        :: IGPARS(:)
Referenced by w3canomd::secspom(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3iogomd::w3outg(), w3src4md::w3sds4(), w3setg(), w3srcemd::w3srce(), and w3ref1md::w3sref().
igrid
integer w3gdatmd::igrid = -1
Definition at line 618 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3snlsmd::insnls(), w3adatmd::w3dima(), w3idatmd::w3dimi(), w3wdatmd::w3dimw(), w3adatmd::w3dmnl(), w3odatmd::w3dmo2(), w3odatmd::w3dmo3(), w3odatmd::w3dmo5(), w3setg(), w3wavemd::w3wave(), w3adatmd::w3xdma(), wmmdatmd::wmdimd(), and wmmdatmd::wmdimm().
iiceddisp
real, pointer w3gdatmd::iiceddisp
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3dispmd::liu_forward_dispersion(), and w3setg().
iicedisp
logical, pointer w3gdatmd::iicedisp
Definition at line 1217 of file w3gdatmd.F90.
Referenced by w3exnc(), w3expo(), w3setg(), and w3srcemd::w3srce().
iicefdisp
real, pointer w3gdatmd::iicefdisp
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3dispmd::liu_forward_dispersion(), and w3setg().
iicehdisp
real, pointer w3gdatmd::iicehdisp
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3dispmd::liu_forward_dispersion(), and w3setg().
iicehfac
real, pointer w3gdatmd::iicehfac
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uic1().
iicehinit
real, pointer w3gdatmd::iicehinit
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3setg().
iicehmin
real, pointer w3gdatmd::iicehmin
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3dispmd::liu_forward_dispersion(), w3setg(), w3sis2md::w3sis2(), and w3updtmd::w3uic1().
iicesmooth
logical, pointer w3gdatmd::iicesmooth
Definition at line 1217 of file w3gdatmd.F90.
Referenced by w3setg(), w3sis2md::w3sis2(), and w3srcemd::w3srce().
ijkcel
integer, dimension(:,:), pointer w3gdatmd::ijkcel
Definition at line 1170 of file w3gdatmd.F90.
   INTEGER, POINTER :: IJKCel(:,:), IJKUFc(:,:), IJKVFc(:,:)
Referenced by w3oacpmd::cpl_oasis_grid(), w3smcomd::smc_interp(), w3psmcmd::smcaverg(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), w3psmcmd::w3psmc(), and w3setg().
ijkcel3
integer, dimension(:), pointer w3gdatmd::ijkcel3
Definition at line 1174 of file w3gdatmd.F90.
   INTEGER, POINTER :: IJKCel3(:), IJKCel4(:), &
        IJKVFc5(:), IJKVFc6(:), &
        IJKUFc5(:), IJKUFc6(:)
Referenced by w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3psmcmd::w3psmc(), and w3setg().
ijkcel4
integer, dimension(:), pointer w3gdatmd::ijkcel4
Definition at line 1174 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcxuno2(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno3(), w3psmcmd::w3psmc(), and w3setg().
ijkufc
integer, dimension(:,:), pointer w3gdatmd::ijkufc
Definition at line 1170 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcaverg(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3psmcmd::w3psmc(), and w3setg().
ijkufc5
integer, dimension(:), pointer w3gdatmd::ijkufc5
Definition at line 1174 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcaverg(), w3psmcmd::w3psmc(), and w3setg().
ijkufc6
integer, dimension(:), pointer w3gdatmd::ijkufc6
Definition at line 1174 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcaverg(), w3psmcmd::w3psmc(), and w3setg().
ijkvfc
integer, dimension(:,:), pointer w3gdatmd::ijkvfc
Definition at line 1170 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcaverg(), w3psmcmd::smcgradn(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), w3psmcmd::w3psmc(), and w3setg().
ijkvfc5
integer, dimension(:), pointer w3gdatmd::ijkvfc5
Definition at line 1174 of file w3gdatmd.F90.
Referenced by w3psmcmd::w3psmc(), and w3setg().
ijkvfc6
integer, dimension(:), pointer w3gdatmd::ijkvfc6
Definition at line 1174 of file w3gdatmd.F90.
Referenced by w3psmcmd::w3psmc(), and w3setg().
iktab
integer, dimension(:,:), pointer w3gdatmd::iktab
Definition at line 1321 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
index_cell
integer, dimension(:), pointer w3gdatmd::index_cell
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), pdlib_w3profsmd::pdlib_init(), w3profsmd::w3cflug(), and w3setg().
index_map
integer, dimension(:), pointer w3gdatmd::index_map
Definition at line 1114 of file w3gdatmd.F90.
   INTEGER, POINTER        :: INDEX_MAP(:)
Referenced by pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_mapsta_init(), and pdlib_w3profsmd::pdlib_w3xypug().
iobdp
integer*1, dimension(:), pointer w3gdatmd::iobdp
Definition at line 1130 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), w3profsmd::setdepth(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
iobdp_loc
integer*1, dimension(:), pointer w3gdatmd::iobdp_loc
Definition at line 1118 of file w3gdatmd.F90.
   INTEGER*1, POINTER   :: IOBDP_LOC(:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), and w3ref1md::w3sref().
iobp
integer*2, dimension(:), pointer w3gdatmd::iobp
Definition at line 1129 of file w3gdatmd.F90.
   INTEGER*2, POINTER      :: IOBP(:)
Referenced by pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi_source_2(), yowfunction::computeboundaryinformation(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3triamd::readmsh_iobp(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::setdepth(), w3triamd::ug_getopenboundary(), w3triamd::ug_gradients(), w3profsmd::w3cflug(), w3setg(), w3srcemd::w3srce(), w3wavemd::w3wave(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
iobp_loc
integer*2, dimension(:), pointer w3gdatmd::iobp_loc
Definition at line 1117 of file w3gdatmd.F90.
   INTEGER*2, POINTER   :: IOBP_LOC(:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3srcemd::w3srce(), w3ref1md::w3sref(), and w3wavemd::w3wave().
iobpa
integer*1, dimension(:), pointer w3gdatmd::iobpa
Definition at line 1130 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
iobpa_loc
integer*1, dimension(:), pointer w3gdatmd::iobpa_loc
Definition at line 1119 of file w3gdatmd.F90.
   INTEGER*1, POINTER   :: IOBPA_LOC(:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), and w3ref1md::w3sref().
iobpd
integer*1, dimension(:,:), pointer w3gdatmd::iobpd
Definition at line 1130 of file w3gdatmd.F90.
   INTEGER*1, POINTER      :: IOBPD(:,:), IOBDP(:), IOBPA(:)
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_w3xypug(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3gig1md::w3addig(), w3setg(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
iobpd_loc
integer*1, dimension(:,:), pointer w3gdatmd::iobpd_loc
Definition at line 1116 of file w3gdatmd.F90.
   INTEGER*1, POINTER   :: IOBPD_LOC(:,:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3srcemd::w3srce(), and w3ref1md::w3sref().
ipars
integer w3gdatmd::ipars = -1
Definition at line 618 of file w3gdatmd.F90.
Referenced by w3setg().
iqtpe
integer pointer w3gdatmd::iqtpe
Definition at line 1345 of file w3gdatmd.F90.
   INTEGER, POINTER        :: IQTPE, GQNF1, GQNT1, GQNQ_OM2
Referenced by w3snl2md::insnl2(), w3exnc(), w3setg(), w3snl2md::w3snl2(), and w3srcemd::w3srce().
is1c1
real, pointer w3gdatmd::is1c1
Definition at line 1426 of file w3gdatmd.F90.
   REAL, POINTER           :: IS1C1, IS1C2
Referenced by w3setg(), and w3sis1md::w3sis1().
is1c2
real, pointer w3gdatmd::is1c2
Definition at line 1426 of file w3gdatmd.F90.
Referenced by w3setg(), and w3sis1md::w3sis1().
is2pars
real, dimension(:), pointer w3gdatmd::is2pars
Definition at line 1161 of file w3gdatmd.F90.
   REAL,    POINTER        :: IS2PARS(:)
Referenced by w3sis2md::insis2(), w3setg(), w3sis2md::w3sis2(), and w3srcemd::w3srce().
isgrd
integer w3gdatmd::isgrd = -1
Definition at line 618 of file w3gdatmd.F90.
Referenced by w3setg().
ismcbp
integer, dimension(:), pointer w3gdatmd::ismcbp
Definition at line 1171 of file w3gdatmd.F90.
   INTEGER, POINTER :: ISMCBP(:),   ICLBAC(:)
Referenced by w3setg().
itsa
integer, pointer w3gdatmd::itsa
Definition at line 1368 of file w3gdatmd.F90.
   INTEGER, POINTER        :: ITSA, IALT
Referenced by w3setg(), and w3snl4md::w3snl4().
ja_ie
integer, dimension(:,:,:), pointer w3gdatmd::ja_ie
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3setg().
jaa
integer, dimension(:), pointer w3gdatmd::jaa
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), w3wavset::fd_wave_setup_apply_fct(), w3setg(), and w3profsmd::w3xypfsnimp().
kdcon
real, pointer w3gdatmd::kdcon
Definition at line 1347 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snl1().
kdmn
real, pointer w3gdatmd::kdmn
Definition at line 1347 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snl1().
lam
real, pointer w3gdatmd::lam
Definition at line 1347 of file w3gdatmd.F90.
Referenced by w3snl1md::insnl1(), and w3setg().
len
real(8), dimension(:,:), pointer w3gdatmd::len
Definition at line 1122 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3triamd::nvectri(), and w3setg().
mapfs
integer, dimension(:,:), pointer w3gdatmd::mapfs
Definition at line 1163 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::action_limiter_local(), pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), pdlib_field_vec::do_output_exchanges(), w3snl5md::insnl5(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::scal_integral_print_general(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::setdepth(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3wavset::trig_compute_lh_stress(), w3wavset::trig_wave_setup_computation(), w3triamd::ug_gradients(), w3updtmd::w3dzxy(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iopomd::w3iopp(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3triamd::w3nestug(), w3setg(), w3setref(), w3ref1md::w3sref(), w3wavemd::w3wave(), w3profsmd::w3xypug(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), and pdlib_w3profsmd::write_var_to_text_file().
mapsf
integer, dimension(:,:), pointer w3gdatmd::mapsf
Definition at line 1163 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::block_solver_init(), w3iogomd::calc_wbt(), w3oacpmd::cpl_oasis_define(), wmesmfmd::createexpmesh(), w3wavset::fd_compute_diff(), wmesmfmd::fieldindex(), w3parall::get_jsea_ibelong(), w3parall::init_get_jsea_isproc(), w3smcomd::mapsta_smc(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3wavset::preparation_fd_scheme(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), w3profsmd::setdepth(), w3ogcmmd::snd_fields_to_ocean(), w3parall::synchronize_ipgl_etc_array(), w3bounc(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3exnc(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iosfmd::w3iosf(), w3pro3md::w3map3(), w3pro3md::w3mapt(), w3triamd::w3nestug(), w3wavemd::w3nmin(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3uic1(), w3updtmd::w3uic5(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3urho(), w3updtmd::w3utau(), w3updtmd::w3utrn(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), and wmgridmd::wmsmceql().
mapst2
integer, dimension(:,:), pointer w3gdatmd::mapst2
Definition at line 1163 of file w3gdatmd.F90.
Referenced by w3exnc(), w3initmd::w3init(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3setg(), w3setref(), w3updtmd::w3uice(), w3updtmd::w3ulev(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
mapsta
integer, dimension(:,:), pointer w3gdatmd::mapsta
Definition at line 1163 of file w3gdatmd.F90.
   INTEGER, POINTER        :: MAPSTA(:,:), MAPST2(:,:),            &
        MAPFS(:,:), MAPSF(:,:)
Referenced by pdlib_w3profsmd::block_solver_init(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), wmesmfmd::fieldindex(), w3snl5md::insnl5(), w3smcomd::mapsta_smc(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::setdepth(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3ogcmmd::snd_fields_to_ocean(), w3wavset::trig_compute_lh_stress(), w3triamd::ug_gradients(), w3bounc(), w3bound(), w3iosfmd::w3cprt(), w3updtmd::w3dzxy(), w3exnc(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3triamd::w3nestug(), w3iogomd::w3outg(), w3setg(), w3setref(), w3updtmd::w3uice(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3utrn(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), and wmwavemd::wmwave().
mapsta_loc
integer, dimension(:), pointer w3gdatmd::mapsta_loc
Definition at line 1115 of file w3gdatmd.F90.
   INTEGER, POINTER        :: MAPSTA_LOC(:)
Referenced by pdlib_w3profsmd::pdlib_mapsta_init().
mapth
integer, dimension(:), pointer w3gdatmd::mapth
Definition at line 1231 of file w3gdatmd.F90.
Referenced by w3gig1md::w3addig(), w3sbs1md::w3sbs1(), w3setg(), w3ref1md::w3sref(), and w3updtmd::w3ulev().
mapwn
integer, dimension(:), pointer w3gdatmd::mapwn
Definition at line 1231 of file w3gdatmd.F90.
   INTEGER, POINTER        :: MAPWN(:), MAPTH(:)
Referenced by pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3gig1md::w3addig(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt8md::w3sbt8(), w3sbt9md::w3sbt9(), w3setg(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3ref1md::w3sref(), w3updtmd::w3ubpt(), and w3updtmd::w3ulev().
maxx
real, pointer w3gdatmd::maxx
Definition at line 1133 of file w3gdatmd.F90.
   REAL,POINTER            :: MAXX, MAXY, DXYMAX
Referenced by w3triamd::coordmax(), w3iopomd::w3iopp(), w3iotrmd::w3iotr(), w3setg(), and wmiopomd::wmiopp().
maxy
real, pointer w3gdatmd::maxy
Definition at line 1133 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3iopomd::w3iopp(), w3iotrmd::w3iotr(), w3setg(), and wmiopomd::wmiopp().
mpars
type(mpar), dimension(:), allocatable, target w3gdatmd::mpars
Definition at line 1090 of file w3gdatmd.F90.
   TYPE(MPAR), TARGET, ALLOCATABLE :: MPARS(:)
Referenced by w3snl3md::insnl3(), w3snlsmd::insnls(), w3dims(), w3nmod(), and w3setg().
mrfct
integer, pointer w3gdatmd::mrfct
Definition at line 1167 of file w3gdatmd.F90.
Referenced by w3oacpmd::cpl_oasis_grid(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno3(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno3(), w3iogrmd::w3iogr(), w3psmcmd::w3psmc(), and w3setg().
narc
integer, pointer w3gdatmd::narc
Definition at line 1168 of file w3gdatmd.F90.
Referenced by w3smcomd::smc_interp(), w3iogrmd::w3iogr(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3utau(), w3updtmd::w3uwnd(), wminitmd::wminit(), and wminitmd::wminitnml().
nauxgr
integer w3gdatmd::nauxgr
Definition at line 618 of file w3gdatmd.F90.
Referenced by w3idatmd::w3dimi(), w3dims(), w3dimug(), w3dimx(), w3odatmd::w3dmo2(), w3gntx(), w3idatmd::w3ninp(), w3nmod(), w3odatmd::w3nout(), w3sbs1(), w3setg(), w3idatmd::w3seti(), and w3odatmd::w3seto().
nbac
integer, pointer w3gdatmd::nbac
Definition at line 1168 of file w3gdatmd.F90.
Referenced by w3smcomd::smc_interp(), w3iogrmd::w3iogr(), w3setg(), w3wavemd::w3wave(), wminitmd::wminit(), and wminitmd::wminitnml().
nbedge
integer, pointer w3gdatmd::nbedge
Definition at line 1104 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NBEDGE
Referenced by w3wavset::fd_wave_setup_compute_system(), and w3setg().
nbgl
integer, pointer w3gdatmd::nbgl
Definition at line 1168 of file w3gdatmd.F90.
Referenced by w3iogrmd::w3iogr(), w3setg(), and w3wavemd::w3wave().
nbnd_map
integer, pointer w3gdatmd::nbnd_map
Definition at line 1113 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NBND_MAP
Referenced by pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_mapsta_init(), and pdlib_w3profsmd::pdlib_w3xypug().
nbsmc
integer, pointer w3gdatmd::nbsmc
Definition at line 1168 of file w3gdatmd.F90.
Referenced by w3iogrmd::w3iogr(), w3setg(), wminitmd::wminit(), and wminitmd::wminitnml().
ncel
integer, pointer w3gdatmd::ncel
Definition at line 1167 of file w3gdatmd.F90.
   INTEGER, POINTER :: NCel, NUFc, NVFc, NRLv, MRFct
Referenced by w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), w3psmcmd::w3gathsmc(), w3iogrmd::w3iogr(), w3psmcmd::w3psmc(), w3psmcmd::w3scatsmc(), w3setg(), w3wavemd::w3wave(), wminitmd::wminit(), and wminitmd::wminitnml().
ndpths
integer, pointer w3gdatmd::ndpths
Definition at line 1351 of file w3gdatmd.F90.
Referenced by w3snl2md::insnl2(), and w3setg().
ndtab
integer, parameter w3gdatmd::ndtab =2000
Definition at line 637 of file w3gdatmd.F90.
   INTEGER,    PARAMETER   :: NDTAB=2000
Referenced by w3src4md::insin4(), w3dims(), and w3src4md::w3sds4().
neigh
integer, dimension(:,:), pointer w3gdatmd::neigh
Definition at line 1105 of file w3gdatmd.F90.
Referenced by w3wavset::fd_compute_lh_stress(), and w3setg().
nfrcut
integer, pointer w3gdatmd::nfrcut
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nfrmax
integer, pointer w3gdatmd::nfrmax
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nfrmin
integer, pointer w3gdatmd::nfrmin
Definition at line 1356 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NFRMIN, NFRMAX, NFRCUT, NTHMAX,      &
        NTHEXP, NSPMIN, NSPMAX, NSPMX2,      &
        NQA, SNLNQ
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nfrx
integer, pointer w3gdatmd::nfrx
Definition at line 1376 of file w3gdatmd.F90.
Referenced by w3snlsmd::insnls(), w3setg(), and w3snlsmd::w3snls().
nglo
integer, pointer w3gdatmd::nglo
Definition at line 1168 of file w3gdatmd.F90.
   INTEGER, POINTER :: NGLO, NARC, NBGL, NBAC, NBSMC
Referenced by w3smcomd::smc_interp(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3iogrmd::w3iogr(), w3psmcmd::w3psmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3utau(), w3updtmd::w3uwnd(), and w3wavemd::w3wave().
ngrids
integer w3gdatmd::ngrids = -1
Definition at line 618 of file w3gdatmd.F90.
   INTEGER                 :: NGRIDS = -1, igrid = -1, isgrd = -1, &
        ipars = -1, nauxgr
Referenced by w3adatmd::w3dima(), w3idatmd::w3dimi(), w3dims(), w3dimug(), w3wdatmd::w3dimw(), w3dimx(), w3adatmd::w3dmnl(), w3odatmd::w3dmo2(), w3odatmd::w3dmo3(), w3odatmd::w3dmo5(), w3gntx(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3idatmd::w3ninp(), w3nmod(), w3odatmd::w3nout(), w3sbs1(), w3setg(), w3adatmd::w3xdma(), wmmdatmd::wmdimd(), wmmdatmd::wmdimm(), and wmmdatmd::wmndat().
nic4
integer, parameter w3gdatmd::nic4 =16
Definition at line 622 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: NIC4=16 ,  nic42=5
Referenced by w3dimx(), and w3sic4md::w3sic4().
nic42
integer, parameter w3gdatmd::nic42 =5
Definition at line 622 of file w3gdatmd.F90.
Referenced by w3dimx().
nitersec1
integer, pointer w3gdatmd::nitersec1
Definition at line 1181 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NITERSEC1
Referenced by w3setg(), and w3wavemd::w3wave().
nittin
integer pointer w3gdatmd::nittin
Definition at line 1281 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NITTIN
Referenced by w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3setg(), and w3src2md::w3spr2().
nk
integer, pointer w3gdatmd::nk
Definition at line 1230 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NK, NK2, NTH, NSPEC
Referenced by pdlib_w3profsmd::action_limiter_local(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::block_solver_explicit_init(), pdlib_w3profsmd::block_solver_init(), w3srcemd::calc_fpi(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), pdlib_w3profsmd::compute_mean_param(), pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_field_vec::do_output_exchanges(), pdlib_w3profsmd::ergout(), wmesmfmd::fieldindex(), pdlib_field_vec::get_array_size(), w3sic3md::ic3table_cheng(), w3sbs1md::insbs1(), w3src3md::insin3(), w3src4md::insin4(), w3sis2md::insis2(), w3snl1md::insnl1(), w3snl2md::insnl2(), w3snl3md::insnl3(), w3snl5md::insnl5(), w3snl1md::insnlgqm(), w3snlsmd::insnls(), pdlib_w3profsmd::jacobi_init(), w3dispmd::liu_forward_dispersion(), w3dispmd::liu_reverse_dispersion(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::print_wn_statistic(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3partmd::ptnghb(), pdlib_w3profsmd::scal_integral_print_general(), w3iogomd::secondhh(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3srcemd::sign_vsd_patankar_ww3(), w3srcemd::sign_vsd_semi_implicit_ww3(), w3iogomd::skewness(), w3psmcmd::smcgtcrfr(), w3psmcmd::smckuno2(), w3src6md::tau_wave_atmos(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3bounc(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3crnc(), w3adatmd::w3dima(), w3dims(), w3adatmd::w3dmnl(), w3exgi(), w3exnc(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3sic3md::w3ic3wncg_cheng(), w3sic3md::w3ic3wncg_v1(), w3sic5md::w3ic5wncg(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3initmd::w3mpio(), w3ounp(), w3partmd::w3part(), w3psmcmd::w3psmc(), w3sis2md::w3rpwnice(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sbt8md::w3sbt8(), w3sbt9md::w3sbt9(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snl5md::w3snl5(), w3snl1md::w3snlgqm(), w3snlsmd::w3snls(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3str1md::w3str1(), w3swldmd::w3swl4(), w3swldmd::w3swl6(), w3updtmd::w3ubpt(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmiohg(), wmiopomd::wmiopo(), and pdlib_w3profsmd::write_var_to_text_file().
nk2
integer, pointer w3gdatmd::nk2
Definition at line 1230 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smckuno2(), w3dims(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), and w3setg().
nkd
integer, parameter w3gdatmd::nkd =1300
Definition at line 636 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3dims(), and w3src4md::w3sds4().
nkhs
integer, parameter w3gdatmd::nkhs =2000
Definition at line 636 of file w3gdatmd.F90.
   INTEGER,    PARAMETER   :: NKHS=2000, nkd=1300
Referenced by w3src4md::insin4(), w3dims(), and w3src4md::w3sds4().
nltail
real pointer w3gdatmd::nltail
Definition at line 1346 of file w3gdatmd.F90.
   REAL, POINTER           :: NLTAIL, GQTHRSAT, GQTHRCOU, GQAMP(:)
Referenced by w3snl2md::insnl2(), w3snl1md::insnlgqm(), and w3setg().
nlvcel
integer, dimension(:), pointer w3gdatmd::nlvcel
Definition at line 1169 of file w3gdatmd.F90.
   INTEGER, POINTER :: NLvCel(:), NLvUFc(:), NLvVFc(:)
Referenced by w3psmcmd::w3psmc(), and w3setg().
nlvufc
integer, dimension(:), pointer w3gdatmd::nlvufc
Definition at line 1169 of file w3gdatmd.F90.
Referenced by w3psmcmd::w3psmc(), and w3setg().
nlvvfc
integer, dimension(:), pointer w3gdatmd::nlvvfc
Definition at line 1169 of file w3gdatmd.F90.
Referenced by w3psmcmd::w3psmc(), and w3setg().
nnz
integer, pointer w3gdatmd::nnz
Definition at line 1109 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), w3wavset::fd_wave_setup_apply_fct(), w3triamd::readmsh(), w3setg(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
nqa
integer, pointer w3gdatmd::nqa
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nrlv
integer, pointer w3gdatmd::nrlv
Definition at line 1167 of file w3gdatmd.F90.
Referenced by w3smcomd::smc_interp(), w3iogrmd::w3iogr(), w3psmcmd::w3psmc(), w3setg(), wminitmd::wminit(), and wminitmd::wminitnml().
nsea
integer, pointer w3gdatmd::nsea
Definition at line 1097 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::all_va_integral_print(), w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_compute_lh_stress(), w3wavset::fd_wave_setup_apply_fct(), w3wavset::fd_wave_setup_apply_precond(), w3wavset::fd_wave_setup_computation(), w3wavset::fd_wave_setup_compute_system(), w3smcomd::mapsta_smc(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3wavset::preparation_fd_scheme(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3parall::set_up_nseal_nsealm(), w3smcomd::smc_interp(), w3psmcmd::smcaverg(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3r(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3r(), w3agcmmd::snd_fields_to_atmos(), w3igcmmd::snd_fields_to_ice(), w3parall::synchronize_global_array(), w3parall::synchronize_ipgl_etc_array(), w3wavset::trig_wave_setup_computation(), w3triamd::ug_gradients(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3bounc(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3adatmd::w3dima(), w3idatmd::w3dimi(), w3wdatmd::w3dimw(), w3dimx(), w3adatmd::w3dmnl(), w3updtmd::w3dzxy(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3pro3md::w3mapt(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3wavemd::w3nmin(), w3psmcmd::w3psmc(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3uic1(), w3updtmd::w3uic5(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3urho(), w3updtmd::w3utau(), w3updtmd::w3utrn(), w3updtmd::w3uwnd(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypug(), w3wavset::wave_setup_computation(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmgridmd::wmsmceql(), and wmupdtmd::wmupd1().
nseal
integer, pointer w3gdatmd::nseal
Definition at line 1097 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::all_field_integral_print(), pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::all_vaold_integral_print(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::block_solver_init(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3oacpmd::cpl_oasis_define(), wmesmfmd::createexpmesh(), pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_field_vec::do_output_exchanges(), pdlib_w3profsmd::ergout(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_wave_setup_computation(), wmesmfmd::fieldindex(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::print_wn_statistic(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), pdlib_w3profsmd::scal_integral_print_general(), pdlib_w3profsmd::scal_integral_print_r4(), pdlib_w3profsmd::scal_integral_print_r8(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), w3profsmd::setdepth(), w3iogomd::skewness(), w3agcmmd::snd_fields_to_atmos(), w3igcmmd::snd_fields_to_ice(), w3ogcmmd::snd_fields_to_ocean(), w3parall::synchronize_global_array(), w3wavset::trig_compute_lh_stress(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_scalar_prod(), w3wavset::trig_wave_setup_solve_poisson_neumann_dir(), w3triamd::ug_gradients(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3iosfmd::w3cprt(), w3adatmd::w3dima(), w3wdatmd::w3dimw(), w3adatmd::w3dmnl(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3setg(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3wavset::wave_setup_computation(), wminitmd::wminit(), wminitmd::wminitnml(), and pdlib_w3profsmd::write_var_to_text_file().
nspec
integer, pointer w3gdatmd::nspec
Definition at line 1230 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::action_limiter_local(), pdlib_w3profsmd::all_field_integral_print(), pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::all_vaold_integral_print(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::block_solver_init(), w3srcemd::calc_fpi(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_field_vec::do_output_exchanges(), pdlib_w3profsmd::ergout(), w3sbs1md::insbs1(), w3snl1md::insnl1(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::printtotaloffcontrib(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::pt_fld(), w3partmd::ptmean(), w3partmd::ptnghb(), w3partmd::ptsort(), pdlib_w3profsmd::scal_integral_print_general(), w3srcemd::sign_vsd_patankar_ww3(), w3srcemd::sign_vsd_semi_implicit_ww3(), w3src6md::tau_wave_atmos(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3adatmd::w3dima(), w3dims(), w3wdatmd::w3dimw(), w3adatmd::w3dmnl(), w3odatmd::w3dmo2(), w3odatmd::w3dmo5(), w3exgi(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro1md::w3map1(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3partmd::w3part(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sbt8md::w3sbt8(), w3sbt9md::w3sbt9(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3snl1md::w3snl1(), w3snl5md::w3snl5(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3str1md::w3str1(), w3swldmd::w3swl4(), w3swldmd::w3swl6(), w3updtmd::w3ubpt(), w3updtmd::w3uice(), w3updtmd::w3ulev(), w3adatmd::w3xdma(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), and pdlib_w3profsmd::write_var_to_text_file().
nsph
integer, pointer w3gdatmd::nsph
Definition at line 1376 of file w3gdatmd.F90.
Referenced by w3snlsmd::insnls(), w3setg(), and w3snlsmd::w3snls().
nspl
integer, pointer w3gdatmd::nspl
Definition at line 1376 of file w3gdatmd.F90.
Referenced by w3snlsmd::insnls(), w3setg(), and w3snlsmd::w3snls().
nspmax
integer, pointer w3gdatmd::nspmax
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nspmin
integer, pointer w3gdatmd::nspmin
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nspmx2
integer, pointer w3gdatmd::nspmx2
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nth
integer, pointer w3gdatmd::nth
Definition at line 1230 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::action_limiter_local(), w3fld1md::appendtail(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::block_solver_explicit_init(), pdlib_w3profsmd::block_solver_init(), w3srcemd::calc_fpi(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), pdlib_w3profsmd::compute_mean_param(), pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_w3profsmd::ergout(), wmesmfmd::fieldindex(), w3sbs1md::insbs1(), w3src4md::insin4(), w3sis2md::insis2(), w3snl1md::insnl1(), w3snl2md::insnl2(), w3snl3md::insnl3(), w3snl5md::insnl5(), w3snl1md::insnlgqm(), w3snlsmd::insnls(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3partmd::ptnghb(), pdlib_w3profsmd::scal_integral_print_general(), w3iogomd::secondhh(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3srcemd::sign_vsd_patankar_ww3(), w3srcemd::sign_vsd_semi_implicit_ww3(), w3iogomd::skewness(), w3psmcmd::smcdhxy(), w3psmcmd::smcgtcrfr(), w3psmcmd::smckuno2(), w3src6md::tau_wave_atmos(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3bounc(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3crnc(), w3adatmd::w3dima(), w3dims(), w3dimug(), w3adatmd::w3dmnl(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro1md::w3map1(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3ounp(), w3partmd::w3part(), w3psmcmd::w3psmc(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3setref(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snl5md::w3snl5(), w3snl1md::w3snlgqm(), w3snlsmd::w3snls(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3str1md::w3str1(), w3swldmd::w3swl4(), w3swldmd::w3swl6(), w3updtmd::w3ubpt(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), and pdlib_w3profsmd::write_var_to_text_file().
nthexp
integer, pointer w3gdatmd::nthexp
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nthmax
integer, pointer w3gdatmd::nthmax
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
nthx
integer, pointer w3gdatmd::nthx
Definition at line 1376 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NTHX, NFRX, NSPL, NSPH
Referenced by w3snlsmd::insnls(), w3setg(), and w3snlsmd::w3snls().
ntri
integer, pointer w3gdatmd::ntri
Definition at line 1109 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NTRI,COUNTRI,COUNTOT,NNZ
Referenced by w3triamd::area_si(), w3triamd::count(), wmesmfmd::createexpmesh(), w3triamd::get_boundary_status(), w3triamd::nvectri(), pdlib_w3profsmd::pdlib_init(), w3triamd::readmsh(), w3triamd::set_iobp(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), wmesmfmd::setexport(), w3triamd::spatial_grid(), w3triamd::ug_gradients(), w3profsmd::w3cflug(), w3dimug(), w3exnc(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
nufc
integer, pointer w3gdatmd::nufc
Definition at line 1167 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcaverg(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3iogrmd::w3iogr(), w3psmcmd::w3psmc(), w3setg(), wminitmd::wminit(), and wminitmd::wminitnml().
nvfc
integer, pointer w3gdatmd::nvfc
Definition at line 1167 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcaverg(), w3psmcmd::smcgradn(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), w3iogrmd::w3iogr(), w3psmcmd::w3psmc(), w3setg(), wminitmd::wminit(), and wminitmd::wminitnml().
nx
integer, pointer w3gdatmd::nx
Definition at line 1097 of file w3gdatmd.F90.
   INTEGER, POINTER        :: NX, NY, NSEA, NSEAL, TRFLAG
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::createexpmesh(), pdlib_field_vec::do_output_exchanges(), w3wavset::fd_compute_lh_stress(), w3wavset::fd_set_meanvalue_to_zero(), w3wavset::fd_wave_setup_apply_fct(), w3wavset::fd_wave_setup_computation(), w3wavset::fd_wave_setup_compute_system(), w3wavset::fd_wave_setup_scalar_prod(), w3wavset::fd_wave_setup_solve_poisson_neumann_dir(), wmesmfmd::fieldindex(), w3triamd::get_boundary_status(), interp(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3wavset::preparation_fd_scheme(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), w3triamd::readmsh(), w3triamd::readmshobc(), pdlib_w3profsmd::scal_integral_print_general(), pdlib_w3profsmd::set_iobdp_pdlib(), w3triamd::set_iobp(), pdlib_w3profsmd::set_iobpa_pdlib(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::setdepth(), wmesmfmd::setexport(), w3smcomd::smc_interp(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3parall::synchronize_global_array(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_scalar_prod(), w3triamd::ug_getopenboundary(), w3triamd::ug_gradients(), pdlib_field_vec::unst_pdlib_write_to_file(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3adatmd::w3dima(), w3idatmd::w3dimi(), w3dimug(), w3adatmd::w3dmnl(), w3odatmd::w3dmo3(), w3odatmd::w3dmo5(), w3updtmd::w3dzxy(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3gntx(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3pro1md::w3map1(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3pro3md::w3mapt(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3triamd::w3nestug(), w3wavemd::w3nmin(), w3prnc(), w3psmcmd::w3psmc(), w3sbs1(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3utrn(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupd1(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), wmwavemd::wmwave(), and pdlib_w3profsmd::write_var_to_text_file().
ny
integer, pointer w3gdatmd::ny
Definition at line 1097 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::createexpmesh(), w3wavset::fd_compute_lh_stress(), w3wavset::fd_wave_setup_compute_system(), wmesmfmd::fieldindex(), interp(), pdlib_w3profsmd::pdlib_w3xypug(), w3wavset::preparation_fd_scheme(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), w3triamd::readmshobc(), pdlib_w3profsmd::scal_integral_print_general(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), wmesmfmd::setexport(), w3smcomd::smc_interp(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3r(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3r(), w3triamd::ug_getopenboundary(), pdlib_field_vec::unst_pdlib_write_to_file(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3adatmd::w3dima(), w3idatmd::w3dimi(), w3adatmd::w3dmnl(), w3odatmd::w3dmo3(), w3odatmd::w3dmo5(), w3updtmd::w3dzxy(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3gntx(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3pro1md::w3map1(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3pro3md::w3mapt(), w3initmd::w3mpip(), w3wavemd::w3nmin(), w3prnc(), w3psmcmd::w3psmc(), w3sbs1(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3setg(), w3updtmd::w3ucur(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3utrn(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypug(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupd1(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), wmwavemd::wmwave(), and pdlib_w3profsmd::write_var_to_text_file().
ofstab
real, pointer w3gdatmd::ofstab
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uwnd().
optioncall
integer w3gdatmd::optioncall = 3
Definition at line 1110 of file w3gdatmd.F90.
   INTEGER                 :: optionCall = 3 ! take care all other options are basically wrong
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and w3srcemd::w3srce().
p2msf
integer, dimension(:), pointer w3gdatmd::p2msf
Definition at line 1098 of file w3gdatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), w3adatmd::w3dima(), w3iogomd::w3flgrdupdt(), w3initmd::w3mpio(), w3iogomd::w3outg(), w3adatmd::w3seta(), w3setg(), w3adatmd::w3xdma(), and w3adatmd::w3xeta().
pfmove
real, pointer w3gdatmd::pfmove
Definition at line 1183 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_w3xypug(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3setg(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
pinit
logical, pointer w3gdatmd::pinit
Definition at line 1241 of file w3gdatmd.F90.
   LOGICAL, POINTER        :: PINIT
Referenced by w3setg().
polat
real, pointer w3gdatmd::polat
Definition at line 1191 of file w3gdatmd.F90.
   REAL, POINTER         :: PoLat, PoLon
Referenced by w3smcomd::calc_interp(), w3ounfmetamd::init_meta(), w3bounc(), w3bound(), w3crnc(), w3exnc(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3ounf(), w3setg(), and w3updtmd::w3ubpt().
polon
real, pointer w3gdatmd::polon
Definition at line 1191 of file w3gdatmd.F90.
Referenced by w3smcomd::calc_interp(), w3bounc(), w3bound(), w3crnc(), w3exnc(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), and w3setg().
pos_cell
integer, dimension(:), pointer w3gdatmd::pos_cell
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), w3profsmd::w3cflug(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and w3profsmd::w3xypug().
posi
integer, dimension(:,:), pointer w3gdatmd::posi
Definition at line 1124 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), w3setg(), and w3profsmd::w3xypfsnimp().
qbi
real, dimension(:,:), pointer w3gdatmd::qbi
Definition at line 1323 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
qi5dis
integer, pointer w3gdatmd::qi5dis
Definition at line 1372 of file w3gdatmd.F90.
   INTEGER, POINTER        :: QI5DIS, QI5KEV, QI5IPL, QI5PMX
Referenced by w3snl5md::insnl5(), and w3setg().
qi5ipl
integer, pointer w3gdatmd::qi5ipl
Definition at line 1372 of file w3gdatmd.F90.
Referenced by w3snl5md::insnl5(), and w3setg().
qi5kev
integer, pointer w3gdatmd::qi5kev
Definition at line 1372 of file w3gdatmd.F90.
Referenced by w3snl5md::insnl5(), and w3setg().
qi5nnz
integer(kind=8), pointer w3gdatmd::qi5nnz
Definition at line 1373 of file w3gdatmd.F90.
   INTEGER(KIND=8), POINTER:: QI5NNZ
Referenced by w3snl5md::insnl5(), w3wdatmd::w3dimw(), w3setg(), and w3snl5md::w3snl5().
qi5pmx
integer, pointer w3gdatmd::qi5pmx
Definition at line 1372 of file w3gdatmd.F90.
Referenced by w3snl5md::insnl5(), w3setg(), and w3snl5md::w3snl5().
qr5dpt
real, pointer w3gdatmd::qr5dpt
Definition at line 1371 of file w3gdatmd.F90.
   REAL, POINTER           :: QR5DPT, QR5OML
Referenced by w3snl5md::insnl5(), w3setg(), and w3snl5md::w3snl5().
qr5oml
real, pointer w3gdatmd::qr5oml
Definition at line 1371 of file w3gdatmd.F90.
Referenced by w3snl5md::insnl5(), and w3setg().
qst1
integer, dimension(:,:,:), pointer w3gdatmd::qst1
Definition at line 1359 of file w3gdatmd.F90.
   INTEGER, POINTER        :: QST1(:,:,:), QST4(:,:,:)
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
qst2
real, dimension(:,:,:), pointer w3gdatmd::qst2
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
qst3
real, dimension(:,:,:), pointer w3gdatmd::qst3
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
qst4
integer, dimension(:,:,:), pointer w3gdatmd::qst4
Definition at line 1359 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
qst5
real, dimension(:,:,:), pointer w3gdatmd::qst5
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
qst6
real, dimension(:,:,:), pointer w3gdatmd::qst6
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
reflc
real, dimension(:,:), pointer w3gdatmd::reflc
Definition at line 1101 of file w3gdatmd.F90.
   REAL,    POINTER        :: REFLC(:,:)
Referenced by w3setg(), w3setref(), and w3wavemd::w3wave().
refld
integer, dimension(:,:), pointer w3gdatmd::refld
Definition at line 1102 of file w3gdatmd.F90.
   INTEGER, POINTER        :: REFLD(:,:)
Referenced by w3setg(), w3setref(), and w3wavemd::w3wave().
refpars
real, dimension(:), pointer w3gdatmd::refpars
Definition at line 1139 of file w3gdatmd.F90.
   REAL,    POINTER        :: REFPARS(:)
Referenced by pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3setg(), w3setref(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
refran
real, pointer w3gdatmd::refran
Definition at line 1263 of file w3gdatmd.F90.
Referenced by w3psmcmd::smcdhxy(), and w3setg().
rlgtype
integer, parameter w3gdatmd::rlgtype = 1
Definition at line 624 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: RLGTYPE = 1
Referenced by w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::fieldindex(), wmesmfmd::setupimpbmsk(), w3bounc(), w3bound(), w3crnc(), w3exnc(), w3gntx(), w3iopomd::w3iopp(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3snl5md::w3snl5(), w3ref1md::w3sref(), w3updtmd::w3uini(), w3updtmd::w3utrn(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wmgridmd::wmsmceql(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
rref
logical, dimension(:), pointer w3gdatmd::rref
Definition at line 1138 of file w3gdatmd.F90.
   LOGICAL, POINTER        ::  RREF(:)
Referenced by w3setg(), and w3setref().
rstype
integer, pointer w3gdatmd::rstype
Definition at line 1095 of file w3gdatmd.F90.
   INTEGER, POINTER :: RSTYPE
Referenced by w3initmd::w3init(), w3iorsmd::w3iors(), w3setg(), w3uprstr(), and w3wavemd::w3wave().
rwindc
real, pointer w3gdatmd::rwindc
Definition at line 1248 of file w3gdatmd.F90.
   REAL, POINTER           :: RWINDC
Referenced by w3setg(), and w3updtmd::w3uwnd().
satindices
integer, dimension(:,:), pointer w3gdatmd::satindices
Definition at line 1321 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
satweights
real, dimension(:,:), pointer w3gdatmd::satweights
Definition at line 1323 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
sbtc1
real, pointer w3gdatmd::sbtc1
Definition at line 1384 of file w3gdatmd.F90.
   REAL, POINTER           :: SBTC1
Referenced by w3sbt1md::w3sbt1(), and w3setg().
sbtcx
real, dimension(:), pointer w3gdatmd::sbtcx
Definition at line 1387 of file w3gdatmd.F90.
   REAL, POINTER           :: SBTCX(:)
Referenced by w3sbt4md::w3sbt4(), and w3setg().
sdbc1
real, pointer w3gdatmd::sdbc1
Definition at line 1393 of file w3gdatmd.F90.
   REAL, POINTER           :: SDBC1, SDBC2
Referenced by w3sdb1md::w3sdb1(), and w3setg().
sdbc2
real, pointer w3gdatmd::sdbc2
Definition at line 1393 of file w3gdatmd.F90.
Referenced by w3sdb1md::w3sdb1(), and w3setg().
sdbsc
real, pointer w3gdatmd::sdbsc
Definition at line 1395 of file w3gdatmd.F90.
   REAL, POINTER           :: SDBSC
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), and w3setg().
sds6a1
real, pointer w3gdatmd::sds6a1
Definition at line 1335 of file w3gdatmd.F90.
Referenced by w3src6md::w3sds6(), and w3setg().
sds6a2
real, pointer w3gdatmd::sds6a2
Definition at line 1335 of file w3gdatmd.F90.
Referenced by w3src6md::w3sds6(), and w3setg().
sds6et
logical, pointer w3gdatmd::sds6et
Definition at line 1338 of file w3gdatmd.F90.
   LOGICAL, POINTER        :: SDS6ET, SWL6S6, SWL6CSTB1
Referenced by w3src6md::w3sds6(), and w3setg().
sds6p1
integer, pointer w3gdatmd::sds6p1
Definition at line 1337 of file w3gdatmd.F90.
   INTEGER, POINTER        :: SDS6P1, SDS6P2
Referenced by w3src6md::w3sds6(), and w3setg().
sds6p2
integer, pointer w3gdatmd::sds6p2
Definition at line 1337 of file w3gdatmd.F90.
Referenced by w3src6md::w3sds6(), and w3setg().
sdsaln
real, pointer w3gdatmd::sdsaln
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
sdsc1
real, pointer w3gdatmd::sdsc1
Definition at line 1301 of file w3gdatmd.F90.
Referenced by w3src1md::w3sds1(), and w3setg().
sed_d50
real, dimension(:), pointer w3gdatmd::sed_d50
Definition at line 1214 of file w3gdatmd.F90.
   REAL, POINTER         :: SED_D50(:), SED_PSIC(:)
Referenced by w3setg(), and w3wavemd::w3wave().
sed_psic
real, dimension(:), pointer w3gdatmd::sed_psic
Definition at line 1214 of file w3gdatmd.F90.
Referenced by w3setg(), and w3wavemd::w3wave().
sgrds
type(sgrd), dimension(:), allocatable, target w3gdatmd::sgrds
Definition at line 1089 of file w3gdatmd.F90.
   TYPE(SGRD), TARGET, ALLOCATABLE :: SGRDS(:)
Referenced by w3uostmd::uost_initgrid(), w3uostmd::uost_setgrid(), w3dims(), w3nmod(), w3setg(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmiohg(), wmiopomd::wmiopo(), wmgridmd::wmrspc(), and wmgridmd::wmsmceql().
shstab
real, pointer w3gdatmd::shstab
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3uwnd().
si
real(8), dimension(:), pointer w3gdatmd::si
Definition at line 1122 of file w3gdatmd.F90.
Referenced by w3triamd::area_si(), w3wavset::fd_set_meanvalue_to_zero(), pdlib_w3profsmd::pdlib_init(), w3wavset::trig_set_meanvalue_to_zero(), w3profsmd::w3cflug(), w3setg(), w3ref1md::w3sref(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
sig
real, dimension(:), pointer w3gdatmd::sig
Definition at line 1234 of file w3gdatmd.F90.
Referenced by pdlib_w3profsmd::action_limiter_local(), w3srcemd::calc_fpi(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), pdlib_w3profsmd::compute_mean_param(), wmesmfmd::fieldindex(), w3sic3md::ic3table_cheng(), w3sbs1md::insbs1(), w3src3md::insin3(), w3src4md::insin4(), w3sis2md::insis2(), w3snl1md::insnl1(), w3snl2md::insnl2(), w3snl3md::insnl3(), w3snl5md::insnl5(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3iogomd::secondhh(), w3iogomd::skewness(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3crnc(), w3exnc(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3sic3md::w3ic3wncg_cheng(), w3sic3md::w3ic3wncg_v1(), w3sic5md::w3ic5wncg(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3iogomd::w3outg(), w3partmd::w3part(), w3psmcmd::w3psmc(), w3sis2md::w3rpwnice(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sbt8md::w3sbt8(), w3sbt9md::w3sbt9(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src4md::w3sds4(), w3setg(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snl5md::w3snl5(), w3snl1md::w3snlgqm(), w3snlsmd::w3snls(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3str1md::w3str1(), w3swldmd::w3swl6(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypug(), wmgridmd::wmgeql(), and wmgridmd::wmghgh().
sig2
real, dimension(:), pointer w3gdatmd::sig2
Definition at line 1234 of file w3gdatmd.F90.
Referenced by wmesmfmd::fieldindex(), w3iobcmd::w3iobc(), w3sbs1md::w3sbs1(), w3src6md::w3sds6(), w3setg(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3ref1md::w3sref(), w3swldmd::w3swl4(), w3updtmd::w3ubpt(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), and wminiomd::wmiohs().
sin6a0
real, pointer w3gdatmd::sin6a0
Definition at line 1335 of file w3gdatmd.F90.
   REAL, POINTER           :: SIN6A0, SDS6A1, SDS6A2, SWL6B1, &
        SIN6WS, SIN6FC
Referenced by w3setg(), and w3src6md::w3sin6().
sin6fc
real, pointer w3gdatmd::sin6fc
Definition at line 1335 of file w3gdatmd.F90.
Referenced by w3setg().
sin6ws
real, pointer w3gdatmd::sin6ws
Definition at line 1335 of file w3gdatmd.F90.
Referenced by w3src6md::w3sds6(), w3setg(), and w3src6md::w3sin6().
sinc1
real, pointer w3gdatmd::sinc1
Definition at line 1301 of file w3gdatmd.F90.
   REAL, POINTER           :: SINC1, SDSC1
Referenced by w3setg(), and w3src1md::w3sin1().
sinit
logical, pointer w3gdatmd::sinit
Definition at line 1237 of file w3gdatmd.F90.
   LOGICAL, POINTER        :: SINIT
Referenced by w3setg().
sintailpar
real, dimension(:), pointer w3gdatmd::sintailpar
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::calc_ustar(), w3src4md::insin4(), w3setg(), w3src4md::w3sin4(), and w3srcemd::w3srce().
slnc1
real, pointer w3gdatmd::slnc1
Definition at line 1295 of file w3gdatmd.F90.
   REAL, POINTER           :: SLNC1, FSPM, FSHF
Referenced by w3setg(), and w3sln1md::w3sln1().
smctype
integer, parameter w3gdatmd::smctype = 4
Definition at line 627 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: SMCTYPE = 4
Referenced by w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), w3gntx(), w3iobcmd::w3iobc(), w3ounf(), w3ref1md::w3sref(), w3uprstr(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmioeg(), wminiomd::wmioes(), and wmgridmd::wmsmceql().
snlc1
real, pointer w3gdatmd::snlc1
Definition at line 1347 of file w3gdatmd.F90.
   REAL, POINTER           :: SNLC1, LAM, KDCON, KDMN,             &
        SNLS1, SNLS2, SNLS3
Referenced by w3setg(), and w3snl1md::w3snl1().
snlcd
real, dimension(:), pointer w3gdatmd::snlcd
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), and w3setg().
snlcs
real, dimension(:), pointer w3gdatmd::snlcs
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), and w3setg().
snll
real, dimension(:), pointer w3gdatmd::snll
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), and w3setg().
snlm
real, dimension(:), pointer w3gdatmd::snlm
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), and w3setg().
snlmsc
real, pointer w3gdatmd::snlmsc
Definition at line 1360 of file w3gdatmd.F90.
   REAL, POINTER           :: SNLMSC, SNLNSC, SNLSFD, SNLSFS
Referenced by w3setg(), and w3snl3md::w3snl3().
snlnq
integer, pointer w3gdatmd::snlnq
Definition at line 1356 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), and w3setg().
snlnsc
real, pointer w3gdatmd::snlnsc
Definition at line 1360 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl3md::w3snl3().
snls1
real, pointer w3gdatmd::snls1
Definition at line 1347 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snl1().
snls2
real, pointer w3gdatmd::snls2
Definition at line 1347 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snl1().
snls3
real, pointer w3gdatmd::snls3
Definition at line 1347 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl1md::w3snl1().
snlsfd
real, pointer w3gdatmd::snlsfd
Definition at line 1360 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl3md::w3snl3().
snlsfs
real, pointer w3gdatmd::snlsfs
Definition at line 1360 of file w3gdatmd.F90.
Referenced by w3setg(), and w3snl3md::w3snl3().
snlt
real, dimension(:), pointer w3gdatmd::snlt
Definition at line 1361 of file w3gdatmd.F90.
Referenced by w3snl3md::insnl3(), and w3setg().
snsst
real, dimension(:,:), pointer w3gdatmd::snsst
Definition at line 1377 of file w3gdatmd.F90.
Referenced by w3snlsmd::insnls(), w3setg(), and w3snlsmd::w3snls().
solverthr_stp
real(8), pointer w3gdatmd::solverthr_stp
Definition at line 1408 of file w3gdatmd.F90.
   REAL(8), POINTER  :: SOLVERTHR_STP
Referenced by w3wavset::trig_wave_setup_solve_poisson_neumann_dir(), and w3setg().
spcbac
real, dimension(:,:), pointer w3gdatmd::spcbac
Definition at line 1204 of file w3gdatmd.F90.
   REAL   , POINTER :: SPCBAC(:,:), ANGARC(:)
Referenced by w3setg(), and w3wavemd::w3wave().
ssdsabk
real, pointer w3gdatmd::ssdsabk
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), and w3setg().
ssdsbck
real, pointer w3gdatmd::ssdsbck
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
ssdsbint
real, pointer w3gdatmd::ssdsbint
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), and w3setg().
ssdsbm
real, dimension(:), pointer w3gdatmd::ssdsbm
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), and w3setg().
ssdsbr
real pointer w3gdatmd::ssdsbr
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), and w3setg().
ssdsbrf1
real, pointer w3gdatmd::ssdsbrf1
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
ssdsbrf2
real, pointer w3gdatmd::ssdsbrf2
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3setg().
ssdsbrfdf
integer, pointer w3gdatmd::ssdsbrfdf
Definition at line 1321 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), and w3setg().
ssdsbt
real pointer w3gdatmd::ssdsbt
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), and w3setg().
ssdsc
real, dimension(:), pointer w3gdatmd::ssdsc
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), w3setg(), and w3src4md::w3spr4().
ssdsc1
real, pointer w3gdatmd::ssdsc1
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg().
ssdsc2
real, pointer w3gdatmd::ssdsc2
Definition at line 1311 of file w3gdatmd.F90.
ssdsc3
real, pointer w3gdatmd::ssdsc3
Definition at line 1311 of file w3gdatmd.F90.
ssdsc4
real, pointer w3gdatmd::ssdsc4
Definition at line 1311 of file w3gdatmd.F90.
ssdsc5
real, pointer w3gdatmd::ssdsc5
Definition at line 1311 of file w3gdatmd.F90.
ssdsc6
real, pointer w3gdatmd::ssdsc6
Definition at line 1311 of file w3gdatmd.F90.
ssdscos
real pointer w3gdatmd::ssdscos
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), and w3setg().
ssdsdik
integer, pointer w3gdatmd::ssdsdik
Definition at line 1321 of file w3gdatmd.F90.
ssdsdth
real pointer w3gdatmd::ssdsdth
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::w3sds4(), and w3setg().
ssdshck
real, pointer w3gdatmd::ssdshck
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), and w3setg().
ssdsiso
integer, pointer w3gdatmd::ssdsiso
Definition at line 1321 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), and w3setg().
ssdsp
real pointer w3gdatmd::ssdsp
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::w3sds4(), and w3setg().
ssdspbk
real, pointer w3gdatmd::ssdspbk
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), and w3setg().
ssinbr
real, pointer w3gdatmd::ssinbr
Definition at line 1324 of file w3gdatmd.F90.
Referenced by w3setg(), and w3src4md::w3sin4().
ssinthp
real pointer w3gdatmd::ssinthp
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3sin3(), and w3src4md::w3sin4().
sstxftf
real pointer w3gdatmd::sstxftf
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3spr3(), and w3src4md::w3spr4().
sstxftftail
real, pointer w3gdatmd::sstxftftail
Definition at line 1340 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3spr3(), and w3src4md::w3spr4().
sstxftwn
real pointer w3gdatmd::sstxftwn
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3spr3(), and w3src4md::w3spr4().
sswellf
real, dimension(:), pointer w3gdatmd::sswellf
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src3md::w3spr3(), and w3src4md::w3spr4().
sswellfpar
integer, pointer w3gdatmd::sswellfpar
Definition at line 1321 of file w3gdatmd.F90.
   INTEGER, POINTER        :: SSWELLFPAR, SSDSISO,SSDSBRFDF,       &
        IKTAB(:,:), SATINDICES(:,:),SSDSDIK
Referenced by w3setg().
stedu
real, pointer w3gdatmd::stedu
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3iogomd::w3outg(), and w3setg().
stexu
real, pointer w3gdatmd::stexu
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3iogomd::w3outg(), and w3setg().
steyu
real, pointer w3gdatmd::steyu
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3iogomd::w3outg(), and w3setg().
swl6b1
real, pointer w3gdatmd::swl6b1
Definition at line 1335 of file w3gdatmd.F90.
Referenced by w3setg(), w3swldmd::w3swl4(), and w3swldmd::w3swl6().
swl6cstb1
logical, pointer w3gdatmd::swl6cstb1
Definition at line 1338 of file w3gdatmd.F90.
Referenced by w3setg(), and w3swldmd::w3swl6().
swl6s6
logical, pointer w3gdatmd::swl6s6
Definition at line 1338 of file w3gdatmd.F90.
Referenced by gxexpo(), w3exnc(), w3expo(), w3setg(), and w3srcemd::w3srce().
sx
real, pointer w3gdatmd::sx
Definition at line 1183 of file w3gdatmd.F90.
   REAL, POINTER           :: SX, SY, X0, Y0, DTCFL, DTCFLI, DTMAX, &
        DTMIN, DMIN, CTMAX, FICE0, FICEN,     &
        FICEL, PFMOVE, STEXU, STEYU, STEDU,   &
        IICEHMIN, IICEHINIT, ICESCALES(:),    &
        IICEHFAC, IICEHDISP, IICEDDISP, IICEFDISP, &
        BTBETA, AAIRCMIN, AAIRGB
Referenced by w3triamd::coordmax(), w3oacpmd::cpl_oasis_grid(), w3smcomd::smc_interp(), w3psmcmd::smcgradn(), w3bounc(), w3bound(), w3exnc(), w3gntx(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3psmcmd::w3psmc(), w3setg(), w3ref1md::w3sref(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro2md::w3xyp2(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
sy
real, pointer w3gdatmd::sy
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3oacpmd::cpl_oasis_grid(), w3smcomd::smc_interp(), w3psmcmd::smcgradn(), w3bounc(), w3bound(), w3exnc(), w3gntx(), w3iobcmd::w3iobc(), w3psmcmd::w3psmc(), w3setg(), w3ref1md::w3sref(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro2md::w3xyp2(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
tail_id
integer pointer w3gdatmd::tail_id
Definition at line 1270 of file w3gdatmd.F90.
   INTEGER, POINTER         :: TAIL_ID
Referenced by w3fld1md::infld(), and w3setg().
tail_lev
real pointer w3gdatmd::tail_lev
Definition at line 1271 of file w3gdatmd.F90.
   REAL, POINTER            :: TAIL_LEV, TAIL_TRAN1, TAIL_TRAN2
Referenced by w3fld1md::infld(), and w3setg().
tail_tran1
real pointer w3gdatmd::tail_tran1
Definition at line 1271 of file w3gdatmd.F90.
Referenced by w3fld1md::infld(), and w3setg().
tail_tran2
real pointer w3gdatmd::tail_tran2
Definition at line 1271 of file w3gdatmd.F90.
Referenced by w3fld1md::infld(), and w3setg().
th
real, dimension(:), pointer w3gdatmd::th
Definition at line 1234 of file w3gdatmd.F90.
   REAL, POINTER           :: TH(:), ESIN(:), ECOS(:), ES2(:),     &
        ESC(:), EC2(:), SIG(:), SIG2(:),     &
        DSIP(:), DSII(:), DDEN(:), DDEN2(:)
Referenced by w3fld1md::appendtail(), w3src4md::insin4(), w3snl2md::insnl2(), w3snl5md::insnl5(), w3partmd::ptmean(), w3iogomd::secondhh(), swh_rsrt_1pw(), w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3bounc(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3iobcmd::w3iobc(), w3iotrmd::w3iotr(), w3partmd::w3part(), w3setg(), w3setref(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3sis1md::w3sis1(), w3snl2md::w3snl2(), w3snl4md::w3snl4(), w3snl5md::w3snl5(), w3srcemd::w3srce(), w3updtmd::w3uini(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmiohg(), and wmiopomd::wmiopo().
trflag
integer, pointer w3gdatmd::trflag
Definition at line 1097 of file w3gdatmd.F90.
Referenced by w3setg(), and w3updtmd::w3utrn().
tria
real(8), dimension(:), pointer w3gdatmd::tria
Definition at line 1131 of file w3gdatmd.F90.
   REAL(8), POINTER        :: TRIA(:)
Referenced by w3triamd::area_si(), w3triamd::spatial_grid(), w3triamd::ug_gradients(), w3setg(), w3profsmd::w3xypfsfct2(), and w3profsmd::w3xypfsnimp().
trigp
integer, dimension(:,:), pointer w3gdatmd::trigp
Definition at line 1111 of file w3gdatmd.F90.
   INTEGER, POINTER        :: TRIGP(:,:)
Referenced by w3triamd::area_si(), wmesmfmd::createexpmesh(), w3triamd::get_boundary_status(), w3triamd::nvectri(), pdlib_w3profsmd::pdlib_init(), w3triamd::readmsh(), w3triamd::set_iobp(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), wmesmfmd::setexport(), w3triamd::spatial_grid(), w3triamd::ug_gradients(), w3profsmd::w3cflug(), w3exnc(), w3iopomd::w3iopp(), w3setg(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), and wmiopomd::wmiopp().
trnx
real, dimension(:,:), pointer w3gdatmd::trnx
Definition at line 1200 of file w3gdatmd.F90.
   REAL   , POINTER :: TRNX(:,:), TRNY(:,:) ! TRANSPARENCY INFORMATION ON IX,IY
Referenced by w3initmd::w3init(), w3iopomd::w3iopp(), w3setg(), w3setref(), and w3wavemd::w3wave().
trny
real, dimension(:,:), pointer w3gdatmd::trny
Definition at line 1200 of file w3gdatmd.F90.
Referenced by w3initmd::w3init(), w3iopomd::w3iopp(), w3setg(), w3setref(), and w3wavemd::w3wave().
ttauwshelter
real pointer w3gdatmd::ttauwshelter
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::insin4(), w3src4md::tabu_tauhf2(), w3setg(), and w3src4md::w3sin4().
ungtype
integer, parameter w3gdatmd::ungtype = 3
Definition at line 626 of file w3gdatmd.F90.
   INTEGER, PARAMETER      :: UNGTYPE = 3
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::fieldindex(), w3parall::get_jsea_ibelong(), wmscrpmd::get_scrip_info(), w3parall::init_get_isea(), w3parall::init_get_jsea_isproc(), wmmdatmd::init_get_jsea_isproc_glob(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::scal_integral_print_general(), w3parall::set_up_nseal_nsealm(), wmesmfmd::setupimpbmsk(), pdlib_w3profsmd::test_mpi_status(), w3gig1md::w3addig(), w3bounc(), w3bound(), w3crnc(), w3adatmd::w3dima(), w3wdatmd::w3dimw(), w3dimx(), w3adatmd::w3dmnl(), w3exnc(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3adatmd::w3seta(), w3srcemd::w3srce(), w3ref1md::w3sref(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3wavemd::w3wave(), w3adatmd::w3xdma(), w3adatmd::w3xeta(), w3profsmd::w3xypug(), w3wavset::wave_setup_computation(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), wmupdtmd::wmupdv(), and pdlib_w3profsmd::write_var_to_text_file().
uostfactorlocal
real, pointer w3gdatmd::uostfactorlocal
Definition at line 1401 of file w3gdatmd.F90.
   REAL, POINTER           :: UOSTFACTORLOCAL, UOSTFACTORSHADOW
Referenced by w3setg().
uostfactorshadow
real, pointer w3gdatmd::uostfactorshadow
Definition at line 1401 of file w3gdatmd.F90.
Referenced by w3setg().
uostfilelocal
character(len=:), pointer w3gdatmd::uostfilelocal
Definition at line 1400 of file w3gdatmd.F90.
   CHARACTER(LEN=:), POINTER   :: UOSTFILELOCAL, UOSTFILESHADOW
Referenced by w3setg().
uostfileshadow
character(len=:), pointer w3gdatmd::uostfileshadow
Definition at line 1400 of file w3gdatmd.F90.
Referenced by w3setg().
us3df
integer, dimension(:), pointer w3gdatmd::us3df
Definition at line 1098 of file w3gdatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), wmesmfmd::calcstokes3d(), pdlib_field_vec::do_output_exchanges(), w3adatmd::w3dima(), w3iogomd::w3fldtoij(), w3iogomd::w3flgrdflag(), w3iogomd::w3flgrdupdt(), w3initmd::w3mpio(), w3iogomd::w3readflgrd(), w3adatmd::w3seta(), w3setg(), w3adatmd::w3xdma(), and w3adatmd::w3xeta().
ussp_wn
real, dimension(:), pointer w3gdatmd::ussp_wn
Definition at line 1099 of file w3gdatmd.F90.
   REAL,    POINTER        :: USSP_WN(:)
Referenced by w3iogomd::calc_u3stokes(), w3exnc(), and w3setg().
usspf
integer, dimension(:), pointer w3gdatmd::usspf
Definition at line 1098 of file w3gdatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), w3adatmd::w3dima(), w3iogomd::w3fldtoij(), w3iogomd::w3flgrdflag(), w3iogomd::w3flgrdupdt(), w3initmd::w3mpio(), w3iogomd::w3readflgrd(), w3adatmd::w3seta(), w3setg(), w3adatmd::w3xdma(), and w3adatmd::w3xeta().
wdcg
real, pointer w3gdatmd::wdcg
Definition at line 1260 of file w3gdatmd.F90.
   REAL, POINTER           :: WDCG, WDTH
Referenced by w3pro3md::w3cflxy(), w3setg(), and w3pro3md::w3xyp3().
wdth
real, pointer w3gdatmd::wdth
Definition at line 1260 of file w3gdatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3setg(), and w3pro3md::w3xyp3().
wwcor
real, dimension(:), pointer w3gdatmd::wwcor
Definition at line 1251 of file w3gdatmd.F90.
   REAL, POINTER           :: WWCOR(:)
Referenced by w3setg(), and w3updtmd::w3uwnd().
wwnmeanp
real pointer w3gdatmd::wwnmeanp
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3spr3(), and w3src4md::w3spr4().
wwnmeanptail
real, pointer w3gdatmd::wwnmeanptail
Definition at line 1340 of file w3gdatmd.F90.
   REAL, POINTER           :: WWNMEANPTAIL, SSTXFTFTAIL
Referenced by w3setg(), w3src3md::w3spr3(), and w3src4md::w3spr4().
x0
real, pointer w3gdatmd::x0
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3oacpmd::cpl_oasis_grid(), w3smcomd::smc_interp(), w3bounc(), w3bound(), w3exnc(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3setg(), w3wdasmd::w3wdas(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
xf1
real, pointer w3gdatmd::xf1
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
xf2
real, pointer w3gdatmd::xf2
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
xfc
real, pointer w3gdatmd::xfc
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
xfh
real, pointer w3gdatmd::xfh
Definition at line 1304 of file w3gdatmd.F90.
Referenced by w3src2md::w3sds2(), and w3setg().
xflt
real, pointer w3gdatmd::xflt
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
xfr
real, pointer w3gdatmd::xfr
Definition at line 1232 of file w3gdatmd.F90.
Referenced by w3srcemd::calc_fpi(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), w3src4md::insin4(), w3snl1md::insnl1(), w3snl3md::insnl3(), w3snl1md::insnlgqm(), w3snlsmd::insnls(), pdlib_w3profsmd::pdlib_w3xypug(), w3partmd::ptmean(), w3iogomd::secondhh(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3iogomd::skewness(), w3psmcmd::smckuno2(), w3src3md::tabu_tauhf(), w3src6md::tau_wave_atmos(), w3bounc(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3crnc(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3iobcmd::w3iobc(), w3iotrmd::w3iotr(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3setg(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3sis2md::w3sis2(), w3snl4md::w3snl4(), w3snl1md::w3snlgqm(), w3snlsmd::w3snls(), w3trck(), w3trnc(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypug(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmiohg(), and wmiopomd::wmiopo().
xft
real, pointer w3gdatmd::xft
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
xgrd
double precision, dimension(:,:), pointer w3gdatmd::xgrd
Definition at line 1205 of file w3gdatmd.F90.
   DOUBLE PRECISION, POINTER :: XGRD(:,:), YGRD(:,:) ! X AND Y DEFINED ON IX,IY
Referenced by w3triamd::coordmax(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::createexpmesh(), w3wavset::fd_compute_diff(), w3snl5md::insnl5(), w3triamd::nvectri(), pdlib_w3profsmd::pdlib_init(), yowpdlibmain::postpartition2(), w3triamd::readmsh(), yowpdlibmain::runparmetis(), w3triamd::spatial_grid(), w3bounc(), w3bound(), w3exnc(), w3gntx(), w3initmd::w3init(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3triamd::w3nestug(), w3setg(), w3setref(), w3wavemd::w3wave(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmgridmd::wmsmceql(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
xrel
real, pointer w3gdatmd::xrel
Definition at line 1245 of file w3gdatmd.F90.
Referenced by w3setg(), and w3srcemd::w3srce().
xsi
real, dimension(:), pointer w3gdatmd::xsi
Definition at line 1361 of file w3gdatmd.F90.
Referenced by expand(), w3snl3md::insnl3(), w3setg(), and w3snl3md::w3snl3().
y0
real, pointer w3gdatmd::y0
Definition at line 1183 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3oacpmd::cpl_oasis_grid(), w3smcomd::smc_interp(), w3bounc(), w3bound(), w3exnc(), w3iobcmd::w3iobc(), w3iopomd::w3iopp(), w3setg(), w3wdasmd::w3wdas(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
ygrd
double precision, dimension(:,:), pointer w3gdatmd::ygrd
Definition at line 1205 of file w3gdatmd.F90.
Referenced by w3triamd::coordmax(), w3oacpmd::cpl_oasis_grid(), wmesmfmd::createexpmesh(), w3wavset::fd_compute_diff(), w3snl5md::insnl5(), w3triamd::nvectri(), pdlib_w3profsmd::pdlib_init(), yowpdlibmain::postpartition2(), w3triamd::readmsh(), yowpdlibmain::runparmetis(), w3triamd::spatial_grid(), w3bounc(), w3bound(), w3exnc(), w3gntx(), w3initmd::w3init(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3triamd::w3nestug(), w3setg(), w3setref(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3updtmd::w3ucur(), w3updtmd::w3ulev(), w3wavemd::w3wave(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmgridmd::wmsmceql(), wmupdtmd::wmupds(), and wmupdtmd::wmupdv().
zb
real, dimension(:), pointer w3gdatmd::zb
Definition at line 1195 of file w3gdatmd.F90.
   REAL   , POINTER :: ZB(:)
Referenced by yowpdlibmain::postpartition2(), w3triamd::readmsh(), w3initmd::w3init(), w3iopomd::w3iopp(), w3setg(), w3updtmd::w3ulev(), w3uprstr(), and w3wavemd::w3wave().
zwind
real, pointer w3gdatmd::zwind
Definition at line 1304 of file w3gdatmd.F90.
   REAL, POINTER           :: ZWIND, FSWELL, SHSTAB,               &
        OFSTAB, CCNG, CCPS, FFNG, FFPS,      &
        CDSA0, CDSA1, CDSA2, SDSALN,         &
        CDSB0, CDSB1, CDSB2, CDSB3, FPIMIN,  &
        XFH, XF1, XF2
Referenced by w3setg(), w3src2md::w3sin2(), w3src2md::w3spr2(), w3srcemd::w3srce(), and w3updtmd::w3uwnd().
zz0max
real pointer w3gdatmd::zz0max
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src4md::calc_ustar(), w3src3md::tabu_stress(), w3src4md::tabu_stress(), w3src3md::tabu_tauhf(), w3src4md::tabu_tauhf(), w3src4md::tabu_tauhf2(), and w3setg().
zz0rat
real pointer w3gdatmd::zz0rat
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3setg(), w3src3md::w3sin3(), and w3src4md::w3sin4().
zzalp
real pointer w3gdatmd::zzalp
Definition at line 1311 of file w3gdatmd.F90.
Referenced by w3src3md::tabu_tauhf(), w3src4md::tabu_tauhf(), w3src4md::tabu_tauhf2(), w3setg(), w3src3md::w3sin3(), and w3src4md::w3sin4().
zzwnd
real pointer w3gdatmd::zzwnd
Definition at line 1311 of file w3gdatmd.F90.
   REAL, POINTER           :: ZZWND, AALPHA, BBETA, ZZ0MAX, ZZ0RAT,&
        ZZALP, FFXFM, FFXPM,                 &
        SSINTHP, TTAUWSHELTER, SSWELLF(:),   &
        SSDSC1, SSDSC2, SSDSC3, SSDSBR,      &
        SSDSP, WWNMEANP, SSTXFTF, SSTXFTWN,  &
        SSDSC4, SSDSC5, SSDSC6, SSDSBT,      &
        DDELTA1, DDELTA2,                    &
        SSDSCOS, SSDSDTH, SSDSBM(:)
Referenced by w3src3md::calc_ustar(), w3src4md::calc_ustar(), w3src3md::tabu_stress(), w3src4md::tabu_stress(), w3setg(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src4md::w3spr4(), and w3srcemd::w3srce().