WAVEWATCH III: w3src1md Module Reference
w3src1md Module Reference
Bundle WAM cycle 3 input and dissipation source terms with their defining parameters.
Functions/Subroutines
subroutine w3spr1 (A, CG, WN, EMEAN, FMEAN, WNMEAN, AMAX)
subroutine w3sin1 (A, K, USTAR, USDIR, S, D)
Calculate diagonal of input source (actual source term put together in W3SRCE).
subroutine w3sds1 (A, K, EMEAN, FMEAN, WNMEAN, S, D)
Calculate whitecapping source term and diagonal term of derivative.
Detailed Description
Bundle WAM cycle 3 input and dissipation source terms with their defining parameters.
Author
H. L. Tolman
Date
29-May-2009
Function/Subroutine Documentation
w3sds1()
subroutine w3src1md::w3sds1 (real, dimension(nspec), intent(in) A, real, dimension(nspec), intent(in) K, real, intent(in) EMEAN, real, intent(in) FMEAN, real, intent(in) WNMEAN, real, dimension(nspec), intent(out) S, real, dimension(nspec), intent(out) D)
Calculate whitecapping source term and diagonal term of derivative.
Parameters
[in] A Action density spectrum (1-D).
[in] K Wavenumber for entire spectrum.
[in] EMEAN Mean wave energy.
[in] FMEAN Mean wave frequency.
[in] WNMEAN Mean wavenumber.
[out] S Source term (1-D version).
[out] D Diagonal term of derivative.
Author
H. L. Tolman
Date
23-Dec-2004
Definition at line 433 of file w3src1md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         23-Dec-2004 |
     !/                  +-----------------------------------+
     !/
     !/    05-Dec-1996 : Final FORTRAN 77                    ( version 1.18 )
     !/    08-Dec-1999 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/    23-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/
     !  1. Purpose :
     !
     !     Calculate whitecapping source term and diagonal term of derivative.
     !
     !  2. Method :
     !
     !       WAM-3
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       A       R.A.  I   Action density spectrum (1-D).
     !       K       R.A.  I   Wavenumber for entire spectrum.          *)
     !       EMEAN   Real  I   Mean wave energy.
     !       FMEAN   Real  I   Mean wave frequency.
     !       WNMEAN  Real  I   Mean wavenumber.
     !       S       R.A.  O   Source term (1-D version).
     !       D       R.A.  O   Diagonal term of derivative.             *)
     !     ----------------------------------------------------------------
     !                         *) Stored in 1-D array with dimension NTH*NK
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      PRT2DS    Subr. W3SRRYMD Print plot of spectrum.
     !      OUTMAT    Subr. W3SRRYMD Print out matrix.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !      W3EXPO    Subr.   N/A    Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S   Enable subroutine tracing.
     !     !/T   Enable general test output.
     !     !/T0  2-D print plot of source term.
     !     !/T1  Print arrays.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: nk, nth, nspec, sig, sdsc1
 #ifdef W3_T
     USE w3odatmd, ONLY: ndst
 #endif
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
 #ifdef W3_T0
     USE w3arrymd, ONLY: prt2ds
 #endif
 #ifdef W3_T1
     USE w3arrymd, ONLY: outmat
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: A(NSPEC), K(NSPEC),                  &
          EMEAN, FMEAN, WNMEAN
     REAL, INTENT(OUT)       :: S(NSPEC), D(NSPEC)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IS
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
 #ifdef W3_T0
     INTEGER                 :: IK, ITH
 #endif
     REAL                    :: FACTOR
 #ifdef W3_T0
     REAL                    :: DOUT(NK,NTH)
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SDS1')
 #endif
     !
     ! 1.  Common factor
     !
     factor = sdsc1 * fmean * wnmean**3 * emean**2
     !
 #ifdef W3_T
     WRITE (ndst,9000) sdsc1, fmean, wnmean, emean, factor
 #endif
     !
     ! 3.  Source term
     !
     d = factor * k
     s = d * a
     !
     ! ... Test output of arrays
     !
 #ifdef W3_T0
     DO ik=1, nk
       DO ith=1, nth
         dout(ik,ith) = d(ith+(ik-1)*nth)
       END DO
     END DO
     CALL prt2ds (ndst, nk, nk, nth, dout, sig(1:), '  ', 1.,    &
          0.0, 0.001, 'Diag Sds', ' ', 'NONAME')
 #endif
     !
 #ifdef W3_T1
     CALL outmat (ndst, d, nth, nth, nk, 'diag Sds')
 #endif
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SDS1 : COMMON FACT.: ',5e10.3)
 #endif
     !/
     !/ End of W3SDS1 ----------------------------------------------------- /
     !/
References w3odatmd::ndst, w3gdatmd::nk, w3gdatmd::nspec, w3gdatmd::nth, w3arrymd::outmat(), w3arrymd::prt2ds(), w3gdatmd::sdsc1, w3gdatmd::sig, and w3servmd::strace().
Referenced by gxexpo(), w3exnc(), w3expo(), and w3srcemd::w3srce().
w3sin1()
subroutine w3src1md::w3sin1 (real, dimension(nspec), intent(in) A, real, dimension(nspec), intent(in) K, real, intent(in) USTAR, real, intent(in) USDIR, real, dimension(nspec), intent(out) S, real, dimension(nspec), intent(out) D)
Calculate diagonal of input source (actual source term put together in W3SRCE).
Parameters
[in] A Action density spectrum (1-D).
[in] K Wavenumber for entire spectrum.
[in] USTAR Friction velocity.
[in] USDIR Direction of USTAR.
[out] S Source term (1-D version).
[out] D Diagonal term of derivative.
Author
H. L. Tolman
Date
23-Dec-2004
Definition at line 256 of file w3src1md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         23-Dec-2004 |
     !/                  +-----------------------------------+
     !/
     !/    05-Dec-1996 : Final FORTRAN 77                    ( version 1.18 )
     !/    08-Dec-1999 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/    23-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/
     !  1. Purpose :
     !
     !     Calculate diagonal of input source (actual source term put
     !     together in W3SRCE).
     !
     !  2. Method :
     !
     !       WAM-3 : Snyder et al. (1981), Komen et al. (1984).
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       A       R.A.  I   Action density spectrum (1-D).
     !       K       R.A.  I   Wavenumber for entire spectrum.          *)
     !       USTAR   Real  I   Friction velocity.
     !       USDIR   Real  I   Direction of USTAR.
     !       S       R.A.  O   Source term (1-D version).
     !       D       R.A.  O   Diagonal term of derivative.             *)
     !     ----------------------------------------------------------------
     !                         *) Stored as 1-D array with dimension NTH*NK
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      PRT2DS    Subr. W3SRRYMD Print plot of spectrum.
     !      OUTMAT    Subr. W3SRRYMD Print out matrix.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !      W3EXPO    Subr.   N/A    Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S   Enable subroutine tracing.
     !     !/T   Enable general test output.
     !     !/T0  2-D print plot of source term.
     !     !/T1  Print arrays.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_T
     USE constants
 #endif
     USE w3gdatmd, ONLY: nk, nth, nspec, sig, sig2, esin, ecos, sinc1
 #ifdef W3_T
     USE w3odatmd, ONLY: ndst
 #endif
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
 #ifdef W3_T0
     USE w3arrymd, ONLY: prt2ds
 #endif
 #ifdef W3_T1
     USE w3arrymd, ONLY: outmat
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: A(NSPEC), K(NSPEC), USTAR, USDIR
     REAL, INTENT(OUT)       :: S(NSPEC), D(NSPEC)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IS
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
 #ifdef W3_T0
     INTEGER                 :: IK, ITH
 #endif
     REAL                    :: COSU, SINU
 #ifdef W3_T0
     REAL                    :: DOUT(NK,NTH)
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SIN1')
 #endif
     !
 #ifdef W3_T
     WRITE (ndst,9000) sinc1, ustar, usdir*rade
 #endif
     !
     ! 1.  Preparations
     !
     cosu   = cos(usdir)
     sinu   = sin(usdir)
     !
     ! 2.  Diagonal
     !
     DO is=1, nspec
       d(is) = sinc1 * sig2(is) * max( 0. ,                         &
            ( ustar * (ecos(is)*cosu+esin(is)*sinu)                  &
            * k(is)/sig2(is) - 0.035714) )
     END DO
     !
     s = d * a
     !
     ! ... Test output of arrays
     !
 #ifdef W3_T0
     DO ik=1, nk
       DO ith=1, nth
         dout(ik,ith) = d(ith+(ik-1)*nth)
       END DO
     END DO
     CALL prt2ds (ndst, nk, nk, nth, dout, sig(1:), '  ', 1.,    &
          0.0, 0.001, 'Diag Sin', ' ', 'NONAME')
 #endif
     !
 #ifdef W3_T1
     CALL outmat (ndst, d, nth, nth, nk, 'diag Sin')
 #endif
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SIN1 : COMMON FACT.: ',3e10.3)
 #endif
     !/
     !/ End of W3SIN1 ----------------------------------------------------- /
     !/
References w3gdatmd::ecos, w3gdatmd::esin, w3odatmd::ndst, w3gdatmd::nk, w3gdatmd::nspec, w3gdatmd::nth, w3arrymd::outmat(), w3arrymd::prt2ds(), constants::rade, w3gdatmd::sig, w3gdatmd::sig2, w3gdatmd::sinc1, and w3servmd::strace().
Referenced by gxexpo(), w3exnc(), w3expo(), and w3srcemd::w3srce().
w3spr1()
subroutine w3src1md::w3spr1 (real, dimension(nth,nk), intent(in) A, real, dimension(nk), intent(in) CG, real, dimension(nk), intent(in) WN, real, intent(out) EMEAN, real, intent(out) FMEAN, real, intent(out) WNMEAN, real, intent(out) AMAX)
Parameters
[in] A Action as a function of direction and wavenumber.
[in] CG Group velocities.
[in] WN Wavenumber.
[out] EMEAN Mean wave energy.
[out] FMEAN Mean wave frequency.
[out] WNMEAN mean wavenumber.
[out] AMAX Maximum action density in spectrum.
Author
H. L. Tolman
Date
23-Dec-2004
Definition at line 88 of file w3src1md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         23-Dec-2004 |
     !/                  +-----------------------------------+
     !/
     !/    06-Dec-1996 : Final FORTRAN 77                    ( version 1.18 )
     !/    06-Dec-1999 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/    23-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/
     !  1. Purpose :
     !
     !     Calculate mean wave parameters for the use in the source term
     !     routines. (WAM-3)
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       A       R.A.  I   Action as a function of direction and
     !                         wavenumber.
     !       CG      R.A.  I   Group velocities.
     !       WN      R.A.  I   Wavenumbers.
     !       EMEAN   Real  O   Mean wave energy.
     !       FMEAN   Real  O   Mean wave frequency.
     !       WNMEAN  Real  O   Mean wavenumber.
     !       AMAX    Real  O   Maximum action density in spectrum.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !      W3EXPO    Subr.   N/A    Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !     !/T  Enable test output.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants
     USE w3gdatmd, ONLY: nk, nth, sig, dden, fte, ftf, ftwn
 #ifdef W3_T
     USE w3odatmd, ONLY: ndst
 #endif
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: A(NTH,NK), CG(NK), WN(NK)
     REAL, INTENT(OUT)       :: EMEAN, FMEAN, WNMEAN, AMAX
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IK, ITH
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     REAL                    :: EB(NK), EBAND
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SPR1')
 #endif
     !
     emean  = 0.
     fmean  = 0.
     wnmean = 0.
     amax   = 0.
     !
     ! 1.  Integral over directions
     !
     DO ik=1, nk
       eb(ik) = 0.
       DO ith=1, nth
         eb(ik) = eb(ik) + a(ith,ik)
         amax   = max( amax , a(ith,ik) )
       END DO
     END DO
     !
     ! 2.  Integrate over directions
     !
     DO ik=1, nk
       eb(ik) = eb(ik) * dden(ik) / cg(ik)
       emean  = emean  + eb(ik)
       fmean  = fmean  + eb(ik) / sig(ik)
       wnmean = wnmean + eb(ik) / sqrt(wn(ik))
     END DO
     !
     ! 3.  Add tail beyond discrete spectrum
     !     ( DTH * SIG absorbed in FTxx )
     !
     eband  = eb(nk) / dden(nk)
     emean  = emean  + eband * fte
     fmean  = fmean  + eband * ftf
     wnmean = wnmean + eband * ftwn
     !
     ! 4.  Final processing
     !
     fmean  = tpiinv * emean / max( 1.e-7 , fmean )
     wnmean = ( emean / max( 1.e-7 , wnmean ) )**2
     !
 #ifdef W3_T
     WRITE (ndst,9000) emean, fmean, wnmean
 #endif
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SPR1 : E,F,WN MEAN ',3e10.3)
 #endif
     !/
     !/ End of W3SPR1 ----------------------------------------------------- /
     !/
References w3gdatmd::dden, w3gdatmd::fte, w3gdatmd::ftf, w3gdatmd::ftwn, w3odatmd::ndst, w3gdatmd::nk, w3gdatmd::nth, w3gdatmd::sig, w3servmd::strace(), and constants::tpiinv.
Referenced by gxexpo(), w3exnc(), w3expo(), and w3srcemd::w3srce().