WAVEWATCH III: w3wdatmd Module Reference
w3wdatmd Module Reference
Define data structures to set up wave model dynamic data for several models simultaneously.
Data Types
type wdata
Functions/Subroutines
subroutine w3ndat (NDSE, NDST)
Set up the number of grids to be used.
subroutine w3dimw (IMOD, NDSE, NDST, F_ONLY)
Initialize an individual data grid at the proper dimensions.
subroutine w3setw (IMOD, NDSE, NDST)
Select one of the WAVEWATCH III grids / models.
Variables
integer nwdata = -1
integer iwdata = -1
type(wdata), dimension(:), allocatable, target wdatas
integer, dimension(:), pointer time
integer, dimension(:), pointer tlev
integer, dimension(:), pointer tice
integer, dimension(:), pointer trho
integer, dimension(:), pointer tic1
integer, dimension(:), pointer tic5
integer, dimension(:), pointer time00
integer, dimension(:), pointer timeend
integer, dimension(:), pointer qi5tbeg
real, dimension(:), pointer qr5tim0
real, dimension(:, :), pointer qr5cvk0
real, dimension(:), pointer qr5tmix
complex, dimension(:, :), pointer qc5int0
real, dimension(:,:), pointer va
real, dimension(:), pointer wlv
real, dimension(:), pointer ice
real, dimension(:), pointer rhoair
real, dimension(:), pointer ust
real, dimension(:), pointer ustdir
real, dimension(:), pointer asf
real, dimension(:), pointer fpis
real, dimension(:), pointer berg
real, dimension(:), pointer iceh
real, dimension(:), pointer icef
real, dimension(:), pointer icedmax
real, dimension(:), pointer zeta_setup
real, dimension(:), pointer fx_zs
real, dimension(:), pointer fy_zs
real, dimension(:), pointer sxx_zs
real, dimension(:), pointer sxy_zs
real, dimension(:), pointer syy_zs
real, dimension(:,:), pointer vstot
real, dimension(:,:), pointer vdtot
real, dimension(:,:), pointer vaold
logical, dimension(:), pointer shavetot
logical, pointer dinit
logical, pointer fl_all
Detailed Description
Define data structures to set up wave model dynamic data for several models simultaneously.
The number of grids is taken from W3GDATMD, and needs to be set first with W3DIMG.
Author
H. L. Tolman
Date
22-Mar-2021
Function/Subroutine Documentation
w3dimw()
subroutine w3wdatmd::w3dimw (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, logical, intent(in), optional F_ONLY)
Initialize an individual data grid at the proper dimensions.
Allocate directly into the structure array. Note that this cannot be done through the pointer alias!
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
[in] F_ONLY FLag for initializing field arrays only.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 343 of file w3wdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    22-Oct-2004 : Origination.                        ( version 3.06 )
     !/    13-Jun-2006 : Allocate VA consistent with MPI     ( version 3.09 )
     !/                  data types and initialize as needed.
     !/    05-Jul-2006 : Consolidate stress vector.          ( version 3.09 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    14-Nov-2013 : Initialize UST and USTDIR.          ( version 4.13 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    22-Mar-2021 : Support for variable air density    ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       F_ONLY  L.O.   I   FLag for initializing field arrays only.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOGO    Subr. W3IOGOMD Grid output IO routine.
     !      W3IORS    Subr. W3IORSMD Restart file IO routine.
     !      WW3_SHEL  Prog.   N/A    Main wave model driver.
     !      WW3_STRT  Prog.   N/A    Initial conditions program.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - W3SETW needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, igrid, w3setg, nspec, nsea, nseal, grids
     USE w3odatmd, ONLY: naproc, iaproc
     USE w3servmd, ONLY: extcde
     USE constants, ONLY : lpdlib, dair
     USE w3parall, ONLY: set_up_nseal_nsealm, lsloc
 #ifdef W3_NL5
     USE w3gdatmd, ONLY: qi5nnz
 #endif
 #ifdef W3_PDLIB
     use yownodepool, only: npa, np
     use yowrankmodule, only : rank
     USE w3gdatmd, ONLY: gtype, ungtype
 #endif
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST
     LOGICAL, INTENT(IN), OPTIONAL :: F_ONLY
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID, NSEALM, NSEATM
     INTEGER                 :: NSEAL_DUMMY, ISEA
 #ifdef W3_PDLIB
     INTEGER IRANK
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3DIMW')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( PRESENT(f_only) ) THEN
       fl_all = .NOT. f_only
     ELSE
       fl_all = .true.
     END IF
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nwdata ) THEN
       WRITE (ndse,1002) imod, nwdata
       CALL extcde (2)
     END IF
     !
     IF ( wdatas(imod)%DINIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     CALL set_up_nseal_nsealm(nseal_dummy, nsealm)
     nseatm = nsealm * naproc
     !
     IF ( fl_all ) THEN
       ALLOCATE ( wdatas(imod)%VA(nspec,0:nsealm), stat=istat ); wdatas(imod)%VA = 0.
       check_alloc_status( istat )
 #ifdef W3_PDLIB
       ALLOCATE ( wdatas(imod)%SHAVETOT(nseal), stat=istat )
 #endif
 #ifdef W3_PDLIB
       IF (.not. lsloc) THEN
         ALLOCATE ( wdatas(imod)%VSTOT(nspec,nseal), stat=istat )
 #endif
 #ifdef W3_PDLIB
         ALLOCATE ( wdatas(imod)%VDTOT(nspec,nseal), stat=istat )
 #endif
 #ifdef W3_PDLIB
       ENDIF ! LSLOC
       ALLOCATE ( wdatas(imod)%VAOLD(nspec,nseal), stat=istat )
 #endif
 #ifdef W3_PDLIB
       IF (.not. lsloc) THEN
         wdatas(imod)%VSTOT=0
 #endif
 #ifdef W3_PDLIB
         wdatas(imod)%VDTOT=0
 #endif
 #ifdef W3_PDLIB
       ENDIF ! LSLOC
       wdatas(imod)%SHAVETOT=.false.
 #endif
       !
       ! * Four arrays for NL5 (QL)
       ! * AFAIK, the set up of QR5TIM0, QR5CVK0, QC5INT0 should be similar
       ! * to VA, though I am not really clear about how FL_ALL works.
       ! *
 #ifdef W3_NL5
       ALLOCATE ( wdatas(imod)%QR5TIM0(0:nsealm),             &
            wdatas(imod)%QR5CVK0(nspec, 0:nsealm),      &
            wdatas(imod)%QC5INT0(qi5nnz, 0:nsealm),     &
            wdatas(imod)%QR5TMIX(0:nsealm), stat=istat)
       check_alloc_status( istat )
 #endif
       !
       ! * Initialized NL5 arrays with zero (QL)
 #ifdef W3_NL5
       wdatas(imod)%QR5TIM0 = 0.0
       wdatas(imod)%QR5CVK0 = 0.0
       wdatas(imod)%QC5INT0 = (0.0, 0.0)
       wdatas(imod)%QR5TMIX = 0.0
 #endif
       !
 #ifdef W3_NL5
       WRITE(*, *)
       WRITE(*, '(A, I4, I12)') '  [WW3 WDAT]: IMOD & QI5NNZ: ', imod, qi5nnz
       WRITE(*, *)
 #endif
       !
       IF ( nseal .NE. nsealm ) THEN
         DO isea=nseal+1,nsealm
           wdatas(imod)%VA(:,isea) = 0.
           !
 #ifdef W3_NL5
           wdatas(imod)%QR5TIM0(isea)   = 0.0
           wdatas(imod)%QR5CVK0(:,isea) = 0.0
           wdatas(imod)%QC5INT0(:,isea) = (0.0, 0.0)
           wdatas(imod)%QR5TMIX(isea)   = 0.0
 #endif
         END DO
       END IF
     END IF
     !
     ! ICE, ICEH, ICEF must be defined from 0:NSEA
     ALLOCATE ( wdatas(imod)%WLV(nsea),                              &
          wdatas(imod)%ICE(0:nsea),                            &
          wdatas(imod)%RHOAIR(nsea),                           &
 #ifdef W3_SETUP
          wdatas(imod)%ZETA_SETUP(nsea),                       &
 #endif
          wdatas(imod)%BERG(nsea),                             &
          wdatas(imod)%ICEH(0:nsea),                           &
          wdatas(imod)%ICEF(0:nsea),                           &
          wdatas(imod)%ICEDMAX(nsea),                          &
          wdatas(imod)%UST(0:nseatm),                          &
          wdatas(imod)%USTDIR(0:nseatm),                       &
          wdatas(imod)%ASF(nseatm),                            &
          wdatas(imod)%FPIS(nseatm), stat=istat                )
     check_alloc_status( istat )
     wdatas(imod)%WLV   (:) = 0.
     wdatas(imod)%ICE   (0:nsea) = 0.
     wdatas(imod)%RHOAIR(:) = dair
 #ifdef W3_SETUP
     wdatas(imod)%ZETA_SETUP(:) = 0.
 #endif
     wdatas(imod)%BERG  (:) = 0.
     wdatas(imod)%ICEH  (0:nsea) = grids(imod)%IICEHINIT
     wdatas(imod)%ICEF  (0:nsea) = 1000.
     wdatas(imod)%ICEDMAX(:) = 1000.
     wdatas(imod)%UST   (0:nseatm) = 1.e-5
     wdatas(imod)%USTDIR(0:nseatm) = 0.
     wdatas(imod)%ASF   (:) = 0.
     wdatas(imod)%FPIS  (:) = 0.
     wdatas(imod)%DINIT     = .true.
     CALL w3setw ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DIMW : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DIMW : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NWDATA = ',i10/)
 1003 FORMAT (/' *** ERROR W3DIMW : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DIMW : MODEL ',i4,' DIM. AT ',2i5,i7)
 #endif
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3setw ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
 #ifdef W3_T
 9001 FORMAT (' TEST W3DIMW : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DIMW : POINTERS RESET')
 9003 FORMAT (' TEST W3DIMW : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DIMW ----------------------------------------------------- /
     !/
References constants::dair, w3servmd::extcde(), fl_all, w3gdatmd::grids, w3gdatmd::gtype, w3odatmd::iaproc, w3gdatmd::igrid, constants::lpdlib, w3parall::lsloc, w3odatmd::naproc, w3gdatmd::ngrids, yownodepool::np, yownodepool::npa, w3gdatmd::nsea, w3gdatmd::nseal, w3gdatmd::nspec, nwdata, w3gdatmd::qi5nnz, yowrankmodule::rank, w3parall::set_up_nseal_nsealm(), w3servmd::strace(), w3gdatmd::ungtype, w3gdatmd::w3setg(), w3setw(), and wdatas.
Referenced by w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), and w3shel().
w3ndat()
subroutine w3wdatmd::w3ndat (integer, intent(in) NDSE, integer, intent(in) NDST)
Set up the number of grids to be used.
Use data stored in NGRIDS in W3GDATMD.
Parameters
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
10-Dec-2014
Definition at line 210 of file w3wdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    31-Mar-2004 : Origination.                        ( version 3.06 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Set up the number of grids to be used.
     !
     !  2. Method :
     !
     !     Use data stored in NGRIDS in W3GDATMD.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Error checks on previous setting of variable NGRIDS.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: I
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3NDAT')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001) ngrids
       CALL extcde (1)
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set variable and allocate arrays
     !
     ALLOCATE ( wdatas(0:ngrids), stat=istat )
     check_alloc_status( istat )
     nwdata = ngrids
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Initialize parameters
     !
     DO i=0, ngrids
       wdatas(i)%DINIT  = .false.
       wdatas(i)%FL_ALL = .false.
     END DO
     !
 #ifdef W3_T
     WRITE (ndst,9000) ngrids
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3NDAT : NGRIDS NOT YET SET *** '/         &
          '                    NGRIDS = ',i10/                   &
          '                    RUN W3NMOD FIRST'/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3NDAT : SETTING UP FOR ',i4,' GRIDS')
 #endif
     !/
     !/ End of W3NDAT ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3gdatmd::ngrids, nwdata, w3servmd::strace(), and wdatas.
Referenced by gxoutf(), gxoutp(), w3bounc(), w3bound(), w3grib(), w3grid_interp(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3shel(), w3strt(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().
w3setw()
subroutine w3wdatmd::w3setw (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Select one of the WAVEWATCH III grids / models.
Point pointers to the proper variables in the proper element of the GRIDS array.
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 660 of file w3wdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    31-Mar-2004 : Origination.                        ( version 3.06 )
     !/    05-Jul-2006 : Consolidate stress vector.          ( version 3.09 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    22-Mar-2021 : Support for variable air density    ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Select one of the WAVEWATCH III grids / models.
     !
     !  2. Method :
     !
     !     Point pointers to the proper variables in the proper element of
     !     the GRIDS array.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Many subroutines in the WAVEWATCH system.
     !
     !  6. Error messages :
     !
     !     Checks on parameter list IMOD.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SETW')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( nwdata .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.0 .OR. imod.GT.nwdata ) THEN
       WRITE (ndse,1002) imod, nwdata
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model numbers
     !
     iwdata = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers
     !
     time   => wdatas(imod)%TIME
 #ifdef W3_OASIS
     time00 => wdatas(imod)%TIME00
     timeend => wdatas(imod)%TIMEEND
 #endif
 #ifdef W3_NL5
     qi5tbeg => wdatas(imod)%QI5TBEG
 #endif
     tlev   => wdatas(imod)%TLEV
     tice   => wdatas(imod)%TICE
     trho   => wdatas(imod)%TRHO
     tic1   => wdatas(imod)%TIC1
     tic5   => wdatas(imod)%TIC5
     dinit  => wdatas(imod)%DINIT
     fl_all => wdatas(imod)%FL_ALL
     !
     IF ( dinit ) THEN
       IF ( fl_all ) THEN
         va     => wdatas(imod)%VA
 #ifdef W3_NL5
         qr5tim0 => wdatas(imod)%QR5TIM0
         qr5cvk0 => wdatas(imod)%QR5CVK0
         qc5int0 => wdatas(imod)%QC5INT0
         qr5tmix => wdatas(imod)%QR5TMIX
 #endif
 #ifdef W3_PDLIB
         shavetot     => wdatas(imod)%SHAVETOT
         vstot     => wdatas(imod)%VSTOT
         vdtot     => wdatas(imod)%VDTOT
         vaold     => wdatas(imod)%VAOLD
 #endif
       END IF
       wlv    => wdatas(imod)%WLV
       ice    => wdatas(imod)%ICE
       rhoair => wdatas(imod)%RHOAIR
 #ifdef W3_SETUP
       zeta_setup => wdatas(imod)%ZETA_SETUP
       fx_zs => wdatas(imod)%FX_zs
       fy_zs => wdatas(imod)%FY_zs
       sxx_zs => wdatas(imod)%SXX_zs
       sxy_zs => wdatas(imod)%SXY_zs
       syy_zs => wdatas(imod)%SYY_zs
 #endif
       berg   => wdatas(imod)%BERG
       iceh   => wdatas(imod)%ICEH
       icef   => wdatas(imod)%ICEF
       icedmax=> wdatas(imod)%ICEDMAX
       ust    => wdatas(imod)%UST
       ustdir => wdatas(imod)%USTDIR
       asf    => wdatas(imod)%ASF
       fpis   => wdatas(imod)%FPIS
     END IF
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3SETW : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3SETW : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NWDATA = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SETW : MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of W3SETW ----------------------------------------------------- /
     !/
References asf, berg, dinit, w3servmd::extcde(), fl_all, fpis, fx_zs, fy_zs, ice, icedmax, icef, iceh, iwdata, nwdata, qc5int0, qi5tbeg, qr5cvk0, qr5tim0, qr5tmix, rhoair, shavetot, w3servmd::strace(), sxx_zs, sxy_zs, syy_zs, tic1, tic5, tice, time, time00, timeend, tlev, trho, ust, ustdir, va, vaold, vdtot, vstot, wdatas, wlv, and zeta_setup.
Referenced by wmesmfmd::createexpmesh(), gxoutf(), gxoutp(), w3bounc(), w3bound(), w3dimw(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3shel(), w3strt(), w3uprstr(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
Variable Documentation
asf
real, dimension(:), pointer w3wdatmd::asf
Definition at line 183 of file w3wdatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iosfmd::w3cprt(), w3exgi(), w3grid_interp(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3initmd::w3mpio(), w3setw(), w3updtmd::w3uwnd(), and w3wavemd::w3wave().
berg
real, dimension(:), pointer w3wdatmd::berg
Definition at line 183 of file w3wdatmd.F90.
Referenced by gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3ounf(), w3outf(), w3setw(), w3updtmd::w3uice(), w3updtmd::w3utrn(), and w3wavemd::w3wave().
dinit
logical, pointer w3wdatmd::dinit
Definition at line 195 of file w3wdatmd.F90.
   LOGICAL, POINTER        :: DINIT, FL_ALL
Referenced by w3iogomd::w3iogo(), w3iorsmd::w3iors(), and w3setw().
fl_all
logical, pointer w3wdatmd::fl_all
Definition at line 195 of file w3wdatmd.F90.
Referenced by w3dimw(), and w3setw().
fpis
real, dimension(:), pointer w3wdatmd::fpis
Definition at line 183 of file w3wdatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3iogomd::w3outg(), w3setw(), and w3wavemd::w3wave().
fx_zs
real, dimension(:), pointer w3wdatmd::fx_zs
Definition at line 187 of file w3wdatmd.F90.
Referenced by w3setw().
fy_zs
real, dimension(:), pointer w3wdatmd::fy_zs
Definition at line 187 of file w3wdatmd.F90.
Referenced by w3setw().
ice
real, dimension(:), pointer w3wdatmd::ice
Definition at line 183 of file w3wdatmd.F90.
Referenced by gxoutf(), w3exgi(), w3grib(), w3grid_interp(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3ounf(), w3outf(), w3setw(), w3updtmd::w3uic5(), w3updtmd::w3uice(), w3updtmd::w3utrn(), and w3wavemd::w3wave().
icedmax
real, dimension(:), pointer w3wdatmd::icedmax
Definition at line 183 of file w3wdatmd.F90.
Referenced by w3setw(), w3updtmd::w3uic5(), and w3wavemd::w3wave().
icef
real, dimension(:), pointer w3wdatmd::icef
Definition at line 183 of file w3wdatmd.F90.
Referenced by gxoutf(), w3igcmmd::snd_fields_to_ice(), w3exgi(), w3grid_interp(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3setw(), w3updtmd::w3uic5(), and w3wavemd::w3wave().
iceh
real, dimension(:), pointer w3wdatmd::iceh
Definition at line 183 of file w3wdatmd.F90.
Referenced by gxoutf(), w3exgi(), w3grid_interp(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3ounf(), w3outf(), w3setw(), w3updtmd::w3uic1(), w3updtmd::w3uic5(), and w3wavemd::w3wave().
iwdata
integer w3wdatmd::iwdata = -1
Definition at line 134 of file w3wdatmd.F90.
Referenced by w3setw(), and w3wavemd::w3wave().
nwdata
integer w3wdatmd::nwdata = -1
Definition at line 134 of file w3wdatmd.F90.
   INTEGER                 :: NWDATA = -1, iwdata = -1
Referenced by w3dimw(), w3ndat(), and w3setw().
qc5int0
complex, dimension(:, :), pointer w3wdatmd::qc5int0
Definition at line 181 of file w3wdatmd.F90.
   COMPLEX, POINTER        :: QC5INT0(:, :)
Referenced by w3setw(), and w3snl5md::w3snl5().
qi5tbeg
integer, dimension(:), pointer w3wdatmd::qi5tbeg
Definition at line 179 of file w3wdatmd.F90.
   INTEGER, POINTER        :: QI5TBEG(:)
Referenced by w3setw(), w3shel(), and w3snl5md::w3snl5().
qr5cvk0
real, dimension(:, :), pointer w3wdatmd::qr5cvk0
Definition at line 180 of file w3wdatmd.F90.
Referenced by w3setw(), and w3snl5md::w3snl5().
qr5tim0
real, dimension(:), pointer w3wdatmd::qr5tim0
Definition at line 180 of file w3wdatmd.F90.
   REAL, POINTER           :: QR5TIM0(:), QR5CVK0(:, :), QR5TMIX(:)
Referenced by w3setw(), and w3snl5md::w3snl5().
qr5tmix
real, dimension(:), pointer w3wdatmd::qr5tmix
Definition at line 180 of file w3wdatmd.F90.
Referenced by w3setw(), and w3snl5md::w3snl5().
rhoair
real, dimension(:), pointer w3wdatmd::rhoair
Definition at line 183 of file w3wdatmd.F90.
Referenced by gxoutf(), w3exgi(), w3grib(), w3grid_interp(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3ounf(), w3outf(), w3setw(), w3updtmd::w3urho(), and w3wavemd::w3wave().
shavetot
logical, dimension(:), pointer w3wdatmd::shavetot
Definition at line 193 of file w3wdatmd.F90.
   LOGICAL, POINTER        :: SHAVETOT(:)
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setw(), and w3wavemd::w3wave().
sxx_zs
real, dimension(:), pointer w3wdatmd::sxx_zs
Definition at line 188 of file w3wdatmd.F90.
   REAL, POINTER :: SXX_zs(:), SXY_zs(:), SYY_zs(:)
Referenced by w3setw().
sxy_zs
real, dimension(:), pointer w3wdatmd::sxy_zs
Definition at line 188 of file w3wdatmd.F90.
Referenced by w3setw().
syy_zs
real, dimension(:), pointer w3wdatmd::syy_zs
Definition at line 188 of file w3wdatmd.F90.
Referenced by w3setw().
tic1
integer, dimension(:), pointer w3wdatmd::tic1
Definition at line 172 of file w3wdatmd.F90.
Referenced by w3iorsmd::w3iors(), w3setw(), w3updtmd::w3uic1(), and w3wavemd::w3wave().
tic5
integer, dimension(:), pointer w3wdatmd::tic5
Definition at line 172 of file w3wdatmd.F90.
Referenced by w3iorsmd::w3iors(), w3setw(), w3updtmd::w3uic5(), and w3wavemd::w3wave().
tice
integer, dimension(:), pointer w3wdatmd::tice
Definition at line 172 of file w3wdatmd.F90.
Referenced by w3exgi(), w3initmd::w3init(), w3iorsmd::w3iors(), w3setw(), w3updtmd::w3uice(), and w3wavemd::w3wave().
time
integer, dimension(:), pointer w3wdatmd::time
Definition at line 172 of file w3wdatmd.F90.
   INTEGER, POINTER        :: TIME(:), TLEV(:), TICE(:), TRHO(:),  &
        TIC1(:), TIC5(:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), gxoutf(), gxoutp(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), wmesmfmd::setservices(), w3bullmd::w3bull(), w3pro3md::w3cflxy(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3psmcmd::w3psmc(), w3src6md::w3sds6(), w3setw(), w3shel(), w3srcemd::w3srce(), w3updtmd::w3ucur(), w3updtmd::w3uic1(), w3updtmd::w3uic5(), w3updtmd::w3uice(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3urho(), w3updtmd::w3utau(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmupdtmd::wmupd1(), wmupdtmd::wmupd2(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
time00
integer, dimension(:), pointer w3wdatmd::time00
Definition at line 175 of file w3wdatmd.F90.
   INTEGER, POINTER        :: TIME00(:)
Referenced by w3setw(), w3shel(), and w3wavemd::w3wave().
timeend
integer, dimension(:), pointer w3wdatmd::timeend
Definition at line 176 of file w3wdatmd.F90.
   INTEGER, POINTER        :: TIMEEND(:)
Referenced by w3setw(), w3shel(), and w3wavemd::w3wave().
tlev
integer, dimension(:), pointer w3wdatmd::tlev
Definition at line 172 of file w3wdatmd.F90.
Referenced by w3exgi(), w3initmd::w3init(), w3iorsmd::w3iors(), w3setw(), w3updtmd::w3ulev(), and w3wavemd::w3wave().
trho
integer, dimension(:), pointer w3wdatmd::trho
Definition at line 172 of file w3wdatmd.F90.
Referenced by w3initmd::w3init(), w3iorsmd::w3iors(), w3setw(), and w3updtmd::w3urho().
ust
real, dimension(:), pointer w3wdatmd::ust
Definition at line 183 of file w3wdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_field_vec::do_output_exchanges(), wmesmfmd::fieldindex(), gxoutf(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3exgi(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3setw(), w3updtmd::w3uice(), w3updtmd::w3ulev(), and w3wavemd::w3wave().
ustdir
real, dimension(:), pointer w3wdatmd::ustdir
Definition at line 183 of file w3wdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3setw(), and w3wavemd::w3wave().
va
real, dimension(:,:), pointer w3wdatmd::va
Definition at line 183 of file w3wdatmd.F90.
   REAL, POINTER           :: VA(:,:), WLV(:), ICE(:), RHOAIR(:),  &
        UST(:), USTDIR(:), ASF(:), FPIS(:),  &
        BERG(:), ICEH(:), ICEF(:), ICEDMAX(:)
Referenced by pdlib_w3profsmd::all_field_integral_print(), pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_field_vec::do_output_exchanges(), pdlib_w3profsmd::ergout(), wmesmfmd::fieldindex(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3iosfmd::w3cprt(), w3exgi(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3grid_interp(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iorsmd::w3iors(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3setw(), w3shel(), w3srcemd::w3srce(), w3uprstr(), w3wavemd::w3wave(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmwavemd::wmwave(), and pdlib_w3profsmd::write_var_to_text_file().
vaold
real, dimension(:,:), pointer w3wdatmd::vaold
Definition at line 192 of file w3wdatmd.F90.
   REAL, POINTER           :: VAOLD(:,:)
Referenced by pdlib_w3profsmd::all_vaold_integral_print(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::ergout(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setw(), and w3wavemd::w3wave().
vdtot
real, dimension(:,:), pointer w3wdatmd::vdtot
Definition at line 191 of file w3wdatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setw(), and w3wavemd::w3wave().
vstot
real, dimension(:,:), pointer w3wdatmd::vstot
Definition at line 191 of file w3wdatmd.F90.
   REAL, POINTER           :: VSTOT(:,:), VDTOT(:,:)
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3setw(), and w3wavemd::w3wave().
wdatas
type(wdata), dimension(:), allocatable, target w3wdatmd::wdatas
Definition at line 168 of file w3wdatmd.F90.
   TYPE(WDATA), TARGET, ALLOCATABLE :: WDATAS(:)
Referenced by w3dimw(), w3exgi(), w3grid_interp(), w3ndat(), w3setw(), and wminiomd::wmiohg().
wlv
real, dimension(:), pointer w3wdatmd::wlv
Definition at line 183 of file w3wdatmd.F90.
Referenced by gxoutf(), w3exgi(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3ounf(), w3outf(), w3setw(), and w3updtmd::w3ulev().
zeta_setup
real, dimension(:), pointer w3wdatmd::zeta_setup
Definition at line 187 of file w3wdatmd.F90.
   REAL, POINTER :: ZETA_SETUP(:), FX_zs(:), FY_zs(:)
Referenced by w3wavset::fd_wave_setup_computation(), w3wavset::trig_wave_setup_computation(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3ounf(), w3setw(), and w3updtmd::w3ulev().