WAVEWATCH III: w3idatmd Module Reference
w3idatmd Module Reference
Define data structures to set up wave model input data for several models simultaneously.
Data Types
type input
Functions/Subroutines
subroutine w3ninp (NDSE, NDST)
Set up the number of grids to be used.
subroutine w3dimi (IMOD, NDSE, NDST, FLAGSTIDEIN)
Initialize an individual data grid at the proper dimensions.
subroutine w3seti (IMOD, NDSE, NDST)
Select one of the WAVEWATCH III grids / models.
Variables
integer nidata = -1
integer iidata = -1
integer jfirst = 1
integer ntide
real, dimension(:), allocatable tidefreq
type(input), dimension(:), allocatable, target inputs
integer, dimension(:,:), pointer tfn
integer, dimension(:), pointer tln
integer, dimension(:), pointer tc0
integer, dimension(:), pointer tcn
integer, dimension(:), pointer tw0
integer, dimension(:), pointer twn
integer, dimension(:), pointer tu0
integer, dimension(:), pointer tun
integer, dimension(:), pointer tin
integer, dimension(:), pointer tr0
integer, dimension(:), pointer trn
integer, dimension(:), pointer t0n
integer, dimension(:), pointer t1n
integer, dimension(:), pointer t2n
integer, dimension(:), pointer tdn
integer, dimension(:), pointer tg0
integer, dimension(:), pointer tgn
integer, dimension(:), pointer ttn
integer, dimension(:), pointer tvn
integer, dimension(:), pointer tzn
integer, dimension(:), pointer ti1
integer, dimension(:), pointer ti2
integer, dimension(:), pointer ti3
integer, dimension(:), pointer ti4
integer, dimension(:), pointer ti5
real, pointer ga0
real, pointer gd0
real, pointer gan
real, pointer gdn
real, dimension(:,:), pointer wx0
real, dimension(:,:), pointer wy0
real, dimension(:,:), pointer dt0
real, dimension(:,:), pointer wxn
real, dimension(:,:), pointer wyn
real, dimension(:,:), pointer dtn
real, pointer ifdef
real, pointer w3_wrst
real, dimension(:,:,:,:), pointer cxtide
real, dimension(:,:,:,:), pointer cytide
real, dimension(:,:,:,:), pointer wltide
logical, pointer iinit
logical, dimension(:), pointer inflags1
logical, dimension(:), pointer inflags2
logical, dimension(:), pointer flagsc
logical, pointer fllev
logical, pointer flcur
logical, pointer flwind
logical, pointer flice
logical, pointer fltaua
logical, pointer flrhoa
logical, pointer flmth
logical, pointer flmvs
logical, pointer flmdn
logical, pointer flic1
logical, pointer flic2
logical, pointer flic3
logical, pointer flic4
logical, pointer flic5
logical, pointer fllevtide
logical, pointer flcurtide
logical, pointer fllevresi
logical, pointer flcurresi
Detailed Description
Define data structures to set up wave model input data for several models simultaneously.
Author
H. L. Tolman
Date
22-Mar-2021
Function/Subroutine Documentation
w3dimi()
subroutine w3idatmd::w3dimi (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, logical, dimension(4), intent(in), optional FLAGSTIDEIN)
Initialize an individual data grid at the proper dimensions.
Allocate directly into the structure array. Note that this cannot be done through the pointer alias!
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
[in] FLAGSTIDEIN
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 435 of file w3idatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    02-Apr-2004 : Origination.                        ( version 3.06 )
     !/    19-Jul-2006 : Adding auxiliary grids.             ( version 3.10 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    21-Jun-2018 : Add FSWND input for SMC grid. JGLi  ( version 6.04 )
     !/    22-Mar-2021 : Momentum and air density support    ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Main wave model drivers.
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - W3SETI needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd,  ONLY: ngrids, nauxgr, igrid, w3setg, nx, ny
 #ifdef W3_SMC
     USE w3gdatmd,  ONLY: fswnd, nsea
 #endif
     USE w3servmd,  ONLY: extcde
 #ifdef W3_S
     USE w3servmd,  ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     LOGICAL, INTENT(IN), OPTIONAL     :: FLAGSTIDEIN(4)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID
     LOGICAL                 :: FLAGSTIDE(4)=.false.
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DIMI')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.nidata ) THEN
       WRITE (ndse,1002) imod, -nauxgr, nidata
       CALL extcde (2)
     END IF
     !
     IF ( inputs(imod)%IINIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
 #ifdef W3_TIDE
     IF ( PRESENT(flagstidein) ) THEN
       flagstide(:) = flagstidein(:)
     END IF
 #endif
     flic1  => inputs(imod)%INFLAGS1(-7)
     flic2  => inputs(imod)%INFLAGS1(-6)
     flic3  => inputs(imod)%INFLAGS1(-5)
     flic4  => inputs(imod)%INFLAGS1(-4)
     flic5  => inputs(imod)%INFLAGS1(-3)
     !
     flmdn  => inputs(imod)%INFLAGS1(-2)
     flmth  => inputs(imod)%INFLAGS1(-1)
     flmvs  => inputs(imod)%INFLAGS1(0)
     !
     fllev  => inputs(imod)%INFLAGS1(1)
     flcur  => inputs(imod)%INFLAGS1(2)
 #ifdef W3_TIDE
     fllevtide  => inputs(imod)%INFLAGS1(11)
     flcurtide  => inputs(imod)%INFLAGS1(12)
     fllevresi  => inputs(imod)%INFLAGS1(13)
     flcurresi  => inputs(imod)%INFLAGS1(14)
     !
     fllevtide = flagstide(1)
     flcurtide = flagstide(2)
     fllevresi = flagstide(3)
     flcurresi = flagstide(4)
 #endif
     flwind => inputs(imod)%INFLAGS1(3)
     flice  => inputs(imod)%INFLAGS1(4)
     fltaua => inputs(imod)%INFLAGS1(5)
     flrhoa => inputs(imod)%INFLAGS1(6)
     !
     ! notes: future improvement: flags for ICEPx should be
     !     "all or nothing" rather than 5 individual flags
     IF ( flic1  ) THEN
       ALLOCATE ( inputs(imod)%ICEP1(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( flic2  ) THEN
       ALLOCATE ( inputs(imod)%ICEP2(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( flic3  ) THEN
       ALLOCATE ( inputs(imod)%ICEP3(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( flic4  ) THEN
       ALLOCATE ( inputs(imod)%ICEP4(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( flic5  ) THEN
       ALLOCATE ( inputs(imod)%ICEP5(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( flmdn  ) THEN
       ALLOCATE ( inputs(imod)%MUDD(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( flmth  ) THEN
       ALLOCATE ( inputs(imod)%MUDT(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( flmvs  ) THEN
       ALLOCATE ( inputs(imod)%MUDV(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( fllev  ) THEN
       ALLOCATE ( inputs(imod)%WLEV(nx,ny), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( flcur  ) THEN
 #ifdef W3_SMC
       IF( fswnd ) THEN
         ALLOCATE ( inputs(imod)%CX0(nsea,1) ,              &
              inputs(imod)%CY0(nsea,1) ,              &
              inputs(imod)%CXN(nsea,1) ,              &
              inputs(imod)%CYN(nsea,1) , stat=istat )
       ELSE
 #endif
         ALLOCATE ( inputs(imod)%CX0(nx,ny) ,              &
              inputs(imod)%CY0(nx,ny) ,              &
              inputs(imod)%CXN(nx,ny) ,              &
              inputs(imod)%CYN(nx,ny) , stat=istat )
 #ifdef W3_SMC
       ENDIF
 #endif
       check_alloc_status( istat )
     END IF
     !
 #ifdef W3_TIDE
     IF ( fllevtide  ) THEN
       ALLOCATE ( inputs(imod)%WLTIDE(nx,ny,ntide,2), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( flcurtide  ) THEN
       ALLOCATE ( inputs(imod)%CXTIDE(nx,ny,ntide,2),  &
            inputs(imod)%CYTIDE(nx,ny,ntide,2), stat=istat )
       check_alloc_status( istat )
     END IF
 #endif
     !
 #ifdef W3_WRST
     IF(.NOT.(inputs(imod)%WRSTIINIT)) THEN
       ALLOCATE (   inputs(imod)%WXNwrst(nx,ny) ,              &
            inputs(imod)%WYNwrst(nx,ny) , stat=istat )
       inputs(imod)%WRSTIINIT=.true.
     ENDIF
 #endif
     IF ( flwind ) THEN
 #ifdef W3_SMC
       IF( fswnd ) THEN
         ALLOCATE ( inputs(imod)%WX0(nsea,1) ,              &
              inputs(imod)%WY0(nsea,1) ,              &
              inputs(imod)%DT0(nsea,1) ,              &
              inputs(imod)%WXN(nsea,1) ,              &
              inputs(imod)%WYN(nsea,1) ,              &
              inputs(imod)%DTN(nsea,1) , stat=istat )
       ELSE
 #endif
         ALLOCATE ( inputs(imod)%WX0(nx,ny) ,              &
              inputs(imod)%WY0(nx,ny) ,              &
              inputs(imod)%DT0(nx,ny) ,              &
              inputs(imod)%WXN(nx,ny) ,              &
              inputs(imod)%WYN(nx,ny) ,              &
              inputs(imod)%DTN(nx,ny) , stat=istat )
 #ifdef W3_SMC
       ENDIF
 #endif
       check_alloc_status( istat )
       inputs(imod)%DT0 = 0.
       inputs(imod)%DTN = 0.
     END IF
     !
     IF ( flice  ) THEN
       ALLOCATE ( inputs(imod)%ICEI(nx,ny),              &
            inputs(imod)%BERGI(nx,ny), stat=istat )
       check_alloc_status( istat )
       inputs(imod)%BERGI = 0.
     END IF
     !
     IF ( fltaua  ) THEN
 #ifdef W3_SMC
       IF( fswnd ) THEN
         ALLOCATE ( inputs(imod)%UX0(nsea,1) ,              &
              inputs(imod)%UY0(nsea,1) ,              &
              inputs(imod)%UXN(nsea,1) ,              &
              inputs(imod)%UYN(nsea,1) , stat=istat )
       ELSE
 #endif
         ALLOCATE ( inputs(imod)%UX0(nx,ny) ,              &
              inputs(imod)%UY0(nx,ny) ,              &
              inputs(imod)%UXN(nx,ny) ,              &
              inputs(imod)%UYN(nx,ny) , stat=istat )
 #ifdef W3_SMC
       ENDIF
 #endif
       check_alloc_status( istat )
     END IF
     !
     IF ( flrhoa  ) THEN
 #ifdef W3_SMC
       IF( fswnd ) THEN
         ALLOCATE ( inputs(imod)%RH0(nsea,1) ,             &
              inputs(imod)%RHN(nsea,1) , stat=istat )
       ELSE
 #endif
         ALLOCATE ( inputs(imod)%RH0(nx,ny) ,              &
              inputs(imod)%RHN(nx,ny) , stat=istat )
 #ifdef W3_SMC
       ENDIF
 #endif
       check_alloc_status( istat )
     END IF
     !
     inputs(imod)%IINIT  = .true.
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3seti ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     !
     RETURN
     !
     ! Check inputs for stresses
     IF(fltaua) THEN
 #ifdef W3_FLX0
       WRITE (ndse,*) " *** WARNING W3DIMI : TAUA NOT USED *** "
 #endif
 #ifdef W3_FLX1
       WRITE (ndse,*) " *** WARNING W3DIMI : TAUA NOT USED *** "
 #endif
 #ifdef W3_FLX2
       WRITE (ndse,*) " *** WARNING W3DIMI : TAUA NOT USED *** "
 #endif
 #ifdef W3_FLX3
       WRITE (ndse,*) " *** WARNING W3DIMI : TAUA NOT USED *** "
 #endif
 #ifdef W3_FLX4
       WRITE (ndse,*) " *** WARNING W3DIMI : TAUA NOT USED *** "
 #endif
     END IF
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DIMI : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DIMI : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NAUXGR = ',i10/                   &
          '                    NIDATA = ',i10/)
 1003 FORMAT (/' *** ERROR W3DIMI : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DIMI : MODEL ',i4,' DIM. AT ',2i5,i7)
 9001 FORMAT (' TEST W3DIMI : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DIMI : POINTERS RESET')
 9003 FORMAT (' TEST W3DIMI : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DIMI ----------------------------------------------------- /
     !/
References w3servmd::extcde(), flcur, flcurresi, flcurtide, flic1, flic2, flic3, flic4, flic5, flice, fllev, fllevresi, fllevtide, flmdn, flmth, flmvs, flrhoa, fltaua, flwind, w3gdatmd::fswnd, w3gdatmd::igrid, inputs, w3gdatmd::nauxgr, w3gdatmd::ngrids, nidata, w3gdatmd::nsea, ntide, w3gdatmd::nx, w3gdatmd::ny, w3servmd::strace(), w3gdatmd::w3setg(), and w3seti().
Referenced by w3initmd::w3init(), wminitmd::wminit(), and wminitmd::wminitnml().
w3ninp()
subroutine w3idatmd::w3ninp (integer, intent(in) NDSE, integer, intent(in) NDST)
Set up the number of grids to be used.
Use data stored in NGRIDS in W3GDATMD.
Parameters
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 283 of file w3idatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    02-Apr-2004 : Origination.                        ( version 3.06 )
     !/    19-Jul-2006 : Adding auxiliary grids.             ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    22-Mar-2021 : Momentum and air density support    ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Set up the number of grids to be used.
     !
     !  2. Method :
     !
     !     Use data stored in NGRIDS in W3GDATMD.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Error checks on previous setting of variable NGRIDS.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, nauxgr
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: I
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3NINP')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001) ngrids
       CALL extcde (1)
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set variable and allocate arrays
     !
     ALLOCATE ( inputs(-nauxgr:ngrids), stat=istat )
     check_alloc_status( istat )
     nidata = ngrids
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Initialize parameters
     !
     DO i=-nauxgr, ngrids
       inputs(i)%TFN(1,:) = -1
       inputs(i)%TFN(2,:) =  0
       inputs(i)%TC0(1)   = -1
       inputs(i)%TC0(2)   =  0
       inputs(i)%TW0(1)   = -1
       inputs(i)%TW0(2)   =  0
       inputs(i)%TU0(1)   = -1
       inputs(i)%TU0(2)   =  0
       inputs(i)%TR0(1)   = -1
       inputs(i)%TR0(2)   =  0
       inputs(i)%TDN(1)   = -1
       inputs(i)%TDN(2)   =  0
       inputs(i)%TG0(1)   = -1
       inputs(i)%TG0(2)   =  0
       inputs(i)%GA0      = 0.
       inputs(i)%GD0      = 0.
       inputs(i)%GAN      = 0.
       inputs(i)%GDN      = 0.
       inputs(i)%IINIT    = .false.
       inputs(i)%INFLAGS1 = .false.
       inputs(i)%INFLAGS2 = .false.
       inputs(i)%FLAGSC   = .false.
     END DO
     !
 #ifdef W3_T
     WRITE (ndst,9000) -nauxgr, ngrids
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3NINP : NGRIDS NOT YET SET *** '/         &
          '                    NGRIDS = ',i10/                   &
          '                    RUN W3NMOD FIRST'/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3NINP : SETTING UP FOR ',i2,' -',i3,' GRIDS')
 #endif
     !/
     !/ End of W3NINP ----------------------------------------------------- /
     !/
References w3servmd::extcde(), inputs, w3gdatmd::nauxgr, w3gdatmd::ngrids, nidata, and w3servmd::strace().
Referenced by w3shel(), w3strt(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().
w3seti()
subroutine w3idatmd::w3seti (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Select one of the WAVEWATCH III grids / models.
Point pointers to the proper variables in the proper element of the GRIDS array.
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 819 of file w3idatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    02-Apr-2004 : Origination.                        ( version 3.06 )
     !/    19-Jul-2006 : Adding auxiliary grids.             ( version 3.10 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    22-Mar-2021 : Momentum and air density support    ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Select one of the WAVEWATCH III grids / models.
     !
     !  2. Method :
     !
     !     Point pointers to the proper variables in the proper element of
     !     the GRIDS array.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any subroutine.
     !
     !  6. Error messages :
     !
     !     Many subroutines in the WAVEWATCH system.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: nauxgr
     !
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3SETI')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( nidata .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.-nauxgr .OR. imod.GT.nidata ) THEN
       WRITE (ndse,1002) imod, -nauxgr, nidata
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model numbers
     !
     iidata = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers
     !
     tfn    => inputs(imod)%TFN
     tc0    => inputs(imod)%TC0
     tw0    => inputs(imod)%TW0
     tu0    => inputs(imod)%TU0
     tr0    => inputs(imod)%TR0
     tg0    => inputs(imod)%TG0
     tdn    => inputs(imod)%TDN
     !
     ti1    => inputs(imod)%TFN(:,-7)
     ti2    => inputs(imod)%TFN(:,-6)
     ti3    => inputs(imod)%TFN(:,-5)
     ti4    => inputs(imod)%TFN(:,-4)
     ti5    => inputs(imod)%TFN(:,-3)
     !
     tzn    => inputs(imod)%TFN(:,-2)
     ttn    => inputs(imod)%TFN(:,-1)
     tvn    => inputs(imod)%TFN(:,0)
     !
     tln    => inputs(imod)%TFN(:,1)
     tcn    => inputs(imod)%TFN(:,2)
     twn    => inputs(imod)%TFN(:,3)
     tin    => inputs(imod)%TFN(:,4)
     tun    => inputs(imod)%TFN(:,5)
     trn    => inputs(imod)%TFN(:,6)
     t0n    => inputs(imod)%TFN(:,7)
     t1n    => inputs(imod)%TFN(:,8)
     t2n    => inputs(imod)%TFN(:,9)
     tgn    => inputs(imod)%TFN(:,10)
     !
     ga0    => inputs(imod)%GA0
     gd0    => inputs(imod)%GD0
     gan    => inputs(imod)%GAN
     gdn    => inputs(imod)%GDN
     !
     iinit  => inputs(imod)%IINIT
     inflags1  => inputs(imod)%INFLAGS1
     inflags2  => inputs(imod)%INFLAGS2
     flagsc => inputs(imod)%FLAGSC
     !
     flic1  => inputs(imod)%INFLAGS1(-7)
     flic2  => inputs(imod)%INFLAGS1(-6)
     flic3  => inputs(imod)%INFLAGS1(-5)
     flic4  => inputs(imod)%INFLAGS1(-4)
     flic5  => inputs(imod)%INFLAGS1(-3)
     !
     flmdn  => inputs(imod)%INFLAGS1(-2)
     flmth  => inputs(imod)%INFLAGS1(-1)
     flmvs  => inputs(imod)%INFLAGS1(0)
     !
     fllev  => inputs(imod)%INFLAGS1(1)
     flcur  => inputs(imod)%INFLAGS1(2)
 #ifdef W3_TIDE
     fllevtide  => inputs(imod)%INFLAGS1(11)
     flcurtide  => inputs(imod)%INFLAGS1(12)
     fllevresi  => inputs(imod)%INFLAGS1(13)
     flcurresi  => inputs(imod)%INFLAGS1(14)
 #endif
     flwind => inputs(imod)%INFLAGS1(3)
     flice  => inputs(imod)%INFLAGS1(4)
     fltaua => inputs(imod)%INFLAGS1(5)
     flrhoa => inputs(imod)%INFLAGS1(6)
     !
     IF ( iinit ) THEN
       !
       IF ( flic1  ) THEN
         icep1  => inputs(imod)%ICEP1
       END IF
       IF ( flic2  ) THEN
         icep2  => inputs(imod)%ICEP2
       END IF
       IF ( flic3  ) THEN
         icep3  => inputs(imod)%ICEP3
       END IF
       IF ( flic4  ) THEN
         icep4  => inputs(imod)%ICEP4
       END IF
       IF ( flic5  ) THEN
         icep5  => inputs(imod)%ICEP5
       END IF
       !
       IF ( flmdn  ) THEN
         mudd   => inputs(imod)%MUDD
       END IF
       IF ( flmth  ) THEN
         mudt   => inputs(imod)%MUDT
       END IF
       IF ( flmvs  ) THEN
         mudv   => inputs(imod)%MUDV
       END IF
       !
       IF ( fllev  ) THEN
         wlev   => inputs(imod)%WLEV
       END IF
       !
       IF ( flcur  ) THEN
         cx0    => inputs(imod)%CX0
         cy0    => inputs(imod)%CY0
         cxn    => inputs(imod)%CXN
         cyn    => inputs(imod)%CYN
       END IF
 #ifdef W3_TIDE
       IF ( fllevtide ) THEN
         wltide => inputs(imod)%WLTIDE
       END IF
       IF ( flcurtide ) THEN
         cxtide => inputs(imod)%CXTIDE
         cytide => inputs(imod)%CYTIDE
       END IF
 #endif
       !
 #ifdef W3_WRST
       wxnwrst    => inputs(imod)%WXNwrst
       wynwrst    => inputs(imod)%WYNwrst
 #endif
       IF ( flwind  ) THEN
         wx0    => inputs(imod)%WX0
         wy0    => inputs(imod)%WY0
         dt0    => inputs(imod)%DT0
         wxn    => inputs(imod)%WXN
         wyn    => inputs(imod)%WYN
         dtn    => inputs(imod)%DTN
       END IF
       !
       IF ( flice  ) THEN
         icei   => inputs(imod)%ICEI
         bergi  => inputs(imod)%BERGI
       END IF
       !
       IF ( fltaua  ) THEN
         ux0    => inputs(imod)%UX0
         uy0    => inputs(imod)%UY0
         uxn    => inputs(imod)%UXN
         uyn    => inputs(imod)%UYN
       END IF
       !
       IF ( flrhoa  ) THEN
         rh0    => inputs(imod)%RH0
         rhn    => inputs(imod)%RHN
       END IF
       !
     END IF
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3SETI : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3SETI : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NAUXGR = ',i10/                   &
          '                    NIDATA = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SETI : MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of W3SETI ----------------------------------------------------- /
     !/
References cxtide, cytide, dt0, dtn, w3servmd::extcde(), flagsc, flcur, flcurresi, flcurtide, flic1, flic2, flic3, flic4, flic5, flice, fllev, fllevresi, fllevtide, flmdn, flmth, flmvs, flrhoa, fltaua, flwind, ga0, gan, gd0, gdn, iidata, iinit, inflags1, inflags2, inputs, w3gdatmd::nauxgr, nidata, w3servmd::strace(), t0n, t1n, t2n, tc0, tcn, tdn, tfn, tg0, tgn, ti1, ti2, ti3, ti4, ti5, tin, tln, tr0, trn, ttn, tu0, tun, tvn, tw0, twn, tzn, wltide, wx0, wxn, wy0, and wyn.
Referenced by wmesmfmd::createexpmesh(), w3dimi(), w3initmd::w3init(), w3iorsmd::w3iors(), w3sbs1(), w3shel(), w3uprstr(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupdt().
Variable Documentation
cxtide
real, dimension(:,:,:,:), pointer w3idatmd::cxtide
Definition at line 256 of file w3idatmd.F90.
   REAL, POINTER           :: CXTIDE(:,:,:,:),         &
        CYTIDE(:,:,:,:), WLTIDE(:,:,:,:)
Referenced by w3seti(), and w3updtmd::w3ucur().
cytide
real, dimension(:,:,:,:), pointer w3idatmd::cytide
Definition at line 256 of file w3idatmd.F90.
Referenced by w3seti(), and w3updtmd::w3ucur().
dt0
real, dimension(:,:), pointer w3idatmd::dt0
Definition at line 243 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().
dtn
real, dimension(:,:), pointer w3idatmd::dtn
Definition at line 243 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().
flagsc
logical, dimension(:), pointer w3idatmd::flagsc
Definition at line 260 of file w3idatmd.F90.
Referenced by w3seti(), and w3shel().
flcur
logical, pointer w3idatmd::flcur
Definition at line 261 of file w3idatmd.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3adatmd::w3dima(), w3dimi(), w3initmd::w3init(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3psmcmd::w3psmc(), w3seti(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
flcurresi
logical, pointer w3idatmd::flcurresi
Definition at line 266 of file w3idatmd.F90.
Referenced by w3dimi(), and w3seti().
flcurtide
logical, pointer w3idatmd::flcurtide
Definition at line 266 of file w3idatmd.F90.
Referenced by w3dimi(), w3seti(), and w3updtmd::w3ucur().
flic1
logical, pointer w3idatmd::flic1
Definition at line 264 of file w3idatmd.F90.
   LOGICAL, POINTER        :: FLIC1, FLIC2, FLIC3, FLIC4, FLIC5
Referenced by w3dimi(), w3initmd::w3init(), w3seti(), w3updtmd::w3uic1(), and w3wavemd::w3wave().
flic2
logical, pointer w3idatmd::flic2
Definition at line 264 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
flic3
logical, pointer w3idatmd::flic3
Definition at line 264 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
flic4
logical, pointer w3idatmd::flic4
Definition at line 264 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
flic5
logical, pointer w3idatmd::flic5
Definition at line 264 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
flice
logical, pointer w3idatmd::flice
Definition at line 261 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
fllev
logical, pointer w3idatmd::fllev
Definition at line 261 of file w3idatmd.F90.
   LOGICAL, POINTER        :: FLLEV, FLCUR, FLWIND, FLICE, FLTAUA, &
        FLRHOA
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
fllevresi
logical, pointer w3idatmd::fllevresi
Definition at line 266 of file w3idatmd.F90.
Referenced by w3dimi(), and w3seti().
fllevtide
logical, pointer w3idatmd::fllevtide
Definition at line 266 of file w3idatmd.F90.
   LOGICAL, POINTER        ::  FLLEVTIDE, FLCURTIDE,  &
        FLLEVRESI, FLCURRESI
Referenced by w3dimi(), w3seti(), and w3updtmd::w3ulev().
flmdn
logical, pointer w3idatmd::flmdn
Definition at line 263 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), and w3seti().
flmth
logical, pointer w3idatmd::flmth
Definition at line 263 of file w3idatmd.F90.
   LOGICAL, POINTER        :: FLMTH, FLMVS, FLMDN
Referenced by w3dimi(), w3initmd::w3init(), and w3seti().
flmvs
logical, pointer w3idatmd::flmvs
Definition at line 263 of file w3idatmd.F90.
Referenced by w3dimi(), w3initmd::w3init(), and w3seti().
flrhoa
logical, pointer w3idatmd::flrhoa
Definition at line 261 of file w3idatmd.F90.
Referenced by w3adatmd::w3dima(), w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
fltaua
logical, pointer w3idatmd::fltaua
Definition at line 261 of file w3idatmd.F90.
Referenced by w3adatmd::w3dima(), w3dimi(), w3initmd::w3init(), w3seti(), and w3wavemd::w3wave().
flwind
logical, pointer w3idatmd::flwind
Definition at line 261 of file w3idatmd.F90.
Referenced by w3adatmd::w3dima(), w3dimi(), w3initmd::w3init(), w3sbs1(), w3seti(), and w3wavemd::w3wave().
ga0
real, pointer w3idatmd::ga0
Definition at line 242 of file w3idatmd.F90.
   REAL, POINTER           :: GA0, GD0, GAN, GDN
Referenced by w3seti(), w3wavemd::w3wave(), and wmupdtmd::wmupd1().
gan
real, pointer w3idatmd::gan
Definition at line 242 of file w3idatmd.F90.
Referenced by w3seti(), w3wavemd::w3wave(), and wmupdtmd::wmupd1().
gd0
real, pointer w3idatmd::gd0
Definition at line 242 of file w3idatmd.F90.
Referenced by w3seti(), w3wavemd::w3wave(), and wmupdtmd::wmupd1().
gdn
real, pointer w3idatmd::gdn
Definition at line 242 of file w3idatmd.F90.
Referenced by w3seti(), w3wavemd::w3wave(), and wmupdtmd::wmupd1().
ifdef
real, pointer w3idatmd::ifdef
Definition at line 243 of file w3idatmd.F90.
iidata
integer w3idatmd::iidata = -1
Definition at line 160 of file w3idatmd.F90.
Referenced by w3seti(), and w3wavemd::w3wave().
iinit
logical, pointer w3idatmd::iinit
Definition at line 259 of file w3idatmd.F90.
   LOGICAL, POINTER        :: IINIT
Referenced by w3seti(), wminitmd::wminit(), and wminitmd::wminitnml().
inflags1
logical, dimension(:), pointer w3idatmd::inflags1
Definition at line 260 of file w3idatmd.F90.
   LOGICAL, POINTER        :: INFLAGS1(:), INFLAGS2(:), FLAGSC(:)
Referenced by w3sbt8md::w3sbt8(), w3sbt9md::w3sbt9(), w3seti(), w3shel(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupd1(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
inflags2
logical, dimension(:), pointer w3idatmd::inflags2
Definition at line 260 of file w3idatmd.F90.
Referenced by w3sic3md::ic3table_cheng(), w3seti(), w3shel(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3srcemd::w3srce(), wminitmd::wminit(), and wminitmd::wminitnml().
inputs
type(input), dimension(:), allocatable, target w3idatmd::inputs
Definition at line 232 of file w3idatmd.F90.
   TYPE(INPUT), TARGET, ALLOCATABLE :: INPUTS(:)
Referenced by w3dimi(), w3ninp(), w3adatmd::w3seta(), w3seti(), w3adatmd::w3xeta(), wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupd2().
jfirst
integer w3idatmd::jfirst = 1
Definition at line 162 of file w3idatmd.F90.
   INTEGER                 :: JFIRST = 1
Referenced by w3shel(), wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupdt().
nidata
integer w3idatmd::nidata = -1
Definition at line 160 of file w3idatmd.F90.
   INTEGER                 :: NIDATA = -1, iidata = -1
Referenced by w3dimi(), w3ninp(), and w3seti().
ntide
integer w3idatmd::ntide
Definition at line 165 of file w3idatmd.F90.
   INTEGER                 :: NTIDE   ! number of tidal constituents
Referenced by w3dimi(), w3updtmd::w3ucur(), and w3updtmd::w3ulev().
t0n
integer, dimension(:), pointer w3idatmd::t0n
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
t1n
integer, dimension(:), pointer w3idatmd::t1n
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
t2n
integer, dimension(:), pointer w3idatmd::t2n
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tc0
integer, dimension(:), pointer w3idatmd::tc0
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3ucur(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tcn
integer, dimension(:), pointer w3idatmd::tcn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3ucur(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tdn
integer, dimension(:), pointer w3idatmd::tdn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tfn
integer, dimension(:,:), pointer w3idatmd::tfn
Definition at line 236 of file w3idatmd.F90.
   INTEGER, POINTER        :: TFN(:,:), TLN(:), TC0(:), TCN(:),    &
        TW0(:), TWN(:), TU0(:), TUN(:),      &
        TIN(:), TR0(:), TRN(:), T0N(:),      &
        T1N(:), T2N(:), TDN(:), TG0(:),      &
        TGN(:), TTN(:), TVN(:), TZN(:),      &
        TI1(:), TI2(:), TI3(:), TI4(:), TI5(:)
Referenced by w3seti(), and wmupdtmd::wmupdt().
tg0
integer, dimension(:), pointer w3idatmd::tg0
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tgn
integer, dimension(:), pointer w3idatmd::tgn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
ti1
integer, dimension(:), pointer w3idatmd::ti1
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uic1(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
ti2
integer, dimension(:), pointer w3idatmd::ti2
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
ti3
integer, dimension(:), pointer w3idatmd::ti3
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
ti4
integer, dimension(:), pointer w3idatmd::ti4
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
ti5
integer, dimension(:), pointer w3idatmd::ti5
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uic5(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tidefreq
real, dimension(:), allocatable w3idatmd::tidefreq
Definition at line 166 of file w3idatmd.F90.
   REAL, ALLOCATABLE       :: TIDEFREQ(:)
tin
integer, dimension(:), pointer w3idatmd::tin
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uice(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tln
integer, dimension(:), pointer w3idatmd::tln
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3ulev(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tr0
integer, dimension(:), pointer w3idatmd::tr0
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3urho(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
trn
integer, dimension(:), pointer w3idatmd::trn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3urho(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
ttn
integer, dimension(:), pointer w3idatmd::ttn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tu0
integer, dimension(:), pointer w3idatmd::tu0
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3utau(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tun
integer, dimension(:), pointer w3idatmd::tun
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3utau(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tvn
integer, dimension(:), pointer w3idatmd::tvn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tw0
integer, dimension(:), pointer w3idatmd::tw0
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
twn
integer, dimension(:), pointer w3idatmd::twn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
tzn
integer, dimension(:), pointer w3idatmd::tzn
Definition at line 236 of file w3idatmd.F90.
Referenced by w3seti(), wmupdtmd::wmupd1(), and wmupdtmd::wmupdt().
w3_wrst
real, pointer w3idatmd::w3_wrst
Definition at line 243 of file w3idatmd.F90.
wltide
real, dimension(:,:,:,:), pointer w3idatmd::wltide
Definition at line 256 of file w3idatmd.F90.
Referenced by w3seti(), and w3updtmd::w3ulev().
wx0
real, dimension(:,:), pointer w3idatmd::wx0
Definition at line 243 of file w3idatmd.F90.
   REAL, POINTER           :: WX0(:,:), WY0(:,:), DT0(:,:),        &
        WXN(:,:), WYN(:,:), DTN(:,:),        &
 #ifdef W3_WRST
Referenced by w3seti(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().
wxn
real, dimension(:,:), pointer w3idatmd::wxn
Definition at line 243 of file w3idatmd.F90.
Referenced by w3iorsmd::w3iors(), w3seti(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().
wy0
real, dimension(:,:), pointer w3idatmd::wy0
Definition at line 243 of file w3idatmd.F90.
Referenced by w3seti(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().
wyn
real, dimension(:,:), pointer w3idatmd::wyn
Definition at line 243 of file w3idatmd.F90.
Referenced by w3iorsmd::w3iors(), w3seti(), w3updtmd::w3uwnd(), and wmupdtmd::wmupd1().