WAVEWATCH III: wmmdatmd Module Reference
wmmdatmd Module Reference
Define data structures to set up wave model dynamic data for several models simultaneously.
Data Types
type bpst
type eqst
type hgst
type mdata
Functions/Subroutines
subroutine wmndat (NDSE, NDST)
Set up the number of grids to be used.
subroutine wmdimd (IMOD, NDSE, NDST, J)
Initialize an individual data grid at the proper dimensions.
subroutine wmdimm (IMOD, NDSE, NDST)
Initialize an individual data grid at the proper dimensions.
subroutine wmsetm (IMOD, NDSE, NDST)
Select one of the WAVEWATCH III grids / models.
subroutine init_get_jsea_isproc_glob (ISEA, J, JSEA, ISPROC)
Introduce mapping for ISPROC and JSEA when using PDLIB in the Multigrid approach.
Variables
integer nmdata = -1
NMDATA.
integer imdata = -1
IMDATA.
integer mdsi = 8
MDSI.
integer mdso = 9
MDSO.
integer mdss = 6
MDSS.
integer mdst = 6
MDST.
integer mdse = 6
MDSE.
integer mdsup
MDSUP.
integer mdsupa
MDSUPA.
integer nmproc = 1
NMPROC.
integer improc = 1
IMPROC.
integer nmplog = 1
NMPLOG.
integer nmpscr = 1
NMPSCR.
integer nmptst = 1
NMPTST.
integer nmperr = 1
NMPERR.
integer nmpupt = 1
NMPUPT.
integer, dimension(2) stime
STIME.
integer, dimension(2) etime
ETIME.
integer nrgrd
NRGRD.
integer nrinp
NRINP.
integer nrgrp
NRGRP.
integer nmvmax
NMVMAX.
integer ngrpsmc
NGRPSMC.
integer, dimension(8) clkdt1
CLKDT1.
integer, dimension(8) clkdt2
CLKDT2.
integer, dimension(8) clkdt3
CLKDT3.
integer mdsp
MDSP.
integer mpi_comm_mwave
MPI_COMM_MWAVE.
integer, parameter mtagb = 0
MTAGB.
integer, parameter mtag0 = 1000
MTAG0.
integer, parameter mtag1 = 40000
MTAG1.
integer, parameter mtag2 = 1000000
MTAG2.
integer, parameter mtag_ub = 2**21-1
MPI_TAG_UB on Cray XC40.
integer, dimension(:,:), allocatable mdsf
MDSF.
integer, dimension(:), allocatable grank
GRANK.
integer, dimension(:), allocatable grgrp
GRGRP.
integer, dimension(:,:), allocatable ingrp
INGRP.
integer, dimension(:,:), allocatable grdhgh
GRDHGH.
integer, dimension(:,:), allocatable grdeql
GRDEQL.
integer, dimension(:,:), allocatable grdlow
GRDLOW.
integer, dimension(:,:), allocatable allprc
ALLPRC.
integer, dimension(:,:), allocatable modmap
MODMAP.
integer, dimension(:,:), allocatable tsync
TSYNC.
integer, dimension(:,:), allocatable tmax
TMAX.
integer, dimension(:,:), allocatable toutp
TOUTP.
integer, dimension(:,:), allocatable tdata
TDATA.
integer, dimension(:), allocatable grstat
GRSTAT.
integer, dimension(:,:), allocatable nbi2g
NBI2G.
integer, dimension(:,:), allocatable inpmap
INPMAP.
integer, dimension(:), allocatable nbista
NBISTA.
integer, dimension(:), allocatable hghsta
HGHSTA.
integer, dimension(:), allocatable eqlsta
EQLSTA.
real clkfin
CLKFIN.
real, dimension(:), allocatable dtres
DTRES.
logical flgbdi =.FALSE.
FLGBDI.
logical flghg1
FLGHG1.
logical flghg2
FLGHG2.
logical, dimension(:,:), allocatable respec
RESPEC.
logical, dimension(:), allocatable bcdump
BCDUMP.
logical, dimension(:), allocatable iflsti
IFLSTI.
logical, dimension(:), allocatable iflstl
IFLSTL.
logical, dimension(:), allocatable iflstr
IFLSTR.
character(len=3), dimension(:,:), allocatable idinp
IDINP.
type(mdata), dimension(:), allocatable, target mdatas
MDATAS.
type(bpst), dimension(:,:), allocatable, target bpstge
BPSTGE.
type(hgst), dimension(:,:), allocatable, target hgstge
HGSTGE.
type(eqst), dimension(:,:), allocatable, target eqstge
EQSTGE.
integer, dimension(:), pointer rcld
RCLD.
integer, dimension(:), pointer ndt
NDT.
integer, pointer nmv
NMV.
integer, dimension(:,:,:), pointer tmv
TMV.
integer, dimension(:,:), pointer nbi2s
NBI2S.
integer, dimension(:,:), pointer mapmsk
MAPMSK.
integer, dimension(:), pointer uptmap
UPTMAP.
integer, pointer mpi_comm_grd
MPI_COMM_GRD.
integer, pointer mpi_comm_bct
MPI_COMM_BCT.
integer, pointer croot
CROOT.
real, dimension(:,:), pointer data0
DATA0.
real, dimension(:,:), pointer data1
DATA1.
real, dimension(:,:), pointer data2
DATA2.
real, dimension(:,:), pointer amv
AMV.
real, dimension(:,:), pointer dmv
DMV.
real, dimension(:,:), pointer mapbdi
MAPBDI.
real, dimension(:,:), pointer mapodi
MAPODI.
integer, dimension(:), pointer sea_ipgl
SEA_IPGL.
integer, dimension(:), pointer sea_ipgl_to_proc
SEA_IPGL_TO_PROC.
logical, pointer minit
MINIT.
logical, pointer fllstl
FLLSTL.
logical, pointer fllstr
FLLSTR.
logical, pointer fllsti
FLLSTI.
logical, pointer fldat0
FLDAT0.
logical, pointer fldat1
FLDAT1.
logical, pointer fldat2
FLDAT2.
logical, pointer fbcast
FBCAST.
Detailed Description
Define data structures to set up wave model dynamic data for several models simultaneously.
Author
H. L. Tolman
Date
22-Mar-2021
Function/Subroutine Documentation
init_get_jsea_isproc_glob()
subroutine wmmdatmd::init_get_jsea_isproc_glob (integer, intent(in) ISEA, integer, intent(in) J, integer, intent(out) JSEA, integer, intent(out) ISPROC)
Introduce mapping for ISPROC and JSEA when using PDLIB in the Multigrid approach.
Parameters
[in] ISEA
[in] J
[out] JSEA
[out] ISPROC
Author
Aron Roland
Date
14-Jun-2018
Definition at line 1333 of file wmmdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           Aron Roland             |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         14-Jun-2018 |
     !/                  +-----------------------------------+
     !/
     !/    06-Jun-2018 : Origination.                        ( version 6.04 )
     !/
     !  1. Purpose : Introduce mapping for ISPROC and JSEA when using PDLIB
     !               in the Multigrid approach
     !
     !  2. Method :
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !  7. Remarks
     !  8. Structure :
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     USE constants, ONLY: lpdlib
     USE w3odatmd, ONLY: outpts
     USE w3gdatmd, ONLY: gtype, grids, ungtype
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     integer, intent(in) :: ISEA, J
     integer, intent(out) :: JSEA, ISPROC
     integer nb
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'INIT_GET_JSEA_ISPROC_GLOB')
 #endif
     IF (.NOT. lpdlib) THEN
       nb=outpts(j)%NAPROC
       jsea   = 1 + (isea-1)/nb
       isproc=1
 #ifdef W3_DIST
       isproc = mdatas(j)%CROOT - 1 + isea - (jsea-1)*nb
 #endif
     ELSE
 #ifdef W3_PDLIB
       IF (grids(j)%GTYPE .ne. ungtype) THEN
         nb=outpts(j)%NAPROC
         jsea   = 1 + (isea-1)/nb
         isproc = mdatas(j)%CROOT - 1 + isea - (jsea-1)*nb
       ELSE
         jsea   = mdatas(j)%SEA_IPGL(isea)
         isproc = mdatas(j)%SEA_IPGL_TO_PROC(isea)
       ENDIF
 #endif
     ENDIF
     !/
     !/ End of INIT_GET_JSEA_ISPROC_GLOB  ---------------------------------- /
     !/
References w3gdatmd::grids, w3gdatmd::gtype, constants::lpdlib, mdatas, w3odatmd::outpts, w3servmd::strace(), and w3gdatmd::ungtype.
Referenced by wmgridmd::wmgeql(), wmgridmd::wmghgh(), and wminiomd::wmiobg().
wmdimd()
subroutine wmmdatmd::wmdimd (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, integer, intent(in) J)
Initialize an individual data grid at the proper dimensions.
Allocate directly into the structure array. Note that this cannot be done through the pointer alias!
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
[in] J Data set [1,2,3].
Author
H. L. Tolman
Date
10-Dec-2014
Definition at line 787 of file wmmdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    22-Feb-2005 : Origination.                        ( version 3.07 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       J       Int.   I   Data set [1,2,3].
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - WMSETM needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, igrid, w3setg
     USE w3odatmd, ONLY: naproc
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST, J
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMDIMD')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nmdata ) THEN
       WRITE (ndse,1002) imod, nmdata
       CALL extcde (2)
     END IF
     !
     IF ( mdatas(imod)%MINIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     IF ( j .EQ. 0 ) THEN
       ALLOCATE ( mdatas(imod)%TMV(2,-7:4,nmv) ,            &
            mdatas(imod)%AMV(nmv,-7:4)   ,            &
            mdatas(imod)%DMV(nmv,-7:4)   , stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( j .EQ. 1 ) THEN
       IF ( fldat0 ) DEALLOCATE ( mdatas(imod)%DATA0 )
       ALLOCATE ( mdatas(imod)%DATA0(rcld(j),ndt(j)), stat=istat )
       check_alloc_status( istat )
       fldat0 = .true.
     END IF
     !
     IF ( j .EQ. 2 ) THEN
       IF ( fldat1 ) DEALLOCATE ( mdatas(imod)%DATA1 )
       ALLOCATE ( mdatas(imod)%DATA1(rcld(j),ndt(j)), stat=istat )
       check_alloc_status( istat )
       fldat1 = .true.
     END IF
     !
     IF ( j .EQ. 3 ) THEN
       IF ( fldat2 ) DEALLOCATE ( mdatas(imod)%DATA2 )
       ALLOCATE ( mdatas(imod)%DATA2(rcld(j),ndt(j)), stat=istat )
       check_alloc_status( istat )
       fldat2 = .true.
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL wmsetm ( imod, ndse, ndst )
     !
     IF ( j .EQ. 0 ) THEN
       tmv    = 0
       amv    = 0.
       dmv    = 0.
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR WMDIMD : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR WMDIMD : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NMDATA = ',i10/)
 1003 FORMAT (/' *** ERROR WMDIMD : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST WMDIMD : MODEL ',i4,' DIM. AT ',2i5,i7)
 9001 FORMAT (' TEST WMDIMD : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST WMDIMD : POINTERS RESET')
 #endif
     !/
     !/ End of WMDIMD ----------------------------------------------------- /
     !/
References amv, dmv, w3servmd::extcde(), fldat0, fldat1, fldat2, w3gdatmd::igrid, mdatas, w3odatmd::naproc, ndt, w3gdatmd::ngrids, nmdata, nmv, rcld, w3servmd::strace(), tmv, w3gdatmd::w3setg(), and wmsetm().
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupd1().
wmdimm()
subroutine wmmdatmd::wmdimm (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Initialize an individual data grid at the proper dimensions.
Allocate directly into the structure array. Note that this cannot be done through the pointer alias!
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Feb-2005
Definition at line 990 of file wmmdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Feb-2005 !
     !/                  +-----------------------------------+
     !/
     !/    22-Feb-2005 : Origination.                        ( version 3.07 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - WMSETM needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, igrid, w3setg
     USE w3odatmd, ONLY: naproc
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMDIMM')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nmdata ) THEN
       WRITE (ndse,1002) imod, nmdata
       CALL extcde (2)
     END IF
     !
     IF ( mdatas(imod)%MINIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     !     ALLOCATE ( MDATAS(IMOD)%...
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL wmsetm ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update flag
     !
     minit  = .true.
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR WMDIMM : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR WMDIMM : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NMDATA = ',i10/)
 1003 FORMAT (/' *** ERROR WMDIMM : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST WMDIMM : MODEL ',i4,' DIM. AT ',2i5,i7)
 9001 FORMAT (' TEST WMDIMM : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST WMDIMM : POINTERS RESET')
 9003 FORMAT (' TEST WMDIMM : FLAGS SET')
 #endif
     !/
     !/ End of WMDIMM ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3gdatmd::igrid, mdatas, minit, w3odatmd::naproc, w3gdatmd::ngrids, nmdata, w3servmd::strace(), w3gdatmd::w3setg(), and wmsetm().
wmndat()
subroutine wmmdatmd::wmndat (integer, intent(in) NDSE, integer, intent(in) NDST)
Set up the number of grids to be used.
Use data stored in NGRIDS in W3GDATMD.
Parameters
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 584 of file wmmdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    22-Feb-2005 : Origination.                        ( version 3.07 )
     !/    16-Dec-2005 : Add staging of boundary data.       ( version 3.08 )
     !/                  Add HGSTGE data.                    ( version 3.08 )
     !/    24-Mar-2006 : Add EQSTGE data.                    ( version 3.09 )
     !/    25-May-2006 : Add STIME in BPSTGE.                ( version 3.09 )
     !/    12-Jan-2007 : Add FLSTI and FLLSTL.               ( version 3.10 )
     !/    22-Jan-2007 : Add NAVMAX.                         ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    22-Mar-2021 : Support for air density input       ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Set up the number of grids to be used.
     !
     !  2. Method :
     !
     !     Use data stored in NGRIDS in W3GDATMD.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Error checks on previous setting of variable NGRIDS.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: I, J
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMNDAT')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001) ngrids
       CALL extcde (1)
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set variable and allocate arrays
     !
     ALLOCATE ( mdatas(ngrids), bpstge(ngrids,ngrids),               &
          hgstge(ngrids,ngrids), eqstge(ngrids,ngrids),        &
          bcdump(nrgrd), iflsti(nrinp), iflstl(nrinp),         &
          iflstr(nrinp), stat=istat )
     check_alloc_status( istat )
 #ifdef W3_MPI
     ALLOCATE ( nbista(ngrids), hghsta(ngrids), eqlsta(ngrids), &
          stat=istat )
     check_alloc_status( istat )
 #endif
     nmdata = ngrids
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Initialize parameters
     !
 #ifdef W3_MPI
     nbista = 0
     hghsta = 0
     eqlsta = 0
 #endif
     !
     iflsti = .false.
     iflstl = .false.
     iflstr = .false.
     !
     DO i=1, ngrids
       mdatas(i)%MINIT  = .false.
       mdatas(i)%MSKINI = .false.
       mdatas(i)%FLDAT0 = .false.
       mdatas(i)%FLDAT1 = .false.
       mdatas(i)%FLDAT2 = .false.
 #ifdef W3_MPI
       mdatas(i)%MPI_COMM_GRD = -99
       mdatas(i)%MPI_COMM_BCT = -99
 #endif
       DO j=1, ngrids
         bpstge(i,j)%VTIME(1) = -1
         bpstge(i,j)%VTIME(2) =  0
 #ifdef W3_MPI
         bpstge(i,j)%STIME(1) = -1
         bpstge(i,j)%STIME(2) =  0
 #endif
         bpstge(i,j)%INIT     = .false.
 #ifdef W3_MPI
         bpstge(i,j)%NRQBPS   = 0
 #endif
         hgstge(i,j)%VTIME(1) = -1
         hgstge(i,j)%VTIME(2) =  0
         hgstge(i,j)%XTIME(1) = -1
         hgstge(i,j)%XTIME(2) =  0
         hgstge(i,j)%NTOT     =  0
         hgstge(i,j)%NREC     =  0
         hgstge(i,j)%NRC1     =  0
         hgstge(i,j)%NSND     =  0
         hgstge(i,j)%NSN1     =  0
         hgstge(i,j)%NSMX     =  0
 #ifdef W3_MPI
         hgstge(i,j)%NRQHGS   =  0
         hgstge(i,j)%NRQOUT   =  0
 #endif
         hgstge(i,j)%INIT     = .false.
         eqstge(i,j)%VTIME(1) = -1
         eqstge(i,j)%VTIME(2) =  0
         eqstge(i,j)%NTOT     =  0
         eqstge(i,j)%NREC     =  0
         eqstge(i,j)%NSND     =  0
         eqstge(i,j)%NAVMAX   =  1
 #ifdef W3_MPI
         eqstge(i,j)%NRQEQS   =  0
         eqstge(i,j)%NRQOUT   =  0
 #endif
         eqstge(i,j)%INIT     = .false.
       END DO
     END DO
     !
 #ifdef W3_T
     WRITE (ndst,9000) ngrids
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR WMNDAT : NGRIDS NOT YET SET *** '/         &
          '                    NGRIDS = ',i10/                   &
          '                    RUN W3NMOD FIRST'/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST WMNDAT : SETTING UP FOR ',i4,' GRIDS')
 #endif
     !/
     !/ End of WMNDAT ----------------------------------------------------- /
     !/
References bcdump, bpstge, eqlsta, eqstge, w3servmd::extcde(), hghsta, hgstge, iflsti, iflstl, iflstr, mdatas, nbista, w3gdatmd::ngrids, nmdata, nrgrd, nrinp, and w3servmd::strace().
Referenced by wminitmd::wminit(), and wminitmd::wminitnml().
wmsetm()
subroutine wmmdatmd::wmsetm (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Select one of the WAVEWATCH III grids / models.
Point pointers to the proper variables in the proper element of the GRIDS array.
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 1169 of file wmmdatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    13-Jun-2005 : Origination.                       ( version 3.07 )
     !/    22-Mar-2021 : Support for air density input      ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Select one of the WAVEWATCH III grids / models.
     !
     !  2. Method :
     !
     !     Point pointers to the proper variables in the proper element of
     !     the GRIDS array.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Many subroutines in the WAVEWATCH system.
     !
     !  6. Error messages :
     !
     !     Checks on parameter list IMOD.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMSETM')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( nmdata .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nmdata ) THEN
       WRITE (ndse,1002) imod, nmdata
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model numbers
     !
     imdata = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers
     !
     !
     nmv    => mdatas(imod)%NMV
     tmv    => mdatas(imod)%TMV
     amv    => mdatas(imod)%AMV
     dmv    => mdatas(imod)%DMV
 #ifdef W3_MPI
     mpi_comm_grd => mdatas(imod)%MPI_COMM_GRD
     mpi_comm_bct => mdatas(imod)%MPI_COMM_BCT
     croot  => mdatas(imod)%CROOT
     fbcast => mdatas(imod)%FBCAST
 #endif
     rcld   => mdatas(imod)%RCLD
     ndt    => mdatas(imod)%NDT
     data0  => mdatas(imod)%DATA0
     data1  => mdatas(imod)%DATA1
     data2  => mdatas(imod)%DATA2
     nbi2s  => mdatas(imod)%NBI2S
     mapmsk => mdatas(imod)%MAPMSK
     minit  => mdatas(imod)%MINIT
     fllstl => mdatas(imod)%FLLSTL
     fllsti => mdatas(imod)%FLLSTI
     fllstr => mdatas(imod)%FLLSTR
     mapbdi => mdatas(imod)%MAPBDI
     mapodi => mdatas(imod)%MAPODI
 #ifdef W3_PDLIB
     sea_ipgl => mdatas(imod)%SEA_IPGL
     sea_ipgl_to_proc => mdatas(imod)%SEA_IPGL_TO_PROC
 #endif
     uptmap => mdatas(imod)%UPTMAP
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR WMSETM : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR WMSETM : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                   &
          '                    NMDATA = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST WMSETM : MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of WMSETM ----------------------------------------------------- /
     !/
References amv, croot, data0, data1, data2, dmv, w3servmd::extcde(), fbcast, fllsti, fllstl, fllstr, imdata, mapbdi, mapmsk, mapodi, mdatas, minit, mpi_comm_bct, mpi_comm_grd, nbi2s, ndt, nmdata, nmv, rcld, sea_ipgl, sea_ipgl_to_proc, w3servmd::strace(), tmv, and uptmap.
Referenced by wmesmfmd::createexpmesh(), wmdimd(), wmdimm(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
Variable Documentation
allprc
integer, dimension(:,:), allocatable wmmdatmd::allprc
ALLPRC.
Definition at line 360 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: ALLPRC(:,:)
Referenced by wmwavemd::wmbcst(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobs(), and wmiopomd::wmiopo().
amv
real, dimension(:,:), pointer wmmdatmd::amv
AMV.
Definition at line 550 of file wmmdatmd.F90.
   REAL, POINTER              :: AMV(:,:)
Referenced by wmdimd(), wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), wmupdtmd::wmupd1(), and wmwavemd::wmwave().
bcdump
logical, dimension(:), allocatable wmmdatmd::bcdump
BCDUMP.
Definition at line 382 of file wmmdatmd.F90.
   LOGICAL, ALLOCATABLE    :: BCDUMP(:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), and wmndat().
bpstge
type(bpst), dimension(:,:), allocatable, target wmmdatmd::bpstge
BPSTGE.
Definition at line 529 of file wmmdatmd.F90.
   TYPE(BPST),  TARGET, ALLOCATABLE  :: BPSTGE(:,:)
Referenced by wminiomd::wmiobf(), wminiomd::wmiobg(), wminiomd::wmiobs(), and wmndat().
clkdt1
integer, dimension(8) wmmdatmd::clkdt1
CLKDT1.
Definition at line 336 of file wmmdatmd.F90.
   INTEGER                 :: CLKDT1(8)
Referenced by wmfinlmd::wmfinl(), wminitmd::wminit(), and wminitmd::wminitnml().
clkdt2
integer, dimension(8) wmmdatmd::clkdt2
CLKDT2.
Definition at line 337 of file wmmdatmd.F90.
   INTEGER                 :: CLKDT2(8)
Referenced by wmfinlmd::wmfinl(), wminitmd::wminit(), and wminitmd::wminitnml().
clkdt3
integer, dimension(8) wmmdatmd::clkdt3
CLKDT3.
Definition at line 338 of file wmmdatmd.F90.
   INTEGER                 :: CLKDT3(8)
Referenced by wmfinlmd::wmfinl().
clkfin
real wmmdatmd::clkfin
CLKFIN.
Definition at line 376 of file wmmdatmd.F90.
   REAL                    :: CLKFIN
Referenced by wmfinlmd::wmfinl(), wminitmd::wminit(), and wminitmd::wminitnml().
croot
integer, pointer wmmdatmd::croot
CROOT.
Definition at line 545 of file wmmdatmd.F90.
   INTEGER, POINTER           :: CROOT
Referenced by wmwavemd::wmbcst(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), and wmwavemd::wmwave().
data0
real, dimension(:,:), pointer wmmdatmd::data0
DATA0.
Definition at line 547 of file wmmdatmd.F90.
   REAL, POINTER              :: DATA0(:,:)
Referenced by wmsetm(), and wmupdtmd::wmupd1().
data1
real, dimension(:,:), pointer wmmdatmd::data1
DATA1.
Definition at line 548 of file wmmdatmd.F90.
   REAL, POINTER              :: DATA1(:,:)
Referenced by wmsetm(), and wmupdtmd::wmupd1().
data2
real, dimension(:,:), pointer wmmdatmd::data2
DATA2.
Definition at line 549 of file wmmdatmd.F90.
   REAL, POINTER              :: DATA2(:,:)
Referenced by wmsetm(), and wmupdtmd::wmupd1().
dmv
real, dimension(:,:), pointer wmmdatmd::dmv
DMV.
Definition at line 551 of file wmmdatmd.F90.
   REAL, POINTER              :: DMV(:,:)
Referenced by wmdimd(), wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), wmupdtmd::wmupd1(), and wmwavemd::wmwave().
dtres
real, dimension(:), allocatable wmmdatmd::dtres
DTRES.
Definition at line 377 of file wmmdatmd.F90.
   REAL,    ALLOCATABLE    :: DTRES(:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
eqlsta
integer, dimension(:), allocatable wmmdatmd::eqlsta
EQLSTA.
Definition at line 373 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: EQLSTA(:)
Referenced by wminiomd::wmioeg(), and wmndat().
eqstge
type(eqst), dimension(:,:), allocatable, target wmmdatmd::eqstge
EQSTGE.
Definition at line 531 of file wmmdatmd.F90.
   TYPE(EQST),  TARGET, ALLOCATABLE  :: EQSTGE(:,:)
Referenced by wmgridmd::wmgeql(), wminiomd::wmioef(), wminiomd::wmioeg(), wminiomd::wmioes(), wmndat(), and wmgridmd::wmsmceql().
etime
integer, dimension(2) wmmdatmd::etime
ETIME.
Definition at line 329 of file wmmdatmd.F90.
   INTEGER                 :: ETIME(2)
Referenced by wmesmfmd::setservices(), w3mlti(), w3sbs1(), wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupd1(), wmupdtmd::wmupd2(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
fbcast
logical, pointer wmmdatmd::fbcast
FBCAST.
Definition at line 568 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FBCAST
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), and wmwavemd::wmwave().
fldat0
logical, pointer wmmdatmd::fldat0
FLDAT0.
Definition at line 563 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FLDAT0
Referenced by wmdimd().
fldat1
logical, pointer wmmdatmd::fldat1
FLDAT1.
Definition at line 564 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FLDAT1
Referenced by wmdimd().
fldat2
logical, pointer wmmdatmd::fldat2
FLDAT2.
Definition at line 565 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FLDAT2
Referenced by wmdimd().
flgbdi
logical wmmdatmd::flgbdi =.FALSE.
FLGBDI.
Definition at line 378 of file wmmdatmd.F90.
   LOGICAL                 :: FLGBDI=.false.
Referenced by wmgridmd::wmghgh().
flghg1
logical wmmdatmd::flghg1
FLGHG1.
Definition at line 379 of file wmmdatmd.F90.
   LOGICAL                 :: FLGHG1
Referenced by wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiohg(), wminiomd::wmiohs(), and wmwavemd::wmwave().
flghg2
logical wmmdatmd::flghg2
FLGHG2.
Definition at line 380 of file wmmdatmd.F90.
   LOGICAL                 :: FLGHG2
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiohg(), wminiomd::wmiohs(), and wmwavemd::wmwave().
fllsti
logical, pointer wmmdatmd::fllsti
FLLSTI.
Definition at line 562 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FLLSTI
Referenced by wmsetm(), wmupdtmd::wmupd1(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
fllstl
logical, pointer wmmdatmd::fllstl
FLLSTL.
Definition at line 560 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FLLSTL
Referenced by wmsetm(), wmupdtmd::wmupd1(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
fllstr
logical, pointer wmmdatmd::fllstr
FLLSTR.
Definition at line 561 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: FLLSTR
Referenced by wmsetm(), wmupdtmd::wmupd1(), wmupdtmd::wmupdt(), and wmwavemd::wmwave().
grank
integer, dimension(:), allocatable wmmdatmd::grank
GRANK.
Definition at line 353 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: GRANK(:)
Referenced by wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wmgridmd::wmsmceql(), and wmwavemd::wmwave().
grdeql
integer, dimension(:,:), allocatable wmmdatmd::grdeql
GRDEQL.
Definition at line 357 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: GRDEQL(:,:)
Referenced by wmgridmd::wmgeql(), wminitmd::wminit(), wminitmd::wminitnml(), wmgridmd::wmsmceql(), and wmwavemd::wmwave().
grdhgh
integer, dimension(:,:), allocatable wmmdatmd::grdhgh
GRDHGH.
Definition at line 356 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: GRDHGH(:,:)
Referenced by wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
grdlow
integer, dimension(:,:), allocatable wmmdatmd::grdlow
GRDLOW.
Definition at line 359 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: GRDLOW(:,:)
Referenced by wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
grgrp
integer, dimension(:), allocatable wmmdatmd::grgrp
GRGRP.
Definition at line 354 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: GRGRP(:)
Referenced by wmgridmd::wmgeql(), wminitmd::wminit(), wminitmd::wminitnml(), and wmgridmd::wmsmceql().
grstat
integer, dimension(:), allocatable wmmdatmd::grstat
GRSTAT.
Definition at line 366 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: GRSTAT(:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
hghsta
integer, dimension(:), allocatable wmmdatmd::hghsta
HGHSTA.
Definition at line 372 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: HGHSTA(:)
Referenced by wminiomd::wmiohg(), and wmndat().
hgstge
type(hgst), dimension(:,:), allocatable, target wmmdatmd::hgstge
HGSTGE.
Definition at line 530 of file wmmdatmd.F90.
   TYPE(HGST),  TARGET, ALLOCATABLE  :: HGSTGE(:,:)
Referenced by wmgridmd::wmghgh(), wminiomd::wmiohf(), wminiomd::wmiohg(), wminiomd::wmiohs(), and wmndat().
idinp
character(len=3), dimension(:,:), allocatable wmmdatmd::idinp
IDINP.
Definition at line 386 of file wmmdatmd.F90.
   CHARACTER(LEN=3), ALLOCATABLE :: IDINP(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupd2(), and wmupdtmd::wmupdt().
iflsti
logical, dimension(:), allocatable wmmdatmd::iflsti
IFLSTI.
Definition at line 383 of file wmmdatmd.F90.
   LOGICAL, ALLOCATABLE    :: IFLSTI(:)
Referenced by wmndat(), and wmupdtmd::wmupdt().
iflstl
logical, dimension(:), allocatable wmmdatmd::iflstl
IFLSTL.
Definition at line 384 of file wmmdatmd.F90.
   LOGICAL, ALLOCATABLE    :: IFLSTL(:)
Referenced by wmndat(), and wmupdtmd::wmupdt().
iflstr
logical, dimension(:), allocatable wmmdatmd::iflstr
IFLSTR.
Definition at line 385 of file wmmdatmd.F90.
   LOGICAL, ALLOCATABLE    :: IFLSTR(:)
Referenced by wmndat(), and wmupdtmd::wmupdt().
imdata
integer wmmdatmd::imdata = -1
IMDATA.
Definition at line 311 of file wmmdatmd.F90.
   INTEGER                 :: IMDATA = -1
Referenced by wmsetm().
improc
integer wmmdatmd::improc = 1
IMPROC.
Definition at line 322 of file wmmdatmd.F90.
   INTEGER                 :: IMPROC = 1
Referenced by w3snl4md::insnl4(), rdtime(), wmesmfmd::setservices(), w3mlti(), w3nmlmultimd::w3nmlmulticonf(), w3nmlmultimd::w3nmlmultidef(), w3nmlshelmd::w3nmlshel(), w3sbs1(), wmwavemd::wmbcst(), wmfinlmd::wmfinl(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmupdtmd::wmupd1(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), and wmwavemd::wmwave().
ingrp
integer, dimension(:,:), allocatable wmmdatmd::ingrp
INGRP.
Definition at line 355 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: INGRP(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
inpmap
integer, dimension(:,:), allocatable wmmdatmd::inpmap
INPMAP.
Definition at line 368 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: INPMAP(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupdt().
mapbdi
real, dimension(:,:), pointer wmmdatmd::mapbdi
MAPBDI.
Definition at line 553 of file wmmdatmd.F90.
   REAL, POINTER              :: MAPBDI(:,:)
Referenced by wmgridmd::wmghgh(), and wmsetm().
mapmsk
integer, dimension(:,:), pointer wmmdatmd::mapmsk
MAPMSK.
Definition at line 540 of file wmmdatmd.F90.
   INTEGER, POINTER           :: MAPMSK(:,:)
Referenced by wmgridmd::wmghgh(), wmsetm(), and wmwavemd::wmwave().
mapodi
real, dimension(:,:), pointer wmmdatmd::mapodi
MAPODI.
Definition at line 554 of file wmmdatmd.F90.
   REAL, POINTER              :: MAPODI(:,:)
Referenced by wmgridmd::wmgeql(), and wmsetm().
mdatas
type(mdata), dimension(:), allocatable, target wmmdatmd::mdatas
MDATAS.
Definition at line 528 of file wmmdatmd.F90.
   TYPE(MDATA), TARGET, ALLOCATABLE  :: MDATAS(:)
Referenced by init_get_jsea_isproc_glob(), w3parall::synchronize_ipgl_etc_array(), wmdimd(), wmdimm(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminiomd::wmiobg(), wminiomd::wmioeg(), wminiomd::wmiohg(), wmiopomd::wmiopp(), wmndat(), wmsetm(), and wmgridmd::wmsmceql().
mdse
integer wmmdatmd::mdse = 6
MDSE.
Definition at line 316 of file wmmdatmd.F90.
   INTEGER                 :: MDSE = 6
Referenced by wmesmfmd::createexpmesh(), w3nmlshelmd::read_domain_nml(), w3nmlmultimd::read_domain_nml(), w3nmlshelmd::read_homogeneous_nml(), w3nmlmultimd::read_homogeneous_nml(), w3nmlmultimd::read_input_grid_nml(), w3nmlshelmd::read_input_nml(), w3nmlmultimd::read_model_grid_nml(), w3nmlshelmd::read_output_date_nml(), w3nmlmultimd::read_output_date_nml(), w3nmlshelmd::read_output_type_nml(), w3nmlmultimd::read_output_type_nml(), w3mlti(), w3nmlmultimd::w3nmlmulticonf(), w3nmlmultimd::w3nmlmultidef(), w3nmlshelmd::w3nmlshel(), w3sbs1(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmupdtmd::wmupd1(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), wmwavemd::wmwave(), and wmwavemd::wmwout().
mdsf
integer, dimension(:,:), allocatable wmmdatmd::mdsf
MDSF.
Definition at line 352 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: MDSF(:,:)
Referenced by w3sbs1(), wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupd1().
mdsi
integer wmmdatmd::mdsi = 8
MDSI.
Definition at line 312 of file wmmdatmd.F90.
   INTEGER                 :: MDSI = 8
Referenced by w3mlti(), wminitmd::wminit(), and wminitmd::wminitnml().
mdso
integer wmmdatmd::mdso = 9
MDSO.
Definition at line 313 of file wmmdatmd.F90.
   INTEGER                 :: MDSO = 9
Referenced by w3mlti(), wmfinlmd::wmfinl(), wminitmd::wminit(), wminitmd::wminitnml(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), and wmwavemd::wmwave().
mdsp
integer wmmdatmd::mdsp
MDSP.
Definition at line 341 of file wmmdatmd.F90.
   INTEGER                 :: MDSP
Referenced by wmfinlmd::wmfinl(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
mdss
integer wmmdatmd::mdss = 6
MDSS.
Definition at line 314 of file wmmdatmd.F90.
   INTEGER                 :: MDSS = 6
Referenced by rdtime(), w3mlti(), w3sbs1(), wmfinlmd::wmfinl(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), and wmwavemd::wmwave().
mdst
integer wmmdatmd::mdst = 6
MDST.
Definition at line 315 of file wmmdatmd.F90.
   INTEGER                 :: MDST = 6
Referenced by wmesmfmd::createexpmesh(), w3mlti(), w3sbs1(), wmwavemd::wmbcst(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobf(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioef(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohf(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmrspc(), wmgridmd::wmsmceql(), wmupdtmd::wmupd1(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), wmwavemd::wmwave(), and wmwavemd::wmwout().
mdsup
integer wmmdatmd::mdsup
MDSUP.
Definition at line 317 of file wmmdatmd.F90.
   INTEGER                 :: MDSUP
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmiopomd::wmiopo().
mdsupa
integer wmmdatmd::mdsupa
MDSUPA.
Definition at line 319 of file wmmdatmd.F90.
   INTEGER                 :: MDSUPA
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmiopomd::wmiopo().
minit
logical, pointer wmmdatmd::minit
MINIT.
Definition at line 559 of file wmmdatmd.F90.
   LOGICAL, POINTER           :: MINIT
Referenced by wmdimm(), and wmsetm().
modmap
integer, dimension(:,:), allocatable wmmdatmd::modmap
MODMAP.
Definition at line 361 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: MODMAP(:,:)
Referenced by wminitmd::wminit(), and wminitmd::wminitnml().
mpi_comm_bct
integer, pointer wmmdatmd::mpi_comm_bct
MPI_COMM_BCT.
Definition at line 544 of file wmmdatmd.F90.
   INTEGER, POINTER           :: MPI_COMM_BCT
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), and wmwavemd::wmwave().
mpi_comm_grd
integer, pointer wmmdatmd::mpi_comm_grd
MPI_COMM_GRD.
Definition at line 543 of file wmmdatmd.F90.
   INTEGER, POINTER           :: MPI_COMM_GRD
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmsetm(), and wmwavemd::wmwave().
mpi_comm_mwave
integer wmmdatmd::mpi_comm_mwave
MPI_COMM_MWAVE.
Definition at line 344 of file wmmdatmd.F90.
   INTEGER                 :: MPI_COMM_MWAVE
Referenced by w3nmlmultimd::w3nmlmulticonf(), w3nmlmultimd::w3nmlmultidef(), w3nmlshelmd::w3nmlshel(), wmwavemd::wmbcst(), wmfinlmd::wmfinl(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), and wmwavemd::wmwave().
mtag0
integer, parameter wmmdatmd::mtag0 = 1000
MTAG0.
Definition at line 346 of file wmmdatmd.F90.
   INTEGER, PARAMETER      :: MTAG0 = 1000
Referenced by wminiomd::wmiobg(), wminiomd::wmiobs(), and wmiopomd::wmiopo().
mtag1
integer, parameter wmmdatmd::mtag1 = 40000
MTAG1.
Definition at line 347 of file wmmdatmd.F90.
   INTEGER, PARAMETER      :: MTAG1 = 40000
Referenced by wminiomd::wmiobs(), wminiomd::wmiohg(), and wminiomd::wmiohs().
mtag2
integer, parameter wmmdatmd::mtag2 = 1000000
MTAG2.
Definition at line 348 of file wmmdatmd.F90.
   INTEGER, PARAMETER      :: MTAG2 = 1000000
Referenced by wminiomd::wmioeg(), wminiomd::wmioes(), and wminiomd::wmiohs().
mtag_ub
integer, parameter wmmdatmd::mtag_ub = 2**21-1
MPI_TAG_UB on Cray XC40.
Definition at line 349 of file wmmdatmd.F90.
   INTEGER, PARAMETER      :: MTAG_UB = 2**21-1
Referenced by wminiomd::wmioes().
mtagb
integer, parameter wmmdatmd::mtagb = 0
MTAGB.
Definition at line 345 of file wmmdatmd.F90.
   INTEGER, PARAMETER      :: MTAGB = 0
Referenced by wmwavemd::wmbcst(), and wmwavemd::wmwout().
nbi2g
integer, dimension(:,:), allocatable wmmdatmd::nbi2g
NBI2G.
Definition at line 367 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: NBI2G(:,:)
Referenced by wmgridmd::wmglow(), wminiomd::wmiobg(), and wminiomd::wmiobs().
nbi2s
integer, dimension(:,:), pointer wmmdatmd::nbi2s
NBI2S.
Definition at line 539 of file wmmdatmd.F90.
   INTEGER, POINTER           :: NBI2S(:,:)
Referenced by wmgridmd::wmglow(), wminiomd::wmiobg(), wminiomd::wmiobs(), and wmsetm().
nbista
integer, dimension(:), allocatable wmmdatmd::nbista
NBISTA.
Definition at line 371 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: NBISTA(:)
Referenced by wminiomd::wmiobg(), and wmndat().
ndt
integer, dimension(:), pointer wmmdatmd::ndt
NDT.
Definition at line 536 of file wmmdatmd.F90.
   INTEGER, POINTER           :: NDT(:)
Referenced by wmdimd(), wmsetm(), and wmupdtmd::wmupd1().
ngrpsmc
integer wmmdatmd::ngrpsmc
NGRPSMC.
Definition at line 334 of file wmmdatmd.F90.
   INTEGER                 :: NGRPSMC
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wminiomd::wmioeg().
nmdata
integer wmmdatmd::nmdata = -1
NMDATA.
Definition at line 310 of file wmmdatmd.F90.
   INTEGER                 :: NMDATA = -1
Referenced by wmdimd(), wmdimm(), wmndat(), and wmsetm().
nmperr
integer wmmdatmd::nmperr = 1
NMPERR.
Definition at line 326 of file wmmdatmd.F90.
   INTEGER                 :: NMPERR = 1
Referenced by wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmupdtmd::wmupd1(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), and wmwavemd::wmwave().
nmplog
integer wmmdatmd::nmplog = 1
NMPLOG.
Definition at line 323 of file wmmdatmd.F90.
   INTEGER                 :: NMPLOG = 1
Referenced by w3nmlmultimd::w3nmlmulticonf(), w3nmlmultimd::w3nmlmultidef(), w3nmlshelmd::w3nmlshel(), wmfinlmd::wmfinl(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
nmproc
integer wmmdatmd::nmproc = 1
NMPROC.
Definition at line 321 of file wmmdatmd.F90.
   INTEGER                 :: NMPROC = 1
Referenced by wmesmfmd::setexport(), wmesmfmd::setservices(), w3mlti(), w3sbs1(), wmwavemd::wmbcst(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wmiopomd::wmiopo(), wmgridmd::wmsmceql(), and wmwavemd::wmwave().
nmpscr
integer wmmdatmd::nmpscr = 1
NMPSCR.
Definition at line 324 of file wmmdatmd.F90.
   INTEGER                 :: NMPSCR = 1
Referenced by w3snl4md::insnl4(), rdtime(), wmesmfmd::setservices(), w3mlti(), w3sbs1(), wmfinlmd::wmfinl(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopp(), wmupdtmd::wmupd2(), wmupdtmd::wmupds(), wmupdtmd::wmupdt(), wmupdtmd::wmupdv(), and wmwavemd::wmwave().
nmptst
integer wmmdatmd::nmptst = 1
NMPTST.
Definition at line 325 of file wmmdatmd.F90.
   INTEGER                 :: NMPTST = 1
Referenced by wmwavemd::wmwave().
nmpupt
integer wmmdatmd::nmpupt = 1
NMPUPT.
Definition at line 327 of file wmmdatmd.F90.
   INTEGER                 :: NMPUPT = 1
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmiopomd::wmiopo().
nmv
integer, pointer wmmdatmd::nmv
NMV.
Definition at line 537 of file wmmdatmd.F90.
   INTEGER, POINTER           :: NMV
Referenced by wmdimd(), wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), wmupdtmd::wmupd1(), and wmwavemd::wmwave().
nmvmax
integer wmmdatmd::nmvmax
NMVMAX.
Definition at line 333 of file wmmdatmd.F90.
   INTEGER                 :: NMVMAX
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmupdtmd::wmupd1().
nrgrd
integer wmmdatmd::nrgrd
NRGRD.
Definition at line 330 of file wmmdatmd.F90.
   INTEGER                 :: NRGRD
Referenced by w3mlti(), w3sbs1(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobf(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioef(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohf(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmndat(), wmgridmd::wmrspc(), wmgridmd::wmsmceql(), and wmwavemd::wmwave().
nrgrp
integer wmmdatmd::nrgrp
NRGRP.
Definition at line 332 of file wmmdatmd.F90.
   INTEGER                 :: NRGRP
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
nrinp
integer wmmdatmd::nrinp
NRINP.
Definition at line 331 of file wmmdatmd.F90.
   INTEGER                 :: NRINP
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmndat().
rcld
integer, dimension(:), pointer wmmdatmd::rcld
RCLD.
Definition at line 535 of file wmmdatmd.F90.
   INTEGER, POINTER           :: RCLD(:)
Referenced by wmdimd(), wmsetm(), and wmupdtmd::wmupd1().
respec
logical, dimension(:,:), allocatable wmmdatmd::respec
RESPEC.
Definition at line 381 of file wmmdatmd.F90.
   LOGICAL, ALLOCATABLE    :: RESPEC(:,:)
Referenced by wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmiohg(), wmiopomd::wmiopo(), and wmgridmd::wmrspc().
sea_ipgl
integer, dimension(:), pointer wmmdatmd::sea_ipgl
SEA_IPGL.
Definition at line 556 of file wmmdatmd.F90.
   INTEGER, POINTER           :: SEA_IPGL(:)
Referenced by wmsetm().
sea_ipgl_to_proc
integer, dimension(:), pointer wmmdatmd::sea_ipgl_to_proc
SEA_IPGL_TO_PROC.
Definition at line 557 of file wmmdatmd.F90.
   INTEGER, POINTER           :: SEA_IPGL_TO_PROC(:)
Referenced by wmsetm().
stime
integer, dimension(2) wmmdatmd::stime
STIME.
Definition at line 328 of file wmmdatmd.F90.
   INTEGER                 :: STIME(2)
Referenced by wmesmfmd::setservices(), w3sbs1(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
tdata
integer, dimension(:,:), allocatable wmmdatmd::tdata
TDATA.
Definition at line 365 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: TDATA(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
tmax
integer, dimension(:,:), allocatable wmmdatmd::tmax
TMAX.
Definition at line 363 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: TMAX(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
tmv
integer, dimension(:,:,:), pointer wmmdatmd::tmv
TMV.
Definition at line 538 of file wmmdatmd.F90.
   INTEGER, POINTER           :: TMV(:,:,:)
Referenced by wmdimd(), wminitmd::wminit(), wminitmd::wminitnml(), wmsetm(), wmupdtmd::wmupd1(), and wmwavemd::wmwave().
toutp
integer, dimension(:,:), allocatable wmmdatmd::toutp
TOUTP.
Definition at line 364 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: TOUTP(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiohg(), wminiomd::wmiohs(), and wmwavemd::wmwave().
tsync
integer, dimension(:,:), allocatable wmmdatmd::tsync
TSYNC.
Definition at line 362 of file wmmdatmd.F90.
   INTEGER, ALLOCATABLE    :: TSYNC(:,:)
Referenced by wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmioes(), wminiomd::wmiohs(), and wmwavemd::wmwave().
uptmap
integer, dimension(:), pointer wmmdatmd::uptmap
UPTMAP.
Definition at line 541 of file wmmdatmd.F90.
   INTEGER, POINTER           :: UPTMAP(:)
Referenced by wmiopomd::wmiopo(), and wmsetm().