WAVEWATCH III: w3iogrmd Module Reference
w3iogrmd Module Reference
Reading/writing of model definition file.
Functions/Subroutines
subroutine w3iogr (INXOUT, NDSM, IMOD, FEXT ifdef W3_ASCII
Reading and writing of the model definition file.
Detailed Description
Reading/writing of model definition file.
Arrays allocated here on read or ing ww3_grid on write.
Author
H. L. Tolman
F. Ardhuin
Date
15-Apr-2020
Function/Subroutine Documentation
w3iogr()
subroutine w3iogrmd::w3iogr (character, dimension(*), intent(in) INXOUT, integer, intent(in) NDSM, integer, intent(in), optional IMOD, character, dimension(*), intent(in), optional FEXT, ifdef, W3_ASCII)
Reading and writing of the model definition file.
The file is opened within the routine, the name is pre-defined and the unit number is given in the parameter list. The model definition file is written using UNFORMATTED write statements.
Parameters
[in] INXOUT Test string for read/write.
[in] NDSM File unit number.
[in] IMOD Model number for W3GDAT etc.
[in] FEXT File extension to be used.
Author
H. L. Tolman
F. Ardhuin
Date
19-Oct-2020
Definition at line 117 of file w3iogrmd.F90.
                       ,ndsa                    &
 #endif
           )
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  !            F. Ardhuin             !
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         19-Oct-2020 |
     !/                  +-----------------------------------+
     !/
     !/    14-Jan-1999 : Distributed FORTRAN 77 version.     ( version 1.18 )
     !/    04-Feb-2000 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/                  Major changes to logistics.
     !/    14-Feb-2000 : Exact-NL added.                     ( version 2.01 )
     !/    09-Jan-2001 : Flat grid option.                   ( version 2.06 )
     !/    02-Feb-2001 : Exact-NL version 3.0                ( version 2.07 )
     !/    27-Feb-2001 : Third propagation scheme added.     ( version 2.08 )
     !/    16-Mar-2001 : Fourth propagation scheme added.    ( version 2.09 )
     !/    29-Mar-2001 : Sub-grid islands added.             ( version 2.10 )
     !/    11-Jan-2002 : Sub-grid ice added.                 ( version 2.15 )
     !/    09-May-2002 : Switch clean up.                    ( version 2.21 )
     !/    27-Aug-2002 : Exact-NL version 4.0                ( version 2.22 )
     !/    26-Nov-2002 : Adding first VDIA and MDIA.         ( version 3.01 )
     !/    01-Aug-2003 : Adding moving grid GSE correction.  ( version 3.03 )
     !/    08-Mar-2004 : Multiple grid version.              ( version 3.06 )
     !/    04-May-2005 : Change to MPI_COMM_WAVE.            ( version 3.07 )
     !/    24-Jun-2005 : Add MAPST2 processing.              ( version 3.07 )
     !/    09-Nov-2005 : Remove soft boundary options.       ( version 3.08 )
     !/    23-Jun-2006 : Add W3SLN1 parameters.              ( version 3.09 )
     !/    27-Jun-2006 : Adding file name preamble.          ( version 3.09 )
     !/    25-Jul-2006 : Reorder for 'GRID' option to read   ( version 3.10 )
     !/                  spectral data also.
     !/    28-Oct-2006 : Add partitioning pars.              ( version 3.10 )
     !/    26-Mar-2007 : Add partitioning pars.              ( version 3.11 )
     !/    16-Apr-2006 : Add Miche limiter pars.             ( version 3.11 )
     !/    25-Apr-2007 : Adding Battjes-Janssen Sdb.         ( version 3.11 )
     !/    09-Oct-2007 : Adding WAM cycle 4+ Sin and Sds.    ( version 3.13 )
     !/    29-May-2009 : Preparing distribution version.     ( version 3.14 )
     !/    30-Oct-2009 : Fix ndst arg in call to w3dmo5.     ( version 3.14 )
     !/                  (T. J. Campbell, NRL)
     !/    30-Oct-2009 : Implement curvilinear grid type.    ( version 3.14 )
     !/                  (W. E. Rogers & T. J. Campbell, NRL)
     !/    23-Dec-2009 : Addition of COU namelists           ( version 3.14 )
     !/    31-Oct-2010 : Implement unstructured grids        ( version 3.14 )
     !/                  (A. Roland and F. Ardhuin)
     !/    06-Dec-2010 : Change from GLOBAL (logical) to ICLOSE (integer) to
     !/                  specify index closure for a grid.   ( version 3.14 )
     !/                  (T. J. Campbell, NRL)
     !/    12-Jun-2012 : Add /RTD option or rotated grid option.
     !/                  (Jian-Guo Li)                       ( version 4.06 )
     !/    13-Jul-2012 : Move GMD (SNL3) and nonlinear filter (SNLS)
     !/                  from 3.15 (HLT).                    ( version 4.08 )
     !/    12-Dec-2012 : Adding SMC grid.  JG_Li             ( version 4.08 )
     !/    19-Dec-2012 : Add NOSWLL to file.                 ( version 4.11 )
     !/    01-Jul-2013 : Document UQ / UNO switches in file  ( version 4.12 )
     !/    10-Sep-2013 : Add IG1 parameters                  ( version 4.12 )
     !/    16-Sep-2013 : Add Arctic part in SMC grid.        ( version 4.12 )
     !/    11-Nov-2013 : Make SMC and RTD grids compatible.  ( version 4.13 )
     !/    06-Mar-2014 : Writes out a help message on error  ( version 4.18 )
     !/    10-Mar-2014 : Add IC2 parameters                  ( version 5.01 )
     !/    29-May-2014 : Add IC3 parameters                  ( version 5.01 )
     !/    20-Aug-2016 : Add IOBPA                           ( version 5.12 )
     !/    08-Mar-2018 : Add FSWND for SMC grid.             ( version 6.02 )
     !/    05-Jun-2018 : Add PDLIB/DEBUGINIT and implcit scheme parameters
     !/                  for unstructured grids              ( version 6.04 )
     !/    27-Jul-2018 : Added PTMETH and PTFCUT parameters  ( version 6.05 )
     !/                  (C. Bunney, UKMO)
     !/    18-Aug-2018 : S_{ice} IC5 (Q. Liu)                ( version 6.06 )
     !/    26-Aug-2018 : UOST (Mentaschi et al. 2015, 2018)  ( version 6.06 )
     !/    15-Apr-2020 : Adds optional opt-out for CFL on BC ( version 7.08 )
     !/    18-Jun-2020 : Adds 360-day calendar option        ( version 7.08 )
     !/    19-Oct-2020 : Add AIRCMIN, AIRGB parameters       ( version 7.08 )
     !/    07-07-2021  : S_{nl} GKE NL5 (Q. Liu)             ( version 7.12 )
     !/    19-Jul-2021 : Momentum and air density support    ( version 7.14 )
     !/
     !/    Copyright 2009-2013 National Weather Service (NWS),
     !/       National Oceanic and Atmospheric Administration.  All rights
     !/       reserved.  WAVEWATCH III is a trademark of the NWS.
     !/       No unauthorized use without permission.
     !/
     !  1. Purpose :
     !
     !     Reading and writing of the model definition file.
     !
     !  2. Method :
     !
     !     The file is opened within the routine, the name is pre-defined
     !     and the unit number is given in the parameter list. The model
     !     definition file is written using UNFORMATTED write statements.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       INXOUT  C*(*)  I   Test string for read/write, valid are:
     !                         'READ',  'WRITE' and 'GRID'.
     !       NDSM    Int.   I   File unit number.
     !       NDSA    Int.   I   File unit number. ascii
     !       IMOD    Int.   I   Model number for W3GDAT etc.
     !       FEXT    C*(*)  I   File extension to be used.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See above.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3INIT    Subr. W3INITMD Wave model initialization routine.
     !      ......    Prog.   N/A    All WAVEWATCH III aux programs and
     !                               drivers.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       Tests on INXOUT, file status and on array dimensions.
     !
     !  7. Remarks :
     !
     !     - The model definition file has the pre-defined name
     !       'mod_def.FILEXT'.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/MPI  MPI calls
     !
     !     !/LNn  Select source terms
     !     !/STn
     !     !/NLn
     !     !/BTn
     !     !/DBn
     !     !/TRn
     !     !/BSn
     !     !/XXn
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     use w3servmd, only : print_memcheck
     USE constants
     USE w3gdatmd
 #ifdef W3_MPI
     USE w3adatmd, ONLY: mpi_comm_wave
 #endif
     USE w3odatmd
 #ifdef W3_ST2
     USE w3src2md, ONLY: inptab
 #endif
 #ifdef W3_ST3
     USE w3src3md, ONLY: insin3
 #endif
 #ifdef W3_ST4
     USE w3src4md, ONLY: insin4, taut, tauhft, tauhft2, &
          delu, deltauw, delust, &
          delalp, deltail, &
          dikcumul
 #endif
 #ifdef W3_NL1
     USE w3snl1md, ONLY: insnl1, insnlgqm
 #endif
 #ifdef W3_NL2
     USE w3snl2md, ONLY: insnl2
 #endif
 #ifdef W3_NL3
     USE w3snl3md, ONLY: insnl3
 #endif
 #ifdef W3_NL5
     USE w3snl5md, ONLY: insnl5
 #endif
 #ifdef W3_NLS
     USE w3snlsmd, ONLY: insnls
 #endif
 #ifdef W3_IS2
     USE w3sis2md, ONLY: insis2
 #endif
     USE w3timemd, ONLY: caltype
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     USE w3dispmd
 #ifdef W3_UOST
     USE w3uostmd, ONLY: uost_initgrid
 #endif
     !
 #ifdef W3_MPI
     include "mpif.h"
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)             :: NDSM
     INTEGER, INTENT(IN), OPTIONAL   :: IMOD
     CHARACTER, INTENT(IN)           :: INXOUT*(*)
     CHARACTER, INTENT(IN), OPTIONAL :: FEXT*(*)
 #ifdef W3_ASCII
     INTEGER, INTENT(IN), OPTIONAL   :: NDSA
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IGRD, IERR, I, J, MTH, MK, ISEA, IX, IY
     INTEGER                 :: IEXT, IPRE
 #ifdef W3_ST4
     INTEGER                 :: IK, ITH, IK2, ITH2
 #endif
     INTEGER, ALLOCATABLE    :: MAPTMP(:,:)
 #ifdef W3_MPI
     INTEGER                 :: IERR_MPI, IP
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
 #ifdef W3_T
     INTEGER                 :: K
 #endif
     LOGICAL                 :: WRITE, FLTEST = .false., testll,     &
          flsnl2 = .false.
     LOGICAL, SAVE           :: FLINP = .false. , fldisp = .false.,  &
          flis  = .false.
     CHARACTER(LEN=10)       :: VERTST
     CHARACTER(LEN=13)       :: TEMPXT
     CHARACTER(LEN=30)       :: TNAME0, TNAME1, TNAME2, TNAME3,      &
          TNAME4, TNAME5, TNAME6,              &
          TNAMEP, TNAMEG, TNAMEF, TNAMEI
     CHARACTER(LEN=30)       :: FNAME0, FNAME1, FNAME2, FNAME3,      &
          FNAME4, FNAME5, FNAME6,              &
          FNAMEP, FNAMEG, FNAMEF, FNAMEI
     CHARACTER(LEN=35)       :: IDTST
     CHARACTER(LEN=60)       :: MESSAGE(5)
     LOGICAL                 :: GLOBAL
     REAL, ALLOCATABLE       :: XGRD4(:,:), YGRD4(:,:)
     integer                 :: memunit
     !/
     !/ ------------------------------------------------------------------- /
     !/
     memunit = 740+iaproc
 #ifdef W3_S
     CALL strace (ient, 'W3IOGR')
 #endif
     !
     call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 1')
     message =(/ '     MOD DEF FILE WAS GENERATED WITH A DIFFERENT    ', &
          '     WW3 VERSION OR USING A DIFFERENT SWITCH FILE.  ',        &
          '     MAKE SURE WW3_GRID IS COMPILED WITH SAME SWITCH',        &
          '     AS WW3_SHEL OR WW3_MULTI, RUN WW3_GRID AGAIN   ',        &
          '     AND THEN TRY AGAIN THE PROGRAM YOU JUST USED.  '/)
     !
     tnamef = '------------------------------'
     tname0 = '------------------------------'
     tname1 = '------------------------------'
     tname2 = '------------------------------'
     tname3 = '------------------------------'
     tname4 = '------------------------------'
     tname5 = '------------------------------'
     tname6 = '------------------------------'
     tnamep = '------------------------------'
     tnameg = '------------------------------'
     tnamei = '------------------------------'
     !
 #ifdef W3_FLX1
     tnamef = 'Wu (1980)                     '
 #endif
 #ifdef W3_FLX2
     tnamef = 'Tolman and Chalikov (1996)    '
 #endif
 #ifdef W3_FLX3
     tnamef = 'T and C(1996) with cap on Cd  '
 #endif
 #ifdef W3_FLX4
     tnamef = 'Hwang (2011) with cap on Cd   '
 #endif
 #ifdef W3_FLX5
     tnamef = 'Direct use of stress          '
 #endif
 #ifdef W3_LN0
     tname0 = 'Not defined                   '
 #endif
 #ifdef W3_LN1
     tname0 = 'Cavaleri and M.-R. (1982)     '
 #endif
 #ifdef W3_ST0
     tname1 = 'Not defined                   '
 #endif
 #ifdef W3_ST1
     tname1 = 'WAM cycles 1 through 3        '
 #endif
 #ifdef W3_ST2
     tname1 = 'Tolman and Chalikov (1996)    '
 #endif
 #ifdef W3_ST3
     tname1 = 'WAM cycle 4+                  '
 #endif
 #ifdef W3_ST4
     tname1 = 'Ardhuin et al. (2009+)        '
 #endif
 #ifdef W3_ST6
     tname1 = 'BYDB input and dissipation    '
 #endif
 #ifdef W3_NL0
     tname2 = 'Not defined                   '
 #endif
 #ifdef W3_NL1
     tname2 = 'Discrete Interaction Approx.  '
 #endif
 #ifdef W3_NL2
     tname2 = 'Exact nonlinear interactions  '
 #endif
 #ifdef W3_NL3
     tname2 = 'Generalized Multiple DIA      '
 #endif
 #ifdef W3_NL4
     tname2 = 'Two Scaled Approximation      '
 #endif
 #ifdef W3_NL5
     tname2 = 'Generalized Kinetic Equation  '
 #endif
 #ifdef W3_BT0
     tname3 = 'Not defined                   '
 #endif
 #ifdef W3_BT1
     tname3 = 'JONSWAP                       '
 #endif
 #ifdef W3_BT4
     tname3 = 'SHOWEX                        '
 #endif
 #ifdef W3_BT8
     tname3 = 'Muddy Bed (D & L)             '
 #endif
 #ifdef W3_IC1
     tnamei = 'Ice sink term (uniform k_i)   '
 #endif
 #ifdef W3_IC2
     tnamei = 'Ice sink term (Lui et al)     '
 #endif
 #ifdef W3_IC3
     tnamei = 'Ice sink term (Wang and Shen) '
 #endif
 #ifdef W3_IC4
     tnamei = 'Ice sink term (empirical)     '
 #endif
 #ifdef W3_IC5
     tnamei = 'Ice sink term (eff. medium)   '
 #endif
 #ifdef W3_DB0
     tname4 = 'Not defined                   '
 #endif
 #ifdef W3_DB1
     tname4 = 'Battjes and Janssen (1978)    '
 #endif
 #ifdef W3_TR0
     tname5 = 'Not defined                   '
 #endif
 #ifdef W3_BS0
     tname6 = 'Not defined                   '
 #endif
 #ifdef W3_PR0
     tnamep = 'No propagation                '
 #endif
 #ifdef W3_PR1
     tnamep = 'First order upstream          '
 #endif
 #ifdef W3_UQ
     tnamep = '3rd order UQ scheme           '
 #endif
 #ifdef W3_UNO
     tnamep = '2nd order UNO scheme          '
 #endif
 #ifdef W3_PR0
     tnameg = 'No GSE aleviation             '
 #endif
 #ifdef W3_PR1
     tnameg = 'No GSE aleviation (1up prop)  '
 #endif
 #ifdef W3_PR2
     tnameg = 'Diffusion operator            '
 #endif
 #ifdef W3_PR3
     tnameg = 'Averaging operator            '
 #endif
     !
     fnamef = tnamef
     fname0 = tname0
     fname1 = tname1
     fname2 = tname2
     fname3 = tname3
     fname4 = tname4
     fname5 = tname5
     fname6 = tname6
     fnamep = tnamep
     fnameg = tnameg
     fnamei = tnamei
     !
 #ifdef W3_T
     fltest = .true.
 #endif
 #ifdef W3_NL2
     flsnl2 = .true.
 #endif
     !
     ! test input parameters ---------------------------------------------- *
     !
     IF ( PRESENT(imod) ) THEN
       igrd   = imod
     ELSE
       igrd   = 1
     END IF
     !
     IF ( PRESENT(fext) ) THEN
       tempxt = fext
     ELSE
       tempxt = 'ww3'
     END IF
     !
     IF (inxout.NE.'READ' .AND. inxout.NE.'WRITE'                    &
          .AND. inxout.NE.'GRID') THEN
       IF ( iaproc .EQ. naperr ) WRITE (ndse,900) inxout
       CALL extcde ( 1 )
     END IF
     !
     WRITE  = inxout .EQ. 'WRITE'
     !
 #ifdef W3_T
     WRITE (ndst,9000) inxout, WRITE, ndsm, igrd, tempxt
 #endif
     !
     CALL w3seto ( igrd, ndse, ndst )
     CALL w3setg ( igrd, ndse, ndst )
     filext = tempxt
     call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 2')
     !
     ! open file ---------------------------------------------------------- *
     !
     iext   = len_trim(filext)
     ipre   = len_trim(fnmpre)
     !
     !AR: ADD DEBUGFLAG      WRITE(*,*) 'FILE=', FNMPRE(:IPRE)//'mod_def.'//FILEXT(:IEXT)
     IF ( WRITE ) THEN
       OPEN (ndsm,file=fnmpre(:ipre)//'mod_def.'//filext(:iext),   &
            form='UNFORMATTED', convert=file_endian,err=800,iostat=ierr)
 #ifdef W3_ASCII
       OPEN (ndsa,file=fnmpre(:ipre)//'mod_def.'//filext(:iext)//'.txt',   &
            form='FORMATTED',err=800,iostat=ierr)
 #endif
     ELSE
       OPEN (ndsm,file=fnmpre(:ipre)//'mod_def.'//filext(:iext),   &
            form='UNFORMATTED', convert=file_endian,status='OLD',err=800,iostat=ierr)
     ENDIF
     !
     rewind( ndsm )
     !
     ! Dimensions and test information --------------------------------------
     !
     IF ( WRITE ) THEN
       WRITE (ndsm)                                               &
            idstr, vergrd, nx, ny, nsea, nth, nk,                 &
            nbi, nfbpo, gname, fname0, fname1, fname2, fname3,    &
            fname4, fname5, fname6, fnamep, fnameg,               &
            fnamef, fnamei
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                             &
            'IDSTR, VERGRD, NX, NY, NSEA, NTH, NK,                &
            NBI, NFBPO, GNAME, FNAME0, FNAME1, FNAME2, FNAME3,    &
            FNAME4, FNAME5, FNAME6, FNAMEP, FNAMEG,               &
            FNAMEF, FNAMEI:',                                     &
            idstr, vergrd, nx, ny, nsea, nth, nk,                 &
            nbi, nfbpo, gname, fname0, fname1, fname2, fname3,    &
            fname4, fname5, fname6, fnamep, fnameg,               &
            fnamef, fnamei
 #endif
       !
 #ifdef W3_SMC
       WRITE (ndsm) ncel, nufc, nvfc, nrlv, mrfct
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'NCel, NUFc, NVFc, NRLv, MRFct:',           &
                      ncel, nufc, nvfc, nrlv, mrfct
 #endif
       WRITE (ndsm) nglo, narc, nbgl, nbac, nbsmc
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'NGLO, NARC, NBGL, NBAC, NBSMC:',             &
                    nglo, narc, nbgl, nbac, nbsmc
 #endif
 #endif
       !
       WRITE (ndsm)                                               &
            (nbo(i),i=0,nfbpo), (nbo2(i),i=0,nfbpo)
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                             &
            '(NBO(I),I=0,NFBPO), (NBO2(I),I=0,NFBPO):',           &
            (nbo(i),i=0,nfbpo), (nbo2(i),i=0,nfbpo)
 #endif
 #ifdef W3_T
       WRITE (ndst,9001) idstr, vergrd, nx, ny, nsea, nth, nk,    &
            nbi, nfbpo, 9, gname, fname0, fname1, fname2, fname3, &
            fname4, fname5, fname6, fnamep, fnameg,               &
            fnamef, fnamei
       WRITE (ndst,9002) (nbo(i),i=0,nfbpo)
       WRITE (ndst,9003) (nbo2(i),i=0,nfbpo)
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                    &
            idtst, vertst, nx, ny, nsea, mth, mk,                 &
            nbi, nfbpo, gname, fname0, fname1, fname2, fname3,    &
            fname4, fname5, fname6, fnamep, fnameg,               &
            fnamef, fnamei
       !
 #ifdef W3_SMC
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                    &
            ncel, nufc, nvfc, nrlv, mrfct
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                    &
            nglo, narc, nbgl, nbac, nbsmc
 #endif
       !
       nk     = mk
       nth    = mth
       nk2    = nk + 2
       nspec  = nk * nth
 #ifdef W3_T
       WRITE (ndst,9001) idstr, vergrd, nx, ny, nsea, nth, nk,    &
            nbi, nfbpo, 9, gname, fname0, fname1, fname2, fname3, &
            fname4, fname5, fname6, fnamep, fnameg,               &
            fnamef, fnamei
 #endif
       !
       IF ( idtst .NE. idstr ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,901) idtst, idstr
         CALL extcde ( 10 )
       END IF
       IF ( vertst .NE. vergrd ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,902) vertst, vergrd
         CALL extcde ( 11 )
       END IF
       IF ( nfbpo .GT. 9 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,904) nfbpo, 9
         CALL extcde ( 13 )
       END IF
       IF ( fname0 .NE. tname0 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 0, filext(:iext), fname0, tname0, &
              message
         CALL extcde ( 14 )
       END IF
       IF ( fname1 .NE. tname1 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 1, filext(:iext), fname1, tname1, &
              message
         CALL extcde ( 15 )
       END IF
       IF ( fname2 .NE. tname2 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 2, filext(:iext), fname2, tname2, &
              message
         CALL extcde ( 16 )
       END IF
       IF ( fname3 .NE. tname3 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 3, filext(:iext), fname3, tname3, &
              message
         CALL extcde ( 17 )
       END IF
       IF ( fnamei .NE. tnamei ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 3, filext(:iext), fnamei, tnamei, &
              message
         CALL extcde ( 17 )
       END IF
       IF ( fname4 .NE. tname4 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 4, filext(:iext), fname4, tname4, &
              message
         CALL extcde ( 18 )
       END IF
       IF ( fname5 .NE. tname5 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 5, filext(:iext), fname5, tname5, &
              message
         CALL extcde ( 19 )
       END IF
       IF ( fname6 .NE. tname6 ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,905) 6, filext(:iext), fname6, tname6, &
              message
         CALL extcde ( 20 )
       END IF
       IF ( fnamep .NE. tnamep ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,906) fnamep, tnamep
         CALL extcde ( 22 )
       END IF
       IF ( fnameg .NE. tnameg ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,907) fnameg, tnameg, message
         CALL extcde ( 22 )
       END IF
       IF ( fnamef .NE. tnamef ) THEN
         IF ( iaproc .EQ. naperr )                               &
              WRITE (ndse,908) filext(:iext), fnamef, tnamef, message
         CALL extcde ( 24 )
       END IF
       !
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                   &
            (nbo(i),i=0,nfbpo), (nbo2(i),i=0,nfbpo)
 #ifdef W3_T
       WRITE (ndst,9002) (nbo(i),i=0,nfbpo)
       WRITE (ndst,9003) (nbo2(i),i=0,nfbpo)
 #endif
       !
     ENDIF
     call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 3')
     !
     ! Parameters in modules  --------------------------------------------- *
     !                                                   Module W3GDAT GRID
     !
     ALLOCATE ( maptmp(ny,nx) )
     !
     IF ( WRITE ) THEN
       maptmp = mapsta + 8*mapst2
       WRITE (ndsm)                                            &
            gtype, flagll, iclose
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                          &
            'GTYPE, FLAGLL, ICLOSE:',                          &
            gtype, flagll, iclose
 #endif
       !
       ! Writes different kind of information depending on grid type
       !
       SELECT CASE ( gtype )
         !!Li  SMCTYPE shares info with RLGTYPE.   JGLi12Oct2020
       CASE ( rlgtype, smctype )
         WRITE (ndsm)                                          &
              sx, sy, x0, y0
 #ifdef W3_ASCII
         WRITE (ndsa,*)                                        &
              'SX, SY, X0, Y0:',                               &
              sx, sy, x0, y0
 #endif
       CASE ( clgtype )
         WRITE (ndsm)                                          &
              REAL(XGRD), REAL(YGRD)
 #ifdef W3_ASCII
         WRITE (ndsa,*)                                        &
              'REAL(XGRD), REAL(YGRD):',                       &
              REAL(XGRD), REAL(YGRD)
 #endif
       CASE (ungtype)
         WRITE (ndsm)                                          &
              fsn, fspsi,fsfct,fsnimp,fstotalimp,fstotalexp,   &
              fsbccfl, fsrefraction, fsfreqshift, fssource,    &
              do_change_wlv, solverthr_stp, crit_dep_stp,      &
              ntri,countot, countri, nnz,                      &
              b_jgs_terminate_maxiter,                         &
              b_jgs_terminate_difference,                      &
              b_jgs_terminate_norm,                            &
              b_jgs_limiter,                                   &
              b_jgs_block_gauss_seidel,                        &
              b_jgs_use_jacobi,                                &
              b_jgs_maxiter,                                   &
              b_jgs_pmin,                                      &
              b_jgs_diff_thr,                                  &
              b_jgs_norm_thr,                                  &
              b_jgs_nlevel,                                    &
              b_jgs_source_nonlinear
 #ifdef W3_ASCII
         WRITE (ndsa,*)                                        &
              'FSN, FSPSI,FSFCT,FSNIMP,FSTOTALIMP,FSTOTALEXP,   &
              FSBCCFL, FSREFRACTION, FSFREQSHIFT, FSSOURCE,    &
              DO_CHANGE_WLV, SOLVERTHR_STP, CRIT_DEP_STP,      &
              NTRI,COUNTOT, COUNTRI, NNZ,                      &
              B_JGS_TERMINATE_MAXITER,                         &
              B_JGS_TERMINATE_DIFFERENCE,                      &
              B_JGS_TERMINATE_NORM,                            &
              B_JGS_LIMITER,                                   &
              B_JGS_BLOCK_GAUSS_SEIDEL,                        &
              B_JGS_USE_JACOBI,                                &
              B_JGS_MAXITER,                                   &
              B_JGS_PMIN,                                      &
              B_JGS_DIFF_THR,                                  &
              B_JGS_NORM_THR,                                  &
              B_JGS_NLEVEL,                                    &
              B_JGS_SOURCE_NONLINEAR:',                        &
              fsn, fspsi,fsfct,fsnimp,fstotalimp,fstotalexp,   &
              fsbccfl, fsrefraction, fsfreqshift, fssource,    &
              do_change_wlv, solverthr_stp, crit_dep_stp,      &
              ntri,countot, countri, nnz,                      &
              b_jgs_terminate_maxiter,                         &
              b_jgs_terminate_difference,                      &
              b_jgs_terminate_norm,                            &
              b_jgs_limiter,                                   &
              b_jgs_block_gauss_seidel,                        &
              b_jgs_use_jacobi,                                &
              b_jgs_maxiter,                                   &
              b_jgs_pmin,                                      &
              b_jgs_diff_thr,                                  &
              b_jgs_norm_thr,                                  &
              b_jgs_nlevel,                                    &
              b_jgs_source_nonlinear
 #endif
         !Init COUNTCON and IOBDP to zero, it needs to be set somewhere or
         !removed
         countcon=0
         iobdp=0
         WRITE (ndsm)                                          &
              x0, y0, sx, sy, dxymax, xgrd, ygrd, trigp, tria, &
              len, ien, angle0, angle, si, maxx, maxy,         &
              dxymax, index_cell, ccon, countcon, ie_cell,     &
              pos_cell, iobp, iobpa, iobdp, iobpd, iaa, jaa, posi
 #ifdef W3_ASCII
         WRITE (ndsa,*)                                          &
              'X0, Y0, SX, SY, DXYMAX, XGRD, YGRD, TRIGP, TRIA, &
              LEN, IEN, ANGLE0, ANGLE, SI, MAXX, MAXY,         &
              DXYMAX, INDEX_CELL, CCON, COUNTCON, IE_CELL,     &
              POS_CELL, IOBP, IOBPA, IOBDP, IOBPD, IAA, JAA, POSI:', &
              x0, y0, sx, sy, dxymax, xgrd, ygrd, trigp, tria, &
              len, ien, angle0, angle, si, maxx, maxy,         &
              dxymax, index_cell, ccon, countcon, ie_cell,     &
              pos_cell, iobp, iobpa, iobdp, iobpd, iaa, jaa, posi
 #endif
       END SELECT !GTYPE
       !
       WRITE (ndsm)                                            &
            zb, maptmp, mapfs, mapsf, trflag
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                          &
            'ZB, MAPTMP, MAPFS, MAPSF, TRFLAG:',               &
            zb, maptmp, mapfs, mapsf, trflag
 #endif
       !
 #ifdef W3_SMC
       IF( gtype .EQ. smctype ) THEN
         WRITE (ndsm)  nlvcel, nlvufc, nlvvfc
         WRITE (ndsm)  ijkcel, ijkufc, ijkvfc, ismcbp
         WRITE (ndsm)  iclbac
         WRITE (ndsm)  angarc
         WRITE (ndsm)  ctrnx,  ctrny,  clatf
 #ifdef W3_ASCII
         WRITE (ndsa,*)  'NLvCel, NLvUFc, NLvVFc:',            &
                         nlvcel, nlvufc, nlvvfc
         WRITE (ndsa,*)  'IJKCel, IJKUFc, IJKVFc, ISMCBP:',    &
                         ijkcel, ijkufc, ijkvfc, ismcbp
         WRITE (ndsa,*)  'ICLBAC:',                            &
                         iclbac
         WRITE (ndsa,*)  'ANGARC:',                            &
                         angarc
         WRITE (ndsa,*)  'CTRNX,  CTRNY,  CLATF:',             &
                         ctrnx,  ctrny,  clatf
 #endif
         IF ( fltest ) THEN
           WRITE (ndse,"('  NRLv, MRFct and NBSMC values are',3I9)") nrlv, mrfct, nbsmc
           WRITE (ndse,"('  IJKCel, IJKUFc, IJKVFc Write for',3I9)") ncel, nufc, nvfc
           WRITE (ndse,"('  CTRNXY transparency write for 2x', I9)") ncel
         ENDIF
       ENDIF
 #endif
       !
       IF ( trflag .NE. 0 ) WRITE (ndsm) trnx, trny
 #ifdef W3_ASCII
       IF ( trflag .NE. 0 ) WRITE (ndsa,*) 'TRNX, TRNY:', trnx, trny
 #endif
       WRITE (ndsm)                     &
            dtcfl, dtcfli, dtmax, dtmin, dmin, ctmax,              &
            fice0, ficen, ficel, pfmove, fldry, flcx, flcy, flcth, &
            flck, flsou, flbpi, flbpo, clats, clatis, cthg0s,      &
            stexu, steyu, stedu, iicehmin, iicehinit, iicedisp,    &
            icescales(1:4), caltype, cmprtrck, iicehfac, iicehdisp,&
            iiceddisp, iicefdisp, btbeta,                          &
            aaircmin, aairgb
 #ifdef W3_ASCII
       WRITE (ndsa,*)                   &
            'DTCFL, DTCFLI, DTMAX, DTMIN, DMIN, CTMAX,             &
            FICE0, FICEN, FICEL, PFMOVE, FLDRY, FLCX, FLCY, FLCTH, &
            FLCK, FLSOU, FLBPI, FLBPO, CLATS, CLATIS, CTHG0S,      &
            STEXU, STEYU, STEDU, IICEHMIN, IICEHINIT, IICEDISP,    &
            ICESCALES(1:4), CALTYPE, CMPRTRCK, IICEHFAC, IICEHDISP,&
            IICEDDISP, IICEFDISP, BTBETA,                          &
            AAIRCMIN, AAIRGB:',                                    &
            dtcfl, dtcfli, dtmax, dtmin, dmin, ctmax,              &
            fice0, ficen, ficel, pfmove, fldry, flcx, flcy, flcth, &
            flck, flsou, flbpi, flbpo, clats, clatis, cthg0s,      &
            stexu, steyu, stedu, iicehmin, iicehinit, iicedisp,    &
            icescales(1:4), caltype, cmprtrck, iicehfac, iicehdisp,&
            iiceddisp, iicefdisp, btbeta,                          &
            aaircmin, aairgb
 #endif
       WRITE(ndsm)gridshift
 #ifdef W3_ASCII
       WRITE(ndsa,*)'GRIDSHIFT:',                                  &
                  gridshift
 #endif
 #ifdef W3_SEC1
       WRITE (ndsm) nitersec1
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'NITERSEC1:',                                &
                    nitersec1
 #endif
 #endif
 #ifdef W3_RTD
       !!  Add rotated Polat/lon and AnglD to mod_def   JGLi12Jun2012
       WRITE (ndsm) polat, polon, angld, flagunr
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'PoLat, PoLon, AnglD, FLAGUNR:',             &
                    polat, polon, angld, flagunr
 #endif
 #endif
       !!        WRITE(NDSM)                                                 &
       !!             COUG_2D, COUG_RAD3D, COUG_US3D
     ELSE
       call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 4')
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                      &
            gtype, flagll, iclose
       !!Li      IF (.NOT.GINIT) CALL W3DIMX ( IGRD, NX, NY, NSEA, NDSE, NDST )
       IF (.NOT.ginit) CALL w3dimx ( igrd, nx, ny, nsea, ndse, ndst &
 #ifdef W3_SMC
            , ncel, nufc, nvfc, nrlv, nbsmc                         &
            , narc, nbac, nspec                                     &
 #endif
            )
       !
       ! Reads different kind of information depending on grid type
       !
       SELECT CASE ( gtype )
         !!Li  SMCTYPE shares info with RLGTYPE.   JGLi12Oct2020
       CASE ( rlgtype, smctype )
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                 &
              sx, sy, x0, y0
         DO ix=1,nx
           xgrd(:,ix) = real(x0 + real(ix-1)*sx)
         END DO
         DO iy=1,ny
           ygrd(iy,:) = real(y0 + real(iy-1)*sy)
         END DO
       CASE ( clgtype )
         ALLOCATE(xgrd4(ny,nx),ygrd4(ny,nx)); xgrd4 = 0.; ygrd4 = 0.
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
              xgrd4, ygrd4
         xgrd = xgrd4
         ygrd = ygrd4
         DEALLOCATE(xgrd4, ygrd4)
         !Set SX, SY, X0, Y0 to large values if curvilinear grid
         x0 = huge(x0); y0 = huge(y0)
         sx = huge(sx); sy = huge(sy)
       CASE (ungtype)
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
              fsn, fspsi,fsfct,fsnimp,fstotalimp,fstotalexp,   &
              fsbccfl, fsrefraction, fsfreqshift, fssource,    &
              do_change_wlv, solverthr_stp, crit_dep_stp,      &
              ntri,countot, countri, nnz,                      &
              b_jgs_terminate_maxiter,                         &
              b_jgs_terminate_difference,                      &
              b_jgs_terminate_norm,                            &
              b_jgs_limiter,                                   &
              b_jgs_block_gauss_seidel,                        &
              b_jgs_use_jacobi,                                &
              b_jgs_maxiter,                                   &
              b_jgs_pmin,                                      &
              b_jgs_diff_thr,                                  &
              b_jgs_norm_thr,                                  &
              b_jgs_nlevel,                                    &
              b_jgs_source_nonlinear
         IF (.NOT. guginit) THEN
           CALL w3dimug ( igrd, ntri, nx, countot, nnz, ndse, ndst )
         END IF
         call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 5')
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
              x0, y0, sx, sy, dxymax, xgrd, ygrd, trigp, tria, &
              len, ien, angle0, angle, si, maxx, maxy,         &
              dxymax, index_cell, ccon, countcon, ie_cell,     &
              pos_cell, iobp, iobpa, iobdp, iobpd, iaa, jaa, posi
         call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 6')
       END SELECT !GTYPE
       !
       IF (gtype.NE.ungtype) CALL w3gntx ( igrd, ndse, ndst )
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)   &
            zb, maptmp, mapfs, mapsf, trflag
       !
 #ifdef W3_SMC
       IF( gtype .EQ. smctype ) THEN
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
              nlvcel, nlvufc, nlvvfc
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
              ijkcel, ijkufc, ijkvfc, ismcbp
         DO j=lbound(ijkcel,2), ubound(ijkcel,2)
           ijkcel3(j) = ijkcel(3,j)
           ijkcel4(j) = ijkcel(4,j)
         END DO
         DO j=lbound(ijkvfc,2), ubound(ijkvfc,2)
           ijkvfc5(j) = ijkvfc(5,j)
           ijkvfc6(j) = ijkvfc(6,j)
         END DO
         DO j=lbound(ijkufc,2), ubound(ijkufc,2)
           ijkufc5(j) = ijkufc(5,j)
           ijkufc6(j) = ijkufc(6,j)
         END DO
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
              iclbac
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
              angarc
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
              ctrnx,  ctrny,  clatf
       ENDIF
 #endif
       !
       mapsta = mod(maptmp+2,8) - 2
       mapst2 = (maptmp-mapsta) / 8
       mapsf(:,3) = mapsf(:,2) + (mapsf(:,1)-1)*ny
       IF ( trflag .NE. 0 ) THEN
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR) TRNX, trny
       END IF
 #ifdef W3_UOST
       ! UOST (Unresolved Obstacles Source Term) is enabled.
       ! setting TRNX, TRNY to null values
       trnx = 1
       trny = 1
 #endif
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                     &
            dtcfl, dtcfli, dtmax, dtmin, dmin, ctmax,              &
            fice0, ficen, ficel, pfmove, fldry, flcx, flcy,        &
            flcth, flck, flsou, flbpi, flbpo, clats, clatis,       &
            cthg0s, stexu, steyu, stedu, iicehmin, iicehinit,      &
            iicedisp, icescales(1:4), caltype, cmprtrck, iicehfac, &
            iiceddisp, iicehdisp, iicefdisp, btbeta,               &
            aaircmin, aairgb
       READ(ndsm,END=801,ERR=802,IOSTAT=IERR)gridshift
 #ifdef W3_SEC1
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) nitersec1
 #endif
       !
 #ifdef W3_RTD
       !!  Read rotated Polat/lon and AnglD from mod_def   JGLi12Jun2012
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) PoLat, PoLon, AnglD, flagunr
 #endif
       !
     END IF
     call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 7')
     !
 #ifdef W3_T
     WRITE (ndst,9010) gtype, flagll, iclose, sx, sy, x0, y0, trflag
     WRITE (ndst,9011) 'MAPSTA'
     DO iy=min(ny,20), 1, -1
       WRITE (ndst,9012) (mapsta(iy,ix),ix=1,min(nx,30))
     END DO
     WRITE (ndst,9011) 'MAPST2'
     DO iy=min(ny,20), 1, -1
       WRITE (ndst,9012) (mapst2(iy,ix),ix=1,min(nx,30))
     END DO
     WRITE (ndst,9011) 'MAPFS'
     DO iy=min(ny,20), 1, -1
       WRITE (ndst,9013) (mapfs(iy,ix),ix=1,min(nx,12))
     END DO
     IF ( trflag .NE. 0 ) THEN
       WRITE (ndst,9011) 'TRNX'
       DO iy=min(ny,20), 1, -1
         WRITE (ndst,9014) (trnx(iy,ix),ix=1,min(nx,12))
       END DO
       WRITE (ndst,9011) 'TRNY'
       DO iy=min(ny,20), 1, -1
         WRITE (ndst,9014) (trny(iy,ix),ix=1,min(nx,12))
       END DO
     END IF
 #endif
     !
     DEALLOCATE ( maptmp )
     !
 #ifdef W3_T
     WRITE (ndst,9015) dtcfl, dtcfli, dtmax, dtmin,               &
          dmin, ctmax, fice0, ficen, ficel, pfmove,  &
          stexu, steyu, stedu
     WRITE (ndst,9016) fldry, flcx, flcy, flcth, flck,            &
          flsou, flbpi, flbpo
     WRITE (ndst,9017) (clats(isea),isea=1,1),                    &
          (clatis(isea),isea=1,1), (cthg0s(iy),isea=1,1)
 #endif
     !
     ! Spectral parameters ------------------------------------------------ *
     !                                                 Module W3GDATMD SGRD
     !
     IF ( WRITE ) THEN
       WRITE (ndsm)                                                  &
            mapwn, mapth, dth, th, esin, ecos, es2, esc, ec2,        &
            xfr, fr1, sig, sig2, dsip, dsii, dden, dden2, fte,       &
            ftf, ftwn, fttr, ftwl, facti1, facti2, fachfa, fachfe
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                                &
            'MAPWN, MAPTH, DTH, TH, ESIN, ECOS, ES2, ESC, EC2,       &
            XFR, FR1, SIG, SIG2, DSIP, DSII, DDEN, DDEN2, FTE,       &
            FTF, FTWN, FTTR, FTWL, FACTI1, FACTI2, FACHFA, FACHFE:', &
            mapwn, mapth, dth, th, esin, ecos, es2, esc, ec2,        &
            xfr, fr1, sig, sig2, dsip, dsii, dden, dden2, fte,       &
            ftf, ftwn, fttr, ftwl, facti1, facti2, fachfa, fachfe
 #endif
     ELSE
       IF (.NOT.sinit) CALL w3dims ( igrd, nk, nth, ndse, ndst )
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                       &
            mapwn, mapth, dth, th, esin, ecos, es2, esc, ec2,        &
            xfr, fr1, sig, sig2, dsip, dsii, dden, dden2, fte,       &
            ftf, ftwn, fttr, ftwl, facti1, facti2, fachfa, fachfe
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9030) (mapwn(i),i=1,8), (mapth(i),i=1,8), dth*rade, &
          (th(i)*rade,i=1,4), (esin(i),i=1,4), (ecos(i),i=1,4),      &
          xfr, sig(1)*tpiinv, sig(nk)*tpiinv, fte, ftf, ftwn, fttr,  &
          ftwl, facti1, facti2, fachfa, fachfe
 #endif
     !
     !
     ! Output flags for 3D parameters ------------------------------------- *
     !                                                 Module W3GDATMD
     IF ( WRITE ) THEN
       WRITE (ndsm)                                                &
            e3df, p2msf, us3df,usspf, ussp_wn
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                              &
            'E3DF, P2MSF, US3DF,USSPF, USSP_WN:',                  &
            e3df, p2msf, us3df,usspf, ussp_wn
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                     &
            e3df, p2msf, us3df,usspf, ussp_wn
     END IF
     IF ( inxout .EQ. 'GRID' ) THEN
       CLOSE (ndsm)
       RETURN
     END IF
     !
     ! Parameters for output boundary points ------------------------------ *
     !                                                 Module W3ODATMD OUT5
     !
     IF ( WRITE ) THEN
       WRITE (ndsm)                                               &
            xbpo, ybpo, rdbpo, ipbpo, isbpo
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                              &
            'XBPO, YBPO, RDBPO, IPBPO, ISBPO:',                   &
            xbpo, ybpo, rdbpo, ipbpo, isbpo
 #endif
     ELSE
       CALL w3dmo5 ( igrd, ndse, ndst, 2 )
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                    &
            xbpo, ybpo, rdbpo, ipbpo, isbpo
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9020)
     DO i=1, nfbpo
       WRITE (ndst,9021) i
       DO j=nbo(i-1)+1,nbo(i)
         WRITE (ndst,9022) j-nbo(i-1), (ipbpo(j,k),k=1,4),        &
              (rdbpo(j,k),k=1,4)
       END DO
       WRITE (ndst,9023) (isbpo(j),j=nbo2(i-1)+1,nbo2(i))
     END DO
 #endif
     !
     ! Parameters for spectral partitioning  ------------------------------ *
     !                                                 Module W3ODATMD OUT6
     !
     IF ( WRITE ) THEN
       WRITE (ndsm)                                               &
            ihmax, hspmin, wsmult, wscut, flcomb, noswll,         &
            ptmeth, ptfcut
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                             &
            'IHMAX, HSPMIN, WSMULT, WSCUT, FLCOMB, NOSWLL,        &
            PTMETH, PTFCUT:',                                     &
            ihmax, hspmin, wsmult, wscut, flcomb, noswll,         &
            ptmeth, ptfcut
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                    &
            ihmax, hspmin, wsmult, wscut, flcomb, noswll,         &
            ptmeth, ptfcut
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9025) ihmax, hspmin, wsmult, wscut, flcomb, noswll
 #endif
     !
     ! Numerical parameters ----------------------------------------------- *
     !                                                 Module W3GDATMD NPAR
     !
     IF ( WRITE ) THEN
       WRITE (ndsm)                                               &
            facp, xrel, xflt, fxfm, fxpm, xft, xfc, facsd, fhmax, &
            ffacberg, delab, fwtable
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                              &
            'FACP, XREL, XFLT, FXFM, FXPM, XFT, XFC, FACSD, FHMAX, &
            FFACBERG, DELAB, FWTABLE:',                           &
            facp, xrel, xflt, fxfm, fxpm, xft, xfc, facsd, fhmax, &
            ffacberg, delab, fwtable
 #endif
 #ifdef W3_RWND
       WRITE (ndsm)                                               &
            rwindc
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                             &
            'RWINDC:',                                            &
            rwindc
 #endif
 #endif
 #ifdef W3_WCOR
       WRITE (ndsm)                                               &
            wwcor
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                             &
            'WWCOR:',                                             &
            wwcor
 #endif
 #endif
 #ifdef W3_REF1
       WRITE (ndsm)                                               &
            rref, refpars, reflc, refld
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                             &
            'RREF, REFPARS, REFLC, REFLD:',                       &
            rref, refpars, reflc, refld
 #endif
 #endif
 #ifdef W3_IG1
       WRITE   (ndsm)                                             &
            igpars(1:12)
 #ifdef W3_ASCII
       WRITE   (ndsa,*)                                           &
            'IGPARS(1:12):',                                      &
            igpars(1:12)
 #endif
 #endif
 #ifdef W3_IC2
       WRITE   (ndsm)                                             &
            ic2pars(1:8)
 #ifdef W3_ASCII
       WRITE   (ndsa,*)                                           &
            'IC2PARS(1:8):',                                      &
            ic2pars(1:8)
 #endif
 #endif
 #ifdef W3_IC3
       WRITE   (ndsm)                                             &
            ic3pars
 #ifdef W3_ASCII
       WRITE   (ndsa,*)                                           &
            'IC3PARS:',                                           &
            ic3pars
 #endif
 #endif
 #ifdef W3_IC4
       WRITE   (ndsm)                                             &
            ic4pars,ic4_ki,ic4_fc,ic4_cn,ic4_fmin,ic4_kibk
 #ifdef W3_ASCII
       WRITE   (ndsa,*)                                           &
            'IC4PARS,IC4_KI,IC4_FC,IC4_CN,IC4_FMIN,IC4_KIBK:',    &
            ic4pars,ic4_ki,ic4_fc,ic4_cn,ic4_fmin,ic4_kibk
 #endif
 #endif
 #ifdef W3_IC5
       WRITE   (ndsm)                                             &
            ic5pars
 #ifdef W3_ASCII
       WRITE   (ndsa,*)                                           &
            'IC5PARS:',                                           &
            ic5pars
 #endif
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                    &
            facp, xrel, xflt, fxfm, fxpm, xft, xfc, facsd, fhmax, &
            ffacberg, delab, fwtable
 #ifdef W3_RWND
       READ  (ndsm,END=801,ERR=802,IOSTAT=IERR)                                               &
            rwindc
 #endif
 #ifdef W3_WCOR
       READ  (ndsm,END=801,ERR=802,IOSTAT=IERR)                                               &
            wwcor
 #endif
 #ifdef W3_REF1
       READ  (ndsm,END=801,ERR=802,IOSTAT=IERR)                                               &
            rref, refpars, reflc, refld
 #endif
 #ifdef W3_IG1
       READ   (ndsm,END=801,ERR=802,IOSTAT=IERR)                                              &
            igpars(1:12)
 #endif
 #ifdef W3_IC2
       READ   (ndsm,END=801,ERR=802,IOSTAT=IERR)                                              &
            ic2pars(1:8)
 #endif
 #ifdef W3_IC3
       READ   (ndsm,END=801,ERR=802,IOSTAT=IERR)                                              &
            ic3pars
 #endif
 #ifdef W3_IC4
       READ   (ndsm,END=801,ERR=802,IOSTAT=IERR)                                              &
            ic4pars,ic4_ki,ic4_fc,ic4_cn,ic4_fmin,ic4_kibk
 #endif
 #ifdef W3_IC5
       READ   (ndsm,END=801,ERR=802,IOSTAT=IERR)                                              &
            ic5pars
 #endif
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9040) facp, xrel, xflt, fxfm, fxpm, xft, xfc,    &
          facsd, fhmax
 #endif
     !
     ! Source term parameters --------------------------------------------- *
     !                                                 Module W3GDATMD SFLP
     !                                                 Module W3GDATMD SLNP
     !                                                 Module W3GDATMD SRCP
     !                                                 Module W3GDATMD SNLP
     !                                                 Module W3GDATMD SBTP
     !
 #ifdef W3_FLX2
     IF ( WRITE ) THEN
       WRITE (ndsm)                            nittin, cinxsi
 #ifdef W3_ASCII
       WRITE (ndsa,*)'                            NITTIN, CINXSI:', &
                                               nittin, cinxsi
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) NITTIN, cinxsi
     END IF
     IF ( fltest ) WRITE (ndst,9048) nittin, cinxsi
 #endif
     !
 #ifdef W3_FLX3
     IF ( WRITE ) THEN
       WRITE (ndsm)                                          &
            nittin, cinxsi, cd_max, cap_id
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                          &
            'NITTIN, CINXSI, CD_MAX, CAP_ID:',                &
            nittin, cinxsi, cd_max, cap_id
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
            nittin, cinxsi, cd_max, cap_id
     END IF
     IF ( fltest ) WRITE (ndst,9048) nittin, cap_id, cinxsi, cd_max
 #endif
     !
 #ifdef W3_FLX4
     IF ( WRITE ) THEN
       WRITE (ndsm)                            flx4a0
 #ifdef W3_ASCII
       WRITE (ndsa,*)'                            FLX4A0:',   &
                                               flx4a0
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) flx4a0
     END IF
 #endif
     !
     !
 #ifdef W3_LN1
     IF ( WRITE ) THEN
       WRITE (ndsm)                            slnc1, fspm, fshf
 #ifdef W3_ASCII
       WRITE (ndsa,*)'                            SLNC1, FSPM, FSHF:', &
                                               slnc1, fspm, fshf
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) SLNC1, FSPM, fshf
     END IF
     IF ( fltest ) WRITE (ndst,9049) slnc1, fspm, fshf
 #endif
     !
 #ifdef W3_ST1
     IF ( WRITE ) THEN
       WRITE (ndsm)                            sinc1, sdsc1
 #ifdef W3_ASCII
       WRITE (ndsa,*)'                            SINC1, SDSC1:', &
                                               sinc1, sdsc1
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) SINC1, sdsc1
     END IF
     IF ( fltest ) WRITE (ndst,9050) sinc1, sdsc1
 #endif
     !
 #ifdef W3_ST2
     IF ( WRITE ) THEN
       WRITE (ndsm)                                             &
            zwind, fswell,                                      &
            shstab, ofstab, ccng, ccps, ffng, ffps,             &
            cdsa0, cdsa1, cdsa2, sdsaln,                        &
            cdsb0, cdsb1, cdsb2, cdsb3, fpimin, xfh, xf1, xf2
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                           &
            'ZWIND, FSWELL,                                    &
            SHSTAB, OFSTAB, CCNG, CCPS, FFNG, FFPS,             &
            CDSA0, CDSA1, CDSA2, SDSALN,                        &
            CDSB0, CDSB1, CDSB2, CDSB3, FPIMIN, XFH, XF1, XF2:',&
            zwind, fswell,                                      &
            shstab, ofstab, ccng, ccps, ffng, ffps,             &
            cdsa0, cdsa1, cdsa2, sdsaln,                        &
            cdsb0, cdsb1, cdsb2, cdsb3, fpimin, xfh, xf1, xf2
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                  &
            zwind, fswell,                                      &
            shstab, ofstab, ccng, ccps, ffng, ffps,             &
            cdsa0, cdsa1, cdsa2, sdsaln,                        &
            cdsb0, cdsb1, cdsb2, cdsb3, fpimin, xfh, xf1, xf2
       IF ( .NOT. flinp ) CALL inptab
       flinp  = .true.
     END IF
     IF ( fltest ) WRITE (ndst,9050)                            &
          zwind, fswell, cdsa0, cdsa1, cdsa2,                   &
          sdsaln, cdsb0, cdsb1, cdsb2, cdsb3, fpimin, xfh, xf1, &
          xf2, shstab, ofstab, ccng, ccps, ffng, ffps
 #endif
     !
 #ifdef W3_ST3
     IF ( WRITE ) THEN
       WRITE (ndsm)                                             &
            zzwnd, aalpha, zz0max, bbeta, ssinthp, zzalp,       &
            sswellf, ssdsc1, wwnmeanp, wwnmeanptail, sstxftf,   &
            sstxftftail, sstxftwn,                              &
            ddelta1, ddelta2, sstxftf, sstxftwn,                &
            ffxpm, ffxfm
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                           &
            'ZZWND, AALPHA, ZZ0MAX, BBETA, SSINTHP, ZZALP,      &
            SSWELLF, SSDSC1, WWNMEANP, WWNMEANPTAIL, SSTXFTF,   &
            SSTXFTFTAIL, SSTXFTWN,                              &
            DDELTA1, DDELTA2, SSTXFTF, SSTXFTWN,                &
            FFXPM, FFXFM:',                                     &
            zzwnd, aalpha, zz0max, bbeta, ssinthp, zzalp,       &
            sswellf, ssdsc1, wwnmeanp, wwnmeanptail, sstxftf,   &
            sstxftftail, sstxftwn,                              &
            ddelta1, ddelta2, sstxftf, sstxftwn,                &
            ffxpm, ffxfm
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                  &
            zzwnd, aalpha, zz0max, bbeta, ssinthp, zzalp,       &
            sswellf, ssdsc1, wwnmeanp, wwnmeanptail, sstxftf,   &
            sstxftftail, sstxftwn,                              &
            ddelta1, ddelta2, sstxftf, sstxftwn,                &
            ffxpm, ffxfm
       IF ( .NOT. flinp ) THEN
         CALL insin3
         flinp  = .true.
       END IF
     END IF
 #endif
     !
 #ifdef W3_ST4
     IF ( WRITE ) THEN
       CALL insin4(.true.)
       WRITE (ndsm)                                           &
            zzwnd, aalpha, zz0max, bbeta, ssinthp, zzalp,     &
            ttauwshelter, sswellfpar, sswellf, ssinbr,        &
            zz0rat, ssdsc,                                    &
            ssdsiso, ssdsbr, ssdsbt, ssdsbm, ssdsp,           &
            ssdscos, ssdsdth, wwnmeanp, wwnmeanptail,sstxftf, &
            sstxftftail, sstxftwn, sstxftf, sstxftwn,         &
            ssdsbrf1, ssdsbrf2, ssdsbrfdf,ssdsbck, ssdsabk,   &
            ssdspbk, ssdsbint, ffxpm, ffxfm, ffxfa,           &
            ssdshck,                                          &
            iktab, dcki, qbi, satindices, satweights,         &
            dikcumul, cumulw, sintailpar, capchnk
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                         &
            'ZZWND, AALPHA, ZZ0MAX, BBETA, SSINTHP, ZZALP,    &
            TTAUWSHELTER, SSWELLFPAR, SSWELLF, SSINBR,        &
            ZZ0RAT, SSDSC,                                    &
            SSDSISO, SSDSBR, SSDSBT, SSDSBM, SSDSP,           &
            SSDSCOS, SSDSDTH, WWNMEANP, WWNMEANPTAIL,SSTXFTF, &
            SSTXFTFTAIL, SSTXFTWN, SSTXFTF, SSTXFTWN,         &
            SSDSBRF1, SSDSBRF2, SSDSBRFDF,SSDSBCK, SSDSABK,   &
            SSDSPBK, SSDSBINT, FFXPM, FFXFM, FFXFA,           &
            SSDSHCK,                                          &
            IKTAB, DCKI, QBI, SATINDICES, SATWEIGHTS,         &
            DIKCUMUL, CUMULW, SINTAILPAR, CAPCHNK:',          &
            zzwnd, aalpha, zz0max, bbeta, ssinthp, zzalp,     &
            ttauwshelter, sswellfpar, sswellf, ssinbr,        &
            zz0rat, ssdsc,                                    &
            ssdsiso, ssdsbr, ssdsbt, ssdsbm, ssdsp,           &
            ssdscos, ssdsdth, wwnmeanp, wwnmeanptail,sstxftf, &
            sstxftftail, sstxftwn, sstxftf, sstxftwn,         &
            ssdsbrf1, ssdsbrf2, ssdsbrfdf,ssdsbck, ssdsabk,   &
            ssdspbk, ssdsbint, ffxpm, ffxfm, ffxfa,           &
            ssdshck,                                          &
            iktab, dcki, qbi, satindices, satweights,         &
            dikcumul, cumulw, sintailpar, capchnk
 #endif
       IF (sintailpar(1).GT.0.5) THEN
         WRITE (ndsm) delust, deltail, deltauw, delu, delalp, &
                      taut, tauhft
         IF (ttauwshelter.GT.0) WRITE (ndsm) tauhft2
 #ifdef W3_ASCII
         WRITE (ndsa,*) 'DELUST, DELTAIL, DELTAUW, DELU, DELALP,&
                      TAUT, TAUHFT:',                         &
                      delust, deltail, deltauw, delu, delalp, &
                      taut, tauhft
         IF (ttauwshelter.GT.0) WRITE (ndsa,*) 'TAUHFT2:', tauhft2
 #endif
       END IF
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                &
            zzwnd, aalpha, zz0max, bbeta, ssinthp, zzalp,     &
            ttauwshelter, sswellfpar, sswellf, ssinbr,        &
            zz0rat, ssdsc,                                    &
            ssdsiso, ssdsbr, ssdsbt, ssdsbm, ssdsp,           &
            ssdscos, ssdsdth, wwnmeanp, wwnmeanptail,sstxftf, &
            sstxftftail, sstxftwn, sstxftf, sstxftwn,         &
            ssdsbrf1, ssdsbrf2, ssdsbrfdf,ssdsbck, ssdsabk,   &
            ssdspbk, ssdsbint, ffxpm, ffxfm, ffxfa,           &
            ssdshck,                                          &
            iktab, dcki, qbi, satindices, satweights,         &
            dikcumul, cumulw, sintailpar, capchnk
       IF (sintailpar(1).GT.0.5) THEN
         CALL insin4(.false.)
         READ (ndsm,END=801,ERR=802,IOSTAT=IERR)              &
              delust, deltail, deltauw, delu, delalp,  &
              taut, tauhft
         IF (ttauwshelter.GT.0) READ(ndsm,END=801,ERR=802,IOSTAT=IERR) tauhft2
       END IF
     END IF
 #endif
     !
 #ifdef W3_ST6
     IF ( WRITE ) THEN
       WRITE (ndsm) sin6a0, sds6et, sds6a1, sds6a2,           &
            sds6p1, sds6p2, swl6s6, swl6b1, swl6cstb1,        &
            sin6ws, sin6fc
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'SIN6A0, SDS6ET, SDS6A1, SDS6A2,        &
            SDS6P1, SDS6P2, SWL6S6, SWL6B1, SWL6CSTB1,        &
            SIN6WS, SIN6FC:',                                 &
                    sin6a0, sds6et, sds6a1, sds6a2,           &
            sds6p1, sds6p2, swl6s6, swl6b1, swl6cstb1,        &
            sin6ws, sin6fc
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                &
            sin6a0, sds6et, sds6a1, sds6a2,                   &
            sds6p1, sds6p2, swl6s6, swl6b1, swl6cstb1,        &
            sin6ws, sin6fc
     END IF
 #endif
     !
     ! ... Nonlinear interactions
     !
 #ifdef W3_NL1
     IF ( WRITE ) THEN
       WRITE (ndsm)                                         &
            snlc1, lam, kdcon, kdmn, snls1, snls2, snls3,   &
            iqtpe, nltail, gqnf1, gqnt1,                    &
            gqnq_om2, gqthrsat, gqthrcou, gqamp
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                       &
            'SNLC1, LAM, KDCON, KDMN, SNLS1, SNLS2, SNLS3,  &
            IQTPE, NLTAIL, GQNF1, GQNT1,                    &
            GQNQ_OM2, GQTHRSAT, GQTHRCOU, GQAMP:',          &
            snlc1, lam, kdcon, kdmn, snls1, snls2, snls3,   &
            iqtpe, nltail, gqnf1, gqnt1,                    &
            gqnq_om2, gqthrsat, gqthrcou, gqamp
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)              &
            snlc1, lam, kdcon, kdmn, snls1, snls2, snls3,   &
            iqtpe, nltail, gqnf1, gqnt1,                    &
            gqnq_om2, gqthrsat, gqthrcou, gqamp
     END IF
     IF ( fltest ) WRITE (ndst,9051) snlc1, lam,            &
          kdcon, kdmn, snls1, snls2, snls3,                 &
          iqtpe, nltail, gqnf1, gqnt1, gqnq_om2,            &
          gqthrsat, gqthrcou, gqamp
 #endif
     !
 #ifdef W3_NL2
     IF ( WRITE ) THEN
       WRITE (ndsm) iqtpe, nltail, ndpths
       WRITE (ndsm) dpthnl
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'IQTPE, NLTAIL, NDPTHS:',             &
                    iqtpe, nltail, ndpths
       WRITE (ndsa,*) 'DPTHNL:',                            &
                    dpthnl
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)              &
            iqtpe, nltail, ndpths
       ALLOCATE ( mpars(igrd)%SNLPS%DPTHNL(ndpths) )
       dpthnl => mpars(igrd)%SNLPS%DPTHNL
       pinit  = .true.
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) dpthnl
     END IF
     IF ( fltest ) WRITE (ndst,9051) iqtpe, nltail, ndpths
     IF ( fltest ) WRITE (ndst,9151) dpthnl
 #endif
     !
 #ifdef W3_NL3
     IF ( WRITE ) THEN
       WRITE (ndsm) snlnq, snlmsc, snlnsc, snlsfd, snlsfs
       WRITE (ndsm) snll(1:snlnq), snlm(1:snlnq),           &
            snlt(1:snlnq), snlcd(1:snlnq),                  &
            snlcs(1:snlnq)
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'SNLNQ, SNLMSC, SNLNSC, SNLSFD, SNLSFS:',&
                    snlnq, snlmsc, snlnsc, snlsfd, snlsfs
       WRITE (ndsa,*) 'SNLL(1:SNLNQ), SNLM(1:SNLNQ),           &
            SNLT(1:SNLNQ), SNLCD(1:SNLNQ),                  &
            SNLCS(1:SNLNQ):',                               &
                    snll(1:snlnq), snlm(1:snlnq),           &
            snlt(1:snlnq), snlcd(1:snlnq),                  &
            snlcs(1:snlnq)
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)              &
            snlnq, snlmsc, snlnsc, snlsfd, snlsfs
       ALLOCATE ( mpars(igrd)%SNLPS%SNLL(snlnq),            &
            mpars(igrd)%SNLPS%SNLM(snlnq),                  &
            mpars(igrd)%SNLPS%SNLT(snlnq),                  &
            mpars(igrd)%SNLPS%SNLCD(snlnq),                 &
            mpars(igrd)%SNLPS%SNLCS(snlnq) )
       snll   => mpars(igrd)%SNLPS%SNLL
       snlm   => mpars(igrd)%SNLPS%SNLM
       snlt   => mpars(igrd)%SNLPS%SNLT
       snlcd  => mpars(igrd)%SNLPS%SNLCD
       snlcs  => mpars(igrd)%SNLPS%SNLCS
       pinit  = .true.
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)              &
            snll, snlm, snlt, snlcd, snlcs
     END IF
     IF ( fltest ) WRITE (ndst,9051) snlnq, snlmsc, snlnsc, &
          snlsfd, snlsfs
     IF ( fltest ) THEN
       DO i=1, snlnq
         WRITE (ndst,9151) snll(i), snlm(i), snlt(i),       &
              snlcd(i), snlcs(i)
       END DO
     END IF
 #endif
     !
 #ifdef W3_NL4
     IF ( WRITE ) THEN
       WRITE (ndsm) itsa, ialt
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'ITSA, IALT:',                        &
                    itsa, ialt
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)              &
            itsa, ialt
     END IF
     IF ( fltest ) WRITE (ndst,9051) itsa, ialt
 #endif
     !
     ! (QL: INXOUT = Grid option ?)
 #ifdef W3_NL5
     IF (write) THEN
       CALL insnl5
       WRITE (ndsm) qr5dpt, qr5oml, qi5dis, qi5kev,          &
            qi5nnz, qi5ipl, qi5pmx
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'QR5DPT, QR5OML, QI5DIS, QI5KEV,       &
            QI5NNZ, QI5IPL, QI5PMX:',                        &
                    qr5dpt, qr5oml, qi5dis, qi5kev,          &
            qi5nnz, qi5ipl, qi5pmx
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
            qr5dpt, qr5oml, qi5dis, qi5kev,                  &
            qi5nnz, qi5ipl, qi5pmx
     END IF
     IF ( fltest ) WRITE (ndst,9051) qr5dpt, qr5oml, qi5dis, &
          qi5kev, qi5nnz, qi5ipl,                            &
          qi5pmx
 #endif
     !
 #ifdef W3_NLS
     IF ( WRITE ) THEN
       WRITE (ndsm)                                          &
            cnlsa, cnlsc, cnlsfm, cnlsc1, cnlsc2, cnlsc3
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                        &
            'CNLSA, CNLSC, CNLSFM, CNLSC1, CNLSC2, CNLSC3:', &
            cnlsa, cnlsc, cnlsfm, cnlsc1, cnlsc2, cnlsc3
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
            cnlsa, cnlsc, cnlsfm, cnlsc1, cnlsc2, cnlsc3
     END IF
     IF ( fltest ) WRITE (ndst,9251)                         &
          cnlsa, cnlsc, cnlsfm, cnlsc1, cnlsc2, cnlsc3
 #endif
     !
 #ifdef W3_NL1
     IF ( .NOT. WRITE ) THEN
       IF (iqtpe.GT.0) THEN
         CALL insnl1 ( igrd )
       ELSE
         CALL insnlgqm
       END IF
     END IF
 #endif
 #ifdef W3_NL3
     IF ( .NOT. WRITE ) CALL insnl3
 #endif
 #ifdef W3_NLS
     IF ( .NOT. WRITE ) CALL insnls
 #endif
     !
     ! Layered barriers needed for file management in xnl_init
     !
 #ifdef W3_MPI
     IF ( flsnl2 .AND. .NOT.WRITE ) THEN
       DO ip=1, iaproc-1
         CALL mpi_barrier (  mpi_comm_wave, ierr_mpi )
       END DO
     END IF
 #endif
 #ifdef W3_NL2
     IF ( .NOT. WRITE ) CALL insnl2
 #endif
 #ifdef W3_MPI
     IF ( flsnl2 .AND. .NOT.WRITE ) THEN
       DO ip=iaproc, naproc-1
         CALL mpi_barrier (  mpi_comm_wave, ierr_mpi )
       END DO
     END IF
 #endif
     !
     ! ... Bottom friction ...
     !
 #ifdef W3_BT1
     IF ( WRITE ) THEN
       WRITE (ndsm)                            sbtc1
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'SBTC1:',                sbtc1
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) sbtc1
     END IF
     IF ( fltest ) WRITE (ndst,9052) sbtc1
 #endif
     !
     !
 #ifdef W3_BT4
     IF ( WRITE ) THEN
       WRITE (ndsm)                                          &
            sbtcx, sed_d50, sed_psic
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                        &
            'SBTCX, SED_D50, SED_PSIC:',                     &
            sbtcx, sed_d50, sed_psic
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)               &
            sbtcx, sed_d50, sed_psic
     END IF
 #endif
     !
     ! ... Depth induced breaking ...
     !
     call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 8')
 #ifdef W3_DB1
     IF ( WRITE ) THEN
       WRITE (ndsm)                                            &
            sdbc1, sdbc2, fdonly
 #ifdef W3_ASCII
       WRITE (ndsa,*)                                          &
            'SDBC1, SDBC2, FDONLY:',                           &
            sdbc1, sdbc2, fdonly
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                 &
            sdbc1, sdbc2, fdonly
     END IF
     !
     IF ( fltest ) WRITE (ndst,9053) sdbc1, sdbc2, fdonly
 #endif
 #ifdef W3_UOST
     IF ( WRITE ) THEN
       WRITE (ndsm) uostfilelocal, uostfileshadow,             &
            uostfactorlocal, uostfactorshadow
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'UOSTFILELOCAL, UOSTFILESHADOW,          &
            UOSTFACTORLOCAL, UOSTFACTORSHADOW:',               &
                      uostfilelocal, uostfileshadow,           &
            uostfactorlocal, uostfactorshadow
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                 &
            uostfilelocal, uostfileshadow,                     &
            uostfactorlocal, uostfactorshadow
       CALL uost_initgrid(igrd, uostfilelocal, uostfileshadow, &
            uostfactorlocal, uostfactorshadow)
 #endif
 #ifdef W3_UOST
     END IF
 #endif
     !
 #ifdef W3_IS1
     IF ( WRITE ) THEN
       WRITE (ndsm)                            is1c1, is1c2
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'IS1C1, IS1C2:',         is1c1, is1c2
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) IS1C1, is1c2
     END IF
 #endif
     !
 #ifdef W3_IS2
     IF ( WRITE ) THEN
       WRITE (ndsm)                            is2pars
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'IS3PARS:',              is2pars
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) is2pars
       IF ( .NOT. flis ) THEN
         CALL insis2
         flis  = .true.
       END IF
     END IF
 #endif
     !
     ! Propagation scheme ------------------------------------------------- *
     !                                                 Module W3GDATMD PROP
     !
 #ifdef W3_PR2
     IF ( WRITE ) THEN
       WRITE (ndsm) dtme, clatmn
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'DTME, CLATMN:', dtme, clatmn
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                &
            dtme, clatmn
     END IF
     !
     IF ( fltest ) WRITE (ndst,9060) dtme, clatmn
 #endif
     !
 #ifdef W3_PR3
     IF ( WRITE ) THEN
       WRITE (ndsm) wdcg, wdth
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'WDCG, WDTH:', wdcg, wdth
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                &
            wdcg, wdth
     END IF
     !
     IF ( fltest ) WRITE (ndst,9060) wdcg, wdth
 #endif
     !
 #ifdef W3_SMC
     IF ( WRITE ) THEN
       WRITE(ndsm) dtms, refran, funo3, fverg, fswnd, arctc
 #ifdef W3_ASCII
       WRITE(ndsa,*) 'DTMS, Refran, FUNO3, FVERG, FSWND, ARCTC:', &
                   dtms, refran, funo3, fverg, fswnd, arctc
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR)                &
            dtms, refran, funo3, fverg, fswnd, arctc
     END IF
     !
     IF ( fltest ) WRITE (ndst,9260) dtms, refran
 #endif
     !
 #ifdef W3_FLD1
     IF ( WRITE ) THEN
       WRITE (ndsm)  tail_id, tail_lev, tail_tran1, tail_tran2
 #ifdef W3_ASCII
       WRITE (ndsa,*)  'TAIL_ID, TAIL_LEV, TAIL_TRAN1, TAIL_TRAN2:', &
                     tail_id, tail_lev, tail_tran1, tail_tran2
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
            tail_id, tail_lev, tail_tran1, tail_tran2
     END IF
 #endif
 #ifdef W3_FLD2
     IF ( WRITE ) THEN
       WRITE (ndsm) tail_id, tail_lev, tail_tran1, tail_tran2
 #ifdef W3_ASCII
       WRITE (ndsa,*) 'TAIL_ID, TAIL_LEV, TAIL_TRAN1, TAIL_TRAN2:', &
                    tail_id, tail_lev, tail_tran1, tail_tran2
 #endif
     ELSE
       READ (ndsm,END=801,ERR=802,IOSTAT=IERR) &
            tail_id, tail_lev, tail_tran1, tail_tran2
     END IF
 #endif
     !
     ! Interpolation tables ( fill locally ) ----------------------------- *
     !                                                      Module W3DISPMD
     !
     IF ( .NOT.WRITE .AND. .NOT.fldisp ) THEN
 #ifdef W3_T
       WRITE (ndst,9070)
 #endif
       CALL distab
       fldisp = .true.
     END IF
     !
     CLOSE ( ndsm )
 #ifdef W3_ASCII
     IF ( WRITE ) THEN
       CLOSE ( ndsa )
     END IF
 #endif
     call print_memcheck(memunit, 'memcheck_____:'//' WIOGR SECTION 9')
     !
     RETURN
     !
     ! Escape locations read errors --------------------------------------- *
     !
 800 CONTINUE
     IF ( iaproc .EQ. naperr ) WRITE (ndse,1000) filext(:iext), ierr
     CALL extcde ( 50 )
     !
 801 CONTINUE
     IF ( iaproc .EQ. naperr ) WRITE (ndse,1001) filext(:iext)
     CALL extcde ( 51 )
     !
 802 CONTINUE
     IF ( iaproc .EQ. naperr ) WRITE (ndse,1002) filext(:iext), ierr, &
          message
     CALL extcde ( 52 )
     !
     ! Formats
     !
 900 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     ILEGAL INXOUT VALUE: ',a/)
 901 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     ILEGAL IDSTR, READ : ',a/                     &
          '                  CHECK : ',a/)
 902 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     ILEGAL VERGRD, READ : ',a/                    &
          '                   CHECK : ',a/)
 904 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     ILEGAL NFBPO READ : ',i8/                     &
          '                 CHECK : ',i8/)
 905 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     UNEXPECTED SOURCE TERM IDENTIFIER',i2/        &
          '          IN mod_def.',a,' FILE : ',a/             &
          '    EXPECTED FROM switch FILE : ',a,/              &
          5(a,/) /)
     !               '     CHECK CONSISTENCY OF SWITCHES IN PROGRAMS'/)
 906 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     UNEXPECTED PROPAGATION SCHEME IDENTIFIER'/    &
          '                IN FILE :',a/                      &
          '               EXPECTED :',a/                      &
          '     CHECK CONSISTENCY OF SWITCHES IN PROGRAMS'/)
 907 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     UNEXPECTED GSE ALEVIATION IDENTIFIER'/        &
          '                IN FILE :',a/                      &
          '               EXPECTED :',a/                      &
          , 5(a,/) /)
     !               '     CHECK CONSISTENCY OF SWITCHES IN PROGRAMS'/)
 908 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR :'/         &
          '     UNEXPECTED FLUX PARAMETERIZATION IDENTIFIER'/ &
          '         IN mod_def.',a,' :',a/                    &
          '               EXPECTED :',a/                      &
          , 5(a,/) /)
     !               '     CHECK CONSISTENCY OF SWITCHES IN PROGRAMS'/)
     !
 1000 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR : '/       &
          '     ERROR IN OPENING mod_def.',a,' FILE'/         &
          '     IOSTAT =',i5/)
 1001 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR : '/       &
          '     PREMATURE END OF mod_def.',a,' FILE'/)
 1002 FORMAT (/' *** WAVEWATCH III ERROR IN W3IOGR : '/,      &
          '     ERROR IN READING FROM mod_def.',a,' FILE'/    &
          '     IOSTAT =',i5,                                 &
          5(a,/) /)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3IOGR : INXOUT = ',a,', WRITE = ',l1,   &
          ', UNIT =',i3,', IGRD =',i3,', FEXT = ',a)
 9001 FORMAT (' TEST W3IOGR : TEST PARAMETERS :'/             &
          '       IDSTR : ',a/                                &
          '      VERGRD : ',a/                                &
          '    NX/Y/SEA : ',3i10/                             &
          '      NTH,NK : ',2i10/                             &
          '         NBI : ',i10/                              &
          '       NFBPO : ',2i10/                             &
          '      GNAME  : ',a/                                &
          '      FNAME0 : ',a/                                &
          '      FNAME1 : ',a/                                &
          '      FNAME2 : ',a/                                &
          '      FNAME3 : ',a/                                &
          '      FNAME4 : ',a/                                &
          '      FNAME5 : ',a/                                &
          '      FNAME6 : ',a/                                &
          '      FNAMEP : ',a/                                &
          '      FNAMEG : ',a/                                &
          '      FNAMEF : ',a/                                &
          '      FNAMEI : ',a)
 9002 FORMAT ('      NBO    : ',10i5)
 9003 FORMAT ('      NBO2   : ',10i5)
     !
 9010 FORMAT (' TEST W3IOGR : MODULE W3GDATMD GRID'/          &
          '      GTYPE  : ',i9/                               &
          '      FLAGLL : ',l9/                               &
          '      ICLOSE : ',i9/                               &
          '      SX, SY : ',2e10.3/                           &
          '      X0, Y0 : ',2e10.3/                           &
          '      TRFLAG : ',i9)
 9011 FORMAT ('      LOWER LEFT PART OF ',a)
 9012 FORMAT ('     ',4x,30i2)
 9013 FORMAT ('     ',12i6)
 9014 FORMAT ('     ',12f6.2)
 9015 FORMAT ('      STEPS  : ',4f8.1/                        &
          '      DEPTH  : ',f8.1,f10.3/                       &
          '      FICE0/N: ',f9.2,f8.2/                        &
          '      FICEL  : ',f9.1 /                            &
          '      PFMOVE : ',f9.2 /                            &
          '      STEXU  : ',f9.2 /                            &
          '      STEYU  : ',f9.2 /                            &
          '      STEDU  : ',f9.2)
     !
 9016 FORMAT ('      FLAGS  : ',8l2)
 9017 FORMAT ('      CLATS   : ',3f8.3,' ...'/                &
          '      CLATIS  : ',3f8.3,' ...'/                    &
          '      CTHG0S  : ',3e11.3,' ...')
     !
 9020 FORMAT (' TEST W3IOGR : MODULE W3ODATMD OUT5')
 9021 FORMAT ('      INTERPOLATION DATA : FILE ',i1)
 9022 FORMAT ('          ',i5,2x,4i4,2x,4f5.2)
 9023 FORMAT ('          ',10i7)
 9025 FORMAT (' TEST W3IOGR : MODULE W3ODATMD OUT6'/          &
          '      PARTITIONING DATA :',i5,3e10.3,l4,2x,i4)
     !
 9030 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SGRD'/          &
          '      MAPWN  : ',8i4,' ...'/                       &
          '      MAPTH  : ',8i4,' ...'/                       &
          '      DTH    : ',f6.1/                             &
          '      TH     : ',4f6.1,' ...'/                     &
          '      ESIN   : ',4f6.3,' ...'/                     &
          '      ECOS   : ',4f6.3,' ...'/                     &
          '      XFR    : ',f6.3/                             &
          '      FR     : ',f6.3,' ...',f6.3/                 &
          '      FACs   : ',6e10.3/                           &
          '               ',3e10.3)
     !
 9040 FORMAT (' TEST W3IOGR : MODULE W3GDATMD NPAR'/          &
          '      FACs   : ',5e10.3/                           &
          '               ',4e10.3)
 #endif
     !
 #ifdef W3_FLX2
 9048 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SFLP'/          &
          '      FLUXES : ',i5,3x,e10.3)
 #endif
 #ifdef W3_FLX3
 9048 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SFLP'/          &
          '      FLUXES : ',2i5,3x,2e10.3)
 #endif
     !
 #ifdef W3_LN1
 9049 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SLNP'/          &
          '      INPUT  : ',3e10.3)
 #endif
     !
 #ifdef W3_ST1
 9050 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SRCP'/          &
          '      INPUT  : ',e10.3/                            &
          '      DISSIP : ',e10.3)
 #endif
 #ifdef W3_ST2
 9050 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SRCP'/          &
          '      INPUT  : ',2e10.3/                           &
          '      DISSIP : ',4e10.3/                           &
          '               ',5e10.3/                           &
          '               ',3e10.3/                           &
          '      STAB2  : ',6e10.3)
 #endif
     !
 #ifdef W3_NL1
 9051 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SNLP'/          &
          '      DATA   : ',2e10.3/                           &
          '               ',5e10.3)
 #endif
     !
 #ifdef W3_NL2
 9051 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SNLP'/          &
          '      DATA   : ',i4,f5.1,i4)
 9151 FORMAT ('               ',5f7.1)
 #endif
     !
 #ifdef W3_NL3
 9051 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SNLP'/          &
          '      DATA   : ',i4,4f8.3)
 9151 FORMAT ('               ',2f8.3,f6.1,2e12.4)
 #endif
     !
 #ifdef W3_NL4
 9051 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SNLP'/          &
          '      DATA   : ',i4,i4)
 #endif
     !
 #ifdef W3_NL5
 9051 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SNLP'/          &
          '      DATA   : ', f7.1, f8.2, 2i2.1, i12, 2i2.1)
 #endif
     !
 #ifdef W3_NLS
 9251 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SNLP (NLS)'/    &
          '      DATA   : ',f8.3,e12.4,4f8.3)
 #endif
     !
 #ifdef W3_BT1
 9052 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SBTP'/          &
          '      DATA   : ',e10.3)
 #endif
     !
 #ifdef W3_DB1
 9053 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SDBP'/          &
          '      DATA   : ',2e10.3,l4)
 #endif
     !
 #ifdef W3_PR2
 9060 FORMAT (' TEST W3IOGR : MODULE W3GDATMD PROP'/          &
          '      DATA   : ',2e10.3)
 #endif
     !
 #ifdef W3_PR3
 9060 FORMAT (' TEST W3IOGR : MODULE W3GDATMD PROP'/          &
          '      DATA   : ',2f6.2)
 #endif
     !
 #ifdef W3_SMC
 9260 FORMAT (' TEST W3IOGR : MODULE W3GDATMD SMCG'/          &
          '      DATA   : ',3e10.3)
 #endif
     !
 #ifdef W3_T
 9070 FORMAT (' TEST W3IOGR : DISPERSION INTEPOLATION TABLES')
 #endif
     !/
     !/ End of W3IOGR ----------------------------------------------------- /
     !/
References w3timemd::caltype, w3src4md::delalp, w3src4md::deltail, w3src4md::deltauw, w3src4md::delu, w3src4md::delust, w3src4md::dikcumul, w3servmd::extcde(), file(), constants::file_endian, w3gdatmd::filext, w3odatmd::fnmpre, w3gdatmd::gname, w3odatmd::iaproc, include(), w3src2md::inptab(), w3src3md::insin3(), w3src4md::insin4(), w3sis2md::insis2(), w3snl1md::insnl1(), w3snl2md::insnl2(), w3snl3md::insnl3(), w3snl5md::insnl5(), w3snl1md::insnlgqm(), w3snlsmd::insnls(), w3adatmd::mpi_comm_wave, w3gdatmd::mrfct, w3odatmd::naperr, w3gdatmd::narc, w3gdatmd::nbac, w3gdatmd::nbgl, w3odatmd::nbi, w3odatmd::nbo, w3odatmd::nbo2, w3gdatmd::nbsmc, w3gdatmd::ncel, w3odatmd::ndse, w3odatmd::ndst, w3odatmd::nfbpo, w3gdatmd::nglo, w3gdatmd::nk, w3gdatmd::nrlv, w3gdatmd::nsea, w3gdatmd::nth, w3gdatmd::nufc, w3gdatmd::nvfc, w3gdatmd::nx, w3gdatmd::ny, w3servmd::print_memcheck(), w3servmd::strace(), w3src4md::tauhft, w3src4md::tauhft2, w3src4md::taut, w3uostmd::uost_initgrid(), w3gdatmd::w3setg(), and w3odatmd::w3seto().
Referenced by gxoutf(), gxoutp(), w3bounc(), w3bound(), w3grib(), w3gspl(), w3initmd::w3init(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3strt(), w3trnc(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().