WAVEWATCH III: scrip_constants Module Reference
scrip_constants Module Reference
Variables
real(kind=scrip_r8), parameter zero = 0.0_SCRIP_r8
real(kind=scrip_r8), parameter one = 1.0_SCRIP_r8
real(kind=scrip_r8), parameter two = 2.0_SCRIP_r8
real(kind=scrip_r8), parameter three = 3.0_SCRIP_r8
real(kind=scrip_r8), parameter four = 4.0_SCRIP_r8
real(kind=scrip_r8), parameter five = 5.0_SCRIP_r8
real(kind=scrip_r8), parameter half = 0.5_SCRIP_r8
real(kind=scrip_r8), parameter quart = 0.25_SCRIP_r8
real(kind=scrip_r8), parameter bignum = 1.e+20_SCRIP_r8
real(kind=scrip_r8), parameter tiny = 1.e-14_SCRIP_r8
real(kind=scrip_r8), parameter pi = 3.14159265359_SCRIP_r8
real(kind=scrip_r8), parameter pi2 = two*pi
real(kind=scrip_r8), parameter pih = half*pi
Variable Documentation
bignum
real (kind = scrip_r8), parameter scrip_constants::bignum = 1.e+20_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
five
real (kind = scrip_r8), parameter scrip_constants::five = 5.0_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
four
real (kind = scrip_r8), parameter scrip_constants::four = 4.0_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
half
real (kind = scrip_r8), parameter scrip_constants::half = 0.5_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
Referenced by wmscrpmd::get_scrip_info_structured(), scrip_remap_conservative::line_integral_phi(), scrip_remap_conservative::line_integral_theta(), scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), and scrip_remap_conservative::ptincell().
one
real (kind = scrip_r8), parameter scrip_constants::one = 1.0_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_remap_conservative::intersection(), scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), scrip_remap_conservative::ptincell(), scrip_remap_conservative::ptinpolarpoly(), scrip_remap_conservative::ptinpoly(), scrip_remap_conservative::ptinpolygen(), scrip_remap_conservative::ptinpolygen2(), scrip_remap_conservative::remap_conserv(), and wmscrpmd::scrip_wrapper().
pi
real (kind = scrip_r8), parameter scrip_constants::pi = 3.14159265359_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_remap_conservative::cell_integrate(), scrip_remap_conservative::converge_to_bdry(), scrip_grids::grid_init(), scrip_remap_conservative::intersection(), scrip_remap_conservative::line_integral_phi(), scrip_remap_conservative::line_integral_theta(), scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), scrip_remap_conservative::ptincell(), scrip_remap_conservative::ptinpolarpoly(), scrip_remap_conservative::ptinpoly(), scrip_remap_conservative::ptinpolygen(), scrip_remap_conservative::remap_conserv(), and scrip_grids::scrip_gridcomputearea().
pi2
real (kind = scrip_r8), parameter scrip_constants::pi2 = two*pi
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_remap_conservative::cell_integrate(), scrip_remap_conservative::converge_to_bdry(), scrip_grids::grid_init(), scrip_remap_conservative::intersection(), scrip_remap_conservative::line_integral_phi(), scrip_remap_conservative::line_integral_theta(), scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), scrip_remap_conservative::ptincell(), scrip_remap_conservative::ptinpolarpoly(), scrip_remap_conservative::ptinpoly(), scrip_remap_conservative::ptinpolygen(), scrip_remap_conservative::remap_conserv(), and scrip_grids::scrip_gridcomputearea().
pih
real (kind = scrip_r8), parameter scrip_constants::pih = half*pi
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_grids::grid_init(), scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::modify_polar_cell(), scrip_remap_conservative::pole_intersection(), scrip_remap_conservative::ptincell(), scrip_remap_conservative::ptinpolarpoly(), and scrip_remap_conservative::remap_conserv().
quart
real (kind = scrip_r8), parameter scrip_constants::quart = 0.25_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), and scrip_remap_conservative::ptincell().
three
real (kind = scrip_r8), parameter scrip_constants::three = 3.0_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
tiny
real (kind = scrip_r8), parameter scrip_constants::tiny = 1.e-14_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_remap_conservative::cell_integrate(), scrip_remap_conservative::converge_to_bdry(), scrip_remap_conservative::find_adj_cell(), scrip_remap_conservative::intersection(), scrip_remap_conservative::pole_intersection(), scrip_remap_conservative::ptinpolarpoly(), scrip_remap_conservative::ptinpoly(), scrip_remap_conservative::ptinpolygen(), and scrip_remap_conservative::ptinpolygen2().
two
real (kind = scrip_r8), parameter scrip_constants::two = 2.0_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
Referenced by scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), and scrip_remap_conservative::ptincell().
zero
real (kind = scrip_r8), parameter scrip_constants::zero = 0.0_SCRIP_r8
Definition at line 50 of file scrip_constants.f.
        real (kind = scrip_r8), parameter ::
      &     zero   = 0.0_scrip_r8,
      &     one    = 1.0_scrip_r8,
      &     two    = 2.0_scrip_r8,
      &     three  = 3.0_scrip_r8,
      &     four   = 4.0_scrip_r8,
      &     five   = 5.0_scrip_r8,
      &     half   = 0.5_scrip_r8,
      &     quart  = 0.25_scrip_r8,
      &     bignum = 1.e+20_scrip_r8,
      &     tiny   = 1.e-14_scrip_r8,
      &     pi     = 3.14159265359_scrip_r8,
      &     pi2    = two*pi,
      &     pih    = half*pi
Referenced by scrip_grids::grid_init(), scrip_remap_conservative::intersection(), scrip_remap_conservative::line_integral_phi(), scrip_remap_conservative::line_integral_theta(), scrip_remap_conservative::locate_segstart(), scrip_remap_conservative::pole_intersection(), scrip_remap_conservative::ptincell(), scrip_remap_conservative::ptinpolarpoly(), scrip_remap_conservative::ptinpoly(), scrip_remap_conservative::remap_conserv(), wmscrpmd::scrip_wrapper(), and scrip_remap_conservative::store_link_cnsrv().