WAVEWATCH III: w3nmluprstrmd Module Reference
w3nmluprstrmd Module Reference
Data Types
type nml_restart_t
type nml_update_t
Functions/Subroutines
subroutine w3nmluprstr (NDSI, INFILE, NML_RESTART, NML_UPDATE, IERR)
subroutine read_restart_nml (NDSI, NML_RESTART)
subroutine read_update_nml (NDSI, NML_UPDATE)
subroutine report_restart_nml (NML_RESTART)
subroutine report_update_nml (NML_UPDATE)
Variables
character(256) msg
integer ndsn
Function/Subroutine Documentation
read_restart_nml()
subroutine w3nmluprstrmd::read_restart_nml (integer, intent(in) NDSI, type(nml_restart_t), intent(inout) NML_RESTART)
Definition at line 169 of file w3nmluprstrmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         06-Oct-2020 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI         Int.
     !      NML_RESTART  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name        TYPE   Module  Description
     !     ----------------------------------------------------------------
     !      W3NMLUPRSTR Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                 :: NDSI
     TYPE(NML_RESTART_T), INTENT(INOUT)    :: NML_RESTART
     ! locals
     INTEGER                                :: IERR
     TYPE(NML_RESTART_T) :: RESTART
     namelist /restart_nml/ restart
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_RESTART_NML')
 #endif
     ! set default values
     restart%RESTARTTIME  = '19680607 120000'
     ! read restart namelist
     rewind(ndsi)
     READ (ndsi, nml=restart_nml, iostat=ierr, iomsg=msg)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_RESTART_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (1)
     END IF
     ! save namelist
     nml_restart = restart
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmluprstr().
read_update_nml()
subroutine w3nmluprstrmd::read_update_nml (integer, intent(in) NDSI, type(nml_update_t), intent(inout) NML_UPDATE)
Definition at line 272 of file w3nmluprstrmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         06-Oct-2020 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI         Int.
     !      NML_UPDATE   Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name        TYPE   Module  Description
     !     ----------------------------------------------------------------
     !      W3NMLUPRSTR Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                 :: NDSI
     TYPE(NML_UPDATE_T), INTENT(INOUT)   :: NML_UPDATE
     ! locals
     INTEGER                                :: IERR
     TYPE(NML_UPDATE_T) :: UPDATE
     namelist /update_nml/ update
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_UPDATE_NML')
 #endif
     ! set default values for update approach
     ! as set, these would run the update but not correct
     ! any spectra (scalar correction by factor of 1.0)
     update%UPDPROC    = 'UPD0F'      ! Update type
     update%PRCNTG     = 1.0          ! Scalar correction factor (1.0=no correction)
     update%PRCNTGCAP  = 10.0         ! Cap on correction factor
     update%THRWSEA    = 0.7          ! Energy threshold for wind-sea dominance
     update%FILE       = 'anl.grbtxt' ! Corrected analysed SWH field file
     ! read file namelist
     rewind(ndsi)
     READ (ndsi, nml=update_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_UPDATE_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (2)
     END IF
     ! save namelist
     nml_update = update
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmluprstr().
report_restart_nml()
subroutine w3nmluprstrmd::report_restart_nml (type(nml_restart_t), intent(in) NML_RESTART)
Definition at line 381 of file w3nmluprstrmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         06-Oct-2020 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_RESTART  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name        TYPE   Module  Description
     !     ----------------------------------------------------------------
     !      W3NMLUPRSTR Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_RESTART_T), INTENT(IN) :: NML_RESTART
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_RESTART_NML')
 #endif
     WRITE (msg,'(A)') 'RESTART % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,10) trim(msg),'RESTARTTIME = ', trim(nml_restart%RESTARTTIME)
 10  FORMAT (a,2x,a,a)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmluprstr().
report_update_nml()
subroutine w3nmluprstrmd::report_update_nml (type(nml_update_t), intent(in) NML_UPDATE)
Definition at line 464 of file w3nmluprstrmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         06-Oct-2020 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_UPDATE  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name        TYPE   Module  Description
     !     ----------------------------------------------------------------
     !      W3NMLUPRSTR Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_UPDATE_T), INTENT(IN) :: NML_UPDATE
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_UPDATE_NML')
 #endif
     WRITE (msg,'(A)') 'UPDATE % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,10) trim(msg),'UPDPROC   = ', trim(nml_update%UPDPROC)
     ! PRCNTG only used by UPD0F
     IF (trim(nml_update%UPDPROC) .EQ. 'UPD0F') THEN
       WRITE (ndsn,11) trim(msg),'PRCNTG    = ', nml_update%PRCNTG
     ELSE
       WRITE (ndsn,11) trim(msg),'PRCNTGCAP = ', nml_update%PRCNTGCAP
       ! THRWSEA only used by UPD5/6
       IF ((trim(nml_update%UPDPROC) .EQ. 'UPD5') .OR. &
            (trim(nml_update%UPDPROC) .EQ. 'UPD6')) THEN
         WRITE (ndsn,11) trim(msg),'THRWSEA   = ', nml_update%THRWSEA
       ENDIF
       WRITE (ndsn,10) trim(msg),'FILE      = ', trim(nml_update%FILE)
     ENDIF
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,f5.3)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmluprstr().
w3nmluprstr()
subroutine w3nmluprstrmd::w3nmluprstr (integer, intent(in) NDSI, character*(*), intent(in) INFILE, type(nml_restart_t), intent(inout) NML_RESTART, type(nml_update_t), intent(inout) NML_UPDATE, integer, intent(out) IERR)
Definition at line 50 of file w3nmluprstrmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         06-Oct-2020 |
     !/                  +-----------------------------------+
     !/
     !
     !  1. Purpose :
     !
     !     Reads all the namelist to define the output field
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI        Int.
     !      INFILE      Char.
     !      NML_RESTART type.
     !      NML_UPDATE  type.
     !      IERR        Int.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !      READ_RESTART_NML
     !      READ_UPDATE_NML
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name       TYPE   Module   Description
     !     ----------------------------------------------------------------
     !      WW3_UPRSTR Prog.  N/A      Update restart file
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                         :: NDSI
     CHARACTER*(*), INTENT(IN)                   :: INFILE
     TYPE(NML_RESTART_T), INTENT(INOUT)          :: NML_RESTART
     TYPE(NML_UPDATE_T), INTENT(INOUT)           :: NML_UPDATE
     INTEGER, INTENT(OUT)                        :: IERR
 #ifdef W3_S
     INTEGER, SAVE                             :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'W3NMLUPRSTR')
 #endif
     ! open namelist log file
     ndsn = 3
     OPEN (ndsn, file=trim(infile)//'.log', form='formatted', iostat=ierr)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A)') 'ERROR: open full nml file '//trim(infile)//'.log failed'
       RETURN
     END IF
     ! open input file
     OPEN (ndsi, file=trim(infile), form='formatted', status='old', iostat=ierr)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A)') 'ERROR: open input file '//trim(infile)//' failed'
       RETURN
     END IF
     ! read restart time namelist
     CALL read_restart_nml (ndsi, nml_restart)
     CALL report_restart_nml (nml_restart)
     ! read update approach namelist
     CALL read_update_nml (ndsi, nml_update)
     CALL report_update_nml (nml_update)
     ! close namelist files
     CLOSE (ndsi)
     CLOSE (ndsn)
References file(), w3odatmd::ndse, ndsn, read_restart_nml(), read_update_nml(), report_restart_nml(), report_update_nml(), and w3servmd::strace().
Referenced by w3uprstr().
Variable Documentation
msg
character(256) w3nmluprstrmd::msg
Definition at line 41 of file w3nmluprstrmd.F90.
   CHARACTER(256)                :: MSG
Referenced by read_restart_nml(), read_update_nml(), report_restart_nml(), and report_update_nml().
ndsn
integer w3nmluprstrmd::ndsn
Definition at line 42 of file w3nmluprstrmd.F90.
   INTEGER                       :: NDSN
Referenced by report_restart_nml(), report_update_nml(), and w3nmluprstr().