WAVEWATCH III: w3gsrumd Module Reference
w3gsrumd Module Reference
Data Types
type t_gsu
type t_nns
Functions/Subroutines
subroutine, public w3gsud (GSU)
subroutine, public w3gsup (GSU, IUNIT, LFULL)
type(t_nns) function, pointer, public w3nnsc (NLVL)
subroutine, public w3nnsd (NNS)
subroutine, public w3nnsp (NNS, IUNIT)
Variables
integer, parameter, public mskc_none = 0
integer, parameter, public mskc_part = 1
integer, parameter, public mskc_full = 2
integer, parameter, public iclo_none = -1
integer, parameter, public iclo_smpl = 2
integer, parameter, public iclo_grdi = ICLO_SMPL
integer, parameter, public iclo_grdj = 3
integer, parameter, public iclo_trdl = 6
integer, parameter, public iclo_trpl = 8
real(8), parameter pi = 3.14159265358979323846D0
Function/Subroutine Documentation
w3gsud()
subroutine, public w3gsrumd::w3gsud (type(t_gsu), intent(inout) GSU)
Definition at line 790 of file w3gsrumd.F90.
     TYPE(T_GSU), INTENT(INOUT) :: GSU
     !     Local parameters
     INTEGER :: IB, JB
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3GSUD')
 #endif
     !
     IF ( ASSOCIATED(gsu%PTR) ) THEN
       !
       CALL w3nnsd(gsu%PTR%NNP)
       !
       IF ( ASSOCIATED(gsu%PTR%B) ) THEN
         DO ib=1,gsu%PTR%NBX
           DO jb=1,gsu%PTR%NBY
             IF ( gsu%PTR%B(jb,ib)%N .GT. 0 ) THEN
               DEALLOCATE(gsu%PTR%B(jb,ib)%I)
               NULLIFY(gsu%PTR%B(jb,ib)%I)
               DEALLOCATE(gsu%PTR%B(jb,ib)%J)
               NULLIFY(gsu%PTR%B(jb,ib)%J)
             END IF
           END DO
         END DO
         DEALLOCATE(gsu%PTR%B)
         NULLIFY(gsu%PTR%B)
       END IF
       !
       CALL w3nnsd(gsu%PTR%NNB)
       !
       DEALLOCATE(gsu%PTR)
       NULLIFY(gsu%PTR)
       !
     END IF
References w3servmd::strace(), and w3nnsd().
Referenced by w3fldsmd::w3fldp(), and w3gsup().
w3gsup()
subroutine, public w3gsrumd::w3gsup (type(t_gsu), intent(in) GSU, integer, intent(in), optional IUNIT, logical, intent(in), optional LFULL)
Definition at line 885 of file w3gsrumd.F90.
     TYPE(T_GSU), INTENT(IN) :: GSU
     INTEGER, OPTIONAL, INTENT(IN) :: IUNIT
     LOGICAL, OPTIONAL, INTENT(IN) :: LFULL
     !     Local parameters
     INTEGER, PARAMETER :: NBYTE_PTR=4
     INTEGER, PARAMETER :: NBYTE_INT=4
     TYPE(CLASS_GSU), POINTER :: PTR
     INTEGER :: NDST, K, IB, JB, NBYTE
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3GSUP')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input
     !
     IF ( .NOT.ASSOCIATED(gsu%PTR) ) THEN
       WRITE(0,'(/1A,1A/)') 'W3GSUP ERROR -- ', &
            'grid search utility object not created'
       CALL extcde (1)
     END IF
     IF ( PRESENT(iunit) ) THEN
       ndst = iunit
     ELSE
       ndst = 6
     END IF
     ptr => gsu%PTR
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Compute approximate memory usage
     !
     nbyte = (nbyte_int+nbyte_ptr*2)*SIZE(ptr%B)
     DO ib=1,ptr%NBX
       DO jb=1,ptr%NBY
         nbyte = nbyte + nbyte_int*2*ptr%B(jb,ib)%N
       END DO
     END DO
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Output
     !
     WRITE(ndst,'(//80A)') ('-',k=1,80)
     WRITE(ndst,'(A)') 'Report on grid search utility object'
     WRITE(ndst,'( 80A)') ('-',k=1,80)
     WRITE(ndst,'(A,1L2)') 'Grid  ijg:',ptr%IJG
     WRITE(ndst,'(A,1L2)') 'Grid  llg:',ptr%LLG
     WRITE(ndst,'(A,1I2)') 'Grid iclo:',ptr%ICLO
     WRITE(ndst,'(A,1L2)') 'Grid lclo:',ptr%LCLO
     WRITE(ndst,'(A,1I2)') 'Grid precision:',ptr%GKIND
     WRITE(ndst,'(A,2I6)') 'Grid lbx,lby:',ptr%LBX,ptr%LBY
     WRITE(ndst,'(A,2I6)') 'Grid ubx,uby:',ptr%UBX,ptr%UBY
     WRITE(ndst,'(A,2I6)') 'Grid  nx, ny:',ptr%NX,ptr%NY
     IF ( PRESENT(lfull) ) THEN
       IF ( lfull ) THEN
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(A)') 'Nearest-neighbor point search indices'
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         CALL w3nnsp(ptr%NNP,ndst)
       END IF
     END IF
     WRITE(ndst,'( 80A)') ('-',k=1,80)
     WRITE(ndst,'(A)') 'Bucket-search object'
     WRITE(ndst,'( 80A)') ('-',k=1,80)
     WRITE(ndst,'(A,4E24.16)') 'Spatial grid search domain: ', &
          ptr%XMIN,ptr%YMIN,ptr%XMAX,ptr%YMAX
     WRITE(ndst,'(A,2I6)') 'nbx,nby:',ptr%NBX,ptr%NBY
     WRITE(ndst,'(A,2E24.16)') 'dxb,dyb:',ptr%DXB,ptr%DYB
     WRITE(ndst,'(A,1F10.1)') 'Approximate memory usage (MB):', &
          REAL(NBYTE)/2**20
     IF ( PRESENT(lfull) ) THEN
       IF ( lfull ) THEN
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(A)') 'Search bucket bounds:'
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(2A4,4A24)') 'IB','JB','X1','Y1','X2','Y2'
         DO ib=1,ptr%NBX
           DO jb=1,ptr%NBY
             WRITE(ndst,'(2I4,4E24.16)') ib,jb, &
                  ptr%XMIN+(ib-1)*ptr%DXB,ptr%YMIN+(jb-1)*ptr%DYB, &
                  ptr%XMIN+(ib  )*ptr%DXB,ptr%YMIN+(jb  )*ptr%DYB
           END DO
         END DO
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(A)') 'Number of cells in each search bucket:'
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         DO jb=ptr%NBY,1,-1
           WRITE(ndst,'(500I4)') (ptr%B(jb,ib)%N,ib=1,ptr%NBX)
         END DO
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(A)') 'Search bucket cell lists:'
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(3A4,A)') 'IB','JB','NC',': ( IC, JC), ...'
         DO jb=1,ptr%NBY
           DO ib=1,ptr%NBX
             WRITE(ndst,'(3I4,A,500(A,I3,A,I3,A))') ib,jb, &
                  ptr%B(jb,ib)%N, ': ', &
                  ( '(',ptr%B(jb,ib)%I(k),',',ptr%B(jb,ib)%J(k),') ', &
                  k=1,ptr%B(jb,ib)%N )
           END DO
         END DO
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         WRITE(ndst,'(A)') 'Nearest-neighbor bucket search indices'
         WRITE(ndst,'( 80A)') ('-',k=1,80)
         CALL w3nnsp(ptr%NNB,ndst)
       END IF !LFULL
     END IF !PRESENT(LFULL)
     WRITE(ndst,'( 80A)') ('-',k=1,80)
     WRITE(ndst,'( 80A)') ('-',k=1,80)
References check(), iclo_grdi, iclo_grdj, iclo_none, iclo_trdl, iclo_trpl, mskc_full, mskc_none, mskc_part, w3servmd::strace(), w3gsud(), w3nnsc(), and w3nnsp().
Referenced by w3fldsmd::w3fldp(), w3gdatmd::w3gntx(), and w3iotrmd::w3iotr().
w3nnsc()
type(t_nns) function, pointer, public w3gsrumd::w3nnsc (integer, intent(in) NLVL)
Definition at line 6820 of file w3gsrumd.F90.
     TYPE(T_NNS), POINTER :: NNS
     INTEGER, INTENT(IN)  :: NLVL
     !     Local parameters
     INTEGER :: I, J, L, N
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3NNSC')
 #endif
     !
     !-----allocate object
     ALLOCATE(nns)
     !-----initialize sizes
     nns%NLVL = nlvl
     nns%NNBR = (2*nlvl+1)**2
     !-----allocate arrays
     ALLOCATE(nns%N1(0:nns%NLVL))
     ALLOCATE(nns%N2(0:nns%NLVL))
     ALLOCATE(nns%DI(0:nns%NNBR-1))
     ALLOCATE(nns%DJ(0:nns%NNBR-1))
     !-----compute index deltas for nearest-neighbor searches
     n = 0
     !-----central point
     l = 0
     nns%N1(l) = 0;  nns%N2(l) = (2*l+1)**2-1;
     nns%DI(n) = 0;  nns%DJ(n) = 0;
     !-----loop over levels
     DO l=1,nns%NLVL
       !---------nnbr loop bounds
       nns%N1(l) = (2*l-1)**2;  nns%N2(l) = (2*l+1)**2-1;
       !---------bottom-layer
       j = -l
       DO i=-l,l-1
         n = n + 1
         nns%DI(n) = i;  nns%DJ(n) = j;
       END DO
       !---------right-layer
       i =  l
       DO j=-l,l-1
         n = n + 1
         nns%DI(n) = i;  nns%DJ(n) = j;
       END DO
       !---------top-layer
       j =  l
       DO i=l,-l+1,-1
         n = n + 1
         nns%DI(n) = i;  nns%DJ(n) = j;
       END DO
       !---------left-layer
       i = -l
       DO j=l,-l+1,-1
         n = n + 1
         nns%DI(n) = i;  nns%DJ(n) = j;
       END DO
     END DO !loop over levels
References w3servmd::strace().
Referenced by w3gsup(), and w3nnsp().
w3nnsd()
subroutine, public w3gsrumd::w3nnsd (type(t_nns), pointer NNS)
Definition at line 6931 of file w3gsrumd.F90.
     TYPE(T_NNS), POINTER :: NNS
     !     Local parameters
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3NNSD')
 #endif
     !
     IF ( ASSOCIATED(nns) ) THEN
       nns%NLVL = 0
       nns%NNBR = 0
       IF ( ASSOCIATED(nns%N1) ) THEN
         DEALLOCATE(nns%N1);  NULLIFY(nns%N1);
       END IF
       IF ( ASSOCIATED(nns%N2) ) THEN
         DEALLOCATE(nns%N2);  NULLIFY(nns%N2);
       END IF
       IF ( ASSOCIATED(nns%DI) ) THEN
         DEALLOCATE(nns%DI);  NULLIFY(nns%DI);
       END IF
       IF ( ASSOCIATED(nns%DJ) ) THEN
         DEALLOCATE(nns%DJ);  NULLIFY(nns%DJ);
       END IF
       DEALLOCATE(nns)
       NULLIFY(nns)
     END IF
References w3servmd::strace().
Referenced by w3gsud().
w3nnsp()
subroutine, public w3gsrumd::w3nnsp (type(t_nns), intent(in) NNS, integer, intent(in), optional IUNIT)
Definition at line 7012 of file w3gsrumd.F90.
     TYPE(T_NNS), INTENT(IN) :: NNS
     INTEGER, OPTIONAL, INTENT(IN) :: IUNIT
     !     Local parameters
     INTEGER :: NDST, L, N
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3NNSP')
 #endif
     !
     IF ( PRESENT(iunit) ) THEN
       ndst = iunit
     ELSE
       ndst = 6
     END IF
     !
     WRITE(ndst,'(A,2I6)') 'nlvl,nnbr:',nns%NLVL,nns%NNBR
     DO l=0,nns%NLVL
       DO n=nns%N1(l),nns%N2(l)
         WRITE(ndst,'(A,4I6)') 'l,n,di,dj:',l,n,nns%DI(n),nns%DJ(n)
       END DO
     END DO
References iclo_grdi, iclo_grdj, iclo_none, iclo_trdl, iclo_trpl, include(), w3servmd::strace(), and w3nnsc().
Referenced by w3gsup().
Variable Documentation
iclo_grdi
integer, parameter, public w3gsrumd::iclo_grdi = ICLO_SMPL
Definition at line 316 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: ICLO_GRDI =  iclo_smpl
Referenced by w3gsup(), and w3nnsp().
iclo_grdj
integer, parameter, public w3gsrumd::iclo_grdj = 3
Definition at line 317 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: ICLO_GRDJ =  3
Referenced by w3gsup(), and w3nnsp().
iclo_none
integer, parameter, public w3gsrumd::iclo_none = -1
Definition at line 314 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: ICLO_NONE = -1
Referenced by w3fldsmd::w3fldp(), w3gsup(), and w3nnsp().
iclo_smpl
integer, parameter, public w3gsrumd::iclo_smpl = 2
Definition at line 315 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: ICLO_SMPL =  2
Referenced by w3fldsmd::w3fldp().
iclo_trdl
integer, parameter, public w3gsrumd::iclo_trdl = 6
Definition at line 318 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: ICLO_TRDL =  6
Referenced by w3gsup(), and w3nnsp().
iclo_trpl
integer, parameter, public w3gsrumd::iclo_trpl = 8
Definition at line 319 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: ICLO_TRPL =  8
Referenced by w3gsup(), and w3nnsp().
mskc_full
integer, parameter, public w3gsrumd::mskc_full = 2
Definition at line 283 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: MSKC_FULL = 2
Referenced by w3gsup().
mskc_none
integer, parameter, public w3gsrumd::mskc_none = 0
Definition at line 281 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: MSKC_NONE = 0
Referenced by w3fldsmd::w3fldp(), and w3gsup().
mskc_part
integer, parameter, public w3gsrumd::mskc_part = 1
Definition at line 282 of file w3gsrumd.F90.
   INTEGER, PARAMETER, PUBLIC :: MSKC_PART = 1
Referenced by w3fldsmd::w3fldp(), and w3gsup().
pi
real(8), parameter w3gsrumd::pi = 3.14159265358979323846D0
Definition at line 377 of file w3gsrumd.F90.
   REAL(8), PARAMETER :: PI = 3.14159265358979323846d0