WAVEWATCH III: w3smcomd Module Reference
w3smcomd Module Reference
Service module for support of SMC regridding and interpolation.
Functions/Subroutines
subroutine smc_interp ()
Generate SMC interpolation/output information.
subroutine w3s2xy_smcrg (S, XY)
Regrid SMC data onto a regular grid.
subroutine w3s2xy_smcrg_dir (S, XY)
Regrid directional SMC data onto a regular grid.
subroutine mapsta_smc ()
Calculates a new MAPSTA using SMC grid cell averaging.
subroutine read_smcint ()
Read interpolation information from smcint.ww3.
subroutine calc_interp ()
Calculates weights for SMC to arbitrary grid intepolation.
subroutine w3s2xy_smcnn (S, XY, DIRN)
Fill regular grid using nearest SMC point data.
subroutine w3s2xy_smcnn_int (S, XY, DIRN)
Nearest neighbour interpolation.
subroutine w3s2xy_smc (S, XY, DIR)
Entry point for SMC version of W3S2XY.
Variables
double precision sxo
Output grid longitude origin.
double precision syo
Output grid latitude origin.
double precision exo
Output grid final longitude.
double precision eyo
Output grid final latitude.
double precision dxo
Output grid cell longitude size.
double precision dyo
Output grid cell latitude size.
integer nxo
Output grid number of longitude cells.
integer nyo
Output grid number of latitude cells.
integer smcotype
Type of SMC output: 1=seapoint grid of SMC cells; 2=regridding to regular grid; 3=interpolation to arbtrary grid; 4=nearest neighbour interpolation to arbitrary grid.
integer celfac
Output grid cell scaling factor; should be an integer power of 2.
integer, dimension(:), allocatable xidx
X-indices of SMC cells in regular grid.
integer, dimension(:), allocatable yidx
Y-Indices of SMC cells in regular grid.
integer, dimension(:), allocatable xspan
Number of longitude cells SMC cell spans.
integer, dimension(:), allocatable yspan
Number of longitude cells SMC cell spans.
real, dimension(:), allocatable wts
Regridding weights.
real, dimension(:,:), allocatable cov
Wet fraction (coverage) of cell.
integer, dimension(:,:), allocatable mapsmc
Regridded MAPSTA.
logical, dimension(:), allocatable smcmask
Mask for type 1 output (flat array)
integer, dimension(:), allocatable smcidx
Indices of SMC cells within output grid domain.
integer, dimension(:), allocatable smccx
SMC grid definition.
integer, dimension(:), allocatable smccy
Latitude cell size factors.
real dlat
Base longitude cell size.
real dlon
Base latitude cell size.
integer cfac
SMC scaling factor (number of levels)
real noval
Fill value for seapoints with no value.
integer, dimension(:,:), allocatable nnidx
Nearest neighbour SMC point to regular grid.
real, dimension(:,:), allocatable xdist
Lng.
real, dimension(:,:), allocatable ydist
Lat.
integer ndsmc
ww3_smcint file unit number
integer smcnout
Number of SMC output cells.
integer nsmc
Number of SMC cells used in regridding.
Detailed Description
Service module for support of SMC regridding and interpolation.
For SMC grids, four types of output are possible:
Flat grid (seapoint) output of SMC cells with associated cell size variables (cx and cy). Requires extra effort to plot as grid is not regular.
Regular, uniformly gridded output to a specified output grid. This is achieved by area averaging of the SMC cells. The output grid will be aligned with the SMC grid cell edges which may result in the actual output grid being slightly different to the original user request. A land/sea mask is created by keeping track of the cell coverage and setting cells with total coverage of <50% UNDEF.
[Experimental] Arbitrary regualar grid re-gridding using indices and weights generated from WW3_SMCINT*. Uses the local gradient within the grid cell and distance between cell centres to interpolate.
[Experimental] As type 3, but with no interpolation - value from surrounding SMC cell only.
* The ww3_smcint program is experimental and not yet included in the official WW3 distribution; it is currently part of the UK Met Office's suite of internal tools.
Remarks
Note - directional fields are expected to be passed to routines with units of radians (cartesian convention). They will be OUTPUT in units of degrees (nautical convention).
Author
Chris Bunney
Date
21-Jul-2021
Change log
Date Ver Comments
18-Jan-2016 4.18 Initial version
28-Sep-2016 4.18 Bug fix EXO/EYO calcs for whole domain output
05-Oct-2016 4.18 Bug fix regular grid indicies for type 2 output
29-Sep-2017 4.18 Revise calculation of indicies to ensure selected cells fall inside user selected areas.
18-Apr-2018 4.18 Added Type 3 and 4 SMC output
20-Jun-2018 4.18 Directional fields output as nautical convention (deg)
27-Jun-2018 6.05 Ported to V6
06-Jan-2021 7.12 Use ARCTC option for SMC grid.
20-Jul-2021 7.12 Fix bug where edge cells in design grid may not be matched due where SMC cell > base grid size.
21-Jul-2021 7.12 Elevated some grid variables to DOUBLE PRECISION, fixed EXO/EYO bug
Function/Subroutine Documentation
calc_interp()
subroutine w3smcomd::calc_interp
Calculates weights for SMC to arbitrary grid intepolation.
Calculates the interpolation indices and weights for regridding an SMC grid to an arbitrary regular grid. Calculated index is that of the SMC cell that contains output cell centre. Weights are the distance in metres between the output and SMC cell centres.
A future version may allow for output grids to be on a rotated pole.
Author
Chris Bunney
Date
18-Apr-2018
Definition at line 623 of file w3smcomd.F90.
     USE w3gdatmd, ONLY: clats
     USE constants, ONLY : dera, radius
 #ifdef W3_RTD
     USE w3servmd, ONLY: w3lltoeq
     USE w3gdatmd, ONLY: polon, polat
 #endif
     IMPLICIT NONE
     INTEGER :: IERR, I, J, ISEA, N, CFAC
     REAL :: mlon(NSEA), mlat(NSEA), olon(nxo,nyo), olat(nxo,nyo),     &
          ang(nxo,nyo), lon, lat
 #ifdef W3_RTD
     REAL :: tmplon(nxo,nyo), tmplat(nxo,nyo)
 #endif
     ! Determine smallest cell size factor:
     cfac = 2**(nrlv - 1)
     ! Get smallest SMC grid cells step size:
     dlat = sy / cfac
     dlon = sx / cfac
     ALLOCATE(xdist(nx,ny), ydist(ny,nx))
     ! Model lat/lons:
     DO isea = 1,nsea
       mlon(isea) = (x0-0.5*sx) + (ijkcel(1,isea) + 0.5 * ijkcel(3,isea)) * dlon
       mlat(isea) = (y0-0.5*sy) + (ijkcel(2,isea) + 0.5 * ijkcel(4,isea)) * dlat
     ENDDO
     ! Generate output grid cell centres:
     DO i=1,nxo
       DO j=1,nyo
         olon(i,j) = sxo + (i-1) * dxo
         olat(i,j) = syo + (j-1) * dyo
       ENDDO
     ENDDO
 #ifdef W3_RTD
     tmplat = olat
     tmplon = olon
     print*,'Rotating coordinates'
     CALL w3lltoeq ( tmplat, tmplon, olat, olon,                       &
          ang, polat, polon, nxo*nyo )
     print*,'Rotating coordinates complete'
 #endif
     ! Cycle over output grid points and find containing SMC cell:
     ! NOTE : BRUTE FORCE!
     nnidx(:,:) = -1
     DO i=1,nxo
       print*,i,' of ',nxo
       DO j=1,nyo
         lon = olon(i,j)
         lat = olat(i,j)
         IF(lon .LT. x0 - sx / 2) lon = lon + 360.0
         IF(lon .GT. (x0 + (nx-1) * sx) + 0.5 * sx) lon = lon - 360.0
         DO isea=1,nsea
           IF(mlon(isea) - 0.5 * ijkcel(3,isea) * dlon .LE. lon .AND.    &
                mlon(isea) + 0.5 * ijkcel(3,isea) * dlon .GE. lon .AND.    &
                mlat(isea) - 0.5 * ijkcel(4,isea) * dlat .LE. lat .AND.    &
                mlat(isea) + 0.5 * ijkcel(4,isea) * dlat .GE. lat ) THEN
             ! Match!
             nnidx(i,j) = isea
             xdist(i,j) = (lon - mlon(isea)) * dera * radius * clats(isea)
             ydist(i,j) = (lat - mlat(isea)) * dera * radius
             EXIT
           ENDIF
         ENDDO
       ENDDO
     ENDDO
References w3gdatmd::clats, constants::dera, dlat, dlon, dxo, dyo, nnidx, w3gdatmd::polat, w3gdatmd::polon, constants::radius, sxo, syo, w3servmd::w3lltoeq(), xdist, and ydist.
mapsta_smc()
subroutine w3smcomd::mapsta_smc
Calculates a new MAPSTA using SMC grid cell averaging.
Author
Chris Bunney
Date
02-Jul-2013
Definition at line 519 of file w3smcomd.F90.
     IMPLICIT NONE
     ! Local parameters
     INTEGER           :: I, J, IX, IY, IMX, IMY, ISEA
     ! Initialise coverage and output arrays:
     cov(:,:) = 0.0
     mapsmc(:,:) = 0
     DO isea=1,nsea
       imx = mapsf(isea,1)
       imy = mapsf(isea,2)
       IF(xidx(isea) .EQ. -1) cycle   ! Out of grid
       ! Loop over number of spanned cells:
       DO i=0, xspan(isea) - 1
         DO j=0, yspan(isea) - 1
           ix = xidx(isea) + i
           iy = yidx(isea) + j
           ! Spans outside of grid?
           IF(ix .GT. nxo .OR. iy .GT. nyo) cycle
           ! MAPSTA values: 0=Excluded, (+-)1=Sea, (+-2)=Input boundary
           ! We will just keep track of sea and non-sea points:
           IF(mapsta(imy, imx) .NE. 0) THEN
             ! Keep track of how much of cell is (wet) covered:
             cov(ix, iy) = cov(ix, iy) + wts(isea)
           ENDIF
         ENDDO
       ENDDO
     ENDDO
     ! Create coastline by masking out areas with < 50% coverage:
     DO ix=1,nxo
       DO iy=1,nyo
         IF(cov(ix,iy) .LT. 0.5) THEN
           mapsmc(ix, iy) = 0
         ELSE
           mapsmc(ix, iy) = 1
         ENDIF
       ENDDO
     ENDDO
     RETURN
References cov, w3gdatmd::mapsf, mapsmc, w3gdatmd::mapsta, w3gdatmd::nsea, nxo, nyo, wts, xidx, xspan, yidx, and yspan.
read_smcint()
subroutine w3smcomd::read_smcint
Read interpolation information from smcint.ww3.
Reads the interpolation indices and distance weights from the smcint.ww3 file generated by ww3_smcint program.
Author
Chris Bunney
Date
18-Apr-2018
Definition at line 580 of file w3smcomd.F90.
     USE w3servmd, ONLY: extcde
     IMPLICIT NONE
     ! Locals
     INTEGER :: IERR, I, J
     REAL :: PLATO, PLONO ! Not used yet....future version might allow
     ! output to a rotated pole grid...
     ndsmc = 50
     OPEN(ndsmc, file='smcint.ww3', status='old', form='unformatted', convert=file_endian, iostat=ierr)
     IF(ierr .NE. 0) THEN
       WRITE(*,*) "ERROR! Failed to open smcint.ww3 for reading"
       CALL extcde(1)
     ENDIF
     ! Header
     READ(ndsmc) nxo, nyo, sxo, syo, dxo, dyo, plono, plato
     ALLOCATE(nnidx(nxo,nyo), xdist(nxo,nyo), ydist(nxo,nyo))
     ! Indices and weights:
     READ(ndsmc)((nnidx(i,j), xdist(i,j), ydist(i,j),i=1,nxo),j=1,nyo)
     CLOSE(ndsmc)
References dxo, dyo, w3servmd::extcde(), file(), constants::file_endian, ndsmc, nnidx, nxo, nyo, sxo, syo, xdist, and ydist.
smc_interp()
subroutine w3smcomd::smc_interp
Generate SMC interpolation/output information.
This subroutine generates index or mask values for extraction of SMC data to either a flat grid or regular lat/lon grid, depending on the type of SMC output grid selected:
Type 1: Generates a mask for extracting only points from the user requested region.
Type 2: Calculate interpolation indices and weights for regridding the irregular SMC grid onto a regular, uniformly spaced lat/lon grid.
Author
Chris Bunney
Date
22-Oct-2015
Definition at line 143 of file w3smcomd.F90.
     IMPLICIT NONE
     ! Locals
     REAL    :: CX0, CY0   ! SW corner of origin of grid
     REAL    :: S0CHK, XSNAP, YSNAP
     INTEGER :: ISEA, mx, my, ixx, iyy, J
     REAL    :: lat, lon
     j = 1
     nsmc = 0
     ! Determine smallest cell size factor:
     cfac = 2**(nrlv - 1)
     ! Get smallest SMC grid cells step size:
     dlat = sy / cfac
     dlon = sx / cfac
     ! SW Corner of grid origin cell:
     cx0 = x0 - sx / 2.
     cy0 = y0 - sy / 2.
     ! Grid cell size to snap design grid to. Will be regular grid
     ! resolution for cellsize <= cfac, or cellsize for cellsize > cfac
     xsnap = sx
     ysnap = sy
     IF(celfac .gt. cfac) xsnap = celfac * dlon
     IF(celfac .gt. cfac) ysnap = celfac * dlat
     ! Get start lat,lon (must be aligned with SMC grid edges). Use
     ! regular grid origins if SXO or SYO is -999.9 (use full grid):
     IF(abs(sxo + 999.9) .LT. 1e-4) THEN
       sxo = cx0
     ELSE
       s0chk = cx0 + floor((sxo - cx0) / xsnap) * xsnap
       ! Ensure first grid value falls within specified range
       IF (s0chk .LT. sxo) THEN
         sxo = s0chk + xsnap
       ELSE
         sxo = s0chk
       ENDIF
     ENDIF
     IF(abs(syo + 999.9) .LT. 1e-4) THEN
       syo = cy0
     ELSE
       s0chk = cy0 + floor((syo - cy0) / ysnap) * ysnap
       ! Ensure first grid value falls within specified range
       IF (s0chk .LT. syo) THEN
         syo = s0chk + ysnap
       ELSE
         syo = s0chk
       ENDIF
     ENDIF
     ! Use regular grid extents for last lat/lon if user
     ! specifies -999.9 for EXO/EYO (use full grid):
     IF(abs(exo + 999.9) .LT. 1e-4) THEN
       exo = cx0 + sx * nx ! TRHC of last cell
     ENDIF
     IF(abs(eyo + 999.9) .LT. 1e-4) THEN
       eyo = cy0 + sy * ny ! TRHC of last cell
     ENDIF
     ! Ouput grid cell dx/dy will be integer factor of smallest
     ! SMC grid cell size:
     dxo = dlon * celfac
     dyo = dlat * celfac
     ! Determine number of cells in grid:
     nxo = nint((exo - sxo) / dxo)
     nyo = nint((eyo - syo) / dyo)
     IF(smcotype .EQ. 2) THEN
       ! Initialise all indices to "missing":
       xidx(:) = -1
       yidx(:) = -1
     ENDIF
     ! Loop over cell array and calculate regidding factors:
     DO isea=1, nsea
       !          ! For grids with Arctic region: make sure we don't double count
       !          ! the overlapping boundary cells. Also, don't process the arctic
       !          ! cell (which is always the last cell).
       !          ! Note: NARC contains ALL the boundary cells (global + arctic).
       !          ! whereas NGLO contains only the global boundary cells.
       !          IF(ISEA .GT. NGLO-NBAC .AND. ISEA .LT. NSEA-NARC+1) CYCLE
       IF( arctc .AND. &
            isea .GT. nglo-nbac .AND. isea .LT. nsea-narc+1) cycle
       ! Get grid cell size:
       mx = ijkcel(3,isea)
       my = ijkcel(4,isea)
       ! Determine cell lat/lon (bottom left corner of cell)
       lon = cx0 + ijkcel(1,isea) * dlon
       lat = cy0 + ijkcel(2,isea) * dlat
       ! For output type 1 (seapoint array), just check whether
       ! cell centre is within specified domain range, and update
       ! output mask accordingly:
       IF( smcotype .EQ. 1 ) THEN
         ! Ensure longitude ranges are aligned
         lon = lon + 0.5 * mx * dlon
         lat = lat + 0.5 * my * dlat
         IF(lon .LT. sxo) lon = lon + 360.0
         IF(lon .GT. exo) lon = lon - 360.0
         ! Now check if it is within range of requested domain:
         IF(lon .GE. sxo .AND. lon .LE. exo .AND.           &
              lat .GE. syo .AND. lat .LE. eyo ) THEN
           smcmask(isea) = .true.
           smcidx(j) = isea
           j = j + 1
         ENDIF
         cycle
       ENDIF ! SMCOTYPE == 1
       ! For output type 2 (area averaged regular grid), determine
       ! SMC grid cell location and coverage in output grid:
       ! Align lons
       IF(lon .LT. sxo) THEN
         lon = lon + 360.
       ENDIF
       IF(lon .GT. exo) THEN
         lon = lon - 360.
       ENDIF
       ! Find first SW cell in design grid:
       ! We add on 1/2 of the smallest SMC cell dlon/dlat values to ensure
       ! source grid cell ends up in the correct target grid cell (after
       ! integer trunction):
       ixx = floor((lon + 0.5*dlon - sxo) / dxo) + 1
       iyy = floor((lat + 0.5*dlat - syo) / dyo) + 1
       ! If we fall outside the left/bottom edge of the design grid,
       ! check for cases where the SMC cell has a lon or lat
       ! scaling factor > cfac (design grid is assumed to align
       ! its origin with cells of size cfac). For such cells,
       ! keep moving the left/bottom edge up by cfac until
       ! the SW corner (possibly) matches a design grid cell.
       IF(ixx .LE. 0 .AND. ixx + mx / celfac .GT. 0) THEN
         DO WHILE(mx .GT. cfac)
           mx = mx - cfac
           lon = lon + dlon * cfac
           ixx = floor((lon + 0.5*dlon - sxo) / dxo) + 1
           IF(ixx .GT. 0) EXIT ! Found cell lon-edge in design grid
         ENDDO
       ENDIF
       IF(iyy .LE. 0 .AND. iyy + my / celfac .GT. 0) THEN
         DO WHILE(my .GT. cfac)
           my = my - cfac
           lat = lat + dlat * cfac
           iyy = floor((lat + 0.5*dlat - syo) / dyo) + 1
           IF(iyy .GT. 0) EXIT ! Found cell lat-edge in design grid
         ENDDO
       ENDIF
       ! If SMC cell definitely out of design grid domain, then cycle.
       IF(ixx .LE. 0 .OR. ixx .GT. nxo .OR.                          &
            iyy .LE. 0 .OR. iyy .GT. nyo) THEN
         xidx(isea) = -1
         yidx(isea) = -1
         cycle
       ENDIF
       xidx(isea) = ixx
       yidx(isea) = iyy
       nsmc = nsmc + 1
       smcidx(nsmc) = isea
       ! find out how many cells it covers in the x/y directions:
       xspan(isea) = max(1, int(mx / celfac))
       yspan(isea) = max(1, int(my / celfac))
       ! Do a bit of error checking (non fatal - just produced warning):
       IF(xspan(isea) .GT. 1) THEN
         IF(abs((sxo+(ixx-1)*dxo) - lon) .GT. dxo/100.0) THEN
           print*, 'Potential problem with SMC grid cell span:'
           print*, xspan(isea), float(mx) / celfac
           print*, lon,lat
           print*, sxo+(ixx-1)*dxo,syo+iyy*dyo,dxo,dyo
           print*, "diff:", (sxo+(ixx-1)*dxo) - lon
         ENDIF
       ENDIF
       ! calc cell weight in relation to output grid:
       wts(isea) = min(1., dble(min(celfac, mx) * min(celfac, my)) / &
            (celfac**2))
     ENDDO
     ! Reset SXO and SYO to be the cell-centre (currently cell SW edge):
     sxo = sxo + 0.5 * dxo
     syo = syo + 0.5 * dyo
References w3gdatmd::arctc, celfac, cfac, dlat, dlon, dxo, dyo, exo, eyo, w3gdatmd::ijkcel, w3gdatmd::narc, w3gdatmd::nbac, w3gdatmd::nglo, w3gdatmd::nrlv, w3gdatmd::nsea, nsmc, w3gdatmd::nx, nxo, w3gdatmd::ny, nyo, smcidx, smcmask, smcotype, w3gdatmd::sx, sxo, w3gdatmd::sy, syo, wts, w3gdatmd::x0, xidx, xspan, w3gdatmd::y0, yidx, and yspan.
w3s2xy_smc()
subroutine w3smcomd::w3s2xy_smc (real, dimension(:), intent(in) S, real, dimension(nxo,nyo), intent(out) XY, logical, optional DIR)
Entry point for SMC version of W3S2XY.
Dispatches to regridding subroutine based on SMCOTYPE. Optional DIR logical specifies whether field is a directional value; in which case it will be decomposed into u/v components prior to any interpolation.
Parameters
[in] S Input array on SMC grid
[out] XY Output array to store interpolated 2D field
[in] DIR (Optional) Set to .TRUE. if S is a directional field
Author
Chris Bunney
Date
18-Apr-2018
Definition at line 817 of file w3smcomd.F90.
     IMPLICIT NONE
     REAL, INTENT(IN)  :: S(:)
     REAL, INTENT(OUT) :: XY(NXO,NYO)
     LOGICAL, OPTIONAL :: DIR
     LOGICAL           :: DIRN
     INTEGER           :: ISEA
     IF(PRESENT(dir)) THEN
       dirn = dir
     ELSE
       dirn = .false.
     ENDIF
     IF(smcotype .EQ. 1) THEN
       ! Flat sea point array
       xy(:,1) = pack(s, smcmask)
       IF(dirn) THEN
         ! Convert to nautical convention in degrees
         DO isea=1,nxo
           IF(xy(isea,1) .NE. undef) THEN
             xy(isea,1) = mod(630. - rade * xy(isea,1), 360.)
           ENDIF
         ENDDO
       ENDIF
     ELSEIF(smcotype .EQ. 2) THEN
       ! Regular gridded SMC cells
       IF(dirn) THEN
         CALL w3s2xy_smcrg_dir(s, xy)
       ELSE
         CALL w3s2xy_smcrg(s, xy)
       ENDIF
     ELSEIF(smcotype .EQ. 3) THEN
       ! Regridded to arbitrary regular grid with interpolation
       CALL w3s2xy_smcnn_int(s, xy, dirn)
     ELSEIF(smcotype .EQ. 4) THEN
       ! Regridded to arbitrary regular grid - no interpolation
       CALL w3s2xy_smcnn(s, xy, dirn)
     ELSE
       WRITE(*,*) "Uknonwn SMC type!", smcotype
       ! Unknown SMC type!
       stop
     ENDIF
References constants::rade, smcmask, smcotype, constants::undef, w3s2xy_smcnn(), w3s2xy_smcnn_int(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
w3s2xy_smcnn()
subroutine w3smcomd::w3s2xy_smcnn (real, dimension(:), intent(in) S, real, dimension(nxo,nyo), intent(out) XY, logical, intent(in) DIRN)
Fill regular grid using nearest SMC point data.
Directional fields (DIRN=True) will be assumed to be in radians and will be converted to degrees in nautical convention.
Parameters
[in] S Input array on SMC grid
[out] XY Output array to store interpolated 2D field
[in] DIRN Set to .TRUE. if S is a directional field
Author
Chris Bunney
Date
18-Apr-2018
Definition at line 712 of file w3smcomd.F90.
     IMPLICIT NONE
     ! Input parameters:
     REAL, INTENT(IN)    :: S(:)        ! Inupt array
     REAL, INTENT(OUT)   :: XY(NXO,NYO) ! Output data
     LOGICAL, INTENT(IN) :: DIRN        ! Directional field?
     ! Local parameters
     INTEGER           :: I, J, IX, IY, ISEA, ISMC
     DO ix = 1,nxo
       DO iy = 1,nyo
         isea = nnidx(ix,iy) ! Nearest neighbour SMC point
         IF(isea .EQ. -1) THEN
           ! Land
           xy(ix,iy) = undef
         ELSE
           IF(s(isea) .EQ. undef) THEN
             ! Set undefined sea points to NOVAL
             xy(ix,iy) = noval
           ELSE
             xy(ix,iy) = s(isea)
             IF(dirn) THEN
               ! Convert direction fields to degrees nautical
               xy(ix,iy) = mod(630. - rade * xy(ix,iy), 360.0)
             ENDIF
           ENDIF
         ENDIF
       ENDDO
     ENDDO
References nnidx, noval, constants::rade, and constants::undef.
Referenced by w3s2xy_smc().
w3s2xy_smcnn_int()
subroutine w3smcomd::w3s2xy_smcnn_int (real, dimension(:), intent(in) S, real, dimension(nxo,nyo), intent(out) XY, logical, intent(in) DIRN)
Nearest neighbour interpolation.
Fill regular grid using nearest SMC point data and interpolate output value based on local gradient and distance between grid cell centres.
Directional fields (DIRN=True) will be assumed to be in radians and will be converted to degrees in nautical convention.
Parameters
[in] S Input array on SMC grid
[out] XY Output array to store interpolated 2D field
[in] DIRN Set to .TRUE. if S is a directional field
Author
Chris Bunney
Date
18-Apr-2018
Definition at line 763 of file w3smcomd.F90.
     USE w3psmcmd, ONLY: smcgradn
     IMPLICIT NONE
     ! Input parameters:
     REAL, INTENT(IN)    :: S(:)        ! Input array
     REAL, INTENT(OUT)   :: XY(NXO,NYO) ! Output array
     LOGICAL, INTENT(IN) :: DIRN        ! Directional field?
     ! Locals
     INTEGER           :: I, J, IX, IY, ISEA, ISMC
     REAL              :: CVQ(-9:NSEA)
     REAL              :: GrdX(NSEA), GrdY(NSEA)
     ! Calculate local gradients:
     cvq(1:nsea) = s ! Need to copy S into array with bounds starting at -9
     CALL smcgradn(cvq, grdx, grdy, 0)
     ! Interpolate:
     DO ix = 1,nxo
       DO iy = 1,nyo
         isea = nnidx(ix,iy) ! Nearest neighbour SMC point
         IF(isea .EQ. -1) THEN
           xy(ix,iy) = undef
         ELSE
           ! Interpolate using local gradient and distance from cell centre:
           xy(ix,iy) = s(isea) + grdx(isea) * xdist(ix,iy) + grdy(isea) * ydist(ix,iy)
           IF(dirn) THEN
             ! Convert direction fields to degrees nautical
             xy(ix,iy) = mod(630. - rade * xy(ix,iy), 360.0)
           ENDIF
         ENDIF
       ENDDO
     ENDDO
References nnidx, constants::rade, w3psmcmd::smcgradn(), constants::undef, xdist, and ydist.
Referenced by w3s2xy_smc().
w3s2xy_smcrg()
subroutine w3smcomd::w3s2xy_smcrg (real, dimension(:), intent(in) S, real, dimension(nxo,nyo), intent(out) XY)
Regrid SMC data onto a regular grid.
Regrids scalar data from the SMC grid onto a regular grid. Uses pre-calculated grid indices and weights generated from the smc_interp() subroutine.
Remarks
If source field is directional data, use the w3s2xy_smcrg_dir() subroutine instead.
Parameters
[in] S Source field, on SMC grid.
[out] XY Storage for regridded field; must be 2D array with dimensions of (NXO,NYO).
Author
Chris Bunney
Date
02-Jul-2013
Definition at line 360 of file w3smcomd.F90.
     IMPLICIT NONE
     ! Input parameters:
     REAL, INTENT(IN)  :: S(:)
     REAL, INTENT(OUT) :: XY(NXO,NYO)
     ! Local parameters
     INTEGER           :: I, J, IX, IY, ISEA, ISMC
     ! Initialise coverage and output arrays:
     cov(:,:) = 0.0
     xy(:,:) = 0.0
     DO ismc=1,nsmc
       isea = smcidx(ismc)
       IF(s(isea) .EQ. undef) cycle   ! MDI
       ! Loop over number of spanned cells:
       DO i=0, xspan(isea) - 1
         DO j=0, yspan(isea) - 1
           ix = xidx(isea) + i
           iy = yidx(isea) + j
           ! Spans outside of grid?
           IF(ix .GT. nxo .OR. iy .GT. nyo) cycle
           ! Interpolate:
           xy(ix, iy) = xy(ix, iy) + s(isea) * wts(isea)
           ! Keep track of how much of cell is (wet) covered:
           cov(ix, iy) = cov(ix, iy) + wts(isea)
         ENDDO
       ENDDO
     ENDDO
     ! Create coastline by masking out areas with < 50% coverage:
     DO ix=1,nxo
       DO iy=1,nyo
         IF(mapsmc(ix,iy) .EQ. 0) THEN
           ! Make land point
           xy(ix,iy) = undef
         ELSE IF(cov(ix,iy) .LT. 0.5) THEN
           ! More than half of cell has UNDEF values - set to NOVAL:
           xy(ix,iy) = noval
         ELSE IF(cov(ix,iy) .LT. 1.0) THEN
           ! If coverage < 1.0, scale values back to full cell coverage.
           ! Without this step, points around coast could end up with lower
           ! waveheights due to weights not summing to 1.0:
           xy(ix,iy) = xy(ix,iy) * ( 1.0 / cov(ix,iy) )
         ENDIF
       ENDDO
     ENDDO
     RETURN
References cov, mapsmc, noval, nsmc, smcidx, constants::undef, wts, xidx, xspan, yidx, and yspan.
Referenced by w3s2xy_smc().
w3s2xy_smcrg_dir()
subroutine w3smcomd::w3s2xy_smcrg_dir (real, dimension(:), intent(in) S, real, dimension(nxo,nyo), intent(out) XY)
Regrid directional SMC data onto a regular grid.
Regrids directioanl scalar data from the SMC grid onto a regular grid. Uses pre-calculated grid indices and weights generated from the smc_interp() subroutine.
Remarks
Functionality as per w3s2xy_smc(), but decomposes the field into u/v components first to ensure proper area averaging of directional data (handles cyclic transition between 359 -> 0 degrees).
Parameters
[in] S Directional source field, on SMC grid.
[out] XY Storage for regridded field; must be 2D array with dimensions of (NXO,NYO).
Author
Chris Bunney
Date
02-Jul-2013
Definition at line 439 of file w3smcomd.F90.
     IMPLICIT NONE
     ! Input parameters:
     REAL, INTENT(IN)  :: S(:)
     REAL, INTENT(OUT) :: XY(NXO,NYO)
     ! Local parameters
     INTEGER           :: I, J, IX, IY, ISEA, ISMC
     REAL, ALLOCATABLE :: AUX1(:,:), AUX2(:,:)
     REAL              :: COSS, SINS
     ! Initialise coverage and output arrays:
     ALLOCATE(aux1(nxo,nyo),aux2(nxo,nyo))
     cov(:,:) = 0.0
     xy(:,:) = 0.0
     aux1(:,:) = 0.0
     aux2(:,:) = 0.0
     DO ismc=1,nsmc
       isea = smcidx(ismc)
       IF(s(isea) .EQ. undef) cycle   ! MDI
       coss = cos(s(isea))
       sins = sin(s(isea))
       ! Loop over number of spanned cells:
       DO i=0, xspan(isea) - 1
         DO j=0, yspan(isea) - 1
           ix = xidx(isea) + i
           iy = yidx(isea) + j
           ! Spans outside of grid?
           IF(ix .GT. nxo .OR. iy .GT. nyo) cycle
           ! Interpolate:
           !XY(IX, IY) = XY(IX, IY) + S(ISEA) * WTS(ISEA)
           aux1(ix, iy) = aux1(ix, iy) + coss * wts(isea)
           aux2(ix, iy) = aux2(ix, iy) + sins * wts(isea)
           ! Keep track of how much of cell is (wet) covered:
           cov(ix, iy) = cov(ix, iy) + wts(isea)
         ENDDO
       ENDDO
     ENDDO
     ! Create coastline by masking out areas with < 50% coverage:
     DO ix=1,nxo
       DO iy=1,nyo
         IF(mapsmc(ix,iy) .EQ. 0) THEN
           ! Make land point
           xy(ix,iy) = undef
         ELSE IF(cov(ix,iy) .LT. 0.5) THEN
           ! More than half of cell has UNDEF values - set to NOVAL
           xy(ix,iy) = noval
         ELSE IF(cov(ix,iy) .LT. 1.0) THEN
           ! If coverage < 1.0, scale values back to full cell coverage.
           ! Without this step, points around coast could end up with lower
           ! waveheights due to weights not summing to 1.0:
           xy(ix,iy) = atan2(aux2(ix,iy), aux1(ix,iy))
           xy(ix,iy) = mod(630. - rade * xy(ix,iy), 360. )
         ELSE
           xy(ix,iy) = atan2(aux2(ix,iy), aux1(ix,iy))
           xy(ix,iy) = mod(630. - rade * xy(ix,iy), 360. )
         ENDIF
       ENDDO
     ENDDO
     RETURN
References cov, mapsmc, noval, nsmc, constants::rade, smcidx, constants::undef, wts, xidx, xspan, yidx, and yspan.
Referenced by w3s2xy_smc().
Variable Documentation
celfac
integer w3smcomd::celfac
Output grid cell scaling factor; should be an integer power of 2.
Definition at line 92 of file w3smcomd.F90.
   INTEGER              :: CELFAC
Referenced by smc_interp(), and w3ounf().
cfac
integer w3smcomd::cfac
SMC scaling factor (number of levels)
Definition at line 108 of file w3smcomd.F90.
   INTEGER              :: CFAC
Referenced by smc_interp().
cov
real, dimension(:,:), allocatable w3smcomd::cov
Wet fraction (coverage) of cell.
Definition at line 98 of file w3smcomd.F90.
   REAL, ALLOCATABLE    :: COV(:,:)
Referenced by mapsta_smc(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
dlat
real w3smcomd::dlat
Base longitude cell size.
Definition at line 106 of file w3smcomd.F90.
   REAL                 :: DLAT
Referenced by calc_interp(), and smc_interp().
dlon
real w3smcomd::dlon
Base latitude cell size.
Definition at line 107 of file w3smcomd.F90.
   REAL                 :: DLON
Referenced by calc_interp(), and smc_interp().
dxo
double precision w3smcomd::dxo
Output grid cell longitude size.
Definition at line 81 of file w3smcomd.F90.
   DOUBLE PRECISION     :: DXO
Referenced by calc_interp(), read_smcint(), and smc_interp().
dyo
double precision w3smcomd::dyo
Output grid cell latitude size.
Definition at line 82 of file w3smcomd.F90.
   DOUBLE PRECISION     :: DYO
Referenced by calc_interp(), read_smcint(), and smc_interp().
exo
double precision w3smcomd::exo
Output grid final longitude.
Definition at line 79 of file w3smcomd.F90.
   DOUBLE PRECISION     :: EXO
Referenced by smc_interp(), and w3ounf().
eyo
double precision w3smcomd::eyo
Output grid final latitude.
Definition at line 80 of file w3smcomd.F90.
   DOUBLE PRECISION     :: EYO
Referenced by smc_interp(), and w3ounf().
mapsmc
integer, dimension(:,:), allocatable w3smcomd::mapsmc
Regridded MAPSTA.
Definition at line 99 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: MAPSMC(:,:)
Referenced by mapsta_smc(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
ndsmc
integer w3smcomd::ndsmc
ww3_smcint file unit number
Definition at line 116 of file w3smcomd.F90.
   INTEGER              :: NDSMC
Referenced by read_smcint().
nnidx
integer, dimension(:,:), allocatable w3smcomd::nnidx
Nearest neighbour SMC point to regular grid.
Definition at line 113 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: NNIDX(:,:)
Referenced by calc_interp(), read_smcint(), w3s2xy_smcnn(), and w3s2xy_smcnn_int().
noval
real w3smcomd::noval
Fill value for seapoints with no value.
Definition at line 110 of file w3smcomd.F90.
   REAL                 :: NOVAL
Referenced by w3ounf(), w3s2xy_smcnn(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
nsmc
integer w3smcomd::nsmc
Number of SMC cells used in regridding.
Definition at line 120 of file w3smcomd.F90.
   INTEGER              :: NSMC
Referenced by smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
nxo
integer w3smcomd::nxo
Output grid number of longitude cells.
Definition at line 83 of file w3smcomd.F90.
   INTEGER              :: NXO
Referenced by mapsta_smc(), read_smcint(), and smc_interp().
nyo
integer w3smcomd::nyo
Output grid number of latitude cells.
Definition at line 84 of file w3smcomd.F90.
   INTEGER              :: NYO
Referenced by mapsta_smc(), read_smcint(), and smc_interp().
smccx
integer, dimension(:), allocatable w3smcomd::smccx
SMC grid definition.
Longitude cell size factors
Definition at line 104 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: SMCCX(:)
smccy
integer, dimension(:), allocatable w3smcomd::smccy
Latitude cell size factors.
Definition at line 105 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: SMCCY(:)
smcidx
integer, dimension(:), allocatable w3smcomd::smcidx
Indices of SMC cells within output grid domain.
Definition at line 101 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: SMCIDX(:)
Referenced by smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
smcmask
logical, dimension(:), allocatable w3smcomd::smcmask
Mask for type 1 output (flat array)
Definition at line 100 of file w3smcomd.F90.
   LOGICAL, ALLOCATABLE :: SMCMASK(:)
Referenced by smc_interp(), and w3s2xy_smc().
smcnout
integer w3smcomd::smcnout
Number of SMC output cells.
Definition at line 119 of file w3smcomd.F90.
   INTEGER              :: SMCNOUT
smcotype
integer w3smcomd::smcotype
Type of SMC output: 1=seapoint grid of SMC cells; 2=regridding to regular grid; 3=interpolation to arbtrary grid; 4=nearest neighbour interpolation to arbitrary grid.
Definition at line 90 of file w3smcomd.F90.
   INTEGER              :: SMCOTYPE
Referenced by w3ounfmetamd::init_meta(), smc_interp(), w3ounf(), and w3s2xy_smc().
sxo
double precision w3smcomd::sxo
Output grid longitude origin.
Definition at line 77 of file w3smcomd.F90.
   DOUBLE PRECISION     :: SXO
Referenced by calc_interp(), read_smcint(), smc_interp(), and w3ounf().
syo
double precision w3smcomd::syo
Output grid latitude origin.
Definition at line 78 of file w3smcomd.F90.
   DOUBLE PRECISION     :: SYO
Referenced by calc_interp(), read_smcint(), smc_interp(), and w3ounf().
wts
real, dimension(:), allocatable w3smcomd::wts
Regridding weights.
Definition at line 97 of file w3smcomd.F90.
   REAL, ALLOCATABLE    :: WTS(:)
Referenced by mapsta_smc(), smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
xdist
real, dimension(:,:), allocatable w3smcomd::xdist
Lng.
distance to nearest neighbour
Definition at line 114 of file w3smcomd.F90.
   REAL, ALLOCATABLE    :: XDIST(:,:)
Referenced by calc_interp(), read_smcint(), and w3s2xy_smcnn_int().
xidx
integer, dimension(:), allocatable w3smcomd::xidx
X-indices of SMC cells in regular grid.
Definition at line 93 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: XIDX(:)
Referenced by mapsta_smc(), smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
xspan
integer, dimension(:), allocatable w3smcomd::xspan
Number of longitude cells SMC cell spans.
Definition at line 95 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: XSPAN(:)
Referenced by mapsta_smc(), smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
ydist
real, dimension(:,:), allocatable w3smcomd::ydist
Lat.
distance to nearest neighbour
Definition at line 115 of file w3smcomd.F90.
   REAL, ALLOCATABLE    :: YDIST(:,:)
Referenced by calc_interp(), read_smcint(), and w3s2xy_smcnn_int().
yidx
integer, dimension(:), allocatable w3smcomd::yidx
Y-Indices of SMC cells in regular grid.
Definition at line 94 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: YIDX(:)
Referenced by mapsta_smc(), smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().
yspan
integer, dimension(:), allocatable w3smcomd::yspan
Number of longitude cells SMC cell spans.
Definition at line 96 of file w3smcomd.F90.
   INTEGER, ALLOCATABLE :: YSPAN(:)
Referenced by mapsta_smc(), smc_interp(), w3s2xy_smcrg(), and w3s2xy_smcrg_dir().