WAVEWATCH III: wmwavemd Module Reference
wmwavemd Module Reference
Running the multi-grid version of WAVEWATCH III up to a given ending time for each grid.
Functions/Subroutines
subroutine wmwave (TEND)
Run multi-grid version of WAVEWATCH III.
subroutine wmprnt (MDSO, NRGRD, TSYNC, GRSTAT)
Print out action table in the log file log. mww3.
subroutine wmbcst (DATA, NR, IMOD, NMOD, ID)
Non-blocking broadcast for integer arrays.
subroutine wmwout (IMOD, NMOD, ID)
Non-blocking broadcast using dummy parameter to have output.
Detailed Description
Running the multi-grid version of WAVEWATCH III up to a given ending time for each grid.
Author
H. L. Tolman
Date
22-Mar-2021
Function/Subroutine Documentation
wmbcst()
subroutine wmwavemd::wmbcst (integer, dimension(nr), intent(inout) DATA, integer, intent(in) NR, integer, intent(in) IMOD, integer, intent(in) NMOD, integer, intent(in) ID)
Non-blocking broadcast for integer arrays.
Non-blocking broadcast, initially for times only, but made for any integer array. Sending data from first process in the model communicator to all processes that are in the overall communicator but not in the model communicator.
Standard send and receives using defined communicator. Send form first processor in communicator.
Parameters
[in,out] DATA Data to be send/received.
[in] NR Size of array.
[in] IMOD Model number.
[in] NMOD Number of models.
[in] ID ID number, used with NMOD for ITAG.
Author
H. L. Tolman
Date
02-Feb-2007
Definition at line 1952 of file wmwavemd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         02-Feb-2007 !
     !/                  +-----------------------------------+
     !/
     !/    02-Feb-2007 : Origination.                        ( version 3.10 )
     !/
     !  1. Purpose :
     !
     !     Non-blocking broadcast, initially for times only, but made for
     !     any integer array. Sending data from first process in the
     !     model cummunicator to all processes that are in the overall
     !     communicator but not in the model communicator.
     !
     !  2. Method :
     !
     !     Standard send and receives using defined communicator. Send
     !     form first processor in communicator.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       DATA    I.A.  I/O  Data to be send/received.
     !       NR      Int.   I   Size of array.
     !       IMOD    Int.   I   Model number.
     !       NMOD    Int.   I   Number of models.
     !       ID      Int.   I   ID number, used with NMOD for ITAG.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Sur.  W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      WMWAVE    Subr. WMWAVEMD Multi-grid wave model routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/MPIT Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !
 #ifdef W3_MPI
     USE wmmdatmd, ONLY: mdst, mtagb, improc, nmproc, allprc,   &
          croot, mpi_comm_mwave
 #endif
     !
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
 #ifdef W3_MPI
     include "mpif.h"
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NR, IMOD, NMOD, ID
     INTEGER, INTENT(INOUT)  :: DATA(NR)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_MPI
     INTEGER                 :: ITAG, IP, IERR_MPI,             &
          STATUS(MPI_STATUS_SIZE)
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMBCST')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 0.  Initializations
     !
 #ifdef W3_MPI
     itag   = mtagb + imod + id*nmod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Processor to send data from
     !
 #ifdef W3_MPI
     IF ( allprc(improc,imod) .EQ. 1 ) THEN
       DO ip=1, nmproc
         IF ( allprc(ip,imod) .EQ. 0 ) THEN
 #endif
 #ifdef W3_MPI
           CALL mpi_send ( DATA, nr, mpi_integer, ip-1,     &
                itag, mpi_comm_mwave, ierr_mpi )
         END IF
       END DO
 #endif
       !
       ! -------------------------------------------------------------------- /
       ! 2.  Processor to receive data at
       !
 #ifdef W3_MPI
     ELSE IF ( allprc(improc,imod) .EQ. 0 ) THEN
 #endif
 #ifdef W3_MPI
       CALL mpi_recv ( DATA, nr, mpi_integer, croot-1, itag,  &
            mpi_comm_mwave, status, ierr_mpi )
 #endif
       !
       ! -------------------------------------------------------------------- /
       ! 3.  Processor with no action
       !
 #ifdef W3_MPI
     END IF
 #endif
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_MPIT
 9000 FORMAT ( ' TEST WMBCST : INPUTS :',4i4)
 9001 FORMAT ( ' TEST WMBCST : IMPROC, NMPROC:',2i5,'  ALLPRC :')
 9002 FORMAT (14x,13i5)
 #endif
     !
 #ifdef W3_MPIT
 9010 FORMAT ( ' TEST WMBCST : IAPROC =',i5,'    SENDING TO ',i5)
 #endif
     !
 #ifdef W3_MPIT
 9020 FORMAT ( ' TEST WMBCST : IAPROC =',i5,                    &
          '    RECEIVING FROM ',i5)
 #endif
     !
 #ifdef W3_MPIT
 9030 FORMAT ( ' TEST WMBCST : IAPROC =',i5,'    NO ACTION')
 #endif
     !/
     !/ End of WMBCST ----------------------------------------------------- /
     !/
References wmmdatmd::allprc, wmmdatmd::croot, wmmdatmd::improc, include(), wmmdatmd::mdst, wmmdatmd::mpi_comm_mwave, wmmdatmd::mtagb, wmmdatmd::nmproc, and w3servmd::strace().
Referenced by wmwave().
wmprnt()
subroutine wmwavemd::wmprnt (integer, intent(in) MDSO, integer, intent(in) NRGRD, integer, dimension(2), intent(in) TSYNC, integer, dimension(nrgrd), intent(in) GRSTAT)
Print out action table in the log file log. mww3.
Parameters
[in] MDSO
[in] NRGRD Number of grids.
[in] TSYNC Synchronization time.
[in] GRSTAT Status array per grid.
Author
H. L. Tolman
Date
22-Feb-2005
Definition at line 1777 of file wmwavemd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Feb-2005 |
     !/                  +-----------------------------------+
     !/
     !/    22-Feb-2005 : Origination.                        ( version 3.07 )
     !/
     !  1. Purpose :
     !
     !     Print out action table in the log file log.ww3m
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NRGRD   Int.   I   Number of grids.
     !       TSYN    I.A.   I   Synchronization time.
     !       GRSTAT  I.A.   I   Status array per grid.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      STME21    Subr. W3TIMEMD Print date and time readable.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      WMWAVE    Subr. WMWAVEMD Multi-grid wave model routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S     Enable subroutine tracing.
     !     !/T     Test output.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     USE w3timemd, ONLY: stme21
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: MDSO, NRGRD, TSYNC(2), GRSTAT(NRGRD)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER, PARAMETER      :: IW = 15
     INTEGER                 :: I, I0, IN
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     INTEGER, SAVE           :: IDLAST(2)
     LOGICAL, SAVE           :: FIRST = .true.
     CHARACTER(LEN=23)       :: IDTIME
     CHARACTER(LEN=3)        :: STR(IW), LNE(IW)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMPRNT')
 #endif
     !
     DO i=1, iw
       lne(i) = '---'
     END DO
     !
     IF ( first ) THEN
       WRITE (mdso,900) nrgrd, lne, '-+'
       first  = .false.
       idlast(1) = -1
       idlast(2) =  0
     ELSE
       backspace(mdso)
     END IF
     !
     CALL stme21 ( tsync, idtime )
     !
     DO i=1, min(iw,nrgrd)
       WRITE (str(i),'(I3)') grstat(i)
     END DO
     DO i=1+min(iw,nrgrd), iw
       str(i) = '   '
     END DO
     !
     IF ( idlast(1).EQ.tsync(1) .AND. idlast(2).EQ.tsync(2) ) THEN
 #ifdef W3_O11
       WRITE (mdso,903) str, ' |'
 #endif
     ELSE IF ( idlast(1) .EQ. tsync(1) ) THEN
       WRITE (mdso,902) idtime(12:19), str, ' |'
     ELSE
       WRITE (mdso,901) idtime(01:19), str, ' |'
     END IF
     idlast = tsync
     !
     IF ( nrgrd .GT. iw ) THEN
       i0     = 1
       in     = iw
       DO
         i0     = i0 + iw
         in     = in + iw
         DO i=i0, min(in,nrgrd)
           WRITE (str(i-i0+1),'(I3)') grstat(i)
         END DO
         DO i=1+min(in,nrgrd), in
           str(i-i0+1) = '   '
         END DO
         WRITE (mdso,903) str, ' |'
         IF ( in .GE. nrgrd ) EXIT
       END DO
     END IF
     !
     WRITE (mdso,904) lne, '-+'
     !
     RETURN
     !
     ! Formats
     !
 900 FORMAT (1x,' Time (sync rank 1)  | Status for',i3,' grids'/     &
          1x,'---------------------+',16a)
 901 FORMAT (2x,a19,' |',16a)
 902 FORMAT (2x,11x,a8,' |',16a)
 903 FORMAT (21x,' |',16a)
 904 FORMAT (1x,'---------------------+',16a)
     !/
     !/ End of WMPRNT ----------------------------------------------------- /
     !/
References w3timemd::stme21(), and w3servmd::strace().
Referenced by wmwave().
wmwave()
subroutine wmwavemd::wmwave (integer, dimension(2,nrgrd), intent(in) TEND)
Run multi-grid version of WAVEWATCH III.
Parameters
[in] TEND Ending time for calculations for each grid.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 91 of file wmwavemd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    13-Jun-2005 : Origination.                        ( version 3.07 )
     !/    30-Jan-2006 : Add static nesting.                 ( version 3.08 )
     !/    25-May-2006 : Add overlapping grids.              ( version 3.09 )
     !/    09-Aug-2006 : Unified point output added.         ( version 3.10 )
     !/    22-Dec-2006 : Final algorith changes for tests.   ( version 3.10 )
     !/    25-Jan-2007 : Tweaking algorithm.                 ( version 3.10 )
     !/    02-Feb-2007 : Replacing MPI_BCAST with WMBCST.    ( version 3.10 )
     !/    07-Feb-2007 : Reintroduce pre-fetching.           ( version 3.10 )
     !/    10-May-2007 : Removing / streamlining WMBCST.     ( version 3.11 )
     !/    21-Jun-2007 : Dedicated output processes.         ( version 3.11 )
     !/    20-Sep-2007 : Fix reset of GRSTAT in 0.b          ( version 3.13 )
     !/    20-Aug-2010 : Fix MAPSTA/MAPST2 bug sec. 9.a.   ( version 3.14.6 )
     !/    12-Mar-2012 : Use MPI_COMM_NULL for checks.       ( version 3.14 )
     !/    28-Jan-2014 : Add memory hwm to profiling.        ( version 5.00 )
     !/    22-Mar-2021 : Support for air density input       ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Run multi-grid version of WAVEWATCH III.
     !
     !  2. Method :
     !
     !     See manual.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       TEND    I.A.   I   Ending time for calculations for each grid.
     !     ----------------------------------------------------------------
     !
     !     Local variables
     !     ----------------------------------------------------------------
     !       J       Int.   Group counter.
     !       JJ      Int.   Grid in group counter.
     !       I       Int.   Grid counter.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SETG    Subr  W3GDATMD Point to grid/model.
     !      W3SETW    Subr  W3WDATMD Point to grid/model.
     !      W3SETA    Subr  W3ADATMD Point to grid/model.
     !      W3SETO    Subr  W3ODATMD Point to grid/model.
     !      W3IOPE    Subr  W3IOPOMD Extracting point output.
     !      W3WAVE    Subr  W3WAVEMD Actual ave model routine.
     !      STRACE    Subr  W3SERVMD Subroutine tracing.
     !      EXTCDE    Subr    Id.    Abort program with exit code.
     !      WWTIME    Subr    Id.    System time in readable format.
     !      PRTIME    Subr    Id.    Profiling routine ( !/MPRF )
     !      STME21    Subr  W3TIMEMD Print date and time readable.
     !      DSEC21    Func    Id.    Difference between times.
     !      TICK21    Subr    Id.    Advance time.
     !      WMSETM    Subr  WMMDATMD Point to grid/model.
     !      WMUPDT    Subr  WMUPDTMD Update input fields at driver level.
     !      WMIOBG    Subr  WMINIOMD Gather staged boundary data.
     !      WMIOBS    Subr    Id.    Stage boundary data.
     !      WMIOBF    Subr    Id.    Finalize WMIOBS.            ( !/MPI )
     !      WMIOHS    Subr    Id.    Stage high-to-low data.
     !      WMIOHG    Subr    Id.    Gather staged high-to-low data.
     !      WMIOHF    Subr    Id.    Finalize WMIOHS.            ( !/MPI )
     !      WMIOES    Subr    Id.    Stage same-rank data.
     !      WMIOEG    Subr    Id.    Gather staged same-rank data.
     !      WMIOEF    Subr    Id.    Finalize WMIOES.            ( !/MPI )
     !      WMIOPO    Subr  WMIOPOMD Unified point output.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3MLTI    Prog.   N/A    Multi-grid model driver.
     !      ....                     Any coupled model.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     See formats 1000 and following, or escape locations 2000 and
     !     following.
     !
     !  7. Remarks :
     !
     !     - If no action is taken in the endless loop, an error is
     !       assumed (code 2099). This should never take place in the
     !       default driver, but may be a problem in a coupled model.
     !     - If output is requested for the initial model time, TSYNC
     !       is set to TIME instead of (-1,0) for GRSTAT = 0. In this case
     !       input is updated, after which GRSTAT is set to 6 instead
     !       of 1. This assures that restarts do not impact model results
     !       by spurious double reconciliations.
     !
     !  8. Structure :
     !
     !     See source code and manual.
     !
     !  9. Switches :
     !
     !       !/S     Enable subroutine tracing.
     !       !/T     Enable test output.
     !       !/MPIT  Enable test output (use with !/MPI only).
     !       !/MPRF  Profiling.
     !
     !       !/SHRD, !/DIST, !/MPI
     !               Shared / distributed program model.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants
     !/
     USE w3gdatmd, ONLY: w3setg
     USE w3wdatmd, ONLY: w3setw
     USE w3adatmd, ONLY: w3seta
     USE w3odatmd, ONLY: w3seto, notype
     USE w3iopomd, ONLY: w3iope
     USE w3wavemd, ONLY: w3wave
     USE w3servmd, ONLY: extcde, wwtime
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
 #ifdef W3_MPRF
     USE w3timemd, ONLY: prtime
 #endif
     USE w3timemd, ONLY: dsec21, stme21, tick21
     USE wmmdatmd, ONLY: wmsetm
     USE wmupdtmd, ONLY: wmupdt
     USE wminiomd, ONLY: wmiobg, wmiobs, wmiobf, wmiohg, wmiohs,     &
          wmiohf, wmioeg, wmioes, wmioef
     USE wmiopomd, ONLY: wmiopo
     !/
     USE w3gdatmd, ONLY: dtmax, nx, ny, mapsta, mapst2
     USE w3wdatmd, ONLY: time, va
     USE w3odatmd, ONLY: flout, tonext, dtout, tolast, iaproc,       &
          nappnt, nopts, unipts
 #ifdef W3_MPI
     USE w3odatmd, ONLY: nrqpo, irqpo1
 #endif
     USE w3idatmd, ONLY: inflags1
     USE wmmdatmd, ONLY: mdso, mdss, mdst, mdse, improc,             &
          nmproc, nmpscr, nmperr, nmptst, nmplog,     &
          stime, etime, nmv, tmv, amv, dmv,           &
          nrgrd, nrgrp, grank, ingrp, grdhgh, grdeql, &
          grdlow, tsync, tmax, toutp, tdata, grstat,  &
          fllstl, fllsti, fllstr, dtres, flghg1,      &
          flghg2, mapmsk
 #ifdef W3_MPI
     USE wmmdatmd, ONLY: mpi_comm_mwave, mpi_comm_grd,          &
          mpi_comm_bct, croot, fbcast
 #endif
 #ifdef W3_MPRF
     USE wmmdatmd, ONLY: mdsp
 #endif
     !/
     IMPLICIT NONE
     !
 #ifdef W3_MPI
     include "mpif.h"
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: TEND(2,NRGRD)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: J, JJ, I, JO, TPRNT(2), TAUX(2),     &
          II, JJJ, IX, IY, UPNEXT(2), UPLAST(2)
     INTEGER                 :: DUMMY2(35)=0
 #ifdef W3_T
     INTEGER                 :: ILOOP
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
 #ifdef W3_MPI
     INTEGER                 :: IERR_MPI, NMPSCS
     INTEGER, ALLOCATABLE    :: STATUS(:,:)
 #endif
     REAL                    :: DTTST, DTMAXI
 #ifdef W3_MPRF
     REAL                    :: PRFT0, PRFTN, PRFTS
     REAL(KIND=8)            :: get_memory
 #endif
     CHARACTER(LEN=8)        :: WTIME
     CHARACTER(LEN=23)       :: MTIME
     LOGICAL                 :: DONE, TSTAMP, FLAGOK, DO_UPT,        &
          FLG_O1, FLG_O2
 #ifdef W3_MPI
     LOGICAL                 :: FLAG
 #endif
     LOGICAL, ALLOCATABLE    :: FLSYNC(:), GRSYNC(:), TMSYNC(:),     &
          FLEQOK(:)
 #ifdef W3_MPI
     LOGICAL, ALLOCATABLE    :: PREGTB(:), PREGTH(:), PREGTE(:)
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !
 #ifdef W3_S
     CALL strace (ient, 'WMWAVE')
 #endif
     !
 #ifdef W3_MPRF
     CALL prtime ( prft0 )
 #endif
     !
 #ifdef W3_O10
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc ) WRITE (mdss,900)
 #endif
     !
     ! 0.  Initializations ------------------------------------------------ /
     ! 0.a Initial testing
     !     Test GRSTAT
     !
     DO i=1, nrgrd
       IF ( ( grstat(i).LT.0 .OR. grstat(i).GT.7 ) .AND.             &
            grstat(i).NE.99 ) GOTO 2000
       !
       !     Consistency of times for grids
       !
       IF ( tsync(1,i) .NE. -1 ) THEN
         dttst  = dsec21( tsync(:,i), tend(:,i) )
         IF ( dttst .LT. 0. ) GOTO 2001
       END IF
     END DO
     !
     !     Consistency of times within groups, set global TSYNC(:,0)
     !
     DO j=1, nrgrp
       DO jj=2, ingrp(j,0)
         IF ( dsec21(tsync(:,ingrp(j,1)),tsync(:,ingrp(j,jj))).NE.0. &
              .OR. dsec21(tend(:,ingrp(j,1)),tend(:,ingrp(j,jj))).NE.0. ) &
              GOTO 2002
       END DO
       IF ( grank(ingrp(j,1)).EQ.1 .AND. tsync(1,0).EQ.-1 )          &
            tsync(:,0) = tsync(:,ingrp(j,1))
     END DO
     !
     !     Check if FLSYNC initialized
     !
     IF ( .NOT. ALLOCATED(flsync) ) THEN
       ALLOCATE ( flsync(nrgrd), grsync(nrgrp), tmsync(nrgrd),     &
            fleqok(nrgrd) )
 #ifdef W3_MPI
       ALLOCATE ( pregtb(nrgrd), pregth(nrgrd), pregte(nrgrd) )
 #endif
       flsync = .false.
       grsync = .false.
       tmsync = .true.
       fleqok = .false.
 #ifdef W3_MPI
       pregtb = .false.
       pregth = .false.
       pregte = .false.
 #endif
     END IF
     !
     ! 0.b Reset GRSTAT as needed
     !
     DO i=1, nrgrd
       CALL w3setw ( i, mdse, mdst )
       dttst  = dsec21( time, tend(:,i) )
       IF ( grstat(i).EQ.99 .AND. dttst.GT.0. ) grstat(i) = 0
     END DO
     !
     ! 0.c Other initializations
     !
     dtres  = 0.
 #ifdef W3_MPI
     nmpscs = nmpscr
 #endif
     !
     IF ( unipts ) THEN
       CALL w3seto ( 0, mdse, mdst )
       upnext = tonext(:,2)
       uplast = tolast(:,2)
       do_upt = .true.
     ELSE
       upnext(1) = -1
       upnext(2) =  0
       do_upt = .false.
     END IF
     !
     ! 0.d Output
     !
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc ) THEN
       CALL wmprnt ( mdso, nrgrd, tsync(:,0), grstat )
       CALL stme21 ( tsync(:,0), mtime )
       CALL wwtime ( wtime )
       WRITE (mdss,901) mtime, wtime, minval(grstat), maxval(grstat)
       tprnt  = tsync(:,0)
       tstamp = .true.
     ENDIF
     !
 #ifdef W3_MPI
     CALL mpi_barrier (mpi_comm_mwave,ierr_mpi)
 #endif
     !
 #ifdef W3_MPRF
     CALL prtime ( prftn )
     WRITE (mdsp,990) prft0, prftn, get_memory()
 #endif
     !
     ! 1.  Setting up loop structure -------------------------------------- /
     !
 #ifdef W3_T
     iloop  = 0
 #endif
     !
     loop_outer: DO
       !
       IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc .AND.                &
            dsec21(tprnt,tsync(:,0)).NE.0. ) THEN
         IF ( .NOT. tstamp ) WRITE (mdss,*)
         CALL wmprnt ( mdso, nrgrd, tsync(:,0), grstat )
         CALL stme21 ( tsync(:,0), mtime )
         CALL wwtime ( wtime )
         WRITE (mdss,901) mtime, wtime, minval(grstat), maxval(grstat)
         !
         tprnt  = tsync(:,0)
         tstamp = .true.
       ENDIF
       !
 #ifdef W3_T
       iloop  = iloop + 1
       WRITE (mdst,9000) iloop, tsync(:,0)
       DO i=1, nrgrd
         CALL w3setw ( i, mdse, mdst )
         WRITE (mdst,9001) i, grstat(i), time, tsync(:,i), tend(:,i)
       END DO
       IF ( iloop .EQ. -1 ) CALL extcde ( 508 )
 #endif
       !
       done   = .false.
       tprnt  = tsync(:,0)
       !
       loop_j: DO j=1, nrgrp
         !
 #ifdef W3_MPI
         grsync(j) = .false.
         DO jj=1, ingrp(j,0)
           i      = ingrp(j,jj)
           CALL wmsetm ( i, mdse, mdst )
           grsync(j) = grsync(j) .OR. fbcast
         END DO
 #endif
         !
         loop_jj: DO jj=1, ingrp(j,0)
           i      = ingrp(j,jj)
           CALL wmsetm ( i, mdse, mdst )
           !
 #ifdef W3_MPI
           IF ( grstat(i).EQ.0 ) tmsync(i) = .NOT. fbcast
           IF ( fbcast ) THEN
             nmpscr = croot
           ELSE
             nmpscr = nmpscs
           END IF
 #endif
           !
           ! 2.  Update input fields -------------------------------------------- /
           !     ( GRSTAT = 0 )
           !
           ! 2.a Check TDATA and finish step if data is still OK
           !
 #ifdef W3_SHRD
           IF ( grstat(i) .EQ. 0 ) THEN
 #endif
 #ifdef W3_MPI
             IF ( grstat(i).EQ.0 .AND. .NOT.flsync(i) ) THEN
 #endif
               !
 #ifdef W3_T
               WRITE (mdst,9002) i, grstat(i), ' '
 #endif
               !
               IF ( tdata(1,i) .EQ. -1 ) THEN
                 dttst  = 0.
               ELSE
                 CALL w3setw ( i, mdse, mdst )
                 dttst  = dsec21( time , tdata(:,i) )
               END IF
 #ifdef W3_T
               WRITE (mdst,9020) dttst
 #endif
               !
               IF ( dttst .GT. 0. ) THEN
                 grstat(i) = 1
 #ifdef W3_T
                 WRITE (mdst,9003) i, grstat(i)
 #endif
                 done      = .true.
               END IF
               !
 #ifdef W3_MPI
             END IF ! IF ( GRSTAT(I).EQ.0 .AND. .NOT.FLSYNC(I)
 #endif
 #ifdef W3_SHRD
           END IF ! IF ( GRSTAT(I) .EQ. 0 )
 #endif
           !
           ! 2.b Update input and TDATA
           !
 #ifdef W3_SHRD
           IF ( grstat(i) .EQ. 0 ) THEN
 #endif
 #ifdef W3_MPI
             IF ( grstat(i).EQ.0 .AND. .NOT.flsync(i) .AND.       &
                  mpi_comm_grd .NE. mpi_comm_null ) THEN
 #endif
               !
 #ifdef W3_MPRF
               CALL prtime ( prft0 )
 #endif
               IF ( dttst .LE. 0 ) THEN
                 IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc )        &
                      WRITE (mdss,*)
                 tstamp = .false.
                 CALL wmupdt ( i, tdata(:,i) )
 #ifdef W3_T
                 WRITE (mdst,9021) time, tdata(:,i), tend(:,i)
 #endif
               END IF
               !
               ! 2.c Finish up if possible ( !/SHRD or .NOT. FBCAST or no update )
               !
 #ifdef W3_SHRD
               grstat(i) = 1
               done      = .true.
 #endif
               !
 #ifdef W3_MPI
               IF ( .NOT. grsync(j) ) THEN
 #endif
 #ifdef W3_MPIT
                 WRITE (mdst,9902) i, grstat(i),             &
                      'NO SYNC FOR TDATA NEEDED'
 #endif
 #ifdef W3_MPI
                 grstat(i) = 1
                 done      = .true.
               END IF ! IF ( .NOT. GRSYNC(J) )
 #endif
               !
 #ifdef W3_MPRF
               CALL prtime ( prftn )
               WRITE (mdsp,991) prft0, prftn, get_memory(),    &
                    'ST00', i
 #endif
               !
 #ifdef W3_MPI
             END IF ! IF ( GRSTAT(I).EQ.0 .AND. .NOT.FLSYNC(I) .AND. MPI_COMM_GRD .NE. MPI_COMM_NULL )
 #endif
 #ifdef W3_SHRD
           END IF ! IF ( GRSTAT(I) .EQ. 0 )
 #endif
           !
           ! 2.d Synchronize in parts ( !/MPI )
           !
 #ifdef W3_MPI
           IF ( grstat(i).EQ.0 .AND. grsync(j) ) THEN
             done   = .true.
 #endif
             !
 #ifdef W3_MPI
             IF ( flsync(i) ) THEN
 #endif
 #ifdef W3_MPIT
               WRITE (mdst,9902) i, grstat(i),             &
                    'SYNCING TDATA'
 #endif
 #ifdef W3_MPRF
               IF (flsync(i)) CALL prtime ( prft0 )
 #endif
 #ifdef W3_MPI
               IF ( fbcast ) CALL wmbcst                    &
                    ( tdata(1,i), 2, i, nrgrd, 1 )
 #endif
 #ifdef W3_MPRF
               IF (flsync(i)) CALL prtime ( prftn )
               IF (flsync(i)) WRITE (mdsp,991)             &
                    prft0, prftn, get_memory(), 'BCST',i
 #endif
 #ifdef W3_MPIT
               WRITE (mdst,9902) i, grstat(i), 'SYNCING DONE'
 #endif
 #ifdef W3_MPI
               grstat(i) = 1
               flsync(i) = .false.
               IF ( grsync(j) ) cycle loop_jj
             ELSE
 #endif
 #ifdef W3_MPIT
               WRITE (mdst,9902) i, grstat(i),             &
                    'CYCLE BEFORE SYNCING TDATA'
 #endif
 #ifdef W3_MPI
               flsync(i) = .true.
               cycle loop_jj
             END IF ! IF ( FLSYNC(I) )
 #endif
             !
 #ifdef W3_MPI
           END IF ! IF ( GRSTAT(I).EQ.0 .AND. GRSYNC(J)
 #endif
           !
           ! 3.  Update data from lower ranked grids ---------------------------- /
           !     ( GRSTAT = 1 )
           !
           ! 3.a Skip for initial output only
           !
           IF ( grstat(i) .EQ. 1 .AND. tsync(1,i) .NE. -1 ) THEN
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), 'FIRST PART'
 #endif
             CALL w3setw ( i, mdse, mdst )
             dttst  = dsec21( time, tsync(:,i) )
             IF ( dttst .EQ. 0. ) THEN
               grstat(i) = 7
 #ifdef W3_T
               WRITE (mdst,9003) i, grstat(i)
 #endif
               done      = .true.
             END IF
           END IF ! IF ( GRSTAT(I) .EQ. 1 .AND. TSYNC(1,I) .NE. -1 )
           !
           ! 3.b Normal processing
           !
           IF ( grstat(i) .EQ. 1 ) THEN
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), 'SECOND PART'
 #endif
 #ifdef W3_MPRF
             CALL prtime ( prft0 )
 #endif
             !
             ! 3.b.1 Test if data is there
             !
             flagok = .true.
             CALL w3setw ( i, mdse, mdst )
             taux   = time
             DO jjj=1, grdlow(i,0)
               CALL w3setw ( grdlow(i,jjj), mdse, mdst )
               flagok = flagok .AND. dsec21(taux,time).GT.0.       &
                    .AND. grstat(grdlow(i,jjj)).EQ.5
             END DO
             CALL w3setw ( i, mdse, mdst )
             !
 #ifdef W3_T
             WRITE (mdst,9004) flagok
 #endif
             !
             ! 3.b.1 Get the data
             !
 #ifdef W3_MPI
             IF ( .NOT.flagok .AND. .NOT.pregtb(i) ) THEN
               IF ( mpi_comm_grd.NE.mpi_comm_null )         &
                    CALL wmiobg (i,flag)
               pregtb(i) = .true.
             END IF
 #endif
             !
             IF ( flagok ) THEN
 #ifdef W3_SHRD
               CALL wmiobg ( i, flagok )
 #endif
 #ifdef W3_MPI
               IF ( mpi_comm_grd.NE.mpi_comm_null )         &
                    CALL wmiobg ( i )
               pregtb(i) = .false.
 #endif
               grstat(i) = 2
               done      = .true.
             END IF ! IF ( FLAGOK )
             !
 #ifdef W3_MPRF
             CALL prtime ( prftn )
             WRITE (mdsp,991) prft0, prftn, get_memory(),    &
                  'ST01', i
 #endif
           END IF ! IF ( GRSTAT(I) .EQ. 1 )
           !
           ! 4.  Update model time step ----------------------------------------- /
           !     ( GRSTAT = 2 )
           !
           IF ( grstat(i) .EQ. 2 ) THEN
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), ' '
 #endif
 #ifdef W3_MPRF
             CALL prtime ( prft0 )
 #endif
             !
             ! 4.a Check TMAX and update as necessary ( needs !/MPI synchronizaion )
             !
             CALL w3setw ( i, mdse, mdst )
             IF ( tmax(1,i) .EQ. -1 ) THEN
               tmax(:,i) = time
               dttst  = 0.
             ELSE
               dttst  = dsec21(time,tmax(:,i))
             END IF
             !
             IF ( dttst .LE. 0 ) THEN
               CALL w3setg ( i, mdse, mdst )
               dtmaxi = real(nint(dtmax+dtres(i)+0.0001))
               dtres(i)= dtres(i)+ dtmax - dtmaxi
               IF ( abs(dtres(i)) .LT. 0.001 ) dtres(i) = 0.
               tmax(:,i) = time
               CALL tick21 ( tmax(:,i), dtmaxi )
               taux   = tmax(:,i)
               IF ( tdata(1,i) .NE. -1 ) THEN
                 IF ( dsec21(tdata(:,i),tmax(:,i)) .GT. 0 )    &
                      tmax(:,i) = tdata(:,i)
               END IF
               IF ( toutp(1,i) .NE. -1 ) THEN
                 IF ( dsec21(toutp(:,i),tmax(:,i)) .GT. 0 )    &
                      tmax(:,i) = toutp(:,i)
               END IF
               IF ( unipts ) THEN
                 IF ( dsec21(upnext,tmax(:,i)) .GT. 0 )        &
                      tmax(:,i) = upnext(:)
               END IF
 #ifdef W3_T
               WRITE (mdst,9040) tmax(:,i), dtres(i), taux,   &
                    tdata(:,i), toutp(:,i), upnext
 #endif
               done   = .true.
               cycle loop_jj
 #ifdef W3_T
             ELSE
               WRITE (mdst,9041) tmax(:,i)
 #endif
             END IF ! IF ( DTTST .LE. 0 )
             !
             ! 4.b Lowest ranked grids, minimum of all TMAXes
             !
 #ifdef W3_T
             WRITE (mdst,9042) grank(i)
 #endif
             !
             IF ( grank(i) .EQ. 1 ) THEN
               !
               taux   = tmax(:,i)
               flagok = .true.
               !
               ! 4.b.1 Check if all grids have reached previous sync point
               !
               DO ii=1, nrgrd
                 CALL w3setw ( ii, mdse, mdst )
 #ifdef W3_SHRD
                 IF ( time(1) .NE. -1 ) THEN
 #endif
 #ifdef W3_MPI
                   IF ( time(1).NE.-1 .AND.                   &
                        mpi_comm_grd.NE.mpi_comm_null ) THEN
 #endif
                     IF ( dsec21(time,tsync(:,0)) .NE. 0 ) THEN
                       flagok = .false.
                       EXIT
                     END IF
 #ifdef W3_MPI
                   END IF ! IF ( TIME(1).NE.-1 .AND. MPI_COMM_GRD.NE.MPI_COMM_NULL )
 #endif
 #ifdef W3_SHRD
                 END IF ! IF ( TIME(1) .NE. -1 ) THEN
 #endif
               END DO
               !
               ! 4.b.2 Check availability of data
               !
               DO ii=1, nrgrd
                 IF ( grank(ii) .EQ. 1 ) THEN
                   IF ( tmax(1,ii) .EQ. -1 ) THEN
                     flagok = .false.
                     EXIT
                   ELSE
                     IF ( dsec21(taux,tmax(:,ii)) .LT. 0. ) &
                          taux   = tmax(:,ii)
                   END IF
                 END IF
               END DO
               !
               CALL w3setw ( i, mdse, mdst )
               flagok = flagok .AND. dsec21(time,taux).GT.0.
               !
               ! 4.b.3 Update TSYNC for all grids
               !
               IF ( flagok ) THEN
                 !
                 tsync(:,0) = taux
                 do_upt = .true.
                 DO ii=1, nrgrd
                   IF ( grank(ii) .EQ. 1 ) THEN
                     tsync(:,ii) = taux
                     IF ( grstat(ii) .EQ. 2 ) grstat(ii) = 3
 #ifdef W3_T
                     IF ( grstat(ii) .EQ. 3 )             &
                          WRITE (mdst,9003) ii, grstat(ii)
 #endif
                   END IF
                 END DO
                 done   = .true.
 #ifdef W3_MPRF
                 CALL prtime ( prfts )
                 WRITE (mdsp,992) prfts, prfts,          &
                      get_memory(), 'TIME', tsync(:,0)
 #endif
                 !
                 ! 4.b.4 Output
                 !
 #ifdef W3_T
                 WRITE (mdst,9043) tsync(:,0)
                 WRITE (mdst,9045)
                 WRITE (mdst,9046) (ii,tsync(:,ii),ii=0,nrgrd)
 #endif
                 !
                 ! 4.b.5 Skip computations so that all grids start processing
                 !       simultaneously.
                 !
 #ifdef W3_MPRF
                 CALL prtime ( prftn )
                 WRITE (mdsp,991) prft0, prftn,          &
                      get_memory(), 'ST02', i
 #endif
 #ifdef W3_T
                 IF ( ingrp(j,0) .GT. 1 ) WRITE (mdst,9006)
 #endif
                 IF ( ingrp(j,0) .GT. 1 ) GOTO 1111
                 !
               END IF ! IF ( FLAGOK )
               !
               ! 4.c Other grids, logical from relations and TMAXes
               !
             ELSE IF ( tsync(1,0) .NE. -1 ) THEN
               !
               taux   = tsync(:,0)
               flagok = .true.
               !
               ! 4.c.1 Check availability of data within group
               !       Time within group needs to be the same for load balancing.
               !
               DO jjj=1, ingrp(j,0)
                 ii     = ingrp(j,jjj)
                 IF ( tmax(1,ii) .EQ. -1 ) THEN
                   flagok = .false.
                   EXIT
                 ELSE
                   IF ( dsec21(taux,tmax(:,ii)) .LT. 0. )     &
                        taux   = tmax(:,ii)
                 END IF
               END DO
               !
               ! 4.c.2 Check with dependent lower rank grids ( TSYNC )
               !
               DO jjj=1, grdlow(i,0)
                 ii     = grdlow(i,jjj)
                 IF ( tsync(1,ii) .EQ. -1 ) THEN
                   flagok = .false.
                   EXIT
                 ELSE
                   IF ( dsec21(taux,tsync(:,ii)) .LT. 0. )     &
                        taux   = tsync(:,ii)
                 END IF
               END DO
               !
               ! 4.c.3 Check with dependent higher rank grids ( TSYNC )
               !       No check needed
               !
               ! 4.c.4 Final check against grid time
               !
               CALL w3setw ( i, mdse, mdst )
               flagok = flagok .AND. dsec21(time,taux).GT.0.
               !
               ! 4.c.5 Update TSYNC throughout group
               !
               IF ( flagok ) THEN
                 !
                 DO jjj=1, ingrp(j,0)
                   ii     = ingrp(j,jjj)
                   tsync(:,ii) = taux
                   IF ( grstat(ii) .EQ. 2 ) grstat(ii) = 3
 #ifdef W3_T
                   IF ( grstat(ii) .EQ. 3 )                 &
                        WRITE (mdst,9003) ii, grstat(ii)
 #endif
                 END DO
                 done   = .true.
                 !
 #ifdef W3_T
                 WRITE (mdst,9044) tsync(:,i), taux
                 WRITE (mdst,9045)
                 WRITE (mdst,9046) (ii,tsync(:,ii),ii=0,nrgrd)
 #endif
                 !
                 ! 4.c.6 Skip computations so that all grids in group are advanced
                 !       simultaneously.
 #ifdef W3_MPRF
                 CALL prtime ( prftn )
                 WRITE (mdsp,991) prft0, prftn,          &
                      get_memory(),  'ST02', i
 #endif
 #ifdef W3_T
                 IF ( ingrp(j,0) .GT. 1 ) WRITE (mdst,9006)
 #endif
                 IF ( ingrp(j,0) .GT. 1 ) GOTO 1111
                 !
               END IF ! IF ( FLAGOK )
               !
             END IF ! 4.b IF ( GRANK(I) .EQ. 1 )
             !
           END IF ! 4. IF ( GRSTAT(I) .EQ. 2 )
           !
           ! 5.  Run the wave model --------------------------------------------- /
           !     ( GRSTAT = 3 ) w3xdatmd data structures set in W3WAVE
           !
           ! 5.a Run model
           !
 #ifdef W3_SHRD
           IF ( grstat(i) .EQ. 3 ) THEN
 #endif
             !
 #ifdef W3_MPI
             IF ( grstat(i).EQ.3 .AND.                            &
                  mpi_comm_grd .EQ. mpi_comm_null ) THEN
               CALL w3setw ( i, mdse, mdst )
               time      = tsync(:,i)
               grstat(i) = 4
               done      = .true.
             ELSE IF ( grstat(i).EQ.3 .AND.                     &
                  mpi_comm_grd .NE. mpi_comm_null ) THEN
 #endif
               !
 #ifdef W3_T
               WRITE (mdst,9002) i, grstat(i), 'RUNNING MODEL'
 #endif
 #ifdef W3_MPRF
               CALL prtime ( prft0 )
 #endif
               !
               CALL wmsetm ( i, mdse, mdst )
               CALL w3wave ( i, dummy2, tsync(:,i), .false., .true. )
               IF ( fllstl ) inflags1(1) = .false.
               IF ( fllsti ) inflags1(4) = .false.
               IF ( fllstr ) inflags1(6) = .false.
               !
               ! 5.b Stage data for grids with equal rank
               !
 #ifdef W3_MPI
               CALL wmioef ( i )
 #endif
               CALL wmioes ( i )
               !
               ! 5.c Finish up
               !
               grstat(i) = 4
               done      = .true.
               !
 #ifdef W3_MPRF
               CALL prtime ( prftn )
               WRITE (mdsp,991) prft0, prftn, get_memory(),    &
                    'ST03', i
 #endif
               !
 #ifdef W3_MPI
             END IF ! IF ( GRSTAT(I).EQ.3 .AND. MPI_COMM_GRD .EQ. MPI_COMM_NULL )
 #endif
 #ifdef W3_SHRD
           END IF ! IF ( GRSTAT(I) .EQ. 3 )
 #endif
           !
           ! 6.  Reconcile grids with same rank --------------------------------- /
           !     and stage data transfer to higher and lower ranked grids.
           !     ( GRSTAT = 4 )
           !
           IF ( grstat(i) .EQ. 4 ) THEN
 #ifdef W3_MPRF
             CALL prtime ( prft0 )
 #endif
             !
             ! 6.a Test against times and statuses of dependent grids
             !     Note: This is done per GROUP, not per local equal grid dependence
             !           Therefore, it is essential that sync times per group are
             !           equal (4.c.1) and that all equal grid dependences are a
             !           subset of groups (WMGEQL 5.d)
             !
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), 'FIRST PART'
             WRITE (mdst,9005) fleqok(i)
 #endif
             !
             ! 6.a.1 Check if sync point is reached
             !
             IF ( .NOT. fleqok(i) ) THEN
               !
               flagok = .true.
               CALL w3setw ( i, mdse, mdst )
               taux   = time
               DO jjj=1, ingrp(j,0)
                 CALL w3setw ( ingrp(j,jjj), mdse, mdst )
                 flagok = flagok .AND. dsec21(taux,time).EQ.0.   &
                      .AND. grstat(ingrp(j,jjj)).EQ.4
               END DO
               CALL w3setw ( i, mdse, mdst )
 #ifdef W3_T
               WRITE (mdst,9004) flagok
 #endif
               !
               ! 6.a.2 Point reached, set flag for all in group and cycle
               !
               IF ( flagok ) THEN
                 DO jjj=1, ingrp(j,0)
                   fleqok(ingrp(j,jjj)) = .true.
 #ifdef W3_T
                   WRITE (mdst,9061) ingrp(j,jjj),      &
                        fleqok(ingrp(j,jjj))
 #endif
                 END DO
                 done      = .true.
 #ifdef W3_MPRF
                 CALL prtime ( prftn )
                 WRITE (mdsp,991) prft0, prftn,      &
                      get_memory(), 'ST04', i
 #endif
                 !
 #ifdef W3_T
                 IF ( ingrp(j,0) .GT. 1 ) WRITE (mdst,9006)
 #endif
                 IF ( ingrp(j,0) .GT. 1 ) GOTO 1111
               END IF ! IF ( FLAGOK )
               !
             END IF !  IF ( .NOT. FLEQOK(I) )
             !
             ! 6.b Call gathering routine, reset FLEQOK and cycle
             !
 #ifdef W3_MPI
             IF ( .NOT.fleqok(i) .AND. .NOT.pregte(i) ) THEN
               IF ( mpi_comm_grd.NE.mpi_comm_null )    &
                    CALL wmioeg (i,flag)
               pregte(i) = .true.
             END IF
 #endif
             !
             IF ( fleqok(i) ) THEN
 #ifdef W3_SHRD
               CALL wmioeg ( i )
 #endif
 #ifdef W3_MPI
               IF ( mpi_comm_grd.NE.mpi_comm_null )    &
                    CALL wmioeg ( i )
               pregte(i) = .false.
 #endif
               grstat(i) = 5
               fleqok(i) = .false.
               done      = .true.
             END IF
             !
             ! 6.c Stage data
             !
             IF ( grstat(i) .EQ. 5 ) THEN
               !
 #ifdef W3_T
               WRITE (mdst,9002) i, grstat(i)-1, 'SECOND PART'
 #endif
               !
 #ifdef W3_SHRD
               CALL wmiobs ( i )
 #endif
               !
 #ifdef W3_MPI
               IF ( mpi_comm_grd .NE. mpi_comm_null ) THEN
                 CALL wmiobf ( i )
                 CALL wmiobs ( i )
               END IF
 #endif
               !
 #ifdef W3_MPRF
               CALL prtime ( prftn )
               WRITE (mdsp,991) prft0, prftn,          &
                    get_memory(), 'ST04', i
 #endif
               cycle loop_jj
               !
             END IF ! IF ( GRSTAT(I) .EQ. 5 )
             !
 #ifdef W3_MPRF
             CALL prtime ( prftn )
             WRITE (mdsp,991) prft0, prftn,              &
                  get_memory(),  'ST04', i
 #endif
             !
           END IF ! 6. IF ( GRSTAT(I) .EQ. 4 )
           !
           ! 7.  Reconcile with higher ranked grids ----------------------------- /
           !     ( GRSTAT = 5 )
           !
           !     This needs to be a little more complicated than with boundary
           !     data to assure proper logic in cases where data providing
           !     data does not get data back (e.g., as for the boundary grid
           !     in mww3_test_04)
           !
           IF ( grstat(i) .EQ. 5 ) THEN
 #ifdef W3_MPRF
             CALL prtime ( prft0 )
 #endif
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), ' '
 #endif
             !
             ! 7.a Test against times and statuses of dependent grids
             !
             IF ( grdhgh(i,0) .EQ. 0 ) THEN
               grstat(i) = 6
               done      = .true.
             ELSE
               !
               flagok = .true.
               CALL w3setw ( i, mdse, mdst )
               taux   = time
               DO jjj=1, grdhgh(i,0)
                 CALL w3setw ( grdhgh(i,jjj), mdse, mdst )
                 IF ( .NOT. ( dsec21(taux,time).EQ.0. .AND.      &
                      ( grstat(grdhgh(i,jjj)).GE.7  .OR. &
                      grstat(grdhgh(i,jjj)).LE.2 ) ) ) &
                      flagok = .false.
               END DO
               CALL w3setw ( i, mdse, mdst )
               !
 #ifdef W3_T
               WRITE (mdst,9004) flagok
 #endif
               !
               ! 7.b Call gathering routine
               !
 #ifdef W3_MPI
               IF ( .NOT.flagok .AND. .NOT.pregth(i) ) THEN
                 IF ( mpi_comm_grd.NE.mpi_comm_null )     &
                      CALL wmiohg ( i, flag )
                 pregth(i) = .true.
               END IF
 #endif
               !
               IF ( flagok ) THEN
 #ifdef W3_SHRD
                 CALL wmiohg ( i, flagok )
 #endif
 #ifdef W3_MPI
                 IF ( mpi_comm_grd.NE.mpi_comm_null )     &
                      CALL wmiohg ( i )
                 pregth(i) = .false.
 #endif
                 grstat(i) = 6
                 done      = .true.
               END IF ! IF ( FLAGOK )
               !
             END IF ! IF ( GRDHGH(I,0) .EQ. 0 )
             !
             ! 7.c Stage data
             !
 #ifdef W3_SHRD
             IF ( grstat(i) .EQ. 6 ) CALL wmiohs ( i )
 #endif
             !
 #ifdef W3_MPI
             IF ( grstat(i) .EQ. 6 .AND.                  &
                  mpi_comm_grd .NE. mpi_comm_null ) THEN
               CALL wmiohf ( i )
               CALL wmiohs ( i )
             END IF
 #endif
             !
 #ifdef W3_T
             IF (grstat(i).EQ.6) WRITE(mdst,9003) i, grstat(i)
 #endif
 #ifdef W3_MPRF
             CALL prtime ( prftn )
             WRITE (mdsp,991) prft0, prftn, get_memory(),     &
                  'ST05', i
 #endif
           END IF ! 7. IF ( GRSTAT(I) .EQ. 5 )
           !
           ! 8.  Perform data assimmilation ------------------------------------- /
           !     ( GRSTAT = 6 ) Placeholder only .....
           !
           IF ( grstat(i) .EQ. 6 ) THEN
 #ifdef W3_MPRF
             CALL prtime ( prft0 )
 #endif
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), ' '
 #endif
             grstat(i) = 7
 #ifdef W3_MPRF
             CALL prtime ( prftn )
             WRITE (mdsp,991) prft0, prftn, get_memory(),     &
                  'ST06', i
 #endif
             done      = .true.
           END IF ! IF ( GRSTAT(I) .EQ. 6 )
           !
           ! 9.  Perform output ------------------------------------------------- /
           !     ( GRSTAT = 7 ) w3xdatmd data structures set in W3WAVE
           !
           !
           ! 9.a Check times and finish step if no output to be made
           !
 #ifdef W3_SHRD
           IF ( grstat(i) .EQ. 7 ) THEN
 #endif
 #ifdef W3_MPI
             IF ( grstat(i).EQ.7 .AND. .NOT.flsync(i) ) THEN
 #endif
               !
 #ifdef W3_T
               WRITE (mdst,9002) i, grstat(i), ' '
 #endif
               !
               IF ( toutp(1,i) .EQ. -1 ) THEN
                 dttst  = 1.
               ELSE
                 CALL w3setw ( i, mdse, mdst )
                 dttst  = dsec21( time , toutp(:,i) )
               END IF
 #ifdef W3_T
               WRITE (mdst,9090) dttst
 #endif
               flg_o1 = dttst .EQ. 0.
               !
               IF ( unipts ) THEN
                 CALL w3setw ( i, mdse, mdst )
                 dttst  = dsec21( time , upnext )
                 flg_o2 = dttst .EQ. 0.
               ELSE
                 flg_o2 = .false.
               END IF
               !
               IF ( .NOT.flg_o1 .AND. .NOT.flg_o2 ) THEN
                 grstat(i) = 8
 #ifdef W3_T
                 WRITE (mdst,9003) i, grstat(i)
 #endif
                 done      = .true.
               END IF
               !
 #ifdef W3_MPI
             END IF ! IF ( GRSTAT(I).EQ.7 .AND. .NOT.FLSYNC(I) )
 #endif
 #ifdef W3_SHRD
           END IF ! IF ( GRSTAT(I) .EQ. 7 )
 #endif
           !
           ! 9.b Perform output
           !
           IF ( grstat(i) .EQ. 7 ) THEN
 #ifdef W3_MPI
             IF ( mpi_comm_grd .NE. mpi_comm_null ) THEN
 #endif
               !
 #ifdef W3_MPRF
               CALL prtime ( prft0 )
 #endif
               !
               IF ( flg_o1 ) THEN
                 CALL w3setg ( i, mdse, mdst )
                 CALL wmsetm ( i, mdse, mdst )
                 IF ( flghg1 .AND. .NOT.flghg2 .AND.               &
                      grdhgh(i,0).GT.0 ) THEN
                   mapst2 = mapst2 - 8*mapmsk
                   mapsta = abs(mapsta)
                   DO ix=1, nx
                     DO iy=1, ny
                       IF ( mapst2(iy,ix) .GT. 0 )               &
                            mapsta(iy,ix) = - mapsta(iy,ix)
                     END DO
                   END DO
                   !
                 END IF
                 !
                 CALL w3wave ( i, dummy2, tsync(:,i), .false. )
                 !
                 IF ( flghg1 .AND. .NOT.flghg2 .AND.               &
                      grdhgh(i,0).GT.0 ) THEN
                   mapst2 = mapst2 + 8*mapmsk
                   mapsta = abs(mapsta)
                   DO ix=1, nx
                     DO iy=1, ny
                       IF ( mapst2(iy,ix) .GT. 0 )               &
                            mapsta(iy,ix) = - mapsta(iy,ix)
                     END DO
                   END DO
                 END IF
                 !
                 IF ( fllstl ) inflags1(1) = .false.
                 IF ( fllsti ) inflags1(4) = .false.
                 IF ( fllstr ) inflags1(6) = .false.
                 !
                 ! 9.c Update TOUPT
                 !
                 toutp(1,i) = -1
                 toutp(2,i) =  0
                 !
                 DO jo=1, notype
                   IF ( .NOT.flout(jo) ) cycle
                   IF ( toutp(1,i) .EQ. -1 ) THEN
                     toutp(:,i) = tonext(:,jo)
                   ELSE
                     dttst = dsec21( toutp(:,i) , tonext(:,jo) )
                     IF (dttst.LT.0.) toutp(:,i) = tonext(:,jo)
                   ENDIF
                 END DO
                 ! CHECKPOINT
                 jo=8
                 IF ( .NOT.flout(jo) ) cycle
                 IF ( toutp(1,i) .EQ. -1 ) THEN
                   toutp(:,i) = tonext(:,jo)
                 ELSE
                   dttst = dsec21( toutp(:,i) , tonext(:,jo) )
                   IF (dttst.LT.0.) toutp(:,i) = tonext(:,jo)
                 ENDIF
                 ! END CHECKPOINT
                 !
 #ifdef W3_T
                 WRITE (mdst,9091) toutp(:,i)
 #endif
                 !
               END IF ! IF ( FLG_O1 )
               !
               ! 9.d Process unified point output for selected grid
               !
               IF ( unipts ) THEN
                 IF ( flg_o2 ) THEN
                   CALL w3seto ( i, mdse, mdst )
                   !
 #ifdef W3_MPI
                   IF ( nrqpo.NE.0 ) CALL mpi_startall      &
                        ( nrqpo, irqpo1, ierr_mpi )
 #endif
                   !
                   IF ( nopts.NE.0 .AND. iaproc.EQ.nappnt ) THEN
                     CALL w3setg ( i, mdse, mdst )
                     CALL w3seta ( i, mdse, mdst )
                     CALL w3iope ( va )
                   END IF
                   !
 #ifdef W3_MPI
                   IF ( nrqpo .NE. 0 ) THEN
                     ALLOCATE ( status(mpi_status_size,nrqpo) )
                     CALL mpi_waitall                      &
                          ( nrqpo, irqpo1, status, ierr_mpi )
                     DEALLOCATE ( status )
                   END IF
 #endif
                   !
 #ifdef W3_T
                   WRITE (mdst,9092) nopts
 #endif
                   !
                 END IF ! IF ( FLG_O2 )
                 !
               END IF ! IF ( UNIPTS )
               !
 #ifdef W3_MPRF
               CALL prtime ( prftn )
               WRITE (mdsp,991) prft0, prftn,get_memory(),      &
                    'ST07', i
 #endif
               !
               ! 9.e Update TOUPT outside communicator
               !
 #ifdef W3_MPI
             ELSE IF ( flg_o1 ) THEN
 #endif
               !
 #ifdef W3_MPI
               CALL w3seto ( i, mdse, mdst )
               CALL w3setw ( i, mdse, mdst )
 #endif
               !
 #ifdef W3_MPI
               time       = toutp(:,i)
               toutp(1,i) = -1
               toutp(2,i) =  0
 #endif
               !
 #ifdef W3_MPI
               DO jo=1, notype
 #endif
                 !
 #ifdef W3_MPI
                 IF ( flout(jo) ) THEN
                   DO
                     dttst = dsec21( time, tonext(:,jo) )
                     IF ( dttst .LE. 0. ) THEN
                       CALL tick21 ( tonext(:,jo), dtout(jo) )
                       dttst = dsec21( tonext(:,jo), tolast(:,jo) )
                       IF ( dttst .LT. 0. ) THEN
                         flout(jo) = .false.
                         EXIT
                       END IF
                     ELSE
                       EXIT
                     END IF
                   END DO
                 END IF ! IF ( FLOUT(JO) )
 #endif
                 !
 #ifdef W3_MPI
                 IF ( .NOT.flout(jo) ) cycle
                 IF ( toutp(1,i) .EQ. -1 ) THEN
                   toutp(:,i) = tonext(:,jo)
                 ELSE
                   dttst = dsec21( toutp(:,i) , tonext(:,jo) )
                   IF (dttst.LT.0.) toutp(:,i) = tonext(:,jo)
                 ENDIF
 #endif
                 !
 #ifdef W3_MPI
               END DO ! DO JO=1, NOTYPE
 #endif
               !
               ! Checkpoint
               !
 #ifdef W3_MPI
               jo=8
 #endif
               !
 #ifdef W3_MPI
               IF ( flout(jo) ) THEN
                 DO
                   dttst = dsec21( time, tonext(:,jo) )
                   IF ( dttst .LE. 0. ) THEN
                     CALL tick21 ( tonext(:,jo), dtout(jo) )
                     dttst = dsec21( tonext(:,jo), tolast(:,jo) )
                     IF ( dttst .LT. 0. ) THEN
                       flout(jo) = .false.
                       EXIT
                     END IF
                   ELSE
                     EXIT
                   END IF
                 END DO
               END IF ! IF ( FLOUT(JO) )
 #endif
               !
 #ifdef W3_MPI
               IF ( .NOT.flout(jo) ) cycle
               IF ( toutp(1,i) .EQ. -1 ) THEN
                 toutp(:,i) = tonext(:,jo)
               ELSE
                 dttst = dsec21( toutp(:,i) , tonext(:,jo) )
                 IF (dttst.LT.0.) toutp(:,i) = tonext(:,jo)
               ENDIF
 #endif
               !
               ! End Checkpoint
 #ifdef W3_MPIT
               WRITE (mdst,9991) toutp(:,i)
 #endif
 #ifdef W3_MPI
             END IF ! 9.b IF ( MPI_COMM_GRD .NE. MPI_COMM_NULL )
 #endif
             !
             ! 9.f Finish up
             !
             grstat(i) = 8
             done      = .true.
             !
           END IF ! 9.b IF ( GRSTAT(I) .EQ. 7 )
           !
           ! 10. Go to next time step ------------------------------------------- /
           !     ( GRSTAT = 8 ) ( 9 added for diagnostic output only ... )
           !                    ( Unified point output and synchronization added )
           !
           IF ( grstat(i) .EQ. 8 ) THEN
             !
 #ifdef W3_T
             WRITE (mdst,9002) i, grstat(i), ' '
 #endif
             !
             ! 10.a Processing unified point output
             !
             IF ( unipts .AND. do_upt ) THEN
               CALL w3setw ( i, mdse, mdst )
               flagok = dsec21( time, upnext ) .EQ. 0.
 #ifdef W3_T
               WRITE (mdst,9095) flagok
 #endif
             ELSE
               flagok = .false.
             END IF
             !
             IF ( flagok ) THEN
               !
               DO ii=1, nrgrd
                 CALL w3setw ( ii, mdse, mdst )
                 flagok = flagok .AND. grstat(ii).EQ.8 .AND.     &
                      dsec21(time,upnext).EQ.0.
               END DO
 #ifdef W3_T
               WRITE (mdst,9096) flagok
 #endif
               !
               IF ( flagok ) THEN
                 !
 #ifdef W3_MPRF
                 CALL prtime ( prft0 )
 #endif
                 CALL wmiopo ( upnext )
                 do_upt = .false.
                 !
                 CALL w3seto ( 0, mdse, mdst )
                 CALL tick21 ( upnext, dtout(2) )
                 IF ( dsec21(upnext,uplast) .GE. 0. ) THEN
                   tonext(:,2) = upnext
                 ELSE
                   unipts = .false.
                   upnext(1) = -1
                   upnext(2) =  0
                 END IF
                 !
                 DO ii=1, nrgrd
                   CALL w3setw ( ii, mdse, mdst )
                   dttst  = dsec21( time, tend(:,ii) )
                   IF ( dttst .GT. 0. ) THEN
                     grstat(ii) = 9
                   ELSE IF ( dttst .EQ. 0 ) THEN
                     grstat(ii) = 99
                   END IF
                   tsync(1,ii) = -1
                   tsync(2,ii) =  0
 #ifdef W3_T
                   IF ( i .NE. ii )                         &
                        WRITE (mdst,9003) ii, grstat(ii)
 #endif
                 END DO
                 !
                 done      = .true.
 #ifdef W3_MPRF
                 CALL prtime ( prftn )
                 WRITE (mdsp,991) prft0, prftn,          &
                      get_memory(), 'UPTS',i
 #endif
               END IF ! IF ( FLAGOK )
               !
             ELSE
               flagok = .true.
             END IF ! IF ( FLAGOK )
             !
             ! 10.b Regular processing
             !
             IF ( flagok ) THEN
               CALL w3setw ( i, mdse, mdst )
               dttst  = dsec21( time, tend(:,i) )
               IF ( dttst .GT. 0. ) THEN
                 grstat(i) = 9
                 done      = .true.
               ELSE IF ( dttst .EQ. 0 ) THEN
                 grstat(i) = 99
                 done      = .true.
               END IF
 #ifdef W3_T
               WRITE (mdst,9003) i, grstat(i)
 #endif
             END IF ! IF ( FLAGOK )
             !
             IF ( grstat(i).EQ.9 .OR. grstat(i).EQ.99 ) THEN
               tsync(1,i) = -1
               tsync(2,i) =  0
             END IF
             !
           END IF ! 10. IF ( GRSTAT(I) .EQ. 8 )
           !
           ! ... End of loops started in 1. ------------------------------------- /
           !
         END DO loop_jj
         !
 1111    CONTINUE
         !
       END DO loop_j
       !
 #ifdef W3_MPI
       nmpscr = nmpscs
 #endif
       IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc )                    &
            CALL wmprnt ( mdso, nrgrd, tsync(:,0), grstat )
       !
       DO i=1, nrgrd
         IF ( grstat(i) .EQ. 9 ) grstat(i) = 0
       END DO
       !
       IF ( .NOT. done ) GOTO 2099
       IF ( minval(grstat) .EQ. 99 ) EXIT loop_outer
     END DO loop_outer
     !
     !    End of routine -------------------------------------------------- /
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc ) THEN
       CALL wwtime ( wtime )
       WRITE (mdss,902) wtime
     ENDIF
     !
 #ifdef W3_MPI
     DO i=1, nrgrd
       CALL wmsetm ( i, mdse, mdst )
       IF ( mpi_comm_grd .NE. mpi_comm_null ) THEN
         CALL wmiobf ( i )
         CALL wmiohf ( i )
         CALL wmioef ( i )
       END IF
     END DO
 #endif
     !
 #ifdef W3_O10
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc ) WRITE (mdss,999)
 #endif
     !
 #ifdef W3_T
     WRITE (mdst,9100)
 #endif
     !
     RETURN
     !
     ! Escape locations
     !
 2000 CONTINUE
     IF ( improc .EQ. nmperr ) WRITE (mdse,1000) i, grstat(i)
     CALL extcde ( 2000 )
     RETURN
     !
 2001 CONTINUE
     IF ( improc .EQ. nmperr ) WRITE (mdse,1001) i, tsync(:,i),      &
          tend(:,i)
     CALL extcde ( 2001 )
     RETURN
     !
 2002 CONTINUE
     IF ( improc .EQ. nmperr ) WRITE (mdse,1002) j, ingrp(j,1),      &
          ingrp(j,jj), tsync(:,ingrp(j,1)), tsync(:,ingrp(j,jj)),    &
          tend(:,ingrp(j,1)), tend(:,ingrp(j,jj))
     CALL extcde ( 2002 )
     RETURN
     !
 2099 CONTINUE
     IF ( improc .EQ. nmperr ) WRITE (mdse,1099)
     CALL extcde ( 2099 )
     RETURN
     !
     ! Formats
     !
 900 FORMAT ( ' ========== STARTING WAVE MODEL (WMWAVE) ==========', &
          '============================'/)
 901 FORMAT ('  MWW3 calculating for ',a,' at ',a,'  status [',      &
          i2,'-',i2,']')
 902 FORMAT ('  MWW3 reached the end of the computation loop at ',a)
 #ifdef W3_MPRF
 990 FORMAT (1x,3f12.3,' WMWAVE INIT')
 991 FORMAT (1x,3f12.3,' WMWAVE ',a4,i6)
 992 FORMAT (1x,3f12.3,' WMWAVE ',a4,i9.8,i7.6)
 #endif
 999 FORMAT (/' ========== END OF WAVE MODEL (WMWAVE) ============', &
          '============================'/)
     !
 1000 FORMAT (/' *** WAVEWATCH III ERROR IN WMWAVE : *** '/           &
          '     GRID',i3,' HAS ILLEGAL GRSTAT :',i8/)
     !
 1001 FORMAT (/' *** WAVEWATCH III ERROR IN WMWAVE : *** '/           &
          '     GRID',i3,' HAS ILLEGAL TSYNC / TEND '/           &
          '     TSYNC :',i9.8,i7.6/                              &
          '     TEND  :',i9.8,i7.6/)
     !
 1002 FORMAT (/' *** WAVEWATCH III ERROR IN WMWAVE : *** '/           &
          '     GROUP',i3,' HAS INCOMPATIBLE TIMES ',            &
          'IN GRIDS ',i3,' AND ',i3/                             &
          '     TSYNC :',i9.8,i7.6,1x,i9.8,i7.6/                 &
          '     TEND  :',i9.8,i7.6,1x,i9.8,i7.6/)
     !
     ! Note: This 1099 error can occur when multi-grid time steps are not
     !       compatible.
 1099 FORMAT (/' *** WAVEWATCH III ERROR IN WMWAVE : *** '/           &
          '     ABORT FOR POSSIBLE ENDLESS LOOP '/)
     !
 #ifdef W3_T
 9000 FORMAT ( ' TEST WMWAVE : LOOP',i8,' ======================', &
          '===== (',i9.8,i7.6,' ) =='/ &
          '               GRID, GRSTAT, TIME, TSYNC, TEND')
 9001 FORMAT ( '              ',i3,i3,3(i10.8,i7.6))
 9002 FORMAT ( ' TEST WMWAVE : PROCESSING GRID',i3,                &
          ' STATUS',i3,' ',a)
 #endif
 #ifdef W3_MPIT
 9902 FORMAT ( ' MPIT WMWAVE : PROCESSING GRID',i3,             &
          ' STATUS',i3,' ',a)
 #endif
 #ifdef W3_T
 9003 FORMAT ( ' TEST WMWAVE : GRID',i3,' STATUS RESET TO',i3)
 9004 FORMAT ( ' TEST WMWAVE : FLAGOK = ',l1)
 9005 FORMAT ( ' TEST WMWAVE : FLEQOK = ',l1)
 9006 FORMAT ( ' TEST WMWAVE : CYCLE GROUP')
 #endif
     !
 #ifdef W3_T
 9020 FORMAT ( ' TEST WMWAVE : DTTST ',e10.3)
 9021 FORMAT ( ' TEST WMWAVE : TIME  :',i10.8,i7.6/                &
          '               TDATA :',i10.8,i7.6/                &
          '               TEND  :',i10.8,i7.6)
 #endif
     !
 #ifdef W3_T
 9040 FORMAT ( ' TEST WMWAVE : TMAX  :',i10.8,i7.6,f8.2/           &
          '               DTMAX :',i10.8,i7.6/                &
          '               TDATA :',i10.8,i7.6/                &
          '               TOUTP :',i10.8,i7.6/                &
          '               UPNEXT:',i10.8,i7.6)
 9041 FORMAT ( ' TEST WMWAVE : TMAX  :',i10.8,i7.6)
 #endif
 #ifdef W3_MPIT
 9941 FORMAT ( ' MPIT WMWAVE : TMAX  :',i10.8,i7.6)
 #endif
 #ifdef W3_T
 9042 FORMAT ( ' TEST WMWAVE : GRANK :',i4,' FOR GRSTAT = 2')
 9043 FORMAT ( ' TEST WMWAVE : GLOBAL TSYNC :',i10.8,i7.6)
 9044 FORMAT ( ' TEST WMWAVE : LOCAL TSYNC :',i10.8,i7.6,          &
          ' (',i8.8,i7.6,')')
 9045 FORMAT ( ' TEST WMWAVE : GRID TSYNC')
 9046 FORMAT ( '             ',i5,i10.8,i7.6)
 #endif
     !
 #ifdef W3_T
 9061 FORMAT ( '               GRID',i4,',  FLEQOK = ',l1)
 #endif
     !
 #ifdef W3_T
 9090 FORMAT ( ' TEST WMWAVE : DTTST ',e10.3)
 9091 FORMAT ( ' TEST WMWAVE : NEXT TOUTP :',i10.8,i7.6)
 #endif
 #ifdef W3_MPIT
 9991 FORMAT ( ' MPIT WMWAVE : NEXT TOUTP :',i10.8,i7.6)
 #endif
 #ifdef W3_T
 9092 FORMAT ( ' TEST WMWAVE : UNIFIED POINT OUTPUT PREP DONE',i6)
 #endif
     !
 #ifdef W3_T
 9095 FORMAT ( ' TEST WMWAVE : UNIFIED POINT OUTPUT, FLAGOK = ',l1)
 9096 FORMAT ( '               ALL GRIDS, FLAGOK = ',l1)
 #endif
     !
 #ifdef W3_T
 9100 FORMAT ( ' TEST WMWAVE : LOOP DONE  ======================', &
          '==============================')
 #endif
     !/
     !/ End of WMWAVE ----------------------------------------------------- /
     !/
References wmmdatmd::amv, wmmdatmd::croot, wmmdatmd::dmv, w3timemd::dsec21(), w3gdatmd::dtmax, w3odatmd::dtout, wmmdatmd::dtres, wmmdatmd::etime, w3servmd::extcde(), wmmdatmd::fbcast, wmmdatmd::flghg1, wmmdatmd::flghg2, wmmdatmd::fllsti, wmmdatmd::fllstl, wmmdatmd::fllstr, w3odatmd::flout, wmmdatmd::grank, wmmdatmd::grdeql, wmmdatmd::grdhgh, wmmdatmd::grdlow, wmmdatmd::grstat, w3odatmd::iaproc, wmmdatmd::improc, include(), w3idatmd::inflags1, wmmdatmd::ingrp, w3odatmd::irqpo1, wmmdatmd::mapmsk, w3gdatmd::mapst2, w3gdatmd::mapsta, wmmdatmd::mdse, wmmdatmd::mdso, wmmdatmd::mdsp, wmmdatmd::mdss, wmmdatmd::mdst, wmmdatmd::mpi_comm_bct, wmmdatmd::mpi_comm_grd, wmmdatmd::mpi_comm_mwave, w3odatmd::nappnt, wmmdatmd::nmperr, wmmdatmd::nmplog, wmmdatmd::nmproc, wmmdatmd::nmpscr, wmmdatmd::nmptst, wmmdatmd::nmv, w3odatmd::nopts, w3odatmd::notype, wmmdatmd::nrgrd, wmmdatmd::nrgrp, w3odatmd::nrqpo, w3gdatmd::nx, w3gdatmd::ny, w3timemd::prtime(), wmmdatmd::stime, w3timemd::stme21(), w3servmd::strace(), wmmdatmd::tdata, w3timemd::tick21(), w3wdatmd::time, wmmdatmd::tmax, wmmdatmd::tmv, w3odatmd::tolast, w3odatmd::tonext, wmmdatmd::toutp, wmmdatmd::tsync, w3odatmd::unipts, w3wdatmd::va, w3iopomd::w3iope(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3wavemd::w3wave(), wmbcst(), wminiomd::wmiobf(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioef(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohf(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmprnt(), wmmdatmd::wmsetm(), wmupdtmd::wmupdt(), and w3servmd::wwtime().
Referenced by w3mlti(), and w3sbs1().
wmwout()
subroutine wmwavemd::wmwout (integer, intent(in) IMOD, integer, intent(in) NMOD, integer, intent(in) ID)
Non-blocking broadcast using dummy parameter to have output.
Processes wait for computations on first node to be finished. Needed for profiling purposes only.
Standard send and recieves using defined communicator. Send form first processor in communicator.
Parameters
[in] IMOD Model number.
[in] NMOD Number of models.
[in] ID ID number, used with NMOD for ITAG.
Author
H. L. Tolman
Date
21-Jun-2007
Definition at line 2134 of file wmwavemd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         21-Jun-2007 !
     !/                  +-----------------------------------+
     !/
     !/    21-Jun-2007 : Origination.                        ( version 3.11 )
     !/
     !  1. Purpose :
     !
     !     Non-blocking broadcast using dummy parameter to have output!
     !     processes wait for computations on first node to be finished.
     !     Neede for profiling purposes only.
     !
     !  2. Method :
     !
     !     Standard send and recieves using defined communicator. Send
     !     form first processor in communicator.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number.
     !       NMOD    Int.   I   Number of models.
     !       ID      Int.   I   ID number, used with NMOD for ITAG.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Sur.  W3SERVMD Subroutine tracing.
     !      W3SETO    Subr. W3ODATMD Point to data structure
     !      W3SETA    Subr. W3ADATMD Point to data structure
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      WMWAVE    Subr. WMWAVEMD Multi-grid wave model routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/MPIT Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !
 #ifdef W3_MPI
     USE w3odatmd, ONLY: w3seto
     USE w3adatmd, ONLY: w3seta
 #endif
     !
 #ifdef W3_MPI
     USE w3odatmd, ONLY: iaproc, naproc, ntproc
     USE w3adatmd, ONLY: mpi_comm_wave
     USE wmmdatmd, ONLY: mdst, mdse, mtagb
 #endif
     !
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
 #ifdef W3_MPI
     include "mpif.h"
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NMOD, ID
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_MPI
     INTEGER                 :: ITAG, IP, IERR_MPI,             &
          STATUS(MPI_STATUS_SIZE)
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
 #ifdef W3_MPI
     REAL, SAVE              :: DUMMY = 999.
 #endif
     !/
 #ifdef W3_S
     CALL strace (ient, 'WMWOUT')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 0.  Initializations
     !
 #ifdef W3_MPI
     CALL w3seto ( imod, mdse, mdst )
     CALL w3seta ( imod, mdse, mdst )
     itag   = mtagb + imod + id*nmod
 #endif
     !
 #ifdef W3_MPI
     IF ( iaproc .LT. 1 ) THEN
 #endif
 #ifdef W3_MPI
       RETURN
     END IF
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Processor to send data from
     !
 #ifdef W3_MPI
     IF ( iaproc .EQ. 1 ) THEN
       DO ip=naproc+1, ntproc
 #endif
 #ifdef W3_MPI
         CALL mpi_send ( dummy, 1, mpi_integer, ip-1,         &
              itag, mpi_comm_wave, ierr_mpi )
       END DO
 #endif
       !
       ! -------------------------------------------------------------------- /
       ! 2.  Processor to receive data at
       !
 #ifdef W3_MPI
     ELSE IF ( iaproc .GT. naproc ) THEN
 #endif
 #ifdef W3_MPI
       CALL mpi_recv ( dummy, 1, mpi_integer, 0, itag,        &
            mpi_comm_wave, status, ierr_mpi )
 #endif
       !
       ! -------------------------------------------------------------------- /
       ! 3.  Processor with no action
       !
 #ifdef W3_MPI
     END IF
 #endif
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_MPIT
 9000 FORMAT ( ' TEST WMWOUT : INPUTS :',4i4)
 9001 FORMAT ( ' TEST WMWOUT : IAPROC, NAPROC, NTPROC :',3i5)
 9002 FORMAT ( ' TEST WMWOUT : NOT IN COMMUNICATOR')
 #endif
     !
 #ifdef W3_MPIT
 9010 FORMAT ( ' TEST WMWOUT : IAPROC =',i5,'    SENDING TO ',i5)
 #endif
     !
 #ifdef W3_MPIT
 9020 FORMAT ( ' TEST WMWOUT : IAPROC =',i5,                    &
          '    RECEIVING FROM ',i5)
 #endif
     !
 #ifdef W3_MPIT
 9030 FORMAT ( ' TEST WMWOUT : IAPROC =',i5,'    NO ACTION')
 #endif
     !/
     !/ End of WMWOUT ----------------------------------------------------- /
     !/
References w3odatmd::iaproc, include(), wmmdatmd::mdse, wmmdatmd::mdst, w3adatmd::mpi_comm_wave, wmmdatmd::mtagb, w3odatmd::naproc, w3odatmd::ntproc, w3servmd::strace(), w3adatmd::w3seta(), and w3odatmd::w3seto().