WAVEWATCH III: w3metamd Module Reference
w3metamd Module Reference
Dynamic storage for meta data attribute/value pairs.
Data Types
interface meta_list_append
Interface to facilitate adding real/int/character values to list.
type meta_list_t
Linked list of meta data pairs.
type meta_pair_t
Type for storing a user defined metadata pair as linked list element.
Functions/Subroutines
subroutine del_meta_list (LIST)
Deletes all entries in list.
type(meta_list_t) function copy_meta_list (LIST)
Create a deep copy of a meta data list.
subroutine print_meta_list (LIST)
Prints meta pairs in list to screen.
subroutine meta_list_append_m (LIST, META)
Append META_PAIR_T object to list.
subroutine meta_list_append_r (LIST, ATTNAME, RVAL)
Append REAL value attribute to list.
subroutine meta_list_append_i (LIST, ATTNAME, IVAL)
Append INTEGER value attribute to list.
subroutine meta_list_append_c (LIST, ATTNAME, SVAL)
Append CHARACTER string value attribute to list.
subroutine meta_list_find_attr (LIST, ATTN, META, ERR)
Find (first) entry in list with matching attname.
logical function meta_list_has_attr (LIST, ATTN)
Tests whether list contains an entry with specified attname.
Variables
character(len= *), parameter unsetc = "unset"
Value to represent "unset" character variable.
real, parameter unsetr = HUGE(1.0)
Value to represent "unset" real variable.
Detailed Description
Dynamic storage for meta data attribute/value pairs.
Provides types for handling "meta data" (attribute/value pairs) and a linked list construct for dynamic storage.
Change log
Date Ver Comments
16-Dec-2020 7.12 Creation
Author
Chris Bunney
Date
16-Dec-2020
Function/Subroutine Documentation
copy_meta_list()
type(meta_list_t) function w3metamd::copy_meta_list (type(meta_list_t), intent(in) LIST)
Create a deep copy of a meta data list.
A "deep copy" ensures that a copy is made of the underlying linked list, rather than a simply copy of the pointers to the existing list.
Parameters
[in] LIST The list to copy
Returns
A new META_LIST_T
Author
Chris Bunney
Definition at line 116 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(IN) :: LIST
     TYPE(META_LIST_T)             :: COPY
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T), POINTER :: P
     NULLIFY(copy%HEAD)
     NULLIFY(copy%TAIL)
     copy%N = 0
     IF(list%N .EQ. 0) RETURN
     ! Deep copy list
     p => list%HEAD
     DO
       CALL meta_list_append_m(copy, p)
       IF(.NOT. ASSOCIATED(p%NEXT)) EXIT
       p => p%NEXT
     ENDDO
References meta_list_append_m().
del_meta_list()
subroutine w3metamd::del_meta_list (type(meta_list_t), intent(inout) LIST)
Deletes all entries in list.
Parameters
[in,out] LIST The list to clear.
Author
Chris Bunney
Definition at line 75 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(INOUT) :: LIST
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T), POINTER :: P
     IF(.NOT. ASSOCIATED(list%HEAD)) RETURN
     DO
       NULLIFY(p)
       IF(ASSOCIATED(list%HEAD%NEXT)) p => list%HEAD%NEXT
       DEALLOCATE(list%HEAD)
       IF(.NOT. ASSOCIATED(p)) EXIT
       list%HEAD => p
     ENDDO
     NULLIFY(list%HEAD)
     NULLIFY(list%TAIL)
     list%N = 0
Referenced by w3ounfmetamd::teardown_meta().
meta_list_append_c()
subroutine w3metamd::meta_list_append_c (type(meta_list_t), intent(inout) LIST, character(*), intent(in) ATTNAME, character(*), intent(in) SVAL)
Append CHARACTER string value attribute to list.
Parameters
[in,out] LIST The list to append to
[in] ATTNAME The attribute name
[in] SVAL The attribute value (CHARACTER string)
Author
Chris Bunney
Definition at line 284 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(INOUT) :: LIST
     CHARACTER(*), INTENT(IN)         :: ATTNAME, SVAL
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T) :: META
     meta%ATTNAME = attname
     meta%ATTVAL = sval
     meta%TYPE = 'c'
     CALL meta_list_append(list, meta)
meta_list_append_i()
subroutine w3metamd::meta_list_append_i (type(meta_list_t), intent(inout) LIST, character(*), intent(in) ATTNAME, integer, intent(in) IVAL)
Append INTEGER value attribute to list.
Parameters
[in,out] LIST The list to append to
[in] ATTNAME The attribute name
[in] IVAL The attribute value (INTEGER)
Author
Chris Bunney
Definition at line 255 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(INOUT) :: LIST
     CHARACTER(*), INTENT(IN)         :: ATTNAME
     INTEGER, INTENT(IN)              :: IVAL
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T) :: META
     meta%ATTNAME = attname
     WRITE(meta%ATTVAL,*) ival
     meta%TYPE = 'i'
     CALL meta_list_append(list, meta)
meta_list_append_m()
subroutine w3metamd::meta_list_append_m (type(meta_list_t), intent(inout) LIST, type(meta_pair_t), intent(in) META)
Append META_PAIR_T object to list.
Parameters
[in,out] LIST The list to append to
[in] META The META_PAIR_T object to append.
Author
Chris Bunney
Definition at line 184 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(INOUT) :: LIST
     TYPE(META_PAIR_T), INTENT(IN) :: META
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T), POINTER :: P
     ALLOCATE(p)
     ! Empty list?
     IF(list%N .EQ. 0) THEN
       !IF(.NOT. ASSOCIATED(LIST%HEAD)) THEN
       list%HEAD => p
     ELSE
       list%TAIL%NEXT => p
     ENDIF
     list%TAIL => p
     p%ATTNAME = meta%ATTNAME
     p%ATTVAL = meta%ATTVAL
     p%TYPE = meta%TYPE
     NULLIFY(p%NEXT)
     list%N = list%N + 1
Referenced by copy_meta_list().
meta_list_append_r()
subroutine w3metamd::meta_list_append_r (type(meta_list_t), intent(inout) LIST, character(*), intent(in) ATTNAME, real, intent(in) RVAL)
Append REAL value attribute to list.
Parameters
[in,out] LIST The list to append to
[in] ATTNAME The attribute name
[in] RVAL The attribute value (REAL)
Author
Chris Bunney
Definition at line 226 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(INOUT) :: LIST
     CHARACTER(*), INTENT(IN)         :: ATTNAME
     REAL, INTENT(IN)                 :: RVAL
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T) :: META
     meta%ATTNAME = attname
     WRITE(meta%ATTVAL,*) rval
     meta%TYPE = 'r'
     CALL meta_list_append(list, meta)
meta_list_find_attr()
subroutine w3metamd::meta_list_find_attr (type(meta_list_t), intent(in) LIST, character(*), intent(in) ATTN, type(meta_pair_t), intent(out), pointer META, integer, intent(out) ERR)
Find (first) entry in list with matching attname.
Parameters
[in] LIST List to search
[in] ATTN Attribute name to search for
[out] META Meta data type to store matched result in
[out] ERR Error status (0=Found, 1=Empty list, 2=Not found)
Author
Chris Bunney
Definition at line 313 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(IN)           :: LIST
     CHARACTER(*), INTENT(IN)                :: ATTN
     TYPE(META_PAIR_T), POINTER, INTENT(OUT) :: META
     INTEGER, INTENT(OUT)                    :: ERR
     err = 0
     ! Empty list?
     IF(.NOT. ASSOCIATED(list%HEAD)) THEN
       err = 1
       RETURN
     ENDIF
     meta => list%HEAD
     DO
       IF(trim(meta%ATTNAME) == trim(attn)) RETURN
       IF(.NOT. ASSOCIATED(meta%NEXT)) EXIT
       meta => meta%NEXT
     ENDDO
     ! Not found
     NULLIFY(meta)
     err = 2
meta_list_has_attr()
logical function w3metamd::meta_list_has_attr (type(meta_list_t), intent(in) LIST, character(*), intent(in) ATTN)
Tests whether list contains an entry with specified attname.
Parameters
[in] LIST The list to search
[in] ATTN Attribute name to search for
Returns
LOGICAL: True if match found, False otherwise.
Author
Chris Bunney
Definition at line 354 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(IN)           :: LIST
     CHARACTER(*), INTENT(IN)                :: ATTN
     LOGICAL                                 :: FOUND
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T), POINTER :: P
     found = .false.
     ! Empty list?
     IF(.NOT. ASSOCIATED(list%HEAD)) THEN
       RETURN
     ENDIF
     p => list%HEAD
     DO
       IF(trim(p%ATTNAME) == trim(attn)) THEN
         found = .true.
         RETURN
       ENDIF
       IF(.NOT. ASSOCIATED(p%NEXT)) EXIT
       p => p%NEXT
     ENDDO
print_meta_list()
subroutine w3metamd::print_meta_list (type(meta_list_t), intent(in) LIST)
Prints meta pairs in list to screen.
Parameters
[in] LIST Linked list of meta data to print
Author
Chris Bunney
Definition at line 150 of file w3metamd.F90.
     IMPLICIT NONE
     TYPE(META_LIST_T), INTENT(IN) :: LIST
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     TYPE(META_PAIR_T), POINTER :: P
     IF(.NOT. ASSOCIATED(list%HEAD)) THEN
       WRITE(*,*) 'List empty.'
       RETURN
     ENDIF
     p => list%HEAD
     DO
       WRITE(*, '(A," [",A1,"] : ", A)') trim(p%ATTNAME), p%TYPE,      &
            trim(p%ATTVAL)
       IF(.NOT. ASSOCIATED(p%NEXT)) EXIT
       p => p%NEXT
     ENDDO
Variable Documentation
unsetc
character(len=*), parameter w3metamd::unsetc = "unset"
Value to represent "unset" character variable.
Definition at line 38 of file w3metamd.F90.
   CHARACTER(LEN=*), PARAMETER :: UNSETC = "unset"
unsetr
real, parameter w3metamd::unsetr = HUGE(1.0)
Value to represent "unset" real variable.
Definition at line 40 of file w3metamd.F90.
   REAL, PARAMETER             :: UNSETR = huge(1.0)