WAVEWATCH III: w3tidemd Module Reference
w3tidemd Module Reference
Functions/Subroutines
subroutine tide_write_results (LP, filename, ndef, KD1, KD2, ITZ, xlat, xlon, RES, SSQ, RMSR0, SDEV0, SDEV, RMSR, RESMAX, IMAX, RMSRP)
subroutine tide_find_indices_prediction (LIST, INDS, TIDE_PRMF)
subroutine tide_find_indices_analysis (LIST)
subroutine tide_set_indices
subroutine setvuf_fast (h, pp, s, p, enp, dh, dpp, ds, dp, dnp, tau, XLAT, F, U, V)
subroutine tide_read_settings (filename, fnam6, fnam7, fnam8, fnam9, fnam11)
subroutine tide_read_anapar (KR1, LP, filename, KD1, KD2, XLON, XLAT, NDEF, ITREND, ITZ)
subroutine tide_read_timeseries (KR2, filename, KD1, KD2, TIDE_NTI, NDEF)
subroutine astr (d1, h, pp, s, p, np, dh, dpp, ds, dp, dnp)
double precision function dpythag (a, b)
subroutine dsvbksb (u, w, v, m, n, mp, np, b, x)
subroutine dsvdcmp (a, m, n, mp, np, w, v)
integer *4 function juldayt (id, mm, iyyy)
subroutine caldatt (julian, id, mm, iyyy)
subroutine svd (q, u, v, cov, w, p, b, sig, ic, m, n, mm, N2, toler, jc, ssq, res)
subroutine vuf_set_parameters
subroutine vuf (KONX, Vx, ux, FX, ITIME)
subroutine opnvuf (filename)
subroutine setvuf (hr, XLAT, ITIME)
subroutine flex_tidana_webpage (IX, IY, XLON, XLAT, KD1, KD2, ndef, itrend, RES, SSQ, RMSR0, SDEV0, RMSR, RESMAX, IMAX, ITEST)
subroutine tide_predict (itrend, ndef, N, HOURS, DATAIN, PREDICTED, RESID, XLAT, SDEV, RMSR)
subroutine tide_predict_only (itrend, ndef, N, TIDE_HOURS, PREDICTED, XLAT)
Variables
double precision, parameter twpi =3.1415926535898*2.
double precision, parameter fac =TWPI/360.
integer, parameter mc =70
integer, parameter nr =106000
integer, parameter nmaxp1 =MC*2
integer, parameter nmaxpm =NR*2+NMAXP1
integer, parameter mc2 =MC*2
character *5, parameter kblank =' '
integer ntidal_con
integer ntotal_con
integer nkonco
character *5, dimension(:), allocatable tidecon_allnames
character *5, dimension(:), allocatable konco_con
real, dimension(:), allocatable semi
real, dimension(:), allocatable coef_con
real, dimension(:,:), allocatable v_arg
real, dimension(:,:), allocatable f_arg
real, dimension(:,:), allocatable u_arg
real, dimension(180) ee
real, dimension(180) ph
integer, dimension(180) ldel
integer, dimension(180) mdel
integer, dimension(180) ndel
integer, dimension(180) ir
integer, dimension(:), allocatable tide_indexj
integer, dimension(:), allocatable tide_indexjk
integer tide_mf
integer tide_nx
integer tide_ny
real, dimension(:), allocatable tide_freqc
character(len=5), dimension(:), allocatable tidecon_namei
character(len=5), dimension(:), allocatable tidecon_name
character(len=5), dimension(10) tide_konan
character(len=5), dimension(10, 10) tide_konin
real, dimension(10, 10) tide_r
real, dimension(10, 10) tide_zeta
real, dimension(10) tide_sigan
real, dimension(10, 10) tide_sigin
integer tide_nin
integer, dimension(10) tide_ninf
real, dimension(:,:,:,:,:), allocatable tidal_const
integer(kind=4) tide_nti
real, dimension(:,:), allocatable tide_data
integer(kind=4), dimension(:), allocatable tide_days
integer(kind=4), dimension(:), allocatable tide_secs
real(kind=8), dimension(:), allocatable tide_hours
real, parameter tide_dt = 1800.
real, dimension(mc, 2) tide_ampc
real, dimension(mc, 2) tide_phg
real, dimension(mc, 2) tide_sig1
real, dimension(mc, 2) tide_sig2
real, dimension(mc, 2) tide_sig3
real, dimension(mc, 2) tide_ttest
real, dimension(10, 10, 2) tide_ampci
real, dimension(10, 10, 2) tide_phgi
integer, dimension(mc) tide_index
integer, dimension(mc) tide_index2
integer ndset
integer tide_verbose = 0
Function/Subroutine Documentation
astr()
subroutine w3tidemd::astr (real(kind=8), intent(in) d1, real(kind=8), intent(out) h, real(kind=8), intent(out) pp, real(kind=8), intent(out) s, real(kind=8), intent(out) p, real(kind=8), intent(out) np, real(kind=8), intent(out) dh, real(kind=8), intent(out) dpp, real(kind=8), intent(out) ds, real(kind=8), intent(out) dp, real(kind=8), intent(out) dnp)
Definition at line 911 of file w3tidemd.F90.
     !      this subroutine calculates the following five ephermides
     !      of the sun and moon
     !      h = mean longitude of the sum
     !      pp = mean longitude of the solar perigee
     !      s = mean longitude of the moon
     !      p = mean longitude of the lunar perigee
     !      np = negative of the longitude of the mean ascending node
     !      and their rates of change.
     !      Units for the ephermides are cycles and for their derivatives
     !      are cycles/365 days
     !      The formulae for calculating this ephermides were taken from
     !      pages 98 and 107 of the Explanatory Supplement to the
     !      Astronomical Ephermeris and the American Ephermis and
     !      Nautical Almanac (1961)
     !
     implicit none
     REAL(KIND=8), intent(in ):: d1
     REAL(KIND=8), intent(out):: h,pp,s,p,np,dh,dpp,ds,dp,dnp
     !
     !   Local variables
     !
     REAL(KIND=8)              :: d2,f,f2
     d2=d1*1.d-4
     f=360.d0
     f2=f/365.d0
     h=279.696678d0+.9856473354d0*d1+.00002267d0*d2*d2
     pp=281.220833d0+.0000470684d0*d1+.0000339d0*d2*d2+&
          .00000007d0*d2**3
     s=270.434164d0+13.1763965268d0*d1-.000085d0*d2*d2+&
          .000000039d0*d2**3
     p=334.329556d0+.1114040803d0*d1-.0007739d0*d2*d2-&
          .00000026d0*d2**3
     np=-259.183275d0+.0529539222d0*d1-.0001557d0*d2*d2-&
          .00000005d0*d2**3
     h=h/f
     pp=pp/f
     s=s/f
     p=p/f
     np=np/f
     h=h-dint(h)
     pp=pp-dint(pp)
     s=s-dint(s)
     p=p-dint(p)
     np=np-dint(np)
     dh=.9856473354d0+2.d-8*.00002267d0*d1
     dpp=.0000470684d0+2.d-8*.0000339d0*d1&
          +3.d-12*.00000007d0*d1**2
     ds=13.1763965268d0-2.d-8*.000085d0*d1+&
          3.d-12*.000000039d0*d1**2
     dp=.1114040803d0-2.d-8*.0007739d0*d1-&
          3.d-12*.00000026d0*d1**2
     dnp=+.0529539222d0-2.d-8*.0001557d0*d1-&
          3.d-12*.00000005d0*d1**2
     dh=dh/f2
     dpp=dpp/f2
     ds=ds/f2
     dp=dp/f2
     dnp=dnp/f2
     return
Referenced by setvuf(), w3updtmd::w3ucur(), and w3updtmd::w3ulev().
caldatt()
subroutine w3tidemd::caldatt (integer(kind=4), intent(in) julian, integer(kind=4), intent(out) id, integer(kind=4), intent(out) mm, integer(kind=4), intent(out) iyyy)
Definition at line 1284 of file w3tidemd.F90.
     ! See numerical recipes 2nd ed. The order of month and day have been swapped!
     ! Should be removed : same is now in W3TIMEMD
     !*********************************************************************
     IMPLICIT NONE
     INTEGER(KIND=4),    INTENT(in)  :: julian
     INTEGER(KIND=4),    INTENT(out) :: id,mm,iyyy
     INTEGER(KIND=4), PARAMETER :: IGREG=2299161
     INTEGER(KIND=4) ja,jalpha,jb,jc,jd,je
     if (julian.GE.igreg) THEN
       jalpha=int(((julian-1867216)-0.25)/36524.25)
       ja=julian+1+jalpha-int(0.25*jalpha)
     ELSE
       ja=julian
     ENDIF
     jb=ja+1524
     jc=int(6680.+((jb-2439870)-122.1)/365.25)
     jd=365*jc+int(0.25*jc)
     je=int((jb-jd)/30.6001)
     id=jb-jd-int(30.6001*je)
     mm=je-1
     IF (mm.GT.12) mm=mm-12
     iyyy=jc-4715
     IF (mm.GT.2) iyyy=iyyy-1
     IF (iyyy.LE.0) iyyy=iyyy-1
     RETURN
Referenced by tide_write_results().
dpythag()
double precision function w3tidemd::dpythag (double precision a, double precision b)
Definition at line 977 of file w3tidemd.F90.
     DOUBLE PRECISION a,b,dpythag
     DOUBLE PRECISION absa,absb
     absa=abs(a)
     absb=abs(b)
     IF (absa.gt.absb)then
       dpythag=absa*sqrt(1.0d0+(absb/absa)**2)
     else
       IF (absb.eq.0.0d0)then
         dpythag=0.0d0
       else
         dpythag=absb*sqrt(1.0d0+(absa/absb)**2)
       endif
     endif
     return
Referenced by dsvdcmp().
dsvbksb()
subroutine w3tidemd::dsvbksb (double precision, dimension(mp,np) u, double precision, dimension(np) w, double precision, dimension(np,np) v, integer m, integer n, integer mp, integer np, double precision, dimension(mp) b, double precision, dimension(np) x)
Definition at line 996 of file w3tidemd.F90.
     INTEGER m,mp,n,np,NMAX
     DOUBLE PRECISION b(mp),u(mp,np),v(np,np),w(np),x(np)
     parameter(nmax=500)
     INTEGER i,j,jj
     DOUBLE PRECISION s,tmp(NMAX)
     do j=1,n
       s=0.0d0
       IF (w(j).ne.0.0d0)then
         do i=1,m
           s=s+u(i,j)*b(i)
         end do
         s=s/w(j)
       endif
       tmp(j)=s
     end do
     do  j=1,n
       s=0.0d0
       do  jj=1,n
         s=s+v(j,jj)*tmp(jj)
       end do
       x(j)=s
     end do
     return
Referenced by svd().
dsvdcmp()
subroutine w3tidemd::dsvdcmp (double precision, dimension(mp,np) a, integer m, integer n, integer mp, integer np, double precision, dimension(np) w, double precision, dimension(np,np) v)
Definition at line 1024 of file w3tidemd.F90.
     INTEGER m,mp,n,np,NMAX
     DOUBLE PRECISION a(mp,np),v(np,np),w(np)
     parameter(nmax=500)
     INTEGER i,its,j,jj,k,l,nm
     DOUBLE PRECISION anorm,c,f,g,h,s,scale,x,y,z,rv1(NMAX)
     g=0.0d0
     scale=0.0d0
     anorm=0.0d0
     do i=1,n
       l=i+1
       rv1(i)=scale*g
       g=0.0d0
       s=0.0d0
       scale=0.0d0
       IF (i.le.m)then
         DO k=i,m
           scale=scale+abs(a(k,i))
         END DO
         IF (scale.ne.0.0d0) THEN
           DO  k=i,m
             a(k,i)=a(k,i)/scale
             s=s+a(k,i)*a(k,i)
           END DO
           f=a(i,i)
           g=-sign(sqrt(s),f)
           h=f*g-s
           a(i,i)=f-g
           DO j=l,n
             s=0.0d0
             DO k=i,m
               s=s+a(k,i)*a(k,j)
             END DO
             f=s/h
             DO k=i,m
               a(k,j)=a(k,j)+f*a(k,i)
             END DO
           END DO
           DO k=i,m
             a(k,i)=scale*a(k,i)
           END DO
           !
         END IF
         !
       END IF
       !
       w(i)=scale *g
       g=0.0d0
       s=0.0d0
       scale=0.0d0
       IF ((i.le.m).and.(i.ne.n))then
         do k=l,n
           scale=scale+abs(a(i,k))
         end do
         IF (scale.ne.0.0d0)then
           do k=l,n
             a(i,k)=a(i,k)/scale
             s=s+a(i,k)*a(i,k)
           end do
           f=a(i,l)
           g=-sign(sqrt(s),f)
           h=f*g-s
           a(i,l)=f-g
           do k=l,n
             rv1(k)=a(i,k)/h
           end do
           do j=l,m
             s=0.0d0
             do k=l,n
               s=s+a(j,k)*a(i,k)
             end do
             do k=l,n
               a(j,k)=a(j,k)+s*rv1(k)
             end do
           end do
           do k=l,n
             a(i,k)=scale*a(i,k)
           end do
         endif
       endif
       anorm=max(anorm,(abs(w(i))+abs(rv1(i))))
     end do
     do i=n,1,-1
       IF (i.lt.n)then
         IF (g.ne.0.0d0)then
           do j=l,n
             v(j,i)=(a(i,j)/a(i,l))/g
           end do
           do j=l,n
             s=0.0d0
             do k=l,n
               s=s+a(i,k)*v(k,j)
             end do
             do k=l,n
               v(k,j)=v(k,j)+s*v(k,i)
             end do
           end do
         endif
         do j=l,n
           v(i,j)=0.0d0
           v(j,i)=0.0d0
         end do
       endif
       v(i,i)=1.0d0
       g=rv1(i)
       l=i
     end do
     do i=min(m,n),1,-1
       l=i+1
       g=w(i)
       do  j=l,n
         a(i,j)=0.0d0
       end do
       IF (g.ne.0.0d0)then
         g=1.0d0/g
         do j=l,n
           s=0.0d0
           do k=l,m
             s=s+a(k,i)*a(k,j)
           end do
           f=(s/a(i,i))*g
           do k=i,m
             a(k,j)=a(k,j)+f*a(k,i)
           end do
         end do
         do j=i,m
           a(j,i)=a(j,i)*g
         end do
       else
         do  j= i,m
           a(j,i)=0.0d0
         end do
       endif
       a(i,i)=a(i,i)+1.0d0
     end do
     do k=n,1,-1
       do  its=1,30
         do  l=k,1,-1
           nm=l-1
           IF ((abs(rv1(l))+anorm).eq.anorm)  goto 2
           IF ((abs(w(nm))+anorm).eq.anorm)  goto 1
         end do
 1       c=0.0d0
         s=1.0d0
         do  i=l,k
           f=s*rv1(i)
           rv1(i)=c*rv1(i)
           IF ((abs(f)+anorm).eq.anorm) goto 2
           g=w(i)
           h=dpythag(f,g)
           w(i)=h
           h=1.0d0/h
           c= (g*h)
           s=-(f*h)
           do j=1,m
             y=a(j,nm)
             z=a(j,i)
             a(j,nm)=(y*c)+(z*s)
             a(j,i)=-(y*s)+(z*c)
           end do
         end do
 2       z=w(k)
         IF (l.eq.k)then
           IF (z.lt.0.0d0)then
             w(k)=-z
             do j=1,n
               v(j,k)=-v(j,k)
             end do
           endif
           goto 3
         endif
         IF (its.eq.30) THEN
           WRITE(6,*) 'no convergence in svdcmp'
           stop
         END IF
         x=w(l)
         nm=k-1
         y=w(nm)
         g=rv1(nm)
         h=rv1(k)
         f=((y-z)*(y+z)+(g-h)*(g+h))/(2.0d0*h*y)
         g=dpythag(f,1.0d0)
         f=((x-z)*(x+z)+h*((y/(f+sign(g,f)))-h))/x
         c=1.0d0
         s=1.0d0
         do  j=l,nm
           i=j+1
           g=rv1(i)
           y=w(i)
           h=s*g
           g=c*g
           z=dpythag(f,h)
           rv1(j)=z
           c=f/z
           s=h/z
           f= (x*c)+(g*s)
           g=-(x*s)+(g*c)
           h=y*s
           y=y*c
           do  jj=1,n
             x=v(jj,j)
             z=v(jj,i)
             v(jj,j)= (x*c)+(z*s)
             v(jj,i)=-(x*s)+(z*c)
           end do
           z=dpythag(f,h)
           w(j)=z
           IF (z.ne.0.0d0)then
             z=1.0d0/z
             c=f*z
             s=h*z
           endif
           f= (c*g)+(s*y)
           x=-(s*g)+(c*y)
           do jj=1,m
             y=a(jj,j)
             z=a(jj,i)
             a(jj,j)= (y*c)+(z*s)
             a(jj,i)=-(y*s)+(z*c)
           end do
         end do
         rv1(l)=0.0d0
         rv1(k)=f
         w(k)=x
       end do
 3     continue
     end do
     return
References dpythag().
Referenced by svd().
flex_tidana_webpage()
subroutine w3tidemd::flex_tidana_webpage (integer(kind=4), intent(in) IX, integer(kind=4), intent(in) IY, real, intent(in) XLON, real, intent(in) XLAT, integer(kind=4), intent(in) KD1, integer(kind=4), intent(in) KD2, integer, intent(in) ndef, integer, intent(in) itrend, real, dimension(ndef), intent(out) RES, real, dimension(ndef), intent(out) SSQ, real(kind=8), dimension(ndef), intent(out) RMSR0, real(kind=8), dimension(ndef), intent(out) SDEV0, real(kind=8), dimension(ndef), intent(out) RMSR, real(kind=8), dimension(ndef), intent(out) RESMAX, integer, dimension(ndef), intent(out) IMAX, integer, intent(in) ITEST)
Definition at line 2033 of file w3tidemd.F90.
     !
     !***********************************************************************
     !*
     !*  THIS PROGRAM DOES A TIDAL HEIGHTS 'HARMONIC' ANALYSIS OF IRREGULARLY
     !*  SAMPLED OBSERVATIONS.  THE ANALYSIS METHOD IS A LEAST SQUARES FIT
     !*  USING SVD COUPLED WITH NODAL MODULATION AND INFERENCE(IF SO REQUESTED).
     !*
     !*      The code is based on TOPEX analysis code originally developed by Josef
     !*      Cherniawsky (JAOT, 2001, 18(4): 649-664) and modified by Rob Bell and
     !*      Mike Foreman. Enhancements to that version include
     !*
     !*      1. Provision for multi-constituent inferences computed directly within
     !*        the least squares matrix rather than as post fit corrections. This
     !*        means that the inferred constituents will affect all constituents, not
     !*        just the reference constituent.
     !*
     !*      2. An extension to permit the analysis of current observations.
     !*
     !*      3. Removal of a central time as the basis for the calculation of the
     !*        astronomical arguments V. Now the V value for each observation, as well
     !*        as those for the nodal corrections f and u (done for the JAOT analysis),
     !*        are incorporated directly into the overdetermined matrix. These changes
     !*        mean that analyses no longer need be restricted to periods of a year or
     !*        less. (Though as the period approaches 18.6 years, using another "long
     !*        period" analysis program that solves for the "nodal satellites" directly
     !*        is advisable.)
     !*
     !***********************************************************************
     !*
     !*  FILE REFERENCE NUMBERS OF DEVICES REQUIRED BY THIS PROGRAM.
     !*      KR  - INPUT FILE  - CONTAINS THE TIDAL CONSTITUENT INFORMATION.
     !*      KR1 - INPUT FILE  - GIVES ANALYSIS TYPE AND TIDAL STATION
     !*                          DETAILS.
     !*      KR2 - INPUT FILE  - CONTAINS THE OBSERVED TIMES AND HEIGHTS.
     !*  PRESENTLY KR,KR1,KR2, AND LP ARE ASSIGNED THE RESPECTIVE VALUES
     !*  8,5,9, AND 6.  SEE THE MANUAL OR COMMENT STATEMENTS WITHIN THIS
     !*  PROGRAM FOR FURTHER DETAILS ON THEIR USE.
     !*
     !***********************************************************************
     !*
     !*  ARRAY DEFINITIONS AND DIMENSION GUIDELINES.
     !*
     !*  LET    MC      BE THE TOTAL NUMBER OF CONSTITUENTS, INCLUDING Z0
     !*                 AND ANY INFERRED CONSTITUENTS, TO BE INCLUDED IN THE
     !*                 ANALYSIS; (For T/P, MC=30 > NUMBER OF CONSTITUENTS)
     !*         TIDE_NTI    BE THE NUMBER OF TIDAL HEIGHT OBSERVATIONS;
     !*         NR      BE THE NUMBER OF INPUT RECORDS OF OBSERVED TIDAL
     !*                 HEIGHTS (For T/P data, same as TIDE_NTI, set to 200)
     !*         MPAR    BE 2*MC-1;
     !*         NEQ     BE TIDE_NTI*2 IF ALL THE OBSERVATIONS ARE EXTREMES AND
     !*                 THE DERIVATIVE CONDITION IS TO BE INCLUDED FOR EACH,
     !*                 AND TIDE_NTI OTHERWISE (= NR for T/P data).
     !*  THEN PARAMETERS NMAXP1, AND NMAXPM SHOULD BE AT LEAST MPAR+1, AND
     !*  NEQ+MPAR RESPECTIVELY.  THEY ARE CURRENTLY SET TO 40 AND 240.
     !*
     !*  TIDECON_NAME(I) IS THE ARRAY CONTAINING ALL THE CONSTITUENT NAMES,
     !*                 INCLUDING Z0 AND ANY INFERRED CONSTITUENTS, TO BE IN
     !*                 THE ANALYSIS.  IT SHOULD BE DIMENSIONED AT LEAST MC.
     !*  TIDE_FREQC(I),      ARE THE ARRAYS OF FREQUENCIES IN CYCLES/HR AND
     !*  FREQ(I)        RADIANS/HR RESPECTIVELY CORRESPONDING TO THE
     !*                 CONSTITUENT NAME(I).  THEY SHOULD BE DIMENSIONED AT
     !*                 LEAST MC.
     !*  AMP(I),PH(I)   ARE ARRAYS CONTAINING THE RAW AMPLITUDE AND PHASE FOR
     !*                 CONSTITUENT NAME(I) AS FOUND VIA THE LEAST SQUARES
     !*                 ANALYSIS.  THEY SHOULD BE DIMENSIONED AT LEAST MC.
     !*  AMPC(I),PHG(I) ARE ARRAYS CONTAINING THE AMPLITUDE AND PHASE FOR
     !*                 CONSTITUENT NAME(I) AFTER CORRECTIONS FOR NODAL
     !*                 MODULATION, ASTRONOMICAL ARGUMENT AND INFERRED
     !*                 CONSTITUENTS.  THEIR MINIMUM DIMENSION SHOULD BE MC.
     !*  TIDE_DATA(I)   AND HEIGHTS, OF THE OBSERVED DATA AS IT IS INPUT BY
     !*                 RECORD.  THEY SHOULD BE DIMENSIONED ACCORDINGLY( AT
     !*                 PRESENT ONLY 6 OBSERVATIONS ARE EXPECTED PER RECORD).
     !*  X(I)           ARRAY  CONTAINING ALL THE TIMES(IN HOURS AS
     !*                 MEASURED FROM THE CENTRE OF THE ANALYSIS PERIOD) ITS MINIMUM
     !*                 DIMENSION SHOULD BE TIDE_NTI.
     !*  NSTN(I)        IS THE ARRAY CONTAINING THE TIDAL STATION TIDECON_NAME.  IT
     !*                 SHOULD HAVE MINIMUM DIMENSION 5.
     !*  Q(I)           IS THE OVERDETERMINED ARRAY OF EQUATIONS THAT IS
     !*                 SOLVED IN THE LEAST SQUARES SENSE BY THE MODIFIED
     !*                 GRAM-SCHMIDT ALGORITHM.  IT SHOULD HAVE THE EXACT
     !*                 DIMENSION OF NMAXPM BY NMAXP1.
     !*  P(I)           IS THE ARRAY CONTAINING THE TIDAL CONSTITUENT SINE
     !*                 AND COSINE COEFICIENTS AS FOUND WITH THE LEAST
     !*                 SQUARES FIT.  IT SHOULD HAVE MINIMUM DIMENSION MPAR.
     !
     !***********************************************************************
     !
     IMPLICIT NONE
     INTEGER, INTENT(IN)         :: NDEF, ITREND, ITEST
     INTEGER(KIND=4), INTENT(IN) :: KD1, KD2, IX, IY
     REAL           , INTENT(IN) :: XLON, XLAT
     REAL(KIND=8)   , intent(out):: sdev0(ndef), rmsr0(ndef), rmsr(ndef), resmax(ndef)
     REAL           , INTENT(OUT):: SSQ(NDEF), RES(NDEF)
     INTEGER        , INTENT(OUT):: IMAX(NDEF)
     !
     INTEGER                     :: I, I1, I2, I21, II1, IDEF, ICODE,  INFLAG,  &
          J, INFTOT, IREP, J2, JCODE, JJ1, K, K2, KH1,     &
          KH2, KHM, KINF, L, M, MEQ, N, NCOL, NEW, NMAX
     REAL(KIND=8)                :: aamp, arg, arg1, arg2, arg3, c, c2, c3,     &
          fx, fxi,  s, s2, s3, ux, vx, uxi, vxi,  &
          wmin, wmax, xmid
     REAL                        :: TOLER
     REAL(KIND=8)                :: av, sdev, sum2, hrm
     DOUBLE PRECISION            :: X(NR),Y(NR), TIME(NR)
     REAL                        :: Q(NMAXPM,NMAXP1),FREQ(MC),AMP(MC),PH(MC)
     DOUBLE PRECISION            :: P(NMAXP1),CENHR,CUMHR
     DOUBLE PRECISION            :: yy
     !
     !     Additional arrays, for use in the SVD routine (J.Ch., Aug. 1997)
     DOUBLE PRECISION     :: U(NMAXPM,NMAXP1),V(NMAXP1,NMAXP1),      &
          COV(NMAXP1,NMAXP1),B(NMAXPM),W(NMAXP1),SIG(NMAXPM)
     !
     !***********************************************************************
     !
     kh1=24*kd1
     kh2=24*(kd2+1)
     khm=(kh1+kh2)/2
     hrm=khm
     cenhr=dfloat((kh2-kh1)/2)
     IF (itrend.eq.1) then
       m=2*tide_mf
     else
       m=2*tide_mf-1
     END IF
     i=0
     DO i=1,tide_mf
       freq(i)=tide_freqc(i)*twpi
     END DO
     !
     !***********************************************************************
     !*  DETERMINE THE CENTRAL HOUR OF THE ANALYSIS PERIOD AND SET UP THE
     !*  DEPENDENT AND INDEPENDENT VARIABLES, Y AND X.
     ! actually, CUMHR=24.d0*(KD-KHM) (check), but keep same notation as before
     !
     k=1
     DO i=1,tide_nti
       cumhr=-cenhr+24.d0*(tide_days(i)-kd1)
       time(i)=cumhr+dfloat(tide_secs(i))/3600.d0
       x(k)=time(i)-time(1)
       n=k
       k=k+1
     END DO
     !
     !***********************************************************************
     !*  SETTING UP THE OVERDETERMINED MATRIX AND SOLVING WITH MODIFIED SVD
     !
     irep=0
     DO idef=1,ndef   ! loop thru once or twice
       ! Modifies the time reference xmid and puts it at 0 : modification by FA, 2012/09/26
       ! the impact of that change has not been verified ...
       xmid=0. !0.5*(TIDE_HOURS(1)+TIDE_HOURS(TIDE_NTI))
       q(1:nmaxpm,1:nmaxp1)=0.0
       DO i=1,n
         !      if itrend=1, then
         !      first 2 parameters are constant and linear trend (per 365 days)
         !      fitted as const+trend(t-tmid) where tmid (=xmid) is the middle time
         !      of the analysis period (This makes the constant consistent with z0
         !      in the old analysis program)
         !      If itrend=0 then the second parameter is is associated with the next
         !      constituent
         q(i,1)=1.
         IF (itrend.eq.1) then
           !            Q(I,2)=(x(i)-xmid)/(24.*365.)
           q(i,2)=x(i)/(24.*365.)
         END IF
         q(i,nmaxp1)=tide_data(i,idef)
         icode=1
         !      should only have to assemble lhs of matrix when idef=1
         !      but something is not right if don't do it 2nd time too
         ! CALL SETVUF(TIDE_HOURS(I),xlat,I)
         DO j=2,tide_mf
           CALL vuf(tidecon_name(j),vx,ux,fx,i)
           !      check to see if this constituent is to be used for inference
           inflag=0
           kinf=0
           IF (tide_nin.GE.0) THEN
             do k=1,tide_nin
               IF (tidecon_name(j).eq.tide_konan(k)) then
                 inflag=1
                 kinf=k
                 EXIT
               END IF
             END DO
           END IF
           !
           IF (inflag.eq.0) then
             arg=(vx+ux)*twpi
             IF (itrend.eq.1) then
               j2=2*(j-1)+1
             else
               j2=2*(j-1)
             END IF
             jj1=j2+1
             q(i,j2)=cos(arg)*fx
             q(i,jj1)=sin(arg)*fx
           else
             IF (itrend.eq.1) then
               j2=2*(j-1)+1
             else
               j2=2*(j-1)
             END IF
             jj1=j2+1
             arg1=(vx+ux)*twpi
             q(i,j2)=cos(arg1)*fx
             q(i,jj1)=sin(arg1)*fx
             do k2=1,tide_ninf(kinf)
               CALL vuf(tide_konin(kinf,k2),vxi,uxi,fxi,i)
               !      freq is radians/hr but sigin is cycles/hr
               arg2=(vxi+uxi)*twpi
               c2=cos(arg2)
               s2=sin(arg2)
               arg3=tide_zeta(kinf,k2)*fac
               c3=cos(arg3)
               s3=sin(arg3)
               q(i,j2)=q(i,j2)+fxi*tide_r(kinf,k2)*(c2*c3-s2*s3)
               q(i,jj1)=q(i,jj1)+fxi*tide_r(kinf,k2)*(c2*s3+s2*c3)
             END DO
           END IF
         END DO ! j
       END DO  !i
 #ifdef W3_T
       WRITE(6,*) 'assembled overdetermined matrix and/or rhs'
 #endif
       nmax=m
       meq=n
       ssq(idef)=1.0
       res(idef)=1.0
       ncol=nmax
       new=nmax
       !
       !***********************************************************************
       !*  CALCULATION OF THE STANDARD DEVIATION OF THE RIGHT HAND SIDES OF
       !*  THE OVERDETERMINED SYSTEM
       !
       av=0.d0
       DO i=1,meq
         av=av+q(i,nmaxp1)
       END DO
       av=av/meq
       sdev=0.d0
       DO i=1,meq
         sdev=sdev+(q(i,nmaxp1)-av)**2
       END DO
       sdev=sdev/(meq-1)
       sdev=sqrt(sdev)
       sdev0(idef)=sdev
 109   CONTINUE
       !
       !   USE SINGULAR-VALUE-DECOMPOSITION TO SOLVE THE OVERDETERMINED SYSTEM
       !
       toler=1.e-5
       DO i=1,nmaxpm
         sig(i)=1.d0
       END DO
       !
       !      no solution if meq lt m. ie underdetermined system
       !      go to next time series
       IF (meq.le.m) then
         write(ndset,*) ' underdetermined system: no svd solution',ix,iy,meq,m
         stop
       END IF
 #ifdef W3_T
       WRITE(6,*) ' applying svd'
 #endif
       CALL svd(q,u,v,cov,w,p,b,sig,icode,meq,nmax,nmaxpm,nmaxp1,toler     &
            ,jcode,ssq(idef),res(idef))
       !        IF (JCODE.GT.0) WRITE(LP,55)JCODE
       !   55 FORMAT('COLUMN',I5,' IS THE 1ST DEPENDENT COLUMNS IN SVD')
       !      write out eigenvalues
       wmax=-1000.
       wmin=1000.
       do i=1,nmax
         IF (w(i).gt.wmax) wmax=w(i)
         IF (w(i).lt.wmin) wmin=w(i)
       end do
       !        write(6,*) ' max, min eigenvalues =',wmax,wmin
       !      write(6,*) ' all eigenvalues'
       !      write(6,56) (w(i),i=1,nmax)
 56    format(10e12.5)
       !***********************************************************************
       IF (ssq(idef).gt.1.e-10) then
         rmsr0(idef)=sqrt(ssq(idef)/(meq-m))
       else
         rmsr0(idef)=0.
       END IF
       rmsr(idef)=0.d0
       resmax(idef)=0.
       do  i=1,n
         yy=q(i,nmaxp1)
         rmsr(idef)=rmsr(idef)+yy*yy
         IF (abs(yy).gt.resmax(idef)) then
           resmax(idef)=abs(yy)
           imax(idef)=i
         END IF
       end do
 160   format(' ',7i2,f15.5,f10.5,i6)
       IF (rmsr(idef).gt.1.e-10) then
         rmsr(idef)=dsqrt(rmsr(idef)/(n-m))
       else
         rmsr(idef)=0.
       END IF
       !      close(unit=25)
       !
       !***********************************************************************
       !*  CALCULATE AMPLITUDES AND PHASES
       !
       !      if itrend=1 then the linear trend is shown as the phase of the constant
       !      Z0 term (& the true phase of Z0 is zero)
       !      otherwise, the phase of Z0 is shown as zero
       amp(1)=p(1)
       IF (itrend.eq.1) then
         ph(1)=p(2)
       else
         ph(1)=0.
       END IF
       DO i=2,tide_mf
         !
         IF (itrend.eq.1) then
           i2=2*(i-1)+1
         else
           i2=2*(i-1)
         END IF
         i21=i2+1
         c=p(i2)
         s=p(i21)
         aamp=sqrt(c*c+s*s)
         IF (aamp.LT.1.e-5) THEN
           ph(i)=0.
         ELSE
           ph(i)=atan2(s,c)/fac
           IF (ph(i).LT.0.) ph(i)=ph(i)+360.
         END IF
         amp(i)=aamp
       END DO  ! end of loop on TIDE_MF
       !***********************************************************************
       !      Note that with f & u included in the lsq fit, we only need V from routine VUF
       !      but we don't want to correct with V for a central hour. Better to include
       !      the right V in the lsq fit. This has been done.
       tide_ampc(1,idef)=amp(1)
       tide_phg(1,idef)=ph(1)
       DO i=2,tide_mf
         tide_ampc(i,idef)=amp(i)
         tide_phg(i,idef)=ph(i)
       END DO
       !
       tide_sig3(:,idef)=0.
       tide_ttest(:,idef)=0.
       !
       IF (itest.GE.1) THEN
         !---------------------------------------------------
         !
         i=1
         IF (cov(1,1).gt.1.e-8) then
           tide_sig1(i,idef)=sqrt(cov(1,1))*rmsr0(idef)
         else
           tide_sig1(i,idef)=0.
         END IF
         IF (itrend.eq.1.and.cov(2,2).gt.1.e-8) then
           tide_sig2(i,idef)=sqrt(cov(2,2))*rmsr0(idef)
         else
           tide_sig2(i,idef)=0.
         END IF
         tide_sig3(i,idef)=0.
         tide_ttest(i,idef)=0.
         !
         !    results for the other constituents
         !
         DO i=2,tide_mf
           IF (itrend.eq.1) then
             i2=2*(i-1)+1
           else
             i2=2*(i-1)
           END IF
           ii1=i2+1
           !
           !      multiply cov values with residual standard deviation, as described in equation
           !      (6) of Cherniasky et al. (2001)
           !
           IF (cov(i2,i2).gt.1.e-8) then
             tide_sig1(i,idef)=sqrt(cov(i2,i2))*rmsr0(idef)
           else
             tide_sig1(i,idef)=0.
           END IF
           IF (cov(ii1,ii1).gt.1.e-8) then
             tide_sig2(i,idef)=sqrt(cov(ii1,ii1))*rmsr0(idef)
           else
             tide_sig2(i,idef)=0.
           END IF
           !      from equation 11 in Pawlowicz et al (2002)
           c=tide_ampc(i,idef)*cos(tide_phg(i,idef)*fac)
           s=tide_ampc(i,idef)*sin(tide_phg(i,idef)*fac)
           tide_sig3(i,idef)=sqrt(((c*tide_sig1(i,idef))**2+(s*tide_sig2(i,idef))**2)/(c**2+s**2))
           tide_ttest(i,idef)=tide_ampc(i,idef)/tide_sig3(i,idef)
         END DO
         !---------------------------------------------------
       END IF ! (ITEST.GE.1)
       !
       !  now inferred constituents
       !
       IF (tide_nin.GE.0) THEN
         l=0
         do k=1,tide_nin
           do i=2,tide_mf
             IF (tidecon_name(i).eq.tide_konan(k)) EXIT
           END DO
           i1=i
           do k2=1,tide_ninf(k)
             l=l+1
             tide_ampci(k,k2,idef)=tide_ampc(i1,idef)*tide_r(k,k2)
             tide_phgi(k,k2,idef)=tide_phg(i1,idef)-tide_zeta(k,k2)
           END DO
         END DO
         inftot=l
       END IF
       !
       !***********************************************************************
       !      compute (Cherniawsky et al (2001), page 653) and rank correlation coefficients
       !      largest niter value are computed and shown
       !      if itrend=1, then the second part of Z0 is the linear trend coefficient
       !
       !      do i=1,m
       !        do j=1,i
       !          cor(i,j)=cov(i,j)/sqrt(cov(i,i)*cov(j,j))
       !          END DO
       !        END DO
       !
       !      niter=20
       !      do 81 iter=1,niter
       !        cormax=0.
       !        do i=2,m
       !          im1=i-1
       !          do j=1,im1
       !            ac=abs(cor(i,j))
       !            if (ac.gt.cormax) then
       !              cormax=ac
       !              imax=i
       !              jmax=j
       !             END IF
       !            END DO
       !          END DO
       !        if (itrend.eq.1) then
       !          iconst=(imax+1)/2
       !          jconst=(jmax+1)/2
       !        else
       !          iconst=(imax+2)/2
       !          jconst=(jmax+2)/2
       !          END IF
       !        write(lp,83) iter,cormax,imax,jmax,TIDECON_NAME(iconst),TIDECON_NAME(jconst)
       !83      format(i5,' largest correlation coefficient is ',f8.3,' at (i,j)='     &
       !           ,2i5,' for constituents ',a5,' and ',a5)
       !        cor(imax,jmax)=0.
       !        END DO
       !
     END DO  ! end of loop on IDEF
     RETURN
References fac, ndset, svd(), tide_ampc, tide_ampci, tide_data, tide_days, tide_freqc, tide_konan, tide_konin, tide_mf, tide_nin, tide_ninf, tide_nti, tide_phg, tide_phgi, tide_r, tide_secs, tide_sig1, tide_sig2, tide_sig3, tide_ttest, tide_zeta, tidecon_name, twpi, and vuf().
juldayt()
integer*4 function w3tidemd::juldayt (integer id, integer mm, integer iyyy)
Definition at line 1257 of file w3tidemd.F90.
     ! See numerical recipes 2nd ed. The order of month and day have been swapped!
     !*********************************************************************
     IMPLICIT NONE
     INTEGER id,mm,iyyy
     INTEGER IGREG
     INTEGER*4 ja,jm,jy
     INTEGER*4 JULDAYT
     igreg=15+31*(10+12*1582)
     jy=iyyy
     IF (jy.EQ.0) WRITE(6,*) 'There is no zero year !!'
     IF (jy.LT.0) jy=jy+1
     IF (mm.GT.2) THEN
       jm=mm+1
     ELSE
       jy=jy-1
       jm=mm+13
     ENDIF
     juldayt=int(365.25*jy)+int(30.6001*jm)+id+1720995
     IF (id+31*(mm+12*iyyy).GE.igreg) THEN
       ja=int(0.01*jy)
       juldayt=juldayt+2-ja+int(0.25*ja)
     ENDIF
     RETURN
Referenced by tide_read_anapar(), and tide_read_timeseries().
opnvuf()
subroutine w3tidemd::opnvuf (character*256, intent(in) filename)
Definition at line 1747 of file w3tidemd.F90.
     IMPLICIT NONE
     CHARACTER*256, INTENT(IN)     :: filename
     INTEGER                  :: J, J1, JBASE, J4, K, K1, JL, JLM, KR
     DOUBLE PRECISION, PARAMETER   :: TWOPI=3.1415926535898*2.
     DOUBLE PRECISION, PARAMETER   :: FAC=twpi/360.
     kr=8
     !
     !***********************************************************************
     !*  HERE THE MAIN CONSTITUENTS AND THEIR DOODSON NUMBERS ARE READ IN
     !*  FORMAT (6X,A5,1X,6I3,F5.2,I4). THE VALUES ARE RESPECTIVELY
     !*     TIDECON_ALLNAMES    = CONSTITUENT NAME
     !*  II,JJ,KK,LL,MM,NN = THE SIX DOODSON NUMBERS
     !*     SEMI   = PHASE CORRECTION
     !*     NJ     = THE NUMBER OF SATELLITES FOR THIS CONSTITUENT.
     !*  THE END OF ALL MAIN CONSTITUENTS IS DENOTED BY A BLANK CARD.
     !
     ALLOCATE(tidecon_allnames(170))
     ALLOCATE(ii(mc2),jj(mc2),kk(mc2),ll(mc2),mm(mc2),nn(mc2), &
          semi(mc2), nj(170))
     ALLOCATE(konco_con(320),coef_con(320))
     kr=8
     open(unit=kr,file=filename,status='old',form='formatted')
     jbase=0
     DO k=1,1000
       READ(kr,60)tidecon_allnames(k),ii(k),jj(k),kk(k),ll(k),mm(k),nn(k),semi(k), &
            nj(k)
 60    FORMAT(6x,a5,1x,6i3,f5.2,i4)
       !WRITE(995,'(I4,A5,1X,6I3,F5.2,I4)') K,TIDECON_ALLNAMES(K),II(K),JJ(K),KK(K),LL(K),MM(K),NN(K),SEMI(K), &
       !           NJ(K)
       IF (tidecon_allnames(k).eq.kblank) go to 100
 70    j1=jbase+1
       IF (nj(k).LT.1) THEN
         nj(k)=1
         jl=j1
         ph(j1)=0.
         ee(j1)=0.
         ldel(j1)=0
         mdel(j1)=0
         ndel(j1)=0
         ir(j1)=0
       ELSE
         jl=jbase+nj(k)
         !
         !***********************************************************************
         !*  IF NJ>0, INFORMATION ON THE SATELLITE CONSTITUENTS IS READ , THREE
         !*  SATELLITES PER CARD, IN THE FORMAT (11X,3(3I3,F4.2,F7.4,1X,I1,1X)).
         !*  FOR EACH SATELLITE THE VALUES READ ARE
         !*     LDEL,MDEL,NDEL = THE CHANGES IN THE LAST THREE DOODSON NUMBERS
         !*                  FROM THOSE OF THE MAIN CONSTITUENT.
         !*     PH     = THE PHASE CORRECTION
         !*     EE     = THE AMPLITUDE RATIO OF THE SATELLITE TIDAL POTENTIAL TO
         !*            THAT OF THE MAIN CONSTITUENT.
         !*     IR     = 1 IF THE AMPLITUDE RATIO HAS TO BE MULTIPLIED BY THE
         !*            LATITUDE CORRECTION FACTOR FOR DIURNAL CONSTITUENTS
         !*            2 IF THE AMPLITUDE RATIO HAS TO BE MULTIPLIED BY THE
         !*            LATITUDE CORRECTION FACTOR FOR SEMI-DIURNAL CONSTI-
         !*            TUENTS.
         !*            OTHERWISE IF NO CORRECTION IS REQUIRED TO THE AMPLITUDE
         !*            RATIO.
         !
         READ(kr,80)(ldel(j),mdel(j),ndel(j),ph(j),ee(j),ir(j),j=j1,jl)
 80      FORMAT((11x,3(3i3,f4.2,f7.4,1x,i1,1x)))
       END IF
       jbase=jl
     end do
 100 ntidal_con=k-1
     jlm=jl
     !
     !***********************************************************************
     !*  THE SHALLOW WATER CONSTITUENTS AND THE MAIN CONSTITUENTS FROM WHICH
     !*  THEY ARE DERIVED ARE READ IN HERE WITH THE FORMAT
     !*  (6X,A5,I1,2X,4(F5.2,A5,5X)). THE VALUES ARE RESPECTIVELY
     !*     TIDECON_ALLNAMES    = NAME  OF THE SHALLOW WATER CONSTITUENT
     !*     NJ     = NUMBER OF MAIN CONSTITUENTS FROM WHICH IT IS DERIVED.
     !*     COEF_CON,KONCO_CON = COMBINATION NUMBER AND NAME OF THESE MAIN
     !*              CONSTITUENTS.
     !*  THE END OF THESE CONSTITUENTS IS DENOTED BY A BLANK CARD.
     !
     jbase=0
     k1=ntidal_con+1
     DO  k=k1,1000
       j1=jbase+1
       j4=j1+3
       READ(kr,130)tidecon_allnames(k),nj(k),(coef_con(j),konco_con(j),j=j1,j4)
 130   FORMAT(6x,a5,i1,2x,4(f5.2,a5,5x))
       !WRITE(995,130)TIDECON_ALLNAMES(K),NJ(K),(COEF_CON(J),KONCO_CON(J),J=J1,J4)
       IF (tidecon_allnames(k).eq.kblank) go to 170
       jbase=jbase+nj(k)
     end do
 170 ntotal_con=k-1
     !  Write out  for cut and paste ...
     !    WRITE(6,*) 'Numbers:',NTIDAL_CON, NTOTAL_CON, JLM, J1, J4
     !    WRITE(996,*) NTIDAL, NTOTAL_CON, JLM, J1, J4
     !999      FORMAT(10("'",A5,"',"),' &')
     !        WRITE(996,999) TIDECON_ALLNAMES(1:NTOTAL_CON)
     !998      FORMAT(10(I3,","),' &')
     !997      FORMAT(10(I4,","),' &')
     !991      FORMAT(10(F5.2,","),' &')
     !990      FORMAT(10(F7.4,","),' &')
     !        WRITE(996,998) II(1:NTIDAL_CON)
     !        WRITE(996,998) JJ(1:NTIDAL_CON)
     !        WRITE(996,998) KK(1:NTIDAL_CON)
     !        WRITE(996,998) LL(1:NTIDAL_CON)
     !        WRITE(996,998) MM(1:NTIDAL_CON)
     !        WRITE(996,998) NN(1:NTIDAL_CON)
     !        WRITE(996,991) SEMI(1:NTIDAL_CON)
     !        WRITE(996,997) NJ(1:NTOTAL_CON)
     !        WRITE(996,998) LDEL(1:JLM)
     !        WRITE(996,998) MDEL(1:JLM)
     !        WRITE(996,998) NDEL(1:JLM)
     !        WRITE(996,991) PH(1:JLM)
     !        WRITE(996,990) EE(1:JLM)
     !        WRITE(996,998) IR(1:JLM)
     !        WRITE(996,991) COEF_CON(1:J4)
     !        WRITE(996,999) KONCO_CON(1:J4)
     RETURN
     !
     !***********************************************************************
     !*  NTIDAL_CON IS THE NUMBER OF MAIN CONSTITUENTS
     !*  NTOTAL_CON IS THE NUMBER OF CONSTITUENTS (MAIN + SHALLOW WATER)
     !*  FOR  THE GIVEN TIME hr, THE TABLE OF F AND V+U VALUES IS
     !*  CALCULATED FOR ALL THE CONSTITUENTS.
     !*     F IS THE NODAL MODULATION ADJUSTMENT FACTOR FOR AMPLITUDE
     !*     U IS THE NODAL MODULATION ADJUSTMENT FACTOR FOR PHASE
     !*     V IS THE ASTRONOMICAL ARGUMENT ADJUSTMENT FOR PHASE.
     !
     !      setvuf calculates the V,u,f values at time hr for all constituents
     !
References coef_con, ee, file(), ir, kblank, konco_con, ldel, mc2, mdel, ndel, ntidal_con, ntotal_con, ph, semi, and tidecon_allnames.
setvuf()
subroutine w3tidemd::setvuf (real(kind=8), intent(in) hr, real, intent(in) XLAT, integer, intent(in) ITIME)
Definition at line 1891 of file w3tidemd.F90.
     !      setvuf calculates the V,u,f values at time hr for all constituents
     IMPLICIT NONE
     REAL(KIND=8), intent(in)  :: hr
     REAL,         INTENT(IN)  :: XLAT
     INTEGER,      INTENT(IN)  :: ITIME
     !
     !   Local variables
     !
     INTEGER                   :: KD0, INT24, INTDYS, &
          JBASE, J, K, L, J1, K1, JL, LK, iflag
     INTEGER                   :: IV, IUU
     !
     REAL(KIND=4), parameter   :: pi=3.1415926536
     REAL(KIND=4), parameter   :: twopi=2.*3.1415926536
     !
     REAL                      :: SLAT, VDBL, VV, SUMC, SUMS, RR, &
          UUDBL, UU, CXLAT
     REAL(KIND=8)              :: d1,h,pp,s,p,enp,dh,dpp,ds,dp,dnp,hh,tau
     INTEGER                   :: indx(170)
     cxlat = max(abs(xlat), 5.)
     slat=sin(pi*cxlat/180.)
     !
     !***********************************************************************
     !*  THE ASTRONOMICAL ARGUMENTS ARE CALCULATED BY LINEAR APPROXIMATION
     !*  AT THE MID POINT OF THE ANALYSIS PERIOD.
     !
     !      day number measured from January 0.5 1900 (i.e.,
     !      1200 UT December 31, 1899
     d1=hr/24.d0
     ! This was with "gregorian days from KDAY"
     !call gday(31,12,99,18,kd0)   !  CALL GDAY(IDd,IMm,IYy,ICc,KDd)
     ! Now uses "julian days from JULDAYT"
     ! KD0= 693961
     !KD0=JULDAYT(31,12,1899)   ! JULDAYT(id,mm,iyyy)
     kd0= 2415020
     ! substracting 0.5day is not necessary anymore with new time functions
     d1=d1-dfloat(kd0)
     call astr(d1,h,pp,s,p,enp,dh,dpp,ds,dp,dnp)
     int24=24
     intdys=int((hr+0.00001)/int24)
     hh=hr-dfloat(intdys*int24)
     tau=hh/24.d0+h-s
     !
     !***********************************************************************
     !*  ONLY THE FRACTIONAL PART OF A SOLAR DAY NEED BE RETAINED FOR COMPU-
     !*  TING THE LUNAR TIME TAU.
     !
     jbase=0
     DO  k=1,ntidal_con
       do l=1,tide_mf
         IF (tidecon_allnames(k).eq.tidecon_name(l)) then
           indx(k)=l
         END IF
       end do
       vdbl=ii(k)*tau+jj(k)*s+kk(k)*h+ll(k)*p+mm(k)*enp+nn(k)*pp+semi(k)
       iv=vdbl
       iv=(iv/2)*2
       vv=vdbl-iv
       j1=jbase+1
       jl=jbase+nj(k)
       sumc=1.
       sums=0.
       DO j=j1,jl
         !
         !***********************************************************************
         !*  HERE THE SATELLITE AMPLITUDE RATIO ADJUSTMENT FOR LATITUDE IS MADE
         !
         rr=ee(j)
         l=ir(j)+1
         IF (l.EQ.2) THEN
           rr=ee(j)*0.36309*(1.-5.*slat*slat)/slat
         ELSE IF (l.EQ.3) THEN
           rr=ee(j)*2.59808*slat
         END IF
         uudbl=ldel(j)*p+mdel(j)*enp+ndel(j)*pp+ph(j)
         iuu=uudbl
         uu=uudbl-iuu
         sumc=sumc+rr*cos(uu*twopi)
         sums=sums+rr*sin(uu*twopi)
       end do
       f_arg(k,itime)=sqrt(sumc*sumc+sums*sums)
       v_arg(k,itime)=vv
       u_arg(k,itime)=atan2(sums,sumc)/twopi
       jbase=jl
     end do
     !
     !***********************************************************************
     !*  HERE F AND V+U OF THE SHALLOW WATER CONSTITUENTS ARE COMPUTED FROM
     !*  THE VALUES OF THE MAIN CONSTITUENT FROM WHICH THEY ARE DERIVED.
     !
     jbase=0
     k1=ntidal_con+1
     IF (k1.GT.ntotal_con) RETURN
     !
     DO k=k1,ntotal_con
       f_arg(k,itime)=1.0
       v_arg(k,itime)=0.0
       u_arg(k,itime)=0.
       iflag=0
       DO lk=1,tide_mf
         IF (tidecon_allnames(k).eq.tidecon_name(lk)) then
           iflag=1
           EXIT
         END IF
       END DO   ! lk
       DO j=tide_indexj(k),tide_indexj(k)+nj(k)-1
         l=tide_indexjk(j)
         f_arg(k,itime)=f_arg(k,itime)*f_arg(l,itime)**abs(coef_con(j))
         v_arg(k,itime)=v_arg(k,itime)+coef_con(j)*v_arg(l,itime)
         u_arg(k,itime)=u_arg(k,itime)+coef_con(j)*u_arg(l,itime)
       END DO   ! J
     END DO     ! K
     !  Test output for verification purposes
     IF (itime.EQ.-1) THEN
       WRITE(992,'(A,F20.2,13F8.3)') 'TEST ISEA 0:',    &
            d1,h,s,tau,pp,s,p,enp,dh,dpp,ds,dp,dnp,xlat
       do l=1,tide_mf
         do k=1,ntotal_con
           IF (tidecon_allnames(k).eq.tidecon_name(l)) then
             tide_index(l)=k
             WRITE(992,'(A,4I9,F12.0,3F8.3,I4,X,A)') 'TEST ISEA 1:',1,l,20071201,0,hr,    &
                  f_arg(k,itime),u_arg(k,itime),v_arg(k,itime),tide_index(l),tidecon_name(l)
           END IF
         END DO
       ENDDO
     ENDIF
     RETURN
     !
References astr(), coef_con, ee, f_arg, ir, ldel, mdel, ndel, ntidal_con, ntotal_con, ph, constants::pi, semi, tide_index, tide_indexj, tide_indexjk, tide_mf, tidecon_allnames, tidecon_name, u_arg, and v_arg.
setvuf_fast()
subroutine w3tidemd::setvuf_fast (real(kind=8), intent(in) h, real(kind=8), intent(in) pp, real(kind=8), intent(in) s, real(kind=8), intent(in) p, real(kind=8), intent(in) enp, real(kind=8), intent(in) dh, real(kind=8), intent(in) dpp, real(kind=8), intent(in) ds, real(kind=8), intent(in) dp, real(kind=8), intent(in) dnp, real(kind=8), intent(in) tau, real, intent(in) XLAT, real, dimension(ntil), intent(out) F, real, dimension(ntil), intent(out) U, real, dimension(ntil), intent(out) V)
Definition at line 532 of file w3tidemd.F90.
     !      setvuf calculates the V,u,f values at time hr for all constituents
     IMPLICIT NONE
     REAL,         INTENT(IN)  :: XLAT
     REAL(KIND=8), intent(in)  :: h,pp,s,p,enp,dh,dpp,ds,dp,dnp,tau
     INTEGER, PARAMETER        :: NTIL=44
     REAL        , INTENT(OUT) :: F(NTIL),U(NTIL),V(NTIL)
     REAL                      :: FA(170),UA(170),VA(170)
     !
     !   Local variables
     !
     INTEGER                   :: K, L, L2, JBASE, J1, J, JL, K1
     REAL(KIND=4), parameter   :: pi=3.1415926536
     REAL(KIND=4), parameter   :: twopi=2.*3.1415926536
     REAL                      :: SLAT, VDBL, RR, SUMC, SUMS, UUDBL, UU, CXLAT
     INTEGER                   :: IUU, IV
     ! This comment was taken from t_tide, a matlab tidal prediction suite
     !
     ! Apparently the second-order terms in the tidal potential go to zero
     ! at the equator, but the third-order terms do not. Hence when trying
     ! to infer the third-order terms from the second-order terms, the
     ! nodal correction factors blow up. In order to prevent this, it is
     ! assumed that the equatorial forcing is due to second-order forcing
     ! OFF the equator, from about the 5 degree location. Latitudes are
     ! hence (somewhat arbitrarily) forced to be no closer than 5 deg to
     ! the equator, as per note in Foreman.
     cxlat = max(abs(xlat), 5.)
     slat=sin(pi*cxlat/180.)
     jbase=0
     ! All
     ! 1'Z0  *','SA   ','SSA *','MSM *','MM   *,'MSF *','MF  *','ALP1*','2Q1  ','SIG1 ', &
     !11'Q1   ','RHO1 ','O1  *','TAU1 ','BET1 ','NO1  ','CHI1 ','PI1  ','P1  *','S1   ', &
     !21'K1  *','PSI1 ','PHI1 ','THE1 ','J1   ','OO1  ','UPS1 ','OQ2  ','EPS2*','2N2 *', &
     !31'MU2 *','N2  *','NU2 *','GAM2 ','H1   ','M2  *','H2   ','LDA2*','L2  *','T2   ', &
     !41'S2  *','R2   ','K2  *','ETA2 ','M3   ','2PO1 ','SO1  ','ST36 ','2NS2 ','ST37 ', &
     !51'ST1  ','ST2  ','ST3  ','O2   ','ST4  ','SNK2 ','OP2  ','MKS2*','ST5  ','ST6  ', &
     !61'2SK2 ','MSN2 ','ST7  ','2SM2 ','ST38 ','SKM2 ','2SN2 ','NO3  ','MO3  ','NK3  ', &
     !71'SO3  ','MK3  ','SP3  ','SK3  ','ST8  ','N4   ','3MS4 ','ST39 ','MN4  ','ST40 ', &
     !81'ST9  ','M4   ','ST10 ','SN4  ','KN4  ','MS4  ','MK4  ','SL4  ','S4   ','SK4  ', &
     !91'MNO5 ','2MO5 ','3MP5 ','MNK5 ','2MP5 ','2MK5 ','MSK5 ','3KM5 ','2SK5 ','ST11 ', &
     !01'2NM6 ','ST12 ','ST41 ','2MN6 ','ST13 ','M6   ','MSN6 ','MKN6 ','2MS6 ','2MK6 ', &
     !11'NSK6 ','2SM6 ','MSK6 ','ST42 ','S6   ','ST14 ','ST15 ','M7   ','ST16 ','3MK7 ', &
     !21'ST17 ','ST18 ','3MN8 ','ST19 ','M8   ','ST20 ','ST21 ','3MS8 ','3MK8 ','ST22 ', &
     !31'ST23 ','ST24 ','ST25 ','ST26 ','4MK9 ','ST27 ','ST28 ','M10  ','ST29 ','ST30 ', &
     !41'ST31 ','ST32 ','ST33 ','M12  ','ST34 ','ST35 '/)
     !   Possible
     !       'Z0   ', 'SSA  ', 'MSM  ', 'MM   ', 'MSF  ', 'MF   ', 'ALP1 ', '2Q1  ', 'SIG1 ', 'Q1   ',  &
     !       'RHO1 ', 'O1   ', 'TAU1 ', 'BET1 ', 'NO1  ', 'CHI1 ', 'P1   ', 'K1   ', 'PHI1 ', 'THE1 ',  &
     !       'J1   ', 'SO1  ', 'OO1  ', 'UPS1 ', 'OQ2  ', 'EPS2 ', '2N2  ', 'MU2  ', 'N2   ', 'NU2  ',  &
     !       'M2   ', 'MKS2 ', 'LDA2 ', 'L2   ', 'S2   ', 'K2   ', 'MSN2 ', 'ETA2 ', 'MO3  ', 'M3   ',  &
     !       'SO3  ', 'MK3  ', 'SK3  ', 'MN4  ', 'M4   ', 'SN4  ', 'MS4  ', 'MK4  ', 'S4   ', 'SK4  ',  &
     !       '2MK5 ', '2SK5 ', '2MN6 ', 'M6   ', '2MS6 ', '2MK6 ', '2SM6 ', 'MSK6 ', '3MK7 ', 'M8   ' /)
     ! Subset
     !       'Z0   ', 'SSA  ', 'MSM  ', 'MM   ', 'MSF  ', 'MF   ',  &
     !                'O1   ',                                     'P1   ', 'K1   '                  ,  &
     !                                                    'EPS2 ', '2N2  ', 'MU2  ', 'N2   ', 'NU2  ',  &
     !       'M2   ', 'MKS2 ', 'LDA2 ', 'L2   ', 'S2   ', 'K2   ', 'MSN2 ', 'ETA2 ', 'MO3  ', 'M3   ',  &
     !       'SO3  ', 'MK3  ', 'SK3  ', 'MN4  ', 'M4   ', 'SN4  ', 'MS4  ', 'MK4  ', 'S4   ', 'SK4  ',  &
     !       '2MK5 ', '2SK5 ', '2MN6 ', 'M6   ', '2MS6 ', '2MK6 ', '2SM6 ', 'MSK6 ', '3MK7 ', 'M8   ' /)
     !
     jbase=0
     ! initialize arrays to avoid NaN values
     fa(:)=0
     ua(:)=0
     va(:)=0
     DO k=1,ntidal_con
       j1=jbase+1
       jl=jbase+nj(k)
       DO l=1,tide_mf
         IF (tide_index2(l).EQ.k) THEN
           vdbl=ii(k)*tau+jj(k)*s+kk(k)*h+ll(k)*p+mm(k)*enp+nn(k)*pp+semi(k)
           iv=vdbl
           iv=(iv/2)*2
           sumc=1.
           sums=0.
           DO j=j1,jl
             ! ITIME ???
             !***********************************************************************
             !*  HERE THE SATELLITE AMPLITUDE RATIO ADJUSTMENT FOR LATITUDE IS MADE
             !
             rr=ee(j)
             l2=ir(j)+1
             IF (l2.EQ.2) THEN
               rr=ee(j)*0.36309*(1.-5.*slat*slat)/slat
             ELSE IF (l2.EQ.3) THEN
               rr=ee(j)*2.59808*slat
             END IF
             uudbl=ldel(j)*p+mdel(j)*enp+ndel(j)*pp+ph(j)
             iuu=uudbl
             uu=uudbl-iuu
             sumc=sumc+rr*cos(uu*twopi)
             sums=sums+rr*sin(uu*twopi)
           END DO
           !
           fa(k)=sqrt(sumc*sumc+sums*sums)
           va(k)=vdbl-iv
           ua(k)=atan2(sums,sumc)/twopi
         END IF
         jbase=jl ! (indx(L).EQ.K)
       END DO   ! L
     END DO     ! K
     !
     !  HERE F AND V+U OF THE SHALLOW WATER CONSTITUENTS ARE COMPUTED FROM
     !  THE VALUES OF THE MAIN CONSTITUENT FROM WHICH THEY ARE DERIVED.
     !
     k1=ntidal_con+1
     IF (k1.GT.ntotal_con) RETURN
     !
     DO k=k1,ntotal_con
       fa(k)=1.0
       va(k)=0.0
       ua(k)=0.
       DO j=tide_indexj(k),tide_indexj(k)+nj(k)-1
         l2=tide_indexjk(j)
         fa(k)=fa(k)*fa(l2)**abs(coef_con(j))
         va(k)=va(k)+coef_con(j)*va(l2)
         ua(k)=ua(k)+coef_con(j)*ua(l2)
       END DO   ! J
     END DO     ! K
     !
     DO l=1,tide_mf
       f(l)=fa(tide_index2(l))
       u(l)=ua(tide_index2(l))
       v(l)=va(tide_index2(l))
     END DO   ! L
     RETURN
     !
References coef_con, ee, ir, ldel, mdel, ndel, ntidal_con, ntotal_con, ph, constants::pi, semi, tide_index2, tide_indexj, tide_indexjk, and tide_mf.
Referenced by w3updtmd::w3ucur(), and w3updtmd::w3ulev().
svd()
subroutine w3tidemd::svd (real, dimension(mm,n2), intent(inout) q, double precision, dimension(mm,n2), intent(out) u, double precision, dimension(n2,n2), intent(out) v, double precision, dimension(n2,n2), intent(out) cov, double precision, dimension(n2), intent(out) w, double precision, dimension(n2), intent(out) p, double precision, dimension(mm), intent(out) b, double precision, dimension(mm), intent(inout) sig, integer, intent(in) ic, integer, intent(in) m, integer, intent(in) n, integer, intent(in) mm, integer, intent(in) N2, real, intent(in) toler, integer, intent(inout) jc, real, intent(inout) ssq, real, intent(inout) res)
Definition at line 1314 of file w3tidemd.F90.
     !-----------------------------------------------------------------------
     ! svd uses singular-value-decomposition to calculate the least-squares
     ! solution p to an overdetermined system of linear equations with
     ! coefficient matrix q, which includes right hand side vector b.
     !
     ! there are two ways to use svd:
     ! 1 given an overdetermined system, svd will orthogonalize
     !   a and b and produce the least-squares solution.
     ! 2 given an orthogonalized a (i.e. output from 1),
     !   svd will orthogonalize b with respect to a and produce
     !   the least-squares solution. this allows the use of
     !   multiple r.h.s. without reorthogonalizing a.
     !-----------------------------------------------------------------------
     ! description of parameters:
     ! ic     an input code which must be set to 1 or 2
     ! m      the number of equations (rows of q) to solve.
     ! n      the total number of columns of q to be used (<N2)
     ! N2   the number of columns of q, at least n+1.
     ! mm   the number of rows of q, at least N2+m.
     ! q      an mm-by-N2 array which on entry must contain the
     !        matrix a in its first m rows and n columns, and the vector
     !        b in its first m rows of column mm. on exit the residual
     !        of equation i is stored in q(i,N2), i=1 to m.
     ! sig    measurement error (standard deviation) for the rhs
     !        from the calling program (can be set to 1.)
     ! u      an mm-by-N2 matrix used in svd, replaced by "left" matrix u
     ! v      an N2-by-N2 matrix of n "right" eigenvectors of q (=u)
     ! w      an N2-diagonal vector(matrix) of n eigenvalues of q (u)
     ! cov    an output covariance matrix between eigenvectors of q (u)
     ! toler  an input tolerance, for acceptable matrix condition number
     ! p      an output array of dimension at least N2 containing
     !        the least-squares solution in positions 1 to n.
     ! jc     an output code which is set to the index of the
     !        1st dependent column, if such a column is detected.
     ! ssq    sum of squares of the residuals
     ! res    the largest residual in magnitude
     !-----------------------------------------------------------------------
     ! history:
     !       written by j. cherniawsky, august 1997
     !        last modified              august 1998
     !-----------------------------------------------------------------------
     IMPLICIT NONE
     ! PARAMETERS
     integer, parameter        :: nwt=302      ! make nwt > expected value of N2
     ! I/O VARIABLES
     integer, intent(IN)               :: ic, m, n, N2, mm
     real, intent(IN)                  :: toler
     real, intent(INOUT)               :: q(mm,N2), ssq, res
     integer, intent(INOUT)            :: jc
     double precision, intent(INOUT)   :: sig(mm)
     double precision, intent(OUT)     :: u(mm,N2),v(N2,N2),cov(N2,N2),      &
          w(N2),b(mm),p(N2)
     ! LOCAL VARIABLES
     double precision          :: wti(nwt)
     integer                   :: i, j, k
     real                      :: wmax, thresh
     double precision          :: eps, sum, resi
     jc=0
     do i=1,mm
       b(i)=q(i,n2)
     enddo
     ! no need to solve if only rhs has changed
     IF (ic.eq.2) go to 10
     ! define a "design matrix" u(=a) and set-up working arrays
     do j=1,n2
       do i=1,mm
         u(i,j)=q(i,j)
       enddo
     enddo
     ! compute svd decomposition of u(=a), with a being replaced by its upper
     ! matrix u, viz a=u*w*transpose(v), and vector w is output of a diagonal
     ! matrix of singular values w(i), i=1,n.
     call dsvdcmp(u,m,n,mm,n2,w,v)
     ! check for small singular values
     wmax=0.
     do j=1,n
       IF (w(j).gt.wmax) wmax=w(j)
     enddo
     thresh=toler*wmax
     do j=1,n
       IF (w(j).lt.thresh) then
         w(j)=0.d0
         IF (jc.lt.1) jc=j
       endif
     enddo
 10  eps=1.d-10
     ! compute summation weights (wti, used below)
     do j=1,n
       wti(j)=0.d0
       IF (w(j).gt.eps) then
         !         wti(j)=sig(j)*sig(j)/(w(j)*w(j))
         wti(j)=1.d0/(w(j)*w(j))
       endif
     enddo
     ! use back-substitution to compute the solution p(i), i=1,n
     call dsvbksb(u,w,v,m,n,mm,n2,b,p)
     ! compute chisq (=ssq) and the largest residual (res)
     ssq=0.
     res=0.
     do i=1,m
       sum=0.d0
       do j=1,n
         sum=sum+p(j)*q(i,j)
       enddo
       resi=abs(b(i)-sum)
       !      TIDE_MF addition
       q(i,n2)=b(i)-sum
       res=max(res,resi)
       ssq=ssq+resi**2
     enddo
     ! compute variances, covariances, these may need to be given dimension
     ! of b(i), e.g., using sig(i), but this is better done after return to main
     do i=1,n
       do j=1,i
         sum=0.d0
         do k=1,n
           sum=sum+v(i,k)*v(j,k)*wti(k)
         enddo
         cov(i,j)=sum
         cov(j,i)=sum
       enddo
     enddo
     return
References dsvbksb(), and dsvdcmp().
Referenced by flex_tidana_webpage().
tide_find_indices_analysis()
subroutine w3tidemd::tide_find_indices_analysis (character(len=100), dimension(70), intent(in) LIST)
Definition at line 343 of file w3tidemd.F90.
     !/                  +-----------------------------------+
     !/                  |           F. Ardhuin              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         21-Apr-2020 |
     !/                  +-----------------------------------+
     !/
     !/    29-Jun-2013 : Creation                            ( version 4.11 )
     !/    21-Apr-2020 : Add 5 additional tidal const.       ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Finds indices of tidal constituents to be used for analysis
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       LIST         Char  I  Array of tidal constituents names to be used
     !     ----------------------------------------------------------------
     !
     !
     !  4. Subroutines used :
     !
     !     None
     !
     !  5. Called by :
     !
     !     ww3_prtide
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S  Enable subroutine tracing.
     !       !/T  Enable test output.
     !
     ! 10. Source code :
     !
     USE w3odatmd, ONLY: iaproc, naproc, naperr, napout
     USE w3odatmd, ONLY: ndse, ndso
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/ ------------------------------------------------------------------- /
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     CHARACTER(LEN=100), INTENT(IN) :: LIST(70)
     !
     INTEGER TIDE_MF_ALL
     CHARACTER(LEN=5)             :: TIDECON_NAME_ALL(65)      ! array of names of tidal constituents
     REAL                         :: TIDE_FREQC_ALL(65)        ! array of freq. of tidal constituents
     INTEGER                      :: INDS(65), J, FOUND, NTIDES
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   =   0
 #endif
     !
 #ifdef W3_S
     CALL strace (ient, 'TIDE_FIND_INDICES_PREDICTION')
 #endif
     !
     tidecon_name_all(:)=(/ &
          'Z0   ', 'SSA  ', 'MSM  ', 'MM   ', 'MSF  ', 'MF   ', 'ALP1 ', '2Q1  ', 'SIG1 ', 'Q1   ',  &
          'RHO1 ', 'O1   ', 'TAU1 ', 'BET1 ', 'NO1  ', 'CHI1 ', 'P1   ', 'K1   ', 'PHI1 ', 'THE1 ',  &
          'J1   ', 'SO1  ', 'OO1  ', 'UPS1 ', 'OQ2  ', 'EPS2 ', '2N2  ', 'MU2  ', 'N2   ', 'NU2  ',  &
          'M2   ', 'MKS2 ', 'LDA2 ', 'L2   ', 'S2   ', 'K2   ', 'MSN2 ', 'ETA2 ', 'MO3  ', 'M3   ',  &
          'SO3  ', 'MK3  ', 'SK3  ', 'MN4  ', 'M4   ', 'SN4  ', 'MS4  ', 'MK4  ', 'S4   ', 'SK4  ',  &
          '2MK5 ', '2SK5 ', '2MN6 ', 'M6   ', '2MS6 ', '2MK6 ', '2SM6 ', 'MSK6 ', '3MK7 ', 'M8   ',  &
          'N4   ', 'R2   ', 'S1   ', 'SA   ', 'T2   ' /)
     !
     tide_freqc_all(:)=(/0.0000000000, 0.0002281591, 0.0013097807, 0.0015121520, 0.0028219327, 0.0030500918, &
          0.0343965698, 0.0357063505, 0.0359087218, 0.0372185025, 0.0374208738, &
          0.0387306544, 0.0389588136, 0.0400404351, 0.0402685943, 0.0404709655, &
          0.0415525871, 0.0417807462, 0.0420089053, 0.0430905269, 0.0432928982, &
          0.0446026789, 0.0448308380, 0.0463429900, 0.0759749448, 0.0761773160, &
          0.0774870967, 0.0776894680, 0.0789992487, 0.0792016200, 0.0805114007, &
          0.0807395598, 0.0818211814, 0.0820235526, 0.0833333333, 0.0835614924, &
          0.0848454853, 0.0850736444, 0.1192420551, 0.1207671010, 0.1220639878, &
          0.1222921469, 0.1251140796, 0.1595106494, 0.1610228013, 0.1623325820, &
          0.1638447340, 0.1640728931, 0.1666666667, 0.1668948258, 0.2028035476, &
          0.2084474129, 0.2400220500, 0.2415342020, 0.2443561347, 0.2445842938, &
          0.2471780673, 0.2474062264, 0.2833149482, 0.3220456027, &
          0.157998497 , 0.083447407 , 0.041666667 , 0.000114080 , 0.083219259 /)
     inds(:) = 0
     !
     IF (trim(list(1)).EQ.'FAST') THEN
       tide_mf = 44
       inds(1:44)= (/ 1, 2, 3, 4, 5, 6, 12, 17, 18, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,  &
            37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,&
            55, 56, 57, 58, 59, 60 /)
       !
     ELSE IF (trim(list(1)).EQ.'VFAST') THEN
       tide_mf = 20
       inds(1:20)= (/ 1, 2, 3, 5, 6, 27, 28, 29, 30, 31, 35, 36, 37, 44, 45, 47, 49, 54, 55, 60 /)
       !
     ELSE
       tide_mf=0
       ntides=0
       !
       DO WHILE (len_trim(list(tide_mf+1)).NE.0)
         !
         tide_mf=tide_mf+1
         found = 0
         DO j=1,65
           IF (trim(tidecon_name_all(j)).EQ.trim(list(tide_mf))) THEN
             ntides=ntides+1
             inds(ntides)=j
             found = 1
             IF (iaproc.EQ.napout) WRITE(ndso,'(A,I4,2A,E12.2)')  &
                  'Tidal constituent in analysis:', j, ' ', &
                  trim(tidecon_name_all(j)),tide_freqc_all(j)
           END IF
         END DO
         IF (found.EQ.0 .AND. iaproc.EQ.napout) WRITE(ndso,'(A,I4,A,A)') &
              'Tidal constituent ',tide_mf,trim(list(tide_mf)),' not available.'
         !
       END DO
       !
       tide_mf=ntides
     END IF
     !
     ! Defines names and frequencies
     !
     IF (ALLOCATED(tide_freqc)) DEALLOCATE(tide_freqc)
     ALLOCATE(tide_freqc(tide_mf),tidecon_name(tide_mf))
     DO j=1,tide_mf
       tidecon_name(j) = tidecon_name_all(inds(j))
       tide_freqc(j) = tide_freqc_all(inds(j))
     END DO
     CALL tide_set_indices
     !
References w3odatmd::iaproc, w3odatmd::naperr, w3odatmd::napout, w3odatmd::naproc, w3odatmd::ndse, w3odatmd::ndso, w3servmd::strace(), tide_freqc, tide_mf, tide_set_indices(), and tidecon_name.
tide_find_indices_prediction()
subroutine w3tidemd::tide_find_indices_prediction (character(len=100), dimension(70), intent(in) LIST, integer, dimension(70), intent(out) INDS, integer, intent(out) TIDE_PRMF)
Definition at line 244 of file w3tidemd.F90.
     !/                  +-----------------------------------+
     !/                  |           F. Ardhuin              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         28-Feb-2013 |
     !/                  +-----------------------------------+
     !/
     !/    29-Jun-2013 : Creation                            ( version 4.11 )
     !/
     !  1. Purpose :
     !
     !     Finds indices of tidal constituents to be used for prediction
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       LIST         Char  I  Array of tidal constituents names to be used
     !       INDS         I.A.  O  Array of indices
     !       TIDE_PRMF    I.A.  O  number of constituents to be used
     !     ----------------------------------------------------------------
     !
     !
     !  4. Subroutines used :
     !
     !     None
     !
     !  5. Called by :
     !
     !     ww3_prtide
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S  Enable subroutine tracing.
     !       !/T  Enable test output.
     !
     ! 10. Source code :
     !
     USE w3odatmd, ONLY: iaproc, naproc, naperr, napout
     USE w3odatmd, ONLY: ndse, ndso
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/ ------------------------------------------------------------------- /
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     CHARACTER(LEN=100), INTENT(IN) :: LIST(70)
     INTEGER, INTENT(OUT)    :: INDS(70), TIDE_PRMF
     INTEGER J, FOUND
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   =   0
 #endif
     !
 #ifdef W3_S
     CALL strace (ient, 'TIDE_FIND_INDICES_PREDICTION')
 #endif
     !
     tide_prmf=0
     IF (trim(list(1)).EQ.'VFAST' .OR. trim(list(1)).EQ.'FAST') THEN
       DO j=1,tide_mf
         inds(j)=j
       END DO
       tide_prmf = tide_mf
       RETURN
     END IF
     !
     DO WHILE (len_trim(list(tide_prmf+1)).NE.0)
       tide_prmf=tide_prmf+1
       found = 0
       DO j=1,tide_mf
         IF (trim(tidecon_name(j)).EQ.trim(list(tide_prmf))) THEN
           inds(tide_prmf)=j
           found=1
           IF (iaproc.EQ.napout) WRITE(ndso,'(A,A,E12.2)') 'Tidal constituent to be used in pre:', &
                trim(list(tide_prmf)),tide_freqc(j)
         END IF
       END DO
       IF (found.EQ.0 .AND. iaproc.EQ.napout) WRITE(ndso,'(3A)') 'Tidal constituent ',trim(list(tide_prmf)), &
            ' not available.'
     END DO
     !
References w3odatmd::iaproc, w3odatmd::naperr, w3odatmd::napout, w3odatmd::naproc, w3odatmd::ndse, w3odatmd::ndso, w3servmd::strace(), tide_freqc, tide_mf, and tidecon_name.
tide_predict()
subroutine w3tidemd::tide_predict (integer, intent(in) itrend, integer, intent(in) ndef, integer, intent(in) N, real(kind=8), dimension(n), intent(in) HOURS, real, dimension(n,ndef), intent(in) DATAIN, real, dimension(n,ndef), intent(out) PREDICTED, real, dimension(n,ndef), intent(out) RESID, real, intent(in) XLAT, real(kind=8), dimension(ndef), intent(out) SDEV, real(kind=8), dimension(ndef), intent(out) RMSR)
Definition at line 2512 of file w3tidemd.F90.
     !
     IMPLICIT NONE
     !
     INTEGER,       INTENT(IN)      :: itrend, NDEF, N
     REAL(KIND=8)  , intent(in)     :: hours(n)
     REAL,          INTENT(IN)      :: XLAT, DATAIN(N,NDEF)
     REAL(KIND=8),  intent(out)     :: sdev(ndef),rmsr(ndef)
     REAL,          INTENT(OUT)     :: PREDICTED(N,NDEF), RESID(N,NDEF)
     !
     INTEGER                        :: IDEF, I, K, K2
     INTEGER                        :: J, M
     REAL                           :: ARG, ADD, SUM1, SSQ
     REAL(KIND=8)                   :: vx, ux, fx
     m = 2*tide_mf
     DO idef=1,ndef
       sdev=0.d0
       DO i=1,n
         IF (itrend.eq.1) THEN
           sum1=tide_ampc(1,idef)+tide_phg(1,idef)*hours(i)/(365.*24.)
         ELSE
           sum1=tide_ampc(1,idef)
         END IF
         !
         DO j=2,tide_mf
           CALL vuf(tidecon_name(j),vx,ux,fx,i)
           arg=(vx+ux)*twpi-tide_phg(j,idef)*fac
           add=fx*tide_ampc(j,idef)*cos(arg)
           sum1=sum1+add
         END DO
         !
         IF (tide_nin.NE.0) THEN
           DO k=1,tide_nin
             DO k2=1,tide_ninf(k)
               CALL vuf(tide_konin(k,k2),vx,ux,fx,i)
               arg=(vx+ux)*twpi-tide_phgi(k,k2,idef)*fac
               add=fx*tide_ampci(k,k2,idef)*cos(arg)
               sum1=sum1+add
             END DO
           END DO
         END IF
         !
         predicted(i,idef)=sum1
         !
         resid(i,idef)=datain(i,idef)-sum1
         sdev(idef)=sdev(idef)+resid(i,idef)**2
       END DO
       !
       ssq=sdev(idef)
       rmsr(idef)=sqrt(ssq/(n-m))
       sdev(idef)=sqrt(ssq/n)
     ENDDO
     !
References fac, tide_ampc, tide_ampci, tide_konin, tide_mf, tide_nin, tide_ninf, tide_phg, tide_phgi, tidecon_name, twpi, and vuf().
tide_predict_only()
subroutine w3tidemd::tide_predict_only (integer, intent(in) itrend, integer, intent(in) ndef, integer, intent(in) N, real(kind=8), dimension(n), intent(in) TIDE_HOURS, real, dimension(n,ndef), intent(out) PREDICTED, real, intent(in) XLAT)
Definition at line 2570 of file w3tidemd.F90.
     !
     IMPLICIT NONE
     !
     INTEGER,       INTENT(IN)      :: itrend, NDEF, N
     REAL(KIND=8)  , intent(in)     :: tide_hours(n)
     REAL,          INTENT(IN)      :: XLAT
     REAL,          INTENT(OUT)     :: PREDICTED(N,NDEF)
     !
     INTEGER                        :: IDEF, I, K, K2
     INTEGER                        :: J
     REAL                           :: ARG, ADD, SUM1
     REAL(KIND=8)                   :: vx, ux, fx
     DO idef=1,ndef
       DO i=1,n
         IF (itrend.eq.1) THEN
           sum1=tide_ampc(1,idef)+tide_phg(1,idef)*tide_hours(i)/(365.*24.)
         ELSE
           sum1=tide_ampc(1,idef)
         END IF
         !
         DO j=2,tide_mf
           CALL vuf(tidecon_name(j),vx,ux,fx,i)
           arg=(vx+ux)*twpi-tide_phg(j,idef)*fac
           add=fx*tide_ampc(j,idef)*cos(arg)
           sum1=sum1+add
         END DO
         !
         IF (tide_nin.NE.0) THEN
           DO k=1,tide_nin
             DO k2=1,tide_ninf(k)
               CALL vuf(tide_konin(k,k2),vx,ux,fx,i)
               arg=(vx+ux)*twpi-tide_phgi(k,k2,idef)*fac
               add=fx*tide_ampci(k,k2,idef)*cos(arg)
               sum1=sum1+add
             END DO
           END DO
         END IF
         !
         predicted(i,idef)=sum1
         !
       END DO
       !
     ENDDO
     !
References fac, tide_ampc, tide_ampci, tide_hours, tide_konin, tide_mf, tide_nin, tide_ninf, tide_phg, tide_phgi, tidecon_name, twpi, and vuf().
tide_read_anapar()
subroutine w3tidemd::tide_read_anapar (integer, intent(in) KR1, integer, intent(in) LP, character*256, intent(in) filename, integer(kind=4), intent(out) KD1, integer(kind=4), intent(out) KD2, real, intent(out) XLON, real, intent(out) XLAT, integer, intent(out) NDEF, integer, intent(out) ITREND, character*4, intent(out) ITZ)
Definition at line 717 of file w3tidemd.F90.
     ! Parameters for reading KR1
     IMPLICIT NONE
     INTEGER,       INTENT(IN)     :: KR1, LP
     CHARACTER*256, INTENT(IN)     :: filename
     INTEGER(KIND=4), INTENT(OUT)  :: KD1, KD2
     INTEGER        , INTENT(OUT)  :: NDEF,ITREND
     REAL,            INTENT(OUT)  :: XLON, XLAT
     CHARACTER*4 ,    INTENT(OUT)  :: ITZ
     !
     INTEGER                   :: I, IY
     INTEGER       ID1,IM1,IY1,ID2,IM2,IY2,IC1,IC2
     INTEGER       JSTN, LATD,LATM,LOND,LONM, K, K2
     CHARACTER*4   NSTN(5)
     open(unit=kr1,file=filename,status='old',form='formatted')
     !
     !*
     !***********************************************************************
     !*  READ FROM DEVICE KR1 THE ANALYSIS TYPE AND TIDAL STATION DETAILS.
     !*
     !*  1)ONE RECORD FOR THE VARIABLES TIDE_MF
     !*  TIDE_MF   = THE NUMBER OF CONSTITUENTS, INCLUDING THE CONSTANT TERM Z0,
     !*         TO BE IN THE LEAST SQUARES FIT.
     !*
     !*  2)ONE RECORD FOR EACH OF THE TIDE_MF CONSTITUENTS TO BE INCLUDED IN THE
     !*  FIT.  EACH RECORD CONTAINS THE VARIABLES NAME AND TIDE_FREQC IN THE
     !*  FORMAT (A5,2X,F13.10).  NAME IS THE CONSTITUENT NAME, WHICH SHOULD
     !*  BE LEFT JUSTIFIED IN THE ALPHANUMERIC FIELD, WHILE TIDE_FREQC IS ITS
     !*  FREQUENCY MEASURED IN CYCLES PER HOUR.
     !*
     !*  3) ONE RECORD IN THE FORMAT (8I5) CONTAINING THE FOLLOWING
     !*  INFORMATION ON THE TIME PERIOD OF THE ANALYSIS.
     !*  ID1,IM1,IY1 - DAY,MONTH,YEAR OF THE BEGINNING OF THE ANALYSIS
     !*                PERIOD,
     !*  ID2,IM2,IY2 - DAY,MONTH,YEAR OF THE END OF THE ANALYSIS PERIOD.
     !*  IC1,IC2     - CENTURY OFR THE BEGINNING AND END OF THE ANALYSIS
     !*                PERIOD (ZERO VALUES ARE RESET TO 19)
     !*
     !*
     !*  4)ONE RECORD IN THE FORMAT (I5,5A4,1X,A4,4I5) CONTAINING THE
     !*  FOLLOWING TIDAL STATION  INFORMATION.
     !*  JSTN      = TIDAL STATION NUMBER,
     !*  (NSTN(I),I=1,5) = TIDAL STATION NAME,
     !              *  ITZ       = TIME ZONE IN WHICH THE OBSERVATIONS WERE RECORDED,
     !              *  LATD,LATM = STATION LATITUDE IN DEGREES AND MINUTES,
     !              *  LOND,LONM = STATION LONGITUDE IN DEGREES AND MINUTES.
     !              *
     !              *  5)ONE SET RECORDS FOR EACH POSSIBLE INFERENCE. THE FIRST RECORD HAS THE
     !              *      CONSITUENT NAME, ITS FREQUENCY, AND THE NUMBER OF CONSTITUENTS TO BE
     !              *      INFERRED (4X,A5,E16.10,i5), WHILE THERE IS ONE RECORD FOR EACH OF THE
     !              *      CONSTITUENTS TO BE INFERRED WITH THE NAME, FREQUENCY, AMPLITUDE RATIO
     !              *      (INFERRED TO REFERENCE) AND PHASE DIFFERENCE (GREENWICH PHASE LAG OF
     !              *      THE INFERRED CONSTITUENT SUBTRACTED FROM THE GREENWICH PHASE LAG OF THE
     !              *    (ANALYSED CONSTITUENT IN THE FORMAT(4X,A5,E16.10,2F10.3)
     !              *
     !              *  FOR KR1 INPUT, ALL CONSTITUENT NAMES SHOULD BE LEFT JUSTIFIED IN
     !              *  THE ALPHANUMERIC FIELD, FREQUENCIES ARE MEASURED IN CYCLES/HOUR, AND
     !              *  ALL CONSTITUENTS MUST BE INCLUDED IN THE LIST IN READ FROM FNAM8.
     !
     !                    write(6,*) ' reading from unit kr1'
     READ(kr1,*) tide_mf,ndef,itrend
     ALLOCATE(tide_freqc(tide_mf),tidecon_name(tide_mf))
     !      ndef=1 if only 1D field to be analysed (eg., elevations)
     !      ndef=2 if 2D field: velocity components, EW followed by NS   : this is now de-activated
 #ifdef W3_T
     WRITE(6,*)  ' number of constituents & degrees of freedom=',tide_mf,ndef
 #endif
     IF (itrend.eq.1) then
 #ifdef W3_T
       WRITE(6,*) ' a linear trend is included in the analysis'
 #endif
     else
 #ifdef W3_T
       WRITE(6,*) ' no linear trend is included'
 #endif
     END IF
     !      TIDE_MF= number of consituents, excluding linear trend. The constant
     !      term, Z0 should be first in the list.
     !      itrend= 1 if include linear trend
     !      itrend= otherwise, no trend
     !      number of unknowns, M, depends on whether we have a linear trend
 10  FORMAT(2i5,f5.2)
     READ(kr1,11) (tidecon_name(i),tide_freqc(i),i=1,tide_mf)
 #ifdef W3_T
     WRITE(6,*)    (tidecon_name(i),tide_freqc(i),i=1,tide_mf)
 #endif
 11  FORMAT(4x,a5,f16.10)
     READ(kr1,7) id1,im1,iy1,id2,im2,iy2,ic1,ic2
 #ifdef W3_T
     WRITE(6,*)   id1,im1,iy1,id2,im2,iy2,ic1,ic2
 #endif
     IF (ic1.EQ.0) ic1=19
     IF (ic2.EQ.0) ic2=19
 7   FORMAT(16i5)
     READ(kr1,9) jstn,nstn(1:5),itz,latd,latm,lond,lonm
 9   FORMAT(i5,5a4,1x,a4,4i5)
     iy=ic1*100+iy1
     kd1=juldayt(id1,im1,iy)
     iy=ic2*100+iy2
     kd2=juldayt(id2,im2,iy)
     !
     !      read in inference information now as it will be used in the lsq matrix
     !
     DO k=1,10
       READ(kr1,'(4X,A5,E17.10,i5)')tide_konan(k),tide_sigan(k),tide_ninf(k)
       !      write(6,1010)TIDE_KONAN(K),TIDE_SIGAN(K),TIDE_NINF(k)
       IF (tide_konan(k).EQ.kblank) EXIT
       do k2=1,tide_ninf(k)
         read(kr1,'(4X,A5,E17.10,2F10.3)') tide_konin(k,k2),tide_sigin(k,k2),tide_r(k,k2),tide_zeta(k,k2)
       END DO
     END DO
     tide_nin=k-1
     CLOSE(kr1)
     xlat=latd+latm/60.
     xlon=lond+lonm/60.
     RETURN
References file(), juldayt(), kblank, tide_freqc, tide_konan, tide_konin, tide_mf, tide_nin, tide_ninf, tide_r, tide_sigan, tide_sigin, tide_zeta, and tidecon_name.
tide_read_settings()
subroutine w3tidemd::tide_read_settings (character*256, intent(in) filename, character*256, intent(out) fnam6, character*256, intent(out) fnam7, character*256, intent(out) fnam8, character*256, intent(out) fnam9, character*256, intent(out) fnam11)
Definition at line 672 of file w3tidemd.F90.
     IMPLICIT NONE
     CHARACTER*256, INTENT(IN)     :: filename
     CHARACTER*256, INTENT(OUT)    :: fnam6,fnam7,fnam8,fnam9,fnam11
     INTEGER KIN
     ! Parameters for reading KR1
     !      FILE I/O
     !      KIN is the master input file.
     !      fnam6 is the file to which the output is sent. It is assigned the number
     !            lp.
     !      fnam7 is file containing the constituents to be included in the analysis,
     !            the analysis period, inference parameters, the flag controlling
     !            height or current analyses, and site information. It is assigned the
     !            number kr1.
     !      fnam8 is the file containing all the astronomical argument information
     !            (it should not have to be changed)
     !      fnam11 is a file to which information on the SVD matrix fit is output when
     !
     !      Original, fitted, and residual time series are output to file 25 while
     !      the same are also output to file 26 in a format that could be input to
     !      Excel for plotting.
     !
     kin=40   ! Input file assigned to unit 4
     !      OPEN(UNIT=KIN,FILE='tuk75_tidana.inp',STATUS='OLD')
     !      OPEN(UNIT=KIN,FILE='victoria_2008_test.inp',STATUS='OLD')
     OPEN(unit=kin,file=filename,status='OLD')
     !      OPEN(UNIT=KIN,FILE='kiw05_mar2008.inp',STATUS='OLD')
     !      OPEN(UNIT=KIN,FILE='tcs05_sep07-mar08.inp',STATUS='OLD')
     read(kin,'(a)') fnam6
     read(kin,'(a)') fnam7
     read(kin,'(a)') fnam8
     read(kin,'(a)') fnam9
     read(kin,'(a)') fnam11
     !      open(unit=11,file=fnam11,status='unknown',form='formatted')
     !      unit 25 stores the residual time series
     !read(KIN,'(a)') fname
     !open(unit=25,file=fname,status='unknown',form='formatted')
     !read(KIN,'(a)') fname
     !open(unit=26,file=fname,status='unknown',form='formatted')
References file().
tide_read_timeseries()
subroutine w3tidemd::tide_read_timeseries (integer, intent(in) KR2, character*256, intent(in) filename, integer(kind=4), intent(in) KD1, integer(kind=4), intent(in) KD2, integer(kind=4), intent(out) TIDE_NTI, integer, intent(in) NDEF)
Definition at line 844 of file w3tidemd.F90.
     !
     IMPLICIT NONE
     !
     INTEGER,       INTENT(IN)     :: KR2, NDEF
     CHARACTER*256, INTENT(IN)     :: filename
     INTEGER(KIND=4), INTENT(IN)   :: KD1,KD2
     INTEGER(KIND=4), INTENT(OUT)  :: TIDE_NTI
     !
     INTEGER                       :: I, idd,imm,icc,iyy,ihh,imin,isec,iy
     REAL, ALLOCATABLE             :: TIDE_DATATMP(:,:)
     INTEGER(KIND=4), ALLOCATABLE  :: TIDE_DAYSTMP(:), TIDE_SECSTMP(:)
     INTEGER(KIND=4)               :: KDD
     INTEGER                       :: ICODE
     REAL                          :: htt(NDEF)
     !
     ! Initialize Variables
     !
     ALLOCATE( tide_datatmp(nr,ndef), tide_daystmp(nr), tide_secstmp(nr) )
     ! Reads in data between dates kd1 and kd2 in file kr2
     !
     OPEN(unit=kr2,file=filename,status='old',form='formatted')
     icode = 0
     kdd = kd1
     i=0
     DO WHILE(icode.EQ.0.AND.kdd.LE.kd2)
       !
       ! reads with the original Foreman's format
       !
       READ(kr2,145,iostat=icode) idd,imm,icc,iyy,ihh,imin,htt(1:ndef)
 145   format(6i2,4f10.4)
       isec=0
       iy=icc*100+iyy
       kdd=juldayt(idd,imm,iy)
       IF (kdd.lt.kd1) then
         WRITE(*,*) icc,iyy,imm,idd,ihh,imin
         WRITE(*,*)'kd, kd1, kd2 =',kdd,kd1,kd2
         write(*,*) ' observation before analysis period'
       ELSE
         !
         !  Fills in data array
         !
         IF (icode.EQ.0.AND.kdd.LE.kd2) THEN
           i=i+1
           tide_datatmp(i,:)=htt(:)
           tide_daystmp(i)=kdd
           tide_secstmp(i)=ihh*3600+imin*60+isec
         END IF
       END IF
     END DO
     tide_nti=i
     ALLOCATE( tide_data(tide_nti,ndef) )
     ALLOCATE( tide_days(tide_nti), tide_secs(tide_nti), tide_hours(tide_nti) )
     tide_data(1:tide_nti,1:ndef)=tide_datatmp(1:tide_nti,1:ndef)
     tide_days(1:tide_nti)=tide_daystmp(1:tide_nti)
     tide_secs(1:tide_nti)=tide_secstmp(1:tide_nti)
     tide_hours(:)=24.d0*dfloat(tide_days(:))+dfloat(tide_secs(:))/3600.d0
     CLOSE(kr2)
     RETURN
References file(), juldayt(), nr, tide_data, tide_days, tide_hours, and tide_secs.
tide_set_indices()
subroutine w3tidemd::tide_set_indices
Definition at line 495 of file w3tidemd.F90.
     !
     IMPLICIT NONE
     !
     INTEGER J, K, K1, L, J1, JL, L2, KM1, JBASE
     !
     DO l=1,tide_mf
       DO k=1,ntotal_con
         IF (tidecon_allnames(k).EQ.tidecon_name(l)) tide_index2(l)=k
       END DO
     END DO
     !
     tide_indexj(:)=0
     tide_indexjk(:)=0
     jbase=0
     k1=ntidal_con+1
     !
     DO k=k1,ntotal_con
       j1=jbase+1
       tide_indexj(k)=j1
       jl=jbase+nj(k)
       DO j=j1,jl
         km1=k-1
         l2=0
         DO l2=1,km1
           IF (tidecon_allnames(l2).EQ.konco_con(j)) THEN
             tide_indexjk(j)=l2
           END IF
         END DO ! L2
       END DO   ! J
       jbase=jl
     END DO     ! K
     !
References konco_con, ntidal_con, ntotal_con, tide_index2, tide_indexj, tide_indexjk, tide_mf, tidecon_allnames, and tidecon_name.
Referenced by tide_find_indices_analysis().
tide_write_results()
subroutine w3tidemd::tide_write_results (integer, intent(in) LP, character*256, intent(in) filename, integer, intent(in) ndef, integer(kind=4), intent(in) KD1, integer(kind=4), intent(in) KD2, character*4, intent(in) ITZ, real, intent(in) xlat, real, intent(in) xlon, real, dimension(ndef), intent(in) RES, real, dimension(ndef), intent(in) SSQ, real(kind=8), dimension(ndef), intent(in) RMSR0, real(kind=8), dimension(ndef), intent(in) SDEV0, real(kind=8), dimension(ndef), intent(in) SDEV, real(kind=8), dimension(ndef), intent(in) RMSR, real(kind=8), dimension(ndef), intent(in) RESMAX, integer, dimension(ndef), intent(in) IMAX, real(kind=8), dimension(ndef), intent(in) RMSRP)
Definition at line 146 of file w3tidemd.F90.
     IMPLICIT NONE
     !
     CHARACTER*256, INTENT(IN)     :: filename
     INTEGER,       INTENT(IN)     :: LP, NDEF, IMAX(NDEF)
     INTEGER(KIND=4),INTENT(IN)    :: KD1,KD2
     CHARACTER*4  , INTENT(IN)     :: ITZ
     REAL(KIND=8),  intent(in)     :: rmsr0(ndef), &
          sdev0(ndef), sdev(ndef), rmsr(ndef), resmax(ndef), rmsrp(ndef)
     REAL         , INTENT(IN)     :: RES(NDEF), SSQ(NDEF), XLAT,XLON
     !
     INTEGER                       :: IDEF, I, K, K2, L, I1, INFTOT
     INTEGER                       :: ID1,IM1,IY1,ID2,IM2,IY2
     open(unit=lp,file=filename,status='unknown',form='formatted')
     CALL caldatt(kd1,id1,im1,iy1)
     CALL caldatt(kd2,id2,im2,iy2)
     WRITE(lp,15) id1,im1,iy1,id2,im2,iy2,itz
 15  FORMAT(/'THE ANALYSIS PERIOD IS FROM',i3,'/',i2,'/',i4,     &
          ' TO ',i2,'/',i2,'/',i4,'  IN THE TIME ZONE ',a4)
     WRITE(lp,*)'USING SVD TO SOLVE THE OVERDETERMINED SYSTEM'
     !      write(lp,150)ID1,IM1,IC1,IY1,ID2,IM2,IC2,IY2
 150 format(2i3,2i2,5x,2i3,2i2)
     WRITE(lp,255)tide_nti
 255 FORMAT('NUMBER OF POINTS IN THE ANALYSIS =',i6)
     write(lp,*) ' nin=',tide_nin
     DO idef=1,ndef
       WRITE(lp,52) res(idef),ssq(idef)
 52    FORMAT('LARGEST RESIDUAL MAGNITUDE & RESIDUAL SUM OF SQUARES:'     &
            ,2e12.5)
       WRITE(lp,66) sdev0(idef),rmsr0(idef)
 66    FORMAT(     &
            'ST. DEV. OF RIGHT HAND SIDES OF ORIGINAL OVERDETERMINED SYSTEM:' &
            ,e12.5/ &
            '                       AND THE ROOT MEAN SQUARE RESIDUAL ERROR:' &
            ,e12.5)
       write(lp,*) ' rms residual: brute force =',rmsr(idef)
       write(lp,*) ' max residual: ',resmax(idef),imax(idef)
       WRITE(lp,41)
 41    FORMAT('HARMONIC ANALYSIS RESULTS: AMPLITUDES, PHASE LAGS, C, S,      &
            & amp SD estimates, t-test value')
       !      write out results for constant term & linear trend
       DO i=1,tide_mf
         WRITE(lp,43) tidecon_name(i),tide_freqc(i),tide_ampc(i,idef),tide_phg(i,idef),     &
              tide_sig1(i,idef),tide_sig2(i,idef),tide_sig3(i,idef),tide_ttest(i,idef)
       END DO
 43    FORMAT(5x,a5,4x,f12.9,2x,f10.5,2x,f10.3,5x,4f8.3)
       !
       !*  INFERENCE results are given now
       !
       IF (tide_nin.GE.0) THEN
         write(lp,*) ' INFERENCE RESULTS'
         l=0
         do k=1,tide_nin
           do i=2,tide_mf
             IF (tidecon_name(i).eq.tide_konan(k)) EXIT
           END DO
           i1=i
           do k2=1,tide_ninf(k)
             l=l+1
             write(lp,79) tide_konin(k,k2),tide_sigin(k,k2),tide_ampci(k,k2,idef), &
                  tide_phgi(k,k2,idef)
 79          format(5x,a5,4x,f12.9,15x,f10.4,5x,f10.4)
           END DO
         END DO
         inftot=l
       END IF
       WRITE(lp,70)tide_nti,tide_mf*2,'    ',xlat,xlon,sngl(sdev0),sngl(sdev)
 70    format('N,m,LAT,LON,SDEV0,SDEV:  ',2i10,a4,f9.4,f10.4,2f10.2)
       !
       IF (tide_nin.GT.0) THEN
         WRITE(lp,71) rmsrp(idef)
 71      FORMAT('ROOT MEAN SQUARE RESIDUAL ERROR AFTER INFERENCE IS',     &
              e15.6, //)
       ELSE
         WRITE(lp,72) rmsrp(idef)
 72      FORMAT('RECALCULATED ROOT MEAN SQUARE RESIDUAL ERROR IS   ',     &
              e15.6, //)
       ENDIF
     END DO
References caldatt(), file(), tide_ampc, tide_ampci, tide_freqc, tide_konan, tide_konin, tide_mf, tide_nin, tide_ninf, tide_nti, tide_phg, tide_phgi, tide_sig1, tide_sig2, tide_sig3, tide_sigin, tide_ttest, and tidecon_name.
vuf()
subroutine w3tidemd::vuf (character*5, intent(in) KONX, real(kind=8), intent(out) Vx, real(kind=8), intent(out) ux, real(kind=8), intent(out) FX, integer, intent(in) ITIME)
Definition at line 1705 of file w3tidemd.F90.
     !
     !
     !* GIVEN CONSTITUENT KONX , THE NODAL CORRECTIONS V+U AND F ARE RETURNED
     ! That subroutine can now be replaced by look-up table to get K from J
     !
     !
     IMPLICIT NONE
     !
     character*5, INTENT(IN)      :: KONX
     REAL(KIND=8), intent(out)    :: vx,ux,fx
     INTEGER,      INTENT(IN)     :: ITIME
     INTEGER          :: K
     DO  k=1,ntotal_con
       IF (tidecon_allnames(k).eq.konx) go to 40
     END DO
     WRITE(ndset,30) konx
 30  FORMAT('ERROR IN VUF: STOP.',a5)
     stop
 40  vx=v_arg(k,itime)
     ux=u_arg(k,itime)
     fx=f_arg(k,itime)
     RETURN
     !
     !***********************************************************************
     !*  THE ASTRONOMICAL ARGUMENTS AND THEIR RATES OF CHANGE,
     !*  S0,H0,P0,ENP0,PP0,DS,DH,DP,DNP,DPP,  ARE READ FROM TWO RECORDS IN
     !*  THE FORMAT(5F13.10):
     !*     S0  = MEAN LONGITUDE OF THE MOON (CYCLES) AT 000 ET 1/1/1976.
     !*     H0  = MEAN LONGITUDE OF THE SUN.
     !*     P0  = MEAN LONGITUDE OF THE LUNAR PERIGEE.
     !*     ENP0= NEGATIVE OF THE MEAN LONGITUDE OF THE ASCENDING NODE.
     !*     PP0 = MEAN LONGITUDE OF THE SOLAR PERIGEE (PERIHELION).
     !*     DS,DH,DP,DNP,DPP ARE THEIR RESPECTIVE RATES OF CHANGE OVER A 365
     !*     DAY PERIOD AS OF 000 ET 1/1/1976.
     !
References f_arg, ndset, ntotal_con, tidecon_allnames, u_arg, and v_arg.
Referenced by flex_tidana_webpage(), tide_predict(), and tide_predict_only().
vuf_set_parameters()
subroutine w3tidemd::vuf_set_parameters
Definition at line 1445 of file w3tidemd.F90.
     !
     !***********************************************************************
     !*  HERE THE MAIN CONSTITUENTS AND THEIR DOODSON NUMBERS ARE SET
     !*  FORMAT (6X,A5,1X,6I3,F5.2,I4). THE VALUES ARE RESPECTIVELY
     !*     TIDECON_ALLNAMES   = CONSTITUENT NAME
     !*  II,JJ,KK,LL,MM,NN = THE SIX DOODSON NUMBERS
     !*     SEMI   = PHASE CORRECTION
     !*     NJ     = THE NUMBER OF SATELLITES FOR THIS CONSTITUENT.
     !*  THE END OF ALL MAIN CONSTITUENTS IS DENOTED BY A BLANK CARD.
     !
     IMPLICIT NONE
     INTEGER          :: JLM
     ntidal_con = 45
     ntotal_con = 45+101
     nkonco = 251
     jlm = 170
     ALLOCATE(tide_indexj(ntotal_con),tide_indexjk(nkonco))
     !
     ALLOCATE(tidecon_allnames(ntotal_con))
     ALLOCATE(ii(ntidal_con),jj(ntidal_con),kk(ntidal_con),ll(ntidal_con),mm(ntidal_con), &
          nn(ntidal_con),semi(ntidal_con), nj(ntotal_con))
     ALLOCATE(konco_con(nkonco),coef_con(nkonco))
     tidecon_allnames(:)=(/ &
          'Z0   ','SA   ','SSA  ','MSM  ','MM   ','MSF  ','MF   ','ALP1 ','2Q1  ','SIG1 ', &
          'Q1   ','RHO1 ','O1   ','TAU1 ','BET1 ','NO1  ','CHI1 ','PI1  ','P1   ','S1   ', &
          'K1   ','PSI1 ','PHI1 ','THE1 ','J1   ','OO1  ','UPS1 ','OQ2  ','EPS2 ','2N2  ', &
          'MU2  ','N2   ','NU2  ','GAM2 ','H1   ','M2   ','H2   ','LDA2 ','L2   ','T2   ', &
          'S2   ','R2   ','K2   ','ETA2 ','M3   ','2PO1 ','SO1  ','ST36 ','2NS2 ','ST37 ', &
          'ST1  ','ST2  ','ST3  ','O2   ','ST4  ','SNK2 ','OP2  ','MKS2 ','ST5  ','ST6  ', &
          '2SK2 ','MSN2 ','ST7  ','2SM2 ','ST38 ','SKM2 ','2SN2 ','NO3  ','MO3  ','NK3  ', &
          'SO3  ','MK3  ','SP3  ','SK3  ','ST8  ','N4   ','3MS4 ','ST39 ','MN4  ','ST40 ', &
          'ST9  ','M4   ','ST10 ','SN4  ','KN4  ','MS4  ','MK4  ','SL4  ','S4   ','SK4  ', &
          'MNO5 ','2MO5 ','3MP5 ','MNK5 ','2MP5 ','2MK5 ','MSK5 ','3KM5 ','2SK5 ','ST11 ', &
          '2NM6 ','ST12 ','ST41 ','2MN6 ','ST13 ','M6   ','MSN6 ','MKN6 ','2MS6 ','2MK6 ', &
          'NSK6 ','2SM6 ','MSK6 ','ST42 ','S6   ','ST14 ','ST15 ','M7   ','ST16 ','3MK7 ', &
          'ST17 ','ST18 ','3MN8 ','ST19 ','M8   ','ST20 ','ST21 ','3MS8 ','3MK8 ','ST22 ', &
          'ST23 ','ST24 ','ST25 ','ST26 ','4MK9 ','ST27 ','ST28 ','M10  ','ST29 ','ST30 ', &
          'ST31 ','ST32 ','ST33 ','M12  ','ST34 ','ST35 '/)
     ii(:)=(/ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1, &
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1, &
          1,  1,  1,  1,  1,  1,  1,  2,  2,  2, &
          2,  2,  2,  2,  2,  2,  2,  2,  2,  2, &
          2,  2,  2,  2,  3 /)
     jj(:)=(/ 0,  0,  0,  1,  1,  2,  2, -4, -3, -3, &
          -2, -2, -1, -1,  0,  0,  0,  1,  1,  1, &
          1,  1,  1,  2,  2,  3,  4, -3, -3, -2, &
          -2, -1, -1,  0,  0,  0,  0,  1,  1,  2, &
          2,  2,  2,  3,  0 /)
     kk(:)=(/ 0,  1,  2, -2,  0, -2,  0,  2,  0,  2, &
          0,  2,  0,  2, -2,  0,  2, -3, -2, -1, &
          0,  1,  2, -2,  0,  0,  0,  0,  2,  0, &
          2,  0,  2, -2, -1,  0,  1, -2,  0, -3, &
          -2, -1,  0,  0,  0 /)
     ll(:)=(/ 0,  0,  0,  1, -1,  0,  0,  1,  2,  0, &
          1, -1,  0,  0,  1,  1, -1,  0,  0,  0, &
          0,  0,  0,  1, -1,  0, -1,  3,  1,  2, &
          0,  1, -1,  2,  0,  0,  0,  1, -1,  0, &
          0,  0,  0, -1,  0 /)
     mm(:)=(/ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0 /)
     nn(:)=(/ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  1,  0,  1, &
          0, -1,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  1,  0, -1,  0,  0,  1, &
          0, -1,  0,  0,  0 /)
     semi(:)=(/ 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,-0.25,-0.25,-0.25, &
          -0.25,-0.25,-0.25,-0.75,-0.75,-0.75,-0.75,-0.25,-0.25,-0.75, &
          -0.75,-0.75,-0.75,-0.75,-0.75,-0.75,-0.75, 0.00, 0.00, 0.00, &
          0.00, 0.00, 0.00,-0.50,-0.50, 0.00, 0.00,-0.50,-0.50, 0.00, &
          0.00,-0.50, 0.00, 0.00,-0.50 /)
     nj(:)=(/    1,   1,   1,   1,   1,   1,   1,   2,   5,   4, &
          10,   5,   8,   5,   1,   9,   2,   1,   6,   2, &
          10,   1,   5,   4,  10,   8,   5,   2,   3,   4, &
          3,   4,   4,   3,   2,   9,   1,   1,   5,   1, &
          3,   2,   5,   7,   1,   2,   2,   3,   2,   2, &
          3,   4,   3,   1,   3,   3,   2,   3,   3,   4, &
          2,   3,   4,   2,   3,   3,   2,   2,   2,   2, &
          2,   2,   2,   2,   3,   1,   2,   4,   2,   3, &
          4,   1,   3,   2,   2,   2,   2,   2,   1,   2, &
          3,   2,   2,   3,   2,   2,   3,   3,   2,   3, &
          2,   4,   3,   2,   4,   1,   3,   3,   2,   2, &
          3,   2,   3,   3,   1,   3,   3,   1,   3,   2, &
          4,   2,   2,   4,   1,   3,   3,   2,   2,   4, &
          2,   3,   3,   3,   2,   3,   2,   1,   3,   2, &
          4,   2,   3,   1,   2,   4/)
     ldel(1:jlm)=(/  0,  0,  0,  0,  0,  0,  0, -1,  0, -2, &
          -1, -1,  0,  0, -1,  0,  0,  2, -2, -2, &
          -1, -1, -1,  0, -1,  0,  1,  2,  0,  0, &
          1,  2,  2, -1,  0,  0,  1,  1,  1,  2, &
          2, -2, -1,  0,  0,  0,  0, -2, -2, -2, &
          -1, -1, -1,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  1,  2,  2,  0,  0, -2, -1, -1, &
          -1,  0,  0,  0,  0,  1,  1,  0, -2, -2, &
          0,  0,  0, -2, -1,  0,  0,  0,  0,  0, &
          1,  1,  1,  1,  2,  2,  2, -2, -2, -2, &
          -1, -1,  0,  0,  0, -2,  0,  0,  1,  1, &
          -1,  0, -1, -1,  0, -2, -1, -1,  0, -1, &
          -1,  0, -2, -1,  0,  0,  0,  1,  2,  2, &
          -2, -1,  0,  0,  1, -1, -1,  0,  0,  1, &
          1,  1,  2,  2,  0,  0,  0,  2,  2,  2, &
          2,  0,  0,  1,  2,  0,  0, -1, -1,  0, &
          0,  0,  0,  0,  0,  1,  1,  1,  2,  0/)
     mdel(1:jlm)=(/  0,  0,  0,  0,  0,  0,  0,  0, -1, -2, &
          -1,  0, -2, -1,  0, -2, -1,  0, -3, -2, &
          -2, -1,  0, -2,  0, -1,  0,  0, -2, -1, &
          0,  0,  1,  0, -2, -1, -1,  0,  1,  0, &
          1,  0,  0, -1,  1,  2, -1, -2, -1,  0, &
          -1,  0,  1, -1,  1,  2, -1,  1, -1, -2, &
          -1,  0,  0,  0,  1,  0,  1, -1, -1,  0, &
          1, -2, -1,  1,  2,  0,  1,  1,  0,  1, &
          0,  1,  2, -1,  0, -1,  1, -1,  1,  2, &
          -1,  0,  1,  2,  0,  1,  2, -1,  0,  1, &
          0,  1,  1,  2,  3,  0,  1,  2,  0,  1, &
          0, -1, -1,  0, -1, -2, -1,  0, -1, -1, &
          0, -1, -2,  0, -2, -1, -1,  0,  0,  1, &
          -2,  0, -1, -1,  0, -1,  0, -2, -1, -1, &
          0,  1,  0,  1, -1, -1, -1, -1,  0,  1, &
          2,  0, -1,  0,  0,  0,  1,  0,  1, -1, &
          1,  2, -1,  1,  2,  0,  1,  2,  0, -1 /)
     ndel(1:jlm)=(/ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  1,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  2,  0,  0,  0, -2,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          -2,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  1,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0, -1,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  0,  0,  2,  2,  0,  0,  0, &
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0 /)
     ph(1:jlm)=(/ 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.75, 0.00, 0.50, &
          0.75, 0.75, 0.50, 0.00, 0.75, 0.50, 0.00, 0.50, 0.50, 0.50, &
          0.75, 0.75, 0.75, 0.50, 0.00, 0.00, 0.75, 0.50, 0.50, 0.00, &
          0.75, 0.50, 0.00, 0.25, 0.50, 0.00, 0.25, 0.75, 0.25, 0.50, &
          0.50, 0.00, 0.25, 0.50, 0.50, 0.50, 0.00, 0.50, 0.00, 0.00, &
          0.75, 0.25, 0.75, 0.50, 0.00, 0.50, 0.50, 0.00, 0.50, 0.00, &
          0.50, 0.50, 0.75, 0.50, 0.50, 0.00, 0.50, 0.00, 0.75, 0.25, &
          0.75, 0.00, 0.50, 0.00, 0.50, 0.25, 0.25, 0.00, 0.00, 0.00, &
          0.00, 0.50, 0.50, 0.00, 0.25, 0.50, 0.00, 0.50, 0.00, 0.50, &
          0.75, 0.25, 0.25, 0.25, 0.50, 0.50, 0.50, 0.50, 0.00, 0.00, &
          0.25, 0.25, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.25, 0.25, &
          0.25, 0.50, 0.25, 0.25, 0.50, 0.50, 0.25, 0.25, 0.50, 0.25, &
          0.25, 0.50, 0.50, 0.00, 0.00, 0.50, 0.50, 0.75, 0.00, 0.50, &
          0.00, 0.25, 0.50, 0.50, 0.50, 0.75, 0.75, 0.00, 0.50, 0.25, &
          0.75, 0.75, 0.00, 0.00, 0.50, 0.50, 0.50, 0.00, 0.50, 0.50, &
          0.50, 0.00, 0.00, 0.75, 0.00, 0.50, 0.00, 0.75, 0.75, 0.50, &
          0.00, 0.00, 0.50, 0.00, 0.00, 0.75, 0.75, 0.75, 0.50, 0.50 /)
     ee(1:jlm)=(/ 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0360, 0.1906, 0.0063, &
          0.0241, 0.0607, 0.0063, 0.1885, 0.0095, 0.0061, 0.1884, 0.0087, 0.0007, 0.0039, &
          0.0010, 0.0115, 0.0292, 0.0057, 0.0008, 0.1884, 0.0018, 0.0028, 0.0058, 0.1882, &
          0.0131, 0.0576, 0.0175, 0.0003, 0.0058, 0.1885, 0.0004, 0.0029, 0.0004, 0.0064, &
          0.0010, 0.0446, 0.0426, 0.0284, 0.2170, 0.0142, 0.2266, 0.0057, 0.0665, 0.3596, &
          0.0331, 0.2227, 0.0290, 0.0290, 0.2004, 0.0054, 0.0282, 0.2187, 0.0078, 0.0008, &
          0.0112, 0.0004, 0.0004, 0.0015, 0.0003, 0.3534, 0.0264, 0.0002, 0.0001, 0.0007, &
          0.0001, 0.0001, 0.0198, 0.1356, 0.0029, 0.0002, 0.0001, 0.0190, 0.0344, 0.0106, &
          0.0132, 0.0384, 0.0185, 0.0300, 0.0141, 0.0317, 0.1993, 0.0294, 0.1980, 0.0047, &
          0.0027, 0.0816, 0.0331, 0.0027, 0.0152, 0.0098, 0.0057, 0.0037, 0.1496, 0.0296, &
          0.0240, 0.0099, 0.6398, 0.1342, 0.0086, 0.0611, 0.6399, 0.1318, 0.0289, 0.0257, &
          0.1042, 0.0386, 0.0075, 0.0402, 0.0373, 0.0061, 0.0117, 0.0678, 0.0374, 0.0018, &
          0.0104, 0.0375, 0.0039, 0.0008, 0.0005, 0.0373, 0.0373, 0.0042, 0.0042, 0.0036, &
          0.1429, 0.0293, 0.0330, 0.0224, 0.0447, 0.0001, 0.0004, 0.0005, 0.0373, 0.0001, &
          0.0009, 0.0002, 0.0006, 0.0002, 0.0217, 0.0448, 0.0366, 0.0047, 0.2505, 0.1102, &
          0.0156, 0.0000, 0.0022, 0.0001, 0.0001, 0.2535, 0.0141, 0.0024, 0.0004, 0.0128, &
          0.2980, 0.0324, 0.0187, 0.4355, 0.0467, 0.0747, 0.0482, 0.0093, 0.0078, 0.0564 /)
     ir(1:jlm)=(/ 0,  0,  0,  0,  0,  0,  0,  1,  0,  0, &
          1,  1,  0,  0,  1,  0,  0,  0,  0,  0, &
          1,  1,  1,  0,  0,  0,  1,  0,  0,  0, &
          1,  0,  0,  1,  0,  0,  1,  1,  1,  0, &
          0,  0,  1,  0,  0,  0,  0,  0,  0,  0, &
          1,  1,  1,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  1,  0,  0,  0,  0,  0,  1,  1, &
          1,  0,  0,  0,  0,  1,  1,  0,  0,  0, &
          0,  0,  0,  0,  1,  0,  0,  0,  0,  0, &
          1,  1,  1,  1,  0,  0,  0,  0,  0,  0, &
          1,  1,  0,  0,  0,  0,  0,  0,  1,  1, &
          2,  0,  2,  2,  0,  0,  2,  2,  0,  2, &
          2,  0,  0,  0,  0,  0,  0,  2,  0,  0, &
          0,  2,  0,  0,  0,  2,  2,  0,  0,  2, &
          2,  2,  0,  0,  0,  0,  0,  0,  0,  0, &
          0,  0,  0,  2,  0,  0,  0,  2,  2,  0, &
          0,  0,  0,  0,  0,  2,  2,  2,  0,  0 /)
     coef_con(:)=(/ 2.00,-1.00, 1.00,-1.00, 2.00, 1.00,-2.00, 2.00,-1.00, 3.00, &
          -2.00, 2.00, 1.00,-2.00, 1.00, 1.00, 1.00,-2.00, 2.00, 1.00, &
          -2.00, 2.00, 2.00, 1.00,-2.00, 1.00, 1.00,-1.00, 1.00, 1.00, &
          1.00, 1.00,-1.00, 1.00, 2.00,-2.00, 2.00, 1.00,-1.00,-1.00, &
          2.00,-1.00, 1.00, 1.00,-1.00, 2.00, 1.00,-1.00,-1.00, 2.00, &
          -1.00, 2.00, 1.00,-2.00, 1.00, 1.00,-1.00, 2.00,-1.00, 1.00, &
          1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, &
          1.00, 1.00, 1.00, 2.00, 1.00,-1.00, 2.00, 3.00,-1.00, 1.00, &
          1.00, 1.00,-1.00, 1.00, 1.00, 2.00, 1.00,-1.00, 1.00, 1.00, &
          1.00,-1.00, 2.00, 2.00, 1.00,-1.00, 1.00, 1.00, 1.00, 1.00, &
          1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 2.00, 1.00, 1.00, 1.00, &
          1.00, 1.00, 2.00, 1.00, 3.00,-1.00, 1.00, 1.00, 1.00, 2.00, &
          1.00, 2.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 2.00, &
          1.00, 3.00, 1.00,-1.00, 2.00, 1.00, 2.00, 1.00, 1.00,-1.00, &
          3.00, 1.00,-1.00, 2.00, 1.00, 2.00, 1.00, 1.00,-1.00, 3.00, &
          1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 2.00, 1.00, 2.00, 1.00, &
          1.00, 1.00, 1.00, 2.00, 1.00, 1.00, 1.00, 1.00, 2.00, 2.00, &
          -1.00, 3.00, 2.00, 1.00, 1.00, 2.00, 1.00, 1.00, 3.50, 2.00, &
          1.00, 1.00, 3.00, 1.00, 1.00, 1.00, 1.00, 1.00, 2.00, 2.00, &
          3.00, 1.00, 3.00, 1.00, 1.00,-1.00, 4.00, 2.00, 1.00, 1.00, &
          2.00, 1.00, 1.00, 3.00, 1.00, 3.00, 1.00, 1.00, 1.00, 1.00, &
          1.00, 2.00, 2.00, 2.00, 1.00, 1.00, 2.00, 2.00, 1.00, 3.00, &
          1.00, 1.00, 4.00, 1.00, 3.00, 1.00, 1.00, 4.00, 1.00, 5.00, &
          3.00, 1.00, 1.00, 4.00, 1.00, 2.00, 1.00, 1.00, 1.00, 3.00, &
          2.00, 4.00, 1.00, 1.00, 6.00, 5.00, 1.00, 3.00, 1.00, 1.00, &
          1.00 /)
     konco_con(:)=(/  &
          'P1   ','O1   ','S2   ','O1   ','M2   ','N2   ','S2   ','N2   ','S2   ','M2   ', &
          'S2   ','N2   ','K2   ','S2   ','M2   ','N2   ','K2   ','S2   ','M2   ','S2   ', &
          'K2   ','O1   ','K2   ','N2   ','S2   ','S2   ','N2   ','K2   ','O1   ','P1   ', &
          'M2   ','K2   ','S2   ','M2   ','K2   ','S2   ','S2   ','N2   ','M2   ','K2   ', &
          'S2   ','K2   ','M2   ','S2   ','N2   ','K2   ','M2   ','S2   ','N2   ','S2   ', &
          'M2   ','M2   ','S2   ','N2   ','S2   ','K2   ','M2   ','S2   ','N2   ','N2   ', &
          'O1   ','M2   ','O1   ','N2   ','K1   ','S2   ','O1   ','M2   ','K1   ','S2   ', &
          'P1   ','S2   ','K1   ','M2   ','N2   ','S2   ','N2   ','M2   ','S2   ','M2   ', &
          'S2   ','N2   ','K2   ','M2   ','N2   ','M2   ','S2   ','K2   ','M2   ','N2   ', &
          'K2   ','S2   ','M2   ','M2   ','K2   ','S2   ','S2   ','N2   ','K2   ','N2   ', &
          'M2   ','S2   ','M2   ','K2   ','S2   ','L2   ','S2   ','S2   ','K2   ','M2   ', &
          'N2   ','O1   ','M2   ','O1   ','M2   ','P1   ','M2   ','N2   ','K1   ','M2   ', &
          'P1   ','M2   ','K1   ','M2   ','S2   ','K1   ','K2   ','K1   ','M2   ','S2   ', &
          'K1   ','N2   ','K2   ','S2   ','N2   ','M2   ','N2   ','M2   ','K2   ','S2   ', &
          'M2   ','S2   ','K2   ','M2   ','N2   ','M2   ','N2   ','K2   ','S2   ','M2   ', &
          'M2   ','S2   ','N2   ','M2   ','K2   ','N2   ','M2   ','S2   ','M2   ','K2   ', &
          'N2   ','S2   ','K2   ','S2   ','M2   ','M2   ','S2   ','K2   ','M2   ','S2   ', &
          'K2   ','S2   ','M2   ','N2   ','O1   ','N2   ','M2   ','K1   ','M2   ','M2   ', &
          'S2   ','O1   ','M2   ','K1   ','M2   ','S2   ','K2   ','O1   ','M2   ','N2   ', &
          'M2   ','N2   ','M2   ','N2   ','K2   ','S2   ','M2   ','M2   ','S2   ','N2   ', &
          'M2   ','N2   ','K2   ','M2   ','S2   ','M2   ','K2   ','M2   ','S2   ','N2   ', &
          'K2   ','M2   ','S2   ','M2   ','S2   ','K2   ','M2   ','N2   ','K1   ','M2   ', &
          'N2   ','K1   ','M2   ','K1   ','M2   ','S2   ','K1   ','M2   ','N2   ','M2   ', &
          'M2   ','N2   ','S2   ','M2   ','S2   ','M2   ','N2   ','S2   ','K2   ','M2   ', &
          'S2   ','M2   ','S2   ','K1   ','M2   ','M2   ','S2   ','M2   ','N2   ','K2   ', &
          'S2   '/)
References coef_con, ee, ir, konco_con, ldel, mdel, ndel, nkonco, ntidal_con, ntotal_con, ph, semi, tide_indexj, tide_indexjk, and tidecon_allnames.
Variable Documentation
coef_con
real, dimension(:), allocatable w3tidemd::coef_con
Definition at line 100 of file w3tidemd.F90.
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
ee
real, dimension(180) w3tidemd::ee
Definition at line 102 of file w3tidemd.F90.
   REAL                          :: EE(180),PH(180)
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
f_arg
real, dimension(:,:), allocatable w3tidemd::f_arg
Definition at line 101 of file w3tidemd.F90.
Referenced by setvuf(), and vuf().
fac
double precision, parameter w3tidemd::fac =TWPI/360.
Definition at line 87 of file w3tidemd.F90.
   DOUBLE PRECISION, PARAMETER  :: FAC=twpi/360.
Referenced by flex_tidana_webpage(), tide_predict(), and tide_predict_only().
ir
integer, dimension(180) w3tidemd::ir
Definition at line 103 of file w3tidemd.F90.
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
kblank
character*5, parameter w3tidemd::kblank =' '
Definition at line 94 of file w3tidemd.F90.
   CHARACTER*5, PARAMETER       :: KBLANK='     '
Referenced by opnvuf(), and tide_read_anapar().
konco_con
character*5, dimension(:), allocatable w3tidemd::konco_con
Definition at line 98 of file w3tidemd.F90.
   CHARACTER*5,    ALLOCATABLE   :: KONCO_CON(:)
Referenced by opnvuf(), tide_set_indices(), and vuf_set_parameters().
ldel
integer, dimension(180) w3tidemd::ldel
Definition at line 103 of file w3tidemd.F90.
   INTEGER                       :: LDEL(180),MDEL(180),NDEL(180),IR(180)
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
mc
integer, parameter w3tidemd::mc =70
Definition at line 92 of file w3tidemd.F90.
   INTEGER, PARAMETER          :: MC=70,nr=106000,nmaxp1=mc*2,nmaxpm=nr*2+nmaxp1
mc2
integer, parameter w3tidemd::mc2 =MC*2
Definition at line 93 of file w3tidemd.F90.
   INTEGER, PARAMETER          :: MC2=mc*2
Referenced by opnvuf().
mdel
integer, dimension(180) w3tidemd::mdel
Definition at line 103 of file w3tidemd.F90.
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
ndel
integer, dimension(180) w3tidemd::ndel
Definition at line 103 of file w3tidemd.F90.
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
ndset
integer w3tidemd::ndset
Definition at line 136 of file w3tidemd.F90.
   INTEGER                      :: NDSET, TIDE_VERBOSE = 0
Referenced by flex_tidana_webpage(), and vuf().
nkonco
integer w3tidemd::nkonco
Definition at line 96 of file w3tidemd.F90.
Referenced by vuf_set_parameters().
nmaxp1
integer, parameter w3tidemd::nmaxp1 =MC*2
Definition at line 92 of file w3tidemd.F90.
nmaxpm
integer, parameter w3tidemd::nmaxpm =NR*2+NMAXP1
Definition at line 92 of file w3tidemd.F90.
nr
integer, parameter w3tidemd::nr =106000
Definition at line 92 of file w3tidemd.F90.
Referenced by tide_read_timeseries().
ntidal_con
integer w3tidemd::ntidal_con
Definition at line 96 of file w3tidemd.F90.
   INTEGER                     :: NTIDAL_CON, NTOTAL_CON, NKONCO
Referenced by opnvuf(), setvuf(), setvuf_fast(), tide_set_indices(), and vuf_set_parameters().
ntotal_con
integer w3tidemd::ntotal_con
Definition at line 96 of file w3tidemd.F90.
Referenced by opnvuf(), setvuf(), setvuf_fast(), tide_set_indices(), vuf(), and vuf_set_parameters().
ph
real, dimension(180) w3tidemd::ph
Definition at line 102 of file w3tidemd.F90.
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
semi
real, dimension(:), allocatable w3tidemd::semi
Definition at line 100 of file w3tidemd.F90.
   REAL, ALLOCATABLE             :: SEMI(:),COEF_CON(:)
Referenced by opnvuf(), setvuf(), setvuf_fast(), and vuf_set_parameters().
tidal_const
real, dimension(:,:,:,:,:), allocatable w3tidemd::tidal_const
Definition at line 117 of file w3tidemd.F90.
   REAL, ALLOCATABLE            :: TIDAL_CONST(:,:,:,:,:)                 ! array of freq. of tidal constituents
Referenced by w3fldsmd::w3fldtide2().
tide_ampc
real, dimension(mc,2) w3tidemd::tide_ampc
Definition at line 129 of file w3tidemd.F90.
   REAL                         :: TIDE_AMPC(MC,2), TIDE_PHG(MC,2),   &
        TIDE_SIG1(MC,2), TIDE_SIG2(MC,2),  &
        TIDE_SIG3(MC,2), TIDE_TTEST(MC,2)
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), tide_write_results(), w3updtmd::w3ucur(), and w3updtmd::w3ulev().
tide_ampci
real, dimension(10,10,2) w3tidemd::tide_ampci
Definition at line 132 of file w3tidemd.F90.
   REAL                         :: TIDE_ampci(10,10,2), TIDE_phgi(10,10,2)
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), and tide_write_results().
tide_data
real, dimension(:,:), allocatable w3tidemd::tide_data
Definition at line 122 of file w3tidemd.F90.
   REAL, ALLOCATABLE            :: TIDE_DATA(:,:)
Referenced by flex_tidana_webpage(), and tide_read_timeseries().
tide_days
integer(kind=4), dimension(:), allocatable w3tidemd::tide_days
Definition at line 123 of file w3tidemd.F90.
   INTEGER(KIND=4), ALLOCATABLE :: TIDE_DAYS(:), TIDE_SECS(:)
Referenced by flex_tidana_webpage(), and tide_read_timeseries().
tide_dt
real, parameter w3tidemd::tide_dt = 1800.
Definition at line 125 of file w3tidemd.F90.
   REAL,            PARAMETER   :: TIDE_DT = 1800.   ! time step used for forcing
tide_freqc
real, dimension(:), allocatable w3tidemd::tide_freqc
Definition at line 110 of file w3tidemd.F90.
   REAL, ALLOCATABLE            :: TIDE_FREQC(:)                 ! array of freq. of tidal constituents
Referenced by flex_tidana_webpage(), tide_find_indices_analysis(), tide_find_indices_prediction(), tide_read_anapar(), tide_write_results(), and w3fldsmd::w3fldtide2().
tide_hours
real(kind=8), dimension(:), allocatable w3tidemd::tide_hours
Definition at line 124 of file w3tidemd.F90.
   REAL(KIND=8),    allocatable :: tide_hours(:)
Referenced by tide_predict_only(), and tide_read_timeseries().
tide_index
integer, dimension(mc) w3tidemd::tide_index
Definition at line 133 of file w3tidemd.F90.
   INTEGER                      :: TIDE_INDEX(MC),TIDE_INDEX2(MC)
Referenced by setvuf().
tide_index2
integer, dimension(mc) w3tidemd::tide_index2
Definition at line 133 of file w3tidemd.F90.
Referenced by setvuf_fast(), tide_set_indices(), and w3updtmd::w3ucur().
tide_indexj
integer, dimension(:), allocatable w3tidemd::tide_indexj
Definition at line 105 of file w3tidemd.F90.
   INTEGER , ALLOCATABLE         :: TIDE_INDEXJ(:),TIDE_INDEXJK(:)
Referenced by setvuf(), setvuf_fast(), tide_set_indices(), and vuf_set_parameters().
tide_indexjk
integer, dimension(:), allocatable w3tidemd::tide_indexjk
Definition at line 105 of file w3tidemd.F90.
Referenced by setvuf(), setvuf_fast(), tide_set_indices(), and vuf_set_parameters().
tide_konan
character(len=5), dimension(10) w3tidemd::tide_konan
Definition at line 113 of file w3tidemd.F90.
   CHARACTER(LEN=5)             :: TIDE_KONAN(10), TIDE_KONIN(10,10)
Referenced by flex_tidana_webpage(), tide_read_anapar(), and tide_write_results().
tide_konin
character(len=5), dimension(10,10) w3tidemd::tide_konin
Definition at line 113 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), tide_read_anapar(), and tide_write_results().
tide_mf
integer w3tidemd::tide_mf
Definition at line 109 of file w3tidemd.F90.
   INTEGER                      :: TIDE_MF, TIDE_NX, TIDE_NY
Referenced by flex_tidana_webpage(), setvuf(), setvuf_fast(), tide_find_indices_analysis(), tide_find_indices_prediction(), tide_predict(), tide_predict_only(), tide_read_anapar(), tide_set_indices(), tide_write_results(), w3fldsmd::w3fldtide1(), w3fldsmd::w3fldtide2(), w3updtmd::w3ucur(), and w3updtmd::w3ulev().
tide_nin
integer w3tidemd::tide_nin
Definition at line 116 of file w3tidemd.F90.
   INTEGER                      :: TIDE_NIN,TIDE_NINF(10)
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), tide_read_anapar(), and tide_write_results().
tide_ninf
integer, dimension(10) w3tidemd::tide_ninf
Definition at line 116 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), tide_read_anapar(), and tide_write_results().
tide_nti
integer(kind=4) w3tidemd::tide_nti
Definition at line 121 of file w3tidemd.F90.
   INTEGER(KIND=4)              :: TIDE_NTI
Referenced by flex_tidana_webpage(), and tide_write_results().
tide_nx
integer w3tidemd::tide_nx
Definition at line 109 of file w3tidemd.F90.
tide_ny
integer w3tidemd::tide_ny
Definition at line 109 of file w3tidemd.F90.
tide_phg
real, dimension(mc,2) w3tidemd::tide_phg
Definition at line 129 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), tide_write_results(), w3updtmd::w3ucur(), and w3updtmd::w3ulev().
tide_phgi
real, dimension(10,10,2) w3tidemd::tide_phgi
Definition at line 132 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), and tide_write_results().
tide_r
real, dimension(10,10) w3tidemd::tide_r
Definition at line 114 of file w3tidemd.F90.
   REAL                         :: TIDE_R(10,10), TIDE_ZETA(10,10)
Referenced by flex_tidana_webpage(), and tide_read_anapar().
tide_secs
integer(kind=4), dimension(:), allocatable w3tidemd::tide_secs
Definition at line 123 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), and tide_read_timeseries().
tide_sig1
real, dimension(mc,2) w3tidemd::tide_sig1
Definition at line 129 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), and tide_write_results().
tide_sig2
real, dimension(mc,2) w3tidemd::tide_sig2
Definition at line 129 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), and tide_write_results().
tide_sig3
real, dimension(mc,2) w3tidemd::tide_sig3
Definition at line 129 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), and tide_write_results().
tide_sigan
real, dimension(10) w3tidemd::tide_sigan
Definition at line 115 of file w3tidemd.F90.
   REAL                         :: TIDE_SIGAN(10),TIDE_SIGIN(10,10)   ! these two are only read from files and written out
Referenced by tide_read_anapar().
tide_sigin
real, dimension(10,10) w3tidemd::tide_sigin
Definition at line 115 of file w3tidemd.F90.
Referenced by tide_read_anapar(), and tide_write_results().
tide_ttest
real, dimension(mc,2) w3tidemd::tide_ttest
Definition at line 129 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), and tide_write_results().
tide_verbose
integer w3tidemd::tide_verbose = 0
Definition at line 136 of file w3tidemd.F90.
tide_zeta
real, dimension(10,10) w3tidemd::tide_zeta
Definition at line 114 of file w3tidemd.F90.
Referenced by flex_tidana_webpage(), and tide_read_anapar().
tidecon_allnames
character*5, dimension(:), allocatable w3tidemd::tidecon_allnames
Definition at line 97 of file w3tidemd.F90.
   CHARACTER*5,    ALLOCATABLE :: TIDECON_ALLNAMES(:)       ! array of names of tidal constituents
Referenced by opnvuf(), setvuf(), tide_set_indices(), vuf(), vuf_set_parameters(), and w3updtmd::w3ucur().
tidecon_name
character(len=5), dimension(:), allocatable w3tidemd::tidecon_name
Definition at line 112 of file w3tidemd.F90.
   CHARACTER(LEN=5), ALLOCATABLE:: TIDECON_NAME(:)               ! array of names of tidal constituents
Referenced by flex_tidana_webpage(), setvuf(), tide_find_indices_analysis(), tide_find_indices_prediction(), tide_predict(), tide_predict_only(), tide_read_anapar(), tide_set_indices(), tide_write_results(), and w3fldsmd::w3fldtide2().
tidecon_namei
character(len=5), dimension(:), allocatable w3tidemd::tidecon_namei
Definition at line 111 of file w3tidemd.F90.
   CHARACTER(LEN=5), ALLOCATABLE:: TIDECON_NAMEI(:)              ! array of names of tidal constituents
Referenced by w3fldsmd::w3fldtide2().
twpi
double precision, parameter w3tidemd::twpi =3.1415926535898*2.
Definition at line 86 of file w3tidemd.F90.
   DOUBLE PRECISION, PARAMETER  :: TWPI=3.1415926535898*2.
Referenced by flex_tidana_webpage(), tide_predict(), tide_predict_only(), w3updtmd::w3ucur(), and w3updtmd::w3ulev().
u_arg
real, dimension(:,:), allocatable w3tidemd::u_arg
Definition at line 101 of file w3tidemd.F90.
Referenced by setvuf(), and vuf().
v_arg
real, dimension(:,:), allocatable w3tidemd::v_arg
Definition at line 101 of file w3tidemd.F90.
   REAL , ALLOCATABLE            :: V_ARG(:,:),F_ARG(:,:),U_ARG(:,:)
Referenced by setvuf(), and vuf().