WAVEWATCH III: yownodepool Module Reference
yownodepool Module Reference
Has data that belong to nodes.
Data Types
type t_node
Holds the nodes data.
Functions/Subroutines
type(t_node) function, pointer, public nodes (id_local)
return pointer to the (global) node from the local id.
type(t_node) function, pointer, public ghosts (id)
return pointer to the (global) (ghost) node Ghost nodes are nodes in the global node array, with the particularity that their local id is the id from another domain This is in effekt ghostlg(1:ng)
subroutine, public finalizenodepool ()
Variables
real(rkind), dimension(:), allocatable, target, public x
coordinates of the local + ghost nodes.
real(rkind), dimension(:), allocatable, target, public y
real(rkind), dimension(:), allocatable, target, public z
real(rkind), dimension(:), allocatable, target, public pdlib_si
real(rkind), dimension(:), allocatable, target, public pdlib_tria
real(rkind), dimension(:), allocatable, target, public pdlib_tria03
real(rkind), dimension(:,:), allocatable, target, public pdlib_ien
integer, dimension(:), allocatable, target, public pdlib_ccon
integer, dimension(:), allocatable, target, public pdlib_ia
integer, dimension(:), allocatable, target, public pdlib_ja
integer, dimension(:), allocatable, target, public pdlib_ia_p
integer, dimension(:), allocatable, target, public pdlib_ja_p
integer, dimension(:,:,:), allocatable, target, public pdlib_ja_ie
integer, dimension(:), allocatable, target, public pdlib_pos_cell
integer, dimension(:), allocatable, target, public pdlib_ie_cell
integer, dimension(:,:), allocatable, target, public pdlib_ie_cell2
integer, dimension(:,:), allocatable, target, public pdlib_pos_cell2
integer, dimension(:,:), allocatable, target, public pdlib_posi
integer, dimension(:), allocatable, target, public pdlib_i_diag
integer, dimension(:), allocatable, target, public listnp
integer, dimension(:), allocatable, target, public listnpa
integer, dimension(:), allocatable, target, public listiplg
integer, public np_global = 0
number of nodes, global
integer, public pdlib_nnz = 0
integer, public np = 0
number of nodes, local
integer, public ng = 0
number of ghost nodes this partition holds
integer, public npa = 0
number of ghost + resident nodes this partition holds
type(t_node), dimension(:), allocatable, target, public nodes_global
all nodes with their data.
integer, public maxconnnodes = 0
max number of conntected nodes to a node
integer, dimension(:,:), allocatable, public connnodes_data
conntected Node Array.
integer, dimension(:), allocatable, public iplg
Node local to global mapping.
integer, dimension(:), allocatable, public ipgl
Node global to local mapping np_global long.
integer, dimension(:), allocatable, public ghostlg
Ghost local to global mapping ng long.
integer, dimension(:), allocatable, public ghostgl
Ghost global to local mapping np_global long.
integer, dimension(:), allocatable, public np_perproc
Numbers of Nodes pro Processor.
integer, dimension(:), allocatable, public np_perprocsum
Number of Nodes pro Processor totalize.
Detailed Description
Has data that belong to nodes.
Function/Subroutine Documentation
finalizenodepool()
subroutine, public yownodepool::finalizenodepool
Definition at line 220 of file yownodepool.F90.
     implicit none
     if(allocated(x))              deallocate(x)
     if(allocated(y))              deallocate(y)
     if(allocated(z))              deallocate(z)
     if(allocated(nodes_global))   deallocate(nodes_global)
     if(allocated(connnodes_data)) deallocate(connnodes_data)
     if(allocated(iplg))           deallocate(iplg)
     if(allocated(ipgl))           deallocate(ipgl)
     if(allocated(ghostlg))        deallocate(ghostlg)
     if(allocated(ghostgl))        deallocate(ghostgl)
     if(allocated(np_perproc))     deallocate(np_perproc)
     if(allocated(np_perprocsum))  deallocate(np_perprocsum)
References connnodes_data, ghostgl, ghostlg, ipgl, iplg, nodes_global, np_perproc, np_perprocsum, x, y, and z.
Referenced by yowpdlibmain::finalizepd().
ghosts()
type(t_node) function, pointer, public yownodepool::ghosts (integer, intent(in) id)
return pointer to the (global) (ghost) node Ghost nodes are nodes in the global node array, with the particularity that their local id is the id from another domain This is in effekt ghostlg(1:ng)
Parameters
id Counts from 1 to ng
Returns
pointer to the (global) node
Definition at line 172 of file yownodepool.F90.
     implicit none
     integer, intent(in) :: id
     type(t_Node), pointer :: ghosts
     ghosts => nodes_global(ghostlg(id))
References connnodes_data, ghostlg, nodes_global, and np.
Referenced by yowpdlibmain::findconndomains(), yowpdlibmain::findghostnodes(), yowexchangemodule::pdlib_exchange1dreal(), and yowexchangemodule::pdlib_exchange2dreal().
nodes()
type(t_node) function, pointer, public yownodepool::nodes (integer, intent(in) id_local)
return pointer to the (global) node from the local id.
This is in effekt iplg(id_local)
Parameters
id_local the local node number
Returns
poiner to the (global) node
Definition at line 159 of file yownodepool.F90.
     implicit none
     integer, intent(in) :: id_local
     type(t_Node), pointer :: nodes
     nodes => nodes_global(iplg(id_local))
References iplg, and nodes_global.
Referenced by yowpdlibmain::exchangeghostids(), yowpdlibmain::findconnnodes(), yowpdlibmain::findghostnodes(), yowpdlibmain::postpartition(), and yowpdlibmain::runparmetis().
Variable Documentation
connnodes_data
integer, dimension(:,:), allocatable, public yownodepool::connnodes_data
conntected Node Array.
2D Array. Holds the global node numbers conntected to each other.
Parameters
1 global node number from wich you want the neighbors
2 from 1 to t_Node::nConnNodes
Definition at line 112 of file yownodepool.F90.
   integer, public, allocatable :: connNodes_data(:,:)
Referenced by finalizenodepool(), yowpdlibmain::findconnnodes(), and ghosts().
ghostgl
integer, dimension(:), allocatable, public yownodepool::ghostgl
Ghost global to local mapping np_global long.
give the local ghost node id. local ghost node ids for other ranks are set to 0!
Definition at line 129 of file yownodepool.F90.
   integer, public, allocatable :: ghostgl(:)
Referenced by yowexchangemodule::creatempitype(), finalizenodepool(), and yowpdlibmain::findghostnodes().
ghostlg
integer, dimension(:), allocatable, public yownodepool::ghostlg
Ghost local to global mapping ng long.
give the global node id of nodes, which belong to adjacent domains
Definition at line 125 of file yownodepool.F90.
   integer, public, allocatable :: ghostlg(:)
Referenced by yowpdlibmain::computetria_ien_si_ccon(), yowpdlibmain::element_crosses_dateline(), finalizenodepool(), yowpdlibmain::findghostnodes(), ghosts(), and yowpdlibmain::postpartition2().
ipgl
integer, dimension(:), allocatable, public yownodepool::ipgl
Node global to local mapping np_global long.
give the local node id but only for this rank. local node id for other ranks are set to 0!
Definition at line 120 of file yownodepool.F90.
   integer, public, allocatable :: ipgl(:)
Referenced by yowexchangemodule::creatempitype(), finalizenodepool(), w3parall::get_jsea_ibelong(), w3parall::init_get_jsea_isproc(), yowpdlibmain::initfromgriddim(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), yowpdlibmain::postpartition(), and pdlib_w3profsmd::set_ug_iobp_pdlib_init().
iplg
integer, dimension(:), allocatable, public yownodepool::iplg
Node local to global mapping.
np long. give the gobal node id
Definition at line 116 of file yownodepool.F90.
   integer, public, allocatable :: iplg(:)
Referenced by pdlib_w3profsmd::action_limiter_local(), pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3wavset::compute_active_node(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), yowpdlibmain::computetria_ien_si_ccon(), wmesmfmd::createexpmesh(), w3wavset::differentiate_xydir_mapsta(), yowpdlibmain::element_crosses_dateline(), yowrankmodule::exchangeiplg(), wmesmfmd::fieldindex(), finalizenodepool(), yowpdlibmain::findghostnodes(), w3parall::get_jsea_ibelong(), w3parall::init_get_isea(), w3parall::init_get_jsea_isproc(), yowpdlibmain::initfromgriddim(), nodes(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), yowpdlibmain::postpartition(), yowpdlibmain::postpartition2(), yowpdlibmain::prepartition(), yowpdlibmain::runparmetis(), pdlib_w3profsmd::scal_integral_print_general(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), wmesmfmd::setupimpbmsk(), w3parall::synchronize_global_array(), w3wavset::trig_compute_lh_stress(), w3wavset::trig_wave_setup_apply_precond(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_compute_system(), w3wavemd::w3wave(), and pdlib_w3profsmd::write_var_to_text_file().
listiplg
integer, dimension(:), allocatable, target, public yownodepool::listiplg
Definition at line 86 of file yownodepool.F90.
Referenced by yowfunction::computeboundaryinformation(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), pdlib_field_vec::unst_pdlib_read_from_file(), and pdlib_field_vec::unst_pdlib_write_to_file().
listnp
integer, dimension(:), allocatable, target, public yownodepool::listnp
Definition at line 86 of file yownodepool.F90.
   integer, public, target, allocatable :: ListNP(:), ListNPA(:), ListIPLG(:)
Referenced by yowfunction::computeboundaryinformation(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), pdlib_field_vec::unst_pdlib_read_from_file(), and pdlib_field_vec::unst_pdlib_write_to_file().
listnpa
integer, dimension(:), allocatable, target, public yownodepool::listnpa
Definition at line 86 of file yownodepool.F90.
Referenced by yowfunction::computeboundaryinformation(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), pdlib_field_vec::unst_pdlib_read_from_file(), and pdlib_field_vec::unst_pdlib_write_to_file().
maxconnnodes
integer, public yownodepool::maxconnnodes = 0
max number of conntected nodes to a node
Definition at line 106 of file yownodepool.F90.
   integer, public :: maxConnNodes = 0
Referenced by yowpdlibmain::findconnnodes().
ng
integer, public yownodepool::ng = 0
number of ghost nodes this partition holds
Definition at line 96 of file yownodepool.F90.
   integer, public :: ng = 0
Referenced by yowpdlibmain::computetria_ien_si_ccon(), yowpdlibmain::element_crosses_dateline(), yowpdlibmain::findconndomains(), yowpdlibmain::findghostnodes(), yowpdlibmain::initfromgriddim(), yowexchangemodule::pdlib_exchange1dreal(), yowexchangemodule::pdlib_exchange2dreal(), and yowpdlibmain::postpartition2().
nodes_global
type(t_node), dimension(:), allocatable, target, public yownodepool::nodes_global
all nodes with their data.
to iterate over all local nodes, use funtion node(local id) to get a pointer to t_node
Definition at line 103 of file yownodepool.F90.
   type(t_Node), public, allocatable, target :: nodes_global(:)
Referenced by yowpdlibmain::assignmesh(), yowelementpool::belongto(), wmesmfmd::createexpmesh(), yowpdlibmain::element_crosses_dateline(), finalizenodepool(), yowpdlibmain::findconnnodes(), yowpdlibmain::findghostnodes(), ghosts(), nodes(), yowexchangemodule::pdlib_exchange1dreal(), yowexchangemodule::pdlib_exchange2dreal(), yowpdlibmain::postpartition(), yowpdlibmain::postpartition2(), and yowpdlibmain::runparmetis().
np
integer, public yownodepool::np = 0
number of nodes, local
Definition at line 93 of file yownodepool.F90.
   integer, public :: np  = 0
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::all_vaold_integral_print(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::block_solver_explicit_init(), pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), w3wavset::compute_active_node(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), yowpdlibmain::computetria_ien_si_ccon(), yowexchangemodule::creatempitype(), pdlib_w3profsmd::deallocate_pdlib_global(), yowpdlibmain::element_crosses_dateline(), yowpdlibmain::exchangeghostids(), yowrankmodule::exchangeiplg(), wmesmfmd::fieldindex(), yowpdlibmain::findconnnodes(), yowpdlibmain::findghostnodes(), ghosts(), yowpdlibmain::initfromgriddim(), pdlib_w3profsmd::jacobi_init(), yowexchangemodule::pdlib_exchange1dreal(), yowexchangemodule::pdlib_exchange2dreal(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), yowpdlibmain::postpartition(), yowpdlibmain::postpartition2(), yowpdlibmain::prepartition(), pdlib_w3profsmd::print_wn_statistic(), yowpdlibmain::runparmetis(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), wmesmfmd::setupimpbmsk(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_compute_system(), w3wavset::trig_wave_setup_scalar_prod(), w3wavset::trig_wave_setup_solve_poisson_neumann_dir(), w3wdatmd::w3dimw(), w3wavemd::w3wave(), and pdlib_w3profsmd::write_var_to_text_file().
np_global
integer, public yownodepool::np_global = 0
number of nodes, global
Definition at line 89 of file yownodepool.F90.
   integer, public :: np_global = 0
Referenced by yowpdlibmain::assignmesh(), yowpdlibmain::computetria_ien_si_ccon(), yowpdlibmain::element_crosses_dateline(), yowrankmodule::exchangeiplg(), yowpdlibmain::findconnnodes(), yowpdlibmain::findghostnodes(), w3triamd::get_boundary_status(), yowpdlibmain::initfromgriddim(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), yowpdlibmain::postpartition(), yowpdlibmain::postpartition2(), yowpdlibmain::prepartition(), yowpdlibmain::runparmetis(), and w3parall::synchronize_ipgl_etc_array().
np_perproc
integer, dimension(:), allocatable, public yownodepool::np_perproc
Numbers of Nodes pro Processor.
Has the number of nodes each thread ows. Array is nTasks long
Definition at line 133 of file yownodepool.F90.
   integer, public, allocatable :: np_perProc(:)
Referenced by finalizenodepool(), yowpdlibmain::postpartition(), yowpdlibmain::prepartition(), and yowpdlibmain::runparmetis().
np_perprocsum
integer, dimension(:), allocatable, public yownodepool::np_perprocsum
Number of Nodes pro Processor totalize.
Has the sum of nodes each thread owen. Array in nTasks+1 long Processor i stores np_perProcSum(i)::np_perProcSum(i+1)-1 nodes
Definition at line 138 of file yownodepool.F90.
   integer, public, allocatable :: np_perProcSum(:)
Referenced by finalizenodepool(), yowpdlibmain::initfromgriddim(), yowpdlibmain::postpartition(), yowpdlibmain::prepartition(), and yowpdlibmain::runparmetis().
npa
integer, public yownodepool::npa = 0
number of ghost + resident nodes this partition holds
Definition at line 99 of file yownodepool.F90.
   integer, public :: npa = 0
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::all_vaold_integral_print(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::block_solver_explicit_init(), pdlib_w3profsmd::block_solver_init(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), pdlib_w3profsmd::check_array_integral_nx_r8(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3wavset::compute_active_node(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), yowpdlibmain::computetria_ien_si_ccon(), wmesmfmd::createexpmesh(), pdlib_w3profsmd::deallocate_pdlib_global(), w3wavset::differentiate_xydir(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), yowpdlibmain::element_crosses_dateline(), yowrankmodule::exchangeiplg(), yowexchangemodule::finalizeexchangemodule(), yowpdlibmain::findghostnodes(), yowpdlibmain::initfromgriddim(), pdlib_w3profsmd::jacobi_init(), yowexchangemodule::pdlib_exchange1dreal(), yowexchangemodule::pdlib_exchange2dreal(), yowexchangemodule::pdlib_exchange2dreal_zero(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), yowpdlibmain::postpartition2(), pdlib_w3profsmd::printtotaloffcontrib(), yowpdlibmain::runparmetis(), pdlib_w3profsmd::scal_integral_print_general(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3parall::set_up_nseal_nsealm(), w3parall::synchronize_global_array(), w3wavset::trig_compute_lh_stress(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_apply_precond(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_compute_system(), w3wavset::trig_wave_setup_scalar_prod(), w3wavset::trig_wave_setup_solve_poisson_neumann_dir(), w3triamd::ug_gradients(), w3wdatmd::w3dimw(), w3initmd::w3init(), w3wavemd::w3wave(), wminiomd::wmioeg(), wminiomd::wmiohg(), and pdlib_w3profsmd::write_var_to_text_file().
pdlib_ccon
integer, dimension(:), allocatable, target, public yownodepool::pdlib_ccon
Definition at line 81 of file yownodepool.F90.
   integer, public, target, allocatable :: PDLIB_CCON(:), PDLIB_IA(:), PDLIB_JA(:)
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::computetria_ien_si_ccon(), yowpdlibmain::element_crosses_dateline(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), and pdlib_w3profsmd::printtotaloffcontrib().
pdlib_i_diag
integer, dimension(:), allocatable, target, public yownodepool::pdlib_i_diag
Definition at line 85 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::element_crosses_dateline(), w3wavset::fd_wave_setup_apply_precond(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3wavset::preparation_fd_scheme(), pdlib_w3profsmd::printtotaloffcontrib(), w3wavset::trig_wave_setup_apply_precond(), w3wavset::trig_wave_setup_compute_system(), and w3srcemd::w3srce().
pdlib_ia
integer, dimension(:), allocatable, target, public yownodepool::pdlib_ia
Definition at line 81 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), w3wavset::compute_active_node(), yowpdlibmain::element_crosses_dateline(), w3wavset::fd_wave_setup_apply_fct(), w3wavset::fd_wave_setup_apply_precond(), w3wavset::preparation_fd_scheme(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_apply_precond(), and w3wavset::trig_wave_setup_computation().
pdlib_ia_p
integer, dimension(:), allocatable, target, public yownodepool::pdlib_ia_p
Definition at line 82 of file yownodepool.F90.
   integer, public, target, allocatable :: PDLIB_IA_P(:), PDLIB_JA_P(:), PDLIB_JA_IE(:,:,:)
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::element_crosses_dateline(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), and pdlib_w3profsmd::printtotaloffcontrib().
pdlib_ie_cell
integer, dimension(:), allocatable, target, public yownodepool::pdlib_ie_cell
Definition at line 83 of file yownodepool.F90.
Referenced by yowpdlibmain::element_crosses_dateline().
pdlib_ie_cell2
integer, dimension(:,:), allocatable, target, public yownodepool::pdlib_ie_cell2
Definition at line 84 of file yownodepool.F90.
   integer, public, target, allocatable :: PDLIB_IE_CELL2(:,:), PDLIB_POS_CELL2(:,:)
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::element_crosses_dateline(), and pdlib_w3profsmd::pdlib_w3xypfsfct2().
pdlib_ien
real(rkind), dimension(:,:), allocatable, target, public yownodepool::pdlib_ien
Definition at line 80 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::computetria_ien_si_ccon(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), and w3triamd::ug_gradients().
pdlib_ja
integer, dimension(:), allocatable, target, public yownodepool::pdlib_ja
Definition at line 81 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), w3wavset::compute_active_node(), yowpdlibmain::element_crosses_dateline(), w3wavset::fd_wave_setup_apply_fct(), w3wavset::fd_wave_setup_apply_precond(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3wavset::preparation_fd_scheme(), pdlib_w3profsmd::printtotaloffcontrib(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_apply_precond(), and w3wavset::trig_wave_setup_computation().
pdlib_ja_ie
integer, dimension(:,:,:), allocatable, target, public yownodepool::pdlib_ja_ie
Definition at line 82 of file yownodepool.F90.
Referenced by yowpdlibmain::element_crosses_dateline(), and w3wavset::trig_wave_setup_compute_system().
pdlib_ja_p
integer, dimension(:), allocatable, target, public yownodepool::pdlib_ja_p
Definition at line 82 of file yownodepool.F90.
Referenced by yowpdlibmain::element_crosses_dateline().
pdlib_nnz
integer, public yownodepool::pdlib_nnz = 0
Definition at line 90 of file yownodepool.F90.
   integer, public :: PDLIB_NNZ = 0
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), w3wavset::compute_active_node(), pdlib_w3profsmd::deallocate_pdlib_global(), yowpdlibmain::element_crosses_dateline(), w3wavset::fd_wave_setup_apply_precond(), w3wavset::fd_wave_setup_computation(), w3wavset::fd_wave_setup_compute_system(), w3wavset::fd_wave_setup_solve_poisson_neumann_dir(), pdlib_w3profsmd::jacobi_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3wavset::preparation_fd_scheme(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_apply_precond(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_compute_system(), and w3wavset::trig_wave_setup_solve_poisson_neumann_dir().
pdlib_pos_cell
integer, dimension(:), allocatable, target, public yownodepool::pdlib_pos_cell
Definition at line 83 of file yownodepool.F90.
   integer, public, target, allocatable :: PDLIB_POS_CELL(:), PDLIB_IE_CELL(:)
Referenced by yowpdlibmain::element_crosses_dateline().
pdlib_pos_cell2
integer, dimension(:,:), allocatable, target, public yownodepool::pdlib_pos_cell2
Definition at line 84 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), and yowpdlibmain::element_crosses_dateline().
pdlib_posi
integer, dimension(:,:), allocatable, target, public yownodepool::pdlib_posi
Definition at line 85 of file yownodepool.F90.
   integer, public, target, allocatable :: PDLIB_POSI(:,:), PDLIB_I_DIAG(:)
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), and yowpdlibmain::element_crosses_dateline().
pdlib_si
real(rkind), dimension(:), allocatable, target, public yownodepool::pdlib_si
Definition at line 80 of file yownodepool.F90.
   real(rkind), public, target, allocatable :: PDLIB_SI(:), PDLIB_TRIA(:), PDLIB_TRIA03(:), PDLIB_IEN(:,:)
Referenced by pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::computetria_ien_si_ccon(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3wavset::trig_set_meanvalue_to_zero(), w3srcemd::w3srce(), and w3ref1md::w3sref().
pdlib_tria
real(rkind), dimension(:), allocatable, target, public yownodepool::pdlib_tria
Definition at line 80 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::computetria_ien_si_ccon(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3wavset::trig_compute_diff(), w3wavset::trig_wave_setup_compute_system(), and w3triamd::ug_gradients().
pdlib_tria03
real(rkind), dimension(:), allocatable, target, public yownodepool::pdlib_tria03
Definition at line 80 of file yownodepool.F90.
Referenced by pdlib_w3profsmd::calcarray_jacobi_vec(), and yowpdlibmain::computetria_ien_si_ccon().
x
real(rkind), dimension(:), allocatable, target, public yownodepool::x
coordinates of the local + ghost nodes.
range [1:npa]
Definition at line 79 of file yownodepool.F90.
   real(rkind), public, target, allocatable :: x(:), y(:), z(:)
Referenced by yowpdlibmain::computetria_ien_si_ccon(), finalizenodepool(), yowpdlibmain::postpartition2(), and w3wavset::trig_compute_diff().
y
real(rkind), dimension(:), allocatable, target, public yownodepool::y
Definition at line 79 of file yownodepool.F90.
Referenced by yowpdlibmain::computetria_ien_si_ccon(), finalizenodepool(), yowpdlibmain::postpartition2(), and w3wavset::trig_compute_diff().
z
real(rkind), dimension(:), allocatable, target, public yownodepool::z
Definition at line 79 of file yownodepool.F90.
Referenced by yowpdlibmain::computetria_ien_si_ccon(), finalizenodepool(), and yowpdlibmain::postpartition2().