WAVEWATCH III: yowexchangemodule Module Reference
yowexchangemodule Module Reference
Has only the ghost nodes assign to a neighbor domain.
Data Types
type t_neighbordomain
Holds some data belong to a neighbor Domain.
Functions/Subroutines
subroutine creatempitype (this)
subroutine, public initnbrdomains (nConnD)
subroutine, public creatempitypes ()
subroutine, public pdlib_exchange1dreal (U)
exchange values in U.
subroutine, public pdlib_exchange2dreal (U)
subroutine, public setdimsize (second)
set the size of the second and third dimension for exchange
subroutine, public finalizeexchangemodule ()
subroutine, public pdlib_exchange2dreal_zero (U)
Variables
type(t_neighbordomain), dimension(:), allocatable, public neighbordomains
Knows for all domains neighbors, which node we must send or revc from neighbor domains from 1 to nConnDomains.
integer, public nconndomains = 0
Number of neighbor domains.
integer, public n2nddim = 1
number of the second dimension for exchange
integer, public nnthdim = 1
number of the second dimension for exchange (nth only for wave model)
Detailed Description
Has only the ghost nodes assign to a neighbor domain.
Function/Subroutine Documentation
creatempitype()
subroutine yowexchangemodule::creatempitype (class(t_neighbordomain), intent(inout) this)
Definition at line 151 of file yowexchangeModule.F90.
     use yowerr
     use mpi
     use yownodepool, only: ghostgl, np, ipgl
     use yowdatapool, only: rtype, itype
     implicit none
     class(t_neighborDomain), intent(inout) :: this
     integer :: ierr
     integer :: dsplSend(this%numNodesToSend)
     integer :: dsplRecv(this%numNodesToReceive)
     ! MPI datatypes for size(U) == npa+1  U(0:npa)
     dsplsend = ipgl(this%nodesToSend)
     dsplrecv = ghostgl(this%nodesToReceive) + np
     ! p1D real
     call mpi_type_create_indexed_block(this%numNodesToSend, 1, dsplsend, rtype, this%p1DRsendType_zero, ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p1DRsendType_zero,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_create_indexed_block(this%numNodesToReceive, 1, dsplrecv, rtype, this%p1DRrecvType_zero, ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p1DRrecvType_zero,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     ! MPI datatypes for size(U) == npa  U(1:npa)
     dsplsend(:) = dsplsend(:) - 1 ! C count from 0; FORTRAN count from 1
     dsplrecv(:) = dsplrecv(:) - 1
     ! p1D real
     call mpi_type_create_indexed_block(this%numNodesToSend, 1, dsplsend, rtype, this%p1DRsendType,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p1DRsendType,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_create_indexed_block(this%numNodesToReceive, 1, dsplrecv, rtype, this%p1DRrecvType,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p1DRrecvType,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     ! MPI datatypes for size(U) == npa+1  U(0:npa)
     ! p2D real second dim is n2ndDim long
     dsplsend = (ipgl(this%nodesToSend)) * n2nddim
     dsplrecv = (ghostgl(this%nodesToReceive) + np) * n2nddim
     call mpi_type_create_indexed_block(this%numNodesToSend, n2nddim, dsplsend, rtype, this%p2DRsendType_zero,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p2DRsendType_zero,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_create_indexed_block(this%numNodesToReceive, n2nddim, dsplrecv, rtype, this%p2DRrecvType_zero,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p2DRrecvType_zero,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     ! MPI datatypes for size(U) == npa  U(1:npa)
     ! p2D real second dim is n2ndDim long
     dsplsend = (ipgl(this%nodesToSend)-1) * n2nddim
     dsplrecv = (ghostgl(this%nodesToReceive) + np -1) * n2nddim
     call mpi_type_create_indexed_block(this%numNodesToSend, n2nddim, dsplsend, rtype, this%p2DRsendType1,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p2DRsendType1,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_create_indexed_block(this%numNodesToReceive, n2nddim, dsplrecv, rtype, this%p2DRrecvType1,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
     call mpi_type_commit(this%p2DRrecvType1,ierr)
     if(ierr /= mpi_success) CALL parallel_abort("createMPIType", ierr)
References yownodepool::ghostgl, yownodepool::ipgl, yowdatapool::itype, n2nddim, yownodepool::np, yowerr::parallel_abort(), and yowdatapool::rtype.
creatempitypes()
subroutine, public yowexchangemodule::creatempitypes
Definition at line 236 of file yowexchangeModule.F90.
     implicit none
     integer :: i
     do i=1, nconndomains
       call neighbordomains(i)%createMPIType()
     end do
References nconndomains, and neighbordomains.
Referenced by yowpdlibmain::exchangeghostids().
finalizeexchangemodule()
subroutine, public yowexchangemodule::finalizeexchangemodule
Definition at line 381 of file yowexchangeModule.F90.
     implicit none
     integer :: i
     if(allocated(neighbordomains)) then
       do i=1, size(neighbordomains)
         call neighbordomains(i)%finalize()
       end do
       deallocate(neighbordomains)
     endif
References yowdatapool::comm, yowdatapool::myrank, nconndomains, neighbordomains, yownodepool::npa, yowerr::parallel_abort(), and yowdatapool::rkind.
Referenced by yowpdlibmain::finalizepd(), and initnbrdomains().
initnbrdomains()
subroutine, public yowexchangemodule::initnbrdomains (integer, intent(in) nConnD)
Definition at line 224 of file yowexchangeModule.F90.
     use yowerr
     implicit none
     integer, intent(in) :: nConnD
     integer :: stat
     call finalizeexchangemodule()
     nconndomains = nconnd
     allocate(neighbordomains(nconndomains), stat=stat)
     if(stat/=0)  CALL abort('neighborDomains allocation failure')
References yowerr::abort(), finalizeexchangemodule(), nconndomains, and neighbordomains.
Referenced by yowpdlibmain::findconndomains().
pdlib_exchange1dreal()
subroutine, public yowexchangemodule::pdlib_exchange1dreal (real(kind=rkind), dimension(:), intent(inout) U)
exchange values in U.
Parameters
[in,out] U array with values to exchange. np+ng long. Send values from U(1:np) to other threads. Receive values from other threads and updates U(np+1:np+ng
Note
MPI recv tag: 10000 + MPI rank
MPI send tag: 10000 + neighbor MPI rank
Definition at line 251 of file yowexchangeModule.F90.
     use yowdatapool, only: comm, myrank, rkind
     use yownodepool, only: t_node, nodes_global, np, ng, ghosts, npa
     use yowerr
     use mpi
     implicit none
     real(kind=rkind), intent(inout) :: u(:)
     integer :: i, ierr, tag
     integer :: sendRqst(nConnDomains), recvRqst(nConnDomains)
     integer :: recvStat(MPI_STATUS_SIZE, nConnDomains), sendStat(MPI_STATUS_SIZE, nConnDomains)
     character(len=140) :: errmsg
     if(size(u) /= npa) then
       WRITE(errmsg, *) 'size(U)=', size(u), ' but npa=', npa
       CALL abort(errmsg)
     endif
     ! post receives
     do i=1, nconndomains
       tag = 10000 + myrank
       call mpi_irecv(u, 1, neighbordomains(i)%p1DRrecvType, &
            neighbordomains(i)%domainID-1, tag, comm, &
            recvrqst(i), ierr)
       if(ierr/=mpi_success) then
         CALL parallel_abort("MPI_IRecv", ierr)
       endif
     enddo
     ! post sends
     do i=1, nconndomains
       tag = 10000 + (neighbordomains(i)%domainID-1)
       call mpi_isend(u, 1, neighbordomains(i)%p1DRsendType, &
            neighbordomains(i)%domainID-1, tag, comm, &
            sendrqst(i), ierr);
       if(ierr/=mpi_success) then
         CALL parallel_abort("MPI_ISend", ierr)
       endif
     end do
     ! Wait for completion
     call mpi_waitall(nconndomains, recvrqst, recvstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     call mpi_waitall(nconndomains, sendrqst, sendstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
References yowerr::abort(), yowdatapool::comm, yownodepool::ghosts(), yowdatapool::myrank, nconndomains, neighbordomains, yownodepool::ng, yownodepool::nodes_global, yownodepool::np, yownodepool::npa, yowerr::parallel_abort(), and yowdatapool::rkind.
Referenced by yowpdlibmain::computetria_ien_si_ccon(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3wavset::trig_wave_setup_apply_fct(), w3wavset::trig_wave_setup_apply_precond(), w3wavset::trig_wave_setup_computation(), and w3triamd::ug_gradients().
pdlib_exchange2dreal()
subroutine, public yowexchangemodule::pdlib_exchange2dreal (real(kind=rkind), dimension(:,:), intent(inout) U)
Definition at line 303 of file yowexchangeModule.F90.
     use yowdatapool, only: comm, myrank, rkind
     use yownodepool, only: t_node, nodes_global, np, ng, ghosts, npa
     use yowerr
     use mpi
     USE w3odatmd, only : iaproc
     implicit none
     real(kind=rkind), intent(inout) :: u(:,:)
     integer :: i, ierr, tag
     integer :: sendRqst(nConnDomains), recvRqst(nConnDomains)
     integer :: recvStat(MPI_STATUS_SIZE, nConnDomains), sendStat(MPI_STATUS_SIZE, nConnDomains)
 #ifdef W3_DEBUGEXCH
     WRITE(740+iaproc,*) 'PDLIB_exchange2Dreal, step 3'
     FLUSH(740+iaproc)
 #endif
     ! post receives
 #ifdef W3_DEBUGEXCH
     WRITE(740+iaproc,*) 'PDLIB_exchange2Dreal, step 4'
     FLUSH(740+iaproc)
 #endif
     do i=1, nconndomains
       tag = 30000 + myrank
       call mpi_irecv(u, 1, neighbordomains(i)%p2DRrecvType1, &
            neighbordomains(i)%domainID-1, tag, comm, &
            recvrqst(i), ierr)
       if(ierr/=mpi_success) then
         CALL parallel_abort("MPI_IRecv", ierr)
       endif
     enddo
 #ifdef W3_DEBUGEXCH
     WRITE(740+iaproc,*) 'PDLIB_exchange2Dreal, step 5'
     FLUSH(740+iaproc)
 #endif
     ! post sends
     do i=1, nconndomains
       tag = 30000 + (neighbordomains(i)%domainID-1)
       call mpi_isend(u, 1, neighbordomains(i)%p2DRsendType1, &
            neighbordomains(i)%domainID-1, tag, comm, &
            sendrqst(i), ierr)
       if(ierr/=mpi_success) then
         CALL parallel_abort("MPI_ISend", ierr)
       endif
     end do
 #ifdef W3_DEBUGEXCH
     WRITE(740+iaproc,*) 'PDLIB_exchange2Dreal, step 6'
     FLUSH(740+iaproc)
 #endif
     ! Wait for completion
     call mpi_waitall(nconndomains, recvrqst, recvstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
 #ifdef W3_DEBUGEXCH
     WRITE(740+iaproc,*) 'PDLIB_exchange2Dreal, step 11'
     FLUSH(740+iaproc)
 #endif
     call mpi_waitall(nconndomains, sendrqst, sendstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
 #ifdef W3_DEBUGEXCH
     WRITE(740+iaproc,*) 'PDLIB_exchange2Dreal, step 12'
     FLUSH(740+iaproc)
 #endif
References yowdatapool::comm, yownodepool::ghosts(), w3odatmd::iaproc, yowdatapool::myrank, nconndomains, neighbordomains, yownodepool::ng, yownodepool::nodes_global, yownodepool::np, yownodepool::npa, yowerr::parallel_abort(), and yowdatapool::rkind.
Referenced by pdlib_w3profsmd::pdlib_explicit_block(), and pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block().
pdlib_exchange2dreal_zero()
subroutine, public yowexchangemodule::pdlib_exchange2dreal_zero (real(kind=rkind), dimension(n2nddim,0:npa), intent(inout) U)
Note
MPI recv tag: 30001 + MPI rank
MPI send tag: 30001 + neighbor MPI rank
Definition at line 468 of file yowexchangeModule.F90.
     use yowdatapool, only: comm, myrank, rkind
     use yownodepool, only: npa
     use yowerr
     use mpi
     implicit none
     real(kind=rkind), intent(inout) :: u(n2nddim,0:npa)
     integer :: i, ierr, tag
     integer :: sendRqst(nConnDomains), recvRqst(nConnDomains)
     integer :: recvStat(MPI_STATUS_SIZE, nConnDomains), sendStat(MPI_STATUS_SIZE, nConnDomains)
     character(len=200) errstr
     ! It is impossible to add these range checks because assumed shape array start vom 1:npa+1 even if you allocate it from 0:npa
     !     if(size(U,2) /= npa+1) then
     !       write(errstr, *) "size(U,2) /= npa+1", size(U,2), "should be", npa+1
     !       ABORT(errstr)
     !     endif
     !
     !     if(ubound(U,2) /= npa) then
     !       write(errstr, *) "ubound(U,2) /= npa", ubound(U,2), "should be", npa
     !       ABORT(errstr)
     !     endif
     !
     !     if(lbound(U,2) /= 0) then
     !       write(errstr, *) "lbound(U,2) /= 0", lbound(U,2), "should be 0"
     !       ABORT(errstr)
     !     endif
     !    if((size(U,1) /= n2ndDim) ) then
     !        write(errstr, *) "size(U,1) /= n2ndDim size(U,1)=", size(U,1), " n2ndDim=", n2ndDim
     !        ABORT(errstr)
     !    endif
     ! post receives
     do i=1, nconndomains
       tag = 30001 + myrank
       call mpi_irecv(u, &
            1, &
            neighbordomains(i)%p2DRrecvType_zero, &
            neighbordomains(i)%domainID-1, &
            tag, &
            comm, &
            recvrqst(i), &
            ierr)
       if(ierr/=mpi_success) then
         CALL parallel_abort("MPI_IRecv", ierr)
       endif
     enddo
     ! post sends
     do i=1, nconndomains
       tag = 30001 + (neighbordomains(i)%domainID-1)
       call mpi_isend(u, &
            1, &
            neighbordomains(i)%p2DRsendType_zero, &
            neighbordomains(i)%domainID-1, &
            tag, &
            comm, &
            sendrqst(i), &
            ierr);
       if(ierr/=mpi_success) then
         CALL parallel_abort("MPI_ISend", ierr)
       endif
     end do
     ! Wait for completion
     call mpi_waitall(nconndomains, recvrqst, recvstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     call mpi_waitall(nconndomains, sendrqst, sendstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
References yowdatapool::comm, yowdatapool::myrank, n2nddim, nconndomains, neighbordomains, yownodepool::npa, yowerr::parallel_abort(), and yowdatapool::rkind.
Referenced by pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), wminiomd::wmioeg(), and wminiomd::wmiohg().
setdimsize()
subroutine, public yowexchangemodule::setdimsize (integer, intent(in) second)
set the size of the second and third dimension for exchange
Note
the size of the first dimension is npa
call this before initPD()
Definition at line 375 of file yowexchangeModule.F90.
     implicit none
     integer, intent(in) :: second
     n2nddim = second
References n2nddim.
Referenced by yowpdlibmain::initfromgriddim().
Variable Documentation
n2nddim
integer, public yowexchangemodule::n2nddim = 1
number of the second dimension for exchange
Definition at line 108 of file yowexchangeModule.F90.
   integer, public :: n2ndDim = 1
Referenced by creatempitype(), pdlib_exchange2dreal_zero(), and setdimsize().
nconndomains
integer, public yowexchangemodule::nconndomains = 0
Number of neighbor domains.
Definition at line 105 of file yowexchangeModule.F90.
   integer, public :: nConnDomains = 0
Referenced by creatempitypes(), yowpdlibmain::exchangeghostids(), finalizeexchangemodule(), yowpdlibmain::initfromgriddim(), initnbrdomains(), pdlib_exchange1dreal(), pdlib_exchange2dreal(), and pdlib_exchange2dreal_zero().
neighbordomains
type(t_neighbordomain), dimension(:), allocatable, public yowexchangemodule::neighbordomains
Knows for all domains neighbors, which node we must send or revc from neighbor domains from 1 to nConnDomains.
Definition at line 102 of file yowexchangeModule.F90.
   type(t_neighborDomain), public, allocatable :: neighborDomains(:)
Referenced by creatempitypes(), yowpdlibmain::exchangeghostids(), finalizeexchangemodule(), yowpdlibmain::findconndomains(), initnbrdomains(), pdlib_exchange1dreal(), pdlib_exchange2dreal(), and pdlib_exchange2dreal_zero().
nnthdim
integer, public yowexchangemodule::nnthdim = 1
number of the second dimension for exchange (nth only for wave model)
Definition at line 111 of file yowexchangeModule.F90.
   integer, public :: nnthDim = 1