WAVEWATCH III: yowrankmodule Module Reference
yowrankmodule Module Reference
Provides access to some information of all threads e.g.
Data Types
type t_rank
Functions/Subroutines
subroutine, public initrankmodule ()
allocate and exchange
subroutine exchangeiplg ()
send iplg from this thread to every neighbor thread
subroutine calcistart ()
subroutine, public finalizerankmodule ()
Variables
type(t_rank), dimension(:), allocatable, public rank
Provides access to some information of all threads e.g.
integer, dimension(:), allocatable, public ipgl_to_proc
integer, dimension(:), allocatable, public ipgl_tot
integer, dimension(:), allocatable, public ipgl_npa
Detailed Description
Provides access to some information of all threads e.g.
iplg
Function/Subroutine Documentation
calcistart()
subroutine yowrankmodule::calcistart
Definition at line 238 of file yowrankModule.F90.
     use yowdatapool, only: ntasks, myrank
     implicit none
     integer :: ir
     rank(1)%IStart = 1
     do ir=2, ntasks
       rank(ir)%IStart = rank(ir-1)%IStart + rank(ir-1)%np
     end do
References yowdatapool::myrank, yowdatapool::ntasks, and rank.
Referenced by initrankmodule().
exchangeiplg()
subroutine yowrankmodule::exchangeiplg
send iplg from this thread to every neighbor thread
Definition at line 91 of file yowrankModule.F90.
     use yownodepool, only: np, npa, iplg, np_global
     use yowdatapool, only: ntasks, myrank, comm, itype
     use mpi
     implicit none
     integer :: i, ierr, stat
     integer :: sendRqst(nTasks), recvRqst(nTasks)
     integer :: recvStat(MPI_STATUS_SIZE, nTasks), sendStat(MPI_STATUS_SIZE, nTasks)
     integer IPglob, J, istat
     ! step1 exchange np
     ! step2 exchange npa
     ! step3 allocate rank%iplg
     ! step4 exchange iplg
     ! step1 exchange np
     ! post receives
     do i=1, ntasks
       if(i /= myrank+1) then
         call mpi_irecv(rank(i)%np, 1, itype, i-1, &
              42, comm, recvrqst(i), ierr)
         if(ierr/=mpi_success) then
           CALL parallel_abort("MPI_IRecv", ierr)
         endif
       else
         recvrqst(i) = mpi_request_null
       endif
     end do
     ! post sends
     do i=1, ntasks
       if(i /= myrank+1) then
         call mpi_isend(np, 1, itype, i-1, &
              42, comm, sendrqst(i), ierr)
         if(ierr/=mpi_success) then
           CALL parallel_abort("MPI_ISend", ierr)
         endif
       else
         sendrqst(i) = mpi_request_null
       endif
     end do
     rank(myrank+1)%np = np
     ! Wait for completion
     call mpi_waitall(ntasks, recvrqst, recvstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     call mpi_waitall(ntasks, sendrqst, sendstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     ! step2 exchange npa
     ! post receives
     do i=1, ntasks
       if(i /= myrank+1) then
         call mpi_irecv(rank(i)%npa, 1, itype, i-1, &
              42, comm, recvrqst(i), ierr)
         if(ierr/=mpi_success) then
           CALL parallel_abort("MPI_IRecv", ierr)
         endif
       else
         recvrqst(i) = mpi_request_null
       endif
     end do
     ! post sends
     do i=1, ntasks
       if(i /= myrank+1) then
         call mpi_isend(npa, 1, itype, i-1, &
              42, comm, sendrqst(i), ierr)
         if(ierr/=mpi_success) then
           CALL parallel_abort("MPI_ISend", ierr)
         endif
       else
         sendrqst(i) = mpi_request_null
       endif
     end do
     rank(myrank+1)%npa = npa
     ! Wait for completion
     call mpi_waitall(ntasks, recvrqst, recvstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     call mpi_waitall(ntasks, sendrqst, sendstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     ! step3 allocal rank%iplg
     do i=1, ntasks
       if(allocated(rank(i)%iplg)) deallocate(rank(i)%iplg)
       allocate(rank(i)%iplg(rank(i)%npa), stat=stat)
       if(stat/=0) CALL abort('rank%iplg allocation failure')
       rank(i)%iplg = 0
     end do
     ! step4 exchange iplg
     ! post receives
     do i=1, ntasks
       if(i /= myrank+1) then
         call mpi_irecv(rank(i)%iplg, rank(i)%npa, itype, i-1, &
              42, comm, recvrqst(i), ierr)
         if(ierr/=mpi_success) then
           CALL parallel_abort("MPI_IRecv", ierr)
         endif
       else
         recvrqst(i) = mpi_request_null
       endif
     end do
     ! post sends
     do i=1, ntasks
       if(i /= myrank+1) then
         call mpi_isend(iplg, npa, itype, i-1, &
              42, comm, sendrqst(i), ierr)
         if(ierr/=mpi_success) then
           CALL parallel_abort("MPI_ISend", ierr)
         endif
       else
         sendrqst(i) = mpi_request_null
       endif
     end do
     rank(myrank+1)%iplg = iplg
     ! Wait for completion
     call mpi_waitall(ntasks, recvrqst, recvstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     call mpi_waitall(ntasks, sendrqst, sendstat,ierr)
     if(ierr/=mpi_success) CALL parallel_abort("waitall", ierr)
     allocate(ipgl_to_proc(np_global), ipgl_tot(np_global), stat=istat)
     if(istat /= 0) CALL parallel_abort("allocatation error", 1)
     do i=1,ntasks
       DO j=1,rank(i)%np
         ipglob=rank(i)%iplg(j)
         ipgl_to_proc(ipglob)=i
         ipgl_tot(ipglob)=j
       END DO
     END DO
     allocate(ipgl_npa(np_global), stat=istat)
     if(istat /= 0) CALL parallel_abort("allocatation error b", 1)
     ipgl_npa=0
     DO j=1,rank(myrank+1)%npa
       ipglob=rank(myrank+1)%iplg(j)
       ipgl_npa(ipglob)=j
     END DO
References yowerr::abort(), yowdatapool::comm, ipgl_npa, ipgl_to_proc, ipgl_tot, yownodepool::iplg, yowdatapool::itype, yowdatapool::myrank, yownodepool::np, yownodepool::np_global, yownodepool::npa, yowdatapool::ntasks, yowerr::parallel_abort(), and rank.
Referenced by initrankmodule().
finalizerankmodule()
subroutine, public yowrankmodule::finalizerankmodule
Definition at line 249 of file yowrankModule.F90.
     implicit none
     integer :: i
     if(allocated(rank)) then
       do i=1, size(rank)
         if(allocated(rank(i)%iplg)) deallocate(rank(i)%iplg)
       end do
       deallocate(rank)
     endif
References rank.
Referenced by yowpdlibmain::finalizepd().
initrankmodule()
subroutine, public yowrankmodule::initrankmodule
allocate and exchange
Definition at line 76 of file yowrankModule.F90.
     use yowdatapool, only: ntasks, myrank
     implicit none
     integer :: stat
     if(allocated(rank)) deallocate(rank)
     allocate(rank(ntasks), stat=stat)
     if(stat/=0) CALL abort('rank allocation failure')
     call exchangeiplg()
     call calcistart()
References yowerr::abort(), calcistart(), exchangeiplg(), yowdatapool::myrank, yowdatapool::ntasks, and rank.
Referenced by yowpdlibmain::initfromgriddim().
Variable Documentation
ipgl_npa
integer, dimension(:), allocatable, public yowrankmodule::ipgl_npa
Definition at line 70 of file yowrankModule.F90.
   integer, public, allocatable :: ipgl_npa(:)
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), exchangeiplg(), w3parall::get_jsea_ibelong(), yowpdlibmain::initfromgriddim(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), and pdlib_w3profsmd::pdlib_w3xypfspsi2().
ipgl_to_proc
integer, dimension(:), allocatable, public yowrankmodule::ipgl_to_proc
Definition at line 69 of file yowrankModule.F90.
   integer, public, allocatable :: IPGL_TO_PROC(:), ipgl_tot(:)
Referenced by exchangeiplg(), w3parall::get_jsea_ibelong(), w3parall::init_get_jsea_isproc(), and w3parall::synchronize_ipgl_etc_array().
ipgl_tot
integer, dimension(:), allocatable, public yowrankmodule::ipgl_tot
Definition at line 69 of file yowrankModule.F90.
Referenced by exchangeiplg(), w3parall::get_jsea_ibelong(), w3parall::init_get_jsea_isproc(), and w3parall::synchronize_ipgl_etc_array().
rank
type(t_rank), dimension(:), allocatable, public yowrankmodule::rank
Provides access to some information of all threads e.g.
iplg
Note
range [1:nTasks]
range[myrank] are filled with the values from this rank
Definition at line 68 of file yowrankModule.F90.
   type(t_rank),public, allocatable :: rank(:)
Referenced by calcistart(), exchangeiplg(), finalizerankmodule(), initrankmodule(), w3parall::set_up_nseal_nsealm(), wmesmfmd::setupimpbmsk(), w3wdatmd::w3dimw(), and w3initmd::w3init().