WAVEWATCH III: yowelementpool Module Reference
yowelementpool Module Reference
Functions/Subroutines
logical function, public belongto (ele_in, rank)
Returns true if the element belongs to rank.
subroutine, public finalizeelementpool ()
Variables
integer, public ne_global = 0
number of elements, global
integer, public ne = 0
number of local elements
integer, dimension(:,:), allocatable, target, public ine
number of elements of the augmented domain
integer, dimension(:), allocatable, target, public ielg
global element array.
Function/Subroutine Documentation
belongto()
logical function, public yowelementpool::belongto (integer, dimension(3), intent(in) ele_in, integer, intent(in), optional rank)
Returns true if the element belongs to rank.
conversione: If a element is connected to domain 1,2 and 3. It belongs to 1,2 and 3.
Parameters
[in] rank optional. If not given, datapool:myrank is used
Definition at line 74 of file yowelementpool.F90.
     use yowdatapool, only: myrank, ntasks
     use yownodepool, only: t_node, nodes_global
     implicit none
     integer, intent(in) :: ele_in(3)
     integer, intent(in), optional :: rank
     logical :: belongTo
     integer :: myDomainID
     integer :: nodes(3)
     integer J
     if(present(rank) .eqv. .true.) then
       mydomainid = rank +1
     else
       mydomainid = myrank + 1
     endif
     ! check if this element adjoint to three different domains.
     belongto = .false.
     DO j=1,3
       IF (nodes_global(ele_in(j)) % domainID == mydomainid) THEN
         belongto = .true.
       END IF
     END DO
References yowdatapool::myrank, yownodepool::nodes_global, and yowdatapool::ntasks.
Referenced by yowpdlibmain::postpartition2().
finalizeelementpool()
subroutine, public yowelementpool::finalizeelementpool
Definition at line 102 of file yowelementpool.F90.
     implicit none
     if(allocated(ine))        deallocate(ine)
     !if(allocated(INE_global)) deallocate(INE_global)
     if(allocated(ielg))       deallocate(ielg)
References ielg, and ine.
Referenced by yowpdlibmain::finalizepd().
Variable Documentation
ielg
integer, dimension(:), allocatable, target, public yowelementpool::ielg
global element array.
it stored the global node IDs first index from 1 to 3. second index from 1 to ne_global Element local to global mapping ne long. give the global element id
Definition at line 65 of file yowelementpool.F90.
   integer, public, target, allocatable :: ielg(:)
Referenced by yowpdlibmain::computetria_ien_si_ccon(), wmesmfmd::createexpmesh(), yowpdlibmain::element_crosses_dateline(), finalizeelementpool(), yowpdlibmain::postpartition2(), and w3triamd::ug_gradients().
ine
integer, dimension(:,:), allocatable, target, public yowelementpool::ine
number of elements of the augmented domain
local element array. it stores the local node IDs first index from 1 to 3. second index from 1 to ne. local node IDs in [1:np]. local ghost IDs in [np+1:np+ng]
Definition at line 56 of file yowelementpool.F90.
   integer, public, target, allocatable :: INE(:,:)
Referenced by pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::computetria_ien_si_ccon(), wmesmfmd::createexpmesh(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), yowpdlibmain::element_crosses_dateline(), finalizeelementpool(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), yowpdlibmain::postpartition2(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3wavset::trig_compute_diff(), w3wavset::trig_wave_setup_compute_system(), and w3triamd::ug_gradients().
ne
integer, public yowelementpool::ne = 0
number of local elements
Definition at line 48 of file yowelementpool.F90.
   integer, public :: ne = 0
Referenced by pdlib_w3profsmd::block_solver_explicit_init(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), yowpdlibmain::computetria_ien_si_ccon(), wmesmfmd::createexpmesh(), w3wavset::differentiate_xydir_mapsta(), w3wavset::differentiate_xydir_native(), yowpdlibmain::element_crosses_dateline(), yowpdlibmain::initfromgriddim(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), yowpdlibmain::postpartition2(), yowpdlibmain::runparmetis(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3wavset::trig_wave_setup_compute_system(), and w3triamd::ug_gradients().
ne_global
integer, public yowelementpool::ne_global = 0
number of elements, global
Definition at line 45 of file yowelementpool.F90.
   integer, public :: ne_global = 0
Referenced by yowpdlibmain::assignmesh(), yowpdlibmain::computetria_ien_si_ccon(), yowpdlibmain::element_crosses_dateline(), yowpdlibmain::findconnnodes(), w3triamd::get_boundary_status(), yowpdlibmain::initfromgriddim(), yowpdlibmain::postpartition2(), and yowpdlibmain::runparmetis().