WAVEWATCH III: w3nmlboundmd Module Reference
w3nmlboundmd Module Reference
Data Types
type nml_bound_t
Functions/Subroutines
subroutine w3nmlbound (NDSI, INFILE, NML_BOUND, IERR)
subroutine read_bound_nml (NDSI, NML_BOUND)
subroutine report_bound_nml (NML_BOUND)
Variables
character(256) msg
report message
integer ndsn
namelist file unit
Function/Subroutine Documentation
read_bound_nml()
subroutine w3nmlboundmd::read_bound_nml (integer, intent(in) NDSI, type(nml_bound_t), intent(inout) NML_BOUND)
Parameters
[in] ndsi namelist file unit
[in,out] nml_bound bound structure
Definition at line 154 of file w3nmlboundmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         27-May-2021 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI         Int.
     !      NML_BOUND    Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLBOUND Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
     !/S      USE W3SERVMD, ONLY: STRACE
     IMPLICIT NONE
     INTEGER, INTENT(IN)                 :: NDSI
     TYPE(NML_BOUND_T), INTENT(INOUT)    :: NML_BOUND
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_BOUND_T) :: BOUND
     namelist /bound_nml/ bound
     !/S      INTEGER, SAVE                           :: IENT = 0       !< strace error code
     ierr = 0
     !/S      CALL STRACE (IENT, 'READ_BOUND_NML')
     ! set default values for track structure
     bound%MODE       = 'WRITE'
     bound%INTERP     = 2
     bound%VERBOSE    = 1
     bound%FILE       = 'spec.list'
     ! read bound namelist
     rewind(ndsi)
     READ (ndsi, nml=bound_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_BOUND_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (1)
     END IF
     ! save namelist
     nml_bound = bound
References w3servmd::extcde(), msg, and w3odatmd::ndse.
Referenced by w3nmlbound().
report_bound_nml()
subroutine w3nmlboundmd::report_bound_nml (type(nml_bound_t), intent(in) NML_BOUND)
Parameters
[in] nml_bound bound structure
Definition at line 259 of file w3nmlboundmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         27-May-2021 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_BOUND  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLBOUND Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/S      USE W3SERVMD, ONLY: STRACE
     IMPLICIT NONE
     TYPE(NML_BOUND_T), INTENT(IN) :: NML_BOUND
     !/S      INTEGER, SAVE                           :: IENT = 0            ! strace error code
     !/S      CALL STRACE (IENT, 'REPORT_BOUND_NML')
     WRITE (msg,'(A)') 'BOUND % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,10) trim(msg),'MODE       = ', trim(nml_bound%MODE)
     WRITE (ndsn,11) trim(msg),'INTERP     = ', nml_bound%INTERP
     WRITE (ndsn,11) trim(msg),'VERBOSE    = ', nml_bound%VERBOSE
     WRITE (ndsn,10) trim(msg),'FILE       = ', trim(nml_bound%FILE)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
References msg, and ndsn.
Referenced by w3nmlbound().
w3nmlbound()
subroutine w3nmlboundmd::w3nmlbound (integer, intent(in) NDSI, character*(*), intent(in) INFILE, type(nml_bound_t), intent(inout) NML_BOUND, integer, intent(out) IERR)
Parameters
[in] ndsi input file unit
[in] infile input file name
[in,out] nml_bound bound structure
[out] ierr error code
Definition at line 45 of file w3nmlboundmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         27-May-2021 |
     !/                  +-----------------------------------+
     !/
     !
     !  1. Purpose :
     !
     !     Reads all the namelist to define the input boundary
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI        Int.
     !      INFILE      Char.
     !      NML_BOUND   type.
     !      IERR        Int.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !      READ_BOUND_NML
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      WW3_BOUND  Prog.   N/A    Preprocess input boundaries.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     !/S      USE W3SERVMD, ONLY: STRACE
     IMPLICIT NONE
     INTEGER, INTENT(IN)                         :: NDSI
     CHARACTER*(*), INTENT(IN)                   :: INFILE
     TYPE(NML_BOUND_T), INTENT(INOUT)            :: NML_BOUND
     INTEGER, INTENT(OUT)                        :: IERR
     !/S      INTEGER, SAVE                             :: IENT = 0   !< strace error code
     ierr = 0
     !/S      CALL STRACE (IENT, 'W3NMLBOUND')
     ! open namelist log file
     ndsn = 3
     OPEN (ndsn, file=trim(infile)//'.log', form='formatted', iostat=ierr)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A)') 'ERROR: open full nml file '//trim(infile)//'.log failed'
       RETURN
     END IF
     ! open input file
     OPEN (ndsi, file=trim(infile), form='formatted', status='old', iostat=ierr)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A)') 'ERROR: open input file '//trim(infile)//' failed'
       RETURN
     END IF
     ! read bound namelist
     CALL read_bound_nml (ndsi, nml_bound)
     CALL report_bound_nml (nml_bound)
     ! close namelist files
     CLOSE (ndsi)
     CLOSE (ndsn)
References file(), w3odatmd::ndse, ndsn, read_bound_nml(), and report_bound_nml().
Referenced by w3bound().
Variable Documentation
msg
character(256) w3nmlboundmd::msg
report message
Definition at line 36 of file w3nmlboundmd.F90.
   CHARACTER(256)                :: MSG
Referenced by read_bound_nml(), and report_bound_nml().
ndsn
integer w3nmlboundmd::ndsn
namelist file unit
Definition at line 37 of file w3nmlboundmd.F90.
   INTEGER                       :: NDSN
Referenced by report_bound_nml(), and w3nmlbound().