WAVEWATCH III: w3sic5md Module Reference
w3sic5md Module Reference
Calculate ice source term S_{ice} according to different ice models:
Functions/Subroutines
subroutine, public w3sic5 (A, DEPTH, CG, WN, IX, IY, S, D)
Calculate ice source term S_{ice} according to 3 different sea ice models.
subroutine, public w3ic5wncg (WN_R, WN_I, CG, HICE, IVISC, RHOI, ISMODG, HWAT)
Calculation of complex wavenumber arrays for ice-coupled waves.
subroutine, public fsdisp (HICE, IVISC, RHOI, ISMODG, HWAT, WT, WNR, WNI)
Calculate the complex wavenumber for waves in ice according to three different sea ice models.
Detailed Description
Calculate ice source term S_{ice} according to different ice models:
Author
Q. Liu
E. Rogers
Date
19-May-2021
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
fsdisp()
subroutine, public w3sic5md::fsdisp (real, intent(in) HICE, real, intent(in) IVISC, real, intent(in) RHOI, real, intent(in) ISMODG, real, intent(in) HWAT, real, intent(in) WT, real, intent(out) WNR, real, intent(out) WNI)
Calculate the complex wavenumber for waves in ice according to three different sea ice models.
Parameters
[in] HICE Thickness of ice (m).
[in] IVISC Viscosity parameter of ice (m^2 s^{-1}).
[in] RHOI The density of ice (kg m^{-3}).
[in] ISMODG Effecitive shear modulus G of ice (Pa).
[in] HWAT Water depth.
[in] WT Wave period (s; 1/freq).
[out] WNR The real part of the wave number.
[out] WNI The imaginary part of the wave number.
Author
Q. Liu
Date
19-May-2021
Definition at line 653 of file w3sic5md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           Q. Liu                  |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         19-May-2021 |
     !/                  +-----------------------------------+
     !/
     !/    17-Mar-2016 : Origination                         ( version 5.10)
     !/                                                      ( Q. Liu)
     !/    17-Mar-2016 : Start from the Matlab code `FoxSquire.m` (provided
     !/                  by Prof. Vernon Squire from University of Otago)
     !/                                                      ( Q. Liu)
     !/    25-Apr-2017 : Add more filters                    ( Q. Liu)
     !/
     !/    19-May-2021 : Incl. RP and M2 ice models          ( Q. Liu)
     !/
     !  1. Purpose :
     !
     !     Calculate the complex wavenumber for waves in ice according to
     !     three different sea ice models, i.e., FS, RP and M2 (see Liu et
     !     al. 2020)
     !
     !  2. Method :
     !     Mainly solving the dispersion relations of FS and RP models (
     !     Eqs. (20, 24, 25)) in Mosig et al. (2015))
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     Name     Type   Intent   Description
     !     ----------------------------------------------------------------
     !     HICE     Real.  IN       thickness of ice (m)
     !     IVISC    Real.  IN       viscosity parameter of ice (m^2 s^{-1})
     !     RHOI     Real.  IN       the density of ice (kg m^{-3})
     !     ISMODG   Real.  IN       effecitive shear modulus G of ice (Pa)
     !     HWAT     Real.  IN       water depth
     !     WT       Real.  IN       wave period (s; 1/freq)
     !     WNR      Real.  Out      the real. part of the wave number
     !     WNI      Real.  Out      the imag. part of the wave number
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      POLYROOTS Subr. /        Find the roots of a general polynomial
     !      NR_ROOT   Func. /        Newton-Raphson root finding
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IC5WNCG Subr. /        Wavenumber and group velocity of ice-
     !                               coupled waves
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     See Format 1000, 1001, 1002
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     USE constants, ONLY: grav, tpi
     USE w3dispmd,  ONLY: wavnu1
     USE w3servmd,  ONLY: extcde
     USE w3odatmd,  ONLY: ndse, iaproc, naproc, naperr
     USE w3gdatmd,  ONLY: ic5pars
     USE w3gsrumd,  ONLY: w3inan
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     REAL, INTENT(IN)      :: HICE, IVISC, RHOI, ISMODG, HWAT, WT
     REAL, INTENT(OUT)     :: WNR, WNI
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !
     REAL                  :: IC5MINIG, IC5MINWT, IC5MAXKRATIO, &
          IC5MAXKI, IC5MINHW, IC5VEMOD
     REAL                  :: TISMODG, TWT, TRATIO, THW
     REAL, PARAMETER       :: NU = 0.3, rhow = 1025.
     !     COMPLEX               :: GV, C1
     !     REAL                  :: SIGMA, C2, WNO, CGO, THKH,  &
     COMPLEX               :: GV, C1, C2
     REAL                  :: SIGMA, WNO, CGO, THKH,  &
          RTRL(5), RTIM(5), RTANG(5)
     INTEGER               :: IREAL
     !     COMPLEX(KDPC)         :: GUESS, CROOT, C1D
     !     REAL(KDP)             :: C2D, HWATD
     COMPLEX(KDPC)         :: GUESS, CROOT, C1D, C2D
     REAL(KDP)             :: HWATD
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'FSDISP')
 #endif
     ! Note, same as W3IC3WNCG_xx in w3sic3md :
     !     HICE   →   ICE1
     !     IVISC  →   ICE2
     !     RHOI   →   ICE3
     !     ISMODG →   ICE4
     ! 0.  Initializations ------------------------------------------------ *
     ! Set limiters
     !
     ! When G = 0, the FS method does not provide a solution. It is not
     ! unexpected because the FS model is originally devised as a
     ! thin elastic plate model in which elasticity is necessary.
     !
     ! The FS algorithm may also have issues for very short wave periods,
     ! shallow waters and low G (e.g., T~3 s, d~10 m, hi~0.5 m, G<10^6 Pa)
     !
     ic5minig     = ic5pars(1) ! Minimum G
     ic5minwt     = ic5pars(2) ! Minimum T
     ic5maxkratio = ic5pars(3) ! Maximum k_{ow}/k_r
     ic5maxki     = ic5pars(4) ! Maximum k_i
     ic5minhw     = ic5pars(5) ! Minimum d
     ic5vemod     = ic5pars(9) ! Model selected 1: EFS, 2: RP, 3: M2
     !
     tismodg  = max(ic5minig, ismodg)
     twt      = max(ic5minwt, wt)
     thw      = max(ic5minhw, hwat)
     !
     ! G <= 0. is not allowed
     IF (abs(tismodg) < errtol) THEN
       IF ( iaproc .EQ. naperr ) WRITE(ndse, 1000) 'FSDISP'
       CALL extcde(1)
     END IF
     !
     ! σ = 2π / T
     sigma = tpi / twt
     !
     IF (abs(ic5vemod - 1.) < errtol) THEN
       ! Complex shear modulus Gv = G - i σ ρ η (EFS model)
       gv = cmplx(tismodg, -1. * sigma * rhoi * ivisc)
       !
       ! -------------------------------------------------------------------- *
       ! Note that Eq. (24) in Mosig et al. (2015) can be written like below:
       ! (c1 * k^5 + c2 * k) * tanh(HWAT*k) - 1 = 0
       ! Most Important part of this module --------------------------------- *
       c1 = gv * hice**3. / (6. * rhow * sigma**2.)
       !
       ! To be divided by (1-NU) or multiplied by (1+NU) ??
       ! Beam model: then multiplied by (1+ν)
       ! Plate model: then divided by (1-ν)
       ! The beam version is more theoretically (J.E.M. Mosig, personal
       ! communication, 2016), although there is only very marginal difference
       ! between this two version as (1+NU = 1.3 and 1/(1-NU) ~ 1.4)
       c1 = c1 * (1+nu)
       !         C1 = C1 / (1-NU)
       !
       ! C2
       !         C2 = GRAV / SIGMA**2. - RHOI * HICE / RHOW
       c2 = cmplx(grav / sigma**2. - rhoi * hice / rhow, 0.)
       !
     ELSE IF (abs(ic5vemod - 2.) < errtol) THEN
       ! See Appendix of Liu et al. (2020) - RP model
       c1 = cmplx(tismodg * hice**3. * (1+nu) / (6. * rhow * sigma**2.), 0.)
       c2 = cmplx(grav/sigma**2. - rhoi * hice / rhow,              &
            -1. * ivisc / (rhow * sigma))
       !
     ELSE IF (abs(ic5vemod - 3.) > errtol) THEN
       WRITE(ndse, 1003) 'FSDISP', ic5vemod
       CALL extcde(4)
     END IF
     ! Use the dispersion in open water to get an approximation of
     ! tanh(HWAT * k). We can also roughly use the dispersion in deep
     ! water case, that is tanh(HWAT*k) ~ 1.
     ! Wavenumber in the open water
     !     WAVNU1(SI, H, K, CG)
     CALL wavnu1(sigma, thw, wno, cgo)
     thkh = tanh(wno * thw)
     !
     IF (abs(ic5vemod - 1.) < errtol .OR. abs(ic5vemod - 2.) < errtol) THEN
       ! Get the first guess of the complex wavenumber
       CALL polyroots(6, &
            (/real(real(c1))*thkh, 0., 0., 0., real(real(c2))*thkh, -1./),&
            rtrl, rtim)
       rtang = atan2(rtim, rtrl)
       !
       ! There should only be one real root in RTRL + i * RTIM because in
       ! this case (ivisc=0) the original viscoelastic-type model reduced to
       ! the thin elastic plate model which has only one real solution.
       ! Find its index ...
       !
       ireal = minloc(abs(rtang), dim=1)
       IF (rtrl(ireal) <= 0. .OR. abs(rtim(ireal)) > errtol) THEN
         IF ( iaproc .EQ. naperr ) WRITE(ndse, 1001) 'FSDISP'
         CALL extcde(2)
       END IF
       !
       ! Get the first guess for iteration
       guess = rtrl(ireal) * exp(cmplx(0., 1e-6))
       !
       ! Newton-Raphson method
       ! Turn c1, c2, hwat to be double
       c1d = c1; c2d = c2; hwatd = thw
       croot = nr_root(c1d, c2d, hwatd, guess)
       wnr = real(real(croot))
       wni = real(aimag(croot))
       !
     ELSE IF (abs(ic5vemod - 3.) < errtol) THEN ! M2
       ! Model with Order 3 Power Law (section 6.2 in Meylan et al. (2018, JGR-Ocean))
       ! Based on my understanding, the wavelength does not change because
       ! the elasticity is not considered in this model
       wnr = wno ! Open-water wavenumber
       ! Eq. (53) in Meylan et al. (2018)
       wni = hice * ivisc * sigma**3. / (rhow * grav**2.)
     END IF
     !
     ! RATIO Check
     ! Using the ratio k0 / kr as a basic check for the reliability of
     ! FSDISP. The FS dispersion relation can give a very different kr from
     ! k0, especially for small wave periods (k0/kr is as high as 100).
     ! From my tests, using IC5MAXKRATIO = 1000. can basically detect most
     ! spurious solutions (although not all of them)
     !
     ! ISNAN Check
     ! Common ways used are:
     ! NAN = SQRT(-1.) or
     ! a /= a then a is NaN or
     ! ISNAN func (supported by gfortran & ifort)
     !        --- ISNAN -> W3INAN because ISNAN is not supported by pgi
     ! For very few cases, we can get nan | negative ki | kr
     !
     ! (N.B.) NaN problem solved by using CMPLX_TANH2
     !
     tratio = wno / wnr
     IF (w3inan(wnr) .OR. w3inan(wni) .OR. wnr <= 0 .OR. wni <= 0. &
          .OR. tratio >= ic5maxkratio) THEN
       IF ( iaproc .EQ. naperr )                       &
            WRITE(ndse, 1002) 'FSDISP', hice, ivisc, tismodg, hwat, twt, &
            wno, wnr, wni
       CALL extcde(3)
     END IF
     !
     ! Filter high ki
     wni = min(ic5maxki, wni)
     !
     ! FORMAT
 1000 FORMAT(/' *** WAVEWATCH III ERROR IN W3SIC5MD : '/   &
          '     Subr. ', a, ': Zero shear modulus G is not allowed&
          & in the FS viscoelastic model'/)
     !
 1001 FORMAT(/' *** WAVEWATCH III ERROR IN W3SIC5MD : '/   &
          '     Subr. ', a, ': get a bad first guess'/)
     !
 1002 FORMAT(/' *** WAVEWATCH III ERROR IN W3SIC5MD : '/   &
          ' -----------------------------------------------------'/&
          '     Subr. ', a,'   : get NaN/NeG/Huge kr or ki for'   /&
          ' -----------------------------------------------------'/&
          '  Ice thickness     : ', f9.1, ' m'/         &
          '  Ice viscosity     : ', e9.2, ' m2/s'/      &
          '  Ice shear modulus : ', e9.2, ' Pa' /       &
          '  Water depth       : ', f9.1, ' m'/         &
          '  Wave period       : ', f10.2, ' s'/        &
          '  Wave number (Ko)  : ', f11.3, ' rad/m'/    &
          '  Wave number (Kr)  : ', f11.3, ' rad/m'/    &
          '  Attenu. Rate (Ki) : ', e9.2, ' /m'/)
     !
 1003 FORMAT(/' *** WAVEWATCH III ERROR IN W3SIC5MD : '/   &
          '     Subr. ', a, ': Unknown VE model (', f5.0, ')'/)
     !/
     !/ End of FSDISP ----------------------------------------------------- /
     !/
References w3servmd::extcde(), constants::grav, w3odatmd::iaproc, w3gdatmd::ic5pars, w3odatmd::naperr, w3odatmd::naproc, w3odatmd::ndse, w3servmd::strace(), constants::tpi, and w3dispmd::wavnu1().
Referenced by w3ic5wncg().
w3ic5wncg()
subroutine, public w3sic5md::w3ic5wncg (real, dimension(:), intent(inout) WN_R, real, dimension(:), intent(inout) WN_I, real, dimension(:), intent(in) CG, real, intent(in) HICE, real, intent(in) IVISC, real, intent(in) RHOI, real, intent(in) ISMODG, real, intent(in) HWAT)
Calculation of complex wavenumber arrays for ice-coupled waves.
Using the Fox-Squire dispersion relations to get (kr, ki) and then get cg by cg = dσ / dk (here dk uses kr).
Parameters
[in,out] WN_R The real part of the wave number.
[in,out] WN_I The imaginary part of the wave number.
[in,out] CG Group velocity (m s^{-1}).
[in,out] HICE Thickness of ice (m).
[in,out] IVISC Viscosity parameter of ice (m^2 s^{-1}).
[in,out] RHOI The density of ice (kg m^{-3}).
[in,out] ISMODG Effecitive shear modulus G of ice (Pa).
[in,out] HWAT Water depth.
Author
Q. Liu
E. Rogers
Date
25-Apr-2017
Definition at line 495 of file w3sic5md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           Q. Liu                  |
     !/                  |           E. Rogers               |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         25-Apr-2017 |
     !/                  +-----------------------------------+
     !/
     !/    17-Apr-2016 : Origination                         ( version 5.10)
     !/                                                      ( Q. Liu )
     !/    17-Apr-2016 : Start from W3IC3WNCG_CHENG          ( Q. Liu )
     !/
     !/ 1. Purpose:
     !     Calculation of complex wavenumber arrays for ice-coupled waves.
     !
     !     This also allows us to use Cg_ice in the advection part of the
     !     radiative transfer energy equation (RTE). --- abandoned in the end
     !
     !  2. Method:
     !     Using the  Fox-Squire dispersion relations to get (kr, ki) and
     !     then get cg by cg = dσ / dk (here dk uses kr)
     !
     !  3. Parameters:
     !
     !     Parameter list:
     !     ----------------------------------------------------------------
     !     Name     Type   Intent   Description
     !     ----------------------------------------------------------------
     !     WN_R     R.A.   I/O      the real. part of the wave number
     !     WN_I     R.A.   I/O      the imag. part of the wave number
     !     CG       R.A.   I        group velocity (m s^{-1})
     !     HICE     Real.  I        thickness of ice (m)
     !     IVISC    Real.  I        viscosity parameter of ice (m^2 s^{-1})
     !     RHOI     Real.  I        the density of ice (kg m^{-3})
     !     ISMODG   Real.  I        effecitive shear modulus G of ice (Pa)
     !     HWAT     Real.  I        water depth
     !     ----------------------------------------------------------------
     !     * the intent of WN_R/I must be inout
     !     * CG is unchanged but still kept here because some legacy reasons.
     !
     !  4. Subroutines used:
     !
     !     Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     FSDISP    Subr. /        dispersion relations for ice-coupled waves
     !     CGINICE5  Subr. /        group velocity for given (σ, kr) array
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     W3SIC5    Subr. Public   Ice source term
     !     W3WAVE    Subr. W3WAVEMD WW3 integration
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     USE constants, ONLY: tpi
     USE w3gdatmd,  ONLY: nk, sig
     USE w3odatmd,  ONLY: ndse, iaproc, naproc, naperr
     USE w3servmd,  ONLY: extcde
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     REAL, INTENT(INOUT)   :: WN_R(:), WN_I(:)
     REAL, INTENT(IN)      :: CG(:)
     REAL, INTENT(IN)      :: HICE, IVISC, RHOI, ISMODG, HWAT
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     REAL, ALLOCATABLE     :: SIGMA(:)
     INTEGER               :: KL, KU, IK
     REAL                  :: TWN_R, TWN_I
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3IC5WNCG')
 #endif
     !/
     ! Initialize SIGMA {in w3gdatmd: SIG (0: NK+1)}
     IF (ALLOCATED(sigma)) DEALLOCATE(sigma); ALLOCATE(sigma(SIZE(cg)))
     sigma = 0.
     IF (SIZE(wn_r, 1) .EQ. nk) THEN
       kl    = 1
       ku    = nk
       sigma = sig(1:nk)
     ELSE IF (SIZE(wn_r,1) .EQ. nk+2) THEN
       kl    = 1
       ku    = nk+2
       sigma = sig(0:nk+1)
     ELSE
       IF ( iaproc .EQ. naperr ) WRITE(ndse,900) 'W3IC5WNCG'
       CALL extcde(3)
     END IF
     !
     ! Fox-Squire dispersion
     DO ik = kl, ku
       !         FSDISP(HICE, IVISC, RHOI, ISMODG, HWAT, WT, WNR, WNI)
       CALL fsdisp(hice, ivisc, rhoi, ismodg, hwat, tpi/sigma(ik), &
            twn_r, twn_i)
       wn_r(ik) = twn_r
       wn_i(ik) = twn_i
     END DO
     !
     DEALLOCATE(sigma)
     !
 900 FORMAT(/' *** WAVEWATCH III ERROR IN W3SIC5MD : '/   &
          '     Subr. ', a, ': Cannot determine bounds of&
          & wavenumber array.'/)
     !/
     !/ End of W3IC5WNCG -------------------------------------------------- /
     !/
References w3servmd::extcde(), fsdisp(), w3odatmd::iaproc, w3odatmd::naperr, w3odatmd::naproc, w3odatmd::ndse, w3gdatmd::nk, w3gdatmd::sig, w3servmd::strace(), and constants::tpi.
Referenced by w3sic5().
w3sic5()
subroutine, public w3sic5md::w3sic5 (real, dimension(nspec), intent(in) A, real, intent(in) DEPTH, real, dimension(nk), intent(in) CG, real, dimension(nk), intent(in) WN, integer, intent(in) IX, integer, intent(in) IY, real, dimension(nspec), intent(out) S, real, dimension(nspec), intent(out) D)
Calculate ice source term S_{ice} according to 3 different sea ice models.
(Mosig et al. 2015, Meylan et al. 2018, Liu et al. 2020).
Parameters
[in] A Action density spectrum (1-D).
[in] DEPTH Local water depth.
[in] CG Group velocities.
[in] WN Wavenumbers.
[in] IX Grid index.
[in] IY Grid index.
[out] S Source term (1-D version).
[out] D Diagonal term of derivative (1-D version).
Author
Q. Liu
E. Rogers
Date
19-May-2021
Definition at line 169 of file w3sic5md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           Q. Liu                  |
     !/                  |           E. Rogers               |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         19-May-2021 |
     !/                  +-----------------------------------+
     !/
     !/    23-Mar-2016 : Origination                         ( version 5.10 )
     !/                                                      ( Q. Liu)
     !/    23-Mar-2016 : Started from w3sic1/2/3/4 subr.     ( Q. Liu)
     !/    05-Apr-2016 : Options for Cg_{ice} or Cg          ( Q. Liu)
     !/    25-Apr-2017 : Add more filters                    ( Q. Liu)
     !/    20-Aug-2018 : Ready to be merged to master (v6.06)( Q. Liu)
     !/
     !/    Copyright 2009 National Weather Service (NWS),
     !/       National Oceanic and Atmospheric Administration.  All rights
     !/       reserved.  WAVEWATCH III is a trademark of the NWS.
     !/       No unauthorized use without permission.
     !/
     !/ 1. Purpose :
     !     Calculate ice source term S_{ice} according to 3 different sea ice
     !     models (Mosig et al. 2015, Meylan et al. 2018, Liu et al. 2020)
     !
     !  2. Method :
     !     Regarding i/o (general to all Sice modules): S_{ice} source term
     !     is calculated using up to 5 parameters read from input files.
     !     These parameters are allowed to vary in space and time.
     !     The parameters control the exponential decay rate k_i.
     !     Since there are 5 parameters, this permits description of
     !     dependence of k_i on frequency or wavenumber.
     !
     !     Sea ice affects the wavenumber k of wind-generated ocean waves.
     !     The ice-modified wavenumber can be expressed as a complex number
     !     k = k_r + i * k_i, with the real part k_r representing impact of
     !     the sea ice on the physical wavelength and propagation speeds,
     !     producing something analogous to shoaling and refraction by
     !     bathymetry, whereas the imaginary part of the complex
     !     wavenumber, k_i, is an exponential decay coefficient
     !     k_i(x,y,t,sigma) (depending on location, time and frequency,
     !     respectively), representing wave attenuation, and can be
     !     introduced in a wave model such as WW3 as S_ice/E=-2*Cg*k_i,
     !     where S_ice is one of several dissipation mechanisms, along
     !     with whitecapping, for example, S_ds=S_wc+S_ice+⋯. The k_r -
     !     modified by ice would enter the model via the C calculations
     !     on the left-hand side of the governing equation.The fundamentals
     !     are straightforward, e.g. Rogers and Holland (2009 and
     !     subsequent unpublished work) modified a similar model, SWAN
     !     (Booij et al. 1999) to include the effects of a viscous mud
     !     layer using the same approach (k = k_r + i*k_i) previously.
     !
     !     General approach is analogous to Rogers and Holland (2009)
     !         approach for mud.
     !     See text near their eq. 1 :
     !       k        = k_r  +  i * k_i
     !       eta(x,t) = Real( a * exp( i * ( k * x - sigma * t ) ) )
     !       a        = a0 * exp( -k_i * x )
     !       S / E    = -2 * Cg * k_i (see also Komen et al. (1994, pg. 170)
     !
     !     Following W3SBT1 as a guide, equation 1 of W3SBT1 says:
     !         S = D * E
     !     However, the code of W3SBT1 has
     !         S = D * A
     !     This leads me to believe that the calling routine is
     !         expecting "S/sigma" not "S"
     !     Thus we will use D = S/E = -2 * Cg * k_i
     !        (see also documentation of W3SIC1)
     !
     !     Notes regarding numerics:
     !     -------------------------
     !     Experiments with constant k_i values suggest that results may be
     !        dependent on resolution if insufficient resolution is used.
     !        For detailed information, see documentation of W3SIC1.
     !
     !     Note regarding applicability/validity:
     !     --------------------------------------
     !     Similar to the Wang and Shen model used in w3sic3md, the 3 models
     !     used here are empirical medium models as well which treat the sea
     !     ice cover as a continuum and use 1/2 empirical rheological para-
     !     meters, i.e., the effective shear modulus of ice G and the effec-
     !     tive viscosity η to characterize sea ices of various type. Please
     !     see the documentation of w3sic3md for a detailed discussion of
     !     this kind of model.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       A       R.A.  I   Action density spectrum (1-D).
     !       DEPTH   Real  I   Local water depth.
     !       CG      R.A.  I   Group velocities.
     !       WN      R.A.  I   Wavenumbers
     !       IX,IY   I.S.  I   Grid indices.
     !       S       R.A.  O   Source term (1-D version).
     !       D       R.A.  O   Diagonal term of derivative (1-D version).
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing (!/S switch).
     !      PRT2DS    Subr. W3ARRYMD Print plot output (!/T0 switch).
     !      OUTMAT    Subr. W3ARRYMD Matrix output (!/T1 switch).
     !      W3IC5WNCG Subr. /        Wavenumber and group velocity of ice-
     !                               coupled waves
     !     ----------------------------------------------------------------
     !      * / means this module
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !      W3EXPO    Subr.   N/A    ASCII Point output post-processor.
     !      W3EXNC    Subr.   N/A    NetCDF Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !     If ice parameter 1 is zero, no calculations are made.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !     !/T   Enable general test output.
     !     !/T0  2-D print plot of source term.
     !     !/T1  Print arrays.
     !
     ! 10. Source code :
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_T
     USE w3odatmd, ONLY: ndst
 #endif
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
 #ifdef W3_T0
     USE w3arrymd, ONLY: prt2ds
 #endif
 #ifdef W3_T1
     USE w3arrymd, ONLY: outmat
 #endif
     !/
     USE constants, ONLY: tpi
     USE w3servmd,  ONLY: extcde
     USE w3odatmd,  ONLY: ndse, iaproc, naproc, naperr
     USE w3gdatmd,  ONLY: nk, nth, nspec, sig, mapwn, ic5pars
     USE w3idatmd,  ONLY: inflags2, icep1, icep2, icep3, icep4, icei
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: CG(NK), WN(NK), A(NSPEC), DEPTH
     REAL, INTENT(OUT)       :: S(NSPEC), D(NSPEC)
     INTEGER, INTENT(IN)     :: IX, IY
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
 #ifdef W3_T0
     INTEGER                :: ITH
     REAL                   :: DOUT(NK,NTH)
 #endif
     !/
     REAL                    :: ICECOEF1, ICECOEF2, ICECOEF3, &
          ICECOEF4, ICECONC
     REAL, DIMENSION(NK)     :: D1D, WN_R, WN_I
     !     REAL                    :: TWN_R, TWN_I
     INTEGER                 :: IK, IKTH
     LOGICAL                 :: NOICE
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SIC5')
 #endif
     !
     ! 0.  Initializations ------------------------------------------------ /
     d        = 0.
     d1d      = 0.
     wn_r     = 0.
     wn_i     = 0.
     !
     icecoef1 = 0.
     icecoef2 = 0.
     icecoef3 = 0.
     icecoef4 = 0.
     iceconc  = 0.
     !
     ! Set the ice parameters from input
     IF (inflags2(-7)) THEN
       icecoef1 = icep1(ix, iy) ! ice thickness h_i
     ELSE
       IF ( iaproc .EQ. naperr )                       &
            WRITE (ndse,1001) 'ICE PARAMETER 1 (HICE)'
       CALL extcde(2)
     ENDIF
     !
     IF (inflags2(-6)) THEN
       icecoef2 = icep2(ix, iy) ! effective viscosity of ice η
     ELSE
       IF ( iaproc .EQ. naperr )                       &
            WRITE (ndse,1001) 'ICE PARAMETER 2 (VISC)'
       CALL extcde(2)
     ENDIF
     !
     IF (inflags2(-5)) THEN
       icecoef3 = icep3(ix, iy) ! density of ice ρ_i
     ELSE
       IF ( iaproc .EQ. naperr )                       &
            WRITE (ndse,1001) 'ICE PARAMETER 3 (DENS)'
       CALL extcde(2)
     ENDIF
     !
     IF (inflags2(-4)) THEN
       icecoef4 = icep4(ix, iy) ! effective shear modulus of ice G
     ELSE
       IF ( iaproc .EQ. naperr )                       &
            WRITE (ndse,1001) 'ICE PARAMETER 4 (ELAS)'
       CALL extcde(2)
     ENDIF
     !
     IF (inflags2(4)) iceconc = icei(ix, iy) ! ice concentration
     !
     ! 1. No ice --------------------------------------------------------- /
     noice = .false.
     !     Zero ice thickness
     !     Very small ice thickness may cause problems in POLYROOTS because
     !     the first coefficient C1 may be very close to zero. So we regard
     !     cases where hice is less than 0.0001 as no ice.
     !     IF (ICECOEF1 < ERRTOL) NOICE = .TRUE.
     IF (icecoef1 < 0.0001) noice = .true.
     !     zero ice concentration
     IF (inflags2(4) .AND. iceconc < errtol) noice = .true.
     !
     ! Calculate the decay rate k_i
     IF ( noice ) THEN
       d1d = 0.
       !
       ! 2. Ice ------------------------------------------------------------- /
     ELSE
       !         W3IC5WNCG(WN_R, WN_I, CG, HICE, IVISC, RHOI, ISMODG, HWAT)
       CALL w3ic5wncg(wn_r, wn_i, cg, icecoef1, icecoef2, &
            icecoef3, icecoef4, depth)
       ! recall that D=S/E=-2*Cg_{ice}*k_i
       ! In some cases, the FS model yields very large Cg_{ice}, which
       ! subquently may result in numerical failure due to the violation of CFL
       ! conditions, therefore we still use ice-free group velocity to advect
       ! wave packets.
       !
       DO ik = 1, nk
         d1d(ik) = -2.0 * cg(ik) * wn_i(ik)
       END DO
     END IF
     !
     ! 2.1 Fill diagonal matrix
     DO ikth = 1, nspec
       d(ikth) = d1d(mapwn(ikth))
     END DO
     s = d * a
     !
     ! ... Test output of arrays
     !
 #ifdef W3_T0
     DO ik=1, nk
       DO ith=1, nth
         dout(ik,ith) = d(ith+(ik-1)*nth)
       END DO
     END DO
     CALL prt2ds (ndst, nk, nk, nth, dout, sig(1:), '  ', 1.,    &
          0.0, 0.001, 'Diag Sice', ' ', 'NONAME')
 #endif
     !
 #ifdef W3_T1
     CALL outmat (ndst, d, nth, nth, nk, 'diag Sice')
 #endif
     !
     ! Formats
     !
 1001 FORMAT(/' *** WAVEWATCH III ERROR IN W3SIC5MD : '/   &
          '     ',a,' IS NOT DEFINED IN ww3_shel.inp.')
     !/
     !/ End of W3SIC5------------------------------------------------------ /
     !/
References w3servmd::extcde(), w3odatmd::iaproc, w3gdatmd::ic5pars, w3idatmd::inflags2, w3gdatmd::mapwn, w3odatmd::naperr, w3odatmd::naproc, w3odatmd::ndse, w3odatmd::ndst, w3gdatmd::nk, w3gdatmd::nspec, w3gdatmd::nth, w3arrymd::outmat(), w3arrymd::prt2ds(), w3gdatmd::sig, w3servmd::strace(), constants::tpi, and w3ic5wncg().
Referenced by gxexpo(), and w3srcemd::w3srce().