WAVEWATCH III: w3adatmd Module Reference
w3adatmd Module Reference
Define data structures to set up wave model auxiliary data for several models simultaneously.
Data Types
type wadat
Functions/Subroutines
subroutine w3naux (NDSE, NDST)
Set up the number of grids to be used.
subroutine w3dima (IMOD, NDSE, NDST, D_ONLY)
Initialize an individual data grid at the proper dimensions.
subroutine w3xdma (IMOD, NDSE, NDST, OUTFLAGS)
Version of W3DIMX for extended ouput arrays only.
subroutine w3dmnl (IMOD, NDSE, NDST, NSP, NSPX)
Initialize an individual data grid at the proper dimensions (DIA).
subroutine w3seta (IMOD, NDSE, NDST)
Select one of the WAVEWATCH III grids / models.
subroutine w3xeta (IMOD, NDSE, NDST)
Reduced version of W3SETA to point to expended output arrays.
Variables
integer nadata = -1
integer iadata = -1
integer, parameter mpibuf = 6
type(wadat), dimension(:), allocatable, target wadats
real, dimension(:,:), pointer cg
real, dimension(:,:), pointer wn
real, dimension(:,:), pointer ic3wn_r
real, dimension(:,:), pointer ic3wn_i
real, dimension(:,:), pointer ic3cg
real, dimension(:), pointer ca0
real, dimension(:), pointer cai
real, dimension(:), pointer cd0
real, dimension(:), pointer cdi
real, dimension(:), pointer ua0
real, dimension(:), pointer uai
real, dimension(:), pointer ud0
real, dimension(:), pointer udi
real, dimension(:), pointer ma0
real, dimension(:), pointer mai
real, dimension(:), pointer ra0
real, dimension(:), pointer rai
real, dimension(:), pointer md0
real, dimension(:), pointer mdi
real, dimension(:), pointer as0
real, dimension(:), pointer asi
real, dimension(:,:), pointer atrnx
real, dimension(:,:), pointer atrny
real, dimension(:), pointer dw
real, dimension(:), pointer ua
real, dimension(:), pointer ud
real, dimension(:), pointer u10
real, dimension(:), pointer u10d
real, dimension(:), pointer as
real, dimension(:), pointer cx
real, dimension(:), pointer cy
real, dimension(:), pointer taua
real, dimension(:), pointer tauadir
real, dimension(:), pointer hs
real, dimension(:), pointer wlm
real, dimension(:), pointer t02
real, dimension(:), pointer t0m1
real, dimension(:), pointer t01
real, dimension(:), pointer fp0
real, dimension(:), pointer thm
real, dimension(:), pointer ths
real, dimension(:), pointer thp0
real, dimension(:), pointer hsig
real, dimension(:), pointer stmaxe
real, dimension(:), pointer stmaxd
real, dimension(:), pointer hmaxe
real, dimension(:), pointer hcmaxe
real, dimension(:), pointer hmaxd
real, dimension(:), pointer hcmaxd
real, dimension(:), pointer qp
real, dimension(:), pointer wbt
real, dimension(:), pointer wnmean
real, dimension(:,:), pointer ef
real, dimension(:,:), pointer th1m
real, dimension(:,:), pointer sth1m
real, dimension(:,:), pointer th2m
real, dimension(:,:), pointer sth2m
real, dimension(:,:), pointer phs
real, dimension(:,:), pointer ptp
real, dimension(:,:), pointer plp
real, dimension(:,:), pointer pdir
real, dimension(:,:), pointer psi
real, dimension(:,:), pointer pws
real, dimension(:), pointer pwst
real, dimension(:), pointer pnr
real, dimension(:,:), pointer pgw
real, dimension(:,:), pointer psw
real, dimension(:,:), pointer pthp0
real, dimension(:,:), pointer pqp
real, dimension(:,:), pointer ppe
real, dimension(:,:), pointer ptm1
real, dimension(:,:), pointer pt1
real, dimension(:,:), pointer pt2
real, dimension(:,:), pointer pep
real, dimension(:), pointer charn
real, dimension(:), pointer cge
real, dimension(:), pointer phiaw
real, dimension(:), pointer tauwix
real, dimension(:), pointer tauwiy
real, dimension(:), pointer tauwnx
real, dimension(:), pointer tauwny
real, dimension(:,:), pointer whitecap
real, dimension(:), pointer tws
real, dimension(:), pointer sxx
real, dimension(:), pointer syy
real, dimension(:), pointer sxy
real, dimension(:), pointer tauox
real, dimension(:), pointer tauoy
real, dimension(:), pointer bhd
real, dimension(:), pointer phioc
real, dimension(:), pointer tusx
real, dimension(:), pointer tusy
real, dimension(:), pointer ussx
real, dimension(:), pointer ussy
real, dimension(:), pointer tauocx
real, dimension(:), pointer tauocy
real, dimension(:), pointer prms
real, dimension(:), pointer tpms
real, dimension(:), pointer phice
real, dimension(:,:), pointer tauice
real, dimension(:,:), pointer p2sms
real, dimension(:,:), pointer us3d
real, dimension(:,:), pointer ussp
real, dimension(:), pointer aba
real, dimension(:), pointer abd
real, dimension(:), pointer uba
real, dimension(:), pointer ubd
real, dimension(:,:), pointer bedforms
real, dimension(:), pointer phibbl
real, dimension(:,:), pointer taubbl
real, dimension(:), pointer mssx
real, dimension(:), pointer mssy
real, dimension(:), pointer mssd
real, dimension(:), pointer mscx
real, dimension(:), pointer mscy
real, dimension(:), pointer mscd
real, dimension(:), pointer qkk
real, dimension(:), pointer skew
real, dimension(:), pointer embia1
real, dimension(:), pointer embia2
real, dimension(:), pointer dtdyn
real, dimension(:), pointer fcut
real, dimension(:), pointer cflxymax
real, dimension(:), pointer cflthmax
real, dimension(:), pointer cflkmax
real, dimension(:,:), pointer usero
real, dimension(:,:), pointer dddx
real, dimension(:,:), pointer dddy
real, dimension(:,:), pointer dcxdx
real, dimension(:,:), pointer dcydx
real, dimension(:,:), pointer dcxdy
real, dimension(:,:), pointer dcydy
real, dimension(:,:,:), pointer dcdx
real, dimension(:,:,:), pointer dcdy
real, dimension(:), pointer dhdx
real, dimension(:), pointer dhdy
real, dimension(:,:), pointer dhlmt
integer, dimension(:), pointer is0
integer, dimension(:), pointer is2
real, dimension(:), pointer facvx
real, dimension(:), pointer facvy
integer, pointer nmx0
integer, pointer nmx1
integer, pointer nmx2
integer, pointer nmy0
integer, pointer nmy1
integer, pointer nmy2
integer, pointer nact
integer, pointer nmxy
integer, dimension(:), pointer mapx2
integer, dimension(:), pointer mapy2
integer, dimension(:), pointer mapaxy
integer, dimension(:), pointer mapxy
integer, dimension(:), pointer mapth2
integer, dimension(:), pointer mapwn2
integer, pointer ncent
integer, dimension(:), pointer mapcxy
logical, dimension(:), pointer maptrn
integer, dimension(:,:), pointer iter
integer, pointer nfr
integer, pointer nfrhgh
integer, pointer nfrchg
integer, pointer nspecx
integer, pointer nspecy
integer, dimension(:), pointer ip11
integer, dimension(:), pointer ip12
integer, dimension(:), pointer ip13
integer, dimension(:), pointer ip14
integer, dimension(:), pointer im11
integer, dimension(:), pointer im12
integer, dimension(:), pointer im13
integer, dimension(:), pointer im14
integer, dimension(:), pointer ip21
integer, dimension(:), pointer ip22
integer, dimension(:), pointer ip23
integer, dimension(:), pointer ip24
integer, dimension(:), pointer im21
integer, dimension(:), pointer im22
integer, dimension(:), pointer im23
integer, dimension(:), pointer im24
integer, dimension(:), pointer ic11
integer, dimension(:), pointer ic12
integer, dimension(:), pointer ic21
integer, dimension(:), pointer ic22
integer, dimension(:), pointer ic31
integer, dimension(:), pointer ic32
integer, dimension(:), pointer ic41
integer, dimension(:), pointer ic42
integer, dimension(:), pointer ic51
integer, dimension(:), pointer ic52
integer, dimension(:), pointer ic61
integer, dimension(:), pointer ic62
integer, dimension(:), pointer ic71
integer, dimension(:), pointer ic72
integer, dimension(:), pointer ic81
integer, dimension(:), pointer ic82
real, pointer dal1
real, pointer dal2
real, pointer dal3
real, pointer awg1
real, pointer awg2
real, pointer awg3
real, pointer awg4
real, pointer awg5
real, pointer awg6
real, pointer awg7
real, pointer awg8
real, pointer swg1
real, pointer swg2
real, pointer swg3
real, pointer swg4
real, pointer swg5
real, pointer swg6
real, pointer swg7
real, pointer swg8
real, dimension(:), pointer af11
logical, pointer nlinit
integer, dimension(:), pointer iappro
integer, pointer mpi_comm_wave
integer, pointer mpi_comm_wcmp
integer, pointer ww3_field_vec
integer, pointer ww3_spec_vec
integer, pointer nrqsg1
integer, pointer nrqsg2
integer, pointer ibfloc
integer, pointer isploc
integer, pointer nsploc
integer, dimension(:), pointer bstat
integer, dimension(:), pointer bispl
integer, dimension(:,:), pointer irqsg1
integer, dimension(:,:), pointer irqsg2
real, dimension(:,:), pointer gstore
real, dimension(:,:), pointer sstore
real, dimension(:,:,:), pointer sppnt
integer, pointer itime
integer, pointer ipass
integer, pointer idlast
integer, pointer nsealm
real, dimension(:,:), pointer alpha
logical, pointer ainit
logical, pointer ainit2
logical, pointer fl_all
logical, pointer flcold
logical, pointer fliwnd
Detailed Description
Define data structures to set up wave model auxiliary data for several models simultaneously.
The number of grids is taken from W3GDATMD, and needs to be set first with W3DIMG.
Author
H. L. Tolman
Date
22-Mar-2021
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
w3dima()
subroutine w3adatmd::w3dima (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, logical, intent(in), optional D_ONLY)
Initialize an individual data grid at the proper dimensions.
Allocate directly into the structure array. Note that this cannot be done through the pointer alias!
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
[in] D_ONLY Flag for initializing data arrays only.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 846 of file w3adatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    28-Dec-2004 : Origination.                        ( version 3.06 )
     !/    20-Jul-2005 : Adding output fields.               ( version 3.07 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    28-Mar-2007 : Add partitioned data arrays.        ( version 3.11 )
     !/                  Add additional undefined arrays.
     !/    22-Feb-2008 ; Modify MAPTH2 declaration.          ( version 3.14 )
     !/    31-Oct-2010 : Added initialization of CX,CY,DW    ( version 3.14 )
     !/    25-Dec-2012 : Memory reduction for outputs.       ( version 4.11 )
     !/    28-Jul-2013 : Bug fix initialization P2SMS.       ( version 4.11 )
     !/    30-Apr-2014 : Memory reduction for group3.        ( version 5.00 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    22-Mar-2021 : Adds TAUA, WNMEAN, TAUOC parameters ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data grid at the proper dimensions.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       D_ONLY  L.O.   I   FLag for initializing data arrays only.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOGO    Subr. W3IOGOMD Grid output IO routine.
     !      WW3_SHEL  Prog.   N/A    Wave model driver.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - W3SETA needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/SHRD, !/DIST
     !              Shared / distributed memory model
     !
     !     !/PRn    Propagation scheme selection.
     !
     !     !/S      Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants, ONLY : lpdlib
     USE w3gdatmd, ONLY: ngrids, igrid, w3setg, nk, nx, ny, nsea,    &
          nseal, nspec, nth, e3df, p2msf, us3df,      &
          usspf, gtype, ungtype
     USE w3odatmd, ONLY: iaproc, naproc, ntproc, napfld,             &
          noswll, noextr, undef, flogrd, flogr2
     USE w3idatmd, ONLY: flcur, flwind, fltaua, flrhoa
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST
     LOGICAL, INTENT(IN), OPTIONAL :: D_ONLY
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID, NXXX, NSEAL_tmp
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DIMA')
 #endif
     integer :: memunit
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     memunit = 30000+iaproc
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 0')
     IF ( PRESENT(d_only) ) THEN
       fl_all = .NOT. d_only
     ELSE
       fl_all = .true.
     END IF
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nadata ) THEN
       WRITE (ndse,1002) imod, nadata
       CALL extcde (2)
     END IF
     !
     IF ( wadats(imod)%AINIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 1')
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !     Call W3SETA to assure of pointes FLCUR, FLWND, and FLTAUA
     !
     CALL w3seta ( imod, ndse, ndst )
     !
     !AR: Check this below more ...
     nxxx   = nsealm * naproc
     !
     !     Output and input parameteres by output type
     !
     !  1) Forcing fields (these arrays are always needed)
     !
     ALLOCATE ( wadats(imod)%DW(0:nsea) , stat=istat )
     check_alloc_status( istat )
     wadats(imod)%DW(:)=0.
     !
     ALLOCATE ( wadats(imod)%CX(0:nsea) , wadats(imod)%CY(0:nsea) , &
          stat=istat )
     check_alloc_status( istat )
     wadats(imod)%CX(:)=0.
     wadats(imod)%CY(:)=0.
     !
     ALLOCATE ( wadats(imod)%UA(0:nsea) , wadats(imod)%UD(0:nsea) , &
          wadats(imod)%U10(nsea)  , wadats(imod)%U10D(nsea) , &
          wadats(imod)%AS(0:nsea) , stat=istat )
     check_alloc_status( istat )
     !
     ALLOCATE ( wadats(imod)%TAUA(0:nsea) ,                         &
          wadats(imod)%TAUADIR(0:nsea), stat=istat )
     check_alloc_status( istat )
     wadats(imod)%TAUA(:)   =0.
     wadats(imod)%TAUADIR(:)=0.
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 2')
     !
     !     Water level WLV stored in W3WDATMD
     !     Ice concentration ICE stored in W3WDATMD
     !     Ice floe sizes ICEF and ICEDMAX stored in W3WDATMD
     !     Iceberg damping BERG stored in W3WDATMD
     !
     ! 2) Standard mean wave parameters
     !    Here, all short arrays are always allocated to reduce logical
     !    checks in all computations. The coresponding full size arrays
     !    are allocated in W3MPIO only as needed to keep the memory
     !    footprint down.
     !
     IF (nsealm .eq. 0) THEN
       nsealm=nsea
     END IF
     ALLOCATE ( wadats(imod)%HS (nsealm), wadats(imod)%WLM (nsealm), &
          wadats(imod)%T02  (nsealm), wadats(imod)%T0M1(nsealm),     &
          wadats(imod)%T01  (nsealm), wadats(imod)%FP0 (nsealm),     &
          wadats(imod)%THM  (nsealm), wadats(imod)%THS (nsealm),     &
          wadats(imod)%THP0 (nsealm), wadats(imod)%HSIG(nsealm),     &
          wadats(imod)%STMAXE (nsealm),                              &
          wadats(imod)%STMAXD(nsealm),                               &
          wadats(imod)%HMAXE(nsealm), wadats(imod)%HMAXD(nsealm),    &
          wadats(imod)%HCMAXE(nsealm),                               &
          wadats(imod)%HCMAXD(nsealm), wadats(imod)%QP(nsealm),      &
          wadats(imod)%WBT(nsealm),                                  &
          wadats(imod)%WNMEAN(nsealm),                               &
          stat=istat )
     check_alloc_status( istat )
     !
     wadats(imod)%HS     = undef
     wadats(imod)%WLM    = undef
     wadats(imod)%T02    = undef
     wadats(imod)%T0M1   = undef
     wadats(imod)%T01    = undef
     wadats(imod)%FP0    = undef
     wadats(imod)%THM    = undef
     wadats(imod)%THS    = undef
     wadats(imod)%THP0   = undef
     wadats(imod)%HSIG   = undef
     wadats(imod)%STMAXE = undef
     wadats(imod)%STMAXD = undef
     wadats(imod)%HMAXE  = undef
     wadats(imod)%HMAXD  = undef
     wadats(imod)%HCMAXE = undef
     wadats(imod)%HCMAXD = undef
     wadats(imod)%QP     = undef
     wadats(imod)%WBT    = undef
     wadats(imod)%WNMEAN = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 3')
     !
     ! 3) Frequency-dependent standard parameters
     !
     ! For the 3D arrays: the allocation is performed only if these arrays are allowed
     !                    by specific variables defined through the mod_def file
     !                    and read by w3iogr, which is called before W3DIMA.
     IF (  e3df(1,1).GT.0 ) THEN
       ALLOCATE(wadats(imod)%EF(nsealm,e3df(2,1):e3df(3,1)),    &
            stat=istat )
       check_alloc_status( istat )
     END IF
     IF (  e3df(1,2).GT.0 ) THEN
       ALLOCATE(wadats(imod)%TH1M(nsealm,e3df(2,2):e3df(3,2)),  &
            stat=istat )
       check_alloc_status( istat )
     END IF
     IF (  e3df(1,3).GT.0 ) THEN
       ALLOCATE(wadats(imod)%STH1M(nsealm,e3df(2,3):e3df(3,3)), &
            stat=istat )
       check_alloc_status( istat )
     END IF
     IF (  e3df(1,4).GT.0 ) THEN
       ALLOCATE(wadats(imod)%TH2M(nsealm,e3df(2,4):e3df(3,4)),  &
            stat=istat )
       check_alloc_status( istat )
     END IF
     IF (  e3df(1,5).GT.0 ) THEN
       ALLOCATE(wadats(imod)%STH2M(nsealm,e3df(2,5):e3df(3,5)), &
            stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF (  e3df(1,1).GT.0 ) wadats(imod)%EF      = undef
     IF (  e3df(1,2).GT.0 ) wadats(imod)%TH1M    = undef
     IF (  e3df(1,3).GT.0 ) wadats(imod)%STH1M   = undef
     IF (  e3df(1,4).GT.0 ) wadats(imod)%TH2M    = undef
     IF (  e3df(1,5).GT.0 ) wadats(imod)%STH2M   = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 4')
     !
     ! 4) Spectral Partitions parameters
     !
     ALLOCATE ( wadats(imod)%PHS(nsealm,0:noswll),                   &
          wadats(imod)%PTP(nsealm,0:noswll),                   &
          wadats(imod)%PLP(nsealm,0:noswll),                   &
          wadats(imod)%PDIR(nsealm,0:noswll),                  &
          wadats(imod)%PSI(nsealm,0:noswll),                   &
          wadats(imod)%PWS(nsealm,0:noswll),                   &
          wadats(imod)%PWST(nsealm),                           &
          wadats(imod)%PNR(nsealm),                            &
          wadats(imod)%PTHP0(nsealm,0:noswll),                 &
          wadats(imod)%PQP(nsealm,0:noswll),                   &
          wadats(imod)%PPE(nsealm,0:noswll),                   &
          wadats(imod)%PGW(nsealm,0:noswll),                   &
          wadats(imod)%PSW(nsealm,0:noswll),                   &
          wadats(imod)%PTM1(nsealm,0:noswll),                  &
          wadats(imod)%PT1(nsealm,0:noswll),                   &
          wadats(imod)%PT2(nsealm,0:noswll),                   &
          wadats(imod)%PEP(nsealm,0:noswll),                   &
          stat=istat )
     check_alloc_status( istat )
     !
     wadats(imod)%PHS    = undef
     wadats(imod)%PTP    = undef
     wadats(imod)%PLP    = undef
     wadats(imod)%PDIR   = undef
     wadats(imod)%PSI    = undef
     wadats(imod)%PWS    = undef
     wadats(imod)%PWST   = undef
     wadats(imod)%PNR    = undef
     wadats(imod)%PTHP0  = undef
     wadats(imod)%PQP    = undef
     wadats(imod)%PPE    = undef
     wadats(imod)%PGW    = undef
     wadats(imod)%PSW    = undef
     wadats(imod)%PTM1   = undef
     wadats(imod)%PT1    = undef
     wadats(imod)%PT2    = undef
     wadats(imod)%PEP    = undef
     !
     ! 5) Atmosphere-waves layer
     !
     !    Friction velocity UST and USTDIR in W3WDATMD
     !
     ALLOCATE ( wadats(imod)%CHARN   (nsealm),                       &
          wadats(imod)%TWS     (nsealm),                       &
          wadats(imod)%CGE     (nsealm),                       &
          wadats(imod)%PHIAW   (nsealm),                       &
          wadats(imod)%TAUWIX  (nsealm),                       &
          wadats(imod)%TAUWIY  (nsealm),                       &
          wadats(imod)%TAUWNX  (nsealm),                       &
          wadats(imod)%TAUWNY  (nsealm),                       &
          wadats(imod)%WHITECAP(nsealm,4),                     &
          stat=istat )
     check_alloc_status( istat )
     !
     wadats(imod)%CHARN    = undef
     wadats(imod)%TWS      = undef
     wadats(imod)%CGE      = undef
     wadats(imod)%PHIAW    = undef
     wadats(imod)%TAUWIX   = undef
     wadats(imod)%TAUWIY   = undef
     wadats(imod)%TAUWNX   = undef
     wadats(imod)%TAUWNY   = undef
     wadats(imod)%WHITECAP = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 5')
     !
     ! 6) Wave-ocean layer
     !
     ALLOCATE ( wadats(imod)%SXX   (nsealm) ,                  &
          wadats(imod)%SYY   (nsealm) ,                        &
          wadats(imod)%SXY   (nsealm) ,                        &
          wadats(imod)%TAUOX (nsealm) ,                        &
          wadats(imod)%TAUOY (nsealm) ,                        &
          wadats(imod)%BHD   (nsealm) ,                        &
          wadats(imod)%PHIOC (nsealm) ,                        &
          wadats(imod)%TUSX  (nsealm) ,                        &
          wadats(imod)%TUSY  (nsealm) ,                        &
          wadats(imod)%USSX  (nsealm) ,                        &
          wadats(imod)%USSY  (nsealm) ,                        &
          wadats(imod)%TAUOCX(nsealm) ,                        &
          wadats(imod)%TAUOCY(nsealm) ,                        &
          wadats(imod)%PRMS  (nsealm) ,                        &
          wadats(imod)%TPMS  (nsealm) ,                        &
          wadats(imod)%PHICE (nsealm) ,                        &
          wadats(imod)%TAUICE(nsealm,2),                       &
          stat=istat )
     check_alloc_status( istat )
     !
     ! For the 3D arrays: the allocation is performed only if these arrays are allowed
     !                    by specific variables defined through the mod_def file
     !                    and read by w3iogr, which is called before W3DIMA.
     IF (  p2msf(1).GT.0 ) THEN
       ALLOCATE(wadats(imod)%P2SMS(nsealm,p2msf(2):p2msf(3)), stat=istat )
       check_alloc_status( istat )
     END IF
     IF (  us3df(1).GT.0 ) THEN ! maybe use US3DF(2:3)
       ALLOCATE(wadats(imod)%US3D(nsealm,nk*2), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( usspf(1).GT.0 ) THEN
       ALLOCATE(wadats(imod)%USSP(nsealm,nk*2), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%SXX    = undef
     wadats(imod)%SYY    = undef
     wadats(imod)%SXY    = undef
     wadats(imod)%TAUOX  = undef
     wadats(imod)%TAUOY  = undef
     wadats(imod)%BHD    = undef
     wadats(imod)%PHIOC  = undef
     wadats(imod)%TUSX   = undef
     wadats(imod)%TUSY   = undef
     wadats(imod)%USSX   = undef
     wadats(imod)%USSY   = undef
     wadats(imod)%TAUOCX = undef
     wadats(imod)%TAUOCY = undef
     wadats(imod)%PRMS   = undef
     wadats(imod)%TPMS   = undef
     wadats(imod)%PHICE  = undef
     wadats(imod)%TAUICE = undef
     IF (  p2msf(1).GT.0 ) wadats(imod)%P2SMS  = undef
     IF (  us3df(1).GT.0 ) wadats(imod)%US3D   = undef
     IF (  usspf(1).GT.0 ) wadats(imod)%USSP   = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 6')
     !
     ! 7) Wave-bottom layer
     !
     ALLOCATE ( wadats(imod)%ABA(nsealm) , wadats(imod)%ABD(nsealm) , &
          wadats(imod)%UBA(nsealm) , wadats(imod)%UBD(nsealm) ,       &
          wadats(imod)%BEDFORMS(nsealm,3),                            &
          wadats(imod)%PHIBBL  (nsealm)  ,                            &
          wadats(imod)%TAUBBL  (nsealm,2), stat=istat           )
     check_alloc_status( istat )
     !
     wadats(imod)%ABA    = undef
     wadats(imod)%ABD    = undef
     wadats(imod)%UBA    = undef
     wadats(imod)%UBD    = undef
     wadats(imod)%BEDFORMS = undef
     wadats(imod)%PHIBBL = undef
     wadats(imod)%TAUBBL = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 7')
     !
     ! 8) Spectrum parameters
     !
     ALLOCATE ( wadats(imod)%MSSX(nsealm), wadats(imod)%MSSY(nsealm), &
          wadats(imod)%MSCX(nsealm), wadats(imod)%MSCY(nsealm), &
          wadats(imod)%MSSD(nsealm), wadats(imod)%MSCD(nsealm), &
          wadats(imod)%QKK(nsealm), wadats(imod)%SKEW(nsealm),  &
          wadats(imod)%EMBIA1(nsealm), wadats(imod)%EMBIA2(nsealm),  &
               stat=istat )
     check_alloc_status( istat )
     !
     wadats(imod)%MSSX   = undef
     wadats(imod)%MSSY   = undef
     wadats(imod)%MSSD   = undef
     wadats(imod)%MSCX   = undef
     wadats(imod)%MSCY   = undef
     wadats(imod)%MSCD   = undef
     wadats(imod)%QKK    = undef
     wadats(imod)%SKEW   = undef
     wadats(imod)%EMBIA1 = undef
     wadats(imod)%EMBIA2 = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 8')
     !
     ! 9) Numerical diagnostics
     !
     !
     ALLOCATE ( wadats(imod)%DTDYN   (nsealm) , &
          wadats(imod)%FCUT    (nsealm) ,       &
          wadats(imod)%CFLXYMAX(nsealm) ,       &
          wadats(imod)%CFLTHMAX(nsealm) ,       &
          wadats(imod)%CFLKMAX (nsealm) , stat=istat            )
     check_alloc_status( istat )
     !
     wadats(imod)%DTDYN    = undef
     wadats(imod)%FCUT     = undef
     wadats(imod)%CFLXYMAX = undef
     wadats(imod)%CFLTHMAX = undef
     wadats(imod)%CFLKMAX  = undef
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 9')
     !
     ! 10) User defined
     !
     ALLOCATE ( wadats(imod)%USERO(nsealm,noextr), stat=istat )
     check_alloc_status( istat )
     !
     wadats(imod)%USERO  = undef
     !
     ALLOCATE ( wadats(imod)%WN(0:nk+1,0:nsea), stat=istat )
     check_alloc_status( istat )
 #ifdef W3_IC3
     ALLOCATE (wadats(imod)%IC3WN_R(0:nk+1,0:300), stat=istat )
     check_alloc_status( istat )
     ALLOCATE (wadats(imod)%IC3WN_I(0:nk+1,0:300), stat=istat )
     check_alloc_status( istat )
 #endif
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 10')
     !
     IF ( fl_all ) THEN
       !
       ALLOCATE ( wadats(imod)%CG(0:nk+1,0:nsea), stat=istat )
       check_alloc_status( istat )
 #ifdef W3_IC3
       ALLOCATE (wadats(imod)%IC3CG(0:nk+1,0:300), stat=istat )
       check_alloc_status( istat )
 #endif
       !
       IF ( flcur  ) THEN
         ALLOCATE ( wadats(imod)%CA0(nsea) , &
              wadats(imod)%CAI(nsea) ,       &
              wadats(imod)%CD0(nsea) ,       &
              wadats(imod)%CDI(nsea) ,       &
              stat=istat )
         check_alloc_status( istat )
       END IF
       !
       IF ( flwind ) THEN
         ALLOCATE ( wadats(imod)%UA0(nsea) , &
              wadats(imod)%UAI(nsea) ,       &
              wadats(imod)%UD0(nsea) ,       &
              wadats(imod)%UDI(nsea) ,       &
              wadats(imod)%AS0(nsea) ,       &
              wadats(imod)%ASI(nsea) ,       &
              stat=istat )
         check_alloc_status( istat )
       END IF
       !
       IF ( fltaua  ) THEN
         ALLOCATE ( wadats(imod)%MA0(nsea) , &
              wadats(imod)%MAI(nsea) ,       &
              wadats(imod)%MD0(nsea) ,       &
              wadats(imod)%MDI(nsea) ,       &
              stat=istat )
         check_alloc_status( istat )
       END IF
       !
       IF ( flrhoa  ) THEN
         ALLOCATE ( wadats(imod)%RA0(nsea) , &
              wadats(imod)%RAI(nsea) ,       &
              stat=istat )
         check_alloc_status( istat )
       END IF
       !
       ALLOCATE ( wadats(imod)%ATRNX(ny*nx,-1:1) ,                 &
            wadats(imod)%ATRNY(ny*nx,-1:1) , stat=istat      )
       check_alloc_status( istat )
       !
       IF (.NOT. lpdlib) THEN
         ALLOCATE ( wadats(imod)%DDDX(ny,nx)  ,    &
              wadats(imod)%DDDY(ny,nx)  ,          &
              wadats(imod)%DCDX(0:nk+1,ny,nx)  ,   &
              wadats(imod)%DCDY(0:nk+1,ny,nx)  ,   &
              wadats(imod)%DCXDX(ny,nx) ,          &
              wadats(imod)%DCYDX(ny,nx) ,          &
              wadats(imod)%DCXDY(ny,nx) ,          &
              wadats(imod)%DCYDY(ny,nx) , stat=istat           )
       ELSE
         ALLOCATE ( wadats(imod)%DDDX(1,nseal)  ,  &
              wadats(imod)%DDDY(1,nseal)  ,        &
              wadats(imod)%DCDX(0:nk+1,1,nseal)  , &
              wadats(imod)%DCDY(0:nk+1,1,nseal)  , &
              wadats(imod)%DCXDX(1,nseal) ,        &
              wadats(imod)%DCYDX(1,nseal) ,        &
              wadats(imod)%DCXDY(1,nseal) ,        &
              wadats(imod)%DCYDY(1,nseal) ,        &
              stat=istat           )
       ENDIF
       check_alloc_status( istat )
       wadats(imod)%DDDX = 0.
       wadats(imod)%DDDY = 0.
       wadats(imod)%DCDX = 0.
       wadats(imod)%DCDY = 0.
       wadats(imod)%DCXDX = 0.
       wadats(imod)%DCYDX = 0.
       wadats(imod)%DCXDY = 0.
       wadats(imod)%DCYDY = 0.
       !
 #ifdef W3_SMC
       ALLOCATE ( wadats(imod)%DHDX(nsea) ,                  &
            wadats(imod)%DHDY(nsea) ,                        &
            wadats(imod)%DHLMT(nth,nsea) , stat=istat        )
       check_alloc_status( istat )
 #endif
       !
       ALLOCATE ( wadats(imod)%ALPHA(nk,nseal) , stat=istat )
       check_alloc_status( istat )
       !
 #ifdef W3_PR1
       ALLOCATE ( wadats(imod)%IS0(nspec)   ,           &
            wadats(imod)%IS2(nspec)   ,                 &
            wadats(imod)%FACVX(ny*nx) ,                 &
            wadats(imod)%FACVY(ny*nx) , stat=istat      )
       check_alloc_status( istat )
 #endif
       !
 #ifdef W3_PR2
       ALLOCATE ( wadats(imod)%MAPX2(ny*nx)       ,     &
            wadats(imod)%MAPY2(ny*nx)       ,           &
            wadats(imod)%MAPAXY(ny*nx)      ,           &
            wadats(imod)%MAPXY(nsea)        ,           &
            wadats(imod)%MAPTH2((nk+2)*nth) ,           &
            wadats(imod)%MAPWN2(nspec+nth) , stat=istat )
       check_alloc_status( istat )
       wadats(imod)%MAPTH2 = 0
 #endif
       !
       IF (gtype .EQ. ungtype) THEN
         ALLOCATE( wadats(imod)%ITER(nk,nth), stat=istat )
         check_alloc_status( istat )
       END IF
       !
 #ifdef W3_PR3
       ALLOCATE ( wadats(imod)%MAPX2(ny*nx)       ,     &
            wadats(imod)%MAPY2(ny*nx)       ,           &
            wadats(imod)%MAPAXY(ny*nx)      ,           &
            wadats(imod)%MAPCXY(nsea)       ,           &
            wadats(imod)%MAPTH2((nk+2)*nth) ,           &
            wadats(imod)%MAPWN2(nspec+nth)  ,           &
            wadats(imod)%MAPTRN(ny*nx) , stat=istat     )
       check_alloc_status( istat )
       wadats(imod)%MAPTH2 = 0
 #endif
       !
       ALLOCATE ( wadats(imod)%IAPPRO(nspec) ,          &
            wadats(imod)%SPPNT(nth,nk,4), stat=istat         )
       check_alloc_status( istat )
       !
     END IF
     !
     wadats(imod)%AINIT  = .true.
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 11')
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3seta ( imod, ndse, ndst )
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA 12')
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     call print_memcheck(memunit, 'memcheck_____:'//' W3DIMA END')
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DIMA : GRIDS NOT INITIALIZED *** '/ &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DIMA : ILLEGAL MODEL NUMBER *** '/  &
          '                    IMOD   = ',i10/                   &
          '                    NADATA = ',i10/)
 1003 FORMAT (/' *** ERROR W3DIMA : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DIMA : MODEL ',i4)
 9001 FORMAT (' TEST W3DIMA : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DIMA : POINTERS RESET')
 9003 FORMAT (' TEST W3DIMA : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DIMA ----------------------------------------------------- /
     !/
References w3gdatmd::e3df, w3servmd::extcde(), fl_all, w3idatmd::flcur, w3odatmd::flogr2, w3odatmd::flogrd, w3idatmd::flrhoa, w3idatmd::fltaua, w3idatmd::flwind, w3gdatmd::gtype, w3odatmd::iaproc, w3gdatmd::igrid, constants::lpdlib, nadata, w3odatmd::napfld, w3odatmd::naproc, w3gdatmd::ngrids, w3gdatmd::nk, w3odatmd::noextr, w3odatmd::noswll, w3gdatmd::nsea, w3gdatmd::nseal, nsealm, w3gdatmd::nspec, w3gdatmd::nth, w3odatmd::ntproc, w3gdatmd::nx, w3gdatmd::ny, w3gdatmd::p2msf, w3servmd::strace(), w3gdatmd::ungtype, w3gdatmd::us3df, w3gdatmd::usspf, w3seta(), w3gdatmd::w3setg(), and wadats.
Referenced by w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), and w3shel().
w3dmnl()
subroutine w3adatmd::w3dmnl (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, integer, intent(in) NSP, integer, intent(in) NSPX)
Initialize an individual data grid at the proper dimensions (DIA).
Allocate directly into the structure array. Note that this cannot be done through the pointer alias!
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
[in] NSP Array dimensions.
[in] NSPX Array dimensions.
Author
H. L. Tolman
Date
10-Dec-2014
Definition at line 2431 of file w3adatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 |
     !/                  +-----------------------------------+
     !/
     !/    24-Dec-2004 : Origination.                        ( version 3.06 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data grid at the proper dimensions (DIA).
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       NSP(X)  Int.   I   Array dimensions.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      INSNL1    Subr. W3SNL1MD Traditional DIA approach to Snl.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - W3SETA needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S      Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, igrid, nk, nx, ny, nsea, nseal,     &
          nspec, nth, gtype, ungtype
     USE w3odatmd, ONLY: naproc
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST, NSP, NSPX
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DMNL')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nadata ) THEN
       WRITE (ndse,1002) imod, nadata
       CALL extcde (2)
     END IF
     !
 #ifdef W3_NL1
     IF ( wadats(imod)%NLINIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
 #endif
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
 #ifdef W3_NL1
     ALLOCATE ( wadats(imod)%IP11(nspx),  &
          wadats(imod)%IP12(nspx),        &
          wadats(imod)%IP13(nspx),        &
          wadats(imod)%IP14(nspx),        &
          wadats(imod)%IM11(nspx),        &
          wadats(imod)%IM12(nspx),        &
          wadats(imod)%IM13(nspx),        &
          wadats(imod)%IM14(nspx),        &
          wadats(imod)%IP21(nspx),        &
          wadats(imod)%IP22(nspx),        &
          wadats(imod)%IP23(nspx),        &
          wadats(imod)%IP24(nspx),        &
          wadats(imod)%IM21(nspx),        &
          wadats(imod)%IM22(nspx),        &
          wadats(imod)%IM23(nspx),        &
          wadats(imod)%IM24(nspx),        &
          wadats(imod)%IC11(nsp) ,        &
          wadats(imod)%IC12(nsp) ,        &
          wadats(imod)%IC21(nsp) ,        &
          wadats(imod)%IC22(nsp) ,        &
          wadats(imod)%IC31(nsp) ,        &
          wadats(imod)%IC32(nsp) ,        &
          wadats(imod)%IC41(nsp) ,        &
          wadats(imod)%IC42(nsp) ,        &
          wadats(imod)%IC51(nsp) ,        &
          wadats(imod)%IC52(nsp) ,        &
          wadats(imod)%IC61(nsp) ,        &
          wadats(imod)%IC62(nsp) ,        &
          wadats(imod)%IC71(nsp) ,        &
          wadats(imod)%IC72(nsp) ,        &
          wadats(imod)%IC81(nsp) ,        &
          wadats(imod)%IC82(nsp) ,        &
          wadats(imod)%AF11(nspx),        &
          stat=istat                      )
     check_alloc_status( istat )
     wadats(imod)%NLINIT = .true.
 #endif
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3seta ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !
 #ifdef W3_NL1
     nspecx = nspx
 #endif
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DMNL : GRIDS NOT INITIALIZED *** '/ &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DMNL : ILLEGAL MODEL NUMBER *** '/  &
          '                    IMOD   = ',i10/                   &
          '                    NADATA = ',i10/)
 #ifdef W3_NL1
 1003 FORMAT (/' *** ERROR W3DMNL : ARRAY(S) ALREADY ALLOCATED *** ')
 #endif
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DMNL : MODEL ',i4)
 9001 FORMAT (' TEST W3DMNL : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DMNL : POINTERS RESET')
 9003 FORMAT (' TEST W3DMNL : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DMNL ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3gdatmd::gtype, w3gdatmd::igrid, nadata, w3odatmd::naproc, w3gdatmd::ngrids, w3gdatmd::nk, w3gdatmd::nsea, w3gdatmd::nseal, w3gdatmd::nspec, nspecx, w3gdatmd::nth, w3gdatmd::nx, w3gdatmd::ny, w3servmd::strace(), w3gdatmd::ungtype, w3seta(), and wadats.
Referenced by w3snl1md::insnl1().
w3naux()
subroutine w3adatmd::w3naux (integer, intent(in) NDSE, integer, intent(in) NDST)
Set up the number of grids to be used.
Use data stored in NGRIDS in W3GDATMD.
Parameters
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
10-Dec-2014
Definition at line 704 of file w3adatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    14-Dec-2004 : Origination.                        ( version 3.06 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Set up the number of grids to be used.
     !
     !  2. Method :
     !
     !     Use data stored in NGRIDS in W3GDATMD.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation.
     !
     !  5. Called by :
     !
     !     Any program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Error checks on previous setting of variable NGRIDS.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids
     USE w3servmd, ONLY: extcde
     USE w3odatmd, ONLY: iaproc
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: I
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3NAUX')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001) ngrids
       CALL extcde (1)
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set variable and allocate arrays
     !
     ALLOCATE ( wadats(ngrids), stat=istat )
     check_alloc_status( istat )
     nadata = ngrids
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Initialize parameters
     !
     DO i=1, ngrids
       wadats(i)%ITIME  = 0
       wadats(i)%IPASS  = 0
       wadats(i)%IDLAST = 0
       wadats(i)%NSEALM = 0
       wadats(i)%FLCOLD = .false.
       wadats(i)%FLIWND = .false.
       wadats(i)%AINIT  = .false.
       wadats(i)%AINIT2 = .false.
       wadats(i)%FL_ALL = .false.
 #ifdef W3_NL1
       wadats(i)%NLINIT  = .false.
 #endif
     END DO
     !
 #ifdef W3_T
     WRITE (ndst,9000) ngrids
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3NAUX : NGRIDS NOT YET SET *** '/         &
          '                    NGRIDS = ',i10/                   &
          '                    RUN W3NMOD FIRST'/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3NAUX : SETTING UP FOR ',i4,' GRIDS')
 #endif
     !/
     !/ End of W3NAUX ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3odatmd::iaproc, nadata, w3gdatmd::ngrids, w3servmd::strace(), and wadats.
Referenced by gxoutf(), gxoutp(), w3bounc(), w3bound(), w3grib(), w3grid_interp(), w3gspl(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3strt(), w3trnc(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().
w3seta()
subroutine w3adatmd::w3seta (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Select one of the WAVEWATCH III grids / models.
Point pointers to the proper variables in the proper element of the GRIDS array.
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 2645 of file w3adatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    28-Dec-2004 : Origination.                        ( version 3.06 )
     !/    04-May-2005 : Adding MPI_COMM_WAVE.               ( version 3.07 )
     !/    20-Jul-2005 : Adding output fields.               ( version 3.07 )
     !/    09-Nov-2005 : Removing soft boundary option.      ( version 3.08 )
     !/    13-Jun-2006 : Splitting STORE in G/SSTORE.        ( version 3.09 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    28_Mar-2007 : Add partitioned data arrays.        ( version 3.11 )
     !/                  Add aditional undefined arrays.
     !/    22-Mar-2021 : Adds TAUA, WNMEAN, TAUOC parameters ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Select one of the WAVEWATCH III grids / models.
     !
     !  2. Method :
     !
     !     Point pointers to the proper variables in the proper element of
     !     the GRIDS array.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation below.
     !
     !  5. Called by :
     !
     !     Many subroutines in the WAVEWATCH system.
     !
     !  6. Error messages :
     !
     !     Checks on parameter list IMOD.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/MPI  Paralllel model environment.
     !
     !     !/PRn    Propagation scheme selection.
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !
     USE w3idatmd, ONLY: inputs
     USE w3gdatmd, ONLY: e3df, p2msf, us3df, usspf, gtype, ungtype
     !
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3SETA')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( nadata .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nadata ) THEN
       WRITE (ndse,1002) imod, nadata
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model numbers
     !
     iadata = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers
     !
     itime  => wadats(imod)%ITIME
     ipass  => wadats(imod)%IPASS
     idlast => wadats(imod)%IDLAST
     nsealm => wadats(imod)%NSEALM
     flcold => wadats(imod)%FLCOLD
     fliwnd => wadats(imod)%FLIWND
     ainit  => wadats(imod)%AINIT
     ainit2 => wadats(imod)%AINIT2
     fl_all => wadats(imod)%FL_ALL
     !
 #ifdef W3_PR2
     nmx0   => wadats(imod)%NMX0
     nmx1   => wadats(imod)%NMX1
     nmx2   => wadats(imod)%NMX2
     nmy0   => wadats(imod)%NMY0
     nmy1   => wadats(imod)%NMY1
     nmy2   => wadats(imod)%NMY2
     nact   => wadats(imod)%NACT
     nmxy   => wadats(imod)%NMXY
 #endif
     !
 #ifdef W3_PR3
     nmx0   => wadats(imod)%NMX0
     nmx1   => wadats(imod)%NMX1
     nmx2   => wadats(imod)%NMX2
     nmy0   => wadats(imod)%NMY0
     nmy1   => wadats(imod)%NMY1
     nmy2   => wadats(imod)%NMY2
     nact   => wadats(imod)%NACT
     ncent  => wadats(imod)%NCENT
 #endif
     !
 #ifdef W3_NL1
     nfr    => wadats(imod)%NFR
     nfrhgh => wadats(imod)%NFRHGH
     nfrchg => wadats(imod)%NFRCHG
     nspecx => wadats(imod)%NSPECX
     nspecy => wadats(imod)%NSPECY
     dal1   => wadats(imod)%DAL1
     dal2   => wadats(imod)%DAL2
     dal3   => wadats(imod)%DAL3
     awg1   => wadats(imod)%AWG1
     awg2   => wadats(imod)%AWG2
     awg3   => wadats(imod)%AWG3
     awg4   => wadats(imod)%AWG4
     awg5   => wadats(imod)%AWG5
     awg6   => wadats(imod)%AWG6
     awg7   => wadats(imod)%AWG7
     awg8   => wadats(imod)%AWG8
     swg1   => wadats(imod)%SWG1
     swg2   => wadats(imod)%SWG2
     swg3   => wadats(imod)%SWG3
     swg4   => wadats(imod)%SWG4
     swg5   => wadats(imod)%SWG5
     swg6   => wadats(imod)%SWG6
     swg7   => wadats(imod)%SWG7
     swg8   => wadats(imod)%SWG8
     nlinit => wadats(imod)%NLINIT
 #endif
     !
 #ifdef W3_MPI
     mpi_comm_wave => wadats(imod)%MPI_COMM_WAVE
     mpi_comm_wcmp => wadats(imod)%MPI_COMM_WCMP
     ww3_field_vec => wadats(imod)%WW3_FIELD_VEC
     ww3_spec_vec => wadats(imod)%WW3_SPEC_VEC
     nrqsg1 => wadats(imod)%NRQSG1
     nrqsg2 => wadats(imod)%NRQSG2
     ibfloc => wadats(imod)%IBFLOC
     isploc => wadats(imod)%ISPLOC
     nsploc => wadats(imod)%NSPLOC
     bstat  => wadats(imod)%BSTAT
     bispl  => wadats(imod)%BISPL
 #endif
     !
     IF ( ainit ) THEN
       !
       dw     => wadats(imod)%DW
       ua     => wadats(imod)%UA
       ud     => wadats(imod)%UD
       u10    => wadats(imod)%U10
       u10d   => wadats(imod)%U10D
       as     => wadats(imod)%AS
       cx     => wadats(imod)%CX
       cy     => wadats(imod)%CY
       taua   => wadats(imod)%TAUA
       tauadir=> wadats(imod)%TAUADIR
       !
       hs     => wadats(imod)%HS
       wlm    => wadats(imod)%WLM
       t02    => wadats(imod)%T02
       t0m1   => wadats(imod)%T0M1
       t01    => wadats(imod)%T01
       fp0    => wadats(imod)%FP0
       thm    => wadats(imod)%THM
       ths    => wadats(imod)%THS
       thp0   => wadats(imod)%THP0
       hsig   => wadats(imod)%HSIG
       stmaxe => wadats(imod)%STMAXE
       stmaxd => wadats(imod)%STMAXD
       hmaxe  => wadats(imod)%HMAXE
       hmaxd  => wadats(imod)%HMAXD
       hcmaxe => wadats(imod)%HCMAXE
       hcmaxd => wadats(imod)%HCMAXD
       qp     => wadats(imod)%QP
       wbt    => wadats(imod)%WBT
       wnmean => wadats(imod)%WNMEAN
       !
       ef     => wadats(imod)%EF
       th1m   => wadats(imod)%TH1M
       sth1m  => wadats(imod)%STH1M
       th2m   => wadats(imod)%TH2M
       sth2m  => wadats(imod)%STH2M
       !
       phs    => wadats(imod)%PHS
       ptp    => wadats(imod)%PTP
       plp    => wadats(imod)%PLP
       pdir   => wadats(imod)%PDIR
       psi    => wadats(imod)%PSI
       pws    => wadats(imod)%PWS
       pwst   => wadats(imod)%PWST
       pnr    => wadats(imod)%PNR
       pthp0  => wadats(imod)%PTHP0
       pqp    => wadats(imod)%PQP
       ppe    => wadats(imod)%PPE
       pgw    => wadats(imod)%PGW
       psw    => wadats(imod)%PSW
       ptm1   => wadats(imod)%PTM1
       pt1    => wadats(imod)%PT1
       pt2    => wadats(imod)%PT2
       pep    => wadats(imod)%PEP
       !
       charn    => wadats(imod)%CHARN
       tws      => wadats(imod)%TWS
       cge      => wadats(imod)%CGE
       phiaw    => wadats(imod)%PHIAW
       tauwix   => wadats(imod)%TAUWIX
       tauwiy   => wadats(imod)%TAUWIY
       tauwnx   => wadats(imod)%TAUWNX
       tauwny   => wadats(imod)%TAUWNY
       whitecap => wadats(imod)%WHITECAP
       !
       sxx    => wadats(imod)%SXX
       syy    => wadats(imod)%SYY
       sxy    => wadats(imod)%SXY
       tauox  => wadats(imod)%TAUOX
       tauoy  => wadats(imod)%TAUOY
       bhd    => wadats(imod)%BHD
       phioc  => wadats(imod)%PHIOC
       tusx   => wadats(imod)%TUSX
       tusy   => wadats(imod)%TUSY
       ussx   => wadats(imod)%USSX
       ussy   => wadats(imod)%USSY
       prms   => wadats(imod)%PRMS
       tpms   => wadats(imod)%TPMS
       p2sms  => wadats(imod)%P2SMS
       us3d   => wadats(imod)%US3D
       phice  => wadats(imod)%PHICE
       tauice => wadats(imod)%TAUICE
       ussp   => wadats(imod)%USSP
       tauocx => wadats(imod)%TAUOCX
       tauocy => wadats(imod)%TAUOCY
       !
       aba    => wadats(imod)%ABA
       abd    => wadats(imod)%ABD
       uba    => wadats(imod)%UBA
       ubd    => wadats(imod)%UBD
       bedforms=> wadats(imod)%BEDFORMS
       phibbl => wadats(imod)%PHIBBL
       taubbl => wadats(imod)%TAUBBL
       !
       mssx   => wadats(imod)%MSSX
       mssy   => wadats(imod)%MSSY
       mssd   => wadats(imod)%MSSD
       mscx   => wadats(imod)%MSCX
       mscy   => wadats(imod)%MSCY
       mscd   => wadats(imod)%MSCD
       qkk    => wadats(imod)%QKK
       skew   => wadats(imod)%SKEW
       embia1  => wadats(imod)%EMBIA1
       embia2  => wadats(imod)%EMBIA2
       !
       dtdyn    => wadats(imod)%DTDYN
       fcut     => wadats(imod)%FCUT
       cflxymax => wadats(imod)%CFLXYMAX
       cflthmax => wadats(imod)%CFLTHMAX
       cflkmax =>  wadats(imod)%CFLKMAX
       !
       usero  => wadats(imod)%USERO
       !
       wn     => wadats(imod)%WN
 #ifdef W3_IC3
       ic3wn_r=> wadats(imod)%IC3WN_R
       ic3wn_i=> wadats(imod)%IC3WN_I
 #endif
       !
       IF ( fl_all ) THEN
         !
         cg     => wadats(imod)%CG
 #ifdef W3_IC3
         ic3cg  => wadats(imod)%IC3CG
 #endif
         !
         atrnx  => wadats(imod)%ATRNX
         atrny  => wadats(imod)%ATRNY
         !
         dddx   => wadats(imod)%DDDX
         dddy   => wadats(imod)%DDDY
         dcdx   => wadats(imod)%DCDX
         dcdy   => wadats(imod)%DCDY
         dcxdx  => wadats(imod)%DCXDX
         dcydx  => wadats(imod)%DCYDX
         dcxdy  => wadats(imod)%DCXDY
         dcydy  => wadats(imod)%DCYDY
         !
 #ifdef W3_SMC
         dhdx   => wadats(imod)%DHDX
         dhdy   => wadats(imod)%DHDY
         dhlmt  => wadats(imod)%DHLMT
 #endif
         !
         alpha  => wadats(imod)%ALPHA
         !
         IF ( inputs(imod)%INFLAGS1(2) ) THEN
           ca0    => wadats(imod)%CA0
           cai    => wadats(imod)%CAI
           cd0    => wadats(imod)%CD0
           cdi    => wadats(imod)%CDI
         END IF
         !
         IF ( inputs(imod)%INFLAGS1(3) ) THEN
           ua0    => wadats(imod)%UA0
           uai    => wadats(imod)%UAI
           ud0    => wadats(imod)%UD0
           udi    => wadats(imod)%UDI
           as0    => wadats(imod)%AS0
           asi    => wadats(imod)%ASI
         END IF
         !
         IF ( inputs(imod)%INFLAGS1(5) ) THEN
           ma0    => wadats(imod)%MA0
           mai    => wadats(imod)%MAI
           md0    => wadats(imod)%MD0
           mdi    => wadats(imod)%MDI
         END IF
         !
         IF ( inputs(imod)%INFLAGS1(6) ) THEN
           ra0    => wadats(imod)%RA0
           rai    => wadats(imod)%RAI
         END IF
         !
 #ifdef W3_PR1
         is0    => wadats(imod)%IS0
         is2    => wadats(imod)%IS2
         facvx  => wadats(imod)%FACVX
         facvy  => wadats(imod)%FACVY
 #endif
         !
 #ifdef W3_PR2
         mapx2  => wadats(imod)%MAPX2
         mapy2  => wadats(imod)%MAPY2
         mapaxy => wadats(imod)%MAPAXY
         mapxy  => wadats(imod)%MAPXY
         mapth2 => wadats(imod)%MAPTH2
         mapwn2 => wadats(imod)%MAPWN2
 #endif
         !
 #ifdef W3_PR3
         mapx2  => wadats(imod)%MAPX2
         mapy2  => wadats(imod)%MAPY2
         mapaxy => wadats(imod)%MAPAXY
         mapcxy => wadats(imod)%MAPCXY
         mapth2 => wadats(imod)%MAPTH2
         mapwn2 => wadats(imod)%MAPWN2
         maptrn => wadats(imod)%MAPTRN
 #endif
         !
         IF (gtype .EQ. ungtype) iter   => wadats(imod)%ITER
         !
         iappro => wadats(imod)%IAPPRO
         sppnt  => wadats(imod)%SPPNT
         !
       END IF
       !
     END IF
     !
 #ifdef W3_NL1
     IF ( nlinit ) THEN
       ip11   => wadats(imod)%IP11
       ip12   => wadats(imod)%IP12
       ip13   => wadats(imod)%IP13
       ip14   => wadats(imod)%IP14
       im11   => wadats(imod)%IM11
       im12   => wadats(imod)%IM12
       im13   => wadats(imod)%IM13
       im14   => wadats(imod)%IM14
       ip21   => wadats(imod)%IP21
       ip22   => wadats(imod)%IP22
       ip23   => wadats(imod)%IP23
       ip24   => wadats(imod)%IP24
       im21   => wadats(imod)%IM21
       im22   => wadats(imod)%IM22
       im23   => wadats(imod)%IM23
       im24   => wadats(imod)%IM24
       ic11   => wadats(imod)%IC11
       ic12   => wadats(imod)%IC12
       ic21   => wadats(imod)%IC21
       ic22   => wadats(imod)%IC22
       ic31   => wadats(imod)%IC31
       ic32   => wadats(imod)%IC32
       ic41   => wadats(imod)%IC41
       ic42   => wadats(imod)%IC42
       ic51   => wadats(imod)%IC51
       ic52   => wadats(imod)%IC52
       ic61   => wadats(imod)%IC61
       ic62   => wadats(imod)%IC62
       ic71   => wadats(imod)%IC71
       ic72   => wadats(imod)%IC72
       ic81   => wadats(imod)%IC81
       ic82   => wadats(imod)%IC82
       af11   => wadats(imod)%AF11
     END IF
 #endif
 #ifdef W3_MPI
     IF ( nrqsg1 .NE. 0 ) THEN
       irqsg1 => wadats(imod)%IRQSG1
       irqsg2 => wadats(imod)%IRQSG2
     END IF
     gstore => wadats(imod)%GSTORE
     sstore => wadats(imod)%SSTORE
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3SETA : GRIDS NOT INITIALIZED *** '/ &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3SETA : ILLEGAL MODEL NUMBER *** '/  &
          '                    IMOD   = ',i10/                   &
          '                    NADATA = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SETA : MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of W3SETA ----------------------------------------------------- /
     !/
References aba, abd, af11, ainit, ainit2, alpha, as, as0, asi, atrnx, atrny, awg1, awg2, awg3, awg4, awg5, awg6, awg7, awg8, bedforms, bhd, bispl, bstat, ca0, cai, cd0, cdi, cflkmax, cflthmax, cflxymax, cg, cge, charn, cx, cy, dal1, dal2, dal3, dcdx, dcdy, dcxdx, dcxdy, dcydx, dcydy, dddx, dddy, dhdx, dhdy, dhlmt, dtdyn, dw, w3gdatmd::e3df, ef, embia1, embia2, w3servmd::extcde(), facvx, facvy, fcut, fl_all, flcold, fliwnd, fp0, gstore, w3gdatmd::gtype, hcmaxd, hcmaxe, hmaxd, hmaxe, hs, hsig, iadata, iappro, ibfloc, ic11, ic12, ic21, ic22, ic31, ic32, ic3cg, ic3wn_i, ic3wn_r, ic41, ic42, ic51, ic52, ic61, ic62, ic71, ic72, ic81, ic82, idlast, im11, im12, im13, im14, im21, im22, im23, im24, w3idatmd::inputs, ip11, ip12, ip13, ip14, ip21, ip22, ip23, ip24, ipass, irqsg1, irqsg2, is0, is2, isploc, iter, itime, ma0, mai, mapaxy, mapcxy, mapth2, maptrn, mapwn2, mapx2, mapxy, mapy2, md0, mdi, mpi_comm_wave, mpi_comm_wcmp, mscd, mscx, mscy, mssd, mssx, mssy, nact, nadata, ncent, nfr, nfrchg, nfrhgh, nlinit, nmx0, nmx1, nmx2, nmxy, nmy0, nmy1, nmy2, nrqsg1, nrqsg2, nsealm, nspecx, nspecy, nsploc, w3gdatmd::p2msf, p2sms, pdir, pep, pgw, phiaw, phibbl, phice, phioc, phs, plp, pnr, ppe, pqp, prms, psi, psw, pt1, pt2, pthp0, ptm1, ptp, pws, pwst, qkk, qp, ra0, rai, skew, sppnt, sstore, sth1m, sth2m, stmaxd, stmaxe, w3servmd::strace(), swg1, swg2, swg3, swg4, swg5, swg6, swg7, swg8, sxx, sxy, syy, t01, t02, t0m1, taua, tauadir, taubbl, tauice, tauocx, tauocy, tauox, tauoy, tauwix, tauwiy, tauwnx, tauwny, th1m, th2m, thm, thp0, ths, tpms, tusx, tusy, tws, u10, u10d, ua, ua0, uai, uba, ubd, ud, ud0, udi, w3gdatmd::ungtype, us3d, w3gdatmd::us3df, usero, ussp, w3gdatmd::usspf, ussx, ussy, wadats, wbt, whitecap, wlm, wn, wnmean, ww3_field_vec, and ww3_spec_vec.
Referenced by wmesmfmd::createexpmesh(), pdlib_field_vec::do_output_exchanges(), gxoutf(), gxoutp(), w3bounc(), w3bound(), w3dima(), w3dmnl(), w3grib(), w3grid_interp(), w3gspl(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3strt(), w3trnc(), w3uprstr(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopp(), wmwavemd::wmwave(), and wmwavemd::wmwout().
w3xdma()
subroutine w3adatmd::w3xdma (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, logical, dimension(nogrp,ngrpp), intent(in) OUTFLAGS)
Version of W3DIMX for extended ouput arrays only.
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
[in] OUTFLAGS
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 1523 of file w3adatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 !
     !/                  +-----------------------------------+
     !/
     !/    26-Dec-2012 : Origination.                        ( version 3.06 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    22-Mar-2021 : Adds WNMEAN, TAUOC parameters       ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Version of W3DIMX for extended ouput arrays only.
     !
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, igrid, w3setg, nk, nx, ny, nsea,    &
          nseal, nspec, nth, e3df, p2msf, us3df,      &
          usspf, gtype, ungtype
     USE w3odatmd, ONLY: iaproc, naproc, ntproc, napfld,             &
          noswll, noextr, undef, flogrd, flogr2,      &
          nogrp, ngrpp
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST
     LOGICAL, INTENT(IN)           :: OUTFLAGS(NOGRP,NGRPP)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID, NXXX, I
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3XDMA')
 #endif
     integer :: memunit
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     memunit = 30000+iaproc
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nadata ) THEN
       WRITE (ndse,1002) imod, nadata
       CALL extcde (2)
     END IF
     !
     IF ( wadats(imod)%AINIT2 ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     nxxx   = nsealm * naproc
     !
     IF ( outflags( 2, 1) ) THEN
       ALLOCATE ( wadats(imod)%XHS(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XHS(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 2) ) THEN
       ALLOCATE ( wadats(imod)%XWLM(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XWLM(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 3) ) THEN
       ALLOCATE ( wadats(imod)%XT02(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XT02(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 4) ) THEN
       ALLOCATE ( wadats(imod)%XT0M1(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XT0M1(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 5) ) THEN
       ALLOCATE ( wadats(imod)%XT01 (nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XT01 (1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 6) .OR. outflags( 2,18) ) THEN
       ! TP output shares FP0 internal field with FP
       ALLOCATE ( wadats(imod)%XFP0(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XFP0(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 7) ) THEN
       ALLOCATE ( wadats(imod)%XTHM(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTHM(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 8) ) THEN
       ALLOCATE ( wadats(imod)%XTHS(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTHS(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 9) ) THEN
       ALLOCATE ( wadats(imod)%XTHP0(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTHP0(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 10) ) THEN
       ALLOCATE ( wadats(imod)%XHSIG(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XHSIG(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 11) ) THEN
       ALLOCATE ( wadats(imod)%XSTMAXE(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XSTMAXE(1) )
     END IF
     !
     IF ( outflags( 2, 12) ) THEN
       ALLOCATE ( wadats(imod)%XSTMAXD(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XSTMAXD(1) )
     END IF
     !
     IF ( outflags( 2, 13) ) THEN
       ALLOCATE ( wadats(imod)%XHMAXE(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XHMAXE(1) )
     END IF
     !
     IF ( outflags( 2, 14) ) THEN
       ALLOCATE ( wadats(imod)%XHCMAXE(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XHCMAXE(1) )
     END IF
     !
     !
     IF ( outflags( 2, 15) ) THEN
       ALLOCATE ( wadats(imod)%XHMAXD(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XHMAXD(1) )
     END IF
     !
     IF ( outflags( 2, 16) ) THEN
       ALLOCATE ( wadats(imod)%XHCMAXD(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XHCMAXD(1) )
     END IF
     !
     IF ( outflags( 2, 17) ) THEN
       ALLOCATE ( wadats(imod)%XWBT (nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XWBT (1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 2, 19) ) THEN
       ALLOCATE ( wadats(imod)%XWNMEAN(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XWNMEAN(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XHS    = undef
     wadats(imod)%XWLM   = undef
     wadats(imod)%XT02   = undef
     wadats(imod)%XT0M1  = undef
     wadats(imod)%XT01   = undef
     wadats(imod)%XFP0   = undef
     wadats(imod)%XTHM   = undef
     wadats(imod)%XTHS   = undef
     wadats(imod)%XTHP0  = undef
     wadats(imod)%XHSIG  = undef
     wadats(imod)%XSTMAXE= undef
     wadats(imod)%XSTMAXD= undef
     wadats(imod)%XHMAXE = undef
     wadats(imod)%XHMAXD = undef
     wadats(imod)%XHCMAXE= undef
     wadats(imod)%XHCMAXD= undef
     wadats(imod)%XWBT   = undef
     wadats(imod)%XWNMEAN= undef
     !
     IF ( outflags( 3, 1) ) THEN
       ALLOCATE ( wadats(imod)%XEF(nxxx,e3df(2,1):e3df(3,1)), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XEF(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( outflags( 3, 2) ) THEN
       ALLOCATE ( wadats(imod)%XTH1M(nxxx,e3df(2,2):e3df(3,2)), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTH1M(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( outflags( 3, 3) ) THEN
       ALLOCATE ( wadats(imod)%XSTH1M(nxxx,e3df(2,3):e3df(3,3)), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XSTH1M(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     IF ( outflags( 3, 4) ) THEN
       ALLOCATE ( wadats(imod)%XTH2M(nxxx,e3df(2,4):e3df(3,4)), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTH2M(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 3, 5) ) THEN
       ALLOCATE ( wadats(imod)%XSTH2M(nxxx,e3df(2,5):e3df(3,5)), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XSTH2M(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XEF     = undef
     wadats(imod)%XTH1M   = undef
     wadats(imod)%XSTH1M  = undef
     wadats(imod)%XTH2M   = undef
     wadats(imod)%XSTH2M  = undef
     !
     IF ( outflags( 4, 1) ) THEN
       ALLOCATE ( wadats(imod)%XPHS(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPHS(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 2) ) THEN
       ALLOCATE ( wadats(imod)%XPTP(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPTP(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 3) ) THEN
       ALLOCATE ( wadats(imod)%XPLP(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPLP(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 4) ) THEN
       ALLOCATE ( wadats(imod)%XPDIR(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPDIR(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 5) ) THEN
       ALLOCATE ( wadats(imod)%XPSI(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPSI(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 6) ) THEN
       ALLOCATE ( wadats(imod)%XPWS(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPWS(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 7) ) THEN
       ALLOCATE ( wadats(imod)%XPTHP0(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPTHP0(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 8) ) THEN
       ALLOCATE ( wadats(imod)%XPQP(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPQP(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4, 9) ) THEN
       ALLOCATE ( wadats(imod)%XPPE(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPPE(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,10) ) THEN
       ALLOCATE ( wadats(imod)%XPGW(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPGW(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,11) ) THEN
       ALLOCATE ( wadats(imod)%XPSW(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPSW(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,12) ) THEN
       ALLOCATE ( wadats(imod)%XPTM1(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPTM1(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,13) ) THEN
       ALLOCATE ( wadats(imod)%XPT1(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPT1(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,14) ) THEN
       ALLOCATE ( wadats(imod)%XPT2(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPT2(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,15) ) THEN
       ALLOCATE ( wadats(imod)%XPEP(nxxx,0:noswll), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPEP(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,16) ) THEN
       ALLOCATE ( wadats(imod)%XPWST(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPWST(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 4,17) ) THEN
       ALLOCATE ( wadats(imod)%XPNR(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPNR(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XPHS   = undef
     wadats(imod)%XPTP   = undef
     wadats(imod)%XPLP   = undef
     wadats(imod)%XPDIR  = undef
     wadats(imod)%XPSI   = undef
     wadats(imod)%XPWS   = undef
     wadats(imod)%XPWST  = undef
     wadats(imod)%XPNR   = undef
     wadats(imod)%XPTHP0 = undef
     wadats(imod)%XPQP   = undef
     wadats(imod)%XPPE   = undef
     wadats(imod)%XPGW   = undef
     wadats(imod)%XPSW   = undef
     wadats(imod)%XPTM1  = undef
     wadats(imod)%XPT1   = undef
     wadats(imod)%XPT2   = undef
     wadats(imod)%XPEP   = undef
     !
     IF ( outflags( 5, 2) ) THEN
       ALLOCATE ( wadats(imod)%XCHARN(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XCHARN(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 5, 3) ) THEN
       ALLOCATE ( wadats(imod)%XCGE(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XCGE(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 5, 4) ) THEN
       ALLOCATE ( wadats(imod)%XPHIAW(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPHIAW(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 5, 5) ) THEN
       ALLOCATE ( wadats(imod)%XTAUWIX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUWIY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTAUWIX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUWIY(1) )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 5, 6) ) THEN
       ALLOCATE ( wadats(imod)%XTAUWNX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUWNY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTAUWNX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUWNY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 5, 7) .OR. outflags( 5, 8) .OR.           &
          outflags( 5, 9) .OR. outflags( 5,10)) THEN
       ALLOCATE ( wadats(imod)%XWHITECAP(nxxx,4), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XWHITECAP(1,4), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 5, 11) ) THEN
       ALLOCATE ( wadats(imod)%XTWS(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTWS(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XCHARN    = undef
     wadats(imod)%XTWS      = undef
     wadats(imod)%XCGE      = undef
     wadats(imod)%XPHIAW    = undef
     wadats(imod)%XTAUWIX   = undef
     wadats(imod)%XTAUWIY   = undef
     wadats(imod)%XTAUWNX   = undef
     wadats(imod)%XTAUWNY   = undef
     wadats(imod)%XWHITECAP = undef
     !
     IF ( outflags( 6, 1) ) THEN
       ALLOCATE ( wadats(imod)%XSXX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XSYY(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XSXY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XSXX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XSYY(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XSXY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 2) ) THEN
       ALLOCATE ( wadats(imod)%XTAUOX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUOY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTAUOX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUOY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 3) ) THEN
       ALLOCATE ( wadats(imod)%XBHD(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XBHD(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 4) ) THEN
       ALLOCATE ( wadats(imod)%XPHIOC(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPHIOC(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 5) ) THEN
       ALLOCATE ( wadats(imod)%XTUSX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTUSY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTUSX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTUSY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 6) ) THEN
       ALLOCATE ( wadats(imod)%XUSSX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XUSSY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XUSSX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XUSSY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 7) ) THEN
       ALLOCATE ( wadats(imod)%XPRMS(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTPMS(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPRMS(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTPMS(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 8) ) THEN
       ALLOCATE ( wadats(imod)%XUS3D(nxxx,2*nk), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XUS3D(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 9) ) THEN
       ALLOCATE ( wadats(imod)%XP2SMS(nxxx,p2msf(2):p2msf(3)), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XP2SMS(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6,10) ) THEN
       ALLOCATE ( wadats(imod)%XTAUICE(nxxx,2), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTAUICE(1,2), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6,11) ) THEN
       ALLOCATE ( wadats(imod)%XPHICE(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPHICE(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 12) ) THEN
       ALLOCATE ( wadats(imod)%XUSSP(nxxx,2*nk), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XUSSP(1,1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 6, 13) ) THEN
       ALLOCATE ( wadats(imod)%XTAUOCX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUOCY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTAUOCX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XTAUOCY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XSXX    = undef
     wadats(imod)%XSYY    = undef
     wadats(imod)%XSXY    = undef
     wadats(imod)%XTAUOX  = undef
     wadats(imod)%XTAUOY  = undef
     wadats(imod)%XBHD    = undef
     wadats(imod)%XPHIOC  = undef
     wadats(imod)%XTUSX   = undef
     wadats(imod)%XTUSY   = undef
     wadats(imod)%XUSSX   = undef
     wadats(imod)%XUSSY   = undef
     wadats(imod)%XPRMS   = undef
     wadats(imod)%XTPMS   = undef
     wadats(imod)%XUS3D   = undef
     wadats(imod)%XP2SMS  = undef
     wadats(imod)%XPHICE  = undef
     wadats(imod)%XTAUICE = undef
     wadats(imod)%XUSSP   = undef
     wadats(imod)%XTAUOCX = undef
     wadats(imod)%XTAUOCY = undef
     !
     IF ( outflags( 7, 1) ) THEN
       ALLOCATE ( wadats(imod)%XABA(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XABD(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XABA(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XABD(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 7, 2) ) THEN
       ALLOCATE ( wadats(imod)%XUBA(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XUBD(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XUBA(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XUBD(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 7, 3) ) THEN
       ALLOCATE ( wadats(imod)%XBEDFORMS(nxxx,3), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XBEDFORMS(1,3), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 7, 4) ) THEN
       ALLOCATE ( wadats(imod)%XPHIBBL(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XPHIBBL(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 7, 5) ) THEN
       ALLOCATE ( wadats(imod)%XTAUBBL(nxxx,2), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XTAUBBL(1,2), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XABA    = undef
     wadats(imod)%XABD    = undef
     wadats(imod)%XUBA    = undef
     wadats(imod)%XUBD    = undef
     wadats(imod)%XBEDFORMS = undef
     wadats(imod)%XPHIBBL = undef
     wadats(imod)%XTAUBBL = undef
     !
     IF ( outflags( 8, 1) ) THEN
       ALLOCATE ( wadats(imod)%XMSSX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XMSSY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XMSSX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XMSSY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 8, 2) ) THEN
       ALLOCATE ( wadats(imod)%XMSCX(nxxx), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XMSCY(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XMSCX(1), stat=istat )
       check_alloc_status( istat )
       ALLOCATE ( wadats(imod)%XMSCY(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 8, 3) ) THEN
       ALLOCATE ( wadats(imod)%XMSSD(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XMSSD(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 8, 4) ) THEN
       ALLOCATE ( wadats(imod)%XMSCD(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XMSCD(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 8,  5) ) THEN
       ALLOCATE ( wadats(imod)%XQP(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XQP(1) )
     END IF
     !
     IF ( outflags( 8,  6) ) THEN
       ALLOCATE ( wadats(imod)%XQKK(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XQKK(1) )
     END IF
     !
     IF ( outflags( 8,  7) ) THEN
       ALLOCATE ( wadats(imod)%XSKEW(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XSKEW(1) )
     END IF
     !
     IF ( outflags( 8,  8) ) THEN
       ALLOCATE ( wadats(imod)%XEMBIA1(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XEMBIA1(1) )
     END IF
     !
     IF ( outflags( 8,  9) ) THEN
       ALLOCATE ( wadats(imod)%XEMBIA2(nxxx) )
     ELSE
       ALLOCATE ( wadats(imod)%XEMBIA2(1) )
     END IF
     !
     wadats(imod)%XMSSX   = undef
     wadats(imod)%XMSSY   = undef
     wadats(imod)%XMSSD   = undef
     wadats(imod)%XMSCX   = undef
     wadats(imod)%XMSCY   = undef
     wadats(imod)%XMSCD   = undef
     wadats(imod)%XQP(1)  = undef
     wadats(imod)%XQKK    = undef
     wadats(imod)%XSKEW   = undef
     wadats(imod)%XEMBIA1 = undef
     wadats(imod)%XEMBIA2 = undef
     !
     IF ( outflags( 9, 1) ) THEN
       ALLOCATE ( wadats(imod)%XDTDYN(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XDTDYN(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 9, 2) ) THEN
       ALLOCATE ( wadats(imod)%XFCUT(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XFCUT(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 9, 3) ) THEN
       ALLOCATE ( wadats(imod)%XCFLXYMAX(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XCFLXYMAX(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 9, 4) ) THEN
       ALLOCATE ( wadats(imod)%XCFLTHMAX(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XCFLTHMAX(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     IF ( outflags( 9, 5) ) THEN
       ALLOCATE ( wadats(imod)%XCFLKMAX(nxxx), stat=istat )
       check_alloc_status( istat )
     ELSE
       ALLOCATE ( wadats(imod)%XCFLKMAX(1), stat=istat )
       check_alloc_status( istat )
     END IF
     !
     wadats(imod)%XDTDYN    = undef
     wadats(imod)%XFCUT     = undef
     wadats(imod)%XCFLXYMAX = undef
     wadats(imod)%XCFLTHMAX = undef
     wadats(imod)%XCFLKMAX  = undef
     !
     DO i=1, noextr
       IF ( outflags(10, i) ) THEN
         ALLOCATE ( wadats(imod)%XUSERO(nxxx,i), stat=istat )
         check_alloc_status( istat )
       ELSE
         ALLOCATE ( wadats(imod)%XUSERO(1,i), stat=istat )
         check_alloc_status( istat )
       END IF
     END DO
     !
     wadats(imod)%XUSERO  = undef
     !
     wadats(imod)%AINIT2 = .true.
     !
 #ifdef W3_T
     WRITE (ndst,9001)
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     call print_memcheck(memunit, 'memcheck_____:'//' W3XDMA')
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3XDMA : GRIDS NOT INITIALIZED *** '/ &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3XDMA : ILLEGAL MODEL NUMBER *** '/  &
          '                    IMOD   = ',i10/                   &
          '                    NADATA = ',i10/)
 1003 FORMAT (/' *** ERROR W3XDMA : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3XDMA : MODEL ',i4)
 9001 FORMAT (' TEST W3XDMA : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3XDMA : POINTERS RESET')
 9003 FORMAT (' TEST W3XDMA : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3XDMA ----------------------------------------------------- /
     !/
References w3gdatmd::e3df, w3servmd::extcde(), w3odatmd::flogr2, w3odatmd::flogrd, w3gdatmd::gtype, w3odatmd::iaproc, w3gdatmd::igrid, nadata, w3odatmd::napfld, w3odatmd::naproc, w3gdatmd::ngrids, w3odatmd::ngrpp, w3gdatmd::nk, w3odatmd::noextr, w3odatmd::nogrp, w3odatmd::noswll, w3gdatmd::nsea, w3gdatmd::nseal, nsealm, w3gdatmd::nspec, w3gdatmd::nth, w3odatmd::ntproc, w3gdatmd::nx, w3gdatmd::ny, w3gdatmd::p2msf, w3servmd::strace(), w3gdatmd::ungtype, w3gdatmd::us3df, w3gdatmd::usspf, w3gdatmd::w3setg(), and wadats.
Referenced by pdlib_field_vec::do_output_exchanges(), and w3initmd::w3mpio().
w3xeta()
subroutine w3adatmd::w3xeta (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Reduced version of W3SETA to point to expended output arrays.
Parameters
[in] IMOD Model number to point to.
[in] NDSE Error output unit number.
[in] NDST Test output unit number.
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 3118 of file w3adatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    25-Dec-2012 : Origination.                        ( version 4.11 )
     !/    30-Apr-2014 : Add s/th1-2m                        ( version 5.01 )
     !/    22-Mar-2021 : Adds WNMEAN, TAUOC parameters       ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Reduced version of W3SETA to point t expended output arrays.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !
     USE w3idatmd, ONLY: inputs
     USE w3gdatmd, ONLY: e3df, p2msf, us3df, usspf, gtype, ungtype
     !
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3XETA')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( nadata .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.nadata ) THEN
       WRITE (ndse,1002) imod, nadata
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model numbers
     !
     iadata = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers
     !
     IF ( ainit2 ) THEN
       !
       hs     => wadats(imod)%XHS
       wlm    => wadats(imod)%XWLM
       t02    => wadats(imod)%XT02
       t0m1   => wadats(imod)%XT0M1
       t01    => wadats(imod)%XT01
       fp0    => wadats(imod)%XFP0
       thm    => wadats(imod)%XTHM
       ths    => wadats(imod)%XTHS
       thp0   => wadats(imod)%XTHP0
       hsig   => wadats(imod)%XHSIG
       stmaxe => wadats(imod)%XSTMAXE
       stmaxd => wadats(imod)%XSTMAXD
       hmaxe  => wadats(imod)%XHMAXE
       hmaxd  => wadats(imod)%XHMAXD
       hcmaxe => wadats(imod)%XHCMAXE
       hcmaxd => wadats(imod)%XHCMAXD
       qp     => wadats(imod)%XQP
       wbt    => wadats(imod)%XWBT
       wnmean => wadats(imod)%XWNMEAN
       !
       ef     => wadats(imod)%XEF
       th1m   => wadats(imod)%XTH1M
       sth1m  => wadats(imod)%XSTH1M
       th2m   => wadats(imod)%XTH2M
       sth2m  => wadats(imod)%XSTH2M
       !
       phs    => wadats(imod)%XPHS
       ptp    => wadats(imod)%XPTP
       plp    => wadats(imod)%XPLP
       pdir   => wadats(imod)%XPDIR
       psi    => wadats(imod)%XPSI
       pws    => wadats(imod)%XPWS
       pwst   => wadats(imod)%XPWST
       pnr    => wadats(imod)%XPNR
       pthp0  => wadats(imod)%XPTHP0
       pqp    => wadats(imod)%XPQP
       ppe    => wadats(imod)%XPPE
       pgw    => wadats(imod)%XPGW
       psw    => wadats(imod)%XPSW
       ptm1   => wadats(imod)%XPTM1
       pt1    => wadats(imod)%XPT1
       pt2    => wadats(imod)%XPT2
       pep    => wadats(imod)%XPEP
       !
       charn    => wadats(imod)%XCHARN
       tws      => wadats(imod)%XTWS
       cge      => wadats(imod)%XCGE
       phiaw    => wadats(imod)%XPHIAW
       tauwix   => wadats(imod)%XTAUWIX
       tauwiy   => wadats(imod)%XTAUWIY
       tauwnx   => wadats(imod)%XTAUWNX
       tauwny   => wadats(imod)%XTAUWNY
       whitecap => wadats(imod)%XWHITECAP
       !
       sxx    => wadats(imod)%XSXX
       syy    => wadats(imod)%XSYY
       sxy    => wadats(imod)%XSXY
       tauox  => wadats(imod)%XTAUOX
       tauoy  => wadats(imod)%XTAUOY
       bhd    => wadats(imod)%XBHD
       phioc  => wadats(imod)%XPHIOC
       tusx   => wadats(imod)%XTUSX
       tusy   => wadats(imod)%XTUSY
       ussx   => wadats(imod)%XUSSX
       ussy   => wadats(imod)%XUSSY
       prms   => wadats(imod)%XPRMS
       tpms   => wadats(imod)%XTPMS
       p2sms  => wadats(imod)%XP2SMS
       us3d   => wadats(imod)%XUS3D
       phice  => wadats(imod)%XPHICE
       tauice => wadats(imod)%XTAUICE
       ussp   => wadats(imod)%XUSSP
       tauocx => wadats(imod)%XTAUOCX
       tauocy => wadats(imod)%XTAUOCY
       aba    => wadats(imod)%XABA
       abd    => wadats(imod)%XABD
       uba    => wadats(imod)%XUBA
       ubd    => wadats(imod)%XUBD
       bedforms=> wadats(imod)%XBEDFORMS
       phibbl => wadats(imod)%XPHIBBL
       taubbl => wadats(imod)%XTAUBBL
       !
       mssx   => wadats(imod)%XMSSX
       mssy   => wadats(imod)%XMSSY
       mssd   => wadats(imod)%XMSSD
       mscx   => wadats(imod)%XMSCX
       mscy   => wadats(imod)%XMSCY
       mscd   => wadats(imod)%XMSCD
       qkk    => wadats(imod)%XQKK
       skew   => wadats(imod)%XSKEW
       embia1 => wadats(imod)%XEMBIA1
       embia2 => wadats(imod)%XEMBIA2
       !
       dtdyn    => wadats(imod)%XDTDYN
       fcut     => wadats(imod)%XFCUT
       cflxymax => wadats(imod)%XCFLXYMAX
       cflthmax => wadats(imod)%XCFLTHMAX
       cflkmax =>  wadats(imod)%XCFLKMAX
       !
       usero  => wadats(imod)%XUSERO
       !
     END IF
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3XETA : GRIDS NOT INITIALIZED *** '/ &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3XETA : ILLEGAL MODEL NUMBER *** '/  &
          '                    IMOD   = ',i10/                   &
          '                    NADATA = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3XETA : MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of W3XETA ----------------------------------------------------- /
     !/
References aba, abd, ainit2, bedforms, bhd, cflkmax, cflthmax, cflxymax, cge, charn, dtdyn, w3gdatmd::e3df, ef, embia1, embia2, w3servmd::extcde(), fcut, fp0, w3gdatmd::gtype, hcmaxd, hcmaxe, hmaxd, hmaxe, hs, hsig, iadata, w3idatmd::inputs, mscd, mscx, mscy, mssd, mssx, mssy, nadata, w3gdatmd::p2msf, p2sms, pdir, pep, pgw, phiaw, phibbl, phice, phioc, phs, plp, pnr, ppe, pqp, prms, psi, psw, pt1, pt2, pthp0, ptm1, ptp, pws, pwst, qkk, qp, skew, sth1m, sth2m, stmaxd, stmaxe, w3servmd::strace(), sxx, sxy, syy, t01, t02, t0m1, taubbl, tauice, tauocx, tauocy, tauox, tauoy, tauwix, tauwiy, tauwnx, tauwny, th1m, th2m, thm, thp0, ths, tpms, tusx, tusy, tws, uba, ubd, w3gdatmd::ungtype, us3d, w3gdatmd::us3df, usero, ussp, w3gdatmd::usspf, ussx, ussy, wadats, wbt, whitecap, wlm, and wnmean.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), and w3initmd::w3mpio().
Variable Documentation
aba
real, dimension(:), pointer w3adatmd::aba
Definition at line 614 of file w3adatmd.F90.
   REAL, POINTER           :: ABA(:), ABD(:), UBA(:), UBD(:),      &
        BEDFORMS(:,:), PHIBBL(:), TAUBBL(:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), wmesmfmd::fieldindex(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
abd
real, dimension(:), pointer w3adatmd::abd
Definition at line 614 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
af11
real, dimension(:), pointer w3adatmd::af11
Definition at line 670 of file w3adatmd.F90.
   REAL, POINTER           :: AF11(:)
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ainit
logical, pointer w3adatmd::ainit
Definition at line 688 of file w3adatmd.F90.
   LOGICAL, POINTER        :: AINIT, AINIT2, FL_ALL, FLCOLD, FLIWND
Referenced by w3iogomd::w3iogo(), and w3seta().
ainit2
logical, pointer w3adatmd::ainit2
Definition at line 688 of file w3adatmd.F90.
Referenced by w3seta(), and w3xeta().
alpha
real, dimension(:,:), pointer w3adatmd::alpha
Definition at line 687 of file w3adatmd.F90.
   REAL, POINTER           :: ALPHA(:,:)
Referenced by w3seta(), and w3wavemd::w3wave().
as
real, dimension(:), pointer w3adatmd::as
Definition at line 584 of file w3adatmd.F90.
Referenced by gxoutf(), w3exgi(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iotrmd::w3iotr(), w3ounf(), w3outf(), w3seta(), w3updtmd::w3uwnd(), and w3wavemd::w3wave().
as0
real, dimension(:), pointer w3adatmd::as0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3uwnd().
asi
real, dimension(:), pointer w3adatmd::asi
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3uwnd().
atrnx
real, dimension(:,:), pointer w3adatmd::atrnx
Definition at line 578 of file w3adatmd.F90.
Referenced by w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3pro3md::w3mapt(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3utrn(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
atrny
real, dimension(:,:), pointer w3adatmd::atrny
Definition at line 578 of file w3adatmd.F90.
Referenced by w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3pro3md::w3mapt(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3utrn(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
awg1
real, pointer w3adatmd::awg1
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg2
real, pointer w3adatmd::awg2
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg3
real, pointer w3adatmd::awg3
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg4
real, pointer w3adatmd::awg4
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg5
real, pointer w3adatmd::awg5
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg6
real, pointer w3adatmd::awg6
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg7
real, pointer w3adatmd::awg7
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
awg8
real, pointer w3adatmd::awg8
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
bedforms
real, dimension(:,:), pointer w3adatmd::bedforms
Definition at line 614 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
bhd
real, dimension(:), pointer w3adatmd::bhd
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
bispl
integer, dimension(:), pointer w3adatmd::bispl
Definition at line 680 of file w3adatmd.F90.
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
bstat
integer, dimension(:), pointer w3adatmd::bstat
Definition at line 680 of file w3adatmd.F90.
   INTEGER, POINTER        :: BSTAT(:), BISPL(:)
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
ca0
real, dimension(:), pointer w3adatmd::ca0
Definition at line 578 of file w3adatmd.F90.
   REAL, POINTER           :: CA0(:), CAI(:), CD0(:), CDI(:),      &
        UA0(:), UAI(:), UD0(:), UDI(:),      &
        MA0(:), MAI(:), RA0(:), RAI(:),      &
        MD0(:), MDI(:), AS0(:), ASI(:),      &
        ATRNX(:,:), ATRNY(:,:)
Referenced by w3seta(), and w3updtmd::w3ucur().
cai
real, dimension(:), pointer w3adatmd::cai
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3ucur().
cd0
real, dimension(:), pointer w3adatmd::cd0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3ucur().
cdi
real, dimension(:), pointer w3adatmd::cdi
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3ucur().
cflkmax
real, dimension(:), pointer w3adatmd::cflkmax
Definition at line 620 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
cflthmax
real, dimension(:), pointer w3adatmd::cflthmax
Definition at line 620 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
cflxymax
real, dimension(:), pointer w3adatmd::cflxymax
Definition at line 620 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), w3xeta(), and w3profsmd::w3xypug().
cg
real, dimension(:,:), pointer w3adatmd::cg
Definition at line 575 of file w3adatmd.F90.
   REAL, POINTER           :: CG(:,:), WN(:,:)
Referenced by pdlib_w3profsmd::action_limiter_local(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), wmesmfmd::fieldindex(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3iogomd::skewness(), w3wavset::trig_compute_lh_stress(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iotrmd::w3iotr(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3ubpt(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), and wminiomd::wmiohs().
cge
real, dimension(:), pointer w3adatmd::cge
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
charn
real, dimension(:), pointer w3adatmd::charn
Definition at line 603 of file w3adatmd.F90.
   REAL, POINTER           :: CHARN(:), CGE(:), PHIAW(:),          &
        TAUWIX(:), TAUWIY(:), TAUWNX(:),     &
        TAUWNY(:), WHITECAP(:,:), TWS(:)
Referenced by pdlib_field_vec::do_output_exchanges(), wmesmfmd::fieldindex(), gxoutf(), w3agcmmd::snd_fields_to_atmos(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), w3updtmd::w3uice(), w3wavemd::w3wave(), and w3xeta().
cx
real, dimension(:), pointer w3adatmd::cx
Definition at line 584 of file w3adatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), gxoutf(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3psmcmd::smcdcxy(), w3agcmmd::snd_fields_to_atmos(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3exgi(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3ucur(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
cy
real, dimension(:), pointer w3adatmd::cy
Definition at line 584 of file w3adatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_vec(), gxoutf(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3psmcmd::smcdcxy(), w3agcmmd::snd_fields_to_atmos(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3exgi(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3ucur(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
dal1
real, pointer w3adatmd::dal1
Definition at line 666 of file w3adatmd.F90.
   REAL, POINTER           :: DAL1, DAL2, DAL3,                    &
        AWG1, AWG2, AWG3, AWG4, AWG5, AWG6,  &
        AWG7, AWG8, SWG1, SWG2, SWG3, SWG4,  &
        SWG5, SWG6, SWG7, SWG8
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
dal2
real, pointer w3adatmd::dal2
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
dal3
real, pointer w3adatmd::dal3
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
dcdx
real, dimension(:,:,:), pointer w3adatmd::dcdx
Definition at line 629 of file w3adatmd.F90.
   REAL, POINTER           :: DCDX(:,:,:), DCDY(:,:,:)
Referenced by w3parall::prop_refraction_pr1(), w3seta(), and w3wavemd::w3wave().
dcdy
real, dimension(:,:,:), pointer w3adatmd::dcdy
Definition at line 629 of file w3adatmd.F90.
Referenced by w3parall::prop_refraction_pr1(), w3seta(), and w3wavemd::w3wave().
dcxdx
real, dimension(:,:), pointer w3adatmd::dcxdx
Definition at line 627 of file w3adatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcdcxy(), w3seta(), and w3wavemd::w3wave().
dcxdy
real, dimension(:,:), pointer w3adatmd::dcxdy
Definition at line 627 of file w3adatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcdcxy(), w3seta(), and w3wavemd::w3wave().
dcydx
real, dimension(:,:), pointer w3adatmd::dcydx
Definition at line 627 of file w3adatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcdcxy(), w3seta(), and w3wavemd::w3wave().
dcydy
real, dimension(:,:), pointer w3adatmd::dcydy
Definition at line 627 of file w3adatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcdcxy(), w3seta(), and w3wavemd::w3wave().
dddx
real, dimension(:,:), pointer w3adatmd::dddx
Definition at line 627 of file w3adatmd.F90.
   REAL, POINTER           :: DDDX(:,:), DDDY(:,:), DCXDX(:,:),    &
        DCYDX(:,:), DCXDY(:,:), DCYDY(:,:)
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcdhxy(), w3seta(), and w3wavemd::w3wave().
dddy
real, dimension(:,:), pointer w3adatmd::dddy
Definition at line 627 of file w3adatmd.F90.
Referenced by w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3psmcmd::smcdhxy(), w3seta(), and w3wavemd::w3wave().
dhdx
real, dimension(:), pointer w3adatmd::dhdx
Definition at line 631 of file w3adatmd.F90.
   REAL, POINTER         :: DHDX(:), DHDY(:), DHLMT(:,:)
Referenced by w3psmcmd::smcdhxy(), w3seta(), and w3wavemd::w3wave().
dhdy
real, dimension(:), pointer w3adatmd::dhdy
Definition at line 631 of file w3adatmd.F90.
Referenced by w3psmcmd::smcdhxy(), w3seta(), and w3wavemd::w3wave().
dhlmt
real, dimension(:,:), pointer w3adatmd::dhlmt
Definition at line 631 of file w3adatmd.F90.
Referenced by w3psmcmd::smcdhxy(), w3seta(), and w3wavemd::w3wave().
dtdyn
real, dimension(:), pointer w3adatmd::dtdyn
Definition at line 620 of file w3adatmd.F90.
   REAL, POINTER           :: DTDYN(:), FCUT(:), CFLXYMAX(:),      &
        CFLTHMAX(:), CFLKMAX(:)
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
dw
real, dimension(:), pointer w3adatmd::dw
Definition at line 584 of file w3adatmd.F90.
   REAL, POINTER           :: DW(:), UA(:), UD(:), U10(:), U10D(:),&
        AS(:), CX(:), CY(:), TAUA(:), TAUADIR(:)
Referenced by pdlib_w3profsmd::block_solver_init(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), w3wavset::fd_wave_setup_compute_system(), wmesmfmd::fieldindex(), gxoutf(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), pdlib_w3profsmd::set_iobdp_pdlib(), pdlib_w3profsmd::set_iobpa_pdlib(), w3profsmd::setdepth(), w3psmcmd::smcdhxy(), w3wavset::trig_compute_lh_stress(), w3wavset::trig_wave_setup_computation(), w3profsmd::w3cflug(), w3iosfmd::w3cprt(), w3exgi(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), w3updtmd::w3ulev(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3profsmd::w3xypfsn2(), and w3profsmd::w3xypug().
ef
real, dimension(:,:), pointer w3adatmd::ef
Definition at line 594 of file w3adatmd.F90.
   REAL, POINTER           :: EF(:,:), TH1M(:,:), STH1M(:,:),      &
        TH2M(:,:), STH2M(:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
embia1
real, dimension(:), pointer w3adatmd::embia1
Definition at line 617 of file w3adatmd.F90.
Referenced by w3iogomd::skewness(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), and w3xeta().
embia2
real, dimension(:), pointer w3adatmd::embia2
Definition at line 617 of file w3adatmd.F90.
Referenced by w3iogomd::skewness(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), and w3xeta().
facvx
real, dimension(:), pointer w3adatmd::facvx
Definition at line 636 of file w3adatmd.F90.
   REAL, POINTER           :: FACVX(:), FACVY(:)
Referenced by w3pro1md::w3map1(), w3seta(), and w3pro1md::w3xyp1().
facvy
real, dimension(:), pointer w3adatmd::facvy
Definition at line 636 of file w3adatmd.F90.
Referenced by w3pro1md::w3map1(), w3seta(), and w3pro1md::w3xyp1().
fcut
real, dimension(:), pointer w3adatmd::fcut
Definition at line 620 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), w3wavemd::w3wave(), and w3xeta().
fl_all
logical, pointer w3adatmd::fl_all
Definition at line 688 of file w3adatmd.F90.
Referenced by w3dima(), and w3seta().
flcold
logical, pointer w3adatmd::flcold
Definition at line 688 of file w3adatmd.F90.
Referenced by w3initmd::w3init(), w3seta(), and w3wavemd::w3wave().
fliwnd
logical, pointer w3adatmd::fliwnd
Definition at line 688 of file w3adatmd.F90.
Referenced by w3initmd::w3init(), w3seta(), and w3wavemd::w3wave().
fp0
real, dimension(:), pointer w3adatmd::fp0
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3agcmmd::snd_fields_to_atmos(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
gstore
real, dimension(:,:), pointer w3adatmd::gstore
Definition at line 682 of file w3adatmd.F90.
   REAL, POINTER           :: GSTORE(:,:), SSTORE(:,:)
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), and w3seta().
hcmaxd
real, dimension(:), pointer w3adatmd::hcmaxd
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
hcmaxe
real, dimension(:), pointer w3adatmd::hcmaxe
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
hmaxd
real, dimension(:), pointer w3adatmd::hmaxd
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
hmaxe
real, dimension(:), pointer w3adatmd::hmaxe
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
hs
real, dimension(:), pointer w3adatmd::hs
Definition at line 587 of file w3adatmd.F90.
   REAL, POINTER           :: HS(:), WLM(:),  T02(:), T0M1(:),     &
        T01 (:), FP0(:), THM(:), THS(:),     &
        THP0(:), HSIG(:),                    &
        STMAXE(:), STMAXD(:), HMAXE(:),      &
        HCMAXE(:), HMAXD(:), HCMAXD(:),      &
        QP(:), WBT(:), WNMEAN(:)
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3agcmmd::snd_fields_to_atmos(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), w3updtmd::w3ulev(), and w3xeta().
hsig
real, dimension(:), pointer w3adatmd::hsig
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
iadata
integer w3adatmd::iadata = -1
Definition at line 374 of file w3adatmd.F90.
Referenced by w3seta(), w3wavemd::w3wave(), and w3xeta().
iappro
integer, dimension(:), pointer w3adatmd::iappro
Definition at line 674 of file w3adatmd.F90.
   INTEGER, POINTER        :: IAPPRO(:)
Referenced by w3initmd::w3init(), w3initmd::w3mpii(), w3seta(), and w3wavemd::w3wave().
ibfloc
integer, pointer w3adatmd::ibfloc
Definition at line 676 of file w3adatmd.F90.
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
ic11
integer, dimension(:), pointer w3adatmd::ic11
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic12
integer, dimension(:), pointer w3adatmd::ic12
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic21
integer, dimension(:), pointer w3adatmd::ic21
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic22
integer, dimension(:), pointer w3adatmd::ic22
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic31
integer, dimension(:), pointer w3adatmd::ic31
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic32
integer, dimension(:), pointer w3adatmd::ic32
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic3cg
real, dimension(:,:), pointer w3adatmd::ic3cg
Definition at line 576 of file w3adatmd.F90.
Referenced by w3sic3md::ic3table_cheng(), w3sic3md::w3ic3wncg_cheng(), and w3seta().
ic3wn_i
real, dimension(:,:), pointer w3adatmd::ic3wn_i
Definition at line 576 of file w3adatmd.F90.
Referenced by w3sic3md::ic3table_cheng(), w3sic3md::w3ic3wncg_cheng(), and w3seta().
ic3wn_r
real, dimension(:,:), pointer w3adatmd::ic3wn_r
Definition at line 576 of file w3adatmd.F90.
   REAL, POINTER           :: IC3WN_R(:,:), IC3WN_I(:,:), IC3CG(:,:)
Referenced by w3sic3md::ic3table_cheng(), w3sic3md::w3ic3wncg_cheng(), and w3seta().
ic41
integer, dimension(:), pointer w3adatmd::ic41
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic42
integer, dimension(:), pointer w3adatmd::ic42
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic51
integer, dimension(:), pointer w3adatmd::ic51
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic52
integer, dimension(:), pointer w3adatmd::ic52
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic61
integer, dimension(:), pointer w3adatmd::ic61
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic62
integer, dimension(:), pointer w3adatmd::ic62
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic71
integer, dimension(:), pointer w3adatmd::ic71
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic72
integer, dimension(:), pointer w3adatmd::ic72
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic81
integer, dimension(:), pointer w3adatmd::ic81
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ic82
integer, dimension(:), pointer w3adatmd::ic82
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
idlast
integer, pointer w3adatmd::idlast
Definition at line 686 of file w3adatmd.F90.
Referenced by w3seta(), and w3wavemd::w3wave().
im11
integer, dimension(:), pointer w3adatmd::im11
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im12
integer, dimension(:), pointer w3adatmd::im12
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im13
integer, dimension(:), pointer w3adatmd::im13
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im14
integer, dimension(:), pointer w3adatmd::im14
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im21
integer, dimension(:), pointer w3adatmd::im21
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im22
integer, dimension(:), pointer w3adatmd::im22
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im23
integer, dimension(:), pointer w3adatmd::im23
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
im24
integer, dimension(:), pointer w3adatmd::im24
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip11
integer, dimension(:), pointer w3adatmd::ip11
Definition at line 658 of file w3adatmd.F90.
   INTEGER, POINTER        :: IP11(:), IP12(:), IP13(:), IP14(:),  &
        IM11(:), IM12(:), IM13(:), IM14(:),  &
        IP21(:), IP22(:), IP23(:), IP24(:),  &
        IM21(:), IM22(:), IM23(:), IM24(:),  &
        IC11(:), IC12(:), IC21(:), IC22(:),  &
        IC31(:), IC32(:), IC41(:), IC42(:),  &
        IC51(:), IC52(:), IC61(:), IC62(:),  &
        IC71(:), IC72(:), IC81(:), IC82(:)
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip12
integer, dimension(:), pointer w3adatmd::ip12
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip13
integer, dimension(:), pointer w3adatmd::ip13
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip14
integer, dimension(:), pointer w3adatmd::ip14
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip21
integer, dimension(:), pointer w3adatmd::ip21
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip22
integer, dimension(:), pointer w3adatmd::ip22
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip23
integer, dimension(:), pointer w3adatmd::ip23
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ip24
integer, dimension(:), pointer w3adatmd::ip24
Definition at line 658 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
ipass
integer, pointer w3adatmd::ipass
Definition at line 686 of file w3adatmd.F90.
Referenced by wmesmfmd::createexpmesh(), w3seta(), and w3wavemd::w3wave().
irqsg1
integer, dimension(:,:), pointer w3adatmd::irqsg1
Definition at line 681 of file w3adatmd.F90.
   INTEGER, POINTER        :: IRQSG1(:,:), IRQSG2(:,:)
Referenced by w3initmd::w3mpii(), w3seta(), and w3wavemd::w3wave().
irqsg2
integer, dimension(:,:), pointer w3adatmd::irqsg2
Definition at line 681 of file w3adatmd.F90.
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
is0
integer, dimension(:), pointer w3adatmd::is0
Definition at line 635 of file w3adatmd.F90.
   INTEGER, POINTER        :: IS0(:), IS2(:)
Referenced by w3pro1md::w3ktp1(), w3pro1md::w3map1(), and w3seta().
is2
integer, dimension(:), pointer w3adatmd::is2
Definition at line 635 of file w3adatmd.F90.
Referenced by w3pro1md::w3ktp1(), w3pro1md::w3map1(), and w3seta().
isploc
integer, pointer w3adatmd::isploc
Definition at line 676 of file w3adatmd.F90.
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
iter
integer, dimension(:,:), pointer w3adatmd::iter
Definition at line 654 of file w3adatmd.F90.
   INTEGER, POINTER        :: ITER(:,:)
Referenced by pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3seta(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
itime
integer, pointer w3adatmd::itime
Definition at line 686 of file w3adatmd.F90.
   INTEGER, POINTER        :: ITIME, IPASS, IDLAST, NSEALM
Referenced by pdlib_w3profsmd::pdlib_w3xypug(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3psmcmd::w3krtn(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3psmcmd::w3psmc(), w3seta(), w3wavemd::w3wave(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and w3profsmd::w3xypug().
ma0
real, dimension(:), pointer w3adatmd::ma0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3utau().
mai
real, dimension(:), pointer w3adatmd::mai
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3utau().
mapaxy
integer, dimension(:), pointer w3adatmd::mapaxy
Definition at line 642 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
mapcxy
integer, dimension(:), pointer w3adatmd::mapcxy
Definition at line 649 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro3md::w3map3(), w3seta(), and w3pro3md::w3xyp3().
mapth2
integer, dimension(:), pointer w3adatmd::mapth2
Definition at line 642 of file w3adatmd.F90.
Referenced by w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro2md::w3map2(), w3pro3md::w3map3(), and w3seta().
maptrn
logical, dimension(:), pointer w3adatmd::maptrn
Definition at line 651 of file w3adatmd.F90.
   LOGICAL, POINTER        :: MAPTRN(:)
Referenced by w3pro3md::w3cflxy(), w3pro3md::w3mapt(), w3seta(), and w3pro3md::w3xyp3().
mapwn2
integer, dimension(:), pointer w3adatmd::mapwn2
Definition at line 642 of file w3adatmd.F90.
Referenced by w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro2md::w3map2(), w3pro3md::w3map3(), and w3seta().
mapx2
integer, dimension(:), pointer w3adatmd::mapx2
Definition at line 642 of file w3adatmd.F90.
   INTEGER, POINTER        :: MAPX2(:), MAPY2(:), MAPAXY(:),       &
        MAPXY(:), MAPTH2(:), MAPWN2(:)
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
mapxy
integer, dimension(:), pointer w3adatmd::mapxy
Definition at line 642 of file w3adatmd.F90.
Referenced by w3pro2md::w3map2(), w3seta(), and w3pro2md::w3xyp2().
mapy2
integer, dimension(:), pointer w3adatmd::mapy2
Definition at line 642 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
md0
real, dimension(:), pointer w3adatmd::md0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3utau().
mdi
real, dimension(:), pointer w3adatmd::mdi
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3utau().
mpi_comm_wave
integer, pointer w3adatmd::mpi_comm_wave
Definition at line 676 of file w3adatmd.F90.
   INTEGER, POINTER        :: MPI_COMM_WAVE, MPI_COMM_WCMP,        &
        WW3_FIELD_VEC, WW3_SPEC_VEC,         &
        NRQSG1, NRQSG2, IBFLOC, ISPLOC,      &
        NSPLOC
Referenced by yowfunction::computelistnp_listnpa_listiplg(), pdlib_field_vec::do_output_exchanges(), pdlib_w3profsmd::pdlib_init(), w3parall::set_up_nseal_nsealm(), w3parall::synchronize_ipgl_etc_array(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3initmd::w3init(), w3iogrmd::w3iogr(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3seta(), w3wavemd::w3wave(), and wmwavemd::wmwout().
mpi_comm_wcmp
integer, pointer w3adatmd::mpi_comm_wcmp
Definition at line 676 of file w3adatmd.F90.
Referenced by pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), yowfunction::computelistnp_listnpa_listiplg_kernel(), pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_wave_setup_computation(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::scal_integral_print_general(), w3parall::set_up_nseal_nsealm(), w3parall::synchronize_global_array(), w3parall::synchronize_ipgl_etc_array(), pdlib_w3profsmd::test_mpi_status(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_scalar_prod(), w3initmd::w3init(), w3iorsmd::w3iors(), w3seta(), and pdlib_w3profsmd::write_var_to_text_file().
mpibuf
integer, parameter w3adatmd::mpibuf = 6
Definition at line 376 of file w3adatmd.F90.
   INTEGER, PARAMETER      :: MPIBUF = 6
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), and w3psmcmd::w3scatsmc().
mscd
real, dimension(:), pointer w3adatmd::mscd
Definition at line 617 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
mscx
real, dimension(:), pointer w3adatmd::mscx
Definition at line 617 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
mscy
real, dimension(:), pointer w3adatmd::mscy
Definition at line 617 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
mssd
real, dimension(:), pointer w3adatmd::mssd
Definition at line 617 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
mssx
real, dimension(:), pointer w3adatmd::mssx
Definition at line 617 of file w3adatmd.F90.
   REAL, POINTER           :: MSSX(:), MSSY(:), MSSD(:),           &
        MSCX(:), MSCY(:), MSCD(:), QKK(:), SKEW(:), EMBIA1(:), EMBIA2(:)
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
mssy
real, dimension(:), pointer w3adatmd::mssy
Definition at line 617 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
nact
integer pointer w3adatmd::nact
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nadata
integer w3adatmd::nadata = -1
Definition at line 374 of file w3adatmd.F90.
   INTEGER                 :: NADATA = -1, iadata = -1
Referenced by w3dima(), w3dmnl(), w3naux(), w3seta(), w3xdma(), and w3xeta().
ncent
integer, pointer w3adatmd::ncent
Definition at line 647 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro3md::w3map3(), w3seta(), and w3pro3md::w3xyp3().
nfr
integer, pointer w3adatmd::nfr
Definition at line 657 of file w3adatmd.F90.
   INTEGER, POINTER        :: NFR, NFRHGH, NFRCHG, NSPECX, NSPECY
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
nfrchg
integer, pointer w3adatmd::nfrchg
Definition at line 657 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
nfrhgh
integer, pointer w3adatmd::nfrhgh
Definition at line 657 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
nlinit
logical, pointer w3adatmd::nlinit
Definition at line 671 of file w3adatmd.F90.
   LOGICAL, POINTER        :: NLINIT
Referenced by w3seta().
nmx0
integer pointer w3adatmd::nmx0
Definition at line 640 of file w3adatmd.F90.
   INTEGER, POINTER        :: NMX0, NMX1, NMX2, NMY0, NMY1, NMY2,  &
        NACT, NMXY
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nmx1
integer pointer w3adatmd::nmx1
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nmx2
integer pointer w3adatmd::nmx2
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nmxy
integer, pointer w3adatmd::nmxy
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro2md::w3map2(), w3seta(), and w3pro2md::w3xyp2().
nmy0
integer pointer w3adatmd::nmy0
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nmy1
integer pointer w3adatmd::nmy1
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nmy2
integer pointer w3adatmd::nmy2
Definition at line 640 of file w3adatmd.F90.
Referenced by w3pro3md::w3cflxy(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3seta(), w3pro2md::w3xyp2(), and w3pro3md::w3xyp3().
nrqsg1
integer, pointer w3adatmd::nrqsg1
Definition at line 676 of file w3adatmd.F90.
Referenced by w3initmd::w3mpii(), w3seta(), and w3wavemd::w3wave().
nrqsg2
integer, pointer w3adatmd::nrqsg2
Definition at line 676 of file w3adatmd.F90.
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
nsealm
integer, pointer w3adatmd::nsealm
Definition at line 686 of file w3adatmd.F90.
Referenced by pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3triamd::ug_gradients(), pdlib_field_vec::unst_pdlib_read_from_file(), w3iosfmd::w3cprt(), w3dima(), w3initmd::w3init(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3iogomd::w3outg(), w3seta(), w3updtmd::w3uice(), w3uprstr(), and w3xdma().
nspecx
integer, pointer w3adatmd::nspecx
Definition at line 657 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3dmnl(), w3seta(), and w3snl1md::w3snl1().
nspecy
integer, pointer w3adatmd::nspecy
Definition at line 657 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
nsploc
integer, pointer w3adatmd::nsploc
Definition at line 676 of file w3adatmd.F90.
Referenced by w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
p2sms
real, dimension(:,:), pointer w3adatmd::p2sms
Definition at line 612 of file w3adatmd.F90.
   REAL, POINTER           :: P2SMS(:,:), US3D(:,:), USSP(:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pdir
real, dimension(:,:), pointer w3adatmd::pdir
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pep
real, dimension(:,:), pointer w3adatmd::pep
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pgw
real, dimension(:,:), pointer w3adatmd::pgw
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
phiaw
real, dimension(:), pointer w3adatmd::phiaw
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
phibbl
real, dimension(:), pointer w3adatmd::phibbl
Definition at line 614 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
phice
real, dimension(:), pointer w3adatmd::phice
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
phioc
real, dimension(:), pointer w3adatmd::phioc
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
phs
real, dimension(:,:), pointer w3adatmd::phs
Definition at line 597 of file w3adatmd.F90.
   REAL, POINTER           :: PHS(:,:), PTP(:,:), PLP(:,:),        &
        PDIR(:,:), PSI(:,:), PWS(:,:),       &
        PWST(:), PNR(:), PGW(:,:), PSW(:,:), &
        PTHP0(:,:), PQP(:,:), PPE(:,:),      &
        PTM1(:,:), PT1(:,:), PT2(:,:),PEP(:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
plp
real, dimension(:,:), pointer w3adatmd::plp
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pnr
real, dimension(:), pointer w3adatmd::pnr
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ppe
real, dimension(:,:), pointer w3adatmd::ppe
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pqp
real, dimension(:,:), pointer w3adatmd::pqp
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
prms
real, dimension(:), pointer w3adatmd::prms
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
psi
real, dimension(:,:), pointer w3adatmd::psi
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
psw
real, dimension(:,:), pointer w3adatmd::psw
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pt1
real, dimension(:,:), pointer w3adatmd::pt1
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pt2
real, dimension(:,:), pointer w3adatmd::pt2
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pthp0
real, dimension(:,:), pointer w3adatmd::pthp0
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ptm1
real, dimension(:,:), pointer w3adatmd::ptm1
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ptp
real, dimension(:,:), pointer w3adatmd::ptp
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pws
real, dimension(:,:), pointer w3adatmd::pws
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
pwst
real, dimension(:), pointer w3adatmd::pwst
Definition at line 597 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
qkk
real, dimension(:), pointer w3adatmd::qkk
Definition at line 617 of file w3adatmd.F90.
Referenced by w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
qp
real, dimension(:), pointer w3adatmd::qp
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ra0
real, dimension(:), pointer w3adatmd::ra0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3urho().
rai
real, dimension(:), pointer w3adatmd::rai
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3urho().
skew
real, dimension(:), pointer w3adatmd::skew
Definition at line 617 of file w3adatmd.F90.
Referenced by w3iogomd::skewness(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), and w3xeta().
sppnt
real, dimension(:,:,:), pointer w3adatmd::sppnt
Definition at line 684 of file w3adatmd.F90.
   REAL, POINTER           :: SPPNT(:,:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3iopomd::w3iope(), w3initmd::w3mpio(), w3initmd::w3mpip(), and w3seta().
sstore
real, dimension(:,:), pointer w3adatmd::sstore
Definition at line 682 of file w3adatmd.F90.
Referenced by w3initmd::w3mpii(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), and w3seta().
sth1m
real, dimension(:,:), pointer w3adatmd::sth1m
Definition at line 594 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
sth2m
real, dimension(:,:), pointer w3adatmd::sth2m
Definition at line 594 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
stmaxd
real, dimension(:), pointer w3adatmd::stmaxd
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
stmaxe
real, dimension(:), pointer w3adatmd::stmaxe
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
swg1
real, pointer w3adatmd::swg1
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg2
real, pointer w3adatmd::swg2
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg3
real, pointer w3adatmd::swg3
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg4
real, pointer w3adatmd::swg4
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg5
real, pointer w3adatmd::swg5
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg6
real, pointer w3adatmd::swg6
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg7
real, pointer w3adatmd::swg7
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
swg8
real, pointer w3adatmd::swg8
Definition at line 666 of file w3adatmd.F90.
Referenced by w3snl1md::insnl1(), w3seta(), and w3snl1md::w3snl1().
sxx
real, dimension(:), pointer w3adatmd::sxx
Definition at line 607 of file w3adatmd.F90.
   REAL, POINTER           :: SXX(:), SYY(:), SXY(:), TAUOX(:),    &
        TAUOY(:), BHD(:), PHIOC(:),          &
        TUSX(:), TUSY(:), USSX(:), USSY(:),  &
        TAUOCX(:), TAUOCY(:), PRMS(:),       &
        TPMS(:), PHICE(:), TAUICE(:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_compute_lh_stress(), wmesmfmd::fieldindex(), gxoutf(), w3wavset::trig_compute_lh_stress(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
sxy
real, dimension(:), pointer w3adatmd::sxy
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_compute_lh_stress(), wmesmfmd::fieldindex(), gxoutf(), w3wavset::trig_compute_lh_stress(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
syy
real, dimension(:), pointer w3adatmd::syy
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_compute_lh_stress(), wmesmfmd::fieldindex(), gxoutf(), w3wavset::trig_compute_lh_stress(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
t01
real, dimension (:), pointer w3adatmd::t01
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
t02
real, dimension(:), pointer w3adatmd::t02
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
t0m1
real, dimension(:), pointer w3adatmd::t0m1
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
taua
real, dimension(:), pointer w3adatmd::taua
Definition at line 584 of file w3adatmd.F90.
Referenced by gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3ounf(), w3outf(), w3seta(), w3updtmd::w3utau(), and w3wavemd::w3wave().
tauadir
real, dimension(:), pointer w3adatmd::tauadir
Definition at line 584 of file w3adatmd.F90.
Referenced by gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3ounf(), w3outf(), w3seta(), w3updtmd::w3utau(), and w3wavemd::w3wave().
taubbl
real, dimension(:,:), pointer w3adatmd::taubbl
Definition at line 614 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauice
real, dimension(:,:), pointer w3adatmd::tauice
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3igcmmd::snd_fields_to_ice(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauocx
real, dimension(:), pointer w3adatmd::tauocx
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauocy
real, dimension(:), pointer w3adatmd::tauocy
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauox
real, dimension(:), pointer w3adatmd::tauox
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauoy
real, dimension(:), pointer w3adatmd::tauoy
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauwix
real, dimension(:), pointer w3adatmd::tauwix
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauwiy
real, dimension(:), pointer w3adatmd::tauwiy
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauwnx
real, dimension(:), pointer w3adatmd::tauwnx
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
tauwny
real, dimension(:), pointer w3adatmd::tauwny
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
th1m
real, dimension(:,:), pointer w3adatmd::th1m
Definition at line 594 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
th2m
real, dimension(:,:), pointer w3adatmd::th2m
Definition at line 594 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
thm
real, dimension(:), pointer w3adatmd::thm
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
thp0
real, dimension(:), pointer w3adatmd::thp0
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ths
real, dimension(:), pointer w3adatmd::ths
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
tpms
real, dimension(:), pointer w3adatmd::tpms
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
tusx
real, dimension(:), pointer w3adatmd::tusx
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
tusy
real, dimension(:), pointer w3adatmd::tusy
Definition at line 607 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
tws
real, dimension(:), pointer w3adatmd::tws
Definition at line 603 of file w3adatmd.F90.
Referenced by w3agcmmd::snd_fields_to_atmos(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
u10
real, dimension(:), pointer w3adatmd::u10
Definition at line 584 of file w3adatmd.F90.
Referenced by w3iogomd::calc_wbt(), wmesmfmd::fieldindex(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3iosfmd::w3cprt(), w3initmd::w3init(), w3iosfmd::w3iosf(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3uini(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), and w3pro2md::w3xyp2().
u10d
real, dimension(:), pointer w3adatmd::u10d
Definition at line 584 of file w3adatmd.F90.
Referenced by w3iogomd::calc_wbt(), wmesmfmd::fieldindex(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), w3iosfmd::w3cprt(), w3initmd::w3init(), w3iosfmd::w3iosf(), w3seta(), w3updtmd::w3uini(), w3updtmd::w3uwnd(), and w3wavemd::w3wave().
ua
real, dimension(:), pointer w3adatmd::ua
Definition at line 584 of file w3adatmd.F90.
Referenced by gxoutf(), w3exgi(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iotrmd::w3iotr(), w3ounf(), w3outf(), w3seta(), and w3updtmd::w3uwnd().
ua0
real, dimension(:), pointer w3adatmd::ua0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3uwnd().
uai
real, dimension(:), pointer w3adatmd::uai
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3uwnd().
uba
real, dimension(:), pointer w3adatmd::uba
Definition at line 614 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), wmesmfmd::fieldindex(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ubd
real, dimension(:), pointer w3adatmd::ubd
Definition at line 614 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), wmesmfmd::fieldindex(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ud
real, dimension(:), pointer w3adatmd::ud
Definition at line 584 of file w3adatmd.F90.
Referenced by gxoutf(), w3exgi(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iopomd::w3iope(), w3iotrmd::w3iotr(), w3ounf(), w3outf(), w3seta(), and w3updtmd::w3uwnd().
ud0
real, dimension(:), pointer w3adatmd::ud0
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3uwnd().
udi
real, dimension(:), pointer w3adatmd::udi
Definition at line 578 of file w3adatmd.F90.
Referenced by w3seta(), and w3updtmd::w3uwnd().
us3d
real, dimension(:,:), pointer w3adatmd::us3d
Definition at line 612 of file w3adatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), wmesmfmd::calcstokes3d(), pdlib_field_vec::do_output_exchanges(), gxoutf(), wmesmfmd::setservices(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
usero
real, dimension(:,:), pointer w3adatmd::usero
Definition at line 623 of file w3adatmd.F90.
   REAL, POINTER           :: USERO(:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ussp
real, dimension(:,:), pointer w3adatmd::ussp
Definition at line 612 of file w3adatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), wmesmfmd::calcstokes3d(), pdlib_field_vec::do_output_exchanges(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ussx
real, dimension(:), pointer w3adatmd::ussx
Definition at line 607 of file w3adatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
ussy
real, dimension(:), pointer w3adatmd::ussy
Definition at line 607 of file w3adatmd.F90.
Referenced by w3iogomd::calc_u3stokes(), pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
wadats
type(wadat), dimension(:), allocatable, target w3adatmd::wadats
Definition at line 571 of file w3adatmd.F90.
   TYPE(WADAT), TARGET, ALLOCATABLE :: WADATS(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3dima(), w3dmnl(), w3exgi(), w3initmd::w3mpii(), w3naux(), w3seta(), w3xdma(), w3xeta(), wminitmd::wminit(), and wminitmd::wminitnml().
wbt
real, dimension(:), pointer w3adatmd::wbt
Definition at line 587 of file w3adatmd.F90.
Referenced by w3iogomd::calc_wbt(), pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
whitecap
real, dimension(:,:), pointer w3adatmd::whitecap
Definition at line 603 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3exgi(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
wlm
real, dimension(:), pointer w3adatmd::wlm
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutf(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seta(), and w3xeta().
wn
real, dimension(:,:), pointer w3adatmd::wn
Definition at line 575 of file w3adatmd.F90.
Referenced by pdlib_w3profsmd::action_limiter_local(), w3iogomd::calc_u3stokes(), w3iogomd::calc_wbt(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), wmesmfmd::fieldindex(), gxoutf(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::print_wn_statistic(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3wavset::trig_compute_lh_stress(), w3iosfmd::w3cprt(), w3exgi(), w3initmd::w3init(), w3iogomd::w3iogo(), w3ounf(), w3iogomd::w3outg(), w3psmcmd::w3psmc(), w3seta(), w3updtmd::w3ulev(), w3wavemd::w3wave(), and w3pro2md::w3xyp2().
wnmean
real, dimension(:), pointer w3adatmd::wnmean
Definition at line 587 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), wmesmfmd::fieldindex(), w3ogcmmd::snd_fields_to_ocean(), w3exgi(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3seta(), w3wavemd::w3wave(), and w3xeta().
ww3_field_vec
integer, pointer w3adatmd::ww3_field_vec
Definition at line 676 of file w3adatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpii(), w3initmd::w3mpio(), and w3seta().
ww3_spec_vec
integer, pointer w3adatmd::ww3_spec_vec
Definition at line 676 of file w3adatmd.F90.
Referenced by w3initmd::w3mpii(), and w3seta().