WAVEWATCH III: wmfinlmd Module Reference
wmfinlmd Module Reference
Finalization of the multi-grid wave model.
Functions/Subroutines
subroutine wmfinl
Initialize multi-grid version of WAVEWATCH III.
Detailed Description
Finalization of the multi-grid wave model.
Author
H. L. Tolman
Date
04-Feb-2014
Function/Subroutine Documentation
wmfinl()
subroutine wmfinlmd::wmfinl
Initialize multi-grid version of WAVEWATCH III.
Author
H. L. Tolman
Date
28-Jan-2014
Definition at line 75 of file wmfinlmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         28-Jan-2014 |
     !/                  +-----------------------------------+
     !/
     !/    06-May-2005 : Origination.                        ( version 3.07 )
     !/    03-Sep-2012 : Output of initilization time.       ( version 4.10 )
     !/    28-Jan-2014 : Add memory hwm to profiling.        ( version 5.00 )
     !/
     !  1. Purpose :
     !
     !     Initialize multi-grid version of WAVEWATCH III.
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      PRTIME    Subr. W3SERVMD Profiling routine ( !/MPRF )
     !      MPI_BARRIER
     !                Subr.          Standard MPI routines.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      WW3_MULTI Prog.   N/A    Multi-grid model driver.
     !      ....                     Any coupled model.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/MPI   MPI routines.
     !
     !       !/O10   Enable output identifying start and end of routine
     !
     !       !/S     Enable subroutine tracing.
     !       !/T     Enable test output
     !       !/MPRF  Profiling.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_MPRF
     !     use w3getmem ; fake use statement for make_makefile.sh
     !
 #endif
     USE w3timemd, ONLY: tdiff
     USE wmmdatmd, ONLY: mdss, mdso, nmpscr, nmplog, improc
     USE wmmdatmd, ONLY: clkdt1, clkdt2, clkdt3, clkfin
 #ifdef W3_MPRF
     USE wmmdatmd, ONLY: mdsp
 #endif
 #ifdef W3_MPI
     USE wmmdatmd, ONLY: mpi_comm_mwave
 #endif
     !/
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
 #ifdef W3_MPRF
     USE w3timemd, ONLY: prtime
 #endif
     !/
     IMPLICIT NONE
     !
 #ifdef W3_MPI
     include "mpif.h"
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_MPI
     INTEGER                 :: IERR_MPI
 #endif
 #ifdef W3_MPRF
     REAL                    :: PRFT0, PRFTN
     REAL(KIND=8)            :: get_memory
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     ! 1.  Identification at start
     !
 #ifdef W3_S
     CALL strace (ient, 'WMFINL')
 #endif
 #ifdef W3_MPRF
     CALL prtime ( prft0 )
 #endif
     !
 #ifdef W3_O10
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc ) WRITE (mdss,900)
 #endif
     !
     !/ ------------------------------------------------------------------- /
     ! 2.  Finalization
     !
 #ifdef W3_MPI
     CALL mpi_barrier ( mpi_comm_mwave, ierr_mpi )
 #endif
     !
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc )             &
          WRITE (mdss,920) clkfin
     IF ( nmplog.EQ.improc ) WRITE (mdso,920) clkfin
     CALL date_and_time ( values=clkdt3 )
     clkfin = tdiff( clkdt1,clkdt3 )
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc )             &
          WRITE (mdss,921) clkfin
     IF ( nmplog.EQ.improc ) WRITE (mdso,921) clkfin
     !
     !/ ------------------------------------------------------------------- /
     ! 3.  Identification at end
     !
 #ifdef W3_O10
     IF ( mdss.NE.mdso .AND. nmpscr.EQ.improc ) WRITE (mdss,999)
 #endif
     !
 #ifdef W3_MPRF
     CALL prtime ( prftn )
     WRITE (mdsp,990) prft0, prftn, get_memory()
 #endif
     !
     RETURN
     !
     ! Formats
     !
 900 FORMAT ( ' ========== STARTING MWW3 FINALIZATION (WMFINL) ===', &
          '============================' )
 920 FORMAT (/'  Initialization time :',f10.2,' s')
 921 FORMAT ( '  Elapsed time        :',f10.2,' s')
     !
 #ifdef W3_MPRF
 990 FORMAT (1x,3f12.3,' WMFINL')
 #endif
     !
 999 FORMAT (/' ========== END OF MWW3 INITIALIZATION (WMFINL) ===', &
          '============================'/)
     !/
     !/ End of WMFINL ----------------------------------------------------- /
     !/
References wmmdatmd::clkdt1, wmmdatmd::clkdt2, wmmdatmd::clkdt3, wmmdatmd::clkfin, wmmdatmd::improc, include(), wmmdatmd::mdso, wmmdatmd::mdsp, wmmdatmd::mdss, wmmdatmd::mpi_comm_mwave, wmmdatmd::nmplog, wmmdatmd::nmpscr, w3timemd::prtime(), w3servmd::strace(), and w3timemd::tdiff().
Referenced by w3mlti(), and w3sbs1().