WAVEWATCH III: w3odatmd Module Reference
w3odatmd Module Reference
Data Types
type otype1
type otype2
type otype3
type otype4
type otype5
type otype6
type output
Functions/Subroutines
subroutine w3nout (NDSERR, NDSTST)
subroutine w3dmo2 (IMOD, NDSE, NDST, NPT)
subroutine w3dmo3 (IMOD, NDSE, NDST)
subroutine w3dmo5 (IMOD, NDSE, NDST, IBLOCK)
subroutine w3seto (IMOD, NDSERR, NDSTST)
Variables
integer noutp = -1
integer ioutp = -1
integer iostyp = 1
integer, parameter nogrp = 10
integer, parameter ngrpp = 20
integer, parameter dimp = 15
integer, dimension(nogrp) noge
integer notype
integer, parameter noextr = 2
character(len=20), dimension(nogrp, ngrpp) idout
character(len=80) fnmpre = './'
logical unipts = .FALSE.
logical upproc = .FALSE.
type(output), dimension(:), allocatable, target outpts
integer, pointer ndso
integer, pointer ndse
integer, pointer ndst
integer, pointer screen
integer, pointer ntproc
integer, pointer naproc
integer, pointer iaproc
integer, pointer naplog
integer, pointer napout
integer, pointer naperr
integer, pointer napfld
integer, pointer nappnt
integer, pointer naptrk
integer, pointer naprst
integer, pointer napbpt
integer, pointer napprt
integer, pointer noswll
integer, dimension(:), pointer tosnl5
integer, dimension(:), pointer tofrst
integer, dimension(:,:), pointer tonext
integer, dimension(:,:), pointer tolast
integer, dimension(:), pointer tbpi0
integer, dimension(:), pointer tbpin
integer, dimension(:), pointer nds
integer, dimension(:), pointer ofiles
real, dimension(:), pointer dtout
logical, dimension(:), pointer flout
integer, pointer ipass1
integer, pointer nrqgo
integer, pointer nrqgo2
integer, dimension(:), pointer irqgo
integer, dimension(:), pointer irqgo2
logical, dimension(:,:), pointer flogrd
logical, dimension(:,:), pointer flogr2
logical, dimension(:,:), pointer flogrr
logical, dimension(:), pointer flogd
logical, dimension(:), pointer flog2
logical, dimension(:), pointer flogr
logical, pointer write1
integer, pointer ipass2
integer, pointer nopts
integer, pointer nrqpo
integer, pointer nrqpo2
integer, dimension(:,:,:), pointer iptint
integer, dimension(:), pointer il
integer, dimension(:), pointer iw
integer, dimension(:), pointer ii
integer, dimension(:), pointer irqpo1
integer, dimension(:), pointer irqpo2
real, dimension(:,:), pointer ptloc
real, dimension(:,:), pointer ptifac
real, dimension(:), pointer dpo
real, dimension(:), pointer wao
real, dimension(:), pointer wdo
real, dimension(:), pointer aso
real, pointer ifdef
real, pointer w3_flx5
real, dimension(:), pointer zet_seto
character(len=40), dimension(:), pointer ptnme
character(len=13), dimension(:), pointer grdid
logical, pointer o2init
logical, pointer o2irqi
integer, pointer ipass3
integer, pointer it0pnt
integer, pointer it0trk
integer, pointer it0prt
integer, pointer nrqtr
integer, dimension(:), pointer irqtr
logical, pointer o3init
logical, pointer stop
logical, dimension(:,:), pointer mask1
logical, dimension(:,:), pointer mask2
character(len=32), dimension(:,:), pointer trckid
integer, pointer ifile4
integer, pointer nrqrs
integer, pointer nblkrs
integer, pointer rsblks
integer, dimension(:), pointer irqrs
integer, dimension(:), pointer irqrss
real, dimension(:,:,:), pointer vaaux
integer, pointer nbi
integer, pointer nbi2
integer, pointer nfbpo
integer, pointer nki
integer, pointer nthi
integer, dimension(:), pointer nbo
integer, dimension(:), pointer nbo2
integer, dimension(:), pointer ndsl
integer, pointer nrqbp
integer, pointer nrqbp2
integer, dimension(:,:), pointer ipbpi
integer, dimension(:), pointer isbpi
integer, dimension(:,:), pointer ipbpo
integer, dimension(:), pointer isbpo
integer, dimension(:), pointer irqbp1
integer, dimension(:), pointer irqbp2
real, pointer xfri
real, pointer fr1i
real, pointer th1i
real, dimension(:), pointer xbpi
real, dimension(:), pointer ybpi
real, dimension(:,:), pointer rdbpi
real, dimension(:), pointer xbpo
real, dimension(:), pointer ybpo
real, dimension(:,:), pointer rdbpo
real, dimension(:,:), pointer abpi0
real, dimension(:,:), pointer abpin
real, dimension(:,:), pointer abpos
real, dimension(:,:), pointer bbpi0
real, dimension(:,:), pointer bbpin
logical, pointer o5ini1
logical, pointer o5ini2
logical, pointer o5ini3
logical, pointer o5ini4
logical, pointer flbpi
logical, pointer flbpo
logical, pointer filer
logical, pointer filew
logical, pointer filed
logical, pointer spconv
integer, pointer ipass6
integer, pointer ihmax
integer, pointer ix0
integer, pointer ixn
integer, pointer ixs
integer, pointer iy0
integer, pointer iyn
integer, pointer iys
integer, dimension(:,:), pointer icprt
real, pointer hspmin
real, pointer wsmult
real, pointer wscut
real, dimension(:,:), pointer dtprt
logical, pointer flform
logical, pointer flcomb
logical, pointer o6init
integer, pointer ptmeth
real, pointer ptfcut
Function/Subroutine Documentation
w3dmo2()
subroutine w3odatmd::w3dmo2 (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, integer, intent(in) NPT)
Definition at line 952 of file w3odatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 |
     !/                  +-----------------------------------+
     !/
     !/    10-Nov-2004 : Origination.                        ( version 3.06 )
     !/    24-Jul-2006 : Adding unified point output storage.( version 3.10 )
     !/    25-Jul-2006 : Originating grid ID for points.     ( version 3.10 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    30-Oct-2009 : Implement curvilinear grid type.    ( version 3.14 )
     !/                  (W. E. Rogers & T. J. Campbell, NRL)
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data storage for point output.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       NPT     Int.   I   Array size.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation below.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOPO    Subr. W3IOPOMD Point output module.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - W3SETO needs to be called after allocation to point to
     !       proper allocated arrays.
     !     - Note that NOPTS is overwritten in W3IOPP.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S      Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: w3setg, ngrids, nauxgr, igrid, nspec
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST, NPT
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID, NLOW
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DMO2')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     nlow   = min( 0 , -nauxgr )
     IF ( imod.LT.nlow .OR. imod.GT.noutp ) THEN
       WRITE (ndse,1002) imod, nlow, noutp
       CALL extcde (2)
     END IF
     !
     IF ( outpts(imod)%OUT2%O2INIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     ALLOCATE ( outpts(imod)%OUT2%IPTINT(2,4,npt) ,            &
          outpts(imod)%OUT2%IL(npt)         ,                  &
          outpts(imod)%OUT2%IW(npt)         ,                  &
          outpts(imod)%OUT2%II(npt)         ,                  &
          outpts(imod)%OUT2%PTIFAC(4,npt)   ,                  &
          outpts(imod)%OUT2%PTNME(npt)      ,                  &
          outpts(imod)%OUT2%GRDID(npt)      ,                  &
          outpts(imod)%OUT2%DPO(npt)        ,                  &
          outpts(imod)%OUT2%WAO(npt)        ,                  &
          outpts(imod)%OUT2%ZET_SETO(npt)   ,                  &
          outpts(imod)%OUT2%WDO(npt)        ,                  &
          outpts(imod)%OUT2%ASO(npt)        ,                  &
 #ifdef W3_FLX5
          outpts(imod)%OUT2%TAUAO(npt)      ,                  &
          outpts(imod)%OUT2%TAUDO(npt)      ,                  &
          outpts(imod)%OUT2%DAIRO(npt)      ,                  &
 #endif
          outpts(imod)%OUT2%CAO(npt)        ,                  &
          outpts(imod)%OUT2%CDO(npt)        ,                  &
          outpts(imod)%OUT2%ICEO(npt)       ,                  &
          outpts(imod)%OUT2%ICEHO(npt)      ,                  &
          outpts(imod)%OUT2%ICEFO(npt)      ,                  &
          outpts(imod)%OUT2%SPCO(nspec,npt) ,                  &
          outpts(imod)%OUT2%PTLOC(2,npt)    , stat=istat       )
     check_alloc_status( istat )
     !
     outpts(imod)%OUT2%O2INIT = .true.
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3seto ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !
     nopts  = npt
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DMO2 : GRIDS NOT INITIALIZED *** '/ &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DMO2 : ILLEGAL MODEL NUMBER *** '/  &
          '                    IMOD   = ',i10/                   &
          '                    NLOW   = ',i10/                   &
          '                    NOUTP  = ',i10/)
 1003 FORMAT (/' *** ERROR W3DMO2 : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DMO2 : MODEL ',i4)
 9001 FORMAT (' TEST W3DMO2 : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DMO2 : POINTERS RESET')
 9003 FORMAT (' TEST W3DMO2 : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DMO2 ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3gdatmd::igrid, w3gdatmd::nauxgr, w3gdatmd::ngrids, nopts, noutp, w3gdatmd::nspec, outpts, w3servmd::strace(), w3gdatmd::w3setg(), and w3seto().
Referenced by w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopp(), and wmiopomd::wmiopp().
w3dmo3()
subroutine w3odatmd::w3dmo3 (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST)
Definition at line 1151 of file w3odatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    24-Nov-2004 : Origination.                        ( version 3.06 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data storage for track output.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation below.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOTR    Subr. W3IOTRMD Track output module.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !     - W3SETO needs to be called after allocation to point to
     !       proper allocated arrays.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/SHRD, !/DIST, !/MPI
     !              Shared / distributed memory model
     !
     !     !/S      Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: w3setg, ngrids, igrid, nx, ny
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DMO3')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.noutp ) THEN
       WRITE (ndse,1002) imod, noutp
       CALL extcde (2)
     END IF
     !
     IF ( outpts(imod)%OUT3%O3INIT ) THEN
       WRITE (ndse,1003)
       CALL extcde (3)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod
 #endif
     !
     jgrid  = igrid
     IF ( jgrid .NE. imod ) CALL w3setg ( imod, ndse, ndst )
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays
     !
     ALLOCATE ( outpts(imod)%OUT3%MASK1(ny,nx) ,               &
          outpts(imod)%OUT3%MASK2(ny,nx) ,                     &
          outpts(imod)%OUT3%TRCKID(ny,nx), stat=istat          )
     check_alloc_status( istat )
     !
     outpts(imod)%OUT3%O3INIT = .true.
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Point to allocated arrays
     !
     CALL w3seto ( imod, ndse, ndst )
     !
 #ifdef W3_T
     WRITE (ndst,9002)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 4.  Update counters in grid
     !
 #ifdef W3_T
     WRITE (ndst,9003)
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 5.  Restore previous grid setting if necessary
     !
     IF ( jgrid .NE. imod ) CALL w3setg ( jgrid, ndse, ndst )
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DMO3 : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DMO3 : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                        &
          '                    NOUTP  = ',i10/)
 1003 FORMAT (/' *** ERROR W3DMO3 : ARRAY(S) ALREADY ALLOCATED *** ')
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DMO3 : MODEL ',i4)
 9001 FORMAT (' TEST W3DMO3 : ARRAYS ALLOCATED')
 9002 FORMAT (' TEST W3DMO3 : POINTERS RESET')
 9003 FORMAT (' TEST W3DMO3 : DIMENSIONS STORED')
 #endif
     !/
     !/ End of W3DMO3 ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3gdatmd::igrid, w3gdatmd::ngrids, noutp, w3gdatmd::nx, w3gdatmd::ny, outpts, w3servmd::strace(), w3gdatmd::w3setg(), and w3seto().
Referenced by w3iotrmd::w3iotr().
w3dmo5()
subroutine w3odatmd::w3dmo5 (integer, intent(in) IMOD, integer, intent(in) NDSE, integer, intent(in) NDST, integer, intent(in) IBLOCK)
Definition at line 1321 of file w3odatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         10-Dec-2014 !
     !/                  +-----------------------------------+
     !/
     !/    13-Dec-2004 : Origination.                        ( version 3.06 )
     !/    06-Sep-2005 : Second storage for input bound. sp. ( version 3.08 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/
     !  1. Purpose :
     !
     !     Initialize an individual data storage for boundary data.
     !
     !  2. Method :
     !
     !     Allocate directly into the structure array. Note that
     !     this cannot be done through the pointer alias!
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSE    Int.   I   Error output unit number.
     !       NDST    Int.   I   Test output unit number.
     !       IBLOCK  Int.   I   Select block to allocate.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation below.
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOBC    Subr. W3IOBCMD Boundary data output module.
     !      W3IOGR    Subr. W3IOGRMD Grid data output module.
     !      W3WAVE    Subr. W3WAVEMD Actual wave model routine.
     !      WW3_GRID  Prog.   N/A    Grid preprocessing program.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     - Check on input parameters.
     !     - Check on previous allocation.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S      Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: w3setg, ngrids, igrid, nx, ny, nspec
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)           :: IMOD, NDSE, NDST, IBLOCK
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: JGRID
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3DMO5')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndse,1001)
       CALL extcde (1)
     END IF
     !
     IF ( imod.LT.1 .OR. imod.GT.noutp ) THEN
       WRITE (ndse,1002) imod, noutp
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) imod, iblock
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Allocate arrays and reset pointers
     !
     SELECT CASE (iblock)
       !
     CASE (1)
       !
       ALLOCATE ( outpts(imod)%OUT5%IPBPI(nbi,4),              &
            outpts(imod)%OUT5%ISBPI(nbi)  ,                    &
            outpts(imod)%OUT5%XBPI(nbi)   ,                    &
            outpts(imod)%OUT5%YBPI(nbi)   ,                    &
            outpts(imod)%OUT5%RDBPI(nbi,4), stat=istat         )
       check_alloc_status( istat )
       !
       ipbpi  => outpts(imod)%OUT5%IPBPI
       isbpi  => outpts(imod)%OUT5%ISBPI
       xbpi   => outpts(imod)%OUT5%XBPI
       ybpi   => outpts(imod)%OUT5%YBPI
       rdbpi  => outpts(imod)%OUT5%RDBPI
       !
       outpts(imod)%OUT5%O5INI1 = .true.
       !
     CASE (2)
       !
       ALLOCATE ( outpts(imod)%OUT5%IPBPO(nbo(nfbpo),4),       &
            outpts(imod)%OUT5%ISBPO(4*nbo(nfbpo)),             &
            outpts(imod)%OUT5%XBPO(nbo(nfbpo))   ,             &
            outpts(imod)%OUT5%YBPO(nbo(nfbpo))   ,             &
            outpts(imod)%OUT5%RDBPO(nbo(nfbpo),4), stat=istat  )
       check_alloc_status( istat )
       !
       ipbpo  => outpts(imod)%OUT5%IPBPO
       isbpo  => outpts(imod)%OUT5%ISBPO
       xbpo   => outpts(imod)%OUT5%XBPO
       ybpo   => outpts(imod)%OUT5%YBPO
       rdbpo  => outpts(imod)%OUT5%RDBPO
       !
       outpts(imod)%OUT5%O5INI2 = .true.
       outpts(imod)%OUT5%ISBPO = 0
       !
     CASE (3)
       !
       ALLOCATE ( outpts(imod)%OUT5%ABPI0(nspec,0:nbi2),       &
            outpts(imod)%OUT5%ABPIN(nspec,0:nbi2),             &
            outpts(imod)%OUT5%BBPI0(nspec,0:nbi),              &
            outpts(imod)%OUT5%BBPIN(nspec,0:nbi), stat=istat   )
       check_alloc_status( istat )
       !
       abpi0  => outpts(imod)%OUT5%ABPI0
       abpin  => outpts(imod)%OUT5%ABPIN
       bbpi0  => outpts(imod)%OUT5%BBPI0
       bbpin  => outpts(imod)%OUT5%BBPIN
       bbpi0 = -1.
       !
       outpts(imod)%OUT5%O5INI3 = .true.
       !
     CASE (4)
       !
       ALLOCATE ( outpts(imod)%OUT5%ABPOS(nspec,0:nbo2(nfbpo)), stat=istat )
       check_alloc_status( istat )
       !
       abpos  => outpts(imod)%OUT5%ABPOS
       !
       outpts(imod)%OUT5%O5INI4 = .true.
       !
     CASE DEFAULT
       WRITE (ndse,1010)
       CALL extcde (10)
       !
     END SELECT
     !
 #ifdef W3_T
     WRITE (ndst,9001)
 #endif
     !
     ! -------------------------------------------------------------------- /
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3DMO5 : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3DMO5 : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                        &
          '                    NOUTP  = ',i10/)
 1010 FORMAT (/' *** ERROR W3DMO5 : ILLEGAL BLOCK NUMBER  *** '/      &
          '                    IBLOCK = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3DMO5 : MODEL AND BLOCK ',2i4)
 9001 FORMAT (' TEST W3DMO5 : ARRAYS ALLOCATED')
 #endif
     !/
     !/ End of W3DMO5 ----------------------------------------------------- /
     !/
References abpi0, abpin, abpos, bbpi0, bbpin, w3servmd::extcde(), w3gdatmd::igrid, ipbpi, ipbpo, isbpi, isbpo, nbi, nbi2, nbo, nbo2, nfbpo, w3gdatmd::ngrids, noutp, w3gdatmd::nspec, w3gdatmd::nx, w3gdatmd::ny, outpts, rdbpi, rdbpo, w3servmd::strace(), w3gdatmd::w3setg(), xbpi, xbpo, ybpi, and ybpo.
Referenced by w3initmd::w3init(), w3iobcmd::w3iobc(), and wmgridmd::wmglow().
w3nout()
subroutine w3odatmd::w3nout (integer, intent(in) NDSERR, integer, intent(in) NDSTST)
Definition at line 561 of file w3odatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    13-Dec-2004 : Origination.                        ( version 3.06 )
     !/    27-Jun-2006 : Adding file name preamble           ( version 3.09 )
     !/    24-Jul-2006 : Adding unified point output storage.( version 3.10 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    30-Oct-2006 : Add pars for partitioning.          ( version 3.10 )
     !/    26-Mar-2007 : Add pars for partitioning.          ( version 3.11 )
     !/    17-May-2007 : Adding NTPROC/NAPROC separation.    ( version 3.11 )
     !/    18-Dec-2012 : Moving IDOUT initialization here.   ( version 4.11 )
     !/    19-Dec-2012 : Move NOSWLL to data structure.      ( version 4.11 )
     !/    10-Dec-2014 : Add checks for allocate status      ( version 5.04 )
     !/    22-Mar-2021 : Add extra coupling variables        ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Set up the number of grids to be used.
     !
     !  2. Method :
     !
     !     Use data stored in NGRIDS in W3GDATMD.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDSERR  Int.   I   Error output unit number.
     !       NDSTST  Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation below.
     !
     !  5. Called by :
     !
     !     Any main program that uses this grid structure.
     !
     !  6. Error messages :
     !
     !     - Error checks on previous setting of variable NGRIDS.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: ngrids, nauxgr
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDSERR, NDSTST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: I, NLOW, J
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     CHARACTER(LEN=20)       :: STRING
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3NOUT')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( ngrids .EQ. -1 ) THEN
       WRITE (ndserr,1001) ngrids
       CALL extcde (1)
     END IF
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set variable and allocate arrays
     !
     nlow   = min( 0 , -nauxgr )
     ALLOCATE ( outpts(nlow:ngrids), stat=istat )
     check_alloc_status( istat )
     noutp  = ngrids
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Initialize parameters
     !
     DO i=nlow, ngrids
       !
       outpts(i)%NDSO   = 6
       outpts(i)%NDSE   = 6
       outpts(i)%NDST   = 6
       outpts(i)%SCREEN = 6
       !
       outpts(i)%NTPROC = 1
       outpts(i)%NAPROC = 1
       outpts(i)%IAPROC = 1
       outpts(i)%NAPLOG = 1
       outpts(i)%NAPOUT = 1
       outpts(i)%NAPERR = 1
       outpts(i)%NAPFLD = 1
       outpts(i)%NAPPNT = 1
       outpts(i)%NAPTRK = 1
       outpts(i)%NAPRST = 1
       outpts(i)%NAPBPT = 1
       outpts(i)%NAPPRT = 1
       !
       outpts(i)%NOSWLL = -1
       !
       outpts(i)%TBPI0 = (-1,0)
       outpts(i)%TBPIN = (-1,0)
       !
       outpts(i)%OUT1%IPASS1 = 0
 #ifdef W3_MPI
       outpts(i)%OUT1%NRQGO  = 0
       outpts(i)%OUT1%NRQGO2 = 0
 #endif
       !
       outpts(i)%OUT2%IPASS2 = 0
       outpts(i)%OUT2%NOPTS  = 0
       outpts(i)%OUT2%O2INIT = .false.
 #ifdef W3_MPI
       outpts(i)%OUT2%O2IRQI = .false.
 #endif
       !
       outpts(i)%OUT3%IPASS3 = 0
       outpts(i)%OUT3%O3INIT = .false.
       outpts(i)%OUT3%STOP   = .false.
 #ifdef W3_MPI
       outpts(i)%OUT3%NRQTR  = 0
 #endif
       !
       outpts(i)%OUT4%IFILE4 = 0
 #ifdef W3_MPI
       outpts(i)%OUT4%NRQRS  = 0
 #endif
       !
       outpts(i)%OUT5%O5INI1 = .false.
       outpts(i)%OUT5%O5INI2 = .false.
       outpts(i)%OUT5%O5INI3 = .false.
       outpts(i)%OUT5%O5INI4 = .false.
       outpts(i)%OUT5%FILER  = .true.
       outpts(i)%OUT5%FILEW  = .true.
       outpts(i)%OUT5%FILED  = .true.
       !
       outpts(i)%OUT6%IPASS6 = 0
       outpts(i)%OUT6%O6INIT = .false.
       !
     END DO
     !
     !     Set IDOUT
     !       Commented outlines represent reserved slots.
     !
     DO i=1, nogrp
       DO j=1, ngrpp
         idout(i,j) = 'Undefined / Not Used'
       END DO
     END DO
     !
     ! 1) Forcing fields
     !
     noge(1) = 9
 #ifdef W3_BT4
     noge(1) = 10
 #endif
 #ifdef W3_IS2
     noge(1) = 12    ! CB
 #endif
 #ifdef W3_SETUP
     noge(1) = 13    ! CB
 #endif
     !
     idout( 1, 1)  = 'Water depth         '
     idout( 1, 2)  = 'Current vel.        '
     idout( 1, 3)  = 'Wind speed          '
     idout( 1, 4)  = 'Air-sea temp. dif.  '
     idout( 1, 5)  = 'Water level         '
     idout( 1, 6)  = 'Ice concentration   '
     idout( 1, 7)  = 'Iceberg damp coeffic'
     idout( 1, 8)  = 'Atmospheric momentum'
     idout( 1, 9)  = 'Air density         '
 #ifdef W3_BT4
     idout( 1, 10)  = 'Sediment diam D50   '
 #endif
 #ifdef W3_IS2
     idout( 1, 11)  = 'ice thickness   '
     idout( 1, 12) = 'Avg. ice floe diam. '
 #endif
 #ifdef W3_SETUP
     idout( 1, 13)  = 'wave induced setup'
 #endif
     !
     ! 2) Standard mean wave parameters
     !
     noge(2) = 19
 #ifdef W3_OASOCM
     noge(2) = 20
 #endif
     !
     idout( 2, 1)  = 'Wave height         '
     idout( 2, 2)  = 'Mean wave length    '
     idout( 2, 3)  = 'Mean wave period(+2)'
     idout( 2, 4)  = 'Mean wave period(-1)'
     idout( 2, 5)  = 'Mean wave period(+1)'
     idout( 2, 6)  = 'Peak frequency      '
     idout( 2, 7)  = 'Mean wave dir. a1b1 '
     idout( 2, 8)  = 'Mean dir. spr. a1b1 '
     idout( 2, 9)  = 'Peak direction      '
     idout( 2, 10)  = 'Infragravity height'
     idout( 2, 11)  = 'Space-Time Max E   '
     idout( 2, 12)  = 'Space-Time Max Std '
     idout( 2, 13)  = 'Space-Time Hmax    '
     idout( 2, 14)  = 'Spc-Time Hmax^crest'
     idout( 2, 15)  = 'STD Space-Time Hmax'
     idout( 2, 16)  = 'STD ST Hmax^crest  '
     idout( 2, 17)  = 'Dominant wave bT   '
     idout( 2, 18)  = 'Peak prd. (from fp)'
     idout( 2, 19)  = 'Mean wave number   '
 #ifdef W3_OASOCM
     idout( 2, 20) = 'Mean wave dir. norot'
 #endif
     !      IDOUT( 2,10)  = 'Mean wave dir. a2b2'
     !      IDOUT( 2,11)  = 'Mean dir. spr. a2b2'
     !      IDOUT( 2,12)  = 'Windsea height(Sin)'
     !      IDOUT( 2,13)  = 'Windsea peak f(Sin)'
     !      IDOUT( 2,14)  = 'Subrange waveheight'
     !
     ! 3) Frequency-dependent standard parameters
     !
     noge(3) = 6
     !
     idout( 3, 1)  = '1D Freq. Spectrum   '
     idout( 3, 2)  = 'Mean wave dir. a1b1 '
     idout( 3, 3)  = 'Mean dir. spr. a1b1 '
     idout( 3, 4)  = 'Mean wave dir. a2b2 '
     idout( 3, 5)  = 'Mean dir. spr. a2b2 '
     idout( 3, 6)  = 'Wavenumber array    '
     !
     ! 4) Spectral Partitions parameters
     !
     noge(4) = 17
     !
     idout( 4, 1)  = 'Part. wave height   '
     idout( 4, 2)  = 'Part. peak period   '
     idout( 4, 3)  = 'Part. peak wave len.'
     idout( 4, 4)  = 'Part. mean direction'
     idout( 4, 5)  = 'Part. dir. spread   '
     idout( 4, 6)  = 'Part. wind sea frac.'
     idout( 4, 7)  = 'Part. peak direction'
     idout( 4, 8)  = 'Part. peakedness    '
     idout( 4, 9)  = 'Part. peak enh. fac.'
     idout( 4,10)  = 'Part. gaussian width'
     idout( 4,11)  = 'Part. spectral width'
     idout( 4,12)  = 'Part. mean per. (-1)'
     idout( 4,13)  = 'Part. mean per. (+1)'
     idout( 4,14)  = 'Part. mean per. (+2)'
     idout( 4,15)  = 'Part. peak density  '
     idout( 4,16)  = 'Total wind sea frac.'
     idout( 4,17)  = 'Number of partitions'
     !
     ! 5) Atmosphere-waves layer
     !
     noge(5) = 11
     !
     idout( 5, 1)  = 'Friction velocity   '
     idout( 5, 2)  = 'Charnock parameter  '
     idout( 5, 3)  = 'Energy flux         '
     idout( 5, 4)  = 'Wind-wave enrgy flux'
     idout( 5, 5)  = 'Wind-wave net mom. f'
     idout( 5, 6)  = 'Wind-wave neg.mom.f.'
     idout( 5, 7)  = 'Whitecap coverage   '
     idout( 5, 8)  = 'Whitecap mean thick.'
     idout( 5, 9)  = 'Mean breaking height'
     idout( 5,10)  = 'Dominant break prob '
     idout( 5,11)  = 'Wind sea period' ! C.Bunney - reinstated this as is used in ww3_ounf
     ! Is it suposed to be defunct? It is not in ww3_outf...
     !
     ! 6) Wave-ocean layer
     !
     noge(6) = 13
     !
     idout( 6, 1)  = 'Radiation stresses  '
     idout( 6, 2)  = 'Wave-ocean mom. flux'
     idout( 6, 3)  = 'wave ind p Bern Head'
     idout( 6, 4)  = 'Wave-ocean TKE  flux'
     idout( 6, 5)  = 'Stokes transport    '
     idout( 6, 6)  = 'Stokes drift at z=0 '
     idout( 6, 7)  = '2nd order pressure  '
     idout( 6, 8)  = 'Stokes drft spectrum'
     idout( 6, 9)  = '2nd ord press spectr'
     idout( 6,10)  = 'Wave-ice mom. flux  '
     idout( 6,11)  = 'Wave-ice energy flux'
     idout( 6,12)  = 'Split Surface Stokes'
     idout( 6,13)  = 'Tot wav-ocn mom flux'
     !
     ! 7) Wave-bottom layer
     !
     noge(7) = 5
     !
     idout( 7, 1)  = 'Bottom rms ampl.    '
     idout( 7, 2)  = 'Bottom rms velocity '
     idout( 7, 3)  = 'Bedform parameters  '
     idout( 7, 4)  = 'Energy diss. in WBBL'
     idout( 7, 5)  = 'Moment. loss in WBBL'
     !      IDOUT( 7, 6)  = 'Bottom mean period  '
     !      IDOUT( 7, 7)  = 'Bottom mean direct  '
     !      IDOUT( 7, 8)  = 'Bottom direct spread'
     !      IDOUT( 7, 9)  = 'Calc grain rough K_N'
     !
     ! 8) Spectrum parameters
     !
     noge(8) = 9
     !
     idout( 8, 1)  = 'Mean square slopes  '
     idout( 8, 2)  = 'Phillips tail const'
     idout( 8, 3)  = 'Slope direction     '
     idout( 8, 4)  = 'Tail slope direction'
     idout( 8, 5)  = 'Goda peakedness parm'
     idout( 8, 6)  = 'kxky-peakdness      '
     idout( 8, 7)  = 'Skewness            '
     idout( 8, 8)  = 'EM bias(l120+l102)/8'
     idout( 8, 9)  = 'Tracker bias:-l300/8'
     !      IDOUT( 8, 3)  = 'Lx-Ly mean wvlength'
     !      IDOUT( 8, 4)  = 'Surf grad correl XT'
     !      IDOUT( 8, 5)  = 'Surf grad correl YT'
     !      IDOUT( 8, 6)  = 'Surf grad correl XY'
     !      IDOUT( 8, 7)  = 'Surface crest param'
     !      IDOUT( 8, 3)  = '3rd spectral moment '
     !      IDOUT( 8, 4)  = '4th spectral moment '
     !      IDOUT( 8, 6)  = 'Kurtosis            '
     !      IDOUT( 8, 7)  = 'Skewness            '
     !
     ! 9) Numerical diagnostics
     !
     noge(9) = 5
     !
     idout( 9, 1)  = 'Avg. time step.     '
     idout( 9, 2)  = 'Cut-off freq.       '
     idout( 9, 3)  = 'Maximum spatial CFL '
     idout( 9, 4)  = 'Maximum angular CFL '
     idout( 9, 5)  = 'Maximum k advect CFL'
     !      IDOUT( 9, 6)  = 'Avg intrsp proptstep'
     !
     ! 10) User defined
     !
     noge(10) = noextr
     !
     DO i=1, min( 20 , noextr )
       WRITE (string,'(A14,I2.2,A4)') 'User defined #', i, '    '
       idout(10, i) = string
     END DO
     !
 #ifdef W3_T
     WRITE (ndstst,9000) ngrids
 #endif
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3NOUT : NGRIDS NOT YET SET *** '/         &
          '                    NGRIDS = ',i10/                   &
          '                    RUN W3NMOD FIRST'/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3NOUT : SETTING UP FOR ',i4,' GRIDS')
 #endif
     !/
     !/ End of W3NOUT ----------------------------------------------------- /
     !/
References w3servmd::extcde(), idout, w3gdatmd::nauxgr, w3gdatmd::ngrids, ngrpp, noextr, noge, nogrp, noutp, outpts, and w3servmd::strace().
Referenced by gxoutf(), gxoutp(), w3bounc(), w3bound(), w3grib(), w3grid_interp(), w3gspl(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3strt(), w3trck(), w3trnc(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().
w3seto()
subroutine w3odatmd::w3seto (integer, intent(in) IMOD, integer, intent(in) NDSERR, integer, intent(in) NDSTST)
Definition at line 1523 of file w3odatmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         25-Sep-2020 |
     !/                  +-----------------------------------+
     !/
     !/    13-Dec-2004 : Origination.                        ( version 3.06 )
     !/    06-Sep-2005 : Second storage for input bound. sp. ( version 3.08 )
     !/    24-Jul-2006 : Adding unified point output storage.( version 3.10 )
     !/    25-Jul-2006 : Originating grid ID for points.     ( version 3.10 )
     !/    04-Oct-2006 : Add filter to array pointers.       ( version 3.10 )
     !/    30-Oct-2006 : Add pars for partitioning.          ( version 3.10 )
     !/    26-Mar-2007 : Add pars for partitioning.          ( version 3.11 )
     !/    17-May-2007 : Adding NTPROC/NAPROC separation.    ( version 3.11 )
     !/    27-Jul-2010 : Add NKI, NTHI, XFRI, FR1I, TH1I.    ( version 3.14.3 )
     !/    19-Dec-2012 : Move NOSWLL to data structure.      ( version 4.11 )
     !/    12-Dec-2014 : Modify instanciation of NRQTR       ( version 5.04 )
     !/    25-Sep-2020 : Flags for coupling restart          ( version 7.10 )
     !/
     !  1. Purpose :
     !
     !     Select one of the WAVEWATCH III grids / models.
     !
     !  2. Method :
     !
     !     Point pointers to the proper variables in the proper element of
     !     the GRIDS array.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       IMOD    Int.   I   Model number to point to.
     !       NDSERR  Int.   I   Error output unit number.
     !       NDSTST  Int.   I   Test output unit number.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !     See module documentation below.
     !
     !  5. Called by :
     !
     !     Many subroutines in the WAVEWATCH system.
     !
     !  6. Error messages :
     !
     !     Checks on parameter list IMOD.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !  9. Switches :
     !
     !     !/MPI  MPI specific calls.
     !     !/S    Enable subroutine tracing.
     !     !/T    Enable test output
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gdatmd, ONLY: nauxgr
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: IMOD, NDSERR, NDSTST
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NLOW
     INTEGER                 :: J
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'W3SETO')
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Test input and module status
     !
     IF ( noutp .EQ. -1 ) THEN
       WRITE (ndserr,1001)
       CALL extcde (1)
     END IF
     !
     nlow   = min( 0 , -nauxgr )
     IF ( imod.LT.nlow .OR. imod.GT.noutp ) THEN
       WRITE (ndserr,1002) imod, nlow, noutp
       CALL extcde (2)
     END IF
     !
 #ifdef W3_T
     WRITE (ndstst,9000) imod
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 2.  Set model number
     !
     ioutp  = imod
     !
     ! -------------------------------------------------------------------- /
     ! 3.  Set pointers in structure OUTPUT
     !
     ndso   => outpts(imod)%NDSO
     ndse   => outpts(imod)%NDSE
     ndst   => outpts(imod)%NDST
     screen => outpts(imod)%SCREEN
     !
     ntproc => outpts(imod)%NTPROC
     naproc => outpts(imod)%NAPROC
     iaproc => outpts(imod)%IAPROC
     naplog => outpts(imod)%NAPLOG
     napout => outpts(imod)%NAPOUT
     naperr => outpts(imod)%NAPERR
     napfld => outpts(imod)%NAPFLD
     nappnt => outpts(imod)%NAPPNT
     naptrk => outpts(imod)%NAPTRK
     naprst => outpts(imod)%NAPRST
     napbpt => outpts(imod)%NAPBPT
     napprt => outpts(imod)%NAPPRT
     !
     noswll => outpts(imod)%NOSWLL
     !
 #ifdef W3_NL5
     tosnl5 => outpts(imod)%TOSNL5
 #endif
     tofrst => outpts(imod)%TOFRST
     tonext => outpts(imod)%TONEXT
     tolast => outpts(imod)%TOLAST
     tbpi0  => outpts(imod)%TBPI0
     tbpin  => outpts(imod)%TBPIN
     nds    => outpts(imod)%NDS
     ofiles => outpts(imod)%OFILES
     !
     dtout  => outpts(imod)%DTOUT
     flout  => outpts(imod)%FLOUT
     !
     ipass1 => outpts(imod)%OUT1%IPASS1
     write1 => outpts(imod)%OUT1%WRITE1
 #ifdef W3_MPI
     nrqgo  => outpts(imod)%OUT1%NRQGO
     nrqgo2 => outpts(imod)%OUT1%NRQGO2
     IF ( nrqgo  .NE. 0 ) irqgo  => outpts(imod)%OUT1%IRQGO
     IF ( nrqgo2 .NE. 0 ) irqgo2 => outpts(imod)%OUT1%IRQGO2
 #endif
     flogrd => outpts(imod)%OUT1%FLOGRD
     flogr2 => outpts(imod)%OUT1%FLOGR2
     flogrr => outpts(imod)%OUT1%FLOGRR
     flogd   => outpts(imod)%OUT1%FLOGD
     flog2   => outpts(imod)%OUT1%FLOG2
     flogr   => outpts(imod)%OUT1%FLOGR
     !
     ipass2 => outpts(imod)%OUT2%IPASS2
     nopts  => outpts(imod)%OUT2%NOPTS
 #ifdef W3_MPI
     nrqpo  => outpts(imod)%OUT2%NRQPO
     nrqpo2 => outpts(imod)%OUT2%NRQPO2
 #endif
     o2init => outpts(imod)%OUT2%O2INIT
 #ifdef W3_MPI
     o2irqi => outpts(imod)%OUT2%O2IRQI
 #endif
     !
     IF ( o2init ) THEN
       iptint => outpts(imod)%OUT2%IPTINT
       il     => outpts(imod)%OUT2%IL
       iw     => outpts(imod)%OUT2%IW
       ii     => outpts(imod)%OUT2%II
       ptloc  => outpts(imod)%OUT2%PTLOC
       ptifac => outpts(imod)%OUT2%PTIFAC
       dpo    => outpts(imod)%OUT2%DPO
       wao    => outpts(imod)%OUT2%WAO
       zet_seto => outpts(imod)%OUT2%ZET_SETO
       wdo    => outpts(imod)%OUT2%WDO
       aso    => outpts(imod)%OUT2%ASO
 #ifdef W3_FLX5
       tauao  => outpts(imod)%OUT2%TAUAO
       taudo  => outpts(imod)%OUT2%TAUDO
       dairo  => outpts(imod)%OUT2%DAIRO
 #endif
       cao    => outpts(imod)%OUT2%CAO
       cdo    => outpts(imod)%OUT2%CDO
       iceo   => outpts(imod)%OUT2%ICEO
       iceho  => outpts(imod)%OUT2%ICEHO
       icefo  => outpts(imod)%OUT2%ICEFO
       spco   => outpts(imod)%OUT2%SPCO
       ptnme  => outpts(imod)%OUT2%PTNME
       grdid  => outpts(imod)%OUT2%GRDID
     END IF
     !
 #ifdef W3_MPI
     IF ( o2irqi ) THEN
       irqpo1 => outpts(imod)%OUT2%IRQPO1
       irqpo2 => outpts(imod)%OUT2%IRQPO2
     END IF
 #endif
     !
     ipass3 => outpts(imod)%OUT3%IPASS3
 #ifdef W3_MPI
     it0pnt => outpts(imod)%OUT3%IT0PNT
     it0trk => outpts(imod)%OUT3%IT0TRK
     it0prt => outpts(imod)%OUT3%IT0PRT
     nrqtr  => outpts(imod)%OUT3%NRQTR
     IF ( nrqtr .NE. 0 ) irqtr  => outpts(imod)%OUT3%IRQTR
 #endif
     o3init => outpts(imod)%OUT3%O3INIT
     stop   => outpts(imod)%OUT3%STOP
     !
     IF ( o3init ) THEN
       mask1  => outpts(imod)%OUT3%MASK1
       mask2  => outpts(imod)%OUT3%MASK2
       trckid => outpts(imod)%OUT3%TRCKID
     END IF
     !
     ifile4 => outpts(imod)%OUT4%IFILE4
 #ifdef W3_MPI
     nrqrs  => outpts(imod)%OUT4%NRQRS
     nblkrs => outpts(imod)%OUT4%NBLKRS
     rsblks => outpts(imod)%OUT4%RSBLKS
     IF ( nrqrs .NE. 0 ) THEN
       irqrs  => outpts(imod)%OUT4%IRQRS
     END IF
     irqrss => outpts(imod)%OUT4%IRQRSS
     vaaux  => outpts(imod)%OUT4%VAAUX
 #endif
     !
     nbi    => outpts(imod)%OUT5%NBI
     nbi2   => outpts(imod)%OUT5%NBI2
     nfbpo  => outpts(imod)%OUT5%NFBPO
 #ifdef W3_MPI
     nrqbp  => outpts(imod)%OUT5%NRQBP
     nrqbp2 => outpts(imod)%OUT5%NRQBP2
 #endif
     nbo    => outpts(imod)%OUT5%NBO
     nbo2   => outpts(imod)%OUT5%NBO2
     ndsl   => outpts(imod)%OUT5%NDSL
     nki    => outpts(imod)%OUT5%NKI
     nthi   => outpts(imod)%OUT5%NTHI
     xfri   => outpts(imod)%OUT5%XFRI
     fr1i   => outpts(imod)%OUT5%FR1I
     th1i   => outpts(imod)%OUT5%TH1I
     flbpi  => outpts(imod)%OUT5%FLBPI
     flbpo  => outpts(imod)%OUT5%FLBPO
     filer  => outpts(imod)%OUT5%FILER
     filew  => outpts(imod)%OUT5%FILEW
     filed  => outpts(imod)%OUT5%FILED
     spconv => outpts(imod)%OUT5%SPCONV
     o5ini1 => outpts(imod)%OUT5%O5INI1
     o5ini2 => outpts(imod)%OUT5%O5INI2
     o5ini3 => outpts(imod)%OUT5%O5INI3
     o5ini4 => outpts(imod)%OUT5%O5INI4
     !
     IF ( o5ini1 ) THEN
       ipbpi  => outpts(imod)%OUT5%IPBPI
       isbpi  => outpts(imod)%OUT5%ISBPI
       xbpi   => outpts(imod)%OUT5%XBPI
       ybpi   => outpts(imod)%OUT5%YBPI
       rdbpi  => outpts(imod)%OUT5%RDBPI
     END IF
     !
     IF ( o5ini2 ) THEN
       ipbpo  => outpts(imod)%OUT5%IPBPO
       isbpo  => outpts(imod)%OUT5%ISBPO
       xbpo   => outpts(imod)%OUT5%XBPO
       ybpo   => outpts(imod)%OUT5%YBPO
       rdbpo  => outpts(imod)%OUT5%RDBPO
     END IF
     !
     IF ( o5ini3 ) THEN
       abpi0  => outpts(imod)%OUT5%ABPI0
       abpin  => outpts(imod)%OUT5%ABPIN
       bbpi0  => outpts(imod)%OUT5%BBPI0
       bbpin  => outpts(imod)%OUT5%BBPIN
     END IF
     !
     IF ( o5ini4 ) THEN
       abpos  => outpts(imod)%OUT5%ABPOS
     END IF
     !
 #ifdef W3_MPI
     IF ( nrqbp  .NE. 0 ) irqbp1 => outpts(imod)%OUT5%IRQBP1
     IF ( nrqbp2 .NE. 0 ) irqbp2 => outpts(imod)%OUT5%IRQBP2
 #endif
     !
     ipass6 => outpts(imod)%OUT6%IPASS6
     ihmax  => outpts(imod)%OUT6%IHMAX
     hspmin => outpts(imod)%OUT6%HSPMIN
     wsmult => outpts(imod)%OUT6%WSMULT
     wscut  => outpts(imod)%OUT6%WSCUT
     ix0    => outpts(imod)%OUT6%IX0
     ixn    => outpts(imod)%OUT6%IXN
     ixs    => outpts(imod)%OUT6%IXS
     iy0    => outpts(imod)%OUT6%IY0
     iyn    => outpts(imod)%OUT6%IYN
     iys    => outpts(imod)%OUT6%IYS
     icprt  => outpts(imod)%OUT6%ICPRT
     dtprt  => outpts(imod)%OUT6%DTPRT
     flcomb => outpts(imod)%OUT6%FLCOMB
     ptmeth => outpts(imod)%OUT6%PTMETH
     ptfcut => outpts(imod)%OUT6%PTFCUT
     flform => outpts(imod)%OUT6%FLFORM
     o6init => outpts(imod)%OUT6%O6INIT
     !
     RETURN
     !
     ! Formats
     !
 1001 FORMAT (/' *** ERROR W3SETO : GRIDS NOT INITIALIZED *** '/      &
          '                    RUN W3NMOD FIRST '/)
 1002 FORMAT (/' *** ERROR W3SETO : ILLEGAL MODEL NUMBER *** '/       &
          '                    IMOD   = ',i10/                        &
          '                    NLOW   = ',i10/                        &
          '                    NOUTP  = ',i10/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3SETO : MODEL ',i4,' SELECTED')
 #endif
     !/
     !/ End of W3SETO ----------------------------------------------------- /
     !/
References abpi0, abpin, abpos, aso, bbpi0, bbpin, dpo, dtout, dtprt, w3servmd::extcde(), filed, filer, filew, flbpi, flbpo, flcomb, flform, flog2, flogd, flogr, flogr2, flogrd, flogrr, flout, fr1i, grdid, hspmin, iaproc, icprt, ifile4, ihmax, ii, il, ioutp, ipass1, ipass2, ipass3, ipass6, ipbpi, ipbpo, iptint, irqbp1, irqbp2, irqgo, irqgo2, irqpo1, irqpo2, irqrs, irqrss, irqtr, isbpi, isbpo, it0pnt, it0prt, it0trk, iw, ix0, ixn, ixs, iy0, iyn, iys, mask1, mask2, napbpt, naperr, napfld, naplog, napout, nappnt, napprt, naproc, naprst, naptrk, w3gdatmd::nauxgr, nbi, nbi2, nblkrs, nbo, nbo2, nds, ndse, ndsl, ndso, ndst, nfbpo, nki, nopts, noswll, noutp, nrqbp, nrqbp2, nrqgo, nrqgo2, nrqpo, nrqpo2, nrqrs, nrqtr, nthi, ntproc, o2init, o2irqi, o3init, o5ini1, o5ini2, o5ini3, o5ini4, o6init, ofiles, outpts, ptfcut, ptifac, ptloc, ptmeth, ptnme, rdbpi, rdbpo, rsblks, screen, spconv, stop, w3servmd::strace(), tbpi0, tbpin, th1i, tofrst, tolast, tonext, tosnl5, trckid, vaaux, wao, wdo, write1, wscut, wsmult, xbpi, xbpo, xfri, ybpi, ybpo, and zet_seto.
Referenced by wmesmfmd::createexpmesh(), gxoutf(), gxoutp(), w3bounc(), w3bound(), w3dmo2(), w3dmo3(), w3grib(), w3grid_interp(), w3gspl(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iorsmd::w3iors(), w3iotrmd::w3iotr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3strt(), w3trck(), w3trnc(), w3uprstr(), w3wavemd::w3wave(), wmgridmd::wmgeql(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wminiomd::wmioeg(), wminiomd::wmioes(), wminiomd::wmiohg(), wminiomd::wmiohs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), wmgridmd::wmsmceql(), wmwavemd::wmwave(), and wmwavemd::wmwout().
Variable Documentation
abpi0
real, dimension(:,:), pointer w3odatmd::abpi0
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3seto(), w3updtmd::w3ubpt(), and wminiomd::wmiobg().
abpin
real, dimension(:,:), pointer w3odatmd::abpin
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3seto(), w3updtmd::w3ubpt(), and wminiomd::wmiobg().
abpos
real, dimension(:,:), pointer w3odatmd::abpos
Definition at line 541 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3dmo5(), w3iobcmd::w3iobc(), w3initmd::w3mpio(), and w3seto().
aso
real, dimension(:), pointer w3odatmd::aso
Definition at line 492 of file w3odatmd.F90.
Referenced by gxoutp(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopo().
bbpi0
real, dimension(:,:), pointer w3odatmd::bbpi0
Definition at line 541 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3dmo5(), w3psmcmd::w3psmc(), w3seto(), w3updtmd::w3ubpt(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
bbpin
real, dimension(:,:), pointer w3odatmd::bbpin
Definition at line 541 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3dmo5(), w3psmcmd::w3psmc(), w3seto(), w3updtmd::w3ubpt(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), and w3profsmd::w3xypfspsi2().
dimp
integer, parameter w3odatmd::dimp = 15
Definition at line 325 of file w3odatmd.F90.
   INTEGER, PARAMETER      :: DIMP = 15
Referenced by w3iosfmd::w3cprt(), w3iosfmd::w3iosf(), w3ounp(), and w3outp().
dpo
real, dimension(:), pointer w3odatmd::dpo
Definition at line 492 of file w3odatmd.F90.
Referenced by gxoutp(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopo().
dtout
real, dimension(:), pointer w3odatmd::dtout
Definition at line 467 of file w3odatmd.F90.
   REAL, POINTER           :: DTOUT(:)
Referenced by w3fldsmd::w3fldg(), w3initmd::w3init(), w3iotrmd::w3iotr(), w3seto(), w3shel(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
dtprt
real, dimension(:,:), pointer w3odatmd::dtprt
Definition at line 553 of file w3odatmd.F90.
Referenced by w3iosfmd::w3cprt(), w3iosfmd::w3iosf(), w3iogomd::w3outg(), and w3seto().
filed
logical, pointer w3odatmd::filed
Definition at line 546 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
filer
logical, pointer w3odatmd::filer
Definition at line 546 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
filew
logical, pointer w3odatmd::filew
Definition at line 546 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
flbpi
logical, pointer w3odatmd::flbpi
Definition at line 546 of file w3odatmd.F90.
   LOGICAL, POINTER        :: FLBPI, FLBPO, FILER, FILEW, FILED,   &
        SPCONV
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3psmcmd::w3psmc(), w3seto(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), wminitmd::wminit(), and wminitmd::wminitnml().
flbpo
logical, pointer w3odatmd::flbpo
Definition at line 546 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3seto(), wminitmd::wminit(), and wminitmd::wminitnml().
flcomb
logical, pointer w3odatmd::flcomb
Definition at line 554 of file w3odatmd.F90.
Referenced by w3partmd::w3part(), and w3seto().
flform
logical, pointer w3odatmd::flform
Definition at line 554 of file w3odatmd.F90.
   LOGICAL, POINTER        :: FLFORM, FLCOMB, O6INIT
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
flog2
logical, dimension(:), pointer w3odatmd::flog2
Definition at line 478 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), and w3seto().
flogd
logical, dimension(:), pointer w3odatmd::flogd
Definition at line 478 of file w3odatmd.F90.
Referenced by w3grib(), w3initmd::w3init(), and w3seto().
flogr
logical, dimension(:), pointer w3odatmd::flogr
Definition at line 478 of file w3odatmd.F90.
Referenced by w3seto(), and w3shel().
flogr2
logical, dimension(:,:), pointer w3odatmd::flogr2
Definition at line 478 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), w3adatmd::w3dima(), w3initmd::w3init(), w3initmd::w3mpio(), w3iogomd::w3outg(), w3seto(), w3wavemd::w3wave(), and w3adatmd::w3xdma().
flogrd
logical, dimension(:,:), pointer w3odatmd::flogrd
Definition at line 478 of file w3odatmd.F90.
   LOGICAL, POINTER        :: FLOGRD(:,:), FLOGR2(:,:),            &
        FLOGRR(:,:),FLOGD(:), FLOG2(:),      &
        FLOGR(:), WRITE1
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), gxoutf(), w3adatmd::w3dima(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3src4md::w3sds4(), w3seto(), w3wavemd::w3wave(), and w3adatmd::w3xdma().
flogrr
logical, dimension(:,:), pointer w3odatmd::flogrr
Definition at line 478 of file w3odatmd.F90.
Referenced by w3iorsmd::w3iors(), w3initmd::w3mpio(), w3seto(), w3shel(), and w3strt().
flout
logical, dimension(:), pointer w3odatmd::flout
Definition at line 468 of file w3odatmd.F90.
   LOGICAL, POINTER        :: FLOUT(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3init(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3seto(), w3shel(), w3snl5md::w3snl5(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
fnmpre
character(len=80) w3odatmd::fnmpre = './'
Definition at line 330 of file w3odatmd.F90.
   CHARACTER(LEN=80)       :: FNMPRE = './'
Referenced by gxoutf(), gxoutp(), w3ounfmetamd::init_meta(), w3bounc(), w3bound(), w3grib(), w3gridmd::w3grid(), w3grid_interp(), w3gspl(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3shel(), w3srcemd::w3srce(), w3strt(), w3trck(), w3trnc(), w3uprstr(), wminitmd::wminit(), and wminitmd::wminitnml().
fr1i
real, pointer w3odatmd::fr1i
Definition at line 540 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
grdid
character(len=13), dimension(:), pointer w3odatmd::grdid
Definition at line 502 of file w3odatmd.F90.
   CHARACTER(LEN=13), POINTER :: GRDID(:)
Referenced by gxoutp(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopp().
hspmin
real, pointer w3odatmd::hspmin
Definition at line 553 of file w3odatmd.F90.
   REAL, POINTER           :: HSPMIN, WSMULT, WSCUT, DTPRT(:,:)
Referenced by w3seto().
iaproc
integer, pointer w3odatmd::iaproc
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::all_field_integral_print(), pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::all_vaold_integral_print(), pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::block_solver_init(), w3iogomd::calc_u3stokes(), pdlib_w3profsmd::calcarray_jacobi(), pdlib_w3profsmd::calcarray_jacobi2(), pdlib_w3profsmd::calcarray_jacobi3(), pdlib_w3profsmd::calcarray_jacobi4(), pdlib_w3profsmd::calcarray_jacobi_source_1(), pdlib_w3profsmd::calcarray_jacobi_source_2(), pdlib_w3profsmd::calcarray_jacobi_spectral_1(), pdlib_w3profsmd::calcarray_jacobi_spectral_2(), pdlib_w3profsmd::calcarray_jacobi_vec(), wmesmfmd::calcstokes3d(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), w3wavset::compute_active_node(), yowfunction::computeboundaryinformation(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), w3oacpmd::cpl_oasis_define(), wmesmfmd::createexpmesh(), pdlib_w3profsmd::deallocate_pdlib_global(), pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_wave_setup_computation(), wmesmfmd::fieldindex(), w3sic5md::fsdisp(), w3parall::get_jsea_ibelong(), w3parall::init_get_isea(), w3parall::init_get_jsea_isproc(), w3snl2md::insnl2(), w3snl5md::insnl5(), pdlib_w3profsmd::jacobi_init(), yowexchangemodule::pdlib_exchange2dreal(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_mapsta_init(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), pdlib_w3profsmd::pdlib_w3xypug_block_explicit(), pdlib_w3profsmd::pdlib_w3xypug_block_implicit(), w3parall::print_my_time(), pdlib_w3profsmd::print_wn_statistic(), pdlib_w3profsmd::printtotaloffcontrib(), w3parall::prop_freq_shift(), w3parall::prop_freq_shift_m2(), w3parall::prop_refraction_pr1(), w3parall::prop_refraction_pr3(), w3partmd::ptmean(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), w3triamd::readmsh(), w3triamd::readmsh_iobp(), pdlib_w3profsmd::scal_integral_print_general(), w3triamd::set_iobp(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3parall::set_up_nseal_nsealm(), w3agcmmd::snd_fields_to_atmos(), w3igcmmd::snd_fields_to_ice(), w3ogcmmd::snd_fields_to_ocean(), w3parall::synchronize_global_array(), w3parall::synchronize_ipgl_etc_array(), pdlib_w3profsmd::test_mpi_status(), w3tidemd::tide_find_indices_analysis(), w3tidemd::tide_find_indices_prediction(), w3wavset::trig_compute_lh_stress(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_apply_precond(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_compute_system(), w3wavset::trig_wave_setup_scalar_prod(), w3wavset::trig_wave_setup_solve_poisson_neumann_dir(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3iosfmd::w3cprt(), w3adatmd::w3dima(), w3wdatmd::w3dimw(), w3updtmd::w3dzxy(), w3fldsmd::w3fldo(), w3flx1md::w3flx1(), w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3flx4md::w3flx4(), w3flx5md::w3flx5(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3sic5md::w3ic5wncg(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3pro1md::w3ktp1(), w3pro1md::w3map1(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3adatmd::w3naux(), w3ounf(), w3ounp(), w3iogomd::w3outg(), w3prnc(), w3prtide(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3sdb1md::w3sdb1(), w3src6md::w3sds6(), w3seto(), w3shel(), w3sic3md::w3sic3(), w3sic5md::w3sic5(), w3src4md::w3sin4(), w3snl2md::w3snl2(), w3snl5md::w3snl5(), w3src4md::w3spr4(), w3srcemd::w3srce(), w3strt(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3urho(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3wavset::wave_setup_computation(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wmiopomd::wmiopo(), wmwavemd::wmwave(), wmwavemd::wmwout(), and pdlib_w3profsmd::write_var_to_text_file().
icprt
integer, dimension(:,:), pointer w3odatmd::icprt
Definition at line 551 of file w3odatmd.F90.
Referenced by w3iosfmd::w3cprt(), w3iosfmd::w3iosf(), w3iogomd::w3outg(), and w3seto().
idout
character(len=20), dimension(nogrp,ngrpp) w3odatmd::idout
Definition at line 329 of file w3odatmd.F90.
   CHARACTER(LEN=20)       :: IDOUT(NOGRP,NGRPP)
Referenced by gxoutf(), w3iogomd::w3flgrdflag(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3nout(), w3ounf(), w3outf(), w3iogomd::w3readflgrd(), w3shel(), and w3uprstr().
ifdef
real, pointer w3odatmd::ifdef
Definition at line 492 of file w3odatmd.F90.
ifile4
integer, pointer w3odatmd::ifile4
Definition at line 521 of file w3odatmd.F90.
   INTEGER, POINTER        :: IFILE4
Referenced by w3iorsmd::w3iors(), and w3seto().
ihmax
integer, pointer w3odatmd::ihmax
Definition at line 551 of file w3odatmd.F90.
Referenced by w3partmd::pt_fld(), and w3seto().
ii
integer, dimension(:), pointer w3odatmd::ii
Definition at line 488 of file w3odatmd.F90.
Referenced by w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), and w3seto().
il
integer, dimension(:), pointer w3odatmd::il
Definition at line 488 of file w3odatmd.F90.
Referenced by w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), and w3seto().
iostyp
integer w3odatmd::iostyp = 1
Definition at line 321 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3init(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3shel(), wminitmd::wminit(), and wminitmd::wminitnml().
ioutp
integer w3odatmd::ioutp = -1
Definition at line 321 of file w3odatmd.F90.
Referenced by w3seto(), and w3wavemd::w3wave().
ipass1
integer, pointer w3odatmd::ipass1
Definition at line 473 of file w3odatmd.F90.
   INTEGER, POINTER        :: IPASS1
Referenced by w3iogomd::w3iogo(), and w3seto().
ipass2
integer, pointer w3odatmd::ipass2
Definition at line 484 of file w3odatmd.F90.
   INTEGER, POINTER        :: IPASS2, NOPTS
Referenced by w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3ounp(), and w3seto().
ipass3
integer, pointer w3odatmd::ipass3
Definition at line 510 of file w3odatmd.F90.
   INTEGER, POINTER        :: IPASS3
Referenced by w3iotrmd::w3iotr(), and w3seto().
ipass6
integer, pointer w3odatmd::ipass6
Definition at line 551 of file w3odatmd.F90.
   INTEGER, POINTER        :: IPASS6, IHMAX, IX0, IXN, IXS,        &
        IY0, IYN, IYS, ICPRT(:,:)
Referenced by w3iosfmd::w3iosf(), and w3seto().
ipbpi
integer, dimension(:,:), pointer w3odatmd::ipbpi
Definition at line 535 of file w3odatmd.F90.
   INTEGER, POINTER        :: IPBPI(:,:), ISBPI(:),                &
        IPBPO(:,:), ISBPO(:)
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3seto(), w3updtmd::w3ubpt(), and wmgridmd::wmglow().
ipbpo
integer, dimension(:,:), pointer w3odatmd::ipbpo
Definition at line 535 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), and w3seto().
iptint
integer, dimension(:,:,:), pointer w3odatmd::iptint
Definition at line 488 of file w3odatmd.F90.
   INTEGER, POINTER        :: IPTINT(:,:,:), IL(:), IW(:), II(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3snl5md::insnl5(), w3initmd::w3init(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3initmd::w3mpio(), w3initmd::w3mpip(), and w3seto().
irqbp1
integer, dimension(:), pointer w3odatmd::irqbp1
Definition at line 538 of file w3odatmd.F90.
   INTEGER, POINTER        :: IRQBP1(:), IRQBP2(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
irqbp2
integer, dimension(:), pointer w3odatmd::irqbp2
Definition at line 538 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
irqgo
integer, dimension(:), pointer w3odatmd::irqgo
Definition at line 476 of file w3odatmd.F90.
   INTEGER, POINTER        :: IRQGO(:), IRQGO2(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
irqgo2
integer, dimension(:), pointer w3odatmd::irqgo2
Definition at line 476 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
irqpo1
integer, dimension(:), pointer w3odatmd::irqpo1
Definition at line 490 of file w3odatmd.F90.
   INTEGER, POINTER        :: IRQPO1(:), IRQPO2(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3seto(), w3wavemd::w3wave(), and wmwavemd::wmwave().
irqpo2
integer, dimension(:), pointer w3odatmd::irqpo2
Definition at line 490 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iopomd::w3iope(), w3initmd::w3mpio(), w3initmd::w3mpip(), and w3seto().
irqrs
integer, dimension(:), pointer w3odatmd::irqrs
Definition at line 524 of file w3odatmd.F90.
   INTEGER, POINTER        :: IRQRS(:), IRQRSS(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
irqrss
integer, dimension(:), pointer w3odatmd::irqrss
Definition at line 524 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iorsmd::w3iors(), w3initmd::w3mpio(), and w3seto().
irqtr
integer, dimension(:), pointer w3odatmd::irqtr
Definition at line 513 of file w3odatmd.F90.
   INTEGER, POINTER        :: IRQTR(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), and w3seto().
isbpi
integer, dimension(:), pointer w3odatmd::isbpi
Definition at line 535 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3dmo5(), w3iobcmd::w3iobc(), w3triamd::w3nestug(), w3psmcmd::w3psmc(), w3seto(), w3updtmd::w3ubpt(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), and wmgridmd::wmglow().
isbpo
integer, dimension(:), pointer w3odatmd::isbpo
Definition at line 535 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3dmo5(), w3iobcmd::w3iobc(), w3initmd::w3mpio(), and w3seto().
it0pnt
integer, pointer w3odatmd::it0pnt
Definition at line 512 of file w3odatmd.F90.
   INTEGER, POINTER        :: IT0PNT, IT0TRK, IT0PRT, NRQTR
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3initmd::w3mpip(), and w3seto().
it0prt
integer, pointer w3odatmd::it0prt
Definition at line 512 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iosfmd::w3iosf(), w3initmd::w3mpio(), and w3seto().
it0trk
integer, pointer w3odatmd::it0trk
Definition at line 512 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3initmd::w3mpip(), and w3seto().
iw
integer, dimension(:), pointer w3odatmd::iw
Definition at line 488 of file w3odatmd.F90.
Referenced by w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), and w3seto().
ix0
integer, pointer w3odatmd::ix0
Definition at line 551 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
ixn
integer, pointer w3odatmd::ixn
Definition at line 551 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
ixs
integer, pointer w3odatmd::ixs
Definition at line 551 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
iy0
integer, pointer w3odatmd::iy0
Definition at line 551 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
iyn
integer, pointer w3odatmd::iyn
Definition at line 551 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
iys
integer, pointer w3odatmd::iys
Definition at line 551 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), and w3seto().
mask1
logical, dimension(:,:), pointer w3odatmd::mask1
Definition at line 516 of file w3odatmd.F90.
   LOGICAL, POINTER        :: MASK1(:,:), MASK2(:,:)
Referenced by w3iotrmd::w3iotr(), and w3seto().
mask2
logical, dimension(:,:), pointer w3odatmd::mask2
Definition at line 516 of file w3odatmd.F90.
Referenced by w3iotrmd::w3iotr(), and w3seto().
napbpt
integer, pointer w3odatmd::napbpt
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3initmd::w3mpio(), w3seto(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wminiomd::wmiobg().
naperr
integer, pointer w3odatmd::naperr
Definition at line 457 of file w3odatmd.F90.
Referenced by w3sic5md::fsdisp(), w3snl2md::insnl2(), w3partmd::ptmean(), w3tidemd::tide_find_indices_analysis(), w3tidemd::tide_find_indices_prediction(), w3updtmd::w3dzxy(), w3flx1md::w3flx1(), w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3flx4md::w3flx4(), w3flx5md::w3flx5(), w3sic5md::w3ic5wncg(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3pro1md::w3map1(), w3ounp(), w3prnc(), w3prtide(), w3src6md::w3sds6(), w3seto(), w3shel(), w3sic3md::w3sic3(), w3sic5md::w3sic5(), w3snl2md::w3snl2(), w3strt(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), and wmgridmd::wmglow().
napfld
integer, pointer w3odatmd::napfld
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3adatmd::w3dima(), w3initmd::w3init(), w3initmd::w3mpio(), w3iogomd::w3outg(), w3seto(), w3wavemd::w3wave(), w3adatmd::w3xdma(), wminitmd::wminit(), and wminitmd::wminitnml().
naplog
integer, pointer w3odatmd::naplog
Definition at line 457 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3seto(), w3uprstr(), w3wavemd::w3wave(), and w3wdasmd::w3wdas().
napout
integer, pointer w3odatmd::napout
Definition at line 457 of file w3odatmd.F90.
Referenced by w3snl5md::insnl5(), w3tidemd::tide_find_indices_analysis(), w3tidemd::tide_find_indices_prediction(), w3initmd::w3init(), w3iopomd::w3iopp(), w3ounp(), w3prnc(), w3prtide(), w3seto(), w3shel(), w3snl5md::w3snl5(), w3strt(), w3uprstr(), w3wavemd::w3wave(), and w3wdasmd::w3wdas().
nappnt
integer, pointer w3odatmd::nappnt
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3init(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3seto(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopo(), and wmwavemd::wmwave().
napprt
integer, pointer w3odatmd::napprt
Definition at line 457 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iosfmd::w3iosf(), w3seto(), wminitmd::wminit(), and wminitmd::wminitnml().
naproc
integer, pointer w3odatmd::naproc
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::all_va_integral_print(), pdlib_w3profsmd::apply_boundary_condition_va(), w3iogomd::calc_u3stokes(), wmesmfmd::calcstokes3d(), pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), yowfunction::computeboundaryinformation(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), w3oacpmd::cpl_oasis_define(), wmesmfmd::createexpmesh(), pdlib_field_vec::do_output_exchanges(), w3wavset::fd_collect_sxx_xy_yy(), w3wavset::fd_wave_setup_computation(), wmesmfmd::fieldindex(), w3sic5md::fsdisp(), w3parall::get_jsea_ibelong(), w3parall::init_get_isea(), w3parall::init_get_jsea_isproc(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::pdlib_iobp_init(), pdlib_w3profsmd::pdlib_mapsta_init(), w3agcmmd::rcv_fields_from_atmos(), w3igcmmd::rcv_fields_from_ice(), w3ogcmmd::rcv_fields_from_ocean(), pdlib_w3profsmd::scal_integral_print_general(), w3parall::set_up_nseal_nsealm(), wmesmfmd::setexport(), w3agcmmd::snd_fields_to_atmos(), w3igcmmd::snd_fields_to_ice(), w3ogcmmd::snd_fields_to_ocean(), w3parall::synchronize_global_array(), w3parall::synchronize_ipgl_etc_array(), pdlib_w3profsmd::test_mpi_status(), w3tidemd::tide_find_indices_analysis(), w3tidemd::tide_find_indices_prediction(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_scalar_prod(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3iosfmd::w3cprt(), w3adatmd::w3dima(), w3wdatmd::w3dimw(), w3adatmd::w3dmnl(), w3updtmd::w3dzxy(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3grid_interp(), w3sic5md::w3ic5wncg(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iopomd::w3iope(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3wavemd::w3nmin(), w3ounf(), w3ounp(), w3iogomd::w3outg(), w3prnc(), w3prtide(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3seto(), w3shel(), w3sic3md::w3sic3(), w3sic5md::w3sic5(), w3strt(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3updtmd::w3urho(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3adatmd::w3xdma(), w3wavset::wave_setup_computation(), wmmdatmd::wmdimd(), wmmdatmd::wmdimm(), wmgridmd::wmgeql(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wmiopomd::wmiopo(), wmwavemd::wmwout(), and pdlib_w3profsmd::write_var_to_text_file().
naprst
integer, pointer w3odatmd::naprst
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::unst_pdlib_write_to_file(), w3initmd::w3init(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
naptrk
integer, pointer w3odatmd::naptrk
Definition at line 457 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3init(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), w3seto(), wminitmd::wminit(), and wminitmd::wminitnml().
nbi
integer, pointer w3odatmd::nbi
Definition at line 530 of file w3odatmd.F90.
   INTEGER, POINTER        :: NBI, NBI2, NFBPO, NKI, NTHI
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3dmo5(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3triamd::w3nestug(), w3psmcmd::w3psmc(), w3seto(), w3updtmd::w3ubpt(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), wmgridmd::wmghgh(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), and wminiomd::wmiobg().
nbi2
integer, pointer w3odatmd::nbi2
Definition at line 530 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3seto(), and wmgridmd::wmglow().
nblkrs
integer, pointer w3odatmd::nblkrs
Definition at line 523 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iorsmd::w3iors(), w3initmd::w3mpio(), and w3seto().
nbo
integer, dimension(:), pointer w3odatmd::nbo
Definition at line 531 of file w3odatmd.F90.
   INTEGER, POINTER        :: NBO(:), NBO2(:), NDSL(:)
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), and w3seto().
nbo2
integer, dimension(:), pointer w3odatmd::nbo2
Definition at line 531 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3dmo5(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3initmd::w3mpio(), and w3seto().
nds
integer, dimension(:), pointer w3odatmd::nds
Definition at line 464 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3seto(), w3uprstr(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wminiomd::wmiobg().
ndse
integer, pointer w3odatmd::ndse
Definition at line 456 of file w3odatmd.F90.
Referenced by w3fld1md::appendtail(), check_err(), check_error(), pdlib_field_vec::do_output_exchanges(), w3sic5md::fsdisp(), gxoutf(), gxoutp(), w3sic3md::ic3table_cheng(), w3fld1md::infld(), w3src4md::insin4(), w3snl1md::insnl1(), w3snl2md::insnl2(), w3snl3md::insnl3(), w3snl4md::insnl4(), w3snlsmd::insnls(), w3triamd::is_in_ungrid(), w3triamd::is_in_ungrid2(), w3dispmd::liu_forward_dispersion(), w3ounfmetamd::next_line(), w3iopomd::nf90_err_check(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3partmd::ptmean(), w3nmlboundmd::read_bound_nml(), w3nmlbouncmd::read_bound_nml(), w3nmlgridmd::read_curv_nml(), w3nmlgridmd::read_depth_nml(), w3nmlgridmd::read_excluded_nml(), w3nmlounfmd::read_field_nml(), w3nmltrncmd::read_file_nml(), w3nmlounfmd::read_file_nml(), w3nmlounpmd::read_file_nml(), w3nmlprncmd::read_file_nml(), w3nmlprncmd::read_forcing_nml(), w3nmlgridmd::read_grid_nml(), w3nmlgridmd::read_inbound_nml(), w3nmlgridmd::read_mask_nml(), w3nmlgridmd::read_obst_nml(), w3nmlgridmd::read_outbound_nml(), w3nmlounpmd::read_param_nml(), w3nmlounpmd::read_point_nml(), w3nmlgridmd::read_rect_nml(), w3nmluprstrmd::read_restart_nml(), w3nmlgridmd::read_run_nml(), w3nmlgridmd::read_sed_nml(), w3nmlgridmd::read_slope_nml(), w3nmlounfmd::read_smc_nml(), w3nmlgridmd::read_smc_nml(), w3nmlounpmd::read_source_nml(), w3nmlounpmd::read_spectra_nml(), w3nmlgridmd::read_spectrum_nml(), w3nmlgridmd::read_timesteps_nml(), w3nmltrncmd::read_track_nml(), w3nmlgridmd::read_unst_nml(), w3nmluprstrmd::read_update_nml(), w3triamd::readmsh(), w3triamd::readmsh_iobp(), w3triamd::readmshobc(), w3snl4md::shlocr(), w3psmcmd::smcaverg(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), w3sic3md::smooth_k(), w3triamd::spatial_grid(), w3timemd::t2iso(), w3src4md::tabu_tauhf2(), w3tidemd::tide_find_indices_analysis(), w3tidemd::tide_find_indices_prediction(), w3timemd::u2d(), w3uostmd::uost_srctrmcompute(), w3bound(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3updtmd::w3dzxy(), w3fld1md::w3fld1(), w3fld2md::w3fld2(), w3flx1md::w3flx1(), w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3flx4md::w3flx4(), w3flx5md::w3flx5(), w3grib(), w3gspl(), w3sic3md::w3ic3wncg_cheng(), w3sic3md::w3ic3wncg_v1(), w3sic5md::w3ic5wncg(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro1md::w3map1(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3triamd::w3nestug(), w3nmlbouncmd::w3nmlbounc(), w3nmlboundmd::w3nmlbound(), w3nmlgridmd::w3nmlgrid(), w3nmlounfmd::w3nmlounf(), w3nmlounpmd::w3nmlounp(), w3nmlprncmd::w3nmlprnc(), w3nmltrncmd::w3nmltrnc(), w3nmluprstrmd::w3nmluprstr(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3psmcmd::w3psmc(), w3sis2md::w3rpwnice(), w3sbt4md::w3sbt4(), w3sbt8md::w3sbt8(), w3sbt9md::w3sbt9(), w3src6md::w3sds6(), w3seto(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src6md::w3sin6(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3psmcmd::w3smcell(), w3psmcmd::w3smcgmp(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snlsmd::w3snls(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3str1md::w3str1(), w3strt(), w3trck(), w3trnc(), w3updtmd::w3ulev(), w3uprstr(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), wmgridmd::wmglow(), wminitmd::wminit(), and wminitmd::wminitnml().
ndsl
integer, dimension(:), pointer w3odatmd::ndsl
Definition at line 531 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
ndso
integer, pointer w3odatmd::ndso
Definition at line 456 of file w3odatmd.F90.
   INTEGER, POINTER        :: NDSO, NDSE, NDST, SCREEN
Referenced by gxoutf(), gxoutp(), w3snl4md::insnl4(), w3triamd::readmsh(), w3triamd::readmsh_iobp(), w3triamd::readmshobc(), w3tidemd::tide_find_indices_analysis(), w3tidemd::tide_find_indices_prediction(), w3uostmd::uost_initgrid(), w3uostmd::uost_srctrmcompute(), w3bounc(), w3bound(), w3grib(), w3gspl(), w3initmd::w3init(), w3ounf(), w3ounp(), w3outf(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3seto(), w3snl4md::w3snl4(), w3strt(), w3trck(), w3trnc(), w3uprstr(), w3wavemd::w3wave(), and w3wdasmd::w3wdas().
ndst
integer, pointer w3odatmd::ndst
Definition at line 456 of file w3odatmd.F90.
Referenced by w3src4md::calc_ustar(), pdlib_w3profsmd::compute_mean_param(), pdlib_field_vec::do_output_exchanges(), gxoutf(), gxoutp(), w3src2md::inptab(), w3snl1md::insnl1(), w3snl2md::insnl2(), w3snl3md::insnl3(), w3snl4md::insnl4(), w3snlsmd::insnls(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), w3partmd::ptmean(), w3triamd::readmsh(), w3triamd::readmsh_iobp(), w3triamd::readmshobc(), w3psmcmd::smcaverg(), w3psmcmd::smcdcxy(), w3psmcmd::smcdhxy(), w3psmcmd::smcgradn(), w3psmcmd::smcxuno2(), w3psmcmd::smcxuno2r(), w3psmcmd::smcxuno3(), w3psmcmd::smcxuno3r(), w3psmcmd::smcyuno2(), w3psmcmd::smcyuno2r(), w3psmcmd::smcyuno3(), w3psmcmd::smcyuno3r(), w3src3md::tabu_tauhf(), w3src4md::tabu_tauhf(), w3src4md::tabu_tauhf2(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3iosfmd::w3cprt(), w3exnc(), w3wavemd::w3gath(), w3psmcmd::w3gathsmc(), w3grib(), w3gspl(), w3initmd::w3init(), w3iobcmd::w3iobc(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3iosfmd::w3iosf(), w3iotrmd::w3iotr(), w3psmcmd::w3krtn(), w3pro1md::w3ktp1(), w3pro2md::w3ktp2(), w3pro3md::w3ktp3(), w3pro2md::w3map2(), w3pro3md::w3map3(), w3initmd::w3mpii(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3wavemd::w3nmin(), w3ounp(), w3outf(), w3iogomd::w3outg(), w3outp(), w3prep(), w3prnc(), w3prtide(), w3psmcmd::w3psmc(), w3sbt1md::w3sbt1(), w3wavemd::w3scat(), w3psmcmd::w3scatsmc(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3seto(), w3sic1md::w3sic1(), w3sic2md::w3sic2(), w3sic3md::w3sic3(), w3sic4md::w3sic4(), w3sic5md::w3sic5(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3sis1md::w3sis1(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3psmcmd::w3smcell(), w3psmcmd::w3smcgmp(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snlsmd::w3snls(), w3src0md::w3spr0(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3srcemd::w3srce(), w3strt(), w3swldmd::w3swl6(), w3trck(), w3updtmd::w3ucur(), w3updtmd::w3uic1(), w3updtmd::w3uic5(), w3updtmd::w3uice(), w3updtmd::w3uini(), w3updtmd::w3ulev(), w3uprstr(), w3updtmd::w3utau(), w3updtmd::w3utrn(), w3updtmd::w3uwnd(), w3wavemd::w3wave(), w3wdasmd::w3wdas(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), wminitmd::wminit(), and wminitmd::wminitnml().
nfbpo
integer, pointer w3odatmd::nfbpo
Definition at line 530 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3dmo5(), w3iobcmd::w3iobc(), w3iogrmd::w3iogr(), w3initmd::w3mpio(), w3seto(), wminitmd::wminit(), and wminitmd::wminitnml().
ngrpp
integer, parameter w3odatmd::ngrpp = 20
Definition at line 324 of file w3odatmd.F90.
   INTEGER, PARAMETER      :: NGRPP = 20
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), gxoutf(), w3iogomd::w3flgrdflag(), w3iogomd::w3flgrdupdt(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3nout(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3iogomd::w3readflgrd(), w3shel(), w3adatmd::w3xdma(), wminitmd::wminit(), and wminitmd::wminitnml().
nki
integer, pointer w3odatmd::nki
Definition at line 530 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
noextr
integer, parameter w3odatmd::noextr = 2
Definition at line 328 of file w3odatmd.F90.
   INTEGER, PARAMETER      :: NOEXTR=  2
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), w3adatmd::w3dima(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3nout(), and w3adatmd::w3xdma().
noge
integer, dimension(nogrp) w3odatmd::noge
Definition at line 326 of file w3odatmd.F90.
   INTEGER                 :: NOGE(NOGRP)
Referenced by gxoutf(), w3ounfmetamd::init_meta(), w3ounfmetamd::teardown_meta(), w3exgi(), w3grib(), w3initmd::w3mpio(), w3nout(), w3ounf(), w3outf(), w3iogomd::w3readflgrd(), and w3wavemd::w3wave().
nogrp
integer, parameter w3odatmd::nogrp = 10
Definition at line 323 of file w3odatmd.F90.
   INTEGER, PARAMETER      :: NOGRP = 10
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), gxoutf(), w3ounfmetamd::init_meta(), w3ounfmetamd::teardown_meta(), w3iogomd::w3flgrdflag(), w3iogomd::w3flgrdupdt(), w3grib(), w3grid_interp(), w3initmd::w3init(), w3iogomd::w3iogo(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3nout(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3iogomd::w3readflgrd(), w3shel(), w3adatmd::w3xdma(), wminitmd::wminit(), and wminitmd::wminitnml().
nopts
integer, pointer w3odatmd::nopts
Definition at line 484 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), gxoutp(), w3snl5md::insnl5(), w3dmo2(), w3initmd::w3init(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3ounp(), w3outp(), w3seto(), w3snl5md::w3snl5(), wminitmd::wminit(), wminitmd::wminitnml(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), and wmwavemd::wmwave().
noswll
integer, pointer w3odatmd::noswll
Definition at line 460 of file w3odatmd.F90.
   INTEGER, POINTER        :: NOSWLL
Referenced by pdlib_field_vec::do_output_exchanges(), pdlib_field_vec::get_array_size(), gxoutf(), w3adatmd::w3dima(), w3grib(), w3grid_interp(), w3iogomd::w3iogo(), w3initmd::w3mpio(), w3ounf(), w3outf(), w3iogomd::w3outg(), w3seto(), and w3adatmd::w3xdma().
notype
integer w3odatmd::notype
Definition at line 327 of file w3odatmd.F90.
   INTEGER                 :: NOTYPE
Referenced by w3wavemd::w3gath(), w3initmd::w3init(), w3shel(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
noutp
integer w3odatmd::noutp = -1
Definition at line 321 of file w3odatmd.F90.
   INTEGER                 :: NOUTP = -1, ioutp = -1, iostyp = 1
Referenced by w3dmo2(), w3dmo3(), w3dmo5(), w3nout(), and w3seto().
nrqbp
integer, pointer w3odatmd::nrqbp
Definition at line 533 of file w3odatmd.F90.
   INTEGER, POINTER        :: NRQBP, NRQBP2
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
nrqbp2
integer, pointer w3odatmd::nrqbp2
Definition at line 533 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
nrqgo
integer, pointer w3odatmd::nrqgo
Definition at line 475 of file w3odatmd.F90.
   INTEGER, POINTER        :: NRQGO, NRQGO2
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
nrqgo2
integer, pointer w3odatmd::nrqgo2
Definition at line 475 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
nrqpo
integer, pointer w3odatmd::nrqpo
Definition at line 486 of file w3odatmd.F90.
   INTEGER, POINTER        :: NRQPO, NRQPO2
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3seto(), w3wavemd::w3wave(), and wmwavemd::wmwave().
nrqpo2
integer, pointer w3odatmd::nrqpo2
Definition at line 486 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3initmd::w3mpio(), w3initmd::w3mpip(), and w3seto().
nrqrs
integer, pointer w3odatmd::nrqrs
Definition at line 523 of file w3odatmd.F90.
   INTEGER, POINTER        :: NRQRS, NBLKRS, RSBLKS
Referenced by pdlib_field_vec::do_output_exchanges(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3seto(), and w3wavemd::w3wave().
nrqtr
integer, pointer w3odatmd::nrqtr
Definition at line 512 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iotrmd::w3iotr(), w3initmd::w3mpio(), and w3seto().
nthi
integer, pointer w3odatmd::nthi
Definition at line 530 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
ntproc
integer, pointer w3odatmd::ntproc
Definition at line 457 of file w3odatmd.F90.
   INTEGER, POINTER        :: NTPROC, NAPROC, IAPROC, NAPLOG,      &
        NAPOUT, NAPERR, NAPFLD, NAPPNT,      &
        NAPTRK, NAPRST, NAPBPT, NAPPRT
Referenced by pdlib_w3profsmd::check_array_integral_nx_r8_maxfunct(), yowfunction::computelistnp_listnpa_listiplg(), yowfunction::computelistnp_listnpa_listiplg_kernel(), pdlib_field_vec::do_output_exchanges(), pdlib_w3profsmd::pdlib_init(), pdlib_w3profsmd::scal_integral_print_general(), w3parall::set_up_nseal_nsealm(), w3parall::synchronize_global_array(), w3parall::synchronize_ipgl_etc_array(), pdlib_w3profsmd::test_mpi_status(), w3wavset::trig_set_meanvalue_to_zero(), w3wavset::trig_wave_setup_computation(), w3wavset::trig_wave_setup_scalar_prod(), pdlib_field_vec::unst_pdlib_read_from_file(), pdlib_field_vec::unst_pdlib_write_to_file(), w3adatmd::w3dima(), w3initmd::w3init(), w3iorsmd::w3iors(), w3initmd::w3mpio(), w3seto(), w3adatmd::w3xdma(), w3wavset::wave_setup_computation(), wmwavemd::wmwout(), and pdlib_w3profsmd::write_var_to_text_file().
o2init
logical, pointer w3odatmd::o2init
Definition at line 503 of file w3odatmd.F90.
   LOGICAL, POINTER        :: O2INIT
Referenced by w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3seto(), and wmiopomd::wmiopp().
o2irqi
logical, pointer w3odatmd::o2irqi
Definition at line 505 of file w3odatmd.F90.
   LOGICAL, POINTER      :: O2IRQI
Referenced by w3initmd::w3mpip(), w3seto(), and wmiopomd::wmiopp().
o3init
logical, pointer w3odatmd::o3init
Definition at line 515 of file w3odatmd.F90.
   LOGICAL, POINTER        :: O3INIT, STOP
Referenced by w3iotrmd::w3iotr(), and w3seto().
o5ini1
logical, pointer w3odatmd::o5ini1
Definition at line 545 of file w3odatmd.F90.
   LOGICAL, POINTER        :: O5INI1, O5INI2, O5INI3, O5INI4
Referenced by w3seto().
o5ini2
logical, pointer w3odatmd::o5ini2
Definition at line 545 of file w3odatmd.F90.
Referenced by w3seto().
o5ini3
logical, pointer w3odatmd::o5ini3
Definition at line 545 of file w3odatmd.F90.
Referenced by w3seto().
o5ini4
logical, pointer w3odatmd::o5ini4
Definition at line 545 of file w3odatmd.F90.
Referenced by w3seto().
o6init
logical, pointer w3odatmd::o6init
Definition at line 554 of file w3odatmd.F90.
Referenced by w3iosfmd::w3cprt(), and w3seto().
ofiles
integer, dimension(:), pointer w3odatmd::ofiles
Definition at line 466 of file w3odatmd.F90.
   INTEGER, POINTER        :: OFILES(:)
Referenced by w3iogomd::w3iogo(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3seto(), w3shel(), wminitmd::wminit(), and wminitmd::wminitnml().
outpts
type(output), dimension(:), allocatable, target w3odatmd::outpts
Definition at line 452 of file w3odatmd.F90.
   TYPE(OUTPUT), TARGET, ALLOCATABLE :: OUTPTS(:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3parall::get_jsea_ibelong(), w3parall::init_get_isea(), w3parall::init_get_jsea_isproc(), wmmdatmd::init_get_jsea_isproc_glob(), w3iosfmd::w3cprt(), w3dmo2(), w3dmo3(), w3dmo5(), w3grid_interp(), w3initmd::w3init(), w3iosfmd::w3iosf(), w3initmd::w3mpio(), w3initmd::w3mpip(), w3nout(), w3seto(), wmgridmd::wmglow(), wminitmd::wminit(), wminitmd::wminitnml(), wminiomd::wmiobg(), wminiomd::wmiobs(), wmiopomd::wmiopo(), wmiopomd::wmiopp(), and wmgridmd::wmsmceql().
ptfcut
real, pointer w3odatmd::ptfcut
Definition at line 556 of file w3odatmd.F90.
   REAL, POINTER           :: PTFCUT   ! C. Bunney; Part. 5 freq cut
Referenced by w3ounfmetamd::init_meta(), w3ounf(), and w3seto().
ptifac
real, dimension(:,:), pointer w3odatmd::ptifac
Definition at line 492 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), and w3seto().
ptloc
real, dimension(:,:), pointer w3odatmd::ptloc
Definition at line 492 of file w3odatmd.F90.
   REAL, POINTER           :: PTLOC(:,:), PTIFAC(:,:),             &
        DPO(:), WAO(:), WDO(:), ASO(:),      &
 #ifdef W3_FLX5
Referenced by gxoutp(), w3snl5md::insnl5(), w3initmd::w3init(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopp().
ptmeth
integer, pointer w3odatmd::ptmeth
Definition at line 555 of file w3odatmd.F90.
   INTEGER, POINTER        :: PTMETH   ! C. Bunney; Partitioning method
Referenced by w3ounfmetamd::init_meta(), w3iosfmd::w3cprt(), w3ounf(), and w3seto().
ptnme
character(len=40), dimension(:), pointer w3odatmd::ptnme
Definition at line 501 of file w3odatmd.F90.
   CHARACTER(LEN=40), POINTER :: PTNME(:)
Referenced by gxoutp(), w3snl5md::insnl5(), w3initmd::w3init(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3iopomd::w3iopp(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopp().
rdbpi
real, dimension(:,:), pointer w3odatmd::rdbpi
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3seto(), w3updtmd::w3ubpt(), and wmgridmd::wmglow().
rdbpo
real, dimension(:,:), pointer w3odatmd::rdbpo
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), and w3seto().
rsblks
integer, pointer w3odatmd::rsblks
Definition at line 523 of file w3odatmd.F90.
Referenced by pdlib_field_vec::do_output_exchanges(), w3iorsmd::w3iors(), w3initmd::w3mpio(), and w3seto().
screen
integer, pointer w3odatmd::screen
Definition at line 456 of file w3odatmd.F90.
Referenced by w3snl5md::insnl5(), w3initmd::w3init(), w3iopomd::w3iopp(), w3iorsmd::w3iors(), w3ounf(), w3seto(), w3snl5md::w3snl5(), w3srcemd::w3srce(), w3wavemd::w3wave(), and w3wdasmd::w3wdas().
spconv
logical, pointer w3odatmd::spconv
Definition at line 546 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
stop
logical, pointer w3odatmd::stop
Definition at line 515 of file w3odatmd.F90.
Referenced by w3iotrmd::w3iotr(), w3seto(), w3wavemd::w3wave(), and wminiomd::wmioes().
tbpi0
integer, dimension(:), pointer w3odatmd::tbpi0
Definition at line 464 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_w3xypug(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3psmcmd::w3psmc(), w3seto(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), and wminiomd::wmiobg().
tbpin
integer, dimension(:), pointer w3odatmd::tbpin
Definition at line 464 of file w3odatmd.F90.
Referenced by pdlib_w3profsmd::apply_boundary_condition(), pdlib_w3profsmd::apply_boundary_condition_va(), pdlib_w3profsmd::pdlib_explicit_block(), pdlib_w3profsmd::pdlib_jacobi_gauss_seidel_block(), pdlib_w3profsmd::pdlib_w3xypfsfct2(), pdlib_w3profsmd::pdlib_w3xypfsn2(), pdlib_w3profsmd::pdlib_w3xypfspsi2(), pdlib_w3profsmd::pdlib_w3xypug(), w3triamd::set_ug_iobp(), pdlib_w3profsmd::set_ug_iobp_pdlib_init(), w3profsmd::w3cflug(), w3pro3md::w3cflxy(), w3psmcmd::w3psmc(), w3seto(), w3wavemd::w3wave(), w3pro1md::w3xyp1(), w3pro2md::w3xyp2(), w3pro3md::w3xyp3(), w3profsmd::w3xypfsfct2(), w3profsmd::w3xypfsn2(), w3profsmd::w3xypfsnimp(), w3profsmd::w3xypfspsi2(), w3profsmd::w3xypug(), and wminiomd::wmiobg().
th1i
real, pointer w3odatmd::th1i
Definition at line 540 of file w3odatmd.F90.
Referenced by w3iobcmd::w3iobc(), and w3seto().
tofrst
integer, dimension(:), pointer w3odatmd::tofrst
Definition at line 464 of file w3odatmd.F90.
   INTEGER, POINTER        :: TOFRST(:), TONEXT(:,:), TOLAST(:,:), &
        TBPI0(:), TBPIN(:), NDS(:)
Referenced by w3initmd::w3init(), w3seto(), and w3wavemd::w3wave().
tolast
integer, dimension(:,:), pointer w3odatmd::tolast
Definition at line 464 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3iotrmd::w3iotr(), w3seto(), w3snl5md::w3snl5(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
tonext
integer, dimension(:,:), pointer w3odatmd::tonext
Definition at line 464 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), w3seto(), w3wavemd::w3wave(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().
tosnl5
integer, dimension(:), pointer w3odatmd::tosnl5
Definition at line 462 of file w3odatmd.F90.
   INTEGER, POINTER        :: TOSNL5(:)
Referenced by w3initmd::w3init(), w3seto(), w3snl5md::w3snl5(), and w3wavemd::w3wave().
trckid
character(len=32), dimension(:,:), pointer w3odatmd::trckid
Definition at line 517 of file w3odatmd.F90.
   CHARACTER(LEN=32), POINTER   :: TRCKID(:,:)
Referenced by w3iotrmd::w3iotr(), and w3seto().
unipts
logical w3odatmd::unipts = .FALSE.
Definition at line 333 of file w3odatmd.F90.
   LOGICAL                 :: UNIPTS = .false., upproc = .false.
Referenced by w3initmd::w3init(), wminitmd::wminit(), wminitmd::wminitnml(), wmgridmd::wmrspc(), and wmwavemd::wmwave().
upproc
logical w3odatmd::upproc = .FALSE.
Definition at line 333 of file w3odatmd.F90.
Referenced by w3initmd::w3init(), wminitmd::wminit(), and wminitmd::wminitnml().
vaaux
real, dimension(:,:,:), pointer w3odatmd::vaaux
Definition at line 525 of file w3odatmd.F90.
   REAL, POINTER           :: VAAUX(:,:,:)
Referenced by pdlib_field_vec::do_output_exchanges(), w3iorsmd::w3iors(), w3initmd::w3mpio(), and w3seto().
w3_flx5
real, pointer w3odatmd::w3_flx5
Definition at line 492 of file w3odatmd.F90.
wao
real, dimension(:), pointer w3odatmd::wao
Definition at line 492 of file w3odatmd.F90.
Referenced by gxoutp(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopo().
wdo
real, dimension(:), pointer w3odatmd::wdo
Definition at line 492 of file w3odatmd.F90.
Referenced by gxoutp(), w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3ounp(), w3outp(), w3seto(), and wmiopomd::wmiopo().
write1
logical, pointer w3odatmd::write1
Definition at line 478 of file w3odatmd.F90.
Referenced by w3iogomd::w3iogo(), and w3seto().
wscut
real, pointer w3odatmd::wscut
Definition at line 553 of file w3odatmd.F90.
Referenced by w3iogomd::w3outg(), w3partmd::w3part(), and w3seto().
wsmult
real, pointer w3odatmd::wsmult
Definition at line 553 of file w3odatmd.F90.
Referenced by swh_rsrt_1pw(), and w3seto().
xbpi
real, dimension(:), pointer w3odatmd::xbpi
Definition at line 541 of file w3odatmd.F90.
   REAL, POINTER           :: XBPI(:), YBPI(:), RDBPI(:,:),        &
        XBPO(:), YBPO(:), RDBPO(:,:),        &
        ABPI0(:,:), ABPIN(:,:), ABPOS(:,:),  &
        BBPI0(:,:), BBPIN(:,:)
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3triamd::w3nestug(), w3seto(), and wmgridmd::wmglow().
xbpo
real, dimension(:), pointer w3odatmd::xbpo
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), and w3seto().
xfri
real, pointer w3odatmd::xfri
Definition at line 540 of file w3odatmd.F90.
   REAL, POINTER           :: XFRI, FR1I, TH1I
Referenced by w3iobcmd::w3iobc(), and w3seto().
ybpi
real, dimension(:), pointer w3odatmd::ybpi
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), w3triamd::w3nestug(), w3seto(), and wmgridmd::wmglow().
ybpo
real, dimension(:), pointer w3odatmd::ybpo
Definition at line 541 of file w3odatmd.F90.
Referenced by w3dmo5(), w3iobcmd::w3iobc(), and w3seto().
zet_seto
real, dimension(:), pointer w3odatmd::zet_seto
Definition at line 499 of file w3odatmd.F90.
   REAL, POINTER           :: ZET_SETO(:)
Referenced by w3iopomd::w3iope(), w3iopomd::w3iopo(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3ounp(), and w3seto().