WAVEWATCH III: w3flx1md Module Reference
w3flx1md Module Reference
Flux/stress computations according to Wu (1980).
Functions/Subroutines
subroutine w3flx1 (ZWND, U10, U10D, UST, USTD, Z0, CD)
FLux/stress computations according to Wu (1980).
Detailed Description
Flux/stress computations according to Wu (1980).
Author
H. L. Tolman
Date
29-May-2009
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
w3flx1()
subroutine w3flx1md::w3flx1 (real, intent(in) ZWND, real, intent(in) U10, real, intent(in) U10D, real, intent(out) UST, real, intent(out) USTD, real, intent(out) Z0, real, intent(out) CD)
FLux/stress computations according to Wu (1980).
Parameters
[in,out] ZWND Wind height.
[in,out] U10 Wind speed.
[in,out] U10D Wind direction.
[in,out] UST Friction velocity.
[in,out] USTD Direction of friction velocity.
[in,out] Z0 Z0 in profile law.
[in,out] CD Drag coefficient.
Author
H. L. Tolman
Date
03-Jul-2006
Definition at line 89 of file w3flx1md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         03-Jul-2006 |
     !/                  +-----------------------------------+
     !/
     !/    03-Jul-2006 : Origination.                        ( version 3.09 )
     !/
     !  1. Purpose :
     !
     !     FLux/stress computations according to Wu (1980)
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       ZWND    Real   I   Wind height.
     !       U10     Real   I   Wind speed.
     !       U10D    Real   I   Wind direction.
     !       UST     Real   O   Friction velocity.
     !       USTD    Real   0   Direction of friction velocity.
     !       Z0      Real   O   z0 in profile law.
     !       CD      Real   O   Drag coefficient.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse, iaproc, naperr
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: ZWND, U10, U10D
     REAL, INTENT(OUT)       :: UST, USTD, Z0, CD
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3FLX1')
 #endif
     !
     ! 1.  Tests ---------------------------------------------------------- *
     !
     IF ( abs(zwnd-10.) .GT. 0.01 ) THEN
       IF ( iaproc .EQ. naperr ) WRITE (ndse,1000) zwnd
       CALL extcde (1)
     END IF
     !
     ! 2.  Computation ---------------------------------------------------- *
     !
     cd     = 0.001 * (0.8+0.065*u10)
     z0     = zwnd * exp( -0.4 / sqrt(cd) )
     ust    = u10 * sqrt(cd)
     ustd   = u10d
     !
     RETURN
     !
     ! Formats
     !
 1000 FORMAT (/' *** WAVEWATCH III ERROR IN W3STR1 : '/               &
          '     HIGHT OF WIND SHOULD BE 10m IN THIS APPRACH '/   &
          '     ZWND =',f8.2,'m'/)
     !/
     !/ End of W3FLX1 ----------------------------------------------------- /
     !/
References w3servmd::extcde(), w3odatmd::iaproc, w3odatmd::naperr, w3odatmd::ndse, and w3servmd::strace().
Referenced by gxexpo(), w3exnc(), w3expo(), and w3srcemd::w3srce().