WAVEWATCH III: mallocinfo_m Module Reference
mallocinfo_m Module Reference
Data Types
interface mallinfo
type mallinfo_t
This structure type is used to return information about the dynamic memory allocator.
Functions/Subroutines
subroutine getmallocinfo (malinfo)
subroutine printmallinfo (ihdnl, malinfo)
integer(8) function getvmsize ()
integer(8) function getvmrss ()
Function/Subroutine Documentation
getmallocinfo()
subroutine mallocinfo_m::getmallocinfo (type(mallinfo_t), intent(out) malinfo)
Definition at line 107 of file w3meminfo.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |                                   |
     !/                  | Aron Roland (BGS IT&E GmbH)       |
     !/                  | THomas Huxhorn (BGS IT&E GmbH     |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :        01-June-2018 |
     !/                  +-----------------------------------+
     !/
     !/    01-June-2018 : Origination.                        ( version 6.04 )
     !/
     !  1. Purpose : Init pdlib part
     !  2. Method :
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !  7. Remarks
     !  8. Structure :
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     implicit none
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local PARAMETERs
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3XXXX')
 #endif
     type(MallInfo_t), intent(out) :: malinfo
     malinfo = mallinfo()
References w3servmd::strace().
Referenced by w3servmd::print_memcheck().
getvmrss()
integer(8) function mallocinfo_m::getvmrss
Definition at line 361 of file w3meminfo.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |                                   |
     !/                  | Aron Roland (BGS IT&E GmbH)       |
     !/                  | Mathieu Dutour-Sikiric (IRB)      |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :        01-June-2018 |
     !/                  +-----------------------------------+
     !/
     !/    01-June-2018 : Origination.                        ( version 6.04 )
     !/
     !  1. Purpose : Init pdlib part
     !  2. Method :
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !  7. Remarks
     !  8. Structure :
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local PARAMETERs
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3XXXX')
 #endif
     integer(8) :: vmRSS
     character(len=80) :: stat_key, stat_value
     !
     vmrss = 0
     open(unit=1000, file="/proc/self/status", status='old', err=99)
     do while (.true.)
       read(unit=1000, fmt=*, err=88) stat_key, stat_value
       if (stat_key == 'VmRSS:') then
         read(stat_value, *) vmrss
         exit
       end if
     end do
 88  close(unit=1000)
     if (vmrss == 0) goto 99
     return
     !
 99  print *, 'ERROR: procfs not mounted or not compatible'
     vmrss = -1
References file(), and w3servmd::strace().
Referenced by printmallinfo().
getvmsize()
integer(8) function mallocinfo_m::getvmsize
Definition at line 276 of file w3meminfo.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |                                   |
     !/                  | Aron Roland (BGS IT&E GmbH)       |
     !/                  | Mathieu Dutour-Sikiric (IRB)      |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :        01-June-2018 |
     !/                  +-----------------------------------+
     !/
     !/    01-June-2018 : Origination.                        ( version 6.04 )
     !/
     !  1. Purpose : Init pdlib part
     !  2. Method :
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !  7. Remarks
     !  8. Structure :
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local PARAMETERs
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3XXXX')
 #endif
     integer(8) :: vmsize
     character(len=80) :: stat_key, stat_value
     !
     vmsize = 0
     open(unit=1000, file="/proc/self/status", status='old', err=99)
     do while (.true.)
       read(unit=1000, fmt=*, err=88) stat_key, stat_value
       if (stat_key == 'VmSize:') then
         read(stat_value, *) vmsize
         exit
       end if
     end do
 88  close(unit=1000)
     if (vmsize == 0) goto 99
     return
     !
 99  print *, 'ERROR: procfs not mounted or not compatible'
     vmsize = -1
References file(), and w3servmd::strace().
Referenced by printmallinfo().
printmallinfo()
subroutine mallocinfo_m::printmallinfo (integer, intent(in) ihdnl, type(mallinfo_t), intent(in) malinfo)
Definition at line 177 of file w3meminfo.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |                                   |
     !/                  | Aron Roland (BGS IT&E GmbH)       |
     !/                  | Mathieu Dutour-Sikiric (IRB)      |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :        01-June-2018 |
     !/                  +-----------------------------------+
     !/
     !/    01-June-2018 : Origination.                        ( version 6.04 )
     !/
     !  1. Purpose : Init pdlib part
     !  2. Method :
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !  7. Remarks
     !  8. Structure :
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local PARAMETERs
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3XXXX')
 #endif
     real :: ib2m
     integer(8) :: vmsize, vmRSS
     integer, intent(in)          :: ihdnl
     type(MallInfo_t), intent(in) :: malinfo
     if (ihdnl .lt. 1) stop 'ihndl not set'
     ib2m=1./real(1024**2)
     vmsize = getvmsize()
     vmrss  = getvmrss()
     !write(*,'(A72,2F20.10)') "Total size of memory allocated with sbrk by malloc in mbyte.  ", malinfo%arena*ib2m
     !write(*,'(A72,2F20.10)') "Total size of memory allocated with mmap, in mbytes.          ", malinfo%hblkhd*ib2m
     !write(*,'(A72,2F20.10)') "Total size of memory occupied by chunks handed out by malloc.", malinfo%uordblks*ib2m
     !write(*,'(A72,I10)') "Total number of chunks allocated with mmap.                  ", malinfo%hblks
     !write(*,'(A72,I10)') "Number of chunks not in use.                                 ", malinfo%ordblks
     !write(*,'(A72,2F20.10)') "Total size of memory occupied by free (not in use) chunks.   ", malinfo%fordblks*ib2m
     !write(*,'(A72,2F20.10)') "Size of the top-most releasable chunk borders end of the heap", malinfo%keepcost*ib2m
     write(ihdnl,'(A72,2F20.10)') "VM size in proc ", vmsize/1024.
     write(ihdnl,'(A72,2F20.10)') "RSS size in prof ", vmrss/1024.
     call flush(ihdnl)
References getvmrss(), getvmsize(), and w3servmd::strace().
Referenced by w3servmd::print_memcheck().