WAVEWATCH III: w3nmlgridmd Module Reference
w3nmlgridmd Module Reference
Data Types
type nml_coord_file_t
type nml_curv_t
type nml_depth_t
type nml_excl_body_t
type nml_excl_count_t
type nml_excl_point_t
type nml_file_t
type nml_grid_t
type nml_inbnd_count_t
type nml_inbnd_point_t
type nml_mask_t
type nml_obst_t
type nml_outbnd_count_t
type nml_outbnd_line_t
type nml_rect_t
type nml_run_t
type nml_sed_t
type nml_slope_t
type nml_smc_file_t
type nml_smc_t
type nml_spectrum_t
type nml_timesteps_t
type nml_unst_t
Functions/Subroutines
subroutine w3nmlgrid (NDSI, INFILE, NML_SPECTRUM, NML_RUN, NML_TIMESTEPS, NML_GRID, NML_RECT, NML_CURV, NML_UNST, NML_SMC, NML_DEPTH, NML_MASK, NML_OBST, NML_SLOPE, NML_SED, NML_INBND_COUNT, NML_INBND_POINT, NML_EXCL_COUNT, NML_EXCL_POINT, NML_EXCL_BODY, NML_OUTBND_COUNT, NML_OUTBND_LINE, IERR)
subroutine read_spectrum_nml (NDSI, NML_SPECTRUM)
subroutine read_run_nml (NDSI, NML_RUN)
subroutine read_timesteps_nml (NDSI, NML_TIMESTEPS)
subroutine read_grid_nml (NDSI, NML_GRID)
subroutine read_rect_nml (NDSI, NML_RECT)
subroutine read_curv_nml (NDSI, NML_CURV)
subroutine read_unst_nml (NDSI, NML_UNST)
subroutine read_smc_nml (NDSI, NML_SMC)
subroutine read_depth_nml (NDSI, NML_DEPTH)
subroutine read_mask_nml (NDSI, NML_MASK)
subroutine read_obst_nml (NDSI, NML_OBST)
subroutine read_slope_nml (NDSI, NML_SLOPE)
subroutine read_sed_nml (NDSI, NML_SED)
subroutine read_inbound_nml (NDSI, NML_INBND_COUNT, NML_INBND_POINT)
subroutine read_excluded_nml (NDSI, NML_EXCL_COUNT, NML_EXCL_POINT, NML_EXCL_BODY)
subroutine read_outbound_nml (NDSI, NML_OUTBND_COUNT, NML_OUTBND_LINE)
subroutine report_spectrum_nml (NML_SPECTRUM)
subroutine report_run_nml (NML_RUN)
subroutine report_timesteps_nml (NML_TIMESTEPS)
subroutine report_grid_nml (NML_GRID)
subroutine report_rect_nml (NML_RECT)
subroutine report_curv_nml (NML_CURV)
subroutine report_unst_nml (NML_UNST)
subroutine report_smc_nml (NML_SMC)
subroutine report_depth_nml (NML_DEPTH)
subroutine report_mask_nml (NML_MASK)
subroutine report_obst_nml (NML_OBST)
subroutine report_slope_nml (NML_SLOPE)
subroutine report_sed_nml (NML_SED)
subroutine report_inbound_nml (NML_INBND_COUNT, NML_INBND_POINT)
subroutine report_excluded_nml (NML_EXCL_COUNT, NML_EXCL_POINT, NML_EXCL_BODY)
subroutine report_outbound_nml (NML_OUTBND_COUNT, NML_OUTBND_LINE)
Variables
character(256) msg
integer ndsn
Function/Subroutine Documentation
read_curv_nml()
subroutine w3nmlgridmd::read_curv_nml (integer, intent(in) NDSI, type(nml_curv_t), intent(inout) NML_CURV)
Definition at line 1040 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_CURV         Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_CURV_T), INTENT(INOUT)      :: NML_CURV
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_CURV_T) :: CURV
     namelist /curv_nml/ curv
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_CURV_NML')
 #endif
     ! set default values for curv structure
     curv%NX              = 0
     curv%NY              = 0
     !
     curv%XCOORD%SF        = 1.
     curv%XCOORD%OFF       = 0.
     curv%XCOORD%FILENAME  = 'unset'
     curv%XCOORD%IDF       = 21
     curv%XCOORD%IDLA      = 1
     curv%XCOORD%IDFM      = 1
     curv%XCOORD%FORMAT    = '(....)'
     curv%XCOORD%FROM      = 'NAME'
     !
     curv%YCOORD%SF        = 1.
     curv%YCOORD%OFF       = 0.
     curv%YCOORD%FILENAME  = 'unset'
     curv%YCOORD%IDF       = 22
     curv%YCOORD%IDLA      = 1
     curv%YCOORD%IDFM      = 1
     curv%YCOORD%FORMAT    = '(....)'
     curv%YCOORD%FROM      = 'NAME'
     ! read curv namelist
     rewind(ndsi)
     READ (ndsi, nml=curv_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_CURV_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (6)
     END IF
     ! save namelist
     nml_curv = curv
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_depth_nml()
subroutine w3nmlgridmd::read_depth_nml (integer, intent(in) NDSI, type(nml_depth_t), intent(inout) NML_DEPTH)
Definition at line 1422 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_DEPTH        Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_DEPTH_T), INTENT(INOUT)     :: NML_DEPTH
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_DEPTH_T) :: DEPTH
     namelist /depth_nml/ depth
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_DEPTH_NML')
 #endif
     ! set default values for depth structure
     depth%SF         = 1.
     depth%FILENAME   = 'unset'
     depth%IDF        = 50
     depth%IDLA       = 1
     depth%IDFM       = 1
     depth%FORMAT     = '(....)'
     depth%FROM       = 'NAME'
     ! read depth namelist
     rewind(ndsi)
     READ (ndsi, nml=depth_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_DEPTH_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (9)
     END IF
     ! save namelist
     nml_depth = depth
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_excluded_nml()
subroutine w3nmlgridmd::read_excluded_nml (integer, intent(in) NDSI, type(nml_excl_count_t), intent(inout) NML_EXCL_COUNT, type(nml_excl_point_t), dimension(:), intent(inout), allocatable NML_EXCL_POINT, type(nml_excl_body_t), dimension(:), intent(inout), allocatable NML_EXCL_BODY)
Definition at line 2106 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_EXCL_COUNT   Type.
     !      NML_EXCL_POINT   Type.
     !      NML_EXCL_BODY    Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                      :: NDSI
     TYPE(NML_EXCL_COUNT_T), INTENT(INOUT)    :: NML_EXCL_COUNT
     TYPE(NML_EXCL_POINT_T), ALLOCATABLE, INTENT(INOUT)   :: NML_EXCL_POINT(:)
     TYPE(NML_EXCL_BODY_T), ALLOCATABLE, INTENT(INOUT)    :: NML_EXCL_BODY(:)
     ! locals
     INTEGER                   :: IERR, J, K
     TYPE(NML_EXCL_COUNT_T) :: EXCL_COUNT
     namelist /excl_count_nml/ excl_count
     TYPE(NML_EXCL_POINT_T), ALLOCATABLE :: EXCL_POINT(:)
     namelist /excl_point_nml/ excl_point
     TYPE(NML_EXCL_BODY_T), ALLOCATABLE :: EXCL_BODY(:)
     namelist /excl_body_nml/ excl_body
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_EXCLUDED_NML')
 #endif
     ! set default values for excl count structure
     excl_count%N_POINT    = 0
     excl_count%N_BODY     = 0
     ! read excl count namelist
     rewind(ndsi)
     READ (ndsi, nml=excl_count_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_EXCL_COUNT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (16)
     END IF
     ! allocate the total count of excluded points
     ALLOCATE(excl_point(excl_count%N_POINT))
     ALLOCATE(nml_excl_point(excl_count%N_POINT))
     ! set default values for excl point structure
     IF (excl_count%N_POINT .NE. 0 ) THEN
       DO j=1,excl_count%N_POINT
         excl_point(j)%X_INDEX  = 0
         excl_point(j)%Y_INDEX  = 0
         excl_point(j)%CONNECT  = .false.
       END DO
     END IF
     ! read excl point namelist
     rewind(ndsi)
     READ (ndsi, nml=excl_point_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_EXCL_POINT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (17)
     END IF
     ! allocate the total count of excluded bodies
     ALLOCATE(excl_body(excl_count%N_BODY))
     ALLOCATE(nml_excl_body(excl_count%N_BODY))
     ! set default values for excl body structure
     IF (excl_count%N_BODY .NE. 0 ) THEN
       DO k=1,excl_count%N_BODY
         excl_body(k)%X_INDEX  = 0
         excl_body(k)%Y_INDEX  = 0
       END DO
     END IF
     ! read excl body namelist
     rewind(ndsi)
     READ (ndsi, nml=excl_point_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_EXCL_POINT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (18)
     END IF
     ! save namelist
     nml_excl_count = excl_count
     nml_excl_point = excl_point
     nml_excl_body  = excl_body
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_grid_nml()
subroutine w3nmlgridmd::read_grid_nml (integer, intent(in) NDSI, type(nml_grid_t), intent(inout) NML_GRID)
Definition at line 821 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_GRID         Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_GRID_T), INTENT(INOUT)      :: NML_GRID
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_GRID_T) :: GRID
     namelist /grid_nml/ grid
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_GRID_NML')
 #endif
     ! set default values for grid structure
     grid%NAME       = 'unset'
     grid%NML        = 'namelists.nml'
     grid%TYPE       = 'unset'
     grid%COORD      = 'unset'
     grid%CLOS       = 'unset'
     grid%ZLIM       = 0.
     grid%DMIN       = 0.
     ! read grid namelist
     rewind(ndsi)
     READ (ndsi, nml=grid_nml, iostat=ierr, iomsg=msg)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_GRID_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (4)
     END IF
     ! save namelist
     nml_grid = grid
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_inbound_nml()
subroutine w3nmlgridmd::read_inbound_nml (integer, intent(in) NDSI, type(nml_inbnd_count_t), intent(inout) NML_INBND_COUNT, type(nml_inbnd_point_t), dimension(:), intent(inout), allocatable NML_INBND_POINT)
Definition at line 1973 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_INBND_COUNT  Type.
     !      NML_INBND_POINT  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                      :: NDSI
     TYPE(NML_INBND_COUNT_T), INTENT(INOUT)   :: NML_INBND_COUNT
     TYPE(NML_INBND_POINT_T), ALLOCATABLE, INTENT(INOUT)   :: NML_INBND_POINT(:)
     ! locals
     INTEGER                   :: IERR, I
     TYPE(NML_INBND_COUNT_T) :: INBND_COUNT
     namelist /inbnd_count_nml/ inbnd_count
     TYPE(NML_INBND_POINT_T), ALLOCATABLE :: INBND_POINT(:)
     namelist /inbnd_point_nml/ inbnd_point
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_INBOUND_NML')
 #endif
     ! set default values for inbnd count structure
     inbnd_count%N_POINT    = 0
     ! read inbnd count namelist
     rewind(ndsi)
     READ (ndsi, nml=inbnd_count_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_INBND_COUNT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (14)
     END IF
     ! allocate the total count of inbound points
     ALLOCATE(inbnd_point(inbnd_count%N_POINT))
     ALLOCATE(nml_inbnd_point(inbnd_count%N_POINT))
     ! set default values for inbnd point structure
     IF (inbnd_count%N_POINT .NE. 0 ) THEN
       DO i=1,inbnd_count%N_POINT
         inbnd_point(i)%X_INDEX  = 0
         inbnd_point(i)%Y_INDEX  = 0
         inbnd_point(i)%CONNECT  = .false.
       END DO
     END IF
     ! read inbnd point namelist
     rewind(ndsi)
     READ (ndsi, nml=inbnd_point_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_INBND_POINT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (15)
     END IF
     ! save namelist
     nml_inbnd_count = inbnd_count
     nml_inbnd_point = inbnd_point
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_mask_nml()
subroutine w3nmlgridmd::read_mask_nml (integer, intent(in) NDSI, type(nml_mask_t), intent(inout) NML_MASK)
Definition at line 1531 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_MASK         Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_MASK_T), INTENT(INOUT)      :: NML_MASK
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_MASK_T) :: MASK
     namelist /mask_nml/ mask
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_MASK_NML')
 #endif
     ! set default values for mask structure
     mask%SF         = 1.
     mask%FILENAME   = 'unset'
     mask%IDF        = 60
     mask%IDLA       = 1
     mask%IDFM       = 1
     mask%FORMAT     = '(....)'
     mask%FROM       = 'NAME'
     ! read mask namelist
     rewind(ndsi)
     READ (ndsi, nml=mask_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_MASK_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (10)
     END IF
     ! save namelist
     nml_mask = mask
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_obst_nml()
subroutine w3nmlgridmd::read_obst_nml (integer, intent(in) NDSI, type(nml_obst_t), intent(inout) NML_OBST)
Definition at line 1641 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_OBST         Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_OBST_T), INTENT(INOUT)      :: NML_OBST
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_OBST_T) :: OBST
     namelist /obst_nml/ obst
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_OBST_NML')
 #endif
     ! set default values for obst structure
     obst%SF         = 1.
     obst%FILENAME   = 'unset'
     obst%IDF        = 70
     obst%IDLA       = 1
     obst%IDFM       = 1
     obst%FORMAT     = '(....)'
     obst%FROM       = 'NAME'
     ! read obst namelist
     rewind(ndsi)
     READ (ndsi, nml=obst_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_OBST_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (11)
     END IF
     ! save namelist
     nml_obst = obst
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_outbound_nml()
subroutine w3nmlgridmd::read_outbound_nml (integer, intent(in) NDSI, type(nml_outbnd_count_t), intent(inout) NML_OUTBND_COUNT, type(nml_outbnd_line_t), dimension(:), intent(inout), allocatable NML_OUTBND_LINE)
Definition at line 2266 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_OUTBND_COUNT Type.
     !      NML_OUTBND_LINE  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                      :: NDSI
     TYPE(NML_OUTBND_COUNT_T), INTENT(INOUT)    :: NML_OUTBND_COUNT
     TYPE(NML_OUTBND_LINE_T), ALLOCATABLE, INTENT(INOUT)   :: NML_OUTBND_LINE(:)
     ! locals
     INTEGER                   :: IERR, I
     TYPE(NML_OUTBND_COUNT_T) :: OUTBND_COUNT
     namelist /outbnd_count_nml/ outbnd_count
     TYPE(NML_OUTBND_LINE_T), ALLOCATABLE :: OUTBND_LINE(:)
     namelist /outbnd_line_nml/ outbnd_line
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_OUTBOUND_NML')
 #endif
     ! set default values for outbnd count structure
     outbnd_count%N_LINE    = 0
     ! read outbnd count namelist
     rewind(ndsi)
     READ (ndsi, nml=outbnd_count_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_OUTBND_COUNT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (19)
     END IF
     ! allocate the total count of outbound lines
     ALLOCATE(outbnd_line(outbnd_count%N_LINE))
     ALLOCATE(nml_outbnd_line(outbnd_count%N_LINE))
     ! set default values for outbnd line structure
     IF (outbnd_count%N_LINE .NE. 0 ) THEN
       DO i=1,outbnd_count%N_LINE
         outbnd_line(i)%X0   = 0.
         outbnd_line(i)%Y0   = 0.
         outbnd_line(i)%DX   = 0.
         outbnd_line(i)%DY   = 0.
         outbnd_line(i)%NP   = 0
       END DO
     END IF
     ! read outbnd line namelist
     rewind(ndsi)
     READ (ndsi, nml=outbnd_line_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_OUTBND_LINE_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (20)
     END IF
     ! save namelist
     nml_outbnd_count = outbnd_count
     nml_outbnd_line  = outbnd_line
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_rect_nml()
subroutine w3nmlgridmd::read_rect_nml (integer, intent(in) NDSI, type(nml_rect_t), intent(inout) NML_RECT)
Definition at line 930 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_RECT         Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_RECT_T), INTENT(INOUT)      :: NML_RECT
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_RECT_T) :: RECT
     namelist /rect_nml/ rect
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_RECT_NML')
 #endif
     ! set default values for rect structure
     rect%NX         = 0
     rect%NY         = 0
     rect%SX         = 0.
     rect%SY         = 0.
     rect%SF         = 1.
     rect%X0         = 0.
     rect%Y0         = 0.
     rect%SF0        = 1.
     ! read rect namelist
     rewind(ndsi)
     READ (ndsi, nml=rect_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_RECT_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (5)
     END IF
     ! save namelist
     nml_rect = rect
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_run_nml()
subroutine w3nmlgridmd::read_run_nml (integer, intent(in) NDSI, type(nml_run_t), intent(inout) NML_RUN)
Definition at line 606 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI         Int.
     !      NML_RUN      Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)            :: NDSI
     TYPE(NML_RUN_T), INTENT(INOUT) :: NML_RUN
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_RUN_T) :: RUN
     namelist /run_nml/ run
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_RUN_NML')
 #endif
     ! set default values for run structure
     run%FLDRY      = .false.
     run%FLCX       = .false.
     run%FLCY       = .false.
     run%FLCTH      = .false.
     run%FLCK       = .false.
     run%FLSOU      = .false.
     ! read run namelist
     rewind(ndsi)
     READ (ndsi, nml=run_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_RUN_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (2)
     END IF
     ! save namelist
     nml_run = run
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_sed_nml()
subroutine w3nmlgridmd::read_sed_nml (integer, intent(in) NDSI, type(nml_sed_t), intent(inout) NML_SED)
Definition at line 1862 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_SED          Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_SED_T), INTENT(INOUT)       :: NML_SED
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_SED_T) :: SED
     namelist /sed_nml/ sed
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_SED_NML')
 #endif
     ! set default values for sed structure
     sed%SF         = 1.
     sed%FILENAME   = 'unset'
     sed%IDF        = 90
     sed%IDLA       = 1
     sed%IDFM       = 1
     sed%FORMAT     = '(....)'
     sed%FROM       = 'NAME'
     ! read sed namelist
     rewind(ndsi)
     READ (ndsi, nml=sed_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_SED_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (13)
     END IF
     ! save namelist
     nml_sed = sed
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_slope_nml()
subroutine w3nmlgridmd::read_slope_nml (integer, intent(in) NDSI, type(nml_slope_t), intent(inout) NML_SLOPE)
Definition at line 1751 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_SLOPE        Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_SLOPE_T), INTENT(INOUT)     :: NML_SLOPE
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_SLOPE_T) :: SLOPE
     namelist /slope_nml/ slope
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_SLOPE_NML')
 #endif
     ! set default values for slope structure
     slope%SF         = 1.
     slope%FILENAME   = 'unset'
     slope%IDF        = 80
     slope%IDLA       = 1
     slope%IDFM       = 1
     slope%FORMAT     = '(....)'
     slope%FROM       = 'NAME'
     ! read slope namelist
     rewind(ndsi)
     READ (ndsi, nml=slope_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_SLOPE_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (12)
     END IF
     ! save namelist
     nml_slope = slope
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_smc_nml()
subroutine w3nmlgridmd::read_smc_nml (integer, intent(in) NDSI, type(nml_smc_t), intent(inout) NML_SMC)
Definition at line 1272 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_SMC          Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_SMC_T), INTENT(INOUT)       :: NML_SMC
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_SMC_T) :: SMC
     namelist /smc_nml/ smc
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_SMC_NML')
 #endif
     ! set default values for smc structure
     smc%MCELS%FILENAME   = 'unset'
     smc%MCELS%IDF        = 31
     smc%MCELS%IDLA       = 1
     smc%MCELS%IDFM       = 1
     smc%MCELS%FORMAT     = '(....)'
     !
     smc%ISIDE%FILENAME   = 'unset'
     smc%ISIDE%IDF        = 32
     smc%ISIDE%IDLA       = 1
     smc%ISIDE%IDFM       = 1
     smc%ISIDE%FORMAT     = '(....)'
     !
     smc%JSIDE%FILENAME   = 'unset'
     smc%JSIDE%IDF        = 33
     smc%JSIDE%IDLA       = 1
     smc%JSIDE%IDFM       = 1
     smc%JSIDE%FORMAT     = '(....)'
     !
     smc%SUBTR%FILENAME   = 'unset'
     smc%SUBTR%IDF        = 34
     smc%SUBTR%IDLA       = 1
     smc%SUBTR%IDFM       = 1
     smc%SUBTR%FORMAT     = '(....)'
     !
     smc%BUNDY%FILENAME   = 'unset'
     smc%BUNDY%IDF        = 35
     smc%BUNDY%IDLA       = 1
     smc%BUNDY%IDFM       = 1
     smc%BUNDY%FORMAT     = '(....)'
     !
     smc%MBARC%FILENAME   = 'unset'
     smc%MBARC%IDF        = 36
     smc%MBARC%IDLA       = 1
     smc%MBARC%IDFM       = 1
     smc%MBARC%FORMAT     = '(....)'
     !
     smc%AISID%FILENAME   = 'unset'
     smc%AISID%IDF        = 37
     smc%AISID%IDLA       = 1
     smc%AISID%IDFM       = 1
     smc%AISID%FORMAT     = '(....)'
     !
     smc%AJSID%FILENAME   = 'unset'
     smc%AJSID%IDF        = 38
     smc%AJSID%IDLA       = 1
     smc%AJSID%IDFM       = 1
     smc%AJSID%FORMAT     = '(....)'
     ! read smc namelist
     rewind(ndsi)
     READ (ndsi, nml=smc_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_SMC_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (8)
     END IF
     ! save namelist
     nml_smc = smc
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_spectrum_nml()
subroutine w3nmlgridmd::read_spectrum_nml (integer, intent(in) NDSI, type(nml_spectrum_t), intent(inout) NML_SPECTRUM)
Definition at line 499 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI            Int.
     !      NML_SPECTRUM    Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                 :: NDSI
     TYPE(NML_SPECTRUM_T), INTENT(INOUT) :: NML_SPECTRUM
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_SPECTRUM_T) :: SPECTRUM
     namelist /spectrum_nml/ spectrum
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_SPECTRUM_NML')
 #endif
     ! set default values for spectrum structure
     spectrum%XFR        = 0.
     spectrum%FREQ1      = 0.
     spectrum%NK         = 0
     spectrum%NTH        = 0
     spectrum%THOFF      = 0.
     ! read spectrum namelist
     rewind(ndsi)
     READ (ndsi, nml=spectrum_nml, iostat=ierr, iomsg=msg)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_SPECTRUM_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (1)
     END IF
     ! save namelist
     nml_spectrum = spectrum
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_timesteps_nml()
subroutine w3nmlgridmd::read_timesteps_nml (integer, intent(in) NDSI, type(nml_timesteps_t), intent(inout) NML_TIMESTEPS)
Definition at line 714 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_TIMESTEPS    Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_TIMESTEPS_T), INTENT(INOUT) :: NML_TIMESTEPS
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_TIMESTEPS_T) :: TIMESTEPS
     namelist /timesteps_nml/ timesteps
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_TIMESTEPS_NML')
 #endif
     ! set default values for timesteps structure
     timesteps%DTMAX      = 0.
     timesteps%DTXY       = 0.
     timesteps%DTKTH      = 0.
     timesteps%DTMIN      = 0.
     ! read timesteps namelist
     rewind(ndsi)
     READ (ndsi, nml=timesteps_nml, iostat=ierr, iomsg=msg)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_TIMESTEPS_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (3)
     END IF
     ! save namelist
     nml_timesteps = timesteps
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
read_unst_nml()
subroutine w3nmlgridmd::read_unst_nml (integer, intent(in) NDSI, type(nml_unst_t), intent(inout) NML_UNST)
Definition at line 1162 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI             Int.
     !      NML_UNST         Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                  :: NDSI
     TYPE(NML_UNST_T), INTENT(INOUT)      :: NML_UNST
     ! locals
     INTEGER                   :: IERR
     TYPE(NML_UNST_T) :: UNST
     namelist /unst_nml/ unst
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'READ_UNST_NML')
 #endif
     ! set default values for unst structure
     unst%SF              = 0
     unst%FILENAME        = 'unset'
     unst%IDF             = 20
     unst%IDLA            = 1
     unst%IDFM            = 1
     unst%FORMAT          = '(....)'
     unst%UGOBCFILE       = 'unset'
     ! read unst namelist
     rewind(ndsi)
     READ (ndsi, nml=unst_nml, iostat=ierr, iomsg=msg)
     IF (ierr.GT.0) THEN
       WRITE (ndse,'(A,/A)') &
            'ERROR: READ_UNST_NML: namelist read error', &
            'ERROR: '//trim(msg)
       CALL extcde (7)
     END IF
     ! save namelist
     nml_unst = unst
References w3servmd::extcde(), msg, w3odatmd::ndse, and w3servmd::strace().
Referenced by w3nmlgrid().
report_curv_nml()
subroutine w3nmlgridmd::report_curv_nml (type(nml_curv_t), intent(in) NML_CURV)
Definition at line 2856 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_CURV  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_CURV_T), INTENT(IN) :: NML_CURV
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_CURV_NML')
 #endif
     WRITE (msg,'(A)') 'CURV % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,11) trim(msg),'NX                 = ', nml_curv%NX
     WRITE (ndsn,11) trim(msg),'NY                 = ', nml_curv%NY
     !
     WRITE (ndsn,14) trim(msg),'XCOORD % SF        = ', nml_curv%XCOORD%SF
     WRITE (ndsn,14) trim(msg),'XCOORD % OFF       = ', nml_curv%XCOORD%OFF
     WRITE (ndsn,10) trim(msg),'XCOORD % FILENAME  = ', trim(nml_curv%XCOORD%FILENAME)
     WRITE (ndsn,11) trim(msg),'XCOORD % IDF       = ', nml_curv%XCOORD%IDF
     WRITE (ndsn,11) trim(msg),'XCOORD % IDLA      = ', nml_curv%XCOORD%IDLA
     WRITE (ndsn,11) trim(msg),'XCOORD % IDFM      = ', nml_curv%XCOORD%IDFM
     WRITE (ndsn,10) trim(msg),'XCOORD % FORMAT    = ', trim(nml_curv%XCOORD%FORMAT)
     WRITE (ndsn,10) trim(msg),'XCOORD % FROM      = ', trim(nml_curv%XCOORD%FROM)
     !
     WRITE (ndsn,14) trim(msg),'YCOORD % SF        = ', nml_curv%YCOORD%SF
     WRITE (ndsn,14) trim(msg),'YCOORD % OFF       = ', nml_curv%YCOORD%OFF
     WRITE (ndsn,10) trim(msg),'YCOORD % FILENAME  = ', trim(nml_curv%YCOORD%FILENAME)
     WRITE (ndsn,11) trim(msg),'YCOORD % IDF       = ', nml_curv%YCOORD%IDF
     WRITE (ndsn,11) trim(msg),'YCOORD % IDLA      = ', nml_curv%YCOORD%IDLA
     WRITE (ndsn,11) trim(msg),'YCOORD % IDFM      = ', nml_curv%YCOORD%IDFM
     WRITE (ndsn,10) trim(msg),'YCOORD % FORMAT    = ', trim(nml_curv%YCOORD%FORMAT)
     WRITE (ndsn,10) trim(msg),'YCOORD % FROM      = ', trim(nml_curv%YCOORD%FROM)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_depth_nml()
subroutine w3nmlgridmd::report_depth_nml (type(nml_depth_t), intent(in) NML_DEPTH)
Definition at line 3193 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_DEPTH  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_DEPTH_T), INTENT(IN) :: NML_DEPTH
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_DEPTH_NML')
 #endif
     WRITE (msg,'(A)') 'DEPTH % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'SF        = ', nml_depth%SF
     WRITE (ndsn,10) trim(msg),'FILENAME  = ', trim(nml_depth%FILENAME)
     WRITE (ndsn,11) trim(msg),'IDF       = ', nml_depth%IDF
     WRITE (ndsn,11) trim(msg),'IDLA      = ', nml_depth%IDLA
     WRITE (ndsn,11) trim(msg),'IDFM      = ', nml_depth%IDFM
     WRITE (ndsn,10) trim(msg),'FORMAT    = ', trim(nml_depth%FORMAT)
     WRITE (ndsn,10) trim(msg),'FROM      = ', trim(nml_depth%FROM)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_excluded_nml()
subroutine w3nmlgridmd::report_excluded_nml (type(nml_excl_count_t), intent(in) NML_EXCL_COUNT, type(nml_excl_point_t), dimension(nml_excl_count%n_point), intent(in) NML_EXCL_POINT, type(nml_excl_body_t), dimension(nml_excl_count%n_body), intent(in) NML_EXCL_BODY)
Definition at line 3776 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_EXCL_COUNT  Type
     !      NML_EXCL_POINT  Type
     !      NML_EXCL_BODY   Type
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_EXCL_COUNT_T), INTENT(IN) :: NML_EXCL_COUNT
     TYPE(NML_EXCL_POINT_T), INTENT(IN) :: NML_EXCL_POINT(NML_EXCL_COUNT%N_POINT)
     TYPE(NML_EXCL_BODY_T), INTENT(IN)  :: NML_EXCL_BODY(NML_EXCL_COUNT%N_BODY)
     ! locals
     INTEGER              :: I
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_EXCLUDED_NML')
 #endif
     WRITE (msg,'(A)') 'EXCL_COUNT % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,11) trim(msg),'N_POINT       = ', nml_excl_count%N_POINT
     WRITE (ndsn,11) trim(msg),'N_BODY        = ', nml_excl_count%N_BODY
     IF (nml_excl_count%N_POINT .NE. 0) THEN
       DO i=1,nml_excl_count%N_POINT
         WRITE (msg,'(A,I8,A)') 'EXCL_POINT(',i,') % '
         WRITE (ndsn,'(A)')
         WRITE (ndsn,11) trim(msg),'X_INDEX   = ', nml_excl_point(i)%X_INDEX
         WRITE (ndsn,11) trim(msg),'Y_INDEX   = ', nml_excl_point(i)%Y_INDEX
         WRITE (ndsn,13) trim(msg),'CONNECT   = ', nml_excl_point(i)%CONNECT
         WRITE (ndsn,'(A)')
       END DO
     END IF
     IF (nml_excl_count%N_BODY .NE. 0) THEN
       DO i=1,nml_excl_count%N_BODY
         WRITE (msg,'(A,I8,A)') 'EXCL_BODY(',i,') % '
         WRITE (ndsn,'(A)')
         WRITE (ndsn,11) trim(msg),'X_INDEX   = ', nml_excl_body(i)%X_INDEX
         WRITE (ndsn,11) trim(msg),'Y_INDEX   = ', nml_excl_body(i)%Y_INDEX
         WRITE (ndsn,'(A)')
       END DO
     END IF
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f12.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_grid_nml()
subroutine w3nmlgridmd::report_grid_nml (type(nml_grid_t), intent(in) NML_GRID)
Definition at line 2672 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_GRID  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_GRID_T), INTENT(IN) :: NML_GRID
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_GRID_NML')
 #endif
     WRITE (msg,'(A)') 'GRID % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,10) trim(msg),'NAME       = ', trim(nml_grid%NAME)
     WRITE (ndsn,10) trim(msg),'NML        = ', trim(nml_grid%NML)
     WRITE (ndsn,10) trim(msg),'TYPE       = ', trim(nml_grid%TYPE)
     WRITE (ndsn,10) trim(msg),'COORD      = ', trim(nml_grid%COORD)
     WRITE (ndsn,10) trim(msg),'CLOS       = ', trim(nml_grid%CLOS)
     WRITE (ndsn,14) trim(msg),'ZLIM       = ', nml_grid%ZLIM
     WRITE (ndsn,14) trim(msg),'DMIN       = ', nml_grid%DMIN
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_inbound_nml()
subroutine w3nmlgridmd::report_inbound_nml (type(nml_inbnd_count_t), intent(in) NML_INBND_COUNT, type(nml_inbnd_point_t), dimension(nml_inbnd_count%n_point), intent(in) NML_INBND_POINT)
Definition at line 3673 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_INBND_COUNT  Type
     !      NML_INBND_POINT  Type
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_INBND_COUNT_T), INTENT(IN) :: NML_INBND_COUNT
     TYPE(NML_INBND_POINT_T), INTENT(IN) :: NML_INBND_POINT(NML_INBND_COUNT%N_POINT)
     ! locals
     INTEGER              :: I
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_INBOUND_NML')
 #endif
     WRITE (msg,'(A)') 'INBND_COUNT % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,11) trim(msg),'N_POINT       = ', nml_inbnd_count%N_POINT
     IF (nml_inbnd_count%N_POINT .NE. 0) THEN
       DO i=1,nml_inbnd_count%N_POINT
         WRITE (msg,'(A,I8,A)') 'INBND_POINT(',i,') % '
         WRITE (ndsn,'(A)')
         WRITE (ndsn,11) trim(msg),'X_INDEX   = ', nml_inbnd_point(i)%X_INDEX
         WRITE (ndsn,11) trim(msg),'Y_INDEX   = ', nml_inbnd_point(i)%Y_INDEX
         WRITE (ndsn,13) trim(msg),'CONNECT   = ', nml_inbnd_point(i)%CONNECT
         WRITE (ndsn,'(A)')
       END DO
     END IF
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_mask_nml()
subroutine w3nmlgridmd::report_mask_nml (type(nml_mask_t), intent(in) NML_MASK)
Definition at line 3287 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_MASK  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_MASK_T), INTENT(IN) :: NML_MASK
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_MASK_NML')
 #endif
     WRITE (msg,'(A)') 'MASK % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,10) trim(msg),'FILENAME  = ', trim(nml_mask%FILENAME)
     WRITE (ndsn,11) trim(msg),'IDF       = ', nml_mask%IDF
     WRITE (ndsn,11) trim(msg),'IDLA      = ', nml_mask%IDLA
     WRITE (ndsn,11) trim(msg),'IDFM      = ', nml_mask%IDFM
     WRITE (ndsn,10) trim(msg),'FORMAT    = ', trim(nml_mask%FORMAT)
     WRITE (ndsn,10) trim(msg),'FROM      = ', trim(nml_mask%FROM)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_obst_nml()
subroutine w3nmlgridmd::report_obst_nml (type(nml_obst_t), intent(in) NML_OBST)
Definition at line 3382 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_OBST  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_OBST_T), INTENT(IN) :: NML_OBST
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_OBST_NML')
 #endif
     WRITE (msg,'(A)') 'OBST % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'SF        = ', nml_obst%SF
     WRITE (ndsn,10) trim(msg),'FILENAME  = ', trim(nml_obst%FILENAME)
     WRITE (ndsn,11) trim(msg),'IDF       = ', nml_obst%IDF
     WRITE (ndsn,11) trim(msg),'IDLA      = ', nml_obst%IDLA
     WRITE (ndsn,11) trim(msg),'IDFM      = ', nml_obst%IDFM
     WRITE (ndsn,10) trim(msg),'FORMAT    = ', trim(nml_obst%FORMAT)
     WRITE (ndsn,10) trim(msg),'FROM      = ', trim(nml_obst%FROM)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_outbound_nml()
subroutine w3nmlgridmd::report_outbound_nml (type(nml_outbnd_count_t), intent(in) NML_OUTBND_COUNT, type(nml_outbnd_line_t), dimension(nml_outbnd_count%n_line), intent(in) NML_OUTBND_LINE)
Definition at line 3892 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_OUTBND_COUNT  Type
     !      NML_OUTBND_LINE   Type
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_OUTBND_COUNT_T), INTENT(IN) :: NML_OUTBND_COUNT
     TYPE(NML_OUTBND_LINE_T), INTENT(IN)  :: NML_OUTBND_LINE(NML_OUTBND_COUNT%N_LINE)
     ! locals
     INTEGER              :: I
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_OUTBOUND_NML')
 #endif
     WRITE (msg,'(A)') 'OUTBND_COUNT % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,11) trim(msg),'N_LINE        = ', nml_outbnd_count%N_LINE
     IF (nml_outbnd_count%N_LINE .NE. 0) THEN
       DO i=1,nml_outbnd_count%N_LINE
         WRITE (msg,'(A,I8,A)') 'OUTBND_LINE(',i,') % '
         WRITE (ndsn,'(A)')
         WRITE (ndsn,14) trim(msg),'X0        = ', nml_outbnd_line(i)%X0
         WRITE (ndsn,14) trim(msg),'Y0        = ', nml_outbnd_line(i)%Y0
         WRITE (ndsn,14) trim(msg),'DX        = ', nml_outbnd_line(i)%DX
         WRITE (ndsn,14) trim(msg),'DY        = ', nml_outbnd_line(i)%DY
         WRITE (ndsn,11) trim(msg),'NP        = ', nml_outbnd_line(i)%NP
         WRITE (ndsn,'(A)')
       END DO
     END IF
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f12.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_rect_nml()
subroutine w3nmlgridmd::report_rect_nml (type(nml_rect_t), intent(in) NML_RECT)
Definition at line 2763 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_RECT  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_RECT_T), INTENT(IN) :: NML_RECT
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_RECT_NML')
 #endif
     WRITE (msg,'(A)') 'RECT % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,11) trim(msg),'NX         = ', nml_rect%NX
     WRITE (ndsn,11) trim(msg),'NY         = ', nml_rect%NY
     WRITE (ndsn,14) trim(msg),'SX         = ', nml_rect%SX
     WRITE (ndsn,14) trim(msg),'SY         = ', nml_rect%SY
     WRITE (ndsn,14) trim(msg),'SF         = ', nml_rect%SF
     WRITE (ndsn,14) trim(msg),'X0         = ', nml_rect%X0
     WRITE (ndsn,14) trim(msg),'Y0         = ', nml_rect%Y0
     WRITE (ndsn,14) trim(msg),'SF0        = ', nml_rect%SF0
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f12.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_run_nml()
subroutine w3nmlgridmd::report_run_nml (type(nml_run_t), intent(in) NML_RUN)
Definition at line 2492 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_RUN  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_RUN_T), INTENT(IN) :: NML_RUN
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_RUN_NML')
 #endif
     WRITE (msg,'(A)') 'RUN % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,13) trim(msg),'FLDRY      = ', nml_run%FLDRY
     WRITE (ndsn,13) trim(msg),'FLCX       = ', nml_run%FLCX
     WRITE (ndsn,13) trim(msg),'FLCY       = ', nml_run%FLCY
     WRITE (ndsn,13) trim(msg),'FLCTH      = ', nml_run%FLCTH
     WRITE (ndsn,13) trim(msg),'FLCK       = ', nml_run%FLCK
     WRITE (ndsn,13) trim(msg),'FLSOU      = ', nml_run%FLSOU
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_sed_nml()
subroutine w3nmlgridmd::report_sed_nml (type(nml_sed_t), intent(in) NML_SED)
Definition at line 3577 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_SED  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_SED_T), INTENT(IN) :: NML_SED
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_SED_NML')
 #endif
     WRITE (msg,'(A)') 'SED % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'SF        = ', nml_sed%SF
     WRITE (ndsn,10) trim(msg),'FILENAME  = ', trim(nml_sed%FILENAME)
     WRITE (ndsn,11) trim(msg),'IDF       = ', nml_sed%IDF
     WRITE (ndsn,11) trim(msg),'IDLA      = ', nml_sed%IDLA
     WRITE (ndsn,11) trim(msg),'IDFM      = ', nml_sed%IDFM
     WRITE (ndsn,10) trim(msg),'FORMAT    = ', trim(nml_sed%FORMAT)
     WRITE (ndsn,10) trim(msg),'FROM      = ', trim(nml_sed%FROM)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_slope_nml()
subroutine w3nmlgridmd::report_slope_nml (type(nml_slope_t), intent(in) NML_SLOPE)
Definition at line 3479 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_SLOPE  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_SLOPE_T), INTENT(IN) :: NML_SLOPE
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_SLOPE_NML')
 #endif
     WRITE (msg,'(A)') 'SLOPE % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'SF        = ', nml_slope%SF
     WRITE (ndsn,10) trim(msg),'FILENAME  = ', trim(nml_slope%FILENAME)
     WRITE (ndsn,11) trim(msg),'IDF       = ', nml_slope%IDF
     WRITE (ndsn,11) trim(msg),'IDLA      = ', nml_slope%IDLA
     WRITE (ndsn,11) trim(msg),'IDFM      = ', nml_slope%IDFM
     WRITE (ndsn,10) trim(msg),'FORMAT    = ', trim(nml_slope%FORMAT)
     WRITE (ndsn,10) trim(msg),'FROM      = ', trim(nml_slope%FROM)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_smc_nml()
subroutine w3nmlgridmd::report_smc_nml (type(nml_smc_t), intent(in) NML_SMC)
Definition at line 3056 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_SMC   Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_SMC_T), INTENT(IN) :: NML_SMC
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_SMC_NML')
 #endif
     WRITE (msg,'(A)') 'SMC % '
     WRITE (ndsn,'(A)')
     !
     WRITE (ndsn,10) trim(msg),'MCELS % FILENAME  = ', trim(nml_smc%MCELS%FILENAME)
     WRITE (ndsn,11) trim(msg),'MCELS % IDF       = ', nml_smc%MCELS%IDF
     WRITE (ndsn,11) trim(msg),'MCELS % IDLA      = ', nml_smc%MCELS%IDLA
     WRITE (ndsn,11) trim(msg),'MCELS % IDFM      = ', nml_smc%MCELS%IDFM
     WRITE (ndsn,10) trim(msg),'MCELS % FORMAT    = ', trim(nml_smc%MCELS%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'ISIDE % FILENAME  = ', trim(nml_smc%ISIDE%FILENAME)
     WRITE (ndsn,11) trim(msg),'ISIDE % IDF       = ', nml_smc%ISIDE%IDF
     WRITE (ndsn,11) trim(msg),'ISIDE % IDLA      = ', nml_smc%ISIDE%IDLA
     WRITE (ndsn,11) trim(msg),'ISIDE % IDFM      = ', nml_smc%ISIDE%IDFM
     WRITE (ndsn,10) trim(msg),'ISIDE % FORMAT    = ', trim(nml_smc%ISIDE%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'JSIDE % FILENAME  = ', trim(nml_smc%JSIDE%FILENAME)
     WRITE (ndsn,11) trim(msg),'JSIDE % IDF       = ', nml_smc%JSIDE%IDF
     WRITE (ndsn,11) trim(msg),'JSIDE % IDLA      = ', nml_smc%JSIDE%IDLA
     WRITE (ndsn,11) trim(msg),'JSIDE % IDFM      = ', nml_smc%JSIDE%IDFM
     WRITE (ndsn,10) trim(msg),'JSIDE % FORMAT    = ', trim(nml_smc%JSIDE%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'SUBTR % FILENAME  = ', trim(nml_smc%SUBTR%FILENAME)
     WRITE (ndsn,11) trim(msg),'SUBTR % IDF       = ', nml_smc%SUBTR%IDF
     WRITE (ndsn,11) trim(msg),'SUBTR % IDLA      = ', nml_smc%SUBTR%IDLA
     WRITE (ndsn,11) trim(msg),'SUBTR % IDFM      = ', nml_smc%SUBTR%IDFM
     WRITE (ndsn,10) trim(msg),'SUBTR % FORMAT    = ', trim(nml_smc%SUBTR%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'BUNDY % FILENAME  = ', trim(nml_smc%BUNDY%FILENAME)
     WRITE (ndsn,11) trim(msg),'BUNDY % IDF       = ', nml_smc%BUNDY%IDF
     WRITE (ndsn,11) trim(msg),'BUNDY % IDLA      = ', nml_smc%BUNDY%IDLA
     WRITE (ndsn,11) trim(msg),'BUNDY % IDFM      = ', nml_smc%BUNDY%IDFM
     WRITE (ndsn,10) trim(msg),'BUNDY % FORMAT    = ', trim(nml_smc%BUNDY%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'MBARC % FILENAME  = ', trim(nml_smc%MBARC%FILENAME)
     WRITE (ndsn,11) trim(msg),'MBARC % IDF       = ', nml_smc%MBARC%IDF
     WRITE (ndsn,11) trim(msg),'MBARC % IDLA      = ', nml_smc%MBARC%IDLA
     WRITE (ndsn,11) trim(msg),'MBARC % IDFM      = ', nml_smc%MBARC%IDFM
     WRITE (ndsn,10) trim(msg),'MBARC % FORMAT    = ', trim(nml_smc%MBARC%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'AISID % FILENAME  = ', trim(nml_smc%AISID%FILENAME)
     WRITE (ndsn,11) trim(msg),'AISID % IDF       = ', nml_smc%AISID%IDF
     WRITE (ndsn,11) trim(msg),'AISID % IDLA      = ', nml_smc%AISID%IDLA
     WRITE (ndsn,11) trim(msg),'AISID % IDFM      = ', nml_smc%AISID%IDFM
     WRITE (ndsn,10) trim(msg),'AISID % FORMAT    = ', trim(nml_smc%AISID%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'AJSID % FILENAME  = ', trim(nml_smc%AJSID%FILENAME)
     WRITE (ndsn,11) trim(msg),'AJSID % IDF       = ', nml_smc%AJSID%IDF
     WRITE (ndsn,11) trim(msg),'AJSID % IDLA      = ', nml_smc%AJSID%IDLA
     WRITE (ndsn,11) trim(msg),'AJSID % IDFM      = ', nml_smc%AJSID%IDFM
     WRITE (ndsn,10) trim(msg),'AJSID % FORMAT    = ', trim(nml_smc%AJSID%FORMAT)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_spectrum_nml()
subroutine w3nmlgridmd::report_spectrum_nml (type(nml_spectrum_t), intent(in) NML_SPECTRUM)
Definition at line 2402 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_SPECTRUM  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_SPECTRUM_T), INTENT(IN) :: NML_SPECTRUM
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_SPECTRUM_NML')
 #endif
     WRITE (msg,'(A)') 'SPECTRUM % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'XFR        = ', nml_spectrum%XFR
     WRITE (ndsn,14) trim(msg),'FREQ1      = ', nml_spectrum%FREQ1
     WRITE (ndsn,11) trim(msg),'NK         = ', nml_spectrum%NK
     WRITE (ndsn,11) trim(msg),'NTH        = ', nml_spectrum%NTH
     WRITE (ndsn,14) trim(msg),'THOFF      = ', nml_spectrum%THOFF
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_timesteps_nml()
subroutine w3nmlgridmd::report_timesteps_nml (type(nml_timesteps_t), intent(in) NML_TIMESTEPS)
Definition at line 2583 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_TIMESTEPS  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_TIMESTEPS_T), INTENT(IN) :: NML_TIMESTEPS
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_TIMESTEPS_NML')
 #endif
     WRITE (msg,'(A)') 'TIMESTEPS % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'DTMAX      = ', nml_timesteps%DTMAX
     WRITE (ndsn,14) trim(msg),'DTXY       = ', nml_timesteps%DTXY
     WRITE (ndsn,14) trim(msg),'DTKTH      = ', nml_timesteps%DTKTH
     WRITE (ndsn,14) trim(msg),'DTMIN      = ', nml_timesteps%DTMIN
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
report_unst_nml()
subroutine w3nmlgridmd::report_unst_nml (type(nml_unst_t), intent(in) NML_UNST)
Definition at line 2962 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !/
     !  1. Purpose :
     !
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NML_UNST  Type.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      W3NMLGRID Subr.   N/A    Namelist configuration routine.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     TYPE(NML_UNST_T), INTENT(IN) :: NML_UNST
 #ifdef W3_S
     INTEGER, SAVE                           :: IENT = 0
 #endif
 #ifdef W3_S
     CALL strace (ient, 'REPORT_UNST_NML')
 #endif
     WRITE (msg,'(A)') 'UNST % '
     WRITE (ndsn,'(A)')
     WRITE (ndsn,14) trim(msg),'SF        = ', nml_unst%SF
     WRITE (ndsn,10) trim(msg),'FILENAME  = ', trim(nml_unst%FILENAME)
     WRITE (ndsn,11) trim(msg),'IDF       = ', nml_unst%IDF
     WRITE (ndsn,11) trim(msg),'IDLA      = ', nml_unst%IDLA
     WRITE (ndsn,11) trim(msg),'IDFM      = ', nml_unst%IDFM
     WRITE (ndsn,10) trim(msg),'FORMAT    = ', trim(nml_unst%FORMAT)
     !
     WRITE (ndsn,10) trim(msg),'UGOBCFILE = ', trim(nml_unst%UGOBCFILE)
 10  FORMAT (a,2x,a,a)
 11  FORMAT (a,2x,a,i8)
 13  FORMAT (a,2x,a,l1)
 14  FORMAT (a,2x,a,f8.2)
References msg, ndsn, and w3servmd::strace().
Referenced by w3nmlgrid().
w3nmlgrid()
subroutine w3nmlgridmd::w3nmlgrid (integer, intent(in) NDSI, character*(*), intent(in) INFILE, type(nml_spectrum_t), intent(inout) NML_SPECTRUM, type(nml_run_t), intent(inout) NML_RUN, type(nml_timesteps_t), intent(inout) NML_TIMESTEPS, type(nml_grid_t), intent(inout) NML_GRID, type(nml_rect_t), intent(inout) NML_RECT, type(nml_curv_t), intent(inout) NML_CURV, type(nml_unst_t), intent(inout) NML_UNST, type(nml_smc_t), intent(inout) NML_SMC, type(nml_depth_t), intent(inout) NML_DEPTH, type(nml_mask_t), intent(inout) NML_MASK, type(nml_obst_t), intent(inout) NML_OBST, type(nml_slope_t), intent(inout) NML_SLOPE, type(nml_sed_t), intent(inout) NML_SED, type(nml_inbnd_count_t), intent(inout) NML_INBND_COUNT, type(nml_inbnd_point_t), dimension(:), intent(inout), allocatable NML_INBND_POINT, type(nml_excl_count_t), intent(inout) NML_EXCL_COUNT, type(nml_excl_point_t), dimension(:), intent(inout), allocatable NML_EXCL_POINT, type(nml_excl_body_t), dimension(:), intent(inout), allocatable NML_EXCL_BODY, type(nml_outbnd_count_t), intent(inout) NML_OUTBND_COUNT, type(nml_outbnd_line_t), dimension(:), intent(inout), allocatable NML_OUTBND_LINE, integer, intent(out) IERR)
Definition at line 255 of file w3nmlgridmd.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           M. Accensi              |
     !/                  |                                   |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         15-May-2018 |
     !/                  +-----------------------------------+
     !/
     !
     !  1. Purpose :
     !
     !     Reads all the namelist to define the model grid
     !
     !  2. Method :
     !
     !     See source term routines.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !      NDSI              Int.
     !      INFILE            Char.
     !      NML_SPECTRUM      Type
     !      NML_RUN           Type
     !      NML_TIMESTEPS     Type
     !      NML_GRID          Type
     !      NML_RECT          Type
     !      NML_CURV          Type
     !      NML_UNST          Type
     !      NML_SMC           Type
     !      NML_DEPTH         Type
     !      NML_MASK          Type
     !      NML_OBST          Type
     !      NML_SLOPE         Type
     !      NML_SED           Type
     !      NML_INBND_COUNT   Type
     !      NML_INBND_POINT   Type
     !      NML_EXCL_COUNT    Type
     !      NML_EXCL_POINT    Type
     !      NML_EXCL_BODY     Type
     !      NML_OUTBND_COUNT  Type
     !      NML_OUTBND_LINE   Type
     !      IERR              Int.
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD SUBROUTINE tracing.
     !      READ_SPECTRUM_NML
     !      REPORT_SPECTRUM_NML
     !      READ_RUN_NML
     !      REPORT_RUN_NML
     !      READ_TIMESTEPS_NML
     !      REPORT_TIMESTEPS_NML
     !      READ_GRID_NML
     !      REPORT_GRID_NML
     !      READ_RECT_NML
     !      REPORT_RECT_NML
     !      READ_CURV_NML
     !      REPORT_CURV_NML
     !      READ_UNST_NML
     !      REPORT_UNST_NML
     !      READ_SMC_NML
     !      REPORT_SMC_NML
     !      READ_DEPTH_NML
     !      REPORT_DEPTH_NML
     !      READ_MASK_NML
     !      REPORT_MASK_NML
     !      READ_OBST_NML
     !      REPORT_OBST_NML
     !      READ_SLOPE_NML
     !      REPORT_SLOPE_NML
     !      READ_SED_NML
     !      REPORT_SED_NML
     !      READ_INBOUND_NML
     !      REPORT_INBOUND_NML
     !      READ_EXCLUDED_NML
     !      REPORT_EXCLUDED_NML
     !      READ_OUTBOUND_NML
     !      REPORT_OUTBOUND_NML
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      TYPE  Module   Description
     !     ----------------------------------------------------------------
     !      WW3_GRID  Prog.   N/A    Preprocess model grid.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3odatmd, ONLY: ndse
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     IMPLICIT NONE
     INTEGER, INTENT(IN)                         :: NDSI
     CHARACTER*(*), INTENT(IN)                   :: INFILE
     TYPE(NML_SPECTRUM_T), INTENT(INOUT)         :: NML_SPECTRUM
     TYPE(NML_RUN_T), INTENT(INOUT)              :: NML_RUN
     TYPE(NML_TIMESTEPS_T), INTENT(INOUT)        :: NML_TIMESTEPS
     TYPE(NML_GRID_T), INTENT(INOUT)             :: NML_GRID
     TYPE(NML_RECT_T), INTENT(INOUT)             :: NML_RECT
     TYPE(NML_CURV_T), INTENT(INOUT)             :: NML_CURV
     TYPE(NML_UNST_T), INTENT(INOUT)             :: NML_UNST
     TYPE(NML_SMC_T), INTENT(INOUT)              :: NML_SMC
     TYPE(NML_DEPTH_T), INTENT(INOUT)            :: NML_DEPTH
     TYPE(NML_MASK_T), INTENT(INOUT)             :: NML_MASK
     TYPE(NML_OBST_T), INTENT(INOUT)             :: NML_OBST
     TYPE(NML_SLOPE_T), INTENT(INOUT)            :: NML_SLOPE
     TYPE(NML_SED_T), INTENT(INOUT)              :: NML_SED
     TYPE(NML_INBND_COUNT_T), INTENT(INOUT)      :: NML_INBND_COUNT
     TYPE(NML_INBND_POINT_T), ALLOCATABLE, INTENT(INOUT)      :: NML_INBND_POINT(:)
     TYPE(NML_EXCL_COUNT_T), INTENT(INOUT)       :: NML_EXCL_COUNT
     TYPE(NML_EXCL_POINT_T), ALLOCATABLE, INTENT(INOUT)       :: NML_EXCL_POINT(:)
     TYPE(NML_EXCL_BODY_T), ALLOCATABLE, INTENT(INOUT)        :: NML_EXCL_BODY(:)
     TYPE(NML_OUTBND_COUNT_T), INTENT(INOUT)     :: NML_OUTBND_COUNT
     TYPE(NML_OUTBND_LINE_T), ALLOCATABLE, INTENT(INOUT)      :: NML_OUTBND_LINE(:)
     INTEGER, INTENT(OUT)                        :: IERR
 #ifdef W3_S
     INTEGER, SAVE                             :: IENT = 0
 #endif
     ierr = 0
 #ifdef W3_S
     CALL strace (ient, 'W3NMLGRID')
 #endif
     ! open namelist log file
     ndsn = 3
     OPEN (ndsn, file=trim(infile)//'.log', form='formatted', iostat=ierr)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A)') 'ERROR: open full nml file '//trim(infile)//'.log failed'
       RETURN
     END IF
     ! open input file
     OPEN (ndsi, file=trim(infile), form='formatted', status='old', iostat=ierr)
     IF (ierr.NE.0) THEN
       WRITE (ndse,'(A)') 'ERROR: open input file '//trim(infile)//' failed'
       RETURN
     END IF
     ! read spectrum namelist
     CALL read_spectrum_nml (ndsi, nml_spectrum)
     CALL report_spectrum_nml (nml_spectrum)
     ! read run namelist
     CALL read_run_nml (ndsi, nml_run)
     CALL report_run_nml (nml_run)
     ! read timesteps namelist
     CALL read_timesteps_nml (ndsi, nml_timesteps)
     CALL report_timesteps_nml (nml_timesteps)
     ! read grid namelist
     CALL read_grid_nml (ndsi, nml_grid)
     CALL report_grid_nml (nml_grid)
     ! read rect namelist
     CALL read_rect_nml (ndsi, nml_rect)
     CALL report_rect_nml (nml_rect)
     ! read curv namelist
     CALL read_curv_nml (ndsi, nml_curv)
     CALL report_curv_nml (nml_curv)
     ! read unst namelist
     CALL read_unst_nml (ndsi, nml_unst)
     CALL report_unst_nml (nml_unst)
     ! read smc namelist
     CALL read_smc_nml (ndsi, nml_smc)
     CALL report_smc_nml (nml_smc)
     ! read depth namelist
     CALL read_depth_nml (ndsi, nml_depth)
     CALL report_depth_nml (nml_depth)
     ! read mask namelist
     CALL read_mask_nml (ndsi, nml_mask)
     CALL report_mask_nml (nml_mask)
     ! read obst namelist
     CALL read_obst_nml (ndsi, nml_obst)
     CALL report_obst_nml (nml_obst)
     ! read slope namelist
     CALL read_slope_nml (ndsi, nml_slope)
     CALL report_slope_nml (nml_slope)
     ! read sed namelist
     CALL read_sed_nml (ndsi, nml_sed)
     CALL report_sed_nml (nml_sed)
     ! read inbound namelist
     CALL read_inbound_nml (ndsi, nml_inbnd_count, nml_inbnd_point)
     CALL report_inbound_nml (nml_inbnd_count, nml_inbnd_point)
     ! read excluded namelist
     CALL read_excluded_nml (ndsi, nml_excl_count, nml_excl_point, nml_excl_body)
     CALL report_excluded_nml (nml_excl_count, nml_excl_point, nml_excl_body)
     ! read outbound namelist
     CALL read_outbound_nml (ndsi, nml_outbnd_count, nml_outbnd_line)
     CALL report_outbound_nml (nml_outbnd_count, nml_outbnd_line)
     ! close namelist files
     CLOSE (ndsi)
     CLOSE (ndsn)
References file(), w3odatmd::ndse, ndsn, read_curv_nml(), read_depth_nml(), read_excluded_nml(), read_grid_nml(), read_inbound_nml(), read_mask_nml(), read_obst_nml(), read_outbound_nml(), read_rect_nml(), read_run_nml(), read_sed_nml(), read_slope_nml(), read_smc_nml(), read_spectrum_nml(), read_timesteps_nml(), read_unst_nml(), report_curv_nml(), report_depth_nml(), report_excluded_nml(), report_grid_nml(), report_inbound_nml(), report_mask_nml(), report_obst_nml(), report_outbound_nml(), report_rect_nml(), report_run_nml(), report_sed_nml(), report_slope_nml(), report_smc_nml(), report_spectrum_nml(), report_timesteps_nml(), report_unst_nml(), and w3servmd::strace().
Referenced by w3gridmd::w3grid().
Variable Documentation
msg
character(256) w3nmlgridmd::msg
Definition at line 241 of file w3nmlgridmd.F90.
   CHARACTER(256)                :: MSG
Referenced by read_curv_nml(), read_depth_nml(), read_excluded_nml(), read_grid_nml(), read_inbound_nml(), read_mask_nml(), read_obst_nml(), read_outbound_nml(), read_rect_nml(), read_run_nml(), read_sed_nml(), read_slope_nml(), read_smc_nml(), read_spectrum_nml(), read_timesteps_nml(), read_unst_nml(), report_curv_nml(), report_depth_nml(), report_excluded_nml(), report_grid_nml(), report_inbound_nml(), report_mask_nml(), report_obst_nml(), report_outbound_nml(), report_rect_nml(), report_run_nml(), report_sed_nml(), report_slope_nml(), report_smc_nml(), report_spectrum_nml(), report_timesteps_nml(), and report_unst_nml().
ndsn
integer w3nmlgridmd::ndsn
Definition at line 242 of file w3nmlgridmd.F90.
   INTEGER                       :: NDSN
Referenced by report_curv_nml(), report_depth_nml(), report_excluded_nml(), report_grid_nml(), report_inbound_nml(), report_mask_nml(), report_obst_nml(), report_outbound_nml(), report_rect_nml(), report_run_nml(), report_sed_nml(), report_slope_nml(), report_smc_nml(), report_spectrum_nml(), report_timesteps_nml(), report_unst_nml(), and w3nmlgrid().