WAVEWATCH III: scrip_remap_vars Module Reference
scrip_remap_vars Module Reference
Functions/Subroutines
subroutine init_remap_vars
subroutine resize_remap_vars (nmap, increment)
Variables
integer(scrip_i4), parameter norm_opt_none = 1
integer(scrip_i4), parameter norm_opt_dstarea = 2
integer(scrip_i4), parameter norm_opt_frcarea = 3
integer(scrip_i4), parameter map_type_conserv = 1
integer(scrip_i4), parameter map_type_bilinear = 2
integer(scrip_i4), parameter map_type_bicubic = 3
integer(scrip_i4), parameter map_type_distwgt = 4
integer(scrip_i4), parameter map_type_particle = 5
integer(scrip_i4), save max_links_map1
integer(scrip_i4), save num_links_map1
integer(scrip_i4), save max_links_map2
integer(scrip_i4), save num_links_map2
integer(scrip_i4), save num_maps
integer(scrip_i4), save num_wts
integer(scrip_i4), save map_type
integer(scrip_i4), save norm_opt
integer(scrip_i4), save resize_increment
integer(scrip_i4), dimension(:), allocatable, save grid1_add_map1
integer(scrip_i4), dimension(:), allocatable, save grid2_add_map1
integer(scrip_i4), dimension(:), allocatable, save grid1_add_map2
integer(scrip_i4), dimension(:), allocatable, save grid2_add_map2
real(scrip_r8), dimension(:,:), allocatable, save wts_map1
real(scrip_r8), dimension(:,:), allocatable, save wts_map2
real(kind=scrip_r8) frac_lowest
real(kind=scrip_r8) frac_highest
real(kind=scrip_r8) wt_lowest
real(kind=scrip_r8) wt_highest
Function/Subroutine Documentation
init_remap_vars()
subroutine scrip_remap_vars::init_remap_vars
Definition at line 97 of file scrip_remap_vars.f.
 !-----------------------------------------------------------------------
 !
 !     this routine initializes some variables and provides an initial
 !     allocation of arrays (fairly large so frequent resizing
 !     unnecessary).
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     determine the number of weights
 !
 !-----------------------------------------------------------------------
       select case (map_type)
       case(map_type_conserv)
         num_wts = 3
       case(map_type_bilinear)
         num_wts = 1
       case(map_type_bicubic)
         num_wts = 4
       case(map_type_distwgt)
         num_wts = 1
       case(map_type_particle)
         num_wts = 1
       end select
 !-----------------------------------------------------------------------
 !
 !     initialize num_links and set max_links to four times the largest
 !     of the destination grid sizes initially (can be changed later).
 !     set a default resize increment to increase the size of link
 !     arrays if the number of links exceeds the initial size
 !
 !-----------------------------------------------------------------------
       num_links_map1 = 0
       max_links_map1 = 4*grid2_size
       if (num_maps > 1) then
         num_links_map2 = 0
         max_links_map1 = max(4*grid1_size,4*grid2_size)
         max_links_map2 = max_links_map1
       endif
       resize_increment = 0.1*max(grid1_size,grid2_size)
 !-----------------------------------------------------------------------
 !
 !     allocate address and weight arrays for mapping 1
 !
 !-----------------------------------------------------------------------
       allocate (grid1_add_map1(max_links_map1),
      &          grid2_add_map1(max_links_map1),
      &          wts_map1(num_wts, max_links_map1))
 !-----------------------------------------------------------------------
 !
 !     allocate address and weight arrays for mapping 2 if necessary
 !
 !-----------------------------------------------------------------------
       if (num_maps > 1) then
         allocate (grid1_add_map2(max_links_map2),
      &            grid2_add_map2(max_links_map2),
      &            wts_map2(num_wts, max_links_map2))
       endif
 !-----------------------------------------------------------------------
References grid1_add_map1, grid1_add_map2, scrip_grids::grid1_size, grid2_add_map1, grid2_add_map2, scrip_grids::grid2_size, map_type, map_type_bicubic, map_type_bilinear, map_type_conserv, map_type_distwgt, map_type_particle, max_links_map1, max_links_map2, num_links_map1, num_links_map2, num_maps, num_wts, resize_increment, wts_map1, and wts_map2.
Referenced by scrip_interface::scrip().
resize_remap_vars()
subroutine scrip_remap_vars::resize_remap_vars (integer (scrip_i4), intent(in) nmap, integer (scrip_i4), intent(in) increment)
Definition at line 173 of file scrip_remap_vars.f.
 !-----------------------------------------------------------------------
 !
 !     this routine resizes remapping arrays by increasing(decreasing)
 !     the max_links by increment
 !
 !-----------------------------------------------------------------------
 !-----------------------------------------------------------------------
 !
 !     input variables
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4), intent(in) ::
      &     nmap,      ! identifies which mapping array to resize
      &     increment  ! the number of links to add(subtract) to arrays
 !-----------------------------------------------------------------------
 !
 !     local variables
 !
 !-----------------------------------------------------------------------
       integer (SCRIP_i4) ::
      &   ierr,     ! error flag
      &   mxlinks   ! size of link arrays
       integer (SCRIP_i4), dimension(:), allocatable ::
      &   add1_tmp, ! temp array for resizing address arrays
      &   add2_tmp  ! temp array for resizing address arrays
       real (SCRIP_r8), dimension(:,:), allocatable ::
      &   wts_tmp   ! temp array for resizing weight arrays
 !-----------------------------------------------------------------------
 !
 !     resize map 1 arrays if required.
 !
 !-----------------------------------------------------------------------
       select case (nmap)
       case(1)
         !***
         !*** allocate temporaries to hold original values
         !***
         mxlinks = size(grid1_add_map1)
         allocate (add1_tmp(mxlinks), add2_tmp(mxlinks),
      &            wts_tmp(num_wts,mxlinks))
         add1_tmp = grid1_add_map1
         add2_tmp = grid2_add_map1
         wts_tmp  = wts_map1
         !***
         !*** deallocate originals and increment max_links then
         !*** reallocate arrays at new size
         !***
         deallocate (grid1_add_map1, grid2_add_map1, wts_map1)
         max_links_map1 = mxlinks + increment
         allocate (grid1_add_map1(max_links_map1),
      &            grid2_add_map1(max_links_map1),
      &            wts_map1(num_wts,max_links_map1))
         !***
         !*** restore original values from temp arrays and
         !*** deallocate temps
         !***
         mxlinks = min(mxlinks, max_links_map1)
         grid1_add_map1(1:mxlinks) = add1_tmp(1:mxlinks)
         grid2_add_map1(1:mxlinks) = add2_tmp(1:mxlinks)
         wts_map1(:,1:mxlinks) = wts_tmp(:,1:mxlinks)
         deallocate(add1_tmp, add2_tmp, wts_tmp)
 !-----------------------------------------------------------------------
 !
 !     resize map 2 arrays if required.
 !
 !-----------------------------------------------------------------------
       case(2)
         !***
         !*** allocate temporaries to hold original values
         !***
         mxlinks = size(grid1_add_map2)
         allocate (add1_tmp(mxlinks), add2_tmp(mxlinks),
      &            wts_tmp(num_wts,mxlinks),stat=ierr)
         if (ierr .ne. 0) then
           print *,'error allocating temps in resize: ',ierr
           stop
         endif
         add1_tmp = grid1_add_map2
         add2_tmp = grid2_add_map2
         wts_tmp  = wts_map2
         !***
         !*** deallocate originals and increment max_links then
         !*** reallocate arrays at new size
         !***
         deallocate (grid1_add_map2, grid2_add_map2, wts_map2)
         max_links_map2 = mxlinks + increment
         allocate (grid1_add_map2(max_links_map2),
      &            grid2_add_map2(max_links_map2),
      &            wts_map2(num_wts,max_links_map2),stat=ierr)
         if (ierr .ne. 0) then
           print *,'error allocating new arrays in resize: ',ierr
           stop
         endif
         !***
         !*** restore original values from temp arrays and
         !*** deallocate temps
         !***
         mxlinks = min(mxlinks, max_links_map2)
         grid1_add_map2(1:mxlinks) = add1_tmp(1:mxlinks)
         grid2_add_map2(1:mxlinks) = add2_tmp(1:mxlinks)
         wts_map2(:,1:mxlinks) = wts_tmp(:,1:mxlinks)
         deallocate(add1_tmp, add2_tmp, wts_tmp)
       end select
 !-----------------------------------------------------------------------
References grid1_add_map1, grid1_add_map2, grid2_add_map1, grid2_add_map2, max_links_map1, max_links_map2, num_wts, wts_map1, and wts_map2.
Referenced by scrip_interface::scrip(), and scrip_remap_conservative::store_link_cnsrv().
Variable Documentation
frac_highest
real (kind = scrip_r8) scrip_remap_vars::frac_highest
Definition at line 87 of file scrip_remap_vars.f.
Referenced by scrip_remap_conservative::remap_conserv(), and wmscrpmd::scrip_wrapper().
frac_lowest
real (kind = scrip_r8) scrip_remap_vars::frac_lowest
Definition at line 87 of file scrip_remap_vars.f.
       real (kind = scrip_r8) :: frac_lowest,frac_highest
Referenced by scrip_remap_conservative::remap_conserv(), and wmscrpmd::scrip_wrapper().
grid1_add_map1
integer (scrip_i4), dimension(:), allocatable, save scrip_remap_vars::grid1_add_map1
Definition at line 77 of file scrip_remap_vars.f.
       integer (SCRIP_i4), dimension(:), allocatable, save ::
      &      grid1_add_map1, ! grid1 address for each link in mapping 1
      &      grid2_add_map1, ! grid2 address for each link in mapping 1
      &      grid1_add_map2, ! grid1 address for each link in mapping 2
      &      grid2_add_map2  ! grid2 address for each link in mapping 2
Referenced by init_remap_vars(), scrip_remap_read::read_remap_scrip_ww3(), scrip_remap_conservative::remap_conserv(), resize_remap_vars(), scrip_interface::scrip(), scrip_interface::scrip_clear(), wmscrpmd::scrip_wrapper(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), scrip_remap_write::write_remap_scrip_ww3(), and scrip_remap_write::write_remap_ww3().
grid1_add_map2
integer (scrip_i4), dimension(:), allocatable, save scrip_remap_vars::grid1_add_map2
Definition at line 77 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), resize_remap_vars(), scrip_interface::scrip_clear(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), and scrip_remap_write::write_remap_ww3().
grid2_add_map1
integer (scrip_i4), dimension(:), allocatable, save scrip_remap_vars::grid2_add_map1
Definition at line 77 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_read::read_remap_scrip_ww3(), scrip_remap_conservative::remap_conserv(), resize_remap_vars(), scrip_interface::scrip(), scrip_interface::scrip_clear(), wmscrpmd::scrip_wrapper(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), scrip_remap_write::write_remap_scrip_ww3(), and scrip_remap_write::write_remap_ww3().
grid2_add_map2
integer (scrip_i4), dimension(:), allocatable, save scrip_remap_vars::grid2_add_map2
Definition at line 77 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), resize_remap_vars(), scrip_interface::scrip_clear(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), and scrip_remap_write::write_remap_ww3().
map_type
integer (scrip_i4), save scrip_remap_vars::map_type
Definition at line 66 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_read::read_remap_ww3(), scrip_interface::scrip(), scrip_interface::scrip_clear(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
map_type_bicubic
integer (scrip_i4), parameter scrip_remap_vars::map_type_bicubic = 3
Definition at line 59 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_read::read_remap_ww3(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
map_type_bilinear
integer (scrip_i4), parameter scrip_remap_vars::map_type_bilinear = 2
Definition at line 59 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_read::read_remap_ww3(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
map_type_conserv
integer (scrip_i4), parameter scrip_remap_vars::map_type_conserv = 1
Definition at line 59 of file scrip_remap_vars.f.
       integer (SCRIP_i4), parameter ::
      &      map_type_conserv  = 1
      &,     map_type_bilinear = 2
      &,     map_type_bicubic  = 3
      &,     map_type_distwgt  = 4
      &,     map_type_particle = 5
Referenced by init_remap_vars(), scrip_remap_read::read_remap_ww3(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
map_type_distwgt
integer (scrip_i4), parameter scrip_remap_vars::map_type_distwgt = 4
Definition at line 59 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_read::read_remap_ww3(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
map_type_particle
integer (scrip_i4), parameter scrip_remap_vars::map_type_particle = 5
Definition at line 59 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
max_links_map1
integer (scrip_i4), save scrip_remap_vars::max_links_map1
Definition at line 66 of file scrip_remap_vars.f.
       integer (SCRIP_i4), save ::
      &      max_links_map1  ! current size of link arrays
      &,     num_links_map1  ! actual number of links for remapping
      &,     max_links_map2  ! current size of link arrays
      &,     num_links_map2  ! actual number of links for remapping
      &,     num_maps        ! num of remappings for this grid pair
      &,     num_wts         ! num of weights used in remapping
      &,     map_type        ! identifier for remapping method
      &,     norm_opt        ! option for normalization (conserv only)
      &,     resize_increment ! default amount to increase array size
Referenced by init_remap_vars(), scrip_remap_read::read_remap_scrip_ww3(), resize_remap_vars(), scrip_interface::scrip(), scrip_interface::scrip_clear(), wmscrpmd::scrip_wrapper(), and scrip_remap_conservative::store_link_cnsrv().
max_links_map2
integer (scrip_i4), save scrip_remap_vars::max_links_map2
Definition at line 66 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), resize_remap_vars(), scrip_interface::scrip(), scrip_interface::scrip_clear(), and scrip_remap_conservative::store_link_cnsrv().
norm_opt
integer (scrip_i4), save scrip_remap_vars::norm_opt
Definition at line 66 of file scrip_remap_vars.f.
Referenced by scrip_remap_read::read_remap_ww3(), scrip_remap_conservative::remap_conserv(), scrip_interface::scrip(), scrip_interface::scrip_clear(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
norm_opt_dstarea
integer (scrip_i4), parameter scrip_remap_vars::norm_opt_dstarea = 2
Definition at line 54 of file scrip_remap_vars.f.
Referenced by scrip_remap_read::read_remap_ww3(), scrip_remap_conservative::remap_conserv(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
norm_opt_frcarea
integer (scrip_i4), parameter scrip_remap_vars::norm_opt_frcarea = 3
Definition at line 54 of file scrip_remap_vars.f.
Referenced by scrip_remap_read::read_remap_ww3(), scrip_remap_conservative::remap_conserv(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
norm_opt_none
integer (scrip_i4), parameter scrip_remap_vars::norm_opt_none = 1
Definition at line 54 of file scrip_remap_vars.f.
       integer (SCRIP_i4), parameter ::
      &      norm_opt_none    = 1
      &,     norm_opt_dstarea = 2
      &,     norm_opt_frcarea = 3
Referenced by scrip_remap_read::read_remap_ww3(), scrip_remap_conservative::remap_conserv(), scrip_interface::scrip(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
num_links_map1
integer (scrip_i4), save scrip_remap_vars::num_links_map1
Definition at line 66 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_read::read_remap_scrip_ww3(), scrip_remap_conservative::remap_conserv(), scrip_interface::scrip(), scrip_interface::scrip_clear(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), and scrip_remap_write::write_remap_scrip_ww3().
num_links_map2
integer (scrip_i4), save scrip_remap_vars::num_links_map2
Definition at line 66 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_interface::scrip(), scrip_interface::scrip_clear(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap_csm(), and scrip_remap_write::write_remap_scrip().
num_maps
integer (scrip_i4), save scrip_remap_vars::num_maps
Definition at line 66 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_conservative::remap_conserv(), scrip_interface::scrip(), scrip_interface::scrip_clear(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap(), and scrip_remap_write::write_remap_ww3().
num_wts
integer (scrip_i4), save scrip_remap_vars::num_wts
Definition at line 66 of file scrip_remap_vars.f.
Referenced by scrip_remap_conservative::cell_integrate(), init_remap_vars(), scrip_remap_read::read_remap_scrip_ww3(), scrip_remap_conservative::remap_conserv(), resize_remap_vars(), scrip_interface::scrip_clear(), wmscrpmd::scrip_wrapper(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), and scrip_remap_write::write_remap_scrip_ww3().
resize_increment
integer (scrip_i4), save scrip_remap_vars::resize_increment
Definition at line 66 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_interface::scrip_clear(), and scrip_remap_conservative::store_link_cnsrv().
wt_highest
real (kind = scrip_r8) scrip_remap_vars::wt_highest
Definition at line 88 of file scrip_remap_vars.f.
Referenced by scrip_remap_conservative::remap_conserv(), and wmscrpmd::scrip_wrapper().
wt_lowest
real (kind = scrip_r8) scrip_remap_vars::wt_lowest
Definition at line 88 of file scrip_remap_vars.f.
       real (kind = scrip_r8) :: wt_lowest,wt_highest
Referenced by scrip_remap_conservative::remap_conserv(), and wmscrpmd::scrip_wrapper().
wts_map1
real (scrip_r8), dimension(:,:), allocatable, save scrip_remap_vars::wts_map1
Definition at line 83 of file scrip_remap_vars.f.
       real (SCRIP_r8), dimension(:,:), allocatable, save ::
      &      wts_map1, ! map weights for each link (num_wts,max_links)
      &      wts_map2  ! map weights for each link (num_wts,max_links)
Referenced by init_remap_vars(), scrip_remap_read::read_remap_scrip_ww3(), scrip_remap_conservative::remap_conserv(), resize_remap_vars(), scrip_interface::scrip(), scrip_interface::scrip_clear(), wmscrpmd::scrip_wrapper(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), scrip_remap_write::write_remap_scrip_ww3(), and scrip_remap_write::write_remap_ww3().
wts_map2
real (scrip_r8), dimension(:,:), allocatable, save scrip_remap_vars::wts_map2
Definition at line 83 of file scrip_remap_vars.f.
Referenced by init_remap_vars(), scrip_remap_conservative::remap_conserv(), resize_remap_vars(), scrip_interface::scrip_clear(), scrip_remap_conservative::store_link_cnsrv(), scrip_remap_write::write_remap(), scrip_remap_write::write_remap_csm(), scrip_remap_write::write_remap_scrip(), and scrip_remap_write::write_remap_ww3().