WAVEWATCH III: w3fld2md Module Reference
w3fld2md Module Reference
Functions/Subroutines
subroutine w3fld2 (ASPC, FPI, WNDX, WNDY, ZWND, DEPTH, RIB, DAIR, UST, USTD, Z0, TAUNUX, TAUNUY, CHARN)
subroutine wnd2sat (WND10, SAT)
Function/Subroutine Documentation
w3fld2()
subroutine w3fld2md::w3fld2 (real, dimension(nspec), intent(in) ASPC, real, intent(in) FPI, real, intent(in) WNDX, real, intent(in) WNDY, real, intent(in) ZWND, real, intent(in) DEPTH, real, intent(in) RIB, real, intent(in) DAIR, real, intent(out) UST, real, intent(out) USTD, real, intent(out) Z0, real, intent(inout) TAUNUX, real, intent(inout) TAUNUY, real, intent(out), optional CHARN)
Definition at line 67 of file w3fld2md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III      NOAA/NCEP/NOPP |
     !/                  |           B. G. Reichl            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    01-Jul-2013 : Origination                         (version 3.14)
     !/    19-Mar-2015 : Clean-up for submission             (version 5.12)
     !/    22-Mar-2021 : Consider DAIR a variable            ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Wind stress vector calculation from wave spectrum and
     !        n-meter wind speed vector.
     !
     !  2. Method :
     !     See Donelan et al. (2012).
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       ASPC    Real   I   1-D Wave action spectrum.
     !       FPI     Real   I   Peak input frequency.
     !       WNDX    Real   I   X-dir wind (assumed referenced to current)
     !       WNDY    Real   I   Y-dir wind (assumed referenced to current)
     !       ZWND    Real   I   Wind height.
     !       DEPTH   Real   I   Water depth.
     !       RIB     Real   I   Bulk Richardson number in lower atm
     !       DAIR    Real   I   Air density
     !       TAUNUX  Real   0   X-dir viscous stress (guessed from prev.)
     !       TAUNUY  Real   0   Y-dir viscous stress (guessed from prev.)
     !       UST     Real   O   Friction velocity.
     !       USTD    Real   O   Direction of friction velocity.
     !       Z0      Real   O   Surface roughness length
     !       CHARN   Real   O,optional   Charnock parameter
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      APPENDTAIL Subr. W3FLD1MD  Modification of tail for calculation
     !      SIG2WN     Subr. W3FLD1MD  Depth-dependent dispersion relation
     !      MFLUX      Subr. W3FLD1MD  MO stability correction
     !      WND2Z0M    Subr. W3FLD1MD  Bulk Z0 from wind
     !      CALC_FPI   Subr. W3FLD1MD  Calculate peak frequency
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3ASIM    Subr. W3ASIMMD Air-sea interface module.
     !      W3EXPO    Subr.   N/A    Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants, ONLY: dwat, grav, tpi, pi, kappa
     USE w3gdatmd,  ONLY: nk, nth, nspec, sig, dth, xfr, th
     USE w3odatmd,  ONLY: ndse
     USE w3servmd,  ONLY: extcde
     USE w3fld1md,  ONLY: appendtail,sig2wn,wnd2z0m,infld,tail_choice,&
          tail_level, tail_transition_ratio1,         &
          tail_transition_ratio2
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: ASPC(NSPEC), WNDX, WNDY, &
          ZWND, DEPTH, RIB, DAIR, FPI
     REAL, INTENT(OUT)       :: UST, USTD, Z0
     REAL, INTENT(OUT),OPTIONAL :: CHARN
     REAL, INTENT(INOUT)     :: TAUNUX, TAUNUY
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     !-Parameters
     REAL, PARAMETER  :: NU=0.105/10000.0
     !-Commonly used values
     REAL :: UREF, UREFD
     !-Tail
     REAL :: SAT
     REAL :: KMAX, KTAILA, KTAILB, KTAILC
     INTEGER :: KA1, KA2, KA3, NKT
     !-Extended spectrum
     REAL, ALLOCATABLE, DIMENSION(:)   :: WN, DWN, CP, sig2,TAUINTX, TAUINTY
     REAL, ALLOCATABLE, DIMENSION(:,:) :: SPC2
     !-Stress Calculation
     INTEGER :: K, T, ITS
     REAL :: TAUXW, TAUYW, TAUX, TAUY
     REAL :: USTRA, USTRB, USTSM
     REAL :: A1, SCIN
     REAL :: CD, CDF, CDS
     real :: wnd_z, wnd_z_mag, wnd_z_proj, wnd_effect
     ! Stress iteration
     REAL :: B1, B2
     REAL :: USTRI1, USTRF1, USTRI2, USTRF2
     REAL :: USTGRA, SLO
     LOGICAL :: UST_IT_FLG(2)
     !-Z0 iteration
     REAL :: z01,z02
     !-Wind iteration
     real :: wnd_10_x, wnd_10_y, wnd_10_mag, wnd_10_dir
     real :: u35_1, v35_1, u35_2, v35_2, u35_3, v35_3
     REAL :: DIFU10xx, DIFU10yx, DIFU10xy, DIFU10yy
     REAL :: fd_a, fd_b, fd_c, fd_d
     REAL :: DU, DV, UITV, VITV, CH
     REAL :: APAR, DTX(3), DTY(3), DT
     LOGICAL :: WIFLG, WND_IT_FLG
     !-MO stability correction
     LOGICAL :: HEIGHTFLG
     integer :: wi_count, wi
     real :: wnd_ref_al,wnd_ref_ax
     real :: wndpa, wndpax, wndpay, wndpe,wndpex, wndpey
     LOGICAL :: NO_ERR
     LOGICAL :: ITERFLAG
     INTEGER :: ITTOT
     INTEGER :: COUNT
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     LOGICAL, SAVE           :: FIRST = .true.
 #ifdef W3_OMPG
     !$omp threadprivate( FIRST )
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'C3FLD2')
 #endif
     !
     ! 0.  Initializations ------------------------------------------------ *
     !
     !     **********************************************************
     !     ***    The initialization routine should include all   ***
     !     *** initialization, including reading data from files. ***
     !     **********************************************************
     !
     IF ( first ) THEN
       CALL infld
       first  = .false.
     END IF
     !----------------------------|
     ! Calculate Reference height |
     !  wind magnitude            |
     !----------------------------|
     uref=sqrt(wndx**2+wndy**2)
     urefd=atan2(wndy,wndx)
     !----------------------------------------------|
     ! Check if wind height not equal to 10 m       |
     !----------------------------------------------|
     !HeightFLG = (abs(zwnd-10.).GT.0.1) ! True if not 10m
     !----------------------------------------------|
     ! Assume bulk and calculate 10 m wind guess for|
     ! defining tail level                          |
     !----------------------------------------------|
     CALL wnd2z0m(uref,z01)  ! first guess at z0
     wnd_10_mag=uref
     ittot=1
     ! If input wind is not 10m, solve for approx 10 m
     !-------------------------------------------------|
     ! If height != 10 m, then iterate to get 10 m wind|
     ! (assuming neutral -- this is just a guess)      |
     !-------------------------------------------------|
     !IF (HeightFLG) THEN
     !   IterFLAG=.true.
     !   COUNT = 1 !COUNT is now counting iteration over z0
     !   do while(IterFLAG)
     !      wnd_10_mag=UREF*log(10./z01)/log(zwnd/z01)
     !      CALL wnd2z0m(wnd_10_mag,z02)
     !      if ( (abs(z01/z02-1.).GT.0.001) .AND. &
     !           (COUNT.LT.10))THEN
     !         z01 = z02
     !      else
     !         IterFLAG = .false.
     !      endif
     !      COUNT = COUNT + 1
     !   enddo
     !   ITTOT = 3 !extra iterations for 10m wind
     !ELSE
     !   wnd_10_mag = uref
     !   ITTOT = 1 !no iteration needed
     !ENDIF
     if (tail_choice.eq.0) then
       sat=tail_level
     elseif (tail_choice.eq.1) then
       CALL wnd2sat(wnd_10_mag,sat)
     endif
     ! now you have the guess at 10 m wind mag. and z01
     !/
     !--------------------------|
     ! Get first guess at ustar |
     !--------------------------|
     ustra = uref*kappa/log(zwnd/z01)
     ustd = urefd
     wnd_10_dir = urefd
     wnd_10_x=wnd_10_mag*cos(wnd_10_dir)
     wnd_10_y=wnd_10_mag*sin(wnd_10_dir)
     !
     ! 1.  Attach Tail ---------------------------------------------------- *
     !
     call sig2wn ( sig(nk),depth,kmax)
     nkt = nk
     DO WHILE ( kmax .LT. 366. )
       nkt = nkt + 1
       kmax = ( kmax * xfr**2 )
     ENDDO
     ALLOCATE( wn(nkt), dwn(nkt), cp(nkt),sig2(nkt), spc2(nkt,nth), &
          tauintx(nkt),tauinty(nkt))
     !|--------------------------------------------------------------------|
     !|----Build Discrete Wavenumbers for defining spectrum on-------------|
     !|--------------------------------------------------------------------|
     DO k = 1, nk
       call sig2wn(sig(k),depth,wn(k))
       cp(k) = sig(k) / wn(k)
       sig2(k) = sig(k)
     ENDDO
     DO k = ( nk + 1 ), ( nkt)
       sig2(k)=sig2(k-1)*xfr
       call sig2wn(sig2(k),depth,wn(k))
       cp(k)=sig2(k)/wn(k)
     ENDDO
     DO k = 2, nkt-1
       dwn(k) = (wn(k+1) - wn(k-1)) / 2.0
     ENDDO
     dwn(1) = ( wn(2)- ( wn(1) / (xfr **2.0) ) ) / 2.0
     dwn(nkt) = ( wn(nkt)*(xfr**2.0) -  wn(nkt-1)) / 2.0
     !|---------------------------------------------------------------------|
     !|---Attach initial tail-----------------------------------------------|
     !|---------------------------------------------------------------------|
     count=0 !Count is now counting step through 1-d spectrum
     DO k=1, nk
       DO t=1, nth
         count = count + 1
         spc2(k,t) = aspc(count)  * sig(k)
       ENDDO
     ENDDO
     DO k=nk+1, nkt
       DO t=1, nth
         spc2(k,t)=spc2(nk,t)*wn(nk)**3.0/wn(k)**(3.0)
       ENDDO
     ENDDO
     !
     ! 1c. Calculate transitions for new (constant saturation ) tail ------ *
     !
     !-----Wavenumber for beginning of (spectrum level) transition to tail- *
     call sig2wn (fpi*tpi*tail_transition_ratio1,depth,ktaila )
     !-----Wavenumber for end of (spectrum level) transition to tail------- *
     call sig2wn (fpi*tpi*tail_transition_ratio2,depth,ktailb )
     !-----Wavenumber for end of (spectrum direction) transition to tail--- *
     ktailc= ktailb * 2.0
     ka1 = 2     ! Do not modify 1st wavenumber bin
     DO WHILE ( ( ktaila .GE. wn(ka1) ) .AND. (ka1 .LT. nkt-6) )
       ka1 = ka1 + 1
     ENDDO
     ka2 = ka1+2
     DO WHILE ( ( ktailb .GE. wn(ka2) ) .AND. (ka2 .LT. nkt-4) )
       ka2 = ka2 + 1
     ENDDO
     ka3 = ka2+2
     DO WHILE ( ( ktailc .GE. wn(ka3)) .AND. (ka3 .LT. nkt-2) )
       ka3 = ka3 + 1
     ENDDO
     CALL appendtail(spc2,wn,nkt,ka1,ka2,ka3,atan2(wndy,wndx),sat)
     ! Now the spectrum is set w/ tail level SAT
     !
     ! 2. Enter iteration ------------------------------------------------- *
     !
     ! Add new iteration for wind
     !
     ! Wind perturbations for iteration
     !DT = 1.E-04
     !DTX = (/ 1. , -1. , 0. /)
     !DTY = (/ 0. , 1. , -1. /)
     !/
     heightflg=.false.!Not set-up for non-10 m winds
     wiflg = .true.   !This kicks out when wind iteration complete
     no_err = .true.  !This kicks out when there is an error
     wi_count = 1     !Count is now counting wind iterations
     ! - start of wind iteration (if applicable)
     DO WHILE ( wiflg .AND. no_err )  !Wind iteration
       !/
       DO wi = 1, ittot   !Newton-Raphson solve for derivatives if zwnd not 10 m.
         ! If iterating over 10 m wind need to adjust guesses to get slopes
         IF (heightflg) THEN
           wnd_10_x = wnd_10_x + dtx(wi)*dt
           wnd_10_y = wnd_10_y + dty(wi)*dt
           wnd_10_mag = sqrt(wnd_10_x**2+wnd_10_y**2)
           wnd_10_dir = atan2(wnd_10_y,wnd_10_x)
         ENDIF
         !
         ! Stress iteration (inside wind iteration solve for stress)
         its = 1 !ITS is counting stress iteration
         ust_it_flg(1)=.true.
         ust_it_flg(2)=.true.
         DO WHILE ((ust_it_flg(1) .AND. ust_it_flg(2)) .AND. no_err)
           !Get z0 from (guessed) stress and wind magnitude
           z0  = 10. / ( exp( kappa * wnd_10_mag / ustra ) )
           tauintx(1:nkt) = 0.0
           tauinty(1:nkt) = 0.0
           DO k = 1, nkt
             !Waves 'feel' wind at height related to wavelength
             wnd_z = min( pi / wn(k), 20.0 )
             wnd_z_mag = ( ustra / kappa ) * (log(wnd_z/z0))
             DO t = 1, nth
               !projected component of wind in wave direction
               wnd_z_proj = wnd_z_mag * cos( wnd_10_dir-th(t) )
               IF (wnd_z_proj .GT. cp(k)) THEN
                 !Waves slower than wind
                 a1 = 0.11
               ELSEIF (( wnd_z_proj .GE. 0 ) .AND. ( wnd_z_proj .LE. cp(k) )) THEN
                 !Wave faster than wind
                 a1 = 0.01
               ELSEIF (wnd_z_proj .LT. 0) THEN
                 !Waves opposed to wind
                 a1 = 0.1
               ENDIF
               wnd_effect = wnd_z_proj - cp(k)
               scin = a1 * wnd_effect * abs( wnd_effect ) * dair / dwat * &
                    wn(k) / cp(k)
               ! -- Original version assumed g/Cp = sig,(a.k.a in deep water.)
               !   TAUINTX(K) = TAUINTX(K) + SPC2(K,T) * SCIN &
               !        * COS( TH(T) ) / CP(K) * DTH
               !   TAUINTY(K) = TAUINTY(K) + SPC2(K,T) * SCIN &
               !        * SIN( TH(T) ) / CP(K) * DTH
               tauintx(k) = tauintx(k) + spc2(k,t) * scin &
                    * cos( th(t) ) *sig2(k) * dth
               tauinty(k) = tauinty(k) + spc2(k,t) * scin &
                    * sin( th(t) ) *sig2(k) * dth
             ENDDO
           ENDDO
           tauyw = 0.0
           tauxw = 0.0
           DO k = 1, nkt
             !  TAUXW = TAUXW + DWAT * GRAV * DWN(K) * TAUINTX(K)
             !  TAUYW = TAUYW + DWAT * GRAV * DWN(K) * TAUINTY(K)
             tauxw = tauxw + dwat * dwn(k) * tauintx(k)
             tauyw = tauyw + dwat * dwn(k) * tauinty(k)
           ENDDO
           cdf = ( sqrt(tauxw**2.0+tauyw**2.0) / dair ) / wnd_10_mag**2.0
           !|---------------------------------------------------------------------|
           !|----Solve for the smooth drag coefficient to use as initial guess----|
           !|----for the viscous stress-------------------------------------------|
           !|---------------------------------------------------------------------|
           IF (uref .LT. 0.01) THEN
             ustsm = 0.0
             iterflag = .false.
           ELSE
             z02 = 0.001
             iterflag = .true.
           ENDIF
           count = 1
           ! Finding smooth z0 to get smooth drag
           DO WHILE( (iterflag ) .AND. (count .LT. 10) )
             z01 = z02
             ustsm = kappa * wnd_10_mag / ( log( 10. / z01 ) )
             z02 = 0.132 * nu / ustsm
             IF (abs( z02/z01-1.0) .LT. 10.0**(-4)) THEN
               iterflag = .false.
             ELSE
               iterflag = .true.
             ENDIF
             count = count + 1
           ENDDO
           cds = ustsm**2.0 / wnd_10_mag**2.0
           ! smooth drag adjustment based on full drag
           cds = cds / 3.0 * ( 1.0 + 2.0 * cds / ( cds + cdf ) )
           !-----Solve for viscous stress from smooth Cd
           taunux = dair * cds * wnd_10_mag**2.0 * cos( wnd_10_dir )
           taunuy = dair * cds * wnd_10_mag**2.0 * sin( wnd_10_dir )
           !-----Sum drag components
           taux = taunux + tauxw
           tauy = taunuy + tauyw
           !-----Calculate USTAR
           ustrb = sqrt( sqrt( tauy**2.0 + taux**2.0) / dair )
           !-----Calculate stress direction
           ustd = atan2(tauy,taux)
           !Checking ustar. ustra=guess. ustrb=found.
           b1 = ( ustra - ustrb )
           b2 = ( ustra + ustrb ) / 2.0
           its = its + 1
           !Check for convergence
           ust_it_flg(1)=( abs(b1*100.0/b2) .GE. 0.01)
           !If not converged after 20 iterations, quit.
           ust_it_flg(2)=( its .LT. 20 )
           IF ( ust_it_flg(1) .AND. ust_it_flg(2)) THEN
             ! Toyed with methods for improving iteration.
             ! ultimately this was sufficient.
             ! May be imporved upon in future...
             ustra = ustrb*.5 + ustrb*.5
           ELSEIF (abs(b1*100.0/b2) .GE. 5.) THEN
             !After 20 iterations, >5% from converged
             ust_it_flg(1) = .false.
             ust_it_flg(2) = .false.
             print*,'Attn: Stress not converged for windspeed: ',uref
             ust = -999.
             no_err = .false.
           ENDIF
         ENDDO
         !IF (HeightFLG) THEN
         !   ! Get along stress wind at top wave boundary layer (10m)
         !   WNDPA=WND_10_mag*COS(WND_10_dir-USTD)
         !   WNDPE=WND_10_mag*SIN(WND_10_dir-USTD)
         !   ! Calculate Cartesian of across wind
         !   WNDPEx=WNDPE*cos(ustd+pi/2.)! add pi/2 since referenced
         !   WNDPEy=WNDPE*sin(ustd+pi/2.)! to right of stress angle
         !   !Approx as neutral inside 10 m (WBL) calculate z0
         !   wnd_ref_al=uref*cos(urefd-ustd)
         !   z0=10. / exp( wnd_10_mag * KAPPA / ustra )
         !   ! Use that z0 to calculate stability
         !   ! Cd to ref height (based on input wind)
         ! Below is subroutine for computing stability effects
         !   call mflux(wnd_ref_al,zwnd,z0,rib,cd)
         ! 2. Get CD with stability
         ! 3. Get New 35-m wind based on calculated stress Cd from MO
         !   WNDPA=ustra/sqrt(cd)
         !   WNDPAX=WNDPA*cos(ustd)
         !   WNDPAY=WNDPA*sin(ustd)
         !   if (wi.eq.3) then
         !      u35_1=WNDPAX+WNDPEX
         !      v35_1=WNDPAY+WNDPEY
         !   elseif (wi.eq.2) then
         !      u35_2=WNDPAX+WNDPEX
         !      v35_2=WNDPAY+WNDPEY
         !   elseif (wi.eq.1) then
         !      u35_3=WNDPAX+WNDPEX
         !      v35_3=WNDPAY+WNDPEY
         !   endif
         !ENDIF
       ENDDO
       !IF (HeightFLG) THEN
       !   DIFU10xx= u35_3-u35_1
       !   DIFU10yx= v35_3-v35_1
       !   DIFU10xy= u35_2-u35_1
       !   DIFU10yy= v35_2-v35_1
       !   fd_a = difu10xx / DT
       !   fd_b = difu10xy / DT
       !   fd_c = difu10yx / DT
       !   fd_d = difu10yy / DT
       !   du = -wndx+u35_1
       !   dv = -wndy+v35_1
       !   uitv= abs(du)
       !   vitv=abs(dv)
       !   ch=sqrt(uitv*uitv+vitv*vitv)
       !   if (ch.gt.10) then
       !      apar=0.5/(fd_a*fd_d-fd_b*fd_c)
       !   else
       !      apar=1.0/(fd_a*fd_d-fd_b*fd_c)
       !   endif
       ! Check for wind convergence
       !   WND_IT_FLG = (((du**2+dv**2)/(wndx**2+wndy**2)).GT.0.001)
       !
       !   IF ( WND_IT_FLG .AND. WI_COUNT.LT.10 ) THEN
       !      ! New guesses
       !      wnd_10_x=wnd_10_x-apar*( FD_D * DU - FD_B * DV )
       !      wnd_10_y=wnd_10_y-apar*( -FD_C * DU +FD_A * DV )
       !   ELSE
       !      wiflg = .FALSE.
       !      IF (WI_COUNT .gt. 10 .AND. &
       !           ((du**2+dv**2)/(wndx**2+wndy**2)).GT.0.05 ) then
       !         print*,'Attn: W3FLD2 Wind error gt 5%'
       !         !print*,'  Wind y/error: ',wndy,dv
       !         !print*,'  Wind x/error: ',wndx,du
       !         NO_ERR = .false.
       !      endif
       !   ENDIF
       !   WI_COUNT = WI_COUNT + 1
       !ELSE
       wiflg=.false. ! If already 10 m wind then complete.
       !ENDIF
     enddo
     ust = ustrb
     ustd = atan2(tauy, taux)
     cd = ust**2 / uref**2
     IF (PRESENT(charn)) THEN
       charn = 0.01/sqrt(sqrt( taunux**2 + taunuy**2 )/(ust**2))
     ENDIF
     IF (.not.((cd .LT. 0.01).AND.(cd .GT. 0.0005)).or. .not.(no_err)) THEN
       !Fail safe to bulk
       print*,'Attn: W3FLD2 failed, using bulk stress'
       print*,'Calculated Wind/Cd: ',uref,cd,ust
       call wnd2z0m(uref,z0)
       ust = uref * kappa / log(zwnd/z0)
       cd = ust**2/uref**2
       ustd = urefd
     ENDIF
     DEALLOCATE( tauinty , tauintx , &
          spc2, sig2, cp , dwn , wn )
     !STOP
     !/ End of W3FLD2 ----------------------------------------------------- /
     !/
     RETURN
     !
References w3fld1md::appendtail(), w3gdatmd::dth, constants::dwat, w3servmd::extcde(), constants::grav, w3fld1md::infld(), constants::kappa, w3odatmd::ndse, w3gdatmd::nk, w3gdatmd::nspec, w3gdatmd::nth, constants::pi, w3gdatmd::sig, w3fld1md::sig2wn(), w3servmd::strace(), w3fld1md::tail_choice, w3fld1md::tail_level, w3fld1md::tail_transition_ratio1, w3fld1md::tail_transition_ratio2, w3gdatmd::th, constants::tpi, wnd2sat(), w3fld1md::wnd2z0m(), and w3gdatmd::xfr.
Referenced by w3srcemd::w3srce().
wnd2sat()
subroutine w3fld2md::wnd2sat (real, intent(in) WND10, real, intent(out) SAT)
Definition at line 595 of file w3fld2md.F90.
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           B. G. Reichl            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         04-Aug-2016 |
     !/                  +-----------------------------------+
     !/
     !/    15-Jan-2016 : Origination.                        ( version 5.12 )
     !/    05-Aug-2016 : Updated for 2016 HWRF CD/U10 curve  ( J. Meixner   )
     !/
     !  1. Purpose :
     !
     !     Gives level of saturation spectrum to produce
     !         equivalent Cd as in wnd2z0m (for neutral 10m wind)
     !         tuned for method of Donelan et al. 2012
     !
     !  2. Method :
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !Input: WND10 - 10 m neutral wind [m/s]
     !Output: SAT  - Level 1-d saturation spectrum in tail [non-dim]
     !     ----------------------------------------------------------------
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3FLD2    Subr. W3FLD2MD Corresponding source term.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !
     IMPLICIT NONE
     REAL, INTENT(IN) :: WND10
     REAL, INTENT(OUT) :: SAT
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
     CALL strace (ient, 'WND2SAT')
 #endif
     !
     ! ST2, previous HWRF relationship:
     !        SAT =0.000000000000349* WND10**6 +&
     !             -0.000000000250547* WND10**5 +&
     !             0.000000039543565* WND10**4 +&
     !             -0.000002229206185* WND10**3 +&
     !             0.000034922624204* WND10**2 +&
     !             0.000339117617027* WND10**1 +&
     !             0.003521314236550
     !     SAT values based on
     !     HWRF 2016 CD curve, created with  fetch limited cases ST4 physics
     IF (wnd10<20) THEN
       sat = -0.022919753482426e-3* wnd10**2 &
            +0.960758623686446e-3* wnd10    &
            -0.084461041915030e-3
     ELSEIF (wnd10<45) THEN
       sat = -0.000000006585745* wnd10**4 &
            +0.000001058147954* wnd10**3 &
            -0.000065829151883* wnd10**2 &
            +0.001587028483595* wnd10    &
            -0.002857112191889
     ELSE
       sat = -0.000178498197241* wnd10    &
            +0.012706067280674
     ENDIF
     sat = min(max(sat,0.002),0.014)
References w3servmd::strace().
Referenced by w3fld2().