WAVEWATCH III: w3snl5md Module Reference
w3snl5md Module Reference
Interface module for GKE (resonant & quasi-resonant four-wave interactions).
Functions/Subroutines
subroutine, public w3snl5 (A, CG, WN, FMEAN, T1ABS, U10, UDIR, JSEA, S, D, KURT)
Interface to CalcQRSNL subroutine of the GKE module.
subroutine, public insnl5
Initialization for the GKE module (Prepare wavenumber grid & kernel coefficients).
logical function hasnan (NK, NTH, ARR2D)
Check if the 2D array ARR2D contains NaN.
Detailed Description
Interface module for GKE (resonant & quasi-resonant four-wave interactions).
Author
O. Gramstad
Q. Liu
Date
07-Jun-2021
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Function/Subroutine Documentation
hasnan()
logical function w3snl5md::hasnan (integer, intent(in) NK, integer, intent(in) NTH, real, dimension(nk, nth), intent(in) ARR2D)
Check if the 2D array ARR2D contains NaN.
Parameters
NK
NTH
ARR2D
Returns
HasNaN
Author
Q. Liu
Date
25-Apr-2019
Definition at line 887 of file w3snl5md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           Q. Liu                  |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         25-Apr-2019 |
     !/                  +-----------------------------------+
     !/
     !/    24-Apr-2019 : Origination.                        ( version 7.13 )
     !/                                                      ( Q. Liu       )
     !/
     !  1. Purpose :
     !     Check if the 2D array `ARR2D` contains NaN (see also w3gsrumd.ftn)
     !/
     IMPLICIT NONE
     !
     INTEGER, INTENT(IN)  :: NK, NTH        ! # OF FREQ. & DIRC.
     REAL, INTENT(IN)     :: ARR2D(NK, NTH)
     LOGICAL              :: HasNaN
     !/
     hasnan = .true.
     !
     IF ( all(arr2d .GE. -huge(arr2d(1, 1))) .AND.  &
          all(arr2d .LE.  huge(arr2d(1, 1))) ) THEN
       hasnan = .false.
     END IF
     !
     RETURN
     !/
Referenced by w3snl5().
insnl5()
subroutine, public w3snl5md::insnl5
Initialization for the GKE module (Prepare wavenumber grid & kernel coefficients).
Author
Q. Liu
Date
27-Feb-2019
Definition at line 435 of file w3snl5md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           Q. Liu                  |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         27-Feb-2019 |
     !/                  +-----------------------------------+
     !/
     !/    27-Feb-2019 : Origination.                        ( version 7.13 )
     !/                                                      ( Q. Liu )
     !/
     !  1. Purpose :
     !
     !     Initialization for the GKE module (Prepare wavenumber grid & kernel
     !     coefficients)
     !
     !  2. Method :
     !     See subrs. PrepKGrid & PrepKernelIO of gkeModule.f90
     !
     !  3. Parameters :
     !
     !  4. Subroutines used :
     !     ----------------------------------------------------------------
     !      Name          Type  Module      Description
     !     ----------------------------------------------------------------
     !      STRACE        Subr. W3SERVMD    Subroutine tracing.
     !      PrepKernelIO  Subr. gkeModule   KGrid & Kernel Coeff.
     !
     !  5. Called by :
     !     ----------------------------------------------------------------
     !      Name          Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3IOGR        Subr. W3IOGRMD Model definition file management.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3gkemd,  ONLY: qr_depth, qr_oml, qi_disc, qi_kev, qi_nnz,  &
          qi_interp, prepkernelio
     USE w3gdatmd, ONLY: nk, nth, sig, th,                           &
          qr5dpt, qr5oml, qi5dis, qi5kev, qi5nnz,     &
          qi5ipl, qi5pmx
     USE w3odatmd, ONLY: iaproc, napout, screen
     USE w3servmd, ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'INSNL5')
 #endif
     !
     ! Set important parameters for GKE module (QR[I]5DPT/OML/DIS/KEV are
     ! defined in ww3_grid.inp, and QI5NNZ is not known yet)
     qr_depth = qr5dpt
     qr_oml   = qr5oml
     qi_disc  = qi5dis
     qi_kev   = qi5kev
     qi_interp= qi5ipl
     !
     ! Prepare (kx, ky) grid & kernel coefficients
     CALL prepkernelio(nk, nth, sig(1:nk), th, 'WRITE')
     !
     ! Store qi_NNZ to QI5NNZ (which will be used to initialize the
     ! QC5INT0 array)
     qi5nnz   = qi_nnz
     !
     ! Q. Liu (TODO)
     IF (iaproc .EQ. napout) THEN
       WRITE(screen, '(A, F6.1)') " ⊚ → [WW3 SNL₅]: water depth   : ", qr_depth
       WRITE(screen, '(A, F7.2)') " ⊚ → [WW3 SNL₅]: ω λc cut off  : ", qr_oml
       WRITE(screen, '(A, I4)'  ) " ⊚ → [WW3 SNL₅]: Discretiza.   : ", qi_disc
       WRITE(screen, '(A, I4)'  ) " ⊚ → [WW3 SNL₅]: GKE version   : ", qi_kev
       WRITE(screen, '(A, I12)' ) " ⊚ → [WW3 SNL₅]: # of quartets : ", qi_nnz
       WRITE(screen, '(A, I4)'  ) " ⊚ → [WW3 SNL₅]: interpol.     : ", qi_interp
       WRITE(screen, '(A, I4)'  ) " ⊚ → [WW3 SNL₅]: phase mixing  : ", qi5pmx
     END IF
     !/
     !/ End of INSNL5 ----------------------------------------------------- /
     !/
References w3servmd::dist_sphere(), w3gdatmd::dsii, w3gdatmd::dth, w3gdatmd::ecos, w3gdatmd::esin, w3servmd::extcde(), file(), w3gdatmd::flagll, w3odatmd::iaproc, w3odatmd::iptint, w3gdatmd::mapfs, w3gdatmd::mapsta, w3odatmd::napout, w3gdatmd::nk, w3odatmd::nopts, w3gdatmd::nth, w3gkemd::prepkernelio(), w3odatmd::ptloc, w3odatmd::ptnme, w3gdatmd::qi5dis, w3gdatmd::qi5ipl, w3gdatmd::qi5kev, w3gdatmd::qi5nnz, w3gdatmd::qi5pmx, w3gkemd::qi_disc, w3gkemd::qi_interp, w3gkemd::qi_kev, w3gkemd::qi_nnz, w3gdatmd::qr5dpt, w3gdatmd::qr5oml, w3gkemd::qr_depth, w3gkemd::qr_oml, w3odatmd::screen, w3gdatmd::sig, w3servmd::strace(), w3gdatmd::th, constants::tpi, w3dispmd::wavnu1(), w3gdatmd::xgrd, and w3gdatmd::ygrd.
Referenced by w3iogrmd::w3iogr().
w3snl5()
subroutine, public w3snl5md::w3snl5 (real, dimension(nth, nk), intent(in) A, real, dimension(nk), intent(in) CG, real, dimension(nk), intent(in) WN, real, intent(in) FMEAN, integer, dimension(2), intent(in) T1ABS, real, intent(in) U10, real, intent(in) UDIR, integer, intent(in) JSEA, real, dimension(nth,nk), intent(out) S, real, dimension(nth,nk), intent(out) D, real, intent(out) KURT)
Interface to CalcQRSNL subroutine of the GKE module.
Parameters
[in] A
[in] CG
[in] WN
[in] FMEAN
[in] T1ABS
[in] U10
[in] UDIR
[in] JSEA
[out] S
[out] D
[out] KURT
Author
O. Gramstad
Q. Liu
Date
24-Apr-2019
Definition at line 100 of file w3snl5md.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           O. Gramstad             |
     !/                  |           Q. Liu                  |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         24-Apr-2019 |
     !/                  +-----------------------------------+
     !/
     !/    24-Sep-2013 : Origination.                        ( version 3.14 )
     !/    24-Sep-2013 : GKE for resonant & quasi-resonant four-wave
     !/                  interactions                        ( O. Gramstad  )
     !/    27-Feb-2019 : Full implementation of GKE          ( version 7.13 )
     !/                                                      ( Q. Liu       )
     !/    21-Apr-2019 : Phase mixing option                 ( version 7.13 )
     !/                                                      ( Q. Liu       )
     !/    24-Apr-2019 : Phase mixing option (b_T)           ( version 7.13 )
     !/                                                      ( Q. Liu       )
     !/    02-May-2019 : Organize screen output & disable binary output
     !/                                                      ( version 7.13 )
     !/                                                      ( Q. Liu       )
     !/
     !/
     !  1. Purpose :
     !
     !     Interface to CalcQRSNL subr. of the GKE module. Please refer to
     !     -------------
     !     gkeModule.f90 for further details.
     !     -------------
     !
     !     ◆ Different times used in this module
     !
     !     |----o---------o----o--|-|--o-----o------o-----o------o----> (t)
     !     ^    ^         ^       ^ ^ T1ABS (absol. current time step)¹
     !     |    |         |       |
     !     |    |         |       v t0 (relat. time, previous time step)
     !     |    |<------->|
     !     |    | PM_IVAL (phase mixing interval, relat. time)
     !     |    |
     !     |    v PM_PREV (phase mixing, appear quasi-periodically)
     !     |              (relat. time)
     !     |
     !     v TBEG (absol. begining time, defined by ww3_shel.inp)
     !
     !     ¹ Because of using the dynamic integration scheme, T1ABS
     !       is related to, but not the same as, TIME in w3wdatmd.ftn
     !  2. Method :
     !
     !  3. Parameters :
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SRCE    Subr. W3SRCEMD Source term integration.
     !      W3EXPO    Subr.   N/A    Point output post-processor.
     !      GXEXPO    Subr.   N/A    GrADS point output post-processor.
     !     ----------------------------------------------------------------
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !     !/S  Enable subroutine tracing.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE constants, ONLY: grav, tpi
     USE w3gkemd,   ONLY: calcqrsnl, qr_depth
     USE w3gdatmd,  ONLY: nk, nth, nspec, sig, th,            &
          gtype, rlgtype, clgtype,            &
          qr5dpt, qi5nnz, qi5pmx
     USE w3wdatmd,  ONLY: qi5tbeg, qr5tim0, qr5cvk0, qc5int0, &
          qr5tmix
     USE w3odatmd,  ONLY: flout, nopts, tosnl5, tolast, &
          iaproc, napout, screen
     USE w3parall,  ONLY: init_get_isea
     USE w3timemd,  ONLY: dsec21
     USE w3servmd,  ONLY: extcde
 #ifdef W3_S
     USE w3servmd, ONLY: strace
 #endif
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: A(NTH, NK)         ! N(θ, k)
     REAL, INTENT(IN)        :: CG(NK)             ! Cg(k)
     REAL, INTENT(IN)        :: WN(NK)             ! WN(k)
     REAL, INTENT(IN)        :: FMEAN              ! 1/T_{0, -1}
     INTEGER, INTENT(IN)     :: T1ABS(2)           ! Absol. t1
     REAL, INTENT(IN)        :: U10                ! Wind velocity
     REAL, INTENT(IN)        :: UDIR               ! φ (in rad)
     INTEGER, INTENT(IN)     :: JSEA               ! Local sea point count
     REAL, INTENT(OUT)       :: S(NTH,NK),      &  ! Snl
          D(NTH,NK),      &  ! Dnl
          KURT               ! Kurtosis
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     REAL, PARAMETER         :: BTLOW = 10., bthgh = 500.
     REAL                    :: T0REL, T1REL, TDEL1, TDEL2
     REAL                    :: Cvk1(NSPEC), SNL(NSPEC), DNL(NSPEC)
     REAL                    :: Cvk0(NSPEC)
     COMPLEX                 :: INPQR0(QI5NNZ)
     INTEGER                 :: IK, ITH, ISPEC, ISEA, JLOC
     INTEGER, ALLOCATABLE    :: PDIFF(:)
     LOGICAL, SAVE           :: FSTOUT = .true.
     REAL                    :: FACTOR(NK), A2(NK, NTH), S2(NK, NTH)
     REAL                    :: PM_PREV, PM_IVAL, PM_DELT
     REAL                    :: WBT, BTINV
     INTEGER                 :: IUNT
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3SNL5')
 #endif
     !
     !/ ------------------------------------------------------------------- /
     ! Read in wave info. @ the previous time step t0
     ! Array initialization is done in w3wdat/w3setw (called by w3initmd)
     t0rel  = qr5tim0(jsea)              ! t0 (nsea)
     cvk0   = qr5cvk0(:, jsea)           ! Cvk (ns, nsea) @ t0
     inpqr0 = qc5int0(:, jsea)           ! Inpqr (nnz, nsea) @ t0
     !
     ! Calc. Relative time for T1ABS (QI5TBEG as the reference)
     t1rel  = dsec21(qi5tbeg, t1abs)     ! in second
     !
     ! W3WAVEMD: IF ( IT.EQ.0 ) DTG = 1 → T1REL = -1 (the first step of
     ! integration; TIME = TCALC/TOFRST, DTG = 0 →  1, QI5TBEG = TIME - 1)
     IF(t1rel < 0.) t1rel = 0.
     !
     ! Three options for phase mixing
     IF (qi5pmx .EQ. 0) THEN
       ! 1) 0: no phase mixing
 #ifdef W3_TS
       IF (iaproc .EQ. napout)                                    &
            WRITE(screen, '(A, 2(I10.8, I7.6), E12.3)')                &
            " ⊚ → [WW3 SNL₅] QI5TBEG, T1ABS, T1REL:",              &
            qi5tbeg, t1abs, t1rel
 #endif
     ELSE
 #ifdef W3_TS
       IF (iaproc .EQ. napout)                                    &
            WRITE(screen, '(A, 2(I10.8, I7.6), E12.3)', advance='no')  &
            " ⊚ → [WW3 SNL₅] QI5TBEG, T1ABS, T1REL, T1REL[P]:",    &
            qi5tbeg, t1abs, t1rel
 #endif
       !
       ! Calc. Phase mixing interval
       IF (qi5pmx .GT. 0) THEN
         ! 2) N: mix phase by every N characteristic wave periods
         IF (abs(fmean) < 1e-7) THEN      ! FMEAN may be 0.
           pm_ival = real(qi5pmx) * 1.  ! then, assume FMEAN = 1.
         ELSE
           pm_ival = real(qi5pmx) * (1. / fmean)
         END IF
         !
       ELSE IF (qi5pmx .LT. 0) THEN
         ! 3) < 0: mix phase based on dominant wave breaking probability bT
         ! Calc bT
         wbt   = calc_wbtv2(a, cg, wn, qr5dpt, u10, udir) ! [0, 1.]
         ! Mix phase by every 1/bT periods
         ! Odin used bT < 1/15. (0.066) → BTLOW = 15 and PM_IVAL > 150 s
         btinv = max(btlow, min(1./max(1e-6, wbt), bthgh))
         IF (abs(fmean) < 1e-7) THEN      ! FMEAN may be 0.
           pm_ival = btinv * 1.  ! then, assume FMEAN = 1.
         ELSE
           pm_ival = btinv * (1. / fmean)
         END IF
       END IF
       !
       ! Previous phase mixing time (relat. to TBEG)
       ! QR5TMIX has already been initialized in w3wdatmd as zero.
       pm_prev = qr5tmix(jsea)
       ! Update t1 if necessary
       pm_delt = t1rel - pm_prev
       IF (pm_delt .GE. pm_ival) THEN
         qr5tmix(jsea) = t1rel        ! relat. to TBEG → PM_PREV
         t1rel         = 0.
       ELSE
         t1rel         = pm_delt
       END IF
 #ifdef W3_TS
       IF (iaproc .EQ. napout) THEN
         WRITE(screen, '(F9.1)') t1rel
         IF (qi5pmx .LT. 0 ) WRITE(screen, '(A, F6.3)') '↔ bT: ', wbt
       ENDIF
 #endif
     END IF
     !
     ! Calc. Cvk1 from A (C(\bm{k}) = g N(k, θ) / k)
     DO ik = 1, nk
       DO ith = 1, nth
         ispec = ith + (ik-1) * nth
         cvk1(ispec) = a(ith, ik) / wn(ik) * grav
       END DO
     END DO
     !
     ! CalcQRSNL(nk, nth, sig, th, t0, t1, Cvk0, Cvk1, Inpqr0, Snl, Dnl, Kurt)
     ! Depth is needed for reading in kernels at the first run
     qr_depth = qr5dpt
     CALL calcqrsnl(nk, nth, sig(1:nk), th,     &
          t0rel, t1rel, cvk0, cvk1,   &
          inpqr0, snl, dnl, kurt)
     !
     ! Tranform back from C(k) to N(k)
     ! TODO D(ITH, IK) (See NL2 for reference)
     d = 0.0
     DO ik = 1, nk
       DO ith = 1, nth
         ispec = ith + (ik-1) * nth
         s(ith, ik) = snl(ispec) * wn(ik) / grav
       END DO
     END DO
     !
     ! Store wave info. @ t1 → t0
     qr5tim0(jsea)    = t0rel
     qr5cvk0(:, jsea) = cvk0
     qc5int0(:, jsea) = inpqr0
     !
     ! Point output (Snl term)
     ! First ouput action (Find nearest grid points & generate binary files)
     IF (fstout) THEN
       CALL inpout
       fstout = .false.
       IF (iaproc .EQ. napout) THEN
         WRITE(screen, *)
         WRITE(screen, '(A)')                          &
              ' ⊚ → [WW3 SNL₅] Point ouptut initialization'
         WRITE(screen, '(A, I4)')                      &
              ' ⊚ → [WW3 SNL₅] # of valid points: ', nsel
         WRITE(screen, *)
       END IF
     END IF
     !
     ! Calc FACTOR used for Jacobian tranformation from N(k, θ) to E(f, θ)
     factor = tpi / cg * sig(1:nk)
     !
     ! Regular grid & curvilinear grid
     IF ( ((gtype .EQ. rlgtype) .OR. (gtype .EQ. clgtype)) &
          .AND. flout(2) .AND. nsel .GT. 0) THEN
       tdel1 = dsec21(t1abs, tosnl5)
       tdel2 = dsec21(t1abs, tolast(:, 2)) ! not really useful since
       ! TOSNL5 can never catch
       ! TOLAST
       ! Output time
       IF (abs(tdel1) < 1e-6 .OR. abs(tdel2) < 1e-6) THEN
         ! JSEA→ ISEA
         CALL init_get_isea(isea, jsea)
         ! Find the loc of ISEA at PSEA (nearest sea grid point)
         IF (ALLOCATED(pdiff)) DEALLOCATE(pdiff); ALLOCATE(pdiff(nsel))
         pdiff = abs(psea(1:nsel) - isea)
         IF (any(pdiff .EQ. 0)) THEN
           jloc = minloc(pdiff, 1)
 #ifdef W3_TS
           IF (iaproc .EQ. napout)                               &
                WRITE(screen, '(3A, I10.8, I7.6)')                    &
                '✓ Point output for |', pnms(jloc), '| @', t1abs
 #endif
           ! N(θ, k) →  F(f, θ) & S(θ, k) →  S(f, θ)
           DO ith = 1, nth
             a2(:, ith) = a(ith, :) * factor
             s2(:, ith) = s(ith, :) * factor
           END DO
           ! NaN Check
           IF (hasnan(nk, nth, a2) .OR. hasnan(nk, nth, s2)) THEN
             IF (iaproc .EQ. napout)                            &
                  WRITE(screen, *) '★★★ Warning: find NaN in E(f, θ) &
                  & or Snl(f, θ) !'
           END IF
           ! unit no.
           iunt = 500 + jloc
           ! Store data (binary)
           !                 OPEN(IUNT, FILE='NL5_'//trim(PNMS(JLOC))//'_src.bin',  &
           !                      form='unformatted', convert=file_endian, ACCESS='stream',             &
           !                      STATUS='old', POSITION='append', ACTION='write')
           !                 WRITE(IUNT) T1ABS
           !                 WRITE(IUNT) KURT
           !                 WRITE(IUNT) A2
           !                 WRITE(IUNT) S2
           !                 CLOSE(IUNT)
           ! Store data (ascii)
           OPEN(iunt, file='NL5_'//trim(pnms(jloc))//'_src.dat', &
                form='formatted', status='old',                  &
                position='append', action='write')
           WRITE(iunt, '(I10.8, I7.6)') t1abs
           WRITE(iunt, '(ES11.3)')      kurt
           WRITE(iunt, 113) a2
           WRITE(iunt, 113) s2
           CLOSE(iunt)
           !
         END IF
       END IF
     END IF
     ! Format
 113 FORMAT ((10es11.3))
     !/
     !/ End of W3SNL5 ----------------------------------------------------- /
     !/
References w3gkemd::calcqrsnl(), w3gdatmd::clgtype, w3timemd::dsec21(), w3servmd::extcde(), file(), w3odatmd::flout, constants::grav, w3gdatmd::gtype, hasnan(), w3odatmd::iaproc, w3parall::init_get_isea(), w3odatmd::napout, w3gdatmd::nk, w3odatmd::nopts, w3gdatmd::nspec, w3gdatmd::nth, w3wdatmd::qc5int0, w3gdatmd::qi5nnz, w3gdatmd::qi5pmx, w3wdatmd::qi5tbeg, w3wdatmd::qr5cvk0, w3gdatmd::qr5dpt, w3wdatmd::qr5tim0, w3wdatmd::qr5tmix, w3gkemd::qr_depth, w3gdatmd::rlgtype, w3odatmd::screen, w3gdatmd::sig, w3servmd::strace(), w3gdatmd::th, w3odatmd::tolast, w3odatmd::tosnl5, and constants::tpi.
Referenced by w3srcemd::w3srce().