WAVEWATCH III: w3iogomd.F90 File Reference
w3iogomd.F90 File Reference
Gridded output of mean wave parameters.
Modules
module w3iogomd
Gridded output of mean wave parameters.
Functions/Subroutines
subroutine w3iogomd::w3flgrdupdt (NDSO, NDSEN, FLGRD, FLGR2, FLGD, FLG2)
Updates the flags for output parameters based on the mod_def file this is to prevent the allocation of big 3D arrays when not requested.
subroutine w3iogomd::w3readflgrd (NDSI, NDSO, NDSS, NDSEN, COMSTR, FLG1D, FLG2D, IAPROC, NAPOUT, IERR)
Fills in FLG1D and FLG2D arrays from ASCII input file.
subroutine w3iogomd::w3flgrdflag (NDSO, NDSS, NDSEN, FLDOUT, FLG1D, FLG2D, IAPROC, NAPOUT, IERR)
Fills in FLG1D and FLG2D arrays from ASCII input file.
subroutine w3iogomd::w3fldtoij (FLD, I, J, IAPROC, NAPOUT, NDSEN)
Returns the group/field (I/J) indices for a named output field.
subroutine w3iogomd::w3outg (A, FLPART, FLOUTG, FLOUTG2)
Fill necessary arrays with gridded data for output.
subroutine w3iogomd::w3iogo (INXOUT, NDSOG, IOTST, IMOD ifdef W3_ASCII
Read/write gridded output.
subroutine w3iogomd::calc_u3stokes (A, USS_SWITCH)
Output Stokes drift related parameters.
subroutine w3iogomd::calc_wbt (A)
Estimate the dominant wave breaking probability b_T.
subroutine w3iogomd::secondhh (NKHF, FAC0, FAC1, FAC2, FAC3)
Computation of second order harmonics and relevant tables for the altimeter corrections.
real(kind=4) function vmin_d (XI, XJ, XK, XIJ, XIK, XJK, XOI, XOJ, XOK)
real(kind=4) function vplus_d (XI, XJ, XK, XIJ, XIK, XJK, XOI, XOJ, XOK)
subroutine w3iogomd::skewness (A)
Determines skewness paramters in order to obtain correction on altimeter wave height.
Variables
character(len=1024) w3iogomd::fldout
Detailed Description
Gridded output of mean wave parameters.
Author
H. L. Tolman
Date
22-Mar-2021
Definition in file w3iogomd.F90.
Function/Subroutine Documentation
vmin_d()
real(kind=4) function secondhh::vmin_d (real, intent(in) XI, real, intent(in) XJ, real, intent(in) XK, real, intent(in) XIJ, real, intent(in) XIK, real, intent(in) XJK, real, intent(in) XOI, real, intent(in) XOJ, real, intent(in) XOK)
Definition at line 4855 of file w3iogomd.F90.
 !     PETER JANSSEN
 !     PURPOSE.
 !     --------
 !              GIVES NONLINEAR TRANSFER COEFFICIENT FOR THREE
 !              WAVE INTERACTIONS OF DEEP-WATER WAVES IN THE
 !              IDEAL CASE OF NO CURRENT. (CF.ZAKHAROV)
 !     INTERFACE.
 !     ----------
 !              *VMIN_D(XI,XJ,XK)*
 !                      *XI*  - WAVE NUMBER
 !                      *XJ*  - WAVE NUMBER
 !                      *XK*  - WAVE NUMBER
 !     METHOD.
 !     -------
 !              NONE
 !     EXTERNALS.
 !     ----------
 !              NONE.
 !***  1. DETERMINE NONLINEAR TRANSFER.
 !     --------------------------------
       IMPLICIT NONE
       REAL, INTENT(IN) :: XI, XJ, XK, XIJ, XIK, XJK, XOI, XOJ, XOK
       REAL :: RI, RJ, RK, OI, OJ, OK, SQIJK, SQIKJ, SQJKI
       ri=abs(xi)+del1
       rj=abs(xj)+del1
       rk=abs(xk)+del1
       oi=xoi+del1
       oj=xoj+del1
       ok=xok+del1
       sqijk=sqrt(oi*oj*rk/(ok*ri*rj))
       sqikj=sqrt(oi*ok*rj/(oj*ri*rk))
       sqjki=sqrt(oj*ok*ri/(oi*rj*rk))
       vmin_d=zconst*( (xij-ri*rj)*sqijk + (xik-ri*rk)*sqikj             &
      &                + (xjk+rj*rk)*sqjki )
References vplus_d().
Referenced by w3iogomd::secondhh().
vplus_d()
real(kind=4) function secondhh::vplus_d (real, intent(in) XI, real, intent(in) XJ, real, intent(in) XK, real, intent(in) XIJ, real, intent(in) XIK, real, intent(in) XJK, real, intent(in) XOI, real, intent(in) XOJ, real, intent(in) XOK)
Definition at line 4903 of file w3iogomd.F90.
 !***  *VPLUS_D*  DETERMINES THE NONLINEAR TRANSFER COEFFICIENT FOR THREE
 !                WAVE INTERACTIONS OF DEEP-WATER WAVES.
 !     PETER JANSSEN
 !     PURPOSE.
 !     --------
 !              GIVES NONLINEAR TRANSFER COEFFICIENT FOR THREE
 !              WAVE INTERACTIONS OF GRAVITY-CAPILLARY WAVES IN THE
 !              IDEAL CASE OF NO CURRENT. (CF.ZAKHAROV)
 !     INTERFACE.
 !     ----------
 !              *VPLUS_D(XI,XJ,XK)*
 !                        *XI*  - WAVE NUMBER
 !                        *XJ*  - WAVE NUMBER
 !                        *XK*  - WAVE NUMBER
 !     METHOD.
 !     -------
 !              NONE
 !     EXTERNALS.
 !     ----------
 !              NONE.
 !***  1. DETERMINE NONLINEAR TRANSFER.
 !     --------------------------------
       IMPLICIT NONE
       REAL, INTENT(IN) :: XI, XJ, XK, XIJ, XIK, XJK, XOI, XOJ, XOK
       REAL :: RI, RJ, RK, OI, OJ, OK, SQIJK, SQIKJ, SQJKI
       ri=abs(xi)+del1
       rj=abs(xj)+del1
       rk=abs(xk)+del1
       oi=xoi+del1
       oj=xoj+del1
       ok=xok+del1
       sqijk=sqrt(oi*oj*rk/(ok*ri*rj))
       sqikj=sqrt(oi*ok*rj/(oj*ri*rk))
       sqjki=sqrt(oj*ok*ri/(oi*rj*rk))
       vplus_d=zconst*( (xij+ri*rj)*sqijk + (xik+ri*rk)*sqikj            &
      &               + (xjk+rj*rk)*sqjki )
Referenced by w3iogomd::secondhh(), and vmin_d().