WAVEWATCH III: w3partmd.F90 File Reference
w3partmd.F90 File Reference
Spectral partitioning module.
Modules
module w3partmd
Spectral partitioning according to the watershed method.
Functions/Subroutines
subroutine w3partmd::w3part (SPEC, UABS, UDIR, DEPTH, WN, NP, XP, DIMXP)
Interface to watershed partitioning routines.
subroutine w3partmd::ptsort (IMI, IND, IHMAX)
Sorts the image data in ascending order.
subroutine w3partmd::ptnghb
Nearest neighbour calculation.
subroutine w3partmd::pt_fld (IMI, IND, IMO, ZP, NPART)
Image watersheding.
subroutine fifo_add (IV)
Add point to FIFO queue.
subroutine fifo_empty (IEMPTY)
Check if queue is empty.
subroutine fifo_first (IV)
Get point out of queue.
subroutine w3partmd::ptmean (NPI, IMO, ZP, DEPTH, UABS, UDIR, WN, NPO, XP, DIMXP, PMAP)
Compute mean parameters per partition.
Detailed Description
Spectral partitioning module.
Authors
Barbara Tracy, H. L. Tolman, M. Szyszka, Chris Bunney
Date
23 Jul 2018
Definition in file w3partmd.F90.
Function/Subroutine Documentation
fifo_add()
subroutine pt_fld::fifo_add (integer, intent(in) IV)
Add point to FIFO queue.
Parameters
[in] IV Point to add
Author
Barbara Tracy
Date
01 Nov 2006
Definition at line 1105 of file w3partmd.F90.
       INTEGER, INTENT(IN)      :: IV
       !
       iq(iq_end) = iv
       !
       iq_end = iq_end + 1
       IF ( iq_end .GT. nspec ) iq_end = 1
       !
       RETURN
Referenced by w3partmd::pt_fld().
fifo_empty()
subroutine pt_fld::fifo_empty (integer, intent(out) IEMPTY)
Check if queue is empty.
Parameters
[out] IEMPTY Set to 1 if queue is empty, else 0
Author
Barbara Tracy
Date
01 Nov 2006
Definition at line 1124 of file w3partmd.F90.
       INTEGER, INTENT(OUT)     :: IEMPTY
       !
       IF ( iq_start .NE. iq_end ) THEN
         iempty = 0
       ELSE
         iempty = 1
       END IF
       !
       RETURN
Referenced by w3partmd::pt_fld().
fifo_first()
subroutine pt_fld::fifo_first (integer, intent(out) IV)
Get point out of queue.
Parameters
[out] IV Returned point
Author
Barbara Tracy
Date
01 Nov 2006
Definition at line 1144 of file w3partmd.F90.
       INTEGER, INTENT(OUT)     :: IV
       !
       iv = iq(iq_start)
       !
       iq_start = iq_start + 1
       IF ( iq_start .GT. nspec ) iq_start = 1
       !
       RETURN
Referenced by w3partmd::pt_fld().