WAVEWATCH III: w3snl3md.F90 File Reference
w3snl3md.F90 File Reference
Generalized and optimized multiple DIA implementation.
Modules
module w3snl3md
Generalized and optimized multiple DIA implementation.
Functions/Subroutines
subroutine w3snl3md::w3snl3 (A, CG, WN, DEPTH, S, D)
Multiple Discrete Interaction Parameterization for arbitrary depths with generalized quadruplet layout.
subroutine expand (SPEC)
Expand spectrum, subroutine used to simplify addressing.
subroutine expnd2 (ARIN, AROUT)
Expand spectrum to simplify indirect addressing.
subroutine w3snl3md::insnl3
Initialization for generalized multiple DIA routine.
real function minlam (MU, THETA)
Calculate minimum allowed lambda for quadruplet configuration.
real function maxlam (MU, THETA)
Calculate maximum allowed lambda for quadruplet configuration.
Variables
real, parameter, public w3snl3md::lammax = 0.49999
real, parameter, public w3snl3md::delthm = 90.
Detailed Description
Generalized and optimized multiple DIA implementation.
Author
H. L. Tolman
Date
13-Jul-2012
Definition in file w3snl3md.F90.
Function/Subroutine Documentation
expand()
subroutine w3snl3::expand (real, dimension(1-nthmax:nth+nthmax,nfrmin:nfrmax), intent(out) SPEC)
Expand spectrum, subroutine used to simplify addressing.
Parameters
[out] SPEC Expanded spectrum.
Author
H. L. Tolman
Date
21-Aug-2009
Definition at line 644 of file w3snl3md.F90.
       !/
       !/                  +-----------------------------------+
       !/                  | WAVEWATCH-III           NOAA/NCEP |
       !/                  |           H. L. Tolman            |
       !/                  |                        FORTRAN 90 |
       !/                  | Last update :         21-Aug-2009 |
       !/                  +-----------------------------------+
       !/
       !/    03-Jul-2008 : Origination.                        ( version 3.13 )
       !/    21-Aug-2009 : Conversion to F(f,theta) form.      ( version 3.13 )
       !/
       !  1. Purpose :
       !
       !     Expand spectrum, subroutine used to simplify addressing.
       !
       !  3. Parameters :
       !
       !     Parameter list
       !     ----------------------------------------------------------------
       !       SPEC    R.A.  O   Expanded spectrum.
       !     ----------------------------------------------------------------
       !
       ! 10. Source code :
       !
       !/ ------------------------------------------------------------------- /
       IMPLICIT NONE
       !/
       !/ Parameter list
       !/
       REAL, INTENT(OUT)       :: SPEC(1-NTHMAX:NTH+NTHMAX,NFRMIN:NFRMAX)
       !/
       !/ Local parameters
       !/
       INTEGER                 :: IFR, ITH
       !/
       !/ ------------------------------------------------------------------- /
       !
       spec(:,nfrmin:0) = 0.
       !
       spec(1:nth,1:nfr) = a * tpi
       !
       DO ifr=1, nfr
         spec(1:nth,ifr) = spec(1:nth,ifr) * xsi(ifr) / xcg(ifr)
       END DO
       !
       DO ifr=nfr+1, nfrmax
         spec(1:nth,ifr) = spec(1:nth,ifr-1) * fachfe
       END DO
       !
       DO ith=1, nthmax
         spec(nth+ith,1:nfrmax) = spec(   ith   ,1:nfrmax)
         spec( 1 -ith,1:nfrmax) = spec(nth+1-ith,1:nfrmax)
       END DO
       !
       RETURN
       !/
       !/ End of EXPAND ----------------------------------------------------- /
       !/
References w3gdatmd::fachfe, constants::tpi, and w3gdatmd::xsi.
Referenced by w3snl3md::w3snl3(), and w3snlsmd::w3snls().
expnd2()
subroutine w3snl3::expnd2 (real, dimension(nth,nfrcut), intent(in) ARIN, real, dimension(1-nthmax:nth+nthmax,nfrmin:nfrcut), intent(out) AROUT)
Expand spectrum to simplify indirect addressing.
Done 'in place' with temporary array (ARIN = AROUT).
Parameters
[in] ARIN Input array.
[out] AROUT Output array.
Author
H. L. Tolman
Date
16-Jul-2008
Definition at line 717 of file w3snl3md.F90.
       !/
       !/                  +-----------------------------------+
       !/                  | WAVEWATCH-III           NOAA/NCEP |
       !/                  |           H. L. Tolman            |
       !/                  |                        FORTRAN 90 |
       !/                  | Last update :         16-Jul-2008 |
       !/                  +-----------------------------------+
       !/
       !/    16-Jul-2008 : Origination.                        ( version 3.13 )
       !/
       !  1. Purpose :
       !
       !     Expand spectrum to simplify indirect addressing.
       !     Done 'in place' with temporary array ( ARIN = AROUT )
       !
       !  3. Parameters :
       !
       !     Parameter list
       !     ----------------------------------------------------------------
       !       SPIN    R.A.  I   Input array.
       !       SPOUT   R.A.  I   Output array.
       !     ----------------------------------------------------------------
       !
       ! 10. Source code :
       !
       !/ ------------------------------------------------------------------- /
       IMPLICIT NONE
       !/
       !/ Parameter list
       !/
       REAL, INTENT(IN)      :: ARIN(NTH,NFRCUT)
       REAL, INTENT(OUT)     :: AROUT(1-NTHMAX:NTH+NTHMAX,NFRMIN:NFRCUT)
       !/
       !/ Local parameters
       !/
       INTEGER               :: IFR, ITH
       REAL                  :: TEMP(NTH,NFRCUT)
       !/
       !/ ------------------------------------------------------------------- /
       !
       temp   = arin
       !
       arout(:,nfrmin:0) = 0.
       !
       arout(1:nth,1:nfrcut) = temp
       !
       DO ith=1, nthmax
         arout(nth+ith,1:nfrcut) = arout(   ith   ,1:nfrcut)
         arout( 1 -ith,1:nfrcut) = arout(nth+1-ith,1:nfrcut)
       END DO
       !
       RETURN
       !/
       !/ End of EXPND2 ----------------------------------------------------- /
       !/
Referenced by w3snl3md::w3snl3().
maxlam()
real function insnl3::maxlam (real, intent(in) MU, real, intent(in) THETA)
Calculate maximum allowed lambda for quadruplet configuration.
Attention
replaced (likely typo) 'minimum' from original header here with 'maximum'.
Parameters
MU Quadruplet parameters.
THETA Theta in degrees.
Returns
MAXLAM Maximum allowed lambda.
Author
H. L. Tolman
Date
28-Jan-2004
Definition at line 1602 of file w3snl3md.F90.
       !/
       !/                  +-----------------------------------+
       !/                  | WAVEWATCH-III           NOAA/NCEP |
       !/                  |           H. L. Tolman            |
       !/                  |                        FORTRAN 90 |
       !/                  | Last update :         28-Jan-2004 |
       !/                  +-----------------------------------+
       !/
       !/    28-Jan-2009 : Origination.
       !/
       !  1. Purpose :
       !
       !     Calculate minimum allowed lambda for quadruplet configuration.
       !
       !  3. Parameters :
       !
       !     Parameter list
       !     ----------------------------------------------------------------
       !       MU, THETA  Real   Quadruplet parameters, theta in degree.
       !     ----------------------------------------------------------------
       !
       ! 10. Source code :
       !
       !/ ------------------------------------------------------------------- /
       IMPLICIT NONE
       !/
       !/ Parameter list
       !/
       REAL, INTENT(IN)        :: MU, THETA
       !/
       !/ Local parameters
       !/
       REAL                    :: MULOC, THETAR, BB, AUX
       !/
       !/ ------------------------------------------------------------------- /
       !/
       IF ( theta .LT. 0. ) THEN
         maxlam = 0.5
       ELSE
         muloc  = max( 0. , min( 1., mu ) )
         thetar = theta * atan(1.) / 45.
         bb     = (1.+muloc)**4 + (1.-muloc)**4 +                    &
              2. * (1.+muloc)**2 * (1.-muloc)**2 * cos(thetar)
         bb     = sqrt( max( bb , 0. ) )
         maxlam = 0.25 * bb
       END IF
       !
       RETURN
       !/
       !/ End of MAXLAM ----------------------------------------------------- /
       !/
Referenced by w3snl3md::insnl3().
minlam()
real function insnl3::minlam (real, intent(in) MU, real, intent(in) THETA)
Calculate minimum allowed lambda for quadruplet configuration.
Parameters
MU Quadruplet parameters.
THETA Theta in degrees.
Returns
MINLAM Minimum allowed lambda.
Author
H. L. Tolman
Date
28-Jan-2004
Definition at line 1534 of file w3snl3md.F90.
       !/
       !/                  +-----------------------------------+
       !/                  | WAVEWATCH-III           NOAA/NCEP |
       !/                  |           H. L. Tolman            |
       !/                  |                        FORTRAN 90 |
       !/                  | Last update :         28-Jan-2004 |
       !/                  +-----------------------------------+
       !/
       !/    28-Jan-2009 : Origination.
       !/
       !  1. Purpose :
       !
       !     Calculate minimum allowed lambda for quadruplet configuration.
       !
       !  3. Parameters :
       !
       !     Parameter list
       !     ----------------------------------------------------------------
       !       MU, THETA  Real   Quadruplet parameters, theta in degree.
       !     ----------------------------------------------------------------
       !
       ! 10. Source code :
       !
       !/ ------------------------------------------------------------------- /
       IMPLICIT NONE
       !/
       !/ Parameter list
       !/
       REAL, INTENT(IN)        :: MU, THETA
       !/
       !/ Local parameters
       !/
       REAL                    :: MULOC, THETAR, BB, AUX
       !/
       !/ ------------------------------------------------------------------- /
       !/
       IF ( theta .LT. 0. ) THEN
         minlam = 0.
       ELSE
         muloc  = max( 0. , min( 1., mu ) )
         thetar = theta * atan(1.) / 45.
         bb     = (1.+muloc)**4 + (1.-muloc)**4 +                    &
              2. * (1.+muloc)**2 * (1.-muloc)**2 * cos(thetar)
         bb     = sqrt( max( bb , 0. ) )
         aux    = max( 0. , 0.5*bb-1. )
         minlam = sqrt( aux )
       END IF
       !
       RETURN
       !/
       !/ End of MINLAM ----------------------------------------------------- /
       !/
Referenced by w3snl3md::insnl3().