WAVEWATCH III: w3timemd.F90 File Reference
w3timemd.F90 File Reference
Modules
module w3timemd
Functions/Subroutines
subroutine w3timemd::tick21 (TIME, DTIME)
integer function iymd21 (NYMD, M)
real function w3timemd::dsec21 (TIME1, TIME2)
integer function mymd21 (NYMD)
real function w3timemd::tdiff (T1, T2)
subroutine w3timemd::stme21 (TIME, DTME21)
integer function w3timemd::julday (id, mm, iyyy)
subroutine w3timemd::caldat (julian, id, mm, iyyy)
real(kind=8) function w3timemd::time2hours (TIME)
subroutine w3timemd::prinit
subroutine w3timemd::prtime (PTIME)
subroutine w3timemd::t2d (TIME, DAT, IERR)
subroutine w3timemd::d2t (DAT, TIME, IERR)
subroutine w3timemd::d2j (DAT, JULIAN, IERR)
subroutine w3timemd::j2d (JULIAN, DAT, IERR)
double precision function w3timemd::tsub (T1, T2)
double precision function w3timemd::tsubsec (T1, T2)
subroutine w3timemd::u2d (UNITS, DAT, IERR)
subroutine w3timemd::t2iso (TIME, ISODT)
Variables
character, public w3timemd::caltype
Function/Subroutine Documentation
iymd21()
integer function tick21::iymd21 (integer, intent(in) NYMD, integer, intent(in) M)
Definition at line 198 of file w3timemd.F90.
       !/
       !/                  +-----------------------------------+
       !/                  | WAVEWATCH III           NOAA/NCEP |
       !/                  |           H. L. Tolman            |
       !/                  |                        FORTRAN 90 |
       !/                  | Last update :         18-Jun-2020 |
       !/                  +-----------------------------------+
       !/                                Based on INCYMD of the GLA GCM.
       !/
       !/    18-Oct-1998 : Final FORTRAN 77                    ( version 1.18 )
       !/    29-Nov-1999 : Upgrade to FORTRAN 90               ( version 2.00 )
       !/    10-Jan-2017 : Add NOLEAP option, 365 day calendar ( version 6.00 )
       !/    18-Jun-2020 : Add 360-day calendar option         ( version 7.08 )
       !/
       !  1. Purpose :
       !
       !     Increment date in YYYYMMDD format by +/- 1 day.
       !
       !  3. Parameters :
       !
       !     Parameter list
       !     ----------------------------------------------------------------
       !       NYMD    Int.   I   Old date in YYMMDD format.
       !       M       Int.   I   +/- 1 (Day adjustment)
       !     ----------------------------------------------------------------
       !
       !  4. Subroutines used :
       !
       !      Name      Type  Module   Description
       !     ----------------------------------------------------------------
       !      STRACE    Subr. W3SERVMD Subroutine tracing.
       !     ----------------------------------------------------------------
       !
       !  5. Called by :
       !
       !     Any subroutine.
       !
       !  8. Structure :
       !
       !     See source code.
       !
       !  9. Switches :
       !
       !     !/S  Enable subroutine tracing using STRACE.
       !
       ! 10. Source code :
       !
       !/ ------------------------------------------------------------------- /
       !/
       IMPLICIT NONE
       !/
       !/ ------------------------------------------------------------------- /
       !/ Parameter list
       !/
       INTEGER, INTENT(IN)     :: NYMD, M
       !/
       !/ ------------------------------------------------------------------- /
       !/ Local parameters
       !/
       INTEGER                 :: NY, NM, ND
       INTEGER, SAVE           :: NDPM(12)
 #ifdef W3_S
       INTEGER, SAVE           :: IENT = 0
 #endif
       LOGICAL                 :: LEAP
       !/
       !/ ------------------------------------------------------------------- /
       !/
 #ifdef W3_S
       CALL strace (ient, 'IYMD21')
 #endif
       !
       ! Declare the number of days in month depending on calendar
       !
       IF (trim(caltype) .EQ. '360_day' ) THEN
         ndpm=(/ 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30 /)
       ELSE
         ndpm=(/ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 /)
       END IF
       !
       ! "Unpack" and increment date :
       !
       ny   = nymd / 10000
       nm   = mod(nymd,10000) / 100
       nm   = min( 12 , max(1,nm) )
       nd   = mod(nymd,100) + m
       ! Add override for simulations with no leap years
       IF (trim(caltype) .EQ. 'standard' ) THEN
         leap = mod(ny,400).EQ.0 .OR.                           &
              ( mod(ny,4).EQ.0 .AND. mod(ny,100).NE.0 )
       ELSE
         leap = .false.
       END IF
       !
       ! M = -1, change month if necessary :
       !
       IF (nd.EQ.0) THEN
         nm   = nm - 1
         IF (nm.EQ.0) THEN
           nm   = 12
           ny   = ny - 1
         ENDIF
         nd   = ndpm(nm)
         IF (nm.EQ.2 .AND. leap)  nd = 29
       END IF
       !
       ! M = 1, leap year
       !
       IF (nd.EQ.29 .AND. nm.EQ.2 .AND. leap)  GO TO 20
       !
       !        next month
       !
       IF (nd.GT.ndpm(nm)) THEN
         nd = 1
         nm = nm + 1
         IF (nm.GT.12) THEN
           nm = 1
           ny = ny + 1
         ENDIF
       END IF
       !
 20    CONTINUE
       iymd21 = ny*10000 + nm*100 + nd
       !
       RETURN
       !/
       !/ End of IYMD21 ----------------------------------------------------- /
       !/
References w3timemd::caltype, and w3servmd::strace().
Referenced by w3timemd::tick21().
mymd21()
integer function dsec21::mymd21 (integer, intent(in) NYMD)
Definition at line 460 of file w3timemd.F90.
       !/
       !/                  +-----------------------------------+
       !/                  | WAVEWATCH III           NOAA/NCEP |
       !/                  |           H. L. Tolman            |
       !/                  |                        FORTRAN 90 |
       !/                  | Last update :         18-Jun-2020 |
       !/                  +-----------------------------------+
       !/                                Based on MODYMD of the GLA GCM.
       !/
       !/    19-Oct-1998 : Final FORTRAN 77                    ( version 1.18 )
       !/    29-Nov-1999 : Upgrade to FORTRAN 90               ( version 2.00 )
       !/    10-Jan-2017 : Add NOLEAP option, 365 day calendar ( version 6.01 )
       !/    18-Jun-2020 : Add 360-day calendar support        ( version 7.08 )
       !/
       !  1. Purpose :
       !
       !     Convert date in YYMMDD format to julian date.
       !
       !  3. Parameters :
       !
       !     Parameter list
       !     ----------------------------------------------------------------
       !       NYMD    Int.   I   Date in YYMMDD format.
       !     ----------------------------------------------------------------
       !
       !  4. Subroutines used :
       !
       !      Name      Type  Module   Description
       !     ----------------------------------------------------------------
       !      STRACE    Subr. W3SERVMD Subroutine tracing.
       !     ----------------------------------------------------------------
       !
       !  5. Called by :
       !
       !     Any subroutine.
       !
       !  8. Structure :
       !
       !     See source code.
       !
       !  9. Switches :
       !
       !     !/S  Enable subroutine tracing using STRACE.
       !
       ! 10. Source code :
       !
       !/ ------------------------------------------------------------------- /
       !/
       IMPLICIT NONE
       !/
       !/ ------------------------------------------------------------------- /
       !/ Parameter list
       !/
       INTEGER, INTENT(IN)     :: NYMD
       !/
       !/ ------------------------------------------------------------------- /
       !/ Local parameters
       !/
       INTEGER                 :: NY, NM, ND
       INTEGER, SAVE           :: NDPM(12)
 #ifdef W3_S
       INTEGER, SAVE           :: IENT = 0
 #endif
       LOGICAL                 :: LEAP
       !/
       !/ ------------------------------------------------------------------- /
       !/
 #ifdef W3_S
       CALL strace (ient, 'MYMD21')
 #endif
       !
       ! Declare the number of days in month depending on calendar
       !
       IF (trim(caltype) .EQ. '360_day' ) THEN
         ndpm=(/ 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30 /)
       ELSE
         ndpm=(/ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 /)
       END IF
       !
       ! "Unpack" and increment date :
       !
       ny   = nymd / 10000
       nm   = mod(nymd,10000) / 100
       nd   = mod(nymd,100)
       !Allow override for NoLeap simulations
       IF (trim(caltype) .EQ. 'standard' ) THEN
         leap = mod(ny,400).EQ.0 .OR.                           &
              ( mod(ny,4).EQ.0 .AND. mod(ny,100).NE.0 )
       ELSE
         leap=.false.
       ENDIF
       !
       ! Loop over months :
       !
       IF (nm.GT.2 .AND. leap)  nd = nd + 1
       !
 40    CONTINUE
       IF (nm.LE.1)  GO TO 60
       nm = nm - 1
       nd = nd + ndpm(nm)
       GO TO 40
       !
 60    CONTINUE
       mymd21 = nd
       !
       RETURN
       !/
       !/ End of MYMD21 ----------------------------------------------------- /
       !/
References w3timemd::caltype, and w3servmd::strace().
Referenced by w3timemd::dsec21().