WAVEWATCH III: ww3_bound.F90 File Reference
ww3_bound.F90 File Reference
Contains program W3BOUND for boundary conditions.
Functions/Subroutines
program w3bound
Combines spectra files into a nest. ww3 file for boundary conditions.
Detailed Description
Contains program W3BOUND for boundary conditions.
Author
F. Ardhuin
Date
21-Jul-2020
Definition in file ww3_bound.F90.
Function/Subroutine Documentation
w3bound()
program w3bound
Combines spectra files into a nest. ww3 file for boundary conditions.
Finds nearest points and performs linear interpolation. The initial conditions are written to the restart.ww3 using the subroutine W3IORS. Note that the name of the restart file is set in W3IORS.
Author
F. Ardhuin
Date
21-Jul-2020
Definition at line 15 of file ww3_bound.F90.
References w3gdatmd::clgtype, w3servmd::extcde(), file(), constants::file_endian, w3odatmd::flbpi, w3odatmd::fnmpre, w3gdatmd::fr1, w3gdatmd::gname, w3gdatmd::gtype, w3iobcmd::idstrbc, include(), interp(), w3servmd::itrace(), w3gdatmd::mapsf, w3gdatmd::mapsta, w3odatmd::ndse, w3odatmd::ndso, w3servmd::nextln(), w3gdatmd::nk, w3gdatmd::nsea, w3gdatmd::nth, constants::pi, w3gdatmd::polat, w3gdatmd::polon, w3gdatmd::rlgtype, w3servmd::strace(), w3gdatmd::sx, w3gdatmd::sy, constants::tpi, constants::tpiinv, w3gdatmd::ungtype, w3iobcmd::verbptbc, w3servmd::w3eqtoll(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3nmlboundmd::w3nmlbound(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3gdatmd::x0, w3gdatmd::xfr, w3gdatmd::xgrd, w3gdatmd::y0, and w3gdatmd::ygrd.