WAVEWATCH III: ww3_bounc.F90 File Reference
ww3_bounc.F90 File Reference
Contains the boundary condition program, W3BOUNC.
Functions/Subroutines
program w3bounc
Combines spectra files into a nest. ww3 file for boundary conditions.
subroutine check_err (IRET)
Check input return status for error value.
Detailed Description
Contains the boundary condition program, W3BOUNC.
Author
F Ardhuin
M Accensi
Date
21-Jul-2020
Definition in file ww3_bounc.F90.
Function/Subroutine Documentation
check_err()
subroutine check_err (integer IRET)
Check input return status for error value.
Parameters
IRET return status to check
Author
NA
Date
NA
Definition at line 856 of file ww3_bounc.F90.
   USE netcdf
   USE w3odatmd, ONLY: ndse
   USE w3servmd, ONLY: extcde
   IMPLICIT NONE
   INTEGER IRET
   IF (iret .NE. nf90_noerr) THEN
     WRITE(ndse,*) ' *** WAVEWATCH III ERROR IN BOUNC :'
     WRITE(ndse,*) ' NETCDF ERROR MESSAGE: '
     WRITE(ndse,*) nf90_strerror(iret)
     CALL extcde ( 59 )
   END IF
   RETURN
References w3servmd::extcde(), and w3odatmd::ndse.
Referenced by w3bounc(), w3crnc(), w3exnc(), w3ounf(), w3ounp(), w3prnc(), and w3trnc().
w3bounc()
program w3bounc
Combines spectra files into a nest. ww3 file for boundary conditions.
Finds nearest points and performs linear interpolation. The initial conditions are written to the restart.ww3 using the subroutine W3IORS. Note that the name of the restart file is set in W3IORS.
Author
F Ardhuin
M Accensi
Date
21-Jul-2020
Definition at line 22 of file ww3_bounc.F90.
References check_err(), w3gdatmd::clgtype, w3servmd::dist_sphere(), w3gdatmd::dth, w3servmd::extcde(), w3gdatmd::fachfe, file(), constants::file_endian, w3gdatmd::flagll, w3odatmd::fnmpre, w3gdatmd::fr1, w3gdatmd::gname, w3gdatmd::gtype, w3iobcmd::idstrbc, include(), interp(), w3servmd::itrace(), w3gdatmd::mapsf, w3gdatmd::mapsta, w3odatmd::ndso, w3servmd::nextln(), w3gdatmd::nk, w3gdatmd::nsea, w3gdatmd::nth, constants::pi, w3gdatmd::polat, w3gdatmd::polon, w3gdatmd::rlgtype, w3servmd::strace(), w3gdatmd::sx, w3gdatmd::sy, w3gdatmd::th, constants::tpi, constants::tpiinv, w3gdatmd::ungtype, w3iobcmd::verbptbc, w3cspcmd::w3cspc(), w3servmd::w3eqtoll(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3nmlbouncmd::w3nmlbounc(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3gdatmd::x0, w3gdatmd::xfr, w3gdatmd::xgrd, w3gdatmd::y0, and w3gdatmd::ygrd.