WAVEWATCH III: ww3_systrk.F90 File Reference
ww3_systrk.F90 File Reference
Contains program WW3_SYSTRK for tracking of wave systems.
Functions/Subroutines
program ww3_systrk
Perform spatial and temporal tracking of wave systems, based on spectral partition (bulletin) output.
subroutine t2netcdf (lons, lats, data_in, nlons, nlats, nsys, date1, date2, dt, ntime, ivar, outputType)
N/A.
subroutine check (status)
N/A.
subroutine pt2netcdf (longitude, latitude, hs, tp, dir, npoints, date1, date2, dt, ntime, outputType)
N/A.
Detailed Description
Contains program WW3_SYSTRK for tracking of wave systems.
Author
A. J. van der Westhuysen
Jeff Hanson
Eve-Marie Devaliere
Date
16-Jan-2017
Definition in file ww3_systrk.F90.
Function/Subroutine Documentation
check()
subroutine check (integer, intent(in) status)
N/A.
Parameters
[in] status
Author
N/A
Date
N/A
Definition at line 1299 of file ww3_systrk.F90.
   use netcdf
   integer, intent ( in) :: status
   if(status /= nf90_noerr) then
     write(6,996)
 996 FORMAT (/' *** WAVEWATCH III ERROR IN WW3_SYSTRK:'/           &
          'netCDF error:')
     print *, trim(nf90_strerror(status))
     stop "Stopped in netcdf output part"
   endif
Referenced by wmesmfmd::fieldindex(), pt2netcdf(), t2netcdf(), w3gsrumd::w3gsup(), and wmunitmd::wmuinq().
pt2netcdf()
subroutine pt2netcdf (real, dimension(npoints) longitude, real, dimension(npoints) latitude, real, dimension(nsys, npoints, ntime) hs, real, dimension(nsys, npoints, ntime) tp, real, dimension(nsys, npoints, ntime) dir, integer npoints, double precision date1, double precision date2, real dt, integer ntime, integer outputType)
N/A.
Parameters
longitude
latitude
hs
tp
dir
npoints
date1
date2
dt
ntime
outputType
Author
N/A
Date
N/A
Definition at line 1332 of file ww3_systrk.F90.
   USE w3timemd
   use netcdf
   implicit none
   integer :: ntime,npoints,outputType
   integer, parameter :: deflate = 1
   integer :: iret, oldMode
   integer :: ncid
   integer :: system_index_dim
   integer :: point_dim,rec_dim
   integer :: nsys
   integer :: start(3), count(3)
   parameter(nsys = 10)
   integer :: latitude_id
   integer :: longitude_id
   integer :: time_id
   integer :: hs_id
   integer :: tp_id
   integer :: dir_id
   integer :: time_rank
   integer :: hs_rank
   integer :: tp_rank
   integer :: dir_rank
   parameter(time_rank = 1)
   parameter(hs_rank = 3)
   parameter(tp_rank = 3)
   parameter(dir_rank = 3)
 #endif
   !
 #ifdef W3_TRKNC
   integer :: hs_dims(hs_rank)
   integer :: tp_dims(tp_rank)
   integer :: dir_dims(dir_rank)
   real :: latitude(npoints),dt
   real :: longitude(npoints)
   real :: hs(nsys, npoints, ntime)
   real :: tp(nsys, npoints, ntime)
   real :: dir(nsys, npoints, ntime)
   integer :: iyc,imc,idc,ihc,iminc,isc,Jday,Jday0,rec
   double precision date1,date2,timenc
   double precision times(ntime)
 #endif
   !
 #ifdef W3_TRKNC
   iyc=date1/10000
   imc=(date1-iyc*10000)/100
   idc=int(date1-dble(iyc*10000)-dble(imc*100))
   ihc=date2/10000
   iminc=(date2-ihc*10000)/100
   isc=date2-ihc*10000-100*iminc
   timenc=dble(julday(idc,imc,iyc))+(dble(ihc)+(dble(iminc)+ &
        (dble(isc)/60.0d0))/60.0d0)/24.0d0
   jday0=julday(1,1,1990)
   timenc=timenc-jday0
   do rec=1,ntime
     times(rec)=timenc+dble( (rec-1)*dt)/3600.0d0/24.0d0
   enddo
 #endif
   !
 #ifdef W3_TRKNC
   if(outputtype.EQ.3) then
     iret = nf90_create('sys_pnt.ww3.nc', nf90_clobber, ncid)
   endif
   if (outputtype.EQ.4) iret = nf90_create('sys_pnt.ww3.nc',nf90_netcdf4, ncid)
   call check(iret)
   iret = nf90_set_fill(ncid,nf90_nofill,oldmode)
   call check(iret)
   ! define dimensions
   iret = nf90_def_dim(ncid, 'system_index', nsys, system_index_dim)
   call check(iret)
   iret = nf90_def_dim(ncid, 'point', npoints, point_dim)
   call check(iret)
   iret = nf90_def_dim(ncid, 'time', ntime, rec_dim)
   call check(iret)
   ! define variables
   iret = nf90_def_var(ncid, 'latitude', nf90_real, point_dim, &
        latitude_id)
   call check(iret)
   if (outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,latitude_id,1,1,deflate))
   iret = nf90_def_var(ncid, 'longitude', nf90_real, point_dim, &
        longitude_id)
   call check(iret)
   if (outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,longitude_id,1,1,deflate))
   iret = nf90_def_var(ncid, 'time', nf90_double, rec_dim, &
        time_id)
   call check(iret)
   if (outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,time_id,1,1,deflate) )
   hs_dims(3) = rec_dim
   hs_dims(2) = point_dim
   hs_dims(1) = system_index_dim
   iret = nf90_def_var(ncid, 'hs', nf90_real,  &
        hs_dims, hs_id)
   call check(iret)
   if (outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,hs_id,1,1,deflate))
   tp_dims(3) = rec_dim
   tp_dims(2) = point_dim
   tp_dims(1) = system_index_dim
   iret = nf90_def_var(ncid, 'tp', nf90_real, &
        tp_dims, tp_id)
   call check(iret)
   if (outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,tp_id,1,1,deflate))
   dir_dims(3) = rec_dim
   dir_dims(2) = point_dim
   dir_dims(1) = system_index_dim
   iret = nf90_def_var(ncid, 'dir', nf90_real, &
        dir_dims, dir_id)
   call check(iret)
   if (outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,dir_id,1,1,deflate))
   ! assign attributes
   iret = nf90_put_att(ncid, latitude_id, 'units', 'degrees_north')
   call check(iret)
   iret = nf90_put_att(ncid, latitude_id, 'long_name', 'latitude')
   call check(iret)
   iret = nf90_put_att(ncid, latitude_id, 'standard_name', 'latitude')
   call check(iret)
   iret = nf90_put_att(ncid, latitude_id, 'axis', 'Y')
   call check(iret)
   iret = nf90_put_att(ncid, longitude_id, 'units', 'degrees_east')
   call check(iret)
   iret = nf90_put_att(ncid, longitude_id,'long_name','longitude')
   call check(iret)
   iret = nf90_put_att(ncid, longitude_id,'standard_name','longitude')
   call check(iret)
   iret = nf90_put_att(ncid, longitude_id, 'axis', 'X')
   call check(iret)
   iret = nf90_put_att(ncid, time_id, 'units', &
        'days since 1990-01-01 00:00:00')
   call check(iret)
   iret = nf90_put_att(ncid, time_id, 'long_name','julian day(UT)')
   call check(iret)
   iret = nf90_put_att(ncid, time_id, 'standard_name','time')
   call check(iret)
   iret = nf90_put_att(ncid, time_id, 'conventions', &
        'relative julian day with decimal part (as part of the day)')
   call check(iret)
   iret = nf90_put_att(ncid, time_id, 'axis', 'T')
   call check(iret)
   iret = nf90_put_att(ncid, hs_id, 'units', 'm')
   call check(iret)
   iret = nf90_put_att(ncid, hs_id,'long_name','significant_wave_height')
   call check(iret)
   iret = nf90_put_att(ncid, hs_id, 'missing_value', &
        '999.9999')
   call check(iret)
   iret = nf90_put_att(ncid, tp_id, 'units', 's')
   call check(iret)
   iret = nf90_put_att(ncid, tp_id,'long_name','peak_period')
   call check(iret)
   iret = nf90_put_att(ncid, tp_id, 'missing_value', &
        '999.9999')
   call check(iret)
   iret = nf90_put_att(ncid, dir_id, 'units', 'degrees')
   call check(iret)
   iret = nf90_put_att(ncid, dir_id,'long_name','peak_direction')
   call check(iret)
   iret = nf90_put_att(ncid, dir_id, 'missing_value',&
        '999.9999')
   call check(iret)
   ! leave define mode
   iret = nf90_enddef(ncid)
   call check(iret)
   iret = nf90_put_var(ncid, latitude_id, latitude)
   call check(iret)
 #endif
   !
 #ifdef W3_TRKNC
   iret = nf90_put_var(ncid, longitude_id, longitude)
   call check(iret)
 #endif
   !
 #ifdef W3_TRKNC
   iret = nf90_put_var(ncid, time_id, times)
   call check(iret)
 #endif
   !
 #ifdef W3_TRKNC
   start = (/ 1, 1, 1 /)
   count = (/ nsys,npoints,ntime /)
 #endif
   !
 #ifdef W3_TRKNC
   iret = nf90_put_var(ncid, hs_id, hs,&
        start = start, count = count )
   call check(iret)
   iret = nf90_put_var(ncid, tp_id, tp, &
        start = start, count = count )
   call check(iret)
   iret = nf90_put_var(ncid, dir_id, dir,&
        start = start, count = count )
   call check(iret)
   iret = nf90_close(ncid)
   call check(iret)
   return
References check(), and w3timemd::julday().
Referenced by ww3_systrk().
t2netcdf()
subroutine t2netcdf (real, dimension(nlons) lons, real, dimension(nlats) lats, real, dimension(nlons, nlats, nsys,ntime) data_in, integer nlons, integer nlats, integer nsys, double precision date1, double precision date2, real dt, integer ntime, integer ivar, integer outputType)
N/A.
Parameters
lons
lats
data_in
nlons
nlats
nsys
date1
date2
dt
ntime
ivar
outputType
Author
N/A
Date
N/A
Definition at line 1129 of file ww3_systrk.F90.
   USE w3timemd
   use netcdf
   implicit none
   character (len = 15) :: file_name
   integer, parameter :: ndims = 4
   integer, parameter :: deflate = 1
   integer :: outputType, ncid, oldMode
   integer :: nlons,nlats,nsys,rec,ntime,ivar
   double precision :: date1,date2,timenc
   real :: data_in(nlons, nlats, nsys,ntime)
   real :: lats(nlats), lons(nlons),dt
   double precision :: times(ntime)
   integer :: iyc,imc,idc,ihc,iminc,isc,Jday,Jday0
   integer :: iret
 #endif
   !
 #ifdef W3_TRKNC
   integer :: lon_varid, lat_varid, rec_varid
   character (len = *), parameter :: lsys_name = "system_index"
   character (len = *), parameter :: lat_name = "latitude"
   character (len = *), parameter :: lon_name = "longitude"
   character (len = *), parameter :: time_name = "time"
   integer :: sys_dimid, lon_dimid, lat_dimid, rec_dimid
   integer :: start(ndims), count(ndims)
 #endif
   !
 #ifdef W3_TRKNC
   character (len = *), parameter :: var1_name="hs"
   character (len = *), parameter :: var2_name="tp"
   character (len = *), parameter :: var3_name="dir"
   character (len = *), parameter :: var4_name="dspr"
   integer :: var1_varid, var2_varid, var3_varid,var4_varid
   integer :: dimids(ndims)
 #endif
   !
 #ifdef W3_TRKNC
   character (len = *), parameter :: units = "units"
   character (len = *), parameter :: var1_units = "m"
   character (len = *), parameter :: var2_units = "s"
   character (len = *), parameter :: var3_units = "degrees"
   character (len = *), parameter :: var4_units = "degrees"
   character (len = *), parameter :: lat_units = "degrees_north"
   character (len = *), parameter :: lon_units = "degrees_east"
   iyc=date1/10000
   imc=(date1-iyc*10000)/100
   idc=int(date1-dble(iyc*10000)-dble(imc*100))
   ihc=date2/10000
   iminc=(date2-ihc*10000)/100
   isc=date2-ihc*10000-100*iminc
   timenc=dble(julday(idc,imc,iyc))+(dble(ihc)+(dble(iminc)+ &
        (dble(isc)/60.0d0))/60.0d0)/24.0d0
   jday0=julday(1,1,1990)
   timenc=timenc-jday0
   do rec=1,ntime
     times(rec)=timenc+dble( (rec-1)*dt)/3600.0d0/24.0d0
   enddo
   if( ivar == 1) then
     file_name = "sys_hs.ww3.nc"
   else if( ivar == 2) then
     file_name = "sys_tp.ww3.nc"
   else if( ivar == 3) then
     file_name = "sys_dir.ww3.nc"
   else
     file_name = "sys_dspr.ww3.nc"
   endif
 #endif
   !
 #ifdef W3_TRKNC
   ! create the netcdf file.
   if (outputtype.EQ.3) then
     call check( nf90_create(file_name, nf90_clobber, ncid) )
   endif
   if(outputtype.EQ.4) call check( nf90_create(file_name,nf90_netcdf4,ncid))
   call check ( nf90_set_fill(ncid,nf90_nofill,oldmode) )
   call check( nf90_def_dim(ncid, lsys_name, nsys, sys_dimid) )
   call check( nf90_def_dim(ncid, lat_name, nlats, lat_dimid) )
   call check( nf90_def_dim(ncid, lon_name, nlons, lon_dimid) )
   call check( nf90_def_dim(ncid, time_name, ntime, rec_dimid) )
   call check( nf90_def_var(ncid, lat_name, nf90_real, lat_dimid,lat_varid))
   if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,lat_varid,1,1,deflate) )
   call check( nf90_def_var(ncid, lon_name, nf90_real, lon_dimid,lon_varid))
   if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,lon_varid,1,1,deflate) )
   call check( nf90_def_var(ncid,time_name,nf90_double,rec_dimid,rec_varid))
   if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,rec_varid,1,1,deflate) )
 #endif
   !
 #ifdef W3_TRKNC
   call check( nf90_put_att(ncid, lat_varid, units, lat_units) )
   call check( nf90_put_att(ncid, lat_varid, 'long_name', 'latitude') )
   call check( nf90_put_att(ncid, lat_varid, 'standard_name', 'latitude') )
   call check( nf90_put_att(ncid, lat_varid, 'axis','Y'))
   call check( nf90_put_att(ncid, lon_varid, units, lon_units) )
   call check( nf90_put_att(ncid, lon_varid, 'long_name', 'longitude') )
   call check( nf90_put_att(ncid, lon_varid, 'standard_name', 'longitude') )
   call check( nf90_put_att(ncid, lon_varid, 'axis','X'))
   call check(nf90_put_att(ncid,rec_varid,units,&
        'days since 1990-01-01 00:00:00'))
   call check(nf90_put_att(ncid,rec_varid,'long_name','julian day (UT)'))
   call check( nf90_put_att(ncid, rec_varid,'standard_name', 'time') )
   call check( nf90_put_att(ncid, rec_varid, 'conventions',&
        'relative julian day with decimal part (as part of the day)' ) )
   call check( nf90_put_att(ncid, rec_varid, 'axis','T'))
 #endif
   !
 #ifdef W3_TRKNC
   dimids = (/ lon_dimid, lat_dimid, sys_dimid, rec_dimid /)
   if( ivar == 1) then
     call check( nf90_def_var(ncid, var1_name, nf90_real, dimids,var1_varid) )
     if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,var1_varid,1,1,deflate) )
     call check( nf90_put_att(ncid, var1_varid, units, var1_units) )
     call check( nf90_put_att(ncid, var1_varid,'long_name','significant_wave_height') )
     call check( nf90_put_att(ncid, var1_varid,'missing_value','9999.00'))
   else if( ivar == 2) then
     call check( nf90_def_var(ncid, var2_name, nf90_real, dimids, var2_varid) )
     if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,var2_varid,1,1,deflate) )
     call check( nf90_put_att(ncid, var2_varid, units, var2_units) )
     call check( nf90_put_att(ncid, var2_varid,'long_name','peak_period') )
     call check( nf90_put_att(ncid, var2_varid,'missing_value','9999.00') )
   else if ( ivar ==3 ) then
     call check( nf90_def_var(ncid, var3_name, nf90_real, dimids, var3_varid) )
     if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,var3_varid,1,1,deflate) )
     call check( nf90_put_att(ncid, var3_varid, units, var3_units) )
     call check( nf90_put_att(ncid, var3_varid,'long_name','peak_direction') )
     call check( nf90_put_att(ncid, var3_varid,'missing_value','9999.00') )
   else
     call check( nf90_def_var(ncid, var4_name, nf90_real, dimids, var4_varid) )
     if(outputtype.EQ.4) call check( nf90_def_var_deflate(ncid,var4_varid,1,1,deflate) )
     call check( nf90_put_att(ncid, var4_varid, units, var4_units) )
     call check( nf90_put_att(ncid,var4_varid,'long_name','directional_spread') )
     call check( nf90_put_att(ncid, var4_varid,'missing_value','9999.00') )
   endif
   call check( nf90_enddef(ncid) )
 #endif
   !
 #ifdef W3_TRKNC
   call check( nf90_put_var(ncid, lat_varid, lats) )
   call check( nf90_put_var(ncid, lon_varid, lons) )
   call check( nf90_put_var(ncid, rec_varid, times) )
 #endif
   !
 #ifdef W3_TRKNC
   count = (/ nlons, nlats, nsys, ntime /)
   start = (/ 1, 1, 1, 1 /)
   if( ivar == 1) then
     call check( nf90_put_var(ncid, var1_varid, data_in, start = start, &
          count = count) )
   else if( ivar == 2) then
     call check( nf90_put_var(ncid, var2_varid, data_in, start = start, &
          count = count) )
   else if( ivar == 3) then
     call check( nf90_put_var(ncid, var3_varid, data_in, start = start, &
          count = count) )
   else
     call check( nf90_put_var(ncid, var4_varid, data_in, start = start, &
          count = count) )
   endif
   call check( nf90_close(ncid) )
References check(), and w3timemd::julday().
Referenced by ww3_systrk().
ww3_systrk()
program ww3_systrk
Perform spatial and temporal tracking of wave systems, based on spectral partition (bulletin) output.
This is a controller program. It reads the input parameter file ww3_systrk.inp and calls subroutine waveTracking_NWS_V2 to perform the actual tracking procedure. Write output (fields and point output).
Author
A. J. van der Westhuysen
Jeff Hanson
Eve-Marie Devaliere
Date
16-Jan-2017
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Definition at line 29 of file ww3_systrk.F90.
References file(), include(), constants::pi, pt2netcdf(), t2netcdf(), w3timemd::tdiff(), and w3strkmd::wavetracking_nws_v2().