WAVEWATCH III: ww3_gspl.F90 File Reference
ww3_gspl.F90 File Reference
Contains the grid splitting program.
Data Types
type stats_grid
type stats_mean
type part_grid
Functions/Subroutines
program w3gspl
Grid splitting program.
subroutine grinfo
Compile statistical info on all sub grids (no halo).
subroutine grtrim
Trim edges of all grids where they are next to another grid or next to unassigned grid points.
subroutine grfill (ND)
Reassign unassigned grid points to grids, starting with the smallest grids.
subroutine grlost
Reassign unassigned grid points to grids.
subroutine grsqrg
Attempt to square-up grid.
subroutine grsngl (OK)
Remove seapoints with only one adjacent point in same grid.
subroutine grsepa (OK, FRAC)
Remove smaller grid parts.
subroutine grfsml
Subroutine called when lowest grid size is stuck.
subroutine grflrg
Like GRFSML for largest grid ...
subroutine gr1grd
Extract single grid from master map.
Detailed Description
Contains the grid splitting program.
Author
H. L. Tolman
Date
18-Nov-2013
Definition in file ww3_gspl.F90.
Function/Subroutine Documentation
gr1grd()
subroutine w3gspl::gr1grd
Extract single grid from master map.
Extract single grid from master map, including halo needed for grid overlap in ww3_multi.
Author
H. L. Tolman
Date
18-Nov-2012
Definition at line 3084 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         18-Nov-2012 |
     !/                  +-----------------------------------+
     !/
     !/    23-Sep-2012 : Origination.                        ( version 4.10 )
     !/    24-Jan-2013 : Correct X0 to be in range.          ( version 4.10 )
     !/    04-Feb-2013 : Add corner point to halo.           ( version 4.10 )
     !/    18-Nov-2012 : Add user-defined halo extension.    ( version 4.14 )
     !/
     !  1. Purpose :
     !
     !     Extract single grid from master map, including halo needed for
     !     grid overlap in ww3_multi.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NIT, IIT,  IXL, IXH, IYL, IYH, NOCNT,&
          NOCNTM, NOCNTL, JX, JY, ISEA, MX, MY
     INTEGER                 :: MTMP2(NY,NX)
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     REAL                    :: XOFF
     LOGICAL                 :: MASK(NY,NX), LEFT, RIGHT, THERE
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GR1GRD')
 #endif
     !
 #ifdef W3_T7
     WRITE (ndst,9000) ig
 #endif
     !
     ! 1.  Set up MTEMP with MAPSTA 0,1,3 for grid ------------------------ *
     !
     DO ix=1, nx
       DO iy=1, ny
         IF ( msplit(iy,ix) .EQ. ig ) THEN
           mtemp(iy,ix) = 1
         ELSE IF ( msplit(iy,ix) .GT. 0 ) THEN
           mtemp(iy,ix) = 3
         ELSE
           mtemp(iy,ix) = 0
         END IF
       END DO
     END DO
     !
     ! 2.  Add ALL MAPSTA = 2 points to grid ------------------------------ *
     !
     DO ix=1, nx
       DO iy=1, ny
         IF ( mapsta(iy,ix) .EQ. 2 ) THEN
           mtemp(iy,ix) = 2
         END IF
       END DO
     END DO
     !
     ! 3.  Add halo ------------------------------------------------------- *
     ! 3.a Set up halo width depending on scheme and time steps
     !     NEEDED TO SET UP A LITTLE WIDER. NOT SURE WHY. NEED TO CHECK WITH
     !     WMEQL SUBROUTINE.
     !
 #ifdef W3_PR0
     nit    = 0
 #endif
 #ifdef W3_PR1
     nit    = 1 + nhext + ( 1 + int(dtmax/dtcfl-0.001) ) * 1
 #endif
 #ifdef W3_UQ
     nit    = 1 + nhext + ( 1 + int(dtmax/dtcfl-0.001) ) * 3
 #endif
 #ifdef W3_UNO
     nit    = 1 + nhext + ( 1 + int(dtmax/dtcfl-0.001) ) * 3
 #endif
     !
     ! 3.b Exand halo
     !
     DO iit=1, nit
       !
       mask   = .false.
       !
       DO ix=1, nx
         ixl    = 1 + mod(ix-2+nx,nx)
         ixh    = 1 + mod(ix,nx)
         DO iy=2, ny-1
           IF ( mtemp(iy,ix) .EQ. 3 ) mask(iy,ix) =                  &
                ( ( mtemp(iy+1,ix ) .EQ. 1 ) .OR.       &
                ( mtemp(iy-1,ix ) .EQ. 1 ) .OR.       &
                ( mtemp(iy  ,ixh) .EQ. 1 ) .OR.       &
                ( mtemp(iy  ,ixl) .EQ. 1 ) )          &
                .OR.    (   ( mtemp(iy+1,ixl) .EQ. 1 ) .AND.      &
                ( ( mtemp(iy  ,ixl) .EQ. 1 ) .OR.       &
                ( mtemp(iy+1,ix ) .EQ. 1 ) ) )        &
                .OR.    (   ( mtemp(iy+1,ixh) .EQ. 1 ) .AND.      &
                ( ( mtemp(iy  ,ixh) .EQ. 1 ) .OR.       &
                ( mtemp(iy+1,ix ) .EQ. 1 ) ) )        &
                .OR.    (   ( mtemp(iy-1,ixh) .EQ. 1 ) .AND.      &
                ( ( mtemp(iy  ,ixh) .EQ. 1 ) .OR.       &
                ( mtemp(iy-1,ix ) .EQ. 1 ) ) )        &
                .OR.    (   ( mtemp(iy-1,ixl) .EQ. 1 ) .AND.      &
                ( ( mtemp(iy  ,ixl) .EQ. 1 ) .OR.       &
                ( mtemp(iy-1,ix ) .EQ. 1 ) ) )
         END DO
       END DO
       !
       DO ix=1, nx
         DO iy=1, ny
           IF ( mask(iy,ix) ) mtemp(iy,ix) = 1
         END DO
       END DO
       !
     END DO
     !
     ! 3.c Contract halo
     !
     !     MTMP2 = MTEMP
     !
     !     DO IIT=1, NIT
     !
     !       MASK   = .FALSE.
     !
     !       DO IX=1, NX
     !         IXL    = 1 + MOD(IX-2+NX,NX)
     !         IXH    = 1 + MOD(IX,NX)
     !         DO IY=2, NY-1
     !           IF ( MTMP2(IY,IX) .EQ. 1 ) MASK(IY,IX) =                  &
     !                             ( ( MTMP2(IY+1,IX ) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY-1,IX ) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY  ,IXH) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY  ,IXL) .EQ. 3 ) )          &
     !                   .OR.    (   ( MTMP2(IY+1,IXL) .EQ. 3 ) .AND.      &
     !                             ( ( MTMP2(IY  ,IXL) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY+1,IX ) .EQ. 3 ) ) )        &
     !                   .OR.    (   ( MTMP2(IY+1,IXH) .EQ. 3 ) .AND.      &
     !                             ( ( MTMP2(IY  ,IXH) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY+1,IX ) .EQ. 3 ) ) )        &
     !                   .OR.    (   ( MTMP2(IY-1,IXH) .EQ. 3 ) .AND.      &
     !                             ( ( MTMP2(IY  ,IXH) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY-1,IX ) .EQ. 3 ) ) )        &
     !                   .OR.    (   ( MTMP2(IY-1,IXL) .EQ. 3 ) .AND.      &
     !                             ( ( MTMP2(IY  ,IXL) .EQ. 3 ) .OR.       &
     !                               ( MTMP2(IY-1,IX ) .EQ. 3 ) ) )
     !           END DO
     !         END DO
     !
     !       DO IX=1, NX
     !         DO IY=1, NY
     !           IF ( MASK(IY,IX) ) MTMP2(IY,IX) = 3
     !           END DO
     !         END DO
     !
     !       END DO
     !
     ! 3.d Check if consistent .....
     !
     !     DO IX=1, NX
     !       DO IY=1, NY
     !         IF ( MSPLIT(IY,IX).EQ.IG .OR. MTMP2(IY,IX).EQ.1 ) THEN
     !             IF ( MSPLIT(IY,IX).EQ.IG .AND. MTMP2(IY,IX).NE.1 ) THEN
     !                 write (ndst,*) ix, iy, '  in grid, not in e-c grid'
     !               END IF
     !             IF ( MSPLIT(IY,IX).NE.IG .AND. MTMP2(IY,IX).EQ.1 ) THEN
     !                 write (ndst,*) ix, iy, '  in e-c grid, not in grid'
     !               END IF
     !           END IF
     !         END DO
     !       END DO
     !
     ! 4.  Remove extraeneous MAPSTA = 2 ---------------------------------- *
     !
     DO ix=1, nx
       !
       IF ( global ) THEN
         ixl    = 1 + mod(ix-2+nx,nx)
         ixh    = 1 + mod(ix,nx)
       ELSE
         ixl    = max( 1 , ix-1 )
         ixh    = min( nx , ix+1 )
       END IF
       !
       DO iy=1, ny
         IF ( mtemp(iy,ix) .EQ. 2 ) THEN
           iyl    = max( 1 , iy-1 )
           iyh    = min( ny , iy+1 )
           IF ( .NOT. ( ( mtemp(iyl,ix ) .EQ. 1 ) .OR.             &
                ( mtemp(iyh,ix ) .EQ. 1 ) .OR.             &
                ( mtemp(iy ,ixl) .EQ. 1 ) .OR.             &
                ( mtemp(iy ,ixh) .EQ. 1 ) ) )              &
                mtemp(iy,ix) = 3
         END IF
       END DO
       !
     END DO
     !
 #ifdef W3_T7
     WRITE (ndst,9040)
 #endif
     !
     ! 5.  Recompute grid range ------------------------------------------- *
     !     Using GSTOLD to store info for modified grid
     !
 #ifdef W3_T7
     WRITE (ndst,9050) gstats(ig)%STRADLE, gstats(ig)%NPTS,          &
          gstats(ig)%NXL, gstats(ig)%NXH,               &
          gstats(ig)%NYL, gstats(ig)%NYH
 #endif
     !
     gstold(ig)%STRADLE = .false.
     gstold(ig)%NPTS    = 0
     gstold(ig)%NXL     = nx
     gstold(ig)%NXH     = 1
     gstold(ig)%NYL     = ny
     gstold(ig)%NYH     = 1
     !
     IF ( global ) THEN
       !
       left   = .false.
       right  = .false.
       !
       DO iy=1, ny
         IF ( mtemp(iy, 1).EQ.1 .OR.  mtemp(iy, 1).EQ.2 ) left   = .true.
         IF ( mtemp(iy,nx).EQ.1 .OR.  mtemp(iy,nx).EQ.2 ) right  = .true.
       END DO
       gstold(ig)%STRADLE = left .AND. right
       !
     END IF
     !
     DO iy=1, ny
       DO ix=1, nx
         IF ( mtemp(iy,ix).EQ.1 .OR.  mtemp(iy,ix).EQ.2 ) THEN
           gstold(ig)%NPTS = gstold(ig)%NPTS + 1
           gstold(ig)%NXL  = min( gstold(ig)%NXL , ix )
           gstold(ig)%NXH  = max( gstold(ig)%NXH , ix )
           gstold(ig)%NYL  = min( gstold(ig)%NYL , iy )
           gstold(ig)%NYH  = max( gstold(ig)%NYH , iy )
         END IF
       END DO
     END DO
     !
     IF ( gstold(ig)%STRADLE ) THEN
       nocnt  = 0
       nocntm = 0
       nocntl = 0
       DO ix=1, nx
         there  = .false.
         DO iy=1, ny
           IF ( mtemp(iy,ix).EQ.1 .OR.  mtemp(iy,ix).EQ.2 ) THEN
             there  = .true.
             EXIT
           END IF
         END DO
         IF ( there ) THEN
           nocnt = 0
         ELSE
           nocnt = nocnt + 1
           IF ( nocnt .GT. nocntm ) THEN
             nocntm = nocnt
             nocntl = ix
           END IF
         END IF
       END DO
       gstold(ig)%NXL = nocntl + 1
       gstold(ig)%NXH = nocntl - nocntm
     END IF
     !
     ! ... Make sure outside of grid is 2 or 3
     !
 #ifdef W3_T7
     WRITE (ndst,9051) gstold(ig)%STRADLE, gstold(ig)%NPTS,          &
          gstold(ig)%NXL, gstold(ig)%NXH,               &
          gstold(ig)%NYL, gstold(ig)%NYH
 #endif
     left   = .false.
     right  = .false.
     !
     DO ix=1, nx
       left   = left  .OR. ( mtemp(gstold(ig)%NYL,ix) .EQ. 1 )
       right  = right .OR. ( mtemp(gstold(ig)%NYH,ix) .EQ. 1 )
     END DO
     !
     IF ( left  ) gstold(ig)%NYL = gstold(ig)%NYL - 1
     IF ( right ) gstold(ig)%NYH = gstold(ig)%NYH + 1
     !
     DO iy=1, ny
       left   = left  .OR. ( mtemp(iy,gstold(ig)%NXL) .EQ. 1 )
       right  = right .OR. ( mtemp(iy,gstold(ig)%NXH) .EQ. 1 )
     END DO
     !
     IF ( left  ) gstold(ig)%NXL = gstold(ig)%NXL - 1
     IF ( right ) gstold(ig)%NXH = gstold(ig)%NXH + 1
     !
     IF ( global .AND. gstold(ig)%NXL.EQ.0 ) THEN
       gstold(ig)%NXL     = nx
       gstold(ig)%STRADLE = .true.
     END IF
     !
     IF ( global .AND. gstold(ig)%NXH.EQ.nx+1 ) THEN
       gstold(ig)%NXH     = 1
       gstold(ig)%STRADLE = .true.
     END IF
     !
 #ifdef W3_T7
     WRITE (ndst,9052) gstold(ig)%STRADLE, gstold(ig)%NPTS,          &
          gstold(ig)%NXL, gstold(ig)%NXH,               &
          gstold(ig)%NYL, gstold(ig)%NYH
 #endif
     !
     ! 6.  Extract reduced grid data -------------------------------------- *
     !
     my             = 1 + gstold(ig)%NYH - gstold(ig)%NYL
     mx             = 1 + gstold(ig)%NXH - gstold(ig)%NXL
     IF ( gstold(ig)%STRADLE ) mx = mx + nx
     pgrid(ig)%NY   = my
     pgrid(ig)%NX   = mx
     pgrid(ig)%NSEA = gstold(ig)%NPTS
     pgrid(ig)%X0   = x0 + real(gstold(ig)%NXL-1)*sx
     pgrid(ig)%Y0   = y0 + real(gstold(ig)%NYL-1)*sy
     pgrid(ig)%SX   = sx
     pgrid(ig)%SY   = sy
     !
     xoff   = 360. * real( nint((pgrid(ig)%X0+0.5*real(mx-1)*sx)/360.) )
     pgrid(ig)%X0   = pgrid(ig)%X0 - xoff
     !
 #ifdef W3_T7
     WRITE (ndst,9060) pgrid(ig)%NX, pgrid(ig)%NY, pgrid(ig)%NSEA,   &
          pgrid(ig)%X0, pgrid(ig)%Y0, pgrid(ig)%SX, pgrid(ig)%SY
 #endif
     !
     ALLOCATE ( pgrid(ig)%ZBIN(mx,my) ,          &
          pgrid(ig)%OBSX(mx,my) ,          &
          pgrid(ig)%OBSY(mx,my) ,          &
          pgrid(ig)%MASK(mx,my) )
     !
     pgrid(ig)%ZBIN   = zbdum
     pgrid(ig)%OBSX   = 0.
     pgrid(ig)%OBSY   = 0.
     pgrid(ig)%MASK   = 99
     !
     DO ix=1, pgrid(ig)%NX
       jx     = 1 + mod( ix+gstold(ig)%NXL-2 , nx )
       DO iy=1, pgrid(ig)%NY
         jy     = iy + gstold(ig)%NYL - 1
         isea   = mapfs(jy,jx)
         IF ( mtemp(jy,jx) .NE. 0 ) THEN
           pgrid(ig)%ZBIN(ix,iy) = zb(isea)
         END IF
         IF ( trflag .NE. 0 ) THEN
           pgrid(ig)%OBSX(ix,iy) = 1. - trnx(jy,jx)
           pgrid(ig)%OBSY(ix,iy) = 1. - trny(jy,jx)
         END IF
         pgrid(ig)%MASK(ix,iy) = mtemp(jy,jx)
       END DO
     END DO
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T7
 9000 FORMAT ( 'TEST GR1GRD: EXTRACTING GRID:',i4)
 9040 FORMAT ( '             MASK ON FULL GRID COMPUTED')
 9050 FORMAT ( 'TEST GR1GRD: GRID STATS :'/                           &
          '             GRID MAP     :',l2,2x,i8,4i5)
 9051 FORMAT ( '             HALO ADDED   :',l2,2x,i8,4i5)
 9052 FORMAT ( '             BORDER ADDED :',l2,2x,i8,4i5)
 9060 FORMAT ( 'TEST GR1GRD: EXTRACTED GRID :',2i5,i8/                &
          '                             ',4e12.5)
 #endif
     !
     !/ End of GR1GRD ----------------------------------------------------- /
     !/
grfill()
subroutine w3gspl::grfill (integer, intent(in) ND)
Reassign unassigned grid points to grids, starting with the smallest grids.
Parameters
[in] ND Depth of halo for first sweep.
Author
H. L. Tolman
Date
01-Feb-2013
Definition at line 1652 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Feb-2013 |
     !/                  +-----------------------------------+
     !/
     !/    07-Sep-2012 : Origination.                        ( version 4.10 )
     !/    18-Sep-2012 : Include edge points of grid.        ( version 4.10 )
     !/                  Add convergence check.
     !/    29-Jan-2013 : Add error code on stop.             ( version 4.10 )
     !/    29-Jan-2013 : Add error test output.              ( version 4.10 )
     !/    01-Feb-2013 : Loop over selected sea points only. ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Reassign unassigned grid points to grids, starting with the
     !     smallest grids.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       ND      Int.   I   Depth of halo for first sweep.
     !     ----------------------------------------------------------------
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: ND
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NMIN, I, NDEPTH, NITT, NADD, IXL, IXR,&
          NLEFT, NRIGHT, NXL, NXH, NYL, NYH
     INTEGER                 :: NXYOFF = 3
     INTEGER                 :: IIX(NSEA), IIY(NSEA), ISEA, NSEAL
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     LOGICAL                 :: DONE(NG), MASK(NY,NX), FLOST(NG),     &
          XFL(NX), YFL(NY)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRFILL')
 #endif
     !
     ! 1.  Loop to assure all reassigned ---------------------------------- *
     !
     ndepth = nd
     nitt   = 0
     nleft  = -1
     flost  = .false.
     !
     nseal  = 0
     DO ix=1, nx
       DO iy=1, ny
         IF ( msplit(iy,ix) .EQ. -1 ) THEN
           nseal  = nseal + 1
           iix(nseal) = ix
           iiy(nseal) = iy
         END IF
       END DO
     END DO
     !
     DO
       nitt   = nitt + 1
       !
       ! 2.  Loop over all grids -------------------------------------------- *
       !
       done   = .false.
       !
       DO j=1, ng
         !
         ! 3.  Find smallest unprocessed grid --------------------------------- *
         !
         nmin   = nsea + 1
         ig     = 0
         !
         DO i=1, ng
           IF ( .NOT.done(i) .AND. gstats(i)%NPTS.LT.nmin ) THEN
             ig     = i
             nmin   = gstats(i)%NPTS
           END IF
         END DO
         !
         done(ig) = .true.
         !
 #ifdef W3_T2
         WRITE (ndst,9030) ig, j, nmin
 #endif
         !
         ! 4.  Loop for halos per grid ---------------------------------------- *
         !
         DO, i=1, ndepth
           !
           mask   = .false.
           !
           ! 5.  Mark grid point for adding ------------------------------------- *
           !
           DO isea=1, nseal
             ix     = iix(isea)
             iy     = iiy(isea)
             ixl    = 1 + mod(ix-2+nx,nx)
             ixr    = 1 + mod(ix,nx)
             IF ( msplit(iy,ix) .EQ. -1 ) mask(iy,ix) =              &
                  ( msplit(iy+1,ix ) .EQ. ig )    &
                  .OR.  ( msplit(iy-1,ix ) .EQ. ig )    &
                  .OR.  ( msplit(iy  ,ixr) .EQ. ig )    &
                  .OR.  ( msplit(iy  ,ixl) .EQ. ig )
           END DO
           !
           ! 6.  Add marked grid point ------------------------------------------ *
           !
           nadd   = 0
           !
           DO isea=1, nseal
             ix     = iix(isea)
             iy     = iiy(isea)
             IF ( mask(iy,ix) ) THEN
               msplit(iy,ix) = ig
               nadd          = nadd + 1
             END IF
           END DO
           !
           IF ( nadd .EQ. 0 ) EXIT
           !
           ! ... End loop started in 4.
           !
         END DO
         !
         ! ... End loop started in 2.
         !
       END DO
       !
       ndepth = 1
       !
       ! 7.  Check convergence ---------------------------------------------- *
       ! 7.a Find number of points left
       !
       nright = nleft
       nleft  = 0
       !
       DO isea=1, nseal
         ix     = iix(isea)
         iy     = iiy(isea)
         IF ( msplit(iy,ix) .EQ. -1 ) nleft = nleft + 1
       END DO
       !
 #ifdef W3_T2
       WRITE (ndst,9070) nitt, nleft
 #endif
       !
       ! 7.b No point left, exit loop
       !
       IF ( nleft .EQ. 0 ) EXIT
       !
       ! 7.c Stuck with points left
       !
       IF ( nright .GT. 0 ) THEN
         IF ( nleft .EQ. nright ) THEN
           !
           ! 7.d Do lost point correction once
           !
           IF ( .NOT. flost(ig) ) THEN
             CALL grlost
             flost(ig) = .true.
           ELSE
             !
             ! 7.e Got stuck for good, error message and ouput
             !
             WRITE (ndse,1000) ig, nitt, nleft
             !
             xfl    = .false.
             yfl    = .false.
             !
             DO isea=1, nseal
               ix     = iix(isea)
               iy     = iiy(isea)
               IF ( msplit(iy,ix) .EQ. -1 ) THEN
                 xfl(max(1,ix-nxyoff):min(nx,ix+nxyoff)) = .true.
                 yfl(max(1,iy-nxyoff):min(ny,iy+nxyoff)) = .true.
               END IF
             END DO
             !
             nxl   = 0
             nxh   = 0
             DO ix=1, nx
               IF ( xfl(ix) .AND. nxl.EQ. 0 ) nxl = ix
               IF ( xfl(ix) .AND. ix.EQ. nx ) nxh = ix
               IF ( .NOT. xfl(ix) .AND. nxl.NE. 0 ) nxh = ix-1
               IF ( nxh .NE. 0 ) THEN
                 nyl   = 0
                 nyh   = 0
                 DO iy=1, ny
                   IF ( yfl(iy) .AND. nyl.EQ. 0 ) nyl = iy
                   IF ( yfl(iy) .AND. iy.EQ. ny ) nyh = iy
                   IF ( .NOT. yfl(iy) .AND. nyl.NE. 0 )      &
                        nyh = iy-1
                   IF ( nyh .NE. 0 ) THEN
                     WRITE (ndst,1001) nxl, nxh, nyh, nyl
                     DO i=nyh, nyl, -1
                       WRITE (ndst,1002) msplit(i,nxl:nxh)
                     END DO
                     nyl    = 0
                     nyh    = 0
                   END IF
                 END DO
                 nxl   = 0
                 nxh   = 0
               END IF
             END DO
             !
             ! ... Stop program with error output ...
             !
             stop 01
           ENDIF
           !
         END IF
       END IF
       !
       ! ... End loop started in 1.
       !
     END DO
     !
     RETURN
     !
     ! Formats
     !
 1000 FORMAT (/' *** ERROR GRFILL : NO MORE CONVERGENCE, ',           &
          'NITT, NLEFT:',2i8,' ***'/)
 1001 FORMAT ( ' MAP OUTPUT FOR GRID',i3,' AND X AND Y RANGE :',4i6/)
 1002 FORMAT ( ' ',60i2)
     !
 #ifdef W3_T2
 9030 FORMAT ( 'TEST GRFILL: PROCESSING GRID',i5,'   (',i5,')',i8)
 9060 FORMAT ( 'TEST GRFILL: GRID, HALO, NADD :',i5,i2,i8)
 9070 FORMAT ( 'TEST GRFILL: NITT, NLEFT :',2i6)
 #endif
     !
     !/ End of GRFILL ----------------------------------------------------- /
     !/
References grlost().
grflrg()
subroutine w3gspl::grflrg
Like GRFSML for largest grid ...
Author
H. L. Tolman
Date
29-Jan-2013
Definition at line 2925 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         29-Jan-2013 |
     !/                  +-----------------------------------+
     !/
     !/    19-Sep-2012 : Origination.                        ( version 4.10 )
     !/    29-Jan-2013 : Add error code on stop.             ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Like GRFSML for largest grid ...
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NBIG, IGMAX(NG), NNEXT, JG
 !!!      INTEGER                 :: NSMALL, IGMIN(NG), NNEXT, JG, IGADD, &
 !!!                                 IGTEST, FREE(NG), NFREE, NBIG, IGB,  &
 !!!                                 MX, MY, NX0, NXN, NY0, NYN
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     CHARACTER(LEN=1)        :: NEXTTO(0:NG,0:NG), TEMP(NG)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRFLRG')
 #endif
     !
     ! 1.  Find big(s) ---------------------------------------------------- *
     !
     nbig   = 0
     igmax  = 0
     !
     DO ig=1,ng
       IF ( gstats(ig)%INSTAT .AND.                                  &
            gstats(ig)%NPTS .EQ. mstats%NMAX ) THEN
         nbig   = nbig + 1
         igmax(nbig)  = ig
       END IF
     END DO
     !
 #ifdef W3_T6
     WRITE (ndst,9010) nbig, igmax(:nbig)
 #endif
     !
     ! 2.  Find neighbours ------------------------------------------------ *
     !
     nextto = '.'
     !
     DO ix=1, nx-1
       DO iy=1, ny-1
         nextto(msplit(iy  ,ix  ),msplit(iy+1,ix  )) = 'X'
         nextto(msplit(iy+1,ix  ),msplit(iy  ,ix  )) = 'X'
         nextto(msplit(iy  ,ix+1),msplit(iy  ,ix  )) = 'X'
         nextto(msplit(iy  ,ix  ),msplit(iy  ,ix+1)) = 'X'
       END DO
     END DO
     !
     IF ( global ) THEN
       DO iy=1, ny-1
         nextto(msplit(iy  ,nx),msplit(iy+1,nx)) = 'X'
         nextto(msplit(iy+1,nx),msplit(iy  ,nx)) = 'X'
         nextto(msplit(iy  , 1),msplit(iy  ,nx)) = 'X'
         nextto(msplit(iy  ,nx),msplit(iy  , 1)) = 'X'
       END DO
     END IF
     !
     DO ig=0,ng
       nextto(ig,ig) = '-'
     END DO
     !
 #ifdef W3_T6
     WRITE (ndst,9020)
     DO ig=1, ng
       temp   = nextto(ig,1:)
       WRITE (ndst,9021) ig, temp
     END DO
 #endif
     !
     ! 3.  Loop over big grids -------------------------------------------- *
     !
     DO j=1, nbig
       !
 #ifdef W3_T6
       WRITE (ndst,9030) igmax(j)
 #endif
       !
       ! 3.a Find neighbours
       !
       ig     = igmax(j)
       nnext  = 0
       DO jg=1, ng
         IF ( nextto(ig,jg) .EQ. 'X' ) nnext  = nnext + 1
       END DO
       !
 #ifdef W3_T6
       WRITE (ndst,9031) nnext
 #endif
       !
       ! 3.b Enough neighbours found, mark as 'not to be processed further'
       !
       IF ( nnext .GE. 1 ) THEN
         gstats(ig)%INSTAT = .false.
 #ifdef W3_T6
         WRITE (ndst,9032)
 #endif
       ELSE
         !
         ! 3.c Biggest grid is isolated, should split
         !
         WRITE (ndse,930)
         stop 11
         !
       END IF
       !
     END DO
     !
     RETURN
     !
     ! Formats
     !
 930 FORMAT ( ' *** ERROR GRFLRG: LARGEST GRID IS ISOLATED ***'      &
          '     SPLITTING NOT YET IMPLEMENTED '/)
     !
 #ifdef W3_T6
 9010 FORMAT ( 'TEST GRFLRG:',i2,' BIG GRIDS:',10i4)
 9020 FORMAT ( 'TEST GRFLRG: NEIGHBOUR MAP PER GRID')
 9021 FORMAT (2x,i3,2x,120a1)
 9030 FORMAT ( 'TEST GRFLRG: PROCESSING BIG GRID',i4)
 9031 FORMAT ( '             GRID HAS',i3,' NEIGHBOURS')
 9032 FORMAT ( '             NO ACTION')
 #endif
     !
     !/ End of GRFLRG ----------------------------------------------------- /
     !/
grfsml()
subroutine w3gspl::grfsml
Subroutine called when lowest grid size is stuck.
Attempting to join to neighbor grid, otherwise mark as a accepted small grid. note that a small grid does not influence parallel scaling like a big grid does .....
Author
H. L. Tolman
Date
04-Feb-2013
Definition at line 2639 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         04-Feb-2013 |
     !/                  +-----------------------------------+
     !/
     !/    13-Sep-2012 : Origination.                        ( version 4.10 )
     !/    04-Feb-2013 : Bug fix grid splitting.             ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Subroutine called when lowest grid size is stuck. Attempting to
     !     joint to neighbor grid, otherwise mark as accepted small grid.
     !     note that small grid does not influence parallel scaling like a
     !     big grid does .....
     !
     !     1-Feb-2013: Also used for early small-grid merging.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NSMALL, IGMIN(NG), NNEXT, JG, IGADD, &
          IGTEST, FREE(NG), NFREE, NBIG, IGB,  &
          MX, MY, NX0, NXN, NY0, NYN, JX
 #ifdef W3_T5
     INTEGER                 :: NXNT
 #endif
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     CHARACTER(LEN=1)        :: NEXTTO(0:NG,0:NG), TEMP(NG)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRFSML')
 #endif
     !
     ! 1.  Find small(s) -------------------------------------------------- *
     !
     nsmall = 0
     igmin  = 0
     !
     DO ig=1,ng
       IF ( gstats(ig)%INSTAT .AND.                                  &
            gstats(ig)%NPTS .EQ. mstats%NMIN ) THEN
         nsmall = nsmall + 1
         igmin(nsmall)  = ig
       END IF
     END DO
     !
 #ifdef W3_T5
     WRITE (ndst,9010) nsmall, igmin(:nsmall)
 #endif
     !
     ! 2.  Find neighbours ------------------------------------------------ *
     !
     nextto = '.'
     !
     DO ix=1, nx-1
       DO iy=1, ny-1
         nextto(msplit(iy  ,ix  ),msplit(iy+1,ix  )) = 'X'
         nextto(msplit(iy+1,ix  ),msplit(iy  ,ix  )) = 'X'
         nextto(msplit(iy  ,ix+1),msplit(iy  ,ix  )) = 'X'
         nextto(msplit(iy  ,ix  ),msplit(iy  ,ix+1)) = 'X'
       END DO
     END DO
     !
     IF ( global ) THEN
       DO iy=1, ny-1
         nextto(msplit(iy  ,nx),msplit(iy+1,nx)) = 'X'
         nextto(msplit(iy+1,nx),msplit(iy  ,nx)) = 'X'
         nextto(msplit(iy  , 1),msplit(iy  ,nx)) = 'X'
         nextto(msplit(iy  ,nx),msplit(iy  , 1)) = 'X'
       END DO
     END IF
     !
     DO ig=0,ng
       nextto(ig,ig) = '-'
     END DO
     !
 #ifdef W3_T5
     WRITE (ndst,9020)
     DO ig=1, ng
       temp   = nextto(ig,1:)
       WRITE (ndst,9021) ig, temp
     END DO
 #endif
     !
     ! 3.  Loop over small grids ------------------------------------------ *
     !
     free   = 0
     nfree  = 0
     !
     DO j=1, nsmall
       !
 #ifdef W3_T5
       WRITE (ndst,9030) igmin(j)
 #endif
       !
       ! 3.a Find neighbours
       !
       ig     = igmin(j)
       igadd   = 0
       igtest  = nsea + 1
       nnext  = 0
       DO jg=1, ng
         IF ( nextto(ig,jg) .EQ. 'X' ) THEN
           nnext  = nnext + 1
           IF ( gstats(jg)%NPTS .LT. igtest ) THEN
             igtest = gstats(jg)%NPTS
             igadd  = jg
           END IF
         END IF
       END DO
       !
 #ifdef W3_T5
       WRITE (ndst,9031) nnext
 #endif
       !
       ! 3.b No neighbours found, mark as 'not to be processed further'
       !
       IF ( nnext .EQ. 0 ) THEN
         gstats(ig)%INSTAT = .false.
 #ifdef W3_T5
         WRITE (ndst,9032) ig
 #endif
       ELSE
         !
         ! 3.c Check smallest neighbor
         !
 #ifdef W3_T5
         WRITE (ndst,9033) igadd, igtest, igtest+ingmin, nint(xmean)
 #endif
         !
         IF ( igtest + ingmin .LT. nint(xmean) ) THEN
           !
           ! ... Merge grids
           !
           DO ix=1, nx
             DO iy=1, ny
               IF ( msplit(iy,ix) .EQ. ig ) msplit(iy,ix) = igadd
             END DO
           END DO
           !
           nfree  = nfree + 1
           free(nfree) = ig
           !
         ELSE
           !
           ! ... Remove grid(s) from stats
           !
 #ifdef W3_T5
           WRITE (ndst,9034)
 #endif
           !
           gstats(ig)%INSTAT = .false.
 #ifdef W3_T5
           WRITE (ndst,9032) ig
 #endif
           nnext  = 0
           DO jg=1, ng
             IF ( nextto(igadd,jg) .EQ. 'X' ) nnext  = nnext + 1
           END DO
           IF ( nnext .EQ. 1 ) THEN
             gstats(igadd)%INSTAT = .false.
 #ifdef W3_T5
             WRITE (ndst,9032) igadd
 #endif
           END IF
           !
         END IF
         !
       END IF
       !
     END DO
     !
     ! 4.  Make new grids as needed --------------------------------------- *
     !
 #ifdef W3_T5
     WRITE (ndst,9040) nfree
 #endif
     !
     DO j=1, nfree
       !
 #ifdef W3_T5
       WRITE (ndst,9041) free(j)
 #endif
       !
       ! 4.a Find biggest grid
       !
       nbig   = 0
       igb    = 0
       !
       DO ig=1, ng
         IF ( gstats(ig)%NPTS .GT. nbig ) THEN
           nbig   = gstats(ig)%NPTS
           igb    = ig
         END IF
       END DO
       !
       ! 4.a Split biggest grid
       !
       nx0    = gstats(igb)%NXL
       nxn    = gstats(igb)%NXH
       ny0    = gstats(igb)%NYL
       nyn    = gstats(igb)%NYH
       !
       my     = 1 + gstats(igb)%NYH - gstats(igb)%NYL
       mx     = 1 + gstats(igb)%NXH - gstats(igb)%NXL
       IF ( gstats(igb)%STRADLE ) mx     = mx + nx
       !
       IF ( my .GE. mx ) THEN
 #ifdef W3_T5
         WRITE (ndst,9042) igb, 'VERTICAL', mx, my
 #endif
         nyn    = ny0 + my/2
       ELSE
 #ifdef W3_T5
         WRITE (ndst,9042) igb, 'HORIZONTAL', mx, my
 #endif
         nxn    = nx0 + mx/2
 #ifdef W3_T5
         nxnt   = 1 + mod(nxn-1,nx)
 #endif
       END IF
 #ifdef W3_T5
       WRITE (ndst,9043) gstats(igb)%NXL, gstats(igb)%NXH,       &
            gstats(igb)%NYL, gstats(igb)%NYH,       &
            gstats(igb)%STRADLE, nx0, nxn, ny0, nyn
 #endif
       !
       DO ix=nx0, nxn
         jx     = 1 + mod(ix-1,nx)
         DO iy=ny0, nyn
           IF ( msplit(iy,jx) .EQ. igb ) msplit(iy,jx) = free(j)
         END DO
       END DO
       !
       gstats(igb)%NPTS = 0
       gstats(free(j))%NPTS = 0
       !
     END DO
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T5
 9010 FORMAT ( 'TEST GRFSML:',i2,' SMALL GRIDS:',10i4)
 9020 FORMAT ( 'TEST GRFSML: NEIGHBOUR MAP PER GRID')
 9021 FORMAT (2x,i3,2x,120a1)
 9030 FORMAT ( 'TEST GRFSML: PROCESSING SMALL GRID',i4)
 9031 FORMAT ( '             GRID HAS',i3,' NEIGHBOURS')
 9032 FORMAT ( '             REMOVED GRID',i4,' FROM STATS')
 9033 FORMAT ( '             SMALLEST NEIGHBOUR AND SIZE',i4,i6/      &
          '             SIZE OF COMBINED GRIDS',i8,'  (',i8,')')
 9034 FORMAT ( '             GRIDS TOO LARGE TO MERGE')
 9040 FORMAT ( 'TEST GRFSML: GENERATING',i3,' NEW GRIDS')
 9041 FORMAT ( '             MAKING GRID NR.:',i4)
 9042 FORMAT ( '             SPLITTING GRID',i3,' ',a,', MX,MY:',2i6)
 9043 FORMAT ( '             OLD RANGE :',4i6,l4/                     &
          '             NEW RANGE :',4i6)
 #endif
     !
     !/ End of GRFSML ----------------------------------------------------- /
     !/
grinfo()
subroutine w3gspl::grinfo
Compile statistical info on all sub grids (no halo).
Author
H. L. Tolman
Date
13-Sep-2012
Definition at line 1302 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         13-Sep-2012 |
     !/                  +-----------------------------------+
     !/
     !/    06-Sep-2012 : Origination.                        ( version 4.10 )
     !/    13-Sep-2012 : Option to exclude grids from stats. ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Compile statistical info on all sub grids (no halo).
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NOCNT, NOCNTM, NOCNTL, NGC, NSEAC
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     REAL                    :: SUMSQR
     LOGICAL                 :: LEFT, RIGHT, THERE
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRINFO')
 #endif
     !
     ! 1.  Initialization ------------------------------------------------- *
     !
     gstats(:)%STRADLE = .false.
     gstats(:)%NPTS    = 0
     gstats(:)%NXL     = nx
     gstats(:)%NXH     = 1
     gstats(:)%NYL     = ny
     gstats(:)%NYH     = 1
     !
     ! 2.  Get STRADLE, NGC ----------------------------------------------- *
     !
     ngc    = 0
     !
     DO ig=1, ng
       left   = .false.
       right  = .false.
       IF ( gstats(ig)%INSTAT ) ngc = ngc + 1
       DO iy=1, ny
         IF ( msplit(iy, 1) .EQ. ig ) left   = .true.
         IF ( msplit(iy,nx) .EQ. ig ) right  = .true.
       END DO
       gstats(ig)%STRADLE = left .AND. right
     END DO
     !
     IF ( ngc .EQ. 0 ) THEN
       ngc    = 1
       done   = .true.
     END IF
     !
     ! 3.  Run grid stats ------------------------------------------------- *
     ! 3.a General
     !
     DO iy=1, ny
       DO ix=1, nx
         ig     = msplit(iy,ix)
         IF ( msplit(iy,ix) .GT. 0 ) THEN
           gstats(ig)%NPTS = gstats(ig)%NPTS + 1
           gstats(ig)%NXL  = min( gstats(ig)%NXL , ix )
           gstats(ig)%NXH  = max( gstats(ig)%NXH , ix )
           gstats(ig)%NYL  = min( gstats(ig)%NYL , iy )
           gstats(ig)%NYH  = max( gstats(ig)%NYH , iy )
         END IF
       END DO
     END DO
     !
     ! 3.b Stradled grids
     !
     IF ( ng .GT. 1) THEN
       DO ig=1, ng
         IF ( gstats(ig)%STRADLE ) THEN
           nocnt  = 0
           nocntm = 0
           nocntl = 0
           DO ix=1, nx
             there  = .false.
             DO iy=1, ny
               IF ( msplit(iy,ix) .EQ. ig ) THEN
                 there  = .true.
                 EXIT
               END IF
             END DO
             IF ( there ) THEN
               nocnt = 0
             ELSE
               nocnt = nocnt + 1
               IF ( nocnt .GT. nocntm ) THEN
                 nocntm = nocnt
                 nocntl = ix
               END IF
             END IF
           END DO
           gstats(ig)%NXL = nocntl + 1
           gstats(ig)%NXH = nocntl - nocntm
         END IF
       END DO
     ELSE
       gstats(1)%STRADLE = .false.
     END IF
     !
     ! 3.c Corrected NSEA
     !
     nseac   = 0
     !
     DO ig=1, ng
       IF ( gstats(ig)%INSTAT ) nseac = nseac + gstats(ig)%NPTS
     END DO
     !
     ! 4.  Run overall stats ---------------------------------------------- *
     !
     mstats%NMIN = nsea + 1
     mstats%NMAX = 0
     xmean  = real(nseac) / real(ngc)
     sumsqr = 0.
     !
     DO ig=1, ng
       IF ( .NOT. gstats(ig)%INSTAT ) cycle
       mstats%NMIN = min( mstats%NMIN , gstats(ig)%NPTS )
       mstats%NMAX = max( mstats%NMAX , gstats(ig)%NPTS )
       sumsqr      = sumsqr + ( real(gstats(ig)%NPTS) - xmean )**2
     END DO
     !
     mstats%RSTD = sqrt( sumsqr / real(ngc) )
     !
     ! 5.  Test output ---------------------------------------------------- *
     !
 #ifdef W3_T1
     WRITE (ndst,9000)
     DO ig=1, ng
       WRITE (ndst,9001) ig, gstats(ig)%STRADLE, gstats(ig)%NPTS, &
            gstats(ig)%NXL, gstats(ig)%NXH,      &
            gstats(ig)%NYL, gstats(ig)%NYH
     END DO
     WRITE (ndst,9010) mstats%NMIN, mstats%NMAX, mstats%RSTD
 #endif
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T1
 9000 FORMAT ( 'TEST GRINFO: J, STRADLE, NPTS,NXL-H, NYL-H')
 9001 FORMAT ( '           ',i4,2x,l1,2x,i7,4i5)
 9010 FORMAT ( 'TEST GRINFO: MIN, MAX, STD:',2i8,f10.2)
 #endif
     !
     !/ End of GRINFO ----------------------------------------------------- /
     !/
grlost()
subroutine w3gspl::grlost
Reassign unassigned grid points to grids.
Dealing with lost point by finding closest grids.
Author
H. L. Tolman
Date
09-Jan-2013
Definition at line 1913 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         .9-Jan-2013 |
     !/                  +-----------------------------------+
     !/
     !/    31-Jan-2013 : Origination.                        ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Reassign unassigned grid points to grids. Dealing with lost
     !     point by finding closest grids.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IX, IY, IOFF, JJX, JX, JY, IG, I
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     INTEGER                 :: IFOUND(-1:NG)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRLOST')
 #endif
     !
     ! 1.  Loop over all grid points -------------------------------------- *
     !
     DO ix=1, nx
       DO iy=1, ny
         !
         IF ( msplit(iy,ix) .EQ. -1 ) THEN
           !
           ! 2.  Find nearest grid(s) ------------------------------------------- *
           !
           ioff   = 1
           !
           DO
             !
             ifound = 0
             DO jjx=ix-ioff, ix+ioff
               IF ( global ) THEN
                 jx     = 1 + mod(jjx-1+2*nx,nx)
               ELSE
                 jx     = jjx
               END IF
               IF ( jx.LT.1 .OR. jx.GT.nx ) cycle
               DO jy=iy-ioff, iy+ioff
                 IF ( jy.LT.1 .OR. jy.GT.ny ) cycle
                 ifound(msplit(jy,jx)) = ifound(msplit(jy,jx)) + 1
               END DO
             END DO
             !
             ig     = 0
             DO i=1, ng
               IF ( ifound(i) .GT. 0 ) THEN
                 ig     = i
                 EXIT
               END IF
             END DO
             !
             IF ( ig .NE. 0 ) THEN
               msplit(iy,ix) = ig
               EXIT
             END IF
             !
             ioff   = ioff + 1
             IF ( ioff .GT. nx .AND. ioff.GT.ny ) EXIT
           END DO
           !
           ! ... End of loops and logic started in 1.
           !
         END IF
         !
       END DO
     END DO
     !
     RETURN
     !
     ! Formats
     !
     !/ End of GRLOST ----------------------------------------------------- /
     !/
Referenced by grfill().
grsepa()
subroutine w3gspl::grsepa (logical, intent(inout) OK, real, intent(in) FRAC)
Remove smaller grid parts.
Remove smaller parts of a grid that are separated from the main body, and that can be attached to other grids.
Parameters
[in,out] OK
[in] FRAC Fraction of average size used to remove grid part.
Author
H. L. Tolman
Date
01-Feb-2013
Definition at line 2294 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Feb-2013 |
     !/                  +-----------------------------------+
     !/
     !/    10-Sep-2012 : Origination.                        ( version 4.10 )
     !/    18-Sep-2012 : Include edge points of grid.        ( version 4.10 )
     !/    01-Feb-2013 : Much faster algorithms.             ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Remove smller parts of a grid that are separated from the main
     !     body, and that can be attached to other grids.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       OK      Log.  I/O  Flag for grid status, .F. if values of
     !                          -1 are left in MSPLIT.
     !       FRAC    Real   I   Fraction of average size used to remove grid
     !                          part.
     !     ----------------------------------------------------------------
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     REAL, INTENT(IN)        :: FRAC
     LOGICAL, INTENT(INOUT)  :: OK
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IPAVG, IPCHCK, ID, IPTOT, IX, IY,    &
          IXL, IYL, IDL, JX, JY, KY, IPT,      &
          IXH, IYH, I, J, K, L, IMIN, LMIN
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     INTEGER                 :: GMASK(NY,NX), IIX(NSEA), IIY(NSEA)
     INTEGER, ALLOCATABLE    :: PMAP(:), INGRD(:)
     LOGICAL                 :: PREV
     LOGICAL,ALLOCATABLE     :: FLNEXT(:), NEXTTO(:,:)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRSEPA')
 #endif
     !
     ipavg  = nint( real(nsea) / real(ng) )
     ipchck = nint( frac * real(nsea) / real(ng) )
     !
 #ifdef W3_T4
     WRITE (ndst,9000) ipavg, ipchck
 #endif
     !
     ! 1.  Loop over grids ------------------------------------------------ *
     !
     DO ig=1, ng
       !
       gmask  = 0
       id     = 0
       !
 #ifdef W3_T4
       WRITE (ndst,9010) ig
 #endif
       !
       ! 2.  Find all parts ------------------------------------------------- *
       ! 2.a First loop, partial parts
       !
       iptot  = 0
       !
       DO ix=1, nx
         !
         ixl    = 1 + mod(ix-2+nx,nx)
         prev   = .false.
         !
         DO iy=1, ny
           IF (msplit(iy,ix) .EQ. ig ) THEN
             iptot  = iptot + 1
             iix(iptot) = ix
             iiy(iptot) = iy
             IF ( .NOT. prev) THEN
               id     = id + 1
               prev   = .true.
             END IF
             gmask(iy,ix) = id
           ELSE IF ( prev ) THEN
             prev   = .false.
             idl    = 0
             DO jy=iy-1, 1, -1
               IF ( gmask(jy,ix) .EQ. 0 ) EXIT
               IF ( gmask(jy,ixl).NE.0 .AND. idl.EQ.0 )            &
                    idl = gmask(jy,ixl)
             END DO
             IF ( idl .NE. 0 ) THEN
               DO ky=jy+1, iy-1
                 IF ( gmask(ky,ix).EQ.id ) gmask(ky,ix) = idl
               END DO
               id     = id - 1
             END IF
             !
           END  IF
         END DO
       END DO
       !
       ! 2.b Grid too small, do not cut
       !
       IF ( iptot .LE. ipavg ) THEN
 #ifdef W3_T4
         WRITE (ndst,9020) iptot, ipavg
 #endif
         cycle
       END IF
       !
       ! 2.c Neighbouring grid parts
       !     Raw data
       !
       ALLOCATE ( nextto(0:id,0:id), pmap(0:id) )
       nextto = .false.
       !
       DO ipt=1, iptot
         ix     = iix(ipt)
         iy     = iiy(ipt)
         ixl    = 1 + mod(ix-2+nx,nx)
         iyl    = iy - 1
         ixh    = 1 + mod(ix,nx)
         iyh    = iy + 1
         nextto( gmask(iy,ix) , gmask(iy ,ixl) ) = .true.
         nextto( gmask(iy,ix) , gmask(iy ,ixh) ) = .true.
         nextto( gmask(iy,ix) , gmask(iyl,ix ) ) = .true.
         nextto( gmask(iy,ix) , gmask(iyh,ix ) ) = .true.
       END DO
       !
       !     Make symmetric
       !
       DO i=1, id
         DO j=1, id
           nextto(i,j) = nextto(i,j) .OR. nextto(j,i)
         END DO
       END DO
       !
       !     Connect accross neighbours
       !
       DO i=1, id
         DO j=1, id
           IF ( nextto(i,j) ) THEN
             DO k=1, id
               IF ( nextto(k,j) ) THEN
                 nextto(k,i) = .true.
                 nextto(i,k) = .true.
               END IF
             END DO
           END IF
         END DO
       END DO
       !
       !     Map the parts
       !
       idl    = id
       pmap   = 0
       id     = 0
       !
       DO i=1, idl
         IF ( pmap(i) .EQ. 0 ) THEN
           id     = id + 1
           DO j=1, idl
             IF ( nextto(j,i) ) EXIT
           END DO
           IF ( j .GT. idl ) THEN
             pmap(i) = id
           ELSE
             DO k=i, idl
               IF ( pmap(k).EQ.0 .AND. nextto(j,k) ) pmap(k) = id
             END DO
           END IF
         END IF
       END DO
       !
       DEALLOCATE ( nextto )
       !
       ! 3.  Grid is contiguous --------------------------------------------- *
       !
       IF ( id .EQ. 1 ) THEN
 #ifdef W3_T4
         WRITE (ndst,9030) ig
 #endif
         DEALLOCATE ( pmap )
         cycle
       END IF
       !
       ! 4.  Grid is split, get stats --------------------------------------- *
       !
 #ifdef W3_T4
       WRITE (ndst,9040) ig
 #endif
       !
       ! 4.a Construct final map for grid
       !
       DO ipt=1, iptot
         ix     = iix(ipt)
         iy     = iiy(ipt)
         gmask(iy,ix) = pmap(gmask(iy,ix))
       END DO
       !
       DEALLOCATE ( pmap )
       !
       ! 4.b Run stats
       !
       ALLOCATE ( ingrd(id), flnext(id) )
       ingrd  = 0
       flnext = .false.
       iptot  = 0
       !
       DO jx=1, nx
         DO jy=1, ny
           IF ( gmask(jy,jx) .GT. 0 ) THEN
             ingrd(gmask(jy,jx))  = ingrd(gmask(jy,jx)) + 1
             iptot                = iptot + 1
           END IF
         END DO
       END DO
       !
       DO jx=1, nx
         DO jy=1, ny-1
           IF ( ( gmask(jy  ,jx) .GT. 0 ) .AND.                      &
                ( sea(jy+1,jx) .AND. msplit(jy+1,jx).NE.ig ) )       &
                flnext(gmask(jy  ,jx)) = .true.
           IF ( ( gmask(jy+1,jx) .GT. 0 ) .AND.                      &
                ( sea(jy  ,jx) .AND. msplit(jy  ,jx).NE.ig ) )       &
                flnext(gmask(jy+1,jx)) = .true.
         END DO
       END DO
       !
       DO jy=1, ny
         DO jx=1, nx-1
           IF ( ( gmask(jy,jx  ) .GT. 0 ) .AND.                      &
                ( sea(jy,jx+1) .AND. msplit(jy,jx+1).NE.ig ) )       &
                flnext(gmask(jy,jx  )) = .true.
           IF ( ( gmask(jy,jx+1) .GT. 0 ) .AND.                      &
                ( sea(jy,jx  ) .AND. msplit(jy,jx  ).NE.ig ) )       &
                flnext(gmask(jy,jx+1)) = .true.
         END DO
         IF ( global ) THEN
           IF ( ( gmask(jy,nx) .GT. 0 ) .AND.                      &
                ( sea(jy, 1) .AND. msplit(jy, 1).NE.ig ) )         &
                flnext(gmask(jy,nx)) = .true.
           IF ( ( gmask(jy, 1) .GT. 0 ) .AND.                      &
                ( sea(jy,nx) .AND. msplit(jy,nx).NE.ig ) )         &
                flnext(gmask(jy, 1)) = .true.
         END IF
       END DO
       !
 #ifdef W3_T4
       DO j=1, id
         WRITE (ndst,9041) j, ingrd(j), flnext(j)
       END DO
 #endif
       !
       ! 5.  Grid large enough, find smallest part -------------------------- *
       !
       imin   = nsea
       lmin   = 0
       !
       DO j=1, id
         IF ( flnext(j) .AND. ingrd(j).LT.imin ) THEN
           imin   = ingrd(j)
           lmin   = j
         END IF
       END DO
       !
       IF ( lmin .EQ. 0 ) THEN
 #ifdef W3_T4
         WRITE (ndst,9050)
 #endif
         DEALLOCATE ( ingrd, flnext )
         cycle
       END IF
       !
       IF ( imin .GT. ipchck ) THEN
 #ifdef W3_T4
         WRITE (ndst,9051)
 #endif
         DEALLOCATE ( ingrd, flnext )
         cycle
       END IF
       !
       ! 6.  Part to cut has been identified -------------------------------- *
       !
 #ifdef W3_T4
       WRITE (ndst,9060) lmin
 #endif
       !
       DO jx=1, nx
         DO jy=1, ny
           IF ( gmask(jy,jx) .EQ. lmin ) msplit(jy,jx) = -1
         END DO
       END DO
       !
       DEALLOCATE ( ingrd, flnext )
       ok     = .false.
       !
       ! ... End loops started in 1.
       !
     END DO
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T4
 9000 FORMAT ( 'TEST GRSEPA: IPAVG/CHCK:',2i8)
 9010 FORMAT ( 'TEST GRSEPA: WORKING ON GRID'i4)
 9020 FORMAT ( '             GRID TOO SMALL TO CUT',2i8)
 9030 FORMAT ( 'TEST GRSEPA: GRID',i4,' IS CONTIGUOUS')
 9040 FORMAT ( 'TEST GRSEPA: GRID',i4,' CONTAINS PARTS')
 9041 FORMAT ( '             PART, SIZE, NEIGHBOUR:',i4,i8,l4)
 9050 FORMAT ( '             NO PART NEXT TO OTHER')
 9051 FORMAT ( '             NO PART SMALL ENOUGH')
 9060 FORMAT ( '             CUTTING PART',i4)
 #endif
     !
     !/ End of GRSEPA ----------------------------------------------------- /
     !/
grsngl()
subroutine w3gspl::grsngl (logical, intent(inout) OK)
Remove seapoints with only one adjacent point in same grid.
Remove points from a grid that are in the middle of the sea, but that have only one adjacent point in the same grid. Directly select a new grid for this point rather than deactivate and use GRFILL.
Parameters
[in,out] OK Flag for grid status
Author
H. L. Tolman
Date
09-Sep-2012
Definition at line 2123 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         09-Sep-2012 |
     !/                  +-----------------------------------+
     !/
     !/    09-Sep-2012 : Origination.                        ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Remove points from a grid that are in the middle of the sea, but
     !     that have omly one adjacent point in the same grid. Directly
     !     select a new grid for this point rather than deactivate and use
     !     GRFILL.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       OK      Log.  I/O  Flag for grid status, .F. if values of
     !                          -1 are left in MSPLIT.
     !     ----------------------------------------------------------------
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     LOGICAL, INTENT(INOUT)  :: OK
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NX0, NXN, IXL, IXH, COUNT(-1:NG),    &
          INEW1, INEW2, INEW
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRSNGL')
 #endif
     !
     ! 1.  Set up looping ------------------------------------------------- *
     !
     IF ( global ) THEN
       nx0    =  1
       nxn    = nx
     ELSE
       nx0    =  2
       nxn    = nx-1
     END IF
     !
     ! 2.  Loops over 2D grid --------------------------------------------- *
     !
     DO ix=nx0, nxn
       !
       ixl    = ix - 1
       ixh    = ix + 1
       IF ( ix .EQ.  1 ) ixl = nx
       IF ( ix .EQ. nx ) ixh =  1
       !
       DO iy=2, ny-1
         !
         ! 3.  Central sea points only ---------------------------------------- *
         !
         IF ( sea(iy,ix) .AND. sea(iy-1,ix ) .AND. sea(iy+1,ix )      &
              .AND. sea(iy  ,ixl) .AND. sea(iy  ,ixh) ) THEN
           !
           ! 4.  Check for 'lost points' ---------------------------------------- *
           !
           count  = 0
           ig     = msplit(iy,ix)
           !
           count(ig) = 1
           count(msplit(iy-1,ix )) = count(msplit(iy-1,ix )) + 1
           count(msplit(iy+1,ix )) = count(msplit(iy+1,ix )) + 1
           count(msplit(iy  ,ixl)) = count(msplit(iy  ,ixl)) + 1
           count(msplit(iy  ,ixh)) = count(msplit(iy  ,ixh)) + 1
           !
           IF ( count(ig) .LE. 2 ) THEN
             !
 #ifdef W3_T3
             WRITE (ndst,9040) ix, iy, ig
 #endif
             !
             inew1  = -1
             inew2  = -1
             !
             DO j=1, ng
               IF ( count(j) .GE. 2 ) THEN
 #ifdef W3_T3
                 WRITE (ndst,9041) j
 #endif
                 IF ( inew1 .EQ. -1 ) THEN
                   inew1  = j
                 ELSE
                   inew2  = j
                   EXIT
                 END IF
               END IF
             END DO
             !
             IF ( inew1 .EQ. -1 ) THEN
               inew   = -1
               ok     = .false.
 #ifdef W3_T3
               WRITE (ndst,9043)
 #endif
             ELSE IF ( inew2 .EQ. -1 ) THEN
               inew   = inew1
 #ifdef W3_T3
               WRITE (ndst,9042) inew
 #endif
             ELSE
               IF ( gstats(inew1)%NPTS .GT.                     &
                    gstats(inew2)%NPTS ) THEN
                 inew   = inew2
               ELSE
                 inew   = inew1
               END IF
 #ifdef W3_T3
               WRITE (ndst,9042) inew
 #endif
             END IF
             !
             msplit(iy,ix) = inew
             !
           END IF
           !
         END IF
         !
         ! ... End loops started in 2.
         !
       END DO
       !
     END DO
     !
     RETURN
     !
     ! Formats
     !
 #ifdef W3_T3
 9040 FORMAT ( 'TEST GRSNGL: POINT FOUND, IX, IY, IG:',2i5,i4)
 9041 FORMAT ( '                     CANDIDATE GRID :',10x,i4)
 9042 FORMAT ( '                     GRID USED      :',10x,i4)
 9043 FORMAT ( '                     GRID LEFT UNDIFINED')
 #endif
     !
     !/ End of GRSNGL ----------------------------------------------------- /
     !/
grsqrg()
subroutine w3gspl::grsqrg
Attempt to square-up grid.
Attempt to square-up grid by taking off grid point in outermost grid point in X and Y only, after which GRFILL is to be run to re-assign grid points.
Author
H. L. Tolman
Date
07-Sep-2012
Definition at line 2017 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         07-Sep-2012 |
     !/                  +-----------------------------------+
     !/
     !/    07-Sep-2012 : Origination.                        ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Attemp to square-up grid by taking off grid point in outermost
     !     grid point in X and Y only, after which GRFILL is to be run to
     !     re-assign grid points,
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: MX, MY
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRSQRG')
 #endif
     !
     ! 1.  Loop over grids ------------------------------------------------ *
     !
     DO ig=1, ng
       !
       my     = 1 + gstats(ig)%NYH - gstats(ig)%NYL
       mx     = 1 + gstats(ig)%NXH - gstats(ig)%NXL
       IF ( gstats(ig)%STRADLE ) mx     = mx + nx
       !
       ! 2.  Top ------------------------------------------------------------ *
       !
       IF ( my .GE. 5 ) THEN
         !
         DO ix=1, nx
           IF (msplit(gstats(ig)%NYH,ix) .EQ. ig )                 &
                msplit(gstats(ig)%NYH,ix) = -1
         END DO
         !
         ! 3.  Bottom --------------------------------------------------------- *
         !
         DO ix=1, nx
           IF (msplit(gstats(ig)%NYL,ix) .EQ. ig )                 &
                msplit(gstats(ig)%NYL,ix) = -1
         END DO
         !
       END IF
       !
       ! 4.  Left ----------------------------------------------------------- *
       !
       IF ( mx .GE. 5 ) THEN
         !
         DO iy=gstats(ig)%NYL, gstats(ig)%NYH
           IF (msplit(iy,gstats(ig)%NXL) .EQ. ig )                 &
                msplit(iy,gstats(ig)%NXL) = -1
         END DO
         !
         ! 5.  Right ---------------------------------------------------------- *
         !
         DO iy=gstats(ig)%NYH, gstats(ig)%NYH
           IF (msplit(iy,gstats(ig)%NXH) .EQ. ig )                 &
                msplit(iy,gstats(ig)%NXH) = -1
         END DO
         !
       END IF
       !
       ! ... End loop started in 1.
       !
     END DO
     !
     RETURN
     !
     ! Formats
     !
     !/ End of GRSQRG ----------------------------------------------------- /
     !/
grtrim()
subroutine w3gspl::grtrim
Trim edges of all grids where they are next to another grid or next to unassigned grid points.
This trimming is done in preparation for reassigning edges of grids to smaller adjacent grids.
Author
H. L. Tolman
Date
01-Feb-2013
Definition at line 1480 of file ww3_gspl.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         01-Feb-2013 |
     !/                  +-----------------------------------+
     !/
     !/    07-Sep-2012 : Origination.                        ( version 4.10 )
     !/    18-Sep-2012 : Include edge points of grid.        ( version 4.10 )
     !/    01-Feb-2013 : Add dynamic trim range.             ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !    Trim edges of all grids where they are next to another grid or next
     !    to unassigned grid points. This is done in preparation for
     !    reassigning edges of grids to smaller adjacent grids.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: ITARG, ITL, IPTS, MX, MY, ICIRC, NWDTH
 #ifdef W3_S
     INTEGER, SAVE           :: IENT = 0
 #endif
     LOGICAL                 :: MASK(NY,NX)
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'GRTRIM')
 #endif
     !
     itarg  = nsea / ng
     !
     ! 1.  Loop over grids ------------------------------------------------ *
     !
     DO ig=1, ng
       !
       ipts   = gstats(ig)%NPTS
       my     = 1 + gstats(ig)%NYH - gstats(ig)%NYL
       mx     = 1 + gstats(ig)%NXH - gstats(ig)%NXL
       IF ( gstats(ig)%STRADLE ) mx     = mx + nx
       icirc  = 2 * ( mx + my )
       !
       nwdth  = 1
       !
       itl    = min( itarg , max( itarg-2*icirc , 3*icirc ) )
       IF ( ipts .LT. itl ) nwdth  = 0
       !
       IF ( ipts.GT.itarg ) THEN
         nwdth = 1 +                                              &
              max(0,+nint((real((ipts-itarg))/real(icirc)-1.)/3.))
       ENDIF
       !
       DO j=1, nwdth
         !
         mask   = .false.
         !
         ! 2.  Mark points to be removed -------------------------------------- *
         !
         DO ix=2, nx-1
           IF ( msplit( 1,ix) .EQ. ig ) mask( 1,ix) =                &
                (sea( 2,ix  ).AND.(msplit( 2,ix  ).NE.ig))       &
                .OR. (sea( 1,ix+1).AND.(msplit( 1,ix+1).NE.ig))       &
                .OR. (sea( 1,ix-1).AND.(msplit( 1,ix-1).NE.ig))
           DO iy=2, ny-1
             IF ( msplit(iy,ix) .EQ. ig ) mask(iy,ix) =              &
                  (sea(iy+1,ix  ).AND.(msplit(iy+1,ix  ).NE.ig)) &
                  .OR. (sea(iy-1,ix  ).AND.(msplit(iy-1,ix  ).NE.ig)) &
                  .OR. (sea(iy  ,ix+1).AND.(msplit(iy  ,ix+1).NE.ig)) &
                  .OR. (sea(iy  ,ix-1).AND.(msplit(iy  ,ix-1).NE.ig))
           END DO
           IF ( msplit(ny,ix) .EQ. ig ) mask(ny,ix) =                &
                (sea(ny-1,ix  ).AND.(msplit(ny-1,ix  ).NE.ig))   &
                .OR. (sea(ny  ,ix+1).AND.(msplit(ny  ,ix+1).NE.ig))   &
                .OR. (sea(ny  ,ix-1).AND.(msplit(ny  ,ix-1).NE.ig))
         END DO
         !
         IF ( global ) THEN
           IF ( msplit( 1, 1) .EQ. ig ) mask( 1, 1) =              &
                (sea( 2, 1).AND.(msplit( 2, 1).NE.ig))         &
                .OR. (sea( 1, 2).AND.(msplit( 1, 2).NE.ig))         &
                .OR. (sea( 1,nx).AND.(msplit( 1,nx).NE.ig))
           IF ( msplit( 1,nx) .EQ. ig ) mask( 1,nx) =              &
                (sea( 2,nx  ).AND.(msplit( 2,nx  ).NE.ig))     &
                .OR. (sea( 1, 1  ).AND.(msplit( 1, 1  ).NE.ig))     &
                .OR. (sea( 1,nx-1).AND.(msplit( 1,nx-1).NE.ig))
           DO iy=2, ny-1
             IF ( msplit(iy, 1) .EQ. ig ) mask(iy, 1) =            &
                  (sea(iy+1, 1).AND.(msplit(iy+1, 1).NE.ig))   &
                  .OR. (sea(iy-1, 1).AND.(msplit(iy-1, 1).NE.ig))   &
                  .OR. (sea(iy  , 2).AND.(msplit(iy  , 2).NE.ig))   &
                  .OR. (sea(iy  ,nx).AND.(msplit(iy  ,nx).NE.ig))
             IF ( msplit(iy,nx) .EQ. ig ) mask(iy,nx) =            &
                  (sea(iy+1,nx).AND.(msplit(iy+1,nx).NE.ig))   &
                  .OR. (sea(iy-1,nx).AND.(msplit(iy-1,nx).NE.ig))   &
                  .OR. (sea(iy  , 1).AND.(msplit(iy  , 1).NE.ig))   &
                  .OR. (sea(iy,nx-1).AND.(msplit(iy,nx-1).NE.ig))
           END DO
           IF ( msplit(ny, 1) .EQ. ig ) mask(ny, 1) =              &
                (sea(ny-1, 1).AND.(msplit(ny-1, 1).NE.ig))     &
                .OR. (sea(ny  , 2).AND.(msplit(ny  , 2).NE.ig))     &
                .OR. (sea(ny  ,nx).AND.(msplit(ny  ,nx).NE.ig))
           IF ( msplit(ny,nx) .EQ. ig ) mask(ny,nx) =              &
                (sea(ny-1,nx).AND.(msplit(ny-1,nx).NE.ig))     &
                .OR. (sea(ny  , 1).AND.(msplit(ny  , 1).NE.ig))     &
                .OR. (sea(ny,nx-1).AND.(msplit(ny,nx-1).NE.ig))
         ELSE
           IF ( msplit( 1, 1) .EQ. ig ) mask( 1, 1) =              &
                (sea( 2, 1).AND.(msplit( 2, 1).NE.ig))         &
                .OR. (sea( 1, 2).AND.(msplit( 1, 2).NE.ig))
           IF ( msplit( 1,nx) .EQ. ig ) mask( 1,nx) =              &
                (sea( 2,nx  ).AND.(msplit( 2,nx  ).NE.ig))     &
                .OR. (sea( 1,nx-1).AND.(msplit( 1,nx-1).NE.ig))
           DO iy=2, ny-1
             IF ( msplit(iy, 1) .EQ. ig ) mask(iy, 1) =            &
                  (sea(iy+1, 1).AND.(msplit(iy+1, 1).NE.ig))   &
                  .OR. (sea(iy-1, 1).AND.(msplit(iy-1, 1).NE.ig))   &
                  .OR. (sea(iy  , 2).AND.(msplit(iy  , 2).NE.ig))
             IF ( msplit(iy,nx) .EQ. ig ) mask(iy,nx) =            &
                  (sea(iy+1,nx).AND.(msplit(iy+1,nx).NE.ig))   &
                  .OR. (sea(iy-1,nx).AND.(msplit(iy-1,nx).NE.ig))   &
                  .OR. (sea(iy,nx-1).AND.(msplit(iy,nx-1).NE.ig))
           END DO
           IF ( msplit(ny, 1) .EQ. ig ) mask(ny, 1) =              &
                (sea(ny-1, 1).AND.(msplit(ny-1, 1).NE.ig))     &
                .OR. (sea(ny  , 2).AND.(msplit(ny  , 2).NE.ig))
           IF ( msplit(ny,nx) .EQ. ig ) mask(ny,nx) =              &
                (sea(ny-1,nx).AND.(msplit(ny-1,nx).NE.ig))     &
                .OR. (sea(ny,nx-1).AND.(msplit(ny,nx-1).NE.ig))
         END IF
         !
         ! 3.  Remove marked points ------------------------------------------- *
         !
         DO ix=1, nx
           DO iy=1, ny
             IF ( mask(iy,ix) ) THEN
               msplit(iy,ix) = -1
             END IF
           END DO
         END DO
         !
         ! ... End loops started in 1.
         !
       END DO
     END DO
     !
     RETURN
     !
     ! Formats
     !
     !/ End of GRTRIM ----------------------------------------------------- /
     !/
w3gspl()
program w3gspl
Grid splitting program.
Take an existing grid and create from this the grid data for a set of overlapping grids to be used in the ww3_multi code for hybid paralellization.
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Author
H. L. Tolman
Date
18-Nov-2013
Definition at line 26 of file ww3_gspl.F90.
References w3servmd::extcde(), w3odatmd::fnmpre, w3servmd::itrace(), w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3arrymd::outa2i(), w3arrymd::outa2r(), w3servmd::strace(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3odatmd::w3nout(), w3adatmd::w3seta(), and w3odatmd::w3seto().