WAVEWATCH III: ww3_multi.F90 File Reference
ww3_multi.F90 File Reference
Contains driver program for multi-grid, W3MLTI.
Functions/Subroutines
program w3mlti
Program shell or driver to run the multi-grid wave model (uncoupled).
Detailed Description
Contains driver program for multi-grid, W3MLTI.
Author
H. L. Tolman
Date
29-May-2009
Definition in file ww3_multi.F90.
Function/Subroutine Documentation
w3mlti()
program w3mlti
Program shell or driver to run the multi-grid wave model (uncoupled).
Author
H. L. Tolman
Date
29-May-2009
Definition at line 14 of file ww3_multi.F90.
References wmmdatmd::etime, file(), wmmdatmd::improc, include(), wmmdatmd::mdse, wmmdatmd::mdsi, wmmdatmd::mdso, wmmdatmd::mdss, wmmdatmd::mdst, wmmdatmd::nmproc, wmmdatmd::nmpscr, wmmdatmd::nrgrd, wmfinlmd::wmfinl(), wminitmd::wminit(), wminitmd::wminitnml(), and wmwavemd::wmwave().