WAVEWATCH III: ww3_outp.F90 File Reference
ww3_outp.F90 File Reference
Post-processing of point output.
Functions/Subroutines
program w3outp
Post-processing of point output.
subroutine w3expo
Perform actual point output.
Detailed Description
Post-processing of point output.
Author
H. L. Tolman
J.H. Alves
A. Chawla
F. Ardhuin
E. Rogers
T. Campbell
Date
27-Aug-2015
Definition in file ww3_outp.F90.
Function/Subroutine Documentation
w3expo()
subroutine w3outp::w3expo
Perform actual point output.
Author
H. L. Tolman
J. H. Alves
F. Ardhuin
A. Chawla
Date
06-Feb-2014
Definition at line 1045 of file ww3_outp.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |            J.H. Alves             |
     !/                  |            F. Ardhuin             |
     !/                  |             A. Chawla             |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         06-Feb-2014 |
     !/                  +-----------------------------------+
     !/
     !/    08-Jun-1999 : Final FORTRAN 77                    ( version 1.18 )
     !/    21-Jan-2000 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/                  Massive changes to logistics
     !/    09-Jan-2001 : U* bug fix in tabular output        ( version 2.05 )
     !/    25-Jan-2001 : Flat grid version                   ( version 2.06 )
     !/    02-Feb-2001 : Xnl version 3.0                     ( version 2.07 )
     !/    11-Jun-2001 : Clean up                            ( version 2.11 )
     !/    11-Oct-2001 : Clean up, X*, Y* in tables          ( version 2.14 )
     !/    24-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/    17-Apr-2006 : Filter for directional spread.      ( version 3.09 )
     !/    23-Jun-2006 : Linear input added.                 ( version 3.09 )
     !/    03-Jul-2006 : Separate flux modules.              ( version 3.09 )
     !/    28-Oct-2006 : Add partitioning option.            ( version 3.10 )
     !/    24-Mar-2007 : Add pars for entire spectrum.       ( version 3.11 )
     !/    25-Apr-2007 : Battjes-Janssen Sdb added.          ( version 3.11 )
     !/                  (J. H. Alves)
     !/    09-Oct-2007 : WAM 4+ Sin and Sds added.           ( version 3.13 )
     !/                  (F. Ardhuin)
     !/    09-Oct-2007 : Experimental Sbs (BS1) added.       ( version 3.13 )
     !/                  (F. Ardhuin)
     !/    09-Apr-2008 : Adding an additional output for     ( version 3.12 )
     !/                  WMO standard (A. Chawla)
     !/    29-Apr-2008 : Adjust format partition output.     ( version 3.14 )
     !/    01-Jul-2011 : Adding BT4                          ( version 4.01 )
     !/    16-Jul-2012 : Move GMD (SNL3) and nonlinear filter (SNLS)
     !/                  from 3.15 (HLT).                    ( version 4.08 )
     !/    26-Dec-2012 : Modified obsolete declarations.     ( version 4.11 )
     !/    06-Feb-2014 : Fix header format in part. files.   ( version 4.18 )
     !/    19-Jul-2021 : Momentum and air density support    ( version 7.14 )
     !/
     !  1. Purpose :
     !
     !     Perform actual point output.
     !
     !  3. Parameters :
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SPRn    Subr. W3SRCnMD Mean wave parameters for use in
     !                               source terms.
     !      W3FLXn    Subr. W3FLXnMD Flux/stress computation.
     !      W3SLNn    Subr. W3SLNnMD Linear input.
     !      W3SINn    Subr. W3SRCnMD Input source term.
     !      W3SDSn    Subr. W3SRCnMD Whitecapping source term
     !      W3SNLn    Subr. W3SNLnMD Nonlinear interactions.
     !      W3SBTn    Subr. W3SBTnMD Bottom friction source term.
     !      W3SDBn    Subr. W3SBTnMD Depth induced breaking source term.
     !      W3STRn    Subr. W3STRnMD Triad interaction source term.
     !      W3SBSn    Subr. W3SBSnMD Bottom scattering source term.
     !      W3PART    Sunr. W3PARTMD Spectral partitioning routine.
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      STME21    Subr. W3TIMEMD Convert time to string.
     !      PRT1DS    Subr. W3ARRYMD Print plot of 1-D spectrum.
     !      PRT1DM    Subr.   Id.    Print plot of several 1-D spectra.
     !      PRT2DS    Subr.   Id.    Print plot of 2-D spectrum.
     !      WAVNU1    Subr. W3DISPMD Solve dispersion relation.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Main program in which it is contained,
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !     - Spectra are relative frequency energy spectra.
     !     - Note that arrays CX and CY of the main program now contain
     !       the absolute current speed and direction respectively.
     !
     !     - BT8&9 issues :
     !
     !       Q: What is the problem?
     !       A: Point output of Sbot with BT8 or BT9 is not presently
     !          supported.
     !
     !       Q: What can a user do now?
     !       A: When using BT8 or BT9 with ITYPE=3 , the
     !          user should set the 5th T/F value in ww3_outp.inp for
     !          ITYPE=3 to "F" like so :
     !          2  1. 1. 51   T T T T F T  0  F
     !        $               ^ ^ ^ ^ ^ ^ Sum of selected sources
     !        $               | | | | ^ Wave-bottom interactions
     !        $               | | | ^ Dissipation
     !        $               | | ^ Nonlinear interactions
     !        $               | ^ Wind-wave interactions
     !        $               ^ Spectrum
     !          If the user really need this source function, he/she
     !          needs to add test output to the mud subroutine
     !          directly
     !
     !       Q: Why doesn't this functionality exist?
     !       A: The Sbot source function in ww3_outp was originally written
     !          with the case of BT1 in mind. BT1 uses a uniform friction
     !          factor, so it does not need any special variable for the
     !          local friction factor. BT8 and BT9 allow non-uniform mud
     !          variables (thickness, density, viscosity) and the mud
     !          subroutines are written with ww3_shel in mind, where the
     !          source function is calculated on the computational grid
     !          point IX IY.
     !       Q: How can we add this functionality?
     !       A: To fix it, we would need to :
     !          1) interpolate the mud variables from the computational
     !             grid point IX IY to the output points (this is already
     !             done now for wind, for example) (the same should probably
     !             be done for the ice properties also) This would be done
     !             in w3iopomd.ftn, analogous to what is done now for the
     !             wind variable WAO.
     !          2) manage the arrays for the new variables (mud and ice
     !             properties on the output points) This would be done in
     !             w3odatmd.ftn, again analogous to what is done now for the
     !             wind variable WAO.
     !          3) change the mud routines so that they take the local mud
     !             parameters through the subroutine arguments rather than
     !             taking IX IY as subroutine arguments. This would allow
     !             flexibility to call the mud routine from ww3_shel or
     !             ww3_outp (instead of just ww3_shel as is the case now).
     !
     !/---------------------------------------------------------------------/
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S      Enable subroutine tracing.
     !       !/T      Enable test output.
     !
     !       !/FLXx   Flux/stress computation.
     !       !/LNx    Linear input package
     !       !/STx    Source term package
     !       !/NLx    Nonlinear interaction package
     !       !/BTx    Bottom friction package
     !       !/ICx    S_ice source term package
     !       !/DBx    Depth-induced breaking package
     !       !/TRx    Triad interaction package
     !       !/BSx    Bottom scattering package
     !
     !       !/STAB2  Stability correction for !/ST2
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_FLX1
     USE w3flx1md
 #endif
 #ifdef W3_FLX2
     USE w3flx2md
 #endif
 #ifdef W3_FLX3
     USE w3flx3md
 #endif
 #ifdef W3_FLX4
     USE w3flx4md
 #endif
 #ifdef W3_FLX5
     USE w3flx5md
 #endif
 #ifdef W3_LN1
     USE w3sln1md
 #endif
 #ifdef W3_ST1
     USE w3src1md
 #endif
 #ifdef W3_ST2
     USE w3src2md
 #endif
 #ifdef W3_ST3
     USE w3src3md
 #endif
 #ifdef W3_ST4
     USE w3src4md, ONLY : w3spr4, w3sin4, w3sds4
 #endif
 #ifdef W3_ST6
     USE w3src6md
     USE w3swldmd, ONLY : w3swl6
     USE w3gdatmd, ONLY : swl6s6
 #endif
 #ifdef W3_NL1
     USE w3snl1md
 #endif
 #ifdef W3_NL2
     USE w3snl2md
 #endif
 #ifdef W3_NL3
     USE w3snl3md
 #endif
 #ifdef W3_NL4
     USE w3snl4md
 #endif
 #ifdef W3_NLS
     USE w3snlsmd
 #endif
 #ifdef W3_BT1
     USE w3sbt1md
 #endif
 #ifdef W3_BT4
     USE w3sbt4md
 #endif
 #ifdef W3_BT8
     USE w3sbt8md
 #endif
 #ifdef W3_BT9
     USE w3sbt9md
 #endif
 #ifdef W3_DB1
     USE w3sdb1md
 #endif
 #ifdef W3_BS1
     USE w3sbs1md
 #endif
 #ifdef W3_IS2
     USE w3sis2md
     USE w3gdatmd, ONLY: iicedisp
 #endif
     USE w3partmd, ONLY: w3part
     USE w3dispmd, ONLY: wavnu1, liu_forward_dispersion
     !/
     USE w3arrymd, ONLY: prt1ds, prt2ds, prt1dm
     USE w3dispmd, ONLY: nar1d, dfac, n1max, ecg1, ewn1, dsie
     USE w3bullmd, ONLY: w3bull
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: J, I1, I2, ISP, IKM, ITH,            &
          IK, IH, IM, IS, IYR, IMTH, IDY, ITT, &
          I, NPART, IP, IX, IY, ISEA
     INTEGER, SAVE           :: IPASS  = 0
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
     REAL                    :: DEPTH, SQRTH, CDIR, SIX, R1, R2,     &
          UDIR, UDIRR, UABS, XL, XH, XL2, XH2, &
          ET, EWN, ETR, ETX, ETY, EBND, EBX,   &
          EBY, HSIG, WLEN, TMEAN, THMEAN,      &
          THSPRD, EMAX, EL, EH, DENOM, FP, THP,&
          SPP, CD, USTAR, FACTOR, UNORM, ESTAR,&
          FPSTAR, FACF, FACE, FACS, HMAT, WNA, &
          XYZ, AGE1, AFR, AGE2, FACT, XSTAR,   &
          YSTAR, FHIGH, ZWND, Z0, USTD, EMEAN, &
          FMEAN, WNMEAN, UDIRCA, X, Y, CHARN,  &
          M2KM, ICEF, ICEDMAX, ICETHICK,       &
          ICECON
 #ifdef W3_FLX5
     REAL                     ::TAUA, TAUADIR, RHOAIR
 #endif
 #ifdef W3_IS2
     REAL                    :: WN_R(NK),CG_ICE(NK), ALPHA_LIU(NK)
 #endif
 #ifdef W3_ST1
     REAL                    :: AMAX, FH1, FH2
 #endif
 #ifdef W3_ST2
     REAL                    :: AMAX, ALPHA(NK), FPI
 #endif
 #ifdef W3_ST3
     REAL                    :: AMAX, FMEANS, FMEANWS, TAUWX, TAUWY, &
          TAUWNX, TAUWNY
 #endif
 #ifdef W3_ST4
     REAL                    :: AMAX, FMEANS, FMEANWS, TAUWX, TAUWY, &
          TAUWNX, TAUWNY, FMEAN1, WHITECAP(1:4), DLWMEAN
 #endif
 #ifdef W3_ST6
     REAL                    :: AMAX, TAUWX, TAUWY, TAUWNX, TAUWNY
 #endif
 #ifdef W3_BS1
     REAL                    :: TAUSCX, TAUSCY
 #endif
 #ifdef W3_BT4
     REAL                    :: D50, PSIC, BEDFORM(3), TAUBBL(2)
 #endif
     REAL                    :: ICE
 #ifdef W3_STAB2
     REAL                    :: STAB0, STAB,  COR1, COR2, ASFAC,     &
          THARG1, THARG2
 #endif
     REAL, SAVE              :: HSMIN  = 0.05
     REAL                    :: WN(NK), CG(NK), R(NK)
     REAL                    :: E(NK,NTH), E1(NK), APM(NK),           &
          THBND(NK), SPBND(NK), A(NTH,NK),      &
          WN2(NTH,NK)
     REAL                    :: DIA(NTH,NK), SWN(NK,NTH), SNL(NK,NTH),&
          SDS(NK,NTH), SBT(NK,NTH), SIS(NK,NTH),&
          STT(NK,NTH), DIA2(NTH,NK)
     REAL                    :: XLN(NTH,NK), XIN(NTH,NK), XNL(NTH,NK),&
          XTR(NTH,NK), XDS(NTH,NK), XDB(NTH,NK),&
          XBT(NTH,NK), XBS(NTH,NK), XXX(NTH,NK),&
          XIS(NTH,NK), XWL(NTH,NK)
     REAL                    :: SIN1(NK), SNL1(NK), SDS1(NK),         &
          SBT1(NK), STT1(NK), SIS1(NK),         &
          E1ALL(NK,6)
     LOGICAL                 :: LBREAK
 #ifdef W3_ST3
     LOGICAL                 :: LLWS(NSPEC)
 #endif
 #ifdef W3_ST4
     LOGICAL                 :: LLWS(NSPEC)
     REAL                    :: LAMBDA(NSPEC)
 #endif
     CHARACTER               :: DTME21*23
     CHARACTER(LEN=4)         VAR1(6)
     CHARACTER(LEN=1)         IDLAT, IDLON
     CHARACTER(LEN=100)       BT8MSG
     !
     DATA var1   / 'Sin ' , 'Snl ', 'Sds ' , 'Sbt ' , 'Sice', 'Stot' /
     !/
     !/ ------------------------------------------------------------------- /
     !/
     ! 1. Initialisations
     !
 #ifdef W3_S
     CALL strace (ient, 'W3EXPO')
 #endif
     !
     IF ( flagll ) THEN
       m2km   = 1.
     ELSE
       m2km   = 1.e-3
     END IF
     !
     xl     = 1./xfr - 1.
     xh     =  xfr - 1.
     xl2    = xl**2
     xh2    = xh**2
     ipass  = ipass + 1
     !
     IF ( itype .EQ. 3 ) THEN
       xln = 0.
       xin = 0.
       xnl = 0.
       xtr = 0.
       xds = 0.
       xdb = 0.
       xbt = 0.
       xbs = 0.
       xwl = 0.
       xxx = 0.
       xis = 0.
     END IF
     !
 #ifdef W3_T
     WRITE (ndst,9000) (flreq(j),j=1,nopts)
     WRITE (ndst,9001) itype, otype, nreq, scale1, scale2, flsrce
 #endif
     !
     !     Output of time
     !
     IF (  ( itype.EQ.1 .AND. otype.EQ.3 ) .OR.                      &
          ( itype.EQ.3 .AND. otype.EQ.4 ) ) THEN
       IF ( flform ) THEN
         WRITE (ndstab) time
       ELSE
         WRITE (ndstab,900) time
       END IF
     END IF
     !
     IF (itype.EQ.2) THEN
       IF ( nreq.EQ.1 .AND. ipass.EQ.1 ) THEN
         IF ( otype.EQ.1 ) THEN
           WRITE (ndstab,1901)
         ELSE IF ( otype.EQ.2 ) THEN
           WRITE (ndstab,1902)
         ELSE IF ( otype.EQ.3 ) THEN
           WRITE (ndstab,1903)
         ELSE IF ( otype.EQ.4 ) THEN
           WRITE (ndstab,1904)
         ELSE IF ( otype.EQ.5 ) THEN
           WRITE (ndstab,1905)
         ELSE IF ( otype.EQ.6 ) THEN
           WRITE (ndstab,1906)
         END IF
       END IF
       IF ( nreq.NE.1 ) THEN
         CALL stme21 ( time , dtme21 )
         IF ( ipass .NE. 1 ) WRITE (ndstab,1910)
         IF ( otype.EQ.1 ) THEN
           IF ( flagll ) THEN
             WRITE (ndstab,1911) dtme21
           ELSE
             WRITE (ndstab,1711) dtme21
           END IF
         ELSE IF ( otype.EQ.2 ) THEN
           IF ( flagll ) THEN
             WRITE (ndstab,1912) dtme21
           ELSE
             WRITE (ndstab,1712) dtme21
           END IF
         ELSE IF ( otype.EQ.3 ) THEN
           WRITE (ndstab,1913) dtme21
         ELSE IF ( otype.EQ.4 ) THEN
           WRITE (ndstab,1914) dtme21
         ELSE IF ( otype.EQ.5 ) THEN
           IF ( flagll ) THEN
             WRITE (ndstab,1915) dtme21
           ELSE
             WRITE (ndstab,1715) dtme21
           END IF
         ELSE IF ( otype.EQ.6 ) THEN
           IF ( flagll ) THEN
             WRITE (ndstab,1916) dtme21
           ELSE
             WRITE (ndstab,1716) dtme21
           END IF
         END IF
       END IF
     END IF
     !
     IF (itype.EQ.3) THEN
       IF ( otype .EQ. 4 ) THEN
         CALL stme21 ( time , dtme21 )
         WRITE (ndso,905) dtme21
       END IF
     END IF
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     !     Loop over output points.
     !
     DO j=1, nopts
       IF ( flreq(j) ) THEN
         !
 #ifdef W3_T
         WRITE (ndst,9002) ptnme(j)
 #endif
         !
         ! 2. Calculate grid parameters using and inlined version of WAVNU1.
         !
         depth    = max( dmin, dpo(j) )
         sqrth    = sqrt( depth )
         udir     = mod( 270. - wdo(j)*rade , 360. )
         udirca   = wdo(j)*rade
         udirr    = wdo(j)
         uabs     = max( 0.001 , wao(j) )
 #ifdef W3_FLX5
         taua     = max( 0.001 , tauao(j))
         tauadir  = mod( 270. - taudo(j)*rade , 360. )
         rhoair   = max( 0. , dairo(j))
 #endif
         cdir     = mod( 270. - cdo(j)*rade , 360. )
 #ifdef W3_IS2
         icedmax  = max( 0., icefo(j))
         icef     = icedmax
         icethick = max(0., iceho(j))
         icecon   = max(0., iceo(j))
 #endif
         !
 #ifdef W3_STAB2
         stab0  = zwind * grav / 273.
         stab   = stab0 * aso(j) / max(5.,wao(j))**2
         stab   = max( -1. , min( 1. , stab ) )
         tharg1 = max( 0. , ffng*(stab-ofstab))
         tharg2 = max( 0. , ffps*(stab-ofstab))
         cor1   = ccng * tanh(tharg1)
         cor2   = ccps * tanh(tharg2)
         asfac  = sqrt( (1.+cor1+cor2)/shstab )
 #endif
         !
 #ifdef W3_T
         WRITE (ndst,9010) depth
 #endif
         DO ik=1, nk
           six    = sig(ik) * sqrth
           i1     = int(six/dsie)
           IF (i1.LE.n1max) THEN
             i2 = i1 + 1
             r1 = six/dsie - real(i1)
             r2 = 1. - r1
             wn(ik) = ( r2*ewn1(i1) + r1*ewn1(i2) ) / depth
             cg(ik) = ( r2*ecg1(i1) + r1*ecg1(i2) ) * sqrth
           ELSE
             wn(ik) = sig(ik)*sig(ik)/grav
             cg(ik) = 0.5 * grav / sig(ik)
           END IF
 #ifdef W3_T
           WRITE (ndst,9011) ik, tpi/sig(ik), wn(ik), cg(ik)
 #endif
           !
         END DO
         !
         ! Computes 2nd order spectrum
         !
 #ifdef W3_IG1
         IF (igpars(2).EQ.1) THEN
           IF(igpars(1).EQ.1) THEN
             CALL w3addig(spco(:,j),dpo(j),wn,cg,0)
           ELSE
             CALL w3add2ndorder(spco(:,j),dpo(j),wn,cg,0)
           END IF
         END IF
 #endif
         !
         ! 3.  Prepare spectra etc.
         ! 3.a Mean wave parameters.
         !
         et     = 0.
         ewn    = 0.
         etr    = 0.
         etx    = 0.
         ety    = 0.
         DO ik=1, nk
           ebnd   = 0.
           ebx    = 0.
           eby    = 0.
           DO ith=1, nth
             isp    = ith + (ik-1)*nth
             e(ik,ith) = spco(isp,j)
             ebnd   = ebnd + spco(isp,j)
             ebx    = ebx  + spco(isp,j)*ecos(ith)
             eby    = eby  + spco(isp,j)*esin(ith)
           END DO
           e1(ik) = ebnd * dth
           apm(ik)= e1(ik) / ( tpi * grav**2 / sig(ik)**5  )
           IF ( e1(ik) .GT. 1.e-5) THEN
             thbnd(ik) = mod(630.- rade*atan2(eby,ebx),360.)
             spbnd(ik) = rade * sqrt( max( 0. , 2.*( 1. -      &
                  sqrt( max(0.,(ebx**2+eby**2)/ebnd**2) ) ) ) )
           ELSE
             thbnd(ik) = -999.9
             spbnd(ik) = -999.9
           END IF
           ebnd   = e1(ik) * dsii(ik) * tpiinv
           et     = et  + ebnd
           ewn    = ewn + ebnd / wn(ik)
           etr    = etr + ebnd / sig(ik)
           etx    = etx + ebx * dsii(ik)
           ety    = ety + eby * dsii(ik)
         END DO
         !
         ! tail factors for radian action etc ...!
         !
         ebnd   = e1(nk) * tpiinv / ( sig(nk) * dth )
         et     = et  + fte *ebnd
         ewn    = ewn + ftwl*ebnd
         etr    = etr + fttr*ebnd
         etx    = dth*etx*tpiinv + fte*ebx*tpiinv/sig(nk)
         ety    = dth*ety*tpiinv + fte*eby*tpiinv/sig(nk)
         !
         hsig   = 4. * sqrt( max(0.,et) )
         IF ( hsig .GT. hsmin ) THEN
           wlen   = ewn / et * tpi
           tmean  = etr / et * tpi
           thmean = mod( 630. - rade*atan2(ety,etx) , 360. )
           thsprd = rade * sqrt( max( 0. , 2.*( 1. - sqrt(     &
                max(0.,(etx**2+ety**2)/et**2) ) ) ) )
           IF ( thsprd .LT. 0.01*rade*dth ) thsprd = 0.
         ELSE
           wlen   = 0.
           tmean  = 0.
           thmean = 0.
           thsprd = 0.
           DO ik=1, nk
             e1(ik) = 0.
             DO ith=1, nth
               e(ik,ith) = 0.
             END DO
           END DO
         END IF
         !
         ! peak frequency
         !
         emax   = e1(nk)
         ikm    = nk
         !
         DO ik=nk-1, 1, -1
           IF ( e1(ik) .GT. emax ) THEN
             emax   = e1(ik)
             ikm    = ik
           END IF
         END DO
         IF ( hsig .GE. hsmin .AND. ikm .NE. nk ) THEN
           IF ( ikm .EQ. 1 ) THEN
             el = - e1(ikm)
           ELSE
             el = e1(ikm-1) - e1(ikm)
           END IF
           eh = e1(ikm+1) - e1(ikm)
           denom  = xl*eh - xh*el
           !
           fp     = sig(ikm) * ( 1. + 0.5 * ( xl2*eh - xh2*el )  &
                / sign( max(abs(denom),1.e-15) , denom ) )
           thp    = thbnd(ikm)
           spp    = spbnd(ikm)
           IF ( spp .LT. 0.01*rade*dth ) spp = 0.
         ELSE
           fp     = 0.
           thp    = 0.
           spp    = 0.
         END IF
         !
         ! spectral partitioning
         !
         IF ( itype.EQ.4 ) CALL w3part                              &
              ( e, uabs, udirca, depth, wn, npart, xpart, dimxp )
         !
         ! nondimensional parameters
         !
         IF ( ( itype.EQ.2 .AND. (otype.EQ.3.OR.otype.EQ.4) ) .OR. &
              ( itype.EQ.1 .AND. (otype.EQ.2) ) ) THEN
           !
           DO ik=1, nk
             factor = tpiinv * cg(ik) / sig(ik)
             DO ith=1, nth
               isp    = ith + (ik-1)*nth
               a(ith,ik)   = factor * spco(isp,j)
               wn2(ith,ik) = wn(ik)
             END DO
           END DO
           !
 #ifdef W3_STAB2
           uabs   = uabs / asfac
 #endif
           !
 #ifdef W3_ST0
           zwnd   = 10.
 #endif
 #ifdef W3_ST1
           zwnd   = 10.
 #endif
 #ifdef W3_ST2
           zwnd   = zwind
 #endif
 #ifdef W3_ST3
           zwnd   = zzwnd
           tauwx  = 0.
           tauwy  = 0.
           llws(:)  = .true.
 #endif
 #ifdef W3_ST4
           llws(:)  = .true.
           zwnd   = zzwnd
           tauwx  = 0.
           tauwy  = 0.
 #endif
 #ifdef W3_ST6
           zwnd   = 10.
 #endif
           ustar  = 1.
           !
 #ifdef W3_ST1
           CALL w3spr1 (a, cg, wn, emean, fmean, wnmean, amax)
           fp     = 0.85 * fmean
 #endif
 #ifdef W3_ST2
           CALL w3spr2 (a, cg, wn, depth, fp , uabs, ustar, &
                emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
           CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                wnmean, amax, uabs, udirr, ustar, ustd,&
                tauwx, tauwy, cd, z0, charn, llws, fmeanws )
 #endif
 #ifdef W3_ST4
           CALL w3spr4 (a, cg, wn, emean, fmean,  fmean1,      &
                wnmean, amax, uabs, udirr,             &
 #ifdef W3_FLX5
                taua, tauadir, rhoair,           &
 #endif
                ustar, ustd, tauwx, tauwy, cd, z0,     &
                charn, llws, fmeanws, dlwmean )
 #endif
 #ifdef W3_ST6
           CALL w3spr6 (a, cg, wn, emean, fmean, wnmean, amax, fp)
 #endif
           !
 #ifdef W3_FLX1
           CALL w3flx1 ( zwnd, uabs, udirr,                   &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX2
           CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,        &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
           CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,        &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX4
           CALL w3flx4 ( zwnd, uabs, udirr, ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX5
           CALL w3flx5 ( zwnd, uabs, udirr, taua, tauadir,    &
                rhoair, ustar, ustd, z0, cd, charn )
 #endif
           !
           DO itt=1, 3
 #ifdef W3_ST2
             CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,    &
                  fpi, xin, dia )
             CALL w3spr2 (a, cg, wn, depth, fpi, uabs, ustar, &
                  emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
             ix=1
             iy=1
             CALL w3sin3 ( a, cg, wn2, uabs, ustar, dair/dwat,&
                  aso(j), udirr, z0, cd, tauwx, tauwy,&
                  tauwnx, tauwny, ice, xin, dia, llws, ix, iy )
             CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                  wnmean, amax, uabs, udirr, ustar, ustd,&
                  tauwx, tauwy, cd, z0, charn, llws, fmeanws )
 #endif
 #ifdef W3_ST4
             ix=1
             iy=1
             CALL w3sin4 ( a, cg, wn2, uabs, ustar, dair/dwat,&
                  aso(j), udirr, z0, cd, tauwx, tauwy,&
                  tauwnx, tauwny, xin, dia, llws, ix, iy, lambda )
             CALL w3spr4 (a, cg, wn, emean, fmean,  fmean1,      &
                  wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                  taua, tauadir, rhoair,             &
 #endif
                  ustar, ustd, tauwx, tauwy, cd, z0,       &
                  charn, llws, fmeanws, dlwmean )
 #endif
 #ifdef W3_FLX2
             CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,      &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
             CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,      &
                  ustar, ustd, z0, cd )
 #endif
           END DO
           !
           ! Add alternative flux calculations here as part of !/ST2 option ....
           ! Also add before actual source term calculation !!!
           !
 #ifdef W3_STAB2
           uabs   = uabs * asfac
 #endif
           !
           IF ( wao(j) .LT. 0.01 ) THEN
             unorm  = 0.
             estar  = 0.
             fpstar = 0.
           ELSE
             IF ( otype.EQ.3 ) THEN
               unorm  = ustar
             ELSE
               unorm  = wao(j)
             END IF
             estar  = et * grav**2 / unorm**4
             fpstar = fp * tpiinv * unorm / grav
             xstar  = ptloc(1,j) * grav / unorm**2
             ystar  = ptloc(2,j) * grav / unorm**2
             IF ( flagll ) THEN
               xstar  = xstar * dera * radius &
                    * cos(ptloc(2,j)*dera)
               ystar  = ystar * dera * radius
             END IF
           END IF
           !
         END IF
         !
         ! 3.4 source terms
         !
         IF ( itype.EQ.3 ) THEN
           !
           DO ik=1, nk
             factor = tpiinv * cg(ik) / sig(ik)
             DO ith=1, nth
               a(ith,ik)   = factor * spco(ith+(ik-1)*nth,j)
               wn2(ith,ik) = wn(ik)
             END DO
           END DO
           !
 #ifdef W3_STAB2
           uabs   = uabs / asfac
 #endif
           !
 #ifdef W3_ST0
           zwnd   = 10.
 #endif
 #ifdef W3_ST1
           zwnd   = 10.
 #endif
 #ifdef W3_ST2
           zwnd   = zwind
 #endif
 #ifdef W3_ST3
           zwnd   = zzwnd
 #endif
 #ifdef W3_ST0
           ustar  = 1.
 #endif
 #ifdef W3_ST1
           ustar  = 1.
 #endif
 #ifdef W3_ST2
           ustar  = 1.
 #endif
 #ifdef W3_ST3
           ustar  = 0.
           ustd   = 0.
           tauwx  = 0.
           tauwy  = 0.
 #endif
 #ifdef W3_ST4
           zwnd   = zzwnd
           ustar  = 0.
           ustd   = 0.
           tauwx  = 0.
           tauwy  = 0.
 #endif
 #ifdef W3_ST6
           zwnd   = 10.
 #endif
           !
 #ifdef W3_ST0
           fhigh  = sig(nk)
 #endif
 #ifdef W3_ST1
           CALL w3spr1 (a, cg, wn, emean, fmean, wnmean, amax)
           fp     = 0.85 * fmean
           fh1    = fxfm * fmean
           fh2    = fxpm / ustar
           fhigh  = max( fh1 , fh2 )
 #endif
 #ifdef W3_ST2
           CALL w3spr2 (a, cg, wn, depth, fp , uabs, ustar, &
                emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
           CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                wnmean, amax, uabs, udirr, ustar, ustd,&
                tauwx, tauwy, cd, z0, charn, llws, fmeanws )
 #endif
 #ifdef W3_ST4
           CALL w3spr4 (a, cg, wn, emean, fmean,  fmean1,        &
                wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                taua, tauadir, rhoair,             &
 #endif
                ustar, ustd, tauwx, tauwy, cd, z0,       &
                charn, llws, fmeanws, dlwmean )
 #endif
 #ifdef W3_ST6
           CALL w3spr6 (a, cg, wn, emean, fmean, wnmean, amax, fp)
           fhigh  = sig(nk)
 #endif
           !
 #ifdef W3_FLX1
           CALL w3flx1 ( zwnd, uabs, udirr,                   &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX2
           CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,        &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
           CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,        &
                ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX4
           CALL w3flx4 ( zwnd, uabs, udirr, ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX5
           CALL w3flx5 ( zwnd, uabs, udirr, taua, tauadir,    &
                rhoair, ustar, ustd, z0, cd, charn )
 #endif
           !
           DO itt=1, 3
 #ifdef W3_ST2
             CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,    &
                  fpi, xin, dia )
             CALL w3spr2 (a, cg, wn, depth, fpi, uabs, ustar, &
                  emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
             CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                  wnmean, amax, uabs, udirr, ustar, ustd,&
                  tauwx, tauwy, cd, z0, charn, llws, fmeanws )
             CALL w3sin3 ( a, cg, wn2, uabs, ustar, dair/dwat,&
                  aso(j), udirr, z0, cd,tauwx, tauwy, &
                  tauwnx, tauwny, ice, xin, dia, llws, ix, iy )
 #endif
 #ifdef W3_ST4
             CALL w3spr4 (a, cg, wn, emean, fmean, fmean1,        &
                  wnmean, amax, uabs, udirr,              &
 #ifdef W3_FLX5
                  taua, tauadir, rhoair,            &
 #endif
                  ustar, ustd, tauwx, tauwy, cd, z0,      &
                  charn, llws, fmeanws, dlwmean )
             CALL w3sin4 ( a, cg, wn2, uabs, ustar, dair/dwat,&
                  aso(j), udirr, z0, cd,tauwx, tauwy, &
                  tauwnx, tauwny, xin, dia, llws, ix, iy, lambda )
 #endif
 #ifdef W3_FLX2
             CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,      &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
             CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,      &
                  ustar, ustd, z0, cd )
 #endif
           END DO
           !
 #ifdef W3_ST2
           fhigh  = xfc * fpi
 #endif
           !
           IF ( flsrce(2) ) THEN
 #ifdef W3_LN1
             CALL w3sln1 (wn, fhigh, ustar, udirr, xln )
 #endif
             !
 #ifdef W3_ST1
             CALL w3sin1 (a, wn2, ustar, udirr,  xin, dia )
 #endif
 #ifdef W3_ST2
             CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,&
                  fpi, xin, dia )
 #endif
 #ifdef W3_ST3
             CALL w3sin3 ( a, cg, wn2, uabs, ustar,       &
                  dair/dwat, aso(j), udirr,      &
                  z0, cd, tauwx, tauwy,tauwnx, tauwny, &
                  ice, xin, dia, llws, ix, iy )
 #endif
 #ifdef W3_ST4
             CALL w3sin4 ( a, cg, wn2, uabs, ustar,       &
                  dair/dwat, aso(j), udirr,      &
                  z0, cd, tauwx, tauwy,tauwnx, tauwny, &
                  xin, dia, llws, ix, iy, lambda )
 #endif
 #ifdef W3_ST6
             CALL w3sin6 (a, cg, wn2, uabs, ustar, udirr, cd, dair, &
                  tauwx, tauwy, tauwnx, tauwny, xin, dia )
 #endif
           END IF
           IF ( flsrce(3) ) THEN
 #ifdef W3_NL1
             IF (iqtpe.GT.0) THEN
               CALL w3snl1 ( a, cg, wnmean*depth,  xnl, dia )
             ELSE
               CALL w3snlgqm ( a, cg, wn, depth,  xnl, dia )
             END IF
 #endif
 #ifdef W3_NL2
             CALL w3snl2 ( a, cg, depth,         xnl, dia )
 #endif
 #ifdef W3_NL3
             CALL w3snl3 ( a, cg, wn, depth,     xnl, dia )
 #endif
 #ifdef W3_NL4
             CALL w3snl4 ( a, cg, wn, depth,     xnl, dia )
 #endif
           END IF
           IF ( flsrce(4) ) THEN
 #ifdef W3_ST1
             CALL w3sds1 ( a, wn2, emean, fmean, wnmean,  &
                  xds, dia )
 #endif
 #ifdef W3_ST2
             CALL w3sds2 ( a, cg, wn, fpi, ustar,         &
                  alpha,                xds, dia )
 #endif
 #ifdef W3_ST3
             CALL w3sds3 ( a, wn, cg, emean, fmeans, wnmean,  &
                  ustar, ustd, depth, xds, dia, ix, iy )
 #endif
 #ifdef W3_ST4
             CALL w3sds4 ( a, wn, cg,  ustar, ustd, depth, dair, xds, &
                  dia, ix, iy, lambda, whitecap, dlwmean )
 #endif
 #ifdef W3_ST6
             CALL w3sds6 ( a, cg, wn,            xds, dia )
             IF (swl6s6) CALL w3swl6 ( a, cg, wn,  xwl, dia )
 #endif
             !
 #ifdef W3_DB1
             CALL w3sdb1 ( i, a, depth, emean, fmean,    &
                  wnmean, cg, lbreak, xdb, dia )
 #endif
           END IF
           IF ( flsrce(5) ) THEN
 #ifdef W3_BT1
             CALL w3sbt1 ( a, cg, wn, depth,     xbt, dia )
 #endif
 #ifdef W3_BT4
             ix=1    ! to be fixed later
             iy=1    ! to be fixed later
             isea=1  ! to be fixed later
             d50 = sed_d50(isea)
             psic= sed_psic(isea)
 #endif
 #ifdef W3_BT4
             CALL w3sbt4 ( a, cg, wn, depth, d50, psic, taubbl,   &
                  bedform, xbt, dia, ix, iy )
 #endif
             bt8msg='ww3_outp: ITYPE=3 with BT8 or BT9: Sbot out'//&
                  'put is not yet supported. Use "F" for the 5'//&
                  'th T/F flag.'
 #ifdef W3_BT8
             CALL extcde( 516,msg=bt8msg)
 #endif
 #ifdef W3_BT9
             CALL extcde( 516,msg=bt8msg)
 #endif
             ! For info on this issue, see : "BT8&9 issues" in "Remarks" section above.
             !...broken....!/BT8                    CALL W3SBT8 ( A, DEPTH, XBT, DIA, IX, IY )
             !...broken....!/BT9                    CALL W3SBT9 ( A, DEPTH, XBT, DIA, IX, IY )
             !
 #ifdef W3_BS1
             CALL w3sbs1 ( a, cg, wn, depth,              &
                  cao(j)*cos(cdo(j)), cao(j)*sin(cdo(j)), &
                  tauscx, tauscy,   xbs, dia )
 #endif
           END IF
           !
           IF ( flsrce(6) ) THEN
 #ifdef W3_IS2
             IF (iicedisp) THEN
               CALL liu_forward_dispersion  (icethick,0.,depth, &
                    sig,wn_r,cg_ice,alpha_liu)
             ELSE
               wn_r=wn
               cg_ice=cg
             END IF
 #endif
             !
 #ifdef W3_IS2
             CALL w3sis2(a, depth, icecon, icethick, icef, icedmax, &
                  ix, iy, xis, dia, dia2, wn, cg, wn_r, cg_ice, r)
 #endif
           END IF
           !
 #ifdef W3_STAB2
           uabs   = uabs * asfac
 #endif
           !
           IF ( iscale.EQ.0 .OR. iscale.EQ.3 ) THEN
             facf   = tpiinv
             face   = 1.
             facs   = 1.
           ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.4 ) THEN
             facf   = tpiinv * uabs / grav
             face   = grav**3 / uabs**5
             facs   = grav**2 / uabs**4
           ELSE IF ( iscale.EQ.2 .OR. iscale.EQ.5 ) THEN
             facf   = tpiinv * ustar / grav
             face   = grav**3 / ustar**5
             facs   = grav**2 / ustar**4
           END IF
           !
           DO ik=1, nk
             factor = tpi / cg(ik) * sig(ik)
             e1(ik) = 0.
             sin1(ik) = 0.
             snl1(ik) = 0.
             sds1(ik) = 0.
             sbt1(ik) = 0.
             stt1(ik) = 0.
             sis1(ik) = 0.
             DO ith=1, nth
               isp         = ith + (ik-1)*nth
               e(ik,ith) = spco(isp,j)
               swn(ik,ith) = ( xln(ith,ik) + xin(ith,ik) ) * factor
               snl(ik,ith) = ( xnl(ith,ik) + xtr(ith,ik) ) * factor
               sds(ik,ith) = ( xds(ith,ik) + xdb(ith,ik) ) * factor
 #ifdef W3_ST6
               sds(ik,ith) =   sds(ik,ith) +(xwl(ith,ik)   * factor)
 #endif
               sbt(ik,ith) = ( xbt(ith,ik) * xbs(ith,ik) ) * factor
               sis(ik,ith) = xis(ith,ik) * factor
               stt(ik,ith) = swn(ik,ith) + snl(ik,ith)+sds(ik,ith)&
                    + sbt(ik,ith) + sis(ik,ith) &
                    + xxx(ith,ik) * factor
               e1(ik) = e1(ik) + e(ik,ith)
               sin1(ik) = sin1(ik) + swn(ik,ith)
               snl1(ik) = snl1(ik) + snl(ik,ith)
               sds1(ik) = sds1(ik) + sds(ik,ith)
               sbt1(ik) = sbt1(ik) + sbt(ik,ith)
               sis1(ik) = sis1(ik) + sis(ik,ith)
             END DO
             e1(ik) = e1(ik)   * dth * face
             sin1(ik) = sin1(ik) * dth * facs
             snl1(ik) = snl1(ik) * dth * facs
             sds1(ik) = sds1(ik) * dth * facs
             sbt1(ik) = sbt1(ik) * dth * facs
             sis1(ik) = sis1(ik) * dth * facs
           END DO
           !
           stt1       = sin1 + snl1 + sds1 + sbt1 + sis1
           e1all(:,1) = sin1
           e1all(:,2) = snl1
           e1all(:,3) = sds1
           e1all(:,4) = sbt1
           e1all(:,5) = sis1
           e1all(:,6) = stt1
           !
         END IF
         !
         ! 4.a Perform output type 1 ( print plots / tables / file )
         !
         IF ( itype .EQ. 1 ) THEN
           !
           IF ( otype .EQ. 1 ) THEN
             !
             IF ( scale1 .GE. 0. )                             &
                  CALL prt1ds (ndso, nk, e1, sig(1:nk), 'RAD/S',&
                  17, scale1, 'E(f)', 'm^2s', ptnme(j) )
             IF ( scale2 .GE. 0. )                             &
                  CALL prt2ds (ndso, nk, nk, nth, e, sig(1:nk), &
                  'RAD/S', 1., scale2, 0.0001, 'E(f,th)',  &
                  'm^2s', ptnme(j) )
             WRITE (ndso,910) dpo(j), uabs
             IF ( wao(j) .GT. 0. ) WRITE (ndso,911) udir
             WRITE (ndso,912) aso(j), cao(j)
             IF ( cao(j) .GT. 0. ) WRITE (ndso,913) cdir
             WRITE (ndso,914) hsig, wlen, tmean, thmean, thsprd
             !
           ELSE IF ( otype .EQ. 2 ) THEN
             !
             CALL stme21 ( time , dtme21 )
             IF ( flagll ) THEN
               WRITE (ndstab,920) dtme21, ptnme(j),          &
                    m2km*ptloc(1,j), m2km*ptloc(2,j),         &
                    dpo(j), ustar, wao(j), udir
             ELSE
               WRITE (ndstab,720) dtme21, ptnme(j),          &
                    m2km*ptloc(1,j), m2km*ptloc(2,j),         &
                    dpo(j), ustar, wao(j), udir
             END IF
             IF ( fp .EQ. 0. ) fp = sig(nk)
             DO ik=1, nk
               WRITE (ndstab,921) tpiinv*sig(ik), sig(ik)/fp,  &
                    e1(ik), thbnd(ik), spbnd(ik), apm(ik)
             END DO
             IF ( fp .EQ. sig(nk) ) fp = 0.
             WRITE (ndstab,922)
             !
           ELSE IF ( otype .EQ. 3 ) THEN
             !
             IF ( flform ) THEN
               WRITE (ndstab) ptnme(j), ptloc(2,j),          &
                    ptloc(1,j), dpo(j), wao(j),    &
                    udir, cao(j), cdir
               WRITE (ndstab) ((e(ik,ith),ik=1,nk),ith=1,nth)
             ELSE
               WRITE (ndstab,901) ptnme(j), m2km*ptloc(2,j), &
                    m2km*ptloc(1,j), dpo(j),   &
                    wao(j), udir, cao(j), cdir
               WRITE (ndstab,902)                            &
                    ((e(ik,ith),ik=1,nk),ith=1,nth)
             END IF
             !
           END IF
           !
           ! 4.b Perform output type 2 ( tables )
           !
         ELSE IF ( itype .EQ. 2 ) THEN
           !
           IF ( nreq .EQ. 1 ) THEN
             !
             iyr    = time(1) / 10000
             imth   = mod( time(1) , 10000 ) / 100
             idy    = mod( time(1) , 100 )
             ih     = time(2) / 10000
             im     = mod( time(2) , 10000 ) / 100
             is     = mod( time(2) , 100 )
             IF ( otype .EQ. 1 ) THEN
               WRITE (ndstab,1921) time(1), ih, im, is,      &
                    dpo(j), cao(j), cdir, wao(j), udir
             ELSE IF ( otype .EQ. 2 ) THEN
               WRITE (ndstab,1922) time(1), ih, im, is,      &
                    hsig, wlen, tmean, thmean, thsprd,     &
                    fp*tpiinv, thp, spp
             ELSE IF ( otype.EQ.3 ) THEN
               WRITE (ndstab,1923) time(1), ih, im, is,      &
                    unorm, estar, fpstar, cd*1000., apm(nk)*100.
             ELSE IF ( otype.EQ.4 ) THEN
               WRITE (ndstab,1924) time(1), ih, im, is,      &
                    unorm, estar, fpstar, cd*1000., apm(nk)*100.
             ELSE IF ( otype.EQ.5 ) THEN
               hmat   = min( 100. , 3.33*grav*hsig/uabs**2 )
               IF ( hsig .GE. hsmin ) THEN
                 CALL wavnu1 ( fp, dpo(j), wna, xyz )
                 age1   = min( 100. , fp / wna / uabs )
                 afr    = tpi / tmean
                 CALL wavnu1 ( afr, dpo(j), wna, xyz )
                 age2   = min( 100. , afr / wna / uabs )
               ELSE
                 age1   = -9.99
                 age2   = -9.99
               END IF
               WRITE (ndstab,1925) time(1), ih, im, is,      &
                    wao(j), udir, hsig, hmat, age1, age2,  &
                    aso(j)
             ELSE IF ( otype.EQ.6 ) THEN
               IF ( hsig .GE. hsmin ) THEN
                 WRITE (ndstab,1926) iyr, imth, idy, ih,    &
                      wao(j), nint(udir), hsig, tpi / fp
               ELSE
                 WRITE (ndstab,1926) iyr, imth, idy, ih,    &
                      wao(j), nint(udir), hsig, 0.0
               END IF
             END IF
             !
           ELSE
             !
             IF ( otype .EQ. 1 ) THEN
               IF ( flagll ) THEN
                 WRITE (ndstab,1931) m2km*ptloc(1,j),      &
                      m2km*ptloc(2,j), dpo(j), cao(j),   &
                      cdir, wao(j), udir
               ELSE
                 WRITE (ndstab,1731) m2km*ptloc(1,j),      &
                      m2km*ptloc(2,j), dpo(j), cao(j),   &
                      cdir, wao(j), udir
               END IF
             ELSE IF ( otype .EQ. 2 ) THEN
               IF ( flagll ) THEN
                 WRITE (ndstab,1932) m2km*ptloc(1,j),      &
                      m2km*ptloc(2,j), hsig, wlen,       &
                      tmean, thmean, thsprd, fp*tpiinv,  &
                      thp, spp
               ELSE
                 WRITE (ndstab,1732) m2km*ptloc(1,j),      &
                      m2km*ptloc(2,j), hsig, wlen,       &
                      tmean, thmean, thsprd, fp*tpiinv,  &
                      thp, spp
               END IF
             ELSE IF ( otype .EQ. 3 ) THEN
               WRITE (ndstab,1933) 1.e-4*xstar,              &
                    1.e-4*ystar, unorm, estar, fpstar,     &
                    cd*1000., apm(nk)*100.
             ELSE IF ( otype .EQ. 4 ) THEN
               WRITE (ndstab,1934) xstar, ystar, unorm,      &
                    estar, fpstar, cd*1000., apm(nk)*100.
             ELSE IF ( otype .EQ. 5 ) THEN
               hmat   = min( 100. , 3.33*grav*hsig/uabs**2 )
               CALL wavnu1 ( fp, dpo(j), wna, xyz )
               age1   = min( 100. , fp / wna / uabs )
               afr    = tpi / tmean
               CALL wavnu1 ( afr, dpo(j), wna, xyz )
               age2   = min( 100. , afr / wna / uabs )
               IF ( flagll ) THEN
                 WRITE (ndstab,1935) m2km*ptloc(1,j),      &
                      m2km*ptloc(2,j), wao(j), udir,     &
                      hsig, hmat, age1, age2, aso(j)
               ELSE
                 WRITE (ndstab,1735) m2km*ptloc(1,j),      &
                      m2km*ptloc(2,j), wao(j), udir,     &
                      hsig, hmat, age1, age2, aso(j)
               END IF
             ELSE IF ( otype .EQ. 6 ) THEN
               IF ( hsig .GE. hsmin ) THEN
                 IF ( flagll ) THEN
                   WRITE (ndstab,1936) m2km*ptloc(1,j),       &
                        m2km*ptloc(2,j), wao(j), nint(udir),&
                        hsig, tpi / fp
                 ELSE
                   WRITE (ndstab,1736) m2km*ptloc(1,j),       &
                        m2km*ptloc(2,j), wao(j), nint(udir),&
                        hsig, tpi / fp
                 END IF
               ELSE
                 IF ( flagll ) THEN
                   WRITE (ndstab,1936) m2km*ptloc(1,j),       &
                        m2km*ptloc(2,j), wao(j), nint(udir),&
                        hsig, 0.0
                 ELSE
                   WRITE (ndstab,1736) m2km*ptloc(1,j),       &
                        m2km*ptloc(2,j), wao(j), nint(udir),&
                        hsig, 0.0
                 END IF
               END IF
             END IF
             !
           END IF
           !
           ! 4.c Perform output type 3 ( source terms )
           !
         ELSE IF ( itype .EQ. 3 ) THEN
           !
           IF ( otype .EQ. 1 ) THEN
             !
             IF ( scale1 .GE. 0. ) THEN
               IF ( flsrce(1) )                              &
                    CALL prt1ds (ndso, nk, e1, sig(1:nk),     &
                    'RAD/S', 17,  0., 'E(f)', 'm^2s',    &
                    ptnme(j) )
               IF (flsrce(2) .OR. flsrce(3) .OR.             &
                    flsrce(4) .OR. flsrce(5) .OR.             &
                    flsrce(6) .OR. flsrce(7) )                &
                    CALL prt1dm (ndso, nk, 6, e1all, sig(1:nk),&
                    'RAD/S', 17, scale1, var1, 'M2',     &
                    ptnme(j) )
             END IF
             IF ( scale2 .GE. 0. ) THEN
               IF ( flsrce(1) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, e,        &
                    sig(1:nk), 'RAD/S', 1., 0., 0.0001,  &
                    'E(f,th)', 'm^2s', ptnme(j) )
               IF ( flsrce(2) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, swn,      &
                    sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                    'Sin(f,th)', 'm^2', ptnme(j) )
               IF ( flsrce(3) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, snl,      &
                    sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                    'Snl(f,th)', 'm^2', ptnme(j) )
               IF ( flsrce(4) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, sds,      &
                    sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                    'Sds(f,th)', 'm^2', ptnme(j) )
               IF ( flsrce(5) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, sbt,      &
                    sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                    'Sbt(f,th)', 'm^2', ptnme(j) )
               IF ( flsrce(6) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, sis,      &
                    sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                    'Sice(f,th)', 'm^2', ptnme(j) )
               IF ( flsrce(7) )                              &
                    CALL prt2ds (ndso, nk, nk, nth, stt,      &
                    sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                    'Stot(f,th)', 'm^2', ptnme(j) )
             END IF
             !
           ELSE IF ( otype .EQ. 2 ) THEN
             !
             CALL stme21 ( time , dtme21 )
             IF ( flagll ) THEN
               WRITE (ndstab,2920) dtme21, ptnme(j),         &
                    m2km*ptloc(1,j), m2km*ptloc(2,j),         &
                    dpo(j), ustar, wao(j)
             ELSE
               WRITE (ndstab,2720) dtme21, ptnme(j),         &
                    m2km*ptloc(1,j), m2km*ptloc(2,j),         &
                    dpo(j), ustar, wao(j)
             END IF
             IF ( iscale.EQ.0 ) THEN
               WRITE (ndstab,2921)
             ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
               WRITE (ndstab,2922)
             ELSE IF ( iscale.EQ.3 ) THEN
               WRITE (ndstab,2923)
             ELSE IF ( iscale.EQ.4 .OR. iscale.EQ.5 ) THEN
               WRITE (ndstab,2924)
             END IF
             IF ( iscale.GE.3 ) facf = 1. / fp
             DO ik=1, nk
               WRITE (ndstab,2930) facf*sig(ik), e1(ik),       &
                    sin1(ik), snl1(ik), sds1(ik), sbt1(ik),       &
                    sis1(ik), stt1(ik)
             END DO
             WRITE (ndstab,2940)
             !
           ELSE IF ( otype .EQ. 3 ) THEN
             !
             CALL stme21 ( time , dtme21 )
             IF ( flagll ) THEN
               WRITE (ndstab,2920) dtme21, ptnme(j),         &
                    m2km*ptloc(1,j), m2km*ptloc(2,j),         &
                    dpo(j), ustar, wao(j)
             ELSE
               WRITE (ndstab,2720) dtme21, ptnme(j),         &
                    m2km*ptloc(1,j), m2km*ptloc(2,j),         &
                    dpo(j), ustar, wao(j)
             END IF
             IF ( iscale.EQ.0 ) THEN
               WRITE (ndstab,2925)
             ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
               WRITE (ndstab,2926)
             ELSE IF ( iscale.EQ.3 ) THEN
               WRITE (ndstab,2927)
             ELSE IF ( iscale.EQ.4 .OR. iscale.EQ.5 ) THEN
               WRITE (ndstab,2928)
             END IF
             !
             IF ( iscale.GE.3 ) facf = 1. / fp
             DO ik=1, nk
               fact   = 1. / max( 1.e-10 , e1(ik) )
               IF ( e1(ik) .GT. 1.e-10 ) THEN
                 WRITE (ndstab,2931) facf*sig(ik), e1(ik),   &
                      fact*sin1(ik), fact*snl1(ik),             &
                      fact*sds1(ik), fact*sbt1(ik),             &
                      fact*sis1(ik),fact*stt1(ik)
               ELSE
                 WRITE (ndstab,2931) facf*sig(ik), e1(ik)
               END IF
             END DO
             WRITE (ndstab,2940)
             !
           ELSE IF ( otype .EQ. 4 ) THEN
             !
             IF ( flform ) THEN
               WRITE (ndstab) ptnme(j), ptloc(2,j),          &
                    ptloc(1,j), dpo(j), wao(j),    &
                    udir, cao(j), cdir
               IF ( flsrce(1) ) WRITE (ndstab)               &
                    ((e(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(2) ) WRITE (ndstab)               &
                    ((swn(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(3) ) WRITE (ndstab)               &
                    ((snl(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(4) ) WRITE (ndstab)               &
                    ((sds(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(5) ) WRITE (ndstab)               &
                    ((sbt(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(6) ) WRITE (ndstab)               &
                    ((sis(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(7) ) WRITE (ndstab)               &
                    ((stt(ik,ith),ik=1,nk),ith=1,nth)
             ELSE
               IF ( flagll ) THEN
                 WRITE (ndstab,901) ptnme(j),              &
                      m2km*ptloc(2,j), m2km*ptloc(1,j),     &
                      dpo(j), wao(j), udir, cao(j), cdir
               ELSE
                 WRITE (ndstab,701) ptnme(j),              &
                      m2km*ptloc(2,j), m2km*ptloc(1,j),     &
                      dpo(j), wao(j), udir, cao(j), cdir
               END IF
               IF ( flsrce(1) ) WRITE (ndstab,902)           &
                    ((e(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(2) ) WRITE (ndstab,902)           &
                    ((swn(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(3) ) WRITE (ndstab,902)           &
                    ((snl(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(4) ) WRITE (ndstab,902)           &
                    ((sds(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(5) ) WRITE (ndstab,902)           &
                    ((sbt(ik,ith),ik=1,nk),ith=1,nth)
               IF ( flsrce(6) ) WRITE (ndstab,902)           &
                    ((sis(ik,ith),ik=1,nk),ith=1, nth)
               IF ( flsrce(7) ) WRITE (ndstab,902)           &
                    ((stt(ik,ith),ik=1,nk),ith=1,nth)
             END IF
             !
           END IF
           !
           ! 4.d Perform output type 4 ( Spectral partitions and bulletins )
           !
         ELSE IF ( itype .EQ. 4 ) THEN
           !
           IF ( otype .EQ. 1 ) THEN
             !
             IF ( flagll ) THEN
               IF ( ptloc(1,j) .LT. 0. )                     &
                    ptloc(1,j) = ptloc(1,j) + 360.
               WRITE (ndstab,940) time, m2km*ptloc(2,j),     &
                    m2km*ptloc(1,j), ptnme(j), npart, depth,  &
                    wao(j), udir, cao(j), cdir
             ELSE
               WRITE (ndstab,943) time, m2km*ptloc(1,j),     &
                    m2km*ptloc(2,j), ptnme(j), npart, depth,  &
                    wao(j), udir, cao(j), cdir
             END IF
             !                   WRITE (NDSTAB,941)
             DO i=0, npart
               WRITE (ndstab,942) i, xpart(:,i)
             END DO
             !
           ELSEIF ( otype .GE. 2 ) THEN
             CALL w3bull (npart, xpart, dimxp, uabs,         &
                  udir, j, iout, timev )
             !
             IF ( flagll ) THEN
               x = m2km * ptloc(1,j)
               y = m2km * ptloc(2,j)
               x      = mod( x+720. , 360. )
               IF ( x .LE. 180. ) THEN
                 idlon  = 'E'
               ELSE
                 x      = 360. - x
                 idlon  = 'W'
               ENDIF
               !IF ( ABS(Y) .LE. 0.0049 ) THEN
               !IDLAT  = '-'
               IF ( y .GE. 0. ) THEN
                 idlat  = 'N'
               ELSE
                 idlat  = 'S'
                 y      = -y
               ENDIF
             ELSE
               idlat = ' '
               idlon = ' '
             ENDIF
             IF ( otype .EQ. 2 .OR. otype .EQ. 4 ) THEN
               ndsbul=ndstab + (j - 1)
 #ifdef W3_NCO
               ndscbul=ndstab + (j - 1) + nopts
 #endif
               IF (iout .EQ. 1) THEN
                 WRITE(hstr,'(I2,1X,A)') timev(2)/10000,   &
                      htype
                 WRITE (ndsbul,970) ptnme(j), y, idlat, x, &
                      idlon, gname, timev(1),  &
                      hstr
                 WRITE (ndsbul,971)
                 WRITE (ndsbul,972)
                 WRITE (ndsbul,971)
 #ifdef W3_NCO
                 WRITE (ndscbul,960) ptnme(j), y, idlat,   &
                      x, idlon, gname, timev(1), hstr
                 WRITE (ndscbul,961)
 #endif
               ENDIF
               WRITE (ndsbul,973) ascbline
 #ifdef W3_NCO
               WRITE (ndscbul,963) cascbline
 #endif
             ENDIF
             IF ( otype .EQ. 3 .OR. otype .EQ. 4 ) THEN
               icsv = 0
               IF ( ndsbul .GT. 0 ) icsv = ndsbul
 #ifdef W3_NCO
               IF ( ndscbul .GT. 0 ) icsv = ndscbul
 #endif
               ndscsv = ndstab + (j - 1) + icsv
               WRITE (ndscsv,'(A664)') csvbline
             ENDIF
           END IF
           !
         END IF
         ! ... End of fields loop
         !
       END IF
     END DO
     !
     RETURN
     !
     ! Formats
     !
 900 FORMAT (i8.8,i7.6)
 901 FORMAT ('''',a10,'''',2f7.2,f10.1,2(f7.2,f6.1))
 701 FORMAT ('''',a10,'''',2(f8.1,'E3'),f10.1,2(f7.2,f6.1))
 902 FORMAT (7e11.3)
 905 FORMAT (9x,a)
 910 FORMAT (/15x,' Water depth       :',f7.1,'  (m)'/               &
          15x,' Wind speed        :',f8.2,' (m/s)')
 911 FORMAT ( 15x,' Wind direction    :',f7.1,'  (degr)')
 912 FORMAT ( 15x,' Air-sea temp. dif.:',f7.1,'  (degr)'/            &
          15x,' Current speed     :',f8.2,' (m/s)')
 913 FORMAT ( 15x,' Current direction :',f7.1,'  (degr)')
 914 FORMAT ( 15x,' Wave height       :',f8.2,' (m)'/                &
          15x,' Mean wave length  :',f6.0,'   (m)'/              &
          15x,' Mean wave period  :',f7.1,'  (s)'/               &
          15x,' Mean wave direct. :',f7.1,'  (degr)'/            &
          15x,' Direct. spread    :',f7.1,'  (degr)'/)
 920 FORMAT (' Time     : ',a/                                  &
          ' Location : ',a,'  (',2f8.2,' )'/                 &
          ' depth    : ',f7.1,'   m'/                        &
          ' U*       : ',f9.3,' m/s'/                        &
          ' U10      : ',f7.1,'   m/s'/                      &
          ' Dir U10  : ',f7.1,'   degr'//                    &
          '      f     f/fp      F(f)    theta    spr    alpha  '/  &
          '     (Hz)    (-)     (m2s)    (deg)   (deg)    (-)   '/  &
          '  --------------------------------------------------')
 720 FORMAT (' Time     : ',a/                                  &
          ' Location : ',a,'  (',2(f8.1,'E3'),' )'/          &
          ' depth    : ',f7.1,'   m'/                        &
          ' U*       : ',f9.3,' m/s'/                        &
          ' U10      : ',f7.1,'   m/s'/                      &
          ' Dir U10  : ',f7.1,'   degr'//                    &
          '      f     f/fp      F(f)    theta    spr    alpha  '/  &
          '     (Hz)    (-)     (m2s)    (deg)   (deg)    (-)   '/  &
          '  --------------------------------------------------')
 921 FORMAT (1x,f8.5,f7.3,e11.3,2f8.1,f8.4)
 922 FORMAT (' '/' ')
     !
 940 FORMAT (1x,i8.8,1x,i6.6,2f8.3,2x,'''',a10,'''',            &
          1x,i3,f7.1,f5.1,f6.1,f5.2,f6.1)
 943 FORMAT (1x,i8.8,1x,i6.6,2(f8.1,'E3'),2x,'''',a10,'''',     &
          1x,i3,f7.1,f5.1,f6.1,f5.2,f6.1)
 941 FORMAT ('        hs     tp     lp       theta     sp      wf')
 942 FORMAT (i3,3f8.2,2f9.2,10f7.2)
     !
     !
 #ifdef W3_NCO
 960 FORMAT ( 'Location : ',a,' (',f5.2,a,1x,f6.2,a,')'/              &
          'Model    : ',a/                                       &
          'Cycle    : ',i8,1x,a//                                &
          'DDHH HS SS PP DDD SS PP DDD SS PP DDD',               &
          ' SS PP DDD SS PP DDD SS PP DDD')
 961 FORMAT ('----------------------------------------',              &
          '---------------------------')
 963 FORMAT (a)
 #endif
     !
 970 FORMAT ( '  Location : ',a,' (',f5.2,a,1x,f6.2,a,')'/            &
          '  Model    : ',a/                                      &
          '  Cycle    : ',i8,1x,a)
 971 FORMAT (' +-------+-----------+-----------------+',              &
          '-----------------+-----------------+----',              &
          '-------------+-----------------+--------',              &
          '---------+')
 972 FORMAT (' | day & |  Hst  n x |    Hs   Tp  dir |',              &
          '    Hs   Tp  dir |',              &
          '    Hs   Tp  dir |',              &
          '    Hs   Tp  dir |',              &
          '    Hs   Tp  dir |',              &
          '    Hs   Tp  dir |'/              &
          ' |  hour |  (m)  - - |    (m)  (s) (d) |',              &
          '    (m)  (s) (d) |',              &
          '    (m)  (s) (d) |',              &
          '    (m)  (s) (d) |',              &
          '    (m)  (s) (d) |',              &
          '    (m)  (s) (d) |')
 973 FORMAT (1x,a)
     !
 1901 FORMAT (                                                        &
          '    Date     Time        d     Uc     Dir.  U10    Dir. '/    &
          '            h  m  s     (m)   (m/s)  (d.N) (m/s)  (d.N) '/    &
          ' ---------------------------------------------------------')
 1902 FORMAT (                                                        &
          '    Date     Time        Hs     L      Tr    Dir.  Spr. ',    &
          '    fp    p_dir  p_spr'/                                      &
          '            h  m  s     (m)    (m)    (s)   (d.N)  (deg)',    &
          '   (Hz)   (d.N)  (deg)'/                                      &
          ' -------------------------------------------------------',    &
          '-----------------------')
 1903 FORMAT (                                                        &
          '    Date     Time       U*       E*        fp*       Cd   alpha'/&
          '            h  m  s   (m/s)     (-)        (-)     *1000  *100'/ &
          ' --------------------------------------------------------------')
 1904 FORMAT (                                                        &
          '    Date     Time     U10       E*        fp*       Cd   alpha'/&
          '            h  m  s  (m/s)     (-)        (-)     *1000  *100'/ &
          ' --------------------------------------------------------------')
 1905 FORMAT (                                                        &
          '   Date     Time     U10    Dir.    Hs      H*    cp/U  ',    &
          '  cm/U     Dt'/                                           &
          '                    (m/s)  (d.N)   (m)     (-)    (-)   ',    &
          '   (-)   (deg)'/                                          &
          ' --------------------------------------------------',          &
          '---------------------')
 1906 FORMAT (                                                         &
          '     Time      U10    Dir. Hs  Tp  '/         &
          '  yr mth dy h  (m/s) (d.N) (m) (s) '/         &
          ' ----------------------------------')
 1910 FORMAT ( ' '/' ' )
 1911 FORMAT (' Time : ',a//                                     &
          '    Long.    Lat.       d     Uc     Dir.  U10    Dir. '/    &
          '                       (m)   (m/s)  (d.N) (m/s)  (d.N) '/    &
          ' --------------------------------------------------------')
 1912 FORMAT (' Time : ',a//                                     &
          '    Long.    Lat.       Hs     L      Tr    Dir.  Spr. ',    &
          '    fp    p_dir  p_spr'/                                     &
          '                       (m)    (m)    (s)   (d.N)  (deg)',    &
          '   (Hz)   (d.N)  (deg)'/                                     &
          ' ------------------------------------------------------',    &
          '-----------------------')
 1711 FORMAT (' Time : ',a//                                     &
          '       X        Y          d     Uc     Dir.  U10    Dir. '/ &
          '      (m)      (m)        (m)   (m/s)  (d.N) (m/s)  (d.N) '/ &
          ' ----------------------------------------------------------')
 1712 FORMAT (' Time : ',a//                                     &
          '       X        Y          Hs     L      Tr    Dir.  Spr. ', &
          '    fp    p_dir  p_spr'/                                     &
          '      (m)      (m))       (m)    (m)    (s)   (d.N)  (deg)', &
          '   (Hz)   (d.N)  (deg)'/                                     &
          ' ------------------------------------------------------',    &
          '-------------------------')
 1913 FORMAT (' Time : ',a//                                          &
          '       X*       Y*       U*       E*        fp*       Cd   alpha'/&
          '      (-)      (-)     (m/s)     (-)        (-)     *1000  *100'/ &
          ' --------------------------------------------------------------')
 1914 FORMAT (' Time : ',a//                                          &
          '       X*       Y*     U10       E*        fp*       Cd   alpha'/ &
          '      (-)      (-)    (m/s)     (-)        (-)     *1000  *100 '/ &
          ' --------------------------------------------------------------')
 1915 FORMAT (' Time : ',a//                                     &
          '     Long.    Lat.   U10    Dir.    Hs      H*    cp/U  ',   &
          '  cm/U     Dt'/                                          &
          '                    (m/s)  (d.N)   (m)     (-)    (-)   ',   &
          '   (-)   (deg)'/                                         &
          ' -------------------------------------------------',         &
          '---------------------')
 1715 FORMAT (' Time : ',a//                                     &
          '       X        Y      U10    Dir.    Hs      H*    cp/U  ', &
          '  cm/U     Dt'/                                          &
          '      (m)      (m)    (m/s)  (d.N)   (m)     (-)    (-)   ', &
          '   (-)   (deg)'/                                         &
          ' ---------------------------------------------------',       &
          '---------------------')
 1916 FORMAT (' Time : ',a//                                     &
          '   Long.     Lat.   U10   Dir.     Hs      Tp  '/         &
          '                 (m/s)   (d.N)    (m)     (s)  '/         &
          '-----------------------------------------------')
 1716 FORMAT (' Time : ',a//                                     &
          '     X      Y      U10      Dir.      Hs       Tp  '/         &
          '    (m)    (m)    (m/s)    (d.N)     (m)      (s)  '/         &
          '---------------------------------------------------')
 1921 FORMAT ( 2x,i8.8,i3,2(1x,i2.2),f10.1,f6.2,f7.1,f6.2,f7.1)
 1922 FORMAT ( 2x,i8.8,i3,2(1x,i2.2),f9.3,f7.1,f7.2,f7.1,f7.2,        &
          f8.4,f7.1,f7.2)
 1923 FORMAT ( 2x,i8.8,i3,2(1x,i2.2),f8.4,2e11.3,2f7.3)
 1924 FORMAT ( 2x,i8.8,i3,2(1x,i2.2),f7.1,2e11.3,2f7.3)
 1925 FORMAT ( 2x,i8.8,i3,2(1x,i2.2),f7.2,f7.1,2f7.2,2f8.2,f7.1)
 1926 FORMAT ( 2x,i4,3(1x,i2),f6.2,1x,i3,2f6.2)
 1931 FORMAT ( 2x,2f8.3,f10.1,f6.2,f7.1,f6.2,f7.1)
 1932 FORMAT ( 2x,2f8.3,f9.3,f7.1,f7.2,f7.1,f7.2,                &
          f8.4,f7.1,f7.2)
 1731 FORMAT ( 2x,2(f7.1,'E3'),f10.1,f6.2,f7.1,f6.2,f7.1)
 1732 FORMAT ( 2x,2(f7.1,'E3'),f9.3,f7.1,f7.2,f7.1,f7.2,         &
          f8.4,f7.1,f7.2)
 1933 FORMAT ( 2x,2(f7.1,'E4'),f8.4,2e11.3,2f7.3)
 1934 FORMAT ( 2x,2f9.1,f7.1,2e11.3,2f7.3)
 1935 FORMAT ( 2x,2f8.3,f7.2,f7.1,2f7.2,2f8.2,f7.1)
 1735 FORMAT ( 2x,2(f7.1,'E3'),f7.2,f7.1,2f7.2,2f8.2,f7.1)
 1936 FORMAT ( 2x,2f8.3,f6.2,1x,i3,2f6.2)
 1736 FORMAT ( 2x,2(f8.2,'E3'),f6.2,1x,i3,2f6.2)
     !
 2920 FORMAT (' Time     : ',a/                                  &
          ' Location : ',a,'  (',2f8.2,' )'/                 &
          ' depth    : ',f7.1,'   m'/                        &
          ' U*       : ',f9.3,' m/s'/                        &
          ' U10      : ',f7.1,'   m/s'/)
 2720 FORMAT (' Time     : ',a/                                  &
          ' Location : ',a,'  (',2(f8.1,'E3'),' )'/          &
          ' depth    : ',f7.1,'   m'/                        &
          ' U*       : ',f9.3,' m/s'/                        &
          ' U10      : ',f7.1,'   m/s'/)
 2921 FORMAT ('    f           E      ',                              &
          '    Sin        Snl        Sds        Sbt       Sice       Stot'/  &
          '   (Hz)       (m2s)    ',                              &
          '   (m2)       (m2)       (m2)       (m2)       (m2)       (m2)'/  &
          ' ------------------------------------------',               &
          '-------------------------------------------')
 2922 FORMAT ('    f*          E*    ',                               &
          '    Sin*       Snl*       Sds*       Sbt*      Sice*      Stot*'/ &
          '   (-)         (-)    ',                               &
          '    (-)        (-)        (-)        (-)        (-)        (-)'/  &
          ' ------------------------------------------',               &
          '-------------------------------------------')
 2923 FORMAT ('   f/fp         E      ',                              &
          '   Sin        Snl        Sds        Sbt       Sice      Stot'/   &
          '   (-)        (m2s)    ',                              &
          '  (m2)       (m2)       (m2)       (m2)       (m2)      (m2)'/   &
          ' ------------------------------------------',               &
          '-------------------------------------------')
 2924 FORMAT ('   f/fp         E*     ',                              &
          '   Sin*       Snl*       Sds*       Sbt*      Sice*      Stot*'/  &
          '     (-)       (-)     ',                              &
          '   (-)        (-)        (-)        (-)        (-)        (-)'/   &
          ' ------------------------------------------',               &
          '-------------------------------------------')
 2925 FORMAT ('    f         E      ',                                &
          '  Tini       Tnli       Tdsi       Tbti      Ticei      Ttoti'/   &
          '   (Hz)     (m2s)    ',                                &
          ' (1/s)      (1/s)      (1/s)      (1/s)      (1/s)      (1/s)'/   &
          ' ----------------------------------------',                 &
          '-------------------------------------------')
 2926 FORMAT ('    f*        E*     ',                                &
          ' Tini*      Tnli*      Tdsi*      Tbti*     Ticei*      Ttoti*'/   &
          '   (-)       (-)     ',                                &
          '  (-)        (-)        (-)        (-)        (-)        (-)'/    &
          ' ----------------------------------------',                 &
          '-------------------------------------------')
 2927 FORMAT ('   f/fp       E      ',                                &
          '  Tini       Tnli       Tdsi       Tbti      Ticei      Ttoti'/   &
          '   (-)       (m2s)    ',                               &
          ' (1/s)      (1/s)      (1/s)      (1/s)      (1/s)      (1/s)'/   &
          ' ----------------------------------------',                 &
          '-------------------------------------------')
 2928 FORMAT ('   f/fp       E*     ',                                &
          ' Tini*      Tnli*      Tdsi*      Tbti*     Ticei*      Ttoti*'/   &
          '   (-)       (-)     ',                                &
          '  (-)        (-)        (-)        (-)        (-)        (-)'/    &
          ' ----------------------------------------',                 &
          '-------------------------------------------')
 2930 FORMAT (1x,f6.4,2x,7e11.3)
 2931 FORMAT (1x,f6.4,7e11.3)
 2940 FORMAT ( ' '/' ' )
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3EXPO : FLAGS :',40l2)
 9001 FORMAT (' TEST W3EXPO : ITPYE  :',i4/                        &
          '               OTPYE  :',i4/                        &
          '               NREQ   :',i4/                        &
          '               SCALE1 :',e10.3/                     &
          '               SCALE2 :',e10.3/                     &
          '               FLSRCE :',7l2)
 9002 FORMAT (' TEST W3EXPO : OUTPUT POINT : ',a)
 9010 FORMAT (' TEST W3EXPO : DEPTH =',f7.1,'  IK, T, K, CG :')
 9011 FORMAT ('               ',i3,f8.2,f8.4,f8.2)
 #endif
     !/
     !/ End of W3EXPO ----------------------------------------------------- /
     !/
References constants::dair, constants::dera, w3dispmd::dfac, w3dispmd::dsie, constants::dwat, w3dispmd::ecg1, w3dispmd::ewn1, constants::grav, w3gdatmd::iicedisp, w3dispmd::liu_forward_dispersion(), w3dispmd::n1max, w3dispmd::nar1d, w3arrymd::prt1dm(), w3arrymd::prt1ds(), w3arrymd::prt2ds(), constants::rade, constants::radius, w3gdatmd::swl6s6, constants::tpi, constants::tpiinv, w3bullmd::w3bull(), w3flx1md::w3flx1(), w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3flx4md::w3flx4(), w3flx5md::w3flx5(), w3partmd::w3part(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snl1md::w3snlgqm(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3swldmd::w3swl6(), and w3dispmd::wavnu1().
Referenced by w3outp().
w3outp()
program w3outp
Post-processing of point output.
Data is read from the grid output file out_pnt.ww3 (raw data) and from the file ww3_outp.inp (NDSI, output requests). Model definition and raw data files are read using WAVEWATCH III subroutines.
Author
H. L. Tolman
J.H. Alves
A. Chawla
F. Ardhuin
E. Rogers
T. Campbell
Date
27-Aug-2015
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Definition at line 36 of file ww3_outp.F90.
References w3bullmd::ascbline, w3odatmd::aso, w3bullmd::bhsdrop, w3bullmd::bhsmin, w3bullmd::cascbline, w3bullmd::csvbline, w3odatmd::dimp, w3bullmd::dmt, w3odatmd::dpo, w3timemd::dsec21(), w3servmd::extcde(), file(), constants::file_endian, w3odatmd::fnmpre, w3odatmd::grdid, w3bullmd::hst, w3servmd::itrace(), w3bullmd::iyy, w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3bullmd::nfld, w3odatmd::nopts, w3bullmd::npmax, w3bullmd::nptab, constants::pi, w3odatmd::ptloc, w3odatmd::ptnme, w3timemd::stme21(), w3servmd::strace(), w3timemd::tick21(), w3wdatmd::time, constants::tpi, constants::tpiinv, w3bullmd::tpt, constants::undef, w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3expo(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3iopomd::w3iopon_read(), w3iopomd::w3iopon_write(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3odatmd::wao, and w3odatmd::wdo.