WAVEWATCH III: ww3_sbs1.F90 File Reference
ww3_sbs1.F90 File Reference
Contains program W3SBS1.
Functions/Subroutines
program w3sbs1
Program shell to run multi half-coupled.
subroutine rdtime (NDS, TIME)
Internal subroutine to get next time in time file.
subroutine rdwind (NDS, TIME, NX, NY, REWIND)
Internal subroutine to test readnext wind fields from the data file.
Detailed Description
Contains program W3SBS1.
Author
H. L. Tolman
A. Chawla
Date
05-Dec-2012
Definition in file ww3_sbs1.F90.
Function/Subroutine Documentation
rdtime()
subroutine w3sbs1::rdtime (integer, intent(in) NDS, integer, dimension(2), intent(out) TIME)
Internal subroutine to get next time in time file.
Including wait until file is there.
Parameters
[in] NDS Unit number for times file.
[out] TIME Next time in times file.
Author
H. L. Tolman
Date
05-Dec-2012
Definition at line 404 of file ww3_sbs1.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH-III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         05-Dec-2012 !
     !/                  +-----------------------------------+
     !/
     !/    10-Aug-2010 : Origination.                      ( version 3.14.4 )
     !/    05-Dec-2012 : Making sleep a system call.       ( version 4.11   )
     !/
     !  1. Purpose :
     !
     !     Internal subroutine to get next time in time file, including
     !     waiting until the file is there.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDS     Int.   I   Unit number for times file.
     !       TIME    I.A.   O   Next time in times file.
     !     ----------------------------------------------------------------
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDS
     INTEGER, INTENT(OUT)    :: TIME(2)
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
 #ifdef W3_SBS
     CHARACTER(LEN=10)       :: COMMAND
 #endif
     !/
     ! -------------------------------------------------------------------- /
     ! 1.  Reading loop
     !
     DO
       !
       READ (nds,910,END=110,ERR=810,IOSTAT=IERR) time
       EXIT
       !
 110   CONTINUE
       IF ( improc .EQ. nmpscr ) WRITE (mdss, 911 )
       backspace nds
       !
 #ifdef W3_SBS
       WRITE (command,'(A5,1X,I4)') 'sleep ', sleep1
       CALL system ( command )
 #endif
       !
     END DO
     !
     RETURN
     !
     ! Escape locations read errors --------------------------------------- *
     !
 810 CONTINUE
     WRITE (mdss,1010) ierr
     CALL extcde ( 10 )
     !
     ! Formats
     !
 910 FORMAT (1x,i8,1x,i6)
     !
 911 FORMAT (/'    END OF TIMES FILE REACHED FOR WIND DATA '/        &
          '       WAITING BEFORE CHECKING AGAIN')
     !
 1010 FORMAT (/' *** WAVEWATCH-III ERROR IN W3SBS1/RDTIME : '/        &
          '     ERROR IN OPENING TIMES FILE'/                   &
          '     IOSTAT =',i5/)
     !/
     !/ End of RDTIME ----------------------------------------------------- /
     !/
References w3servmd::extcde(), wmmdatmd::improc, wmmdatmd::mdss, and wmmdatmd::nmpscr.
Referenced by w3sbs1().
rdwind()
subroutine w3sbs1::rdwind (integer, intent(in) NDS, integer, dimension(2), intent(in) TIME, integer, intent(in) NX, integer, intent(in) NY, logical, intent(in) REWIND)
Internal subroutine to test readnext wind fields from the data file.
Including testing to see if file was read properly.
Parameters
[in] NDS Unit number for times file.
[in] TIME Next time in times file.
[in] NX Grid size in X
[in] NY Grid size in Y
[in] REWIND Flag for wind file rewind
Author
H. L. Tolman
Date
05-Dec-2012
Definition at line 500 of file ww3_sbs1.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH-III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         05-Dec-2012 !
     !/                  +-----------------------------------+
     !/
     !/    10-Aug-2010 : Origination.                      ( version 3.14.4 )
     !/    05-Dec-2012 : Making sleep a system call.       ( version 4.11   )
     !/
     !  1. Purpose :
     !
     !     Internal subroutine to test readnext wind fields from the data
     !     file, including testing to see if file was read properly.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NDS     Int.   I   Unit number for times file.
     !       TIME    I.A.   I   Next time in times file.
     !       NX,NY   Int.   I   Grid size.
     !       REWIND  Log.   I   Flag for wind file rewind.
     !     ----------------------------------------------------------------
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NDS, TIME(2), NX, NY
     LOGICAL, INTENT(IN)     :: REWIND
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: TTIME(2), IX, IY
     INTEGER, SAVE           :: NREW  = 0
     REAL                    :: DTTST, XXX(NX,NY)
 #ifdef W3_SBS
     CHARACTER(LEN=10)       :: COMMAND
 #endif
     !
     ! -------------------------------------------------------------------- /
     ! 1.  Loops
     !
     DO
       !
       ! ... Inner loop reading
       !
       DO
         !
         nrew   = nrew + 1
         READ (nds,END=140,ERR=140) ttime
 #ifdef W3_T
         WRITE (mdst,9000) ttime
 #endif
         !
         nrew   = nrew + 1
         READ (nds,END=130,ERR=130) ((XXX(IX,IY),IX=1,NX),IY=1,NY)
 #ifdef W3_T
         WRITE (mdst,9001) 'U'
 #endif
         !
         nrew   = nrew + 1
         READ (nds,END=120,ERR=120) ((XXX(IX,IY),IX=1,NX),IY=1,NY)
 #ifdef W3_T
         WRITE (mdst,9001) 'V'
 #endif
         !
         IF ( TYPE .EQ. 'WNS' ) then
           nrew   = nrew + 1
           READ (nds,END=110,ERR=110) ((XXX(IX,IY),IX=1,NX),IY=1,NY)
 #ifdef W3_T
           WRITE (mdst,9001) 'DT'
 #endif
         END IF
         !
         EXIT
         !
 110     CONTINUE
         backspace nds
         nrew   = nrew - 1
 120     CONTINUE
         backspace nds
         nrew   = nrew - 1
 130     CONTINUE
         backspace nds
         nrew   = nrew - 1
 140     CONTINUE
         backspace nds
         nrew   = nrew - 1
         !
         IF ( improc .EQ. nmpscr ) WRITE (mdss,900)
         !
 #ifdef W3_SBS
         WRITE (command,'(A5,1X,I4)') 'sleep ', sleep2
         CALL system ( command )
 #endif
         !
       END DO
       !
       ! ... Outer loop catching up
       !
       dttst  = dsec21( time , ttime )
       !
       IF ( dttst .LT. 0. ) THEN
         IF ( improc .EQ. nmpscr ) WRITE (mdss,901) ttime
       ELSE IF ( dttst .EQ. 0. ) THEN
         EXIT
       ELSE
         GOTO 800
       END IF
       !
     END DO
     !
     ! ... Rewind all
     !
     IF ( rewind ) THEN
       !
       IF ( improc.EQ.nmpscr .AND. nrew.GT.4 ) WRITE (mdss,902) nrew
       !
       DO i=1, nrew
         backspace nds
       END DO
       !
       nrew   = 0
       !
     END IF
     !
     RETURN
     !
     ! Escape locations read errors --------------------------------------- *
     !
 800 CONTINUE
     WRITE (mdss,1010)
     CALL extcde ( 10 )
     !
     ! Formats
     !
 900 FORMAT ('       FILE NOT YET COMPLETE ... ')
 901 FORMAT ('         SKIPPING FILE FOR ',i8.8,i7.6)
 902 FORMAT ('         REWINDING FILE BY ',i4,' RECORDS')
     !
 1010 FORMAT (/' *** WAVEWATCH-III ERROR IN W3SBS1/RDWIND : '/        &
          '     FILE READ PAST EXPECTED TIME '/)
     !
 #ifdef W3_T
 9000 FORMAT ( ' TEST RDWIND: TIME READ ',i8.8,1x,i6.6)
 9001 FORMAT ( '              FIELD READ ',a)
 #endif
     !/
     !/ End of RDWIND ----------------------------------------------------- /
     !/
Referenced by w3sbs1().
w3sbs1()
program w3sbs1
Program shell to run multi half-coupled.
Program shell or driver to run the multi-grid wave model in 'half-coupled' mode, that is running side-by-side with a weather model while waiting for wind field to become available.
This version is set up for running at NCEP with a single input wind file, and requires an additional input file. times.inp Input file with time stamps. Add to this input file a time stamp after the field has been properly added to the wind.ww3 or equavalent file. This file should have the time stamps of fields available in the first auxiliary wind input file (grid).
Apart from management of the time stepping, this code is identical to ww3_multi.ftn, and reads the corresponding input file ww3_multi.inp
Note hardwired options and system dependent parts as identified in Section 7.
Author
H. L. Tolman
A. Chawla
Date
05-Dec-2012
Definition at line 36 of file ww3_sbs1.F90.
References w3timemd::dsec21(), wmmdatmd::etime, w3servmd::extcde(), file(), w3gdatmd::filext, w3idatmd::flwind, w3gdatmd::gname, wmmdatmd::improc, include(), wmmdatmd::mdse, wmmdatmd::mdsf, wmmdatmd::mdss, wmmdatmd::mdst, w3gdatmd::nauxgr, w3gdatmd::ngrids, wmmdatmd::nmproc, wmmdatmd::nmpscr, wmmdatmd::nrgrd, w3gdatmd::nx, w3gdatmd::ny, rdtime(), rdwind(), wmmdatmd::stime, w3gdatmd::w3setg(), w3idatmd::w3seti(), wmfinlmd::wmfinl(), wminitmd::wminit(), wmunitmd::wmuget(), wmunitmd::wmuset(), and wmwavemd::wmwave().