WAVEWATCH III: ww3_ounf.F90 File Reference
ww3_ounf.F90 File Reference
Contains program for NetCDF grid output.
Functions/Subroutines
program w3ounf
Post-processing of grid output to NetCDF files.
subroutine w3exnc (NX, NY, IX1, IXN, IY1, IYN, NSEA, FILEPREFIX, E3DF, P2MSF, US3DF, USSPF, NCTYPE, TOGETHER, NCVARTYPEI, FLG2D, NCIDS, S3, STRSTOPDATE)
Perform actual grid output in NetCDF file.
subroutine w3crnc (NCFILE, NCID, DIMID, DIMLN, VARID, EXTRADIM, NCTYPE, MAPSTAOUT)
Desc not available.
subroutine s2grid (S, X, FLDIRN)
Expand the seapoint array to full grid with handling of SMC regridding.
subroutine uv_to_mag_dir (U, V, TOLERANCE)
Converts fields formulated as U/V vectors into magnitude and direction fields.
subroutine check_error (IRET, ILINE)
Desc not available.
Detailed Description
Contains program for NetCDF grid output.
Author
F. Ardhuin
M. Accensi
Date
02-Sep-2021
Definition in file ww3_ounf.F90.
Function/Subroutine Documentation
check_error()
subroutine w3ounf::check_error (integer IRET, integer ILINE)
Desc not available.
Parameters
IRET
ILINE
Author
NA
Date
NA
Definition at line 3904 of file ww3_ounf.F90.
     USE netcdf
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
     IMPLICIT NONE
     INTEGER IRET, ILINE
     IF (iret .NE. nf90_noerr) THEN
       WRITE(ndse,*) ' *** WAVEWATCH III ERROR IN OUNF :'
       WRITE(ndse,*) ' LINE NUMBER ', iline
       WRITE(ndse,*) ' NETCDF ERROR MESSAGE: '
       WRITE(ndse,*) nf90_strerror(iret)
       CALL extcde ( 59 )
     END IF
     RETURN
References w3servmd::extcde(), and w3odatmd::ndse.
s2grid()
subroutine w3ounf::s2grid (real, dimension(:), intent(inout) S, real, dimension(:,:), intent(out) X, logical, intent(in), optional FLDIRN)
Expand the seapoint array to full grid with handling of SMC regridding.
The FLDIRN flag should be set to true for directional fields. In this case, they will be decomposed into U/V components for SMC grid interpolation and converted to oceanograhic convention.
Parameters
[in,out] S Sea point array
[out] X Gridded array
[in] FLDIRN Directional field flag
Author
C Bunney
Date
03-Nov-2021
Definition at line 3788 of file ww3_ounf.F90.
     !/
     !/                  +-----------------------------------+
     !/                  |           C . Bunney              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         03-Nov-2020 |
     !/                  +-----------------------------------+
     !/
     !/    03-Nov-2020 : Creation                            ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Exapand the seapoint array to full grid with handling of
     !     SMC regridding. The FLDIRN flag should be set to true for
     !     directional fields. In this case, they will be decomposed
     !     into U/V components for SMC grid interpolation and converted
     !     to oceanograhic convention.
     !
     !  2. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       S       Real. I  Sea point array
     !       X       Real. O  Gridded array
     !       FLDIRN  Bool. I  Directional field flag
     !     ----------------------------------------------------------------
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY : w3s2xy
     IMPLICIT NONE
     REAL, INTENT(INOUT)  :: S(:)
     REAL, INTENT(OUT) :: X(:,:)
     LOGICAL, OPTIONAL, INTENT(IN) :: FLDIRN
     LOGICAL :: FLDR
     INTEGER :: ISEA
     fldr = .false.
     IF(PRESENT(fldirn)) fldr = fldirn
 #ifdef W3_SMC
     IF( smcgrd ) THEN
       CALL w3s2xy_smc( s, x, fldr )
     ELSE ! IF(SMCGRD)
 #endif
       IF(fldr) THEN
         DO isea=1, nsea
           IF (s(isea) .NE. undef )  THEN
             s(isea) = mod( 630. - rade * s(isea) , 360. )
           END IF
         END DO
       ENDIF
       ! Change UNDEF sea points to NOVAL, if set differently
       IF(noval .NE. undef) WHERE(s .EQ. undef) s = noval
       CALL w3s2xy ( nsea, nsea, nx+1, ny, s, mapsf, x )
 #ifdef W3_SMC
     ENDIF
 #endif
References constants::rade, constants::undef, and w3servmd::w3s2xy().
Referenced by w3exnc().
uv_to_mag_dir()
subroutine w3ounf::uv_to_mag_dir (real, dimension(:), intent(inout) U, real, dimension(:), intent(inout) V, real, intent(in), optional TOLERANCE)
Converts fields formulated as U/V vectors into magnitude and direction fields.
Conversion is done in-place. U becomes magnitude, V becomes direction. Optional TOLERANCE sets minimum magnitude.
Parameters
[in,out] U
[in,out] V
[in] Tolerance
Author
NA
Date
NA
Definition at line 3866 of file ww3_ounf.F90.
     ! Converts fields formulated as U/V vectors into
     ! magnitude and direction fields. Conversion is
     ! done in-place. U becomes magnitude, V becomes
     ! direction. Optional TOLERANCE sets minimum
     ! magnitude.
     IMPLICIT NONE
     REAL, INTENT(INOUT) :: U(:), V(:)
     REAL, INTENT(IN), OPTIONAL :: TOLERANCE
     REAL :: TOL = 1.0
     REAL :: MAG ! Magnitude
     INTEGER :: ISEA
     IF(PRESENT(tolerance)) tol = tolerance
     DO isea=1, nsea
       mag   = sqrt(u(isea)**2 + v(isea)**2)
       IF(mag .GT. tol) THEN
         v(isea) = mod( 630. - rade * atan2(u(isea), v(isea)), 360. )
       ELSE
         v(isea) = undef
         ! TODO - Setting V to undef does not work as later the write
         ! function only checks the U value. Set both to udef?
       END IF
       u(isea) = mag
     END DO
References constants::rade, and constants::undef.
Referenced by w3exnc().
w3crnc()
subroutine w3ounf::w3crnc (character*(*), intent(in) NCFILE, integer, intent(out) NCID, integer, dimension(6), intent(out) DIMID, integer, dimension(6), intent(in) DIMLN, integer, dimension(300), intent(out) VARID, integer, intent(in) EXTRADIM, integer, intent(in) NCTYPE, logical, intent(in) MAPSTAOUT)
Desc not available.
Parameters
[in] NCFILE
[out] NCID
[out] DIMID
[in] DIMLN
[out] VARID
[in] EXTRADIM
[in] NCTYPE
[in] MAPSTAOUT
Author
NA
Date
NA
Definition at line 3290 of file ww3_ounf.F90.
     !
     USE w3gdatmd, ONLY : gtype, flagll, ungtype, clgtype, rlgtype
 #ifdef W3_RTD
     ! Rotated pole parameters from the mod_def file
     USE w3gdatmd, ONLY : polat, polon
 #endif
     USE netcdf
     USE w3timemd
     IMPLICIT NONE
     INTEGER, INTENT(IN)               :: EXTRADIM
     INTEGER, INTENT(IN)               :: NCTYPE
     CHARACTER*(*), INTENT(IN)         :: NCFILE
     INTEGER, INTENT(OUT)              :: NCID
     INTEGER, INTENT(OUT)              :: DIMID(6)
     INTEGER, INTENT(IN)               :: DIMLN(6)
     INTEGER, INTENT(OUT)              :: VARID(300)
     LOGICAL, INTENT(IN)               :: MAPSTAOUT
     !
     !/ ------------------------------------------------------------------- /
     !   Local parameters
     !
     INTEGER                           :: IVAR,IRET,ICODE,STRL,STRL2
     INTEGER                           :: DIMTRI(2)
     INTEGER                           :: DEFLATE=1
     !
     CHARACTER                         :: ATTNAME*120,ATTVAL*120
     !
     coords_attr = ''
     !
     ! Creation in netCDF3 or netCDF4
     !
     IF(nctype.EQ.3) iret = nf90_create(trim(ncfile), nf90_clobber, ncid)
     IF(nctype.EQ.4) iret = nf90_create(trim(ncfile), nf90_netcdf4, ncid)
     CALL check_err(iret)
     !
     ! Define dimensions
     !
     iret = nf90_def_dim(ncid, 'level', dimln(1), dimid(1))
     !
     ! Regular structured case
     !
     IF (gtype.NE.ungtype) THEN
       IF (flagll) THEN
 #ifdef W3_SMC
         IF(smcgrd .AND. smcotype .EQ. 1) THEN
           ! Flat seapoints file
           iret = nf90_def_dim(ncid, 'seapoint', dimln(2), dimid(2))
         ELSE
 #endif
           ! Regular gridded file:
           iret = nf90_def_dim(ncid, 'longitude', dimln(2), dimid(2))
           iret = nf90_def_dim(ncid, 'latitude', dimln(3), dimid(3))
 #ifdef W3_SMC
         ENDIF
 #endif
       ELSE
         iret = nf90_def_dim(ncid, 'x', dimln(2), dimid(2))
         iret = nf90_def_dim(ncid, 'y', dimln(3), dimid(3))
       END IF
       CALL check_err(iret)
       !
       ! Unstructured case
       !
     ELSE
       iret = nf90_def_dim(ncid, 'node', dimln(2), dimid(2))
       iret = nf90_def_dim(ncid, 'element', dimln(3), dimid(3))
       CALL check_err(iret)
     ENDIF
     !
     !
     IF (extradim.EQ.1) THEN
       iret = nf90_def_dim(ncid, 'f', dimln(4), dimid(4))
       CALL check_err(iret)
     ENDIF
     iret = nf90_def_dim(ncid, 'time',nf90_unlimited, dimid(4+extradim))
     CALL check_err(iret)
     IF (gtype.EQ.ungtype) THEN
       iret = nf90_def_dim(ncid, 'noel',3, dimid(5+extradim))
       CALL check_err(iret)
     ENDIF
     !
     !     define variables
     !
     IF (flagll) THEN
       !longitude
       IF (gtype.EQ.rlgtype .OR. gtype.EQ.smctype) THEN
         IF (smcgrd) THEN
 #ifdef W3_SMC
           IF(smcotype .EQ. 1) THEN
             ! Flat SMC grid - use seapoint dimension:
             iret = nf90_def_var(ncid, 'longitude', nf90_float, dimid(2), varid(1))
             CALL check_err(iret)
             iret = nf90_def_var(ncid, 'latitude', nf90_float, dimid(2), varid(2))
             CALL check_err(iret)
             ! Latitude and longitude are auxililary variables in type 1 sea point
             ! SMC file; add to "coordinates" attribute:
             coords_attr = trim(coords_attr) // " latitude longitude"
             ! For seapoint style SMC grid, also define out cell size variables:
             iret = nf90_def_var(ncid, 'cx', nf90_short, dimid(2), varid(5))
             CALL check_err(iret)
             iret = nf90_put_att(ncid, varid(5), 'long_name',        &
                  'longitude cell size factor')
             iret = nf90_put_att(ncid, varid(5), 'valid_min', 1)
             iret = nf90_put_att(ncid, varid(5), 'valid_max', 256)
             iret = nf90_def_var(ncid, 'cy', nf90_short, dimid(2), varid(6))
             call check_err(iret)
             iret = nf90_put_att(ncid, varid(6), 'long_name',        &
                  'latitude cell size factor')
             iret = nf90_put_att(ncid, varid(6), 'valid_min', 1)
             iret = nf90_put_att(ncid, varid(6), 'valid_max', 256)
           ELSE
             ! Regirdded regular SMC grid - use lon/lat dimensions:
             iret = nf90_def_var(ncid, 'longitude', nf90_float, dimid(2), varid(1))
             call check_err(iret)
             iret = nf90_def_var(ncid, 'latitude', nf90_float, dimid(3), varid(2))
             call check_err(iret)
           ENDIF
 #endif
         ELSE
           iret = nf90_def_var(ncid, 'longitude', nf90_float, dimid(2), varid(1))
           iret = nf90_def_var(ncid, 'latitude', nf90_float, dimid(3), varid(2))
         ENDIF ! SMCGRD
       ELSE IF (gtype.EQ.clgtype) THEN
         iret = nf90_def_var(ncid, 'longitude', nf90_float, (/ dimid(2), dimid(3)/), &
              varid(1))
         iret = nf90_def_var(ncid, 'latitude', nf90_float, (/ dimid(2), dimid(3)/), &
              varid(2))
       ELSE
         iret = nf90_def_var(ncid, 'longitude', nf90_float, dimid(2), varid(1))
         iret = nf90_def_var(ncid, 'latitude', nf90_float, dimid(2), varid(2))
       END IF
       iret=nf90_put_att(ncid,varid(1),'units','degree_east')
 #ifdef W3_RTD
       ! Is the grid really rotated
       IF ( .NOT. rtdl ) THEN
 #endif
         iret=nf90_put_att(ncid,varid(1),'long_name','longitude')
         iret=nf90_put_att(ncid,varid(1),'standard_name','longitude')
 #ifdef W3_RTD
       ELSE
         ! Override the above for RTD pole:
         iret=nf90_put_att(ncid,varid(1),'long_name','longitude in rotated pole grid')
         iret=nf90_put_att(ncid,varid(1),'standard_name','grid_longitude')
       END IF
 #endif
       iret=nf90_put_att(ncid,varid(1),'valid_min',-180.0)
       iret=nf90_put_att(ncid,varid(1),'valid_max',360.)
       !
       iret=nf90_put_att(ncid,varid(2),'units','degree_north')
 #ifdef W3_RTD
       IF ( .NOT. rtdl ) THEN
 #endif
         iret=nf90_put_att(ncid,varid(2),'long_name','latitude')
         iret=nf90_put_att(ncid,varid(2),'standard_name','latitude')
 #ifdef W3_RTD
       ELSE
         ! Override the above for RTD pole:
         iret=nf90_put_att(ncid,varid(2),'long_name','latitude in rotated pole grid')
         iret=nf90_put_att(ncid,varid(2),'standard_name','grid_latitude')
       END IF
 #endif
       iret=nf90_put_att(ncid,varid(2),'valid_min',-90.0)
       iret=nf90_put_att(ncid,varid(2),'valid_max',90.)
       !
       IF(smcgrd) THEN
 #ifdef W3_SMC
         IF(smcotype .EQ. 1) THEN
 #endif
 #ifdef W3_RTD
           IF ( rtdl ) THEN
             ! For SMC grid type 1, standard lat/lon variables are 1D:
             iret = nf90_def_var(ncid, 'standard_longitude', nf90_float, &
                  (/ dimid(2) /), varid(7))
             call check_err(iret)
             iret = nf90_def_var(ncid, 'standard_latitude', nf90_float, &
                  (/ dimid(2) /), varid(8))
             call check_err(iret)
           ENDIF ! RTDL
 #endif
 #ifdef W3_SMC
         ELSE
 #endif
 #ifdef W3_RTD
           IF ( rtdl ) THEN
             iret = nf90_def_var(ncid, 'standard_longitude', nf90_float, &
                  (/ dimid(2), dimid(3)/), varid(7))
             call check_err(iret)
             iret = nf90_def_var(ncid, 'standard_latitude', nf90_float, &
                  (/ dimid(2), dimid(3)/), varid(8))
             call check_err(iret)
           ENDIF ! RTDL
 #endif
 #ifdef W3_SMC
         ENDIF
 #endif
       ELSE
 #ifdef W3_RTD
         IF ( rtdl ) THEN
           !Add secondary coordinate system linking rotated grid back to standard lat-lon
           iret = nf90_def_var(ncid, 'standard_longitude', nf90_float, (/ dimid(2), dimid(3)/), &
                varid(7))
           call check_err(iret)
           iret = nf90_def_var(ncid, 'standard_latitude', nf90_float, (/ dimid(2), dimid(3)/), &
                varid(8))
           call check_err(iret)
         END IF
 #endif
       ENDIF ! SMCGRD
 #ifdef W3_RTD
       IF ( rtdl ) THEN
         ! Attributes for standard_longitude:
         iret=nf90_put_att(ncid,varid(7),'units','degree_east')
         iret=nf90_put_att(ncid,varid(7),'long_name','longitude')
         iret=nf90_put_att(ncid,varid(7),'standard_name','longitude')
         iret=nf90_put_att(ncid,varid(7),'valid_min',-180.0)
         iret=nf90_put_att(ncid,varid(7),'valid_max',360.)
         ! Attributes for standard_latitude:
         iret=nf90_put_att(ncid,varid(8),'units','degree_north')
         iret=nf90_put_att(ncid,varid(8),'long_name','latitude')
         iret=nf90_put_att(ncid,varid(8),'standard_name','latitude')
         iret=nf90_put_att(ncid,varid(8),'valid_min',-90.0)
         iret=nf90_put_att(ncid,varid(8),'valid_max',90.)
         ! Add rotated pole grid mapping variable (dummy scalar variable
         ! used to simply store rotated pole information; see CF1.6 conventions).
         ! TODO: FUTURE WW3_OUNF DEVELOPMENT WILL ALLOW USER TO DEFINE THE
         ! COORDINATE REFERENCE SYSTEM - THIS WILL REQUIRE THE BELOW TO BE
         ! HANDLED DIFFERENTLY. C. Bunney.
 #endif
         !! CHRISB: Commenting out below - will be handled by w3oundmeta module
 #ifdef W3_RTD
         !!IRET=NF90_DEF_VAR(NCID, 'rotated_pole', NF90_CHAR, VARID(12))
         !!IRET=NF90_PUT_ATT(NCID, VARID(12), 'grid_north_pole_latitude',POLAT)
         !!IRET=NF90_PUT_ATT(NCID, VARID(12), 'grid_north_pole_longitude',POLON)
         !!IRET=NF90_PUT_ATT(NCID, VARID(12), 'grid_mapping_name',              &
         !!                           'rotated_latitude_longitude')
       END IF
 #endif
       !
     ELSE
       IF (gtype.EQ.rlgtype) THEN
         iret = nf90_def_var(ncid, 'x', nf90_float, dimid(2), varid(1))
         iret = nf90_def_var(ncid, 'y', nf90_float, dimid(3), varid(2))
       ELSE IF (gtype.EQ.clgtype) THEN
         iret = nf90_def_var(ncid, 'x', nf90_float, (/ dimid(2), dimid(3)/), &
              varid(1))
         iret = nf90_def_var(ncid, 'y', nf90_float, (/ dimid(2), dimid(3)/), &
              varid(2))
       ELSE
         iret = nf90_def_var(ncid, 'x', nf90_float, dimid(2), varid(1))
         iret = nf90_def_var(ncid, 'y', nf90_float, dimid(2), varid(2))
       END IF
       !
       iret=nf90_put_att(ncid,varid(1),'units','m')
       iret=nf90_put_att(ncid,varid(1),'long_name','x')
       iret=nf90_put_att(ncid,varid(2),'units','m')
       iret=nf90_put_att(ncid,varid(2),'long_name','y')
       !
     END IF  ! FLAGLL
     !
     iret=nf90_put_att(ncid,varid(1),'axis','X')
     iret=nf90_put_att(ncid,varid(2),'axis','Y')
     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(1), 1, 1, deflate)
     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(2), 1, 1, deflate)
     !
     ! frequency
     !
     if (extradim.EQ.1) THEN
       iret = nf90_def_var(ncid, 'f', nf90_float, dimid(4), varid(10))
       IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       CALL check_err(iret)
       iret=nf90_put_att(ncid,varid(10),'long_name','wave_frequency')
       CALL check_err(iret)
       iret=nf90_put_att(ncid,varid(10),'standard_name','wave_frequency')
       CALL check_err(iret)
       iret=nf90_put_att(ncid,varid(10),'units','s-1')
       CALL check_err(iret)
       iret=nf90_put_att(ncid,varid(10),'axis','Hz')
       CALL check_err(iret)
     END IF
     !
     !  time
     !
     ! CHRISB: Allow different time variable types:
     iret = nf90_def_var(ncid, 'time', tvartype, dimid(4+extradim), varid(3))
     CALL check_err(iret)
     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(3), 1, 1, deflate)
     CALL check_err(iret)
     SELECT CASE (trim(caltype))
     CASE ('360_day')
       iret=nf90_put_att(ncid,varid(3),'long_name','time in 360 day calendar')
     CASE ('365_day')
       iret=nf90_put_att(ncid,varid(3),'long_name','time in 365 day calendar')
     CASE ('standard')
       !IRET=NF90_PUT_ATT(NCID,VARID(3),'long_name','julian day (UT)') ! CB
       iret=nf90_put_att(ncid,varid(3),'long_name','time')
     END SELECT
     CALL check_err(iret)
     iret=nf90_put_att(ncid,varid(3),'standard_name','time')
     CALL check_err(iret)
     ! CHRISB: Allow alternative time units:
     !IRET=NF90_PUT_ATT(NCID,VARID(3),'units','days since 1990-01-01 00:00:00')
     iret=nf90_put_att(ncid,varid(3),'units', epoch)
     CALL check_err(iret)
     ! CHRISB: Not sure this is useful - required information is in "units"
     !IRET=NF90_PUT_ATT(NCID,VARID(3),'conventions', &
     !  'relative julian days with decimal part (as parts of the day )')
     iret=nf90_put_att(ncid,varid(3),'axis','T')
     CALL check_err(iret)
     iret=nf90_put_att(ncid,varid(3),'calendar',trim(caltype))
     CALL check_err(iret)
     !
     ! forecast period and (forecast reference time), if requested
     !
     IF (flgfc) THEN
       iret = nf90_def_var(ncid, 'forecast_period', nf90_int,         &
            dimid(4+extradim), varid(11))
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(11), 'long_name',              &
            'forecast period')
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(11), 'standard_name',          &
            'forecast_period')
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(11), 'units', 's')
       CALL check_err(iret)
       ! Forecast reference time is a scalar variable:
       iret = nf90_def_var(ncid, 'forecast_reference_time',           &
            tvartype, varid=varid(12))
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(12), 'long_name',              &
            'forecast reference time')
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(12), 'standard_name',          &
            'forecast_reference_time')
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(12), 'units', epoch)
       !   'days since 1990-01-01 00:00:00')
       CALL check_err(iret)
       iret = nf90_put_att(ncid, varid(12), 'calendar', 'gregorian')
       CALL check_err(iret)
       ! Add these to auxiliary coordinates list:
       coords_attr = trim(coords_attr) // " forecast_period forecast_reference_time"
     ENDIF
     !
     ! triangles for irregular grids
     !
     IF (gtype.EQ.ungtype) THEN
       dimtri(1)=dimid(4+extradim+1)
       dimtri(2)=dimid(3)
       iret = nf90_def_var(ncid, 'tri', nf90_int, dimtri, varid(4))
       IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(4), 1, 1, deflate)
     END IF
     !
     !  Status map: useful for grid combination
     !
     IF (mapstaout) THEN
       IF (gtype.EQ.ungtype) THEN
         iret = nf90_def_var(ncid,'MAPSTA', nf90_short,(/ dimid(2) /), varid(20))
       ELSE
         iret = nf90_def_var(ncid,'MAPSTA', nf90_short,(/ dimid(2) , dimid(3) /), &
              varid(20))
       ENDIF
       IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(20), 1, 1, deflate)
       !
       iret=nf90_put_att(ncid,varid(20),'long_name','status map')
       iret=nf90_put_att(ncid,varid(20),'standard_name','status map')
       iret=nf90_put_att(ncid,varid(20),'units','1')
       CALL check_err(iret)
       iret=nf90_put_att(ncid,varid(20),'valid_min',-32)
       CALL check_err(iret)
       iret=nf90_put_att(ncid,varid(20),'valid_max',32)
       CALL check_err(iret)
     END IF
     !
     ! Optional (user-defined) coordinate reference system (scalar variable)
     !
     IF(crs_meta%N .GT. 0) THEN
       iret = nf90_def_var(ncid, crs_name, nf90_char, varid=ivar)
       CALL check_err(iret)
       !CALL WRITE_FREEFORM_META(NCID, IVAR, CRS_META, N_CRSMETA, IERR)
       CALL write_freeform_meta_list(ncid, ivar, crs_meta, ierr)
       CALL check_err(iret)
     ENDIF
     !
     ! Global attributes
     !
     IF(fl_default_gbl_meta) THEN
       iret=nf90_put_att(ncid,nf90_global,'WAVEWATCH_III_version_number' ,trim(wwver))
       CALL check_err(iret)
       iret=nf90_put_att(ncid,nf90_global,'WAVEWATCH_III_switches',trim(switches))
       CALL check_err(iret)
 #ifdef W3_ST4
       IF (zzwnd.NE.10)      iret=nf90_put_att(ncid,nf90_global,'SIN4 namelist parameter ZWD',zzwnd)
       IF (aalpha.NE.0.0095) iret=nf90_put_att(ncid,nf90_global,'SIN4 namelist parameter ALPHA0',aalpha)
       IF (bbeta.NE.1.43)    iret=nf90_put_att(ncid,nf90_global,'SIN4 namelist parameter BETAMAX',bbeta)
       IF(ssdsc(7).NE.0.3)   iret=nf90_put_att(ncid,nf90_global,'SDS4 namelist parameter WHITECAPWIDTH', ssdsc(7))
 #endif
       ! ... TO BE CONTINUED ...
       IF(smcgrd) THEN
 #ifdef W3_SMC
         IF(smcotype .EQ. 1) THEN
           iret = nf90_put_att(ncid, nf90_global, 'first_lat', y0)
           call check_err(iret)
           iret = nf90_put_att(ncid, nf90_global, 'first_lon', x0)
           call check_err(iret)
           iret = nf90_put_att(ncid, nf90_global, 'base_lat_size', dlat)
           call check_err(iret)
           iret = nf90_put_att(ncid, nf90_global, 'base_lon_size', dlon)
           call check_err(iret)
           iret=nf90_put_att(ncid,nf90_global,'SMC_grid_type','seapoint')
           call check_err(iret)
         ELSE IF(smcotype .EQ. 2) THEN
           iret=nf90_put_att(ncid,nf90_global,'SMC_grid_type','regular_regridded')
           call check_err(iret)
         ENDIF
 #endif
       ENDIF
     ENDIF ! FL_DEFAULT_GBL_META
     ! ChrisB: Write user global attributes:
     CALL write_global_meta(ncid, iret)
     CALL check_err(iret)
     ! ChrisB: Below is the old way of writing Global attributes, this
     ! is now deprecated, but still supported at the moment...
     open(unit=994,file='NC_globatt.inp',status='old',iostat=icode)
     IF (icode.EQ.0) THEN
       DO WHILE (icode.EQ.0)
         read(994,'(a)',iostat=icode) attname
         read(994,'(a)',iostat=icode) attval
         IF (icode.EQ.0) THEN
           strl=len_trim(attname)
           strl2=len_trim(attval)
           iret=nf90_put_att(ncid,nf90_global,attname(1:strl),attval(1:strl2))
           CALL check_err(iret)
         END IF
       END DO
     ENDIF
     CLOSE(994)
     IF(fl_default_gbl_meta) THEN
       iret=nf90_put_att(ncid,nf90_global,'product_name' ,trim(ncfile))
       CALL check_err(iret)
       iret=nf90_put_att(ncid,nf90_global,'area',trim(gname))
       CALL check_err(iret)
     ENDIF
     RETURN
References w3timemd::caltype, check_err(), w3gdatmd::clgtype, file(), w3gdatmd::flagll, w3gdatmd::gtype, w3gdatmd::polat, w3gdatmd::polon, w3gdatmd::rlgtype, and w3gdatmd::ungtype.
Referenced by w3exnc(), and w3ounp().
w3exnc()
subroutine w3ounf::w3exnc (integer, intent(in) NX, integer, intent(in) NY, integer, intent(in) IX1, integer, intent(in) IXN, integer, intent(in) IY1, integer, intent(in) IYN, integer, intent(in) NSEA, character(30) FILEPREFIX, integer, dimension(3,5), intent(in) E3DF, integer, dimension(3), intent(in) P2MSF, integer, dimension(3), intent(in) US3DF, integer, dimension(2), intent(in) USSPF, integer, intent(in) NCTYPE, logical, intent(in) TOGETHER, integer, intent(in) NCVARTYPEI, logical, dimension(nogrp,ngrpp), intent(in) FLG2D, integer, dimension(nogrp,ngrpp,noswll + 1), intent(inout) NCIDS, integer, intent(inout) S3, character*30, intent(in) STRSTOPDATE)
Perform actual grid output in NetCDF file.
Parameters
[in] NX Grid dimension X
[in] NY Grid dimension Y
[in] IX1 Grid index along X
[in] IXN Grid index along X
[in] IY1 Grid index along Y
[in] IYN Grid index along Y
[in] NSEA Number of sea points
[in,out] FILEPREFIX
[in] E3DF
[in] P2MSF
[in] US3DF
[in] USSPF
[in] NCTYPE
[in] TOGETHER
[in] NCVARTYPEI
[in] FLG2D
[in,out] NCIDS
[in,out] S3
[in] STRSTOPDATE
Author
F. Ardhuin
M. Accensi
Date
22-Mar-2021
Definition at line 863 of file ww3_ounf.F90.
     !/
     !/                  +-----------------------------------+
     !/                  |           F. Ardhuin              |
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    17-Mar-2010 : Creation                            ( version 3.14_SHOM )
     !/    28-Feb-2013 : New option for float output         ( version 4.08 )
     !/    02-Apr-2013 : New structure of output fields.     ( version 4.09 )
     !/    12-Apr-2013 : Allows curvilinear grids            ( version 4.10 )
     !/    30-Apr-2014 : Correct group3 freq dim.            ( version 5.00 )
     !/    23-May-2014 : Adding ice fluxes to W3SRCE         ( version 5.01 )
     !/    14-Oct-2014 : Keep the output files opened        ( version 5.01 )
     !/    03-Nov-2020 : NetCDF metadata moved to separate   ( version 7.12 )
     !/                  module.
     !/    09-Dec-2020 : Set fixed values for VARID indices  ( version 7.12 )
     !/    26-Jan-2021 : Added TP output (derived from fp)   ( version 7.12 )
     !/                  and alternative dir/mag output.
     !/    02-Feb-2021 : Make default global meta optional   ( version 7.12 )
     !/    22-Mar-2021 : New coupling fields output          ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Perform actual grid output in NetCDF file.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NX/Y    Int.  I  Grid dimensions.
     !       IX1/IXN Int.  I  Grid indexes along X
     !       IY1/IYN Int.  I  Grid indexes along Y
     !       NSEA    Int.  I  Number of sea points.
     !     ----------------------------------------------------------------
     !
     !     Internal parameters
     !     ----------------------------------------------------------------
     !       FLTWO   Log.  Flags for two-dimensional field X Y.
     !       FLDIR   Log.  Flags for two-dimensional, directional field.
     !       FLFRQ   Log.  Flags for frequency array (3D field)
     !       X1, X2, XX, XY
     !               R.A.  Output fields
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      EXTCDE    Subr.   Id.    Abort program as graceful as possible.
     !      W3S2XY    Subr.   Id.    Convert from storage to spatial grid.
     !      PRTBLK    Subr. W3ARRYMD Print plot of array.
     !      OUTA2I    Subr.   Id.    Print array of INTEGERS.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Main program in which it is contained.
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !     - Note that arrays CX and CY of the main program now contain
     !       the absolute current speed and direction respectively.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S  Enable subroutine tracing.
     !       !/T  Enable test output.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY : w3s2xy, uv_to_mag_dir
 #ifdef W3_RTD
     USE w3servmd, ONLY : w3thrtn, w3xyrtn, w3eqtoll
 #endif
     USE w3arrymd, ONLY : outa2i, prtblk
     USE w3gdatmd, ONLY : sig, gtype, flagll, mapsta, mapst2
     USE w3gdatmd, ONLY : nk, ungtype, mapsf, ntri, clgtype, rlgtype, &
          xgrd, ygrd, sx, sy, x0, y0, trigp, ussp_wn
 #ifdef W3_RTD
     ! Rotated pole data from the mod_def file
     USE w3gdatmd, ONLY : polat, polon, flagunr, angld
 #endif
 #ifdef W3_T
     USE w3odatmd, ONLY : ndst
 #endif
     USE netcdf
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)     :: NX, NY, IX1, IXN, IY1, IYN, NSEA,     &
          E3DF(3,5), P2MSF(3), US3DF(3),        &
          USSPF(2), NCTYPE, NCVARTYPEI
     CHARACTER(30)           :: FILEPREFIX
     LOGICAL, INTENT(IN)     :: TOGETHER
     LOGICAL, INTENT(IN)     :: FLG2D(NOGRP,NGRPP)
     INTEGER, INTENT(INOUT)  :: NCIDS(NOGRP,NGRPP,NOSWLL + 1), S3
     CHARACTER*30,INTENT(IN) :: STRSTOPDATE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: IFI, IFJ, MFILL, I, J, ISEA, IX, IY,  &
          I1, J1, IPART, INDEXIPART, COORDTYPE
     INTEGER                 :: S1, S2, S4, S5, NCID, OLDNCID, NDSDAT,&
          NFIELD, N, IRET, IK, EXTRADIM, IVAR,  &
          IVAR1
     INTEGER                 :: DIMID(6), VARID(300), START(4),       &
          COUNT(4), DIMLN(6),START1D(2),        &
          COUNT1D(2), DIMFIELD(3),              &
          STARTDATE(8), CURDATE(8),             &
          EPOCHDATE(8),                         &
          MAP(NX+1,NY), MP2(NX+1,NY)
     !
     INTEGER                  :: DEFLATE=1
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   =   0
 #endif
     !
     ! Make the below allocatable to avoid stack overflow on some machines
     INTEGER(KIND=2), ALLOCATABLE    :: MX1(:,:), MXX(:,:), MYY(:,:), &
          MXY(:,:), MAPOUT(:,:)
     !
     REAL                    :: CABS, UABS, MFILLR
 #ifdef W3_BT4
     REAL, PARAMETER            :: LOG2=log(2.)
 #endif
     !
     REAL,DIMENSION(:),  ALLOCATABLE    :: LON, LAT, FREQ
     REAL,DIMENSION(:,:),  ALLOCATABLE  :: LON2D, LAT2D, ANGLD2D
 #ifdef W3_RTD
     REAL,DIMENSION(:,:),  ALLOCATABLE  :: LON2DEQ, LAT2DEQ
 #endif
     ! Make the below allocatable to avoid stack overflow on some machines
     REAL, ALLOCATABLE       :: X1(:,:), X2(:,:), XX(:,:), XY(:,:),   &
          XK(:,:,:), XXK(:,:,:), XYK(:,:,:),    &
          MX1R(:,:), MXXR(:,:), MYYR(:,:),      &
          MXYR(:,:), AUX1(:)
     !
     DOUBLE PRECISION        :: OUTJULDAY
     INTEGER(KIND=8)         :: OUTSECS
     DOUBLE PRECISION        :: SXD, SYD, X0D, Y0D
     !
     CHARACTER*120           :: STR2
     CHARACTER*512           :: PARTCOM
     !CHARACTER*30            :: UNITVAR(3),FORMAT1
     CHARACTER*30            :: FORMAT1
     CHARACTER*30            :: STRSTARTDATE
     CHARACTER               :: FNAMENC*128,                           &
          FORMF*11
     CHARACTER, SAVE         :: OLDTIMEID*16 = '0000000000000000'
     CHARACTER, SAVE         :: TIMEID*16 = '0000000000000000'
     !
     LOGICAL                 :: FLFRQ, FLDIR, FEXIST, FREMOVE
     LOGICAL                 :: CUSTOMFRQ=.false.
 #ifdef W3_T
     LOGICAL                 :: LTEMP(NGRPP)
 #endif
     TYPE(META_T)            :: META(3)
     !TYPE(META_T)            :: META
     !/
     !/ ------------------------------------------------------------------- /
     !/
     !
 #ifdef W3_S
     CALL strace (ient, 'W3EXNC')
 #endif
     !
 #ifdef W3_T
     DO ifi=1, nogrp
       ltemp  = flg2d(ifi,:)
       WRITE (ndst,9000) ifi, ltemp
     END DO
     WRITE (ndst,9001) nctype, ix1, ixn, iy1, iyn, vector
 #endif
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     ! 1.  Preparations
     !
     ! Allocate output storage. This is required with the introduction
     ! of the SMC grid output as the regridded output grid dimensions could
     ! conceivably be larger than the NX and NY values. Making these (large)
     ! arrays allocatable also moves them to the heap and avoids stack
     ! overflow issues that can occur on some architectures. (Chris Bunney)
     IF(smcgrd) THEN
 #ifdef W3_SMC
       ALLOCATE(x1(nxo,nyo), x2(nxo,nyo), xx(nxo,nyo), xy(nxo,nyo))
       ALLOCATE(xk(nxo,nyo,nk), xxk(nxo,nyo,nk), xyk(nxo,nyo,nk))
       ALLOCATE(mx1(nxo,nyo), mxx(nxo,nyo), myy(nxo,nyo),               &
            mxy(nxo,nyo), mapout(nxo,nyo))
       ALLOCATE(mx1r(nxo,nyo), mxxr(nxo,nyo), myyr(nxo,nyo), mxyr(nxo,nyo))
 #endif
     ELSE
       ALLOCATE(x1(nx+1,ny),x2(nx+1,ny),xx(nx+1,ny),xy(nx+1,ny))
       ALLOCATE(xk(nx+1,ny,nk), xxk(nx+1,ny,nk), xyk(nx+1,ny,nk))
       ALLOCATE(mx1(nx,ny), mxx(nx,ny), myy(nx,ny), mxy(nx,ny), mapout(nx,ny))
       ALLOCATE(mx1r(nx,ny), mxxr(nx,ny), myyr(nx,ny), mxyr(nx,ny))
     ENDIF ! SMCGRD
     ALLOCATE(aux1(nsea))
     x1     = undef
     x2     = undef
     xx     = undef
     xy     = undef
     ! CB: Dont output MAPSTA for SMC grid - it does not make sense
     IF( smcgrd .AND. mapstaout) THEN
       WRITE(ndso,*) "MAPSTA output disabled for SMC grids"
       mapstaout = .false.
     ENDIF
     ncvartype  = ncvartypei
     ndsdat=30
     ncid = 0
     !
     !
     !CHRISB: Allow alternative time units:
     CALL t2iso(tepoch, epoch_iso)
     SELECT CASE(timeunit)
     CASE('D')
       epoch = 'days since ' // epoch_iso
     CASE('S')
       epoch = 'seconds since ' // epoch_iso
     CASE DEFAULT
       print*,'Unknown time units: ', timeunit
       CALL extcde(10)
     END SELECT
     CALL u2d(epoch, epochdate, ierr)
     ! 1.1 Set-up transfer files
     mfill  = nf90_fill_short
     mfillr  = nf90_fill_float
     IF (gtype.NE.ungtype) THEN
       coordtype=1
     ELSE
       coordtype=2
     ENDIF
     ! 1.2 Sets the date as ISO8601 convention
     ! S3 defines the number of characters in the date for the filename
     ! S3=0 -> field, S3=4-> YYYY, S3=6 -> YYYYMM, S3=10 -> YYYYMMDDHH
     ! Setups min and max date format
     IF (s3.GT.0 .AND. s3.LT.4) s3=4
     IF (s3.GT.10) s3=10
     !
     ! Defines the format of FILETIME
     s5=s3-8
     s4=s3
     oldtimeid=timeid
     ! if S3=>nodate then filetime='field'
     IF (s3.EQ.0) THEN
       s4=5
       timeid="field"
       ! if S3=>YYYYMMDDHH then filetime='YYYYMMDDTHHZ'
     ELSE IF (s3.EQ.10) THEN
       s4=s4+2 ! add chars for ISO8601 : day T hours Z
       WRITE(format1,'(A,I1,A,I1,A)') '(I8.8,A1,I',s5,'.',s5,',A1)'
       WRITE (timeid,format1) time(1), 'T', &
            floor(real(time(2))/nint(10.**(6-s5))), 'Z'
       ! if S3=>YYYYMMDD then filetime='YYYYMMDD'
     ELSE IF (s3.EQ.8) THEN
       WRITE(format1,'(A,I1,A,I1,A)') '(I',s3,'.',s3,')'
       WRITE (timeid,format1) time(1)
       ! if S3=>YYYYMM then filetime='YYYYMM'
       ! or S3=>YYYY then filetime='YYYY'
     ELSE
       WRITE(format1,'(A,I1,A,I1,A)') '(I',s3,'.',s3,')'
       WRITE (timeid,format1) floor(real(time(1))/nint(10.**(8-s3)))
     END IF
     ! redefines filename with updated date format
     s1=len_trim(fileprefix)
     fnamenc=''
     fnamenc(1:s1)=fileprefix(1:s1)
     fnamenc(s1+1:s1+s4) = timeid(1:s4)
     !
 #ifdef W3_SMC
     !
     !---  Update MAPSMC for SMC type 2 output. This needs to be
     !     done at each timestep as MAPSTA could change if there
     !     are water level or ice input chagnes.
     !
     IF( smcgrd .AND. (smcotype .EQ. 2) ) CALL mapsta_smc()
 #endif
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     ! 2.  Loop over output fields.
     !
     ! Instanciates the field and group indexes
     i1=0
     j1=0
     !
     DO ifi=1, nogrp
       DO ifj=1, ngrpp
         ! If the flag for the variable IFI of the group IFJ is .TRUE.
         IF ( flg2d(ifi,ifj) ) THEN
           ! Instanciates the partition array
           indexipart=1
           ipart=tabipart(indexipart)
           nfield=1 ! Default is one field
           !  Loop over IPART for partition variables
 555       CONTINUE
           ! Initializes the index of field and group at the first flag FLG2D at .TRUE.
           IF (i1.EQ.0) i1=ifi
           IF (j1.EQ.0) j1=ifj
           formf  = '(1X,32I5)'
 #ifdef W3_T
           WRITE (ndst,9020) idout(ifi,ifj)
 #endif
           !
           ! 2.1 Set output arrays and parameters
           !
           ! Initializes the flags for freq and direction dimensions
           flfrq = .false.
           fldir = .false.
           IF (ncvartypei.EQ.3) ncvartype=2
           !
           ! Depth
           IF ( ifi .EQ. 1 .AND. ifj .EQ. 1 ) THEN
             CALL s2grid(dw(1:nsea), x1)
             ! Surface current
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 2 ) THEN
             !! Note - CX and CY read in from .ww3 file are X-Y vectors
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, cx(1:nsea), cy(1:nsea), angld)
 #endif
             !
             IF( .NOT. vector ) THEN
               CALL uv_to_mag_dir(cx(1:nsea), cy(1:nsea), nsea,       &
                    tolerance=0.05, conv='O')
             ENDIF
             !
             CALL s2grid(cx(1:nsea), xx)
             CALL s2grid(cy(1:nsea), xy)
             nfield=2
             !
             ! Wind
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 3 ) THEN
             !! Note - UA and UD read in from .ww3 file are UX,UY
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, ua(1:nsea), ud(1:nsea), angld)
 #endif
             !
             IF( .NOT. vector ) THEN
               CALL uv_to_mag_dir(ua(1:nsea), ud(1:nsea), nsea,       &
                    tolerance=1.0, conv='N')
             ENDIF
             !
             CALL s2grid(ua(1:nsea), xx)
             CALL s2grid(ud(1:nsea), xy)
             nfield=2
             !
             ! Air-sea temperature difference
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 4 ) THEN
             CALL s2grid(as(1:nsea), x1)
             !
             ! Sea surface height above sea level
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 5 ) THEN
             CALL s2grid(wlv, x1)
             !
             ! Sea ice area fraction
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 6 ) THEN
             CALL s2grid(ice(1:nsea), x1)
             ! Icebergs_damping
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 7 ) THEN
             CALL s2grid(berg, x1)
             WHERE ( x1.NE.undef) x1 = x1*0.1
             !
             ! Atmospheric momentum
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 8 ) THEN
             !! Note - TAUA and TAUADIR read in from .ww3 file are TAUAX,TAUAY
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, taua(1:nsea), tauadir(1:nsea), angld)
 #endif
             IF( smcgrd ) THEN
 #ifdef W3_SMC
               CALL w3s2xy_smc( taua(1:nsea), xx )
               CALL w3s2xy_smc( tauadir(1:nsea), xy )
 #endif
             ELSE ! IF(SMCGRD)
               CALL w3s2xy ( nsea, nsea, nx+1, ny, taua(1:nsea)      &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauadir(1:nsea)   &
                    , mapsf, xy )
             ENDIF
             nfield=2
             !
             ! Air density
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 9 ) THEN
             IF( smcgrd ) THEN
 #ifdef W3_SMC
               CALL w3s2xy_smc(rhoair, x1)
 #endif
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, rhoair, mapsf, x1 )
             ENDIF
             !
 #ifdef W3_BT4
             ! Krumbein phi scale
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 10 ) THEN
             CALL s2grid(sed_d50, x1)
             WHERE ( x1.NE.undef) x1 = -log(x1/0.001)/log2
             nfield=1
 #endif
             !
 #ifdef W3_IS2
             ! Ice thickness
           ELSE IF (ifi .EQ. 1 .AND. ifj .EQ. 11 ) THEN
             CALL s2grid(iceh(1:nsea), x1)
             nfield=1
 #endif
             !
 #ifdef W3_IS2
             ! Maximum ice floe diameter
           ELSE IF (ifi .EQ. 1 .AND. ifj .EQ. 12 ) THEN
             CALL s2grid(icef(1:nsea), x1)
             nfield=1
 #endif
             ! Significant wave height
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 1 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=2
             CALL s2grid(hs, x1)
             ! Mean wave length
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 2 ) THEN
             CALL s2grid(wlm, x1)
             !
             ! Mean period T02
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 3 ) THEN
             CALL s2grid(t02, x1)
             !
             ! Mean period T0m1
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 4 ) THEN
             CALL s2grid(t0m1, x1)
             !
             ! Mean period T01
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 5 ) THEN
             CALL s2grid(t01, x1)
             !
             ! Wave peak frequency
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 6 ) THEN
             CALL s2grid(fp0, x1)
             !
             ! Wave mean direction
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 7 ) THEN
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, thm, angld, .false.)
 #endif
             CALL s2grid(thm, x1, .true.)
             !
             ! Directional spread
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 8 ) THEN
             CALL s2grid(ths, x1)
             !
             ! Peak direction
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 9 ) THEN
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, thp0, angld, .false.)
 #endif
             CALL s2grid(thp0, x1, .true.)
             !
             ! Infragravity wave height
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 10 ) THEN
             CALL s2grid(hsig, x1)
             !
             ! Expected maximum sea surface elevation
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 11 ) THEN
             CALL s2grid(stmaxe, x1)
             !
             ! Standard deviation of maximum sea surface elevation
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 12 ) THEN
             CALL s2grid(stmaxd, x1)
             !
             ! Expected maximum wave height
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 13 ) THEN
             CALL s2grid(hmaxe, x1)
             !
             ! Expected maximum wave height from crest
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 14 ) THEN
             CALL s2grid(hcmaxe, x1)
             !
             ! STD of maximum wave height
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 15 ) THEN
             CALL s2grid(hmaxd, x1)
             !
             ! STD of maximum wave height from crest
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 16 ) THEN
             CALL s2grid(hcmaxd, x1)
             !
             ! Dominant wave breaking probability
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 17 ) THEN
             CALL s2grid(wbt, x1)
             !
             ! Wave peak period (derived from peak freq field)
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 18 ) THEN
             DO i=1,nsea
               IF(fp0(i) .NE. undef) THEN
                 aux1(i) = 1.0 / fp0(i)
               ELSE
                 aux1(i) = undef
               ENDIF
             ENDDO
             !
             CALL s2grid(aux1, x1)
             !
             ! Mean wave number
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 19 ) THEN
             IF( smcgrd ) THEN
 #ifdef W3_SMC
               CALL w3s2xy_smc( wnmean, x1 )
 #endif
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, wnmean, mapsf, x1 )
             END IF
             !
             ! Wave elevation spectrum
           ELSE IF ( ifi .EQ. 3 .AND. ifj .EQ. 1 ) THEN
             ! Information for spectral
             flfrq  = .true.
             i1f=e3df(2,1)
             i2f=e3df(3,1)
             DO ik=i1f,i2f
               CALL s2grid(ef(:,ik), xx)
               IF (ncvartype.EQ.2) WHERE ( xx.GE.0.) xx = alog10(xx+1e-12)
               xk(:,:,ik)=xx
             END DO
             !
             ! Mean wave direction frequency spectrum
           ELSE IF ( ifi .EQ. 3 .AND. ifj .EQ. 2 ) THEN
             ! Information for spectral
             flfrq  = .true.
             i1f=e3df(2,2)
             i2f=e3df(3,2)
             DO ik=i1f,i2f
 #ifdef W3_RTD
               ! Rotate direction back to standard pole
               IF ( flagunr ) CALL w3thrtn(nsea, th1m(:,ik), angld, .false.)
 #endif
               CALL s2grid(th1m(:,ik), xx)
               xk(:,:,ik)=xx
             END DO
             !
             ! Spreading frequency spectrum
           ELSE IF ( ifi .EQ. 3 .AND. ifj .EQ. 3 ) THEN
             ! Information for spectral
             flfrq  = .true.
             i1f=e3df(2,3)
             i2f=e3df(3,3)
             DO ik=i1f,i2f
               CALL s2grid(sth1m(:,ik), xx)
               xk(:,:,ik)=xx
             END DO
             !
             ! Second mean wave direction frequency spectrum
           ELSE IF ( ifi .EQ. 3 .AND. ifj .EQ. 4 ) THEN
             ! Information for spectral
             flfrq  = .true.
             i1f=e3df(2,4)
             i2f=e3df(3,4)
             DO ik=i1f,i2f
 #ifdef W3_RTD
               ! Rotate direction back to standard pole
               IF ( flagunr ) CALL w3thrtn(nsea, th2m(:,ik), angld, .false.)
 #endif
               CALL s2grid(th2m(:,ik), xx)
               xk(:,:,ik)=xx
             END DO
             !
             ! Second spreading frequency spectrum
           ELSE IF ( ifi .EQ. 3 .AND. ifj .EQ. 5 ) THEN
             ! Information for spectral
             flfrq  = .true.
             i1f=e3df(2,5)
             i2f=e3df(3,5)
             DO ik=i1f,i2f
               CALL s2grid(sth2m(:,ik), xx)
               xk(:,:,ik)=xx
             END DO
             !
             ! Wave numbers
           ELSE IF ( ifi .EQ. 3 .AND. ifj .EQ. 6 ) THEN
             ! Information for spectral
             flfrq  = .true.
             i1f=1
             i2f=nk
             DO ik=1,nk
               CALL s2grid(wn(ik,:), xx)
               xk(:,:,ik)=xx
             END DO
             !
             ! Partition wave significant height
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 1 ) THEN
             CALL s2grid(phs(:,ipart), x1)
             !
             ! Partition peak period
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 2 ) THEN
             CALL s2grid(ptp(:,ipart), x1)
             ! Partition peak wave length
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 3 ) THEN
             CALL s2grid(plp(:,ipart), x1)
             !
             ! Partition wave mean direction
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 4 ) THEN
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, pdir(:,ipart), angld, .false.)
 #endif
             CALL s2grid(pdir(:,ipart), x1, .true.)
             !
             ! Partition directional spread
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 5 ) THEN
             CALL s2grid(psi(:,ipart), x1)
             !
             ! Partition wind sea fraction
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 6 ) THEN
             CALL s2grid(pws(:,ipart), x1)
             !
             ! Partition peak direction
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 7 ) THEN
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, pthp0(:,ipart), angld, .false.)
 #endif
             CALL s2grid(pthp0(:,ipart), x1, .true.)
             !
             ! Partition peakedness
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 8 ) THEN
             CALL s2grid(pqp(:,ipart), x1)
             !
             ! Partition peak enhancement factor
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 9 ) THEN
             CALL s2grid(ppe(:,ipart), x1)
             !
             ! Partition frequency width
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 10 ) THEN
             CALL s2grid(pgw(:,ipart), x1)
             !
             ! Partition spectral width
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 11 ) THEN
             CALL s2grid(psw(:,ipart), x1)
             !
             ! Partition mean period Tm10
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 12 ) THEN
             CALL s2grid(ptm1(:,ipart), x1)
             !
             ! Partition mean period T01
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 13 ) THEN
             CALL s2grid(pt1(:,ipart), x1)
             !
             ! Partition mean period T02
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 14 ) THEN
             CALL s2grid(pt2(:,ipart), x1)
             !
             ! Partition energy at peak frequency
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 15 ) THEN
             CALL s2grid(pep(:,ipart), x1)
             nfield=1
             !
             ! Partition wind sea fraction
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 16 ) THEN
             CALL s2grid(pwst(:), x1)
             !
             ! Number of wave partitions
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 17 ) THEN
             CALL s2grid(pnr(:), x1)
             !
             ! Friction velocity
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 1 ) THEN
             !! Note - UST and USTDIR read in from .ww3 file are X-Y vectors
             DO isea=1, nsea
               uabs = sqrt(ust(isea)**2+ustdir(isea)**2)
               IF (uabs.GE.10.) THEN
                 ust(isea)=undef
                 ustdir(isea)=undef
               END IF
             END DO
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, ust(1:nsea), ustdir(1:nsea), angld)
 #endif
             CALL s2grid(ust(1:nsea), xx)
             CALL s2grid(ustdir(1:nsea), xy)
             !! Commented out unnecessary statements below for time being
             !! UST,USTDIR are in north-east convention and X1,X2
             !! are not actually written out below
             !DO ISEA=1, NSEA
             !  UABS   = SQRT(UST(ISEA)**2+USTDIR(ISEA)**2)
             !  IF ( UST(ISEA) .EQ. UNDEF ) THEN
             !      USTDIR(ISEA) = UNDEF
             !      UABS         = UNDEF
             !    ELSE IF ( UABS .GT. 0.05 ) THEN
             !      USTDIR(ISEA) = MOD ( 630. -                     &
             !        RADE*ATAN2(USTDIR(ISEA),UST(ISEA)) , 360. )
             !    ELSE
             !      USTDIR(ISEA) = UNDEF
             !    END IF
             !  UST(ISEA) = UABS
             !  END DO
             !CALL W3S2XY (NSEA,NSEA,NX+1,NY, UST   (1:NSEA) , MAPSF, X1 )
             !CALL W3S2XY (NSEA,NSEA,NX+1,NY, USTDIR(1:NSEA) , MAPSF, X2 )
             nfield=2
             !
             ! Charnock coefficient
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 2 ) THEN
             CALL s2grid(charn(1:nsea), x1)
             !
             ! Wave energy flux
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 3 ) THEN
             DO isea=1, nsea
               IF ( cge(isea) .NE. undef )                       &
                    cge(isea) = 0.001 * cge(isea)  ! from W / m to kW / m
             END DO
             CALL s2grid(cge(1:nsea), x1)
             !
             ! Wind to wave energy flux
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 4 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=4
             CALL s2grid(phiaw(1:nsea), x1)
             !
             ! Wave supported wind stress
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 5 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauwix(1:nsea), tauwiy(1:nsea), angld)
 #endif
             CALL s2grid(tauwix(1:nsea), xx)
             CALL s2grid(tauwiy(1:nsea), xy)
             !! Commented out unnecessary statements below for time being
             !! TAUWIX, TAUWIY are in north-east convention and X1,X2
             !! are not actually written out below
             !DO ISEA=1, NSEA
             !  CABS   = SQRT(TAUWIX(ISEA)**2+TAUWIY(ISEA)**2)
             !  IF ( CABS .NE. UNDEF ) THEN
             !      TAUWIY(ISEA) = MOD ( 630. -                         &
             !            RADE*ATAN2(TAUWIY(ISEA),TAUWIX(ISEA)) , 360. )
             !    ELSE
             !      TAUWIY(ISEA) = UNDEF
             !    END IF
             !  TAUWIX(ISEA) = CABS
             !  END DO
             !CALL W3S2XY ( NSEA, NSEA, NX+1, NY, TAUWIX, MAPSF, X1 )
             !CALL W3S2XY ( NSEA, NSEA, NX+1, NY, TAUWIY, MAPSF, X2 )
             nfield=2
             !
             ! Wave to wind stress
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 6 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauwnx(1:nsea), tauwny(1:nsea), angld)
 #endif
             CALL s2grid(tauwnx(1:nsea), xx)
             CALL s2grid(tauwny(1:nsea), xy)
             nfield=2
             !
             ! Whitecap coverage
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 7 ) THEN
             CALL s2grid(whitecap(1:nsea,1), x1)
             !
             ! Whitecap foam thickness
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 8 ) THEN
             CALL s2grid(whitecap(1:nsea,2), x1)
             !
             ! Significant breaking wave height
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 9 ) THEN
             CALL s2grid(whitecap(1:nsea,3), x1)
             !
             ! Whitecap moment
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 10 ) THEN
             CALL s2grid(whitecap(1:nsea,4), x1)
             !
             ! Wind sea mean period T0M1
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 11 ) THEN
             CALL s2grid(tws(1:nsea), x1)
             !
             ! Radiation stress
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 1 ) THEN
 #ifdef W3_RTD
             ! Radition stress components are always left on rotated pole
             ! at present - need to confirm how to de-rotate
 #endif
             CALL s2grid(sxx(1:nsea), x1)
             CALL s2grid(syy(1:nsea), x2)
             CALL s2grid(sxy(1:nsea), xy)
             nfield=3
             !
             ! Wave to ocean stress
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 2 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauox(1:nsea), tauoy(1:nsea), angld)
 #endif
             CALL s2grid(tauox(1:nsea), xx)
             CALL s2grid(tauoy(1:nsea), xy)
             nfield=2
             !
             ! Radiation pressure (Bernouilli Head)
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 3 ) THEN
             CALL s2grid(bhd(1:nsea), x1)
             !
             ! Wave to ocean energy flux
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 4 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=4
             DO isea=1, nsea
               phioc(isea)=min(3000.,phioc(isea))
             END DO
             CALL s2grid(phioc(1:nsea), x1)
             !
             ! Stokes transport
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 5 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tusx(1:nsea), tusy(1:nsea), angld)
 #endif
             CALL s2grid(tusx(1:nsea), xx)
             CALL s2grid(tusy(1:nsea), xy)
             ! X1, X2 will not be output when NFIELD == 2
             ! ( Like for .cur, .wnd, .ust, .taw, and .uss ) (CHA at FCOO 2019-06-13):
             !! Commented out unnecessary statements below for time being
             !! (...) X1,X2 are not actually written out below
             !DO ISEA=1, NSEA
             !  CABS   = SQRT(TUSX(ISEA)**2+TUSY(ISEA)**2)
             !  IF ( CABS .NE. UNDEF ) THEN
             !      TUSY(ISEA) = MOD ( 630. -                         &
             !            RADE*ATAN2(TUSY(ISEA),TUSX(ISEA)) , 360. )
             !    ELSE
             !      TUSY(ISEA) = UNDEF
             !    END IF
             !  TUSX(ISEA) = CABS
             !  END DO
             !IF( SMCGRD ) THEN
 #ifdef W3_SMC
             !CALL W3S2XY_SMC( TUSX(:), X1 )
             !CALL W3S2XY_SMC( TUSY(:), X2 ) ! TODO: CHRISB: TUSY is in degrees....W3S2XY_SMC expects radians...
 #endif
             !ELSE
             !  CALL W3S2XY ( NSEA, NSEA, NX+1, NY,TUSX,MAPSF, X1 )
             !  CALL W3S2XY ( NSEA, NSEA, NX+1, NY,TUSY,MAPSF, X2 )
             !ENDIF ! SMCGRD
             nfield=2
             !
             ! Surface stokes drift
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 6 ) THEN
             DO isea=1, nsea
               ussx(isea)=max(-0.9998,min(0.9998,ussx(isea)))
               ussy(isea)=max(-0.9998,min(0.9998,ussy(isea)))
             END DO
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, ussx(1:nsea), ussy(1:nsea), angld)
 #endif
             CALL s2grid(ussx(1:nsea), xx)
             CALL s2grid(ussy(1:nsea), xy)
             !! Commented out unnecessary statements below for time being
             !! TAUWIX, TAUWIY are in north-east convention and X1,X2
             !! are not actually written out below
             !DO ISEA=1, NSEA
             !  CABS   = SQRT(USSX(ISEA)**2+USSY(ISEA)**2)
             !  IF ( CABS .NE. UNDEF ) THEN
             !      USSY(ISEA) = MOD ( 630. -                         &
             !            RADE*ATAN2(USSY(ISEA),USSX(ISEA)) , 360. )
             !    ELSE
             !      USSY(ISEA) = UNDEF
             !    END IF
             !  USSX(ISEA) = CABS
             !  END DO
             !CALL W3S2XY ( NSEA, NSEA, NX+1, NY,USSX,MAPSF, X1 )
             !CALL W3S2XY ( NSEA, NSEA, NX+1, NY,USSY,MAPSF, X2 )
             nfield=2
             !
             ! Power spectral density of equivalent surface pressure
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 7 ) THEN
             nfield=2
             CALL s2grid(prms(1:nsea), xx)
             CALL s2grid(tpms(1:nsea), xy)
             !
             ! Spectral variance of surface stokes drift
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 8 ) THEN
             ! Information for spectral distribution of surface Stokes drift (2nd file)
             flfrq=.true.
             nfield=2
             i1f=us3df(2)
             i2f=us3df(3)
             DO ik= i1f,i2f
 #ifdef W3_RTD
               ! Rotate x,y vector back to standard pole
               IF ( flagunr ) CALL w3xyrtn(nsea, us3d(:,ik), us3d(:,nk+ik), angld)
 #endif
               CALL s2grid(us3d(:,ik), xx)
               CALL s2grid(us3d(:,nk+ik), xy)
               xxk(:,:,ik)=xx
               xyk(:,:,ik)=xy
             END DO
             !
             ! Base10 logarithm of power spectral density of equivalent surface pressure
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ.  9 ) THEN
             ! Information for spectral microseismic generation data (2nd file)
             flfrq=.true.
             i1f=p2msf(2)
             i2f=p2msf(3)
             DO ik=i1f,i2f
               CALL s2grid(p2sms(:,ik), xx)
               IF (ncvartype.EQ.2) THEN
                 WHERE ( xx.GE.0.) xx = alog10(xx*(dwat*grav)**2+1e-12)
               ELSE
                 WHERE ( xx.GE.0.) xx = xx*(dwat*grav)**2
               END IF
               xk(:,:,ik)=xx
             END DO
             !
             ! Wave to sea ice stress
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 10 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauice(1:nsea,1), tauice(1:nsea,2), angld)
 #endif
             CALL s2grid(tauice(1:nsea,1), xx)
             CALL s2grid(tauice(1:nsea,2), xy)
             nfield=2
             !
             ! Wave to sea ice energy flux
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 11 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=4
             CALL s2grid(phice(1:nsea), x1)
             !
             ! Partitioned surface stokes drift
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 12 ) THEN
             ! Information for spectral distribution of surface Stokes drift (2nd file)
             flfrq=.true.
             IF (usspf(1)==1) THEN
               customfrq=.true.
             ENDIF
             nfield=2
             i1f=1
             i2f=usspf(2)
             DO ik= i1f,i2f
 #ifdef W3_RTD
               ! Rotate x,y vector back to standard pole
               IF ( flagunr ) CALL w3xyrtn(nsea, ussp(:,ik), ussp(:,nk+ik), angld)
 #endif
               CALL s2grid(ussp(:,ik), xx)
               CALL s2grid(ussp(:,nk+ik), xy)
               xxk(:,:,ik) = xx
               xyk(:,:,ik) = xy
             END DO
             !
             ! Total momentum to the ocean
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 13 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauocx(1:nsea), tauocy(1:nsea), angld)
 #endif
             IF( smcgrd ) THEN
 #ifdef W3_SMC
               CALL w3s2xy_smc( tauocx(1:nsea), xx )
               CALL w3s2xy_smc( tauocy(1:nsea), xy )
 #endif
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauocx(1:nsea)     &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauocy(1:nsea)     &
                    , mapsf, xy )
             ENDIF ! SMCGRD
             nfield=2
             !
             ! RMS of bottom displacement amplitude
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 1 ) THEN
             ! NB: ABA and ABD are the X and Y components of the bottom displacement
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, aba(1:nsea), abd(1:nsea), angld)
 #endif
             CALL s2grid(aba(1:nsea), xx)
             CALL s2grid(abd(1:nsea), xy)
             nfield=2
             !
             ! RMS of bottom velocity amplitude
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 2 ) THEN
             ! NB: UBA and UBD are the X and Y components of the bottom velocity
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, uba(1:nsea), ubd(1:nsea), angld)
 #endif
             CALL s2grid(uba(1:nsea), xx)
             CALL s2grid(ubd(1:nsea), xy)
             nfield=2
             !
             ! Bottom roughness
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 3 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, bedforms(1:nsea,2), &
                  bedforms(1:nsea,3), angld)
 #endif
             CALL s2grid(bedforms(1:nsea,1), x1)
             CALL s2grid(bedforms(1:nsea,2), x2)
             CALL s2grid(bedforms(1:nsea,3), xy)
             nfield=3
             !
             ! Wave dissipation in bottom boundary layer
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 4 ) THEN
             CALL s2grid(phibbl(1:nsea), x1)
             !
             ! Wave to bottom boundary layer stress
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 5 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, taubbl(1:nsea,1), &
                  taubbl(1:nsea,2), angld)
 #endif
             CALL s2grid(taubbl(1:nsea,1), xx)
             CALL s2grid(taubbl(1:nsea,2), xy)
             nfield=2
             !
             ! Mean square slope
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 1 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, mssx, mssy, angld)
 #endif
             CALL s2grid(mssx, xx)
             CALL s2grid(mssy, xy)
             nfield=2
             !
             ! Phillips constant
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 2 ) THEN
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, mscx, mscy, angld)
 #endif
             CALL s2grid(mscx, xx)
             CALL s2grid(mscy, xy)
             nfield=2
             !
             ! u direction for mss
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 3 ) THEN
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, mssd, angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( mssd(isea) .NE. undef )  THEN
                 mssd(isea) = mod( 630. - rade*mssd(isea) , 180. )
               END IF
             END DO
             CALL s2grid(mssd, x1)
             !
             ! x direction for msc
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 4 ) THEN
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, mscd, angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( mscd(isea) .NE. undef )  THEN
                 mscd(isea) = mod( 630. - rade*mscd(isea) , 180. )
               END IF
             END DO
             CALL s2grid(mscd, x1)
             !
             ! Peakedness
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 5 ) THEN
             CALL s2grid(qp, x1)
             !
             ! k bandwidth
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 6 ) THEN
             CALL s2grid(qkk, x1)
             !
             ! surface elevation skewness lambda_3,0,0
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 7 ) THEN
             CALL s2grid(skew, x1)
             !
             ! em bias param 1
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 8 ) THEN
             CALL s2grid(embia1, x1)
             !
             ! em bias param 2
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 9 ) THEN
             CALL s2grid(embia2, x1)
             !
             ! Dynamic time step
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 1 ) THEN
             DO isea=1, nsea
               IF ( dtdyn(isea) .NE. undef ) THEN
                 dtdyn(isea) = dtdyn(isea) / 60.
               END IF
             END DO
             CALL s2grid(dtdyn, x1)
             !
             ! Cut off frequency
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 2 ) THEN
             CALL s2grid(fcut, x1)
             !
             ! Maximum CFL for spatial advection
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 3 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=4
             CALL s2grid(cflxymax, x1)
             !
             ! Maximum CFL for direction advection
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 4 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=4
             CALL s2grid(cflthmax, x1)
             !
             ! Maximum CFL for frequency advection
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 5 ) THEN
             IF (ncvartypei.EQ.3) ncvartype=4
             CALL s2grid(cflkmax, x1)
             !
             ! User defined...
           ELSE IF ( ifi .EQ. 10 ) THEN
             !CB WRITE (ENAME,'(A2,I2.2)') '.u', IFJ
             CALL s2grid(usero(:,ifj), x1)
           ELSE
             WRITE (ndse,999) ifi, ifj
             CALL extcde ( 1 )
             !
           END IF ! IFI AND IFJ
           ! CB Get netCDF metadata for IFI, IFJ combination (all components).
           DO i=1,nfield
             meta(i) = getmeta(ifi, ifj, icomp=i, ipart=ipart)
           ENDDO
           ! 2.2 Make map
           ! CB: TODO - need to handle MAPSTA differently for SMC grid output.
           IF( .NOT. smcgrd ) THEN
             DO ix=1, nx
               DO iy=1, ny
                 mapout(ix,iy)=int2(mapsta(iy,ix) + 8*mapst2(iy,ix))
                 IF ( mapsta(iy,ix) .EQ. 0 ) THEN
                   x1(ix,iy) = undef
                   x2(ix,iy) = undef
                   xx(ix,iy) = undef
                   xy(ix,iy) = undef
                 END IF
                 IF ( x1(ix,iy) .EQ. undef ) THEN
                   map(ix,iy) = 0
                 ELSE
                   map(ix,iy) = 1
                 END IF
                 IF ( x2(ix,iy) .EQ. undef ) THEN
                   mp2(ix,iy) = 0
                 ELSE
                   mp2(ix,iy) = 1
                 END IF
               END DO
             END DO
           ENDIF ! CB
           ! 2.3 Setups the output type 4 ( NetCDF file )
           s2=len_trim(meta(1)%ENAME)
           s1=len_trim(fileprefix)+s4
           fnamenc(s1+1:128)='       '
           fnamenc(s1+1:s1+1) = '_'
           ! If flag TOGETHER and not variable with freq dim &
           ! (ef, p2l, ...), no variable name in file name
           IF (together.AND.(.NOT.flfrq)) THEN
             s2=0
             ! If NOT flag TOGETHER or variable with freq dim &
             ! (ef, p2l, ...), add variable name in file name
           ELSE
             fnamenc(s1+2:s1+s2) = meta(1)%ENAME(2:s2)
           ENDIF
           ! Defines the netcdf extension
           fnamenc(s1+s2+1:s1+s2+3) = '.nc'
           fnamenc(s1+s2+4:s1+s2+6) = '   '
           ! If the flag frequency is .TRUE., defines the fourth dimension
           IF (flfrq) THEN
             dimln(4)=i2f-i1f+1
             extradim=1
           ELSE
             dimln(4)=0
             extradim=0
           END IF
           ! If regular grid, initializes the lat/lon or x/y dimension lengths
           IF (gtype.NE.ungtype) THEN
             IF( smcgrd ) THEN
 #ifdef W3_SMC
               IF( smcotype .EQ. 1 ) THEN
                 ! Flat seapoints file
                 !dimln(2) = NSEA
                 dimln(2) = smcnout
                 dimln(3) = -1  ! not used
               ELSE
                 ! Regular gridded lat/lon file:
                 dimln(2) = nxo
                 dimln(3) = nyo
               ENDIF ! SMCOTYPE
 #endif
             ELSE ! SMCGRD
               dimln(2)=ixn-ix1+1
               dimln(3)=iyn-iy1+1
             ENDIF ! SMCGRD
             ! If unstructured mesh, initializes the nelem,tri dimension lengths
           ELSE
             dimln(2)=ixn-ix1+1
             dimln(3)=ntri
           ENDIF
           ! Defines index of first field variable
           ivar1=21
           ! 2.4.1 Save the id of the previous file
           IF (together.AND.(.NOT.flfrq)) THEN
             oldncid = ncids(1,1,1)
           ELSE
             oldncid = ncids(ifi,ifj,ipart+1)
           END IF
           ! 2.4.2 Remove the new file (if not created by the run)
           INQUIRE(file=fnamenc, exist=fexist)
           IF (fexist) THEN
             fremove = .false.
             ! time splitted condition
             IF (index(timeid,oldtimeid).EQ.0) THEN
               ! all variables in the samefile
               IF (together.AND.(.NOT.flfrq).AND.ncid.EQ.0) fremove = .true.
               ! a file per variable
               IF (.NOT.together.OR.flfrq) fremove = .true.
             END IF
             IF (fremove) THEN
               OPEN(unit=1234, iostat=iret, file=fnamenc, status='old')
               IF (iret == 0) CLOSE(1234, status='delete')
               fexist=.false.
             ELSE
               ncid = oldncid
             END IF
           END IF
           ! 2.4.3 Finalize the previous file (if a new one will be created)
           IF (.NOT.fexist) THEN
             IF (index('0000000000000000',oldtimeid).EQ.0 .AND. index(timeid,oldtimeid).EQ.0) THEN
               iret = nf90_redef(oldncid)
               CALL check_err(iret)
               IF(fl_default_gbl_meta) THEN
                 iret=nf90_put_att(oldncid,nf90_global,'stop_date',strstopdate)
                 CALL check_err(iret)
               ENDIF
               iret=nf90_close(oldncid)
               CALL check_err(iret)
             END IF
           END IF
           ! 2.5 Creates the netcdf file
           IF (.NOT.fexist) THEN
             ! Initializes the time dimension length
             dimln(1)=1
             ! If NOT unstructure mesh (i.e. regular grid)
             !! CHRISB: VARNM for lat/lon not actually used below.
             !              IF (GTYPE.NE.UNGTYPE) THEN
             !                ! If spherical coordinate
             !                IF (FLAGLL) THEN
             !                  VARNM(NFIELD+1)='Longitude'
             !                  VARNM(NFIELD+2)='Latitude'
             !                ! If cartesian coordinate
             !                ELSE
             !                  VARNM(NFIELD+1)='x'
             !                  VARNM(NFIELD+2)='y'
             !                END IF
             !              END IF
             ! Initializes the time iteration counter n
             n=1
             ! 2.5.1 Creates the NetCDF file
             CALL w3crnc(fnamenc,ncid,dimid,dimln,varid, &
                  extradim,nctype,mapstaout)
             ! Saves the NCID to keep the file opened to write all the variables
             ! and open/close at each time step
             IF (together.AND.(.NOT.flfrq)) THEN
               ncids(1,1,1)=ncid
             ELSE
               ncids(ifi,ifj,ipart+1)=ncid
             END IF
             ! If curvilinear grid, instanciates lat / lon
             IF (gtype.EQ.clgtype) THEN
               IF (.NOT.ALLOCATED(lon2d)) ALLOCATE(lon2d(nx,ny),lat2d(nx,ny))
               lon2d=transpose(xgrd)
               lat2d=transpose(ygrd)
               IF(fl_default_gbl_meta) THEN
                 iret=nf90_put_att(ncid,nf90_global, &
                      'latitude_resolution','n/a')
                 CALL check_err(iret)
                 iret=nf90_put_att(ncid,nf90_global, &
                      'longitude_resolution','n/a')
                 CALL check_err(iret)
               ENDIF
               ! If NOT curvilinear grid,
             ELSE
               IF( smcgrd ) THEN
 #ifdef W3_SMC
                 IF(smcotype .EQ. 1) THEN
                   ! Flat seapoints file
                   IF(.NOT.ALLOCATED(lon)) ALLOCATE(lon(smcnout))
                   IF(.NOT.ALLOCATED(lat)) ALLOCATE(lat(smcnout))
                   IF(.NOT.ALLOCATED(smccx)) ALLOCATE(smccx(smcnout))
                   IF(.NOT.ALLOCATED(smccy)) ALLOCATE(smccy(smcnout))
                 ELSE
                   ! Regular gridded file
                   IF(.NOT.ALLOCATED(lon)) ALLOCATE(lon(nxo))
                   IF(.NOT.ALLOCATED(lat)) ALLOCATE(lat(nyo))
 #endif
 #ifdef W3_RTD
                   ! Intermediate EQUatorial lat/lon arrays for de-rotation
                   ! of rotated pole coordinates:
                   !!IF(.NOT.ALLOCATED(LON2DEQ)) ALLOCATE(LON2DEQ(NXO,NYO))
                   !!IF(.NOT.ALLOCATED(LAT2DEQ)) ALLOCATE(LAT2DEQ(NXO,NYO))
                   !
                   ! Use local RTDNX/RTDNY variables until CPP implemented to
                   ! avoid compile error when SMC switch not enabled (C.Bunney):
                   IF(.NOT.ALLOCATED(lon2deq)) ALLOCATE(lon2deq(rtdnx,rtdny))
                   IF(.NOT.ALLOCATED(lat2deq)) ALLOCATE(lat2deq(rtdnx,rtdny))
 #endif
 #ifdef W3_SMC
                 ENDIF
 #endif
 #ifdef W3_RTD
                 ! Arrays for de-rotated lat/lon coordinates:
                 IF(.NOT.ALLOCATED(lon2d)) THEN
                   !!ALLOCATE(LON2D(NXO,NYO), LAT2D(NXO,NYO))
                   !!ALLOCATE(ANGLD2D(NXO,NYO))
                   !
                   ! Use local RTDNX/RTDNY variables until CPP implemented to
                   ! avoid compile error when SMC switch not enabled (C.Bunney):
                   ALLOCATE(lon2d(rtdnx,rtdny), lat2d(rtdnx,rtdny))
                   ALLOCATE(angld2d(rtdnx,rtdny))
                 ENDIF
 #endif
               ELSE ! SMCGRD
                 ! instanciates lon with x/lon for regular grid or nodes for unstructured mesh
                 IF (.NOT.ALLOCATED(lon)) ALLOCATE(lon(nx))
 #ifdef W3_RTD
                 ! 2d longitude array for standard grid coordinates
                 IF ( rtdl .AND. .NOT.ALLOCATED(lon2d)) &
                      ALLOCATE(lon2d(nx,ny),lon2deq(nx,ny),angld2d(nx,ny))
 #endif
                 IF (.NOT.ALLOCATED(lat)) THEN
                   ! If regular grid, instanciates lat with y/lat
                   IF (gtype.EQ.rlgtype) THEN
                     ALLOCATE(lat(ny))
 #ifdef W3_RTD
                     ! 2d latitude array for standard grid coordinates
                     IF ( rtdl .AND. .NOT.ALLOCATED(lat2d)) &
                          ALLOCATE(lat2d(nx,ny),lat2deq(nx,ny))
 #endif
                     ! If unstructured mesh, instanciates lat with nodes
                   ELSE
                     ALLOCATE(lat(nx))
                   END IF
                 END IF
               END IF ! SMCGRD
             END IF
             ! 2.5.2 Generates Lat-Lon arrays
             ! If regular grid
             IF (gtype.EQ.rlgtype .OR. gtype.EQ.smctype) THEN
               IF( smcgrd ) THEN
 #ifdef W3_SMC
                 ! CB: Calculate lat/lons of SMC grid
                 IF( smcotype .EQ. 1 ) THEN
                   ! CB: Flat seapoints file
                   DO i=1,smcnout
                     j = smcidx(i)
                     lon(i) = (x0-0.5*sx) + (ijkcel(1,j) + 0.5 * ijkcel(3,j)) * dlon
                     lat(i) = (y0-0.5*sy) + (ijkcel(2,j) + 0.5 * ijkcel(4,j)) * dlat
                     smccx(i) = ijkcel(3,j)
                     smccy(i) = ijkcel(4,j)
                   ENDDO
 #endif
 #ifdef W3_RTD
                   !!CALL W3EQTOLL(lat, lon, LAT2D(:,1), LON2D(:,1),       &
                   !!              ANGLD2D(:,1), POLAT, POLON, NYO*NXO)
                   !
                   ! Use local RTDNX/RTDNY variables until CPP implemented to
                   ! avoid compile error when SMC switch not enabled (C.Bunney):
                   CALL w3eqtoll(lat, lon, lat2d(:,1), lon2d(:,1),       &
                        angld2d(:,1), polat, polon, rtdny*rtdnx)
 #endif
 #ifdef W3_SMC
                 ELSE
                   ! CB: Regridded SMC data
                   sxd=dble(0.000001d0*dnint(1d6*(dble(dxo)) ))
                   syd=dble(0.000001d0*dnint(1d6*(dble(dyo)) ))
                   x0d=dble(0.000001d0*dnint(1d6*(dble(sxo)) ))
                   y0d=dble(0.000001d0*dnint(1d6*(dble(syo)) ))
                   DO i=1,nxo
                     lon(i)=real(x0d+sxd*dble(i-1))
 #endif
 #ifdef W3_RTD
                     lon2deq(i,:) = lon(i)
 #endif
 #ifdef W3_SMC
                   END DO
                   DO i=1,nyo
                     lat(i)=real(y0d+syd*dble(i-1))
 #endif
 #ifdef W3_RTD
                     lat2deq(:,i) = lat(i)
 #endif
 #ifdef W3_SMC
                   END DO
                   WRITE(str2,'(F12.7)') dyo
                   str2=adjustl(str2)
                   IF(fl_default_gbl_meta) THEN
                     iret=nf90_put_att(ncid,nf90_global,   &
                          'latitude_resolution', trim(str2))
                     WRITE(str2,'(F12.7)') dxo
                     str2=adjustl(str2)
                     iret=nf90_put_att(ncid,nf90_global,   &
                          'longitude_resolution',trim(str2))
                   ENDIF
 #endif
 #ifdef W3_RTD
                   !!CALL W3EQTOLL(LAT2DEQ, LON2DEQ, LAT2D, LON2D,       &
                   !!              ANGLD2D, POLAT, POLON, NYO*NXO)
                   !
                   ! Use local RTDNX/RTDNY variables until CPP implemented to
                   ! avoid compile error when SMC switch not enabled (C.Bunney):
                   CALL w3eqtoll(lat2deq, lon2deq, lat2d, lon2d,       &
                        angld2d, polat, polon, rtdny*rtdnx)
 #endif
 #ifdef W3_SMC
                 ENDIF ! SMCOTYPE
 #endif
               ELSE ! SMCGRD
                 sxd=dble(0.000001d0*dnint(1d6*(dble(sx)) ))
                 syd=dble(0.000001d0*dnint(1d6*(dble(sy)) ))
                 x0d=dble(0.000001d0*dnint(1d6*(dble(x0)) ))
                 y0d=dble(0.000001d0*dnint(1d6*(dble(y0)) ))
                 DO i=1,nx
                   lon(i)=real(x0d+sxd*dble(i-1))
                 END DO
                 DO i=1,ny
                   lat(i)=real(y0d+syd*dble(i-1))
                 END DO
 #ifdef W3_RTD
                 IF ( rtdl ) THEN
                   ! Calculate the standard grid coordinates
                   DO i=1,nx
                     lon2deq(i,:)=lon(i)
                   END DO
                   DO i=1,ny
                     lat2deq(:,i)=lat(i)
                   END DO
                   CALL w3eqtoll(lat2deq, lon2deq, lat2d, lon2d,       &
                        angld2d, polat, polon, ny*nx)
                 END IF ! RTDL
 #endif
                 IF(fl_default_gbl_meta) THEN
                   WRITE(str2,'(F12.0)') sy
                   str2=adjustl(str2)
                   iret=nf90_put_att(ncid,nf90_global,   &
                        'latitude_resolution', trim(str2))
                   CALL check_err(iret)
                   WRITE(str2,'(F12.0)') sx
                   str2=adjustl(str2)
                   iret=nf90_put_att(ncid,nf90_global,   &
                        'longitude_resolution',trim(str2))
                   CALL check_err(iret)
                 ENDIF
               END IF ! SMCGRD
             END IF
             ! If unstructured mesh
             IF (gtype.EQ.ungtype) THEN
               lon(:)=xgrd(1,:)
               lat(:)=ygrd(1,:)
               dimln(2)=nx
               dimln(3)=ntri
               IF(fl_default_gbl_meta) THEN
                 iret=nf90_put_att(ncid,nf90_global, &
                      'latitude_resolution','n/a')
                 CALL check_err(iret)
                 iret=nf90_put_att(ncid,nf90_global, &
                      'longitude_resolution','n/a')
                 CALL check_err(iret)
               ENDIF
             END IF
             ! Finishes declaration part in file by adding geographical bounds
             IF(fl_default_gbl_meta) THEN
               IF(smcgrd) THEN
                 WRITE(str2,'(F12.0)') minval(lat)
               ELSE
                 WRITE(str2,'(F12.0)') minval(ygrd)
               ENDIF
               str2=adjustl(str2)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'southernmost_latitude',trim(str2))
               CALL check_err(iret)
               IF(smcgrd) THEN
                 WRITE(str2,'(F12.0)') maxval(lat)
               ELSE
                 WRITE(str2,'(F12.0)') maxval(ygrd)
               ENDIF
               str2=adjustl(str2)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'northernmost_latitude',trim(str2))
               CALL check_err(iret)
               IF(smcgrd) THEN
                 WRITE(str2,'(F12.0)') minval(lon)
               ELSE
                 WRITE(str2,'(F12.0)') minval(xgrd)
               ENDIF
               str2=adjustl(str2)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'westernmost_longitude',trim(str2))
               CALL check_err(iret)
               IF(smcgrd) THEN
                 WRITE(str2,'(F12.0)') maxval(lon)
               ELSE
                 WRITE(str2,'(F12.0)') maxval(xgrd)
               ENDIF
               str2=adjustl(str2)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'easternmost_longitude',trim(str2))
               CALL check_err(iret)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'minimum_altitude','-12000 m')
               CALL check_err(iret)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'maximum_altitude','9000 m')
               CALL check_err(iret)
               iret=nf90_put_att(ncid,nf90_global,  &
                    'altitude_resolution','n/a')
               CALL check_err(iret)
 #ifdef W3_RTD
               IF ( rtdl ) THEN
                 iret=nf90_put_att(ncid,nf90_global,  &
                      'grid_north_pole_latitude',polat)
                 iret=nf90_put_att(ncid,nf90_global,  &
                      'grid_north_pole_longitude',polon)
               END IF
 #endif
             ENDIF ! FL_DEFAULT_GBL_META
             CALL t2d(time,startdate,ierr)
             WRITE(strstartdate,'(I4.4,A,4(I2.2,A),I2.2)') startdate(1),'-',startdate(2),'-', &
                  startdate(3),' ',startdate(5),':',startdate(6),':',startdate(7)
             ! End of define mode of NetCDF file
             iret = nf90_enddef(ncid)
             CALL check_err(iret)
             ! 2.5.3 Writes longitudes, latitudes, triangles, frequency and status map (mapsta) to netcdf file
             ! If regular grid
             IF (gtype.EQ.rlgtype .OR. gtype.EQ.smctype) THEN
               IF(smcgrd) THEN ! CB: shelter original code from SMC grid
 #ifdef W3_SMC
                 iret=nf90_put_var(ncid,varid(1),lon(:))
                 CALL check_err(iret)
                 iret=nf90_put_var(ncid,varid(2),lat(:))
                 CALL check_err(iret)
                 IF(smcotype .EQ. 1) THEN
                   ! For type 1 SCM file also put lat/lons and cell sizes:
                   iret=nf90_put_var(ncid,varid(5),smccx)
                   CALL check_err(iret)
                   iret=nf90_put_var(ncid,varid(6),smccy)
                   CALL check_err(iret)
                 ENDIF
 #endif
               ELSE ! SMCGRD
                 iret=nf90_put_var(ncid,varid(1),lon(ix1:ixn))
                 CALL check_err(iret)
                 iret=nf90_put_var(ncid,varid(2),lat(iy1:iyn))
                 CALL check_err(iret)
               ENDIF ! SMCGRD
 #ifdef W3_RTD
               IF ( rtdl ) THEN
                 iret=nf90_put_var(ncid,varid(7),lon2d(ix1:ixn,iy1:iyn))
                 CALL check_err(iret)
                 iret=nf90_put_var(ncid,varid(8),lat2d(ix1:ixn,iy1:iyn))
                 CALL check_err(iret)
               END IF
 #endif
             END IF
             ! If curvilinear grid
             IF (gtype.EQ.clgtype) THEN
               iret=nf90_put_var(ncid,varid(1),lon2d(ix1:ixn,iy1:iyn))
               CALL check_err(iret)
               iret=nf90_put_var(ncid,varid(2),lat2d(ix1:ixn,iy1:iyn))
               CALL check_err(iret)
             END IF
             ! If unstructured mesh
             IF (gtype.EQ.ungtype) THEN
               iret=nf90_put_var(ncid,varid(1),lon(ix1:ixn))
               CALL check_err(iret)
               iret=nf90_put_var(ncid,varid(2),lat(ix1:ixn))
               CALL check_err(iret)
             END IF
             ! Writes frequencies to netcdf file
             IF (extradim.EQ.1) THEN
               ALLOCATE(freq(i2f-i1f+1))
               !BGR Here is where we should tell it what frequencies are.
               IF (customfrq) THEN
                 DO i=1,usspf(2)
                   freq(i)=sqrt(grav*ussp_wn(i))*tpiinv
                 ENDDO
               ELSE
                 DO i=1,i2f-i1f+1
                   freq(i)=sig(i1f-1+i)*tpiinv
                 END DO
               ENDIF
               iret=nf90_put_var(ncid,varid(10),freq)
               CALL check_err(iret)
               DEALLOCATE(freq)
             END IF
             ! Writes triangles to netcdf file
             IF (gtype.EQ.ungtype) THEN
               iret=nf90_put_var(ncid,varid(4),trigp)
               CALL check_err(iret)
             END IF
             ! Writes status map array at variable index 2+1+coordtype+idim-4
             IF (mapstaout) THEN
               start(1)=1
               start(2)=1
               count(1)=ixn-ix1+1
               count(2)=iyn-iy1+1
               IF (gtype.NE.ungtype) THEN
                 iret=nf90_put_var(ncid,varid(20),mapout(ix1:ixn,iy1:iyn), &
                      (/start(1:2)/),(/count(1:2)/))
               ELSE
                 iret=nf90_put_var(ncid,varid(20),mapout(ix1:ixn,1),(/start(1)/),(/count(1)/))
               ENDIF
               CALL check_err(iret)
             END IF
             ! Write forecast reference time, if requested:
             IF (flgfc) THEN
               IF(timeunit .EQ. 'S') THEN
                 outsecs = tsubsec(epochdate, refdate)
                 iret = nf90_put_var(ncid, varid(12), outsecs)
               ELSE
                 outjulday = tsub(epochdate, refdate)
                 iret = nf90_put_var(ncid, varid(12), outjulday)
               ENDIF
               CALL check_err(iret)
             ENDIF
             WRITE (ndso,973) fnamenc
             ! 2.5.4  Defines the field(LON,LAT,time) of the variable (i.e. ucur,vcur for current variable)
             iret = nf90_redef(ncid)
             CALL check_err(iret)
             DO i=1,nfield
               ivar=ivar1+i
               IF (coordtype.EQ.1) THEN
                 IF (ncvartype.EQ.2) THEN
 #ifdef W3_SMC
                   IF( smcgrd .AND. smcotype .EQ. 1 ) THEN
                     ! SMC Flat file
                     iret = nf90_def_var(ncid,meta(i)%varnm, nf90_short, (/dimid(2), dimid(4+extradim)/), varid(ivar))
                   ELSE
 #endif
                     iret = nf90_def_var(ncid,meta(i)%varnm, nf90_short, dimid(2:4+extradim), varid(ivar))
 #ifdef W3_SMC
                   ENDIF
 #endif
                   CALL check_err(iret)
                   IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                   IF (nctype.EQ.4) CALL check_err(iret)
                 ELSE
 #ifdef W3_SMC
                   IF( smcgrd .AND. smcotype .EQ. 1 ) THEN
                     ! SMC Flat file
                     iret = nf90_def_var(ncid,meta(i)%varnm, nf90_float, (/dimid(2), dimid(4+extradim)/), varid(ivar))
                   ELSE
 #endif
                     iret = nf90_def_var(ncid,meta(i)%varnm, nf90_float, dimid(2:4+extradim), varid(ivar))
 #ifdef W3_SMC
                   ENDIF
 #endif
                   CALL check_err(iret)
                   IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                   IF (nctype.EQ.4) CALL check_err(iret)
                 END IF
               ELSE
                 dimfield(1)=dimid(2)
                 dimfield(2)=dimid(4)
                 dimfield(3)=dimid(5)
                 IF (ncvartype.EQ.2) THEN
                   iret = nf90_def_var(ncid,meta(i)%VARNM, nf90_short, dimfield(1:2+extradim), varid(ivar))
                   CALL check_err(iret)
                   IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                   IF (nctype.EQ.4) CALL check_err(iret)
                 ELSE
                   iret = nf90_def_var(ncid,meta(i)%VARNM, nf90_float, dimfield(1:2+extradim), varid(ivar))
                   CALL check_err(iret)
                   IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                   IF (nctype.EQ.4) CALL check_err(iret)
                 END IF
               END IF
               ! Set scale factor to 1.0 if using FLOAT variables for output
               IF(ncvartype .GT. 2) meta(i)%FSC = 1.0
               !! CB - USE NEW W3META MODULE
               CALL write_meta(ncid, varid(ivar), meta(i), iret) ! CB
               CALL check_err(iret) ! CB
               !
               !! CHRISB: Commenting out below - will be handled by w3oundmeta module
 #ifdef W3_RTD
               !        IF ( RTDL ) THEN
               !          ! Add grid mapping attribute for rotated pole grids:
               !          IRET=NF90_PUT_ATT(NCID,VARID(IVAR),'grid_mapping',    &
               !                            'rotated_pole')
               !          CALL CHECK_ERR(IRET)
               !          END IF
 #endif
             END DO
             !
             ! put START date in global attribute
             IF(fl_default_gbl_meta) THEN
               iret=nf90_put_att(ncid,nf90_global,'start_date',strstartdate)
               CALL check_err(iret)
             ENDIF
             !
             iret = nf90_enddef(ncid)
             CALL check_err(iret)
             ! 2.6 Append data to the existing file
           ELSE  ! FEXIST
             ! 2.6.1 Get the dimensions from the netcdf header
             ! If it is an unstructured mesh
             IF (gtype.EQ.ungtype) THEN
               iret=nf90_inq_varid(ncid, 'tri', varid(4))
               CALL check_err(iret)
               ! If it is a regular grid
             ELSE
               ! If it is spherical coordinate
               IF (flagll) THEN
 #ifdef W3_SMC
                 IF(smcgrd .AND. smcotype .EQ. 1) THEN
                   iret=nf90_inq_dimid(ncid, 'seapoint', dimid(2))
                 ELSE
 #endif
                   iret=nf90_inq_dimid(ncid, 'longitude', dimid(2))
                   iret=nf90_inq_dimid(ncid, 'latitude', dimid(3))
 #ifdef W3_SMC
                 ENDIF
 #endif
                 iret=nf90_inq_varid(ncid, 'longitude', varid(1))
                 iret=nf90_inq_varid(ncid, 'latitude', varid(2))
                 ! If it is cartesian coordinate
               ELSE
                 iret=nf90_inq_dimid(ncid, 'x', dimid(2))
                 iret=nf90_inq_varid(ncid, 'x', varid(1))
                 iret=nf90_inq_dimid(ncid, 'y', dimid(3))
                 iret=nf90_inq_varid(ncid, 'y', varid(2))
               END IF
               CALL check_err(iret)
             END IF
             ! Get the dimension time
             iret=nf90_inq_dimid(ncid, 'time', dimid(4+extradim))
             iret=nf90_inquire_dimension(ncid, dimid(4+extradim),len=n)
             CALL check_err(iret)
             iret=nf90_inq_varid(ncid, 'time', varid(3))
             IF( flgfc ) THEN
               iret = nf90_inq_varid(ncid, 'forecast_period', varid(11))
               CALL check_err(iret)
             ENDIF
             ! Get the dimension f
             IF (extradim.EQ.1) iret=nf90_inq_dimid(ncid, 'f', dimid(4))
             ! 2.6.2 Increments the time step for existing file
             ! If it is the first field of the file in mode together
             ! or NOT together or variable with freq dim (ef or p2l)
             ! ChrisBunney: Also - check IPART=TABIPART in case first
             ! requested output is a partitioned field.
             IF((together .AND. ifi.EQ.i1 .AND. ifj.EQ.j1 .AND. ipart.EQ.tabipart(1))  &
                  .OR.(.NOT.together).OR.flfrq) n=n+1
             ! 2.6.3 Defines or gets the variables identifiers
             ! If it is the first time step, define all the variables and attributes
             IF (n.EQ.1) THEN
               iret = nf90_redef(ncid)
               CALL check_err(iret)
               ! Loops on all the fields of the variable (i.e. ucur/vcur for current)
               DO i=1,nfield
                 ivar=ivar1+i
                 IF (coordtype.EQ.1) THEN
                   IF (ncvartype.EQ.2) THEN
 #ifdef W3_SMC
                     IF( smcgrd .AND. smcotype .EQ. 1 ) THEN
                       ! SMC Flat file
                       iret = nf90_def_var(ncid,meta(i)%varnm, nf90_short, (/dimid(2), dimid(4+extradim)/), varid(ivar))
                     ELSE
 #endif
                       iret = nf90_def_var(ncid,meta(i)%varnm, nf90_short, dimid(2:4+extradim), varid(ivar))
 #ifdef W3_SMC
                     ENDIF
 #endif
                     CALL check_err(iret)
                     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                   ELSE
 #ifdef W3_SMC
                     IF( smcgrd .AND. smcotype .EQ. 1 ) THEN
                       ! SMC Flat file
                       iret = nf90_def_var(ncid,meta(i)%varnm, nf90_float, (/dimid(2), dimid(4+extradim)/), varid(ivar))
                     ELSE
 #endif
                       iret = nf90_def_var(ncid,meta(i)%varnm, nf90_float, dimid(2:4+extradim), varid(ivar))
 #ifdef W3_SMC
                     ENDIF
 #endif
                     CALL check_err(iret)
                     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                     IF (nctype.EQ.4) CALL check_err(iret)
                   END IF
                 ELSE
                   dimfield(1)=dimid(2)
                   dimfield(2)=dimid(4)
                   dimfield(3)=dimid(5)
                   IF (ncvartype.EQ.2) THEN
                     iret = nf90_def_var(ncid,meta(i)%varnm, nf90_short, dimfield(1:2+extradim), varid(ivar))
                     CALL check_err(iret)
                     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                     IF (nctype.EQ.4) CALL check_err(iret)
                   ELSE
                     iret = nf90_def_var(ncid,meta(i)%varnm, nf90_float, dimfield(1:2+extradim), varid(ivar))
                     CALL check_err(iret)
                     IF (nctype.EQ.4) iret = nf90_def_var_deflate(ncid, varid(ivar), 1, 1, deflate)
                     CALL check_err(iret)
                   END IF
                 END IF
                 !
                 ! Set scale factor to 1.0 if using FLOAT variables for output
                 IF(ncvartype .GT. 2) meta(i)%FSC = 1.0
                 !! CB - USE NEW W3META MODULE
                 CALL write_meta(ncid, varid(ivar), meta(i), iret) ! CB
                 CALL check_err(iret) ! CB
                 !
                 !! CHRISB: Commenting out below - will be handled by w3oundmeta module
 #ifdef W3_RTD
                 !          IF ( RTDL ) THEN
                 !            ! Add grid mapping attribute for rotated pole grids:
                 !            IRET=NF90_PUT_ATT(NCID,VARID(IVAR),'grid_mapping',   &
                 !                              'rotated_pole')
                 !            CALL CHECK_ERR(IRET)
                 !            END IF
 #endif
               END DO
               iret = nf90_enddef(ncid)
               CALL check_err(iret)
               ! If it is not the first time step, get all VARID from the netcdf file opened
             ELSE
               iret=nf90_redef(ncid)
               CALL check_err(iret)
               DO i=1,nfield
                 ! Get meta-data for field
                 !META = GETMETA(IFI, IFJ, ICOMP=I, IPART=IPART)
                 ivar=ivar1+i
                 iret=nf90_inq_varid(ncid, meta(i)%VARNM, varid(ivar))
                 CALL check_err(iret)
               END DO
               iret=nf90_enddef(ncid)
               CALL check_err(iret)
             END IF !   N.EQ.1
           END IF  ! FEXIST
           ! 2.6.4 Defines the current time step and index
           CALL t2d(time,curdate,ierr)
           WRITE(ndso,'(A,A9,A,I6,A,I4,A,I2.2,A,I2.2,A,I2.2,A,I2.2,A,I2.2,2A)')        &
                'Writing new record ', meta(1)%ENAME(2:) ,'number ',n,    &
                ' for ',curdate(1),':',curdate(2),':',curdate(3),'T',curdate(5),&
                ':',curdate(6),':',curdate(7),' in file ',trim(fnamenc)
           ! Defines starting point and size of arrays to be written
           start(1)=1
           start(2)=1
           start(3)=1
           start(4)=1
           ! Sets time index
           start(3+1-coordtype+extradim)=n
           count(1)=ixn-ix1+1
           count(2)=iyn-iy1+1
           count(3)=1
           count(4)=1
           start1d(1)=1
           start1d(2)=n
           count1d(1)=ixn-ix1+1
           count1d(2)=1
           ! Puts time in NetCDF file
           IF((ifi.EQ.i1.AND.ifj.EQ.j1.AND.together)  &
                .OR.(.NOT.together).OR.flfrq) THEN
             ivar1 = 21
             IF(timeunit .EQ. 'S') THEN
               ! Time in seconds
               outsecs = tsubsec(epochdate,curdate)
               iret = nf90_put_var(ncid, varid(3), outsecs, (/n/))
             ELSE
               ! Time in days
               outjulday = tsub(epochdate,curdate)
               iret = nf90_put_var(ncid, varid(3), outjulday, (/n/))
             ENDIF
             CALL check_err(iret)
             ! ChrisB: Calculate forecast period w.r.t. forecast reference time:
             IF (flgfc) THEN
               outsecs = tsubsec(refdate, curdate)
               iret = nf90_put_var(ncid, varid(11), outsecs, (/n/))
               CALL check_err(iret)
             ENDIF
           END IF
           !
           ! 2.6.5 Puts field(s) in NetCDF file
           ! NFIELD=3
           IF (ncvartype.EQ.2) THEN
             IF ( nfield.EQ.3 ) THEN
               DO ix=ix1, ixn
                 DO iy=iy1, iyn
                   IF ( x1(ix,iy) .EQ. undef ) THEN
                     mxx(ix,iy) = mfill
                     myy(ix,iy) = mfill
                     mxy(ix,iy) = mfill
                   ELSE
                     mxx(ix,iy) = nint(x1(ix,iy)/meta(1)%FSC)
                     myy(ix,iy) = nint(x2(ix,iy)/meta(2)%FSC)
                     mxy(ix,iy) = nint(xy(ix,iy)/meta(3)%FSC)
                   END IF
                 END DO
               END DO
 #ifdef W3_SMC
               IF(smcgrd .AND. smcotype .EQ. 1) THEN
                 iret=nf90_put_var(ncid,varid(ivar1+1),               &
                      mxx(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+2),               &
                      myy(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+3),               &
                      mxy(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                 call check_err(iret)
               ELSE
 #endif
                 iret=nf90_put_var(ncid,varid(ivar1+1),               &
                      mxx(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+2),               &
                      myy(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+3),               &
                      mxy(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                 call check_err(iret)
 #ifdef W3_SMC
               ENDIF
 #endif
               ! NFIELD=2
             ELSE IF (nfield.EQ.2 ) THEN
               ! EXTRADIM=0
               IF (extradim.EQ.0) THEN
                 DO ix=ix1, ixn
                   DO iy=iy1, iyn
                     IF ( xx(ix,iy) .EQ. undef ) THEN
                       mxx(ix,iy) = mfill
                       myy(ix,iy) = mfill
                     ELSE
                       mxx(ix,iy) = nint(xx(ix,iy)/meta(1)%FSC)
                       myy(ix,iy) = nint(xy(ix,iy)/meta(2)%FSC)
                     END IF
                   END DO
                 END DO
 #ifdef W3_SMC
                 IF(smcgrd .AND. smcotype .EQ. 1) THEN
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mxx(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                   call check_err(iret)
                   iret=nf90_put_var(ncid,varid(ivar1+2),               &
                        myy(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                   call check_err(iret)
                 ELSE
 #endif
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mxx(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                   call check_err(iret)
                   iret=nf90_put_var(ncid,varid(ivar1+2),               &
                        myy(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                   call check_err(iret)
 #ifdef W3_SMC
                 ENDIF
 #endif
                 ! EXTRADIM=1
               ELSE
                 start(3+1-coordtype)=0
                 DO ik=i1f,i2f
                   start(3+1-coordtype)=start(3+1-coordtype)+1
                   DO ix=ix1, ixn
                     DO iy=iy1, iyn
                       IF ( xxk(ix,iy,ik) .EQ. undef ) THEN
                         mxx(ix,iy) = mfill
                         myy(ix,iy) = mfill
                       ELSE
                         mxx(ix,iy) = nint(xxk(ix,iy,ik)/meta(1)%FSC)
                         myy(ix,iy) = nint(xyk(ix,iy,ik)/meta(2)%FSC)
                       END IF
                     END DO
                   END DO
 #ifdef W3_SMC
                   IF(smcgrd .AND. smcotype .EQ. 1) THEN
                     iret=nf90_put_var(ncid,varid(ivar1+1),                      &
                          mxx(ix1:ixn,iy1:iyn),(/start(1), start(3), start(4)/), &
                          (/count(1), count(3), count(4)/))
                     call check_err(iret)
                     iret=nf90_put_var(ncid,varid(ivar1+2),                      &
                          mxy(ix1:ixn,iy1:iyn),(/start(1), start(3), start(4)/), &
                          (/count(1), count(3), count(4)/))
                     call check_err(iret)
                   ELSE
 #endif
                     iret=nf90_put_var(ncid,varid(ivar1+1),               &
                          mxx(ix1:ixn,iy1:iyn),(/start(1:4)/),(/count(1:4)/))
                     call check_err(iret)
                     iret=nf90_put_var(ncid,varid(ivar1+2),               &
                          mxx(ix1:ixn,iy1:iyn),(/start(1:4)/),(/count(1:4)/))
                     call check_err(iret)
 #ifdef W3_SMC
                   ENDIF
 #endif
                 END DO
               END IF  ! EXTRADIM
               ! NFIELD=1
             ELSE
               ! EXTRADIM=0
               IF (extradim.EQ.0) THEN
                 DO ix=ix1, ixn
                   DO iy=iy1, iyn
                     IF ( x1(ix,iy) .EQ. undef ) THEN
                       mx1(ix,iy) = mfill
                     ELSE
                       mx1(ix,iy) = nint(x1(ix,iy)/meta(1)%FSC)
                     END IF
                   END DO
                 END DO
 #ifdef W3_SMC
                 IF(smcgrd .AND. smcotype .EQ. 1) THEN
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mx1(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                   call check_err(iret)
                 ELSE
 #endif
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mx1(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                   call check_err(iret)
 #ifdef W3_SMC
                 ENDIF
 #endif
                 ! EXTRADIM=1
               ELSE
                 start(3+1-coordtype)=0
                 DO ik=i1f,i2f
                   start(3+1-coordtype)=start(3+1-coordtype)+1
                   DO ix=ix1, ixn
                     DO iy=iy1, iyn
                       IF ( xk(ix,iy,ik) .EQ. undef ) THEN
                         mx1(ix,iy) = mfill
                       ELSE
                         mx1(ix,iy) = nint(xk(ix,iy,ik)/meta(1)%FSC)
                       END IF
                     END DO
                   END DO
 #ifdef W3_SMC
                   IF(smcgrd .AND. smcotype .EQ. 1) THEN
                     iret=nf90_put_var(ncid,varid(ivar1+1),                      &
                          mx1(ix1:ixn,iy1:iyn),(/start(1), start(3), start(4)/), &
                          (/count(1), count(3), count(4)/))
                     call check_err(iret)
                   ELSE
 #endif
                     iret=nf90_put_var(ncid,varid(ivar1+1),               &
                          mx1(ix1:ixn,iy1:iyn),(/start(1:4)/),(/count(1:4)/))
                     call check_err(iret)
 #ifdef W3_SMC
                   ENDIF
 #endif
                 END DO
               END IF   ! EXTRADIM
             END IF   ! NFIELD
             !
             ! Real output (NCVARTYPE.GE.3)
             !
           ELSE
             IF ( nfield.EQ.3 ) THEN
               DO ix=ix1, ixn
                 DO iy=iy1, iyn
                   IF ( x1(ix,iy) .EQ. undef ) THEN
                     mxxr(ix,iy) = mfillr
                     myyr(ix,iy) = mfillr
                     mxyr(ix,iy) = mfillr
                   ELSE
                     mxxr(ix,iy) = x1(ix,iy)
                     myyr(ix,iy) = x2(ix,iy)
                     mxyr(ix,iy) = xy(ix,iy)
                   END IF
                 END DO
               END DO
 #ifdef W3_SMC
               IF(smcgrd .AND. smcotype .EQ. 1) THEN
                 iret=nf90_put_var(ncid,varid(ivar1+1),               &
                      mxxr(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+2),               &
                      myyr(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+3),               &
                      mxyr(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                 call check_err(iret)
               ELSE
 #endif
                 iret=nf90_put_var(ncid,varid(ivar1+1),               &
                      mxxr(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+2),               &
                      myyr(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                 call check_err(iret)
                 iret=nf90_put_var(ncid,varid(ivar1+3),               &
                      mxyr(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                 call check_err(iret)
 #ifdef W3_SMC
               ENDIF
 #endif
               ! NFIELD=2
             ELSE IF (nfield.EQ.2 ) THEN
               ! EXTRADIM=0
               IF (extradim.EQ.0) THEN
                 DO ix=ix1, ixn
                   DO iy=iy1, iyn
                     IF ( xx(ix,iy) .EQ. undef ) THEN
                       mxxr(ix,iy) = mfillr
                       myyr(ix,iy) = mfillr
                     ELSE
                       mxxr(ix,iy) = xx(ix,iy)
                       myyr(ix,iy) = xy(ix,iy)
                     END IF
                   END DO
                 END DO
 #ifdef W3_SMC
                 IF(smcgrd .AND. smcotype .EQ. 1) THEN
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mxxr(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                   call check_err(iret)
                   iret=nf90_put_var(ncid,varid(ivar1+2),               &
                        myyr(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                   call check_err(iret)
                 ELSE
 #endif
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mxxr(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                   call check_err(iret)
                   iret=nf90_put_var(ncid,varid(ivar1+2),               &
                        myyr(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                   call check_err(iret)
 #ifdef W3_SMC
                 ENDIF
 #endif
                 ! EXTRADIM=1
               ELSE
                 start(4-coordtype)=0
                 DO ik=i1f,i2f
                   start(4-coordtype)=start(4-coordtype)+1
                   DO ix=ix1, ixn
                     DO iy=iy1, iyn
                       IF ( xxk(ix,iy,ik) .EQ. undef ) THEN
                         mxxr(ix,iy) = mfillr
                         myyr(ix,iy) = mfillr
                       ELSE
                         mxxr(ix,iy) = xxk(ix,iy,ik)
                         myyr(ix,iy) = xyk(ix,iy,ik)
                       END IF
                     END DO
                   END DO
 #ifdef W3_SMC
                   IF(smcgrd .AND. smcotype .EQ. 1) THEN
                     iret=nf90_put_var(ncid,varid(ivar1+1),                       &
                          mxxr(ix1:ixn,iy1:iyn),(/start(1), start(3), start(4)/), &
                          (/count(1), count(3), count(4)/))
                     call check_err(iret)
                     iret=nf90_put_var(ncid,varid(ivar1+2),                       &
                          myyr(ix1:ixn,iy1:iyn),(/start(1), start(3), start(4)/), &
                          (/count(1), count(3), count(4)/))
                     call check_err(iret)
                   ELSE
 #endif
                     iret=nf90_put_var(ncid,varid(ivar1+1),               &
                          mxxr(ix1:ixn,iy1:iyn),(/start(1:4)/),(/count(1:4)/))
                     call check_err(iret)
                     iret=nf90_put_var(ncid,varid(ivar1+2),               &
                          myyr(ix1:ixn,iy1:iyn),(/start(1:4)/),(/count(1:4)/))
                     call check_err(iret)
 #ifdef W3_SMC
                   ENDIF
 #endif
                 END DO
               END IF  ! EXTRADIM
               ! NFIELD=1
             ELSE
               ! EXTRADIM=0
               IF (extradim.EQ.0) THEN
                 DO ix=ix1, ixn
                   DO iy=iy1, iyn
                     IF ( x1(ix,iy) .EQ. undef ) THEN
                       mx1r(ix,iy) = mfillr
                     ELSE
                       mx1r(ix,iy) = x1(ix,iy)
                     END IF
                   END DO
                 END DO
 #ifdef W3_SMC
                 IF(smcgrd .AND. smcotype .EQ. 1) THEN
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mx1r(ix1:ixn,iy1:iyn),(/start(1), start(3)/),(/count(1), count(3)/))
                   call check_err(iret)
                 ELSE
 #endif
                   iret=nf90_put_var(ncid,varid(ivar1+1),               &
                        mx1r(ix1:ixn,iy1:iyn),(/start(1:3)/),(/count(1:3)/))
                   call check_err(iret)
 #ifdef W3_SMC
                 ENDIF
 #endif
                 ! EXTRADIM=1
               ELSE
                 start(4-coordtype)=0
                 DO ik=i1f,i2f
                   start(4-coordtype)=start(4-coordtype)+1
                   DO ix=ix1, ixn
                     DO iy=iy1, iyn
                       IF ( xk(ix,iy,ik) .EQ. undef ) THEN
                         mx1r(ix,iy) = mfillr
                       ELSE
                         mx1r(ix,iy) = xk(ix,iy,ik)
                       END IF
                     END DO
                   END DO
 #ifdef W3_SMC
                   IF(smcgrd .AND. smcotype .EQ. 1) THEN
                     iret=nf90_put_var(ncid,varid(ivar1+1),                       &
                          mx1r(ix1:ixn,iy1:iyn),(/start(1), start(3), start(4)/), &
                          (/count(1), count(3), count(4)/))
                     call check_err(iret)
                   ELSE
 #endif
                     iret=nf90_put_var(ncid,varid(ivar1+1),               &
                          mx1r(ix1:ixn,iy1:iyn),(/start(1:4)/),(/count(1:4)/))
                     call check_err(iret)
 #ifdef W3_SMC
                   ENDIF
 #endif
                 END DO
               END IF   ! EXTRADIM
             END IF   ! NFIELD
           END IF   ! NCVARTYPE
           ! updates the variable index
           ivar1=ivar1+nfield
           ! Loops over IPART for partition variables
           ! ChrisBunney: Don't loop IPART for last two entries in section 4
           ! (16: total wind sea fraction, 17: number of parts) as these fields
           ! do not have partitions.
           IF (ifi .EQ. 4 .AND. ifj .LE. noge(ifi) - 2) THEN
 560         CONTINUE
             IF (indexipart.LT.nbipart) THEN
               indexipart=indexipart+1
               IF (tabipart(indexipart).EQ.-1) GOTO 560
               ipart=tabipart(indexipart)
               GOTO 555
             END IF
           ELSE
             indexipart=1
           END IF
           !
         END IF  ! FLG2D(IFI,IFJ)
       END DO  ! IFI=1, NOGRP
     END DO  ! IFJ=1, NGRPP
     !
     ! Clean up
     DEALLOCATE(x1, x2, xx, xy, xk, xxk, xyk)
     DEALLOCATE(mx1, mxx, myy, mxy, mapout)
     DEALLOCATE(mx1r, mxxr, myyr, mxyr)
     DEALLOCATE(aux1)
     IF (ALLOCATED(lon)) DEALLOCATE(lon, lat)
     IF (ALLOCATED(lon2d)) DEALLOCATE(lon2d, lat2d)
 #ifdef W3_RTD
     IF (ALLOCATED(lon2deq)) DEALLOCATE(lat2deq, lon2deq, angld2d)
 #endif
     !
     RETURN
     !
     ! Error escape locations
     !
     !
     ! Formats
     !
 973 FORMAT ( 'NEW NETCDF FILE WAS CREATED ',a)
 999 FORMAT (/' *** WAVEWATCH III ERROR IN W3EXNC :'/                &
          '     PLEASE UPDATE FIELDS !!! '/                      &
          '     IFI = ',i2, '- IFJ = ',i2/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3EXNC : FLAGS :',i3,2x,20l2)
 9001 FORMAT (' TEST W3EXNC : ITPYE :',i4/                         &
          '             IX1/N   :',2i7/                        &
          '             IY1/N   :',2i7/                        &
          '             VECTOR  :',1l2)
 #endif
     !
 #ifdef W3_T
 9012 FORMAT (' TEST W3EXNC : BLOK PARS    : ',3i4)
 9014 FORMAT ('           BASE NAME : ',a)
 #endif
     !
 #ifdef W3_T
 9020 FORMAT (' TEST W3EXNC : OUTPUT FIELD : ',a)
 #endif
     !/
     !/ End of W3EXNC ----------------------------------------------------- /
     !/
References w3gdatmd::angld, check_err(), w3gdatmd::clgtype, constants::dwat, file(), w3gdatmd::flagll, w3gdatmd::flagunr, constants::grav, w3gdatmd::gtype, w3gdatmd::mapsf, w3gdatmd::mapst2, w3gdatmd::mapsta, w3odatmd::ndst, w3gdatmd::nk, w3gdatmd::ntri, w3arrymd::outa2i(), w3gdatmd::polat, w3gdatmd::polon, w3arrymd::prtblk(), constants::rade, w3gdatmd::rlgtype, s2grid(), w3gdatmd::sig, w3gdatmd::sx, w3gdatmd::sy, constants::tpiinv, w3gdatmd::trigp, constants::undef, w3gdatmd::ungtype, w3gdatmd::ussp_wn, w3servmd::uv_to_mag_dir(), uv_to_mag_dir(), w3crnc(), w3servmd::w3eqtoll(), w3servmd::w3s2xy(), w3servmd::w3thrtn(), w3servmd::w3xyrtn(), w3gdatmd::x0, w3gdatmd::xgrd, w3gdatmd::y0, and w3gdatmd::ygrd.
Referenced by w3ounf(), w3ounp(), and w3trnc().
w3ounf()
program w3ounf
Post-processing of grid output to NetCDF files.
Data is read from the grid output file out_grd.ww3 (raw data) and from the file ww3_ounf.nml or ww3_ounf.inp (NDSI) Model definition and raw data files are read using WAVEWATCH III subroutines. Extra global NetCDF attributes may be read from ASCII file NC_globatt.inp.
Author
F. Ardhuin
M. Accensi
Date
02-Sep-2021
Definition at line 21 of file ww3_ounf.F90.
References w3adatmd::aba, w3adatmd::abd, w3adatmd::as, w3adatmd::bedforms, w3wdatmd::berg, w3adatmd::bhd, w3smcomd::celfac, w3adatmd::cflkmax, w3adatmd::cflthmax, w3adatmd::cflxymax, w3adatmd::cge, w3adatmd::charn, check_err(), w3ounfmetamd::coords_attr, w3ounfmetamd::crs_meta, w3ounfmetamd::crs_name, w3adatmd::cx, w3adatmd::cy, w3adatmd::dtdyn, w3adatmd::dw, w3adatmd::ef, w3adatmd::embia1, w3adatmd::embia2, w3smcomd::exo, w3servmd::extcde(), w3smcomd::eyo, w3adatmd::fcut, file(), w3ounfmetamd::fl_default_gbl_meta, w3odatmd::flogrd, w3odatmd::fnmpre, w3adatmd::fp0, w3ounfmetamd::getmeta(), w3gdatmd::gname, w3gdatmd::gtype, w3adatmd::hcmaxd, w3adatmd::hcmaxe, w3adatmd::hmaxd, w3adatmd::hmaxe, w3adatmd::hs, w3adatmd::hsig, w3odatmd::iaproc, w3wdatmd::ice, w3wdatmd::icef, w3wdatmd::iceh, w3odatmd::idout, w3ounfmetamd::init_meta(), w3servmd::itrace(), w3adatmd::mscd, w3adatmd::mscx, w3adatmd::mscy, w3adatmd::mssd, w3adatmd::mssx, w3adatmd::mssy, w3odatmd::naproc, w3ounfmetamd::ncvartype, w3odatmd::ndse, w3odatmd::ndso, w3servmd::nextln(), w3odatmd::ngrpp, w3odatmd::noge, w3odatmd::nogrp, w3odatmd::noswll, w3smcomd::noval, w3adatmd::p2sms, w3adatmd::pdir, w3adatmd::pep, w3adatmd::pgw, w3adatmd::phiaw, w3adatmd::phibbl, w3adatmd::phice, w3adatmd::phioc, w3adatmd::phs, w3adatmd::plp, w3adatmd::pnr, w3gdatmd::polat, w3adatmd::ppe, w3adatmd::pqp, w3adatmd::prms, w3adatmd::psi, w3adatmd::psw, w3adatmd::pt1, w3adatmd::pt2, w3odatmd::ptfcut, w3adatmd::pthp0, w3adatmd::ptm1, w3odatmd::ptmeth, w3adatmd::ptp, w3adatmd::pws, w3adatmd::pwst, w3adatmd::qkk, w3adatmd::qp, w3wdatmd::rhoair, w3odatmd::screen, w3adatmd::skew, w3smcomd::smcotype, w3gdatmd::smctype, w3adatmd::sth1m, w3adatmd::sth2m, w3adatmd::stmaxd, w3adatmd::stmaxe, w3servmd::str_to_upper(), w3servmd::strace(), w3initmd::switches, w3smcomd::sxo, w3adatmd::sxx, w3adatmd::sxy, w3smcomd::syo, w3adatmd::syy, w3adatmd::t01, w3adatmd::t02, w3adatmd::t0m1, w3adatmd::taua, w3adatmd::tauadir, w3adatmd::taubbl, w3adatmd::tauice, w3adatmd::tauocx, w3adatmd::tauocy, w3adatmd::tauox, w3adatmd::tauoy, w3adatmd::tauwix, w3adatmd::tauwiy, w3adatmd::tauwnx, w3adatmd::tauwny, w3ounfmetamd::teardown_meta(), w3adatmd::th1m, w3adatmd::th2m, w3adatmd::thm, w3adatmd::thp0, w3adatmd::ths, w3wdatmd::time, w3adatmd::tpms, w3adatmd::tusx, w3adatmd::tusy, w3adatmd::tws, w3adatmd::ua, w3adatmd::uba, w3adatmd::ubd, w3adatmd::ud, constants::undef, w3adatmd::us3d, w3adatmd::usero, w3adatmd::ussp, w3adatmd::ussx, w3adatmd::ussy, w3wdatmd::ust, w3wdatmd::ustdir, w3exnc(), w3iogomd::w3flgrdflag(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3nmlounfmd::w3nmlounf(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3iogomd::w3readflgrd(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3adatmd::wbt, w3adatmd::whitecap, w3adatmd::wlm, w3wdatmd::wlv, w3adatmd::wn, w3adatmd::wnmean, w3ounfmetamd::write_freeform_meta_list(), w3ounfmetamd::write_global_meta(), w3ounfmetamd::write_meta(), w3initmd::wwver, and w3wdatmd::zeta_setup.