WAVEWATCH III: ww3_shel.F90 File Reference
ww3_shel.F90 File Reference
Contains generic shell for WAVEWATCH III, W3SHEL.
Functions/Subroutines
program w3shel
A generic shell for WAVEWATCH III, using preformatted input fields.
Detailed Description
Contains generic shell for WAVEWATCH III, W3SHEL.
Author
H. L. Tolman
Date
22-Mar-2021
Definition in file ww3_shel.F90.
Function/Subroutine Documentation
w3shel()
program w3shel
A generic shell for WAVEWATCH III, using preformatted input fields.
Driver for the actual wave model (W3WAVE).
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 16 of file ww3_shel.F90.
References w3oacpmd::cpl_oasis_define(), w3oacpmd::cpl_oasis_finalize(), w3oacpmd::cpl_oasis_grid(), w3oacpmd::cpl_oasis_init(), w3oacpmd::cplt0, w3timemd::d2j(), w3gdatmd::dtmax, w3odatmd::dtout, w3servmd::extcde(), file(), w3gdatmd::flagll, w3idatmd::flagsc, w3iogomd::fldout, w3odatmd::flogr, w3odatmd::flogrr, w3odatmd::flout, w3odatmd::fnmpre, w3odatmd::iaproc, w3oacpmd::id_oasis_time, w3odatmd::idout, include(), w3idatmd::inflags1, w3idatmd::inflags2, w3odatmd::iostyp, w3idatmd::jfirst, constants::lpdlib, w3odatmd::naperr, w3odatmd::napout, w3odatmd::naproc, w3servmd::nextln(), w3odatmd::ngrpp, w3odatmd::nogrp, w3odatmd::notype, w3iorsmd::oarst, w3odatmd::ofiles, w3servmd::print_memcheck(), w3wdatmd::qi5tbeg, w3agcmmd::snd_fields_to_atmos(), w3igcmmd::snd_fields_to_ice(), w3ogcmmd::snd_fields_to_ocean(), w3timemd::t2d(), w3wdatmd::time, w3wdatmd::time00, w3wdatmd::timeend, w3wdatmd::va, w3adatmd::w3dima(), w3wdatmd::w3dimw(), w3iogomd::w3flgrdflag(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3idatmd::w3ninp(), w3nmlshelmd::w3nmlshel(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3iogomd::w3readflgrd(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3idatmd::w3seti(), w3odatmd::w3seto(), and w3wdatmd::w3setw().