WAVEWATCH III: ww3_outf.F90 File Reference
ww3_outf.F90 File Reference
Post-processing of grid output.
Functions/Subroutines
program w3outf
Post-processing of grid output.
subroutine w3exgo (NX, NY, NSEA)
Perform actual grid output.
Detailed Description
Post-processing of grid output.
Author
H. L. Tolman
Date
22-Mar-2021
Definition in file ww3_outf.F90.
Function/Subroutine Documentation
w3exgo()
subroutine w3outf::w3exgo (integer NX, integer NY, integer NSEA)
Perform actual grid output.
Note that arrays CX and CY of the main program now contain the absolute current speed and direction respectively.
Parameters
NX X grid dimension
NY Y grid dimension
NSEA Number of sea points
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 548 of file ww3_outf.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |           H. L. Tolman            |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         22-Mar-2021 |
     !/                  +-----------------------------------+
     !/
     !/    26-Sep-1997 : Final FORTRAN 77                    ( version 1.18 )
     !/    19-Jan-2000 : Upgrade to FORTRAN 90               ( version 2.00 )
     !/                  Massive changes to logistics
     !/    24-Jan-2001 : Flat grid version                   ( version 2.06 )
     !/    23-Apr-2002 : Clean-up                            ( version 2.19 )
     !/    29-Apr-2002 : Adding output fields 17-18.         ( version 2.20 )
     !/    16-Oct-2002 : Fix bound. error for stress output. ( version 3.00 )
     !/    16-Oct-2002 : Fix statistical output for UNDEF.   ( version 3.00 )
     !/    13-Nov-2002 : Add stress vector.                  ( version 3.00 )
     !/    24-Dec-2004 : Multiple grid version.              ( version 3.06 )
     !/    21-Jul-2005 : Adding output fields 19-21.         ( version 3.07 )
     !/    28-Jun-2006 : Adding file name preamble.          ( version 3.09 )
     !/    05-Jul-2006 : Consolidate stress arrays.          ( version 3.09 )
     !/    28-Mar-2007 : Adding partitioned output.          ( version 3.11 )
     !/                  Adding user slots for outputs.
     !/    31-Jul-2007 : Fix file extension errors.          ( version 3.12 )
     !/    25-Dec-2012 : New structure of output fields.     ( version 4.11 )
     !/    25-Jun-2013 : Add type 4 sea point text output.   ( version 4.11 )
     !/    26-Jan-2021 : Added TP field (derived from FP0)   ( version 7.12 )
     !/    22-Mar-2021 : New coupling fields output          ( version 7.13 )
     !/
     !  1. Purpose :
     !
     !     Perform actual grid output.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !       NX/Y    Int.  I  Grid dimensions.
     !       NSEA    Int.  I  Number of sea points.
     !     ----------------------------------------------------------------
     !
     !     Internal parameters
     !     ----------------------------------------------------------------
     !       FLONE   Log.  Flags for one-dimensional field.
     !       FLTWO   Log.  Flags for two-dimensional field X Y.
     !       FLDIR   Log.  Flags for two-dimensional, directional field.
     !       FLTRI   Log.  Flags for three dimensional field.
     !       X1, X2, XX, XY
     !               R.A.  Output fields
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      EXTCDE    Subr.   Id.    Abort program as graceful as possible.
     !      W3S2XY    Subr.   Id.    Convert from storage to spatial grid.
     !      PRTBLK    Subr. W3ARRYMD Print plot of array.
     !      OUTA2I    Subr.   Id.    Print array of INTEGERS.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Main program in which it is contained.
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !     - Note that arrays CX and CY of the main program now contain
     !       the absolute current speed and direction respectively.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S  Enable subroutine tracing.
     !       !/T  Enable test output.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE w3servmd, ONLY : w3s2xy
 #ifdef W3_RTD
     USE w3servmd, ONLY : w3thrtn, w3xyrtn
 #endif
     USE w3arrymd, ONLY : outa2i, prtblk
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER                 :: NX, NY, NSEA
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: NXMAX, NXTOT, NBLOK, IH, IM, IS,     &
          MFILL, J, ISEA, IX, IY, IXB, IB,     &
          IXA, NINGRD, JJ, IFI, IFJ
     INTEGER                 :: MAP(NX+1,NY), MP2(NX+1,NY),          &
          MX1(NX,NY), MXX(NX,NY), MYY(NX,NY),  &
          MXY(NX,NY)
     INTEGER, SAVE           :: IPASS
     !     INTEGER, SAVE           :: NCOL   = 80
     INTEGER, SAVE           :: NCOL   = 132
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   =   0
 #endif
     REAL                    :: FSC, CABS, UABS, FSCA, XMIN, XMAX,   &
          XAVG, XSTD, YGBX, XGBX, AABS
     REAL                    :: X1(NX+1,NY), X2(NX+1,NY),            &
          XX(NX+1,NY), XY(NX+1,NY), DPTMAX(1)
     !!Li  Type 4 sea point only text output variables.  JGLi25Jun2013
     REAL, Dimension(NSEA)   :: XS1, XS2, XS3, XS4, AUX
     !!Li
     DOUBLE PRECISION        :: XDS, XDSQ
     LOGICAL                 :: FLONE, FLTWO, FLDIR, FLTRI
 #ifdef W3_T
     LOGICAL                 :: LTEMP(NGRPP)
 #endif
     CHARACTER               :: OLDTID*8, FNAME*32, ENAME*7,         &
          FORMG*12, FORMF*11, UNITS*10, FSCS*7
     CHARACTER, SAVE         :: TIMEID*8 = '00000000'
     CHARACTER, SAVE         :: FILEID*13 = 'WAVEWATCH III'
 #ifdef W3_BT4
     REAL, PARAMETER            :: LOG2=log(2.)
 #endif
     !/
     !/ ------------------------------------------------------------------- /
     !/
 #ifdef W3_S
     CALL strace (ient, 'W3EXGO')
 #endif
     !
 #ifdef W3_T
     DO ifi=1, nogrp
       ltemp  = flreq(ifi,:)
       WRITE (ndst,9000) ifi, ltemp
     END DO
     WRITE (ndst,9001) itype, ix1, ixn, ixs, iy1, iyn, iys,          &
          scale, vector, ndsdat
 #endif
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     ! 1.  Preparations
     !
     x1     = undef
     x2     = undef
     xx     = undef
     xy     = undef
     !!Li  Type 4 sea point only variables
     xs1    = undef
     xs2    = undef
     xs3    = undef
     xs4    = undef
     !
     !     Number of print-plots
     !
     IF ( itype .EQ. 1 ) THEN
       IF ( scale ) THEN
         nxmax  = ( ncol - 10 ) / 2
       ELSE
         nxmax  = ( ncol - 10 ) / 5
       END IF
       nxtot  = 1 + (ixn-ix1)/ixs
       nblok  = 1 + (nxtot-1)/nxmax
 #ifdef W3_T
       WRITE (ndst,9012) nxmax, nxtot, nblok
 #endif
     END IF
     !
     !     Output file unit number
     !
     IF ( itype .EQ. 2 ) THEN
       ndsdt = ndsdat - 1
       ih    = time(2) / 10000
       im    = mod( time(2) , 10000 ) / 100
       is    = mod( time(2) , 100 )
     END IF
     !
     !     Set-up transfer files
     !
     !!Li  Type 4 share filename with type 3   JGLi25Jun2013
     !!    IF ( ITYPE .EQ. 3 ) THEN
     IF ( itype .EQ. 3 .OR. itype .EQ. 4 ) THEN
       mfill  = -999
       oldtid = timeid
       WRITE (timeid,'(I6.6,I2.2)') mod( time(1) , 1000000 ),      &
            time(2)/10000
       fname(05:12) = timeid
       fname(13:13) = '.'
       IF ( timeid .NE. oldtid ) THEN
         fname(1:4) = 'ww3.'
         ipass    = 1
       ELSE
         WRITE (ename,'(A1,I2.2,A1)') 'e', ipass, '.'
         fname(1:4) = ename
         ipass   = ipass + 1
       END IF
 #ifdef W3_T
       WRITE (ndst,9014) fname(1:13)
 #endif
       formg  = '((10G12.2))'
     END IF
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     ! 2.  Loop over output fields.
     !
     DO ifi=1, nogrp
       DO ifj=1, ngrpp
         IF ( flreq(ifi,ifj) ) THEN
           !
           formf  = '(1X,32I4)'
 #ifdef W3_T
           WRITE (ndst,9020) idout(ifi,ifj)
 #endif
           !
           ! 2.a Set output arrays and parameters
           flone = .false.
           fltwo = .false.
           fldir = .false.
           fltri = .false.
           !
           IF ( ifi .EQ. 1 .AND. ifj .EQ. 1 ) THEN
             flone  = .true.
             dptmax = maxval( dw(1:nsea) )
             fsc    = 1.
             IF ( dptmax(1) .GT. 999. ) THEN
               fsc    = 0.1
             ELSE IF ( dptmax(1) .GT. 99.9 ) THEN
               fsc    = 0.1
             ELSE IF ( dptmax(1) .GT. 9.99 ) THEN
               fsc    = 0.01
             END IF
             IF ( itype .EQ. 3 ) fsc = 0.01
             units  = 'm'
             ename  = '.dpt'
             formf  = '(1X,17I7)'
             IF ( itype .EQ. 4 ) THEN
               xs1    = dw(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, dw(1:nsea)        &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 2 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.01
             ename  = '.cur'
             units  = 'm s-1'
             formf  = '(1X,17I7)'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, cx, cy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = cx(1:nsea)
               xs2    = cy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cx(1:nsea)        &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cy(1:nsea)        &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               cabs   = sqrt(cx(isea)**2+cy(isea)**2)
               IF ( cabs .GT. 0.05 ) THEN
                 cy(isea) = mod( 630. -                         &
                      rade*atan2(cy(isea),cx(isea)) , 360. )
               ELSE
                 cy(isea) = undef
               END IF
               cx(isea) = cabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = cx(1:nsea)
               xs4    = cy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cx(1:nsea)        &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cy(1:nsea)        &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 3 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.1
             ename  = '.wnd'
             units  = 'm s-1'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, ua, ud, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = ua(1:nsea)
               xs2    = ud(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ua(1:nsea)        &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ud(1:nsea)        &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               uabs   = sqrt(ua(isea)**2+ud(isea)**2)
               IF ( uabs .GT. 1.0 ) THEN
                 ud(isea) = mod( 630. -                         &
                      rade*atan2(ud(isea),ua(isea)) , 360. )
               ELSE
                 ud(isea) = undef
               END IF
               ua(isea) = uabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = ua(1:nsea)
               xs4    = ud(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ua(1:nsea)        &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ud(1:nsea)        &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.1
             ename  = '.ast'
             units  = 'K'
             IF ( itype .EQ. 4 ) THEN
               xs1    = as(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, as(1:nsea)        &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 5 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 'm'
             ename  = '.wlv'
             IF ( itype .EQ. 4 ) THEN
               xs1    = wlv
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, wlv   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 6 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.ice'
             IF ( itype .EQ. 4 ) THEN
               xs1    = ice
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ice   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 7 ) THEN
             flone  = .true.
             fsc    = 0.0002
             units  = 'km-1'
             ename  = '.ibg'
             WHERE ( berg.NE.undef) berg = berg*0.1
             IF ( itype .EQ. 4 ) THEN
               xs1    = berg
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, berg  , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 8 ) THEN
             !! Note - TAUA and TAUADIR read in from .ww3 file are TAUAX,TAUAY
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.01
             units  = 'Pa'
             ename  = '.taua'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) THEN
               CALL w3xyrtn(nsea, taua(1:nsea), tauadir(1:nsea), angld)
             ENDIF
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1 = taua(1:nsea)
               xs2 = tauadir(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, taua(1:nsea), mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauadir(1:nsea), mapsf, xy )
             ENDIF
             DO isea=1, nsea
               uabs   = sqrt(taua(isea)**2+tauadir(isea)**2)
               IF ( uabs .GT. 0.01 ) THEN
                 tauadir(isea) = mod( 630. -                     &
                      rade*atan2(taua(isea),tauadir(isea)), 360.)
               ELSE
                 tauadir(isea) = undef
               END IF
               ua(isea) = uabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = taua(1:nsea)
               xs4    = tauadir(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, taua(1:nsea), mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauadir(1:nsea), mapsf, x2)
             ENDIF
             !
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 9 ) THEN
             flone  = .true.
             fsc    = 0.0001
             units  = 'kg m-3'
             ename  = '.rhoa'
             IF ( itype .EQ. 4 ) THEN
               xs1    = rhoair
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, rhoair, mapsf, x1 )
             ENDIF
             !
 #ifdef W3_BT4
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 10 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 'Krumbein phi scale'
             ename  = '.d50'
             WHERE ( sed_d50.NE.undef) sed_d50 = -log(sed_d50/0.001)/log2
             IF ( itype .EQ. 4 ) THEN
               xs1    = sed_d50
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, sed_d50  , mapsf, x1 )
             ENDIF
 #endif
             !
 #ifdef W3_IS2
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 11 ) THEN
             flone = .true.
             fsc = 0.001
             units = 'm'
             ename = '.ic1'
             IF ( itype .EQ. 4) THEN
               xs1    = iceh
             ELSE
               CALL w3s2xy (nsea, nsea, nx+1, ny, iceh, mapsf, x1 )
             ENDIF
 #endif
             !
 #ifdef W3_IS2
           ELSE IF ( ifi .EQ. 1 .AND. ifj .EQ. 12) THEN
             flone = .true.
             fsc = 0.001
             units = 'm'
             ename = '.ic5'
             IF ( itype .EQ. 4) THEN
               xs1    = icef
             ELSE
               CALL w3s2xy (nsea, nsea, nx+1, ny, icef, mapsf, x1 )
             ENDIF
 #endif
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 1 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 'm'
             ename  = '.hs'
             IF ( itype .EQ. 4 ) THEN
               xs1    = hs
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, hs    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 2 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = 'm'
             ename  = '.lm'
             IF ( itype .EQ. 4 ) THEN
               xs1    = wlm
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, wlm   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 3 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.t02'
             IF ( itype .EQ. 4 ) THEN
               xs1    = t02
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, t02   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.t0m1'
             IF ( itype .EQ. 4 ) THEN
               xs1    = t0m1
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, t0m1  , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 5 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.t01'
             IF ( itype .EQ. 4 ) THEN
               xs1    = t01
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, t01   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 6 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = 's-1'
             ename  = '.fp'
             IF ( itype .EQ. 4 ) THEN
               xs1    = fp0
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, fp0   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 7 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = 'degree'
             ename  = '.dir'
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, thm, angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( thm(isea) .NE. undef )                         &
                    thm(isea) = mod( 630. - rade*thm(isea) , 360. )
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = thm
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, thm   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 8 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'degree'
             ename  = '.spr'
             IF ( itype .EQ. 4 ) THEN
               xs1    = ths
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ths   , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 9 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = 'degree'
             ename  = '.dp'
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, thp0, angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( thp0(isea) .NE. undef ) THEN
                 thp0(isea) = mod( 630-rade*thp0(isea) , 360. )
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = thp0
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, thp0  , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 10 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = 'm'
             ename  = '.hig'
             IF ( itype .EQ. 4 ) THEN
               xs1    = hsig
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, hsig  , mapsf, x1 )
             END IF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 11 ) THEN
             flone  = .true.
             fsc    = 0.002
             units  = 'm'
             ename  = '.emc'
             IF ( itype .EQ. 4 ) THEN
               xs1    = stmaxe
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, stmaxe, mapsf, x1 )
             END IF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 12 ) THEN
             flone  = .true.
             fsc    = 0.002
             units  = 'm'
             ename  = '.smc'
             IF ( itype .EQ. 4 ) THEN
               xs1    = stmaxd
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, stmaxd, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 13 ) THEN
             flone  = .true.
             fsc    = 0.002
             units  = 'm'
             ename  = '.emh'
             IF ( itype .EQ. 4 ) THEN
               xs1    = hmaxe
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, hmaxe, mapsf, x1 )
             END IF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 14 ) THEN
             flone  = .true.
             fsc    = 0.002
             units  = 'm'
             ename  = '.eml'
             IF ( itype .EQ. 4 ) THEN
               xs1    = hcmaxe
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, hcmaxe, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 15 ) THEN
             flone  = .true.
             fsc    = 0.002
             units  = 'm'
             ename  = '.smh'
             IF ( itype .EQ. 4 ) THEN
               xs1    = hmaxd
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, hmaxd, mapsf, x1 )
             END IF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 16 ) THEN
             flone  = .true.
             fsc    = 0.002
             units  = 'm'
             ename  = '.sml'
             IF ( itype .EQ. 4 ) THEN
               xs1    = hcmaxd
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, hcmaxd, mapsf, x1)
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 17 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.wbt'
             IF ( itype .EQ. 4 ) THEN
               xs1    = wbt
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, wbt, mapsf, x1)
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 18 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.tp'
             DO i=1,nsea
               IF(fp0(i) .NE. undef) THEN
                 aux(i) = 1.0 / fp0(i)
               ELSE
                 aux(i) = undef
               ENDIF
             ENDDO
             IF ( itype .EQ. 4 ) THEN
               xs1    = aux
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, aux, mapsf, x1)
             ENDIF
             !
           ELSE IF ( ifi .EQ. 2 .AND. ifj .EQ. 19 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = 'm-1'
             ename  = '.wnm'
             IF ( itype .EQ. 4 ) THEN
               xs1    = wnmean
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, wnmean, mapsf, x1)
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 1 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 'm'
             ename  = '.phs'
             IF ( itype .EQ. 4 ) THEN
               xs1    = phs(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, phs(:,ipart)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 2 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.ptp'
             IF ( itype .EQ. 4 ) THEN
               xs1    = ptp(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ptp(:,ipart)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 3 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = 'm'
             ename  = '.plp'
             IF ( itype .EQ. 4 ) THEN
               xs1    = plp(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, plp(:,ipart)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = 'degree'
             ename  = '.pdir'
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, pdir(:,ipart), angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( pdir(isea,ipart) .NE. undef ) THEN
                 pdir(isea,ipart) =                               &
                      mod( 630-rade*pdir(isea,ipart) , 360. )
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = pdir(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pdir(:,ipart)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 5 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'degree'
             ename  = '.pspr'
             IF ( itype .EQ. 4 ) THEN
               xs1    = psi(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, psi(:,ipart)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 6 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.pws'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pws(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pws(:,ipart)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 7 ) THEN
             flone  = .true.
             fsc    = 1.0
             units  = 'degree'
             ename  = '.pdp'
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, pthp0(:,ipart), angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( pthp0(isea,ipart) .NE. undef ) THEN
                 pthp0(isea,ipart) =                           &
                      mod( 630-rade*pthp0(isea,ipart) , 360. )
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = pthp0(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pthp0(:,ipart),   &
                    mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 8 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = '1'
             ename  = '.pqp'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pqp(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pqp(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 9 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = '1'
             ename  = '.ppe'
             IF ( itype .EQ. 4 ) THEN
               xs1    = ppe(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ppe(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 10 ) THEN
             flone  = .true.
             fsc    = 0.0001
             units  = 's-1'
             ename  = '.pgw'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pgw(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pgw(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 11 ) THEN
             flone  = .true.
             fsc    = 0.0001
             units  = '1'
             ename  = '.psw'
             IF ( itype .EQ. 4 ) THEN
               xs1    = psw(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, psw(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 12 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.ptm10'
             IF ( itype .EQ. 4 ) THEN
               xs1    = ptm1(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ptm1(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 13 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.pt01'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pt1(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pt1(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 14 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 's'
             ename  = '.pt02'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pt2(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pt2(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 15 ) THEN
             flone  = .true.
             fsc    = 0.02
             units  = 'm2 s rad-1'
             ename  = '.pep'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pep(:,ipart)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pep(:,ipart), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 16 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.tws'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pwst(:)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pwst(:), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 4 .AND. ifj .EQ. 17 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = '1'
             ename  = '.pnr'
             IF ( itype .EQ. 4 ) THEN
               xs1    = pnr(:)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, pnr(:), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 1 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.001
             ename  = '.ust'
             formf  = '(1X,20I6)'
             units  = 'm s-1'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, ust, ustdir, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = ust(1:nsea)
               xs2    = ustdir(1:nsea)
             ELSE
               CALL w3s2xy (nsea,nsea,nx+1,ny, ust(1:nsea)        &
                    , mapsf, xx )
               CALL w3s2xy (nsea,nsea,nx+1,ny, ustdir(1:nsea)        &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               uabs   = sqrt(ust(isea)**2+ustdir(isea)**2)
               IF ( ust(isea) .EQ. undef ) THEN
                 ustdir(isea) = undef
                 uabs         = undef
               ELSE IF ( uabs .GT. 0.05 ) THEN
                 ustdir(isea) = mod( 630. -                     &
                      rade*atan2(ustdir(isea),ust(isea)) , 360. )
               ELSE
                 ustdir(isea) = undef
               END IF
               ust(isea) = uabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = ust(1:nsea)
               xs4    = ustdir(1:nsea)
             ELSE
               CALL w3s2xy (nsea,nsea,nx+1,ny, ust(1:nsea)        &
                    , mapsf, x1 )
               CALL w3s2xy (nsea,nsea,nx+1,ny, ustdir(1:nsea)        &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 2 ) THEN
             flone  = .true.
             fsc    = 1.e-6
             units  = '1'
             ename  = '.cha'
             IF ( itype .EQ. 4 ) THEN
               xs1    = charn(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, charn(1:nsea)    &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 3 ) THEN
             flone  = .true.
             fsc    = 0.1           !0.01
             units  = 'kW m-1'
             ename  = '.cge'
             DO isea=1, nsea
               IF ( cge(isea) .NE. undef )                       &
                    cge(isea) = 0.001 * cge(isea)
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = cge(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cge(1:nsea)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = 'W m-2'
             ename  = '.faw'
             DO isea=1, nsea
               phiaw(isea)=min(99.98,phiaw(isea))
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = phiaw(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, phiaw(1:nsea)    &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 5 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 1.e-6
             units  = 'm2 s-2'
             ename  = '.taw'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauwix, tauwiy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = tauwix(1:nsea)
               xs2    = tauwiy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwix(1:nsea)    &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwiy(1:nsea)    &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               cabs   = sqrt(tauwix(isea)**2+tauwiy(isea)**2)
               IF ( tauwix(isea) .EQ. undef ) THEN
                 tauwiy(isea) = undef
                 cabs         = undef
               ELSE IF ( tauwix(isea) .EQ. 0. .AND.              &
                    tauwiy(isea) .EQ. 0. ) THEN
                 tauwiy(isea) = undef
               ELSE
                 tauwiy(isea) = mod( 630. -                     &
                      rade*atan2(tauwiy(isea),tauwix(isea)) , 360. )
               END IF
               tauwix(isea) = cabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = tauwix(1:nsea)
               xs4    = tauwiy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwix(1:nsea)   &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwiy(1:nsea)   &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 6 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 1.e-6
             units  = 'm2 s-2'
             ename  = '.twa'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauwnx, tauwny, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = tauwnx(1:nsea)
               xs2    = tauwny(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwnx(1:nsea)    &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwny(1:nsea)    &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               cabs   = sqrt(tauwnx(isea)**2+tauwny(isea)**2)
               IF ( tauwnx(isea) .EQ. undef ) THEN
                 tauwny(isea) = undef
                 cabs         = undef
               ELSE IF ( tauwnx(isea) .EQ. 0. .AND.              &
                    tauwny(isea) .EQ. 0. ) THEN
                 tauwny(isea) = undef
               ELSE
                 tauwny(isea) = mod( 630. -                     &
                      rade*atan2(tauwny(isea),tauwnx(isea)) , 360. )
               END IF
               tauwnx(isea) = cabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = tauwnx(1:nsea)
               xs4    = tauwny(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwnx(1:nsea)   &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauwny(1:nsea)   &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 7 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.wcc'
             IF ( itype .EQ. 4 ) THEN
               xs1    = whitecap(1:nsea,1)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, whitecap(1:nsea,1) &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 8 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'm'
             ename  = '.wcf'
             IF ( itype .EQ. 4 ) THEN
               xs1    = whitecap(1:nsea,2)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, whitecap(1:nsea,2) &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 9 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'm'
             ename  = '.wch'
             IF ( itype .EQ. 4 ) THEN
               xs1    = whitecap(1:nsea,3)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, whitecap(1:nsea,3) &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 5 .AND. ifj .EQ. 10 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = '1'
             ename  = '.wcm'
             IF ( itype .EQ. 4 ) THEN
               xs1    = whitecap(1:nsea,4)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, whitecap(1:nsea,4) &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 1 ) THEN
             fltri  = .true.
             fsc    = 10.
             units  = 'N m-1'
             ename  = '.sxy'
 #ifdef W3_RTD
             ! Radition stress components are always left on rotated pole
             ! at present - need to confirm how to de-rotate (A. Saulter)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = sxx(1:nsea)
               xs2    = syy(1:nsea)
               xs3    = sxy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, sxx(1:nsea)       &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, syy(1:nsea)       &
                    , mapsf, x2 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, sxy(1:nsea)       &
                    , mapsf, xy )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 2 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 1.e-6
             units  = 'm2 s-2'
             ename  = '.two'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauox, tauoy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = tauox(1:nsea)
               xs2    = tauoy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauox(1:nsea)     &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauoy(1:nsea)     &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               uabs   = sqrt(tauox(isea)**2+tauoy(isea)**2)
               IF ( tauox(isea) .EQ. undef ) THEN
                 tauoy(isea) = undef
                 uabs        = undef
               ELSE IF ( uabs .GT. 1.e-8 ) THEN
                 tauoy(isea) = mod( 630. -                     &
                      rade*atan2(tauoy(isea),tauox(isea)) , 360. )
               ELSE
                 tauoy(isea) = undef
               END IF
               tauox(isea) = uabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = tauox(1:nsea)
               xs4    = tauoy(1:nsea)
             ELSE
               CALL w3s2xy (nsea,nsea,nx+1,ny, tauox(1:nsea)         &
                    , mapsf, x1 )
               CALL w3s2xy (nsea,nsea,nx+1,ny, tauoy(1:nsea)         &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ.3 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = 'N m-1'
             ename  = '.bhd'
             IF ( itype .EQ. 4 ) THEN
               xs1    = bhd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, bhd(1:nsea)    &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'W m-2'
             ename  = '.foc'
             DO isea=1, nsea
               phioc(isea)=min(99.98,phioc(isea))
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = phioc(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, phioc(1:nsea)    &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 5 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.001
             units  = 'm2 s-1'
             ename  = '.tus'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tusx, tusy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = tusx(1:nsea)
               xs2    = tusy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tusx(1:nsea)      &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tusy(1:nsea)      &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               cabs   = sqrt(tusx(isea)**2+tusy(isea)**2)
               IF ( tusx(isea) .NE. undef ) THEN
                 tusy(isea) = mod( 630. -                       &
                      rade*atan2(tusy(isea),tusx(isea)) , 360. )
               ELSE
                 tusy(isea) = undef
                 cabs       = undef
               END IF
               tusx(isea) = cabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = tusx(1:nsea)
               xs4    = tusy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny,tusx,mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny,tusy,mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 6 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.001
             units  = 'm s-1'
             ename  = '.uss'
             DO isea=1, nsea
               IF (ussx(isea) .NE. undef ) THEN
                 ussx(isea)=max(-0.9998,min(0.9998,ussx(isea)))
                 ussy(isea)=max(-0.9998,min(0.9998,ussy(isea)))
               END IF
             END DO
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, ussx, ussy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = ussx(1:nsea)
               xs2    = ussy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ussx(1:nsea)     &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ussy(1:nsea)     &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               cabs   = sqrt(ussx(isea)**2+ussy(isea)**2)
               IF ( ussx(isea)  .NE. undef ) THEN
                 ussy(isea) = mod( 630. -                      &
                      rade*atan2(ussy(isea),ussx(isea)) , 360. )
               ELSE
                 ussy(isea) = undef
                 cabs       = undef
               END IF
               ussx(isea) = cabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = ussx(1:nsea)
               xs4    = ussy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ussx(1:nsea),     &
                    mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ussy(1:nsea),     &
                    mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 7 ) THEN
             fltwo  = .true.
             fsc    = 0.01
             ename  = '.p2s'
             units  = 'm4'
             DO isea=1, nsea
               prms(isea)=prms(isea)
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = prms(1:nsea)
               xs2    = tpms(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1,ny,prms,mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1,ny,tpms,mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 6 .AND. ifj .EQ. 13 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 1.e-6
             units  = 'm2 s-2'
             ename  = '.toc'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, tauocx, tauocy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = tauocx(1:nsea)
               xs2    = tauocy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauocx(1:nsea)    &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, tauocy(1:nsea)    &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               uabs   = sqrt(tauocx(isea)**2+tauocy(isea)**2)
               IF ( tauocx(isea) .EQ. undef ) THEN
                 tauocy(isea) = undef
                 uabs         = undef
               ELSE IF ( uabs .GT. 1.e-8 ) THEN
                 tauocy(isea) = mod( 630. -                    &
                      rade*atan2(tauocy(isea),tauocx(isea)) , 360. )
               ELSE
                 tauocy(isea) = undef
               END IF
               tauocx(isea) = uabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = tauocx(1:nsea)
               xs4    = tauocy(1:nsea)
             ELSE
               CALL w3s2xy (nsea,nsea,nx+1,ny, tauocx(1:nsea)        &
                    , mapsf, x1 )
               CALL w3s2xy (nsea,nsea,nx+1,ny, tauocy(1:nsea)        &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 1 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.01
             ename  = '.abr'
             units  = 'm'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, aba, abd, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = aba(1:nsea)
               xs2    = abd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, aba(1:nsea)       &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, abd(1:nsea)       &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               IF ( aba(isea) .NE. undef ) THEN
                 aabs   = sqrt(aba(isea)**2+abd(isea)**2)
                 IF ( aabs .GT. 0.005 ) THEN
                   abd(isea) = mod( 630. -                    &
                        rade*atan2(abd(isea),aba(isea)) , 360. )
                 ELSE
                   abd(isea) = undef
                 END IF
                 aba(isea) = aabs
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = aba(1:nsea)
               xs4    = abd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, aba(1:nsea)       &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, abd(1:nsea)       &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 2 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.01
             ename  = '.ubr'
             units  = 'm s-1'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, uba, ubd, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = uba(1:nsea)
               xs2    = ubd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, uba(1:nsea)       &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ubd(1:nsea)       &
                    , mapsf, xy )
             ENDIF
             DO isea=1, nsea
               IF ( uba(isea) .NE. undef ) THEN
                 uabs   = sqrt(uba(isea)**2+ubd(isea)**2)
                 IF ( uabs .GT. 0.005 ) THEN
                   ubd(isea) = mod( 630. -                    &
                        rade*atan2(ubd(isea),uba(isea)) , 360. )
                 ELSE
                   ubd(isea) = undef
                 END IF
                 uba(isea) = uabs
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = uba(1:nsea)
               xs4    = ubd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, uba(1:nsea)       &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, ubd(1:nsea)       &
                    , mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 3 ) THEN
             fltri  = .true.
             fsc    = 1.e-2
             units  = 'm'
             ename  = '.bed'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, bedforms(1:nsea,2), &
                  bedforms(1:nsea,3), angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = bedforms(1:nsea,1)
               xs2    = bedforms(1:nsea,2)
               xs3    = bedforms(1:nsea,3)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, bedforms(1:nsea,1) &
                    , mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, bedforms(1:nsea,2) &
                    , mapsf, x2 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, bedforms(1:nsea,3) &
                    , mapsf, xy )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'W m-2'
             ename  = '.fbb'
             IF ( itype .EQ. 4 ) THEN
               xs1    = phibbl(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, phibbl(1:nsea)    &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 7 .AND. ifj .EQ. 5 ) THEN
             fltwo  = .true.
             fsc    = 1.e-6
             units  = 'm2 s-2'
             ename  = '.tbb'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, taubbl(1:nsea,1), &
                  taubbl(1:nsea,2), angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = taubbl(1:nsea,1)
               xs2    = taubbl(1:nsea,2)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, taubbl(1:nsea,1)  &
                    , mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, taubbl(1:nsea,2)  &
                    , mapsf, xy )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 1 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 1.e-6
             ename  = '.mss'
             formf  = '(1X,20I6)'
             units  = '1'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, mssx, mssy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = mssx(1:nsea)
               xs2    = mssy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mssx(1:nsea),     &
                    mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny ,mssy(1:nsea),     &
                    mapsf, xy )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 2 ) THEN
             IF ( vector ) THEN
               fltwo  = .true.
             ELSE
               fldir  = .true.
             END IF
             fsc    = 0.00001
             ename  = '.msc'
             units  = '1'
 #ifdef W3_RTD
             ! Rotate x,y vector back to standard pole
             IF ( flagunr ) CALL w3xyrtn(nsea, mscx, mscy, angld)
 #endif
             IF ( itype .EQ. 4 ) THEN
               xs1    = mscx(1:nsea)
               xs2    = mscy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mscx(1:nsea),     &
                    mapsf, xx )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mscy(1:nsea),     &
                    mapsf, xy )
             ENDIF
             DO isea=1, nsea
               cabs   = sqrt(mscx(isea)**2+mscy(isea)**2)
               IF ( mscx(isea)  .EQ. undef ) THEN
                 mscy(isea) = undef
                 cabs       = undef
               ELSE IF ( mscx(isea)  .EQ. 0. .AND.              &
                    mscy(isea)  .EQ. 0. ) THEN
                 mscy(isea) = undef
               ELSE
                 mscy(isea) = mod( 630. -                      &
                      rade*atan2(mscy(isea),mscx(isea)) , 360. )
               END IF
               mscx(isea) = cabs
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs3    = mscx(1:nsea)
               xs4    = mscy(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mscx(1:nsea),     &
                    mapsf, x1 )
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mscy(1:nsea),     &
                    mapsf, x2 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 3 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'degree'
             ename  = '.msd'
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, mssd, angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( mssd(isea) .NE. undef )  THEN
                 mssd(isea) = mod( 630. - rade*mssd(isea) , 180. )
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = mssd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mssd(1:nsea), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'degree'
             ename  = '.mcd'
 #ifdef W3_RTD
             ! Rotate direction back to standard pole
             IF ( flagunr ) CALL w3thrtn(nsea, mscd, angld, .false.)
 #endif
             DO isea=1, nsea
               IF ( mscd(isea) .NE. undef )  THEN
                 mscd(isea) = mod( 630. - rade*mscd(isea) , 180. )
               END IF
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = mscd(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, mscd(1:nsea), mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 5 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.qp'
             IF ( itype .EQ. 4 ) THEN
               xs1    = qp
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, qp, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 6 ) THEN
             flone  = .true.
             fsc    = 0.05
             units  = '1'
             ename  = '.qkk'
             IF ( itype .EQ. 4 ) THEN
               xs1    = qkk
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, qkk, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 7 ) THEN
             flone  = .true.
             fsc    = 0.01
             units  = '1'
             ename  = '.skw'
             IF ( itype .EQ. 4 ) THEN
               xs1    = skew
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, skew, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 8 ) THEN
             flone  = .true.
             fsc    = 0.0001
             units  = '1'
             ename  = '.emb'
             IF ( itype .EQ. 4 ) THEN
               xs1    = embia1
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, embia1, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 8 .AND. ifj .EQ. 9 ) THEN
             flone  = .true.
             fsc    = 0.0001
             units  = '1'
             ename  = '.emc'
             IF ( itype .EQ. 4 ) THEN
               xs1    = embia2
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, embia2, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 1 ) THEN
             flone  = .true.
             fsc    = 0.1
             units  = 'min.'
             ename  = '.dtd'
             DO isea=1, nsea
               IF ( dtdyn(isea) .NE. undef )                       &
                    dtdyn(isea) = dtdyn(isea) / 60.
             END DO
             IF ( itype .EQ. 4 ) THEN
               xs1    = dtdyn(1:nsea)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, dtdyn , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 2 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = 's-1'
             ename  = '.fc'
             IF ( itype .EQ. 4 ) THEN
               xs1    = fcut
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, fcut  , mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 3 ) THEN
             flone  = .true.
             fsc    = 0.001
             fsc    = 1.
             units  = '1'
             ename  = '.cfx'
             IF ( itype .EQ. 4 ) THEN
               xs1    = cflxymax
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cflxymax, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 4 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.cfd'
             IF ( itype .EQ. 4 ) THEN
               xs1    = cflthmax
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cflthmax, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 9 .AND. ifj .EQ. 5 ) THEN
             flone  = .true.
             fsc    = 0.001
             units  = '1'
             ename  = '.cfk'
             IF ( itype .EQ. 4 ) THEN
               xs1    = cflkmax
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, cflkmax, mapsf, x1 )
             ENDIF
             !
           ELSE IF ( ifi .EQ. 10 ) THEN
             flone  = .true.
             fsc    = 1.
             units  = 'TBD'
             WRITE (ename,'(A2,I2.2)') '.u', ifj
             IF ( itype .EQ. 4 ) THEN
               xs1    = usero(:,ifj)
             ELSE
               CALL w3s2xy ( nsea, nsea, nx+1, ny, usero(:,ifj)      &
                    , mapsf, x1 )
             ENDIF
             !
           ELSE
             WRITE (ndse,990) ifi,ifj
             WRITE (ndse,999)
             CALL extcde ( 1 )
             !
           END IF
           !
           ! 2.b Make map
           !
           DO ix=1, nx
             DO iy=1, ny
               IF ( mapsta(iy,ix) .EQ. 0 ) THEN
                 x1(ix,iy) = undef
                 x2(ix,iy) = undef
                 xx(ix,iy) = undef
                 xy(ix,iy) = undef
               END IF
               IF ( x1(ix,iy) .EQ. undef ) THEN
                 map(ix,iy) = 0
               ELSE
                 map(ix,iy) = 1
               END IF
               IF ( x2(ix,iy) .EQ. undef ) THEN
                 mp2(ix,iy) = 0
               ELSE
                 mp2(ix,iy) = 1
               END IF
             END DO
           END DO
           !
           ! 2.c Perform output type 1 ( print plots )
           !
           IF ( itype .EQ. 1 ) THEN
             !
             IF ( scale ) THEN
               fsc    = 0.
               fsca   = 0.
             ELSE
               fsca   = 1.
             END IF
             ixb    = ix1 - ixs
             !
             DO ib=1, nblok
               ixa    = ixb + ixs
               ixb    = ixa + (nxmax-1)*ixs
               ixb    = min( ixb , ixn )
               IF ( fltri ) THEN
                 CALL prtblk (ndso, nx, ny, nx+1, x1, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
                 CALL prtblk (ndso, nx, ny, nx+1, x2, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
                 CALL prtblk (ndso, nx, ny, nx+1, xy, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
               ELSE IF ( flone ) THEN
                 CALL prtblk (ndso, nx, ny, nx+1, x1, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
               ELSE IF ( fltwo ) THEN
                 CALL prtblk (ndso, nx, ny, nx+1, xx, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
                 CALL prtblk (ndso, nx, ny, nx+1, xy, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
               ELSE IF ( fldir ) THEN
                 CALL prtblk (ndso, nx, ny, nx+1, x1, map, 0,    &
                      fsc, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), units)
                 CALL prtblk (ndso, nx, ny, nx+1, x2, mp2, 0,    &
                      fsca, ixa, ixb, ixs, iy1, iyn, iys, &
                      idout(ifi,ifj), 'Deg.')
               END IF
             END DO
             !
             ! 2.d Perform output type 2 ( statistics )
             !
           ELSE IF ( itype .EQ. 2 ) THEN
             xmin   =  1.e20
             xmax   = -1.e20
             xds    =  0.d0
             xdsq   =  0.d0
             ningrd =  0
             !
             DO ix=ix1, ixn
               DO iy=iy1, iyn
                 IF ( x1(ix,iy) .NE. undef ) THEN
                   ningrd = ningrd + 1
                   xmin   = min( xmin , x1(ix,iy) )
                   xmax   = max( xmax , x1(ix,iy) )
                   xds    = xds  + dble(x1(ix,iy))
                   xdsq   = xdsq + dble(x1(ix,iy))**2
                 END IF
               END DO
             END DO
             !
             ndsdt  = ndsdt + 1
             !
             IF ( ningrd .EQ. 0 ) THEN
               WRITE (ndsdt,940) time(1), ih, im, is
             ELSE IF ( ningrd .LE. 2 ) THEN
               xavg   = real( xds / dble(ningrd) )
               WRITE (ndsdt,940) time(1), ih, im, is,            &
                    xmin, xmax
             ELSE
               xavg   = real( xds / dble(ningrd) )
               xstd   = real( ( xdsq - xds**2/dble(ningrd) )    &
                    / dble(ningrd-1) )
               xstd   = sqrt( max( xstd , 0. ) )
               WRITE (ndsdt,940) time(1), ih, im, is,            &
                    xmin, xmax, xavg, xstd
             END IF
             !
             ! 2.e Perform output type 3 ( file )
             !
           ELSE IF ( itype .EQ. 3 ) THEN
             !
             fname(13:) = ename
             IF ( idfm .EQ. 3 ) THEN
               IF(gtype .NE. ungtype) THEN
                 jj     = len_trim(fnmpre)
                 OPEN (ndsdat,file=fnmpre(:jj)//fname,             &
                      form='UNFORMATTED', convert=file_endian,err=800,iostat=ierr)
                 WRITE (ndsdat) fileid, time,                      &
                      minval(xgrd(iy1:iyn,ix1:ixn)),                 &
                      maxval(xgrd(iy1:iyn,ix1:ixn)), ixn-ix1+1,      &
                      minval(ygrd(iy1:iyn,ix1:ixn)),                 &
                      maxval(ygrd(iy1:iyn,ix1:ixn)), iyn-iy1+1,      &
                      ename, fsc, units, idla, idfm, formf, mfill
               ELSE
                 OPEN (ndsdat,file=fname,             &
                      form='UNFORMATTED', convert=file_endian,err=800,iostat=ierr)
                 WRITE (ndsdat) fileid, time,                      &
                      x0,maxx,nx, &
                      y0,maxy,ny, &
                      ename, fsc, units, idla, idfm, formf, mfill
               ENDIF
             ELSE
               IF(gtype .NE. ungtype) THEN
                 jj     = len_trim(fnmpre)
                 OPEN (ndsdat,file=fnmpre(:jj)//fname,err=800,     &
                      iostat=ierr)
                 IF (fsc.LT.1e-4) THEN
                   WRITE(fscs,'(G8.1)') fsc
                 ELSE
                   WRITE(fscs,'(F7.4)') fsc
                 END IF
                 IF ( flagll ) THEN
                   WRITE (ndsdat,950) fileid, time,               &
                        minval(xgrd(iy1:iyn,ix1:ixn)),                 &
                        maxval(xgrd(iy1:iyn,ix1:ixn)), ixn-ix1+1,      &
                        minval(ygrd(iy1:iyn,ix1:ixn)),                 &
                        maxval(ygrd(iy1:iyn,ix1:ixn)), iyn-iy1+1,      &
                        ename, fscs, units, idla, idfm, formf, mfill
                 ELSE
                   WRITE (ndsdat,960) fileid, time,               &
                        minval(xgrd(iy1:iyn,ix1:ixn)),                 &
                        maxval(xgrd(iy1:iyn,ix1:ixn)), ixn-ix1+1,      &
                        minval(ygrd(iy1:iyn,ix1:ixn)),                 &
                        maxval(ygrd(iy1:iyn,ix1:ixn)), iyn-iy1+1,      &
                        ename, fscs, units, idla, idfm, formf, mfill
                 END IF
               ELSE
                 OPEN (ndsdat,file=fname,                      &
                      err=800,iostat=ierr)
                 WRITE (ndsdat, 949) fileid, time,              &
                      x0,maxx,nx, &
                      y0,maxy,ny, &
                      ename, fsc, units, idla, idfm, formf, mfill
               ENDIF
             END IF
             !
             IF ( fltri ) THEN
               DO ix=ix1, ixn
                 DO iy=iy1, iyn
                   IF ( xx(ix,iy) .EQ. undef ) THEN
                     mxx(ix,iy) = mfill
                     myy(ix,iy) = mfill
                     mxy(ix,iy) = mfill
                   ELSE
                     mxx(ix,iy) = nint(x1(ix,iy)/fsc)
                     myy(ix,iy) = nint(x2(ix,iy)/fsc)
                     mxy(ix,iy) = nint(xy(ix,iy)/fsc)
                   END IF
                 END DO
               END DO
               IF ( idla .NE. 5 ) THEN
                 CALL outa2i ( mxx, nx, ny, ix1, ixn, iy1, iyn, &
                      ndsdat, ndst, ndse, idfm, formf, idla, 1, 0 )
                 CALL outa2i ( myy, nx, ny, ix1, ixn, iy1, iyn, &
                      ndsdat, ndst, ndse, idfm, formf, idla, 1, 0 )
                 CALL outa2i ( mxy, nx, ny, ix1, ixn, iy1, iyn, &
                      ndsdat, ndst, ndse, idfm, formf, idla, 1, 0 )
               ELSE
                 DO iy=iy1,iyn
                   ygbx   = y0 + real(iy-1)*sy
                   DO ix=ix1, ixn
                     xgbx   = x0 + real(ix-1)*sx
                     IF ( mxx(ix,iy) .NE. mfill ) THEN
                       IF ( idfm .EQ. 3 ) THEN
                         WRITE (ndsdat)                    &
                              xgbx, ygbx, mxx(ix,iy), myy(ix,iy)
                       ELSE
                         WRITE (ndsdat,951)                &
                              xgbx, ygbx, mxx(ix,iy), myy(ix,iy)
                       END IF
                     END IF
                   END DO
                 END DO
               END IF
             ELSE
               IF ( fltwo .OR. fldir ) THEN
                 DO ix=ix1, ixn
                   DO iy=iy1, iyn
                     IF ( xx(ix,iy) .EQ. undef ) THEN
                       mxx(ix,iy) = mfill
                       myy(ix,iy) = mfill
                     ELSE
                       mxx(ix,iy) = nint(xx(ix,iy)/fsc)
                       myy(ix,iy) = nint(xy(ix,iy)/fsc)
                     END IF
                   END DO
                 END DO
                 IF ( idla .NE. 5 ) THEN
                   CALL outa2i ( mxx, nx, ny, ix1, ixn, iy1, iyn, &
                        ndsdat, ndst, ndse, idfm, formf, idla, 1,0)
                   CALL outa2i ( myy, nx, ny, ix1, ixn, iy1, iyn, &
                        ndsdat, ndst, ndse, idfm, formf, idla, 1,0)
                 ELSE
                   DO iy=iy1,iyn
                     DO ix=ix1, ixn
                       ygbx   = ygrd(iy,ix)
                       xgbx   = xgrd(iy,ix)
                       IF ( mxx(ix,iy) .NE. mfill ) THEN
                         IF ( idfm .EQ. 3 ) THEN
                           WRITE (ndsdat)                    &
                                xgbx, ygbx, mxx(ix,iy), myy(ix,iy)
                         ELSE
                           IF ( flagll ) THEN
                             WRITE (ndsdat,951) xgbx, ygbx, &
                                  mxx(ix,iy), myy(ix,iy)
                           ELSE
                             WRITE (ndsdat,961) xgbx, ygbx, &
                                  mxx(ix,iy), myy(ix,iy)
                           END IF
                         END IF
                       END IF
                     END DO
                   END DO
                 END IF
               ELSE
                 DO ix=ix1, ixn
                   DO iy=iy1, iyn
                     IF ( x1(ix,iy) .EQ. undef ) THEN
                       mx1(ix,iy) = mfill
                     ELSE
                       mx1(ix,iy) = nint(x1(ix,iy)/fsc)
                     END IF
                   END DO
                 END DO
                 IF ( idla .NE. 5 ) THEN
                   CALL outa2i ( mx1, nx, ny, ix1, ixn, iy1, iyn, &
                        ndsdat, ndst, ndse, idfm, formf, idla, 1,0)
                 ELSE
                   DO iy=iy1,iyn
                     DO ix=ix1, ixn
                       ygbx   = ygrd(iy,ix)
                       xgbx   = xgrd(iy,ix)
                       IF ( mx1(ix,iy) .NE. mfill ) THEN
                         IF ( idfm .EQ. 3 ) THEN
                           WRITE (ndsdat)                    &
                                xgbx, ygbx, mx1(ix,iy)
                         ELSE
                           IF ( flagll ) THEN
                             WRITE (ndsdat,951) xgbx, ygbx, &
                                  mx1(ix,iy)
                           ELSE
                             WRITE (ndsdat,961) xgbx, ygbx, &
                                  mx1(ix,iy)
                           END IF
                         END IF
                       END IF
                     END DO
                   END DO
                 END IF
               END IF
             END IF
             !
             CLOSE (ndsdat)
             !
           ELSE IF ( itype .EQ. 4 ) THEN
             !
             fname(13:) = ename
             jj     = len_trim(fnmpre)
             OPEN (ndsdat,file=fnmpre(:jj)//fname,err=800,     &
                  iostat=ierr)
             WRITE (6,*)  fname(1:16)
             !
             IF ( fltri ) THEN
               WRITE (ndsdat,980)  fileid, time, nsea, 3,       &
                    fsc, ename, units, gname
               WRITE(ndsdat, 113)  xs1
               WRITE(ndsdat, 113)  xs2
               WRITE(ndsdat, 113)  xs3
             ENDIF
             IF ( fltwo .OR. fldir ) THEN
               WRITE (ndsdat,980)  fileid, time, nsea, 2,       &
                    fsc, ename, units, gname
               WRITE(ndsdat, 113)  xs1
               WRITE(ndsdat, 113)  xs2
             ENDIF
             IF ( flone ) THEN
               WRITE (ndsdat,980)  fileid, time, nsea, 1,       &
                    fsc, ename, units, gname
               WRITE(ndsdat, 113)  xs1
             ENDIF
             !
             CLOSE (ndsdat)
             !
           END IF
           !
           ! ... End of fields loop
           !
         END IF
       END DO
     END DO
     !
     RETURN
     !
     ! Error escape locations
     !
 800 CONTINUE
     WRITE (ndse,1000) ierr
     CALL extcde (2)
     !
     ! Formats
     !
 113 FORMAT ((10es11.3))
 980 FORMAT (1x,a13,i9.8,i7.6,i9,i3,es10.2,1x,a4,1x,a10,1x,a30)
 940 FORMAT (1x,i8,3i3.2,2x,4e12.4)
 949 FORMAT (1x,a13,i9.8,i7.6,2(2f8.2,i8),                      &
          1x,a4,f8.4,1x,a10,2i2,1x,a11,i4)
 950 FORMAT (1x,a13,1x,i9.8,1x,i7.6,2(1x,2f8.2,1x,i4),          &
          1x,a4,1x,a7,1x,a10,1x,2i2,1x,a11,1x,i4)
 951 FORMAT (1x,2f10.5,2i8)
 960 FORMAT (1x,a13,i9.8,i7.6,2(2e11.3,i4),                     &
          1x,a4,1x,a7,1x,a10,2i2,1x,a11,i4)
 961 FORMAT (1x,2e12.4,2i8)
     !
 990 FORMAT (/' *** WAVEWATCH III ERROR IN W3EXGO :'/           &
          '     GROUP',i2,' PARAMETER',i3,' NOT LISTED '    )
 999 FORMAT (/' *** WAVEWATCH III ERROR IN W3EXGO :'/                &
          '     PLEASE UPDATE FIELDS !!! '/)
     !
 1000 FORMAT (/' *** WAVEWATCH III ERROR IN W3EXGO : '/               &
          '     ERROR IN OPENING OUTPUT FILE'/                   &
          '     IOSTAT =',i5/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3EXGO : FLAGS :',i3,2x,20l2)
 9001 FORMAT (' TEST W3EXGO : ITPYE :',i4/                         &
          '             IX1/N/S :',3i4/                        &
          '             IY1/N/S :',3i4/                        &
          '       SCALE, VECTOR :',2l2/                        &
          '              NDSDAT :',i4)
 #endif
     !
 #ifdef W3_T
 9012 FORMAT (' TEST W3EXGO : BLOK PARS    : ',3i4)
 9014 FORMAT ('           BASE NAME : ',a)
 #endif
     !
 #ifdef W3_T
 9020 FORMAT (' TEST W3EXGO : OUTPUT FIELD : ',a)
 #endif
     !/
     !/ End of W3EXGO ----------------------------------------------------- /
     !/
References file(), constants::file_endian, w3arrymd::outa2i(), w3arrymd::prtblk(), constants::rade, constants::undef, w3servmd::w3s2xy(), w3servmd::w3thrtn(), and w3servmd::w3xyrtn().
Referenced by w3outf().
w3outf()
program w3outf
Post-processing of grid output.
Data is read from the grid output file out_grd.ww3 (raw data) and from the file ww3_outf.inp (NDSI, output requests). Model definition and raw data files are read using WAVEWATCH III subroutines.
     Output types :
      1 : print plots
      2 : field statistics
      3 : transfer file
      4 : text output at sea points (1:NSEA).
Author
H. L. Tolman
Date
22-Mar-2021
Copyright
Copyright 2009-2022 National Weather Service (NWS), National Oceanic and Atmospheric Administration. All rights reserved. WAVEWATCH III is a trademark of the NWS. No unauthorized use without permission.
Definition at line 35 of file ww3_outf.F90.
References w3adatmd::aba, w3adatmd::abd, w3adatmd::as, w3adatmd::bedforms, w3wdatmd::berg, w3adatmd::bhd, w3adatmd::cflkmax, w3adatmd::cflthmax, w3adatmd::cflxymax, w3adatmd::cge, w3adatmd::charn, w3adatmd::cx, w3adatmd::cy, w3adatmd::dtdyn, w3adatmd::dw, w3adatmd::embia1, w3adatmd::embia2, w3servmd::extcde(), w3adatmd::fcut, file(), w3odatmd::flogrd, w3odatmd::fnmpre, w3adatmd::fp0, w3adatmd::hcmaxd, w3adatmd::hcmaxe, w3adatmd::hmaxd, w3adatmd::hmaxe, w3adatmd::hs, w3adatmd::hsig, w3wdatmd::ice, w3wdatmd::icef, w3wdatmd::iceh, w3odatmd::idout, w3servmd::itrace(), w3adatmd::mscd, w3adatmd::mscx, w3adatmd::mscy, w3adatmd::mssd, w3adatmd::mssx, w3adatmd::mssy, w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3odatmd::ngrpp, w3odatmd::noge, w3odatmd::nogrp, w3odatmd::noswll, w3adatmd::pdir, w3adatmd::pep, w3adatmd::pgw, w3adatmd::phiaw, w3adatmd::phibbl, w3adatmd::phioc, w3adatmd::phs, w3adatmd::plp, w3adatmd::pnr, w3adatmd::ppe, w3adatmd::pqp, w3adatmd::prms, w3adatmd::psi, w3adatmd::psw, w3adatmd::pt1, w3adatmd::pt2, w3adatmd::pthp0, w3adatmd::ptm1, w3adatmd::ptp, w3adatmd::pws, w3adatmd::pwst, w3adatmd::qkk, w3adatmd::qp, w3wdatmd::rhoair, w3adatmd::skew, w3adatmd::stmaxd, w3adatmd::stmaxe, w3servmd::strace(), w3adatmd::sxx, w3adatmd::sxy, w3adatmd::syy, w3adatmd::t01, w3adatmd::t02, w3adatmd::t0m1, w3adatmd::taua, w3adatmd::tauadir, w3adatmd::taubbl, w3adatmd::tauocx, w3adatmd::tauocy, w3adatmd::tauox, w3adatmd::tauoy, w3adatmd::tauwix, w3adatmd::tauwiy, w3adatmd::tauwnx, w3adatmd::tauwny, w3adatmd::thm, w3adatmd::thp0, w3adatmd::ths, w3wdatmd::time, w3adatmd::tpms, w3adatmd::tusx, w3adatmd::tusy, w3adatmd::ua, w3adatmd::uba, w3adatmd::ubd, w3adatmd::ud, constants::undef, w3adatmd::usero, w3adatmd::ussx, w3adatmd::ussy, w3wdatmd::ust, w3wdatmd::ustdir, w3exgo(), w3iogomd::w3iogo(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3iogomd::w3readflgrd(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3adatmd::wbt, w3adatmd::whitecap, w3adatmd::wlm, w3wdatmd::wlv, and w3adatmd::wnmean.