WAVEWATCH III: ww3_trnc.F90 File Reference
ww3_trnc.F90 File Reference
Contains program W3TRNC.
Functions/Subroutines
program w3trnc
Convert direct access track output file to netCDF file.
subroutine w3exnc (FILEPREFIX, NCTYPE, NCID, S3, STRSTOPDATE, MK, MTH)
Perform actual track output in NetCDF file.
subroutine w3crnc (NCTYPE, NCFILE, NCID, DIMID, DIMLN, VARID)
Desc not available.
subroutine check_err (IRET)
Desc not available.
Detailed Description
Contains program W3TRNC.
Author
M. Accensi
Date
15-May-2018
Definition in file ww3_trnc.F90.
Function/Subroutine Documentation
check_err()
subroutine w3trnc::check_err (integer IRET)
Desc not available.
Parameters
IRET
Author
NA
Date
NA
Definition at line 1122 of file ww3_trnc.F90.
     USE netcdf
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
     IMPLICIT NONE
     INTEGER IRET
     IF (iret .NE. nf90_noerr) THEN
       WRITE(ndse,*) ' *** WAVEWATCH III ERROR IN TRNC :'
       WRITE(ndse,*) ' NETCDF ERROR MESSAGE: '
       WRITE(ndse,*) nf90_strerror(iret)
       CALL extcde ( 59 )
     END IF
     RETURN
References w3servmd::extcde(), and w3odatmd::ndse.
w3crnc()
subroutine w3trnc::w3crnc (integer, intent(in) NCTYPE, character*(*), intent(in) NCFILE, integer, intent(out) NCID, integer, dimension(:), intent(out) DIMID, integer, dimension(:), intent(in) DIMLN, integer, dimension(:), intent(out) VARID)
Desc not available.
Parameters
[in] NCTYPE
[in] NCFILE
[out] NCID
[out] DIMID
[in] DIMLN
[out] VARID
Author
NA
Date
NA
Definition at line 811 of file ww3_trnc.F90.
     USE netcdf
     IMPLICIT NONE
     INTEGER, INTENT(IN)               :: NCTYPE
     CHARACTER*(*), INTENT(IN)         :: NCFILE
     INTEGER, INTENT(IN)               :: DIMLN(:)
     INTEGER, INTENT(OUT)              :: DIMID(:), VARID(:), NCID
     INTEGER                           :: IRET
     INTEGER                           :: DEFLATE=1
     !
     ! Creation in netCDF3 or netCDF4
     !
     IF(nctype.EQ.3)  iret = nf90_create(trim(ncfile), nf90_clobber, ncid)
     IF(nctype.EQ.4) iret = nf90_create(trim(ncfile), nf90_netcdf4, ncid)
     CALL check_err(iret)
     !
     !     Define generals dimensions
     !
     iret = nf90_def_dim(ncid, 'time', dimln(1), dimid(1))
     CALL check_err(iret)
     iret = nf90_def_dim(ncid, 'frequency', dimln(2), dimid(2))
     CALL check_err(iret)
     iret = nf90_def_dim(ncid, 'direction', dimln(3), dimid(3))
     CALL check_err(iret)
     iret = nf90_def_dim(ncid, 'string32', dimln(4), dimid(4))
     CALL check_err(iret)
     !
     !     define generals variables
     !
     !  time
     iret=nf90_def_var(ncid, 'time', nf90_double, (/dimid(1)/), varid(1))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(1), 1, 1, deflate)
     SELECT CASE (trim(caltype))
     CASE ('360_day')
       iret=nf90_put_att(ncid,varid(1),'long_name','time in 360 day calendar')
     CASE ('365_day')
       iret=nf90_put_att(ncid,varid(1),'long_name','time in 365 day calendar')
     CASE ('standard')
       iret=nf90_put_att(ncid,varid(1),'long_name','julian day (UT)')
     END SELECT
     iret=nf90_put_att(ncid,varid(1),'standard_name','time')
     iret=nf90_put_att(ncid,varid(1),'units','days since 1990-01-01 00:00:00')
     iret=nf90_put_att(ncid,varid(1),'conventions',                   &
          'Relative julian days with decimal part (as parts of the day)')
     iret=nf90_put_att(ncid,varid(1),'axis','T')
     iret=nf90_put_att(ncid,varid(1),'calendar',trim(caltype))
     ! frequency
     iret=nf90_def_var(ncid, 'frequency', nf90_float, (/dimid(2)/),varid(2))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(2), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(2),'long_name','center frequencies for spectra')
     iret=nf90_put_att(ncid,varid(2),'standard_name','frequency')
     iret=nf90_put_att(ncid,varid(2),'units','s-1')
     iret=nf90_put_att(ncid,varid(2),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(2),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(2),'valid_min',0.)
     iret=nf90_put_att(ncid,varid(2),'valid_max',10.)
     iret=nf90_put_att(ncid,varid(2),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(2),'axis','Y')
     !frequency1
     iret=nf90_def_var(ncid, 'frequency1', nf90_float, (/dimid(2)/), varid(3))
     CALL check_err(iret)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(3), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(3),'long_name','frequency of lower band')
     iret=nf90_put_att(ncid,varid(3),'standard_name','frequency_of_lower_band')
     iret=nf90_put_att(ncid,varid(3),'globwave_name','frequency_lower_band')
     iret=nf90_put_att(ncid,varid(3),'units','s-1')
     iret=nf90_put_att(ncid,varid(3),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(3),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(3),'valid_min',0.)
     iret=nf90_put_att(ncid,varid(3),'valid_max',10.)
     iret=nf90_put_att(ncid,varid(3),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(3),'content','Y')
     iret=nf90_put_att(ncid,varid(3),'associates','frequency')
     !frequency2
     iret=nf90_def_var(ncid, 'frequency2', nf90_float, (/dimid(2)/), varid(4))
     CALL check_err(iret)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(4), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(4),'long_name','frequency of upper band')
     iret=nf90_put_att(ncid,varid(4),'standard_name','frequency_of_upper_band')
     iret=nf90_put_att(ncid,varid(4),'globwave_name','frequency_upper_band')
     iret=nf90_put_att(ncid,varid(4),'units','s-1')
     iret=nf90_put_att(ncid,varid(4),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(4),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(4),'valid_min',0.)
     iret=nf90_put_att(ncid,varid(4),'valid_max',10.)
     iret=nf90_put_att(ncid,varid(4),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(4),'content','Y')
     iret=nf90_put_att(ncid,varid(4),'associates','frequency')
     ! frequency area
     iret=nf90_def_var(ncid, 'frequency_area', nf90_float,(/dimid(2)/),varid(5))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(5), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(5),'long_name','frequency spectral bin width')
     iret=nf90_put_att(ncid,varid(5),'standard_name','frequency_area')
     iret=nf90_put_att(ncid,varid(5),'units','s-2')
     iret=nf90_put_att(ncid,varid(5),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(5),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(5),'valid_min',0.)
     iret=nf90_put_att(ncid,varid(5),'valid_max',10.)
     iret=nf90_put_att(ncid,varid(5),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(5),'content','Y')
     iret=nf90_put_att(ncid,varid(5),'associates','frequency')
     ! direction
     iret=nf90_def_var(ncid, 'direction', nf90_float, (/dimid(3)/),varid(6))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(6),'long_name','sea surface wave to direction')
     iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_to_direction')
     iret=nf90_put_att(ncid,varid(6),'units','degree')
     iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
     iret=nf90_put_att(ncid,varid(6),'valid_max',360.)
     iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(6),'axis','Z')
     IF (flagll) THEN
       !  longitude
       iret=nf90_def_var(ncid, 'longitude', nf90_float, (/dimid(1)/),varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','longitude')
       iret=nf90_put_att(ncid,varid(7),'standard_name','longitude')
       iret=nf90_put_att(ncid,varid(7),'units','degree_east')
       iret=nf90_put_att(ncid,varid(7),'valid_min',-180.0)
       iret=nf90_put_att(ncid,varid(7),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','T')
       iret=nf90_put_att(ncid,varid(7),'associates','time')
       !  latitude
       iret=nf90_def_var(ncid, 'latitude', nf90_float, (/dimid(1)/),varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','latitude')
       iret=nf90_put_att(ncid,varid(8),'standard_name','latitude')
       iret=nf90_put_att(ncid,varid(8),'units','degree_north')
       iret=nf90_put_att(ncid,varid(8),'valid_min',-90.0)
       iret=nf90_put_att(ncid,varid(8),'valid_max',180.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','T')
       iret=nf90_put_att(ncid,varid(8),'associates','time')
     ELSE
       !  longitude
       iret=nf90_def_var(ncid, 'x', nf90_float, (/dimid(1)/),varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','x')
       iret=nf90_put_att(ncid,varid(7),'standard_name','x')
       iret=nf90_put_att(ncid,varid(7),'units','m')
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','T')
       iret=nf90_put_att(ncid,varid(7),'associates','time')
       !  latitude
       iret=nf90_def_var(ncid, 'y', nf90_float, (/dimid(1)/),varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','y')
       iret=nf90_put_att(ncid,varid(8),'standard_name','y')
       iret=nf90_put_att(ncid,varid(8),'units','m')
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','T')
       iret=nf90_put_att(ncid,varid(8),'associates','time')
     END IF
     ! Efth
     iret=nf90_def_var(ncid,'efth',nf90_float,(/dimid(3),dimid(2),dimid(1)/),varid(9))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(9),'long_name',                     &
          'sea surface wave directional variance spectral density')
     iret=nf90_put_att(ncid,varid(9),'standard_name',                 &
          'sea_surface_wave_directional_variance_spectral_density')
     iret=nf90_put_att(ncid,varid(9),'globwave_name',                 &
          'directional_variance_spectral_density')
     iret=nf90_put_att(ncid,varid(9),'units','m2 s rad-1')
     iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
     iret=nf90_put_att(ncid,varid(9),'valid_max',10.)
     iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(9),'content','TYZ')
     iret=nf90_put_att(ncid,varid(9),'associates','time frequency direction')
     ! DW - depth
     iret=nf90_def_var(ncid, 'dpt', nf90_float, (/dimid(1)/),varid(10))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(10),'long_name','depth')
     iret=nf90_put_att(ncid,varid(10),'standard_name','depth')
     iret=nf90_put_att(ncid,varid(10),'globwave_name','depth')
     iret=nf90_put_att(ncid,varid(10),'units','m')
     iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(10),'content','T')
     iret=nf90_put_att(ncid,varid(10),'associates','time')
     ! CAO - current speed (m/s)
     iret=nf90_def_var(ncid, 'cur', nf90_float,(/dimid(1)/), varid(11))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(11),'long_name','sea water speed')
     iret=nf90_put_att(ncid,varid(11),'standard_name','sea_water_speed')
     iret=nf90_put_att(ncid,varid(11),'globwave_name','sea_water_speed')
     iret=nf90_put_att(ncid,varid(11),'units','m s-1')
     iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(11),'content','T')
     iret=nf90_put_att(ncid,varid(11),'associates','time')
     ! CDO - current direction (degree)
     iret=nf90_def_var(ncid, 'curdir', nf90_float,(/dimid(1)/), varid(12))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(12),'long_name','direction from of sea water velocity')
     iret=nf90_put_att(ncid,varid(12),'standard_name','direction_of_sea_water_velocity')
     iret=nf90_put_att(ncid,varid(12),'globwave_name','direction_of_sea_water_velocity')
     iret=nf90_put_att(ncid,varid(12),'units','degree')
     iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(12),'content','T')
     iret=nf90_put_att(ncid,varid(12),'associates','time')
     ! WAO - wind speed (m/s)
     iret=nf90_def_var(ncid, 'wnd', nf90_float,(/dimid(1)/), varid(13))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(13),'long_name','wind speed at 10m')
     iret=nf90_put_att(ncid,varid(13),'standard_name','wind_speed')
     iret=nf90_put_att(ncid,varid(13),'globwave_name','wind_speed')
     iret=nf90_put_att(ncid,varid(13),'units','m s-1')
     iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(13),'content','T')
     iret=nf90_put_att(ncid,varid(13),'associates','time')
     ! WDO - wind direction (degree)
     iret=nf90_def_var(ncid, 'wnddir', nf90_float,(/dimid(1)/), varid(14))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(14),'long_name','wind direction')
     iret=nf90_put_att(ncid,varid(14),'standard_name','wind_from_direction')
     iret=nf90_put_att(ncid,varid(14),'globwave_name','wind_from_direction')
     iret=nf90_put_att(ncid,varid(14),'units','m s-1')
     iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(14),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(14),'content','T')
     iret=nf90_put_att(ncid,varid(14),'associates','time')
     ! UST - friction velocity  (m/s)
     iret=nf90_def_var(ncid, 'ust', nf90_float,(/dimid(1)/), varid(15))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(15),'long_name','friction velocity')
     iret=nf90_put_att(ncid,varid(15),'standard_name','friction_velocity')
     iret=nf90_put_att(ncid,varid(15),'globwave_name','friction_velocity')
     iret=nf90_put_att(ncid,varid(15),'units','m s-1')
     iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(15),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(15),'content','T')
     iret=nf90_put_att(ncid,varid(15),'associates','time')
     ! AS - air-sea temperature difference (deg C)
     iret=nf90_def_var(ncid, 'ast',nf90_float,(/dimid(1)/), varid(16))
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(16), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(16),'long_name','air sea temperature difference')
     iret=nf90_put_att(ncid,varid(16),'standard_name','air_sea_temperature_difference')
     iret=nf90_put_att(ncid,varid(16),'globwave_name','air_sea_temperature_difference')
     iret=nf90_put_att(ncid,varid(16),'units','degree')
     iret=nf90_put_att(ncid,varid(16),'scale_factor',1.)
     iret=nf90_put_att(ncid,varid(16),'add_offset',0.)
     iret=nf90_put_att(ncid,varid(16),'_FillValue',nf90_fill_float)
     iret=nf90_put_att(ncid,varid(16),'content','T')
     iret=nf90_put_att(ncid,varid(16),'associates','time')
     !  string32
     iret=nf90_def_var(ncid, 'string32', nf90_int, (/dimid(4)/), varid(17))
     CALL check_err(iret)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(17), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(17),'long_name','track_name number of characters')
     iret=nf90_put_att(ncid,varid(17),'_FillValue',nf90_fill_int)
     iret=nf90_put_att(ncid,varid(17),'axis','W')
     !  track_name
     iret=nf90_def_var(ncid, 'track_name', nf90_char, (/dimid(4),dimid(1)/), varid(18))
     CALL check_err(iret)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(18), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(18),'long_name','track name')
     iret=nf90_put_att(ncid,varid(18),'content','TX')
     iret=nf90_put_att(ncid,varid(18),'associates','time string16')
     RETURN
References check_err().
w3exnc()
subroutine w3trnc::w3exnc (character(30), intent(in) FILEPREFIX, integer, intent(in) NCTYPE, integer, intent(inout) NCID, integer, intent(inout) S3, character(30), intent(in) STRSTOPDATE, integer, intent(in) MK, integer, intent(in) MTH)
Perform actual track output in NetCDF file.
Parameters
[in] FILEPREFIX
[in] NCTYPE
[in,out] NCID
[in,out] S3
[in] STRSTOPDATE
[in] MK
[in] MTH
Author
M. Accensi
Date
08-Apr-2016
Definition at line 462 of file ww3_trnc.F90.
     !/
     !/                  +-----------------------------------+
     !/                  |           M. Accensi              |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :          8-Apr-2016 |
     !/                  +-----------------------------------+
     !/
     !/     8-apr-2016 : Creation                            ( version 5.11 )
     !/
     !  1. Purpose :
     !
     !     Perform actual track output in NetCDF file.
     !
     !  3. Parameters :
     !
     !     Parameter list
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !     Internal parameters
     !     ----------------------------------------------------------------
     !     ----------------------------------------------------------------
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      EXTCDE    Subr.   Id.    Abort program as graceful as possible.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Main program in which it is contained.
     !
     !  6. Error messages :
     !
     !       None.
     !
     !  7. Remarks :
     !
     !       None.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S  Enable subroutine tracing.
     !       !/T  Enable test output.
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
     USE netcdf
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     !/ Parameter list
     !/
     INTEGER, INTENT(IN)       :: NCTYPE, MK, MTH
     CHARACTER(30), INTENT(IN) :: FILEPREFIX, STRSTOPDATE
     INTEGER, INTENT(INOUT)    :: NCID, S3
     !/
     !/ ------------------------------------------------------------------- /
     !/ Local parameters
     !/
     INTEGER                 :: S1, S2, S4, S5, NDSDAT, IRET
     INTEGER                 :: STARTDATE(8), CURDATE(8), REFDATE(8)
     INTEGER                  :: DEFLATE=1
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   =   0
 #endif
     !
     DOUBLE PRECISION        :: OUTJULDAY
     !
     CHARACTER*30            :: STRSTARTDATE
     CHARACTER               :: FNAMENC*50, ENAME*6
     CHARACTER, SAVE         :: OLDTIMEID*16 = '0000000000000000'
     CHARACTER, SAVE         :: TIMEID*16 = '0000000000000000'
     !/
     !/ ------------------------------------------------------------------- /
     !/
     !
 #ifdef W3_S
     CALL strace (ient, 'W3EXNC')
 #endif
     !
     CALL u2d('days since 1990-01-01 00:00:00',refdate,ierr)
     ! 1.1 Sets the date as ISO8601 convention
     ! S3 defines the number of characters in the date for the filename
     ! S3=4-> YYYY, S3=6 -> YYYYMM, S3=10 -> YYYYMMDDHH
     ! Setups min and max date format
     IF (s3.LT.4) s3=4
     IF (s3.GT.10) s3=10
     !
     ! Defines the format of FILETIME
     s5=s3-8
     s4=s3
     oldtimeid=timeid
     ! if S3=>YYYYMMDDHH then filetime='YYYYMMDDTHHMMSSZ'
     IF (s3.EQ.10) THEN
       s4=s4+2 ! add chars for ISO8601 : day T hours Z
       WRITE(format1,'(A,I1,A,I1,A)') '(I8.8,A1,I',s5,'.',s5,',A1)'
       WRITE (timeid,format1) time(1), 'T', &
            floor(real(time(2))/nint(10.**(6-s5))), 'Z'
       ! if S3=>YYYYMMDD then filetime='YYYYMMDD'
     ELSE IF (s3.EQ.8) THEN
       WRITE(format1,'(A,I1,A,I1,A)') '(I',s3,'.',s3,')'
       WRITE (timeid,format1) time(1)
       ! if S3=>YYYYMM then filetime='YYYYMM'
       ! or S3=>YYYY then filetime='YYYY'
     ELSE
       WRITE(format1,'(A,I1,A,I1,A)') '(I',s3,'.',s3,')'
       WRITE (timeid,format1) floor(real(time(1))/nint(10.**(8-s3)))
     END IF
     ! redefines filename with updated date format
     s1=len_trim(fileprefix)
     fnamenc=''
     fnamenc(1:s1)=fileprefix(1:s1)
     fnamenc(s1+1:s1+s4) = timeid(1:s4)
     ! 1.2 Setups the output type 4 ( NetCDF file )
     ename='.trck'
     s2=len_trim(ename)
     s1=len_trim(fileprefix)+s4
     fnamenc(s1+1:50)='       '
     fnamenc(s1+1:s1+1) = '_'
     ! add variable name in file name
     fnamenc(s1+2:s1+s2) = ename(2:s2)
     ! Defines the netcdf extension
     fnamenc(s1+s2+1:s1+s2+3) = '.nc'
     fnamenc(s1+s2+4:s1+s2+6) = '   '
     ! Defines the dimensions
     dimln(1)=nf90_unlimited ! time
     dimln(2)=mk ! frequency
     dimln(3)=mth ! direction
     dimln(4)=32  ! string track name length
     ! 1.3 Gets the netcdf id
     ndsdat=30
     OPEN (ndsdat,file=fnamenc,status='new',iostat=iret)
     IF (iret.EQ.0) THEN
       ! CLOSE old file
       IF (index('0000000000000000',oldtimeid).EQ.0 .AND. index(timeid,oldtimeid).EQ.0) THEN
         iret = nf90_redef(ncid)
         CALL check_err(iret)
         iret=nf90_put_att(ncid,nf90_global,'stop_date',strstopdate)
         CALL check_err(iret)
         iret=nf90_close(ncid)
         CALL check_err(iret)
       END IF
       ncid=0
     ELSE
       ncid=ncid
     END IF
     ! 1.4 Creates the netcdf file
     IF (ncid.EQ.0) THEN
       ! Initializes the time iteration counter n
       it      = 0
       iloc    = 0
       ispec   = 0
       ! 1.4.1 Creates the NetCDF file
       CALL w3crnc(nctype,fnamenc,ncid,dimid,dimln,varid)
       ! put start date in global attribute
       CALL t2d(time,startdate,ierr)
       WRITE(strstartdate,'(I4.4,A,4(I2.2,A),I2.2)') startdate(1),'-',startdate(2),'-', &
            startdate(3),' ',startdate(5),':',startdate(6),':',startdate(7)
       !
       iret=nf90_put_att(ncid,nf90_global,'start_date',strstartdate)
       CALL check_err(iret)
       ! End of define mode of NetCDF file
       iret = nf90_enddef(ncid)
       CALL check_err(iret)
       ! Process lower band and higher band frequencies
       freq1(1:mk)=freq(1:mk)-0.5*(freq(1:mk)-(freq(1:mk)/xfr))
       freq2(1:mk)=freq(1:mk)+0.5*(-freq(1:mk)+(freq(1:mk)*xfr))
       freq1(1)=freq(1)
       freq2(mk)=freq(mk)
       ! Converts direction unit in degree
       dthd=360./mth
       rth0=th1/dth
       DO ith=1, mth
         thd(ith)=dthd*(rth0+real(ith-1))
       END DO
       dir(1:mth)=mod(360-thd(1:mth),360.)
       ! 1.4.2 Adds general variables to NetCDF file
       iret=nf90_put_var(ncid,varid(2),freq)
       CALL check_err(iret)
       iret=nf90_put_var(ncid,varid(3),freq1)
       CALL check_err(iret)
       iret=nf90_put_var(ncid,varid(4),freq2)
       CALL check_err(iret)
       iret=nf90_put_var(ncid,varid(5),dsip)
       CALL check_err(iret)
       iret=nf90_put_var(ncid,varid(6),dir)
       CALL check_err(iret)
       WRITE (ndso,973) fnamenc
     END IF  ! IERR.EQ.0
     ! 1.5 Defines the current time step and index
     CALL t2d(time,curdate,ierr)
     outjulday=tsub(refdate,curdate)
     WRITE(ndso,'(3A,I6,A,I4,A,I2.2,A,I2.2,A,I2.2,A,I2.2,A,I2.2,2A)')       &
          'Writing new record ', ename(2:) ,'number ',it,                  &
          ' for ',curdate(1),':',curdate(2),':',curdate(3),'T',curdate(5), &
          ':',curdate(6),':',curdate(7),' in file ',trim(fnamenc)
     !
     ! 1.6 Exit from W3EXNC if not sea point
     !
     IF ( tststr .NE. 'SEA' ) GOTO 888
     !
     ! 1.6.1 Process speed and direction components
     !
     wao = sqrt( wx**2 + wy**2 )
     IF ( wao.GT.1.e-7 ) THEN
       wdo = mod(270.-atan2(wy,wx)*rade,360.)
     ELSE
       wdo = 0.
     END IF
     cao = sqrt( cx**2 + cy**2 )
     IF ( cao.GT.1.e-7 ) THEN
       cdo = mod(270.-atan2(cy,cx)*rade,360.)
     ELSE
       cdo = 0.
     END IF
     !
     ! 1.7.1 Puts dimensions variables in NetCDF file
     !
     it=it+1
     IF ( ust .LT. 0. ) ust = -1.0
     ! time
     iret=nf90_put_var(ncid,varid(1),outjulday,start=(/it/))
     CALL check_err(iret)
     ! longitude
     iret=nf90_put_var(ncid,varid(7),m2km*x,start=(/it/))
     CALL check_err(iret)
     ! latitude
     iret=nf90_put_var(ncid,varid(8),m2km*y,start=(/it/))
     CALL check_err(iret)
     ! 1.7.2 Puts fields in NetCDF file
     ! 1.7.2.a Write spectrum
     iret=nf90_put_var(ncid,varid(9),                               &
          transpose(spec),start=(/1,1,it/), count=(/mth,mk,1/))
     CALL check_err(iret)
     ! 1.7.2.b Write the basic stuff
     ! Write DW (depth)
     iret=nf90_put_var(ncid, varid(10),dw ,start=(/it/))
     CALL check_err(iret)
     ! Write CAO (current - x direction)
     iret=nf90_put_var(ncid, varid(11),cao ,start=(/it/))
     CALL check_err(iret)
     ! Write CDO (current - y direction)
     iret=nf90_put_var(ncid,varid(12),cdo ,start=(/it/))
     CALL check_err(iret)
     ! Write WAO (wind velocity - x direction)
     iret=nf90_put_var(ncid,varid(13),wao ,start=(/it/))
     CALL check_err(iret)
     ! Write WDO (wind velocity - y direction)
     iret=nf90_put_var(ncid,varid(14),wdo ,start=(/it/))
     CALL check_err(iret)
     ! Write UST (friction velocity)
     iret=nf90_put_var(ncid,varid(15),ust,start=(/it/))
     CALL check_err(iret)
     ! Write AS (air sea temperature difference)
     iret=nf90_put_var(ncid,varid(16),as ,start=(/it/))
     CALL check_err(iret)
     ! Track name
     iret=nf90_put_var(ncid,varid(18),trckid,start=(/1,it/),count=(/len_trim(trckid),1/))
     CALL check_err(iret)
     !
 888 CONTINUE
     !
     RETURN
     !
     ! Formats
     !
 973 FORMAT ( 'NEW NetCDF file was created ',a)
     !/ End of W3EXNC ----------------------------------------------------- /
     !/
References check_err(), file(), constants::rade, and w3crnc().
w3trnc()
program w3trnc
Convert direct access track output file to netCDF file.
Info read from track_o.ww3, written to track.nc.
Author
M. Accensi
Date
15-May-2018
Definition at line 15 of file ww3_trnc.F90.
References check_err(), w3servmd::extcde(), file(), constants::file_endian, w3gdatmd::flagll, w3odatmd::fnmpre, w3gdatmd::gname, w3servmd::itrace(), w3odatmd::ndse, w3odatmd::ndso, w3servmd::nextln(), w3servmd::strace(), w3exnc(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3nmltrncmd::w3nmltrnc(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), and w3gdatmd::xfr.