WAVEWATCH III: ww3_prnc.F90 File Reference
ww3_prnc.F90 File Reference
Contains program W3PRNC.
Functions/Subroutines
program w3prnc
Pre-processing of input fields.
subroutine interp (MXM, MYM, XC, IX21, IX22, IY21, IY22, RD11, RD12, RD21, RD22, FILLVALUE, FA)
Interpolate from a field read from file to the wave grid.
subroutine check_error (IRET, ILINE)
Desc not available.
Detailed Description
Contains program W3PRNC.
Author
M. Accensi
F. Ardhuin
Date
22-Mar-2021
Definition in file ww3_prnc.F90.
Function/Subroutine Documentation
check_error()
subroutine check_error (integer IRET, integer ILINE)
Desc not available.
Parameters
IRET
ILINE
Author
NA
Date
NA
Definition at line 2722 of file ww3_prnc.F90.
   USE netcdf
   USE w3odatmd, ONLY: ndse
   USE w3servmd, ONLY: extcde
   IMPLICIT NONE
   INTEGER IRET, ILINE
   IF (iret .NE. nf90_noerr) THEN
     WRITE(ndse,*) ' *** WAVEWATCH III ERROR IN PRNC :'
     WRITE(ndse,*) ' LINE NUMBER ', iline
     WRITE(ndse,*) ' NETCDF ERROR MESSAGE: '
     WRITE(ndse,*) nf90_strerror(iret)
     CALL extcde ( 59 )
   END IF
   RETURN
References w3servmd::extcde(), and w3odatmd::ndse.
interp()
subroutine interp (integer, intent(in) MXM, integer, intent(in) MYM, real, dimension(mxm,mym), intent(in) XC, integer, dimension(nx,ny), intent(in) IX21, integer, dimension(nx,ny), intent(in) IX22, integer, dimension(nx,ny), intent(in) IY21, integer, dimension(nx,ny), intent(in) IY22, real, dimension(nx,ny), intent(in) RD11, real, dimension(nx,ny), intent(in) RD12, real, dimension(nx,ny), intent(in) RD21, real, dimension(nx,ny), intent(in) RD22, real, intent(in) FILLVALUE, real, dimension(nx,ny), intent(out) FA)
Interpolate from a field read from file to the wave grid.
Invalid points are identified by the fill value read from the netcdf input, and interpolation does not take into account these points. The valid interpolation coefficients are scaled so that the sum is one, otherwise unphysical values can be generated.
When one point is on the boundary but is not an ocean grid point, the interpolation coefficients are zero, and in this case we provide a sensible value - the value as read, not interpolated
Parameters
[in] MXM Dimension X of XC variable
[in] MYM Dimension Y of XC variable
[in] XC Field to be interpolated, as read from the input netcdf
[in] IX21 List of x-index to convert from the original field to the model grid
[in] IX22 List of x-index to convert from the original field to the model grid
[in] IY21 List of y-index to convert from the original field to the model grid
[in] IY22 List of x-index to convert from the original field to the model grid
[in] RD11 Interpolation factor
[in] RD12 Interpolation factor
[in] RD21 Interpolation factor
[in] RD22 Interpolation factor
[in] FILLVALUE Fill value identifying non valid input
[out] FA Result of the interpolation
Author
J. M. Castillo
Date
23-Feb-2021
Definition at line 2580 of file ww3_prnc.F90.
   !/
   !/                  +-----------------------------------+
   !/                  | WAVEWATCH III           NOAA/NCEP |
   !/                  |           J. M. Castillo          |
   !/                  |                        FORTRAN 90 |
   !/                  | Last update :         23-Feb-2021 |
   !/                  +-----------------------------------+
   !/
   !/    23-Feb-2021 : First version                       ( version 7.12 )
   !/
   !  1. Purpose :
   !
   !     Interpolate from a field read from file to the wave grid
   !
   !  2. Method :
   !
   !     Invalid points are identified by the fill value read from the
   !     netcdf input, and interpolation does not take into account
   !     these points. The valid interpolation coefficients are scaled
   !     so that the sum is one, otherwise unphysical values can be
   !     generated.
   !
   !     When one point is on the boundary but is not an ocean grid point,
   !     the interpolation coefficients are zero, and in this case we
   !     provide a sensible value - the value as read, not interpolated
   !
   !  3. Parameters :
   !
   !     Parameter list
   !     ----------------------------------------------------------------
   !       MxM     I      I   Dimensions of the XC variable
   !       XC      R.A.   I   Field to be interpolated, as read from the
   !                          input netcdf
   !       IXxx    I.A.   I   List of x-index to convert from the original
   !                          field to the model grid
   !       IYxx    I.A.   I   List of y-index to convert from the original
   !                          field to the model grid
   !       RDxx    R.A.   I   Interpolation factors
   !       FILLVALUE   R  I   Fill value identifying non valid input
   !       FA      F      O   Result of the interpolation
   !     ----------------------------------------------------------------
   !
   !  4. Subroutines used :
   !
   !     None
   !
   !  5. Called by :
   !
   !      Name      Type  Module   Description
   !     ----------------------------------------------------------------
   !      WW3_PRNC  Prog.   N/A    Input data preprocessor.
   !     ----------------------------------------------------------------
   !
   !  6. Error messages :
   !
   !     None
   !
   !  7. Remarks :
   !
   !  8. Structure :
   !
   !     See source code.
   !
   !  9. Switches :
   !
   ! 10. Source code :
   !
   !/ ------------------------------------------------------------------- /
   USE w3gdatmd, ONLY: nx, ny
   IMPLICIT NONE
   !/
   !/ ------------------------------------------------------------------- /
   !/ Parameter list
   !/
   INTEGER,                     INTENT(IN)  :: MXM, MYM
   REAL,    DIMENSION(MXM,MYM), INTENT(IN)  :: XC
   INTEGER, DIMENSION(NX,NY),   INTENT(IN)  :: IX21, IX22, IY21, IY22
   REAL,    DIMENSION(NX,NY),   INTENT(IN)  :: RD11, RD12, RD21, RD22
   REAL,                        INTENT(IN)  :: FILLVALUE
   REAL,    DIMENSION(NX,NY),   INTENT(OUT) :: FA
   !/
   !/ ------------------------------------------------------------------- /
   !/    Local variables
   !/
   INTEGER      :: IX, IY
   REAL         :: FACTOR
   !/ ------------------------------------------------------------------- /
   DO iy=1,ny
     DO ix=1,nx
       factor = 0.0
       fa(ix,iy) = 0.0
       IF(xc(ix21(ix,iy),iy21(ix,iy)).NE.fillvalue) THEN
         factor = factor + rd11(ix,iy)
         fa(ix,iy) = rd11(ix,iy) * xc(ix21(ix,iy),iy21(ix,iy))
       ENDIF
       IF(xc(ix22(ix,iy),iy21(ix,iy)).NE.fillvalue) THEN
         factor = factor + rd21(ix,iy)
         fa(ix,iy) = fa(ix,iy) + rd21(ix,iy) * xc(ix22(ix,iy),iy21(ix,iy))
       ENDIF
       IF(xc(ix21(ix,iy),iy22(ix,iy)).NE.fillvalue) THEN
         factor = factor + rd12(ix,iy)
         fa(ix,iy) = fa(ix,iy) + rd12(ix,iy) * xc(ix21(ix,iy),iy22(ix,iy))
       ENDIF
       IF(xc(ix22(ix,iy),iy22(ix,iy)).NE.fillvalue) THEN
         factor = factor + rd22(ix,iy)
         fa(ix,iy) = fa(ix,iy) + rd22(ix,iy) * xc(ix22(ix,iy),iy22(ix,iy))
       ENDIF
       IF(factor.GT.0.0) THEN
         fa(ix,iy) = fa(ix,iy) / factor
       ELSE
         ! Interpolation coefficients sum to zero - could be on a boundary
         ! (see note in "method" above). If any surrounding points have a
         ! valid value then use one of them, otherwise set to zero.
         IF( xc(ix21(ix,iy),iy21(ix,iy)) .NE. fillvalue) THEN
           fa(ix,iy) = xc(ix21(ix,iy),iy21(ix,iy))
         ELSE IF( xc(ix22(ix,iy),iy21(ix,iy)) .NE. fillvalue) THEN
           fa(ix,iy) = xc(ix22(ix,iy),iy21(ix,iy))
         ELSE IF( xc(ix21(ix,iy),iy22(ix,iy)) .NE. fillvalue) THEN
           fa(ix,iy) = xc(ix21(ix,iy),iy22(ix,iy))
         ELSE IF( xc(ix22(ix,iy),iy22(ix,iy)) .NE. fillvalue) THEN
           fa(ix,iy) = xc(ix22(ix,iy),iy22(ix,iy))
         ELSE
           ! All surrounding points are FILLVALUE - set to zero.
           fa(ix,iy) = 0.0
         END IF
       END IF
     END DO
   END DO
References w3gdatmd::nx, and w3gdatmd::ny.
Referenced by w3bounc(), w3bound(), and w3prnc().
w3prnc()
program w3prnc
Pre-processing of input fields.
Pre-processing of the input water level, current, wind, ice fields, momentum and air density, as well as assimilation data ... from NetCDF input.
Author
M. Accensi
F. Ardhuin
Date
22-Mar-2021
Definition at line 22 of file ww3_prnc.F90.
References check_err(), w3timemd::d2j(), w3servmd::extcde(), file(), constants::file_endian, w3odatmd::fnmpre, w3gdatmd::gname, w3odatmd::iaproc, w3arrymd::ina2i(), w3arrymd::ina2r(), include(), interp(), w3servmd::itrace(), w3odatmd::naperr, w3odatmd::napout, w3odatmd::naproc, w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3gdatmd::nx, w3gdatmd::ny, w3arrymd::prtblk(), w3servmd::strace(), w3servmd::strsplit(), w3timemd::t2d(), w3fldsmd::w3fldd(), w3fldsmd::w3fldg(), w3fldsmd::w3fldo(), w3fldsmd::w3fldp(), w3fldsmd::w3fldtide1(), w3fldsmd::w3fldtide2(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3nmlprncmd::w3nmlprnc(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), and w3odatmd::w3seto().