WAVEWATCH III: ww3_strt.F90 File Reference
ww3_strt.F90 File Reference
Contains program W3STRT for "cold start" initial conditions.
Functions/Subroutines
program w3strt
Generation of initial conditions for a "cold start" of WAVEWATCH III.
Detailed Description
Contains program W3STRT for "cold start" initial conditions.
Author
H. L. Tolman
Date
06-Jun-2018
Definition in file ww3_strt.F90.
Function/Subroutine Documentation
w3strt()
program w3strt
Generation of initial conditions for a "cold start" of WAVEWATCH III.
General model information is obtained from the model definition file using W3IOGR. The type of the initial field is read from the input file WW3_strt.inp (NDSI). Three types of initial conditions are available.
1) Gaussian distribution in longitude, latitude and frequency, cos power in directions. Can default to single spectral bin.
2) Predefined JONSWAP spectrum, Gaussian height distribution in space.
3) Fetch-limited JONSWAP spectrum based on the actual wind speed. To avoid the need of reading a wind field, the restart file is a "dummy", and the actual initial field is constructed in the initialization routine W3INIT.
4) User defined spectrum throughout the model.
5) Starting from rest.
The initial conditions are written to the restart.WW3 using the subroutine W3IORS. Note that the name of the restart file is set in W3IORS.
Author
H. L. Tolman
Date
06-Jun-2018
Definition at line 37 of file ww3_strt.F90.
References constants::dera, w3servmd::ej5p(), w3servmd::extcde(), file(), w3odatmd::flogrr, w3odatmd::fnmpre, w3odatmd::iaproc, include(), w3servmd::itrace(), w3odatmd::naperr, w3odatmd::napout, w3odatmd::naproc, w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3arrymd::prt1ds(), w3arrymd::prt2ds(), w3arrymd::prtblk(), w3servmd::strace(), constants::tpi, constants::tpiinv, w3iogrmd::w3iogr(), w3iorsmd::w3iors(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3idatmd::w3ninp(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), and w3dispmd::wavnu1().