WAVEWATCH III: ww3_prep.F90 File Reference
ww3_prep.F90 File Reference
Contains program W3PREP for pre-processing of inputs.
Functions/Subroutines
program w3prep
Preprocessing of input data.
Detailed Description
Contains program W3PREP for pre-processing of inputs.
Author
H. L. Tolman
Date
22-Mar-2021
Definition in file ww3_prep.F90.
Function/Subroutine Documentation
w3prep()
program w3prep
Preprocessing of input data.
Pre-processing of the input water level, current, wind, ice fields, momentum and air density, as well as assimilation data for the generic shell W3SHEL (ww3_shel.ftn).
Author
H. L. Tolman
Date
22-Mar-2021
Definition at line 17 of file ww3_prep.F90.
References w3servmd::extcde(), file(), constants::file_endian, w3odatmd::fnmpre, w3arrymd::ina2i(), w3arrymd::ina2r(), w3servmd::itrace(), w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3arrymd::prtblk(), w3timemd::stme21(), w3servmd::strace(), w3fldsmd::w3fldd(), w3fldsmd::w3fldg(), w3fldsmd::w3fldo(), w3fldsmd::w3fldp(), w3iogrmd::w3iogr(), w3adatmd::w3naux(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), and w3odatmd::w3seto().