WAVEWATCH III: ww3_ounp.F90 File Reference
ww3_ounp.F90 File Reference
Contains program W3OUNP.
Functions/Subroutines
program w3ounp
Post-processing of point output.
subroutine w3exnc (I, NCID, NREQ, INDREQ, ORDER)
Perform actual point output.
subroutine w3crnc (ITYPE, OTYPE, NCTYPE, NCFILE, NCID, DIMID, DIMLN, VARID, ONE, TWO, FLSRCE, NCVARTYPE)
Desc not available.
subroutine check_err (IRET, ICODE)
Desc not available.
Detailed Description
Contains program W3OUNP.
Author
F Ardhuin
M Accensi
Date
06-Sep-2021
Definition in file ww3_ounp.F90.
Function/Subroutine Documentation
check_err()
subroutine w3ounp::check_err (integer IRET, integer ICODE)
Desc not available.
Parameters
IRET
ICODE
Author
NA
Date
NA
Definition at line 5570 of file ww3_ounp.F90.
     USE netcdf
     USE w3odatmd, ONLY: ndse
     USE w3servmd, ONLY: extcde
     IMPLICIT NONE
     INTEGER IRET, ICODE
     IF (iret .NE. nf90_noerr) THEN
       WRITE(ndse,*) ' *** WAVEWATCH III ERROR IN OUNP :'
       WRITE(ndse,*) ' NETCDF ERROR MESSAGE: '
       WRITE(ndse,*) nf90_strerror(iret)
       WRITE(ndse,*) ' ICODE: '
       WRITE(ndse,*) icode
       CALL extcde ( icode )
     END IF
     RETURN
References w3servmd::extcde(), and w3odatmd::ndse.
w3crnc()
subroutine w3ounp::w3crnc (integer, intent(in) ITYPE, integer, intent(in) OTYPE, integer, intent(in) NCTYPE, character*(128), intent(in) NCFILE, integer, intent(out) NCID, integer, dimension(7), intent(out) DIMID, integer, dimension(5), intent(in) DIMLN, integer, dimension(28), intent(out) VARID, integer, intent(in) ONE, integer, intent(in) TWO, logical, dimension(7), intent(in), optional FLSRCE, integer, intent(in), optional NCVARTYPE)
Desc not available.
Parameters
[in] ITYPE
[in] OTYPE
[in] NCTYPE
[in] NCFILE
[out] NCID
[out] DIMID
[in] DIMLN
[out] VARID
[in] ONE
[in] TWO
[in] FLSRCE
[in] NCVARTYPE
Author
NA
Date
NA
Definition at line 3086 of file ww3_ounp.F90.
     USE w3gdatmd
     USE netcdf
     implicit none
     INTEGER, INTENT(IN)               :: ITYPE,OTYPE,NCTYPE, ONE, TWO
     CHARACTER*(128), INTENT(IN)       :: NCFILE
     INTEGER, INTENT(IN)               :: DIMLN(5)
     INTEGER, INTENT(OUT)              :: DIMID(7), VARID(28),NCID
     LOGICAL, INTENT(IN), OPTIONAL     :: FLSRCE(7)
     INTEGER, INTENT(IN), OPTIONAL     :: NCVARTYPE
     ! local parameters
     INTEGER                           :: IRET
     INTEGER                             :: DEFLATE=1
     !
     REAL(kind=4)                      :: freq(nk), freq1(nk),freq2(nk), dir(nth)
     !
     ! Creation in netCDF3 or netCDF4
     !
     IF(nctype.EQ.3) iret = nf90_create(trim(ncfile), nf90_clobber, ncid)
     IF(nctype.EQ.4) iret = nf90_create(trim(ncfile), nf90_netcdf4, ncid)
     CALL check_err(iret,20)
     !
     !     Define generals dimensions
     !
     iret = nf90_def_dim(ncid, 'time', dimln(1), dimid(1))
     CALL check_err(iret,21)
     iret = nf90_def_dim(ncid, 'station', dimln(2), dimid(2))
     CALL check_err(iret,22)
     iret = nf90_def_dim(ncid, 'string40', dimln(3), dimid(3))
     CALL check_err(iret,23)
     !
     !     define generals variables
     !
     !  time
     iret=nf90_def_var(ncid, 'time', nf90_double, dimid(1), varid(1))
     CALL check_err(iret,24)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(1), 1, 1, deflate)
     SELECT CASE (trim(caltype))
     CASE ('360_day')
       iret=nf90_put_att(ncid,varid(1),'long_name','time in 360 day calendar')
     CASE ('365_day')
       iret=nf90_put_att(ncid,varid(1),'long_name','time in 365 day calendar')
     CASE ('standard')
       iret=nf90_put_att(ncid,varid(1),'long_name','julian day (UT)')
     END SELECT
     iret=nf90_put_att(ncid,varid(1),'standard_name','time')
     iret=nf90_put_att(ncid,varid(1),'units','days since 1990-01-01 00:00:00')
     iret=nf90_put_att(ncid,varid(1),'conventions','Relative julian days with decimal part (as parts of the day)')
     iret=nf90_put_att(ncid,varid(1),'axis','T')
     iret=nf90_put_att(ncid,varid(1),'calendar',trim(caltype))
     !  station
     iret=nf90_def_var(ncid, 'station', nf90_int, (/dimid(2)/), varid(27))
     CALL check_err(iret,25)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(27), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(27),'long_name','station id')
     iret=nf90_put_att(ncid,varid(27),'_FillValue',nf90_fill_int)
     iret=nf90_put_att(ncid,varid(27),'axis','X')
     !  string40
     iret=nf90_def_var(ncid, 'string40', nf90_int, (/dimid(3)/), varid(28))
     CALL check_err(iret,26)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(28), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(28),'long_name','station_name number of characters')
     iret=nf90_put_att(ncid,varid(28),'_FillValue',nf90_fill_int)
     iret=nf90_put_att(ncid,varid(28),'axis','W')
     !  station_name
     iret=nf90_def_var(ncid, 'station_name', nf90_char, (/dimid(3),dimid(2)/), varid(2))
     CALL check_err(iret,27)
     IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(2), 1, 1, deflate)
     iret=nf90_put_att(ncid,varid(2),'long_name','station name')
     iret=nf90_put_att(ncid,varid(2),'content','XW')
     iret=nf90_put_att(ncid,varid(2),'associates','station string40')
     IF (flww3.NE.0) THEN
       !  wwIII param version
       iret=nf90_def_var(ncid, 'WWIII_param_version', nf90_short, (/dimid(two),dimid(one)/), varid(3))
       CALL check_err(iret,28)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(3), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(3),'long_name','WaveWatch III parameters version')
       iret=nf90_put_att(ncid,varid(3),'standard_name','WWIII_param_version')
       iret=nf90_put_att(ncid,varid(3),'globwave_name','WWIII_param_version')
       iret=nf90_put_att(ncid,varid(3),'units','-')
       iret=nf90_put_att(ncid,varid(3),'scale_factor',1)
       iret=nf90_put_att(ncid,varid(3),'add_offset',0)
       iret=nf90_put_att(ncid,varid(3),'valid_min',1)
       iret=nf90_put_att(ncid,varid(3),'valid_max',999)
       iret=nf90_put_att(ncid,varid(3),'_FillValue',nf90_fill_short)
       iret=nf90_put_att(ncid,varid(3),'content','TX')
       iret=nf90_put_att(ncid,varid(3),'associates','time station')
     END IF
     IF (flagll) THEN
       !  longitude
       iret=nf90_def_var(ncid, 'longitude', nf90_float, (/dimid(two),dimid(one)/), varid(4))
       CALL check_err(iret,29)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(4), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(4),'long_name','longitude')
       iret=nf90_put_att(ncid,varid(4),'standard_name','longitude')
       iret=nf90_put_att(ncid,varid(4),'globwave_name','longitude')
       iret=nf90_put_att(ncid,varid(4),'units','degree_east')
       iret=nf90_put_att(ncid,varid(4),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(4),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(4),'valid_min',-180.0)
       iret=nf90_put_att(ncid,varid(4),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(4),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(4),'content','TX')
       iret=nf90_put_att(ncid,varid(4),'associates','time station')
       !  latitude
       iret=nf90_def_var(ncid, 'latitude', nf90_float, (/dimid(two),dimid(one)/), varid(5))
       CALL check_err(iret,30)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(5), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(5),'long_name','latitude')
       iret=nf90_put_att(ncid,varid(5),'standard_name','latitude')
       iret=nf90_put_att(ncid,varid(5),'globwave_name','latitude')
       iret=nf90_put_att(ncid,varid(5),'units','degree_north')
       iret=nf90_put_att(ncid,varid(5),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(5),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(5),'valid_min',-90.0)
       iret=nf90_put_att(ncid,varid(5),'valid_max',180.)
       iret=nf90_put_att(ncid,varid(5),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(5),'content','TX')
       iret=nf90_put_att(ncid,varid(5),'associates','time station')
     ELSE
       !  longitude
       iret=nf90_def_var(ncid, 'x', nf90_float, (/dimid(two),dimid(one)/), varid(4))
       CALL check_err(iret,31)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(4), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(4),'long_name','x')
       iret=nf90_put_att(ncid,varid(4),'standard_name','x')
       iret=nf90_put_att(ncid,varid(4),'globwave_name','x')
       iret=nf90_put_att(ncid,varid(4),'units','km')
       iret=nf90_put_att(ncid,varid(4),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(4),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(4),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(4),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(4),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(4),'content','TX')
       iret=nf90_put_att(ncid,varid(4),'associates','time station')
       !  latitude
       iret=nf90_def_var(ncid, 'y', nf90_float, (/dimid(two),dimid(one)/), varid(5))
       CALL check_err(iret,32)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(5), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(5),'long_name','y')
       iret=nf90_put_att(ncid,varid(5),'standard_name','y')
       iret=nf90_put_att(ncid,varid(5),'globwave_name','y')
       iret=nf90_put_att(ncid,varid(5),'units','km')
       iret=nf90_put_att(ncid,varid(5),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(5),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(5),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(5),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(5),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(5),'content','TX')
       iret=nf90_put_att(ncid,varid(5),'associates','time station')
     END IF
     ! Process FREQ and DIR dimension values
     freq(1:nk)=sig(1:nk)*tpiinv
     freq1(1:nk)=freq(1:nk)-0.5*(freq(1:nk)-(freq(1:nk)/xfr))
     freq2(1:nk)=freq(1:nk)+0.5*(-freq(1:nk)+(freq(1:nk)*xfr))
     freq1(1)=sig(1)*tpiinv
     freq2(nk)=sig(nk)*tpiinv
     dir(1:nth)=mod(450-thd(1:nth),360.)
     !
     ! ... ITYPE = 1 AND OTYPE = 2
     !
     IF (itype.EQ.1 .AND. otype.EQ.2) THEN
       !
       !     Define specifics dimensions
       !
       iret = nf90_def_dim(ncid, 'frequency', dimln(4), dimid(4))
       CALL check_err(iret,33)
       !
       !     define specifics variables
       !
       !  frequency
       iret=nf90_def_var(ncid, 'frequency', nf90_float, dimid(4), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','frequency of center band')
       iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_frequency')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','frequency')
       iret=nf90_put_att(ncid,varid(6),'units','s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'axis','Y')
       !d
       iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','depth')
       iret=nf90_put_att(ncid,varid(7),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(7),'units','m')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
       !Ust
       iret=nf90_def_var(ncid, 'ust', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','friction velocity')
       iret=nf90_put_att(ncid,varid(8),'standard_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(8),'units','m s-1')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(9),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'units','m s-1')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(10),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(10),'units','degree')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(10),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(10),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !f/fp
       iret=nf90_def_var(ncid, 'ffp', nf90_float, (/ dimid(4),dimid(two),dimid(one) /), varid(11))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name','ffp')
       iret=nf90_put_att(ncid,varid(11),'standard_name','ffp')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','ffp')
       iret=nf90_put_att(ncid,varid(11),'units','1')
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TXY')
       iret=nf90_put_att(ncid,varid(11),'associates','time station frequency')
       !F
       iret=nf90_def_var(ncid, 'f', nf90_float, (/ dimid(4),dimid(two),dimid(one) /), varid(12))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(22), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'long_name','f')
       iret=nf90_put_att(ncid,varid(12),'standard_name','f')
       iret=nf90_put_att(ncid,varid(12),'globwave_name','f')
       iret=nf90_put_att(ncid,varid(12),'units','-')
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',1000.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TXY')
       iret=nf90_put_att(ncid,varid(12),'associates','time station frequency')
       !th1m
       iret=nf90_def_var(ncid, 'th1m', nf90_float, (/ dimid(4),dimid(two),dimid(one) /), varid(13))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'long_name','mean wave direction from spectral moments')
       iret=nf90_put_att(ncid,varid(13),'standard_name','mean_wave_direction')
       iret=nf90_put_att(ncid,varid(13),'globwave_name','mean_wave_direction')
       iret=nf90_put_att(ncid,varid(13),'units','degree')
       iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(13),'content','TXY')
       iret=nf90_put_att(ncid,varid(13),'associates','time station frequency')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(13),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(13),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !sth1m
       iret=nf90_def_var(ncid, 'sth1m', nf90_float,(/ dimid(4),dimid(two),dimid(one) /), varid(14))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(14),'long_name','directional spread from spectral moments')
       iret=nf90_put_att(ncid,varid(14),'standard_name','mean_wave_spreading')
       iret=nf90_put_att(ncid,varid(14),'globwave_name','mean_wave_spreading')
       iret=nf90_put_att(ncid,varid(14),'units','degree')
       iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(14),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(14),'content','TXY')
       iret=nf90_put_att(ncid,varid(14),'associates','time station frequency')
       !alpha
       iret=nf90_def_var(ncid, 'alpha', nf90_float, (/ dimid(4),dimid(two),dimid(one) /), varid(15))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(15),'long_name','spectral intensity coefficient')
       iret=nf90_put_att(ncid,varid(15),'standard_name','spectral_intensity_coefficient')
       iret=nf90_put_att(ncid,varid(15),'globwave_name','spectral_intensity_coefficient')
       iret=nf90_put_att(ncid,varid(15),'units','-')
       iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(15),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(15),'content','TXY')
       iret=nf90_put_att(ncid,varid(15),'associates','time station frequency')
       ! Add values in netCDF file
       iret=nf90_enddef(ncid)
       CALL check_err(iret,34)
       iret=nf90_put_var(ncid,varid(6),freq(1:nk))
       CALL check_err(iret,35)
       !
       ! ... ITYPE = 1 AND OTYPE = 3
       !
     ELSE IF (itype.EQ.1 .AND. otype.EQ.3) THEN
       !
       !     Define specifics dimensions
       !
       iret = nf90_def_dim(ncid, 'frequency', dimln(4), dimid(4))
       CALL check_err(iret,36)
       iret = nf90_def_dim(ncid, 'direction', dimln(5), dimid(5))
       CALL check_err(iret,37)
       !
       !     define specifics variables
       !
       !frequency
       iret=nf90_def_var(ncid, 'frequency', nf90_float, (/dimid(4)/), varid(6))
       CALL check_err(iret,38)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','frequency of center band')
       iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_frequency')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','frequency')
       iret=nf90_put_att(ncid,varid(6),'units','s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'axis','Y')
       !frequency1
       iret=nf90_def_var(ncid, 'frequency1', nf90_float, (/dimid(4)/), varid(7))
       CALL check_err(iret,39)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','frequency of lower band')
       iret=nf90_put_att(ncid,varid(7),'standard_name','frequency_of_lower_band')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','frequency_lower_band')
       iret=nf90_put_att(ncid,varid(7),'units','s-1')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','Y')
       iret=nf90_put_att(ncid,varid(7),'associates','frequency')
       !frequency2
       iret=nf90_def_var(ncid, 'frequency2', nf90_float, (/dimid(4)/), varid(8))
       CALL check_err(iret,40)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','frequency of upper band')
       iret=nf90_put_att(ncid,varid(8),'standard_name','frequency_of_upper_band')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','frequency_upper_band')
       iret=nf90_put_att(ncid,varid(8),'units','s-1')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','Y')
       iret=nf90_put_att(ncid,varid(8),'associates','frequency')
       !direction
       iret=nf90_def_var(ncid, 'direction', nf90_float, (/dimid(5)/), varid(9))
       CALL check_err(iret,41)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','sea surface wave to direction')
       iret=nf90_put_att(ncid,varid(9),'standard_name','sea_surface_wave_to_direction')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','direction')
       iret=nf90_put_att(ncid,varid(9),'units','degree')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'axis','Z')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(9),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(9),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Efth
       IF (ncvartype.LE.3) THEN
         iret=nf90_def_var(ncid,'efth',nf90_short,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(10))
       ELSE
         iret=nf90_def_var(ncid,'efth',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(10))
       END IF
       CALL check_err(iret,42)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name',&
            'sea surface wave directional variance spectral density')
       IF (ncvartype.LE.3) THEN
         iret=nf90_put_att(ncid,varid(10),'standard_name',&
              'base_ten_logarithm_of_sea_surface_wave_directional_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'globwave_name','directional_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'units','log10(m2 s rad-1 +1E-12)')
         iret=nf90_put_att(ncid,varid(10),'scale_factor',0.0004)
         iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
         iret=nf90_put_att(ncid,varid(10),'valid_max',1.e20)
         iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_short)
       ELSE
         iret=nf90_put_att(ncid,varid(10),'standard_name',&
              'sea_surface_wave_directional_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'globwave_name','directional_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'units','m2 s rad-1')
         iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
         iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
         iret=nf90_put_att(ncid,varid(10),'valid_max',1.e20)
         iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       END IF
       iret=nf90_put_att(ncid,varid(10),'content','TXYZ')
       iret=nf90_put_att(ncid,varid(10),'associates','time station frequency direction')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(10),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(10),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !d
       IF (ncvartype.LE.3) THEN
         iret=nf90_def_var(ncid, 'dpt', nf90_short, (/ dimid(two),dimid(one) /), varid(11))
       ELSE
         iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(11))
       END IF
       CALL check_err(iret,43)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name','depth')
       iret=nf90_put_att(ncid,varid(11),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(11),'units','m')
       IF (ncvartype.LE.3) THEN
         iret=nf90_put_att(ncid,varid(11),'scale_factor',0.5)
         iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(11),'valid_min',-200)
         iret=nf90_put_att(ncid,varid(11),'valid_max',200000)
         iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_short)
       ELSE
         iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
         iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(11),'valid_min',-100.)
         iret=nf90_put_att(ncid,varid(11),'valid_max',10000.)
         iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       END IF
       iret=nf90_put_att(ncid,varid(11),'content','TX')
       iret=nf90_put_att(ncid,varid(11),'associates','time station')
       !U10
       IF (ncvartype.LE.3) THEN
         iret=nf90_def_var(ncid, 'wnd', nf90_short, (/ dimid(two),dimid(one) /), varid(12))
       ELSE
         iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(12))
       END IF
       CALL check_err(iret,44)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(12),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(12),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(12),'units','m s-1')
       IF (ncvartype.LE.3) THEN
         iret=nf90_put_att(ncid,varid(12),'scale_factor',0.1)
         iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(12),'valid_min',0)
         iret=nf90_put_att(ncid,varid(12),'valid_max',1000)
         iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_short)
       ELSE
         iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
         iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(12),'valid_min',0.)
         iret=nf90_put_att(ncid,varid(12),'valid_max',100.)
         iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
       END IF
       iret=nf90_put_att(ncid,varid(12),'content','TX')
       iret=nf90_put_att(ncid,varid(12),'associates','time station')
       !Dir
       IF (ncvartype.LE.3) THEN
         iret=nf90_def_var(ncid, 'wnddir', nf90_short, (/ dimid(two),dimid(one) /), varid(13))
       ELSE
         iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(13))
       END IF
       CALL check_err(iret,45)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(13),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(13),'globwave_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(13),'units','degree')
       IF (ncvartype.LE.3) THEN
         iret=nf90_put_att(ncid,varid(13),'scale_factor',0.1)
         iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(13),'valid_min',0)
         iret=nf90_put_att(ncid,varid(13),'valid_max',3600)
         iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_short)
       ELSE
         iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
         iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(13),'valid_min',0.)
         iret=nf90_put_att(ncid,varid(13),'valid_max',360.)
         iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_float)
       END IF
       iret=nf90_put_att(ncid,varid(13),'content','TX')
       iret=nf90_put_att(ncid,varid(13),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(13),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(13),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Uc
       IF (ncvartype.LE.3) THEN
         iret=nf90_def_var(ncid, 'cur', nf90_short, (/ dimid(two),dimid(one) /), varid(14))
       ELSE
         iret=nf90_def_var(ncid, 'cur', nf90_float, (/ dimid(two),dimid(one) /), varid(14))
       END IF
       CALL check_err(iret,46)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(14),'long_name','sea water speed')
       iret=nf90_put_att(ncid,varid(14),'standard_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(14),'globwave_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(14),'units','m s-1')
       IF (ncvartype.LE.3) THEN
         iret=nf90_put_att(ncid,varid(14),'scale_factor',0.1)
         iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(14),'valid_min',0)
         iret=nf90_put_att(ncid,varid(14),'valid_max',1000)
         iret=nf90_put_att(ncid,varid(14),'_FillValue',nf90_fill_short)
       ELSE
         iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
         iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(14),'valid_min',0.)
         iret=nf90_put_att(ncid,varid(14),'valid_max',100.)
         iret=nf90_put_att(ncid,varid(14),'_FillValue',nf90_fill_float)
       END IF
       iret=nf90_put_att(ncid,varid(14),'content','TX')
       iret=nf90_put_att(ncid,varid(14),'associates','time station')
       !Dir
       IF (ncvartype.LE.3) THEN
         iret=nf90_def_var(ncid, 'curdir', nf90_short, (/ dimid(two),dimid(one) /), varid(15))
       ELSE
         iret=nf90_def_var(ncid, 'curdir', nf90_float, (/ dimid(two),dimid(one) /), varid(15))
       END IF
       CALL check_err(iret,47)
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(15),'long_name','direction from of sea water velocity')
       iret=nf90_put_att(ncid,varid(15),'standard_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(15),'globwave_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(15),'units','degree')
       IF (ncvartype.LE.3) THEN
         iret=nf90_put_att(ncid,varid(15),'scale_factor',0.1)
         iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(15),'valid_min',0)
         iret=nf90_put_att(ncid,varid(15),'valid_max',3600)
         iret=nf90_put_att(ncid,varid(15),'_FillValue',nf90_fill_short)
       ELSE
         iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
         iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
         iret=nf90_put_att(ncid,varid(15),'valid_min',0.)
         iret=nf90_put_att(ncid,varid(15),'valid_max',360.)
         iret=nf90_put_att(ncid,varid(15),'_FillValue',nf90_fill_float)
       END IF
       iret=nf90_put_att(ncid,varid(15),'content','TX')
       iret=nf90_put_att(ncid,varid(15),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(15),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(15),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       ! Add values in netCDF file
       iret=nf90_enddef(ncid)
       CALL check_err(iret,48)
       iret=nf90_put_var(ncid,varid(6),freq(1:nk))
       CALL check_err(iret,49)
       iret=nf90_put_var(ncid,varid(7),freq1(1:nk))
       CALL check_err(iret,50)
       iret=nf90_put_var(ncid,varid(8),freq2(1:nk))
       CALL check_err(iret,51)
       iret=nf90_put_var(ncid,varid(9),dir(1:nth))
       CALL check_err(iret,52)
       !
       ! ... ITYPE = 1 AND OTYPE = 4
       !
     ELSE IF (itype.EQ.1 .AND. otype.EQ.4) THEN
       !
       !     Define specifics dimensions
       !
       iret = nf90_def_dim(ncid, 'npart', dimln(4), dimid(4))
       CALL check_err(iret,53)
       !
       !     define specifics variables
       !
       !npart
       iret=nf90_def_var(ncid, 'npart', nf90_int, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','npart')
       iret=nf90_put_att(ncid,varid(6),'standard_name','npart')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','npart')
       iret=nf90_put_att(ncid,varid(6),'units','1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_int)
       iret=nf90_put_att(ncid,varid(6),'axis','Y')
       !d
       iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','depth')
       iret=nf90_put_att(ncid,varid(7),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(7),'units','m')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(8),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(8),'units','m s-1')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(9),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(9),'units','degree')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(9),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(9),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Uc
       iret=nf90_def_var(ncid, 'cur', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','sea water speed')
       iret=nf90_put_att(ncid,varid(10),'standard_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(10),'units','m s-1')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'curdir', nf90_float, (/ dimid(two),dimid(one) /), varid(11))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name',' direction from of sea water velocity')
       iret=nf90_put_att(ncid,varid(11),'standard_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(11),'units','degree')
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TX')
       iret=nf90_put_att(ncid,varid(11),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(11),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(11),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Hs
       iret=nf90_def_var(ncid, 'hs', nf90_float, (/dimid(4),dimid(two),dimid(one)/),varid(12))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'long_name','spectral estimate of significant wave height')
       iret=nf90_put_att(ncid,varid(12),'standard_name','sea_surface_wave_significant_height')
       iret=nf90_put_att(ncid,varid(12),'globwave_name','significant_wave_height')
       iret=nf90_put_att(ncid,varid(12),'units','m')
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TXY')
       iret=nf90_put_att(ncid,varid(12),'associates','time station npart')
       !Tp
       iret=nf90_def_var(ncid, 'tp', nf90_float,(/dimid(4),dimid(two),dimid(one)/),varid(13))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'long_name','dominant_wave_period')
       iret=nf90_put_att(ncid,varid(13),'standard_name','dominant_wave_period')
       iret=nf90_put_att(ncid,varid(13),'globwave_name','dominant_wave_period')
       iret=nf90_put_att(ncid,varid(13),'units','s')
       iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(13),'content','TXY')
       iret=nf90_put_att(ncid,varid(13),'associates','time station npart')
       !L
       iret=nf90_def_var(ncid, 'lp', nf90_float, (/dimid(4),dimid(two),dimid(one)/),varid(14))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(14),'long_name','peak wave length')
       iret=nf90_put_att(ncid,varid(14),'standard_name','peak_wave_length')
       iret=nf90_put_att(ncid,varid(14),'globwave_name','peak_wave_length')
       iret=nf90_put_att(ncid,varid(14),'units','m')
       iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(14),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(14),'content','TXY')
       iret=nf90_put_att(ncid,varid(14),'associates','time station npart')
       !th1m
       iret=nf90_def_var(ncid, 'th1m', nf90_float, (/dimid(4),dimid(two),dimid(one)/),varid(15))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(15),'long_name','mean wave direction from spectral moments')
       iret=nf90_put_att(ncid,varid(15),'standard_name','mean_wave_direction')
       iret=nf90_put_att(ncid,varid(15),'globwave_name','mean_wave_direction')
       iret=nf90_put_att(ncid,varid(15),'units','degree')
       iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(15),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(15),'content','TXY')
       iret=nf90_put_att(ncid,varid(15),'associates','time station npart')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(15),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(15),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !sth1m
       iret=nf90_def_var(ncid, 'sth1m', nf90_float,(/dimid(4),dimid(two),dimid(one)/),varid(16))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(16), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(16),'long_name','directional spread from spectral moments')
       iret=nf90_put_att(ncid,varid(16),'standard_name','mean_wave_spreading')
       iret=nf90_put_att(ncid,varid(16),'globwave_name','mean_wave_spreading')
       iret=nf90_put_att(ncid,varid(16),'units','degree')
       iret=nf90_put_att(ncid,varid(16),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(16),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(16),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(16),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(16),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(16),'content','TXY')
       iret=nf90_put_att(ncid,varid(16),'associates','time station npart')
       !ws
       iret=nf90_def_var(ncid, 'ws', nf90_float,(/dimid(4),dimid(two),dimid(one)/),varid(17))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(17), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(17),'long_name','wind sea fraction')
       iret=nf90_put_att(ncid,varid(17),'standard_name','wind_sea_fraction')
       iret=nf90_put_att(ncid,varid(17),'globwave_name','wind_sea_fraction')
       iret=nf90_put_att(ncid,varid(17),'units','%')
       iret=nf90_put_att(ncid,varid(17),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(17),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(17),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(17),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(17),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(17),'content','TXY')
       iret=nf90_put_att(ncid,varid(17),'associates','time station npart')
       !TM10
       iret=nf90_def_var(ncid, 'tm10', nf90_float,(/dimid(4),dimid(2),dimid(1)/),varid(18))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(18), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(18),'long_name','mean wave period from spectral moments (-1,0)')
       iret=nf90_put_att(ncid,varid(18),'standard_name','mean_wave_period_tm10')
       iret=nf90_put_att(ncid,varid(18),'globwave_name','mean_wave_period_tm10')
       iret=nf90_put_att(ncid,varid(18),'units','seconds')
       iret=nf90_put_att(ncid,varid(18),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(18),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(18),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(18),'valid_max',30.)
       iret=nf90_put_att(ncid,varid(18),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(18),'content','TXY')
       iret=nf90_put_att(ncid,varid(18),'associates','time station npart')
       !T01
       iret=nf90_def_var(ncid, 't01', nf90_float,(/dimid(4),dimid(2),dimid(1)/),varid(19))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(19), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(19),'long_name','mean wave period from spectral moments (0,1)')
       iret=nf90_put_att(ncid,varid(19),'standard_name','mean_wave_period_t01')
       iret=nf90_put_att(ncid,varid(19),'globwave_name','mean_wave_period_t01')
       iret=nf90_put_att(ncid,varid(19),'units','seconds')
       iret=nf90_put_att(ncid,varid(19),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(19),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(19),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(19),'valid_max',30.)
       iret=nf90_put_att(ncid,varid(19),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(19),'content','TXY')
       iret=nf90_put_att(ncid,varid(19),'associates','time station npart')
       !T02
       iret=nf90_def_var(ncid, 't02', nf90_float,(/dimid(4),dimid(2),dimid(1)/),varid(20))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(20), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(20),'long_name','mean wave period from spectral moments (0,2)')
       iret=nf90_put_att(ncid,varid(20),'standard_name','mean_wave_period_t02')
       iret=nf90_put_att(ncid,varid(20),'globwave_name','mean_wave_period_t02')
       iret=nf90_put_att(ncid,varid(20),'units','seconds')
       iret=nf90_put_att(ncid,varid(20),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(20),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(20),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(20),'valid_max',30.)
       iret=nf90_put_att(ncid,varid(20),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(20),'content','TXY')
       iret=nf90_put_att(ncid,varid(20),'associates','time station npart')
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,54)
       !
       ! ... ITYPE = 2 AND OTYPE = 1
       !
     ELSE IF (itype.EQ.2 .AND. otype.EQ.1) THEN
       !d
       iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','depth')
       iret=nf90_put_att(ncid,varid(6),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(6),'units','m')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'content','TX')
       iret=nf90_put_att(ncid,varid(6),'associates','time station')
       !Uc
       iret=nf90_def_var(ncid, 'cur', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','sea water speed')
       iret=nf90_put_att(ncid,varid(7),'standard_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(7),'units','m s-1')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'curdir', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','direction from of sea water velocity')
       iret=nf90_put_att(ncid,varid(8),'standard_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(8),'units','degree')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(8),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(8),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(9),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'units','m s-1')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(10),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(10),'units','degree')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(10),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(10),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !zeta_setup
 #ifdef W3_SETUP
       iret=nf90_def_var(ncid, 'wave_setup', nf90_float, (/ dimid(two),dimid(one) /), varid(11))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name','wave setup')
       iret=nf90_put_att(ncid,varid(11),'standard_name','wave_induced_setup')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','wave_induced_setup')
       iret=nf90_put_att(ncid,varid(11),'units','m')
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TX')
       iret=nf90_put_att(ncid,varid(11),'associates','time station')
 #endif
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,55)
       !
       ! ... ITYPE = 2 AND OTYPE = 2
       !
     ELSE IF (itype.EQ.2 .AND. otype.EQ.2) THEN
       !Hs
       iret=nf90_def_var(ncid, 'hs', nf90_float, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','spectral estimate of significant wave height')
       iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_significant_height')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','significant_wave_height')
       iret=nf90_put_att(ncid,varid(6),'units','m')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'content','TX')
       iret=nf90_put_att(ncid,varid(6),'associates','time station')
       !L
       iret=nf90_def_var(ncid, 'lm', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','mean wave length')
       iret=nf90_put_att(ncid,varid(7),'standard_name','mean_wave_length')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','mean_wave_length')
       iret=nf90_put_att(ncid,varid(7),'units','m')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
       !Tr
       iret=nf90_def_var(ncid, 'tr', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','mean period normalised by the relative frequency')
       iret=nf90_put_att(ncid,varid(8),'standard_name','mean_period_normalised_by_the_relative_frequency')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','mean period normalised by the relative frequency')
       iret=nf90_put_att(ncid,varid(8),'units','s')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !th1p
       iret=nf90_def_var(ncid, 'th1p', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','mean wave direction from spectral moments at spectral peak')
       iret=nf90_put_att(ncid,varid(9),'standard_name','dominant_wave_direction')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','dominant_wave_direction')
       iret=nf90_put_att(ncid,varid(9),'units','degree')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(9),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(9),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !sth1p
       iret=nf90_def_var(ncid, 'sth1p', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','directional spread at spectral peak')
       iret=nf90_put_att(ncid,varid(10),'standard_name','dominant_wave_spreading')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','dominant_wave_spreading')
       iret=nf90_put_att(ncid,varid(10),'units','degree')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
       !fp
       iret=nf90_def_var(ncid, 'fp', nf90_float, (/ dimid(two),dimid(one) /), varid(11))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name','  peak frequency (Fp=1/Tp)')
       iret=nf90_put_att(ncid,varid(11),'standard_name','dominant_wave_frequency')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','dominant_wave_frequency')
       iret=nf90_put_att(ncid,varid(11),'units','s-1')
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TX')
       iret=nf90_put_att(ncid,varid(11),'associates','time station')
       !th1m
       iret=nf90_def_var(ncid, 'th1m', nf90_float, (/ dimid(two),dimid(one) /), varid(12))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'standard_name','mean wave direction from spectral moments')
       iret=nf90_put_att(ncid,varid(12),'standard_name','mean_wave_direction')
       iret=nf90_put_att(ncid,varid(12),'globwave_name','mean_wave_direction')
       iret=nf90_put_att(ncid,varid(12),'units','degree')
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TX')
       iret=nf90_put_att(ncid,varid(12),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(12),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(12),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !sth1m
       iret=nf90_def_var(ncid, 'sth1m', nf90_float, (/ dimid(two),dimid(one) /), varid(13))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'long_name','directional spread from spectral moments')
       iret=nf90_put_att(ncid,varid(13),'standard_name','mean_wave_spreading')
       iret=nf90_put_att(ncid,varid(13),'globwave_name','mean_wave_spreading')
       iret=nf90_put_att(ncid,varid(13),'units','degree')
       iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(13),'content','TX')
       iret=nf90_put_att(ncid,varid(13),'associates','time station')
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,56)
       !
       ! ... ITYPE = 2 AND OTYPE = 3
       !
     ELSE IF (itype.EQ.2 .AND. otype.EQ.3) THEN
       !Ust
       iret=nf90_def_var(ncid, 'ust', nf90_float, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','friction velocity')
       iret=nf90_put_att(ncid,varid(6),'standard_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(6),'units','m s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'content','TX')
       iret=nf90_put_att(ncid,varid(6),'associates','time station')
       !Efst
       iret=nf90_def_var(ncid, 'efst', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name',                     &
            'nondimensionalized using surface elevation variance spectrum')
       iret=nf90_put_att(ncid,varid(7),'standard_name','sea_surface_wave_variance_spectral_density')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','variance_spectral_density')
       iret=nf90_put_att(ncid,varid(7),'units','-')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(7),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(7),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !fpst
       iret=nf90_def_var(ncid, 'fpst', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','nondimensionalized using peak frequency (Fp=1/Tp)')
       iret=nf90_put_att(ncid,varid(8),'standard_name','dominant_wave_frequency')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','dominant_wave_frequency')
       iret=nf90_put_att(ncid,varid(8),'units','-')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !Cd
       iret=nf90_def_var(ncid, 'cd', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','drag coefficient')
       iret=nf90_put_att(ncid,varid(9),'standard_name','drag_coefficient')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','drag_coefficient')
       iret=nf90_put_att(ncid,varid(9),'units','*1000')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !alpha
       iret=nf90_def_var(ncid, 'alpha', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','alpha')
       iret=nf90_put_att(ncid,varid(10),'standard_name','alpha')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','alpha')
       iret=nf90_put_att(ncid,varid(10),'units','*100')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,57)
       !
       ! ... ITYPE = 2 AND OTYPE = 4
       !
     ELSE IF (itype.EQ.2 .AND. otype.EQ.4) THEN
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(6),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(6),'units','m s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'content','TX')
       iret=nf90_put_att(ncid,varid(6),'associates','time station')
       !Efst
       iret=nf90_def_var(ncid, 'efst', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name',                    &
            'nondimensionalized using surface elevation variance spectrum')
       iret=nf90_put_att(ncid,varid(7),'standard_name','sea_surface_wave_variance_spectral_density')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','variance_spectral_density')
       iret=nf90_put_att(ncid,varid(7),'units','-')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(7),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(7),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !fpst
       iret=nf90_def_var(ncid, 'fpst', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name',                    &
            'nondimensionalized using peak frequency (Fp=1/Tp)')
       iret=nf90_put_att(ncid,varid(8),'standard_name','dominant_wave_frequency')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','dominant_wave_frequency')
       iret=nf90_put_att(ncid,varid(8),'units','-')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !Cd
       iret=nf90_def_var(ncid, 'cd', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','drag coefficient')
       iret=nf90_put_att(ncid,varid(9),'standard_name','drag_coefficient')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','drag_coefficient')
       iret=nf90_put_att(ncid,varid(9),'units','*1000')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !alpha
       iret=nf90_def_var(ncid, 'alpha', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','spectral intensity coefficient')
       iret=nf90_put_att(ncid,varid(10),'standard_name','spectral_intensity_coefficient')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','spectral_intensity_coefficient')
       iret=nf90_put_att(ncid,varid(10),'units','*100')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,58)
       !
       ! ... ITYPE = 2 AND OTYPE = 5
       !
     ELSE IF (itype.EQ.2 .AND. otype.EQ.5) THEN
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(6),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(6),'units','m s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'content','TX')
       iret=nf90_put_att(ncid,varid(6),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(7),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(7),'units','degree')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(7),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(7),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Hs
       iret=nf90_def_var(ncid, 'hs', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','spectral estimate of significant wave height')
       iret=nf90_put_att(ncid,varid(8),'standard_name','sea_surface_wave_significant_height')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','significant_wave_height')
       iret=nf90_put_att(ncid,varid(8),'units','m')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !Hsst
       iret=nf90_def_var(ncid, 'hsst', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name',                    &
            'nondimensionalized using spectral estimate of significant wave height')
       iret=nf90_put_att(ncid,varid(9),'standard_name','sea_surface_wave_significant_height')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','significant_wave_height')
       iret=nf90_put_att(ncid,varid(9),'units','-')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !cp/U
       iret=nf90_def_var(ncid, 'cpu', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','phase speed at peak frequency on friction velocity')
       iret=nf90_put_att(ncid,varid(10),'standard_name','peak_wave_age')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','peak_wave_age')
       iret=nf90_put_att(ncid,varid(10),'units','-')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
       !cm/U
       iret=nf90_def_var(ncid, 'cmu', nf90_float, (/ dimid(two),dimid(one) /), varid(11))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name','phase speed at mean frequency on friction velocity')
       iret=nf90_put_att(ncid,varid(11),'standard_name','mean_wave_age')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','mean_wave_age')
       iret=nf90_put_att(ncid,varid(11),'units','-')
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TX')
       iret=nf90_put_att(ncid,varid(11),'associates','time station')
       !Dt
       iret=nf90_def_var(ncid, 'ast', nf90_float, (/ dimid(two),dimid(one) /), varid(12))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'long_name','air sea temperature difference')
       iret=nf90_put_att(ncid,varid(12),'standard_name','air_sea_temperature_difference')
       iret=nf90_put_att(ncid,varid(12),'globwave_name','air_sea_temperature_difference')
       iret=nf90_put_att(ncid,varid(12),'units','degree')
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TX')
       iret=nf90_put_att(ncid,varid(12),'associates','time station')
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,59)
       !
       ! ... ITYPE = 2 AND OTYPE = 6
       !
     ELSE IF (itype.EQ.2 .AND. otype.EQ.6) THEN
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(6),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(6),'units','m s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'content','TX')
       iret=nf90_put_att(ncid,varid(6),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(7),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(7),'units','degree')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(7),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(7),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Hs
       iret=nf90_def_var(ncid, 'hs', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','spectral estimate of significant wave height')
       iret=nf90_put_att(ncid,varid(8),'standard_name','sea_surface_wave_significant_height')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','significant_wave_height')
       iret=nf90_put_att(ncid,varid(8),'units','m')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !Tp
       iret=nf90_def_var(ncid, 'tp', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','dominant wave period')
       iret=nf90_put_att(ncid,varid(9),'standard_name','dominant_wave_period')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','dominant_wave_period')
       iret=nf90_put_att(ncid,varid(9),'units','s')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       ! NF90_ENDDEF function
       iret=nf90_enddef(ncid)
       CALL check_err(iret,60)
       !
       ! ... ITYPE = 3 AND OTYPE = 2
       !
     ELSE IF (itype.EQ.3 .AND. otype.EQ.2) THEN
       !
       !     Define specifics dimensions
       !
       iret = nf90_def_dim(ncid, 'frequency', dimln(4), dimid(4))
       CALL check_err(iret,61)
       !
       !     define specifics variables
       !
       !  frequency / frequencyst / ffp
       IF (iscale.EQ.0) THEN
         iret=nf90_def_var(ncid, 'frequency', nf90_float, dimid(4), varid(6))
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_def_var(ncid, 'frequencyst', nf90_float, dimid(4), varid(6))
       ELSE
         iret=nf90_def_var(ncid, 'ffp', nf90_float, dimid(4), varid(6))
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','frequency of center band')
       iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_frequency')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','frequency')
       iret=nf90_put_att(ncid,varid(6),'units','s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'axis','Y')
       !d
       iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','depth')
       iret=nf90_put_att(ncid,varid(7),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(7),'units','m')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
       !Ust
       iret=nf90_def_var(ncid, 'ust', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','friction velocity')
       iret=nf90_put_att(ncid,varid(8),'standard_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(8),'units','m s-1')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(9),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'units','m s-1')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !Ef / Efst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'ef', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(10))
         iret=nf90_put_att(ncid,varid(10),'long_name','surface elevation variance spectrum')
         iret=nf90_put_att(ncid,varid(10),'standard_name','sea_surface_wave_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'globwave_name','variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'units','m2 s')
       ELSE
         iret=nf90_def_var(ncid, 'efst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(10))
         iret=nf90_put_att(ncid,varid(10),'long_name',                 &
              'nondimensionalized using surface elevation variance spectrum')
         iret=nf90_put_att(ncid,varid(10),'standard_name','sea_surface_wave_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'globwave_name','variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(10),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(10),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(10),'associates','time station ffp')
       END IF
       !Sin / Sinst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'sin', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(11))
         iret=nf90_put_att(ncid,varid(11),'long_name','wind input source term')
         iret=nf90_put_att(ncid,varid(11),'standard_name','wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'globwave_name','wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'sinst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(11))
         iret=nf90_put_att(ncid,varid(11),'long_name',                 &
              'nondimensionalized using wind input source term')
         iret=nf90_put_att(ncid,varid(11),'standard_name','wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'globwave_name','wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(11),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(11),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(11),'associates','time station ffp')
       END IF
       !Snl / Snlst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'snl', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(12))
         iret=nf90_put_att(ncid,varid(12),'long_name','nonlinear 4 wave source term')
         iret=nf90_put_att(ncid,varid(12),'standard_name','nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'globwave_name','nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'snlst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(12))
         iret=nf90_put_att(ncid,varid(12),'long_name',                 &
              'nondimensionalized using nonlinear 4 wave source term')
         iret=nf90_put_att(ncid,varid(12),'standard_name','nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'globwave_name','nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(12),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(12),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(12),'associates','time station ffp')
       END IF
       !Sds / Sdsst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'sds', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(13))
         iret=nf90_put_att(ncid,varid(13),'long_name','wave breaking source term')
         iret=nf90_put_att(ncid,varid(13),'standard_name','wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'globwave_name','wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'sdsst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(13))
         iret=nf90_put_att(ncid,varid(13),'long_name',                 &
              'nondimensionalized using wave breaking source term')
         iret=nf90_put_att(ncid,varid(13),'standard_name','wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'globwave_name','wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(13),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(13),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(13),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(13),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(13),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(13),'associates','time station ffp')
       END IF
       !Sbt / Sbtst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'sbt', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(14))
         iret=nf90_put_att(ncid,varid(14),'long_name','depth induced breaking source term')
         iret=nf90_put_att(ncid,varid(14),'standard_name','depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'globwave_name','depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'sbtst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(14))
         iret=nf90_put_att(ncid,varid(14),'long_name',                 &
              'nondimensionalized using depth induced breaking source term')
         iret=nf90_put_att(ncid,varid(14),'standard_name','depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'globwave_name','depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(14),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(14),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(14),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(14),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(14),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(14),'associates','time station ffp')
       END IF
       !Sice / Sicest
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'sice', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(15))
         iret=nf90_put_att(ncid,varid(15),'long_name','wave-ice interactions source term')
         iret=nf90_put_att(ncid,varid(15),'standard_name','wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'globwave_name','wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'sicest', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(15))
         iret=nf90_put_att(ncid,varid(15),'long_name','nondimensionalized using wave-ice interactions source term')
         iret=nf90_put_att(ncid,varid(15),'standard_name','wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'globwave_name','wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(15),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(15),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(15),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(15),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(15),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(15),'associates','time station ffp')
       END IF
       !Stot / Stotst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'stot', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(16))
         iret=nf90_put_att(ncid,varid(16),'long_name','total source term')
         iret=nf90_put_att(ncid,varid(16),'standard_name','total_source_term')
         iret=nf90_put_att(ncid,varid(16),'globwave_name','total_source_term')
         iret=nf90_put_att(ncid,varid(16),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'stotst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(16))
         iret=nf90_put_att(ncid,varid(16),'long_name','nondimensionalized using total source term')
         iret=nf90_put_att(ncid,varid(16),'standard_name','total_source_term')
         iret=nf90_put_att(ncid,varid(16),'globwave_name','total_source_term')
         iret=nf90_put_att(ncid,varid(16),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(16), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(16),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(16),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(16),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(16),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(16),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(16),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(16),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(16),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(16),'associates','time station ffp')
       END IF
       !  Add values in netCDF file
       iret=nf90_enddef(ncid)
       CALL check_err(iret,62)
       iret=nf90_put_var(ncid,varid(6),freq(1:nk))
       CALL check_err(iret,63)
       !
       ! ... ITYPE = 3 AND OTYPE = 3
       !
     ELSE IF (itype.EQ.3 .AND. otype.EQ.3) THEN
       !
       !     Define specifics dimensions
       !
       iret = nf90_def_dim(ncid, 'frequency', dimln(4), dimid(4))
       CALL check_err(iret,64)
       !
       !     define specifics variables
       !
       !  frequency / frequencyst / ffp
       IF (iscale.EQ.0) THEN
         iret=nf90_def_var(ncid, 'frequency', nf90_float, dimid(4), varid(6))
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_def_var(ncid, 'frequencyst', nf90_float, dimid(4), varid(6))
       ELSE
         iret=nf90_def_var(ncid, 'ffp', nf90_float, dimid(4), varid(6))
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','frequency of center band')
       iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_frequency')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','frequency')
       iret=nf90_put_att(ncid,varid(6),'units','s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'axis','Y')
       !d
       iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','depth')
       iret=nf90_put_att(ncid,varid(7),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(7),'units','m')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','TX')
       iret=nf90_put_att(ncid,varid(7),'associates','time station')
       !Ust
       iret=nf90_def_var(ncid, 'ust', nf90_float, (/ dimid(two),dimid(one) /), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','friction velocity')
       iret=nf90_put_att(ncid,varid(8),'standard_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(8),'units','m s-1')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','TX')
       iret=nf90_put_att(ncid,varid(8),'associates','time station')
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(9),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(9),'units','m s-1')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'content','TX')
       iret=nf90_put_att(ncid,varid(9),'associates','time station')
       !Ef / Efst
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'ef', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(10))
         iret=nf90_put_att(ncid,varid(10),'long_name','surface elevation variance spectrum')
         iret=nf90_put_att(ncid,varid(10),'standard_name','sea_surface_wave_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'globwave_name','variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'units','m2 s')
       ELSE
         iret=nf90_def_var(ncid, 'efst', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(10))
         iret=nf90_put_att(ncid,varid(10),'long_name',                 &
              'nondimensionalized using surface elevation variance spectrum')
         iret=nf90_put_att(ncid,varid(10),'standard_name','sea_surface_wave_variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'globwave_name','variance_spectral_density')
         iret=nf90_put_att(ncid,varid(10),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(10),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(10),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(10),'associates','time station ffp')
       END IF
       !Tini / Tinist
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'tini', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(11))
         iret=nf90_put_att(ncid,varid(11),'long_name','wind input source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(11),'standard_name','inverse_time_scales_wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'globwave_name','inverse_time_scales_wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'tinist', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(11))
         iret=nf90_put_att(ncid,varid(11),'long_name','nondimensionalized using wind input source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(11),'standard_name','inverse_time_scales_wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'globwave_name','inverse_time_scales_wind_input_source_term')
         iret=nf90_put_att(ncid,varid(11),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(11),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(11),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(11),'associates','time station ffp')
       END IF
       !Tnli / Tnlist
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'tnli', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(12))
         iret=nf90_put_att(ncid,varid(12),'long_name','nonlinear 4 wave source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(12),'standard_name','inverse_time_scales_nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'globwave_name','inverse_time_scales_nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'tnlist', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(12))
         iret=nf90_put_att(ncid,varid(12),'long_name','nondimensionalized using nonlinear 4 wave source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(12),'standard_name','inverse_time_scales_nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'globwave_name','inverse_time_scales_nonlinear_4_wave_source_term')
         iret=nf90_put_att(ncid,varid(12),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(12),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(12),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(12),'associates','time station ffp')
       END IF
       !Tdsi / Tdsist
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'tdsi', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(13))
         iret=nf90_put_att(ncid,varid(13),'long_name','wave breaking source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(13),'standard_name','inverse_time_scales_wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'globwave_name','inverse_time_scales_wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'tdsist', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(13))
         iret=nf90_put_att(ncid,varid(13),'long_name','nondimensionalized using wave breaking source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(13),'standard_name','inverse_time_scales_wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'globwave_name','inverse_time_scales_wave_breaking_source_term')
         iret=nf90_put_att(ncid,varid(13),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(13),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(13),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(13),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(13),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(13),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(13),'associates','time station ffp')
       END IF
       !Tbti / Tbtist
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'tbti', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(14))
         iret=nf90_put_att(ncid,varid(14),'long_name','depth induced breaking source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(14),'standard_name','inverse_time_scales_depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'globwave_name','inverse_time_scales_depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'tbtist', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(14))
         iret=nf90_put_att(ncid,varid(14),'long_name','nondimensionalized using depth induced breaking source term &
              normalised by Ef')
         iret=nf90_put_att(ncid,varid(14),'standard_name','inverse_time_scales_depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'globwave_name','inverse_time_scales_depth_induced_breaking_source_term')
         iret=nf90_put_att(ncid,varid(14),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(14),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(14),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(14),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(14),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(14),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(14),'associates','time station ffp')
       END IF
       !Ticei / Ticeist
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'ticei', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(15))
         iret=nf90_put_att(ncid,varid(15),'long_name','wave ice interactions source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(15),'standard_name','inverse_time_scales_wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'globwave_name','inverse_time_scales_wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'ticeist', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(15))
         iret=nf90_put_att(ncid,varid(15),'long_name','nondimensionalized using wave ice interactions source term &
              normalised by Ef')
         iret=nf90_put_att(ncid,varid(15),'standard_name','inverse_time_scales_wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'globwave_name','inverse_time_scales_wave_ice_interactions_source_term')
         iret=nf90_put_att(ncid,varid(15),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(15),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(15),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(15),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(15),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(15),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(15),'associates','time station ffp')
       END IF
       !Ttoti / Ttotist
       IF (iscale.EQ.0 .OR. iscale.EQ.3) THEN
         iret=nf90_def_var(ncid, 'ttoti', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(16))
         iret=nf90_put_att(ncid,varid(16),'long_name','total source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(16),'standard_name','inverse_time_scales_total_source_term')
         iret=nf90_put_att(ncid,varid(16),'globwave_name','inverse_time_scales_total_source_term')
         iret=nf90_put_att(ncid,varid(16),'units','m2')
       ELSE
         iret=nf90_def_var(ncid, 'ttotist', nf90_float,(/dimid(4),dimid(two),dimid(one)/), varid(16))
         iret=nf90_put_att(ncid,varid(16),'long_name','nondimensionalized using total source term normalised by Ef')
         iret=nf90_put_att(ncid,varid(16),'standard_name','inverse_time_scales_total_source_term')
         iret=nf90_put_att(ncid,varid(16),'globwave_name','inverse_time_scales_total_source_term')
         iret=nf90_put_att(ncid,varid(16),'units','-')
       END IF
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(16), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(16),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(16),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(16),'valid_min',-1.)
       iret=nf90_put_att(ncid,varid(16),'valid_max',1.)
       iret=nf90_put_att(ncid,varid(16),'_FillValue', nf90_fill_float)
       iret=nf90_put_att(ncid,varid(16),'content','TXY')
       IF (iscale.EQ.0) THEN
         iret=nf90_put_att(ncid,varid(16),'associates','time station frequency')
       ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.2 ) THEN
         iret=nf90_put_att(ncid,varid(16),'associates','time station frequencyst')
       ELSE
         iret=nf90_put_att(ncid,varid(16),'associates','time station ffp')
       END IF
       !  Add values in netCDF file
       iret=nf90_enddef(ncid)
       CALL check_err(iret,65)
       iret=nf90_put_var(ncid,varid(6),freq(1:nk))
       CALL check_err(iret,66)
       !
       ! ... ITYPE = 3 AND OTYPE = 4
       !
     ELSE IF (itype.EQ.3 .AND. otype.EQ.4) THEN
       !
       !     Define specifics dimensions
       !
       iret = nf90_def_dim(ncid, 'frequency', dimln(4), dimid(4))
       iret = nf90_def_dim(ncid, 'direction', dimln(5), dimid(5))
       CALL check_err(iret,67)
       !
       !     define specifics variables
       !
       !frequency
       iret=nf90_def_var(ncid, 'frequency', nf90_float, (/dimid(4)/), varid(6))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(6), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(6),'long_name','frequency of center band')
       iret=nf90_put_att(ncid,varid(6),'standard_name','sea_surface_wave_frequency')
       iret=nf90_put_att(ncid,varid(6),'globwave_name','frequency')
       iret=nf90_put_att(ncid,varid(6),'units','s-1')
       iret=nf90_put_att(ncid,varid(6),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(6),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(6),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(6),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(6),'axis','Y')
       !frequency1
       iret=nf90_def_var(ncid, 'frequency1', nf90_float, (/dimid(4)/), varid(7))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(7), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(7),'long_name','frequency of lower band')
       iret=nf90_put_att(ncid,varid(7),'standard_name','frequency_of_lower_band')
       iret=nf90_put_att(ncid,varid(7),'globwave_name','frequency_lower_band')
       iret=nf90_put_att(ncid,varid(7),'units','s-1')
       iret=nf90_put_att(ncid,varid(7),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(7),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(7),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(7),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(7),'content','Y')
       iret=nf90_put_att(ncid,varid(7),'associates','frequency')
       !frequency2
       iret=nf90_def_var(ncid, 'frequency2', nf90_float, (/dimid(4)/), varid(8))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(8), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(8),'long_name','frequency of upper band')
       iret=nf90_put_att(ncid,varid(8),'standard_name','frequency_of_upper_band')
       iret=nf90_put_att(ncid,varid(8),'globwave_name','frequency_upper_band')
       iret=nf90_put_att(ncid,varid(8),'units','s-1')
       iret=nf90_put_att(ncid,varid(8),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(8),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(8),'valid_max',10.)
       iret=nf90_put_att(ncid,varid(8),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(8),'content','Y')
       iret=nf90_put_att(ncid,varid(8),'associates','frequency')
       !direction
       iret=nf90_def_var(ncid, 'direction', nf90_float, (/dimid(5)/), varid(9))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(9), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(9),'long_name','sea surface wave to direction')
       iret=nf90_put_att(ncid,varid(9),'standard_name','sea_surface_wave_to_direction')
       iret=nf90_put_att(ncid,varid(9),'globwave_name','direction')
       iret=nf90_put_att(ncid,varid(9),'units','degree')
       iret=nf90_put_att(ncid,varid(9),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(9),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(9),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(9),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(9),'axis','Z')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(9),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(9),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !d
       iret=nf90_def_var(ncid, 'dpt', nf90_float, (/ dimid(two),dimid(one) /), varid(10))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(10), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(10),'long_name','depth')
       iret=nf90_put_att(ncid,varid(10),'standard_name','depth')
       iret=nf90_put_att(ncid,varid(10),'globwave_name','depth')
       iret=nf90_put_att(ncid,varid(10),'units','m')
       iret=nf90_put_att(ncid,varid(10),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(10),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(10),'valid_min',-100.)
       iret=nf90_put_att(ncid,varid(10),'valid_max',10000.)
       iret=nf90_put_att(ncid,varid(10),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(10),'content','TX')
       iret=nf90_put_att(ncid,varid(10),'associates','time station')
       !U10
       iret=nf90_def_var(ncid, 'wnd', nf90_float, (/ dimid(two),dimid(one) /), varid(11))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(11), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(11),'long_name','wind speed at 10m')
       iret=nf90_put_att(ncid,varid(11),'standard_name','wind_speed')
       iret=nf90_put_att(ncid,varid(11),'globwave_name','wind_speed')
       iret=nf90_put_att(ncid,varid(11),'units','m s-1')
       iret=nf90_put_att(ncid,varid(11),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(11),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(11),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(11),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(11),'content','TX')
       iret=nf90_put_att(ncid,varid(11),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'wnddir', nf90_float, (/ dimid(two),dimid(one) /), varid(12))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(12), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(12),'long_name','wind direction')
       iret=nf90_put_att(ncid,varid(12),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(12),'standard_name','wind_from_direction')
       iret=nf90_put_att(ncid,varid(12),'units','degree')
       iret=nf90_put_att(ncid,varid(12),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(12),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(12),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(12),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(12),'content','TX')
       iret=nf90_put_att(ncid,varid(12),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(12),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(12),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Uc
       iret=nf90_def_var(ncid, 'cur', nf90_float, (/ dimid(two),dimid(one) /), varid(13))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(13), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(13),'long_name','sea water speed')
       iret=nf90_put_att(ncid,varid(13),'standard_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(13),'globwave_name','sea_water_speed')
       iret=nf90_put_att(ncid,varid(13),'units','m s-1')
       iret=nf90_put_att(ncid,varid(13),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(13),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(13),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(13),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(13),'content','TX')
       iret=nf90_put_att(ncid,varid(13),'associates','time station')
       !Dir
       iret=nf90_def_var(ncid, 'curdir', nf90_float, (/ dimid(two),dimid(one) /), varid(14))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(14), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(14),'long_name','direction from of sea water velocity')
       iret=nf90_put_att(ncid,varid(14),'standard_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(14),'globwave_name','direction_of_sea_water_velocity')
       iret=nf90_put_att(ncid,varid(14),'units','degree')
       iret=nf90_put_att(ncid,varid(14),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(14),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(14),'valid_max',360.)
       iret=nf90_put_att(ncid,varid(14),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(14),'content','TX')
       iret=nf90_put_att(ncid,varid(14),'associates','time station')
 #ifdef W3_RTD
       IF ( flagunr ) THEN
         iret=nf90_put_att(ncid,varid(14),'direction_reference','True North')
       ELSE
         iret=nf90_put_att(ncid,varid(14),'direction_reference','Rotated Pole Grid North')
       END IF
 #endif
       !Ust
       iret=nf90_def_var(ncid, 'ust', nf90_float, (/ dimid(two),dimid(one) /), varid(15))
       IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(15), 1, 1, deflate)
       iret=nf90_put_att(ncid,varid(15),'long_name','friction velocity')
       iret=nf90_put_att(ncid,varid(15),'standard_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(15),'globwave_name','friction_velocity')
       iret=nf90_put_att(ncid,varid(15),'units','m s-1')
       iret=nf90_put_att(ncid,varid(15),'scale_factor',1.)
       iret=nf90_put_att(ncid,varid(15),'add_offset',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_min',0.)
       iret=nf90_put_att(ncid,varid(15),'valid_max',100.)
       iret=nf90_put_att(ncid,varid(15),'_FillValue',nf90_fill_float)
       iret=nf90_put_att(ncid,varid(15),'content','TX')
       iret=nf90_put_att(ncid,varid(15),'associates','time station')
       !Efth
       IF ( PRESENT(flsrce) ) THEN
         IF ( flsrce(1) )  THEN
           iret=nf90_def_var(ncid,'efth',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(16))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(16), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(16),'long_name',&
                'sea surface wave directional variance spectral density')
           iret=nf90_put_att(ncid,varid(16),'standard_name',&
                'sea_surface_wave_directional_variance_spectral_density')
           iret=nf90_put_att(ncid,varid(16),'globwave_name','directional_variance_spectral_density')
           iret=nf90_put_att(ncid,varid(16),'units','m2 s rad-1')
           iret=nf90_put_att(ncid,varid(16),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(16),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(16),'valid_min',0.)
           iret=nf90_put_att(ncid,varid(16),'valid_max',1.e20)
           iret=nf90_put_att(ncid,varid(16),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(16),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(16),'associates','time station frequency direction')
 #ifdef W3_RTD
           IF ( flagunr ) THEN
             iret=nf90_put_att(ncid,varid(16),'direction_reference','True North')
           ELSE
             iret=nf90_put_att(ncid,varid(16),'direction_reference','Rotated Pole Grid North')
           END IF
 #endif
         ENDIF
         !Swn
         IF ( flsrce(2) )  THEN
           iret=nf90_def_var(ncid,'sin',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(17))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(17), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(17),'long_name','wind input source term')
           iret=nf90_put_att(ncid,varid(17),'standard_name','wind_input_source_term')
           iret=nf90_put_att(ncid,varid(17),'globwave_name','wind_input_source_term')
           iret=nf90_put_att(ncid,varid(17),'units','m2 rad-1')
           iret=nf90_put_att(ncid,varid(17),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(17),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(17),'valid_min',-1.)
           iret=nf90_put_att(ncid,varid(17),'valid_max',1.)
           iret=nf90_put_att(ncid,varid(17),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(17),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(17),'associates','time station frequency direction')
 #ifdef W3_RTD
           iret=nf90_put_att(ncid,varid(17),'direction_reference','Rotated Pole Grid North')
 #endif
         ENDIF
         !Snl
         IF ( flsrce(3) )  THEN
           iret=nf90_def_var(ncid,'snl',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(18))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(18), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(18),'long_name','nonlinear 4 wave source term')
           iret=nf90_put_att(ncid,varid(18),'standard_name','nonlinear_4_wave_source_term')
           iret=nf90_put_att(ncid,varid(18),'globwave_name','nonlinear_4_wave_source_term')
           iret=nf90_put_att(ncid,varid(18),'units','m2 rad-1')
           iret=nf90_put_att(ncid,varid(18),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(18),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(18),'valid_min',-1.)
           iret=nf90_put_att(ncid,varid(18),'valid_max',1.)
           iret=nf90_put_att(ncid,varid(18),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(18),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(18),'associates','time station frequency direction')
 #ifdef W3_RTD
           iret=nf90_put_att(ncid,varid(18),'direction_reference','Rotated Pole Grid North')
 #endif
         ENDIF
         !Sds
         IF ( flsrce(4) )  THEN
           iret=nf90_def_var(ncid,'sds',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(19))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(19), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(19),'long_name','wave breaking source term')
           iret=nf90_put_att(ncid,varid(19),'standard_name','wave_breaking_source_term')
           iret=nf90_put_att(ncid,varid(19),'globwave_name','wave_breaking_source_term')
           iret=nf90_put_att(ncid,varid(19),'units','m2 rad-1')
           iret=nf90_put_att(ncid,varid(19),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(19),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(19),'valid_min',-1.)
           iret=nf90_put_att(ncid,varid(19),'valid_max',1.)
           iret=nf90_put_att(ncid,varid(19),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(19),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(19),'associates','time station frequency direction')
 #ifdef W3_RTD
           iret=nf90_put_att(ncid,varid(19),'direction_reference','Rotated Pole Grid North')
 #endif
         ENDIF
         !Sbt
         IF ( flsrce(5) )  THEN
           iret=nf90_def_var(ncid,'sbt',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(20))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(20), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(20),'long_name','depth induced breaking source term')
           iret=nf90_put_att(ncid,varid(20),'standard_name','depth_induced_breaking_source_term')
           iret=nf90_put_att(ncid,varid(20),'globwave_name','depth_induced_breaking_source_term')
           iret=nf90_put_att(ncid,varid(20),'units','m2 rad-1')
           iret=nf90_put_att(ncid,varid(20),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(20),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(20),'valid_min',-1.)
           iret=nf90_put_att(ncid,varid(20),'valid_max',1.)
           iret=nf90_put_att(ncid,varid(20),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(20),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(20),'associates','time station frequency direction')
 #ifdef W3_RTD
           iret=nf90_put_att(ncid,varid(20),'direction_reference','Rotated Pole Grid North')
 #endif
         ENDIF
         !Sice
         IF ( flsrce(6) )  THEN
           iret=nf90_def_var(ncid,'sice',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(21))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(21), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(21),'long_name','wave-ice interactions source term')
           iret=nf90_put_att(ncid,varid(21),'standard_name','wave_ice_intercations_source_term')
           iret=nf90_put_att(ncid,varid(21),'globwave_name','wave_ice_intercations_source_term')
           iret=nf90_put_att(ncid,varid(21),'units','m2 rad-1')
           iret=nf90_put_att(ncid,varid(21),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(21),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(21),'valid_min',-1.)
           iret=nf90_put_att(ncid,varid(21),'valid_max',1.)
           iret=nf90_put_att(ncid,varid(21),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(21),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(21),'associates','time station frequency direction')
 #ifdef W3_RTD
           iret=nf90_put_att(ncid,varid(21),'direction_reference','Rotated Pole Grid North')
 #endif
         ENDIF
         !Stt
         IF ( flsrce(7) )  THEN
           iret=nf90_def_var(ncid,'stt',nf90_float,(/dimid(5),dimid(4),dimid(two),dimid(one)/),varid(22))
           IF (nctype.EQ.4) iret=nf90_def_var_deflate(ncid, varid(22), 1, 1, deflate)
           iret=nf90_put_att(ncid,varid(22),'long_name','total source term')
           iret=nf90_put_att(ncid,varid(22),'standard_name','total_source_term')
           iret=nf90_put_att(ncid,varid(22),'globwave_name','total_source_term')
           iret=nf90_put_att(ncid,varid(22),'units','m2 rad-1')
           iret=nf90_put_att(ncid,varid(22),'scale_factor',1.)
           iret=nf90_put_att(ncid,varid(22),'add_offset',0.)
           iret=nf90_put_att(ncid,varid(22),'valid_min',-1.)
           iret=nf90_put_att(ncid,varid(22),'valid_max',1.)
           iret=nf90_put_att(ncid,varid(22),'_FillValue',nf90_fill_float)
           iret=nf90_put_att(ncid,varid(22),'content','TXYZ')
           iret=nf90_put_att(ncid,varid(22),'associates','time station frequency direction')
 #ifdef W3_RTD
           iret=nf90_put_att(ncid,varid(22),'direction_reference','Rotated Pole Grid North')
 #endif
         ENDIF
       ENDIF
       !  Add values in netCDF file
       iret=nf90_enddef(ncid)
       CALL check_err(iret,68)
       iret=nf90_put_var(ncid,varid(6),freq(1:nk))
       CALL check_err(iret,69)
       iret=nf90_put_var(ncid,varid(7),freq1(1:nk))
       CALL check_err(iret,70)
       iret=nf90_put_var(ncid,varid(8),freq2(1:nk))
       CALL check_err(iret,71)
       iret=nf90_put_var(ncid,varid(9),dir(1:nth))
       CALL check_err(iret,72)
       !
     END IF
     !
     RETURN
References check_err(), w3gdatmd::flagll, w3gdatmd::flagunr, w3gdatmd::nk, w3gdatmd::nth, w3gdatmd::sig, constants::tpiinv, and w3gdatmd::xfr.
w3exnc()
subroutine w3ounp::w3exnc (integer, intent(in) I, integer, intent(in) NCID, integer, intent(in) NREQ, integer, dimension(nreq), intent(in) INDREQ, logical, intent(in) ORDER)
Perform actual point output.
Spectra are relative frequency energy spectra. Note that arrays CX and CY of the main program now contain the absolute sea water speed and direction respectively.
Parameters
[in] I
[in] NCID
[in] NREQ
[in] INDREQ
[in] ORDER
Author
F. Ardhuin
M. Accensi
Date
14-Mar-2013
Definition at line 1452 of file ww3_ounp.F90.
     !/
     !/                  +-----------------------------------+
     !/                  | WAVEWATCH III           NOAA/NCEP |
     !/                  |            F. Ardhuin             |
     !/                  |            M. Accensi             |
     !/                  |                        FORTRAN 90 |
     !/                  | Last update :         14-Mar-2013 |
     !/                  +-----------------------------------+
     !/
     !/    01-Apr-2011 : Creation                            ( version 3.14 )
     !/    14-Mar-2013 : Optimization and cleanup            ( version 4.10 )
     !/
     !  1. Purpose :
     !
     !     Perform actual point output.
     !
     !  3. Parameters :
     !
     !  4. Subroutines used :
     !
     !      Name      Type  Module   Description
     !     ----------------------------------------------------------------
     !      W3SPRn    Subr. W3SRCnMD Mean wave parameters for use in
     !                               source terms.
     !      W3FLXn    Subr. W3FLXnMD Flux/stress computation.
     !      W3SLNn    Subr. W3SLNnMD Linear input.
     !      W3SINn    Subr. W3SRCnMD Input source term.
     !      W3SDSn    Subr. W3SRCnMD Whitecapping source term
     !      W3SNLn    Subr. W3SNLnMD Nonlinear interactions.
     !      W3SBTn    Subr. W3SBTnMD Bottom friction source term.
     !      W3SDBn    Subr. W3SBTnMD Depth induced breaking source term.
     !      W3STRn    Subr. W3STRnMD Triad interaction source term.
     !      W3SBSn    Subr. W3SBSnMD Bottom scattering source term.
     !      W3SXXn    Subr. W3SXXnMD Unclassified source term.
     !      W3PART    Sunr. W3PARTMD Spectral partitioning routine.
     !      STRACE    Subr. W3SERVMD Subroutine tracing.
     !      STME21    Subr. W3TIMEMD Convert time to string.
     !      PRT1DS    Subr. W3ARRYMD Print plot of 1-D spectrum.
     !      PRT1DM    Subr.   Id.    Print plot of several 1-D spectra.
     !      PRT2DS    Subr.   Id.    Print plot of 2-D spectrum.
     !      WAVNU1    Subr. W3DISPMD Solve dispersion relation.
     !     ----------------------------------------------------------------
     !
     !  5. Called by :
     !
     !     Main program in which it is contained,
     !
     !  6. Error messages :
     !
     !     None.
     !
     !  7. Remarks :
     !
     !     - Spectra are relative frequency energy spectra.
     !     - Note that arrays CX and CY of the main program now contain
     !       the absolute sea water speed and direction respectively.
     !
     !  8. Structure :
     !
     !     See source code.
     !
     !  9. Switches :
     !
     !       !/S      Enable subroutine tracing.
     !       !/T      Enable test output.
     !
     !       !/FLXx   Flux/stress computation.
     !       !/LNx    Linear input package
     !       !/STx    Source term package
     !       !/NLx    Nonlinear interaction package
     !       !/BTx    Bottom friction package
     !       !/ICx    S_ice source term package
     !       !/DBx    Depth-induced breaking package
     !       !/TRx    Triad interaction package
     !       !/BSx    Bottom scattering package
     !
     !       !/STAB2  Stability correction for !/ST2
     !
     ! 10. Source code :
     !
     !/ ------------------------------------------------------------------- /
 #ifdef W3_FLX1
     USE w3flx1md
 #endif
 #ifdef W3_FLX2
     USE w3flx2md
 #endif
 #ifdef W3_FLX3
     USE w3flx3md
 #endif
 #ifdef W3_FLX4
     USE w3flx4md
 #endif
 #ifdef W3_FLX5
     USE w3flx5md
 #endif
 #ifdef W3_LN1
     USE w3sln1md
 #endif
 #ifdef W3_ST1
     USE w3src1md
 #endif
 #ifdef W3_ST2
     USE w3src2md
 #endif
 #ifdef W3_ST3
     USE w3src3md
 #endif
 #ifdef W3_ST4
     USE w3src4md, ONLY : w3spr4, w3sin4, w3sds4
 #endif
 #ifdef W3_ST6
     USE w3src6md
     USE w3swldmd, ONLY : w3swl6
     USE w3gdatmd, ONLY : swl6s6
 #endif
 #ifdef W3_NL1
     USE w3snl1md
     USE w3gdatmd, ONLY: iqtpe
 #endif
 #ifdef W3_NL2
     USE w3snl2md
 #endif
 #ifdef W3_NL3
     USE w3snl3md
 #endif
 #ifdef W3_NL4
     USE w3snl4md
 #endif
 #ifdef W3_BT1
     USE w3sbt1md
 #endif
 #ifdef W3_BT4
     USE w3sbt4md
 #endif
 #ifdef W3_BT8
     USE w3sbt8md
 #endif
 #ifdef W3_BT9
     USE w3sbt9md
 #endif
 #ifdef W3_DB1
     USE w3sdb1md
 #endif
 #ifdef W3_BS1
     USE w3sbs1md
 #endif
 #ifdef W3_IS2
     USE w3sis2md
 #endif
     USE w3partmd, ONLY: w3part
     USE w3dispmd, ONLY: wavnu1, liu_forward_dispersion
     USE w3gdatmd, ONLY: iicedisp
     !/
     USE w3arrymd, ONLY: prt1ds, prt2ds, prt1dm
     USE w3dispmd, ONLY: nar1d, dfac, n1max, ecg1, ewn1, dsie
     USE netcdf
 #ifdef W3_IG1
     USE w3gig1md, ONLY: w3addig
     USE w3canomd, ONLY: w3add2ndorder
 #endif
     IMPLICIT NONE
     !/
     !/ ------------------------------------------------------------------- /
     INTEGER, INTENT(IN)     :: I, NCID, NREQ, INDREQ(NREQ)
     LOGICAL, INTENT(IN)     :: ORDER
     !/ Local parameters
     !/
     INTEGER                 :: J, J1, I1, I2, ISP, IKM,              &
          ITH, IK, ITT, NPART, IX, IY, ISEA
     INTEGER                 :: CURDATE(8), REFDATE(8)
 #ifdef W3_S
     INTEGER, SAVE           :: IENT   = 0
 #endif
     !
     REAL                    :: DEPTH, SQRTH, CDIR, SIX, R1, R2,      &
          UDIR, UDIRR, UABS, XL, XH, XL2, XH2,  &
          ET, EWN, ETR, ETX, ETY, EBND, EBX,    &
          EBY, HSIG, WLEN, TMEAN, THMEAN,       &
          THSPRD, EMAX, EL, EH, DENOM, FP, THP, &
          SPP, CD, USTAR, FACTOR, UNORM, ESTAR, &
          FPSTAR, FACF, FACE, FACS, HMAT, WNA,  &
          XYZ, AGE1, AFR, AGE2, FACT, XSTAR,    &
          YSTAR, FHIGH, ZWND, Z0, USTD, EMEAN,  &
          FMEAN, WNMEAN, UDIRCA, CHARN, M2KM,   &
          ICETHICK, ICECON
 #ifdef W3_FLX5
     REAL                    :: TAUA, TAUADIR, RHOAIR
 #endif
     REAL                    :: WN_R(NK),CG_ICE(NK), ALPHA_LIU(NK),   &
          R(NK), WN(NK), CG(NK), APM(NK),       &
          E3(NTH,NK,NREQ), E(NK,NTH), E1(NK),   &
          THBND(NK), SPBND(NK), A(NTH,NK),      &
          WN2(NTH,NK),                          &
          STT(NK,NTH), SWN(NK,NTH), SNL(NK,NTH),&
          SDS(NK,NTH), SBT(NK,NTH), SIS(NK,NTH),&
          XIN(NTH,NK), XNL(NTH,NK), XTR(NTH,NK),&
          XDS(NTH,NK), XDB(NTH,NK), XBT(NTH,NK),&
          XBS(NTH,NK), XXX(NTH,NK), DIA(NTH,NK),&
          XLN(NTH,NK), XWL(NTH,NK), XIS(NTH,NK),&
          SIN1(NK), SNL1(NK), SDS1(NK),         &
          SBT1(NK), SIS1(NK), STT1(NK),         &
          E1ALL(NK,6), UDIR1(NREQ), CDIR1(NREQ)
 #ifdef W3_FLX5
     REAL                    :: TAUDIR1(NREQ)
 #endif
     REAL, SAVE              :: HSMIN  = 0.05
 #ifdef W3_IS2
     REAL                     :: ICEF, ICEDMAX, DIA2(NTH,NK)
 #endif
 #ifdef W3_ST1
     REAL                    :: AMAX, FH1, FH2
 #endif
 #ifdef W3_ST2
     REAL                    :: AMAX, ALPHA(NK), FPI
 #endif
 #ifdef W3_ST3
     REAL                    :: AMAX, FMEANS, FMEANWS, TAUWX, TAUWY, &
          TAUWNX, TAUWNY
 #endif
 #ifdef W3_ST4
     REAL                    :: AMAX, FMEANS, FMEANWS, TAUWX, TAUWY, &
          TAUWNX, TAUWNY, FMEAN1, WHITECAP(1:4)
     REAL                    :: LAMBDA(NSPEC), DLWMEAN
 #endif
 #ifdef W3_ST6
     REAL                    :: AMAX, TAUWX, TAUWY, TAUWNX, TAUWNY
 #endif
 #ifdef W3_BS1
     REAL                    :: TAUSCX, TAUSCY
 #endif
 #ifdef W3_BT4
     REAL                    :: D50, PSIC, BEDFORM(3), TAUBBL(2)
 #endif
     REAL                    :: ICE
 #ifdef W3_STAB2
     REAL                    :: STAB0, STAB,  COR1, COR2, ASFAC,     &
          THARG1, THARG2
 #endif
     !
     DOUBLE PRECISION        :: OUTJULDAY
     !
     CHARACTER*4             :: VAR1(6)
     !
     LOGICAL                 :: LASTSTATION=.false.
     LOGICAL                 :: SHORT=.true.
     LOGICAL                   :: LBREAK
 #ifdef W3_ST3
     LOGICAL                 :: LLWS(NSPEC)
 #endif
 #ifdef W3_ST4
     LOGICAL                 :: LLWS(NSPEC)
 #endif
     !
     DATA var1   / 'Sin ' , 'Snl ', 'Sds ' , 'Sbt ' , 'Sice', 'Stot' /
     !/
     !/ ------------------------------------------------------------------- /
     !/
     ! 1. Initialisations
     !
 #ifdef W3_S
     CALL strace (ient, 'W3EXNC')
 #endif
     !
     IF ( flagll ) THEN
       m2km   = 1.
     ELSE
       m2km   = 1.e-3
     END IF
     !
     xl     = 1./xfr - 1.
     xh     =  xfr - 1.
     xl2    = xl**2
     xh2    = xh**2
     !
     IF ( itype .EQ. 3 ) THEN
       xln = 0.
       xin = 0.
       xnl = 0.
       xtr = 0.
       xds = 0.
       xdb = 0.
       xbt = 0.
       xbs = 0.
       xwl = 0.
       xis = 0.
       xxx = 0.
     END IF
     !
     CALL u2d('days since 1990-01-01 00:00:00',refdate,ierr)
     !
 #ifdef W3_T
     WRITE (ndst,9000) (flreq(j),j=1,nopts)
     WRITE (ndst,9001) itype, otype, nreq, scale1, scale2, flsrce
 #endif
     !
     !--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
     !     Loop over output points.
     !
     !
     ! Selects first station index
     !
     IF (together) THEN
       j=1
     ELSE
       j=i
     END IF
     !
     ! Short version of the ww3_ounp code for ITYPE = 1
     !                                    and OTYPE = 3
     !
     IF (short.AND.itype.EQ.1.AND.otype.EQ.3) THEN
       depth  = max( dmin, dpo(j) )
       sqrth  = sqrt( depth )
       DO ik=1, nk
         six    = sig(ik) * sqrth
         i1     = int(six/dsie)
         IF (i1.LE.n1max) THEN
           i2 = i1 + 1
           r1 = six/dsie - real(i1)
           r2 = 1. - r1
           wn(ik) = ( r2*ewn1(i1) + r1*ewn1(i2) ) / depth
           cg(ik) = ( r2*ecg1(i1) + r1*ecg1(i2) ) * sqrth
         ELSE
           wn(ik) = sig(ik)*sig(ik)/grav
           cg(ik) = 0.5 * grav / sig(ik)
         END IF
 #ifdef W3_T
         WRITE (ndst,9011) ik, tpi/sig(ik), wn(ik), cg(ik)
 #endif
         !
       END DO
       !
       ! Computes 2nd order spectrum
       !
 #ifdef W3_IG1
       IF (igpars(2).EQ.1) THEN
         IF(igpars(1).EQ.1) THEN
           CALL w3addig(spco(:,j),dpo(j),wn,cg,0)
         ELSE
           CALL w3add2ndorder(spco(:,j),dpo(j),wn,cg,0)
         END IF
       END IF
 #endif
       !
       DO j1=1, nreq
         DO ik=1, nk
           DO ith=1, nth
             isp    = ith + (ik-1)*nth
             e3(ith,ik,j1) = spco(isp,indreq(j1))
           END DO
         END DO
       END DO
       CALL t2d(time,curdate,ierr)
       outjulday=tsub(refdate,curdate)
       iret=nf90_put_var(ncid,varid(1),outjulday,(/iout/))
       CALL check_err(iret,4)
       !
       IF (iout.EQ.1) THEN
         DO j1=1, nreq
           iret=nf90_put_var(ncid,varid(27),indreq(j1),(/j1/))
           CALL check_err(iret,5)
           iret=nf90_put_var(ncid,varid(2),ptnme(indreq(j1)),         &
                start=(/1,j1/),count=(/len_trim(ptnme(indreq(j1))) ,1/))
           CALL check_err(iret,6)
         END DO
       END IF
       !
       DO j1=1, nreq
         IF ((flww3.NE.0).AND.(order)) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
         IF ((flww3.NE.0).AND.(.NOT.order)) iret=nf90_put_var(ncid,varid(3),flww3,(/iout,j1/))
         CALL check_err(iret,7)
       END DO
       !
       IF(order) iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,indreq(1:nreq)),(/1,iout/))
       IF(.NOT.order) iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,indreq(1:nreq)),(/iout,1/))
       CALL check_err(iret,8)
       IF(order) iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,indreq(1:nreq)),(/1,iout/))
       IF(.NOT.order) iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,indreq(1:nreq)),(/iout,1/))
       CALL check_err(iret,9)
       !
       DO j1=1,nreq
         udir1(j1)  = mod( 270. - wdo(indreq(j1))*rade , 360. )
         cdir1(j1)   = mod( 270. - cdo(indreq(j1))*rade , 360. )
 #ifdef W3_FLX5
         taudir1(j1) =  mod( 270. - taudo(indreq(j1))*rade , 360. )
 #endif
       END DO
       !
       IF (ncvartype.LE.3) THEN
         IF(order) iret=nf90_put_var(ncid,varid(11),nint(dpo(indreq(1:nreq))/0.5),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(11),nint(dpo(indreq(1:nreq))/0.5),(/iout,1/))
         CALL check_err(iret,10)
         IF(order) iret=nf90_put_var(ncid,varid(12),nint(wao(indreq(1:nreq))/0.1),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(12),nint(wao(indreq(1:nreq))/0.1),(/iout,1/))
         CALL check_err(iret,11)
         IF(order) iret=nf90_put_var(ncid,varid(13),nint(udir1/0.1),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(13),nint(udir1/0.1),(/iout,1/))
         CALL check_err(iret,12)
         IF(order) iret=nf90_put_var(ncid,varid(14),nint(cao(indreq(1:nreq))/0.1),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(14),nint(cao(indreq(1:nreq))/0.1),(/iout,1/))
         CALL check_err(iret,13)
         IF(order) iret=nf90_put_var(ncid,varid(15),nint(cdir1/0.1),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(15),nint(cdir1/0.1),(/iout,1/))
         CALL check_err(iret,14)
       ELSE
         IF(order) iret=nf90_put_var(ncid,varid(11),dpo(indreq(1:nreq)),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(11),dpo(indreq(1:nreq)),(/iout,1/))
         CALL check_err(iret,10)
         IF(order) iret=nf90_put_var(ncid,varid(12),wao(indreq(1:nreq)),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(12),wao(indreq(1:nreq)),(/iout,1/))
         CALL check_err(iret,11)
         IF(order) iret=nf90_put_var(ncid,varid(13),udir1,(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(13),udir1,(/iout,1/))
         CALL check_err(iret,12)
         IF(order) iret=nf90_put_var(ncid,varid(14),cao(indreq(1:nreq)),(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(14),cao(indreq(1:nreq)),(/iout,1/))
         CALL check_err(iret,13)
         IF(order) iret=nf90_put_var(ncid,varid(15),cdir1,(/1,iout/))
         IF(.NOT.order) iret=nf90_put_var(ncid,varid(15),cdir1,(/iout,1/))
         CALL check_err(iret,14)
       END IF
       !
       IF (ncvartype.LE.3) THEN
         WHERE(e3(:,:,:).GE.0) e3(:,:,:)=nint(alog10(e3(:,:,:)+1e-12)/0.0004)
       END IF
       IF(order) iret=nf90_put_var(ncid,varid(10),e3(1:nth,1:nk,:), &
            start=(/1,1,1,iout/),count=(/nth,nk,nreq,1/))
       IF(.NOT.order) iret=nf90_put_var(ncid,varid(10),e3(1:nth,1:nk,1:nreq), &
            start=(/1,1,iout,1/),count=(/nth,nk,1,nreq/))
       CALL check_err(iret,15)
       !
       ! End of short version
       !
     ELSE
       !
       ! And here is the full thing with all options ITYPE and OTYPE ...
       !
       j1=1
       laststation=.false.
       !
       DO WHILE (.NOT.laststation)
         !
         IF ( flreq(j) ) THEN
           !
           !  Open netCDF file
           !
 #ifdef W3_T
           WRITE (ndst,9002) ptnme(j)
 #endif
           !
           ! 2. Calculate grid parameters using and inlined version of WAVNU1.
           !
           depth    = max( dmin, dpo(j) )
           sqrth    = sqrt( depth )
           udir     = mod( 270. - wdo(j)*rade , 360. )
           udirca   = wdo(j)*rade
           udirr    = wdo(j)
           uabs     = max( 0.001 , wao(j) )
           cdir     = mod( 270. - cdo(j)*rade , 360. )
 #ifdef W3_FLX5
           taua     = max( 0.001 , tauao(j))
           tauadir  = mod( 270. - taudo(j)*rade , 360. )
           rhoair   = max( 0. , dairo(j))
 #endif
 #ifdef W3_IS2
           icedmax  = max( 0., icefo(j))
           icef     = icedmax
 #endif
           icethick = max(0., iceho(j))
           icecon   = max(0., iceo(j))
           !
 #ifdef W3_STAB2
           stab0  = zwind * grav / 273.
           stab   = stab0 * aso(j) / max(5.,wao(j))**2
           stab   = max( -1. , min( 1. , stab ) )
           tharg1 = max( 0. , ffng*(stab-ofstab))
           tharg2 = max( 0. , ffps*(stab-ofstab))
           cor1   = ccng * tanh(tharg1)
           cor2   = ccps * tanh(tharg2)
           asfac  = sqrt( (1.+cor1+cor2)/shstab )
 #endif
           !
 #ifdef W3_T
           WRITE (ndst,9010) depth
 #endif
           DO ik=1, nk
             six    = sig(ik) * sqrth
             i1     = int(six/dsie)
             IF (i1.LE.n1max) THEN
               i2 = i1 + 1
               r1 = six/dsie - real(i1)
               r2 = 1. - r1
               wn(ik) = ( r2*ewn1(i1) + r1*ewn1(i2) ) / depth
               cg(ik) = ( r2*ecg1(i1) + r1*ecg1(i2) ) * sqrth
             ELSE
               wn(ik) = sig(ik)*sig(ik)/grav
               cg(ik) = 0.5 * grav / sig(ik)
             END IF
 #ifdef W3_T
             WRITE (ndst,9011) ik, tpi/sig(ik), wn(ik), cg(ik)
 #endif
             !
           END DO
           !
           ! Computes 2nd order spectrum
           !
 #ifdef W3_IG1
           IF (igpars(2).EQ.1) THEN
             IF(igpars(1).EQ.1) THEN
               CALL w3addig(spco(:,j),dpo(j),wn,cg,0)
             ELSE
               CALL w3add2ndorder(spco(:,j),dpo(j),wn,cg,0)
             END IF
           END IF
 #endif
           !
           !
           ! 3.  Prepare spectra etc.
           ! 3.a Mean wave parameters.
           !
           et     = 0.
           ewn    = 0.
           etr    = 0.
           etx    = 0.
           ety    = 0.
           DO ik=1, nk
             ebnd   = 0.
             ebx    = 0.
             eby    = 0.
             DO ith=1, nth
               isp    = ith + (ik-1)*nth
               e(ik,ith) = spco(isp,j)
               ebnd   = ebnd + spco(isp,j)
               ebx    = ebx  + spco(isp,j)*ecos(ith)
               eby    = eby  + spco(isp,j)*esin(ith)
             END DO
             e1(ik) = ebnd * dth
             apm(ik)= e1(ik) / ( tpi * grav**2 / sig(ik)**5  )
             IF ( e1(ik) .GT. 1.e-5) THEN
               thbnd(ik) = mod(630.- rade*atan2(eby,ebx),360.)
               spbnd(ik) = rade * sqrt( max( 0. , 2.*( 1. -      &
                    sqrt( max(0.,(ebx**2+eby**2)/ebnd**2) ) ) ) )
             ELSE
               thbnd(ik) = -999.9
               spbnd(ik) = -999.9
             END IF
             ebnd   = e1(ik) * dsii(ik) * tpiinv
             et     = et  + ebnd
             ewn    = ewn + ebnd / wn(ik)
             etr    = etr + ebnd / sig(ik)
             etx    = etx + ebx * dsii(ik)
             ety    = ety + eby * dsii(ik)
           END DO
           !
           ! tail factors for radian action etc ...!
           !
           ebnd   = e1(nk) * tpiinv / ( sig(nk) * dth )
           et     = et  + fte *ebnd
           ewn    = ewn + ftwl*ebnd
           etr    = etr + fttr*ebnd
           etx    = dth*etx*tpiinv + fte*ebx*tpiinv/sig(nk)
           ety    = dth*ety*tpiinv + fte*eby*tpiinv/sig(nk)
           !
           hsig   = 4. * sqrt( et )
           IF ( hsig .GT. hsmin ) THEN
             wlen   = ewn / et * tpi
             tmean  = etr / et * tpi
             thmean = mod( 630. - rade*atan2(ety,etx) , 360. )
             thsprd = rade * sqrt( max( 0. , 2.*( 1. - sqrt(     &
                  max(0.,(etx**2+ety**2)/et**2) ) ) ) )
             IF ( thsprd .LT. 0.01*rade*dth ) thsprd = 0.
           ELSE
             wlen   = 0.
             tmean  = 0.
             thmean = 0.
             thsprd = 0.
             e1(1:nk) = 0.
             e(1:nk,1:nth) = 0.
           END IF
           !
           ! 3.b peak frequency
           !
           emax   = e1(nk)
           ikm    = nk
           !
           DO ik=nk-1, 1, -1
             IF ( e1(ik) .GT. emax ) THEN
               emax   = e1(ik)
               ikm    = ik
             END IF
           END DO
           !
           IF ( hsig .GE. hsmin .AND. ikm .NE. nk ) THEN
             IF ( ikm .EQ. 1 ) THEN
               el = - e1(ikm)
             ELSE
               el = e1(ikm-1) - e1(ikm)
             END IF
             eh = e1(ikm+1) - e1(ikm)
             denom  = xl*eh - xh*el
             !
             fp     = sig(ikm) * ( 1. + 0.5 * ( xl2*eh - xh2*el )  &
                  / sign( max(abs(denom),1.e-15) , denom ) )
             thp    = thbnd(ikm)
             spp    = spbnd(ikm)
             IF ( spp .LT. 0.01*rade*dth ) spp = 0.
           ELSE
             fp     = 0.
             thp    = 0.
             spp    = 0.
           END IF
           !
           ! 3.c spectral partitioning
           !
           IF ( itype.EQ.1 .AND. otype.EQ.4 ) THEN
             CALL w3part( e, uabs, udirca, depth, wn, npart, xpart, &
                  dimxp )
           END IF
           !
           ! 3.d nondimensional parameters
           !
           IF ( ( itype.EQ.2 .AND. (otype.EQ.3.OR.otype.EQ.4) ) .OR. &
                ( itype.EQ.1 .AND. (otype.EQ.2) ) ) THEN
             !
             DO ik=1, nk
               factor = tpiinv * cg(ik) / sig(ik)
               DO ith=1, nth
                 isp    = ith + (ik-1)*nth
                 a(ith,ik)   = factor * spco(isp,j)
                 wn2(ith,ik) = wn(ik)
               END DO
             END DO
             !
 #ifdef W3_STAB2
             uabs   = uabs / asfac
 #endif
             !
 #ifdef W3_ST0
             zwnd   = 10.
 #endif
 #ifdef W3_ST1
             zwnd   = 10.
 #endif
 #ifdef W3_ST2
             zwnd   = zwind
 #endif
 #ifdef W3_ST3
             zwnd   = zzwnd
             tauwx  = 0.
             tauwy  = 0.
             llws(:)  = .true.
 #endif
 #ifdef W3_ST4
             llws(:)  = .true.
             zwnd   = zzwnd
             tauwx  = 0.
             tauwy  = 0.
 #endif
 #ifdef W3_ST6
             zwnd   = 10.
 #endif
             !
 #ifdef W3_ST1
             CALL w3spr1 (a, cg, wn, emean, fmean, wnmean, amax)
             fp     = 0.85 * fmean
 #endif
 #ifdef W3_ST2
             CALL w3spr2 (a, cg, wn, depth, fp , uabs, ustar, &
                  emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
             CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                  wnmean, amax, uabs, udirr, ustar, ustd,&
                  tauwx, tauwy, cd, z0, charn, llws, fmeanws )
 #endif
 #ifdef W3_ST4
             CALL w3spr4 (a, cg, wn, emean, fmean, fmean1,       &
                  wnmean, amax, uabs, udirr,             &
 #ifdef W3_FLX5
                  taua, tauadir, rhoair,           &
 #endif
                  ustar, ustd, tauwx, tauwy, cd, z0,     &
                  charn, llws, fmeanws, dlwmean )
 #endif
 #ifdef W3_ST6
             CALL w3spr6 (a, cg, wn, emean, fmean, wnmean, amax, fp)
 #endif
             !
 #ifdef W3_FLX1
             CALL w3flx1 ( zwnd, uabs, udirr,                   &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX2
             CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,        &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
             CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,        &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX4
             CALL w3flx4 ( zwnd, uabs, udirr, ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX5
             CALL w3flx5 ( zwnd, uabs, udirr, taua, tauadir,    &
                  rhoair, ustar, ustd, z0, cd, charn )
 #endif
             !
             DO itt=1, 4
 #ifdef W3_ST2
               CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,    &
                    fpi, xin, dia )
               CALL w3spr2 (a, cg, wn, depth, fpi, uabs, ustar, &
                    emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
               ix=1
               iy=1
               CALL w3sin3 ( a, cg, wn2, uabs, ustar, dair/dwat,&
                    aso(j), udirr, z0, cd, tauwx, tauwy,&
                    tauwnx, tauwny, ice, xin, dia, llws, ix, iy )
               CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                    wnmean, amax, uabs, udirr, ustar, ustd,&
                    tauwx, tauwy, cd, z0, charn, llws, fmeanws )
 #endif
 #ifdef W3_ST4
               ix=1
               iy=1
               CALL w3spr4 (a, cg, wn, emean, fmean, fmean1,      &
                    wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                    taua, tauadir, rhoair,             &
 #endif
                    ustar, ustd, tauwx, tauwy, cd, z0,       &
                    charn, llws, fmeanws,dlwmean )
               CALL w3sds4 ( a, wn, cg, ustar,  ustd, depth, dair, xds, &
                    dia, ix, iy, lambda, whitecap, dlwmean )
               CALL w3sin4 (a, cg, wn2, uabs, ustar, dair/dwat,     &
                    aso(j), udirr, z0, cd, tauwx, tauwy, tauwnx, &
                    tauwny, xin, dia, llws, ix, iy, lambda )
 #endif
 #ifdef W3_FLX2
               CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,      &
                    ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
               CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,      &
                    ustar, ustd, z0, cd )
 #endif
             END DO
             !
             ! Add alternative flux calculations here as part of !/ST2 option ....
             ! Also add before actual source term calculation !!!
             !
 #ifdef W3_STAB2
             uabs   = uabs * asfac
 #endif
             !
             IF ( wao(j) .LT. 0.01 ) THEN
               unorm  = 0.
               estar  = 0.
               fpstar = 0.
             ELSE
               IF ( otype.EQ.3 ) THEN
                 unorm  = ustar
               ELSE
                 unorm  = wao(j)
               END IF
               estar  = et * grav**2 / unorm**4
               fpstar = fp * tpiinv * unorm / grav
               xstar  = ptloc(1,j) * grav / unorm**2
               ystar  = ptloc(2,j) * grav / unorm**2
               IF ( flagll ) THEN
                 xstar  = xstar * dera * radius &
                      * cos(ptloc(2,j)*dera)
                 ystar  = ystar * dera * radius
               END IF
             END IF
             !
           END IF ! 3.d
           !
           ! 3.e source terms
           !
           IF ( itype.EQ.3 ) THEN
             !
             DO ik=1, nk
               factor = tpiinv * cg(ik) / sig(ik)
               DO ith=1, nth
                 a(ith,ik)   = factor * spco(ith+(ik-1)*nth,j)
                 wn2(ith,ik) = wn(ik)
               END DO
             END DO
             !
 #ifdef W3_STAB2
             uabs   = uabs / asfac
 #endif
             !
 #ifdef W3_ST0
             zwnd   = 10.
 #endif
 #ifdef W3_ST1
             zwnd   = 10.
 #endif
 #ifdef W3_ST2
             zwnd   = zwind
 #endif
 #ifdef W3_ST3
             zwnd   = zzwnd
 #endif
 #ifdef W3_ST0
             ustar  = 1.
 #endif
 #ifdef W3_ST1
             ustar  = 1.
 #endif
 #ifdef W3_ST2
             ustar  = 1.
 #endif
 #ifdef W3_ST3
             ustar  = 0.
             ustd   = 0.
             tauwx  = 0.
             tauwy  = 0.
 #endif
 #ifdef W3_ST4
             zwnd   = zzwnd
             ustar  = 0.
             ustd   = 0.
             tauwx  = 0.
             tauwy  = 0.
 #endif
 #ifdef W3_ST6
             zwnd   = 10.
 #endif
             !
 #ifdef W3_ST0
             fhigh  = sig(nk)
 #endif
 #ifdef W3_ST1
             CALL w3spr1 (a, cg, wn, emean, fmean, wnmean, amax)
             fp     = 0.85 * fmean
             fh1    = fxfm * fmean
             fh2    = fxpm / ustar
             fhigh  = max( fh1 , fh2 )
 #endif
 #ifdef W3_ST2
             CALL w3spr2 (a, cg, wn, depth, fp , uabs, ustar, &
                  emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
             CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                  wnmean, amax, uabs, udirr, ustar, ustd,&
                  tauwx, tauwy, cd, z0, charn, llws, fmeanws )
 #endif
 #ifdef W3_ST4
             CALL w3spr4 (a, cg, wn, emean, fmean,  fmean1,        &
                  wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                  taua, tauadir, rhoair,             &
 #endif
                  ustar, ustd, tauwx, tauwy, cd, z0,       &
                  charn, llws, fmeanws, dlwmean )
             CALL w3sds4 ( a, wn, cg, ustar,  ustd, depth, dair, xds, &
                  dia, ix, iy, lambda, whitecap, dlwmean )
 #endif
 #ifdef W3_ST6
             CALL w3spr6 (a, cg, wn, emean, fmean, wnmean, amax, fp)
             fhigh  = sig(nk)
 #endif
             !
 #ifdef W3_FLX1
             CALL w3flx1 ( zwnd, uabs, udirr,                   &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX2
             CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,        &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
             CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,        &
                  ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX4
             CALL w3flx4 ( zwnd, uabs, udirr, ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX5
             CALL w3flx5 ( zwnd, uabs, udirr, taua, tauadir,    &
                  rhoair, ustar, ustd, z0, cd, charn )
 #endif
             !
             DO itt=1, 3
 #ifdef W3_ST2
               CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,    &
                    fpi, xin, dia )
               CALL w3spr2 (a, cg, wn, depth, fpi, uabs, ustar, &
                    emean, fmean, wnmean, amax, alpha, fp )
 #endif
 #ifdef W3_ST3
               CALL w3spr3 (a, cg, wn, emean, fmean, fmeans,       &
                    wnmean, amax, uabs, udirr, ustar, ustd,&
                    tauwx, tauwy, cd, z0, charn, llws, fmeanws )
               CALL w3sin3 ( a, cg, wn2, uabs, ustar, dair/dwat,&
                    aso(j), udirr, z0, cd,tauwx, tauwy, &
                    tauwnx, tauwny, ice, xin, dia, llws, ix, iy )
 #endif
 #ifdef W3_ST4
               CALL w3spr4 (a, cg, wn, emean, fmean, fmean1,       &
                    wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                    taua, tauadir, rhoair,              &
 #endif
                    ustar, ustd,  tauwx, tauwy, cd, z0,      &
                    charn, llws, fmeanws, dlwmean )
               CALL w3sin4 (a, cg, wn2, uabs, ustar, dair/dwat,    &
                    aso(j), udirr, z0, cd, tauwx, tauwy,tauwnx,&
                    tauwny, xin, dia, llws, ix, iy, lambda )
 #endif
 #ifdef W3_FLX2
               CALL w3flx2 ( zwnd, depth, fp, uabs, udirr,      &
                    ustar, ustd, z0, cd )
 #endif
 #ifdef W3_FLX3
               CALL w3flx3 ( zwnd, depth, fp, uabs, udirr,      &
                    ustar, ustd, z0, cd )
 #endif
             END DO
             !
 #ifdef W3_ST2
             fhigh  = xfc * fpi
 #endif
             !
             IF ( flsrce(2) ) THEN
 #ifdef W3_LN1
               CALL w3sln1 (wn, fhigh, ustar, udirr, xln )
 #endif
               !
 #ifdef W3_ST1
               CALL w3sin1 (a, wn2, ustar, udirr,  xin, dia )
 #endif
 #ifdef W3_ST2
               CALL w3sin2 (a, cg, wn2, uabs, udirr, cd, z0,&
                    fpi, xin, dia )
 #endif
 #ifdef W3_ST3
               CALL w3sin3 ( a, cg, wn2, uabs, ustar,       &
                    dair/dwat, aso(j), udirr,      &
                    z0, cd, tauwx, tauwy,tauwnx, tauwny, &
                    ice, xin, dia, llws, ix, iy )
 #endif
               !
 #ifdef W3_ST4
               CALL w3spr4 (a, cg, wn, emean, fmean, fmean1,     &
                    wnmean, amax, uabs, udirr,               &
 #ifdef W3_FLX5
                    taua, tauadir, rhoair,              &
 #endif
                    ustar, ustd, tauwx, tauwy, cd, z0,       &
                    charn, llws, fmeanws, dlwmean )
               CALL w3sds4 ( a, wn, cg, ustar,  ustd, depth, dair, xds, &
                    dia, ix, iy, lambda, whitecap, dlwmean )
               CALL w3sin4 (a, cg, wn2, uabs, ustar, dair/dwat,    &
                    aso(j), udirr, z0, cd, tauwx, tauwy, tauwnx, &
                    tauwny, xin, dia, llws, ix, iy, lambda )
 #endif
 #ifdef W3_ST6
               CALL w3sin6 (a, cg, wn2, uabs, ustar, udirr, cd, dair, &
                    tauwx, tauwy, tauwnx, tauwny, xin, dia )
 #endif
             END IF
             IF ( flsrce(3) ) THEN
 #ifdef W3_NL1
               IF (iqtpe.GT.0) THEN
                 CALL w3snl1 ( a, cg, wnmean*depth,  xnl, dia )
               ELSE
                 CALL w3snlgqm ( a, cg, wn, depth,  xnl, dia )
               END IF
 #endif
 #ifdef W3_NL2
               CALL w3snl2 ( a, cg, depth,         xnl, dia )
 #endif
 #ifdef W3_NL3
               CALL w3snl3 ( a, cg, wn, depth,     xnl, dia )
 #endif
 #ifdef W3_NL4
               CALL w3snl4 ( a, cg, wn, depth,     xnl, dia )
 #endif
             END IF
             IF ( flsrce(4) ) THEN
 #ifdef W3_ST1
               CALL w3sds1 ( a, wn2, emean, fmean, wnmean,  &
                    xds, dia )
 #endif
 #ifdef W3_ST2
               CALL w3sds2 ( a, cg, wn, fpi, ustar,         &
                    alpha,                xds, dia )
 #endif
 #ifdef W3_ST3
               CALL w3sds3 ( a, wn, cg, emean, fmeans, wnmean,  &
                    ustar, ustd, depth, xds, dia, ix, iy )
 #endif
 #ifdef W3_ST4
               CALL w3spr4 (a, cg, wn, emean, fmean, fmean1,       &
                    wnmean, amax, uabs, udirr,                 &
 #ifdef W3_FLX5
                    taua, tauadir, rhoair,               &
 #endif
                    ustar, ustd, tauwx, tauwy, cd, z0,         &
                    charn, llws, fmeanws, dlwmean )
               CALL w3sds4 ( a, wn, cg,  ustar, ustd, depth, dair, xds, &
                    dia, ix, iy, lambda, whitecap , dlwmean)
 #endif
 #ifdef W3_ST6
               CALL w3sds6 ( a, cg, wn, xds, dia )
               IF (swl6s6) CALL w3swl6 ( a, cg, wn, xwl, dia )
 #endif
               !
 #ifdef W3_DB1
               CALL w3sdb1 ( i, a, depth, emean, fmean, &
                    wnmean, cg, lbreak, xdb, dia )
 #endif
             END IF
             IF ( flsrce(5) ) THEN
 #ifdef W3_BT1
               CALL w3sbt1 ( a, cg, wn, depth,     xbt, dia )
 #endif
 #ifdef W3_BT4
               ix=1    ! to be fixed later
               iy=1    ! to be fixed later
               isea=1  ! to be fixed later
               d50 = sed_d50(isea)
               psic= sed_psic(isea)
               CALL w3sbt4 ( a, cg, wn, depth, d50, psic, taubbl,   &
                    bedform, xbt, dia, ix, iy )
 #endif
               ! see remarks about BT8 and BT9 in ww3_outp.ftn
               !....broken....!/BT8        CALL W3SBT8 ( SPEC, DEPTH, VSBT, VDBT, IX, IY )
               !....broken....!/BT9        CALL W3SBT9 ( SPEC, DEPTH, VSBT, VDBT, IX, IY )
               !
 #ifdef W3_BS1
               CALL w3sbs1 ( a, cg, wn, depth,              &
                    cao(j)*cos(cdo(j)), cao(j)*sin(cdo(j)), &
                    tauscx, tauscy,   xbs, dia )
 #endif
               !
             END IF
             IF ( flsrce(6) ) THEN
               IF (iicedisp) THEN
                 CALL liu_forward_dispersion (icethick,0.,depth, &
                      sig,wn_r,cg_ice,alpha_liu)
               ELSE
                 wn_r=wn
                 cg_ice=cg
               END IF
               !
 #ifdef W3_IS2
               CALL w3sis2(a, depth, icecon, icethick, icef, icedmax,  &
                    ix, iy, xis, dia, dia2, wn, cg, wn_r, cg_ice, r)
 #endif
             END IF
             !
 #ifdef W3_STAB2
             uabs   = uabs * asfac
 #endif
             !
             IF ( iscale.EQ.0 .OR. iscale.EQ.3 ) THEN
               facf   = tpiinv
               face   = 1.
               facs   = 1.
             ELSE IF ( iscale.EQ.1 .OR. iscale.EQ.4 ) THEN
               facf   = tpiinv * uabs / grav
               face   = grav**3 / uabs**5
               facs   = grav**2 / uabs**4
             ELSE IF ( iscale.EQ.2 .OR. iscale.EQ.5 ) THEN
               facf   = tpiinv * ustar / grav
               face   = grav**3 / ustar**5
               facs   = grav**2 / ustar**4
             END IF
             !
             DO ik=1, nk
               factor = tpi / cg(ik) * sig(ik)
               e1(ik) = 0.
               sin1(ik) = 0.
               snl1(ik) = 0.
               sds1(ik) = 0.
               sbt1(ik) = 0.
               sis1(ik) = 0.
               stt1(ik) = 0.
               DO ith=1, nth
                 isp         = ith + (ik-1)*nth
                 e(ik,ith) = spco(isp,j)
                 swn(ik,ith) = ( xln(ith,ik) + xin(ith,ik) ) * factor
                 snl(ik,ith) = ( xnl(ith,ik) + xtr(ith,ik) ) * factor
                 sds(ik,ith) = ( xds(ith,ik) + xdb(ith,ik) ) * factor
 #ifdef W3_ST6
                 sds(ik,ith) =   sds(ik,ith) +(xwl(ith,ik)   * factor)
 #endif
                 sbt(ik,ith) = ( xbt(ith,ik) + xbs(ith,ik) ) * factor
                 sis(ik,ith) = xis(ith,ik) * factor
                 stt(ik,ith) = swn(ik,ith) + snl(ik,ith) + sds(ik,ith) + &
                      sbt(ik,ith) + sis(ik,ith) + xxx(ith,ik) * factor
                 e1(ik) = e1(ik) + e(ik,ith)
                 sin1(ik) = sin1(ik) + swn(ik,ith)
                 snl1(ik) = snl1(ik) + snl(ik,ith)
                 sds1(ik) = sds1(ik) + sds(ik,ith)
                 sbt1(ik) = sbt1(ik) + sbt(ik,ith)
                 sis1(ik) = sis1(ik) + sis(ik,ith)
               END DO
               e1(ik) = e1(ik)   * dth * face
               sin1(ik) = sin1(ik) * dth * facs
               snl1(ik) = snl1(ik) * dth * facs
               sds1(ik) = sds1(ik) * dth * facs
               sbt1(ik) = sbt1(ik) * dth * facs
               sis1(ik) = sis1(ik) * dth * facs
             END DO
             !
             stt1       = sin1 + snl1 + sds1 + sbt1 + sis1
             e1all(:,1) = sin1
             e1all(:,2) = snl1
             e1all(:,3) = sds1
             e1all(:,4) = sbt1
             e1all(:,5) = sis1
             e1all(:,6) = stt1
             !
           END IF ! 3.e
           !
           ! 4.a Perform output type 1 ( print plots / tables / file )
           !
           IF ( itype .EQ. 1 ) THEN
             !
             !  Format Time
             !
             IF ( otype .NE. 1 ) THEN
               CALL t2d(time,curdate,ierr)
               outjulday=tsub(refdate,curdate)
               iret=nf90_put_var(ncid,varid(1),outjulday,(/iout/))
               CALL check_err(iret,16)
             END IF
             !
             !  Performs subtype 1
             !
             IF ( otype .EQ. 1 ) THEN
               !
               IF ( scale1 .GE. 0. )                             &
                    CALL prt1ds (ndso, nk, e1, sig(1:nk), 'RAD/S',&
                    17, scale1, 'E(f)', 'm^2s', ptnme(j) )
               IF ( scale2 .GE. 0. )                             &
                    CALL prt2ds (ndso, nk, nk, nth, e, sig(1:nk), &
                    'RAD/S', 1., scale2, 0.0001, 'E(f,th)',  &
                    'm^2s', ptnme(j) )
               IF ( iaproc .EQ. napout ) WRITE (ndso,910) dpo(j), uabs
               IF ( (wao(j) .GT. 0.) .AND. (iaproc .EQ. napout) ) WRITE (ndso,911) udir
               IF ( iaproc .EQ. napout ) WRITE (ndso,912) aso(j), cao(j)
               IF ( (cao(j) .GT. 0.) .AND. (iaproc .EQ. napout) ) WRITE (ndso,913) cdir
               IF ( iaproc .EQ. napout ) WRITE (ndso,914) hsig, wlen, tmean, thmean, thsprd
               !
               !  Performs subtype 2
               !
             ELSE IF ( otype .EQ. 2 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               CALL check_err(iret,17)
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(7),dpo(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(8),ustar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(9),wao(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(10),udir,(/j1,iout/))
               IF ( fp .EQ. 0. ) fp = sig(nk)
               iret=nf90_put_var(ncid,varid(11),sig(1:nk)/fp,start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(12),e1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(13),thbnd(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(14),spbnd(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(15),apm(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               !
               !  Performs subtype 3
               !
             ELSE IF ( otype .EQ. 3 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               CALL check_err(iret,18)
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               IF (ncvartype.LE.3) THEN
                 iret=nf90_put_var(ncid,varid(11),nint(dpo(j)/0.5),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(12),nint(wao(j)/0.1),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(13),nint(udir/0.1),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(14),nint(cao(j)/0.1),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(15),nint(cdir/0.1),(/j1,iout/))
               ELSE
                 iret=nf90_put_var(ncid,varid(11),dpo(j),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(12),wao(j),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(13),udir,(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(14),cao(j),(/j1,iout/))
                 iret=nf90_put_var(ncid,varid(15),cdir,(/j1,iout/))
               END IF
               IF (ncvartype.LE.3) THEN
                 WHERE(e.GE.0) e=nint(alog10(e+1e-12)/0.0004)
               END IF
               iret=nf90_put_var(ncid,varid(10),transpose(e(1:nk,1:nth)), &
                    start=(/1,1,j1,iout/),count=(/nth,nk,1,1/))
               !
               !  Performs subtype 4
               !
             ELSE IF ( otype .EQ. 4 ) THEN
               !
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               CALL check_err(iret,19)
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),npart,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(7),depth,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(8),wao(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(9),udir,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(10),cao(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(11),cdir,(/j1,iout/))
               ! XPART infos - see w3partmd.ftn - SUBROUTINE PTMEAN
               iret=nf90_put_var(ncid,varid(12),xpart(1,0:npart),  &
                    start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(13),xpart(2,0:npart),  &
                    start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(14),xpart(3,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(15),xpart(4,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(16),xpart(5,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(17),xpart(6,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(18),xpart(12,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(19),xpart(13,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               iret=nf90_put_var(ncid,varid(20),xpart(14,0:npart),start=(/1,j1,iout/),count=(/npart,1,1/))
               !
             END IF
             !
             ! 4.b Perform output type 2 ( tables )
             !
           ELSE IF ( itype .EQ. 2 ) THEN
             !  Format Time
             CALL t2d(time,curdate,ierr)
             outjulday=tsub(refdate,curdate)
             iret=nf90_put_var(ncid,varid(1),outjulday,(/iout/))
             !
             !  Performs subtype 1
             !
             IF ( otype .EQ. 1 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),dpo(j),(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(7),cao(j),(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(8),cdir,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(9),wao(j),(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(10),udir,(/ j1,iout /))
 #ifdef W3_SETUP
               iret=nf90_put_var(ncid,varid(11),zet_seto,(/ j1,iout /))
 #endif
               !
               !  Performs subtype 2
               !
             ELSE IF ( otype .EQ. 2 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),hsig,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(7),wlen,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(8),tmean,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(9),thp,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(10),spp,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(11),fp*tpiinv,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(12),thmean,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(13),thsprd,(/ j1,iout /))
               !
               !  Performs subtype 3
               !
             ELSE IF ( otype .EQ. 3 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),1.e-4*xstar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),1.e-4*ystar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),unorm,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(7),estar,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(8),fpstar,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(9),cd*1000.,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(10),apm(nk)*100.,(/ j1,iout /))
               !
               !  Performs subtype 4
               !
             ELSE IF ( otype .EQ. 4 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),xstar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),ystar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),unorm,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(7),estar,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(8),fpstar,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(9),cd*1000.,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(10),apm(nk)*100.,(/ j1,iout /))
               !
               !  Performs subtype 5
               !
             ELSE IF ( otype .EQ. 5 ) THEN
               hmat   = min( 100. , 3.33*grav*hsig/uabs**2 )
               IF ( hsig .GE. hsmin ) THEN
                 CALL wavnu1 ( fp, dpo(j), wna, xyz )
                 age1   = min( 100. , fp / wna / uabs )
                 afr    = tpi / tmean
                 CALL wavnu1 ( afr, dpo(j), wna, xyz )
                 age2   = min( 100. , afr / wna / uabs )
               ELSE
                 age1   = nf90_fill_float
                 age2   = nf90_fill_float
               END IF
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),wao(j),(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(7),udir,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(8),hsig,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(9),hmat,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(10),age1,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(11),age2,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(12),aso(j),(/ j1,iout /))
               !
               !  Performs subtype 6
               !
             ELSE IF ( otype .EQ. 6 ) THEN
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(6),wao(j),(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(7),udir,(/ j1,iout /))
               iret=nf90_put_var(ncid,varid(8),hsig,(/ j1,iout /))
               IF ( hsig .GE. hsmin ) THEN
                 iret=nf90_put_var(ncid,varid(9),tpi/fp,(/ j1,iout /))
               ELSE
                 iret=nf90_put_var(ncid,varid(9),0.0,(/ j1,iout /))
               END IF
             END IF ! OTYPE
             !
             ! 4.c Perform output type 3 ( source terms )
             !
           ELSE IF ( itype .EQ. 3 ) THEN
             !
             !  Format Time
             !
             IF ( otype .NE. 1 ) THEN
               CALL t2d(time,curdate,ierr)
               outjulday=tsub(refdate,curdate)
               iret=nf90_put_var(ncid,varid(1),outjulday,(/iout/))
             END IF
             !
             !  Performs subtype 1
             !
             IF ( otype .EQ. 1 ) THEN
               !
               IF ( scale1 .GE. 0. ) THEN
                 IF ( flsrce(1) )                              &
                      CALL prt1ds (ndso, nk, e1, sig(1:nk),     &
                      'RAD/S', 17,  0., 'E(f)', 'm^2s',    &
                      ptnme(j) )
                 IF (flsrce(2) .OR. flsrce(3) .OR.             &
                      flsrce(4) .OR. flsrce(5) .OR.             &
                      flsrce(6) .OR. flsrce(7) )                &
                      CALL prt1dm (ndso, nk, 6, e1all, sig(1:nk),&
                      'RAD/S', 17, scale1, var1, 'M2',     &
                      ptnme(j) )
               END IF
               IF ( scale2 .GE. 0. ) THEN
                 IF ( flsrce(1) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, e,        &
                      sig(1:nk), 'RAD/S', 1., 0., 0.0001,  &
                      'E(f,th)', 'm^2s', ptnme(j) )
                 IF ( flsrce(2) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, swn,      &
                      sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                      'Sin(f,th)', 'm^2', ptnme(j) )
                 IF ( flsrce(3) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, snl,      &
                      sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                      'Snl(f,th)', 'm^2', ptnme(j) )
                 IF ( flsrce(4) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, sds,      &
                      sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                      'Sds(f,th)', 'm^2', ptnme(j) )
                 IF ( flsrce(5) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, sbt,      &
                      sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                      'Sbt(f,th)', 'm^2', ptnme(j) )
                 IF ( flsrce(6) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, sis,      &
                      sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                      'Sice(f,th)', 'm^2', ptnme(j) )
                 IF ( flsrce(7) )                              &
                      CALL prt2ds (ndso, nk, nk, nth, stt,      &
                      sig(1:nk), 'RAD/S', 1., scale2, 0.0001,&
                      'Stot(f,th)', 'm^2', ptnme(j) )
               END IF
               !
               !  Performs subtype 2
               !
             ELSE IF ( otype .EQ. 2 ) THEN
               !
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(7),dpo(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(8),ustar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(9),wao(j),(/j1,iout/))
               IF ( iscale.GE.3 ) facf = 1. / fp
               iret=nf90_put_var(ncid,varid(6),facf*sig(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(10),e1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(11),sin1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(12),snl1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(13),sds1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(14),sbt1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(15),sis1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               iret=nf90_put_var(ncid,varid(16),stt1(1:nk),start=(/1,j1,iout /),count=(/nk,1,1/))
               !
               !  Performs subtype 3
               !
             ELSE IF ( otype .EQ. 3 ) THEN
               !
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(7),dpo(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(8),ustar,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(9),wao(j),(/j1,iout/))
               IF ( iscale.GE.3 ) facf = 1. / fp
               DO ik=1, nk
                 fact   = 1. / max( 1.e-10 , e1(ik) )
                 iret=nf90_put_var(ncid,varid(6),facf*sig(ik),(/ ik,j1,iout /))
                 iret=nf90_put_var(ncid,varid(10),e1(ik),(/ ik,j1,iout /))
                 IF ( e1(ik) .GT. 1.e-10 ) THEN
                   iret=nf90_put_var(ncid,varid(11),fact*sin1(ik),(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(12),fact*snl1(ik),(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(13),fact*sds1(ik),(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(14),fact*sbt1(ik),(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(15),fact*sis1(ik),(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(16),fact*stt1(ik),(/ ik,j1,iout /))
                 ELSE
                   iret=nf90_put_var(ncid,varid(11),nf90_fill_float,(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(12),nf90_fill_float,(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(13),nf90_fill_float,(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(14),nf90_fill_float,(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(15),nf90_fill_float,(/ ik,j1,iout /))
                   iret=nf90_put_var(ncid,varid(16),nf90_fill_float,(/ ik,j1,iout /))
                 END IF
               END DO
               !
               !  Performs subtype 4
               !
             ELSE IF ( otype .EQ. 4 ) THEN
               !
               iret=nf90_put_var(ncid,varid(27),j,(/j1/))
               iret=nf90_put_var(ncid,varid(2),ptnme(j),start=(/1,j1/),count=(/len_trim(ptnme(j)) ,1/))
               IF (flww3.NE.0) iret=nf90_put_var(ncid,varid(3),flww3,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(4),m2km*ptloc(1,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(5),m2km*ptloc(2,j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(10),dpo(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(11),wao(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(12),udir,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(13),cao(j),(/j1,iout/))
               iret=nf90_put_var(ncid,varid(14),cdir,(/j1,iout/))
               iret=nf90_put_var(ncid,varid(15),ustar,(/j1,iout/))
               IF ( flsrce(1) )  iret=nf90_put_var(ncid,varid(16),   &
                    transpose(e(1:nk,1:nth)), start=(/1,1,j1,iout/),   &
                    count=(/nth,nk,1,1/)                               )
               IF ( flsrce(2) )  iret=nf90_put_var(ncid,varid(17),   &
                    transpose(swn(1:nk,1:nth)), start=(/1,1,j1,iout/), &
                    count=(/nth,nk,1,1/)                               )
               IF ( flsrce(3) )  iret=nf90_put_var(ncid,varid(18),   &
                    transpose(snl(1:nk,1:nth)), start=(/1,1,j1,iout/), &
                    count=(/nth,nk,1,1/)                               )
               IF ( flsrce(4) )  iret=nf90_put_var(ncid,varid(19),   &
                    transpose(sds(1:nk,1:nth)), start=(/1,1,j1,iout/), &
                    count=(/nth,nk,1,1/)                               )
               IF ( flsrce(5) )  iret=nf90_put_var(ncid,varid(20),   &
                    transpose(sbt(1:nk,1:nth)), start=(/1,1,j1,iout/), &
                    count=(/nth,nk,1,1/)                               )
               IF ( flsrce(6) )  iret=nf90_put_var(ncid,varid(21),   &
                    transpose(sis(1:nk,1:nth)), start=(/1,1,j1,iout/), &
                    count=(/nth,nk,1,1/)                               )
               IF ( flsrce(7) )  iret=nf90_put_var(ncid,varid(22),   &
                    transpose(stt(1:nk,1:nth)), start=(/1,1,j1,iout/), &
                    count=(/nth,nk,1,1/)                               )
               !
             END IF
             !
           END IF ! ITYPE
           !
           ! ... End of fields loop
           !
           IF (together) j1=j1+1
         END IF ! FLREQ(J)
         !
         ! Selects next station index or end up if not together
         !
         IF (together) THEN
           j=j+1
           IF (j.GT.nopts) laststation=.true.
         ELSE
           laststation=.true.
         END IF
       END DO ! DO WHILE (.NOT. LASTSTATION)
     END IF  ! NOT SHORT ...
     !
     RETURN
     !
     ! Formats
     !
 910 FORMAT (/15x,' Water depth       :',f7.1,'  (m)'/               &
          15x,' Wind speed        :',f8.2,' (m/s)')
 911 FORMAT ( 15x,' Wind direction    :',f7.1,'  (degr)')
 912 FORMAT ( 15x,' Air-sea temp. dif.:',f7.1,'  (degr)'/            &
          15x,' sea water speed     :',f8.2,' (m/s)')
 913 FORMAT ( 15x,' direction of current (from) :',f7.1,'  (degr)')
 914 FORMAT ( 15x,' Wave height       :',f8.2,' (m)'/                &
          15x,' Mean wave length  :',f6.0,'   (m)'/              &
          15x,' Mean wave period  :',f7.1,'  (s)'/               &
          15x,' Mean wave direct. :',f7.1,'  (degr)'/            &
          15x,' Direct. spread    :',f7.1,'  (degr)'/)
     !
 #ifdef W3_T
 9000 FORMAT (' TEST W3EXNC : FLAGS :',40l2)
 9001 FORMAT (' TEST W3EXNC : ITPYE  :',i4/                        &
          '               OTPYE  :',i4/                        &
          '               NREQ   :',i4/                        &
          '               SCALE1 :',e10.3/                     &
          '               SCALE2 :',e10.3/                     &
          '               FLSRCE :',6l2)
 9002 FORMAT (' TEST W3EXNC : OUTPUT POINT : ',a)
 9010 FORMAT (' TEST W3EXNC : DEPTH =',f7.1,'  IK, T, K, CG :')
 9011 FORMAT ('               ',i3,f8.2,f8.4,f8.2)
 #endif
     !/
     !/ End of W3EXNC ----------------------------------------------------- /
     !/
References check_err(), constants::dair, constants::dera, w3dispmd::dfac, w3dispmd::dsie, constants::dwat, w3dispmd::ecg1, w3dispmd::ewn1, constants::grav, w3gdatmd::iicedisp, w3gdatmd::iqtpe, w3dispmd::liu_forward_dispersion(), w3dispmd::n1max, w3dispmd::nar1d, w3arrymd::prt1dm(), w3arrymd::prt1ds(), w3arrymd::prt2ds(), constants::rade, constants::radius, w3gdatmd::swl6s6, constants::tpi, constants::tpiinv, w3canomd::w3add2ndorder(), w3gig1md::w3addig(), w3flx1md::w3flx1(), w3flx2md::w3flx2(), w3flx3md::w3flx3(), w3flx4md::w3flx4(), w3flx5md::w3flx5(), w3partmd::w3part(), w3sbs1md::w3sbs1(), w3sbt1md::w3sbt1(), w3sbt4md::w3sbt4(), w3sdb1md::w3sdb1(), w3src1md::w3sds1(), w3src2md::w3sds2(), w3src3md::w3sds3(), w3src4md::w3sds4(), w3src6md::w3sds6(), w3src1md::w3sin1(), w3src2md::w3sin2(), w3src3md::w3sin3(), w3src4md::w3sin4(), w3src6md::w3sin6(), w3sis2md::w3sis2(), w3sln1md::w3sln1(), w3snl1md::w3snl1(), w3snl2md::w3snl2(), w3snl3md::w3snl3(), w3snl4md::w3snl4(), w3snl1md::w3snlgqm(), w3src1md::w3spr1(), w3src2md::w3spr2(), w3src3md::w3spr3(), w3src4md::w3spr4(), w3src6md::w3spr6(), w3swldmd::w3swl6(), and w3dispmd::wavnu1().
w3ounp()
program w3ounp
Post-processing of point output.
Data is read from the grid output file out_pnt.ww3 (raw data) and from the file ww3_ounp.nml or ww3_ounp.inp (NDSI). Model definition and raw data files are read using WAVEWATCH III subroutines.
Author
F. Ardhuin
M. Accensi
Date
06-Sep-2021
Definition at line 22 of file ww3_ounp.F90.
References w3odatmd::aso, w3timemd::caltype, check_err(), w3odatmd::dimp, w3odatmd::dpo, w3timemd::dsec21(), w3servmd::extcde(), file(), w3gdatmd::flagll, w3odatmd::fnmpre, w3gdatmd::gname, w3odatmd::grdid, w3odatmd::iaproc, include(), w3odatmd::ipass2, w3servmd::itrace(), w3odatmd::naperr, w3odatmd::napout, w3odatmd::naproc, w3odatmd::ndse, w3odatmd::ndso, w3odatmd::ndst, w3servmd::nextln(), w3gdatmd::nk, w3odatmd::nopts, w3gdatmd::nth, w3odatmd::ptloc, w3odatmd::ptnme, w3timemd::stme21(), w3servmd::strace(), w3servmd::strsplit(), w3timemd::t2d(), w3timemd::tick21(), w3wdatmd::time, w3timemd::tsub(), w3timemd::u2d(), constants::undef, w3crnc(), w3exnc(), w3iogrmd::w3iogr(), w3iopomd::w3iopo(), w3iopomd::w3iopon(), w3adatmd::w3naux(), w3wdatmd::w3ndat(), w3nmlounpmd::w3nmlounp(), w3gdatmd::w3nmod(), w3odatmd::w3nout(), w3adatmd::w3seta(), w3gdatmd::w3setg(), w3odatmd::w3seto(), w3wdatmd::w3setw(), w3odatmd::wao, w3odatmd::wdo, and w3odatmd::zet_seto.